{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData"]]},"kind":"symbol","abstract":[{"type":"text","text":"If set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":" the image is reloaded\/downloaded after each frame. Otherwise the image is loaded only once and reused per frame."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refreshOnEachFrame","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","title":"refreshOnEachFrame","roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKSimulatedCameraMockData(py)refreshOnEachFrame","navigatorTitle":[{"kind":"identifier","text":"refreshOnEachFrame"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshOnEachFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData\/refreshOnEachFrame","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata\/refreshoneachframe"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata\/refreshoneachframe"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSimulatedCameraMockData":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"role":"symbol","title":"SBSDKSimulatedCameraMockData","navigatorTitle":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"type":"topic","abstract":[{"type":"text","text":"A class to describe the mocking data that is fed to a simulated camera device."}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSimulatedCameraMockData/refreshOnEachFrame":{"abstract":[{"type":"text","text":"If set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":" the image is reloaded\/downloaded after each frame. Otherwise the image is loaded only once and reused per frame."}],"navigatorTitle":[{"text":"refreshOnEachFrame","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata\/refreshoneachframe","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refreshOnEachFrame","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","title":"refreshOnEachFrame","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData\/refreshOnEachFrame","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"refreshOnEachFrame","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"refreshOnEachFrame","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"refreshOnEachFrame","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKSimulatedCameraMockData","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData\/title"},{"op":"replace","value":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData\/fragments"},{"op":"replace","value":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData\/navigatorTitle"},{"op":"replace","value":"refreshOnEachFrame","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData~1refreshOnEachFrame\/title"},{"op":"replace","value":[{"text":"refreshOnEachFrame","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData~1refreshOnEachFrame\/fragments"}]}]}