{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkanalyticseventfactory\/proceedwithimage"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkanalyticseventfactory\/proceedwithimage"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEventFactory\/proceedWithImage","interfaceLanguage":"swift"},"abstract":[{"text":"A predefined analytics event.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"proceedWithImage","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAnalyticsEvent","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEvent","text":"SBSDKAnalyticsEvent"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEventFactory"]]},"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"proceedWithImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKAnalyticsEvent","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAnalyticsEvent"}],"symbolKind":"property","roleHeading":"Type Property","title":"proceedWithImage","navigatorTitle":[{"kind":"identifier","text":"proceedWithImage"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAnalyticsEventFactory(cpy)proceedWithImage"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAnalyticsEventFactory":{"navigatorTitle":[{"text":"SBSDKAnalyticsEventFactory","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAnalyticsEventFactory"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEventFactory","type":"topic","abstract":[{"text":"A predefined analytics event.","type":"text"}],"title":"SBSDKAnalyticsEventFactory","url":"\/documentation\/scanbotsdk\/sbsdkanalyticseventfactory","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAnalyticsEvent":{"title":"SBSDKAnalyticsEvent","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkanalyticsevent","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEvent","type":"topic","abstract":[{"text":"The event that is being tracked.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKAnalyticsEvent"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAnalyticsEvent"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAnalyticsEventFactory/proceedWithImage":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"proceedWithImage"},{"text":": ","kind":"text"},{"text":"SBSDKAnalyticsEvent","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAnalyticsEvent","kind":"typeIdentifier"}],"kind":"symbol","title":"proceedWithImage","url":"\/documentation\/scanbotsdk\/sbsdkanalyticseventfactory\/proceedwithimage","abstract":[{"type":"text","text":"A predefined analytics event."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEventFactory\/proceedWithImage","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"proceedWithImage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"op":"replace","value":"proceedWithImage","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"proceedWithImage"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsEvent","text":"SBSDKAnalyticsEvent","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAnalyticsEvent"},{"kind":"text","text":" * "},{"text":"proceedWithImage","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEventFactory\/title","value":"SBSDKAnalyticsEventFactory","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAnalyticsEventFactory"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEventFactory\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEventFactory\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKAnalyticsEventFactory"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEvent\/title","value":"SBSDKAnalyticsEvent","op":"replace"},{"value":[{"text":"SBSDKAnalyticsEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEvent\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEvent\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKAnalyticsEvent"}]},{"value":"proceedWithImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEventFactory~1proceedWithImage\/title"},{"value":[{"text":"proceedWithImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsEventFactory~1proceedWithImage\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}