{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageEditingViewControllerDidFail","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"editingViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"editingViewController","content":[{"inlineContent":[{"text":"The calling ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The occurred error."}]}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"imageEditingViewControllerDidFail(_:with:)","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerDidFail:with:"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKImageEditingViewControllerDelegate(im)imageEditingViewControllerDidFail:with:","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerDidFail"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","kind":"typeIdentifier","text":"SBSDKImageEditingViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}],"required":true},"abstract":[{"text":"Informs the delegate that the image editing view controller failed with an error.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerDidFail(_:with:)"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerdidfail(_:with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerdidfail(_:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerDidFail(_:with:)":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"imageEditingViewControllerDidFail:with:","kind":"identifier"}],"abstract":[{"text":"Informs the delegate that the image editing view controller failed with an error.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerdidfail(_:with:)","required":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerDidFail(_:with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageEditingViewControllerDidFail","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"imageEditingViewControllerDidFail(_:with:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate","abstract":[{"type":"text","text":"A delegate protocol to inform an object about changes in "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"title":"SBSDKImageEditingViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewController":{"abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show and edit an image."}],"title":"SBSDKImageEditingViewController","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller","navigatorTitle":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"imageEditingViewControllerDidFail:with:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"imageEditingViewControllerDidFail:with:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"imageEditingViewControllerDidFail:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"editingViewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"with:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"editingViewController","content":[{"type":"paragraph","inlineContent":[{"text":"The calling ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"The occurred error.","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"imageEditingViewControllerDidFail:with:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerDidFail(_:with:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"imageEditingViewControllerDidFail:with:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerDidFail(_:with:)\/fragments","op":"replace"},{"value":"SBSDKImageEditingViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate\/fragments","op":"replace"},{"value":[{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate\/navigatorTitle"},{"value":"SBSDKImageEditingViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/title"},{"value":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}