{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldType"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"defaultFieldTypeVisibilities","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDisplayState","kind":"typeIdentifier","text":"SBSDKGenericDocumentFieldDisplayState","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDisplayState"},{"kind":"text","text":"]?"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"defaultFieldTypeVisibilities","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"SBSDKGenericDocumentFieldDisplayState","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDisplayState"},{"text":"]?","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"title":"defaultFieldTypeVisibilities","roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"defaultFieldTypeVisibilities"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldType(cpy)defaultFieldTypeVisibilities"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldType\/defaultFieldTypeVisibilities","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldtype\/defaultfieldtypevisibilities"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldtype\/defaultfieldtypevisibilities"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"A dictionary of the default visibility states for generic document field types."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldDisplayState":{"abstract":[{"text":"The generic document fields display status. Whether a field is shown or hidden in the user interface.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddisplaystate","title":"SBSDKGenericDocumentFieldDisplayState","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDisplayState","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentFieldDisplayState","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentFieldDisplayState","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldType":{"navigatorTitle":[{"text":"SBSDKGenericDocumentFieldType","kind":"identifier"}],"title":"SBSDKGenericDocumentFieldType","abstract":[{"type":"text","text":"A generic document field type."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldtype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldType","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentFieldType","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldType/defaultFieldTypeVisibilities":{"role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultFieldTypeVisibilities","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentFieldDisplayState","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDisplayState"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"defaultFieldTypeVisibilities","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldType\/defaultFieldTypeVisibilities","kind":"symbol","title":"defaultFieldTypeVisibilities","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldtype\/defaultfieldtypevisibilities","abstract":[{"type":"text","text":"A dictionary of the default visibility states for generic document field types."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"defaultFieldTypeVisibilities","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"defaultFieldTypeVisibilities","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSDictionary<NSString *,SBSDKGenericDocumentFieldDisplayState *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"defaultFieldTypeVisibilities"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"SBSDKGenericDocumentFieldDisplayState","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDisplayState\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDisplayState\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentFieldDisplayState"}]},{"value":[{"text":"SBSDKGenericDocumentFieldDisplayState","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDisplayState\/navigatorTitle","op":"replace"},{"op":"replace","value":"SBSDKGenericDocumentFieldType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldType\/title"},{"value":[{"text":"SBSDKGenericDocumentFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldType\/navigatorTitle","op":"replace","value":[{"text":"SBSDKGenericDocumentFieldType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldType~1defaultFieldTypeVisibilities\/title","value":"defaultFieldTypeVisibilities","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldType~1defaultFieldTypeVisibilities\/fragments","op":"replace","value":[{"text":"defaultFieldTypeVisibilities","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}