{"kind":"symbol","sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:fullName:normalizedName:commonType:"}],"navigatorTitle":[{"text":"initWithName:fullName:normalizedName:commonType:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"initWithName:fullName:normalizedName:commonType:","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldType(im)initWithName:fullName:normalizedName:commonType:"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldType\/initWithName:fullName:normalizedName:commonType:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithName:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullName:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fullName","kind":"internalParam"},{"kind":"text","text":" "},{"text":"normalizedName:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"normalizedName"},{"text":" ","kind":"text"},{"text":"commonType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentCommonFieldType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKGenericDocumentCommonFieldType"},{"text":") ","kind":"text"},{"text":"commonType","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldtype\/initwithname:fullname:normalizedname:commontype:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldType":{"navigatorTitle":[{"text":"SBSDKGenericDocumentFieldType","kind":"identifier"}],"title":"SBSDKGenericDocumentFieldType","abstract":[{"type":"text","text":"A generic document field type."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldtype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldType","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentFieldType","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType":{"type":"topic","abstract":[{"type":"text","text":"Common field types."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldType"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"title":"SBSDKGenericDocumentCommonFieldType","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldType/initWithName:fullName:normalizedName:commonType:":{"navigatorTitle":[{"kind":"identifier","text":"initWithName:fullName:normalizedName:commonType:"}],"kind":"symbol","abstract":[],"title":"initWithName:fullName:normalizedName:commonType:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldType\/initWithName:fullName:normalizedName:commonType:","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldtype\/initwithname:fullname:normalizedname:commontype:","role":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithName:fullName:normalizedName:commonType:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKGenericDocumentFieldType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldType\/title"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentFieldType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldType\/fragments","op":"replace"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldType\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType\/title","value":"SBSDKGenericDocumentCommonFieldType","op":"replace"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"op":"replace"}]}]}