{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/supportedinterfaceorientations"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/supportedInterfaceOrientations","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"UIInterfaceOrientationMask","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedInterfaceOrientations"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","fragments":[{"text":"supportedInterfaceOrientations","kind":"identifier"}],"title":"supportedInterfaceOrientations","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"property","navigatorTitle":[{"text":"supportedInterfaceOrientations","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController(py)supportedInterfaceOrientations","role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/supportedInterfaceOrientations":{"kind":"symbol","abstract":[],"title":"supportedInterfaceOrientations","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/supportedInterfaceOrientations","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/supportedinterfaceorientations","role":"symbol","fragments":[{"text":"supportedInterfaceOrientations","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller","deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"role":"symbol","title":"SBSDKUIBarcodesBatchScannerViewController","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to detect barcodes batches."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 6.2.0"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController\/title","value":"SBSDKUIBarcodesBatchScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController\/fragments","value":[{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}