{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroCustomImage"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzintrocustomimage\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"fromJsonWithJson:","symbolKind":"method","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MrzIntroCustomImage(cm)fromJsonWithJson:","roleHeading":"Type Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroCustomImage\/fromJsonWithJson:"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2MrzIntroCustomImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroCustomImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MrzIntroCustomImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MrzIntroCustomImage/fromJsonWithJson:":{"title":"fromJsonWithJson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroCustomImage\/fromJsonWithJson:","kind":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzintrocustomimage\/fromjsonwithjson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MrzIntroCustomImage":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MrzIntroCustomImage","title":"SBSDKUI2MrzIntroCustomImage","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MrzIntroCustomImage"}],"role":"symbol","abstract":[{"text":"A custom image for the introduction screen.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzintrocustomimage","navigatorTitle":[{"text":"SBSDKUI2MrzIntroCustomImage","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzIntroCustomImage\/title","value":"SBSDKUI2MrzIntroCustomImage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzIntroCustomImage\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MrzIntroCustomImage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MrzIntroCustomImage\/navigatorTitle","value":[{"text":"SBSDKUI2MrzIntroCustomImage","kind":"identifier"}]}]}]}