{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroScreenConfiguration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroscreenconfiguration\/initwithimage:backgroundcolor:dividercolor:handlercolor:showautomatically:title:explanation:donebutton:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorIntroScreenConfiguration(im)initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","role":"symbol","title":"initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorIntroImage","text":"SBSDKUI2DocumentDataExtractorIntroImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor:"},{"kind":"text","text":"("},{"text":"SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"backgroundColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dividerColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"dividerColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"handlerColor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"handlerColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"showAutomatically:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"showAutomatically","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"title:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"text":"title","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"explanation:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"text":"explanation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"doneButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"doneButton","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroScreenConfiguration\/initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2color","type":"topic","role":"symbol","kind":"symbol","title":"SBSDKUI2Color","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"title":"SBSDKUI2StyledText","abstract":[{"text":"Configuration of the text field appearance.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroScreenConfiguration":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroscreenconfiguration","abstract":[{"type":"text","text":"Configuration of the introduction screen for the document data extractor."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroScreenConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorIntroScreenConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorIntroScreenConfiguration"}],"title":"SBSDKUI2DocumentDataExtractorIntroScreenConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroScreenConfiguration/initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:":{"navigatorTitle":[{"text":"initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","kind":"identifier"}],"kind":"symbol","title":"initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroScreenConfiguration\/initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroscreenconfiguration\/initwithimage:backgroundcolor:dividercolor:handlercolor:showautomatically:title:explanation:donebutton:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ButtonConfiguration":{"abstract":[{"type":"text","text":"Configuration of the button."}],"title":"SBSDKUI2ButtonConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2buttonconfiguration","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroImage":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorIntroImage"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorIntroImage"}],"title":"SBSDKUI2DocumentDataExtractorIntroImage","abstract":[{"type":"text","text":"The image for the introduction screen of a document data extractor screen."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2Color","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle"},{"value":"SBSDKUI2StyledText","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments"},{"value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/navigatorTitle"},{"value":"SBSDKUI2DocumentDataExtractorIntroScreenConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroScreenConfiguration\/title"},{"value":[{"text":"SBSDKUI2DocumentDataExtractorIntroScreenConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroScreenConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2DocumentDataExtractorIntroScreenConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroScreenConfiguration\/navigatorTitle"},{"value":"SBSDKUI2ButtonConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/title"},{"value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage\/title","value":"SBSDKUI2DocumentDataExtractorIntroImage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage\/fragments","value":[{"text":"SBSDKUI2DocumentDataExtractorIntroImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentDataExtractorIntroImage","kind":"identifier"}]}]}]}