{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Performs well even if there are shadows."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preset3","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarizationfilterpreset\/preset3"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarizationfilterpreset\/preset3"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preset3"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKBinarizationFilterPreset@SBSDKBinarizationFilterPresetPreset3","navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset3"}],"role":"symbol","title":"SBSDKBinarizationFilterPreset.preset3","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset\/preset3"},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBinarizationFilterPreset/preset3":{"role":"symbol","navigatorTitle":[{"text":"SBSDKBinarizationFilterPresetPreset3","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset\/preset3","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preset3","kind":"identifier"}],"title":"SBSDKBinarizationFilterPreset.preset3","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarizationfilterpreset\/preset3","kind":"symbol","abstract":[{"type":"text","text":"Performs well even if there are shadows."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBinarizationFilterPreset":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset","navigatorTitle":[{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}],"title":"SBSDKBinarizationFilterPreset","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarizationfilterpreset","abstract":[{"type":"text","text":"Preset of parameters for custom binarization filter."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKBinarizationFilterPresetPreset3","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset3"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKBinarizationFilterPresetPreset3","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKBinarizationFilterPresetPreset3","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset~1preset3\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset3"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset~1preset3\/fragments","op":"replace"},{"value":"SBSDKBinarizationFilterPreset","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBinarizationFilterPreset"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBinarizationFilterPreset"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset\/navigatorTitle","op":"replace"}]}]}