{"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewControllerDelegate\/vinScannerViewController(_:didFinishWith:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewControllerDelegate"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"vinScannerViewController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerViewController","text":"SBSDKUIVINScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"kind":"text","text":": "},{"text":"SBSDKVehicleIdentificationNumberScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","title":"vinScannerViewController(_:didFinishWith:)","roleHeading":"Instance Method","navigatorTitle":[{"text":"vinScannerViewController:didFinishWithResult:","kind":"identifier"}],"required":true,"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUIVINScannerViewControllerDelegate(im)vinScannerViewController:didFinishWithResult:","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscannerviewcontrollerdelegate\/vinscannerviewcontroller(_:didfinishwith:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscannerviewcontrollerdelegate\/vinscannerviewcontroller(_:didfinishwith:)"]}],"abstract":[{"type":"text","text":"Informs the delegate that the vehicle identification number has been scanned and validated."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(vinScannerViewController:didFinishWithResult:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vinScannerViewController"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerViewController","kind":"typeIdentifier","text":"SBSDKUIVINScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"text":" ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKVehicleIdentificationNumberScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The vehicle identification number scanner view controller instance."}]}],"name":"controller"},{"content":[{"inlineContent":[{"type":"text","text":"An object, that contains scanned vehicle identification number."}],"type":"paragraph"}],"name":"result"}],"kind":"parameters"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerViewControllerDelegate/vinScannerViewController(_:didFinishWith:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vinScannerViewController"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerViewController","text":"SBSDKUIVINScannerViewController"},{"kind":"text","text":", "},{"text":"didFinishWith","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKVehicleIdentificationNumberScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerResult"},{"text":")","kind":"text"}],"abstract":[{"text":"Informs the delegate that the vehicle identification number has been scanned and validated.","type":"text"}],"kind":"symbol","title":"vinScannerViewController(_:didFinishWith:)","required":true,"navigatorTitle":[{"text":"vinScannerViewController:didFinishWithResult:","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerviewcontrollerdelegate\/vinscannerviewcontroller(_:didfinishwith:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewControllerDelegate\/vinScannerViewController(_:didFinishWith:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerViewController":{"kind":"symbol","abstract":[{"text":"A highly customizable camera-based view controller to recognize and validate vehicle identification numbers in realtime.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIVINScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerviewcontroller","navigatorTitle":[{"text":"SBSDKUIVINScannerViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewController","type":"topic","title":"SBSDKUIVINScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerViewControllerDelegate":{"abstract":[{"text":"Delegate protocol for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewController"},{"text":".","type":"text"}],"title":"SBSDKUIVINScannerViewControllerDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIVINScannerViewControllerDelegate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUIVINScannerViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerviewcontrollerdelegate","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerResult":{"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A class describing the result of the vehicle identification number scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerresult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVehicleIdentificationNumberScannerResult","kind":"identifier"}],"title":"SBSDKVehicleIdentificationNumberScannerResult","navigatorTitle":[{"text":"SBSDKVehicleIdentificationNumberScannerResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"vinScannerViewController:didFinishWithResult:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"vinScannerViewController:didFinishWithResult:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"vinScannerViewController:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerViewController","kind":"typeIdentifier","text":"SBSDKUIVINScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewController"},{"kind":"text","text":" *) "},{"text":"controller","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didFinishWithResult:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerResult","text":"SBSDKVehicleIdentificationNumberScannerResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"vinScannerViewController:didFinishWithResult:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewControllerDelegate~1vinScannerViewController(_:didFinishWith:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewControllerDelegate~1vinScannerViewController(_:didFinishWith:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"vinScannerViewController:didFinishWithResult:","kind":"identifier"}]},{"value":"SBSDKUIVINScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewController\/title","op":"replace"},{"value":[{"text":"SBSDKUIVINScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewController\/fragments"},{"op":"replace","value":"SBSDKUIVINScannerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewControllerDelegate\/title"},{"op":"replace","value":[{"text":"SBSDKUIVINScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewControllerDelegate\/fragments"},{"value":"SBSDKVehicleIdentificationNumberScannerResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerResult\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScannerResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}