{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapCheckMarkAnimation\/hash","interfaceLanguage":"occ"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapCheckMarkAnimation"]]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2pagesnapcheckmarkanimation\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}],"fragments":[{"text":"hash","kind":"identifier"}],"roleHeading":"Instance Property","title":"hash","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PageSnapCheckMarkAnimation(py)hash","modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PageSnapCheckMarkAnimation/hash":{"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapCheckMarkAnimation\/hash","fragments":[{"text":"hash","kind":"identifier"}],"title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkui2pagesnapcheckmarkanimation\/hash","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PageSnapCheckMarkAnimation":{"title":"SBSDKUI2PageSnapCheckMarkAnimation","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the check mark animation."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapCheckMarkAnimation","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2PageSnapCheckMarkAnimation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PageSnapCheckMarkAnimation"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2pagesnapcheckmarkanimation"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2PageSnapCheckMarkAnimation","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapCheckMarkAnimation\/title","op":"replace"},{"value":[{"text":"SBSDKUI2PageSnapCheckMarkAnimation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapCheckMarkAnimation\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapCheckMarkAnimation\/navigatorTitle","value":[{"text":"SBSDKUI2PageSnapCheckMarkAnimation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}