{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization"]]},"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"reviewDeletePageAlertTitle","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewDeletePageAlertTitle"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"reviewDeletePageAlertTitle","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization(py)reviewDeletePageAlertTitle"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization\/reviewdeletepagealerttitle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization\/reviewdeletepagealerttitle"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization\/reviewDeletePageAlertTitle","interfaceLanguage":"swift"},"abstract":[{"text":"The title of the delete page alert dialog for the review screen.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is “Delete page?”"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewDeletePageAlertTitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerTextLocalization/reviewDeletePageAlertTitle":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization\/reviewdeletepagealerttitle","navigatorTitle":[{"text":"reviewDeletePageAlertTitle","kind":"identifier"}],"abstract":[{"text":"The title of the delete page alert dialog for the review screen.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is “Delete page?”"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization\/reviewDeletePageAlertTitle","title":"reviewDeletePageAlertTitle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reviewDeletePageAlertTitle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","url":"\/documentation\/scanbotdocumentscannersdk","abstract":[{"type":"text","text":"Version: 6.2.0"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerTextLocalization":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"abstract":[{"type":"text","text":"Configuration of all the strings for the standalone cropping screen."}],"role":"symbol","kind":"symbol","type":"topic","title":"SBSDKUI2DocumentScannerTextLocalization","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"reviewDeletePageAlertTitle","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"reviewDeletePageAlertTitle","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"reviewDeletePageAlertTitle"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization~1reviewDeletePageAlertTitle\/title","value":"reviewDeletePageAlertTitle"},{"value":[{"kind":"identifier","text":"reviewDeletePageAlertTitle"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization~1reviewDeletePageAlertTitle\/fragments"},{"value":"SBSDKUI2DocumentScannerTextLocalization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}