{"abstract":[{"type":"text","text":"Foreground color of the top bar buttons on the details screen."}],"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}],"type":"paragraph"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"detailsActionColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/detailsactioncolor"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/detailsactioncolor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/detailsActionColor","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodesBatchScannerUIConfiguration(py)detailsActionColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detailsActionColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"roleHeading":"Instance Property","title":"detailsActionColor","platforms":[],"navigatorTitle":[{"kind":"identifier","text":"detailsActionColor"}],"symbolKind":"property"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration":{"type":"topic","title":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerUIConfiguration"}],"deprecated":true,"abstract":[{"text":"The configuration for user interface of the RTU-UI batch barcode scanner.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerUIConfiguration"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.1"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/detailsActionColor":{"abstract":[{"type":"text","text":"Foreground color of the top bar buttons on the details screen."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/detailsActionColor","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/detailsactioncolor","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detailsActionColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"detailsActionColor","kind":"symbol","navigatorTitle":[{"text":"detailsActionColor","kind":"identifier"}],"deprecated":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"detailsActionColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"detailsActionColor","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"detailsActionColor"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration\/title","value":"SBSDKUIBarcodesBatchScannerUIConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerUIConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"}]},{"value":"detailsActionColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1detailsActionColor\/title"},{"value":[{"text":"detailsActionColor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1detailsActionColor\/fragments","op":"replace"}]}]}