{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Background color of the details screen."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detailsBackgroundColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}]}]}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}],"type":"paragraph"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/detailsBackgroundColor","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","platforms":[],"navigatorTitle":[{"kind":"identifier","text":"detailsBackgroundColor"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodesBatchScannerUIConfiguration(py)detailsBackgroundColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"detailsBackgroundColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"detailsBackgroundColor","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/detailsbackgroundcolor"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/detailsbackgroundcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/detailsBackgroundColor":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/detailsbackgroundcolor","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/detailsBackgroundColor","type":"topic","deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"detailsBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"navigatorTitle":[{"text":"detailsBackgroundColor","kind":"identifier"}],"title":"detailsBackgroundColor","kind":"symbol","abstract":[{"text":"Background color of the details screen.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 6.1.0"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerUIConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration","abstract":[{"text":"The configuration for user interface of the RTU-UI batch barcode scanner.","type":"text"}],"deprecated":true,"title":"SBSDKUIBarcodesBatchScannerUIConfiguration","navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"detailsBackgroundColor","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"detailsBackgroundColor"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"detailsBackgroundColor"},{"text":";","kind":"text"}]}]}},{"value":"detailsBackgroundColor","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1detailsBackgroundColor\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1detailsBackgroundColor\/fragments","value":[{"text":"detailsBackgroundColor","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUIBarcodesBatchScannerUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerUIConfiguration"}]}]}]}