{"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithAbsolutePointA:pointB:pointC:pointD:forSize:","kind":"identifier"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"absolutePointA","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"text":"pointB","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pointC"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"pointD","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"text":")","kind":"text"}],"roleHeading":"Initializer","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon(im)initWithAbsolutePointA:pointB:pointC:pointD:forSize:","title":"init(absolutePointA:pointB:pointC:pointD:for:)","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(initWithAbsolutePointA:pointB:pointC:pointD:forSize:) "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"absolutePointA","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"a"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"text":", ","kind":"text"},{"text":"pointB","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"b","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pointC"},{"kind":"text","text":" "},{"text":"c","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"text":"pointD","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"d","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"size"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The first point of the polygon in absolute coordinates."}]}],"name":"a"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The second point of the polygon in absolute coordinates.","type":"text"}]}],"name":"b"},{"name":"c","content":[{"inlineContent":[{"text":"The third point of the polygon in absolute coordinates.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The fourth point of the polygon in absolute coordinates.","type":"text"}]}],"name":"d"},{"content":[{"inlineContent":[{"text":"The size to use to convert the points to unit coordinates.","type":"text"}],"type":"paragraph"}],"name":"size"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon\/init(absolutepointa:pointb:pointc:pointd:for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon\/init(absolutepointa:pointb:pointc:pointd:for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon\/init(absolutePointA:pointB:pointC:pointD:for:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon"]]},"abstract":[{"text":"One of the designated initializer methods.","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.1.1","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygon/init(absolutePointA:pointB:pointC:pointD:for:)":{"role":"symbol","navigatorTitle":[{"text":"initWithAbsolutePointA:pointB:pointC:pointD:forSize:","kind":"identifier"}],"abstract":[{"text":"One of the designated initializer methods.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon\/init(absolutepointa:pointb:pointc:pointd:for:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon\/init(absolutePointA:pointB:pointC:pointD:for:)","title":"init(absolutePointA:pointB:pointC:pointD:for:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"absolutePointA","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"pointB","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":", "},{"text":"pointC","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"text":", ","kind":"text"},{"text":"pointD","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygon":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon","kind":"symbol","abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}],"title":"SBSDKPolygon","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygon","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithAbsolutePointA:pointB:pointC:pointD:forSize:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAbsolutePointA:pointB:pointC:pointD:forSize:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithAbsolutePointA:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"a"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pointB:"},{"kind":"text","text":"("},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") "},{"kind":"internalParam","text":"b"},{"kind":"text","text":" "},{"text":"pointC:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":") ","kind":"text"},{"text":"c","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pointD:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"text":") ","kind":"text"},{"text":"d","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"forSize:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"size"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"a","content":[{"type":"paragraph","inlineContent":[{"text":"The first point of the polygon in absolute coordinates.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The second point of the polygon in absolute coordinates."}],"type":"paragraph"}],"name":"b"},{"name":"c","content":[{"type":"paragraph","inlineContent":[{"text":"The third point of the polygon in absolute coordinates.","type":"text"}]}]},{"name":"d","content":[{"type":"paragraph","inlineContent":[{"text":"The fourth point of the polygon in absolute coordinates.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The size to use to convert the points to unit coordinates."}],"type":"paragraph"}],"name":"size"}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon~1init(absolutePointA:pointB:pointC:pointD:for:)\/title","op":"replace","value":"initWithAbsolutePointA:pointB:pointC:pointD:forSize:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon~1init(absolutePointA:pointB:pointC:pointD:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAbsolutePointA:pointB:pointC:pointD:forSize:"}],"op":"replace"},{"value":"SBSDKPolygon","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/title","op":"replace"},{"value":[{"text":"SBSDKPolygon","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/fragments"},{"value":[{"text":"SBSDKPolygon","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}