{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon\/rotate180(oldSize:newSize:)"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon\/rotate180(oldsize:newsize:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon\/rotate180(oldsize:newsize:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(rotate180WithOldSize:newSize:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rotate180"},{"kind":"text","text":"("},{"text":"oldSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"text":"newSize","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The size of the absolute coordinate system before rotating it.","type":"text"}],"type":"paragraph"}],"name":"oldSize"},{"name":"newSize","content":[{"inlineContent":[{"text":"The size of the absolute coordinate system after rotating it.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rotate180","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"oldSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"text":"newSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":")","kind":"text"}],"title":"rotate180(oldSize:newSize:)","roleHeading":"Instance Method","symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon(im)rotate180WithOldSize:newSize:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"rotate180WithOldSize:newSize:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon"]]},"abstract":[{"type":"text","text":"Rotates the points of the receiver 180 degrees, transforming it from one absolute space to another."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygon":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon","kind":"symbol","abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}],"title":"SBSDKPolygon","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygon","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.1.1","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygon/rotate180(oldSize:newSize:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon\/rotate180(oldSize:newSize:)","title":"rotate180(oldSize:newSize:)","navigatorTitle":[{"text":"rotate180WithOldSize:newSize:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Rotates the points of the receiver 180 degrees, transforming it from one absolute space to another."}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon\/rotate180(oldsize:newsize:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rotate180","kind":"identifier"},{"text":"(","kind":"text"},{"text":"oldSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"text":"newSize","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":")","kind":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"rotate180WithOldSize:newSize:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rotate180WithOldSize:newSize:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"rotate180WithOldSize:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":") ","kind":"text"},{"text":"oldSize","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"newSize:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"newSize"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The size of the absolute coordinate system before rotating it.","type":"text"}]}],"name":"oldSize"},{"name":"newSize","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The size of the absolute coordinate system after rotating it."}]}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/title","op":"replace","value":"SBSDKPolygon"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/fragments","op":"replace","value":[{"text":"SBSDKPolygon","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKPolygon"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/navigatorTitle","op":"replace"},{"op":"replace","value":"rotate180WithOldSize:newSize:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon~1rotate180(oldSize:newSize:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon~1rotate180(oldSize:newSize:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"rotate180WithOldSize:newSize:","kind":"identifier"}]}]}]}