{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeImageGenerationType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeImageGenerationType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodeImageGenerationType","text":"SBSDKBarcodeImageGenerationType"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use, if you want to receive a full sized image with barcodes."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeImageGenerationType\/none"},{"type":"text","text":"."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This property has no effect if "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/isTrackingOverlayEnabled"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"With the tracking overlay enabled, barcode images cannot be generated."}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/barcodeimagegenerationtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/barcodeimagegenerationtype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/barcodeImageGenerationType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Specifies the way of barcode images generation or disables this generation at all."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeImageGenerationType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeImageGenerationType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodeImageGenerationType"}],"title":"barcodeImageGenerationType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController(py)barcodeImageGenerationType","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"barcodeImageGenerationType"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/barcodeImageGenerationType":{"role":"symbol","title":"barcodeImageGenerationType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeImageGenerationType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeImageGenerationType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodeImageGenerationType"}],"abstract":[{"type":"text","text":"Specifies the way of barcode images generation or disables this generation at all."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/barcodeImageGenerationType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"barcodeImageGenerationType"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/barcodeimagegenerationtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeImageGenerationType":{"role":"symbol","title":"SBSDKBarcodeImageGenerationType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeImageGenerationType"}],"abstract":[{"type":"text","text":"The type of the barcode image generation."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeImageGenerationType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeImageGenerationType"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeimagegenerationtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController":{"role":"symbol","title":"SBSDKBarcodeScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode detector."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeImageGenerationType/none":{"role":"symbol","title":"SBSDKBarcodeImageGenerationType.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"No barcode image generation."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeImageGenerationType\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeImageGenerationTypeNone"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeimagegenerationtype\/none"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/isTrackingOverlayEnabled":{"role":"symbol","title":"isTrackingOverlayEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTrackingOverlayEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Displays an augmented reality view that draws the frames, content and type text of the found barcodes when it finds them."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/isTrackingOverlayEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isTrackingOverlayEnabled"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/istrackingoverlayenabled"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"barcodeImageGenerationType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"barcodeImageGenerationType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeImageGenerationType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodeImageGenerationType","text":"SBSDKBarcodeImageGenerationType"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeImageGenerationType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1barcodeImageGenerationType\/title","value":"barcodeImageGenerationType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1barcodeImageGenerationType\/fragments","value":[{"kind":"identifier","text":"barcodeImageGenerationType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType\/title","value":"SBSDKBarcodeImageGenerationType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeImageGenerationType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/title","value":"SBSDKBarcodeScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType~1none\/title","value":"SBSDKBarcodeImageGenerationTypeNone"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType~1none\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeImageGenerationTypeNone"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1isTrackingOverlayEnabled\/title","value":"isTrackingOverlayEnabled"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1isTrackingOverlayEnabled\/fragments","value":[{"kind":"identifier","text":"isTrackingOverlayEnabled"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}