{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"roleHeading":"Initializer","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController(im)initWithParentViewController:parentView:delegate:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithParentViewController:parentView:delegate:"}],"role":"symbol","title":"init(parentViewController:parentView:delegate:)","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"parentViewController"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"parentView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKBarcodeScannerViewControllerDelegate","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithParentViewController:parentView:delegate:) ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"text":"parentViewController","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"parentView","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKBarcodeScannerViewControllerDelegate","text":"SBSDKBarcodeScannerViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"parentViewController","content":[{"inlineContent":[{"type":"text","text":"The view controller the newly created instance is embedded into."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The view, the newly created instance is embedded into.","type":"text"}]}],"name":"parentView"},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate for the receiver."}]}]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"If ","type":"text"},{"code":"parentViewController","type":"codeVoice"},{"type":"text","text":" conforms to "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate","type":"reference","isActive":true},{"text":" and if the delegate is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":", it is","type":"text"},{"type":"text","text":" "},{"type":"text","text":"automatically set as delegate."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/init(parentviewcontroller:parentview:delegate:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/init(parentviewcontroller:parentview:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/init(parentViewController:parentView:delegate:)","interfaceLanguage":"swift"},"abstract":[{"text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController":{"navigatorTitle":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","kind":"symbol","type":"topic","title":"SBSDKBarcodeScannerViewController","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode detector."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewControllerDelegate":{"role":"symbol","title":"SBSDKBarcodeScannerViewControllerDelegate","kind":"symbol","abstract":[{"type":"text","text":"The delegate protocol of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController"},{"text":" that provides methods for","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"enabling\/disabling detection and managing detected barcodes."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScannerViewControllerDelegate"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate","navigatorTitle":[{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontrollerdelegate","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/init(parentViewController:parentView:delegate:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"parentViewController"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"parentView"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKBarcodeScannerViewControllerDelegate"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/init(parentViewController:parentView:delegate:)","kind":"symbol","type":"topic","role":"symbol","title":"init(parentViewController:parentView:delegate:)","navigatorTitle":[{"text":"initWithParentViewController:parentView:delegate:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/init(parentviewcontroller:parentview:delegate:)","abstract":[{"type":"text","text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithParentViewController:parentView:delegate:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParentViewController:parentView:delegate:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithParentViewController:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"parentViewController","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentView:"},{"text":"(","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":" *) ","kind":"text"},{"text":"parentView","kind":"internalParam"},{"kind":"text","text":" "},{"text":"delegate:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKBarcodeScannerViewControllerDelegate","text":"id<SBSDKBarcodeScannerViewControllerDelegate>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"delegate"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKBarcodeScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/fragments"},{"value":"SBSDKBarcodeScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1init(parentViewController:parentView:delegate:)\/title","value":"initWithParentViewController:parentView:delegate:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithParentViewController:parentView:delegate:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1init(parentViewController:parentView:delegate:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}