{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/init(parentViewController:parentView:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/init(parentviewcontroller:parentview:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/init(parentviewcontroller:parentview:)"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController(im)initWithParentViewController:parentView:","modules":[{"name":"ScanbotSDK"}],"title":"init(parentViewController:parentView:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"parentViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"parentView","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithParentViewController:parentView:"}],"roleHeading":"Initializer"},"kind":"symbol","abstract":[{"text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWithParentViewController:parentView:) "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"text":"parentViewController","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"parentView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"parentViewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller, the newly created instance is embedded into."}]}]},{"name":"parentView","content":[{"inlineContent":[{"text":"The view, the newly created instance is embedded into.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"If parentViewController conforms to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate"},{"type":"text","text":", it is automatically set as delegate."}],"type":"paragraph"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewControllerDelegate":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontrollerdelegate","abstract":[{"type":"text","text":"The delegate protocol of "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","type":"reference"},{"text":" that provides methods for","type":"text"},{"text":" ","type":"text"},{"text":"enabling\/disabling detection and managing detected barcodes.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewControllerDelegate"}],"type":"topic","kind":"symbol","title":"SBSDKBarcodeScannerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController":{"title":"SBSDKBarcodeScannerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to show a camera screen with the barcode detector.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/init(parentViewController:parentView:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/init(parentViewController:parentView:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"parentViewController"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"parentView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","title":"init(parentViewController:parentView:)","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/init(parentviewcontroller:parentview:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithParentViewController:parentView:"}],"abstract":[{"text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithParentViewController:parentView:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithParentViewController:parentView:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithParentViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":" *) "},{"text":"parentViewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"parentView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"parentView","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The view controller, the newly created instance is embedded into."}],"type":"paragraph"}],"name":"parentViewController"},{"name":"parentView","content":[{"type":"paragraph","inlineContent":[{"text":"The view, the newly created instance is embedded into.","type":"text"}]}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate\/title","op":"replace","value":"SBSDKBarcodeScannerViewControllerDelegate"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewControllerDelegate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}]},{"op":"replace","value":"SBSDKBarcodeScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/fragments"},{"op":"replace","value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/navigatorTitle"},{"op":"replace","value":"initWithParentViewController:parentView:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1init(parentViewController:parentView:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1init(parentViewController:parentView:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithParentViewController:parentView:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}