{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController"]]},"metadata":{"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"role":"symbol","title":"viewDidLoad","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController(im)viewDidLoad"},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/viewDidLoad"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/viewdidload"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","title":"SBSDKBarcodeScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to show a camera screen with the barcode detector.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/viewDidLoad":{"fragments":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/viewdidload","abstract":[],"type":"topic","title":"viewDidLoad","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/viewDidLoad","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKBarcodeScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}]},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}