{"abstract":[{"text":"The delegation protocol for ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController","isActive":true},{"type":"text","text":"."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"title":"Conforming Types","type":"conformingTypes","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKGenericTextLineRecognizerViewControllerDelegate","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontrollerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontrollerdelegate"]}],"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewControllerDelegate\/textLineRecognizerViewController(_:didValidate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewControllerDelegate\/textLineRecognizerViewControllerShouldRecognize(_:)"],"anchor":"Instance-Methods"}],"metadata":{"title":"SBSDKGenericTextLineRecognizerViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewControllerDelegate"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewControllerDelegate"}],"roleHeading":"Protocol","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKGenericTextLineRecognizerViewControllerDelegate"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewControllerDelegate","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericTextLineRecognizerViewController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewController"}],"title":"SBSDKGenericTextLineRecognizerViewController","abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show a camera screen with the text line recognizer."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerViewControllerDelegate":{"abstract":[{"type":"text","text":"The delegation protocol for "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController","type":"reference"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewControllerDelegate"}],"title":"SBSDKGenericTextLineRecognizerViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewControllerDelegate"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontrollerdelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerViewControllerDelegate/textLineRecognizerViewController(_:didValidate:)":{"role":"symbol","navigatorTitle":[{"text":"textLineRecognizerViewController:didValidateResult:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontrollerdelegate\/textlinerecognizerviewcontroller(_:didvalidate:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textLineRecognizerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerViewController","text":"SBSDKGenericTextLineRecognizerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didValidate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResult","kind":"typeIdentifier","text":"SBSDKGenericTextLineRecognizerResult"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Informs the delegate that text line(s) has been recognized and validated and passes the result."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewControllerDelegate\/textLineRecognizerViewController(_:didValidate:)","title":"textLineRecognizerViewController(_:didValidate:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerViewControllerDelegate/textLineRecognizerViewControllerShouldRecognize(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"textLineRecognizerViewControllerShouldRecognize","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKGenericTextLineRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerViewController"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"textLineRecognizerViewControllerShouldRecognize:"}],"abstract":[{"text":"Optional. Asks the delegate whether the next video frame should be recognized or not.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontrollerdelegate\/textlinerecognizerviewcontrollershouldrecognize(_:)","title":"textLineRecognizerViewControllerShouldRecognize(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewControllerDelegate\/textLineRecognizerViewControllerShouldRecognize(_:)","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","title":"SBSDKUITextDataScannerViewController","abstract":[{"text":"A highly customizable camera-based view controller to recognize and validate a small rectangular text area in realtime.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKGenericTextLineRecognizerViewControllerDelegate"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKGenericTextLineRecognizerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKGenericTextLineRecognizerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewControllerDelegate\/textLineRecognizerViewController(_:didValidate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewControllerDelegate\/textLineRecognizerViewControllerShouldRecognize(_:)"],"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Conforming Types","type":"conformingTypes","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController"]}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericTextLineRecognizerViewControllerDelegate","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"SBSDKGenericTextLineRecognizerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController\/fragments","op":"replace","value":[{"text":"SBSDKGenericTextLineRecognizerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewController"}]},{"op":"replace","value":"SBSDKGenericTextLineRecognizerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewControllerDelegate\/title"},{"value":[{"text":"SBSDKGenericTextLineRecognizerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewControllerDelegate\/fragments"},{"value":[{"text":"SBSDKGenericTextLineRecognizerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewControllerDelegate\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewControllerDelegate~1textLineRecognizerViewController(_:didValidate:)\/title","op":"replace","value":"textLineRecognizerViewController:didValidateResult:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewControllerDelegate~1textLineRecognizerViewController(_:didValidate:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textLineRecognizerViewController:didValidateResult:"}]},{"value":"textLineRecognizerViewControllerShouldRecognize:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewControllerDelegate~1textLineRecognizerViewControllerShouldRecognize(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewControllerDelegate~1textLineRecognizerViewControllerShouldRecognize(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"textLineRecognizerViewControllerShouldRecognize:","kind":"identifier"}]},{"value":"SBSDKUITextDataScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/title"},{"value":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}