{"abstract":[{"text":"A class to manage playback of sounds and vibration.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdksoundcontroller"]},{"paths":["\/documentation\/scanbotsdk\/sbsdksoundcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","type":"conformsTo"}],"sections":[],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/init(soundType:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/type"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/playBleepSound()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/playCustomSound(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/vibrate()"]}],"metadata":{"title":"SBSDKSoundController","symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSoundController","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSoundController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKSoundController"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSoundController"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundController/init":{"title":"init","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/init","url":"\/documentation\/scanbotsdk\/sbsdksoundcontroller\/init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundController/init(soundType:)":{"abstract":[{"type":"text","text":"Designated initializer."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdksoundcontroller\/init(soundtype:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"soundType"},{"text":": ","kind":"text"},{"text":"SBSDKSoundType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKSoundType"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","title":"init(soundType:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/init(soundType:)","navigatorTitle":[{"kind":"identifier","text":"initWithSoundType:"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundController/vibrate()":{"abstract":[{"text":"Initiates a short vibration of the device. Can be used to give a haptic feedback.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdksoundcontroller\/vibrate()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vibrate","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","kind":"symbol","title":"vibrate()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/vibrate()","navigatorTitle":[{"text":"vibrate","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundController/playBleepSound()":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playBleepSound"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Plays a standard bleep sound."}],"navigatorTitle":[{"kind":"identifier","text":"playBleepSound"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/playBleepSound()","url":"\/documentation\/scanbotsdk\/sbsdksoundcontroller\/playbleepsound()","title":"playBleepSound()"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundController/type":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/scanbotsdk\/sbsdksoundcontroller\/type","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKSoundType","text":"SBSDKSoundType"}],"title":"type","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/type","abstract":[{"text":"To choose between multiple sounds to play.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundController/playCustomSound(from:)":{"abstract":[{"text":"Plays a custom sound loaded from a given URL.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdksoundcontroller\/playcustomsound(from:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"playCustomSound","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","title":"playCustomSound(from:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/playCustomSound(from:)","navigatorTitle":[{"kind":"identifier","text":"playCustomSoundFromURL:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKSoundController"}],"type":"topic","abstract":[{"text":"A class to manage playback of sounds and vibration.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdksoundcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController","title":"SBSDKSoundController","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKSoundController"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKSoundController","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKSoundController"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKSoundController","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/type"],"generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/init","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/init(soundType:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/playBleepSound()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/playCustomSound(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/vibrate()"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKSoundController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController~1init(soundType:)\/title","value":"initWithSoundType:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController~1init(soundType:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithSoundType:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"vibrate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController~1vibrate()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"vibrate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController~1vibrate()\/fragments"},{"op":"replace","value":"playBleepSound","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController~1playBleepSound()\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController~1playBleepSound()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"playBleepSound"}]},{"op":"replace","value":"type","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController~1type\/title"},{"value":[{"kind":"identifier","text":"type"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController~1type\/fragments","op":"replace"},{"value":"playCustomSoundFromURL:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController~1playCustomSound(from:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController~1playCustomSound(from:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playCustomSoundFromURL:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKSoundController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController\/title"},{"value":[{"kind":"identifier","text":"SBSDKSoundController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController\/fragments"},{"value":[{"text":"SBSDKSoundController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}