{"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Configuration of the mode for scanning multiple barcodes."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(SBSDKUI2MultipleScanningMode) "},{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MultipleScanningMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeUseCase"],"type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/init(countingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/init(from:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/allowEmptySubmission","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/arOverlay","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/barcodeInfoMapping","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/countingRepeatDelay","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/manualCountEditDialog","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/mode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/sheet","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/sheetContent"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/toJson()"],"anchor":"Instance-Methods"}],"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Class","role":"symbol","title":"SBSDKUI2MultipleScanningMode","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MultipleScanningMode","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/sheet":{"title":"sheet","abstract":[{"text":"Configuration of the preview mode for scanning multiple barcodes.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/sheet","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"sheet","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/sheet","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"sheet","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet","text":"SBSDKUI2Sheet","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/init(countingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)":{"title":"init(countingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)","url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/init(countingrepeatdelay:allowemptysubmission:mode:sheet:sheetcontent:manualcounteditdialog:barcodeinfomapping:aroverlay:)","abstract":[],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/init(countingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"countingRepeatDelay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"allowEmptySubmission"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"mode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MultipleBarcodesScanningMode","text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sheet"},{"kind":"text","text":": "},{"text":"SBSDKUI2Sheet","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet"},{"kind":"text","text":", "},{"text":"sheetContent","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent","text":"SBSDKUI2SheetContent"},{"text":", ","kind":"text"},{"text":"manualCountEditDialog","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ManualCountEditDialog","kind":"typeIdentifier","text":"SBSDKUI2ManualCountEditDialog"},{"text":", ","kind":"text"},{"text":"barcodeInfoMapping","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeInfoMapping","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeInfoMapping"},{"kind":"text","text":", "},{"kind":"externalParam","text":"arOverlay"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/hash":{"fragments":[{"kind":"identifier","text":"hash"}],"type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/hash","kind":"symbol","title":"hash","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/allowEmptySubmission":{"type":"topic","title":"allowEmptySubmission","url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/allowemptysubmission","kind":"symbol","navigatorTitle":[{"text":"allowEmptySubmission","kind":"identifier"}],"abstract":[{"type":"text","text":"Whether the user can submit an empty barcode list."},{"text":" ","type":"text"},{"text":"Default is false","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/allowEmptySubmission","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"allowEmptySubmission","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/sheetContent":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/sheetContent","navigatorTitle":[{"kind":"identifier","text":"sheetContent"}],"abstract":[{"type":"text","text":"Configuration of the list containing the barcodes that have already been scanned."}],"title":"sheetContent","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/sheetcontent","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sheetContent","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent","text":"SBSDKUI2SheetContent"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/fromJsonWithJson:":{"fragments":[{"kind":"text","text":"+ "},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/fromjsonwithjson:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/fromJsonWithJson:","title":"fromJsonWithJson:","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MultipleScanningMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode","role":"symbol","title":"SBSDKUI2MultipleScanningMode","abstract":[{"type":"text","text":"Configuration of the mode for scanning multiple barcodes."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2MultipleScanningMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/mode":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MultipleBarcodesScanningMode","text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"Mode used for scanning multiple barcodes.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is COUNTING"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/mode","url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/mode","title":"mode","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mode"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/isEqual:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/isequal:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/isEqual:","title":"isEqual:","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/countingRepeatDelay":{"navigatorTitle":[{"text":"countingRepeatDelay","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"Time interval in milliseconds before a barcode is counted again. 0 = no delay. The default value is 1000.","type":"text"},{"type":"text","text":" "},{"text":"Default is 1000","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"countingRepeatDelay","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/countingrepeatdelay","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/countingRepeatDelay","role":"symbol","title":"countingRepeatDelay"},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/manualCountEditDialog":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/manualCountEditDialog","navigatorTitle":[{"kind":"identifier","text":"manualCountEditDialog"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the dialog to manually edit the barcode count."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/manualcounteditdialog","title":"manualCountEditDialog","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"manualCountEditDialog"},{"kind":"text","text":": "},{"text":"SBSDKUI2ManualCountEditDialog","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ManualCountEditDialog"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/barcodeInfoMapping":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"barcodeInfoMapping","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeInfoMapping","text":"SBSDKUI2BarcodeInfoMapping"}],"abstract":[{"type":"text","text":"Appearance of the barcode info mapping."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/barcodeinfomapping","navigatorTitle":[{"kind":"identifier","text":"barcodeInfoMapping"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/barcodeInfoMapping","role":"symbol","type":"topic","title":"barcodeInfoMapping"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/arOverlay":{"abstract":[{"text":"Configuration of the AR overlay.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/aroverlay","navigatorTitle":[{"text":"arOverlay","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"arOverlay"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration"}],"title":"arOverlay","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/arOverlay"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/toJson()":{"navigatorTitle":[{"text":"toJson","kind":"identifier"}],"title":"toJson()","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"toJson","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/tojson()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/toJson()","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}]},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/init()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/init()","url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/init()","abstract":[],"title":"init()","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeUseCase":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeUseCase","kind":"identifier"}],"type":"topic","abstract":[{"text":"Configuration of the barcode scanner screen’s behavior.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeusecase","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeUseCase","kind":"symbol","title":"SBSDKUI2BarcodeUseCase","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2BarcodeUseCase","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/init(from:)":{"type":"topic","title":"init(from:)","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/init(from:)","url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/init(from:)","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"SBSDKUI2MultipleScanningMode","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2MultipleScanningMode"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/allowEmptySubmission","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/arOverlay","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/barcodeInfoMapping","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/countingRepeatDelay","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/manualCountEditDialog","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/mode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/sheet","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/sheetContent"],"anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/init(countingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/toJson()"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/fromJsonWithJson:"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeUseCase"],"kind":"relationships"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeUseCase","text":"SBSDKUI2BarcodeUseCase","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeUseCase","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1sheet\/title","value":"sheet","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1sheet\/fragments","value":[{"text":"sheet","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1init(countingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)\/title","value":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1init(countingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1allowEmptySubmission\/title","value":"allowEmptySubmission"},{"value":[{"text":"allowEmptySubmission","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1allowEmptySubmission\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1sheetContent\/title","value":"sheetContent","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1sheetContent\/fragments","value":[{"text":"sheetContent","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2MultipleScanningMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/fragments","value":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/navigatorTitle","value":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"mode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1mode\/title"},{"value":[{"text":"mode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1mode\/fragments","op":"replace"},{"value":"countingRepeatDelay","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1countingRepeatDelay\/title","op":"replace"},{"op":"replace","value":[{"text":"countingRepeatDelay","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1countingRepeatDelay\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1manualCountEditDialog\/title","op":"replace","value":"manualCountEditDialog"},{"value":[{"kind":"identifier","text":"manualCountEditDialog"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1manualCountEditDialog\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1barcodeInfoMapping\/title","value":"barcodeInfoMapping","op":"replace"},{"value":[{"text":"barcodeInfoMapping","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1barcodeInfoMapping\/fragments","op":"replace"},{"value":"arOverlay","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1arOverlay\/title"},{"op":"replace","value":[{"kind":"identifier","text":"arOverlay"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1arOverlay\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1toJson()\/title","value":"toJson"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1toJson()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJson"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1init()\/title","value":"init"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeUseCase\/title","op":"replace","value":"SBSDKUI2BarcodeUseCase"},{"value":[{"text":"SBSDKUI2BarcodeUseCase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeUseCase\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeUseCase"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeUseCase\/navigatorTitle"}]}]}