{"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKColorDocumentFilter"}],"title":"SBSDKColorDocumentFilter","symbolKind":"class","role":"symbol","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKColorDocumentFilter"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKColorDocumentFilter"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/toJson()"],"anchor":"Instance-Methods","generated":true}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKColorDocumentFilter) "},{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKColorDocumentFilter"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Color document filter. This filter is a good starting point for most use cases."}],"references":{"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorDocumentFilter/copyWithZone:":{"url":"\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter\/copywithzone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","role":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/copyWithZone:","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorDocumentFilter/hash":{"role":"symbol","fragments":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/hash","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter\/hash","type":"topic","kind":"symbol","title":"hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorDocumentFilter/init":{"title":"init","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter\/init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/init","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorDocumentFilter":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter","title":"SBSDKColorDocumentFilter","abstract":[{"text":"Color document filter. This filter is a good starting point for most use cases.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKColorDocumentFilter"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"Foundation.NSCopying"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","role":"symbol","abstract":[{"text":"Base class for all parametric filters.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKParametricFilter","kind":"identifier"}],"title":"SBSDKParametricFilter","type":"topic","navigatorTitle":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorDocumentFilter/toJson()":{"url":"\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter\/tojson()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/toJson()","title":"toJson()","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"toJson","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorDocumentFilter/isEqual:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/isEqual:","type":"topic","kind":"symbol","abstract":[],"role":"symbol","title":"isEqual:","url":"\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter\/isequal:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"SBSDKColorDocumentFilter","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKColorDocumentFilter"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/hash"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/init","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/toJson()"]}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKColorDocumentFilter"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier","text":"SBSDKParametricFilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKColorDocumentFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter\/title"},{"value":[{"kind":"identifier","text":"SBSDKColorDocumentFilter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter\/fragments"},{"value":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter\/navigatorTitle"},{"value":"SBSDKParametricFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/title"},{"value":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/navigatorTitle"},{"value":"toJson","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter~1toJson()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJson"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter~1toJson()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}