{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVolatileKeyProvider","title":"SBSDKVolatileKeyProvider","symbolKind":"class","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}]},"abstract":[{"type":"text","text":"A volatile key provider that generates and stores keys in memory."}],"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/init(keyGenerator:)"]},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/keyGenerator"],"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/deleteKeyForContext(_:keyLength:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/provideKeyForContext(_:keyLength:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/removeAllKeys()"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"inlineContent":[{"type":"text","text":"The key storage is a simple in-memory key-value store, with the key being a hashed and salted version of the context and the key length, and the value being the encryption key."},{"type":"text","text":" "},{"type":"text","text":"Use this provider for temporary encryption and decryption tasks or if you are a using one constant encryption key for all encryption\/decryption tasks, that can be easily be"},{"type":"text","text":" "},{"text":"recreated when the app is restarted, e.g. with generators as ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPBKDF2KeyGenerator"},{"text":" and ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHKDFKeyGenerator","isActive":true},{"type":"text","text":" that have fixed input values."}],"type":"paragraph"},{"style":"important","type":"aside","name":"Important","content":[{"inlineContent":[{"text":"The stored keys are lost when the app is terminated. Any encrypted data at that time will become undecryptable.","type":"text"}],"type":"paragraph"}]}]}],"sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvolatilekeyprovider"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvolatilekeyprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVolatileKeyProvider/provideKeyForContext(_:keyLength:)":{"abstract":[{"text":"Loads or generates the encryption\/decryption key for the given context.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/provideKeyForContext(_:keyLength:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provideKeyForContext","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"keyLength","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyLength","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvolatilekeyprovider\/providekeyforcontext(_:keylength:)","role":"symbol","title":"provideKeyForContext(_:keyLength:)","navigatorTitle":[{"kind":"identifier","text":"provideKeyForContext:keyLength:error:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVolatileKeyProvider/init(keyGenerator:)":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Designated initializer."}],"navigatorTitle":[{"text":"initWithKeyGenerator:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyGenerator"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyGenerator","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyGenerator"},{"text":")","kind":"text"}],"title":"init(keyGenerator:)","url":"\/documentation\/scanbotsdk\/sbsdkvolatilekeyprovider\/init(keygenerator:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/init(keyGenerator:)"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVolatileKeyProvider/removeAllKeys()":{"title":"removeAllKeys()","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/removeAllKeys()","url":"\/documentation\/scanbotsdk\/sbsdkvolatilekeyprovider\/removeallkeys()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAllKeys","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"Removes all keys from the provider."}],"role":"symbol","navigatorTitle":[{"text":"removeAllKeys","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPBKDF2KeyGenerator":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPBKDF2KeyGenerator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPBKDF2KeyGenerator"}],"title":"SBSDKPBKDF2KeyGenerator","abstract":[{"type":"text","text":"A key generator that uses the PBKDF2 algorithm to derive a key from a password and a salt."},{"text":" ","type":"text"},{"type":"text","text":"See https:\/\/en.wikipedia.org\/wiki\/PBKDF2 for more information."}],"url":"\/documentation\/scanbotsdk\/sbsdkpbkdf2keygenerator","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVolatileKeyProvider":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVolatileKeyProvider"}],"type":"topic","abstract":[{"type":"text","text":"A volatile key provider that generates and stores keys in memory."}],"url":"\/documentation\/scanbotsdk\/sbsdkvolatilekeyprovider","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider","title":"SBSDKVolatileKeyProvider","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVolatileKeyProvider"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVolatileKeyProvider/keyGenerator":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keyGenerator"},{"kind":"text","text":": "},{"text":"SBSDKStorageCryptingKeyGenerator","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyGenerator","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkvolatilekeyprovider\/keygenerator","kind":"symbol","title":"keyGenerator","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/keyGenerator","role":"symbol","navigatorTitle":[{"text":"keyGenerator","kind":"identifier"}],"abstract":[{"text":"The key generator that generates an encryption key for a context if no key is available yet.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyProvider":{"type":"topic","title":"SBSDKStorageCryptingKeyProvider","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider","abstract":[{"type":"text","text":"Protocol for loading, storing and providing encryption keys."},{"type":"text","text":" "},{"text":"The context parameter is used to distinguish between different encryption contexts.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeyprovider","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHKDFKeyGenerator":{"kind":"symbol","abstract":[{"text":"A key generator that uses the HMAC based HKDF algorithm to generate a new encryption key. SHA512 is used as the hash function.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The key generation consists of two phases: extraction and expansion."},{"type":"text","text":" "},{"text":"During the extraction a pseudo random key is generated from the input key material and an optional salt.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The expansion phase uses the pseudo random key and the info data block to derive the final key."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHKDFKeyGenerator","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkhkdfkeygenerator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHKDFKeyGenerator"}],"title":"SBSDKHKDFKeyGenerator","navigatorTitle":[{"text":"SBSDKHKDFKeyGenerator","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVolatileKeyProvider/deleteKeyForContext(_:keyLength:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deleteKeyForContext"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"keyLength","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","abstract":[{"text":"Deletes the key for the given context and key length.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkvolatilekeyprovider\/deletekeyforcontext(_:keylength:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/deleteKeyForContext(_:keyLength:)","kind":"symbol","title":"deleteKeyForContext(_:keyLength:)","role":"symbol","navigatorTitle":[{"text":"deleteKeyForContext:keyLength:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"SBSDKVolatileKeyProvider","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKVolatileKeyProvider"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/keyGenerator"]},{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/deleteKeyForContext(_:keyLength:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/init(keyGenerator:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/provideKeyForContext(_:keyLength:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/removeAllKeys()"],"title":"Instance Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider"],"title":"Conforms To","type":"conformsTo"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVolatileKeyProvider","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider~1provideKeyForContext(_:keyLength:)\/title","value":"provideKeyForContext:keyLength:error:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider~1provideKeyForContext(_:keyLength:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"provideKeyForContext:keyLength:error:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"initWithKeyGenerator:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider~1init(keyGenerator:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithKeyGenerator:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider~1init(keyGenerator:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider~1removeAllKeys()\/title","value":"removeAllKeys"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeAllKeys"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider~1removeAllKeys()\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPBKDF2KeyGenerator\/title","value":"SBSDKPBKDF2KeyGenerator","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPBKDF2KeyGenerator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPBKDF2KeyGenerator\/fragments","op":"replace"},{"value":[{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPBKDF2KeyGenerator\/navigatorTitle","op":"replace"},{"value":"SBSDKVolatileKeyProvider","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider\/fragments","value":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider\/navigatorTitle","value":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}]},{"value":"keyGenerator","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider~1keyGenerator\/title"},{"op":"replace","value":[{"text":"keyGenerator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider~1keyGenerator\/fragments"},{"value":"SBSDKStorageCryptingKeyProvider","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/title"},{"value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/navigatorTitle"},{"op":"replace","value":"SBSDKHKDFKeyGenerator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHKDFKeyGenerator\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHKDFKeyGenerator\/fragments","value":[{"text":"SBSDKHKDFKeyGenerator","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKHKDFKeyGenerator"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHKDFKeyGenerator\/navigatorTitle"},{"value":"deleteKeyForContext:keyLength:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider~1deleteKeyForContext(_:keyLength:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider~1deleteKeyForContext(_:keyLength:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteKeyForContext:keyLength:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}