{"metadata":{"navigatorTitle":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"role":"symbol","title":"SBSDKStorageCryptingKeyProvider","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyProvider","symbolKind":"protocol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"roleHeading":"Protocol"},"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider\/init(keyGenerator:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider\/keyGenerator"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider\/provideKeyForContext(_:keyLength:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"content":[{"type":"paragraph","inlineContent":[{"text":"For most applications in Scanbot SDK the context is derived from the URL of the file to encrypted or decrypted by calling the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Foundation\/URL\/sbsdk_encryptionContext"},{"text":" property on the URL.","type":"text"}]}],"style":"note","name":"Note","type":"aside"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeyprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeyprovider"]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Protocol for loading, storing and providing encryption keys."},{"type":"text","text":" "},{"type":"text","text":"The context parameter is used to distinguish between different encryption contexts."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"title":"Conforming Types","type":"conformingTypes","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyProvider/init(keyGenerator:)":{"url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeyprovider\/init(keygenerator:)","abstract":[{"type":"text","text":"Initializer that takes a key generator."}],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyGenerator"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyGenerator","kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyGenerator"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider\/init(keyGenerator:)","required":true,"title":"init(keyGenerator:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithKeyGenerator:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyProvider/provideKeyForContext(_:keyLength:)":{"title":"provideKeyForContext(_:keyLength:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provideKeyForContext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"keyLength","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"abstract":[{"text":"Tries to load the encryption key for the given context and key length.","type":"text"},{"text":" ","type":"text"},{"text":"If no key is available yet, a new key is generated by the receivers key generator and stored under the given context.","type":"text"}],"navigatorTitle":[{"text":"provideKeyForContext:keyLength:error:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider\/provideKeyForContext(_:keyLength:)","url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeyprovider\/providekeyforcontext(_:keylength:)","kind":"symbol","required":true,"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyProvider":{"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"abstract":[{"text":"Protocol for loading, storing and providing encryption keys.","type":"text"},{"text":" ","type":"text"},{"text":"The context parameter is used to distinguish between different encryption contexts.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeyprovider","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider","role":"symbol","title":"SBSDKStorageCryptingKeyProvider"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVolatileKeyProvider":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider","abstract":[{"type":"text","text":"A volatile key provider that generates and stores keys in memory."}],"title":"SBSDKVolatileKeyProvider","url":"\/documentation\/scanbotsdk\/sbsdkvolatilekeyprovider","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Foundation/URL/sbsdk_encryptionContext":{"title":"sbsdk_encryptionContext","abstract":[{"text":"The encryption context of the URL.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Foundation\/URL\/sbsdk_encryptionContext","url":"\/documentation\/scanbotsdk\/foundation\/url\/sbsdk_encryptioncontext","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbsdk_encryptionContext","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyProvider/keyGenerator":{"url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeyprovider\/keygenerator","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider\/keyGenerator","title":"keyGenerator","kind":"symbol","required":true,"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyGenerator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyGenerator","text":"SBSDKStorageCryptingKeyGenerator"}],"abstract":[{"text":"The key generator that generates an encryption key for a context if no key is available yet.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"keyGenerator"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKStorageCryptingKeyProvider","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider\/keyGenerator"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider\/init(keyGenerator:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider\/provideKeyForContext(_:keyLength:)"],"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","type":"conformingTypes","title":"Conforming Types","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithKeyGenerator:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider~1init(keyGenerator:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithKeyGenerator:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider~1init(keyGenerator:)\/fragments"},{"value":"provideKeyForContext:keyLength:error:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider~1provideKeyForContext(_:keyLength:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"provideKeyForContext:keyLength:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider~1provideKeyForContext(_:keyLength:)\/fragments"},{"value":"SBSDKStorageCryptingKeyProvider","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/title"},{"value":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/fragments"},{"value":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/navigatorTitle"},{"value":"SBSDKVolatileKeyProvider","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider\/title"},{"value":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKVolatileKeyProvider"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider\/navigatorTitle"},{"value":"keyGenerator","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider~1keyGenerator\/title"},{"value":[{"kind":"identifier","text":"keyGenerator"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider~1keyGenerator\/fragments"}]}]}