{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicensePlateScannerResult","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"roleHeading":"Class","title":"SBSDKLicensePlateScannerResult","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicensePlateScannerResult","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKLicensePlateScannerResult","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult"},"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/confidence","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/countryCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/croppedImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/isValidationSuccessful","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/licensePlate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/rawString"],"title":"Instance Properties"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"A class describing the result of a license plate scan.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerresult"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","type":"conformsTo"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerResult":{"role":"symbol","title":"SBSDKLicensePlateScannerResult","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerresult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicensePlateScannerResult","kind":"identifier"}],"abstract":[{"type":"text","text":"A class describing the result of a license plate scan."}],"navigatorTitle":[{"text":"SBSDKLicensePlateScannerResult","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerResult/isValidationSuccessful":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isValidationSuccessful"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/isValidationSuccessful","title":"isValidationSuccessful","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerresult\/isvalidationsuccessful","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isValidationSuccessful"}],"abstract":[{"type":"text","text":"Whether the validation of the scanned license plate was successful or not."}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerResult/rawString":{"type":"topic","title":"rawString","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/rawString","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerresult\/rawstring","navigatorTitle":[{"text":"rawString","kind":"identifier"}],"abstract":[{"text":"The whole, raw text that was recognized on the license plate.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawString","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerResult/croppedImage":{"abstract":[{"text":"The image that was used for the detection.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"croppedImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/croppedImage","title":"croppedImage","role":"symbol","navigatorTitle":[{"text":"croppedImage","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerresult\/croppedimage"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerResult/confidence":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerresult\/confidence","abstract":[{"text":"The text recognition confidence.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/confidence","navigatorTitle":[{"kind":"identifier","text":"confidence"}],"kind":"symbol","title":"confidence"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerResult/initWithCountryCode:licensePlate:rawString:confidence:isValidationSuccessful:croppedImage:":{"role":"symbol","type":"topic","abstract":[],"title":"initWithCountryCode:licensePlate:rawString:confidence:isValidationSuccessful:croppedImage:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCountryCode:licensePlate:rawString:confidence:isValidationSuccessful:croppedImage:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/initWithCountryCode:licensePlate:rawString:confidence:isValidationSuccessful:croppedImage:","navigatorTitle":[{"kind":"identifier","text":"initWithCountryCode:licensePlate:rawString:confidence:isValidationSuccessful:croppedImage:"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerresult\/initwithcountrycode:licenseplate:rawstring:confidence:isvalidationsuccessful:croppedimage:"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerResult/countryCode":{"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerresult\/countrycode","role":"symbol","abstract":[{"text":"The country code that recognized on the license plate.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"countryCode"}],"title":"countryCode","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"countryCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/countryCode"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerResult/licensePlate":{"title":"licensePlate","abstract":[{"type":"text","text":"The actual license plate text that was recognized on the license plate."}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerresult\/licenseplate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/licensePlate","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"licensePlate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"licensePlate"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKLicensePlateScannerResult","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKLicensePlateScannerResult","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerResult"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/confidence","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/countryCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/croppedImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/isValidationSuccessful","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/licensePlate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/rawString"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult\/initWithCountryCode:licensePlate:rawString:confidence:isValidationSuccessful:croppedImage:"],"title":"Instance Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicensePlateScannerResult","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKLicensePlateScannerResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult\/title","op":"replace"},{"value":[{"text":"SBSDKLicensePlateScannerResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult\/navigatorTitle","op":"replace"},{"value":"isValidationSuccessful","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult~1isValidationSuccessful\/title","op":"replace"},{"value":[{"text":"isValidationSuccessful","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult~1isValidationSuccessful\/fragments","op":"replace"},{"value":"rawString","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult~1rawString\/title","op":"replace"},{"value":[{"kind":"identifier","text":"rawString"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult~1rawString\/fragments","op":"replace"},{"value":"croppedImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult~1croppedImage\/title","op":"replace"},{"value":[{"text":"croppedImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult~1croppedImage\/fragments","op":"replace"},{"value":"confidence","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult~1confidence\/title","op":"replace"},{"value":[{"text":"confidence","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult~1confidence\/fragments","op":"replace"},{"value":"countryCode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult~1countryCode\/title","op":"replace"},{"value":[{"text":"countryCode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult~1countryCode\/fragments","op":"replace"},{"value":"licensePlate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult~1licensePlate\/title","op":"replace"},{"value":[{"text":"licensePlate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult~1licensePlate\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}