{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/init(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/init(noDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/badAngles","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/badAspectRatio","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/captureManual","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/capturing","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/energySaveMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/noDocumentFound","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/readyToCapture","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/textHintOffCenter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/tooDark","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/tooNoisy","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/tooSmall"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/toJson()"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}],"title":"SBSDKUI2UserGuidanceStates","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceStates","modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}],"roleHeading":"Class"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","type":"conformsTo"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2UserGuidanceStates) ","kind":"text"},{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2UserGuidanceStates"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2userguidancestates"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2userguidancestates"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates"},"abstract":[{"type":"text","text":"Configure the titles of the user guidance hints for different states."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/init(from:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"init(from:)","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/init(from:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/init(from:)","role":"symbol","type":"topic","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/badAspectRatio":{"type":"topic","role":"symbol","title":"badAspectRatio","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"badAspectRatio"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"badAspectRatio","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/badAspectRatio","abstract":[{"text":"The user guidance text displayed when a landscape document is detected when the camera is in portrait mode (and","type":"text"},{"type":"text","text":" "},{"text":"vice versa).","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is “?cameraUserGuidanceBadAspectRatio”"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/badaspectratio"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates":{"abstract":[{"type":"text","text":"Configure the titles of the user guidance hints for different states."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2UserGuidanceStates"}],"title":"SBSDKUI2UserGuidanceStates","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceStates"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/tooNoisy":{"kind":"symbol","role":"symbol","title":"tooNoisy","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/toonoisy","type":"topic","navigatorTitle":[{"text":"tooNoisy","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/tooNoisy","abstract":[{"text":"The user guidance text displayed when the background is too noisy.","type":"text"},{"type":"text","text":" "},{"text":"Default is “?cameraUserGuidanceTooNoisy”","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"tooNoisy","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/toJson()":{"abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/toJson()","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/tojson()","navigatorTitle":[{"kind":"identifier","text":"toJson"}],"kind":"symbol","title":"toJson()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/hash":{"fragments":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/hash","title":"hash","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/hash","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/init()":{"fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"title":"init()","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/init()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/init()","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/readyToCapture":{"kind":"symbol","role":"symbol","title":"readyToCapture","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/readytocapture","type":"topic","navigatorTitle":[{"text":"readyToCapture","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/readyToCapture","abstract":[{"type":"text","text":"The user guidance text displayed when the document is ready to be captured in ‘auto snapping’ mode."},{"text":" ","type":"text"},{"type":"text","text":"Default is “?cameraUserGuidanceReadyToCapture”"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"readyToCapture","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/init(noDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:)":{"type":"topic","title":"init(noDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/init(noDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"noDocumentFound","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"badAspectRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"badAngles"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textHintOffCenter"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tooSmall"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tooNoisy"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"tooDark","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"energySaveMode"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"readyToCapture"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"capturing"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"captureManual"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/init(nodocumentfound:badaspectratio:badangles:texthintoffcenter:toosmall:toonoisy:toodark:energysavemode:readytocapture:capturing:capturemanual:)","navigatorTitle":[{"text":"initWithNoDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/capturing":{"kind":"symbol","role":"symbol","title":"capturing","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/capturing","type":"topic","navigatorTitle":[{"text":"capturing","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/capturing","abstract":[{"text":"The user guidance text displayed when the document is being captured and user needs to hold the device still.","type":"text"},{"type":"text","text":" "},{"text":"Default is “?cameraUserGuidanceReadyToCapture”","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"capturing"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"title":"SBSDKUI2Node","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2node","abstract":[{"type":"text","text":"Abstract class for all the configurations."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2Node","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Node","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/textHintOffCenter":{"kind":"symbol","role":"symbol","title":"textHintOffCenter","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/texthintoffcenter","type":"topic","navigatorTitle":[{"text":"textHintOffCenter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/textHintOffCenter","abstract":[{"type":"text","text":"The user guidance text displayed when the document is not centered in the finder view."},{"text":" ","type":"text"},{"type":"text","text":"Default is “?cameraUserGuidanceTextHintOffCenter”"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textHintOffCenter","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/energySaveMode":{"kind":"symbol","navigatorTitle":[{"text":"energySaveMode","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"energySaveMode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","title":"energySaveMode","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/energysavemode","role":"symbol","abstract":[{"type":"text","text":"The user guidance text displayed when the device is in energy saving mode. iOS only."},{"type":"text","text":" "},{"text":"Default is “?cameraUserGuidanceEnergySaveMode”","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/energySaveMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/tooSmall":{"title":"tooSmall","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/toosmall","abstract":[{"type":"text","text":"The user guidance text displayed when the document is too far from camera."},{"type":"text","text":" "},{"text":"Default is “?cameraUserGuidanceTooSmall”","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"tooSmall","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/tooSmall","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"tooSmall","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/badAngles":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"badAngles","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The user guidance text displayed when the document pitch\/skew angle is unacceptable."},{"text":" ","type":"text"},{"text":"Default is “?cameraUserGuidanceBadAngles”","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/badangles","title":"badAngles","navigatorTitle":[{"kind":"identifier","text":"badAngles"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/badAngles","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/isEqual:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/isEqual:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[],"title":"isEqual:","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/isequal:","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/fromJsonWithJson:":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/fromjsonwithjson:","abstract":[],"title":"fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/fromJsonWithJson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/captureManual":{"url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/capturemanual","abstract":[{"text":"The user guidance text displayed when the document is ready to be captured in ‘manual snapping’ mode.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is “?cameraUserGuidanceReadyToCaptureManual”"}],"title":"captureManual","kind":"symbol","type":"topic","navigatorTitle":[{"text":"captureManual","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"captureManual"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/captureManual","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/noDocumentFound":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/noDocumentFound","abstract":[{"type":"text","text":"The user guidance text displayed when no document is found."},{"type":"text","text":" "},{"text":"Default is “?cameraUserGuidanceNoDocumentFound”","type":"text"}],"title":"noDocumentFound","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/nodocumentfound","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"noDocumentFound"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"text":"noDocumentFound","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/tooDark":{"kind":"symbol","title":"tooDark","abstract":[{"type":"text","text":"The user guidance text displayed when it is too dark to capture an adequate image."},{"type":"text","text":" "},{"type":"text","text":"Default is “?cameraUserGuidanceTooDark”"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/toodark","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/tooDark","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"tooDark","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"tooDark"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2UserGuidanceStates"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceStates"}]},{"op":"replace","value":[{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/badAngles","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/badAspectRatio","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/captureManual","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/capturing","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/energySaveMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/noDocumentFound","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/readyToCapture","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/textHintOffCenter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/tooDark","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/tooNoisy","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/tooSmall"],"title":"Instance Properties","anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/init(noDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/toJson()"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/fromJsonWithJson:"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","text":"SBSDKUI2Node"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1badAspectRatio\/title","op":"replace","value":"badAspectRatio"},{"value":[{"text":"badAspectRatio","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1badAspectRatio\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates\/title","value":"SBSDKUI2UserGuidanceStates"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceStates"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates\/navigatorTitle"},{"op":"replace","value":"tooNoisy","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1tooNoisy\/title"},{"value":[{"kind":"identifier","text":"tooNoisy"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1tooNoisy\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1toJson()\/title","value":"toJson"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1toJson()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"toJson","kind":"identifier"}]},{"value":"init","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1init()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1init()\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1readyToCapture\/title","value":"readyToCapture","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1readyToCapture\/fragments","op":"replace","value":[{"kind":"identifier","text":"readyToCapture"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1init(noDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:)\/title","value":"initWithNoDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1init(noDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithNoDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","kind":"identifier"}],"op":"replace"},{"value":"capturing","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1capturing\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1capturing\/fragments","value":[{"text":"capturing","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title","value":"SBSDKUI2Node"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments","value":[{"text":"SBSDKUI2Node","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Node"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1textHintOffCenter\/title","value":"textHintOffCenter","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1textHintOffCenter\/fragments","value":[{"kind":"identifier","text":"textHintOffCenter"}]},{"value":"energySaveMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1energySaveMode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1energySaveMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"energySaveMode"}]},{"value":"tooSmall","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1tooSmall\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1tooSmall\/fragments","op":"replace","value":[{"text":"tooSmall","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1badAngles\/title","value":"badAngles","op":"replace"},{"op":"replace","value":[{"text":"badAngles","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1badAngles\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1captureManual\/title","value":"captureManual"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1captureManual\/fragments","value":[{"kind":"identifier","text":"captureManual"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1noDocumentFound\/title","value":"noDocumentFound"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1noDocumentFound\/fragments","op":"replace","value":[{"kind":"identifier","text":"noDocumentFound"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1tooDark\/title","value":"tooDark"},{"op":"replace","value":[{"text":"tooDark","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1tooDark\/fragments"}]}]}