{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"Think of it as a 2-dimensional (page file identifier, page file type) disk-backed, dictionary-style image storage.","type":"text"},{"text":" ","type":"text"},{"text":"The default instance serves as backing storage for all ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage"},{"text":" objects.","type":"text"},{"text":" ","type":"text"},{"text":"Can generate preview images of optimal resolution for the devices screen.","type":"text"},{"text":" ","type":"text"},{"text":"Manages two types of images: original images (as from camera or photo library)","type":"text"},{"text":" ","type":"text"},{"text":"and document images (cropped and perspective-corrected).","type":"text"},{"text":" ","type":"text"},{"text":"Helps you efficiently managing and persisting larger images without keeping them in memory.","type":"text"}]},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"Since all images stored here are being persisted to the disk forever, you are responsible for removing"},{"type":"text","text":" "},{"type":"text","text":"unused images."}],"type":"paragraph"}],"style":"warning","name":"Warning"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPageFileStorage","modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}],"title":"SBSDKDocumentPageFileStorage","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}]},"abstract":[{"text":"A class to store and restore images of different types in a memory-efficient way.","type":"text"}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/init(imageFormat:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/init(imageFormat:quality:location:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/init(withJPEGAndCompressionQuality:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/allPageFileIDs","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/writingImageFileFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/writingJpegImageCompressionQuality"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/add(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/existsPageFileID(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/image(withPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/imageURL(withPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/previewImage(withPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/previewImageURL(withPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/removeAll()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/removeAllExcept(pageFileIDs:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/removeImage(forExistingPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/removePageFileID(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/set(_:forExistingPageFileID:pageFileType:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/defaultStorage"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/setDefaultStorage(_:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage","title":"SBSDKDocumentPageFileStorage","kind":"symbol","abstract":[{"text":"A class to store and restore images of different types in a memory-efficient way.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/image(withPageFileID:pageFileType:)":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/image(withpagefileid:pagefiletype:)","navigatorTitle":[{"kind":"identifier","text":"imageWithPageFileID:pageFileType:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPageFileID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageFileType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentPageFileType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"type":"text","text":"Returns the image with the given page file identifier and page file type."}],"role":"symbol","title":"image(withPageFileID:pageFileType:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/image(withPageFileID:pageFileType:)"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/removeAll()":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/removeall()","title":"removeAll()","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/removeAll()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAll","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Removes all images from the receiver.","type":"text"}],"navigatorTitle":[{"text":"removeAll","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPage"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","title":"SBSDKDocumentPage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/set(_:forExistingPageFileID:pageFileType:)":{"kind":"symbol","abstract":[{"type":"text","text":"Sets the image of the given page file type and page file type to the receiver."}],"title":"set(_:forExistingPageFileID:pageFileType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forExistingPageFileID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageFileType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType","kind":"typeIdentifier","text":"SBSDKDocumentPageFileType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","navigatorTitle":[{"text":"set:forExistingPageFileID:pageFileType:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/set(_:forExistingPageFileID:pageFileType:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/set(_:forexistingpagefileid:pagefiletype:)"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/setDefaultStorage(_:)":{"abstract":[{"type":"text","text":"Sets the default instance of this class."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDefaultStorage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKDocumentPageFileStorage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPageFileStorage"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/setdefaultstorage(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/setDefaultStorage(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setDefaultStorage:"}],"role":"symbol","title":"setDefaultStorage(_:)"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/previewImage(withPageFileID:pageFileType:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/previewImage(withPageFileID:pageFileType:)","title":"previewImage(withPageFileID:pageFileType:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/previewimage(withpagefileid:pagefiletype:)","abstract":[{"type":"text","text":"Returns the screen-size preview image with the given page file identifier and page file type."}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"previewImageWithPageFileID:pageFileType:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPageFileID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageFileType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentPageFileType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/writingImageFileFormat":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"writingImageFileFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/writingimagefileformat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/writingImageFileFormat","abstract":[{"text":"File format of the stored images. Read-only. Defaults to JPEG.","type":"text"}],"title":"writingImageFileFormat","navigatorTitle":[{"kind":"identifier","text":"writingImageFileFormat"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/init(withJPEGAndCompressionQuality:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/init(withJPEGAndCompressionQuality:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withJPEGAndCompressionQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"init(withJPEGAndCompressionQuality:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/init(withjpegandcompressionquality:)","navigatorTitle":[{"text":"initWithJPEGAndCompressionQuality:","kind":"identifier"}],"abstract":[{"text":"Initializes a storage with JPEG image format at the default storage location.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/existsPageFileID(_:)":{"kind":"symbol","title":"existsPageFileID(_:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/existspagefileid(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/existsPageFileID(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"existsPageFileID"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"existsPageFileID:"}],"abstract":[{"type":"text","text":"Checks if a page file identifier exists in the receiver."}],"type":"topic"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/previewImageURL(withPageFileID:pageFileType:)":{"title":"previewImageURL(withPageFileID:pageFileType:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewImageURL"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPageFileID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageFileType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType","text":"SBSDKDocumentPageFileType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/previewimageurl(withpagefileid:pagefiletype:)","navigatorTitle":[{"text":"previewImageURLWithPageFileID:pageFileType:","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns the file URL of a screen-size preview of the image with the given page file identifier and page file type."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/previewImageURL(withPageFileID:pageFileType:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/init(imageFormat:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithImageFormat:"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/init(imageFormat:)","abstract":[{"type":"text","text":"Initializes a storage with compression quality set to 80 at the default storage location."}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat","text":"SBSDKImageFileFormat"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/init(imageformat:)","title":"init(imageFormat:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/removeAllExcept(pageFileIDs:)":{"abstract":[{"type":"text","text":"Removes all images from the receiver, except those from the exception list."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/removeallexcept(pagefileids:)","kind":"symbol","navigatorTitle":[{"text":"removeAllExceptWithPageFileIDs:","kind":"identifier"}],"title":"removeAllExcept(pageFileIDs:)","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/removeAllExcept(pageFileIDs:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAllExcept","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pageFileIDs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":"])","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/defaultStorage":{"abstract":[{"text":"The default instance of this class.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/defaultStorage","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/defaultstorage","title":"defaultStorage","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultStorage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentPageFileStorage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPageFileStorage"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"defaultStorage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/removePageFileID(_:)":{"navigatorTitle":[{"kind":"identifier","text":"removePageFileID:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removePageFileID"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/removepagefileid(_:)","title":"removePageFileID(_:)","type":"topic","abstract":[{"text":"Removes all images with the given page file identifier.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/removePageFileID(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/add(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/add(_:)","role":"symbol","title":"add(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":") -> ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","abstract":[{"text":"Adds an image of page file type original to the receiver, generates a page file identifier and returns it.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/add(_:)","navigatorTitle":[{"text":"add:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/writingJpegImageCompressionQuality":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"writingJpegImageCompressionQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"role":"symbol","title":"writingJpegImageCompressionQuality","abstract":[{"text":"If file format is set to JPEG, this property holds the compression quality of the stored images.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/writingJpegImageCompressionQuality","navigatorTitle":[{"kind":"identifier","text":"writingJpegImageCompressionQuality"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/writingjpegimagecompressionquality","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/imageURL(withPageFileID:pageFileType:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageURLWithPageFileID:pageFileType:"}],"abstract":[{"text":"Returns the file URL of the image with the given page file identifier and page file type.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/imageURL(withPageFileID:pageFileType:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPageFileID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pageFileType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType","text":"SBSDKDocumentPageFileType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"imageURL(withPageFileID:pageFileType:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/imageurl(withpagefileid:pagefiletype:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/allPageFileIDs":{"abstract":[{"type":"text","text":"A list of all stored page file identifiers."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/allpagefileids","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allPageFileIDs"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"},{"kind":"text","text":"]"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"allPageFileIDs"}],"title":"allPageFileIDs","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/allPageFileIDs"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/init(imageFormat:quality:location:)":{"type":"topic","abstract":[{"text":"Initializes a storage.","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/init(imageFormat:quality:location:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithImageFormat:quality:location:"}],"title":"init(imageFormat:quality:location:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/init(imageformat:quality:location:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/removeImage(forExistingPageFileID:pageFileType:)":{"abstract":[{"text":"Removes the image with the given page file identifier and page file type.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forExistingPageFileID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":", ","kind":"text"},{"text":"pageFileType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentPageFileType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"removeImageForExistingPageFileID:pageFileType:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/removeimage(forexistingpagefileid:pagefiletype:)","title":"removeImage(forExistingPageFileID:pageFileType:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/removeImage(forExistingPageFileID:pageFileType:)","role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKDocumentPageFileStorage"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/allPageFileIDs","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/writingImageFileFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/writingJpegImageCompressionQuality"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/add(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/existsPageFileID(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/image(withPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/imageURL(withPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/init(imageFormat:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/init(imageFormat:quality:location:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/init(withJPEGAndCompressionQuality:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/previewImage(withPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/previewImageURL(withPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/removeAll()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/removeAllExcept(pageFileIDs:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/removeImage(forExistingPageFileID:pageFileType:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/removePageFileID(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/set(_:forExistingPageFileID:pageFileType:)"],"title":"Instance Methods"},{"generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/defaultStorage"],"title":"Type Properties"},{"generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/setDefaultStorage(_:)"],"title":"Type Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/title","op":"replace","value":"SBSDKDocumentPageFileStorage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1image(withPageFileID:pageFileType:)\/title","op":"replace","value":"imageWithPageFileID:pageFileType:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1image(withPageFileID:pageFileType:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imageWithPageFileID:pageFileType:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1removeAll()\/title","op":"replace","value":"removeAll"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1removeAll()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeAll"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title","op":"replace","value":"SBSDKDocumentPage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments","op":"replace","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1set(_:forExistingPageFileID:pageFileType:)\/title","op":"replace","value":"set:forExistingPageFileID:pageFileType:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1set(_:forExistingPageFileID:pageFileType:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"set:forExistingPageFileID:pageFileType:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1setDefaultStorage(_:)\/title","op":"replace","value":"setDefaultStorage:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1setDefaultStorage(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setDefaultStorage:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1previewImage(withPageFileID:pageFileType:)\/title","op":"replace","value":"previewImageWithPageFileID:pageFileType:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1previewImage(withPageFileID:pageFileType:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"previewImageWithPageFileID:pageFileType:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1writingImageFileFormat\/title","op":"replace","value":"writingImageFileFormat"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1writingImageFileFormat\/fragments","op":"replace","value":[{"text":"writingImageFileFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1init(withJPEGAndCompressionQuality:)\/title","op":"replace","value":"initWithJPEGAndCompressionQuality:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1init(withJPEGAndCompressionQuality:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithJPEGAndCompressionQuality:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1existsPageFileID(_:)\/title","op":"replace","value":"existsPageFileID:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1existsPageFileID(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"existsPageFileID:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1previewImageURL(withPageFileID:pageFileType:)\/title","op":"replace","value":"previewImageURLWithPageFileID:pageFileType:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1previewImageURL(withPageFileID:pageFileType:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"previewImageURLWithPageFileID:pageFileType:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1init(imageFormat:)\/title","op":"replace","value":"initWithImageFormat:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1init(imageFormat:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithImageFormat:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1removeAllExcept(pageFileIDs:)\/title","op":"replace","value":"removeAllExceptWithPageFileIDs:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1removeAllExcept(pageFileIDs:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeAllExceptWithPageFileIDs:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1defaultStorage\/title","op":"replace","value":"defaultStorage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1defaultStorage\/fragments","op":"replace","value":[{"kind":"identifier","text":"defaultStorage"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1removePageFileID(_:)\/title","op":"replace","value":"removePageFileID:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1removePageFileID(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removePageFileID:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1add(_:)\/title","op":"replace","value":"add:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1add(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"add:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1writingJpegImageCompressionQuality\/title","op":"replace","value":"writingJpegImageCompressionQuality"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1writingJpegImageCompressionQuality\/fragments","op":"replace","value":[{"kind":"identifier","text":"writingJpegImageCompressionQuality"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1imageURL(withPageFileID:pageFileType:)\/title","op":"replace","value":"imageURLWithPageFileID:pageFileType:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1imageURL(withPageFileID:pageFileType:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageURLWithPageFileID:pageFileType:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1allPageFileIDs\/title","op":"replace","value":"allPageFileIDs"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1allPageFileIDs\/fragments","op":"replace","value":[{"text":"allPageFileIDs","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1init(imageFormat:quality:location:)\/title","op":"replace","value":"initWithImageFormat:quality:location:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1init(imageFormat:quality:location:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithImageFormat:quality:location:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1removeImage(forExistingPageFileID:pageFileType:)\/title","op":"replace","value":"removeImageForExistingPageFileID:pageFileType:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1removeImage(forExistingPageFileID:pageFileType:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeImageForExistingPageFileID:pageFileType:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}