{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentRootType","title":"SBSDKCheckDocumentRootType","symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"text":"SBSDKCheckDocumentRootType","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckDocumentRootType","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentType"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"topicSections":[{"generated":true,"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/allDocumentTypes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/ausCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/canCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/fraCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/indCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/isrCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/kwtCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/uaeCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/unknownCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/usaCheck"]},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/rootType(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/wrap(_:)"],"title":"Type Methods","anchor":"Type-Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckDocumentRootType","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentroottype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentroottype"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Root document type.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentRootType/isrCheck":{"navigatorTitle":[{"kind":"identifier","text":"isrCheck"}],"abstract":[{"text":"ISRCheck document type.","type":"text"}],"type":"topic","title":"isrCheck","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/isrCheck","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isrCheck"},{"kind":"text","text":": "},{"text":"SBSDKCheckDocumentRootType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentRootType"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentroottype\/isrcheck"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentRootType/usaCheck":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"usaCheck","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKCheckDocumentRootType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentRootType"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentroottype\/usacheck","role":"symbol","abstract":[{"text":"USACheck document type.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"usaCheck","kind":"identifier"}],"title":"usaCheck","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/usaCheck"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentType","abstract":[{"type":"text","text":"A generic documents type."}],"title":"SBSDKGenericDocumentType","navigatorTitle":[{"text":"SBSDKGenericDocumentType","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumenttype","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentType"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentRootType/canCheck":{"title":"canCheck","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/canCheck","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentroottype\/cancheck","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"canCheck"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentRootType","text":"SBSDKCheckDocumentRootType"}],"abstract":[{"text":"CANCheck document type.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"canCheck"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentRootType/ausCheck":{"type":"topic","kind":"symbol","abstract":[{"text":"AUSCheck document type.","type":"text"}],"title":"ausCheck","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentroottype\/auscheck","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/ausCheck","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ausCheck","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKCheckDocumentRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentRootType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"ausCheck","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentRootType/unknownCheck":{"title":"unknownCheck","kind":"symbol","navigatorTitle":[{"text":"unknownCheck","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownCheck"},{"kind":"text","text":": "},{"text":"SBSDKCheckDocumentRootType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentRootType"}],"abstract":[{"type":"text","text":"UnknownCheck document type."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentroottype\/unknowncheck","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/unknownCheck"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentRootType":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCheckDocumentRootType","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentroottype","kind":"symbol","title":"SBSDKCheckDocumentRootType","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckDocumentRootType"}],"abstract":[{"type":"text","text":"Root document type."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentRootType/fraCheck":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentroottype\/fracheck","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fraCheck"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/fraCheck","abstract":[{"type":"text","text":"FRACheck document type."}],"role":"symbol","kind":"symbol","title":"fraCheck","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fraCheck"},{"kind":"text","text":": "},{"text":"SBSDKCheckDocumentRootType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentRootType"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentRootType/uaeCheck":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"uaeCheck"},{"text":": ","kind":"text"},{"text":"SBSDKCheckDocumentRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentRootType","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentroottype\/uaecheck","role":"symbol","type":"topic","abstract":[{"type":"text","text":"UAECheck document type."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"uaeCheck"}],"title":"uaeCheck","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/uaeCheck"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentRootType/initWithName:fullName:normalizedName:":{"title":"initWithName:fullName:normalizedName:","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/initWithName:fullName:normalizedName:","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentroottype\/initwithname:fullname:normalizedname:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithName:fullName:normalizedName:","kind":"identifier"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithName:fullName:normalizedName:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentRootType/rootType(from:)":{"title":"rootType(from:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rootType","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKCheckDocumentRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentRootType"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns root type corresponding to the given document."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/rootType(from:)","navigatorTitle":[{"text":"rootTypeFrom:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentroottype\/roottype(from:)","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentRootType/wrap(_:)":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wrap","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKGenericDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument"},{"kind":"text","text":") -> "},{"text":"SBSDKGenericDocumentWrapper","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentWrapper","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentroottype\/wrap(_:)","title":"wrap(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/wrap(_:)","role":"symbol","navigatorTitle":[{"text":"wrap:","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Creates a strongly-typed wrapper of the given document."},{"text":" ","type":"text"},{"text":"Returns nil if the document type is not part of this document schema.","type":"text"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentRootType/init":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentroottype\/init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/init","title":"init","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentRootType/kwtCheck":{"kind":"symbol","abstract":[{"type":"text","text":"KWTCheck document type."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/kwtCheck","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentroottype\/kwtcheck","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kwtCheck"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentRootType","text":"SBSDKCheckDocumentRootType"}],"title":"kwtCheck","navigatorTitle":[{"text":"kwtCheck","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentRootType/indCheck":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"indCheck"}],"abstract":[{"text":"INDCheck document type.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indCheck"},{"text":": ","kind":"text"},{"text":"SBSDKCheckDocumentRootType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentRootType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/indCheck","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentroottype\/indcheck","title":"indCheck","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentRootType/allDocumentTypes":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentroottype\/alldocumenttypes","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/allDocumentTypes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"allDocumentTypes"}],"kind":"symbol","title":"allDocumentTypes","abstract":[{"text":"Array of all available document root types.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allDocumentTypes"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentRootType","text":"SBSDKCheckDocumentRootType","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKCheckDocumentRootType","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"SBSDKCheckDocumentRootType","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCheckDocumentRootType"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/init","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/initWithName:fullName:normalizedName:"]},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/allDocumentTypes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/ausCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/canCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/fraCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/indCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/isrCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/kwtCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/uaeCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/unknownCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/usaCheck"],"title":"Type Properties","anchor":"Type-Properties"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/rootType(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType\/wrap(_:)"],"title":"Type Methods","anchor":"Type-Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentType"],"title":"Inherits From","type":"inheritsFrom"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckDocumentRootType"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentType","text":"SBSDKGenericDocumentType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"isrCheck","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1isrCheck\/title"},{"value":[{"text":"isrCheck","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1isrCheck\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1usaCheck\/title","value":"usaCheck"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1usaCheck\/fragments","value":[{"kind":"identifier","text":"usaCheck"}]},{"value":"SBSDKGenericDocumentType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentType\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentType\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentType"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentType\/navigatorTitle","op":"replace"},{"value":"canCheck","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1canCheck\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1canCheck\/fragments","value":[{"text":"canCheck","kind":"identifier"}]},{"value":"ausCheck","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1ausCheck\/title"},{"op":"replace","value":[{"text":"ausCheck","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1ausCheck\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1unknownCheck\/title","value":"unknownCheck"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1unknownCheck\/fragments","value":[{"text":"unknownCheck","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType\/title","value":"SBSDKCheckDocumentRootType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType\/fragments","value":[{"text":"SBSDKCheckDocumentRootType","kind":"identifier"}]},{"value":[{"text":"SBSDKCheckDocumentRootType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1fraCheck\/title","value":"fraCheck","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"fraCheck"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1fraCheck\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1uaeCheck\/title","op":"replace","value":"uaeCheck"},{"value":[{"text":"uaeCheck","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1uaeCheck\/fragments","op":"replace"},{"op":"replace","value":"rootTypeFrom:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1rootType(from:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"rootTypeFrom:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1rootType(from:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1wrap(_:)\/title","value":"wrap:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"wrap:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1wrap(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1kwtCheck\/title","value":"kwtCheck"},{"value":[{"kind":"identifier","text":"kwtCheck"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1kwtCheck\/fragments"},{"value":"indCheck","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1indCheck\/title","op":"replace"},{"value":[{"text":"indCheck","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1indCheck\/fragments","op":"replace"},{"value":"allDocumentTypes","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1allDocumentTypes\/title"},{"value":[{"text":"allDocumentTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType~1allDocumentTypes\/fragments","op":"replace"}]}]}