{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"enum","externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeMSIPlesseyChecksumAlgorithm","roleHeading":"Enumeration","role":"symbol","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod10","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1010","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1110IBM","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1110NCR","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod11IBM","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod11NCR","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/none"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true},{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm"]}],"abstract":[{"type":"text","text":"The checksum algorithm for MSI-Plessey type barcodes."}],"sections":[],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"title":"Conforms To","kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/Equatable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/Equatable-Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/equatable-implementations","kind":"article","abstract":[],"title":"Equatable Implementations"},"doc://net.doo.ScanbotSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/mod1010":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mod1010","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod1010","role":"symbol","abstract":[{"type":"text","text":"Mod1010."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1010","kind":"identifier"}],"title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod1010","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1010"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm":{"kind":"symbol","abstract":[{"type":"text","text":"The checksum algorithm for MSI-Plessey type barcodes."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm","role":"symbol","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/mod11IBM":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11IBM"}],"abstract":[{"type":"text","text":"Mod11IBM."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod11IBM","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod11ibm","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod11IBM","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"mod11IBM","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/mod11NCR":{"kind":"symbol","abstract":[{"text":"Mod11NCR.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod11ncr","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod11NCR","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mod11NCR","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod11NCR","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11NCR"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/init(rawValue:)","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/init(rawvalue:)","kind":"symbol","abstract":[],"title":"init(rawValue:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/mod1110IBM":{"navigatorTitle":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110IBM","kind":"identifier"}],"abstract":[{"type":"text","text":"Mod1110IBM."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1110IBM","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod1110ibm","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod1110IBM","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"mod1110IBM","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/mod1110NCR":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod1110ncr","abstract":[{"text":"Mod1110NCR.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1110NCR","navigatorTitle":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110NCR","kind":"identifier"}],"title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod1110NCR","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mod1110NCR"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/RawRepresentable-Implementations","kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/rawrepresentable-implementations","type":"topic","role":"collectionGroup","abstract":[],"title":"RawRepresentable Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/mod10":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod10","abstract":[{"type":"text","text":"Mod10."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod10","navigatorTitle":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod10","kind":"identifier"}],"title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod10","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mod10","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/none":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/none","role":"symbol","type":"topic","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.none","url":"\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"abstract":[{"text":"None.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmNone"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}]},{"value":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod10","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1010","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1110IBM","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1110NCR","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod11IBM","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod11NCR","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/none"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod1010\/title","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1010"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod1010\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1010"}],"op":"replace"},{"value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}]},{"value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod11IBM\/title","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11IBM","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11IBM"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod11IBM\/fragments"},{"op":"replace","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11NCR","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod11NCR\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11NCR"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod11NCR\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod1110IBM\/title","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110IBM","op":"replace"},{"value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110IBM","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod1110IBM\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod1110NCR\/title","op":"replace","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110NCR"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110NCR"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod1110NCR\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod10\/title","op":"replace","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod10"},{"value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod10","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod10\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1none\/title","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmNone"},{"value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmNone","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1none\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}