{"abstract":[{"type":"text","text":"Configuration of the Find and Pick barcode scanning mode."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeUseCase"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FindAndPickScanningMode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2FindAndPickScanningMode"}],"role":"symbol","roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKUI2FindAndPickScanningMode"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKUI2FindAndPickScanningMode) "},{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2FindAndPickScanningMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/init(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/init(scanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:)"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/allowPartialScan","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/arOverlay","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/confirmationAlertDialog","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/confirmationAlertDialogEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/countingRepeatDelay","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/expectedBarcodes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/manualCountEditDialog","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/partialScannedAlertDialog","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/partialScannedAlertDialogEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/scanningCompletedColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/scanningNotScannedColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/scanningPartiallyColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/sheet","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/sheetContent"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/toJson()"]}],"references":{"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/scanningNotScannedColor":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanningNotScannedColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"}],"navigatorTitle":[{"kind":"identifier","text":"scanningNotScannedColor"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/scanningNotScannedColor","title":"scanningNotScannedColor","abstract":[{"type":"text","text":"Color of the not scanned barcode ."},{"type":"text","text":" "},{"type":"text","text":"Default is “?sbColorOutline”"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/scanningnotscannedcolor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/expectedBarcodes":{"title":"expectedBarcodes","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/expectedbarcodes","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/expectedBarcodes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"expectedBarcodes"}],"abstract":[{"type":"text","text":"List of barcodes that the user has to find and scan."}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expectedBarcodes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKUI2ExpectedBarcode","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ExpectedBarcode"},{"kind":"text","text":"]"}]},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/isEqual:":{"title":"isEqual:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/isequal:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/isEqual:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"abstract":[],"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/countingRepeatDelay":{"abstract":[{"type":"text","text":"Time interval in milliseconds before a barcode is counted again. 0 = no delay. The default value is 1000."},{"type":"text","text":" "},{"type":"text","text":"Default is 1000"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/countingRepeatDelay","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/countingrepeatdelay","title":"countingRepeatDelay","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"countingRepeatDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"countingRepeatDelay"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/allowPartialScan":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/allowpartialscan","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowPartialScan"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"allowPartialScan","abstract":[{"type":"text","text":"If the user is allowed to finish the scanning process without scanning all the expected barcodes."},{"type":"text","text":" "},{"type":"text","text":"Default is false"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/allowPartialScan","navigatorTitle":[{"kind":"identifier","text":"allowPartialScan"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/sheetContent":{"abstract":[{"type":"text","text":"Configuration of the list of barcodes required to be found and scanned."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/sheetContent","title":"sheetContent","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/sheetcontent","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sheetContent","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent","text":"SBSDKUI2SheetContent","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"sheetContent","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/scanningPartiallyColor":{"url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/scanningpartiallycolor","navigatorTitle":[{"text":"scanningPartiallyColor","kind":"identifier"}],"abstract":[{"text":"Color of the partially scanned barcode.","type":"text"},{"text":" ","type":"text"},{"text":"Default is “?sbColorWarning”","type":"text"}],"title":"scanningPartiallyColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanningPartiallyColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/scanningPartiallyColor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/sheet":{"url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/sheet","navigatorTitle":[{"kind":"identifier","text":"sheet"}],"abstract":[{"text":"Configuration of the preview mode for the barcodes required to be found and scanned.","type":"text"}],"title":"sheet","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sheet"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet","kind":"typeIdentifier","text":"SBSDKUI2Sheet"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/sheet"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/arOverlay":{"kind":"symbol","role":"symbol","title":"arOverlay","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/aroverlay","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"arOverlay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ArOverlayFindAndPickConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayFindAndPickConfiguration","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"arOverlay"}],"type":"topic","abstract":[{"type":"text","text":"Configuration of the AR overlay."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/arOverlay"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/scanningCompletedColor":{"kind":"symbol","navigatorTitle":[{"text":"scanningCompletedColor","kind":"identifier"}],"title":"scanningCompletedColor","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/scanningCompletedColor","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/scanningcompletedcolor","abstract":[{"text":"Color of the selected barcode.","type":"text"},{"text":" ","type":"text"},{"text":"Default is “?sbColorPositive”","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanningCompletedColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode":{"kind":"symbol","role":"symbol","title":"SBSDKUI2FindAndPickScanningMode","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}],"type":"topic","abstract":[{"text":"Configuration of the Find and Pick barcode scanning mode.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/init()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/init()","kind":"symbol","abstract":[],"type":"topic","title":"init()","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/init(scanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:)":{"title":"init(scanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:)","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/init(scanningcompletedcolor:scanningpartiallycolor:scanningnotscannedcolor:allowpartialscan:expectedbarcodes:countingrepeatdelay:sheet:sheetcontent:manualcounteditdialog:aroverlay:partialscannedalertdialogenabled:partialscannedalertdialog:c-8ofi3","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/init(scanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:)","navigatorTitle":[{"kind":"identifier","text":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"scanningCompletedColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scanningPartiallyColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scanningNotScannedColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowPartialScan"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expectedBarcodes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ExpectedBarcode","text":"SBSDKUI2ExpectedBarcode"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"countingRepeatDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sheet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet","text":"SBSDKUI2Sheet"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sheetContent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent","text":"SBSDKUI2SheetContent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"manualCountEditDialog"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ManualCountEditDialog","text":"SBSDKUI2ManualCountEditDialog"},{"kind":"text","text":", "},{"kind":"externalParam","text":"arOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayFindAndPickConfiguration","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"partialScannedAlertDialogEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"partialScannedAlertDialog"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog"},{"kind":"text","text":", "},{"kind":"externalParam","text":"confirmationAlertDialogEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"confirmationAlertDialog"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog"},{"kind":"text","text":")"}],"abstract":[]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/toJson()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/toJson()","role":"symbol","navigatorTitle":[{"text":"toJson","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/tojson()","title":"toJson()","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/manualCountEditDialog":{"url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/manualcounteditdialog","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"manualCountEditDialog"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ManualCountEditDialog","text":"SBSDKUI2ManualCountEditDialog"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"manualCountEditDialog"}],"type":"topic","abstract":[{"type":"text","text":"Configuration of the dialog to manually edit the barcode count."}],"kind":"symbol","title":"manualCountEditDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/manualCountEditDialog"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/hash":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/hash","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/hash","title":"hash","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"hash"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/init(from:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/init(from:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/init(from:)","title":"init(from:)","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeUseCase":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeUseCase","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeUseCase","kind":"identifier"}],"type":"topic","abstract":[{"text":"Configuration of the barcode scanner screen’s behavior.","type":"text"}],"title":"SBSDKUI2BarcodeUseCase","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeUseCase","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeusecase"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/partialScannedAlertDialog":{"url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/partialscannedalertdialog","abstract":[{"text":"Configuration of the partial scanned alert dialog.","type":"text"}],"kind":"symbol","type":"topic","title":"partialScannedAlertDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/partialScannedAlertDialog","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"partialScannedAlertDialog","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"partialScannedAlertDialog","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/partialScannedAlertDialogEnabled":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/partialScannedAlertDialogEnabled","title":"partialScannedAlertDialogEnabled","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/partialscannedalertdialogenabled","abstract":[{"type":"text","text":"If the partial scanned alert dialog is enabled."},{"type":"text","text":" "},{"type":"text","text":"Default is true"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"partialScannedAlertDialogEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"partialScannedAlertDialogEnabled","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/confirmationAlertDialogEnabled":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/confirmationalertdialogenabled","navigatorTitle":[{"text":"confirmationAlertDialogEnabled","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/confirmationAlertDialogEnabled","abstract":[{"text":"If the confirmation alert dialog is enabled.","type":"text"},{"text":" ","type":"text"},{"text":"Default is false","type":"text"}],"title":"confirmationAlertDialogEnabled","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmationAlertDialogEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/confirmationAlertDialog":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/confirmationalertdialog","navigatorTitle":[{"text":"confirmationAlertDialog","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/confirmationAlertDialog","abstract":[{"type":"text","text":"Configuration of the confirmation alert dialog."}],"title":"confirmationAlertDialog","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmationAlertDialog","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/fromJsonWithJson:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/fromJsonWithJson:","kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/fromjsonwithjson:","title":"fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2FindAndPickScanningMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2FindAndPickScanningMode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/allowPartialScan","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/arOverlay","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/confirmationAlertDialog","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/confirmationAlertDialogEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/countingRepeatDelay","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/expectedBarcodes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/manualCountEditDialog","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/partialScannedAlertDialog","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/partialScannedAlertDialogEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/scanningCompletedColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/scanningNotScannedColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/scanningPartiallyColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/sheet","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/sheetContent"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/init(scanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/toJson()"],"generated":true},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/fromJsonWithJson:"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeUseCase"],"kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeUseCase","text":"SBSDKUI2BarcodeUseCase","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeUseCase","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1scanningNotScannedColor\/title","value":"scanningNotScannedColor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1scanningNotScannedColor\/fragments","op":"replace","value":[{"kind":"identifier","text":"scanningNotScannedColor"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1expectedBarcodes\/title","op":"replace","value":"expectedBarcodes"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1expectedBarcodes\/fragments","op":"replace","value":[{"kind":"identifier","text":"expectedBarcodes"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1countingRepeatDelay\/title","op":"replace","value":"countingRepeatDelay"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1countingRepeatDelay\/fragments","op":"replace","value":[{"kind":"identifier","text":"countingRepeatDelay"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1allowPartialScan\/title","op":"replace","value":"allowPartialScan"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1allowPartialScan\/fragments","op":"replace","value":[{"text":"allowPartialScan","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1sheetContent\/title","op":"replace","value":"sheetContent"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1sheetContent\/fragments","op":"replace","value":[{"kind":"identifier","text":"sheetContent"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1scanningPartiallyColor\/title","op":"replace","value":"scanningPartiallyColor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1scanningPartiallyColor\/fragments","op":"replace","value":[{"kind":"identifier","text":"scanningPartiallyColor"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1sheet\/title","op":"replace","value":"sheet"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1sheet\/fragments","op":"replace","value":[{"text":"sheet","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1arOverlay\/title","op":"replace","value":"arOverlay"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1arOverlay\/fragments","op":"replace","value":[{"kind":"identifier","text":"arOverlay"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1scanningCompletedColor\/title","op":"replace","value":"scanningCompletedColor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1scanningCompletedColor\/fragments","op":"replace","value":[{"text":"scanningCompletedColor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode\/title","op":"replace","value":"SBSDKUI2FindAndPickScanningMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2FindAndPickScanningMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2FindAndPickScanningMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1init()\/title","op":"replace","value":"init"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1init()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1init(scanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:)\/title","op":"replace","value":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1init(scanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1toJson()\/title","op":"replace","value":"toJson"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1toJson()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"toJson","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1manualCountEditDialog\/title","op":"replace","value":"manualCountEditDialog"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1manualCountEditDialog\/fragments","op":"replace","value":[{"text":"manualCountEditDialog","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeUseCase\/title","op":"replace","value":"SBSDKUI2BarcodeUseCase"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeUseCase\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeUseCase"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeUseCase\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeUseCase"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1partialScannedAlertDialog\/title","op":"replace","value":"partialScannedAlertDialog"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1partialScannedAlertDialog\/fragments","op":"replace","value":[{"text":"partialScannedAlertDialog","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1partialScannedAlertDialogEnabled\/title","op":"replace","value":"partialScannedAlertDialogEnabled"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1partialScannedAlertDialogEnabled\/fragments","op":"replace","value":[{"text":"partialScannedAlertDialogEnabled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1confirmationAlertDialogEnabled\/title","op":"replace","value":"confirmationAlertDialogEnabled"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1confirmationAlertDialogEnabled\/fragments","op":"replace","value":[{"text":"confirmationAlertDialogEnabled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1confirmationAlertDialog\/title","op":"replace","value":"confirmationAlertDialog"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode~1confirmationAlertDialog\/fragments","op":"replace","value":[{"text":"confirmationAlertDialog","kind":"identifier"}]}]}]}