{"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/s8SendableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring","doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"title":"SBSDKUIFinderDocumentScannerViewController","modules":[{"name":"ScanbotSDK"}],"role":"symbol","platforms":[],"symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerViewController","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}]},"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/delegate"],"title":"Instance Properties","generated":true},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/viewDidLoad()"]},{"anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/create(document:configuration:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/createNew(configuration:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/present(on:configuration:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/present(on:document:configuration:delegate:)"],"title":"Type Methods","generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An edge-detection based algorithm finds documents in the camera stream within the view finder."},{"text":" ","type":"text"},{"type":"text","text":"A manual or automatic high resolution snapshot can be made. Based on the detected area of the document in the photo,"},{"text":" ","type":"text"},{"type":"text","text":"the photo is cropped and perspective-corrected, so that a nice flattened image of the document only is created."}]}]}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2DocumentScannerViewController instead."}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"A highly customizable camera-based view controller to scan a single documents of a certain aspect ratio.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/initWithCoder:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/initwithcoder:","role":"symbol","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"title":"initWithCoder:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/initWithCoder:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/enableCameraUIConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/enableCameraUIConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/enablecamerauiconfiguration","title":"enableCameraUIConfiguration","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"enableCameraUIConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/enableCameraTextConfiguration":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/enableCameraTextConfiguration","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/enablecameratextconfiguration","title":"enableCameraTextConfiguration","fragments":[{"text":"enableCameraTextConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/delegate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/delegate","deprecated":true,"abstract":[{"type":"text","text":"The receivers delegate."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIFinderDocumentScannerViewControllerDelegate","text":"SBSDKUIFinderDocumentScannerViewControllerDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"title":"delegate","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/delegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/willShowEnableCameraView":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/willShowEnableCameraView","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/willshowenablecameraview","title":"willShowEnableCameraView","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"willShowEnableCameraView","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"willShowEnableCameraView"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/present(on:document:configuration:delegate:)":{"role":"symbol","deprecated":true,"kind":"symbol","navigatorTitle":[{"text":"presentOn:document:withConfiguration:andDelegate:","kind":"identifier"}],"abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController","isActive":true},{"text":" and presents it modally.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"present","kind":"identifier"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"document"},{"text":": ","kind":"text"},{"text":"SBSDKDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUIFinderDocumentScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIFinderDocumentScannerViewControllerDelegate"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerViewController","kind":"typeIdentifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/present(on:document:configuration:delegate:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/present(on:document:configuration:delegate:)","title":"present(on:document:configuration:delegate:)","type":"topic"},"doc://net.doo.ScanbotSDK/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/containerForEnableCameraView":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/containerForEnableCameraView","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/containerforenablecameraview","title":"containerForEnableCameraView","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"containerForEnableCameraView","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:":{"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/documentscannerviewcontroller:didsnapdocumentimage:onimage:withresult:autosnapped:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:"}],"title":"documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:","navigatorTitle":[{"kind":"identifier","text":"documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUICameraViewController","kind":"identifier"}],"title":"SBSDKUICameraViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController","abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController"},{"text":" subclass which adds support for enabled and disabled camera permission.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICameraViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/present(on:configuration:delegate:)":{"deprecated":true,"title":"present(on:configuration:delegate:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/present(on:configuration:delegate:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/present(on:configuration:delegate:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"present","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerConfiguration","text":"SBSDKUIFinderDocumentScannerConfiguration"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIFinderDocumentScannerViewControllerDelegate","text":"SBSDKUIFinderDocumentScannerViewControllerDelegate"},{"text":"?) -> ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerViewController","kind":"typeIdentifier"}],"abstract":[{"text":"Creates a new instance of ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController","isActive":true},{"type":"text","text":" and presents it modally. Creates a new"},{"type":"text","text":" "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument","type":"reference"},{"text":" instance.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"presentOn:configuration:delegate:"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/didFinish":{"navigatorTitle":[{"text":"didFinish","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/didFinish","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/didfinish","title":"didFinish","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didFinish"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s8SendableP"},"doc://net.doo.ScanbotSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/documentScannerViewControllerWillSnapImage:":{"navigatorTitle":[{"kind":"identifier","text":"documentScannerViewControllerWillSnapImage:"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/documentScannerViewControllerWillSnapImage:","type":"topic","kind":"symbol","role":"symbol","title":"documentScannerViewControllerWillSnapImage:","fragments":[{"text":"- ","kind":"text"},{"text":"documentScannerViewControllerWillSnapImage:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/documentscannerviewcontrollerwillsnapimage:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/documentScannerViewControllerDidFailSnappingImage:withError:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/documentScannerViewControllerDidFailSnappingImage:withError:","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/documentscannerviewcontrollerdidfailsnappingimage:witherror:","title":"documentScannerViewControllerDidFailSnappingImage:withError:","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"documentScannerViewControllerDidFailSnappingImage:withError:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"text":"documentScannerViewControllerDidFailSnappingImage:withError:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewController":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIViewController"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIViewController"}],"abstract":[{"type":"text","text":"An abstract base class for RTU-UI view controllers."}],"title":"SBSDKUIViewController","url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/updateFlashButton":{"navigatorTitle":[{"text":"updateFlashButton","kind":"identifier"}],"title":"updateFlashButton","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateFlashButton"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/updateflashbutton","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/updateFlashButton","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/supportedInterfaceOrientations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/supportedInterfaceOrientations","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/supportedinterfaceorientations","title":"supportedInterfaceOrientations","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"supportedInterfaceOrientations"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewControllerDelegate":{"type":"topic","role":"symbol","title":"SBSDKDocumentScannerViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerViewControllerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontrollerdelegate","abstract":[{"type":"text","text":"The delegate protocol of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController"},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/createNew(configuration:delegate:)":{"deprecated":true,"kind":"symbol","title":"createNew(configuration:delegate:)","abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController"},{"text":". Generates a new instance of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument"},{"text":".","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/createnew(configuration:delegate:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/createNew(configuration:delegate:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createNew"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerConfiguration","text":"SBSDKUIFinderDocumentScannerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIFinderDocumentScannerViewControllerDelegate","text":"SBSDKUIFinderDocumentScannerViewControllerDelegate"},{"text":") -> ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerViewController"}],"navigatorTitle":[{"text":"createNewWithConfiguration:andDelegate:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"abstract":[{"text":"A UIViewController subclass to show a camera screen and run a user guiding document detector.","type":"text"}],"type":"topic","title":"SBSDKDocumentScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/didCancel":{"kind":"symbol","role":"symbol","title":"didCancel","navigatorTitle":[{"text":"didCancel","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/didCancel","fragments":[{"text":"- ","kind":"text"},{"text":"didCancel","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/didcancel","type":"topic"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:":{"role":"symbol","title":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","abstract":[],"navigatorTitle":[{"text":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/documentscannerviewcontroller:configurestatusdetectionlabel:fordetectionresult:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/cameraAccessDidChange:":{"type":"topic","kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"text":"cameraAccessDidChange:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"text":"cameraAccessDidChange:","kind":"identifier"}],"title":"cameraAccessDidChange:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/cameraAccessDidChange:","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/cameraaccessdidchange:"},"doc://net.doo.ScanbotSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/viewDidLoad()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/viewdidload()","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/viewDidLoad()","title":"viewDidLoad()","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocument":{"kind":"symbol","role":"symbol","title":"SBSDKDocument","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocument"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocument"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocument","abstract":[{"text":"A thread-safe, mutable container for scanned pages of type ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument","type":"topic"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/didHideEnableCameraView":{"type":"topic","kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"text":"didHideEnableCameraView","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"didHideEnableCameraView","kind":"identifier"}],"title":"didHideEnableCameraView","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/didHideEnableCameraView","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/didhideenablecameraview"},"doc://net.doo.ScanbotSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/create(document:configuration:delegate:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/create(document:configuration:delegate:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/create(document:configuration:delegate:)","title":"create(document:configuration:delegate:)","abstract":[{"type":"text","text":"Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"role":"symbol","kind":"symbol","deprecated":true,"navigatorTitle":[{"text":"createWithDocument:configuration:andDelegate:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"text":"document","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","text":"SBSDKDocument"},{"kind":"text","text":"?, "},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUIFinderDocumentScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIFinderDocumentScannerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerViewController","text":"SBSDKUIFinderDocumentScannerViewController","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController":{"kind":"symbol","role":"symbol","title":"SBSDKUIFinderDocumentScannerViewController","navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller","deprecated":true,"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan a single documents of a certain aspect ratio."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController","type":"topic"},"doc://net.doo.ScanbotSDK/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer"},"doc://net.doo.ScanbotSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding"},"doc://net.doo.ScanbotSDK/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment"},"doc://net.doo.ScanbotSDK/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKUIFinderDocumentScannerViewController","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/containerForEnableCameraView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/delegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/enableCameraTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/enableCameraUIConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/supportedInterfaceOrientations"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/cameraAccessDidChange:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/didCancel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/didFinish","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/didHideEnableCameraView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/documentScannerViewControllerDidFailSnappingImage:withError:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/documentScannerViewControllerWillSnapImage:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/initWithCoder:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/updateFlashButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/viewDidLoad()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/willShowEnableCameraView"],"title":"Instance Methods","generated":true},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/create(document:configuration:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/createNew(configuration:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/present(on:configuration:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/present(on:document:configuration:delegate:)"],"anchor":"Type-Methods","generated":true}],"op":"replace"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController"],"type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewControllerDelegate"],"kind":"relationships","title":"Conforms To"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraViewController","kind":"typeIdentifier","text":"SBSDKUICameraViewController"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController~1delegate\/title"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController~1delegate\/fragments","op":"replace"},{"value":"presentOn:document:withConfiguration:andDelegate:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController~1present(on:document:configuration:delegate:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController~1present(on:document:configuration:delegate:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"presentOn:document:withConfiguration:andDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/title","value":"SBSDKUICameraViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/fragments","value":[{"text":"SBSDKUICameraViewController","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKUICameraViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController~1present(on:configuration:delegate:)\/title","value":"presentOn:configuration:delegate:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController~1present(on:configuration:delegate:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"presentOn:configuration:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/title","value":"SBSDKUIViewController"},{"value":[{"text":"SBSDKUIViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate\/title","value":"SBSDKDocumentScannerViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewControllerDelegate"}]},{"op":"replace","value":[{"text":"SBSDKDocumentScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewControllerDelegate\/navigatorTitle"},{"value":"createNewWithConfiguration:andDelegate:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController~1createNew(configuration:delegate:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"createNewWithConfiguration:andDelegate:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController~1createNew(configuration:delegate:)\/fragments","op":"replace"},{"op":"replace","value":"SBSDKDocumentScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}]},{"value":"viewDidLoad","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController~1viewDidLoad()\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}],"op":"replace"},{"value":"SBSDKDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/title"},{"value":[{"text":"SBSDKDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/navigatorTitle","value":[{"text":"SBSDKDocument","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController~1create(document:configuration:delegate:)\/title","value":"createWithDocument:configuration:andDelegate:"},{"value":[{"kind":"text","text":"+ "},{"text":"createWithDocument:configuration:andDelegate:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController~1create(document:configuration:delegate:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController\/title","op":"replace","value":"SBSDKUIFinderDocumentScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}]}]}]}