{"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIConfiguration"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUILicensePlateScannerConfiguration"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/defaultConfiguration"},{"type":"text","text":" class property to retrieve an instance and modify it as needed."}]}]}],"metadata":{"symbolKind":"class","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUILicensePlateScannerConfiguration"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKUILicensePlateScannerConfiguration","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerConfiguration"}],"role":"symbol"},"abstract":[{"type":"text","text":"This class describes the look and feel, the behavior and the textual contents of the detection RTU-UI screen for license plate scanner."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/init(json:partial:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/behaviorConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/textConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/uiConfiguration"],"generated":true,"anchor":"Instance-Properties"},{"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/defaultConfiguration"],"generated":true,"anchor":"Type-Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerconfiguration"]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerConfiguration/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)":{"abstract":[{"type":"text","text":"Designated initializer. Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration","isActive":true},{"type":"text","text":"."}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:cameraconfiguration:)","navigatorTitle":[{"kind":"identifier","text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","title":"init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"uiConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerUIConfiguration","kind":"typeIdentifier","text":"SBSDKUILicensePlateScannerUIConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerTextConfiguration","kind":"typeIdentifier","text":"SBSDKUILicensePlateScannerTextConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"behaviorConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerBehaviorConfiguration","kind":"typeIdentifier","text":"SBSDKUILicensePlateScannerBehaviorConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration","kind":"typeIdentifier","text":"SBSDKUICameraConfiguration"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerConfiguration/uiConfiguration":{"title":"uiConfiguration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uiConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerUIConfiguration","text":"SBSDKUILicensePlateScannerUIConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"uiConfiguration"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/uiConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerconfiguration\/uiconfiguration","kind":"symbol","abstract":[{"type":"text","text":"The user interface sub-configuration."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerConfiguration/init()":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerconfiguration\/init()","kind":"symbol","role":"symbol","title":"init()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[{"text":"Convenience initializer.","type":"text"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIConfiguration":{"title":"SBSDKUIConfiguration","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuiconfiguration","navigatorTitle":[{"text":"SBSDKUIConfiguration","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"The general configuration class for all RTU-UI components."}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerConfiguration/init(json:partial:)":{"title":"init(json:partial:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/init(json:partial:)","navigatorTitle":[{"kind":"identifier","text":"initWithJson:partial:"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerconfiguration\/init(json:partial:)","kind":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"json"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"partial"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerConfiguration/behaviorConfiguration":{"kind":"symbol","navigatorTitle":[{"text":"behaviorConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/behaviorConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerconfiguration\/behaviorconfiguration","type":"topic","abstract":[{"type":"text","text":"The configuration controlling the scanning screens behavior."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"behaviorConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerBehaviorConfiguration","text":"SBSDKUILicensePlateScannerBehaviorConfiguration","kind":"typeIdentifier"}],"title":"behaviorConfiguration"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration","title":"SBSDKUILicensePlateScannerConfiguration","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerconfiguration","navigatorTitle":[{"text":"SBSDKUILicensePlateScannerConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUILicensePlateScannerConfiguration","kind":"identifier"}],"abstract":[{"text":"This class describes the look and feel, the behavior and the textual contents of the detection RTU-UI screen for license plate scanner.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerConfiguration/defaultConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerconfiguration\/defaultconfiguration","abstract":[{"type":"text","text":"The default configuration."}],"navigatorTitle":[{"text":"defaultConfiguration","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerConfiguration","text":"SBSDKUILicensePlateScannerConfiguration","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/defaultConfiguration","title":"defaultConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerConfiguration/textConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerconfiguration\/textconfiguration","title":"textConfiguration","abstract":[{"type":"text","text":"The configuration for displayed texts."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/textConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUILicensePlateScannerTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerTextConfiguration"}],"type":"topic","navigatorTitle":[{"text":"textConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKUILicensePlateScannerConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerConfiguration"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUILicensePlateScannerConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/behaviorConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/textConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/uiConfiguration"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/init(json:partial:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)"],"generated":true,"title":"Instance Methods"},{"anchor":"Type-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/defaultConfiguration"],"generated":true,"title":"Type Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIConfiguration"],"kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUILicensePlateScannerConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIConfiguration","text":"SBSDKUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIConfiguration"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)\/title","value":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration~1uiConfiguration\/title","value":"uiConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration~1uiConfiguration\/fragments","value":[{"text":"uiConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIConfiguration\/title","value":"SBSDKUIConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration~1init(json:partial:)\/title","value":"initWithJson:partial:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration~1init(json:partial:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithJson:partial:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration~1behaviorConfiguration\/title","value":"behaviorConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration~1behaviorConfiguration\/fragments","value":[{"kind":"identifier","text":"behaviorConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration\/title","value":"SBSDKUILicensePlateScannerConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration\/navigatorTitle","value":[{"text":"SBSDKUILicensePlateScannerConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration~1defaultConfiguration\/title","value":"defaultConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration~1defaultConfiguration\/fragments","value":[{"text":"defaultConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration~1textConfiguration\/title","value":"textConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration~1textConfiguration\/fragments","value":[{"text":"textConfiguration","kind":"identifier"}],"op":"replace"}]}]}