{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/dpi","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/jpegQuality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/ocrConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageFitMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageOrientation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageSize","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pdfAttributes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/resample"],"anchor":"Instance-Properties","title":"Instance Properties"}],"metadata":{"roleHeading":"Class","title":"SBSDKPDFRendererOptions","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRendererOptions","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererOptions"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFRendererOptions"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"class"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPDFRendererOptions"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions","interfaceLanguage":"swift"},"abstract":[{"text":"A class to describe the options being passed to PDF rendering API.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/pdfAttributes":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/pdfattributes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pdfAttributes","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKPDFAttributes","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFAttributes"},{"text":"?","kind":"text"}],"role":"symbol","title":"pdfAttributes","abstract":[{"type":"text","text":"The PDF metadata attributes like title, author, creator, keywords etc."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"pdfAttributes"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pdfAttributes"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/pageFitMode":{"kind":"symbol","title":"pageFitMode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pageFitMode"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageFitMode","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/pagefitmode","abstract":[{"type":"text","text":"How to fit the image into the page. Only used if "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageSize","isActive":true,"type":"reference"},{"type":"text","text":" is not "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/custom","isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The image can either be stretched to fill the page,","type":"text"},{"type":"text","text":" "},{"text":"in one of three ways, or centered on the page without stretching.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageFitMode"},{"kind":"text","text":": "},{"text":"SBSDKPDFRendererPageFitMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageFitMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/pageSize":{"abstract":[{"type":"text","text":"The physical size of the page. If "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/custom","isActive":true},{"type":"text","text":", the page size will be set as the image size at given"},{"text":" ","type":"text"},{"text":"dpi.","type":"text"}],"type":"topic","title":"pageSize","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageSize","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/pagesize","navigatorTitle":[{"kind":"identifier","text":"pageSize"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"pageSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKPDFRendererPageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFRendererOptions"}],"navigatorTitle":[{"text":"SBSDKPDFRendererOptions","kind":"identifier"}],"title":"SBSDKPDFRendererOptions","type":"topic","abstract":[{"text":"A class to describe the options being passed to PDF rendering API.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/pageOrientation":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"pageOrientation","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageOrientation","text":"SBSDKPDFRendererPageOrientation"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/pageorientation","role":"symbol","kind":"symbol","abstract":[{"text":"The orientation of the pages rendered to the PDF.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"pageOrientation"}],"title":"pageOrientation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageOrientation"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageSize/custom":{"abstract":[{"type":"text","text":"Each page is as large as its image at 72 dpi."}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/custom","title":"SBSDKPDFRendererPageSize.custom","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/custom","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageSizeCustom"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/resample":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/resample","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/resample","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resample"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"resample"}],"type":"topic","title":"resample","abstract":[{"type":"text","text":"If set to "},{"code":"True","type":"codeVoice"},{"type":"text","text":" downscales the images to match the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/dpi","isActive":true,"type":"reference"},{"text":" setting before adding it to the PDF if","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the calculated image DPI after stretching is greater than "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/dpi","type":"reference","isActive":true},{"text":". This slows down the PDF generation but results in smaller PDFs.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/jpegQuality":{"abstract":[{"text":"The JPEG quality for images in the range 0-100, where 0 means lowest quality and smallest size, and 100 means highest quality and largest size.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Applies only if "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/resample"},{"text":" is set to ","type":"text"},{"code":"True","type":"codeVoice"},{"type":"text","text":"."}],"title":"jpegQuality","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/jpegQuality","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"jpegQuality"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpegQuality"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/jpegquality","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode/none":{"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKPDFRendererPageFitModeNone","kind":"identifier"}],"title":"SBSDKPDFRendererPageFitMode.none","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/none","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/none"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:)":{"title":"init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"pageSize","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize","text":"SBSDKPDFRendererPageSize","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"pageFitMode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageFitMode","kind":"typeIdentifier","text":"SBSDKPDFRendererPageFitMode"},{"text":", ","kind":"text"},{"text":"pageOrientation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKPDFRendererPageOrientation","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageOrientation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dpi"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resample"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"jpegQuality","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ocrConfiguration"},{"kind":"text","text":": "},{"text":"SBSDKOpticalCharacterRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"pdfAttributes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFAttributes","kind":"typeIdentifier","text":"SBSDKPDFAttributes"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:)","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/init(pagesize:pagefitmode:pageorientation:dpi:resample:jpegquality:ocrconfiguration:pdfattributes:)","abstract":[{"type":"text","text":"Designated initializer."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/init()":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/init()","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/init()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[{"type":"text","text":"Default initializer."}],"title":"init()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/dpi":{"abstract":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/dpi","isActive":true,"type":"reference"},{"type":"text","text":" parameter has two different meanings depending on the value of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageSize","isActive":true},{"text":" and","type":"text"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageFitMode","isActive":true},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageSize","isActive":true},{"type":"text","text":" is set to "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/custom","type":"reference"},{"type":"text","text":"or "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageFitMode","isActive":true,"type":"reference"},{"text":" is set to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/none"},{"text":",","type":"text"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/dpi","isActive":true},{"text":" is the conversion ratio used to convert from units of pixels to physical inches when adding images to the PDF.","type":"text"}],"title":"dpi","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/dpi","type":"topic","kind":"symbol","navigatorTitle":[{"text":"dpi","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dpi","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/dpi","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/ocrConfiguration":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ocrConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration","text":"SBSDKOpticalCharacterRecognizerConfiguration"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"type":"text","text":"The configuration of the optical character recognition and HOCR when rendering a PDF."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/ocrConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/ocrconfiguration","title":"ocrConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ocrConfiguration"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKPDFRendererOptions"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"SBSDKPDFRendererOptions","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPDFRendererOptions"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/dpi","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/jpegQuality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/ocrConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageFitMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageOrientation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageSize","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pdfAttributes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/resample"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:)"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKPDFRendererOptions","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pdfAttributes\/title","op":"replace","value":"pdfAttributes"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pdfAttributes\/fragments","op":"replace","value":[{"text":"pdfAttributes","kind":"identifier"}]},{"value":"pageFitMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pageFitMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pageFitMode\/fragments","value":[{"text":"pageFitMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pageSize\/title","op":"replace","value":"pageSize"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pageSize\/fragments","value":[{"text":"pageSize","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKPDFRendererOptions","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/fragments","value":[{"text":"SBSDKPDFRendererOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/navigatorTitle","value":[{"text":"SBSDKPDFRendererOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pageOrientation\/title","value":"pageOrientation","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pageOrientation\/fragments","op":"replace","value":[{"text":"pageOrientation","kind":"identifier"}]},{"value":"SBSDKPDFRendererPageSizeCustom","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize~1custom\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize~1custom\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFRendererPageSizeCustom"}]},{"value":"resample","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1resample\/title"},{"value":[{"text":"resample","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1resample\/fragments"},{"op":"replace","value":"jpegQuality","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1jpegQuality\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1jpegQuality\/fragments","value":[{"text":"jpegQuality","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKPDFRendererPageFitModeNone","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode~1none\/title"},{"value":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitModeNone"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode~1none\/fragments"},{"value":"initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:pdfAttributes:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1init()\/title","value":"init"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1init()\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1dpi\/title","value":"dpi","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1dpi\/fragments","value":[{"text":"dpi","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1ocrConfiguration\/title","op":"replace","value":"ocrConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1ocrConfiguration\/fragments","value":[{"text":"ocrConfiguration","kind":"identifier"}]}]}]}