{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype"]}],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldType"}],"title":"SBSDKGenericDocumentCommonFieldType","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldType"}],"symbolKind":"enum","roleHeading":"Enumeration","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKGenericDocumentCommonFieldType","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"type":"text","text":"Common field types."}],"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/accountNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/address","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/birthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/birthplace","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/cardAccessNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/countryCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/expiryDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/eyeColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/gender","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/givenNames","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/height","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/id","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/issueDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/issuingAuthority","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/maidenName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/mrz","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/name","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/nationality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/none","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/photo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/placeOfIssue","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/pseudonym","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/remarks","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/routingNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/signature","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/surname","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/titleType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/validFromDate"],"generated":true},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/init(rawValue:)"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/RawRepresentable-Implementations"],"generated":true}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/countryCode":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/countryCode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"countryCode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeCountryCode"}],"abstract":[{"type":"text","text":"Country code (ISO-3166 Alpha-3) field."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/countrycode","title":"SBSDKGenericDocumentCommonFieldType.countryCode","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/mrz":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeMrz"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/mrz","title":"SBSDKGenericDocumentCommonFieldType.mrz","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrz"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/mrz","role":"symbol","abstract":[{"text":"MRZ field.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/routingNumber":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/routingNumber","type":"topic","title":"SBSDKGenericDocumentCommonFieldType.routingNumber","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/routingnumber","abstract":[{"text":"Check routing number.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"routingNumber"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeRoutingNumber"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/pseudonym":{"title":"SBSDKGenericDocumentCommonFieldType.pseudonym","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pseudonym"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/pseudonym","abstract":[{"type":"text","text":"Pseudonym field."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/pseudonym","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypePseudonym"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/address":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"address"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/address","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/address","title":"SBSDKGenericDocumentCommonFieldType.address","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeAddress"}],"abstract":[{"text":"Address field.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/init(rawValue:)":{"title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/init(rawValue:)","role":"symbol","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/init(rawvalue:)"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/remarks":{"abstract":[{"text":"Remarks field in the identity document.","type":"text"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypeRemarks","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/remarks","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/remarks","type":"topic","title":"SBSDKGenericDocumentCommonFieldType.remarks","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remarks","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/cardAccessNumber":{"title":"SBSDKGenericDocumentCommonFieldType.cardAccessNumber","kind":"symbol","abstract":[{"text":"Card access number field.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/cardAccessNumber","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/cardaccessnumber","navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypeCardAccessNumber","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardAccessNumber","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"abstract":[{"text":"Common field types.","type":"text"}],"kind":"symbol","title":"SBSDKGenericDocumentCommonFieldType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/nationality":{"role":"symbol","kind":"symbol","title":"SBSDKGenericDocumentCommonFieldType.nationality","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/nationality","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/nationality","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nationality"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeNationality"}],"abstract":[{"type":"text","text":"Person nationality field."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/Equatable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/equatable-implementations","kind":"article","type":"topic","abstract":[],"role":"collectionGroup"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/issuingAuthority":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeIssuingAuthority"}],"abstract":[{"text":"Document issuing authority field.","type":"text"}],"role":"symbol","title":"SBSDKGenericDocumentCommonFieldType.issuingAuthority","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/issuingauthority","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/issuingAuthority","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingAuthority"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/accountNumber":{"navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypeAccountNumber","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/accountNumber","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Check account number."}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accountNumber","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/accountnumber","title":"SBSDKGenericDocumentCommonFieldType.accountNumber"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/height":{"type":"topic","abstract":[{"type":"text","text":"Person height field."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/height","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/height","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"}],"kind":"symbol","role":"symbol","title":"SBSDKGenericDocumentCommonFieldType.height","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeHeight"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/titleType":{"type":"topic","abstract":[{"text":"Type of the title field in the identity document.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/titleType","title":"SBSDKGenericDocumentCommonFieldType.titleType","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeTitleType"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/titletype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/birthDate":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/birthdate","abstract":[{"text":"Person birth date field.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/birthDate","navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypeBirthDate","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"birthDate","kind":"identifier"}],"type":"topic","title":"SBSDKGenericDocumentCommonFieldType.birthDate","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/id":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypeId","kind":"identifier"}],"title":"SBSDKGenericDocumentCommonFieldType.id","abstract":[{"text":"Document ID.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/id","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/id","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/givenNames":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/givennames","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenNames"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/givenNames","title":"SBSDKGenericDocumentCommonFieldType.givenNames","abstract":[{"text":"Person given names field.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeGivenNames"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/surname":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/surname","kind":"symbol","type":"topic","title":"SBSDKGenericDocumentCommonFieldType.surname","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"surname"}],"abstract":[{"text":"Person surname field.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/surname","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeSurname"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/RawRepresentable-Implementations":{"abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/rawrepresentable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/expiryDate":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/expirydate","navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypeExpiryDate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/expiryDate","role":"symbol","title":"SBSDKGenericDocumentCommonFieldType.expiryDate","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expiryDate","kind":"identifier"}],"abstract":[{"type":"text","text":"Document expiry date field."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/placeOfIssue":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/placeofissue","title":"SBSDKGenericDocumentCommonFieldType.placeOfIssue","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/placeOfIssue","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeOfIssue","kind":"identifier"}],"abstract":[{"text":"Place of issue for the identity card.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypePlaceOfIssue","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/maidenName":{"kind":"symbol","role":"symbol","title":"SBSDKGenericDocumentCommonFieldType.maidenName","abstract":[{"text":"Person maiden name field.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/maidenName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maidenName"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeMaidenName"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/maidenname"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/none":{"abstract":[{"text":"Not valid type.","type":"text"}],"type":"topic","title":"SBSDKGenericDocumentCommonFieldType.none","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeNone"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/none","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/name":{"role":"symbol","title":"SBSDKGenericDocumentCommonFieldType.name","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/name","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeName"}],"kind":"symbol","abstract":[{"text":"Full name field.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/name","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/issueDate":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/issueDate","type":"topic","role":"symbol","abstract":[{"text":"Document issue date field.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issueDate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/issuedate","title":"SBSDKGenericDocumentCommonFieldType.issueDate","navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypeIssueDate","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/eyeColor":{"title":"SBSDKGenericDocumentCommonFieldType.eyeColor","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeColor"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/eyeColor","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/eyecolor","abstract":[{"type":"text","text":"Person eye color field."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeEyeColor"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/photo":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypePhoto"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/photo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"photo"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/photo","role":"symbol","abstract":[{"type":"text","text":"Photo field."}],"title":"SBSDKGenericDocumentCommonFieldType.photo","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/birthplace":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/birthplace","title":"SBSDKGenericDocumentCommonFieldType.birthplace","role":"symbol","abstract":[{"text":"Person birthplace field.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/birthplace","type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypeBirthplace","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"birthplace","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/signature":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"signature"}],"type":"topic","abstract":[{"text":"Signature field.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/signature","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/signature","role":"symbol","title":"SBSDKGenericDocumentCommonFieldType.signature","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeSignature"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/validFromDate":{"kind":"symbol","title":"SBSDKGenericDocumentCommonFieldType.validFromDate","type":"topic","abstract":[{"type":"text","text":"Date of start of validity field."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/validfromdate","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validFromDate","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypeValidFromDate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/validFromDate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/gender":{"type":"topic","abstract":[{"text":"Gender field.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gender"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/gender","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/gender","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeGender"}],"title":"SBSDKGenericDocumentCommonFieldType.gender"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKGenericDocumentCommonFieldType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldType"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/accountNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/address","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/birthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/birthplace","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/cardAccessNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/countryCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/expiryDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/eyeColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/gender","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/givenNames","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/height","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/id","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/issueDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/issuingAuthority","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/maidenName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/mrz","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/name","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/nationality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/none","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/photo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/placeOfIssue","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/pseudonym","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/remarks","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/routingNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/signature","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/surname","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/titleType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/validFromDate"],"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKGenericDocumentCommonFieldTypeCountryCode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1countryCode\/title","op":"replace"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypeCountryCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1countryCode\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeMrz","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1mrz\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypeMrz","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1mrz\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeRoutingNumber","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1routingNumber\/title"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeRoutingNumber"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1routingNumber\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypePseudonym","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1pseudonym\/title"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypePseudonym"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1pseudonym\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeAddress","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1address\/title"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeAddress"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1address\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeRemarks","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1remarks\/title"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeRemarks"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1remarks\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeCardAccessNumber","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1cardAccessNumber\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypeCardAccessNumber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1cardAccessNumber\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType\/navigatorTitle"},{"value":"SBSDKGenericDocumentCommonFieldTypeNationality","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1nationality\/title"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeNationality"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1nationality\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeIssuingAuthority","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1issuingAuthority\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypeIssuingAuthority","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1issuingAuthority\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeAccountNumber","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1accountNumber\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypeAccountNumber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1accountNumber\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeHeight","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1height\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypeHeight","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1height\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeTitleType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1titleType\/title"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeTitleType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1titleType\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeBirthDate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1birthDate\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypeBirthDate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1birthDate\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeId","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1id\/title"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeId"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1id\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeGivenNames","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1givenNames\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypeGivenNames","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1givenNames\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeSurname","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1surname\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypeSurname","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1surname\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeExpiryDate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1expiryDate\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypeExpiryDate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1expiryDate\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypePlaceOfIssue","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1placeOfIssue\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypePlaceOfIssue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1placeOfIssue\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeMaidenName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1maidenName\/title"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeMaidenName"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1maidenName\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeNone","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1none\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypeNone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1none\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1name\/title"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeName"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1name\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeIssueDate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1issueDate\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypeIssueDate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1issueDate\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeEyeColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1eyeColor\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypeEyeColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1eyeColor\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypePhoto","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1photo\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypePhoto","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1photo\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeBirthplace","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1birthplace\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypeBirthplace","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1birthplace\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeSignature","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1signature\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypeSignature","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1signature\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeValidFromDate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1validFromDate\/title"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeValidFromDate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1validFromDate\/fragments"},{"value":"SBSDKGenericDocumentCommonFieldTypeGender","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1gender\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypeGender","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1gender\/fragments"}]}]}