{"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate\/mrzScannerController(_:didDetectMRZ:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate\/mrzScannerControllerShouldDetectMRZ(_:)"]}],"abstract":[{"type":"text","text":"The delegation protocol for the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","isActive":true},{"type":"text","text":" class."}],"relationshipsSections":[{"type":"conformingTypes","title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController"]}],"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Protocol","navigatorTitle":[{"text":"SBSDKMRZScannerViewControllerDelegate","kind":"identifier"}],"symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMRZScannerViewControllerDelegate","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKMRZScannerViewControllerDelegate","title":"SBSDKMRZScannerViewControllerDelegate"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZScannerViewControllerDelegate"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZScannerViewController"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller","title":"SBSDKMRZScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZScannerViewController"}],"abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan machine-readable zones."}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewControllerDelegate/mrzScannerController(_:didDetectMRZ:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate\/mrzScannerController(_:didDetectMRZ:)","title":"mrzScannerController(_:didDetectMRZ:)","abstract":[{"text":"Informs the delegate that the scanner has detected a machine-readable zone.","type":"text"}],"navigatorTitle":[{"text":"mrzScannerController:didDetectMRZ:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate\/mrzscannercontroller(_:diddetectmrz:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"mrzScannerController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMRZScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController"},{"text":", ","kind":"text"},{"text":"didDetectMRZ","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResult"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewController":{"kind":"symbol","type":"topic","title":"SBSDKUIMRZScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}],"abstract":[{"text":"A highly customizable camera-based view controller to detect machine readable zones.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewControllerDelegate":{"abstract":[{"type":"text","text":"The delegation protocol for the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","type":"reference","isActive":true},{"type":"text","text":" class."}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate","title":"SBSDKMRZScannerViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZScannerViewControllerDelegate"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZScannerViewControllerDelegate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewControllerDelegate/mrzScannerControllerShouldDetectMRZ(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate\/mrzscannercontrollershoulddetectmrz(_:)","navigatorTitle":[{"text":"mrzScannerControllerShouldDetectMRZ:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate\/mrzScannerControllerShouldDetectMRZ(_:)","type":"topic","required":true,"abstract":[{"text":"Asks the delegate if the scanner should detect machine-readable zones on the next video frame.","type":"text"},{"text":" ","type":"text"},{"text":"Optional.","type":"text"}],"kind":"symbol","role":"symbol","title":"mrzScannerControllerShouldDetectMRZ(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrzScannerControllerShouldDetectMRZ","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMRZScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKMRZScannerViewControllerDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKMRZScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKMRZScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate\/mrzScannerController(_:didDetectMRZ:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate\/mrzScannerControllerShouldDetectMRZ(_:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController"],"type":"conformingTypes"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZScannerViewControllerDelegate"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKMRZScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/title"},{"value":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/fragments"},{"value":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/navigatorTitle"},{"value":"mrzScannerController:didDetectMRZ:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate~1mrzScannerController(_:didDetectMRZ:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"mrzScannerController:didDetectMRZ:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate~1mrzScannerController(_:didDetectMRZ:)\/fragments"},{"value":"SBSDKUIMRZScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/title"},{"value":[{"text":"SBSDKUIMRZScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/fragments"},{"value":[{"text":"SBSDKUIMRZScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/navigatorTitle"},{"value":"SBSDKMRZScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate\/title"},{"value":[{"text":"SBSDKMRZScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate\/fragments"},{"value":[{"text":"SBSDKMRZScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate\/navigatorTitle"},{"value":"mrzScannerControllerShouldDetectMRZ:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate~1mrzScannerControllerShouldDetectMRZ(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mrzScannerControllerShouldDetectMRZ:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate~1mrzScannerControllerShouldDetectMRZ(_:)\/fragments"}]}]}