{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetector"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetector"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"topicSections":[{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/init(mode:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/acceptedAngleScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/acceptedBrightnessThreshold","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/acceptedSizeScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentAngleScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentDistanceScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentHeightScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentSizeScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentTotalScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentWidthScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectedHorizontalEdges","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectedVerticalEdges","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectionMetrics","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectorMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/preferredAspectRatios","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/requiredAspectRatios"],"anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-101hc","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-4gmrq","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-10171","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-21ing","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/resetSmoothingData()"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/defaultDetectorMode"],"anchor":"Type-Properties","generated":true,"title":"Type Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/setDefaultDetectorMode(_:)"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"SBSDKDocumentDetector","modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetector"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDetector","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetector"},"sections":[],"abstract":[{"text":"A class to detect a document’s outline polygon in a UIImage or CMSampleBufferRef.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetector"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/acceptedAngleScore":{"title":"acceptedAngleScore","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/acceptedAngleScore","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/acceptedanglescore","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedAngleScore"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"abstract":[{"type":"text","text":"The minimum score in percent (0 - 100) of the perspective distortion to accept a detected document."}],"role":"symbol","navigatorTitle":[{"text":"acceptedAngleScore","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/detectedVerticalEdges":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectedVerticalEdges","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectedVerticalEdges","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygonEdge","text":"SBSDKPolygonEdge"},{"text":"]?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"detectedVerticalEdges","kind":"identifier"}],"title":"detectedVerticalEdges","abstract":[{"type":"text","text":"Array of all detected vertical edges during last detection. Can be used for manual magnetic cropping."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/detectedverticaledges","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-21ing":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/detectphotopolygon(on:visibleimagerect:smoothingenabled:)-21ing","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"detectPhotoPolygon","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"visibleImageRect","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"text":"smoothingEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult"},{"text":"?","kind":"text"}],"title":"detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-21ing","navigatorTitle":[{"text":"detectPhotoPolygonOnSampleBuffer:visibleImageRect:smoothingEnabled:","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Executes an edge detection algorithm on the given sample buffer and returns"},{"type":"text","text":" "},{"type":"text","text":"a polygon describing the extends of the detected photos box."},{"text":" ","type":"text"},{"type":"text","text":"For a short period of time the uncompressed image data is hold twice in memory. Use with attention."}]},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/init(mode:)":{"title":"init(mode:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithMode:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/init(mode:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"mode"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDetectorMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectorMode","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Designated initialiizer."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/init(mode:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-4gmrq":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/detectdocumentpolygon(on:visibleimagerect:smoothingenabled:uselivedetectionparameters:)-4gmrq","title":"detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)","abstract":[{"text":"Executes an edge detection algorithm on the given sample buffer and returns","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"a polygon describing the extends of the detected documents box."},{"type":"text","text":" "},{"text":"For a short period of time the uncompressed image data is hold twice in memory. Use with attention.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-4gmrq","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectDocumentPolygon","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"visibleImageRect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"smoothingEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useLiveDetectionParameters"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"detectDocumentPolygonOnSampleBuffer:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectorMode":{"title":"SBSDKDocumentDetectorMode","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectormode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentDetectorMode"}],"abstract":[{"text":"The mode of the document detector: standard or machine-learning-based.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectorMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/currentWidthScore":{"abstract":[{"type":"text","text":"The width score of the latest detected polygon (0 - 100). Part of the size score."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/currentwidthscore","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentWidthScore"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"role":"symbol","kind":"symbol","title":"currentWidthScore","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentWidthScore","navigatorTitle":[{"kind":"identifier","text":"currentWidthScore"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectorMode/standard":{"type":"topic","title":"SBSDKDocumentDetectorMode.standard","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode\/standard","abstract":[{"text":"The standard detection mode.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"standard"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectormode\/standard","navigatorTitle":[{"text":"SBSDKDocumentDetectorModeStandard","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/detectorMode":{"title":"detectorMode","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectorMode","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/detectormode","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectorMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectorMode","text":"SBSDKDocumentDetectorMode","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The current mode of the detector: "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode\/standard","type":"reference"},{"text":" or ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode\/machineLearning","type":"reference"},{"type":"text","text":" based."}],"role":"symbol","navigatorTitle":[{"text":"detectorMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/setDefaultDetectorMode(_:)":{"abstract":[{"type":"text","text":"Set default detector mode. Unless the new instance of detector is initialized with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/init(mode:)"},{"text":" initializer, this new instance will have this mode set.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/setdefaultdetectormode(_:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDefaultDetectorMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectorMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectorMode"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","title":"setDefaultDetectorMode(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/setDefaultDetectorMode(_:)","navigatorTitle":[{"text":"setDefaultDetectorMode:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/init":{"kind":"symbol","title":"init","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/init","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/currentTotalScore":{"navigatorTitle":[{"kind":"identifier","text":"currentTotalScore"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentTotalScore","abstract":[{"text":"The total score of the latest detected polygon (0 - 100).","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentTotalScore","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/currenttotalscore","title":"currentTotalScore","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-10171":{"abstract":[{"text":"Executes an edge detection algorithm on the given image and returns","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"a polygon describing the extends of the detected photos box."},{"text":" ","type":"text"},{"type":"text","text":"For a short period of time the uncompressed image data is hold twice in memory. Use with attention."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/detectphotopolygon(on:visibleimagerect:smoothingenabled:)-10171","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectPhotoPolygon"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"visibleImageRect"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"smoothingEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","title":"detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-10171","navigatorTitle":[{"text":"detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/detectedHorizontalEdges":{"title":"detectedHorizontalEdges","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectedHorizontalEdges","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/detectedhorizontaledges","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectedHorizontalEdges"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygonEdge","text":"SBSDKPolygonEdge","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"abstract":[{"text":"Array of all detected horizontal edges during last detection. Can be used for manual magnetic cropping.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"detectedHorizontalEdges"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-101hc":{"title":"detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-101hc","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/detectdocumentpolygon(on:visibleimagerect:smoothingenabled:uselivedetectionparameters:)-101hc","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectDocumentPolygon"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":", ","kind":"text"},{"text":"visibleImageRect","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"smoothingEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"useLiveDetectionParameters","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Executes an edge detection algorithm on the given image and returns"},{"text":" ","type":"text"},{"text":"a polygon describing the extends of the detected documents box.","type":"text"},{"type":"text","text":" "},{"text":"For a short period of time the uncompressed image data is hold twice in memory. Use with attention.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/detectionMetrics":{"abstract":[{"type":"text","text":"The metrics of the last detection or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionMetrics","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionMetrics","text":"SBSDKDocumentDetectionMetrics"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"detectionMetrics","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectionMetrics","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/detectionmetrics","title":"detectionMetrics"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/acceptedBrightnessThreshold":{"abstract":[{"type":"text","text":"The brightness threshold to accept a detected document in the range of 0 (very dark) to 255 (very bright)."},{"text":" ","type":"text"},{"type":"text","text":"If  the average brightness value of the detectors input image is below this value, the status of the detection will be set to"},{"text":" ","type":"text"},{"type":"codeVoice","code":"SBSDKDocumentDetectionStatus\/error_Brightness"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/acceptedbrightnessthreshold","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedBrightnessThreshold"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","title":"acceptedBrightnessThreshold","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/acceptedBrightnessThreshold","navigatorTitle":[{"text":"acceptedBrightnessThreshold","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetector"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetector"}],"abstract":[{"text":"A class to detect a document’s outline polygon in a UIImage or CMSampleBufferRef.","type":"text"}],"kind":"symbol","title":"SBSDKDocumentDetector","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/requiredAspectRatios":{"title":"requiredAspectRatios","abstract":[{"type":"text","text":"Required aspect ratios for detector."},{"text":" ","type":"text"},{"text":"If not ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" or empty, only polygons resulting in crops with one of the required aspect ratios will be detected.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"requiredAspectRatios"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/requiredaspectratios","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/requiredAspectRatios","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"requiredAspectRatios","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio"},{"text":"]?","kind":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/currentDistanceScore":{"title":"currentDistanceScore","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentDistanceScore","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/currentdistancescore","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentDistanceScore"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"abstract":[{"text":"The distance-from-center score of the latest detected polygon (0 - 100). Part of the total score.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"currentDistanceScore"}]},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/currentHeightScore":{"title":"currentHeightScore","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentHeightScore","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/currentheightscore","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentHeightScore","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The height score of the latest detected polygon (0 - 100). Part of the size score."}],"role":"symbol","navigatorTitle":[{"text":"currentHeightScore","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/resetSmoothingData()":{"title":"resetSmoothingData()","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/resetSmoothingData()","abstract":[{"text":"Resets the smoothingData. If smoothing is enabled the polygon detector smoothes the result with results from","type":"text"},{"type":"text","text":" "},{"text":"previous detections. You should call this method once per second or if the device has been moved.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/resetsmoothingdata()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resetSmoothingData"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"resetSmoothingData"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/currentSizeScore":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentSizeScore","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/currentsizescore","abstract":[{"type":"text","text":"The size score of the latest detected polygon (0 - 100). Part of the total score."}],"title":"currentSizeScore","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentSizeScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"currentSizeScore","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/preferredAspectRatios":{"kind":"symbol","abstract":[{"type":"text","text":"Preferred aspect ratios for detector."},{"type":"text","text":" "},{"text":"If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" or empty, aspect ratio will not take part in defining best document polygon.","type":"text"},{"text":" ","type":"text"},{"text":"If set, polygons with set aspect ratio will be more preferable.","type":"text"}],"type":"topic","title":"preferredAspectRatios","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/preferredaspectratios","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"preferredAspectRatios","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKAspectRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio"},{"kind":"text","text":"]?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/preferredAspectRatios","navigatorTitle":[{"kind":"identifier","text":"preferredAspectRatios"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/acceptedSizeScore":{"title":"acceptedSizeScore","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/acceptedSizeScore","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/acceptedsizescore","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"acceptedSizeScore","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[{"text":"The minimum size in percent (0 - 100) of the screen size to accept a detected document.","type":"text"},{"type":"text","text":" "},{"text":"It is sufficient that height or width match the score.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"acceptedSizeScore","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/currentAngleScore":{"title":"currentAngleScore","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentAngleScore","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/currentanglescore","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"currentAngleScore","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"abstract":[{"text":"The angles score of the latest detected polygon (0 - 100). Part of the total score.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"currentAngleScore","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/defaultDetectorMode":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/defaultdetectormode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/defaultDetectorMode","title":"defaultDetectorMode","kind":"symbol","type":"topic","abstract":[{"text":"Default ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode","isActive":true,"type":"reference"},{"text":" parameter value.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"defaultDetectorMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDetectorMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectorMode"}],"navigatorTitle":[{"text":"defaultDetectorMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectorMode/machineLearning":{"type":"topic","title":"SBSDKDocumentDetectorMode.machineLearning","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode\/machineLearning","abstract":[{"text":"The new machine-learning based detection mode.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"machineLearning","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectormode\/machinelearning","navigatorTitle":[{"text":"SBSDKDocumentDetectorModeMachineLearning","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"SBSDKDocumentDetector","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetector"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"text":"SBSDKDocumentDetector","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/acceptedAngleScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/acceptedBrightnessThreshold","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/acceptedSizeScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentAngleScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentDistanceScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentHeightScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentSizeScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentTotalScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentWidthScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectedHorizontalEdges","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectedVerticalEdges","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectionMetrics","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectorMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/preferredAspectRatios","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/requiredAspectRatios"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-101hc","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-4gmrq","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-10171","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-21ing","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/init","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/init(mode:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/resetSmoothingData()"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/defaultDetectorMode"],"generated":true,"anchor":"Type-Properties"},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/setDefaultDetectorMode(_:)"],"anchor":"Type-Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentDetector"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"acceptedAngleScore","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1acceptedAngleScore\/title"},{"value":[{"text":"acceptedAngleScore","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1acceptedAngleScore\/fragments"},{"value":"detectedVerticalEdges","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectedVerticalEdges\/title"},{"value":[{"text":"detectedVerticalEdges","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectedVerticalEdges\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-21ing\/title","op":"replace","value":"detectPhotoPolygonOnSampleBuffer:visibleImageRect:smoothingEnabled:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-21ing\/fragments","value":[{"text":"- ","kind":"text"},{"text":"detectPhotoPolygonOnSampleBuffer:visibleImageRect:smoothingEnabled:","kind":"identifier"}]},{"value":"initWithMode:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1init(mode:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"initWithMode:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1init(mode:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-4gmrq\/title","op":"replace","value":"detectDocumentPolygonOnSampleBuffer:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:"},{"value":[{"kind":"text","text":"- "},{"text":"detectDocumentPolygonOnSampleBuffer:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-4gmrq\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode\/title","value":"SBSDKDocumentDetectorMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetectorMode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode\/navigatorTitle","value":[{"text":"SBSDKDocumentDetectorMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1currentWidthScore\/title","value":"currentWidthScore"},{"value":[{"kind":"identifier","text":"currentWidthScore"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1currentWidthScore\/fragments"},{"value":"SBSDKDocumentDetectorModeStandard","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode~1standard\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode~1standard\/fragments","value":[{"text":"SBSDKDocumentDetectorModeStandard","kind":"identifier"}]},{"op":"replace","value":"detectorMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectorMode\/title"},{"value":[{"text":"detectorMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectorMode\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1setDefaultDetectorMode(_:)\/title","value":"setDefaultDetectorMode:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setDefaultDetectorMode:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1setDefaultDetectorMode(_:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1currentTotalScore\/title","op":"replace","value":"currentTotalScore"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1currentTotalScore\/fragments","value":[{"kind":"identifier","text":"currentTotalScore"}]},{"value":"detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-10171\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-10171\/fragments"},{"value":"detectedHorizontalEdges","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectedHorizontalEdges\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectedHorizontalEdges\/fragments","value":[{"text":"detectedHorizontalEdges","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-101hc\/title","op":"replace","value":"detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-101hc\/fragments","value":[{"text":"- ","kind":"text"},{"text":"detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectionMetrics\/title","value":"detectionMetrics"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectionMetrics\/fragments","op":"replace","value":[{"kind":"identifier","text":"detectionMetrics"}]},{"value":"acceptedBrightnessThreshold","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1acceptedBrightnessThreshold\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1acceptedBrightnessThreshold\/fragments","value":[{"text":"acceptedBrightnessThreshold","kind":"identifier"}],"op":"replace"},{"value":"SBSDKDocumentDetector","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/title"},{"value":[{"text":"SBSDKDocumentDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1requiredAspectRatios\/title","op":"replace","value":"requiredAspectRatios"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1requiredAspectRatios\/fragments","value":[{"kind":"identifier","text":"requiredAspectRatios"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1currentDistanceScore\/title","op":"replace","value":"currentDistanceScore"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1currentDistanceScore\/fragments","value":[{"kind":"identifier","text":"currentDistanceScore"}],"op":"replace"},{"value":"currentHeightScore","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1currentHeightScore\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1currentHeightScore\/fragments","value":[{"text":"currentHeightScore","kind":"identifier"}]},{"op":"replace","value":"resetSmoothingData","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1resetSmoothingData()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"resetSmoothingData"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1resetSmoothingData()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1currentSizeScore\/title","value":"currentSizeScore"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1currentSizeScore\/fragments","value":[{"text":"currentSizeScore","kind":"identifier"}]},{"op":"replace","value":"preferredAspectRatios","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1preferredAspectRatios\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1preferredAspectRatios\/fragments","value":[{"text":"preferredAspectRatios","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1acceptedSizeScore\/title","value":"acceptedSizeScore"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1acceptedSizeScore\/fragments","value":[{"text":"acceptedSizeScore","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1currentAngleScore\/title","value":"currentAngleScore"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1currentAngleScore\/fragments","value":[{"text":"currentAngleScore","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1defaultDetectorMode\/title","op":"replace","value":"defaultDetectorMode"},{"op":"replace","value":[{"kind":"identifier","text":"defaultDetectorMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1defaultDetectorMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode~1machineLearning\/title","value":"SBSDKDocumentDetectorModeMachineLearning"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode~1machineLearning\/fragments","value":[{"text":"SBSDKDocumentDetectorModeMachineLearning","kind":"identifier"}]}]}]}