{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedPage","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedPage","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKScannedPage","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"class","title":"SBSDKScannedPage"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"text":"A scanned page (","type":"text"},{"code":"SBSDKScannedPage","type":"codeVoice"},{"text":") is a representation of a scanned documents page in digital form.","type":"text"},{"text":" ","type":"text"},{"text":"Each page consists of an original image of the scan, various editing properties like cropping polygon, rotation and filters, some metadata properties like the document detection status and the document quality analyzer result and a number of processed images in different stages.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/documentDetectionStatus","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/documentImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/documentImagePreview","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/documentImagePreviewURI","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/documentImageURI","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/documentQuality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/filters","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/originalImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/originalImageURI","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/polygon","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/rotation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/source","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/unfilteredDocumentImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/unfilteredDocumentImageURI","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/uuid"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/addObserver(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/apply(rotation:polygon:filters:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/applyAsync(rotation:polygon:filters:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/removeObserver(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/toJson()"]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscannedpage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscannedpage"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScannedPage"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"The editing properties of each page can be used to manipulate its final document image in a non-destructive way.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The operations are applied in the following order:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Rotate the original image and save it as the original image. The rotation flag is reset after the rotation operation has been executed."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Crop the original image and save it it as the unfiltered document image."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Run filters on the unfiltered document image, apply the size limit and save it as the document image.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Create screen-sized preview images of original, unfiltered document and document images."}]}]}]},{"type":"paragraph","inlineContent":[{"text":"For performance reasons all 6 images are cached to the disk. The editing operations of all pages are dispatched to a serial queue to avoid race-conditions and memory pressure.","type":"text"}]}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/removeObserver(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/removeobserver(_:)","abstract":[{"text":"Removes an observer from the receiver.","type":"text"}],"role":"symbol","title":"removeObserver(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/removeObserver(_:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeObserver","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKScannedPageObserver","text":"SBSDKScannedPageObserver"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"removeObserver:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/originalImageURI":{"kind":"symbol","title":"originalImageURI","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/originalimageuri","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalImageURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The percent-encoded file URL of the receivers rotated original image."},{"type":"text","text":" "},{"type":"text","text":"Warning: Never delete or manipulate the data at this URL or of the folders within this URL. This will lead to unpredictable behaviour and corrupted data."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"originalImageURI"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/originalImageURI"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/toJson()":{"abstract":[{"type":"text","text":"The pretty-printed JSON representation of the receiver."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/toJson()","kind":"symbol","role":"symbol","title":"toJson()","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/tojson()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"toJson"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/unfilteredDocumentImage":{"url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/unfiltereddocumentimage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/unfilteredDocumentImage","abstract":[{"type":"text","text":"The receivers rotated and cropped unfiltered document image."}],"kind":"symbol","role":"symbol","title":"unfilteredDocumentImage","navigatorTitle":[{"text":"unfilteredDocumentImage","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unfilteredDocumentImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/polygon":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/polygon","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/polygon","navigatorTitle":[{"kind":"identifier","text":"polygon"}],"type":"topic","title":"polygon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"}],"abstract":[{"text":"The polygon used to crop the receiver.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScannedPage"}],"title":"SBSDKScannedPage","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPage"}],"type":"topic","abstract":[{"type":"text","text":"A scanned page ("},{"type":"codeVoice","code":"SBSDKScannedPage"},{"type":"text","text":") is a representation of a scanned documents page in digital form."},{"type":"text","text":" "},{"type":"text","text":"Each page consists of an original image of the scan, various editing properties like cropping polygon, rotation and filters, some metadata properties like the document detection status and the document quality analyzer result and a number of processed images in different stages."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetector","kind":"identifier"}],"abstract":[{"type":"text","text":"A class to detect a document’s outline polygon in a UIImage or CMSampleBufferRef."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector","navigatorTitle":[{"text":"SBSDKDocumentDetector","kind":"identifier"}],"role":"symbol","title":"SBSDKDocumentDetector"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/originalImage":{"abstract":[{"type":"text","text":"The receivers rotated original image."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"originalImage","kind":"identifier"}],"type":"topic","title":"originalImage","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/originalimage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/originalImage","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"originalImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/filters":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"filters","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/filters","kind":"symbol","type":"topic","navigatorTitle":[{"text":"filters","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/filters","title":"filters","abstract":[{"type":"text","text":"The filters to be applied to the receiver."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/rotation":{"abstract":[{"type":"text","text":"The type of rotation to be applied to the receiver."}],"title":"rotation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageRotation","text":"SBSDKImageRotation"}],"navigatorTitle":[{"kind":"identifier","text":"rotation"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/rotation","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/rotation"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/uuid":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/uuid","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uuid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"uuid"}],"title":"uuid","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/uuid","role":"symbol","abstract":[{"type":"text","text":"The globally unique page identifier of the receiver. Readonly."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/source":{"title":"source","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/source","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/source","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageImageSource","text":"SBSDKPageImageSource","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The page source metadata of the receiver, where the original image of the receiver originates from."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzer":{"type":"topic","abstract":[{"text":"Analyzes the quality of a document on a still image.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzer"}],"title":"SBSDKDocumentQualityAnalyzer","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzer","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzer"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/applyAsync(rotation:polygon:filters:completion:)":{"title":"applyAsync(rotation:polygon:filters:completion:)","abstract":[{"type":"text","text":"Applies one or more editing operations on the page at once asynchronously and calls the completion block after finishing."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/applyAsync(rotation:polygon:filters:completion:)","navigatorTitle":[{"text":"applyAsyncWithRotation:polygon:filters:completion:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/applyasync(rotation:polygon:filters:completion:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyAsync","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rotation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRotation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageRotation"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"text":"?, ","kind":"text"},{"text":"filters","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"text":"]?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (() -> ())?)","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/unfilteredDocumentImageURI":{"type":"topic","title":"unfilteredDocumentImageURI","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/unfiltereddocumentimageuri","abstract":[{"type":"text","text":"The percent-encoded file URL of the receivers rotated and cropped unfiltered document image."},{"type":"text","text":" "},{"type":"text","text":"Warning: Never delete or manipulate the data at this URL or of the folders within this URL. This will lead to unpredictable behaviour and corrupted data."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/unfilteredDocumentImageURI","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unfilteredDocumentImageURI","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"unfilteredDocumentImageURI","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/hash":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/hash","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/hash","kind":"symbol","title":"hash","fragments":[{"text":"hash","kind":"identifier"}],"abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/addObserver(_:)":{"title":"addObserver(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/addObserver(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addObserver"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKScannedPageObserver","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKScannedPageObserver"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/addobserver(_:)","abstract":[{"text":"Adds an observer to the receiver.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"addObserver:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/apply(rotation:polygon:filters:)":{"kind":"symbol","type":"topic","abstract":[{"text":"Applies one or more editing operations on the page at once and waits for the completion.","type":"text"}],"title":"apply(rotation:polygon:filters:)","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/apply(rotation:polygon:filters:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apply","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rotation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRotation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageRotation"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"text":"?, ","kind":"text"},{"text":"filters","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"text":"]?)","kind":"text"}],"navigatorTitle":[{"text":"applyWithRotation:polygon:filters:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/apply(rotation:polygon:filters:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/documentImagePreviewURI":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentImagePreviewURI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?"}],"abstract":[{"text":"The percent-encoded file URL of the receivers rotated, cropped and filtered document preview image.","type":"text"},{"text":" ","type":"text"},{"text":"Warning: Never delete or manipulate the data at this URL or of the folders within this URL. This will lead to unpredictable behaviour and corrupted data.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/documentImagePreviewURI","title":"documentImagePreviewURI","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/documentimagepreviewuri","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentImagePreviewURI"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/documentImageURI":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentImageURI","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"documentImageURI","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/documentimageuri","title":"documentImageURI","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/documentImageURI","abstract":[{"text":"The percent-encoded file URL of the receivers rotated, cropped and filtered document image.","type":"text"},{"text":" ","type":"text"},{"text":"Warning: Never delete or manipulate the data at this URL or of the folders within this URL. This will lead to unpredictable behaviour and corrupted data.","type":"text"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/documentImagePreview":{"navigatorTitle":[{"text":"documentImagePreview","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/documentImagePreview","title":"documentImagePreview","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentImagePreview","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/documentimagepreview","abstract":[{"text":"The receivers rotated, cropped and filtered document preview image.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/documentImage":{"abstract":[{"type":"text","text":"The receivers rotated, cropped and filtered document image."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/documentimage","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentImage"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/documentImage","title":"documentImage"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/documentDetectionStatus":{"abstract":[{"type":"text","text":"The document detections status metadata of the receiver. As returned from "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector","type":"reference"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/documentDetectionStatus","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/documentdetectionstatus","title":"documentDetectionStatus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDetectionStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectionStatus","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectionStatus"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/documentQuality":{"abstract":[{"type":"text","text":"The document quality of the receiver. As returned from "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzer"},{"type":"text","text":"."}],"title":"documentQuality","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentQuality"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentQuality","kind":"typeIdentifier","text":"SBSDKDocumentQuality"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/documentQuality","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/documentquality"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKScannedPage","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKScannedPage"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKScannedPage"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/documentImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/documentImagePreview","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/documentImagePreviewURI","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/documentImageURI","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/filters","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/originalImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/originalImageURI","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/polygon","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/rotation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/unfilteredDocumentImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/unfilteredDocumentImageURI","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/uuid"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/addObserver(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/apply(rotation:polygon:filters:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/applyAsync(rotation:polygon:filters:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/removeObserver(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/toJson()"],"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedPage","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"removeObserver:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1removeObserver(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeObserver:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1removeObserver(_:)\/fragments"},{"op":"replace","value":"originalImageURI","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1originalImageURI\/title"},{"op":"replace","value":[{"text":"originalImageURI","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1originalImageURI\/fragments"},{"op":"replace","value":"toJson","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1toJson()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"toJson","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1toJson()\/fragments"},{"op":"replace","value":"unfilteredDocumentImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1unfilteredDocumentImage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"unfilteredDocumentImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1unfilteredDocumentImage\/fragments"},{"op":"replace","value":"polygon","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1polygon\/title"},{"op":"replace","value":[{"kind":"identifier","text":"polygon"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1polygon\/fragments"},{"op":"replace","value":"SBSDKScannedPage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/title"},{"op":"replace","value":[{"text":"SBSDKScannedPage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKScannedPage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/navigatorTitle"},{"op":"replace","value":"SBSDKDocumentDetector","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetector"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/navigatorTitle"},{"op":"replace","value":"originalImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1originalImage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"originalImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1originalImage\/fragments"},{"op":"replace","value":"filters","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1filters\/title"},{"op":"replace","value":[{"text":"filters","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1filters\/fragments"},{"op":"replace","value":"rotation","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1rotation\/title"},{"op":"replace","value":[{"text":"rotation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1rotation\/fragments"},{"op":"replace","value":"uuid","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1uuid\/title"},{"op":"replace","value":[{"text":"uuid","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1uuid\/fragments"},{"op":"replace","value":"SBSDKDocumentQualityAnalyzer","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzer\/title"},{"op":"replace","value":[{"text":"SBSDKDocumentQualityAnalyzer","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzer\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentQualityAnalyzer","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzer\/navigatorTitle"},{"op":"replace","value":"applyAsyncWithRotation:polygon:filters:completion:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1applyAsync(rotation:polygon:filters:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applyAsyncWithRotation:polygon:filters:completion:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1applyAsync(rotation:polygon:filters:completion:)\/fragments"},{"op":"replace","value":"unfilteredDocumentImageURI","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1unfilteredDocumentImageURI\/title"},{"op":"replace","value":[{"text":"unfilteredDocumentImageURI","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1unfilteredDocumentImageURI\/fragments"},{"op":"replace","value":"addObserver:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1addObserver(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addObserver:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1addObserver(_:)\/fragments"},{"op":"replace","value":"applyWithRotation:polygon:filters:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1apply(rotation:polygon:filters:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applyWithRotation:polygon:filters:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1apply(rotation:polygon:filters:)\/fragments"},{"op":"replace","value":"documentImagePreviewURI","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1documentImagePreviewURI\/title"},{"op":"replace","value":[{"text":"documentImagePreviewURI","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1documentImagePreviewURI\/fragments"},{"op":"replace","value":"documentImageURI","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1documentImageURI\/title"},{"op":"replace","value":[{"kind":"identifier","text":"documentImageURI"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1documentImageURI\/fragments"},{"op":"replace","value":"documentImagePreview","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1documentImagePreview\/title"},{"op":"replace","value":[{"kind":"identifier","text":"documentImagePreview"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1documentImagePreview\/fragments"},{"op":"replace","value":"documentImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1documentImage\/title"},{"op":"replace","value":[{"text":"documentImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1documentImage\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}