{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/init(storageLocation:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encrypter:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/encrypter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/fileFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/imageCount","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/imageURLs","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/jpegCompressionQuality"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/add(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/addImage(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/image(at:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/imageURL(at:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/insert(_:at:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/moveImage(from:to:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/removeAll()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/removeImage(at:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/replaceImage(at:with:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/replaceImage(at:withImageAtURL:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/waitUntilWritingCompleted()"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/temporary"],"generated":true,"title":"Type Properties","anchor":"Type-Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKIndexedImageStorage","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkindexedimagestorage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkindexedimagestorage"]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"title":"SBSDKIndexedImageStorage","symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKIndexedImageStorage","roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class.","type":"text"},{"text":" ","type":"text"},{"text":"Manages images in an array-like fashion.","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","type":"conformsTo"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/removeImage(at:)":{"kind":"symbol","type":"topic","title":"removeImage(at:)","abstract":[{"type":"text","text":"Removes the stored image at the given index from the image storage."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/removeImage(at:)","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/removeimage(at:)","navigatorTitle":[{"kind":"identifier","text":"removeImageAtIndex:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/replaceImage(at:with:)":{"abstract":[{"text":"Replaces the receivers image at index with the given image.","type":"text"}],"role":"symbol","type":"topic","title":"replaceImage(at:with:)","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/replaceimage(at:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"replaceImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"replaceImageAtIndex:withImage:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/replaceImage(at:with:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage":{"abstract":[{"text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class.","type":"text"},{"text":" ","type":"text"},{"text":"Manages images in an array-like fashion.","type":"text"}],"role":"symbol","type":"topic","title":"SBSDKIndexedImageStorage","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageStoring":{"url":"\/documentation\/scanbotsdk\/sbsdkimagestoring","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring","navigatorTitle":[{"text":"SBSDKImageStoring","kind":"identifier"}],"abstract":[{"type":"text","text":"Protocol for an order-aware (array like) image storage."}],"type":"topic","role":"symbol","title":"SBSDKImageStoring","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageStoring","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/imageCount":{"abstract":[{"type":"text","text":"Number of images in the receiver."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/imageCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","title":"imageCount","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/imagecount","navigatorTitle":[{"kind":"identifier","text":"imageCount"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/image(at:)":{"title":"image(at:)","navigatorTitle":[{"kind":"identifier","text":"imageAtIndex:"}],"abstract":[{"text":"Returns the stored UIImage at the specified index.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/image(at:)","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/image(at:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/imageURLs":{"title":"imageURLs","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/imageurls","abstract":[{"type":"text","text":"Array of all stored images URLs."}],"navigatorTitle":[{"text":"imageURLs","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageURLs","kind":"identifier"},{"text":": [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/imageURLs","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/copyWithZone:":{"abstract":[],"type":"topic","title":"copyWithZone:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/copywithzone:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/moveImage(from:to:)":{"abstract":[{"type":"text","text":"Moves the image at the source index to the destination index."}],"type":"topic","title":"moveImage(from:to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/moveImage(from:to:)","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/moveimage(from:to:)","role":"symbol","navigatorTitle":[{"text":"moveImageFromIndex:toIndex:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/temporary":{"navigatorTitle":[{"kind":"identifier","text":"temporary"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/temporary","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A new "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage","isActive":true},{"type":"text","text":" at a temporary location (application caches folder)."}],"url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/temporary","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"temporary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKIndexedImageStorage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKIndexedImageStorage"},{"kind":"text","text":"?"}],"title":"temporary"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/fileFormat":{"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileFormat"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat","kind":"typeIdentifier","text":"SBSDKImageFileFormat"}],"abstract":[{"type":"text","text":"Image file format to be used to store the managed images."}],"title":"fileFormat","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fileFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/fileformat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/fileFormat","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/encrypter":{"url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/encrypter","role":"symbol","title":"encrypter","abstract":[{"type":"text","text":"Encrypter used to encrypt and decrypt the image data. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", no encryption\/decryption is used."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/encrypter","navigatorTitle":[{"kind":"identifier","text":"encrypter"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encrypter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/replaceImage(at:withImageAtURL:)":{"url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/replaceimage(at:withimageaturl:)","role":"symbol","title":"replaceImage(at:withImageAtURL:)","abstract":[{"type":"text","text":"Replaces the receivers image at index with the image stored at the given URL."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/replaceImage(at:withImageAtURL:)","navigatorTitle":[{"text":"replaceImageAtIndex:withImageAtURL:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"replaceImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withImageAtURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/imageURL(at:)":{"url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/imageurl(at:)","role":"symbol","title":"imageURL(at:)","abstract":[{"type":"text","text":"Returns the URL of the stored image at the specified index."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/imageURL(at:)","navigatorTitle":[{"kind":"identifier","text":"imageURLAtIndex:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageURL"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/jpegCompressionQuality":{"abstract":[{"type":"text","text":"The JPEG compression if JPEG file format is used. Range: 0.0 - 1.0."}],"title":"jpegCompressionQuality","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpegCompressionQuality"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"navigatorTitle":[{"kind":"identifier","text":"jpegCompressionQuality"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/jpegcompressionquality","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/jpegCompressionQuality","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/waitUntilWritingCompleted()":{"role":"symbol","abstract":[{"type":"text","text":"Blocks the current thread until all enqueued writing operations have been finished."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"waitUntilWritingCompleted"}],"title":"waitUntilWritingCompleted()","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/waitUntilWritingCompleted()","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/waituntilwritingcompleted()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitUntilWritingCompleted"},{"kind":"text","text":"()"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/init(storageLocation:fileFormat:encrypter:)":{"url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/init(storagelocation:fileformat:encrypter:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"storageLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fileFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encrypter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encrypter:)","type":"topic","title":"init(storageLocation:fileFormat:encrypter:)","abstract":[{"type":"text","text":"Initializes a new "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage"},{"type":"text","text":" at the given storage location with given image file format."}],"navigatorTitle":[{"text":"initWithStorageLocation:fileFormat:encrypter:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/addImage(from:)":{"navigatorTitle":[{"kind":"identifier","text":"addImageFromURL:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[{"type":"text","text":"Adds an image from a file into the storage."}],"type":"topic","title":"addImage(from:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/addImage(from:)","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/addimage(from:)"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/removeAll()":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAll"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Removes all stored images from the image storage."}],"url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/removeall()","title":"removeAll()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/removeAll()","navigatorTitle":[{"kind":"identifier","text":"removeAllImages"}]},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/insert(_:at:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insert"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"insertImage:atIndex:"}],"role":"symbol","abstract":[{"type":"text","text":"Inserts a new image into the receiver at the given index."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/insert(_:at:)","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/insert(_:at:)","kind":"symbol","title":"insert(_:at:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/init(storageLocation:)":{"abstract":[{"type":"text","text":"Initializes a new "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage"},{"type":"text","text":" at the given storage location."}],"role":"symbol","title":"init(storageLocation:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"storageLocation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation","kind":"typeIdentifier","text":"SBSDKStorageLocation"},{"kind":"text","text":"?)"}],"url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/init(storagelocation:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithStorageLocation:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/init(storageLocation:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/add(_:)":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/add(_:)","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/add(_:)","navigatorTitle":[{"kind":"identifier","text":"addImage:"}],"title":"add(_:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Adds a "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" into the storage."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/init(storagelocation:fileformat:encrypter:encryptedimagesurls:)","navigatorTitle":[{"text":"initWithStorageLocation:fileFormat:encrypter:encryptedImagesURLs:","kind":"identifier"}],"type":"topic","title":"init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"storageLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation","text":"SBSDKStorageLocation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fileFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat","text":"SBSDKImageFileFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encrypter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"encryptedImagesURLs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"])"}],"role":"symbol","abstract":[{"type":"text","text":"Initializes a new "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage","isActive":true},{"type":"text","text":" at the given storage location with given image file format."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKIndexedImageStorage","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/encrypter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/fileFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/imageCount","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/imageURLs","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/jpegCompressionQuality"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/add(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/addImage(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/image(at:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/imageURL(at:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/init(storageLocation:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encrypter:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/insert(_:at:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/moveImage(from:to:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/removeAll()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/removeImage(at:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/replaceImage(at:with:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/replaceImage(at:withImageAtURL:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/waitUntilWritingCompleted()"],"anchor":"Instance-Methods","generated":true},{"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/temporary"],"anchor":"Type-Properties","generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKIndexedImageStorage","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"removeImageAtIndex:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1removeImage(at:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeImageAtIndex:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1removeImage(at:)\/fragments"},{"op":"replace","value":"replaceImageAtIndex:withImage:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1replaceImage(at:with:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"replaceImageAtIndex:withImage:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1replaceImage(at:with:)\/fragments"},{"op":"replace","value":"SBSDKIndexedImageStorage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/navigatorTitle"},{"op":"replace","value":"SBSDKImageStoring","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageStoring"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageStoring"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/navigatorTitle"},{"op":"replace","value":"imageCount","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1imageCount\/title"},{"op":"replace","value":[{"text":"imageCount","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1imageCount\/fragments"},{"op":"replace","value":"imageAtIndex:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1image(at:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imageAtIndex:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1image(at:)\/fragments"},{"op":"replace","value":"imageURLs","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1imageURLs\/title"},{"op":"replace","value":[{"kind":"identifier","text":"imageURLs"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1imageURLs\/fragments"},{"op":"replace","value":"moveImageFromIndex:toIndex:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1moveImage(from:to:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"moveImageFromIndex:toIndex:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1moveImage(from:to:)\/fragments"},{"op":"replace","value":"temporary","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1temporary\/title"},{"op":"replace","value":[{"kind":"identifier","text":"temporary"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1temporary\/fragments"},{"op":"replace","value":"fileFormat","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1fileFormat\/title"},{"op":"replace","value":[{"text":"fileFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1fileFormat\/fragments"},{"op":"replace","value":"encrypter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1encrypter\/title"},{"op":"replace","value":[{"text":"encrypter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1encrypter\/fragments"},{"op":"replace","value":"replaceImageAtIndex:withImageAtURL:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1replaceImage(at:withImageAtURL:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"replaceImageAtIndex:withImageAtURL:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1replaceImage(at:withImageAtURL:)\/fragments"},{"op":"replace","value":"imageURLAtIndex:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1imageURL(at:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imageURLAtIndex:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1imageURL(at:)\/fragments"},{"op":"replace","value":"jpegCompressionQuality","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1jpegCompressionQuality\/title"},{"op":"replace","value":[{"text":"jpegCompressionQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1jpegCompressionQuality\/fragments"},{"op":"replace","value":"waitUntilWritingCompleted","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1waitUntilWritingCompleted()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"waitUntilWritingCompleted","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1waitUntilWritingCompleted()\/fragments"},{"op":"replace","value":"initWithStorageLocation:fileFormat:encrypter:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1init(storageLocation:fileFormat:encrypter:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStorageLocation:fileFormat:encrypter:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1init(storageLocation:fileFormat:encrypter:)\/fragments"},{"op":"replace","value":"addImageFromURL:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1addImage(from:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addImageFromURL:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1addImage(from:)\/fragments"},{"op":"replace","value":"removeAllImages","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1removeAll()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeAllImages","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1removeAll()\/fragments"},{"op":"replace","value":"insertImage:atIndex:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1insert(_:at:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"insertImage:atIndex:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1insert(_:at:)\/fragments"},{"op":"replace","value":"initWithStorageLocation:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1init(storageLocation:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithStorageLocation:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1init(storageLocation:)\/fragments"},{"op":"replace","value":"addImage:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1add(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addImage:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1add(_:)\/fragments"},{"op":"replace","value":"initWithStorageLocation:fileFormat:encrypter:encryptedImagesURLs:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithStorageLocation:fileFormat:encrypter:encryptedImagesURLs:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}