{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateScannerState"}],"title":"SBSDKMedicalCertificateScannerState","navigatorTitle":[{"text":"SBSDKMedicalCertificateScannerState","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateScannerState","role":"symbol","symbolKind":"enum","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Enumeration"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/capturing","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/energySaving","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/paused","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/recognizing","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/searching"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKMedicalCertificateScannerState","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"type":"text","text":"The live recognition state of the medical certificate scanner."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerState/energySaving":{"title":"SBSDKMedicalCertificateScannerState.energySaving","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"energySaving","kind":"identifier"}],"abstract":[{"text":"The medical certificate scanner is in energy-saving mode.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/energySaving","navigatorTitle":[{"text":"SBSDKMedicalCertificateScannerStateEnergySaving","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate\/energysaving","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerState/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/init(rawValue:)","role":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerState/recognizing":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"recognizing","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate\/recognizing","kind":"symbol","title":"SBSDKMedicalCertificateScannerState.recognizing","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/recognizing","role":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateScannerStateRecognizing","kind":"identifier"}],"abstract":[{"text":"The medical certificate scanner is recognizing a medical certificate.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerState":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMedicalCertificateScannerState"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate","kind":"symbol","title":"SBSDKMedicalCertificateScannerState","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState","role":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateScannerState","kind":"identifier"}],"abstract":[{"text":"The live recognition state of the medical certificate scanner.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerState/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/RawRepresentable-Implementations","type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerState/capturing":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"The medical certificate scanner is capturing a high-res photo of a medical certificate.","type":"text"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateScannerStateCapturing","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"capturing"}],"title":"SBSDKMedicalCertificateScannerState.capturing","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate\/capturing","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/capturing"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerState/paused":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paused","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate\/paused","kind":"symbol","title":"SBSDKMedicalCertificateScannerState.paused","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/paused","role":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateScannerStatePaused","kind":"identifier"}],"abstract":[{"type":"text","text":"The medical certificate scanner has paused the detection and recognition."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerState/searching":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The medical certificate scanner is searching for medical certificates."}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateScannerStateSearching","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searching","kind":"identifier"}],"title":"SBSDKMedicalCertificateScannerState.searching","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate\/searching","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/searching"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerState/Equatable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate\/equatable-implementations","kind":"article","title":"Equatable Implementations","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/Equatable-Implementations","role":"collectionGroup","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKMedicalCertificateScannerState"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerState"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerState"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/capturing","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/energySaving","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/paused","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/recognizing","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/searching"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKMedicalCertificateScannerState","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState~1energySaving\/title","value":"SBSDKMedicalCertificateScannerStateEnergySaving"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState~1energySaving\/fragments","value":[{"text":"SBSDKMedicalCertificateScannerStateEnergySaving","kind":"identifier"}],"op":"replace"},{"value":"SBSDKMedicalCertificateScannerStateRecognizing","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState~1recognizing\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState~1recognizing\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerStateRecognizing"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState\/title","op":"replace","value":"SBSDKMedicalCertificateScannerState"},{"value":[{"text":"SBSDKMedicalCertificateScannerState","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerState"}]},{"value":"SBSDKMedicalCertificateScannerStateCapturing","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState~1capturing\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState~1capturing\/fragments","value":[{"text":"SBSDKMedicalCertificateScannerStateCapturing","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState~1paused\/title","value":"SBSDKMedicalCertificateScannerStatePaused","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState~1paused\/fragments","value":[{"text":"SBSDKMedicalCertificateScannerStatePaused","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState~1searching\/title","value":"SBSDKMedicalCertificateScannerStateSearching"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState~1searching\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerStateSearching"}]}]}]}