{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"minimumInsets","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2EdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2EdgeInsets"}],"navigatorTitle":[{"text":"minimumInsets","kind":"identifier"}],"symbolKind":"property","role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BaseViewFinderConfiguration(py)minimumInsets","title":"minimumInsets","roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/minimuminsets"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/minimuminsets"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"minimumInsets","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2EdgeInsets","text":"SBSDKUI2EdgeInsets","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2EdgeInsets"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/minimumInsets","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"The minimum insets of the viewfinder."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BaseViewFinderConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration","abstract":[{"type":"text","text":"Base configuration of the scanning interface’s viewfinder, serving as guidance to the user."}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"}],"title":"SBSDKUI2BaseViewFinderConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2EdgeInsets":{"title":"SBSDKUI2EdgeInsets","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2EdgeInsets","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2EdgeInsets"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2edgeinsets","abstract":[{"type":"text","text":"Represents the insets of a rectangle."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2EdgeInsets","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration/minimumInsets":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minimumInsets","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2EdgeInsets","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2EdgeInsets"}],"type":"topic","navigatorTitle":[{"text":"minimumInsets","kind":"identifier"}],"abstract":[{"type":"text","text":"The minimum insets of the viewfinder."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/minimumInsets","url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/minimuminsets","role":"symbol","title":"minimumInsets","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"minimumInsets","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"minimumInsets"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2EdgeInsets","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2EdgeInsets","kind":"typeIdentifier","text":"SBSDKUI2EdgeInsets"},{"text":" * ","kind":"text"},{"text":"minimumInsets","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration\/title","value":"SBSDKUI2BaseViewFinderConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKUI2BaseViewFinderConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2EdgeInsets\/title","value":"SBSDKUI2EdgeInsets"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2EdgeInsets\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2EdgeInsets"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2EdgeInsets\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2EdgeInsets"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1minimumInsets\/title","op":"replace","value":"minimumInsets"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1minimumInsets\/fragments","value":[{"text":"minimumInsets","kind":"identifier"}],"op":"replace"}]}]}