{"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","platforms":[{"name":"iOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"13.0"},{"name":"iPadOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"13.0"},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"13.0"},{"name":"macOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"10.15"},{"name":"tvOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"13.0"},{"name":"watchOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"6.0"}],"externalID":"s:7SwiftUI4ViewPAAE8modifieryAA15ModifiedContentVyxqd__Gqd__lF::SYNTHESIZED::s:10ScanbotSDK22SBSDKUI2MRZScannerViewV","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"modifier"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ModifiedContent","preciseIdentifier":"s:7SwiftUI15ModifiedContentV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":">"}],"extendedModule":"SwiftUICore","title":"modifier(_:)","modules":[{"name":"ScanbotSDK","relatedModules":["SwiftUICore"]}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerview\/modifier(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView\/modifier(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView\/View-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.modifier(_:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modifier","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"modifier","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI15ModifiedContentV","text":"ModifiedContent"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":">"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerView/modifier(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modifier","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"ModifiedContent","preciseIdentifier":"s:7SwiftUI15ModifiedContentV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":">","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView\/modifier(_:)","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerview\/modifier(_:)","title":"modifier(_:)","role":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerViewController":{"type":"topic","kind":"symbol","title":"SBSDKUI2MRZScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MRZScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerViewController","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan MRZ (Machine-readable zones) of various documents.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2MRZScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerView/View-Implementations":{"type":"topic","role":"collectionGroup","title":"View Implementations","abstract":[],"kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView\/View-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerview\/view-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerView":{"type":"topic","kind":"symbol","title":"SBSDKUI2MRZScannerView","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerview","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MRZScannerView","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView","abstract":[{"text":"The SwiftUI wrapper for ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerViewController","type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2MRZScannerView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2MRZScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerViewController\/fragments"},{"value":[{"text":"SBSDKUI2MRZScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}