{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/initwithbarcodeformatconfigurations:extracteddocumentformats:onlyacceptdocuments:returnbarcodeimage:enginemode:accumulationconfig:optimizedforoverlays:"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","symbolKind":"method","title":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerConfiguration(im)initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:"}]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithBarcodeFormatConfigurations:"},{"kind":"text","text":"("},{"text":"NSArray<SBSDKBarcodeFormatConfigurationBase *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"barcodeFormatConfigurations","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"extractedDocumentFormats:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKBarcodeDocumentFormat *>"},{"text":" *) ","kind":"text"},{"text":"extractedDocumentFormats","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlyAcceptDocuments:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"text":"onlyAcceptDocuments","kind":"internalParam"},{"kind":"text","text":" "},{"text":"returnBarcodeImage:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"returnBarcodeImage","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"engineMode:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodeScannerEngineMode","text":"SBSDKBarcodeScannerEngineMode"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"engineMode"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accumulationConfig:"},{"kind":"text","text":"("},{"text":"SBSDKBarcodeAccumulationConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeAccumulationConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accumulationConfig"},{"text":" ","kind":"text"},{"kind":"identifier","text":"optimizedForOverlays:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"optimizedForOverlays","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:","type":"topic","title":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/initwithbarcodeformatconfigurations:extracteddocumentformats:onlyacceptdocuments:returnbarcodeimage:enginemode:accumulationconfig:optimizedforoverlays:","navigatorTitle":[{"text":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAccumulationConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationConfiguration","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration for how to accumulate results."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeAccumulationConfiguration"}],"title":"SBSDKBarcodeAccumulationConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode":{"type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode","title":"SBSDKBarcodeScannerEngineMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"abstract":[{"type":"text","text":"The engine mode for barcode scanning."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for the barcode scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration","navigatorTitle":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration","title":"SBSDKBarcodeScannerConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationConfiguration\/title","value":"SBSDKBarcodeAccumulationConfiguration"},{"value":[{"text":"SBSDKBarcodeAccumulationConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeAccumulationConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode\/title","value":"SBSDKBarcodeScannerEngineMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineMode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode\/navigatorTitle","value":[{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}]},{"value":"SBSDKBarcodeScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}]},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/navigatorTitle"}]}]}