{"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvatitledatavehiclebodystylefieldname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvatitledatavehiclebodystylefieldname"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"aamvaTitleDataVehicleBodyStyleFieldName"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelConstants(cpy)aamvaTitleDataVehicleBodyStyleFieldName","symbolKind":"property","title":"aamvaTitleDataVehicleBodyStyleFieldName","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvaTitleDataVehicleBodyStyleFieldName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/aamvaTitleDataVehicleBodyStyleFieldName","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Name of the “VehicleBodyStyle” field type in document type “AAMVA.TitleData”.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaTitleDataVehicleBodyStyleFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants","kind":"symbol","title":"SBSDKBarcodeDocumentModelConstants","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants/aamvaTitleDataVehicleBodyStyleFieldName":{"title":"aamvaTitleDataVehicleBodyStyleFieldName","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvaTitleDataVehicleBodyStyleFieldName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"aamvaTitleDataVehicleBodyStyleFieldName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/aamvaTitleDataVehicleBodyStyleFieldName","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvatitledatavehiclebodystylefieldname","type":"topic","abstract":[{"type":"text","text":"Name of the “VehicleBodyStyle” field type in document type “AAMVA.TitleData”."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"aamvaTitleDataVehicleBodyStyleFieldName","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"aamvaTitleDataVehicleBodyStyleFieldName","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"aamvaTitleDataVehicleBodyStyleFieldName"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/title","value":"SBSDKBarcodeDocumentModelConstants","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1aamvaTitleDataVehicleBodyStyleFieldName\/title","value":"aamvaTitleDataVehicleBodyStyleFieldName"},{"value":[{"text":"aamvaTitleDataVehicleBodyStyleFieldName","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1aamvaTitleDataVehicleBodyStyleFieldName\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}