{"abstract":[{"text":"Normalized full name of the “SecondNonConsecutiveBaggageTagLicensePlateNumber” field type in document type","type":"text"},{"text":" ","type":"text"},{"text":"“BoardingPass.Leg”.","type":"text"}],"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"text":"boardingPassLegSecondNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelConstants(cpy)boardingPassLegSecondNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","roleHeading":"Type Property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"boardingPassLegSecondNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"boardingPassLegSecondNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","symbolKind":"property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/boardingPassLegSecondNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/boardingpasslegsecondnonconsecutivebaggagetaglicenseplatenumberfieldnormalizedname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/boardingpasslegsecondnonconsecutivebaggagetaglicenseplatenumberfieldnormalizedname"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"boardingPassLegSecondNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants","kind":"symbol","title":"SBSDKBarcodeDocumentModelConstants","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants/boardingPassLegSecondNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName":{"role":"symbol","title":"boardingPassLegSecondNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/boardingpasslegsecondnonconsecutivebaggagetaglicenseplatenumberfieldnormalizedname","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Normalized full name of the “SecondNonConsecutiveBaggageTagLicensePlateNumber” field type in document type"},{"type":"text","text":" "},{"type":"text","text":"“BoardingPass.Leg”."}],"navigatorTitle":[{"kind":"identifier","text":"boardingPassLegSecondNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/boardingPassLegSecondNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"boardingPassLegSecondNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"boardingPassLegSecondNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"boardingPassLegSecondNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"boardingPassLegSecondNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKBarcodeDocumentModelConstants","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/title"},{"value":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/navigatorTitle"},{"value":"boardingPassLegSecondNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1boardingPassLegSecondNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName\/title"},{"value":[{"text":"boardingPassLegSecondNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1boardingPassLegSecondNonConsecutiveBaggageTagLicensePlateNumberFieldNormalizedName\/fragments"}]}]}