{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorUIConfiguration\/visibility(forFieldType:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractoruiconfiguration\/visibility(forfieldtype:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractoruiconfiguration\/visibility(forfieldtype:)"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"visibilityForFieldType:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorUIConfiguration(im)visibilityForFieldType:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"visibility"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forFieldType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentFieldDisplayState","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDisplayState"},{"kind":"text","text":"?"}],"symbolKind":"method","roleHeading":"Instance Method","title":"visibility(forFieldType:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorUIConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(visibilityForFieldType:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibility","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forFieldType","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"fieldType","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"SBSDKGenericDocumentFieldDisplayState","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDisplayState","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDisplayState"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"fieldType","content":[{"type":"paragraph","inlineContent":[{"text":"The type of the field.","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"The visibility state for the given field type.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"A convenience method to get the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDisplayState"},{"type":"text","text":" for the given field type."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorUIConfiguration":{"kind":"symbol","abstract":[{"type":"text","text":"The configuration for the user interface of the RTU-UI document data extractor screen."}],"type":"topic","title":"SBSDKUIDocumentDataExtractorUIConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractoruiconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentDataExtractorUIConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIDocumentDataExtractorUIConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorUIConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorUIConfiguration/visibility(forFieldType:)":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractoruiconfiguration\/visibility(forfieldtype:)","title":"visibility(forFieldType:)","navigatorTitle":[{"text":"visibilityForFieldType:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorUIConfiguration\/visibility(forFieldType:)","abstract":[{"type":"text","text":"A convenience method to get the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDisplayState"},{"type":"text","text":" for the given field type."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibility","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forFieldType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"SBSDKGenericDocumentFieldDisplayState","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDisplayState"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldDisplayState":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentFieldDisplayState","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddisplaystate","role":"symbol","title":"SBSDKGenericDocumentFieldDisplayState","navigatorTitle":[{"text":"SBSDKGenericDocumentFieldDisplayState","kind":"identifier"}],"abstract":[{"text":"The generic document fields display status. Whether a field is shown or hidden in the user interface.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDisplayState"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"visibilityForFieldType:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"visibilityForFieldType:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDisplayState","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDisplayState","text":"SBSDKGenericDocumentFieldDisplayState"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"visibilityForFieldType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fieldType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of the field."}]}],"name":"fieldType"}]},"path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The visibility state for the given field type."}]}]},"op":"replace"},{"op":"replace","value":"SBSDKUIDocumentDataExtractorUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKUIDocumentDataExtractorUIConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration\/navigatorTitle"},{"op":"replace","value":"visibilityForFieldType:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration~1visibility(forFieldType:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"visibilityForFieldType:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration~1visibility(forFieldType:)\/fragments"},{"op":"replace","value":"SBSDKGenericDocumentFieldDisplayState","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDisplayState\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentFieldDisplayState"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDisplayState\/fragments"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentFieldDisplayState","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDisplayState\/navigatorTitle"}]}]}