{"abstract":[{"text":"Informs the delegate that the scanner has failed scanning a machine-readable zone.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(mrzScannerController:didFailScanningWithError:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrzScannerController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKMRZScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController"},{"text":", ","kind":"text"},{"text":"didFailScanning","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"controller","content":[{"inlineContent":[{"type":"text","text":"The scanner controller that failed scanning."}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"The error that occurred during scanning."}],"type":"paragraph"}]}],"kind":"parameters"}],"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKMRZScannerViewControllerDelegate(im)mrzScannerController:didFailScanningWithError:","required":true,"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"title":"mrzScannerController(_:didFailScanning:)","navigatorTitle":[{"kind":"identifier","text":"mrzScannerController:didFailScanningWithError:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzScannerController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController","kind":"typeIdentifier","text":"SBSDKMRZScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailScanning"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate\/mrzscannercontroller(_:didfailscanning:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate\/mrzscannercontroller(_:didfailscanning:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate\/mrzScannerController(_:didFailScanning:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewController":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZScannerViewController"}],"abstract":[{"text":"Classic UI view controller that can be used to scan machine-readable zones.","type":"text"}],"title":"SBSDKMRZScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewControllerDelegate":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate","type":"topic","title":"SBSDKMRZScannerViewControllerDelegate","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMRZScannerViewControllerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"The delegation protocol for the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","isActive":true},{"type":"text","text":" class."}],"navigatorTitle":[{"text":"SBSDKMRZScannerViewControllerDelegate","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewControllerDelegate/mrzScannerController(_:didFailScanning:)":{"navigatorTitle":[{"kind":"identifier","text":"mrzScannerController:didFailScanningWithError:"}],"title":"mrzScannerController(_:didFailScanning:)","type":"topic","required":true,"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate\/mrzscannercontroller(_:didfailscanning:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate\/mrzScannerController(_:didFailScanning:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzScannerController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKMRZScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailScanning"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"text":"Informs the delegate that the scanner has failed scanning a machine-readable zone.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"mrzScannerController:didFailScanningWithError:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"mrzScannerController:didFailScanningWithError:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"mrzScannerController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMRZScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didFailScanningWithError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"text":"The scanner controller that failed scanning.","type":"text"}]}]},{"name":"error","content":[{"inlineContent":[{"text":"The error that occurred during scanning.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SBSDKMRZScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/title"},{"value":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKMRZScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/navigatorTitle"},{"value":"SBSDKMRZScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate\/title"},{"value":[{"kind":"identifier","text":"SBSDKMRZScannerViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate\/fragments"},{"value":[{"text":"SBSDKMRZScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate\/navigatorTitle"},{"value":"mrzScannerController:didFailScanningWithError:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate~1mrzScannerController(_:didFailScanning:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"mrzScannerController:didFailScanningWithError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate~1mrzScannerController(_:didFailScanning:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}