{"metadata":{"navigatorTitle":[{"text":"SBSDKAutoSnappingModeEnabled","kind":"identifier"}],"title":"SBSDKAutoSnappingMode.enabled","externalID":"c:@M@ScanbotSDK@E@SBSDKAutoSnappingMode@SBSDKAutoSnappingModeEnabled","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabled","kind":"identifier"}],"role":"symbol","symbolKind":"case"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/enabled"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabled","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkautosnappingmode\/enabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkautosnappingmode\/enabled"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Auto-snapping and user guidance are enabled."}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAutoSnappingMode/enabled":{"url":"\/documentation\/scanbotsdk\/sbsdkautosnappingmode\/enabled","kind":"symbol","title":"SBSDKAutoSnappingMode.enabled","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/enabled","abstract":[{"text":"Auto-snapping and user guidance are enabled.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabled","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKAutoSnappingModeEnabled","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAutoSnappingMode":{"type":"topic","navigatorTitle":[{"text":"SBSDKAutoSnappingMode","kind":"identifier"}],"title":"SBSDKAutoSnappingMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode","abstract":[{"type":"text","text":"The Auto-snapping mode handles different auto-snap scenarios."}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAutoSnappingMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkautosnappingmode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKAutoSnappingModeEnabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKAutoSnappingModeEnabled"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKAutoSnappingModeEnabled","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode~1enabled\/title","value":"SBSDKAutoSnappingModeEnabled"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode~1enabled\/fragments","value":[{"text":"SBSDKAutoSnappingModeEnabled","kind":"identifier"}]},{"op":"replace","value":"SBSDKAutoSnappingMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode\/title"},{"op":"replace","value":[{"text":"SBSDKAutoSnappingMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAutoSnappingMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode\/navigatorTitle"}]}]}