{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"copyCurrentConfiguration"},{"kind":"text","text":"() -> "},{"text":"SBSDKTextPatternScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The current configuration."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController"]]},"abstract":[{"text":"Returns a copy of the receivers current configuration.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontroller\/copycurrentconfiguration()"]},{"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontroller\/copycurrentconfiguration()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController\/copyCurrentConfiguration()"},"metadata":{"title":"copyCurrentConfiguration()","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"copyCurrentConfiguration","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerConfiguration","text":"SBSDKTextPatternScannerConfiguration","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController(im)copyCurrentConfiguration","navigatorTitle":[{"kind":"identifier","text":"copyCurrentConfiguration"}],"roleHeading":"Instance Method"},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerViewController":{"title":"SBSDKTextPatternScannerViewController","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the text pattern scanner."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontroller","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerConfiguration":{"type":"topic","abstract":[{"text":"Configuration for the text pattern scanner.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKTextPatternScannerConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration","title":"SBSDKTextPatternScannerConfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerViewController/copyCurrentConfiguration()":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"copyCurrentConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerConfiguration","text":"SBSDKTextPatternScannerConfiguration"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController\/copyCurrentConfiguration()","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontroller\/copycurrentconfiguration()","abstract":[{"text":"Returns a copy of the receivers current configuration.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyCurrentConfiguration"}],"title":"copyCurrentConfiguration()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"copyCurrentConfiguration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyCurrentConfiguration"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"SBSDKTextPatternScannerConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerConfiguration"},{"text":" *) ","kind":"text"},{"text":"copyCurrentConfiguration","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"The current configuration."}],"type":"paragraph"}],"kind":"content"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/title","op":"replace","value":"SBSDKTextPatternScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/navigatorTitle","value":[{"text":"SBSDKTextPatternScannerViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKTextPatternScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKTextPatternScannerConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/navigatorTitle","value":[{"text":"SBSDKTextPatternScannerConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController~1copyCurrentConfiguration()\/title","value":"copyCurrentConfiguration","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyCurrentConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController~1copyCurrentConfiguration()\/fragments"}]}]}