{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"kind":"symbol","abstract":[{"type":"text","text":"The prioritization of still image quality and capturing speed."}],"metadata":{"title":"SBSDKCapturePhotoQualityPrioritization","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritization"}],"role":"symbol","roleHeading":"Enumeration","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritization"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCapturePhotoQualityPrioritization"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization"},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/quality","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/speed"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"],"title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcapturephotoqualityprioritization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcapturephotoqualityprioritization"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCapturePhotoQualityPrioritization":{"kind":"symbol","title":"SBSDKCapturePhotoQualityPrioritization","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcapturephotoqualityprioritization","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}],"abstract":[{"text":"The prioritization of still image quality and capturing speed.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCapturePhotoQualityPrioritization/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","kind":"article","role":"collectionGroup","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/RawRepresentable-Implementations","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcapturephotoqualityprioritization\/rawrepresentable-implementations","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCapturePhotoQualityPrioritization/speed":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcapturephotoqualityprioritization\/speed","title":"SBSDKCapturePhotoQualityPrioritization.speed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"speed","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCapturePhotoQualityPrioritizationSpeed","kind":"identifier"}],"abstract":[{"text":"Captures a still image at the highest possible speed. The quality of the image may be degraded.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/speed","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCapturePhotoQualityPrioritization/init(rawValue:)":{"type":"topic","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcapturephotoqualityprioritization\/init(rawvalue:)","title":"init(rawValue:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/init(rawValue:)"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCapturePhotoQualityPrioritization/balanced":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"balanced"}],"role":"symbol","type":"topic","title":"SBSDKCapturePhotoQualityPrioritization.balanced","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcapturephotoqualityprioritization\/balanced","abstract":[{"type":"text","text":"Balances capturing speed and image quality equally. This is the default value."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritizationBalanced"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCapturePhotoQualityPrioritization/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/Equatable-Implementations","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcapturephotoqualityprioritization\/equatable-implementations","title":"Equatable Implementations","type":"topic","role":"collectionGroup","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCapturePhotoQualityPrioritization/quality":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"}],"title":"SBSDKCapturePhotoQualityPrioritization.quality","role":"symbol","abstract":[{"type":"text","text":"Captures a still image with the best possible quality in terms of noise, frozen motion and detail in low light."},{"type":"text","text":" "},{"type":"text","text":"The speed of the capturing might be significantly reduced."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritizationQuality"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/quality","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcapturephotoqualityprioritization\/quality"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","abstract":[{"text":"Version: 8.0.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKCapturePhotoQualityPrioritization","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritization"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/quality","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/speed"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKCapturePhotoQualityPrioritization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization\/title"},{"value":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritization"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization\/fragments"},{"value":[{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization\/navigatorTitle"},{"value":"SBSDKCapturePhotoQualityPrioritizationSpeed","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization~1speed\/title"},{"value":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritizationSpeed"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization~1speed\/fragments"},{"value":"SBSDKCapturePhotoQualityPrioritizationBalanced","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization~1balanced\/title"},{"value":[{"text":"SBSDKCapturePhotoQualityPrioritizationBalanced","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization~1balanced\/fragments"},{"value":"SBSDKCapturePhotoQualityPrioritizationQuality","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization~1quality\/title"},{"value":[{"text":"SBSDKCapturePhotoQualityPrioritizationQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization~1quality\/fragments"}]}]}