{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseInfo"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKLicenseStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKLicenseStatus"},{"text":", ","kind":"text"},{"text":"isValid","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"licenseStatusMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"expirationTimestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"expirationDateString","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"errorMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onlineLicenseCheckInProgress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"license","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"nextOnlineLicenseCheckInMs","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"deviceDeregistationErrors","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"SBSDKDeviceDeregistrationError","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDeviceDeregistrationError","kind":"typeIdentifier"},{"text":">)","kind":"text"}],"roleHeading":"Initializer","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","navigatorTitle":[{"text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLicenseInfo(im)initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","title":"init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)"},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseInfo\/init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKLicenseStatus","text":"SBSDKLicenseStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isValid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"licenseStatusMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expirationTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expirationDateString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onlineLicenseCheckInProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nextOnlineLicenseCheckInMs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deviceDeregistationErrors"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDeviceDeregistrationError","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDeviceDeregistrationError","text":"SBSDKDeviceDeregistrationError"},{"kind":"text","text":">)"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdklicenseinfo\/init(status:isvalid:licensestatusmessage:expirationtimestamp:expirationdatestring:errormessage:onlinelicensecheckinprogress:license:nextonlinelicensecheckinms:devicederegistationerrors:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdklicenseinfo\/init(status:isvalid:licensestatusmessage:expirationtimestamp:expirationdatestring:errormessage:onlinelicensecheckinprogress:license:nextonlinelicensecheckinms:devicederegistationerrors:)"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseInfo":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKLicenseInfo","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseInfo","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseInfo"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicenseinfo","title":"SBSDKLicenseInfo","type":"topic","abstract":[{"type":"text","text":"Information about the SDK license."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseStatus":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseStatus"}],"title":"SBSDKLicenseStatus","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Status of the license plate scanner.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDeviceDeregistrationError":{"type":"topic","navigatorTitle":[{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDeviceDeregistrationError","abstract":[{"text":"Description of error that occurred during device deregistration.","type":"text"}],"title":"SBSDKDeviceDeregistrationError","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdevicederegistrationerror"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","abstract":[{"text":"Version: 8.0.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseInfo/init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseInfo\/init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicenseinfo\/init(status:isvalid:licensestatusmessage:expirationtimestamp:expirationdatestring:errormessage:onlinelicensecheckinprogress:license:nextonlinelicensecheckinms:devicederegistationerrors:)","title":"init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKLicenseStatus","text":"SBSDKLicenseStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isValid","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"licenseStatusMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"expirationTimestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"expirationDateString","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"errorMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onlineLicenseCheckInProgress"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"license","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"nextOnlineLicenseCheckInMs","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"deviceDeregistationErrors","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"SBSDKDeviceDeregistrationError","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDeviceDeregistrationError","kind":"typeIdentifier"},{"text":">)","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithStatus:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKLicenseStatus","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus","text":"SBSDKLicenseStatus","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isValid:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isValid","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"licenseStatusMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"licenseStatusMessage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"expirationTimestamp:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"expirationTimestamp","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"expirationDateString:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"expirationDateString","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"errorMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"errorMessage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"onlineLicenseCheckInProgress:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onlineLicenseCheckInProgress","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"license:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"license","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"nextOnlineLicenseCheckInMs:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"nextOnlineLicenseCheckInMs","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"deviceDeregistationErrors:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKDeviceDeregistrationError *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"deviceDeregistationErrors","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseInfo\/title","value":"SBSDKLicenseInfo"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseInfo\/fragments","value":[{"text":"SBSDKLicenseInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseInfo\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKLicenseInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus\/title","value":"SBSDKLicenseStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus\/fragments","value":[{"kind":"identifier","text":"SBSDKLicenseStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus\/navigatorTitle","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDeviceDeregistrationError\/title","value":"SBSDKDeviceDeregistrationError"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDeviceDeregistrationError\/fragments","value":[{"kind":"identifier","text":"SBSDKDeviceDeregistrationError"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDeviceDeregistrationError\/navigatorTitle","value":[{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseInfo~1init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)\/title","value":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseInfo~1init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:"}]}]}]}