{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocument","text":"SBSDKGenericDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocument"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"document"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplan\/initwithgenericdocument:"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlan\/initWithGenericDocument:","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlan"]]},"metadata":{"role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithGenericDocument:"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentDEMedicalPlan(im)initWithGenericDocument:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"initWithGenericDocument:","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentDEMedicalPlan/initWithGenericDocument:":{"kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlan\/initWithGenericDocument:","title":"initWithGenericDocument:","type":"topic","abstract":[],"navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplan\/initwithgenericdocument:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentDEMedicalPlan":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlan"}],"title":"SBSDKBarcodeDocumentDEMedicalPlan","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlan"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplan","abstract":[{"text":"Medical Plan.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlan"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocument":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocument"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocument","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocument","abstract":[{"type":"text","text":"Represents a generic document with fields and sub-documents used for document recognition."}],"type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"role":"symbol","title":"SBSDKGenericDocument"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","kind":"symbol","title":"ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"patch":[{"value":"SBSDKBarcodeDocumentDEMedicalPlan","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlan\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlan\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlan"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKBarcodeDocumentDEMedicalPlan","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlan\/navigatorTitle"},{"value":"SBSDKGenericDocument","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}