{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerBehaviorConfiguration\/minimumNumberOfRequiredFramesWithEqualScanningResult","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerBehaviorConfiguration"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","title":"minimumNumberOfRequiredFramesWithEqualScanningResult","role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerBehaviorConfiguration(py)minimumNumberOfRequiredFramesWithEqualScanningResult","navigatorTitle":[{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minimumNumberOfRequiredFramesWithEqualScanningResult","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscannerbehaviorconfiguration\/minimumnumberofrequiredframeswithequalscanningresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscannerbehaviorconfiguration\/minimumnumberofrequiredframeswithequalscanningresult"]}],"abstract":[{"type":"text","text":"The minimum equal results in accumulated video frames to count as valid."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerBehaviorConfiguration/minimumNumberOfRequiredFramesWithEqualScanningResult":{"title":"minimumNumberOfRequiredFramesWithEqualScanningResult","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"}],"abstract":[{"type":"text","text":"The minimum equal results in accumulated video frames to count as valid."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerBehaviorConfiguration\/minimumNumberOfRequiredFramesWithEqualScanningResult","url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerbehaviorconfiguration\/minimumnumberofrequiredframeswithequalscanningresult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerBehaviorConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerbehaviorconfiguration","navigatorTitle":[{"text":"SBSDKUIVINScannerBehaviorConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIVINScannerBehaviorConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerBehaviorConfiguration","kind":"symbol","role":"symbol","abstract":[{"text":"The configuration for the behavior of the RTU-UI vehicle identification number scanner.","type":"text"}],"title":"SBSDKUIVINScannerBehaviorConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"minimumNumberOfRequiredFramesWithEqualScanningResult"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"minimumNumberOfRequiredFramesWithEqualScanningResult","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"minimumNumberOfRequiredFramesWithEqualScanningResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerBehaviorConfiguration~1minimumNumberOfRequiredFramesWithEqualScanningResult\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerBehaviorConfiguration~1minimumNumberOfRequiredFramesWithEqualScanningResult\/fragments","value":[{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"}]},{"value":"SBSDKUIVINScannerBehaviorConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerBehaviorConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerBehaviorConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIVINScannerBehaviorConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerBehaviorConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIVINScannerBehaviorConfiguration","kind":"identifier"}]}]}]}