{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"ocrResolutionLimit","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ocrResolutionLimit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerBehaviorConfiguration(py)ocrResolutionLimit","modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"ocrResolutionLimit"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ocrResolutionLimit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"Setting it to 0 means no limit.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This parameter might be useful for slower devices or to reduce processing load."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerBehaviorConfiguration"]]},"abstract":[{"type":"text","text":"Maximum image side length (height or width) for OCR processing. If the initial image has longer side - it will be downscaled to the limit."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscannerbehaviorconfiguration\/ocrresolutionlimit"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscannerbehaviorconfiguration\/ocrresolutionlimit"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerBehaviorConfiguration\/ocrResolutionLimit"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerBehaviorConfiguration":{"abstract":[{"text":"The configuration for the behavior of the RTU-UI vehicle identification number scanner.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIVINScannerBehaviorConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerbehaviorconfiguration","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerBehaviorConfiguration","title":"SBSDKUIVINScannerBehaviorConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIVINScannerBehaviorConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerBehaviorConfiguration/ocrResolutionLimit":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ocrResolutionLimit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"abstract":[{"text":"Maximum image side length (height or width) for OCR processing. If the initial image has longer side - it will be downscaled to the limit.","type":"text"}],"title":"ocrResolutionLimit","url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerbehaviorconfiguration\/ocrresolutionlimit","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerBehaviorConfiguration\/ocrResolutionLimit","type":"topic","navigatorTitle":[{"text":"ocrResolutionLimit","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"ocrResolutionLimit","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"ocrResolutionLimit","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ocrResolutionLimit"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerBehaviorConfiguration\/title","op":"replace","value":"SBSDKUIVINScannerBehaviorConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerBehaviorConfiguration\/fragments","value":[{"text":"SBSDKUIVINScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIVINScannerBehaviorConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerBehaviorConfiguration\/navigatorTitle"},{"value":"ocrResolutionLimit","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerBehaviorConfiguration~1ocrResolutionLimit\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ocrResolutionLimit"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerBehaviorConfiguration~1ocrResolutionLimit\/fragments"}]}]}