{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Initializes mock data for a simulated camera device from URLs."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSimulatedCameraMockData\/init(label:imageURL:capturedImageURL:refreshOnEachFrame:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSimulatedCameraMockData"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdksimulatedcameramockdata\/init(label:imageurl:capturedimageurl:refreshoneachframe:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdksimulatedcameramockdata\/init(label:imageurl:capturedimageurl:refreshoneachframe:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"role":"symbol","symbolKind":"init","navigatorTitle":[{"text":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","kind":"identifier"}],"roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"title":"init(label:imageURL:capturedImageURL:refreshOnEachFrame:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"label"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"imageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"capturedImageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"refreshOnEachFrame"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSimulatedCameraMockData(im)initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:) "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"label","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"imageURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"capturedImageURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"? = nil, ","kind":"text"},{"text":"refreshOnEachFrame","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The label to describe the mock data."}]}],"name":"label"},{"name":"imageURL","content":[{"type":"paragraph","inlineContent":[{"text":"A web or file URL to an image file to be used to feed the video stream of simulated camera device.","type":"text"}]}]},{"name":"capturedImageURL","content":[{"inlineContent":[{"type":"text","text":"A web or file URL to an image to be used on simulated camera devices when capturing a still image. If "},{"code":"nil","type":"codeVoice"},{"type":"text","text":", the current frame of the "},{"code":"imageURL","type":"codeVoice"},{"text":" is returned when capturing a still image.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"If set to "},{"code":"true","type":"codeVoice"},{"text":" the image is reloaded\/downloaded after each frame. Otherwise the image is loaded only once and reused per frame.","type":"text"}],"type":"paragraph"}],"name":"refreshOnEachFrame"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSimulatedCameraMockData/init(label:imageURL:capturedImageURL:refreshOnEachFrame:)":{"role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"imageURL","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":", ","kind":"text"},{"text":"capturedImageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"refreshOnEachFrame"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"init(label:imageURL:capturedImageURL:refreshOnEachFrame:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSimulatedCameraMockData\/init(label:imageURL:capturedImageURL:refreshOnEachFrame:)","navigatorTitle":[{"kind":"identifier","text":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:"}],"abstract":[{"text":"Initializes mock data for a simulated camera device from URLs.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdksimulatedcameramockdata\/init(label:imageurl:capturedimageurl:refreshoneachframe:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSimulatedCameraMockData":{"type":"topic","abstract":[{"type":"text","text":"A class to describe the mocking data that is fed to a simulated camera device."}],"url":"\/documentation\/scanbotsdk\/sbsdksimulatedcameramockdata","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSimulatedCameraMockData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"title":"SBSDKSimulatedCameraMockData","navigatorTitle":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLabel:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"label"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageURL:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"imageURL","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"capturedImageURL:"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"capturedImageURL","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshOnEachFrame:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"refreshOnEachFrame","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The label to describe the mock data.","type":"text"}]}],"name":"label"},{"name":"imageURL","content":[{"inlineContent":[{"type":"text","text":"A web or file URL to an image file to be used to feed the video stream of simulated camera device."}],"type":"paragraph"}]},{"name":"capturedImageURL","content":[{"inlineContent":[{"type":"text","text":"A web or file URL to an image to be used on simulated camera devices when capturing a still image. If "},{"code":"nil","type":"codeVoice"},{"text":", the current frame of the ","type":"text"},{"code":"imageURL","type":"codeVoice"},{"text":" is returned when capturing a still image.","type":"text"}],"type":"paragraph"}]},{"name":"refreshOnEachFrame","content":[{"inlineContent":[{"text":"If set to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":" the image is reloaded\/downloaded after each frame. Otherwise the image is loaded only once and reused per frame."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSimulatedCameraMockData~1init(label:imageURL:capturedImageURL:refreshOnEachFrame:)\/title","value":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSimulatedCameraMockData~1init(label:imageURL:capturedImageURL:refreshOnEachFrame:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","kind":"identifier"}]},{"value":"SBSDKSimulatedCameraMockData","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSimulatedCameraMockData\/title","op":"replace"},{"value":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSimulatedCameraMockData\/fragments","op":"replace"},{"value":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSimulatedCameraMockData\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}