{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGrayscaleFilter\/borderWidthFraction","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"borderWidthFraction","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGrayscaleFilter(py)borderWidthFraction","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"borderWidthFraction","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"borderWidthFraction","kind":"identifier"}],"role":"symbol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderWidthFraction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is 0.06","type":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Ignore this fraction of pixels at the edge of the image when calculating statistics.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Pixels at the edge of the image typically have poor statistics. Ignoring them"},{"type":"text","text":" "},{"type":"text","text":"and using only the inner pixels when calculating certain statistics can"},{"type":"text","text":" "},{"type":"text","text":"substantially improve the quality of the result."},{"type":"text","text":" "},{"type":"text","text":"The value must be less than 0.5 but usually good values are between 0 and 0.15."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGrayscaleFilter"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgrayscalefilter\/borderwidthfraction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgrayscalefilter\/borderwidthfraction"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGrayscaleFilter/borderWidthFraction":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGrayscaleFilter\/borderWidthFraction","type":"topic","navigatorTitle":[{"kind":"identifier","text":"borderWidthFraction"}],"title":"borderWidthFraction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderWidthFraction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"text":"Ignore this fraction of pixels at the edge of the image when calculating statistics.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Pixels at the edge of the image typically have poor statistics. Ignoring them"},{"type":"text","text":" "},{"type":"text","text":"and using only the inner pixels when calculating certain statistics can"},{"type":"text","text":" "},{"type":"text","text":"substantially improve the quality of the result."},{"type":"text","text":" "},{"type":"text","text":"The value must be less than 0.5 but usually good values are between 0 and 0.15."}],"url":"\/documentation\/scanbotsdk\/sbsdkgrayscalefilter\/borderwidthfraction","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGrayscaleFilter":{"navigatorTitle":[{"text":"SBSDKGrayscaleFilter","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGrayscaleFilter","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGrayscaleFilter","kind":"identifier"}],"role":"symbol","title":"SBSDKGrayscaleFilter","abstract":[{"text":"Converts color images to grayscale and applies autocontrast.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgrayscalefilter"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"borderWidthFraction","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"borderWidthFraction","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"borderWidthFraction","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"borderWidthFraction","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGrayscaleFilter~1borderWidthFraction\/title"},{"value":[{"text":"borderWidthFraction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGrayscaleFilter~1borderWidthFraction\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGrayscaleFilter\/title","value":"SBSDKGrayscaleFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGrayscaleFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKGrayscaleFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGrayscaleFilter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGrayscaleFilter"}]}]}]}