{"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKResultAccumulationConfiguration(py)hash","fragments":[{"text":"hash","kind":"identifier"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"hash","kind":"identifier"}],"title":"hash"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkresultaccumulationconfiguration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration\/hash"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResultAccumulationConfiguration/hash":{"kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"hash"}],"abstract":[],"title":"hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration\/hash","url":"\/documentation\/scanbotsdk\/sbsdkresultaccumulationconfiguration\/hash","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResultAccumulationConfiguration":{"title":"SBSDKResultAccumulationConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}],"abstract":[{"text":"Configuration for how to accumulate results.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkresultaccumulationconfiguration","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/title","value":"SBSDKResultAccumulationConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/fragments","value":[{"text":"SBSDKResultAccumulationConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/navigatorTitle","value":[{"text":"SBSDKResultAccumulationConfiguration","kind":"identifier"}]}]}]}