{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"writingImageFileFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKImageFileFormat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageFileFormat","text":"SBSDKImageFileFormat"},{"kind":"text","text":" { get }"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageFileFormat\/JPEG","isActive":true},{"type":"text","text":"."}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeImageStorage"]]},"sections":[],"kind":"symbol","abstract":[{"text":"File format of the stored images.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodeimagestorage\/writingimagefileformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodeimagestorage\/writingimagefileformat"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","title":"writingImageFileFormat","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeImageStorage(py)writingImageFileFormat","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"writingImageFileFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKImageFileFormat","text":"SBSDKImageFileFormat"}],"navigatorTitle":[{"text":"writingImageFileFormat","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeImageStorage\/writingImageFileFormat","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerViewController":{"type":"topic","navigatorTitle":[{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to detect QR and barcodes."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController","deprecated":true,"kind":"symbol","role":"symbol","title":"SBSDKUIBarcodeScannerViewController","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescannerviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageFileFormat":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagefileformat","abstract":[{"type":"text","text":"Enumeration of supported image file types."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageFileFormat","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFileFormat"}],"type":"topic","title":"SBSDKImageFileFormat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageFileFormat","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageFileFormat/JPEG":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JPEG"}],"title":"SBSDKImageFileFormat.JPEG","abstract":[{"type":"text","text":"The image file is a JPEG."}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageFileFormat\/JPEG","navigatorTitle":[{"text":"SBSDKImageFileFormatJPEG","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagefileformat\/jpeg"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeImageStorage/writingImageFileFormat":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"writingImageFileFormat"},{"text":": ","kind":"text"},{"text":"SBSDKImageFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKImageFileFormat"}],"role":"symbol","title":"writingImageFileFormat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeImageStorage\/writingImageFileFormat","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodeimagestorage\/writingimagefileformat","navigatorTitle":[{"kind":"identifier","text":"writingImageFileFormat"}],"abstract":[{"text":"File format of the stored images.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeImageStorage":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodeimagestorage","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeImageStorage","abstract":[{"type":"text","text":"A class to store and remove barcode images from "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerViewController"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"SBSDKUIBarcodeImageStorage","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SBSDKUIBarcodeImageStorage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeImageStorage","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"writingImageFileFormat","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"writingImageFileFormat","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKImageFileFormat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageFileFormat","text":"SBSDKImageFileFormat"},{"text":" ","kind":"text"},{"text":"writingImageFileFormat","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"SBSDKUIBarcodeScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController\/fragments","value":[{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerViewController\/navigatorTitle","value":[{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"op":"replace"},{"value":"SBSDKImageFileFormat","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageFileFormat\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageFileFormat"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageFileFormat\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageFileFormat\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageFileFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageFileFormat~1JPEG\/title","op":"replace","value":"SBSDKImageFileFormatJPEG"},{"op":"replace","value":[{"text":"SBSDKImageFileFormatJPEG","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageFileFormat~1JPEG\/fragments"},{"value":"writingImageFileFormat","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeImageStorage~1writingImageFileFormat\/title","op":"replace"},{"value":[{"text":"writingImageFileFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeImageStorage~1writingImageFileFormat\/fragments"},{"value":"SBSDKUIBarcodeImageStorage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeImageStorage\/title"},{"op":"replace","value":[{"text":"SBSDKUIBarcodeImageStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeImageStorage\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeImageStorage\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodeImageStorage"}]}]}]}