{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraAutoSnapButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityDescriptionCameraAutoSnapButton"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization(py)accessibilityDescriptionCameraAutoSnapButton","title":"accessibilityDescriptionCameraAutoSnapButton","roleHeading":"Instance Property","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization\/accessibilityDescriptionCameraAutoSnapButton"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization\/accessibilitydescriptioncameraautosnapbutton"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization\/accessibilitydescriptioncameraautosnapbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The accessibility hint for the ‘auto snapping’ mode button, located in the bottom bar of the camera screen."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraAutoSnapButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is “Tap to enable manual snapping mode”","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerTextLocalization/accessibilityDescriptionCameraAutoSnapButton":{"kind":"symbol","abstract":[{"text":"The accessibility hint for the ‘auto snapping’ mode button, located in the bottom bar of the camera screen.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraAutoSnapButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","title":"accessibilityDescriptionCameraAutoSnapButton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization\/accessibilityDescriptionCameraAutoSnapButton","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization\/accessibilitydescriptioncameraautosnapbutton","role":"symbol","navigatorTitle":[{"text":"accessibilityDescriptionCameraAutoSnapButton","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerTextLocalization":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization","title":"SBSDKUI2DocumentScannerTextLocalization","abstract":[{"text":"Configuration of all the strings for the standalone cropping screen.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"accessibilityDescriptionCameraAutoSnapButton","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"accessibilityDescriptionCameraAutoSnapButton","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"accessibilityDescriptionCameraAutoSnapButton"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"accessibilityDescriptionCameraAutoSnapButton","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization~1accessibilityDescriptionCameraAutoSnapButton\/title","op":"replace"},{"value":[{"kind":"identifier","text":"accessibilityDescriptionCameraAutoSnapButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization~1accessibilityDescriptionCameraAutoSnapButton\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/title","value":"SBSDKUI2DocumentScannerTextLocalization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/fragments","value":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}]}]}]}