{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerview\/defaulthovereffect(_:)-2370k"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView\/defaultHoverEffect(_:)-2370k","interfaceLanguage":"swift"},"metadata":{"externalID":"s:7SwiftUI4ViewPAAE18defaultHoverEffectyQrAA0eF0VSgF::SYNTHESIZED::s:10ScanbotSDK26SBSDKUI2BarcodeScannerViewV","role":"symbol","extendedModule":"SwiftUICore","platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"17.0","beta":false,"name":"iOS"},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"17.0"},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"17.0"},{"introducedAt":"17.0","name":"tvOS","deprecated":false,"unavailable":false,"beta":false},{"deprecated":false,"beta":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"defaultHoverEffect","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI11HoverEffectV","text":"HoverEffect"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"symbolKind":"method","title":"defaultHoverEffect(_:)","modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotSDK"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultHoverEffect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"effect","kind":"internalParam"},{"kind":"text","text":": "},{"text":"HoverEffect","preciseIdentifier":"s:7SwiftUI11HoverEffectV","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"},{"text":"\n","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView\/View-Implementations"]]},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.defaultHoverEffect(_:)"},{"text":".","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerView":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeScannerView"}],"kind":"symbol","abstract":[{"type":"text","text":"The SwiftUI wrapper for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerViewController"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView","title":"SBSDKUI2BarcodeScannerView","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerView","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerview"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerViewController":{"type":"topic","abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to scan QR and barcodes."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerviewcontroller","title":"SBSDKUI2BarcodeScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerView/defaultHoverEffect(_:)-2370k":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerview\/defaulthovereffect(_:)-2370k","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultHoverEffect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"HoverEffect","preciseIdentifier":"s:7SwiftUI11HoverEffectV"},{"text":"?) -> ","kind":"text"},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"role":"symbol","kind":"symbol","title":"defaultHoverEffect(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView\/defaultHoverEffect(_:)-2370k"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerView/View-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView\/View-Implementations","kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerview\/view-implementations","type":"topic","abstract":[],"title":"View Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2BarcodeScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController\/title"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController\/navigatorTitle","value":[{"text":"SBSDKUI2BarcodeScannerViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}