{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFeedbackMode"]]},"metadata":{"navigatorTitle":[{"text":"pageSnapFeedbackNone","kind":"identifier"}],"title":"pageSnapFeedbackNone()","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PageSnapFeedbackMode(cm)pageSnapFeedbackNone","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageSnapFeedbackNone","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PageSnapFeedbackNone","text":"SBSDKUI2PageSnapFeedbackNone","kind":"typeIdentifier"}],"symbolKind":"method","roleHeading":"Type Method","role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2pagesnapfeedbackmode\/pagesnapfeedbacknone()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2pagesnapfeedbackmode\/pagesnapfeedbacknone()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFeedbackMode\/pageSnapFeedbackNone()"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageSnapFeedbackNone","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PageSnapFeedbackNone","text":"SBSDKUI2PageSnapFeedbackNone","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFeedbackNone"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PageSnapFeedbackNone":{"navigatorTitle":[{"text":"SBSDKUI2PageSnapFeedbackNone","kind":"identifier"}],"kind":"symbol","title":"SBSDKUI2PageSnapFeedbackNone","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFeedbackNone","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2pagesnapfeedbacknone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PageSnapFeedbackNone","kind":"identifier"}],"abstract":[{"type":"text","text":"To not use a snap animation."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PageSnapFeedbackMode":{"abstract":[{"text":"The type of animation to display after snapping a page.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackMode"}],"title":"SBSDKUI2PageSnapFeedbackMode","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2pagesnapfeedbackmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFeedbackMode","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PageSnapFeedbackMode/pageSnapFeedbackNone()":{"title":"pageSnapFeedbackNone()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFeedbackMode\/pageSnapFeedbackNone()","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageSnapFeedbackNone"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKUI2PageSnapFeedbackNone","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PageSnapFeedbackNone"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pageSnapFeedbackNone"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2pagesnapfeedbackmode\/pagesnapfeedbacknone()","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"pageSnapFeedbackNone","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"pageSnapFeedbackNone","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFeedbackNone","text":"SBSDKUI2PageSnapFeedbackNone","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PageSnapFeedbackNone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"pageSnapFeedbackNone","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUI2PageSnapFeedbackNone","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackNone\/title"},{"op":"replace","value":[{"text":"SBSDKUI2PageSnapFeedbackNone","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackNone\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackNone"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackNone\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2PageSnapFeedbackMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackMode\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2PageSnapFeedbackMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackMode\/navigatorTitle"},{"op":"replace","value":"pageSnapFeedbackNone","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackMode~1pageSnapFeedbackNone()\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"pageSnapFeedbackNone","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackMode~1pageSnapFeedbackNone()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}