{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult"]]},"metadata":{"navigatorTitle":[{"text":"wordBoxes","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult(py)wordBoxes","role":"symbol","title":"wordBoxes","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wordBoxes"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKWordBox","text":"SBSDKWordBox","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult\/wordboxes"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult\/wordboxes"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult\/wordBoxes"},"abstract":[{"text":"Boxes for each recognized word.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"wordBoxes"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWordBox","text":"SBSDKWordBox","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKWordBox"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerResult":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult","abstract":[{"text":"The result of the text line recognition.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerResult"}],"title":"SBSDKTextPatternScannerResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerResult/wordBoxes":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wordBoxes"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKWordBox","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKWordBox"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"Boxes for each recognized word."}],"title":"wordBoxes","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult\/wordboxes","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult\/wordBoxes","type":"topic","navigatorTitle":[{"kind":"identifier","text":"wordBoxes"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWordBox":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKWordBox"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkwordbox","abstract":[{"type":"text","text":"Structure containing recognized word text and bounds."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWordBox","title":"SBSDKWordBox","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKWordBox","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"wordBoxes","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"wordBoxes"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSArray<SBSDKWordBox *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"wordBoxes","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKTextPatternScannerResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerResult"}],"op":"replace"},{"value":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult~1wordBoxes\/title","value":"wordBoxes"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult~1wordBoxes\/fragments","op":"replace","value":[{"kind":"identifier","text":"wordBoxes"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWordBox\/title","value":"SBSDKWordBox","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWordBox\/fragments","op":"replace","value":[{"text":"SBSDKWordBox","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKWordBox"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWordBox\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}