{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller\/init(parentviewcontroller:parentview:delegate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller\/init(parentviewcontroller:parentview:delegate:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"parentViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"parentView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKMRZScannerViewControllerDelegate","text":"SBSDKMRZScannerViewControllerDelegate"},{"kind":"text","text":"?)"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller the newly created instance is embedded into."}]}],"name":"parentViewController"},{"name":"parentView","content":[{"type":"paragraph","inlineContent":[{"text":"The view the newly created instance is embedded into.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The delegate of the receiver. if ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" and the ","type":"text"},{"type":"codeVoice","code":"parentViewController"},{"text":" conforms to the","type":"text"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate"},{"type":"text","text":" protocol, the "},{"type":"codeVoice","code":"parentViewController"},{"type":"text","text":" is automatically set as delegate."}]}],"name":"delegate"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController\/init(parentViewController:parentView:delegate:)"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController(im)initWithParentViewController:parentView:delegate:","role":"symbol","roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"ScanbotSDK"}],"title":"init(parentViewController:parentView:delegate:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"parentViewController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"parentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKMRZScannerViewControllerDelegate","text":"SBSDKMRZScannerViewControllerDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"initWithParentViewController:parentView:delegate:","kind":"identifier"}]},"abstract":[{"type":"text","text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewController":{"role":"symbol","navigatorTitle":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMRZScannerViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Classic UI view controller that can be used to scan machine-readable zones.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller","title":"SBSDKMRZScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewController/init(parentViewController:parentView:delegate:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController\/init(parentViewController:parentView:delegate:)","title":"init(parentViewController:parentView:delegate:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"parentViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":", "},{"text":"parentView","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKMRZScannerViewControllerDelegate","text":"SBSDKMRZScannerViewControllerDelegate"},{"text":"?)","kind":"text"}],"abstract":[{"text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller\/init(parentviewcontroller:parentview:delegate:)","navigatorTitle":[{"kind":"identifier","text":"initWithParentViewController:parentView:delegate:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewControllerDelegate":{"abstract":[{"text":"The delegation protocol for the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController"},{"type":"text","text":" class."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMRZScannerViewControllerDelegate"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate","title":"SBSDKMRZScannerViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate","navigatorTitle":[{"text":"SBSDKMRZScannerViewControllerDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithParentViewController:parentView:delegate:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithParentViewController:parentView:delegate:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithParentViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":" *) "},{"text":"parentViewController","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"parentView:"},{"text":"(","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"parentView"},{"text":" ","kind":"text"},{"text":"delegate:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKMRZScannerViewControllerDelegate","text":"id<SBSDKMRZScannerViewControllerDelegate>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"delegate"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/title","value":"SBSDKMRZScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController~1init(parentViewController:parentView:delegate:)\/title","op":"replace","value":"initWithParentViewController:parentView:delegate:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController~1init(parentViewController:parentView:delegate:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithParentViewController:parentView:delegate:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate\/title","value":"SBSDKMRZScannerViewControllerDelegate"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMRZScannerViewControllerDelegate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate\/fragments"}]}]}