{"abstract":[{"type":"text","text":"The maximum number of results to be accumulated when live-recognizing machine-readable zones on sample buffers."}],"metadata":{"role":"symbol","title":"maxNumberOfAccumulatedResults","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController(py)maxNumberOfAccumulatedResults","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"maxNumberOfAccumulatedResults","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxNumberOfAccumulatedResults"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxNumberOfAccumulatedResults"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"This sets the second part of the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController\/requiredNumberOfEqualAccumulatedResults","type":"reference","isActive":true},{"type":"text","text":" of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController\/maxNumberOfAccumulatedResults","isActive":true,"type":"reference"},{"type":"text","text":" selector,"},{"text":" ","type":"text"},{"type":"text","text":"e.g. 2 of 4 results must be equal."},{"type":"text","text":" "},{"type":"text","text":"To make the selector less strict, select a higher value, e.g. 2 of 5 or even 2 of 6."},{"text":" ","type":"text"},{"text":"Setting a value lower than the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController\/requiredNumberOfEqualAccumulatedResults","isActive":true,"type":"reference"},{"text":" will throw an exception.","type":"text"},{"type":"text","text":" "},{"text":"Values less-than-or-equal to 0, will effectively turn off the result accumulation.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Defaults to 4.","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller\/maxnumberofaccumulatedresults"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller\/maxnumberofaccumulatedresults"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController\/maxNumberOfAccumulatedResults","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewController":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller","role":"symbol","navigatorTitle":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKMRZScannerViewController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan machine-readable zones."}],"title":"SBSDKMRZScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewController/maxNumberOfAccumulatedResults":{"abstract":[{"type":"text","text":"The maximum number of results to be accumulated when live-recognizing machine-readable zones on sample buffers."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"maxNumberOfAccumulatedResults","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"maxNumberOfAccumulatedResults","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"title":"maxNumberOfAccumulatedResults","url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller\/maxnumberofaccumulatedresults","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController\/maxNumberOfAccumulatedResults","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewController/requiredNumberOfEqualAccumulatedResults":{"abstract":[{"type":"text","text":"The minimum number of equal results in the accumulator when live-recognizing machine-readable zones on sample buffers."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"title":"requiredNumberOfEqualAccumulatedResults","url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller\/requirednumberofequalaccumulatedresults","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController\/requiredNumberOfEqualAccumulatedResults","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"maxNumberOfAccumulatedResults","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"maxNumberOfAccumulatedResults","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":" "},{"text":"maxNumberOfAccumulatedResults","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/title","op":"replace","value":"SBSDKMRZScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/fragments","value":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}]},{"op":"replace","value":"maxNumberOfAccumulatedResults","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController~1maxNumberOfAccumulatedResults\/title"},{"op":"replace","value":[{"kind":"identifier","text":"maxNumberOfAccumulatedResults"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController~1maxNumberOfAccumulatedResults\/fragments"},{"value":"requiredNumberOfEqualAccumulatedResults","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController~1requiredNumberOfEqualAccumulatedResults\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController~1requiredNumberOfEqualAccumulatedResults\/fragments","value":[{"kind":"identifier","text":"requiredNumberOfEqualAccumulatedResults"}]}]}]}