{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatgs1compositeconfiguration\/new"]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration\/new","interfaceLanguage":"occ"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatGS1CompositeConfiguration(cm)new","title":"new","symbolKind":"method","roleHeading":"Type Method","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"new"}],"navigatorTitle":[{"text":"new","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"new"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatGS1CompositeConfiguration/new":{"title":"new","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatgs1compositeconfiguration\/new","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration\/new","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"new"}],"abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"new"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatGS1CompositeConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatgs1compositeconfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration","abstract":[{"text":"GS1 Composite configuration. Add to scanner configuration to scan GS1 Composite barcodes.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"}],"kind":"symbol","title":"SBSDKBarcodeFormatGS1CompositeConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/title","value":"SBSDKBarcodeFormatGS1CompositeConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeFormatGS1CompositeConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"}]}]}]}