{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickArOverlayPolygonConfiguration\/init()","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FindAndPickArOverlayPolygonConfiguration(im)init","roleHeading":"Initializer","symbolKind":"init","role":"symbol","title":"init()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2findandpickaroverlaypolygonconfiguration\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2findandpickaroverlaypolygonconfiguration\/init()"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickArOverlayPolygonConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickArOverlayPolygonConfiguration/init()":{"role":"symbol","type":"topic","title":"init()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickArOverlayPolygonConfiguration\/init()","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickaroverlaypolygonconfiguration\/init()","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickArOverlayPolygonConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickArOverlayPolygonConfiguration","abstract":[{"type":"text","text":"Configuration of the overlay polygon displayed on top of a barcode in the camera preview."}],"type":"topic","title":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickaroverlaypolygonconfiguration"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"init","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickArOverlayPolygonConfiguration~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickArOverlayPolygonConfiguration~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickArOverlayPolygonConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickArOverlayPolygonConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickArOverlayPolygonConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}