{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/successoverlay"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/successoverlay"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/successOverlay"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"successOverlay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ScanCompletionOverlay","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanCompletionOverlay","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanCompletionOverlay"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Configuration of the success overlay.","type":"text"}],"metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","title":"successOverlay","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"successOverlay","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"successOverlay"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2ScanCompletionOverlay","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanCompletionOverlay"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerScreenConfiguration(py)successOverlay"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/successOverlay":{"abstract":[{"type":"text","text":"Configuration of the success overlay."}],"title":"successOverlay","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/successoverlay","role":"symbol","navigatorTitle":[{"text":"successOverlay","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/successOverlay","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"successOverlay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanCompletionOverlay","text":"SBSDKUI2ScanCompletionOverlay","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ScanCompletionOverlay":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ScanCompletionOverlay"}],"abstract":[{"type":"text","text":"Configuration of the overlay to be shown after the successful scan."}],"type":"topic","kind":"symbol","title":"SBSDKUI2ScanCompletionOverlay","navigatorTitle":[{"text":"SBSDKUI2ScanCompletionOverlay","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanCompletionOverlay","url":"\/documentation\/scanbotsdk\/sbsdkui2scancompletionoverlay","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration":{"abstract":[{"text":"Configuration of the screen for detecting credit card data.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardScannerScreenConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration","role":"symbol","title":"SBSDKUI2CreditCardScannerScreenConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"successOverlay","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"successOverlay","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"SBSDKUI2ScanCompletionOverlay","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanCompletionOverlay","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanCompletionOverlay"},{"text":" * ","kind":"text"},{"text":"successOverlay","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"successOverlay","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1successOverlay\/title"},{"value":[{"text":"successOverlay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1successOverlay\/fragments"},{"value":"SBSDKUI2ScanCompletionOverlay","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanCompletionOverlay\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2ScanCompletionOverlay"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanCompletionOverlay\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2ScanCompletionOverlay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanCompletionOverlay\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration\/title","op":"replace","value":"SBSDKUI2CreditCardScannerScreenConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2CreditCardScannerScreenConfiguration","kind":"identifier"}]}]}]}