{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration\/acceptedBrightnessThreshold","interfaceLanguage":"swift"},"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerbehaviorconfiguration\/acceptedbrightnessthreshold"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerbehaviorconfiguration\/acceptedbrightnessthreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration"]]},"kind":"symbol","abstract":[{"text":"The brightness threshold to accept a scanned document in the range of 0 (very dark) to 255 (very bright).","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If  the average brightness value of the scanners input image is below this value, the status of the detection will be set to"},{"text":" ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/errorTooDark","isActive":true,"type":"reference"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerBehaviorConfiguration(py)acceptedBrightnessThreshold","roleHeading":"Instance Property","title":"acceptedBrightnessThreshold","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"acceptedBrightnessThreshold","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"platforms":[],"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"acceptedBrightnessThreshold","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"acceptedBrightnessThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"text":"Minimum value: 0, maximum value: 255. Defaults to 50.","type":"text"}],"type":"paragraph"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerBehaviorConfiguration":{"deprecated":true,"role":"symbol","kind":"symbol","title":"SBSDKUIDocumentScannerBehaviorConfiguration","abstract":[{"text":"Configuration for the behavior of the document scanning screen.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerbehaviorconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/errorTooDark":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorTooDark","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"No document was detected, likely because the input image is too dark."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/errorTooDark","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusErrorTooDark"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/errortoodark","role":"symbol","title":"SBSDKDocumentDetectionStatus.errorTooDark"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerBehaviorConfiguration/acceptedBrightnessThreshold":{"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedBrightnessThreshold"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"role":"symbol","title":"acceptedBrightnessThreshold","navigatorTitle":[{"kind":"identifier","text":"acceptedBrightnessThreshold"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration\/acceptedBrightnessThreshold","abstract":[{"type":"text","text":"The brightness threshold to accept a scanned document in the range of 0 (very dark) to 255 (very bright)."},{"text":" ","type":"text"},{"text":"If  the average brightness value of the scanners input image is below this value, the status of the detection will be set to","type":"text"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/errorTooDark","type":"reference"},{"type":"text","text":"."}],"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerbehaviorconfiguration\/acceptedbrightnessthreshold"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"acceptedBrightnessThreshold","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"acceptedBrightnessThreshold","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"text":"acceptedBrightnessThreshold","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","value":"SBSDKUIDocumentScannerBehaviorConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1errorTooDark\/title","value":"SBSDKDocumentDetectionStatusErrorTooDark","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusErrorTooDark"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1errorTooDark\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration~1acceptedBrightnessThreshold\/title","value":"acceptedBrightnessThreshold"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration~1acceptedBrightnessThreshold\/fragments","op":"replace","value":[{"text":"acceptedBrightnessThreshold","kind":"identifier"}]}]}]}