{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration"]]},"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2DocumentScannerViewController instead."}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerbehaviorconfiguration\/camerapreviewmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerbehaviorconfiguration\/camerapreviewmode"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKVideoContentMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoContentMode"}],"roleHeading":"Instance Property","title":"cameraPreviewMode","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","navigatorTitle":[{"text":"cameraPreviewMode","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerBehaviorConfiguration(py)cameraPreviewMode","platforms":[]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration\/cameraPreviewMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The video layers content mode."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cameraPreviewMode","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode","kind":"typeIdentifier","text":"SBSDKVideoContentMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoContentMode"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerBehaviorConfiguration/cameraPreviewMode":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPreviewMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKVideoContentMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoContentMode","kind":"typeIdentifier"}],"title":"cameraPreviewMode","abstract":[{"text":"The video layers content mode.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration\/cameraPreviewMode","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerbehaviorconfiguration\/camerapreviewmode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cameraPreviewMode"}],"deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerBehaviorConfiguration":{"deprecated":true,"role":"symbol","kind":"symbol","title":"SBSDKUIDocumentScannerBehaviorConfiguration","abstract":[{"text":"Configuration for the behavior of the document scanning screen.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerbehaviorconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerBehaviorConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoContentMode":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvideocontentmode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoContentMode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoContentMode"}],"title":"SBSDKVideoContentMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode","abstract":[{"type":"text","text":"Enumeration of video preview content mode."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"cameraPreviewMode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cameraPreviewMode"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoContentMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode","text":"SBSDKVideoContentMode","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewMode"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"cameraPreviewMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration~1cameraPreviewMode\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration~1cameraPreviewMode\/fragments","value":[{"text":"cameraPreviewMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/title","op":"replace","value":"SBSDKUIDocumentScannerBehaviorConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/navigatorTitle","op":"replace"},{"op":"replace","value":"SBSDKVideoContentMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoContentMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKVideoContentMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}