{"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}],"type":"paragraph"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(presentOn:document:configuration:delegate:) "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":" "},{"kind":"internalParam","text":"presenter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","text":"SBSDKDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerConfiguration","text":"SBSDKUIDocumentScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIDocumentScannerViewControllerDelegate","text":"SBSDKUIDocumentScannerViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerViewController","text":"SBSDKUIDocumentScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The view controller the new instance should be presented on."}],"type":"paragraph"}],"name":"presenter"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The document to which the scanned pages will be added. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" the receiver creates a new document."}]}],"name":"document"},{"content":[{"inlineContent":[{"type":"text","text":"The configuration to define look and feel of the new scanning view controller."}],"type":"paragraph"}],"name":"configuration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate of the new scanning view controller."}]}],"name":"delegate"}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new instance of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController"},{"type":"text","text":"."}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController"},{"type":"text","text":" and presents it modally."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller\/present(on:document:configuration:delegate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller\/present(on:document:configuration:delegate:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/present(on:document:configuration:delegate:)"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"presentOn:document:configuration:delegate:"}],"roleHeading":"Type Method","role":"symbol","platforms":[],"modules":[{"name":"ScanbotSDK"}],"title":"present(on:document:configuration:delegate:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerViewController(cm)presentOn:document:configuration:delegate:","symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","kind":"typeIdentifier","text":"SBSDKDocument"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerConfiguration","kind":"typeIdentifier","text":"SBSDKUIDocumentScannerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIDocumentScannerViewControllerDelegate","kind":"typeIdentifier","text":"SBSDKUIDocumentScannerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerViewController","kind":"typeIdentifier","text":"SBSDKUIDocumentScannerViewController"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerViewController/present(on:document:configuration:delegate:)":{"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller\/present(on:document:configuration:delegate:)","title":"present(on:document:configuration:delegate:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/present(on:document:configuration:delegate:)","type":"topic","abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController"},{"type":"text","text":" and presents it modally."}],"role":"symbol","deprecated":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUIDocumentScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUIDocumentScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIDocumentScannerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SBSDKUIDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"presentOn:document:configuration:delegate:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerConfiguration":{"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerconfiguration","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerConfiguration"}],"abstract":[{"type":"text","text":"This class describes the look and feel, the behavior, as well as the textual contents of the detection screen for documents."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerConfiguration"}],"type":"topic","title":"SBSDKUIDocumentScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerViewControllerDelegate":{"abstract":[{"type":"text","text":"Delegate protocol for "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController","isActive":true},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerViewControllerDelegate"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewControllerDelegate","kind":"symbol","title":"SBSDKUIDocumentScannerViewControllerDelegate","role":"symbol","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPage"}],"type":"topic","title":"SBSDKDocumentPage","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller","title":"SBSDKUIDocumentScannerViewController","navigatorTitle":[{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}],"type":"topic","abstract":[],"deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocument":{"type":"topic","role":"symbol","title":"SBSDKDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocument"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocument","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocument"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument","kind":"symbol","abstract":[{"type":"text","text":"A thread-safe, mutable container for scanned pages of type "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","isActive":true},{"type":"text","text":"."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"presentOn:document:configuration:delegate:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"presentOn:document:configuration:delegate:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUIDocumentScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerViewController"},{"text":" *) ","kind":"text"},{"text":"presentOn:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"text":"presenter","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"document:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKDocument","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"configuration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIDocumentScannerConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"delegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SBSDKUIDocumentScannerViewControllerDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKUIDocumentScannerViewControllerDelegate"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"presenter","content":[{"inlineContent":[{"text":"The view controller the new instance should be presented on.","type":"text"}],"type":"paragraph"}]},{"name":"document","content":[{"inlineContent":[{"type":"text","text":"The document to which the scanned pages will be added. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" the receiver creates a new document."}],"type":"paragraph"}]},{"name":"configuration","content":[{"inlineContent":[{"text":"The configuration to define look and feel of the new scanning view controller.","type":"text"}],"type":"paragraph"}]},{"name":"delegate","content":[{"inlineContent":[{"type":"text","text":"The delegate of the new scanning view controller."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A new instance of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}]}],"kind":"content"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController~1present(on:document:configuration:delegate:)\/title","value":"presentOn:document:configuration:delegate:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController~1present(on:document:configuration:delegate:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"presentOn:document:configuration:delegate:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerConfiguration\/title","value":"SBSDKUIDocumentScannerConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerConfiguration\/fragments","value":[{"text":"SBSDKUIDocumentScannerConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewControllerDelegate\/title","value":"SBSDKUIDocumentScannerViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKUIDocumentScannerViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title","value":"SBSDKDocumentPage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/navigatorTitle","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController\/title","value":"SBSDKUIDocumentScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController\/fragments","value":[{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController\/navigatorTitle","value":[{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/title","value":"SBSDKDocument","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/fragments","value":[{"text":"SBSDKDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/navigatorTitle","value":[{"text":"SBSDKDocument","kind":"identifier"}],"op":"replace"}]}]}