{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCheckStandard","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckStandard","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckstandard\/ind"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckstandard\/ind"]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard\/ind"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard"]]},"kind":"symbol","metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ind","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCheckStandard","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckStandard"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckStandard(cpy)ind","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Property","title":"ind","navigatorTitle":[{"text":"ind","kind":"identifier"}],"role":"symbol","symbolKind":"property"},"abstract":[{"type":"text","text":"A check compatible with the CTS-2010 standard issued by the Reserve Bank of India in 2012."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckStandard/ind":{"role":"symbol","title":"ind","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckStandard","text":"SBSDKCheckStandard"}],"abstract":[{"type":"text","text":"A check compatible with the CTS-2010 standard issued by the Reserve Bank of India in 2012."}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcheckstandard\/ind","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard\/ind","navigatorTitle":[{"kind":"identifier","text":"ind"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckStandard":{"abstract":[{"type":"text","text":"Supported check standards."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckStandard"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckstandard","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckStandard"}],"title":"SBSDKCheckStandard","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"ind"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ind"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckStandard","kind":"typeIdentifier","text":"SBSDKCheckStandard","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard"},{"kind":"text","text":" * "},{"kind":"identifier","text":"ind"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckStandard~1ind\/title","op":"replace","value":"ind"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckStandard~1ind\/fragments","op":"replace","value":[{"kind":"identifier","text":"ind"}]},{"value":"SBSDKCheckStandard","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckStandard\/title"},{"value":[{"kind":"identifier","text":"SBSDKCheckStandard"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckStandard\/fragments"},{"value":[{"text":"SBSDKCheckStandard","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckStandard\/navigatorTitle"}]}]}