{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScanner\/scan(videoFrameImage:in:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The actual scan function. Scans a "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" representation of a camera video frame for a license."}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(scanVideoFrameImage:inRect:) "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"videoFrameImage","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"image","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"text":"in","kind":"externalParam"},{"kind":"text","text":" "},{"text":"rect","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKLicensePlateScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The correct oriented image to scan."}]}],"name":"image"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The rectangle in image coordinates in which to perform the scan. Must be within the boundaries of the video frame."}]}],"name":"rect"}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"The result of the scan."}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"name":"Warning","type":"aside","content":[{"inlineContent":[{"type":"text","text":"This function is not for scanning single images."}],"type":"paragraph"}],"style":"warning"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScanner"]]},"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"scanVideoFrameImage:inRect:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"videoFrameImage"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") -> ","kind":"text"},{"text":"SBSDKLicensePlateScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult"},{"text":"?","kind":"text"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScanner(im)scanVideoFrameImage:inRect:","title":"scan(videoFrameImage:in:)","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescanner\/scan(videoframeimage:in:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescanner\/scan(videoframeimage:in:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerResult":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKLicensePlateScannerResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicensePlateScannerResult"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerresult","title":"SBSDKLicensePlateScannerResult","abstract":[{"text":"A class describing the result of a license plate scan.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScanner":{"title":"SBSDKLicensePlateScanner","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescanner","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLicensePlateScanner"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKLicensePlateScanner","kind":"identifier"}],"abstract":[{"type":"text","text":"A class to scan a vehicle’s license plate in a "},{"type":"codeVoice","code":"UIImage"},{"text":" or ","type":"text"},{"code":"CMSampleBuffer","type":"codeVoice"},{"type":"text","text":" and run a validation on the result."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScanner","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScanner/scan(videoFrameImage:in:)":{"title":"scan(videoFrameImage:in:)","role":"symbol","abstract":[{"type":"text","text":"The actual scan function. Scans a "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" representation of a camera video frame for a license."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"scan","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoFrameImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult","kind":"typeIdentifier","text":"SBSDKLicensePlateScannerResult"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"scanVideoFrameImage:inRect:"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescanner\/scan(videoframeimage:in:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScanner\/scan(videoFrameImage:in:)","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"scanVideoFrameImage:inRect:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"scanVideoFrameImage:inRect:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"SBSDKLicensePlateScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult"},{"text":" *) ","kind":"text"},{"text":"scanVideoFrameImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inRect:"},{"text":"(","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"rect"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult\/title","value":"SBSDKLicensePlateScannerResult"},{"value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScanner\/title","value":"SBSDKLicensePlateScanner","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScanner\/fragments","value":[{"kind":"identifier","text":"SBSDKLicensePlateScanner"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScanner~1scan(videoFrameImage:in:)\/title","value":"scanVideoFrameImage:inRect:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScanner~1scan(videoFrameImage:in:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"scanVideoFrameImage:inRect:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}