{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRegexFilter:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"regexFilter","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumSizeScore:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"minimumSizeScore"},{"text":" ","kind":"text"},{"text":"addAdditionalQuietZone:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"addAdditionalQuietZone","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimum1DQuietZoneSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimum1DQuietZoneSize"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stripCheckDigits:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"stripCheckDigits","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumTextLength:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"minimumTextLength"},{"text":" ","kind":"text"},{"text":"maximumTextLength:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"maximumTextLength","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"iata2of5:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"iata2of5"},{"text":" ","kind":"text"},{"text":"code25:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"code25"},{"text":" ","kind":"text"},{"text":"industrial2of5:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"industrial2of5","kind":"internalParam"},{"kind":"text","text":" "},{"text":"useIATA2OF5Checksum:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"useIATA2OF5Checksum","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode2Of5Configuration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:iata2of5:code25:industrial2of5:useIATA2OF5Checksum:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode2Of5Configuration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode2of5configuration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:stripcheckdigits:minimumtextlength:maximumtextlength:iata2of5:code25:industrial2of5:useiata2of5checksum:"]}],"metadata":{"navigatorTitle":[{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:iata2of5:code25:industrial2of5:useIATA2OF5Checksum:","kind":"identifier"}],"title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:iata2of5:code25:industrial2of5:useIATA2OF5Checksum:","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCode2Of5Configuration(im)initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:iata2of5:code25:industrial2of5:useIATA2OF5Checksum:","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:iata2of5:code25:industrial2of5:useIATA2OF5Checksum:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode2Of5Configuration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:iata2of5:code25:industrial2of5:useIATA2OF5Checksum:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode2Of5Configuration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:iata2of5:code25:industrial2of5:useIATA2OF5Checksum:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode2of5configuration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:stripcheckdigits:minimumtextlength:maximumtextlength:iata2of5:code25:industrial2of5:useiata2of5checksum:","role":"symbol","title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:iata2of5:code25:industrial2of5:useIATA2OF5Checksum:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:iata2of5:code25:industrial2of5:useIATA2OF5Checksum:"}],"fragments":[{"kind":"text","text":"- "},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:iata2of5:code25:industrial2of5:useIATA2OF5Checksum:","kind":"identifier"}],"abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode2Of5Configuration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode2Of5Configuration","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode2of5configuration","type":"topic","title":"SBSDKBarcodeFormatCode2Of5Configuration","abstract":[{"text":"Configuration for all 2-of-5 barcode types (except Interleaved 2-of-5, which is handled by ItfConfig).","type":"text"},{"type":"text","text":" "},{"text":"Add to scanner configuration to scan Code 25, IATA 2-of-5 and Industrial 2-of-5 barcodes.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeFormatCode2Of5Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatCode2Of5Configuration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode2Of5Configuration\/title","op":"replace","value":"SBSDKBarcodeFormatCode2Of5Configuration"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode2Of5Configuration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode2Of5Configuration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode2Of5Configuration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode2Of5Configuration"}]}]}]}