{"kind":"symbol","metadata":{"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView(cm)potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:offset:","title":"potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"potentialViewFinderRectWithBounds","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":", ","kind":"text"},{"text":"finderSafeArea","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"aspectRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minimumInsets","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier","text":"UIEdgeInsets"},{"kind":"text","text":", "},{"kind":"externalParam","text":"offset"},{"text":": ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:offset:"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfinderview\/potentialviewfinderrectwithbounds(_:findersafearea:aspectratio:minimuminsets:offset:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkfinderview\/potentialviewfinderrectwithbounds(_:findersafearea:aspectratio:minimuminsets:offset:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"text":"A function, that returns a rect of a finder, if it will be placed in view with certain bounds, with given aspect ratio and insets. Useful for pre-calculations in some animation cases","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"potentialViewFinderRectWithBounds","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"bounds","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"finderSafeArea","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"aspectRatio"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"minimumInsets","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"},{"kind":"text","text":", "},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The bounds of the view, where potential view will be placed."}]}],"name":"bounds"},{"content":[{"inlineContent":[{"type":"text","text":"An expected aspect ratio."}],"type":"paragraph"}],"name":"aspectRatio"},{"name":"minimumInsets","content":[{"inlineContent":[{"type":"text","text":"Minimal insets of the view finder."}],"type":"paragraph"}]}]},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"A calculated rectangle of a potential view finder.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)":{"navigatorTitle":[{"text":"potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:offset:","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)","abstract":[{"type":"text","text":"A function, that returns a rect of a finder, if it will be placed in view with certain bounds, with given aspect ratio and insets. Useful for pre-calculations in some animation cases"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/potentialviewfinderrectwithbounds(_:findersafearea:aspectratio:minimuminsets:offset:)","title":"potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"potentialViewFinderRectWithBounds","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"text":"finderSafeArea","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"aspectRatio"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minimumInsets"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"offset","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView":{"navigatorTitle":[{"text":"SBSDKFinderView","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIView"},{"text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","type":"topic","title":"SBSDKFinderView","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:offset:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:offset:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") "},{"kind":"identifier","text":"potentialViewFinderRectWithBounds:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"bounds"},{"text":" ","kind":"text"},{"text":"finderSafeArea:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"text":"finderSafeArea","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aspectRatio:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"aspectRatio"},{"text":" ","kind":"text"},{"text":"minimumInsets:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimumInsets","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"offset:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"offset","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"bounds","content":[{"inlineContent":[{"type":"text","text":"The bounds of the view, where potential view will be placed."}],"type":"paragraph"}]},{"name":"aspectRatio","content":[{"type":"paragraph","inlineContent":[{"text":"An expected aspect ratio.","type":"text"}]}]},{"name":"minimumInsets","content":[{"inlineContent":[{"text":"Minimal insets of the view finder.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"A calculated rectangle of a potential view finder.","type":"text"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)\/title","op":"replace","value":"potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:offset:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:offset:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/title","value":"SBSDKFinderView"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/fragments","value":[{"text":"SBSDKFinderView","kind":"identifier"}]},{"value":[{"text":"SBSDKFinderView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/navigatorTitle"}]}]}