{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommononedconfiguration\/new"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonOneDConfiguration\/new"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"new"}],"symbolKind":"method","title":"new","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"new"}],"roleHeading":"Type Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCommonOneDConfiguration(cm)new","role":"symbol"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"new","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonOneDConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonOneDConfiguration/new":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonOneDConfiguration\/new","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommononedconfiguration\/new","role":"symbol","navigatorTitle":[{"text":"new","kind":"identifier"}],"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"new"}],"title":"new"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonOneDConfiguration":{"role":"symbol","kind":"symbol","title":"SBSDKBarcodeFormatCommonOneDConfiguration","abstract":[{"text":"Convenience configuration for enabling the scanning of multiple linear (1D) barcode formats with a common","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"configuration."},{"type":"text","text":" "},{"text":"Add to scanner configuration to enable and configure the scanning of multiple linear (1D) barcode formats.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonOneDConfiguration"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeFormatCommonOneDConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommononedconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonOneDConfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonOneDConfiguration\/title","value":"SBSDKBarcodeFormatCommonOneDConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonOneDConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonOneDConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonOneDConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonOneDConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}