{"kind":"symbol","abstract":[{"text":"List of reports for each field that was verified.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldDetails"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldConsistencyVerificationReport","kind":"typeIdentifier","text":"SBSDKFieldConsistencyVerificationReport","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport"},{"kind":"text","text":">"}]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkconsistencyverificationreport\/fielddetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkconsistencyverificationreport\/fielddetails"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport\/fieldDetails"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"fieldDetails","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKConsistencyVerificationReport(py)fieldDetails","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fieldDetails","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"SBSDKFieldConsistencyVerificationReport","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldConsistencyVerificationReport","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"fieldDetails","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConsistencyVerificationReport/fieldDetails":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkconsistencyverificationreport\/fielddetails","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fieldDetails","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldConsistencyVerificationReport","text":"SBSDKFieldConsistencyVerificationReport","kind":"typeIdentifier"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"fieldDetails","kind":"identifier"}],"title":"fieldDetails","abstract":[{"type":"text","text":"List of reports for each field that was verified."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport\/fieldDetails","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConsistencyVerificationReport":{"type":"topic","role":"symbol","title":"SBSDKConsistencyVerificationReport","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport","kind":"symbol","abstract":[{"type":"text","text":"Report of the document consistency verification. Shows whether information in the fields that correspond to the same logical field is consistent."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKConsistencyVerificationReport"}],"url":"\/documentation\/scanbotsdk\/sbsdkconsistencyverificationreport","navigatorTitle":[{"kind":"identifier","text":"SBSDKConsistencyVerificationReport"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldConsistencyVerificationReport":{"abstract":[{"text":"Report of the field consistency verification.","type":"text"}],"kind":"symbol","title":"SBSDKFieldConsistencyVerificationReport","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFieldConsistencyVerificationReport"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKFieldConsistencyVerificationReport"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkfieldconsistencyverificationreport"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"fieldDetails","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"fieldDetails"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<SBSDKFieldConsistencyVerificationReport *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"fieldDetails","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport~1fieldDetails\/title","value":"fieldDetails"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport~1fieldDetails\/fragments","value":[{"kind":"identifier","text":"fieldDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport\/title","value":"SBSDKConsistencyVerificationReport"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport\/fragments","value":[{"kind":"identifier","text":"SBSDKConsistencyVerificationReport"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKConsistencyVerificationReport"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldConsistencyVerificationReport\/title","value":"SBSDKFieldConsistencyVerificationReport"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldConsistencyVerificationReport\/fragments","value":[{"kind":"identifier","text":"SBSDKFieldConsistencyVerificationReport"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldConsistencyVerificationReport\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFieldConsistencyVerificationReport"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}