{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBasicImageLoadOptions\/initWithCropRect:canvasColor:"},"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCropRect:canvasColor:","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBasicImageLoadOptions(im)initWithCropRect:canvasColor:","symbolKind":"method","roleHeading":"Instance Method","title":"initWithCropRect:canvasColor:","navigatorTitle":[{"text":"initWithCropRect:canvasColor:","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithCropRect:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cropRect","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"canvasColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCanvasColor","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCanvasColor","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKCanvasColor"},{"text":") ","kind":"text"},{"text":"canvasColor","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasicimageloadoptions\/initwithcroprect:canvascolor:"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBasicImageLoadOptions"]]},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBasicImageLoadOptions/initWithCropRect:canvasColor:":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasicimageloadoptions\/initwithcroprect:canvascolor:","role":"symbol","abstract":[],"title":"initWithCropRect:canvasColor:","navigatorTitle":[{"kind":"identifier","text":"initWithCropRect:canvasColor:"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBasicImageLoadOptions\/initWithCropRect:canvasColor:","type":"topic","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCropRect:canvasColor:"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBasicImageLoadOptions":{"abstract":[{"type":"text","text":"Basic options for loading image."}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasicimageloadoptions","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBasicImageLoadOptions","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBasicImageLoadOptions","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBasicImageLoadOptions","kind":"identifier"}],"title":"SBSDKBasicImageLoadOptions"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCanvasColor":{"title":"SBSDKCanvasColor","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcanvascolor","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCanvasColor","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCanvasColor"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCanvasColor"}],"abstract":[{"type":"text","text":"Canvas color to use when converting images with alpha channel to images without alpha channel."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKBasicImageLoadOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBasicImageLoadOptions\/title"},{"value":[{"text":"SBSDKBasicImageLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBasicImageLoadOptions\/fragments"},{"value":[{"text":"SBSDKBasicImageLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBasicImageLoadOptions\/navigatorTitle"},{"value":"SBSDKCanvasColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCanvasColor\/title"},{"value":[{"kind":"identifier","text":"SBSDKCanvasColor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCanvasColor\/fragments"},{"value":[{"text":"SBSDKCanvasColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCanvasColor\/navigatorTitle"}]}]}