{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/init(text:paragraphs:lines:words:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Designated initializer.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"text"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"paragraphs","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock","text":"SBSDKOCRResultBlock"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"lines"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock","text":"SBSDKOCRResultBlock","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"words","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock","text":"SBSDKOCRResultBlock","kind":"typeIdentifier"},{"text":"])","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The recognized text of the page.","type":"text"}]}],"name":"text"},{"content":[{"inlineContent":[{"text":"The paragraph blocks of the page.","type":"text"}],"type":"paragraph"}],"name":"paragraphs"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The line blocks of the page.","type":"text"}]}],"name":"lines"},{"name":"words","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The word blocks of the page."}]}]}],"kind":"parameters"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"init","roleHeading":"Initializer","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRPage(im)initWithText:paragraphs:lines:words:","navigatorTitle":[{"text":"initWithText:paragraphs:lines:words:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"text","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"paragraphs","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKOCRResultBlock","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock"},{"text":"], ","kind":"text"},{"text":"lines","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock","text":"SBSDKOCRResultBlock","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"words"},{"text":": [","kind":"text"},{"text":"SBSDKOCRResultBlock","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"title":"init(text:paragraphs:lines:words:)"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkocrpage\/init(text:paragraphs:lines:words:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkocrpage\/init(text:paragraphs:lines:words:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlock":{"title":"SBSDKOCRResultBlock","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCRResultBlock","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrresultblock","abstract":[{"type":"text","text":"The partial result of an optical character recognition."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKOCRResultBlock","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRPage":{"abstract":[{"type":"text","text":"Represents the results of an optical character recognition (OCR) operation for a single page."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrpage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKOCRPage","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKOCRPage"}],"kind":"symbol","title":"SBSDKOCRPage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRPage/init(text:paragraphs:lines:words:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/init(text:paragraphs:lines:words:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"paragraphs"},{"kind":"text","text":": ["},{"text":"SBSDKOCRResultBlock","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"lines"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock","text":"SBSDKOCRResultBlock","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"words"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock","text":"SBSDKOCRResultBlock","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"title":"init(text:paragraphs:lines:words:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkocrpage\/init(text:paragraphs:lines:words:)","abstract":[{"type":"text","text":"Designated initializer."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithText:paragraphs:lines:words:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithText:paragraphs:lines:words:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithText:paragraphs:lines:words:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithText:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"text","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"paragraphs:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKOCRResultBlock *>"},{"kind":"text","text":" *) "},{"text":"paragraphs","kind":"internalParam"},{"kind":"text","text":" "},{"text":"lines:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKOCRResultBlock *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"lines","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"words:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKOCRResultBlock *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"words"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"text","content":[{"inlineContent":[{"text":"The recognized text of the page.","type":"text"}],"type":"paragraph"}]},{"name":"paragraphs","content":[{"type":"paragraph","inlineContent":[{"text":"The paragraph blocks of the page.","type":"text"}]}]},{"name":"lines","content":[{"type":"paragraph","inlineContent":[{"text":"The line blocks of the page.","type":"text"}]}]},{"name":"words","content":[{"inlineContent":[{"type":"text","text":"The word blocks of the page."}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","value":"SBSDKOCRResultBlock","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock\/fragments","value":[{"text":"SBSDKOCRResultBlock","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKOCRResultBlock","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock\/navigatorTitle"},{"value":"SBSDKOCRPage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKOCRPage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKOCRPage"}]},{"value":"initWithText:paragraphs:lines:words:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage~1init(text:paragraphs:lines:words:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage~1init(text:paragraphs:lines:words:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithText:paragraphs:lines:words:","kind":"identifier"}],"op":"replace"}]}]}