{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrpage\/lines"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrpage\/lines"]}],"kind":"symbol","abstract":[{"type":"text","text":"The line blocks of the page."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"lines"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock","kind":"typeIdentifier","text":"SBSDKOCRResultBlock"},{"text":"]","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/lines","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"lines","kind":"identifier"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"lines","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKOCRResultBlock","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock"},{"text":"]","kind":"text"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","title":"lines","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRPage(py)lines"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRPage/lines":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"lines"}],"title":"lines","abstract":[{"text":"The line blocks of the page.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrpage\/lines","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/lines","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"lines","kind":"identifier"},{"kind":"text","text":": ["},{"text":"SBSDKOCRResultBlock","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock","kind":"typeIdentifier"},{"kind":"text","text":"]"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRPage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCRPage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage","role":"symbol","kind":"symbol","title":"SBSDKOCRPage","abstract":[{"type":"text","text":"Represents the results of an optical character recognition (OCR) operation for a single page."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrpage","navigatorTitle":[{"text":"SBSDKOCRPage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlock":{"navigatorTitle":[{"text":"SBSDKOCRResultBlock","kind":"identifier"}],"abstract":[{"type":"text","text":"The partial result of an optical character recognition."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock","kind":"symbol","title":"SBSDKOCRResultBlock","url":"\/documentation\/scanbotsdk\/sbsdkocrresultblock","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCRResultBlock"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"lines","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"lines","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSArray<SBSDKOCRResultBlock *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"lines","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"lines","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage~1lines\/title"},{"value":[{"text":"lines","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage~1lines\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage\/title","value":"SBSDKOCRPage"},{"value":[{"kind":"identifier","text":"SBSDKOCRPage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock\/title","value":"SBSDKOCRResultBlock"},{"op":"replace","value":[{"text":"SBSDKOCRResultBlock","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock\/fragments"}]}]}