{"metadata":{"navigatorTitle":[{"text":"completed","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FindAndPickBadgeConfiguration(py)completed","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"completed","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgeStyle","text":"SBSDKUI2BadgeStyle","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property","title":"completed"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickBadgeConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/completed"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2findandpickbadgeconfiguration\/completed"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2findandpickbadgeconfiguration\/completed"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"Appearance of the badge when a barcode is completed.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"completed","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgeStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgeStyle","text":"SBSDKUI2BadgeStyle"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickBadgeConfiguration/completed":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickbadgeconfiguration\/completed","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/completed","abstract":[{"text":"Appearance of the badge when a barcode is completed.","type":"text"}],"title":"completed","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"completed","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgeStyle","text":"SBSDKUI2BadgeStyle"}],"navigatorTitle":[{"text":"completed","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BadgeStyle":{"abstract":[{"text":"Configuration of the round button.","type":"text"}],"title":"SBSDKUI2BadgeStyle","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BadgeStyle"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BadgeStyle","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2badgestyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgeStyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickBadgeConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickBadgeConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2FindAndPickBadgeConfiguration"}],"role":"symbol","title":"SBSDKUI2FindAndPickBadgeConfiguration","abstract":[{"text":"Configuration of the round badge on find and pick ar layer.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickbadgeconfiguration","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"completed","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"completed","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SBSDKUI2BadgeStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgeStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgeStyle"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"completed"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickBadgeConfiguration~1completed\/title","op":"replace","value":"completed"},{"op":"replace","value":[{"text":"completed","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickBadgeConfiguration~1completed\/fragments"},{"value":"SBSDKUI2BadgeStyle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgeStyle\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgeStyle\/fragments","value":[{"text":"SBSDKUI2BadgeStyle","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2FindAndPickBadgeConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2FindAndPickBadgeConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}