{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentformat\/medicalcertificate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentformat\/medicalcertificate"]}],"abstract":[{"type":"text","text":"German medical certificate barcode document."}],"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentFormat(cpy)medicalCertificate","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Property","symbolKind":"property","title":"medicalCertificate","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"medicalCertificate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeDocumentFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentFormat"}],"navigatorTitle":[{"text":"medicalCertificate","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentFormat"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentFormat\/medicalCertificate","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"medicalCertificate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentFormat","text":"SBSDKBarcodeDocumentFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentFormat","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentFormat":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentFormat","kind":"identifier"}],"abstract":[{"text":"Type of barcode document format used.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentFormat","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentFormat","kind":"identifier"}],"title":"SBSDKBarcodeDocumentFormat","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentformat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentFormat/medicalCertificate":{"type":"topic","abstract":[{"type":"text","text":"German medical certificate barcode document."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentformat\/medicalcertificate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentFormat\/medicalCertificate","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"medicalCertificate"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeDocumentFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentFormat","kind":"typeIdentifier"}],"title":"medicalCertificate","navigatorTitle":[{"text":"medicalCertificate","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","value":"medicalCertificate","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"medicalCertificate","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentFormat","text":"SBSDKBarcodeDocumentFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentFormat","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"medicalCertificate"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentFormat\/title","value":"SBSDKBarcodeDocumentFormat"},{"value":[{"text":"SBSDKBarcodeDocumentFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentFormat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentFormat\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentFormat~1medicalCertificate\/title","value":"medicalCertificate"},{"value":[{"kind":"identifier","text":"medicalCertificate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentFormat~1medicalCertificate\/fragments","op":"replace"}]}]}