{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration\/multiPageButtonAccessibilityHint"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Text, that is used as an accessibility hint for the multi-page button.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"multiPageButtonAccessibilityHint","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Defaults to “Turns multi page scanning on or off”.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscanneraccessibilityconfiguration\/multipagebuttonaccessibilityhint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscanneraccessibilityconfiguration\/multipagebuttonaccessibilityhint"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration"]]},"metadata":{"navigatorTitle":[{"text":"multiPageButtonAccessibilityHint","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","title":"multiPageButtonAccessibilityHint","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerAccessibilityConfiguration(py)multiPageButtonAccessibilityHint","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiPageButtonAccessibilityHint"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerAccessibilityConfiguration":{"role":"symbol","navigatorTitle":[{"text":"SBSDKUIDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"type":"topic","abstract":[],"title":"SBSDKUIDocumentScannerAccessibilityConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneraccessibilityconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerAccessibilityConfiguration/multiPageButtonAccessibilityHint":{"navigatorTitle":[{"text":"multiPageButtonAccessibilityHint","kind":"identifier"}],"title":"multiPageButtonAccessibilityHint","type":"topic","abstract":[{"type":"text","text":"Text, that is used as an accessibility hint for the multi-page button."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneraccessibilityconfiguration\/multipagebuttonaccessibilityhint","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"multiPageButtonAccessibilityHint","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration\/multiPageButtonAccessibilityHint"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"multiPageButtonAccessibilityHint","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"multiPageButtonAccessibilityHint","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"multiPageButtonAccessibilityHint","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration\/title","value":"SBSDKUIDocumentScannerAccessibilityConfiguration"},{"op":"replace","value":[{"text":"SBSDKUIDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration\/fragments"},{"op":"replace","value":"multiPageButtonAccessibilityHint","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration~1multiPageButtonAccessibilityHint\/title"},{"op":"replace","value":[{"text":"multiPageButtonAccessibilityHint","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration~1multiPageButtonAccessibilityHint\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}