{"kind":"symbol","abstract":[{"type":"text","text":"The image storage was invalid or nil."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrorcode\/invalidimagestorage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrorcode\/invalidimagestorage"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidImageStorage","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode"]]},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidImageStorage"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCodeInvalidImageStorage"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKErrorCode@SBSDKErrorCodeInvalidImageStorage","roleHeading":"Case","title":"SBSDKErrorCode.invalidImageStorage","symbolKind":"case"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/invalidImageStorage","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode":{"navigatorTitle":[{"text":"SBSDKErrorCode","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode","abstract":[{"type":"text","text":"The error codes in the SBSDKErrorDomain."}],"type":"topic","title":"SBSDKErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKErrorCode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkerrorcode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/invalidImageStorage":{"navigatorTitle":[{"text":"SBSDKErrorCodeInvalidImageStorage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/invalidImageStorage","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidImageStorage","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/invalidimagestorage","abstract":[{"type":"text","text":"The image storage was invalid or nil."}],"title":"SBSDKErrorCode.invalidImageStorage","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKErrorCodeInvalidImageStorage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKErrorCodeInvalidImageStorage"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKErrorCodeInvalidImageStorage","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode\/title","value":"SBSDKErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode\/fragments","value":[{"kind":"identifier","text":"SBSDKErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode\/navigatorTitle","value":[{"text":"SBSDKErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1invalidImageStorage\/title","value":"SBSDKErrorCodeInvalidImageStorage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1invalidImageStorage\/fragments","value":[{"kind":"identifier","text":"SBSDKErrorCodeInvalidImageStorage"}],"op":"replace"}]}]}