{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerPolygonConfiguration\/init(enabled:strokeColor:strokeWidth:fillColor:cornerRadius:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerPolygonConfiguration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Create a new instance of ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerPolygonConfiguration","isActive":true},{"type":"text","text":"."}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"enabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true, "},{"text":"strokeColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" = .white, ","kind":"text"},{"text":"strokeWidth","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":" = 2.0, ","kind":"text"},{"text":"fillColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":" = .clear, ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":" = 8.0)"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"enabled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether the polygon is visible or not."}]}]},{"name":"strokeColor","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The stroke color for the polygon displayed over the scanned document."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The stroke width for the polygon displayed around the scanned document."}]}],"name":"strokeWidth"},{"name":"fillColor","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The fill color for the polygon displayed over the scanned document."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The radius to use when drawing rounded corners of the polygon."}],"type":"paragraph"}],"name":"cornerRadius"}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerPolygonConfiguration(im)initWithEnabled:strokeColor:strokeWidth:fillColor:cornerRadius:","roleHeading":"Initializer","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enabled","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"strokeColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"strokeWidth"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"fillColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":", "},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithEnabled:strokeColor:strokeWidth:fillColor:cornerRadius:","kind":"identifier"}],"title":"init(enabled:strokeColor:strokeWidth:fillColor:cornerRadius:)","role":"symbol","modules":[{"name":"ScanbotSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerpolygonconfiguration\/init(enabled:strokecolor:strokewidth:fillcolor:cornerradius:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerpolygonconfiguration\/init(enabled:strokecolor:strokewidth:fillcolor:cornerradius:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerPolygonConfiguration/init(enabled:strokeColor:strokeWidth:fillColor:cornerRadius:)":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerpolygonconfiguration\/init(enabled:strokecolor:strokewidth:fillcolor:cornerradius:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerPolygonConfiguration\/init(enabled:strokeColor:strokeWidth:fillColor:cornerRadius:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Create a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerPolygonConfiguration","type":"reference","isActive":true},{"type":"text","text":"."}],"title":"init(enabled:strokeColor:strokeWidth:fillColor:cornerRadius:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"enabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"strokeColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"strokeWidth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"fillColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cornerRadius"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithEnabled:strokeColor:strokeWidth:fillColor:cornerRadius:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerPolygonConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentScannerPolygonConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerPolygonConfiguration","type":"topic","navigatorTitle":[{"text":"SBSDKDocumentScannerPolygonConfiguration","kind":"identifier"}],"role":"symbol","title":"SBSDKDocumentScannerPolygonConfiguration","abstract":[{"type":"text","text":"Configuration for the polygon displayed over the scanned document."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerpolygonconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"initWithEnabled:strokeColor:strokeWidth:fillColor:cornerRadius:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEnabled:strokeColor:strokeWidth:fillColor:cornerRadius:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"enabled","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"strokeColor:"},{"text":"(","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"strokeColor"},{"kind":"text","text":" "},{"text":"strokeWidth:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"strokeWidth"},{"text":" ","kind":"text"},{"text":"fillColor:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"fillColor"},{"kind":"text","text":" "},{"text":"cornerRadius:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"cornerRadius","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"enabled","content":[{"inlineContent":[{"text":"Whether the polygon is visible or not.","type":"text"}],"type":"paragraph"}]},{"name":"strokeColor","content":[{"type":"paragraph","inlineContent":[{"text":"The stroke color for the polygon displayed over the scanned document.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"The stroke width for the polygon displayed around the scanned document.","type":"text"}],"type":"paragraph"}],"name":"strokeWidth"},{"name":"fillColor","content":[{"type":"paragraph","inlineContent":[{"text":"The fill color for the polygon displayed over the scanned document.","type":"text"}]}]},{"name":"cornerRadius","content":[{"type":"paragraph","inlineContent":[{"text":"The radius to use when drawing rounded corners of the polygon.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerPolygonConfiguration~1init(enabled:strokeColor:strokeWidth:fillColor:cornerRadius:)\/title","value":"initWithEnabled:strokeColor:strokeWidth:fillColor:cornerRadius:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerPolygonConfiguration~1init(enabled:strokeColor:strokeWidth:fillColor:cornerRadius:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithEnabled:strokeColor:strokeWidth:fillColor:cornerRadius:"}]},{"op":"replace","value":"SBSDKDocumentScannerPolygonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerPolygonConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentScannerPolygonConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerPolygonConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerPolygonConfiguration\/navigatorTitle","value":[{"text":"SBSDKDocumentScannerPolygonConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}