{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"fromJsonWithJson:","role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}],"roleHeading":"Type Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAccumulatedResultsVerifierConfiguration(cm)fromJsonWithJson:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"modules":[{"name":"ScanbotSDK"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkaccumulatedresultsverifierconfiguration\/fromjsonwithjson:"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration\/fromJsonWithJson:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKAccumulatedResultsVerifierConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAccumulatedResultsVerifierConfiguration"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAccumulatedResultsVerifierConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKAccumulatedResultsVerifierConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkaccumulatedresultsverifierconfiguration","abstract":[{"text":"Configure the frame accumulation process.","type":"text"}],"title":"SBSDKAccumulatedResultsVerifierConfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKAccumulatedResultsVerifierConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAccumulatedResultsVerifierConfiguration/fromJsonWithJson:":{"url":"\/documentation\/scanbotsdk\/sbsdkaccumulatedresultsverifierconfiguration\/fromjsonwithjson:","title":"fromJsonWithJson:","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration\/fromJsonWithJson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKAccumulatedResultsVerifierConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKAccumulatedResultsVerifierConfiguration"}]},{"value":[{"kind":"identifier","text":"SBSDKAccumulatedResultsVerifierConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}