{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon\/isEqual:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon\/isequal:"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon(im)isEqual:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"title":"isEqual:","symbolKind":"method"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygon/isEqual:":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon\/isEqual:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon\/isequal:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","title":"isEqual:","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygon":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon","title":"SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPolygon"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKPolygon","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/title"},{"value":[{"text":"SBSDKPolygon","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKPolygon"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/navigatorTitle"}]}]}