{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/hashValue"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"modules":[{"relatedModules":["Swift"],"name":"ScanbotSDK"}],"extendedModule":"Swift","title":"hashValue","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@ScanbotSDK@E@SBSDKCapturePhotoQualityPrioritization","roleHeading":"Instance Property","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/RawRepresentable-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"type":"text","text":"."}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCapturePhotoQualityPrioritization":{"url":"\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization","abstract":[{"text":"The prioritization of still image quality and capturing speed.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization","kind":"symbol","title":"SBSDKCapturePhotoQualityPrioritization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCapturePhotoQualityPrioritization/RawRepresentable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization\/rawrepresentable-implementations","type":"topic","kind":"article"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCapturePhotoQualityPrioritization/hashValue":{"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"title":"hashValue","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/hashValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization\/hashvalue","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization\/title","op":"replace","value":"SBSDKCapturePhotoQualityPrioritization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization\/fragments","value":[{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritization"}]}]}]}