{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkrefcountedobjectprofile\/tojson(configuration:)"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkrefcountedobjectprofile\/tojson(configuration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKRefCountedObjectProfile\/toJson(configuration:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"symbolKind":"method","title":"toJson(configuration:)","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKRefCountedObjectProfile(im)toJsonWithConfiguration:"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKRefCountedObjectProfile"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier","text":"SBSDKToJSONConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKToJSONConfiguration"},{"text":" = SBSDKToJSONConfiguration()) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKToJSONConfiguration":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktojsonconfiguration","abstract":[{"type":"text","text":"Configuration used to serialize an object to json."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKToJSONConfiguration"}],"title":"SBSDKToJSONConfiguration","type":"topic","navigatorTitle":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKToJSONConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKRefCountedObjectProfile/toJson(configuration:)":{"kind":"symbol","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"role":"symbol","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKRefCountedObjectProfile\/toJson(configuration:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkrefcountedobjectprofile\/tojson(configuration:)","title":"toJson(configuration:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKRefCountedObjectProfile":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkrefcountedobjectprofile","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKRefCountedObjectProfile"}],"title":"SBSDKRefCountedObjectProfile","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKRefCountedObjectProfile","abstract":[{"text":"Profile info of a reference-counted stored object.","type":"text"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","role":"collection","title":"ScanbotDocumentScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"toJsonWithConfiguration:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"toJsonWithConfiguration:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKToJSONConfiguration\/title","value":"SBSDKToJSONConfiguration"},{"value":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKToJSONConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKToJSONConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKToJSONConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKRefCountedObjectProfile~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKRefCountedObjectProfile~1toJson(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKRefCountedObjectProfile\/title","value":"SBSDKRefCountedObjectProfile"},{"value":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKRefCountedObjectProfile\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKRefCountedObjectProfile\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKRefCountedObjectProfile"}],"op":"replace"}]}]}