{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldValidationStatus\/confirmed","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmed"}]}],"kind":"declarations"}],"metadata":{"title":"SBSDKHealthInsuranceCardFieldValidationStatus.confirmed","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKHealthInsuranceCardFieldValidationStatus@SBSDKHealthInsuranceCardFieldValidationStatusConfirmed","symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"confirmed","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldValidationStatusConfirmed"}],"roleHeading":"Case"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldValidationStatus"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldvalidationstatus\/confirmed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldvalidationstatus\/confirmed"]}],"abstract":[{"type":"text","text":"The fields validation confirmed."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldValidationStatus":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldValidationStatus"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldvalidationstatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldValidationStatus"}],"title":"SBSDKHealthInsuranceCardFieldValidationStatus","abstract":[{"text":"The validation status of a  health insurance card field.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldValidationStatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldValidationStatus/confirmed":{"title":"SBSDKHealthInsuranceCardFieldValidationStatus.confirmed","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldValidationStatusConfirmed"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"confirmed","kind":"identifier"}],"abstract":[{"type":"text","text":"The fields validation confirmed."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldValidationStatus\/confirmed","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldvalidationstatus\/confirmed","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKHealthInsuranceCardFieldValidationStatusConfirmed","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKHealthInsuranceCardFieldValidationStatusConfirmed","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldValidationStatusConfirmed"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldValidationStatus\/title","value":"SBSDKHealthInsuranceCardFieldValidationStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldValidationStatus\/fragments","value":[{"text":"SBSDKHealthInsuranceCardFieldValidationStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldValidationStatus~1confirmed\/title","value":"SBSDKHealthInsuranceCardFieldValidationStatusConfirmed"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldValidationStatus~1confirmed\/fragments","op":"replace","value":[{"text":"SBSDKHealthInsuranceCardFieldValidationStatusConfirmed","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}