{"abstract":[{"text":"The fields validation succeeded.","type":"text"}],"metadata":{"roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardFieldValidationStatusSuccess","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"success","kind":"identifier"}],"title":"SBSDKHealthInsuranceCardFieldValidationStatus.success","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKHealthInsuranceCardFieldValidationStatus@SBSDKHealthInsuranceCardFieldValidationStatusSuccess","symbolKind":"case"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldvalidationstatus\/success"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldvalidationstatus\/success"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldValidationStatus\/success"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"success","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldValidationStatus"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldValidationStatus/success":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldValidationStatusSuccess"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldvalidationstatus\/success","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"success"}],"title":"SBSDKHealthInsuranceCardFieldValidationStatus.success","abstract":[{"text":"The fields validation succeeded.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldValidationStatus\/success"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldValidationStatus":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldValidationStatus"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldvalidationstatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldValidationStatus"}],"title":"SBSDKHealthInsuranceCardFieldValidationStatus","abstract":[{"text":"The validation status of a  health insurance card field.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldValidationStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKHealthInsuranceCardFieldValidationStatusSuccess"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKHealthInsuranceCardFieldValidationStatusSuccess","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldValidationStatusSuccess"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKHealthInsuranceCardFieldValidationStatusSuccess","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldValidationStatus~1success\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldValidationStatus~1success\/fragments","value":[{"text":"SBSDKHealthInsuranceCardFieldValidationStatusSuccess","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldValidationStatus\/title","value":"SBSDKHealthInsuranceCardFieldValidationStatus"},{"value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldValidationStatus"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldValidationStatus\/fragments"}]}]}