{"metadata":{"title":"init(documentFound:quality:orientation:orientationConfidence:cumulativeQualityHistogram:cumulativeContrastHistogram:cumulativeTextSizeHistogram:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"documentFound","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"quality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentQuality","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQuality","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"orientationConfidence","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"cumulativeQualityHistogram","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"cumulativeContrastHistogram"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"cumulativeTextSizeHistogram"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":">)"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Initializer","role":"symbol","navigatorTitle":[{"text":"initWithDocumentFound:quality:orientation:orientationConfidence:cumulativeQualityHistogram:cumulativeContrastHistogram:cumulativeTextSizeHistogram:","kind":"identifier"}],"symbolKind":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQualityAnalyzerResult(im)initWithDocumentFound:quality:orientation:orientationConfidence:cumulativeQualityHistogram:cumulativeContrastHistogram:cumulativeTextSizeHistogram:"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"quality"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQuality","text":"SBSDKDocumentQuality"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"orientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"orientationConfidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"cumulativeQualityHistogram"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"cumulativeContrastHistogram"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"cumulativeTextSizeHistogram"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":">)"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerResult\/init(documentFound:quality:orientation:orientationConfidence:cumulativeQualityHistogram:cumulativeContrastHistogram:cumulativeTextSizeHistogram:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerresult\/init(documentfound:quality:orientation:orientationconfidence:cumulativequalityhistogram:cumulativecontrasthistogram:cumulativetextsizehistogram:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerresult\/init(documentfound:quality:orientation:orientationconfidence:cumulativequalityhistogram:cumulativecontrasthistogram:cumulativetextsizehistogram:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerResult"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzerResult":{"abstract":[{"type":"text","text":"Result of document quality analysis. It can be used to determine, e.g., if a document is good enough to be used for OCR processing."}],"role":"symbol","title":"SBSDKDocumentQualityAnalyzerResult","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerResult","navigatorTitle":[{"text":"SBSDKDocumentQualityAnalyzerResult","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerresult","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQualityAnalyzerResult","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQuality":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentquality","title":"SBSDKDocumentQuality","abstract":[{"type":"text","text":"Result of document quality analysis."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentQuality"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentQuality"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzerResult/init(documentFound:quality:orientation:orientationConfidence:cumulativeQualityHistogram:cumulativeContrastHistogram:cumulativeTextSizeHistogram:)":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerResult\/init(documentFound:quality:orientation:orientationConfidence:cumulativeQualityHistogram:cumulativeContrastHistogram:cumulativeTextSizeHistogram:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"documentFound","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"quality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQuality","text":"SBSDKDocumentQuality","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"orientationConfidence","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"cumulativeQualityHistogram","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"cumulativeContrastHistogram","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"cumulativeTextSizeHistogram","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":">)","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerresult\/init(documentfound:quality:orientation:orientationconfidence:cumulativequalityhistogram:cumulativecontrasthistogram:cumulativetextsizehistogram:)","kind":"symbol","navigatorTitle":[{"text":"initWithDocumentFound:quality:orientation:orientationConfidence:cumulativeQualityHistogram:cumulativeContrastHistogram:cumulativeTextSizeHistogram:","kind":"identifier"}],"title":"init(documentFound:quality:orientation:orientationConfidence:cumulativeQualityHistogram:cumulativeContrastHistogram:cumulativeTextSizeHistogram:)","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithDocumentFound:quality:orientation:orientationConfidence:cumulativeQualityHistogram:cumulativeContrastHistogram:cumulativeTextSizeHistogram:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocumentFound:quality:orientation:orientationConfidence:cumulativeQualityHistogram:cumulativeContrastHistogram:cumulativeTextSizeHistogram:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDocumentFound:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"documentFound"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQuality","text":"SBSDKDocumentQuality"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"quality"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"orientation"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationConfidence:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"orientationConfidence"},{"kind":"text","text":" "},{"kind":"identifier","text":"cumulativeQualityHistogram:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSNumber *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cumulativeQualityHistogram"},{"kind":"text","text":" "},{"kind":"identifier","text":"cumulativeContrastHistogram:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSNumber *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cumulativeContrastHistogram"},{"kind":"text","text":" "},{"kind":"identifier","text":"cumulativeTextSizeHistogram:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cumulativeTextSizeHistogram"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerResult\/title","value":"SBSDKDocumentQualityAnalyzerResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerResult\/navigatorTitle","value":[{"text":"SBSDKDocumentQualityAnalyzerResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality\/title","value":"SBSDKDocumentQuality","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality\/fragments","value":[{"text":"SBSDKDocumentQuality","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality\/navigatorTitle","value":[{"text":"SBSDKDocumentQuality","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerResult~1init(documentFound:quality:orientation:orientationConfidence:cumulativeQualityHistogram:cumulativeContrastHistogram:cumulativeTextSizeHistogram:)\/title","value":"initWithDocumentFound:quality:orientation:orientationConfidence:cumulativeQualityHistogram:cumulativeContrastHistogram:cumulativeTextSizeHistogram:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerResult~1init(documentFound:quality:orientation:orientationConfidence:cumulativeQualityHistogram:cumulativeContrastHistogram:cumulativeTextSizeHistogram:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocumentFound:quality:orientation:orientationConfidence:cumulativeQualityHistogram:cumulativeContrastHistogram:cumulativeTextSizeHistogram:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}