{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encrypter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdksaveimageoptions\/encrypter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdksaveimageoptions\/encrypter"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSaveImageOptions"]]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSaveImageOptions\/encrypter","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Custom encrypter to use when saving the image if the encryptionMode implies encryption must be used."}],"metadata":{"title":"encrypter","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKSaveImageOptions(py)encrypter","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encrypter","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider","text":"SBSDKStorageCryptingProvider"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"encrypter"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"property"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSaveImageOptions/encrypter":{"abstract":[{"type":"text","text":"Custom encrypter to use when saving the image if the encryptionMode implies encryption must be used."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encrypter","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider","text":"SBSDKStorageCryptingProvider","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"encrypter","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSaveImageOptions\/encrypter","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksaveimageoptions\/encrypter","navigatorTitle":[{"kind":"identifier","text":"encrypter"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSaveImageOptions":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSaveImageOptions","abstract":[{"text":"Options for saving image to a path.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSaveImageOptions","kind":"identifier"}],"title":"SBSDKSaveImageOptions","navigatorTitle":[{"text":"SBSDKSaveImageOptions","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksaveimageoptions","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingProvider":{"title":"SBSDKStorageCryptingProvider","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingProvider","abstract":[{"type":"text","text":"Protocol for providing a storage crypting object."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingprovider"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"encrypter","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"encrypter","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider","text":"id<SBSDKStorageCryptingProvider>"},{"kind":"text","text":" "},{"kind":"identifier","text":"encrypter"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"encrypter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSaveImageOptions~1encrypter\/title"},{"value":[{"kind":"identifier","text":"encrypter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSaveImageOptions~1encrypter\/fragments"},{"value":"SBSDKSaveImageOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSaveImageOptions\/title"},{"value":[{"text":"SBSDKSaveImageOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSaveImageOptions\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKSaveImageOptions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSaveImageOptions\/navigatorTitle"},{"value":"SBSDKStorageCryptingProvider","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingProvider\/title"},{"value":[{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingProvider\/fragments"},{"value":[{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingProvider\/navigatorTitle"}]}]}