{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSaveImageOptions\/quality"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"Default is -1","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"quality","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKSaveImageOptions(py)quality","title":"quality","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdksaveimageoptions\/quality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdksaveimageoptions\/quality"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Quality parameter is for jpeg only and is in range 0 to 100. If -1, then settings from hibernation are used."},{"type":"text","text":" "},{"type":"text","text":"In case when the Image Ref was created with a lazy load mode and originally has the same format as the requested to save,"},{"type":"text","text":" "},{"type":"text","text":"then setting quality to -1 leads to simply copying from source to destination,"},{"type":"text","text":" "},{"type":"text","text":"which is time efficient and prevents quality loss caused by jpeg encoding\/decoding."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSaveImageOptions"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSaveImageOptions/quality":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksaveimageoptions\/quality","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSaveImageOptions\/quality","abstract":[{"text":"Quality parameter is for jpeg only and is in range 0 to 100. If -1, then settings from hibernation are used.","type":"text"},{"text":" ","type":"text"},{"text":"In case when the Image Ref was created with a lazy load mode and originally has the same format as the requested to save,","type":"text"},{"text":" ","type":"text"},{"text":"then setting quality to -1 leads to simply copying from source to destination,","type":"text"},{"text":" ","type":"text"},{"text":"which is time efficient and prevents quality loss caused by jpeg encoding\/decoding.","type":"text"}],"navigatorTitle":[{"text":"quality","kind":"identifier"}],"role":"symbol","title":"quality"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSaveImageOptions":{"abstract":[{"type":"text","text":"Options for saving image to a path."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSaveImageOptions","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksaveimageoptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSaveImageOptions","kind":"identifier"}],"title":"SBSDKSaveImageOptions","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKSaveImageOptions","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"quality","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"quality"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSaveImageOptions~1quality\/title","value":"quality","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSaveImageOptions~1quality\/fragments","value":[{"kind":"identifier","text":"quality"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSaveImageOptions\/title","value":"SBSDKSaveImageOptions","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSaveImageOptions\/fragments","value":[{"text":"SBSDKSaveImageOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSaveImageOptions\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKSaveImageOptions"}],"op":"replace"}]}]}