{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen\/enablecameratitle"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen\/enablecameratitle"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Configuration of the camera permission request’s title."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableCameraTitle","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"typeIdentifier"}],"languages":["swift"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen\/enableCameraTitle"},"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"enableCameraTitle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"}],"navigatorTitle":[{"text":"enableCameraTitle","kind":"identifier"}],"symbolKind":"property","title":"enableCameraTitle","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen(py)enableCameraTitle","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","role":"symbol","title":"SBSDKUI2StyledText","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPermissionScreen/enableCameraTitle":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen\/enableCameraTitle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableCameraTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText"}],"title":"enableCameraTitle","abstract":[{"text":"Configuration of the camera permission request’s title.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"enableCameraTitle"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen\/enablecameratitle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPermissionScreen":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}],"title":"SBSDKUI2CameraPermissionScreen","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the camera permission request view."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"enableCameraTitle","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"enableCameraTitle","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"enableCameraTitle"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title","value":"SBSDKUI2StyledText"},{"value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen~1enableCameraTitle\/title","value":"enableCameraTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen~1enableCameraTitle\/fragments","value":[{"kind":"identifier","text":"enableCameraTitle"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/title","value":"SBSDKUI2CameraPermissionScreen"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/fragments","value":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}