{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"statusBarMode","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StatusBarMode","kind":"typeIdentifier","text":"SBSDKUI2StatusBarMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2StatusBarMode"},{"kind":"text","text":" = SBSDKUI2StatusBarMode.dark, "},{"text":"background","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"text":" = SBSDKUI2Color(colorString: \"?sbColorSurface\", isArgb: false), ","kind":"text"},{"kind":"externalParam","text":"iconBackground"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"kind":"text","text":" = SBSDKUI2Color(colorString: \"?sbColorOutline\", isArgb: false), "},{"text":"icon","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle","text":"SBSDKUI2IconStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconStyle","kind":"typeIdentifier"},{"text":" = SBSDKUI2IconStyle(visible: true,\n                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                 isArgb: false)), ","kind":"text"},{"text":"enableCameraButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2ButtonConfiguration(text: \"Grant permission\",\n                                                                                              background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                             isArgb: false),\n                                                                                                                                  fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                           isArgb: false),\n                                                                                                                                  strokeWidth: 0.0),\n                                                                                              foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                                  color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                       isArgb: false),\n                                                                                                                                  useShadow: false)), "},{"kind":"externalParam","text":"closeButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"text":" = SBSDKUI2ButtonConfiguration(text: \"Close\",\n                                                                                       background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                      isArgb: false),\n                                                                                                                           fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                    isArgb: false),\n                                                                                                                           strokeWidth: 0.0),\n                                                                                       foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                           color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                isArgb: false),\n                                                                                                                           useShadow: false)), ","kind":"text"},{"kind":"externalParam","text":"enableCameraTitle"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"text":" = SBSDKUI2StyledText(text: \"Camera permission denied!\",\n                                                                           color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                isArgb: false)), ","kind":"text"},{"text":"enableCameraExplanation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"kind":"text","text":" = SBSDKUI2StyledText(text: \"Please allow the usage of the camera to start the scanning process.\",\n                                       color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                            isArgb: false)))"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen\/init(statusbarmode:background:iconbackground:icon:enablecamerabutton:closebutton:enablecameratitle:enablecameraexplanation:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen\/init(statusbarmode:background:iconbackground:icon:enablecamerabutton:closebutton:enablecameratitle:enablecameraexplanation:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen\/init(statusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"init","title":"init(statusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:)","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"statusBarMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2StatusBarMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2StatusBarMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"background"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"iconBackground"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"icon","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconStyle","text":"SBSDKUI2IconStyle","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"enableCameraButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration"},{"text":", ","kind":"text"},{"text":"closeButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"enableCameraTitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"kind":"text","text":", "},{"kind":"externalParam","text":"enableCameraExplanation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen(im)initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPermissionScreen/init(statusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:)":{"title":"init(statusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:)","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen\/init(statusbarmode:background:iconbackground:icon:enablecamerabutton:closebutton:enablecameratitle:enablecameraexplanation:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"statusBarMode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2StatusBarMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2StatusBarMode"},{"text":", ","kind":"text"},{"text":"background","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":", "},{"text":"iconBackground","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":", "},{"text":"icon","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2IconStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconStyle","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"enableCameraButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"closeButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"enableCameraTitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"enableCameraExplanation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen\/init(statusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StatusBarMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StatusBarMode","navigatorTitle":[{"text":"SBSDKUI2StatusBarMode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2StatusBarMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2statusbarmode","kind":"symbol","abstract":[{"text":"Visual mode used for the status bar icons.","type":"text"}],"type":"topic","role":"symbol","title":"SBSDKUI2StatusBarMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ButtonConfiguration":{"abstract":[{"text":"Button configuration.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2buttonconfiguration","type":"topic","kind":"symbol","title":"SBSDKUI2ButtonConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IconStyle":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"abstract":[{"text":"Configuration of the icon appearance.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2iconstyle","title":"SBSDKUI2IconStyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPermissionScreen":{"title":"SBSDKUI2CameraPermissionScreen","url":"\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen","abstract":[{"text":"Configuration of the camera permission request view.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}],"navigatorTitle":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"abstract":[],"kind":"symbol","title":"SBSDKUI2Color","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2Color","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","url":"\/documentation\/scanbotsdk\/sbsdkui2color","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","type":"topic","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"role":"symbol","title":"SBSDKUI2StyledText"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithStatusBarMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2StatusBarMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2StatusBarMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StatusBarMode"},{"text":") ","kind":"text"},{"text":"statusBarMode","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"background:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"kind":"text","text":" *) "},{"text":"background","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"iconBackground:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"iconBackground"},{"kind":"text","text":" "},{"text":"icon:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2IconStyle","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconStyle"},{"text":" *) ","kind":"text"},{"text":"icon","kind":"internalParam"},{"kind":"text","text":" "},{"text":"enableCameraButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"enableCameraButton"},{"kind":"text","text":" "},{"text":"closeButton:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"closeButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"enableCameraTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"text":"enableCameraTitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableCameraExplanation:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"text":"enableCameraExplanation","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen~1init(statusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen~1init(statusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StatusBarMode\/title","op":"replace","value":"SBSDKUI2StatusBarMode"},{"value":[{"kind":"identifier","text":"SBSDKUI2StatusBarMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StatusBarMode\/fragments","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2StatusBarMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StatusBarMode\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2ButtonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconStyle\/title","value":"SBSDKUI2IconStyle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconStyle\/fragments","value":[{"text":"SBSDKUI2IconStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconStyle\/navigatorTitle","value":[{"text":"SBSDKUI2IconStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/title","op":"replace","value":"SBSDKUI2CameraPermissionScreen"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/fragments","value":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/navigatorTitle"},{"value":"SBSDKUI2Color","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title"},{"value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Color"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title","value":"SBSDKUI2StyledText"},{"value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/navigatorTitle","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"op":"replace"}]}]}