{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiresCareYes","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/requiresCareYes","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/requirescareyes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/requirescareyes"]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiresCareYes","kind":"identifier"}],"title":"SBSDKMedicalCertificateCheckBoxType.requiresCareYes","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBoxTypeRequiresCareYes","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateCheckBoxType@SBSDKMedicalCertificateCheckBoxTypeRequiresCareYes"},"abstract":[{"text":"(Form 21a) Requires care yes (Die Art der Erkrankung macht die Betreuung und Beaufsichtigung notwendig… ja)","type":"text"},{"type":"text","text":" "},{"type":"text","text":"checkbox."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/requiresCareYes":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/requiresCareYes","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/requirescareyes","title":"SBSDKMedicalCertificateCheckBoxType.requiresCareYes","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiresCareYes"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeRequiresCareYes"}],"kind":"symbol","abstract":[{"type":"text","text":"(Form 21a) Requires care yes (Die Art der Erkrankung macht die Betreuung und Beaufsichtigung notwendig… ja)"},{"text":" ","type":"text"},{"text":"checkbox.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType","kind":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBoxType","kind":"identifier"}],"abstract":[{"text":"Type of the checkbox.","type":"text"}],"type":"topic","role":"symbol","title":"SBSDKMedicalCertificateCheckBoxType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxType"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalCertificateCheckBoxTypeRequiresCareYes"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKMedicalCertificateCheckBoxTypeRequiresCareYes","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeRequiresCareYes"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKMedicalCertificateCheckBoxTypeRequiresCareYes","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1requiresCareYes\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1requiresCareYes\/fragments","op":"replace","value":[{"text":"SBSDKMedicalCertificateCheckBoxTypeRequiresCareYes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType\/title","value":"SBSDKMedicalCertificateCheckBoxType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType\/fragments","op":"replace","value":[{"text":"SBSDKMedicalCertificateCheckBoxType","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateCheckBoxType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}