{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus(cpy)inferred","modules":[{"name":"ScanbotSDK"}],"title":"inferred","symbolKind":"property","role":"symbol","roleHeading":"Type Property","navigatorTitle":[{"text":"inferred","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"inferred"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus","kind":"typeIdentifier","text":"SBSDKGenericDocumentFieldValidationStatus"}]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/inferred","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus\/inferred"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus\/inferred"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"inferred","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentFieldValidationStatus","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Field value was inferred from other fields or from domain knowledge.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The field value may differ from what is actually written in the document in unexpected situations."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldValidationStatus":{"title":"SBSDKGenericDocumentFieldValidationStatus","abstract":[{"type":"text","text":"Field validation status."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentFieldValidationStatus"}],"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentFieldValidationStatus","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldValidationStatus/inferred":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/inferred","title":"inferred","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Field value was inferred from other fields or from domain knowledge."},{"text":" ","type":"text"},{"type":"text","text":"The field value may differ from what is actually written in the document in unexpected situations."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus\/inferred","role":"symbol","navigatorTitle":[{"text":"inferred","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"inferred"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus","text":"SBSDKGenericDocumentFieldValidationStatus"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"inferred","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"inferred","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus","kind":"typeIdentifier","text":"SBSDKGenericDocumentFieldValidationStatus"},{"kind":"text","text":" * "},{"text":"inferred","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus\/title","value":"SBSDKGenericDocumentFieldValidationStatus","op":"replace"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentFieldValidationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus\/navigatorTitle","op":"replace","value":[{"text":"SBSDKGenericDocumentFieldValidationStatus","kind":"identifier"}]},{"op":"replace","value":"inferred","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1inferred\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1inferred\/fragments","value":[{"kind":"identifier","text":"inferred"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}