{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encrypter:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes a new "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage"},{"text":" at the given storage location with given image file format.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage\/init(storagelocation:fileformat:encrypter:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage\/init(storagelocation:fileformat:encrypter:)"]}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"storageLocation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation"},{"kind":"text","text":"?, "},{"text":"fileFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKStorageCrypting","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?)"}],"symbolKind":"init","title":"init(storageLocation:fileFormat:encrypter:)","navigatorTitle":[{"kind":"identifier","text":"initWithStorageLocation:fileFormat:encrypter:"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKIndexedImageStorage(im)initWithStorageLocation:fileFormat:encrypter:","role":"symbol","roleHeading":"Initializer","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"storageLocation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation","kind":"typeIdentifier","text":"SBSDKStorageLocation","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageLocation"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"fileFormat"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat","kind":"typeIdentifier","text":"SBSDKImageFileFormat","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFileFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encrypter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?)"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"storageLocation","content":[{"inlineContent":[{"text":"The storage location at which the new storage should reside.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The file format that should be used to store the images.","type":"text"}],"type":"paragraph"}],"name":"fileFormat"},{"name":"encrypter","content":[{"type":"paragraph","inlineContent":[{"text":"The encrypter used to encrypt\/decrypt image data.If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", no encryption is used.","type":"text"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKIndexedImageStorage":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"type":"topic","abstract":[{"type":"text","text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class."},{"type":"text","text":" "},{"type":"text","text":"Manages images in an array-like fashion."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage","title":"SBSDKIndexedImageStorage","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKIndexedImageStorage"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageLocation":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageLocation"}],"type":"topic","abstract":[{"type":"text","text":"Descriptor and helper class for describing and creating a directory on the file system."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragelocation","title":"SBSDKStorageLocation","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageLocation","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKStorageLocation","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCrypting":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecrypting","role":"symbol","type":"topic","kind":"symbol","title":"SBSDKStorageCrypting","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCrypting","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKStorageCrypting","kind":"identifier"}],"abstract":[{"type":"text","text":"Protocol for implementing encryption and decryption of (streamed) data."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.1.1","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFileFormat":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFileFormat","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefileformat","abstract":[{"type":"text","text":"Enumeration of supported image file types."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKImageFileFormat","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFileFormat"}],"title":"SBSDKImageFileFormat"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKIndexedImageStorage/init(storageLocation:fileFormat:encrypter:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage\/init(storagelocation:fileformat:encrypter:)","title":"init(storageLocation:fileFormat:encrypter:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encrypter:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"storageLocation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation","text":"SBSDKStorageLocation","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"fileFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initializes a new "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage","type":"reference","isActive":true},{"type":"text","text":" at the given storage location with given image file format."}],"navigatorTitle":[{"text":"initWithStorageLocation:fileFormat:encrypter:","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithStorageLocation:fileFormat:encrypter:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithStorageLocation:fileFormat:encrypter:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithStorageLocation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageLocation","text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation"},{"text":" *) ","kind":"text"},{"text":"storageLocation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fileFormat:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat","text":"SBSDKImageFileFormat"},{"text":") ","kind":"text"},{"text":"fileFormat","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"encrypter:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","text":"id<SBSDKStorageCrypting>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"encrypter"},{"text":";","kind":"text"}]}]}},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The storage location at which the new storage should reside."}]}],"name":"storageLocation"},{"name":"fileFormat","content":[{"type":"paragraph","inlineContent":[{"text":"The file format that should be used to store the images.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The encrypter used to encrypt\/decrypt image data.If ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":", no encryption is used."}]}],"name":"encrypter"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SBSDKIndexedImageStorage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/fragments","value":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/navigatorTitle","value":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"op":"replace"},{"value":"SBSDKStorageLocation","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageLocation\/title"},{"value":[{"text":"SBSDKStorageLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageLocation\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKStorageLocation"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageLocation\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/title","op":"replace","value":"SBSDKStorageCrypting"},{"value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/navigatorTitle","value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}]},{"value":"SBSDKImageFileFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFileFormat\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFileFormat\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageFileFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFileFormat\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageFileFormat"}]},{"value":"initWithStorageLocation:fileFormat:encrypter:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage~1init(storageLocation:fileFormat:encrypter:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage~1init(storageLocation:fileFormat:encrypter:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStorageLocation:fileFormat:encrypter:"}]}]}]}