{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDevice\/isEqual:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevice\/isequal:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDevice"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCameraDevice(im)isEqual:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"method","title":"isEqual:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDevice/isEqual:":{"kind":"symbol","type":"topic","abstract":[],"title":"isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevice\/isequal:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDevice\/isEqual:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSession"}],"title":"SBSDKCameraSession","role":"symbol","abstract":[{"text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the","type":"text"},{"text":" ","type":"text"},{"text":"camera device and the preview layer. Provides functionality to capture still images.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSession"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDevice":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDevice"}],"title":"SBSDKCameraDevice","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDevice","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraDevice"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevice","type":"topic","abstract":[{"text":"The camera device to be used with a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKCameraSession","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/title"},{"op":"replace","value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/fragments"},{"op":"replace","value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/navigatorTitle"},{"op":"replace","value":"SBSDKCameraDevice","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevice\/title"},{"op":"replace","value":[{"text":"SBSDKCameraDevice","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevice\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraDevice"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevice\/navigatorTitle"}]}]}