{"metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"energySaving","kind":"identifier"}],"title":"SBSDKCheckScannerState.energySaving","externalID":"c:@M@ScanbotSDK@E@SBSDKCheckScannerState@SBSDKCheckScannerStateEnergySaving","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckScannerStateEnergySaving"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerstate\/energysaving"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerstate\/energysaving"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerState\/energySaving"},"abstract":[{"text":"The check scanner is in energy saving mode.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"energySaving","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerState"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerState/energySaving":{"abstract":[{"type":"text","text":"The check scanner is in energy saving mode."}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerState\/energySaving","kind":"symbol","title":"SBSDKCheckScannerState.energySaving","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"energySaving"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckScannerStateEnergySaving"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerstate\/energysaving"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerState":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKCheckScannerState","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The live scanning state of the check scanner.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerState","title":"SBSDKCheckScannerState","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerstate","navigatorTitle":[{"text":"SBSDKCheckScannerState","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKCheckScannerStateEnergySaving"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckScannerStateEnergySaving"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKCheckScannerStateEnergySaving"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKCheckScannerStateEnergySaving","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerState~1energySaving\/title"},{"op":"replace","value":[{"text":"SBSDKCheckScannerStateEnergySaving","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerState~1energySaving\/fragments"},{"value":"SBSDKCheckScannerState","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerState\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerState\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckScannerState"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerState\/navigatorTitle","value":[{"text":"SBSDKCheckScannerState","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}