{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult\/init(patientInfoBox:checkBoxes:dates:documentDetectionResult:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"patientInfoBox"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKMedicalCertificatePatientInfoBox","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoBox","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificatePatientInfoBox"},{"kind":"text","text":", "},{"kind":"externalParam","text":"checkBoxes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKMedicalCertificateCheckBox","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBox","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateCheckBox"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"dates"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKMedicalCertificateDateRecord","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateDateRecord"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"documentDetectionResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectionResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningresult\/init(patientinfobox:checkboxes:dates:documentdetectionresult:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningresult\/init(patientinfobox:checkboxes:dates:documentdetectionresult:)"]}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"patientInfoBox","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKMedicalCertificatePatientInfoBox","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificatePatientInfoBox","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"checkBoxes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKMedicalCertificateCheckBox","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateCheckBox","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"dates","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKMedicalCertificateDateRecord","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateDateRecord","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"documentDetectionResult","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningResult(im)initWithPatientInfoBox:checkBoxes:dates:documentDetectionResult:","symbolKind":"init","navigatorTitle":[{"text":"initWithPatientInfoBox:checkBoxes:dates:documentDetectionResult:","kind":"identifier"}],"title":"init(patientInfoBox:checkBoxes:dates:documentDetectionResult:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionResult":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult","title":"SBSDKDocumentDetectionResult","navigatorTitle":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"abstract":[{"type":"text","text":"Result of the document contour detection."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanningResult/init(patientInfoBox:checkBoxes:dates:documentDetectionResult:)":{"abstract":[],"title":"init(patientInfoBox:checkBoxes:dates:documentDetectionResult:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult\/init(patientInfoBox:checkBoxes:dates:documentDetectionResult:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"patientInfoBox","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificatePatientInfoBox","text":"SBSDKMedicalCertificatePatientInfoBox","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"checkBoxes","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateCheckBox","text":"SBSDKMedicalCertificateCheckBox","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"dates","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateDateRecord","text":"SBSDKMedicalCertificateDateRecord","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"documentDetectionResult","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningresult\/init(patientinfobox:checkboxes:dates:documentdetectionresult:)","type":"topic","navigatorTitle":[{"text":"initWithPatientInfoBox:checkBoxes:dates:documentDetectionResult:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBox":{"abstract":[{"type":"text","text":"Structure to contain full information about found box."}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBox","kind":"identifier"}],"title":"SBSDKMedicalCertificateCheckBox","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckbox","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBox","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateCheckBox","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanningResult":{"kind":"symbol","type":"topic","abstract":[{"text":"The result of the medical certificate scanning.","type":"text"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningresult","title":"SBSDKMedicalCertificateScanningResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoBox":{"abstract":[{"type":"text","text":"Patient information box."}],"title":"SBSDKMedicalCertificatePatientInfoBox","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificatePatientInfoBox","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfobox","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoBox","navigatorTitle":[{"text":"SBSDKMedicalCertificatePatientInfoBox","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecord":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateDateRecord","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateDateRecord","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord","title":"SBSDKMedicalCertificateDateRecord","abstract":[{"type":"text","text":"Structure to contain date record information."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithPatientInfoBox:checkBoxes:dates:documentDetectionResult:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPatientInfoBox:checkBoxes:dates:documentDetectionResult:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithPatientInfoBox:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMedicalCertificatePatientInfoBox","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificatePatientInfoBox","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoBox"},{"text":" *) ","kind":"text"},{"text":"patientInfoBox","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"checkBoxes:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKMedicalCertificateCheckBox *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"checkBoxes"},{"kind":"text","text":" "},{"kind":"identifier","text":"dates:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKMedicalCertificateDateRecord *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dates"},{"kind":"text","text":" "},{"text":"documentDetectionResult:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"documentDetectionResult","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKDocumentDetectionResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/navigatorTitle"},{"op":"replace","value":"initWithPatientInfoBox:checkBoxes:dates:documentDetectionResult:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult~1init(patientInfoBox:checkBoxes:dates:documentDetectionResult:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPatientInfoBox:checkBoxes:dates:documentDetectionResult:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult~1init(patientInfoBox:checkBoxes:dates:documentDetectionResult:)\/fragments"},{"op":"replace","value":"SBSDKMedicalCertificateCheckBox","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBox\/title"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateCheckBox","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBox\/fragments"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateCheckBox","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBox\/navigatorTitle"},{"op":"replace","value":"SBSDKMedicalCertificateScanningResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/title"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/fragments"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/navigatorTitle"},{"op":"replace","value":"SBSDKMedicalCertificatePatientInfoBox","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoBox\/title"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificatePatientInfoBox","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoBox\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoBox"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoBox\/navigatorTitle"},{"op":"replace","value":"SBSDKMedicalCertificateDateRecord","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord\/title"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateDateRecord","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord\/fragments"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateDateRecord","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord\/navigatorTitle"}]}]}