{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"}],"title":"init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"uiConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUIMedicalCertificateScannerUIConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerUIConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerTextConfiguration","text":"SBSDKUIMedicalCertificateScannerTextConfiguration"},{"kind":"text","text":", "},{"text":"behaviorConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerBehaviorConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUICameraConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration"},{"kind":"text","text":")"}],"roleHeading":"Initializer","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerConfiguration(im)initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"},"abstract":[{"text":"Designated initializer. Creates a new instance of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerConfiguration"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"uiConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerUIConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerUIConfiguration","text":"SBSDKUIMedicalCertificateScannerUIConfiguration"},{"text":", ","kind":"text"},{"text":"textConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerTextConfiguration","text":"SBSDKUIMedicalCertificateScannerTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerTextConfiguration"},{"kind":"text","text":", "},{"text":"behaviorConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerBehaviorConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraConfiguration"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration","text":"SBSDKUICameraConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"uiConfiguration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A configuration for the user interface. Defines colors and sizes."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"A configuration for text being displayed in the scanner screen."}],"type":"paragraph"}],"name":"textConfiguration"},{"name":"behaviorConfiguration","content":[{"inlineContent":[{"type":"text","text":"A configuration for the scanner’s behavior."}],"type":"paragraph"}]},{"name":"cameraConfiguration","content":[{"inlineContent":[{"type":"text","text":"A configuration for the scanner’s camera."}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:cameraconfiguration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:cameraconfiguration:)"]}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerUIConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerUIConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescanneruiconfiguration","title":"SBSDKUIMedicalCertificateScannerUIConfiguration","abstract":[{"text":"Configuration for the user interface of the RTU-UI medical certificate scanner.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerUIConfiguration","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUIMedicalCertificateScannerUIConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerConfiguration":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerconfiguration","kind":"symbol","abstract":[{"type":"text","text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI medical certificate scanner."}],"navigatorTitle":[{"text":"SBSDKUIMedicalCertificateScannerConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerConfiguration","title":"SBSDKUIMedicalCertificateScannerConfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerTextConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerTextConfiguration"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configuration for the textual contents of the medical certificate recognizer."}],"role":"symbol","title":"SBSDKUIMedicalCertificateScannerTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannertextconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerTextConfiguration","navigatorTitle":[{"text":"SBSDKUIMedicalCertificateScannerTextConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerConfiguration/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)":{"abstract":[{"type":"text","text":"Designated initializer. Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerConfiguration","type":"reference","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:cameraconfiguration:)","role":"symbol","title":"init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uiConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUIMedicalCertificateScannerUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerUIConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"textConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUIMedicalCertificateScannerTextConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerTextConfiguration"},{"text":", ","kind":"text"},{"text":"behaviorConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerBehaviorConfiguration","kind":"typeIdentifier","text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration"},{"kind":"text","text":", "},{"text":"cameraConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration","text":"SBSDKUICameraConfiguration"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","navigatorTitle":[{"text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraConfiguration":{"type":"topic","abstract":[{"type":"text","text":"Configuration for the camera of all RTU-UI components."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICameraConfiguration"}],"navigatorTitle":[{"text":"SBSDKUICameraConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuicameraconfiguration","title":"SBSDKUICameraConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerBehaviorConfiguration":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerbehaviorconfiguration","role":"symbol","title":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration for the behavior of the RTU-UI medical certificates scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithUiConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIMedicalCertificateScannerUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerUIConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"uiConfiguration"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerTextConfiguration","text":"SBSDKUIMedicalCertificateScannerTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerTextConfiguration"},{"kind":"text","text":" *) "},{"text":"textConfiguration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"behaviorConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration","text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerBehaviorConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"behaviorConfiguration"},{"kind":"text","text":" "},{"text":"cameraConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration","kind":"typeIdentifier","text":"SBSDKUICameraConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration"},{"kind":"text","text":" *) "},{"text":"cameraConfiguration","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"uiConfiguration","content":[{"inlineContent":[{"type":"text","text":"A configuration for the user interface. Defines colors and sizes."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"A configuration for text being displayed in the scanner screen."}],"type":"paragraph"}],"name":"textConfiguration"},{"content":[{"inlineContent":[{"text":"A configuration for the scanner’s behavior.","type":"text"}],"type":"paragraph"}],"name":"behaviorConfiguration"},{"name":"cameraConfiguration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A configuration for the scanner’s camera."}]}]}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerUIConfiguration\/title","value":"SBSDKUIMedicalCertificateScannerUIConfiguration"},{"value":[{"text":"SBSDKUIMedicalCertificateScannerUIConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerUIConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerUIConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerUIConfiguration\/navigatorTitle"},{"value":"SBSDKUIMedicalCertificateScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerConfiguration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerTextConfiguration\/title","value":"SBSDKUIMedicalCertificateScannerTextConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerTextConfiguration"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKUIMedicalCertificateScannerTextConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerTextConfiguration\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)\/title","value":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraConfiguration\/title","op":"replace","value":"SBSDKUICameraConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUICameraConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUICameraConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/title","value":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/fragments","value":[{"text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration"}],"op":"replace"}]}]}