{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeResidencePermitBack\/parsedDeAddress"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parsedDeAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelParsedDeAddress","text":"SBSDKDocumentsModelParsedDeAddress","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelParsedDeAddress"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"parsedDeAddress"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelDeResidencePermitBack(py)parsedDeAddress","role":"symbol","title":"parsedDeAddress","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parsedDeAddress","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelParsedDeAddress","text":"SBSDKDocumentsModelParsedDeAddress","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeResidencePermitBack"]]},"abstract":[{"type":"text","text":"The child document of type “ParsedDeAddress”."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelderesidencepermitback\/parseddeaddress"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelderesidencepermitback\/parseddeaddress"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeResidencePermitBack/parsedDeAddress":{"role":"symbol","abstract":[{"text":"The child document of type “ParsedDeAddress”.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parsedDeAddress","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelParsedDeAddress","text":"SBSDKDocumentsModelParsedDeAddress","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelderesidencepermitback\/parseddeaddress","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeResidencePermitBack\/parsedDeAddress","title":"parsedDeAddress","navigatorTitle":[{"text":"parsedDeAddress","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelParsedDeAddress":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelparseddeaddress","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelParsedDeAddress"}],"role":"symbol","abstract":[{"type":"text","text":"Parsed German Address part of the document"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelParsedDeAddress"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelParsedDeAddress","kind":"symbol","type":"topic","title":"SBSDKDocumentsModelParsedDeAddress"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeResidencePermitBack":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelderesidencepermitback","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeResidencePermitBack","title":"SBSDKDocumentsModelDeResidencePermitBack","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelDeResidencePermitBack"}],"abstract":[{"type":"text","text":"German Residence Permit (Aufenthaltstitel), Back side"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelDeResidencePermitBack"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"parsedDeAddress"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"parsedDeAddress","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelParsedDeAddress","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelParsedDeAddress","text":"SBSDKDocumentsModelParsedDeAddress"},{"kind":"text","text":" * "},{"kind":"identifier","text":"parsedDeAddress"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeResidencePermitBack~1parsedDeAddress\/title","value":"parsedDeAddress"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeResidencePermitBack~1parsedDeAddress\/fragments","value":[{"kind":"identifier","text":"parsedDeAddress"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelParsedDeAddress\/title","value":"SBSDKDocumentsModelParsedDeAddress","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelParsedDeAddress\/fragments","value":[{"text":"SBSDKDocumentsModelParsedDeAddress","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelParsedDeAddress\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentsModelParsedDeAddress"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeResidencePermitBack\/title","value":"SBSDKDocumentsModelDeResidencePermitBack","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeResidencePermitBack\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentsModelDeResidencePermitBack"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeResidencePermitBack\/navigatorTitle","value":[{"text":"SBSDKDocumentsModelDeResidencePermitBack","kind":"identifier"}],"op":"replace"}]}]}