{"sections":[],"metadata":{"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingAppearanceConfiguration(cm)fromJsonWithJson:","title":"fromJsonWithJson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Type Method"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingAppearanceConfiguration\/fromJsonWithJson:"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingappearanceconfiguration\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2CroppingAppearanceConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingAppearanceConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingAppearanceConfiguration"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"json"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingAppearanceConfiguration"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","abstract":[{"text":"Version: 8.0.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingAppearanceConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2CroppingAppearanceConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingAppearanceConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingAppearanceConfiguration","kind":"identifier"}],"title":"SBSDKUI2CroppingAppearanceConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingappearanceconfiguration","abstract":[{"text":"Configuration of the general appearance for the cropping screen.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingAppearanceConfiguration/fromJsonWithJson:":{"abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingappearanceconfiguration\/fromjsonwithjson:","type":"topic","title":"fromJsonWithJson:","kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingAppearanceConfiguration\/fromJsonWithJson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingAppearanceConfiguration\/title","op":"replace","value":"SBSDKUI2CroppingAppearanceConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKUI2CroppingAppearanceConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingAppearanceConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2CroppingAppearanceConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingAppearanceConfiguration\/navigatorTitle"}]}]}