{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(applyDocumentDetectionWithEngineMode:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applyDocumentDetection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"engineMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerEngineMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentScannerEngineMode","text":"SBSDKDocumentScannerEngineMode"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The mode of the document scanner."}]}],"name":"engineMode"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"applyDocumentDetectionWithEngineMode:","kind":"identifier"}],"role":"symbol","title":"applyDocumentDetection(engineMode:)","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPage(im)applyDocumentDetectionWithEngineMode:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyDocumentDetection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"engineMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentScannerEngineMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentScannerEngineMode"},{"text":")","kind":"text"}],"modules":[{"name":"ScanbotSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/applydocumentdetection(enginemode:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/applydocumentdetection(enginemode:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/applyDocumentDetection(engineMode:)"},"abstract":[{"text":"Detects the documents polygon on the original image of the receiver and applies it, regardless of the detection status.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerEngineMode":{"title":"SBSDKDocumentScannerEngineMode","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerenginemode","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerEngineMode","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerEngineMode","navigatorTitle":[{"text":"SBSDKDocumentScannerEngineMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Engines for document scanning."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/applyDocumentDetection(engineMode:)":{"navigatorTitle":[{"text":"applyDocumentDetectionWithEngineMode:","kind":"identifier"}],"title":"applyDocumentDetection(engineMode:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/applyDocumentDetection(engineMode:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/applydocumentdetection(enginemode:)","abstract":[{"text":"Detects the documents polygon on the original image of the receiver and applies it, regardless of the detection status.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyDocumentDetection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"engineMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentScannerEngineMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentScannerEngineMode"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPage"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"title":"SBSDKDocumentPage","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"applyDocumentDetectionWithEngineMode:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applyDocumentDetectionWithEngineMode:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"applyDocumentDetectionWithEngineMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerEngineMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentScannerEngineMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerEngineMode"},{"text":") ","kind":"text"},{"text":"engineMode","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"engineMode","content":[{"inlineContent":[{"type":"text","text":"The mode of the document scanner."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SBSDKDocumentScannerEngineMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerEngineMode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerEngineMode\/fragments","value":[{"text":"SBSDKDocumentScannerEngineMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerEngineMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentScannerEngineMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1applyDocumentDetection(engineMode:)\/title","value":"applyDocumentDetectionWithEngineMode:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1applyDocumentDetection(engineMode:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"applyDocumentDetectionWithEngineMode:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title","value":"SBSDKDocumentPage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/navigatorTitle","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}