{"metadata":{"title":"detectDocument(applyPolygonIfOkay:engineMode:)","navigatorTitle":[{"text":"detectDocumentAndApplyPolygonIfOkay:engineMode:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"applyPolygonIfOkay"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"engineMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentScannerEngineMode","kind":"typeIdentifier","text":"SBSDKDocumentScannerEngineMode"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","kind":"typeIdentifier","text":"SBSDKDocumentDetectionResult"},{"kind":"text","text":"?"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPage(im)detectDocumentAndApplyPolygonIfOkay:engineMode:","roleHeading":"Instance Method","symbolKind":"method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/detectDocument(applyPolygonIfOkay:engineMode:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(detectDocumentAndApplyPolygonIfOkay:engineMode:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"applyPolygonIfOkay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"engineMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentScannerEngineMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentScannerEngineMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerEngineMode"},{"text":") -> ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"If set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", the detected polygon will be applied to the receiver if its detection status is ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/ok","type":"reference"},{"text":".","type":"text"}]}],"name":"applyPolygonIfOkay"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The mode of the document scanner."}]}],"name":"engineMode"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The document scanner result describing the location of the detected document in the image and the status of the detection, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", if no document was detected.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/detectdocument(applypolygonifokay:enginemode:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/detectdocument(applypolygonifokay:enginemode:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Detects the documents polygon on the original image of the receiver."}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/detectDocument(applyPolygonIfOkay:engineMode:)":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/detectdocument(applypolygonifokay:enginemode:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/detectDocument(applyPolygonIfOkay:engineMode:)","title":"detectDocument(applyPolygonIfOkay:engineMode:)","navigatorTitle":[{"kind":"identifier","text":"detectDocumentAndApplyPolygonIfOkay:engineMode:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"applyPolygonIfOkay"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"engineMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentScannerEngineMode","kind":"typeIdentifier","text":"SBSDKDocumentScannerEngineMode"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","kind":"typeIdentifier","text":"SBSDKDocumentDetectionResult"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Detects the documents polygon on the original image of the receiver."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPage"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"title":"SBSDKDocumentPage","type":"topic","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionResult":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Result of the document contour detection."}],"title":"SBSDKDocumentDetectionResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/ok":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/ok","kind":"symbol","title":"SBSDKDocumentDetectionStatus.ok","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/ok","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatusOk","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ok","kind":"identifier"}],"abstract":[{"type":"text","text":"An acceptable document was detected."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerEngineMode":{"title":"SBSDKDocumentScannerEngineMode","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerenginemode","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerEngineMode","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerEngineMode","navigatorTitle":[{"text":"SBSDKDocumentScannerEngineMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Engines for document scanning."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"detectDocumentAndApplyPolygonIfOkay:engineMode:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detectDocumentAndApplyPolygonIfOkay:engineMode:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult"},{"text":" *) ","kind":"text"},{"text":"detectDocumentAndApplyPolygonIfOkay:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"applyPolygonIfOkay","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"engineMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentScannerEngineMode","text":"SBSDKDocumentScannerEngineMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerEngineMode"},{"text":") ","kind":"text"},{"text":"engineMode","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":", the detected polygon will be applied to the receiver if its detection status is "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/ok"},{"type":"text","text":"."}]}],"name":"applyPolygonIfOkay"},{"content":[{"inlineContent":[{"type":"text","text":"The mode of the document scanner."}],"type":"paragraph"}],"name":"engineMode"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"The document scanner result describing the location of the detected document in the image and the status of the detection, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", if no document was detected.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1detectDocument(applyPolygonIfOkay:engineMode:)\/title","value":"detectDocumentAndApplyPolygonIfOkay:engineMode:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1detectDocument(applyPolygonIfOkay:engineMode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detectDocumentAndApplyPolygonIfOkay:engineMode:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title","value":"SBSDKDocumentPage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentPage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/title","value":"SBSDKDocumentDetectionResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/fragments","value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1ok\/title","value":"SBSDKDocumentDetectionStatusOk"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1ok\/fragments","value":[{"text":"SBSDKDocumentDetectionStatusOk","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerEngineMode\/title","op":"replace","value":"SBSDKDocumentScannerEngineMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerEngineMode\/fragments","op":"replace","value":[{"text":"SBSDKDocumentScannerEngineMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerEngineMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentScannerEngineMode","kind":"identifier"}]}]}]}