{"abstract":[{"text":"String being displayed when health insurance card was found but not recognized.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerTextConfiguration\/detectionStatusFailedValidationText","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionStatusFailedValidationText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizertextconfiguration\/detectionstatusfailedvalidationtext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizertextconfiguration\/detectionstatusfailedvalidationtext"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerTextConfiguration"]]},"metadata":{"roleHeading":"Instance Property","title":"detectionStatusFailedValidationText","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionStatusFailedValidationText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardRecognizerTextConfiguration(py)detectionStatusFailedValidationText","symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"detectionStatusFailedValidationText"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerTextConfiguration/detectionStatusFailedValidationText":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionStatusFailedValidationText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerTextConfiguration\/detectionStatusFailedValidationText","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizertextconfiguration\/detectionstatusfailedvalidationtext","role":"symbol","abstract":[{"text":"String being displayed when health insurance card was found but not recognized.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"detectionStatusFailedValidationText"}],"kind":"symbol","title":"detectionStatusFailedValidationText","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerTextConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizertextconfiguration","abstract":[{"type":"text","text":"Configuration for the textual contents of the detector RTU-UI screen for Health Insurance Card scanner."}],"navigatorTitle":[{"text":"SBSDKUIHealthInsuranceCardRecognizerTextConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerTextConfiguration","title":"SBSDKUIHealthInsuranceCardRecognizerTextConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIHealthInsuranceCardRecognizerTextConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"detectionStatusFailedValidationText","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"detectionStatusFailedValidationText"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"detectionStatusFailedValidationText","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerTextConfiguration~1detectionStatusFailedValidationText\/title","value":"detectionStatusFailedValidationText","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerTextConfiguration~1detectionStatusFailedValidationText\/fragments","value":[{"kind":"identifier","text":"detectionStatusFailedValidationText"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerTextConfiguration\/title","value":"SBSDKUIHealthInsuranceCardRecognizerTextConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerTextConfiguration\/fragments","value":[{"text":"SBSDKUIHealthInsuranceCardRecognizerTextConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerTextConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIHealthInsuranceCardRecognizerTextConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}