{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultLicenseFailureHandler"},{"text":"() -> ","kind":"text"},{"text":"SBSDKLicenseFailureHandler","preciseIdentifier":"s:24ScanbotBarcodeScannerSDK26SBSDKLicenseFailureHandlera","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseFailureHandler"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The default license failure handler."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/Scanbot"]]},"abstract":[{"text":"The default license failure handler.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/scanbot\/defaultlicensefailurehandler()"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/scanbot\/defaultlicensefailurehandler()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Type Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"defaultLicenseFailureHandler"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)Scanbot(cm)defaultLicenseFailureHandler","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultLicenseFailureHandler","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:24ScanbotBarcodeScannerSDK26SBSDKLicenseFailureHandlera","kind":"typeIdentifier","text":"SBSDKLicenseFailureHandler"}],"title":"defaultLicenseFailureHandler()"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/Scanbot\/defaultLicenseFailureHandler()"},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/Scanbot":{"url":"\/documentation\/scanbotbarcodescannersdk\/scanbot","navigatorTitle":[{"kind":"identifier","text":"Scanbot"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/Scanbot","title":"Scanbot","abstract":[{"type":"text","text":"Main class of Scanbot SDK. Lets you install the license and allows basic configuration."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Scanbot","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/Scanbot/defaultLicenseFailureHandler()":{"url":"\/documentation\/scanbotbarcodescannersdk\/scanbot\/defaultlicensefailurehandler()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"defaultLicenseFailureHandler","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKLicenseFailureHandler","preciseIdentifier":"s:24ScanbotBarcodeScannerSDK26SBSDKLicenseFailureHandlera","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/Scanbot\/defaultLicenseFailureHandler()","title":"defaultLicenseFailureHandler()","role":"symbol","navigatorTitle":[{"text":"defaultLicenseFailureHandler","kind":"identifier"}],"abstract":[{"text":"The default license failure handler.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKLicenseFailureHandler":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseFailureHandler","abstract":[{"text":"Typealias for license failure handling closure.","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKLicenseFailureHandler","kind":"identifier"}],"title":"SBSDKLicenseFailureHandler","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseFailureHandler"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdklicensefailurehandler","role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"defaultLicenseFailureHandler","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"defaultLicenseFailureHandler","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void (^)(enum SBSDKLicenseStatus, enum SBSDKFeature, NSString *)","preciseIdentifier":"c:BFv(#$@M@ScanbotBarcodeScannerSDK@E@SBSDKLicenseStatus#$@M@ScanbotBarcodeScannerSDK@E@SBSDKFeature#*$objc(cs)NSString)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"defaultLicenseFailureHandler"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The default license failure handler.","type":"text"}]}],"kind":"content"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1Scanbot\/title","op":"replace","value":"Scanbot"},{"value":[{"text":"Scanbot","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1Scanbot\/fragments","op":"replace"},{"value":[{"text":"Scanbot","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1Scanbot\/navigatorTitle"},{"op":"replace","value":"defaultLicenseFailureHandler","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1Scanbot~1defaultLicenseFailureHandler()\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1Scanbot~1defaultLicenseFailureHandler()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"defaultLicenseFailureHandler"}],"op":"replace"}]}]}