{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"imageFileFormat","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"format","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat","kind":"typeIdentifier","text":"SBSDKImageFileFormat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"location"},{"text":": ","kind":"text"},{"text":"SBSDKStorageLocation","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation"},{"kind":"text","text":"?)"}]}]},{"kind":"parameters","parameters":[{"name":"format","content":[{"inlineContent":[{"type":"text","text":"The image file format."}],"type":"paragraph"}]},{"name":"location","content":[{"inlineContent":[{"type":"text","text":"The storage location where image files are saved to. If "},{"code":"nil","type":"codeVoice"},{"text":", the default location is chosen.","type":"text"}],"type":"paragraph"}]}]}],"kind":"symbol","metadata":{"symbolKind":"init","navigatorTitle":[{"text":"initWithImageFileFormat:location:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeImageStorage(im)initWithImageFileFormat:location:","roleHeading":"Initializer","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"imageFileFormat","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat"},{"text":", ","kind":"text"},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation"},{"kind":"text","text":"?)"}],"title":"init(imageFileFormat:location:)","modules":[{"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/init(imageFileFormat:location:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodeimagestorage\/init(imagefileformat:location:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodeimagestorage\/init(imagefileformat:location:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Initializes storage with given image file format and default JPEG compression quality."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeImageStorage":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage","title":"SBSDKUIBarcodeImageStorage","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeImageStorage"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeImageStorage"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeimagestorage","abstract":[{"text":"A class to store and remove barcode images from ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController"},{"text":".","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to detect QR and barcodes.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","role":"symbol","title":"SBSDKUIBarcodeScannerViewController","deprecated":true,"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageLocation":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkstoragelocation","abstract":[{"type":"text","text":"Descriptor and helper class for describing and creating a directory on the file system."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKStorageLocation","kind":"identifier"}],"title":"SBSDKStorageLocation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageLocation"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFileFormat":{"abstract":[{"type":"text","text":"Enumeration of supported image file types."}],"title":"SBSDKImageFileFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageFileFormat","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefileformat","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKImageFileFormat","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeImageStorage/init(imageFileFormat:location:)":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeimagestorage\/init(imagefileformat:location:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/init(imageFileFormat:location:)","abstract":[{"type":"text","text":"Initializes storage with given image file format and default JPEG compression quality."}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"imageFileFormat"},{"text":": ","kind":"text"},{"text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"location","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation","text":"SBSDKStorageLocation"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithImageFileFormat:location:","kind":"identifier"}],"title":"init(imageFileFormat:location:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithImageFileFormat:location:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithImageFileFormat:location:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"initWithImageFileFormat:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat","kind":"typeIdentifier","text":"SBSDKImageFileFormat"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"format"},{"text":" ","kind":"text"},{"kind":"identifier","text":"location:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation","text":"SBSDKStorageLocation"},{"kind":"text","text":" *) "},{"text":"location","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"format","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image file format."}]}]},{"name":"location","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The storage location where image files are saved to. If "},{"code":"nil","type":"codeVoice"},{"text":", the default location is chosen.","type":"text"}]}]}]}},{"value":"SBSDKUIBarcodeImageStorage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeImageStorage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage\/fragments","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUIBarcodeImageStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage\/navigatorTitle"},{"value":"SBSDKUIBarcodeScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/title","op":"replace","value":"SBSDKStorageLocation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/fragments","value":[{"text":"SBSDKStorageLocation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKStorageLocation"}],"op":"replace"},{"value":"SBSDKImageFileFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat\/fragments","value":[{"text":"SBSDKImageFileFormat","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat\/navigatorTitle","value":[{"text":"SBSDKImageFileFormat","kind":"identifier"}]},{"value":"initWithImageFileFormat:location:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1init(imageFileFormat:location:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1init(imageFileFormat:location:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageFileFormat:location:"}]}]}]}