{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentAnalysisMode"]]},"kind":"article","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentAnalysisMode\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentAnalysisMode\/!=(_:_:)"],"title":"Operators","generated":true,"anchor":"Operators"}],"metadata":{"role":"collectionGroup","modules":[{"name":"ScanbotSDK"}],"title":"Equatable Implementations","roleHeading":"API Collection"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentanalysismode\/equatable-implementations"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentAnalysisMode/!=(_:_:)":{"title":"!=(_:_:)","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentanalysismode\/!=(_:_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentAnalysisMode\/!=(_:_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentAnalysisMode":{"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2DocumentAnalysisMode","kind":"identifier"}],"title":"SBSDKUI2DocumentAnalysisMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentAnalysisMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentAnalysisMode","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Determines if the quality analysis for the acknowledgement mode will run on the filtered or the unfiltered image."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentanalysismode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2DocumentAnalysisMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentAnalysisMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentAnalysisMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentAnalysisMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentAnalysisMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentAnalysisMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}