{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerResult"]]},"kind":"symbol","metadata":{"title":"status","modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckRecognitionResultStatus","text":"SBSDKCheckRecognitionResultStatus","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"status"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerResult(py)status","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognitionResultStatus","text":"SBSDKCheckRecognitionResultStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckRecognitionResultStatus"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerresult\/status"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerresult\/status"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerResult\/status","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The status of the check recognition result."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerResult/status":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerResult\/status","navigatorTitle":[{"text":"status","kind":"identifier"}],"type":"topic","title":"status","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerresult\/status","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"text":"SBSDKCheckRecognitionResultStatus","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckRecognitionResultStatus","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The status of the check recognition result."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerResult","navigatorTitle":[{"text":"SBSDKCheckRecognizerResult","kind":"identifier"}],"type":"topic","title":"SBSDKCheckRecognizerResult","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerresult","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKCheckRecognizerResult","kind":"identifier"}],"abstract":[{"type":"text","text":"The result object of a check recognition."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognitionResultStatus":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognitionResultStatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCheckRecognitionResultStatus","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCheckRecognitionResultStatus","kind":"identifier"}],"title":"SBSDKCheckRecognitionResultStatus","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognitionresultstatus","role":"symbol","abstract":[{"text":"An enum describing the status of a check recognition.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"status","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"status","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognitionResultStatus","text":"SBSDKCheckRecognitionResultStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckRecognitionResultStatus"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"status","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerResult~1status\/title","op":"replace"},{"value":[{"kind":"identifier","text":"status"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerResult~1status\/fragments"},{"op":"replace","value":"SBSDKCheckRecognizerResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerResult\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerResult\/fragments","value":[{"text":"SBSDKCheckRecognizerResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognitionResultStatus\/title","value":"SBSDKCheckRecognitionResultStatus","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognitionResultStatus\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckRecognitionResultStatus"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}