{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScanningFlow"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentUuid"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScanningFlow\/documentUuid"},"kind":"symbol","abstract":[{"text":"The UUID of the existing document to be edited.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscanningflow\/documentuuid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscanningflow\/documentuuid"]}],"metadata":{"navigatorTitle":[{"text":"documentUuid","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentUuid"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"title":"documentUuid","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScanningFlow(py)documentUuid"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScanningFlow/documentUuid":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"documentUuid","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScanningFlow\/documentUuid","navigatorTitle":[{"text":"documentUuid","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanningflow\/documentuuid","title":"documentUuid","abstract":[{"type":"text","text":"The UUID of the existing document to be edited."}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScanningFlow":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentScanningFlow","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScanningFlow","title":"SBSDKUI2DocumentScanningFlow","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanningflow","navigatorTitle":[{"text":"SBSDKUI2DocumentScanningFlow","kind":"identifier"}],"abstract":[{"text":"Configuration of the document scanner screen.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"documentUuid","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"documentUuid"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"text":"documentUuid","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScanningFlow~1documentUuid\/title","value":"documentUuid","op":"replace"},{"value":[{"text":"documentUuid","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScanningFlow~1documentUuid\/fragments"},{"value":"SBSDKUI2DocumentScanningFlow","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScanningFlow\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScanningFlow\/fragments","value":[{"text":"SBSDKUI2DocumentScanningFlow","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScanningFlow\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentScanningFlow","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}