{"metadata":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeCustomLanguages","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"title":"removeCustomLanguages()","navigatorTitle":[{"kind":"identifier","text":"removeCustomLanguages"}],"roleHeading":"Type Method","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRLanguagesManager(cm)removeCustomLanguages"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/removecustomlanguages()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/removecustomlanguages()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/removeCustomLanguages()"},"abstract":[{"type":"text","text":"Removes the language files from the custom languages folder and resets the installed languages."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeCustomLanguages"},{"kind":"text","text":"()"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this method to get rid of all custom languages and restore the default languages only."}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager":{"title":"SBSDKOCRLanguagesManager","navigatorTitle":[{"kind":"identifier","text":"SBSDKOCRLanguagesManager"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager","abstract":[{"text":"Helper class to manage trained data files for the Tesseract OCR engine.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCRLanguagesManager"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager/removeCustomLanguages()":{"kind":"symbol","abstract":[{"text":"Removes the language files from the custom languages folder and resets the installed languages.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/removecustomlanguages()","title":"removeCustomLanguages()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/removeCustomLanguages()","navigatorTitle":[{"text":"removeCustomLanguages","kind":"identifier"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeCustomLanguages","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"removeCustomLanguages","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"removeCustomLanguages","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeCustomLanguages"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKOCRLanguagesManager","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager\/title"},{"value":[{"text":"SBSDKOCRLanguagesManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager\/fragments"},{"value":[{"text":"SBSDKOCRLanguagesManager","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager\/navigatorTitle","op":"replace"},{"value":"removeCustomLanguages","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1removeCustomLanguages()\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"removeCustomLanguages","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1removeCustomLanguages()\/fragments","op":"replace"}]}]}