{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckAccountNumberFieldNormalizedName","interfaceLanguage":"swift"},"abstract":[{"text":"Normalized full name of the “AccountNumber” field type in document type “CANCheck”.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"canCheckAccountNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/cancheckaccountnumberfieldnormalizedname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/cancheckaccountnumberfieldnormalizedname"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"title":"canCheckAccountNumberFieldNormalizedName","navigatorTitle":[{"text":"canCheckAccountNumberFieldNormalizedName","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentConstants(cpy)canCheckAccountNumberFieldNormalizedName","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"canCheckAccountNumberFieldNormalizedName","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Type Property","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants":{"abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckDocumentConstants"}],"kind":"symbol","title":"SBSDKCheckDocumentConstants","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKCheckDocumentConstants","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/canCheckAccountNumberFieldNormalizedName":{"type":"topic","abstract":[{"type":"text","text":"Normalized full name of the “AccountNumber” field type in document type “CANCheck”."}],"title":"canCheckAccountNumberFieldNormalizedName","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canCheckAccountNumberFieldNormalizedName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"canCheckAccountNumberFieldNormalizedName","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/cancheckaccountnumberfieldnormalizedname","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckAccountNumberFieldNormalizedName","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","value":"canCheckAccountNumberFieldNormalizedName","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"canCheckAccountNumberFieldNormalizedName"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"canCheckAccountNumberFieldNormalizedName"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants\/title","value":"SBSDKCheckDocumentConstants","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants\/fragments","op":"replace","value":[{"text":"SBSDKCheckDocumentConstants","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1canCheckAccountNumberFieldNormalizedName\/title","op":"replace","value":"canCheckAccountNumberFieldNormalizedName"},{"op":"replace","value":[{"kind":"identifier","text":"canCheckAccountNumberFieldNormalizedName"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1canCheckAccountNumberFieldNormalizedName\/fragments"}]}]}