{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/uaecheckroutingnumberfieldnormalizedname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/uaecheckroutingnumberfieldnormalizedname"]}],"abstract":[{"text":"Normalized full name of the “RoutingNumber” field type in document type “UAECheck”.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/uaeCheckRoutingNumberFieldNormalizedName","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uaeCheckRoutingNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentConstants(cpy)uaeCheckRoutingNumberFieldNormalizedName","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"uaeCheckRoutingNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"symbolKind":"property","navigatorTitle":[{"text":"uaeCheckRoutingNumberFieldNormalizedName","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Type Property","title":"uaeCheckRoutingNumberFieldNormalizedName"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/uaeCheckRoutingNumberFieldNormalizedName":{"kind":"symbol","title":"uaeCheckRoutingNumberFieldNormalizedName","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/uaeCheckRoutingNumberFieldNormalizedName","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/uaecheckroutingnumberfieldnormalizedname","abstract":[{"type":"text","text":"Normalized full name of the “RoutingNumber” field type in document type “UAECheck”."}],"navigatorTitle":[{"kind":"identifier","text":"uaeCheckRoutingNumberFieldNormalizedName"}],"type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uaeCheckRoutingNumberFieldNormalizedName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants":{"title":"SBSDKCheckDocumentConstants","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants","type":"topic","navigatorTitle":[{"text":"SBSDKCheckDocumentConstants","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCheckDocumentConstants"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"uaeCheckRoutingNumberFieldNormalizedName","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"uaeCheckRoutingNumberFieldNormalizedName","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"uaeCheckRoutingNumberFieldNormalizedName","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"uaeCheckRoutingNumberFieldNormalizedName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1uaeCheckRoutingNumberFieldNormalizedName\/title"},{"value":[{"kind":"identifier","text":"uaeCheckRoutingNumberFieldNormalizedName"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1uaeCheckRoutingNumberFieldNormalizedName\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants\/title","value":"SBSDKCheckDocumentConstants"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants\/fragments","value":[{"text":"SBSDKCheckDocumentConstants","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}