{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard\/usa","interfaceLanguage":"swift"},"abstract":[{"text":"A check compatible with the ASC X9 standard used in the USA.","type":"text"}],"metadata":{"roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"usa"}],"role":"symbol","symbolKind":"property","title":"usa","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckStandard(cpy)usa","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"usa","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCheckStandard","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckStandard","kind":"typeIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"usa","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCheckStandard","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckStandard","kind":"typeIdentifier"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckstandard\/usa"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckstandard\/usa"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckStandard/usa":{"type":"topic","kind":"symbol","title":"usa","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"usa","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckStandard","text":"SBSDKCheckStandard"}],"navigatorTitle":[{"text":"usa","kind":"identifier"}],"abstract":[{"type":"text","text":"A check compatible with the ASC X9 standard used in the USA."}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckstandard\/usa","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard\/usa"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckStandard":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKCheckStandard","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckstandard","title":"SBSDKCheckStandard","abstract":[{"text":"Supported check standards.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckStandard"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"usa","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"usa","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"SBSDKCheckStandard","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckStandard","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"usa","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"value":"usa","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckStandard~1usa\/title"},{"value":[{"text":"usa","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckStandard~1usa\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckStandard\/title","value":"SBSDKCheckStandard"},{"value":[{"text":"SBSDKCheckStandard","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckStandard\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckStandard\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCheckStandard","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}