{"metadata":{"role":"symbol","title":"barcodeFormatPdf417Configuration()","modules":[{"name":"ScanbotSDK"}],"externalID":"s:10ScanbotSDK35SBSDKBarcodeFormatConfigurationBaseC07barcoded6Pdf417E0AA0cd6PDF417E0CyFZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"barcodeFormatPdf417Configuration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatPDF417Configuration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatPDF417Configuration"}],"symbolKind":"method","roleHeading":"Type Method"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeFormatPdf417Configuration"},{"kind":"text","text":"() -> "},{"text":"SBSDKBarcodeFormatPDF417Configuration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPDF417Configuration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatPDF417Configuration","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatPdf417Configuration()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatpdf417configuration()"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatPDF417Configuration":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatpdf417configuration","abstract":[{"type":"text","text":"PDF417 configuration. Add to scanner configuration to scan PDF417 codes."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatPDF417Configuration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatPDF417Configuration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPDF417Configuration","title":"SBSDKBarcodeFormatPDF417Configuration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatPdf417Configuration()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatPdf417Configuration()","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatpdf417configuration()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeFormatPdf417Configuration"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatPDF417Configuration","kind":"typeIdentifier","text":"SBSDKBarcodeFormatPDF417Configuration"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[],"title":"barcodeFormatPdf417Configuration()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase":{"type":"topic","title":"SBSDKBarcodeFormatConfigurationBase","abstract":[{"type":"text","text":"Base class for all barcode configurations."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPDF417Configuration\/title","value":"SBSDKBarcodeFormatPDF417Configuration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPDF417Configuration\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeFormatPDF417Configuration","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKBarcodeFormatPDF417Configuration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPDF417Configuration\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase\/title","value":"SBSDKBarcodeFormatConfigurationBase","op":"replace"},{"op":"replace","value":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"op":"replace"}]}]}