{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller\/viewwillappear:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewWillAppear:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"animated"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController\/viewWillAppear:"},"metadata":{"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}],"title":"viewWillAppear:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerViewController(im)viewWillAppear:","roleHeading":"Instance Method"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController","type":"topic","title":"SBSDKBaseScannerViewController","navigatorTitle":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"A highly customizable camera view controller that delivers a basic camera functionality along with video","type":"text"},{"text":" ","type":"text"},{"text":"frame extraction and preprocessing, orientation correction and still image capturing.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewController/viewWillAppear:":{"title":"viewWillAppear:","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller\/viewwillappear:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController\/viewWillAppear:","abstract":[],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKBaseScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/navigatorTitle","op":"replace"}]}]}