{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkshutterbutton\/buttonscannedbackgroundcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkshutterbutton\/buttonscannedbackgroundcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton\/buttonScannedBackgroundColor","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"The background color of the receiver while the scanner status is "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannerStatus\/scanned","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Defaults to clear."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"dynamic"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonScannedBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"buttonScannedBackgroundColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buttonScannedBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"buttonScannedBackgroundColor"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKShutterButton(py)buttonScannedBackgroundColor"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKShutterButton":{"abstract":[{"text":"The button class used in the camera view controller to take a snapshot.","type":"text"},{"text":" ","type":"text"},{"text":"Animates itself depending on its status.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkshutterbutton","kind":"symbol","navigatorTitle":[{"text":"SBSDKShutterButton","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton","title":"SBSDKShutterButton","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKShutterButton","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannerStatus/scanned":{"title":"SBSDKScannerStatus.scanned","abstract":[{"text":"The scanner has scanned something.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanned","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannerStatus\/scanned","navigatorTitle":[{"text":"SBSDKScannerStatusScanned","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkscannerstatus\/scanned"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKShutterButton/buttonScannedBackgroundColor":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonScannedBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"abstract":[{"type":"text","text":"The background color of the receiver while the scanner status is "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannerStatus\/scanned"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Defaults to clear."}],"type":"topic","kind":"symbol","title":"buttonScannedBackgroundColor","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkshutterbutton\/buttonscannedbackgroundcolor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton\/buttonScannedBackgroundColor","navigatorTitle":[{"kind":"identifier","text":"buttonScannedBackgroundColor"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"buttonScannedBackgroundColor","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"buttonScannedBackgroundColor","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" * ","kind":"text"},{"text":"buttonScannedBackgroundColor","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKShutterButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton\/title"},{"value":[{"text":"SBSDKShutterButton","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKShutterButton"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton\/navigatorTitle"},{"value":"SBSDKScannerStatusScanned","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannerStatus~1scanned\/title"},{"value":[{"text":"SBSDKScannerStatusScanned","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannerStatus~1scanned\/fragments"},{"value":"buttonScannedBackgroundColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton~1buttonScannedBackgroundColor\/title"},{"value":[{"text":"buttonScannedBackgroundColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton~1buttonScannedBackgroundColor\/fragments"}]}]}