{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemInfoPosition"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeiteminfoposition\/init(rawvalue:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemInfoPosition\/init(rawValue:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"s:10ScanbotSDK31SBSDKUI2BarcodeItemInfoPositionO8rawValueACSgSi_tcfc","symbolKind":"init"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemInfoPosition/init(rawValue:)":{"title":"init(rawValue:)","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeiteminfoposition\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemInfoPosition\/init(rawValue:)","role":"symbol","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemInfoPosition":{"title":"SBSDKUI2BarcodeItemInfoPosition","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2BarcodeItemInfoPosition","kind":"identifier"}],"abstract":[{"type":"text","text":"Where to display the barcode info box in the camera preview."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeiteminfoposition","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeItemInfoPosition","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemInfoPosition","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemInfoPosition\/title","op":"replace","value":"SBSDKUI2BarcodeItemInfoPosition"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemInfoPosition\/fragments","value":[{"text":"SBSDKUI2BarcodeItemInfoPosition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemInfoPosition\/navigatorTitle","value":[{"text":"SBSDKUI2BarcodeItemInfoPosition","kind":"identifier"}],"op":"replace"}]}]}