{"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Display the barcode info box in the center of the overlay polygon.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemInfoPosition\/stacked","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"stacked","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemInfoPosition"]]},"metadata":{"roleHeading":"Case","title":"SBSDKUI2BarcodeItemInfoPosition.stacked","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodeItemInfoPosition@SBSDKUI2BarcodeItemInfoPositionStacked","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stacked"}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeItemInfoPositionStacked","kind":"identifier"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeiteminfoposition\/stacked"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeiteminfoposition\/stacked"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemInfoPosition/stacked":{"title":"SBSDKUI2BarcodeItemInfoPosition.stacked","type":"topic","navigatorTitle":[{"text":"SBSDKUI2BarcodeItemInfoPositionStacked","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeiteminfoposition\/stacked","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stacked"}],"abstract":[{"type":"text","text":"Display the barcode info box in the center of the overlay polygon."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemInfoPosition\/stacked","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemInfoPosition":{"role":"symbol","kind":"symbol","title":"SBSDKUI2BarcodeItemInfoPosition","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemInfoPosition","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeiteminfoposition","navigatorTitle":[{"text":"SBSDKUI2BarcodeItemInfoPosition","kind":"identifier"}],"abstract":[{"type":"text","text":"Where to display the barcode info box in the camera preview."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeItemInfoPosition"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKUI2BarcodeItemInfoPositionStacked","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemInfoPositionStacked"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKUI2BarcodeItemInfoPositionStacked","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemInfoPosition~1stacked\/title","value":"SBSDKUI2BarcodeItemInfoPositionStacked","op":"replace"},{"value":[{"text":"SBSDKUI2BarcodeItemInfoPositionStacked","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemInfoPosition~1stacked\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemInfoPosition\/title","op":"replace","value":"SBSDKUI2BarcodeItemInfoPosition"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemInfoPosition\/fragments","value":[{"text":"SBSDKUI2BarcodeItemInfoPosition","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}