{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"initWithMode:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithMode:"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithMode:"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataFrameExtractionParameters(im)initWithMode:","roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataFrameExtractionParameters\/initWithMode:"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithMode:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDataExtractionMode","text":"SBSDKDocumentDataExtractionMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mode"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataFrameExtractionParameters"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataframeextractionparameters\/initwithmode:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataFrameExtractionParameters/initWithMode:":{"role":"symbol","navigatorTitle":[{"text":"initWithMode:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataframeextractionparameters\/initwithmode:","kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataFrameExtractionParameters\/initWithMode:","title":"initWithMode:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithMode:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionMode":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractionMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentDataExtractionMode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionMode","title":"SBSDKDocumentDataExtractionMode","abstract":[{"text":"The extraction mode.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataFrameExtractionParameters":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataFrameExtractionParameters"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataFrameExtractionParameters"}],"title":"SBSDKDocumentDataFrameExtractionParameters","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataframeextractionparameters","abstract":[{"type":"text","text":"Parameters for the extraction process."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataFrameExtractionParameters"}},"variantOverrides":[{"patch":[{"value":"SBSDKDocumentDataExtractionMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionMode\/fragments","value":[{"text":"SBSDKDocumentDataExtractionMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionMode"}],"op":"replace"},{"value":"SBSDKDocumentDataFrameExtractionParameters","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataFrameExtractionParameters\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataFrameExtractionParameters\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDataFrameExtractionParameters"}]},{"value":[{"text":"SBSDKDocumentDataFrameExtractionParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataFrameExtractionParameters\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}