{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroScreenConfiguration"]]},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerIntroScreenConfiguration(im)init","title":"init()","modules":[{"name":"ScanbotSDK"}],"symbolKind":"init","role":"symbol","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroScreenConfiguration\/init()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerintroscreenconfiguration\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerintroscreenconfiguration\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerIntroScreenConfiguration/init()":{"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerintroscreenconfiguration\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroScreenConfiguration\/init()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerIntroScreenConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroScreenConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextPatternScannerIntroScreenConfiguration"}],"role":"symbol","kind":"symbol","type":"topic","title":"SBSDKUI2TextPatternScannerIntroScreenConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerIntroScreenConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerintroscreenconfiguration","abstract":[{"type":"text","text":"Configuration of the introduction screen for the generic text scanner."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"init"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroScreenConfiguration~1init()\/title","op":"replace","value":"init"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroScreenConfiguration~1init()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroScreenConfiguration\/title","op":"replace","value":"SBSDKUI2TextPatternScannerIntroScreenConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroScreenConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerIntroScreenConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroScreenConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2TextPatternScannerIntroScreenConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}