{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator\/generate(from:to:)-1lmnn","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"generate(from:to:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"], ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGenerator(im)generateFromImages:toFileURL:","navigatorTitle":[{"text":"generateFromImages:toFileURL:","kind":"identifier"}]},"sections":[],"abstract":[{"type":"text","text":"Synchronously converts the given images to a multipage-TIFF file and saves it to the specified URL."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(generateFromImages:toFileURL:) "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"generate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"images"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fileURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"images","content":[{"inlineContent":[{"type":"text","text":"The array of images to generate the multipage-TIFF from."}],"type":"paragraph"}]},{"name":"fileURL","content":[{"type":"paragraph","inlineContent":[{"text":"The file URL to save the TIFF file at.","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"text":" if the operation was successful, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" otherwise.","type":"text"}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktiffgenerator\/generate(from:to:)-1lmnn"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffgenerator\/generate(from:to:)-1lmnn"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGenerator/generate(from:to:)-1lmnn":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": ["},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"generateFromImages:toFileURL:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator\/generate(from:to:)-1lmnn","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Synchronously converts the given images to a multipage-TIFF file and saves it to the specified URL."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffgenerator\/generate(from:to:)-1lmnn","title":"generate(from:to:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGenerator":{"kind":"symbol","title":"SBSDKTIFFGenerator","url":"\/documentation\/scanbotsdk\/sbsdktiffgenerator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"abstract":[{"text":"A class that converts images to (multipage) TIFF images.","type":"text"},{"type":"text","text":" "},{"text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"When passing an encrypter the generated TIFF images will be encrypted."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"generateFromImages:toFileURL:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"generateFromImages:toFileURL:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"generateFromImages:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<UIImage *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"images","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"toFileURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fileURL"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"images","content":[{"inlineContent":[{"type":"text","text":"The array of images to generate the multipage-TIFF from."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The file URL to save the TIFF file at."}],"type":"paragraph"}],"name":"fileURL"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the operation was successful, "},{"type":"codeVoice","code":"false"},{"text":" otherwise.","type":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator~1generate(from:to:)-1lmnn\/title","value":"generateFromImages:toFileURL:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator~1generate(from:to:)-1lmnn\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"generateFromImages:toFileURL:","kind":"identifier"}]},{"value":"SBSDKTIFFGenerator","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/fragments","value":[{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"op":"replace"},{"value":[{"text":"SBSDKTIFFGenerator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/navigatorTitle"}]}]}