{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerConfiguration\/viewFinder","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Configuration of the view finder.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerconfiguration\/viewfinder"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerconfiguration\/viewfinder"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewFinder"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ViewFinderConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ViewFinderConfiguration","text":"SBSDKUI2ViewFinderConfiguration"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"symbolKind":"property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeScannerConfiguration(py)viewFinder","title":"viewFinder","navigatorTitle":[{"text":"viewFinder","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"viewFinder","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ViewFinderConfiguration"}],"roleHeading":"Instance Property","role":"symbol"},"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ViewFinderConfiguration":{"kind":"symbol","type":"topic","title":"SBSDKUI2ViewFinderConfiguration","navigatorTitle":[{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ViewFinderConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2viewfinderconfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration of the scanning interface’s viewfinder, serving as guidance to the user."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeScannerConfiguration":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}],"title":"SBSDKUI2BarcodeScannerConfiguration","abstract":[{"type":"text","text":"Configuration of the barcode scanner screen."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerConfiguration","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeScannerConfiguration/viewFinder":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerConfiguration\/viewFinder","title":"viewFinder","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewFinder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ViewFinderConfiguration"}],"type":"topic","abstract":[{"type":"text","text":"Configuration of the view finder."}],"role":"symbol","navigatorTitle":[{"text":"viewFinder","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerconfiguration\/viewfinder"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"viewFinder","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"viewFinder","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ViewFinderConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ViewFinderConfiguration","text":"SBSDKUI2ViewFinderConfiguration"},{"text":" * ","kind":"text"},{"text":"viewFinder","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ViewFinderConfiguration\/title","value":"SBSDKUI2ViewFinderConfiguration"},{"value":[{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ViewFinderConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ViewFinderConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2BarcodeScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2BarcodeScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration~1viewFinder\/title","value":"viewFinder"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration~1viewFinder\/fragments","value":[{"kind":"identifier","text":"viewFinder"}],"op":"replace"}]}]}