{"metadata":{"roleHeading":"Type Method","title":"fromJsonWithJson:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKInvalidDataVerificationReport(cm)fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"role":"symbol"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKInvalidDataVerificationReport","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKInvalidDataVerificationReport","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport\/fromjsonwithjson:"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/fromJsonWithJson:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKInvalidDataVerificationReport":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport","navigatorTitle":[{"kind":"identifier","text":"SBSDKInvalidDataVerificationReport"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKInvalidDataVerificationReport"}],"title":"SBSDKInvalidDataVerificationReport","abstract":[{"text":"Report of the field validation verification.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKInvalidDataVerificationReport/fromJsonWithJson:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/fromJsonWithJson:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"kind":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"url":"\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport\/fromjsonwithjson:","title":"fromJsonWithJson:","type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport\/title","value":"SBSDKInvalidDataVerificationReport"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport\/fragments","value":[{"kind":"identifier","text":"SBSDKInvalidDataVerificationReport"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKInvalidDataVerificationReport"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}