{"abstract":[{"text":"Select a full HD (1920x1080) video resolution.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"fullHD","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution\/fullhd"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution\/fullhd"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/fullHD"},"kind":"symbol","sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"fullHD","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Case","title":"SBSDKVideoFrameResolution.fullHD","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKVideoFrameResolution@SBSDKVideoFrameResolutionFullHD","navigatorTitle":[{"text":"SBSDKVideoFrameResolutionFullHD","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFrameResolution/fullHD":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionFullHD"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullHD","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution\/fullhd","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/fullHD","abstract":[{"text":"Select a full HD (1920x1080) video resolution.","type":"text"}],"role":"symbol","kind":"symbol","title":"SBSDKVideoFrameResolution.fullHD"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFrameResolution":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"title":"SBSDKVideoFrameResolution","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution","abstract":[{"type":"text","text":"An enum describing the resolution of a video or camera stream."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 6.1.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"SBSDKVideoFrameResolutionFullHD","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionFullHD"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKVideoFrameResolutionFullHD","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution~1fullHD\/title","value":"SBSDKVideoFrameResolutionFullHD"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution~1fullHD\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionFullHD"}]},{"value":"SBSDKVideoFrameResolution","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution\/fragments","op":"replace","value":[{"text":"SBSDKVideoFrameResolution","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution\/navigatorTitle","op":"replace"}]}]}