{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"doctor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanDoctorInformation","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MedicalPlanDoctorInformation","text":"SBSDKUI2MedicalPlanDoctorInformation"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2medicalplandocumentformat\/doctor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2medicalplandocumentformat\/doctor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanDocumentFormat\/doctor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Doctor Information"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"doctor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2MedicalPlanDoctorInformation","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MedicalPlanDoctorInformation"}],"title":"doctor","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MedicalPlanDocumentFormat(py)doctor","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"doctor"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanDocumentFormat"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalPlanDoctorInformation":{"role":"symbol","title":"SBSDKUI2MedicalPlanDoctorInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanDoctorInformation"}],"abstract":[{"type":"text","text":"Medical Plan Doctor Information"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanDoctorInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanDoctorInformation"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalplandoctorinformation"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalPlanDocumentFormat/doctor":{"role":"symbol","title":"doctor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"doctor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2MedicalPlanDoctorInformation","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MedicalPlanDoctorInformation"}],"abstract":[{"type":"text","text":"Doctor Information"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanDocumentFormat\/doctor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"doctor"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalplandocumentformat\/doctor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalPlanDocumentFormat":{"role":"symbol","title":"SBSDKUI2MedicalPlanDocumentFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanDocumentFormat"}],"abstract":[{"type":"text","text":"Medical Plan Document Format"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanDocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanDocumentFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalplandocumentformat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"doctor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"doctor"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanDoctorInformation","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MedicalPlanDoctorInformation","text":"SBSDKUI2MedicalPlanDoctorInformation"},{"kind":"text","text":" * "},{"kind":"identifier","text":"doctor"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanDoctorInformation\/title","value":"SBSDKUI2MedicalPlanDoctorInformation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanDoctorInformation\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanDoctorInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanDocumentFormat~1doctor\/title","value":"doctor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanDocumentFormat~1doctor\/fragments","value":[{"kind":"identifier","text":"doctor"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanDocumentFormat\/title","value":"SBSDKUI2MedicalPlanDocumentFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanDocumentFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanDocumentFormat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}