{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/cancelButtonAccessibilityLabel","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration"]]},"sections":[],"metadata":{"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cancelButtonAccessibilityLabel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"cancelButtonAccessibilityLabel","kind":"identifier"}],"title":"cancelButtonAccessibilityLabel","platforms":[],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerAccessibilityConfiguration(py)cancelButtonAccessibilityLabel","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Text, that is used as an accessibility label for the cancel button."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cancelButtonAccessibilityLabel","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to “Cancel”."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration\/cancelbuttonaccessibilitylabel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration\/cancelbuttonaccessibilitylabel"],"traits":[{"interfaceLanguage":"occ"}]}],"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}],"type":"paragraph"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerAccessibilityConfiguration/cancelButtonAccessibilityLabel":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration\/cancelbuttonaccessibilitylabel","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelButtonAccessibilityLabel","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","title":"cancelButtonAccessibilityLabel","type":"topic","navigatorTitle":[{"text":"cancelButtonAccessibilityLabel","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/cancelButtonAccessibilityLabel","deprecated":true,"abstract":[{"type":"text","text":"Text, that is used as an accessibility label for the cancel button."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerAccessibilityConfiguration":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"kind":"symbol","title":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration","deprecated":true,"abstract":[{"type":"text","text":"Configuration for the accessibility labels and hints."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.0.0","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"cancelButtonAccessibilityLabel","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"cancelButtonAccessibilityLabel","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"cancelButtonAccessibilityLabel"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"cancelButtonAccessibilityLabel","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration~1cancelButtonAccessibilityLabel\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration~1cancelButtonAccessibilityLabel\/fragments","value":[{"kind":"identifier","text":"cancelButtonAccessibilityLabel"}]},{"value":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}