{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroImage\/receiptsIntroImage()"},"sections":[],"metadata":{"roleHeading":"Type Method","title":"receiptsIntroImage()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiptsIntroImage"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReceiptsIntroImage","text":"SBSDKUI2ReceiptsIntroImage"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IntroImage(cm)receiptsIntroImage","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"receiptsIntroImage"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2introimage\/receiptsintroimage()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2introimage\/receiptsintroimage()"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroImage"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"receiptsIntroImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKUI2ReceiptsIntroImage","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReceiptsIntroImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReceiptsIntroImage"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroImage/receiptsIntroImage()":{"kind":"symbol","role":"symbol","title":"receiptsIntroImage()","url":"\/documentation\/scanbotsdk\/sbsdkui2introimage\/receiptsintroimage()","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"receiptsIntroImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReceiptsIntroImage","text":"SBSDKUI2ReceiptsIntroImage","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"receiptsIntroImage","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroImage\/receiptsIntroImage()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReceiptsIntroImage":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReceiptsIntroImage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ReceiptsIntroImage","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2ReceiptsIntroImage","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The image for the introduction screen with a receipt template."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2receiptsintroimage","title":"SBSDKUI2ReceiptsIntroImage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroImage":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2IntroImage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroImage","url":"\/documentation\/scanbotsdk\/sbsdkui2introimage","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2IntroImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Determines the image for the introduction screen."}],"type":"topic","title":"SBSDKUI2IntroImage"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"receiptsIntroImage","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"receiptsIntroImage","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReceiptsIntroImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReceiptsIntroImage","text":"SBSDKUI2ReceiptsIntroImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"receiptsIntroImage","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"receiptsIntroImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroImage~1receiptsIntroImage()\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroImage~1receiptsIntroImage()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"receiptsIntroImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReceiptsIntroImage\/title","value":"SBSDKUI2ReceiptsIntroImage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReceiptsIntroImage\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ReceiptsIntroImage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReceiptsIntroImage\/navigatorTitle","value":[{"text":"SBSDKUI2ReceiptsIntroImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroImage\/title","value":"SBSDKUI2IntroImage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroImage\/fragments","value":[{"text":"SBSDKUI2IntroImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroImage\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2IntroImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}