{"abstract":[{"type":"text","text":"The medical certificate scanner is scanning a medical certificate."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/scanning"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanning"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate\/scanning"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate\/scanning"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateScannerState@SBSDKMedicalCertificateScannerStateScanning","symbolKind":"case","title":"SBSDKMedicalCertificateScannerState.scanning","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerStateScanning"}],"roleHeading":"Case","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanning","kind":"identifier"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerState/scanning":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateScannerStateScanning","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanning","kind":"identifier"}],"abstract":[{"text":"The medical certificate scanner is scanning a medical certificate.","type":"text"}],"title":"SBSDKMedicalCertificateScannerState.scanning","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate\/scanning","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/scanning"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerState":{"type":"topic","navigatorTitle":[{"text":"SBSDKMedicalCertificateScannerState","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateScannerState","kind":"identifier"}],"title":"SBSDKMedicalCertificateScannerState","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState","abstract":[{"text":"The live scan state of the medical certificate scanner.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalCertificateScannerStateScanning"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKMedicalCertificateScannerStateScanning","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerStateScanning"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState~1scanning\/title","value":"SBSDKMedicalCertificateScannerStateScanning"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState~1scanning\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerStateScanning"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState\/title","value":"SBSDKMedicalCertificateScannerState"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerState"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerState"}]}]}]}