{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayGeneralConfiguration"]]},"abstract":[{"text":"If enabled, the scanner will always immediately scan a barcode in the viewfinder or the camera view. The overlay","type":"text"},{"type":"text","text":" "},{"type":"text","text":"will mark the scanned barcodes and stays above them."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayGeneralConfiguration\/automaticSelectionEnabled","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration(py)automaticSelectionEnabled","symbolKind":"property","title":"automaticSelectionEnabled","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"automaticSelectionEnabled"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"automaticSelectionEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"automaticSelectionEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Default is false","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaygeneralconfiguration\/automaticselectionenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaygeneralconfiguration\/automaticselectionenabled"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayGeneralConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayGeneralConfiguration","role":"symbol","abstract":[{"text":"Configuration of the AR overlay displayed on top of barcodes in the camera preview.","type":"text"}],"title":"SBSDKUI2ArOverlayGeneralConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaygeneralconfiguration","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayGeneralConfiguration/automaticSelectionEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automaticSelectionEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaygeneralconfiguration\/automaticselectionenabled","type":"topic","title":"automaticSelectionEnabled","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayGeneralConfiguration\/automaticSelectionEnabled","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"automaticSelectionEnabled"}],"abstract":[{"type":"text","text":"If enabled, the scanner will always immediately scan a barcode in the viewfinder or the camera view. The overlay"},{"type":"text","text":" "},{"text":"will mark the scanned barcodes and stays above them.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.2","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"automaticSelectionEnabled"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"automaticSelectionEnabled","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"automaticSelectionEnabled"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"SBSDKUI2ArOverlayGeneralConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayGeneralConfiguration~1automaticSelectionEnabled\/title","value":"automaticSelectionEnabled","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayGeneralConfiguration~1automaticSelectionEnabled\/fragments","value":[{"text":"automaticSelectionEnabled","kind":"identifier"}],"op":"replace"}]}]}