{"sections":[],"metadata":{"role":"symbol","symbolKind":"init","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Initializer","title":"init(minZoom:maxZoom:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"minZoom","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"maxZoom"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithMinZoom:andMaxZoom:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKZoomRange(im)initWithMinZoom:andMaxZoom:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomRange"]]},"abstract":[{"type":"text","text":"Designated initializer."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkzoomrange\/init(minzoom:maxzoom:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkzoomrange\/init(minzoom:maxzoom:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(initWithMinZoom:andMaxZoom:) ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"minZoom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"maxZoom"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"minZoom","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The minimum zoom scale."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The maximum zoom scale.","type":"text"}]}],"name":"maxZoom"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomRange\/init(minZoom:maxZoom:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKZoomRange/init(minZoom:maxZoom:)":{"title":"init(minZoom:maxZoom:)","kind":"symbol","abstract":[{"type":"text","text":"Designated initializer."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomRange\/init(minZoom:maxZoom:)","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"minZoom","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"text":"maxZoom","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkzoomrange\/init(minzoom:maxzoom:)","navigatorTitle":[{"kind":"identifier","text":"initWithMinZoom:andMaxZoom:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKZoomRange":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKZoomRange","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKZoomRange","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkzoomrange","title":"SBSDKZoomRange","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomRange","abstract":[{"type":"text","text":"Helper class to define a range for zooming."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithMinZoom:andMaxZoom:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMinZoom:andMaxZoom:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithMinZoom:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"text":") ","kind":"text"},{"text":"minZoom","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"andMaxZoom:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"text":") ","kind":"text"},{"text":"maxZoom","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"minZoom","content":[{"type":"paragraph","inlineContent":[{"text":"The minimum zoom scale.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The maximum zoom scale."}],"type":"paragraph"}],"name":"maxZoom"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomRange~1init(minZoom:maxZoom:)\/title","op":"replace","value":"initWithMinZoom:andMaxZoom:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomRange~1init(minZoom:maxZoom:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithMinZoom:andMaxZoom:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomRange\/title","op":"replace","value":"SBSDKZoomRange"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomRange\/fragments","value":[{"text":"SBSDKZoomRange","kind":"identifier"}]},{"value":[{"text":"SBSDKZoomRange","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomRange\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}