{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"SBSDKMedicalCertificatePatientInfoBox","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoBox","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificatePatientInfoBox"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfobox\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoBox"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:","symbolKind":"method","roleHeading":"Type Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificatePatientInfoBox(cm)fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}],"role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoBox\/fromJsonWithJson:","interfaceLanguage":"occ"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoBox":{"role":"symbol","title":"SBSDKMedicalCertificatePatientInfoBox","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoBox"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoBox","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfobox","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificatePatientInfoBox","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Patient information box."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoBox/fromJsonWithJson:":{"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfobox\/fromjsonwithjson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoBox\/fromJsonWithJson:","kind":"symbol","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:","type":"topic","role":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"SBSDKMedicalCertificatePatientInfoBox","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoBox\/title"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificatePatientInfoBox","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoBox\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoBox\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificatePatientInfoBox","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}