{"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Method","title":"initWithFrame:","symbolKind":"method","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKZoomingImageScrollView(im)initWithFrame:"},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/initWithFrame:","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"frame"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview\/initwithframe:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKZoomingImageScrollView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview","abstract":[{"text":"A scrollable and zoomable ","type":"text"},{"type":"codeVoice","code":"UIScrollView"},{"text":" subclass that displays images and an overlay view.","type":"text"}],"title":"SBSDKZoomingImageScrollView","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKZoomingImageScrollView/initWithFrame:":{"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview\/initwithframe:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/initWithFrame:","title":"initWithFrame:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithFrame:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView\/title","value":"SBSDKZoomingImageScrollView","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView\/fragments","op":"replace","value":[{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView\/navigatorTitle"}]}]}