{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation"]]},"abstract":[{"text":"The edge is oriented horizontally.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdklinesegmentorientation\/horizontal"]},{"paths":["\/documentation\/scanbotsdk\/sbsdklinesegmentorientation\/horizontal"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontal"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/horizontal"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"case","roleHeading":"Case","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKLineSegmentOrientation@SBSDKLineSegmentOrientationHorizontal","title":"SBSDKLineSegmentOrientation.horizontal","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"horizontal","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKLineSegmentOrientationHorizontal","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegmentOrientation":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdklinesegmentorientation","abstract":[{"type":"text","text":"An enum describing the orientation of a polygon edge."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKLineSegmentOrientation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLineSegmentOrientation"}],"title":"SBSDKLineSegmentOrientation"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegmentOrientation/horizontal":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKLineSegmentOrientationHorizontal"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"horizontal","kind":"identifier"}],"title":"SBSDKLineSegmentOrientation.horizontal","abstract":[{"text":"The edge is oriented horizontally.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdklinesegmentorientation\/horizontal","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/horizontal","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKLineSegmentOrientationHorizontal"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKLineSegmentOrientationHorizontal"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKLineSegmentOrientationHorizontal"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation\/title","value":"SBSDKLineSegmentOrientation","op":"replace"},{"value":[{"text":"SBSDKLineSegmentOrientation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLineSegmentOrientation"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation~1horizontal\/title","op":"replace","value":"SBSDKLineSegmentOrientationHorizontal"},{"value":[{"text":"SBSDKLineSegmentOrientationHorizontal","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation~1horizontal\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}