{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingFieldType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MedicalPlanStandardSubheadingFieldType","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanstandardsubheadingfield\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanstandardsubheadingfield\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingField\/type","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Medical Plan Standard Subheading Field Type"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MedicalPlanStandardSubheadingFieldType"}],"title":"type","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2MedicalPlanStandardSubheadingField(py)type","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"type"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingField"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanStandardSubheadingField":{"role":"symbol","title":"SBSDKUI2MedicalPlanStandardSubheadingField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingField"}],"abstract":[{"type":"text","text":"Medical Plan Standard Subheading Field"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingField"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanstandardsubheadingfield"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanStandardSubheadingField/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MedicalPlanStandardSubheadingFieldType"}],"abstract":[{"type":"text","text":"Medical Plan Standard Subheading Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingField\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanstandardsubheadingfield\/type"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanStandardSubheadingFieldType":{"role":"symbol","title":"SBSDKUI2MedicalPlanStandardSubheadingFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldType"}],"abstract":[{"type":"text","text":"Medical Plan Standard Subheading Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanstandardsubheadingfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingFieldType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MedicalPlanStandardSubheadingFieldType","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanStandardSubheadingField\/title","value":"SBSDKUI2MedicalPlanStandardSubheadingField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanStandardSubheadingField\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingField"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanStandardSubheadingField~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanStandardSubheadingField~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanStandardSubheadingFieldType\/title","value":"SBSDKUI2MedicalPlanStandardSubheadingFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanStandardSubheadingFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}