{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"type":"text","text":"Manufacturer of the lens. Optional."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lensMaker","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"title":"lensMaker","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKLensCameraProperties(py)lensMaker","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lensMaker","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"lensMaker","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLensCameraProperties\/lensMaker","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLensCameraProperties"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklenscameraproperties\/lensmaker"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdklenscameraproperties\/lensmaker"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLensCameraProperties/lensMaker":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"lensMaker","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLensCameraProperties\/lensMaker","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklenscameraproperties\/lensmaker","title":"lensMaker","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lensMaker","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"text":"Manufacturer of the lens. Optional.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLensCameraProperties":{"abstract":[{"text":"Encapsulates lens and camera properties. Can be used with polygonal image cropping to achieve a very accurate aspect ratio of the resulting image.","type":"text"},{"text":" ","type":"text"},{"text":"If created from image image metadata, uses a dictionary of some known devices to lookup the values.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLensCameraProperties"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLensCameraProperties"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLensCameraProperties","title":"SBSDKLensCameraProperties","url":"\/documentation\/scanbotsdk\/sbsdklenscameraproperties","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"lensMaker","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"lensMaker","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"lensMaker","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"lensMaker","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLensCameraProperties~1lensMaker\/title","op":"replace"},{"value":[{"text":"lensMaker","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLensCameraProperties~1lensMaker\/fragments","op":"replace"},{"value":"SBSDKLensCameraProperties","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLensCameraProperties\/title","op":"replace"},{"value":[{"text":"SBSDKLensCameraProperties","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLensCameraProperties\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLensCameraProperties"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLensCameraProperties\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}