{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/!=(_:_:)"},"metadata":{"role":"symbol","title":"!=(_:_:)","modules":[{"relatedModules":["Swift"],"name":"ScanbotSDK"}],"extendedModule":"Swift","symbolKind":"op","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@ScanbotSDK@E@SBSDKUI2CapturePhotoQualityPrioritization","roleHeading":"Operator","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/Equatable-Implementations"]]},"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization/Equatable-Implementations":{"abstract":[],"role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization\/equatable-implementations","kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/Equatable-Implementations","title":"Equatable Implementations","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization/!=(_:_:)":{"type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization\/!=(_:_:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/!=(_:_:)","title":"!=(_:_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization":{"navigatorTitle":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization","title":"SBSDKUI2CapturePhotoQualityPrioritization","url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"abstract":[{"text":"Determines the prioritization of still image quality and capturing speed.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2CapturePhotoQualityPrioritization","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/title","op":"replace"},{"value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}