{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackMode\/hash","interfaceLanguage":"occ"},"sections":[],"metadata":{"fragments":[{"kind":"identifier","text":"hash"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PageSnapFeedbackMode(py)hash","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"symbolKind":"property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackMode"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapfeedbackmode\/hash"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PageSnapFeedbackMode":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapfeedbackmode","title":"SBSDKUI2PageSnapFeedbackMode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackMode"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackMode","navigatorTitle":[{"text":"SBSDKUI2PageSnapFeedbackMode","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The type of animation to display after snapping a page."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PageSnapFeedbackMode/hash":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackMode\/hash","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapfeedbackmode\/hash","kind":"symbol","abstract":[],"title":"hash","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"hash"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","url":"\/documentation\/scanbotdocumentscannersdk","abstract":[{"type":"text","text":"Version: 6.2.0"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2PageSnapFeedbackMode","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackMode\/fragments","value":[{"text":"SBSDKUI2PageSnapFeedbackMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}