{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage"]]},"abstract":[{"text":"Applies one or more editing operations on the page at once asynchronously and calls the completion block after finishing.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/applyAsync(rotation:polygon:filters:completion:)"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedPage(im)applyAsyncWithRotation:polygon:filters:completion:","role":"symbol","title":"applyAsync(rotation:polygon:filters:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyAsync","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rotation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageRotation","text":"SBSDKImageRotation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"filters","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (() -> ())?)","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"applyAsyncWithRotation:polygon:filters:completion:","kind":"identifier"}],"symbolKind":"method"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkscannedpage\/applyasync(rotation:polygon:filters:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkscannedpage\/applyasync(rotation:polygon:filters:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyAsync","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rotation","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation","text":"SBSDKImageRotation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageRotation"},{"text":" = .none, ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"text":"? = nil, ","kind":"text"},{"text":"filters","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"text":"]? = nil, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (() -> ())? = nil)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"rotation","content":[{"inlineContent":[{"text":"The rotation of the receiver.","type":"text"}],"type":"paragraph"}]},{"name":"polygon","content":[{"type":"paragraph","inlineContent":[{"text":"The cropping polygon of the receiver. Pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if you do not wish to crop the receiver.","type":"text"}]}]},{"name":"filters","content":[{"inlineContent":[{"text":"The filters to apply on the receiver. Pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if you do not wish to filter the receiver.","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The completion handler to be called after the operation has finished."}],"type":"paragraph"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRotation":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation","url":"\/documentation\/scanbotsdk\/sbsdkimagerotation","title":"SBSDKImageRotation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRotation"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRotation"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Image rotation."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter","navigatorTitle":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"type":"topic","role":"symbol","abstract":[{"text":"Base class for all parametric filters.","type":"text"}],"title":"SBSDKParametricFilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKParametricFilter"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedPage","kind":"identifier"}],"abstract":[{"text":"A scanned page (","type":"text"},{"code":"SBSDKScannedPage","type":"codeVoice"},{"text":") is a representation of a scanned documents page in digital form.","type":"text"},{"text":" ","type":"text"},{"text":"Each page consists of an original image of the scan, various editing properties like cropping polygon, rotation and filters, some metadata properties like the document detection status and the document quality analyzer result and a number of processed images in different stages.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkscannedpage","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKScannedPage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage","title":"SBSDKScannedPage","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"abstract":[{"text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","navigatorTitle":[{"text":"SBSDKPolygon","kind":"identifier"}],"title":"SBSDKPolygon","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygon","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/applyAsync(rotation:polygon:filters:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyAsync","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rotation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageRotation","text":"SBSDKImageRotation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"filters","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (() -> ())?)","kind":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/applyasync(rotation:polygon:filters:completion:)","navigatorTitle":[{"text":"applyAsyncWithRotation:polygon:filters:completion:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/applyAsync(rotation:polygon:filters:completion:)","abstract":[{"type":"text","text":"Applies one or more editing operations on the page at once asynchronously and calls the completion block after finishing."}],"title":"applyAsync(rotation:polygon:filters:completion:)","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"applyAsyncWithRotation:polygon:filters:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"applyAsyncWithRotation:polygon:filters:completion:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"applyAsyncWithRotation:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageRotation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation","text":"SBSDKImageRotation"},{"kind":"text","text":") "},{"kind":"internalParam","text":"rotation"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygon:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","text":"SBSDKPolygon"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"polygon"},{"kind":"text","text":" "},{"kind":"identifier","text":"filters:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKParametricFilter *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"filters"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")()) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The rotation of the receiver."}]}],"name":"rotation"},{"content":[{"inlineContent":[{"type":"text","text":"The cropping polygon of the receiver. Pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if you do not wish to crop the receiver."}],"type":"paragraph"}],"name":"polygon"},{"content":[{"inlineContent":[{"text":"The filters to apply on the receiver. Pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if you do not wish to filter the receiver.","type":"text"}],"type":"paragraph"}],"name":"filters"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The completion handler to be called after the operation has finished.","type":"text"}]}],"name":"completion"}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/title","value":"SBSDKImageRotation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/fragments","value":[{"kind":"identifier","text":"SBSDKImageRotation"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageRotation"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/title","value":"SBSDKParametricFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/fragments","value":[{"text":"SBSDKParametricFilter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKParametricFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/title","value":"SBSDKScannedPage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/fragments","value":[{"text":"SBSDKScannedPage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKScannedPage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title","value":"SBSDKPolygon"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments","value":[{"text":"SBSDKPolygon","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/navigatorTitle","value":[{"text":"SBSDKPolygon","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1applyAsync(rotation:polygon:filters:completion:)\/title","value":"applyAsyncWithRotation:polygon:filters:completion:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1applyAsync(rotation:polygon:filters:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"applyAsyncWithRotation:polygon:filters:completion:","kind":"identifier"}]}]}]}