{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkresultaccumulationconfiguration\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration\/fromJsonWithJson:"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKResultAccumulationConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKResultAccumulationConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"role":"symbol","title":"fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKResultAccumulationConfiguration(cm)fromJsonWithJson:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"roleHeading":"Type Method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResultAccumulationConfiguration":{"abstract":[{"text":"Configuration for how to accumulate results.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}],"title":"SBSDKResultAccumulationConfiguration","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkresultaccumulationconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResultAccumulationConfiguration/fromJsonWithJson:":{"title":"fromJsonWithJson:","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration\/fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"url":"\/documentation\/scanbotsdk\/sbsdkresultaccumulationconfiguration\/fromjsonwithjson:"}},"variantOverrides":[{"patch":[{"value":"SBSDKResultAccumulationConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKResultAccumulationConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}