{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerForm\/type1a","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerForm@SBSDKMedicalCertificateRecognizerFormType1a","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerFormType1a","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"type1a","kind":"identifier"}],"roleHeading":"Case","title":"SBSDKMedicalCertificateRecognizerForm.type1a"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerForm"]]},"kind":"symbol","abstract":[{"text":"Type 1A.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerform\/type1a"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerform\/type1a"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"type1a","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerForm/type1a":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerFormType1a"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type1a"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerForm\/type1a","abstract":[{"type":"text","text":"Type 1A."}],"title":"SBSDKMedicalCertificateRecognizerForm.type1a","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerform\/type1a"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerForm":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerform","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerForm","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerForm","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerForm","kind":"identifier"}],"role":"symbol","title":"SBSDKMedicalCertificateRecognizerForm","abstract":[{"text":"The form type of a recognized medical certificate.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKMedicalCertificateRecognizerFormType1a"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerFormType1a"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerFormType1a"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKMedicalCertificateRecognizerFormType1a","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerForm~1type1a\/title"},{"value":[{"text":"SBSDKMedicalCertificateRecognizerFormType1a","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerForm~1type1a\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerForm\/title","value":"SBSDKMedicalCertificateRecognizerForm","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerForm"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerForm\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}