{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerForm\/type1b"},"metadata":{"role":"symbol","roleHeading":"Case","symbolKind":"case","title":"SBSDKMedicalCertificateRecognizerForm.type1b","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type1b","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerFormType1b","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerForm@SBSDKMedicalCertificateRecognizerFormType1b","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerForm"]]},"abstract":[{"type":"text","text":"Type 1B."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type1b"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerform\/type1b"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerform\/type1b"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerForm/type1b":{"abstract":[{"type":"text","text":"Type 1B."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerForm\/type1b","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerform\/type1b","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerFormType1b"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type1b"}],"title":"SBSDKMedicalCertificateRecognizerForm.type1b"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerForm":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerForm","kind":"identifier"}],"abstract":[{"text":"The form type of a recognized medical certificate.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerform","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerForm","type":"topic","title":"SBSDKMedicalCertificateRecognizerForm","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerForm"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKMedicalCertificateRecognizerFormType1b","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerFormType1b"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKMedicalCertificateRecognizerFormType1b","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerForm~1type1b\/title","op":"replace","value":"SBSDKMedicalCertificateRecognizerFormType1b"},{"value":[{"text":"SBSDKMedicalCertificateRecognizerFormType1b","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerForm~1type1b\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerForm\/title","value":"SBSDKMedicalCertificateRecognizerForm","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerForm"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerForm\/fragments"}]}]}