{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"type21aBack"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerform\/type21aback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerform\/type21aback"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerForm\/type21aBack","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Type 21A Back."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"type21aBack"}],"title":"SBSDKMedicalCertificateRecognizerForm.type21aBack","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerForm@SBSDKMedicalCertificateRecognizerFormType21aBack","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerFormType21aBack"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerForm"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerForm":{"role":"symbol","title":"SBSDKMedicalCertificateRecognizerForm","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerForm"}],"abstract":[{"type":"text","text":"The form type of a recognized medical certificate."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerForm","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerForm"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerform"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerForm/type21aBack":{"role":"symbol","title":"SBSDKMedicalCertificateRecognizerForm.type21aBack","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"type21aBack"}],"abstract":[{"type":"text","text":"Type 21A Back."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerForm\/type21aBack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerFormType21aBack"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerform\/type21aback"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalCertificateRecognizerFormType21aBack"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerFormType21aBack"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerFormType21aBack"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerForm\/title","value":"SBSDKMedicalCertificateRecognizerForm"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerForm\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerForm"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerForm~1type21aBack\/title","value":"SBSDKMedicalCertificateRecognizerFormType21aBack"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerForm~1type21aBack\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerFormType21aBack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}