{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVA\/idCard","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVA"]]},"abstract":[{"type":"text","text":"IDCard."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamva\/idcard"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamva\/idcard"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"idCard","kind":"identifier"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"idCard"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVADLID","kind":"typeIdentifier","text":"SBSDKBarcodeDocumentAAMVADLID"},{"kind":"text","text":"?"}],"role":"symbol","title":"idCard","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVA(py)idCard"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"idCard","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVADLID","text":"SBSDKBarcodeDocumentAAMVADLID","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVADLID"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVADLID":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvadlid","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentAAMVADLID","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentAAMVADLID","kind":"identifier"}],"title":"SBSDKBarcodeDocumentAAMVADLID","type":"topic","abstract":[{"type":"text","text":"Driver License Or ID Document."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVADLID","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVA/idCard":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVA\/idCard","title":"idCard","navigatorTitle":[{"text":"idCard","kind":"identifier"}],"abstract":[{"type":"text","text":"IDCard."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"idCard"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVADLID","text":"SBSDKBarcodeDocumentAAMVADLID","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamva\/idcard","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVA":{"navigatorTitle":[{"text":"SBSDKBarcodeDocumentAAMVA","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVA","role":"symbol","title":"SBSDKBarcodeDocumentAAMVA","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamva","abstract":[{"type":"text","text":"AAMVA."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVA"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"idCard"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"idCard","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVADLID","text":"SBSDKBarcodeDocumentAAMVADLID","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVADLID","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"idCard"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVADLID\/title","value":"SBSDKBarcodeDocumentAAMVADLID"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVADLID"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVADLID\/fragments"},{"value":"idCard","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVA~1idCard\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVA~1idCard\/fragments","value":[{"text":"idCard","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVA\/title","value":"SBSDKBarcodeDocumentAAMVA"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVA\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVA"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}