{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamva\/registrationdata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamva\/registrationdata"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVA\/registrationData"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registrationData"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVARegistrationData","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData","kind":"typeIdentifier","text":"SBSDKBarcodeDocumentAAMVARegistrationData"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"RegistrationData.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVA"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVA(py)registrationData","title":"registrationData","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"registrationData","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKBarcodeDocumentAAMVARegistrationData","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVARegistrationData"},{"text":"?","kind":"text"}],"symbolKind":"property","navigatorTitle":[{"text":"registrationData","kind":"identifier"}],"roleHeading":"Instance Property"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVARegistrationData"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentAAMVARegistrationData","kind":"identifier"}],"title":"SBSDKBarcodeDocumentAAMVARegistrationData","abstract":[{"type":"text","text":"Registration Data. File type “RG”."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVA/registrationData":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVA\/registrationData","abstract":[{"type":"text","text":"RegistrationData."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"registrationData"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamva\/registrationdata","role":"symbol","title":"registrationData","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registrationData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeDocumentAAMVARegistrationData","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVARegistrationData"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVA":{"title":"SBSDKBarcodeDocumentAAMVA","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVA"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVA","kind":"symbol","abstract":[{"type":"text","text":"AAMVA."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamva","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentAAMVA","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"registrationData","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"registrationData"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVARegistrationData","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData","text":"SBSDKBarcodeDocumentAAMVARegistrationData","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"registrationData","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKBarcodeDocumentAAMVARegistrationData","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData\/fragments","value":[{"text":"SBSDKBarcodeDocumentAAMVARegistrationData","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"registrationData","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVA~1registrationData\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVA~1registrationData\/fragments","value":[{"text":"registrationData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVA\/title","value":"SBSDKBarcodeDocumentAAMVA"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVA\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVA"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}