{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamva\/vehiclesafetyinspectiondata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamva\/vehiclesafetyinspectiondata"]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"vehicleSafetyInspectionData","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVA(py)vehicleSafetyInspectionData","title":"vehicleSafetyInspectionData","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"vehicleSafetyInspectionData","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"typeIdentifier","text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData"},{"kind":"text","text":"?"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVA"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVA\/vehicleSafetyInspectionData","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"vehicleSafetyInspectionData","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"VehicleSafetyInspectionData."}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData":{"kind":"symbol","type":"topic","title":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata","navigatorTitle":[{"text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"identifier"}],"abstract":[{"type":"text","text":"Vehicle Safety Inspection Data. File type “VS”."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVA/vehicleSafetyInspectionData":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVA\/vehicleSafetyInspectionData","navigatorTitle":[{"text":"vehicleSafetyInspectionData","kind":"identifier"}],"title":"vehicleSafetyInspectionData","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamva\/vehiclesafetyinspectiondata","abstract":[{"text":"VehicleSafetyInspectionData.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vehicleSafetyInspectionData"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVA":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVA"}],"abstract":[{"text":"AAMVA.","type":"text"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentAAMVA","kind":"identifier"}],"type":"topic","title":"SBSDKBarcodeDocumentAAMVA","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVA","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamva"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"vehicleSafetyInspectionData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"vehicleSafetyInspectionData"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"typeIdentifier","text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData"},{"kind":"text","text":" * "},{"text":"vehicleSafetyInspectionData","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/title","value":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/navigatorTitle","value":[{"text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVA~1vehicleSafetyInspectionData\/title","op":"replace","value":"vehicleSafetyInspectionData"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVA~1vehicleSafetyInspectionData\/fragments","value":[{"kind":"identifier","text":"vehicleSafetyInspectionData"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVA\/title","value":"SBSDKBarcodeDocumentAAMVA","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVA"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVA\/fragments"},{"value":[{"text":"SBSDKBarcodeDocumentAAMVA","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVA\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}