{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStructuredAppendInfo"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStructuredAppendInfo\/isEqual:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkstructuredappendinfo\/isequal:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKStructuredAppendInfo(im)isEqual:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"role":"symbol","title":"isEqual:"},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStructuredAppendInfo/isEqual:":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStructuredAppendInfo\/isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","title":"isEqual:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstructuredappendinfo\/isequal:","role":"symbol","type":"topic","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStructuredAppendInfo":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstructuredappendinfo","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStructuredAppendInfo","title":"SBSDKStructuredAppendInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"The structured append mode can be used to split a message across multiple barcodes."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStructuredAppendInfo\/title","value":"SBSDKStructuredAppendInfo"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKStructuredAppendInfo"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStructuredAppendInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStructuredAppendInfo\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKStructuredAppendInfo"}]}]}]}