{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvadliddriverlicenseendorsementscodefieldname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvadliddriverlicenseendorsementscodefieldname"]}],"abstract":[{"type":"text","text":"Name of the “DriverLicenseEndorsementsCode” field type in document type “AAMVA.DLID”."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/aamvaDLIDDriverLicenseEndorsementsCodeFieldName","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelConstants(cpy)aamvaDLIDDriverLicenseEndorsementsCodeFieldName","roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"aamvaDLIDDriverLicenseEndorsementsCodeFieldName"}],"title":"aamvaDLIDDriverLicenseEndorsementsCodeFieldName","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaDLIDDriverLicenseEndorsementsCodeFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvaDLIDDriverLicenseEndorsementsCodeFieldName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants/aamvaDLIDDriverLicenseEndorsementsCodeFieldName":{"abstract":[{"text":"Name of the “DriverLicenseEndorsementsCode” field type in document type “AAMVA.DLID”.","type":"text"}],"title":"aamvaDLIDDriverLicenseEndorsementsCodeFieldName","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaDLIDDriverLicenseEndorsementsCodeFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/aamvaDLIDDriverLicenseEndorsementsCodeFieldName","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvadliddriverlicenseendorsementscodefieldname","type":"topic","role":"symbol","navigatorTitle":[{"text":"aamvaDLIDDriverLicenseEndorsementsCodeFieldName","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants","type":"topic","title":"SBSDKBarcodeDocumentModelConstants","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants","kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"aamvaDLIDDriverLicenseEndorsementsCodeFieldName","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"aamvaDLIDDriverLicenseEndorsementsCodeFieldName","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"aamvaDLIDDriverLicenseEndorsementsCodeFieldName","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1aamvaDLIDDriverLicenseEndorsementsCodeFieldName\/title","value":"aamvaDLIDDriverLicenseEndorsementsCodeFieldName","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1aamvaDLIDDriverLicenseEndorsementsCodeFieldName\/fragments","value":[{"kind":"identifier","text":"aamvaDLIDDriverLicenseEndorsementsCodeFieldName"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/title","value":"SBSDKBarcodeDocumentModelConstants","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/navigatorTitle","value":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"op":"replace"}]}]}