{"sections":[],"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2SingleScanningMode(im)initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:","title":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithConfirmationSheetEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"confirmationSheetEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodeImageVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"barcodeImageVisible"},{"kind":"text","text":" "},{"kind":"identifier","text":"sheetColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sheetColor"},{"kind":"text","text":" "},{"text":"dividerColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"dividerColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"modalOverlayColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"modalOverlayColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodeTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"text":"barcodeTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodeSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"text":"barcodeSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"submitButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"submitButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"cancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodeInfoMapping:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeInfoMapping","text":"SBSDKUI2BarcodeInfoMapping","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeInfoMapping"},{"text":" *) ","kind":"text"},{"text":"barcodeInfoMapping","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"arOverlay:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayGeneralConfiguration","text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration"},{"text":" *) ","kind":"text"},{"text":"arOverlay","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/initwithconfirmationsheetenabled:barcodeimagevisible:sheetcolor:dividercolor:modaloverlaycolor:barcodetitle:barcodesubtitle:submitbutton:cancelbutton:barcodeinfomapping:aroverlay:"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2StyledText":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2styledtext","type":"topic","navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","title":"SBSDKUI2StyledText"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ButtonConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"title":"SBSDKUI2ButtonConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration of the button.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2buttonconfiguration","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ButtonConfiguration","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Color":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2color","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"title":"SBSDKUI2Color","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeInfoMapping":{"role":"symbol","title":"SBSDKUI2BarcodeInfoMapping","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeinfomapping","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}],"abstract":[{"type":"text","text":"Configuration of the barcode data mapping."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeInfoMapping"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.0","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode/initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:"}],"title":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/initwithconfirmationsheetenabled:barcodeimagevisible:sheetcolor:dividercolor:modaloverlaycolor:barcodetitle:barcodesubtitle:submitbutton:cancelbutton:barcodeinfomapping:aroverlay:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayGeneralConfiguration":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaygeneralconfiguration","abstract":[{"type":"text","text":"Configuration of the AR overlay displayed on top of barcodes in the camera preview."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayGeneralConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"type":"topic","title":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode","navigatorTitle":[{"text":"SBSDKUI2SingleScanningMode","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2SingleScanningMode","kind":"identifier"}],"title":"SBSDKUI2SingleScanningMode","abstract":[{"text":"Configuration of the single barcode scanning mode.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2StyledText","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2ButtonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ButtonConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ButtonConfiguration\/fragments","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2Color","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/title"},{"op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2BarcodeInfoMapping","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeInfoMapping\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeInfoMapping\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeInfoMapping","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeInfoMapping\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2ArOverlayGeneralConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2SingleScanningMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode\/title"},{"op":"replace","value":[{"text":"SBSDKUI2SingleScanningMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2SingleScanningMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}