{"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2AustraliaPostCustomerFormat@SBSDKUI2AustraliaPostCustomerFormatAlphaNumeric","roleHeading":"Case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AustraliaPostCustomerFormatAlphaNumeric"}],"title":"SBSDKUI2AustraliaPostCustomerFormat.alphaNumeric","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"alphaNumeric","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2australiapostcustomerformat\/alphanumeric"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2australiapostcustomerformat\/alphanumeric"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AustraliaPostCustomerFormat\/alphaNumeric"},"abstract":[{"type":"text","text":"The alphanumeric format."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alphaNumeric","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AustraliaPostCustomerFormat"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2AustraliaPostCustomerFormat":{"title":"SBSDKUI2AustraliaPostCustomerFormat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AustraliaPostCustomerFormat","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AustraliaPostCustomerFormat"}],"abstract":[{"text":"The customer format used in AUSTRALIA_POST codes. Only relevant for format codes 59 and 62.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2australiapostcustomerformat","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AustraliaPostCustomerFormat"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 5.2.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2AustraliaPostCustomerFormat/alphaNumeric":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2australiapostcustomerformat\/alphanumeric","kind":"symbol","title":"SBSDKUI2AustraliaPostCustomerFormat.alphaNumeric","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alphaNumeric"}],"navigatorTitle":[{"text":"SBSDKUI2AustraliaPostCustomerFormatAlphaNumeric","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AustraliaPostCustomerFormat\/alphaNumeric","abstract":[{"text":"The alphanumeric format.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKUI2AustraliaPostCustomerFormatAlphaNumeric","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"SBSDKUI2AustraliaPostCustomerFormatAlphaNumeric","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKUI2AustraliaPostCustomerFormatAlphaNumeric","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKUI2AustraliaPostCustomerFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AustraliaPostCustomerFormat\/title"},{"value":[{"text":"SBSDKUI2AustraliaPostCustomerFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AustraliaPostCustomerFormat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AustraliaPostCustomerFormat~1alphaNumeric\/title","value":"SBSDKUI2AustraliaPostCustomerFormatAlphaNumeric"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AustraliaPostCustomerFormat~1alphaNumeric\/fragments","value":[{"text":"SBSDKUI2AustraliaPostCustomerFormatAlphaNumeric","kind":"identifier"}],"op":"replace"}]}]}