{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AustraliaPostCustomerFormat\/numeric"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"numeric","kind":"identifier"}]}]}],"metadata":{"role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"SBSDKUI2AustraliaPostCustomerFormatNumeric","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"SBSDKUI2AustraliaPostCustomerFormat.numeric","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2AustraliaPostCustomerFormat@SBSDKUI2AustraliaPostCustomerFormatNumeric","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numeric","kind":"identifier"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2australiapostcustomerformat\/numeric"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2australiapostcustomerformat\/numeric"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The numeric format."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AustraliaPostCustomerFormat"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2AustraliaPostCustomerFormat":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AustraliaPostCustomerFormat","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2australiapostcustomerformat","title":"SBSDKUI2AustraliaPostCustomerFormat","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AustraliaPostCustomerFormat"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AustraliaPostCustomerFormat"}],"abstract":[{"type":"text","text":"The customer format used in AUSTRALIA_POST codes. Only relevant for format codes 59 and 62."}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2AustraliaPostCustomerFormat/numeric":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AustraliaPostCustomerFormat\/numeric","role":"symbol","title":"SBSDKUI2AustraliaPostCustomerFormat.numeric","abstract":[{"text":"The numeric format.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2australiapostcustomerformat\/numeric","navigatorTitle":[{"text":"SBSDKUI2AustraliaPostCustomerFormatNumeric","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numeric","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUI2AustraliaPostCustomerFormatNumeric"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2AustraliaPostCustomerFormatNumeric","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKUI2AustraliaPostCustomerFormatNumeric","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"SBSDKUI2AustraliaPostCustomerFormat","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AustraliaPostCustomerFormat\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AustraliaPostCustomerFormat\/fragments","value":[{"text":"SBSDKUI2AustraliaPostCustomerFormat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AustraliaPostCustomerFormat\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2AustraliaPostCustomerFormat"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AustraliaPostCustomerFormat~1numeric\/title","op":"replace","value":"SBSDKUI2AustraliaPostCustomerFormatNumeric"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AustraliaPostCustomerFormat~1numeric\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AustraliaPostCustomerFormatNumeric"}]}]}]}