{"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"roleHeading":"Type Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter(cm)fromJsonWithJson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"role":"symbol","title":"fromJsonWithJson:","symbolKind":"method"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"SBSDKParametricFilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter\/fromJsonWithJson:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkparametricfilter\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter/fromJsonWithJson:":{"url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter\/fromjsonwithjson:","kind":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter\/fromJsonWithJson:","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter":{"title":"SBSDKParametricFilter","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","role":"symbol","abstract":[{"text":"Base class for all parametric filters.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKParametricFilter"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKParametricFilter"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/title","op":"replace","value":"SBSDKParametricFilter"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/navigatorTitle","value":[{"text":"SBSDKParametricFilter","kind":"identifier"}]}]}]}