{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreentextlocalization\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization\/fromJsonWithJson:","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"typeIdentifier","text":"SBSDKUI2CreditCardScannerScreenTextLocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromJsonWithJson:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"json"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerScreenTextLocalization(cm)fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"symbolKind":"method","title":"fromJsonWithJson:","roleHeading":"Type Method","role":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenTextLocalization":{"kind":"symbol","title":"SBSDKUI2CreditCardScannerScreenTextLocalization","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenTextLocalization"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreentextlocalization","navigatorTitle":[{"text":"SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the all strings for credit card scanner screen."}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenTextLocalization/fromJsonWithJson:":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreentextlocalization\/fromjsonwithjson:","kind":"symbol","title":"fromJsonWithJson:","type":"topic","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization\/fromJsonWithJson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2CreditCardScannerScreenTextLocalization","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization\/fragments","op":"replace","value":[{"text":"SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenTextLocalization"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization\/navigatorTitle","op":"replace"}]}]}