{"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","title":"stopsCameraSessionWhenDisappeared","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopsCameraSessionWhenDisappeared"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerGeneralConfiguration(py)stopsCameraSessionWhenDisappeared","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"stopsCameraSessionWhenDisappeared"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"stopsCameraSessionWhenDisappeared","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/stopscamerasessionwhendisappeared"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/stopscamerasessionwhendisappeared"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":", the camera session will be stopped entirely, when the base scanner view controller disappears and restarts when it reappears."},{"text":" ","type":"text"},{"text":"The base scanner view controller will cause no CPU load after it disappeared.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Setting it to "},{"type":"codeVoice","code":"False"},{"text":" will NOT stop the camera session, but pauses the delivery of video frames from the camera session to the base scanner view controller.","type":"text"},{"text":" ","type":"text"},{"text":"There is some low CPU activity while the base scanner view controller is not on screen, but there is also no delay when the receiver returns to the screen.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/stopsCameraSessionWhenDisappeared"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration":{"title":"SBSDKBaseScannerGeneralConfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration","type":"topic","abstract":[{"type":"text","text":"The general configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"navigatorTitle":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/stopsCameraSessionWhenDisappeared":{"title":"stopsCameraSessionWhenDisappeared","url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/stopscamerasessionwhendisappeared","abstract":[{"text":"If set to ","type":"text"},{"code":"True","type":"codeVoice"},{"text":", the camera session will be stopped entirely, when the base scanner view controller disappears and restarts when it reappears.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The base scanner view controller will cause no CPU load after it disappeared."},{"type":"text","text":" "},{"type":"text","text":"Setting it to "},{"type":"codeVoice","code":"False"},{"type":"text","text":" will NOT stop the camera session, but pauses the delivery of video frames from the camera session to the base scanner view controller."},{"type":"text","text":" "},{"text":"There is some low CPU activity while the base scanner view controller is not on screen, but there is also no delay when the receiver returns to the screen.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"stopsCameraSessionWhenDisappeared","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"stopsCameraSessionWhenDisappeared","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/stopsCameraSessionWhenDisappeared"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"stopsCameraSessionWhenDisappeared","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"stopsCameraSessionWhenDisappeared"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"text":"stopsCameraSessionWhenDisappeared","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKBaseScannerGeneralConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/fragments","value":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1stopsCameraSessionWhenDisappeared\/title","value":"stopsCameraSessionWhenDisappeared","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1stopsCameraSessionWhenDisappeared\/fragments","op":"replace","value":[{"text":"stopsCameraSessionWhenDisappeared","kind":"identifier"}]}]}]}