{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/videocontentmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/videocontentmode"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"videoContentMode"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoContentMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKVideoContentMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoContentMode","kind":"typeIdentifier"}],"symbolKind":"property","title":"videoContentMode","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerGeneralConfiguration(py)videoContentMode"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration"]]},"abstract":[{"type":"text","text":"The content mode of the video preview layer: fit-in or fill-in. Defaults to "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode\/fillIn","isActive":true},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoContentMode"},{"kind":"text","text":": "},{"text":"SBSDKVideoContentMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoContentMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/videoContentMode","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoContentMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode","abstract":[{"type":"text","text":"Enumeration of video preview content mode."}],"title":"SBSDKVideoContentMode","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvideocontentmode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoContentMode"}],"navigatorTitle":[{"text":"SBSDKVideoContentMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoContentMode/fillIn":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode\/fillIn","url":"\/documentation\/scanbotsdk\/sbsdkvideocontentmode\/fillin","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoContentModeFillIn"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillIn","kind":"identifier"}],"abstract":[{"type":"text","text":"The video layers content is filled into the video layer."},{"type":"text","text":" "},{"type":"text","text":"No visible borders. Video may be cropped to the visible screen area."}],"type":"topic","title":"SBSDKVideoContentMode.fillIn"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration":{"abstract":[{"text":"The general configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration","type":"topic","title":"SBSDKBaseScannerGeneralConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/videoContentMode":{"url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/videocontentmode","type":"topic","role":"symbol","navigatorTitle":[{"text":"videoContentMode","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The content mode of the video preview layer: fit-in or fill-in. Defaults to ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode\/fillIn","isActive":true},{"type":"text","text":"."}],"title":"videoContentMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/videoContentMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"videoContentMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKVideoContentMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoContentMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"videoContentMode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"videoContentMode"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKVideoContentMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoContentMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoContentMode"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode\/title","value":"SBSDKVideoContentMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode\/fragments","value":[{"text":"SBSDKVideoContentMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVideoContentMode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode~1fillIn\/title","value":"SBSDKVideoContentModeFillIn"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode~1fillIn\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoContentModeFillIn"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/title","value":"SBSDKBaseScannerGeneralConfiguration"},{"value":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1videoContentMode\/title","value":"videoContentMode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1videoContentMode\/fragments","value":[{"text":"videoContentMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}