{"metadata":{"role":"symbol","title":"videoFrameResolution","navigatorTitle":[{"text":"videoFrameResolution","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoFrameResolution"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoFrameResolution","text":"SBSDKVideoFrameResolution","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerGeneralConfiguration(py)videoFrameResolution"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/videoframeresolution"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/videoframeresolution"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"The video frame resolution of the preview layer.","type":"text"},{"type":"text","text":" "},{"text":"Defaults to ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution\/auto","type":"reference","isActive":true},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Higher resolutions may improve scanning results but slow down the scanning performance.","type":"text"},{"text":" ","type":"text"},{"text":"In some cases a higher resolution may even decrease the scanning quality.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It is therefore recommended to keep this setting at "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution\/auto"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoFrameResolution"},{"text":": ","kind":"text"},{"text":"SBSDKVideoFrameResolution","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoFrameResolution","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/videoFrameResolution","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/videoFrameResolution":{"role":"symbol","title":"videoFrameResolution","navigatorTitle":[{"kind":"identifier","text":"videoFrameResolution"}],"kind":"symbol","abstract":[{"type":"text","text":"The video frame resolution of the preview layer."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution\/auto"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Higher resolutions may improve scanning results but slow down the scanning performance.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"In some cases a higher resolution may even decrease the scanning quality."},{"text":" ","type":"text"},{"type":"text","text":"It is therefore recommended to keep this setting at "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution\/auto","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/videoframeresolution","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/videoFrameResolution","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoFrameResolution","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKVideoFrameResolution","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoFrameResolution"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFrameResolution":{"role":"symbol","title":"SBSDKVideoFrameResolution","abstract":[{"type":"text","text":"An enum describing the resolution of a video or camera stream."}],"url":"\/documentation\/scanbotsdk\/sbsdkvideoframeresolution","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFrameResolution/auto":{"role":"symbol","title":"SBSDKVideoFrameResolution.auto","url":"\/documentation\/scanbotsdk\/sbsdkvideoframeresolution\/auto","abstract":[{"type":"text","text":"Select the video resolution automatically based on device specifics."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution\/auto","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"auto","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionAuto"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration":{"type":"topic","title":"SBSDKBaseScannerGeneralConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration","navigatorTitle":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"role":"symbol","abstract":[{"text":"The general configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"videoFrameResolution","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"videoFrameResolution"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoFrameResolution","text":"SBSDKVideoFrameResolution","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoFrameResolution"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"videoFrameResolution","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1videoFrameResolution\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1videoFrameResolution\/fragments","value":[{"kind":"identifier","text":"videoFrameResolution"}]},{"value":"SBSDKVideoFrameResolution","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution\/fragments","op":"replace","value":[{"text":"SBSDKVideoFrameResolution","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution~1auto\/title","op":"replace","value":"SBSDKVideoFrameResolutionAuto"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution~1auto\/fragments","value":[{"text":"SBSDKVideoFrameResolutionAuto","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/title","value":"SBSDKBaseScannerGeneralConfiguration","op":"replace"},{"op":"replace","value":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}