{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerapermissionscreen\/fromjsonwithjson:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPermissionScreen","text":"SBSDKUI2CameraPermissionScreen","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CameraPermissionScreen"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPermissionScreen"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPermissionScreen\/fromJsonWithJson:","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"roleHeading":"Type Method","role":"symbol","title":"fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CameraPermissionScreen(cm)fromJsonWithJson:","symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraPermissionScreen/fromJsonWithJson:":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerapermissionscreen\/fromjsonwithjson:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPermissionScreen\/fromJsonWithJson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"abstract":[],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"role":"symbol","title":"fromJsonWithJson:","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraPermissionScreen":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerapermissionscreen","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"abstract":[{"text":"Configuration of the camera permission request view.","type":"text"}],"title":"SBSDKUI2CameraPermissionScreen","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPermissionScreen","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2CameraPermissionScreen","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPermissionScreen\/title"},{"value":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPermissionScreen\/fragments"},{"value":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPermissionScreen\/navigatorTitle"}]}]}