{"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"inactive","kind":"identifier"}],"title":"SBSDKApplicationState.inactive","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKApplicationStateInactive"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKApplicationState@SBSDKApplicationStateInactive","symbolKind":"case","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"sections":[],"abstract":[{"type":"text","text":"The app is inactive and in background."}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKApplicationState\/inactive","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkapplicationstate\/inactive"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkapplicationstate\/inactive"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKApplicationState"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"inactive","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKApplicationState/inactive":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inactive"}],"title":"SBSDKApplicationState.inactive","type":"topic","role":"symbol","abstract":[{"text":"The app is inactive and in background.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKApplicationState\/inactive","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkapplicationstate\/inactive","navigatorTitle":[{"text":"SBSDKApplicationStateInactive","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKApplicationState":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKApplicationState","type":"topic","title":"SBSDKApplicationState","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKApplicationState"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkapplicationstate","navigatorTitle":[{"kind":"identifier","text":"SBSDKApplicationState"}],"abstract":[{"text":"An enum describing the current state of the app.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKApplicationStateInactive"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKApplicationStateInactive","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKApplicationStateInactive"}]}]},"op":"replace"},{"op":"replace","value":"SBSDKApplicationStateInactive","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKApplicationState~1inactive\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKApplicationState~1inactive\/fragments","value":[{"text":"SBSDKApplicationStateInactive","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKApplicationState\/title","value":"SBSDKApplicationState","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKApplicationState"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKApplicationState\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKApplicationState\/navigatorTitle","value":[{"text":"SBSDKApplicationState","kind":"identifier"}]}]}]}