{"metadata":{"role":"symbol","title":"initWithQuality:encryptionMode:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"initWithQuality:encryptionMode:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSaveImageOptions(im)initWithQuality:encryptionMode:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithQuality:encryptionMode:"}]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSaveImageOptions\/initWithQuality:encryptionMode:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdksaveimageoptions\/initwithquality:encryptionmode:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithQuality:"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"quality","kind":"internalParam"},{"kind":"text","text":" "},{"text":"encryptionMode:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKEncryptionMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode","kind":"typeIdentifier","text":"SBSDKEncryptionMode"},{"text":") ","kind":"text"},{"text":"encryptionMode","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSaveImageOptions"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSaveImageOptions":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSaveImageOptions","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSaveImageOptions","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdksaveimageoptions","title":"SBSDKSaveImageOptions","role":"symbol","abstract":[{"text":"Options for saving image to a path.","type":"text"}],"navigatorTitle":[{"text":"SBSDKSaveImageOptions","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSaveImageOptions/initWithQuality:encryptionMode:":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSaveImageOptions\/initWithQuality:encryptionMode:","url":"\/documentation\/scanbotsdk\/sbsdksaveimageoptions\/initwithquality:encryptionmode:","navigatorTitle":[{"kind":"identifier","text":"initWithQuality:encryptionMode:"}],"title":"initWithQuality:encryptionMode:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithQuality:encryptionMode:"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEncryptionMode":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKEncryptionMode","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKEncryptionMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkencryptionmode","title":"SBSDKEncryptionMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode","abstract":[{"text":"Encryption\/Decryption mode to be used when an image is loaded\/saved.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKSaveImageOptions","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSaveImageOptions\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSaveImageOptions\/fragments","value":[{"kind":"identifier","text":"SBSDKSaveImageOptions"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSaveImageOptions\/navigatorTitle","value":[{"text":"SBSDKSaveImageOptions","kind":"identifier"}]},{"op":"replace","value":"SBSDKEncryptionMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode\/title"},{"op":"replace","value":[{"text":"SBSDKEncryptionMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKEncryptionMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}