{"kind":"symbol","sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerScreenTextLocalization(py)accessibilityDescriptionIntroScreenDoneButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionIntroScreenDoneButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"roleHeading":"Instance Property","symbolKind":"property","title":"accessibilityDescriptionIntroScreenDoneButton","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"accessibilityDescriptionIntroScreenDoneButton"}],"modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Accessibility description for the ‘done’\/‘start scanning’ button in the introduction screen."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenTextLocalization\/accessibilityDescriptionIntroScreenDoneButton"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreentextlocalization\/accessibilitydescriptionintroscreendonebutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreentextlocalization\/accessibilitydescriptionintroscreendonebutton"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenTextLocalization"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionIntroScreenDoneButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"Default is “Start scanning”","type":"text"}],"type":"paragraph"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerScreenTextLocalization/accessibilityDescriptionIntroScreenDoneButton":{"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreentextlocalization\/accessibilitydescriptionintroscreendonebutton","title":"accessibilityDescriptionIntroScreenDoneButton","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenTextLocalization\/accessibilityDescriptionIntroScreenDoneButton","abstract":[{"type":"text","text":"Accessibility description for the ‘done’\/‘start scanning’ button in the introduction screen."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionIntroScreenDoneButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"accessibilityDescriptionIntroScreenDoneButton","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerScreenTextLocalization":{"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreentextlocalization","abstract":[{"text":"Configuration of the all strings for MRZ scanner screen.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MRZScannerScreenTextLocalization","kind":"identifier"}],"title":"SBSDKUI2MRZScannerScreenTextLocalization","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenTextLocalization","navigatorTitle":[{"text":"SBSDKUI2MRZScannerScreenTextLocalization","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"accessibilityDescriptionIntroScreenDoneButton","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"accessibilityDescriptionIntroScreenDoneButton"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"accessibilityDescriptionIntroScreenDoneButton"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"accessibilityDescriptionIntroScreenDoneButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenTextLocalization~1accessibilityDescriptionIntroScreenDoneButton\/title","op":"replace"},{"value":[{"text":"accessibilityDescriptionIntroScreenDoneButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenTextLocalization~1accessibilityDescriptionIntroScreenDoneButton\/fragments","op":"replace"},{"value":"SBSDKUI2MRZScannerScreenTextLocalization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenTextLocalization\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerScreenTextLocalization"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenTextLocalization\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerScreenTextLocalization"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenTextLocalization\/navigatorTitle"}]}]}