{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenTextLocalization"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenTextLocalization\/hash","interfaceLanguage":"occ"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}],"title":"hash","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerScreenTextLocalization(py)hash","roleHeading":"Instance Property","fragments":[{"text":"hash","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreentextlocalization\/hash"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerScreenTextLocalization":{"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreentextlocalization","abstract":[{"text":"Configuration of the all strings for MRZ scanner screen.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MRZScannerScreenTextLocalization","kind":"identifier"}],"title":"SBSDKUI2MRZScannerScreenTextLocalization","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenTextLocalization","navigatorTitle":[{"text":"SBSDKUI2MRZScannerScreenTextLocalization","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerScreenTextLocalization/hash":{"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreentextlocalization\/hash","abstract":[],"title":"hash","fragments":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenTextLocalization\/hash","type":"topic","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenTextLocalization\/title","op":"replace","value":"SBSDKUI2MRZScannerScreenTextLocalization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenTextLocalization\/fragments","op":"replace","value":[{"text":"SBSDKUI2MRZScannerScreenTextLocalization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenTextLocalization\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2MRZScannerScreenTextLocalization","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}