{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroMeterDevice\/copyWithZone:"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternIntroMeterDevice(im)copyWithZone:","role":"symbol","title":"copyWithZone:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroMeterDevice"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternintrometerdevice\/copywithzone:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternIntroMeterDevice":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TextPatternIntroMeterDevice","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2TextPatternIntroMeterDevice","kind":"identifier"}],"abstract":[{"type":"text","text":"The image for the introduction screen featuring an electricity meter."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternintrometerdevice","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroMeterDevice","title":"SBSDKUI2TextPatternIntroMeterDevice","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternIntroMeterDevice/copyWithZone:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroMeterDevice\/copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternintrometerdevice\/copywithzone:","role":"symbol","abstract":[],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2TextPatternIntroMeterDevice","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternIntroMeterDevice\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2TextPatternIntroMeterDevice"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternIntroMeterDevice\/fragments"},{"value":[{"text":"SBSDKUI2TextPatternIntroMeterDevice","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternIntroMeterDevice\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}