{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"text":"Renders the document synchronously into a PDF at the specified file url. Performs HOCR if needed.","type":"text"}],"metadata":{"roleHeading":"Type Method","title":"renderDocument(_:with:to:)","navigatorTitle":[{"kind":"identifier","text":"renderDocument:withOptions:output:error:"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIPDFRenderer(cm)renderDocument:withOptions:output:error:","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderDocument"},{"text":"(","kind":"text"},{"text":"SBSDKDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRendererOptions","text":"SBSDKPDFRendererOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIPDFRenderer"]]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuipdfrenderer\/renderdocument(_:with:to:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuipdfrenderer\/renderdocument(_:with:to:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(renderDocument:withOptions:output:error:) "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderDocument"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"document"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument","text":"SBSDKDocument"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"options"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRendererOptions","text":"SBSDKPDFRendererOptions"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"outputURL","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The document to be rendered as a PDF document.","type":"text"}]}],"name":"document"},{"content":[{"inlineContent":[{"text":"The options the PDF renderer uses to render the PDF.","type":"text"}],"type":"paragraph"}],"name":"options"},{"name":"outputURL","content":[{"inlineContent":[{"type":"text","text":"The file URL where the PDF document is saved at."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"content":[{"type":"paragraph","inlineContent":[{"text":"HOCR is the process of adding an invisible text layer on top of each PDF page, containing the text extracted by","type":"text"},{"type":"text","text":" "},{"text":"the optical character recognizer. A PDF with HOCR is searchable and the text can be selected and copy-pasted.","type":"text"}]}],"style":"note","name":"Note","type":"aside"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIPDFRenderer\/renderDocument(_:with:to:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIPDFRenderer":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIPDFRenderer"}],"abstract":[{"text":"A class to render a `SBSDKDocument`` into a PDF.","type":"text"}],"title":"SBSDKUIPDFRenderer","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuipdfrenderer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIPDFRenderer"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIPDFRenderer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIPDFRenderer/renderDocument(_:with:to:)":{"navigatorTitle":[{"text":"renderDocument:withOptions:output:error:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderDocument"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","kind":"typeIdentifier","text":"SBSDKDocument"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRendererOptions","kind":"typeIdentifier","text":"SBSDKPDFRendererOptions"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIPDFRenderer\/renderDocument(_:with:to:)","abstract":[{"type":"text","text":"Renders the document synchronously into a PDF at the specified file url. Performs HOCR if needed."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuipdfrenderer\/renderdocument(_:with:to:)","type":"topic","kind":"symbol","title":"renderDocument(_:with:to:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentPage"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","type":"topic","role":"symbol","title":"SBSDKDocumentPage","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"navigatorTitle":[{"text":"SBSDKDocumentPage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocument":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocument","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocument","type":"topic","role":"symbol","title":"SBSDKDocument","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument","abstract":[{"text":"A thread-safe, mutable container for scanned pages of type ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"text":"SBSDKDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions","title":"SBSDKPDFRendererOptions","type":"topic","abstract":[{"type":"text","text":"A class to describe the options being passed to PDF rendering API."}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRendererOptions","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererOptions"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"renderDocument:withOptions:output:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"renderDocument:withOptions:output:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"renderDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"kind":"text","text":" "},{"text":"withOptions:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKPDFRendererOptions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRendererOptions"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"options"},{"kind":"text","text":" "},{"text":"output:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"outputURL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUIPDFRenderer","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIPDFRenderer\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIPDFRenderer\/fragments","value":[{"text":"SBSDKUIPDFRenderer","kind":"identifier"}],"op":"replace"},{"value":"renderDocument:withOptions:output:error:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIPDFRenderer~1renderDocument(_:with:to:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIPDFRenderer~1renderDocument(_:with:to:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"renderDocument:withOptions:output:error:","kind":"identifier"}]},{"value":"SBSDKDocumentPage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title"},{"value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments"},{"value":"SBSDKDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocument"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/title","value":"SBSDKPDFRendererOptions"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/fragments","value":[{"text":"SBSDKPDFRendererOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}