{"metadata":{"title":"SBSDKImageFilterType.gray","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeGray"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","platforms":[],"externalID":"c:@M@ScanbotSDK@E@SBSDKImageFilterType@SBSDKImageFilterTypeGray","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gray"}],"roleHeading":"Case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gray","kind":"identifier"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/gray","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Please consider using the new class-based SBSDKParametricFilters.","type":"text"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType"]]},"abstract":[{"type":"text","text":"Standard grayscale filter. Creates a grayscaled 8-bit image and optimizes contrast and dynamic range."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/gray"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/gray"]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType":{"type":"topic","title":"SBSDKImageFilterType","abstract":[{"text":"The ScanbotSDK image filter types.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"role":"symbol","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFilterType"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/gray":{"deprecated":true,"abstract":[{"text":"Standard grayscale filter. Creates a grayscaled 8-bit image and optimizes contrast and dynamic range.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeGray"}],"title":"SBSDKImageFilterType.gray","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/gray","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gray"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/gray","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKImageFilterTypeGray","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKImageFilterTypeGray"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKImageFilterTypeGray","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKImageFilterType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/title"},{"value":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/fragments"},{"value":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/navigatorTitle"},{"value":"SBSDKImageFilterTypeGray","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1gray\/title"},{"value":[{"kind":"identifier","text":"SBSDKImageFilterTypeGray"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1gray\/fragments"}]}]}