{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"A filter for black and white conversion using OTSU binarization."}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please consider using the new class-based SBSDKParametricFilters."}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/otsuBinarization"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"otsuBinarization","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKImageFilterType@SBSDKImageFilterTypeOtsuBinarization","roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"otsuBinarization"}],"platforms":[],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeOtsuBinarization"}],"title":"SBSDKImageFilterType.otsuBinarization"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/otsubinarization"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/otsubinarization"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType":{"type":"topic","title":"SBSDKImageFilterType","abstract":[{"text":"The ScanbotSDK image filter types.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"role":"symbol","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFilterType"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/otsuBinarization":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKImageFilterTypeOtsuBinarization","kind":"identifier"}],"deprecated":true,"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/otsubinarization","role":"symbol","abstract":[{"type":"text","text":"A filter for black and white conversion using OTSU binarization."}],"title":"SBSDKImageFilterType.otsuBinarization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/otsuBinarization","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"otsuBinarization","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKImageFilterTypeOtsuBinarization","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKImageFilterTypeOtsuBinarization","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKImageFilterTypeOtsuBinarization"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKImageFilterType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/navigatorTitle"},{"value":"SBSDKImageFilterTypeOtsuBinarization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1otsuBinarization\/title"},{"value":[{"text":"SBSDKImageFilterTypeOtsuBinarization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1otsuBinarization\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}