{"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerResult(py)checkboxes","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkboxes"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerCheckboxResult","text":"SBSDKMedicalCertificateRecognizerCheckboxResult","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"role":"symbol","title":"checkboxes","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"checkboxes","kind":"identifier"}]},"abstract":[{"text":"Array of found checkboxes.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResult\/checkboxes","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"checkboxes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerCheckboxResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerCheckboxResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxResult"},{"kind":"text","text":"]?"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresult\/checkboxes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresult\/checkboxes"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResult"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResult/checkboxes":{"navigatorTitle":[{"text":"checkboxes","kind":"identifier"}],"title":"checkboxes","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Array of found checkboxes."}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresult\/checkboxes","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResult\/checkboxes","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkboxes","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKMedicalCertificateRecognizerCheckboxResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerCheckboxResult"},{"text":"]?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResult","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResult"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerResult","kind":"identifier"}],"abstract":[{"text":"This class describes the results of a medical certificate recognition.","type":"text"}],"title":"SBSDKMedicalCertificateRecognizerResult","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresult","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerCheckboxResult":{"abstract":[{"text":"Contains information about recognized medical certificate checkbox.","type":"text"}],"title":"SBSDKMedicalCertificateRecognizerCheckboxResult","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxresult","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxResult","role":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxResult","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKMedicalCertificateRecognizerCheckboxResult","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"checkboxes"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"checkboxes","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKMedicalCertificateRecognizerCheckboxResult *>"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"checkboxes"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"checkboxes","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResult~1checkboxes\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResult~1checkboxes\/fragments","value":[{"kind":"identifier","text":"checkboxes"}]},{"value":"SBSDKMedicalCertificateRecognizerResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResult\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResult\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificateRecognizerResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxResult\/title","value":"SBSDKMedicalCertificateRecognizerCheckboxResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxResult\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxResult\/navigatorTitle","op":"replace","value":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}