{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelconstants\/isrcheckbanknumberfieldname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelconstants\/isrcheckbanknumberfieldname"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"isrCheckBankNumberFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelConstants"]]},"sections":[],"abstract":[{"type":"text","text":"Name of the “BankNumber” field type in document type “ISRCheck”."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Type Property","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentModelConstants(cpy)isrCheckBankNumberFieldName","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isrCheckBankNumberFieldName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"isrCheckBankNumberFieldName"}],"title":"isrCheckBankNumberFieldName","role":"symbol","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelConstants\/isrCheckBankNumberFieldName"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelConstants":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCheckDocumentModelConstants"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelconstants","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckDocumentModelConstants"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelConstants","title":"SBSDKCheckDocumentModelConstants","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelConstants/isrCheckBankNumberFieldName":{"abstract":[{"type":"text","text":"Name of the “BankNumber” field type in document type “ISRCheck”."}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelconstants\/isrcheckbanknumberfieldname","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"isrCheckBankNumberFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"isrCheckBankNumberFieldName"}],"title":"isrCheckBankNumberFieldName","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelConstants\/isrCheckBankNumberFieldName","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"isrCheckBankNumberFieldName","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"isrCheckBankNumberFieldName","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"isrCheckBankNumberFieldName"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":"SBSDKCheckDocumentModelConstants","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelConstants\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelConstants\/fragments","value":[{"text":"SBSDKCheckDocumentModelConstants","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKCheckDocumentModelConstants","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelConstants\/navigatorTitle"},{"value":"isrCheckBankNumberFieldName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelConstants~1isrCheckBankNumberFieldName\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isrCheckBankNumberFieldName"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelConstants~1isrCheckBankNumberFieldName\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}