{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"copy"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"Any"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"copy()","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring(im)copy","required":true,"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"copy","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"Any"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"copy","kind":"identifier"}],"roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring\/copy()","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagestoring\/copy()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagestoring\/copy()"]}],"sections":[],"abstract":[{"text":"Creates a copy of the storage.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageStoring":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring","type":"topic","navigatorTitle":[{"text":"SBSDKImageStoring","kind":"identifier"}],"abstract":[{"type":"text","text":"Protocol for an order-aware (array like) image storage."}],"role":"symbol","title":"SBSDKImageStoring","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageStoring","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagestoring"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageStoring/copy()":{"title":"copy()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring\/copy()","kind":"symbol","abstract":[{"text":"Creates a copy of the storage.","type":"text"}],"type":"topic","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copy","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"keyword","text":"Any"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagestoring\/copy()","navigatorTitle":[{"kind":"identifier","text":"copy"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"copy","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copy"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"copy"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/title","value":"SBSDKImageStoring"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/fragments","value":[{"kind":"identifier","text":"SBSDKImageStoring"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring~1copy()\/title","value":"copy"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring~1copy()\/fragments","value":[{"kind":"text","text":"- "},{"text":"copy","kind":"identifier"}],"op":"replace"}]}]}