{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring\/image(at:)","interfaceLanguage":"swift"},"abstract":[{"text":"Returns the stored UIImage at the specified index.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(imageAtIndex:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":" "},{"text":"index","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"index","content":[{"type":"paragraph","inlineContent":[{"text":"A valid index of the image.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The image at the given index, or "},{"type":"codeVoice","code":"nil"},{"text":" if the image could not be loaded.","type":"text"}]}],"kind":"content"}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring(im)imageAtIndex:","required":true,"navigatorTitle":[{"text":"imageAtIndex:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","title":"image(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":"("},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?"}],"modules":[{"name":"ScanbotSDK"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagestoring\/image(at:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagestoring\/image(at:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageStoring":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageStoring"}],"navigatorTitle":[{"text":"SBSDKImageStoring","kind":"identifier"}],"title":"SBSDKImageStoring","abstract":[{"text":"Protocol for an order-aware (array like) image storage.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagestoring","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageStoring/image(at:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring\/image(at:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"imageAtIndex:"}],"title":"image(at:)","abstract":[{"text":"Returns the stored UIImage at the specified index.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagestoring\/image(at:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"imageAtIndex:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"imageAtIndex:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"text":"imageAtIndex:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"index"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/title","op":"replace","value":"SBSDKImageStoring"},{"op":"replace","value":[{"text":"SBSDKImageStoring","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring~1image(at:)\/title","op":"replace","value":"imageAtIndex:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"imageAtIndex:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring~1image(at:)\/fragments"}]}]}