{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINIntroDefaultImage"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINIntroDefaultImage(im)isEqual:","modules":[{"name":"ScanbotSDK"}],"title":"isEqual:","symbolKind":"method","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"roleHeading":"Instance Method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinintrodefaultimage\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINIntroDefaultImage\/isEqual:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINIntroDefaultImage/isEqual:":{"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2vinintrodefaultimage\/isequal:","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINIntroDefaultImage\/isEqual:","title":"isEqual:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINIntroDefaultImage":{"url":"\/documentation\/scanbotsdk\/sbsdkui2vinintrodefaultimage","navigatorTitle":[{"text":"SBSDKUI2VINIntroDefaultImage","kind":"identifier"}],"kind":"symbol","type":"topic","title":"SBSDKUI2VINIntroDefaultImage","abstract":[{"type":"text","text":"The default image for the introduction screen."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2VINIntroDefaultImage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINIntroDefaultImage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINIntroDefaultImage\/title","value":"SBSDKUI2VINIntroDefaultImage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINIntroDefaultImage\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2VINIntroDefaultImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINIntroDefaultImage\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2VINIntroDefaultImage"}],"op":"replace"}]}]}