{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2topbarmode\/gradient"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2topbarmode\/gradient"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TopBarMode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TopBarMode\/gradient"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"gradient"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TopBarModeGradient"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gradient","kind":"identifier"}],"title":"SBSDKUI2TopBarMode.gradient","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2TopBarMode@SBSDKUI2TopBarModeGradient"},"abstract":[{"text":"Display the top bar with a gradient background color or a gradient with transparency. The buttons will still be","type":"text"},{"type":"text","text":" "},{"type":"text","text":"visible."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","url":"\/documentation\/scanbotdocumentscannersdk","abstract":[{"type":"text","text":"Version: 6.2.0"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2TopBarMode":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TopBarMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TopBarMode","kind":"identifier"}],"abstract":[{"text":"The visual mode used for the top bar.","type":"text"}],"title":"SBSDKUI2TopBarMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TopBarMode"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2topbarmode","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2TopBarMode/gradient":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TopBarModeGradient"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TopBarMode\/gradient","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2topbarmode\/gradient","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gradient","kind":"identifier"}],"title":"SBSDKUI2TopBarMode.gradient","type":"topic","abstract":[{"type":"text","text":"Display the top bar with a gradient background color or a gradient with transparency. The buttons will still be"},{"type":"text","text":" "},{"text":"visible.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKUI2TopBarModeGradient","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2TopBarModeGradient"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKUI2TopBarModeGradient"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TopBarMode\/title","value":"SBSDKUI2TopBarMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TopBarMode\/fragments","value":[{"text":"SBSDKUI2TopBarMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TopBarMode\/navigatorTitle","value":[{"text":"SBSDKUI2TopBarMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TopBarMode~1gradient\/title","op":"replace","value":"SBSDKUI2TopBarModeGradient"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TopBarMode~1gradient\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2TopBarModeGradient"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}