{"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"],"type":"conformsTo"}],"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/auto","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/disabled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/required"]},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/init(rawValue:)"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/RawRepresentable-Implementations"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKEncryptionMode) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEncryptionMode","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkencryptionmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkencryptionmode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode"},"metadata":{"roleHeading":"Enumeration","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKEncryptionMode","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"SBSDKEncryptionMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEncryptionMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKEncryptionMode"}],"role":"symbol","symbolKind":"enum"},"abstract":[{"type":"text","text":"Encryption\/Decryption mode to be used when an image is loaded\/saved."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncryptionMode/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/init(rawValue:)","kind":"symbol","title":"init(rawValue:)","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencryptionmode\/init(rawvalue:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncryptionMode/required":{"kind":"symbol","title":"SBSDKEncryptionMode.required","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"required"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/required","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencryptionmode\/required","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKEncryptionModeRequired"}],"abstract":[{"text":"Encryption\/Decryption is used when loading\/saving an image. A crypting provider must first be set using ","type":"text"},{"type":"codeVoice","code":"ImageRef.setStorageCryptingProvider"},{"text":". If no provider is set, the loading\/saving operation will fail.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncryptionMode/disabled":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/disabled","navigatorTitle":[{"text":"SBSDKEncryptionModeDisabled","kind":"identifier"}],"abstract":[{"text":"Encryption is not used when loading or saving images. Trying to load an encrypted image will fail.","type":"text"}],"title":"SBSDKEncryptionMode.disabled","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencryptionmode\/disabled"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 8.0.4","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncryptionMode/Equatable-Implementations":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencryptionmode\/equatable-implementations","kind":"article","role":"collectionGroup","title":"Equatable Implementations","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/Equatable-Implementations","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncryptionMode":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode","title":"SBSDKEncryptionMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEncryptionMode"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKEncryptionMode"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencryptionmode","abstract":[{"type":"text","text":"Encryption\/Decryption mode to be used when an image is loaded\/saved."}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncryptionMode/auto":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/auto","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"auto","kind":"identifier"}],"title":"SBSDKEncryptionMode.auto","kind":"symbol","abstract":[{"text":"When saving, images are encrypted only if a crypting provider is set using ","type":"text"},{"type":"codeVoice","code":"ImageRef.setStorageCryptingProvider"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"When loading, images will be decrypted if they’re encrypted and a crypting provider is set, and loaded as-is otherwise.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencryptionmode\/auto","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKEncryptionModeAuto","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s12CaseIterableP":{"type":"unresolvable","title":"Swift.CaseIterable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s12CaseIterableP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncryptionMode/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","kind":"article","type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencryptionmode\/rawrepresentable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKEncryptionMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKEncryptionMode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKEncryptionMode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/auto","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/disabled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/required"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEncryptionMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode~1required\/title","value":"SBSDKEncryptionModeRequired"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode~1required\/fragments","value":[{"kind":"identifier","text":"SBSDKEncryptionModeRequired"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode~1disabled\/title","value":"SBSDKEncryptionModeDisabled"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode~1disabled\/fragments","value":[{"kind":"identifier","text":"SBSDKEncryptionModeDisabled"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode\/title","value":"SBSDKEncryptionMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode\/fragments","value":[{"text":"SBSDKEncryptionMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode\/navigatorTitle","value":[{"text":"SBSDKEncryptionMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode~1auto\/title","value":"SBSDKEncryptionModeAuto"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode~1auto\/fragments","value":[{"text":"SBSDKEncryptionModeAuto","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}