{"metadata":{"role":"symbol","title":"alert(_:isPresented:actions:message:)","modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotSDK"}],"externalID":"s:7SwiftUI4ViewPAAE5alert_11isPresented7actions7messageQrAA4TextV_AA7BindingVySbGqd__yXEqd_0_yXEtAaBRd__AaBRd_0_r0_lF::SYNTHESIZED::s:10ScanbotSDK22SBSDKUI2MRZScannerViewV","extendedModule":"SwiftUICore","platforms":[{"name":"iOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.0"},{"deprecated":false,"name":"iPadOS","introducedAt":"15.0","beta":false,"unavailable":false},{"beta":false,"introducedAt":"15.0","deprecated":false,"unavailable":false,"name":"Mac Catalyst"},{"deprecated":false,"name":"macOS","unavailable":false,"introducedAt":"12.0","beta":false},{"introducedAt":"15.0","unavailable":false,"beta":false,"name":"tvOS","deprecated":false},{"name":"watchOS","unavailable":false,"introducedAt":"8.0","deprecated":false,"beta":false}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alert"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"A"},{"kind":"text","text":", "},{"text":"M","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Text","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4TextV"},{"kind":"text","text":", "},{"text":"isPresented","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Binding","preciseIdentifier":"s:7SwiftUI7BindingV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"actions","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"kind":"typeIdentifier","text":"A"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": () -> ","kind":"text"},{"text":"M","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"symbolKind":"method","roleHeading":"Instance Method"},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView\/alert(_:isPresented:actions:message:)-9y4jn","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView\/View-Implementations"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerview\/alert(_:ispresented:actions:message:)-9y4jn"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"alert","kind":"identifier"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"A"},{"text":", ","kind":"text"},{"text":"M","kind":"genericParameter"},{"text":">(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"title","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4TextV","text":"Text","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isPresented","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Binding","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":">, "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"ViewBuilder","preciseIdentifier":"s:7SwiftUI11ViewBuilderV"},{"kind":"text","text":" "},{"text":"actions","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"kind":"typeIdentifier","text":"A"},{"text":", ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"ViewBuilder","kind":"attribute","preciseIdentifier":"s:7SwiftUI11ViewBuilderV"},{"text":" ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"M","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"},{"kind":"text","text":" "},{"text":"where","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"A"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"M","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"},{"kind":"text","text":"\n"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.alert(_:isPresented:actions:message:)"},{"text":".","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MRZScannerViewController","kind":"identifier"}],"abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan MRZ (Machine-readable zones) of various documents.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerviewcontroller","title":"SBSDKUI2MRZScannerViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerViewController","navigatorTitle":[{"text":"SBSDKUI2MRZScannerViewController","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerView/alert(_:isPresented:actions:message:)-9y4jn":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView\/alert(_:isPresented:actions:message:)-9y4jn","abstract":[],"kind":"symbol","title":"alert(_:isPresented:actions:message:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alert","kind":"identifier"},{"text":"<","kind":"text"},{"text":"A","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"M","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Text","preciseIdentifier":"s:7SwiftUI4TextV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isPresented","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":">, "},{"text":"actions","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"kind":"typeIdentifier","text":"A"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"M","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerview\/alert(_:ispresented:actions:message:)-9y4jn","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerView":{"type":"topic","abstract":[{"text":"The SwiftUI wrapper for ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerViewController"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2MRZScannerView"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerview","title":"SBSDKUI2MRZScannerView","navigatorTitle":[{"text":"SBSDKUI2MRZScannerView","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerView/View-Implementations":{"kind":"article","title":"View Implementations","type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerview\/view-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView\/View-Implementations","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerViewController\/title","value":"SBSDKUI2MRZScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerViewController\/navigatorTitle","value":[{"text":"SBSDKUI2MRZScannerViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}