{"metadata":{"symbolKind":"method","title":"autocapitalization(_:)","extendedModule":"SwiftUICore","platforms":[{"message":"use textInputAutocapitalization(_:)","beta":false,"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecatedAt":"100000.0"},{"deprecated":false,"beta":false,"introducedAt":"13.0","name":"iPadOS","unavailable":false,"deprecatedAt":"100000.0","message":"use textInputAutocapitalization(_:)"},{"deprecated":false,"introducedAt":"13.0","beta":false,"name":"Mac Catalyst","message":"use textInputAutocapitalization(_:)","unavailable":false,"deprecatedAt":"100000.0"},{"deprecatedAt":"100000.0","beta":false,"message":"use textInputAutocapitalization(_:)","introducedAt":"13.0","unavailable":false,"deprecated":false,"name":"tvOS"},{"introducedAt":"1.0","deprecatedAt":"100000.0","beta":false,"message":"use textInputAutocapitalization(_:)","name":"visionOS","deprecated":false,"unavailable":false}],"roleHeading":"Instance Method","role":"symbol","modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotSDK"}],"externalID":"s:7SwiftUI4ViewPAAE18autocapitalizationyQrSo28UITextAutocapitalizationTypeVF::SYNTHESIZED::s:10ScanbotSDK22SBSDKUI2MRZScannerViewV","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autocapitalization"},{"text":"(","kind":"text"},{"text":"UITextAutocapitalizationType","preciseIdentifier":"c:@E@UITextAutocapitalizationType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"code":"View.autocapitalization(_:)","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"use textInputAutocapitalization(_:)"}],"type":"paragraph"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"autocapitalization","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UITextAutocapitalizationType","text":"UITextAutocapitalizationType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"},{"text":"\n","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView\/autocapitalization(_:)"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerview\/autocapitalization(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView\/View-Implementations"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerView/View-Implementations":{"kind":"article","title":"View Implementations","type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerview\/view-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView\/View-Implementations","role":"collectionGroup"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerView/autocapitalization(_:)":{"type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"autocapitalization","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITextAutocapitalizationType","kind":"typeIdentifier","preciseIdentifier":"c:@E@UITextAutocapitalizationType"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerview\/autocapitalization(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView\/autocapitalization(_:)","title":"autocapitalization(_:)","kind":"symbol","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MRZScannerViewController","kind":"identifier"}],"abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan MRZ (Machine-readable zones) of various documents.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerviewcontroller","title":"SBSDKUI2MRZScannerViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerViewController","navigatorTitle":[{"text":"SBSDKUI2MRZScannerViewController","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerView":{"type":"topic","abstract":[{"text":"The SwiftUI wrapper for ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerViewController"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2MRZScannerView"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerview","title":"SBSDKUI2MRZScannerView","navigatorTitle":[{"text":"SBSDKUI2MRZScannerView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2MRZScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerViewController\/fragments"},{"value":[{"text":"SBSDKUI2MRZScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}