{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsSubscriber"]]},"abstract":[{"type":"text","text":"Log an event."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsEvent","text":"SBSDKAnalyticsEvent","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAnalyticsEvent"},{"kind":"text","text":")"}]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsSubscriber\/logEvent(event:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKAnalyticsEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAnalyticsEvent"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"logEventWithEvent:","kind":"identifier"}],"title":"logEvent(event:)","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKAnalyticsSubscriber(im)logEventWithEvent:","roleHeading":"Instance Method","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkanalyticssubscriber\/logevent(event:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkanalyticssubscriber\/logevent(event:)"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 8.0.4","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAnalyticsSubscriber/logEvent(event:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsSubscriber\/logEvent(event:)","navigatorTitle":[{"kind":"identifier","text":"logEventWithEvent:"}],"required":true,"type":"topic","title":"logEvent(event:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAnalyticsEvent","text":"SBSDKAnalyticsEvent"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"type":"text","text":"Log an event."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkanalyticssubscriber\/logevent(event:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAnalyticsSubscriber":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsSubscriber","abstract":[{"text":"The subscriber that is being tracked.","type":"text"}],"kind":"symbol","title":"SBSDKAnalyticsSubscriber","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkanalyticssubscriber","role":"symbol","navigatorTitle":[{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAnalyticsEvent":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAnalyticsEvent"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsEvent","abstract":[{"text":"The event that is being tracked.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKAnalyticsEvent"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkanalyticsevent","kind":"symbol","title":"SBSDKAnalyticsEvent","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"logEventWithEvent:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logEventWithEvent:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"logEventWithEvent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAnalyticsEvent","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsEvent","text":"SBSDKAnalyticsEvent"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"event"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"logEventWithEvent:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsSubscriber~1logEvent(event:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logEventWithEvent:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsSubscriber~1logEvent(event:)\/fragments","op":"replace"},{"value":"SBSDKAnalyticsSubscriber","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsSubscriber\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsSubscriber\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsSubscriber\/navigatorTitle","op":"replace"},{"value":"SBSDKAnalyticsEvent","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsEvent\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAnalyticsEvent"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsEvent\/fragments","op":"replace"},{"value":[{"text":"SBSDKAnalyticsEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsEvent\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}