{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/aamvaVehicleDataFuelTypeFieldNormalizedName","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"aamvaVehicleDataFuelTypeFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"aamvaVehicleDataFuelTypeFieldNormalizedName"}],"title":"aamvaVehicleDataFuelTypeFieldNormalizedName","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelConstants(cpy)aamvaVehicleDataFuelTypeFieldNormalizedName","symbolKind":"property","roleHeading":"Type Property"},"abstract":[{"type":"text","text":"Normalized full name of the “FuelType” field type in document type “AAMVA.VehicleData”."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvaVehicleDataFuelTypeFieldNormalizedName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvavehicledatafueltypefieldnormalizedname"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvavehicledatafueltypefieldnormalizedname"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants/aamvaVehicleDataFuelTypeFieldNormalizedName":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/aamvaVehicleDataFuelTypeFieldNormalizedName","type":"topic","role":"symbol","navigatorTitle":[{"text":"aamvaVehicleDataFuelTypeFieldNormalizedName","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvavehicledatafueltypefieldnormalizedname","abstract":[{"text":"Normalized full name of the “FuelType” field type in document type “AAMVA.VehicleData”.","type":"text"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aamvaVehicleDataFuelTypeFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"aamvaVehicleDataFuelTypeFieldNormalizedName"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"title":"SBSDKBarcodeDocumentModelConstants","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"aamvaVehicleDataFuelTypeFieldNormalizedName","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"aamvaVehicleDataFuelTypeFieldNormalizedName","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"aamvaVehicleDataFuelTypeFieldNormalizedName"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1aamvaVehicleDataFuelTypeFieldNormalizedName\/title","value":"aamvaVehicleDataFuelTypeFieldNormalizedName","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1aamvaVehicleDataFuelTypeFieldNormalizedName\/fragments","value":[{"text":"aamvaVehicleDataFuelTypeFieldNormalizedName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/title","op":"replace","value":"SBSDKBarcodeDocumentModelConstants"},{"op":"replace","value":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}