{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"latvia","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","text":"SBSDKHealthInsuranceCardCountryType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType"]]},"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType(cpy)latvia","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"latvia","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardCountryType"}],"navigatorTitle":[{"text":"latvia","kind":"identifier"}],"symbolKind":"property","roleHeading":"Type Property","title":"latvia"},"abstract":[{"type":"text","text":"The country named Latvia."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/latvia"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/latvia"]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/latvia","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerParameters":{"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}],"abstract":[{"type":"text","text":"The health insurance card recognizer configuration."}],"title":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType":{"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardCountryType","kind":"identifier"}],"abstract":[{"text":"The country types to be used with the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters"},{"type":"text","text":"."}],"title":"SBSDKHealthInsuranceCardCountryType","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardCountryType"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/latvia":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/latvia","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/latvia","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"latvia","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The country named Latvia."}],"navigatorTitle":[{"kind":"identifier","text":"latvia"}],"title":"latvia"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"latvia"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"latvia"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","text":"SBSDKHealthInsuranceCardCountryType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"latvia"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/title","value":"SBSDKHealthInsuranceCardRecognizerParameters"},{"value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerParameters"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/fragments"},{"value":[{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType\/title","value":"SBSDKHealthInsuranceCardCountryType"},{"value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardCountryType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardCountryType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType\/navigatorTitle"},{"value":"latvia","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1latvia\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1latvia\/fragments","value":[{"text":"latvia","kind":"identifier"}]}]}]}