{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType(cpy)poland","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"poland"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","text":"SBSDKHealthInsuranceCardCountryType"}],"symbolKind":"property","title":"poland","navigatorTitle":[{"kind":"identifier","text":"poland"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/poland"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/poland"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"poland","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/poland"},"kind":"symbol","abstract":[{"type":"text","text":"The country named Poland."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/poland":{"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/poland","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"poland","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"abstract":[{"type":"text","text":"The country named Poland."}],"title":"poland","navigatorTitle":[{"kind":"identifier","text":"poland"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/poland","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerParameters":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerParameters"}],"abstract":[{"text":"The health insurance card recognizer configuration.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters","kind":"symbol","title":"SBSDKHealthInsuranceCardRecognizerParameters","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType":{"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardCountryType","kind":"identifier"}],"abstract":[{"text":"The country types to be used with the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters","type":"reference","isActive":true},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType","title":"SBSDKHealthInsuranceCardCountryType","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"value":"poland","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"poland","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType","text":"SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"poland","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1poland\/title","op":"replace","value":"poland"},{"value":[{"text":"poland","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1poland\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/title","value":"SBSDKHealthInsuranceCardRecognizerParameters","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/fragments","value":[{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}]},{"value":"SBSDKHealthInsuranceCardCountryType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType\/fragments","op":"replace","value":[{"text":"SBSDKHealthInsuranceCardCountryType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}