{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/sweden","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"sweden","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The country named Sweden."}],"metadata":{"title":"sweden","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType(cpy)sweden","role":"symbol","roleHeading":"Type Property","navigatorTitle":[{"text":"sweden","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"sweden","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/sweden"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/sweden"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType":{"type":"topic","title":"SBSDKHealthInsuranceCardCountryType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardCountryType"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardCountryType","kind":"identifier"}],"abstract":[{"text":"The country types to be used with the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters"},{"type":"text","text":"."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/sweden":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"sweden","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardCountryType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/sweden","navigatorTitle":[{"kind":"identifier","text":"sweden"}],"type":"topic","title":"sweden","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/sweden","abstract":[{"type":"text","text":"The country named Sweden."}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerParameters":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters","title":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters","type":"topic","abstract":[{"text":"The health insurance card recognizer configuration.","type":"text"}],"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"sweden","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"sweden"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType"},{"text":" * ","kind":"text"},{"text":"sweden","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType\/title","value":"SBSDKHealthInsuranceCardCountryType","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardCountryType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType\/fragments"},{"value":"sweden","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1sweden\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1sweden\/fragments","value":[{"kind":"identifier","text":"sweden"}]},{"value":"SBSDKHealthInsuranceCardRecognizerParameters","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/fragments"}]}]}