{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWithConfiguration:ocrConfiguration:encrypter:) "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration","text":"SBSDKPDFConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration"},{"text":", ","kind":"text"},{"text":"ocrConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKOCREngineConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting","text":"SBSDKStorageCrypting","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"inlineContent":[{"text":"The PDF generation configuration.","type":"text"}],"type":"paragraph"}]},{"name":"ocrConfiguration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The HOCR configuration."}]}]},{"name":"encrypter","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The encrypter the PDF data will be encrypted with, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if no encryption should be used."}]}]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Creates a new instance of the PDF generator and configures it according to the specified configuration."}]}]}],"abstract":[{"type":"text","text":"Designated initializer."}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/init(configuration:ocrConfiguration:encrypter:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:ocrConfiguration:encrypter:"}],"title":"init(configuration:ocrConfiguration:encrypter:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFGenerator(im)initWithConfiguration:ocrConfiguration:encrypter:","roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPDFConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ocrConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKOCREngineConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting"},{"text":"?)","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/init(configuration:ocrconfiguration:encrypter:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/init(configuration:ocrconfiguration:encrypter:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator":{"type":"topic","abstract":[{"type":"text","text":"A class to generate an ordered collection of images with or without performing HOCR."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFGenerator"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPDFGenerator","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator","title":"SBSDKPDFGenerator","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration","abstract":[{"text":"The parameters ","type":"text"},{"type":"codeVoice","code":"pageSize"},{"type":"text","text":", "},{"type":"codeVoice","code":"pageFit"},{"type":"text","text":", "},{"type":"codeVoice","code":"dpi"},{"type":"text","text":" and "},{"type":"codeVoice","code":"resamplingMethod"},{"type":"text","text":" interact in a complex way"},{"text":" ","type":"text"},{"text":"when adding bitmap images (JPEG, PNG, or raw) to the PDF.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"There are three cases to consider:"}],"title":"SBSDKPDFConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKPDFConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator/init(configuration:ocrConfiguration:encrypter:)":{"type":"topic","abstract":[{"type":"text","text":"Designated initializer."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/init(configuration:ocrconfiguration:encrypter:)","navigatorTitle":[{"text":"initWithConfiguration:ocrConfiguration:encrypter:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKPDFConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration"},{"kind":"text","text":", "},{"text":"ocrConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration","text":"SBSDKOCREngineConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/init(configuration:ocrConfiguration:encrypter:)","title":"init(configuration:ocrConfiguration:encrypter:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineConfiguration":{"type":"topic","title":"SBSDKOCREngineConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKOCREngineConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKOCREngineConfiguration","kind":"identifier"}],"abstract":[{"text":"A class describing the configuration of the optical character recognizer (OCR) engine.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCrypting":{"title":"SBSDKStorageCrypting","type":"topic","abstract":[{"type":"text","text":"Protocol for implementing encryption and decryption of (streamed) data."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstoragecrypting","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithConfiguration:ocrConfiguration:encrypter:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:ocrConfiguration:encrypter:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfiguration:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration","kind":"typeIdentifier","text":"SBSDKPDFConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration"},{"kind":"text","text":" *) "},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ocrConfiguration:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration","kind":"typeIdentifier","text":"SBSDKOCREngineConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration"},{"text":" *) ","kind":"text"},{"text":"ocrConfiguration","kind":"internalParam"},{"kind":"text","text":" "},{"text":"encrypter:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","text":"id<SBSDKStorageCrypting>"},{"kind":"text","text":") "},{"text":"encrypter","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The PDF generation configuration."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The HOCR configuration."}],"type":"paragraph"}],"name":"ocrConfiguration"},{"content":[{"inlineContent":[{"type":"text","text":"The encrypter the PDF data will be encrypted with, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if no encryption should be used."}],"type":"paragraph"}],"name":"encrypter"}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator\/title","value":"SBSDKPDFGenerator","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator\/fragments","value":[{"text":"SBSDKPDFGenerator","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKPDFGenerator"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator\/navigatorTitle"},{"value":"SBSDKPDFConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/navigatorTitle","value":[{"text":"SBSDKPDFConfiguration","kind":"identifier"}]},{"op":"replace","value":"initWithConfiguration:ocrConfiguration:encrypter:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1init(configuration:ocrConfiguration:encrypter:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:ocrConfiguration:encrypter:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1init(configuration:ocrConfiguration:encrypter:)\/fragments"},{"op":"replace","value":"SBSDKOCREngineConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKOCREngineConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKOCREngineConfiguration","kind":"identifier"}]},{"value":"SBSDKStorageCrypting","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/fragments","value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}