{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isHidden"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"kind":"symbol","sections":[],"abstract":[{"text":"Wether the tracking overlay is hidden or not.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController\/isHidden"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontroller\/ishidden"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontroller\/ishidden"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isHidden","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isHidden","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController(py)isHidden","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","title":"isHidden"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayController/isHidden":{"type":"topic","title":"isHidden","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontroller\/ishidden","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController\/isHidden","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHidden"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[{"text":"Wether the tracking overlay is hidden or not.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"isHidden"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayController":{"role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}],"type":"topic","kind":"symbol","title":"SBSDKBarcodeTrackingOverlayController","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","abstract":[{"text":"A class that represents an overlay used for visualizing scanned barcodes.","type":"text"},{"text":" ","type":"text"},{"text":"It provides a customizable user interface for displaying barcodes and supports interaction with them.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The overlay can be used to highlight and select barcodes based on user input."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"isHidden"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isHidden"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"isHidden","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController~1isHidden\/title","value":"isHidden","op":"replace"},{"value":[{"text":"isHidden","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController~1isHidden\/fragments"},{"value":"SBSDKBarcodeTrackingOverlayController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/fragments","value":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}