{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2sound\/initwithsuccessbeepenabled:soundtype:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sound(im)initWithSuccessBeepEnabled:soundType:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSuccessBeepEnabled:soundType:"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSuccessBeepEnabled:soundType:","kind":"identifier"}],"symbolKind":"method","title":"initWithSuccessBeepEnabled:soundType:","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound\/initWithSuccessBeepEnabled:soundType:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSuccessBeepEnabled:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"successBeepEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"soundType:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2SoundType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SoundType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2SoundType"},{"text":") ","kind":"text"},{"text":"soundType","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sound":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Sound","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Configuration for the sound.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2Sound","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sound","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound","title":"SBSDKUI2Sound"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SoundType":{"title":"SBSDKUI2SoundType","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Determines the successful detection sound."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2soundtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2SoundType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2SoundType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SoundType","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sound/initWithSuccessBeepEnabled:soundType:":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2sound\/initwithsuccessbeepenabled:soundtype:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound\/initWithSuccessBeepEnabled:soundType:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSuccessBeepEnabled:soundType:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"initWithSuccessBeepEnabled:soundType:","kind":"identifier"}],"title":"initWithSuccessBeepEnabled:soundType:","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/title","value":"SBSDKUI2Sound","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Sound"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/navigatorTitle","value":[{"text":"SBSDKUI2Sound","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SoundType\/title","value":"SBSDKUI2SoundType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SoundType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SoundType"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SoundType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2SoundType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}