{"abstract":[{"type":"text","text":"The cropping progress overlay title."},{"type":"text","text":" "},{"text":"Default is “Please wait…”","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraProgressOverlayTitle"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/cameraprogressoverlaytitle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/cameraprogressoverlaytitle"]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/cameraProgressOverlayTitle","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cameraProgressOverlayTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingTextLocalization(py)cameraProgressOverlayTitle","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"cameraProgressOverlayTitle"}],"title":"cameraProgressOverlayTitle","symbolKind":"property"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.1.1","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/cameraProgressOverlayTitle":{"title":"cameraProgressOverlayTitle","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/cameraProgressOverlayTitle","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/cameraprogressoverlaytitle","abstract":[{"type":"text","text":"The cropping progress overlay title."},{"text":" ","type":"text"},{"text":"Default is “Please wait…”","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cameraProgressOverlayTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cameraProgressOverlayTitle"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization","type":"topic","kind":"symbol","role":"symbol","title":"SBSDKUI2CroppingTextLocalization","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization","navigatorTitle":[{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of all the strings for the standalone cropping screen."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"cameraProgressOverlayTitle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"cameraProgressOverlayTitle","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"cameraProgressOverlayTitle"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1cameraProgressOverlayTitle\/title","value":"cameraProgressOverlayTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1cameraProgressOverlayTitle\/fragments","value":[{"text":"cameraProgressOverlayTitle","kind":"identifier"}]},{"value":"SBSDKUI2CroppingTextLocalization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization\/fragments","value":[{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization\/navigatorTitle","value":[{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}]}]}]}