{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/init(cameraprogressoverlaytitle:croppingtopbarcancelbuttontitle:croppingtopbarconfirmbuttontitle:croppingdetectbuttontitle:croppingrotatebuttontitle:croppingresetbuttontitle:croppingscreentitle:accessibilitydescriptioncroppingtopbarconfirmb-23die"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/init(cameraprogressoverlaytitle:croppingtopbarcancelbuttontitle:croppingtopbarconfirmbuttontitle:croppingdetectbuttontitle:croppingrotatebuttontitle:croppingresetbuttontitle:croppingscreentitle:accessibilitydescriptioncroppingtopbarconfirmb-23die"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cameraProgressOverlayTitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" = \"Please wait...\", ","kind":"text"},{"kind":"externalParam","text":"croppingTopBarCancelButtonTitle"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = \"Cancel\", ","kind":"text"},{"text":"croppingTopBarConfirmButtonTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" = \"Done\", "},{"text":"croppingDetectButtonTitle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" = \"Detect\", ","kind":"text"},{"text":"croppingRotateButtonTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = \"Rotate\", ","kind":"text"},{"kind":"externalParam","text":"croppingResetButtonTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" = \"Reset\", ","kind":"text"},{"text":"croppingScreenTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" = \"Crop\", "},{"text":"accessibilityDescriptionCroppingTopBarConfirmButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = \"Tap to apply changes\", ","kind":"text"},{"kind":"externalParam","text":"accessibilityDescriptionCroppingTopBarCancelButton"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = \"Tap to close screen without applying changes\", ","kind":"text"},{"text":"accessibilityDescriptionCroppingDetectButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" = \"Tap to detect document on the image\", ","kind":"text"},{"kind":"externalParam","text":"accessibilityDescriptionCroppingRotateButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" = \"Tap to rotate document\", ","kind":"text"},{"text":"accessibilityDescriptionCroppingResetButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" = \"Tap to reset document contour to whole image\")","kind":"text"}]}]}],"metadata":{"roleHeading":"Initializer","symbolKind":"init","title":"init(cameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"cameraProgressOverlayTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"croppingTopBarCancelButtonTitle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"croppingTopBarConfirmButtonTitle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"croppingDetectButtonTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"croppingRotateButtonTitle"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"croppingResetButtonTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"croppingScreenTitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"accessibilityDescriptionCroppingTopBarConfirmButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessibilityDescriptionCroppingTopBarCancelButton"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"accessibilityDescriptionCroppingDetectButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"accessibilityDescriptionCroppingRotateButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessibilityDescriptionCroppingResetButton"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingTextLocalization(im)initWithCameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:","navigatorTitle":[{"text":"initWithCameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/init(cameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization":{"title":"SBSDKUI2CroppingTextLocalization","abstract":[{"text":"Configuration of all the strings for the standalone cropping screen.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CroppingTextLocalization"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/init(cameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:)":{"kind":"symbol","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/init(cameraprogressoverlaytitle:croppingtopbarcancelbuttontitle:croppingtopbarconfirmbuttontitle:croppingdetectbuttontitle:croppingrotatebuttontitle:croppingresetbuttontitle:croppingscreentitle:accessibilitydescriptioncroppingtopbarconfirmb-23die","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"cameraProgressOverlayTitle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"croppingTopBarCancelButtonTitle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"croppingTopBarConfirmButtonTitle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"croppingDetectButtonTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"croppingRotateButtonTitle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"croppingResetButtonTitle"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"croppingScreenTitle"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"accessibilityDescriptionCroppingTopBarConfirmButton"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"accessibilityDescriptionCroppingTopBarCancelButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"accessibilityDescriptionCroppingDetectButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessibilityDescriptionCroppingRotateButton"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"accessibilityDescriptionCroppingResetButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(cameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/init(cameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:)","navigatorTitle":[{"kind":"identifier","text":"initWithCameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithCameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithCameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithCameraProgressOverlayTitle:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"cameraProgressOverlayTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"croppingTopBarCancelButtonTitle:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"croppingTopBarCancelButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"croppingTopBarConfirmButtonTitle:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"croppingTopBarConfirmButtonTitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingDetectButtonTitle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"croppingDetectButtonTitle","kind":"internalParam"},{"kind":"text","text":" "},{"text":"croppingRotateButtonTitle:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"croppingRotateButtonTitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingResetButtonTitle:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"croppingResetButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"croppingScreenTitle:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"croppingScreenTitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingTopBarConfirmButton:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionCroppingTopBarConfirmButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingTopBarCancelButton:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionCroppingTopBarCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionCroppingDetectButton:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCroppingDetectButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionCroppingRotateButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCroppingRotateButton"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCroppingResetButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCroppingResetButton","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization\/title","value":"SBSDKUI2CroppingTextLocalization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CroppingTextLocalization"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization\/navigatorTitle","value":[{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1init(cameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:)\/title","value":"initWithCameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1init(cameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:","kind":"identifier"}]}]}]}