{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUIHealthInsuranceCardScannerTextConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardScannerTextConfiguration"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardScannerConfiguration(py)textConfiguration","role":"symbol","title":"textConfiguration","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"textConfiguration","kind":"identifier"}],"symbolKind":"property"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerConfiguration\/textConfiguration"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannerconfiguration\/textconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannerconfiguration\/textconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerConfiguration"]]},"abstract":[{"text":"The configuration for displayed texts.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textConfiguration"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardScannerTextConfiguration","kind":"typeIdentifier","text":"SBSDKUIHealthInsuranceCardScannerTextConfiguration"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerConfiguration/textConfiguration":{"type":"topic","title":"textConfiguration","role":"symbol","navigatorTitle":[{"text":"textConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerConfiguration\/textConfiguration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardScannerTextConfiguration","text":"SBSDKUIHealthInsuranceCardScannerTextConfiguration","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The configuration for displayed texts."}],"url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannerconfiguration\/textconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerConfiguration/defaultConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardScannerConfiguration","text":"SBSDKUIHealthInsuranceCardScannerConfiguration"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannerconfiguration\/defaultconfiguration","abstract":[{"type":"text","text":"The default configuration."}],"title":"defaultConfiguration","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerConfiguration\/defaultConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerConfiguration"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerConfiguration","abstract":[{"text":"This class describes the look and feel, as well as the textual contents of the detection RTU-UI screen for Health Insurance Card scanner.","type":"text"},{"text":" ","type":"text"},{"text":"Use the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerConfiguration\/defaultConfiguration","isActive":true,"type":"reference"},{"text":" class property to retrieve an instance and modify it.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerConfiguration"}],"title":"SBSDKUIHealthInsuranceCardScannerConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannerconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerTextConfiguration":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIHealthInsuranceCardScannerTextConfiguration","kind":"identifier"}],"type":"topic","title":"SBSDKUIHealthInsuranceCardScannerTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerTextConfiguration","navigatorTitle":[{"text":"SBSDKUIHealthInsuranceCardScannerTextConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannertextconfiguration","abstract":[{"text":"Configuration for the textual contents of the detector RTU-UI screen for Health Insurance Card scanner.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"textConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"textConfiguration"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardScannerTextConfiguration","kind":"typeIdentifier","text":"SBSDKUIHealthInsuranceCardScannerTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerTextConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"textConfiguration"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerConfiguration~1textConfiguration\/title","value":"textConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerConfiguration~1textConfiguration\/fragments","value":[{"kind":"identifier","text":"textConfiguration"}],"op":"replace"},{"value":"defaultConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerConfiguration~1defaultConfiguration\/title"},{"value":[{"kind":"identifier","text":"defaultConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerConfiguration~1defaultConfiguration\/fragments"},{"value":"SBSDKUIHealthInsuranceCardScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerConfiguration\/fragments"},{"value":[{"text":"SBSDKUIHealthInsuranceCardScannerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerConfiguration\/navigatorTitle"},{"value":"SBSDKUIHealthInsuranceCardScannerTextConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerTextConfiguration\/title"},{"value":[{"text":"SBSDKUIHealthInsuranceCardScannerTextConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerTextConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerTextConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerTextConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}