{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView\/startAnimation()"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgradientpolygonview\/startanimation()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgradientpolygonview\/startanimation()"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView"]]},"abstract":[{"text":"Starts the animation if the view is visible.","type":"text"}],"kind":"symbol","metadata":{"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"startAnimation","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGradientPolygonView(im)startAnimation","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startAnimation","kind":"identifier"},{"kind":"text","text":"()"}],"title":"startAnimation()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAnimation"},{"kind":"text","text":"()"}]}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonView/startAnimation()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView\/startAnimation()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"startAnimation","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Starts the animation if the view is visible."}],"title":"startAnimation()","url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonview\/startanimation()","kind":"symbol","type":"topic","navigatorTitle":[{"text":"startAnimation","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonView":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGradientPolygonView","kind":"identifier"}],"title":"SBSDKGradientPolygonView","url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonview","abstract":[{"text":"A view that displays a polygon (bezier path) stroked with a gradient. The gradient can be animated and the drawing style is customizable.","type":"text"}],"navigatorTitle":[{"text":"SBSDKGradientPolygonView","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"startAnimation","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"startAnimation"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"startAnimation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"startAnimation","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView~1startAnimation()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"startAnimation"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView~1startAnimation()\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView\/title","value":"SBSDKGradientPolygonView","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGradientPolygonView"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView\/navigatorTitle","value":[{"text":"SBSDKGradientPolygonView","kind":"identifier"}]}]}]}