{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enabled"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceVisibility"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceVisibility\/enabled","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2UserGuidanceVisibility@SBSDKUI2UserGuidanceVisibilityEnabled","role":"symbol","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKUI2UserGuidanceVisibility.enabled","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enabled"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibilityEnabled"}]},"kind":"symbol","abstract":[{"type":"text","text":"Enabled for both ‘auto snapping’ and ‘manual snapping’ modes."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2userguidancevisibility\/enabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2userguidancevisibility\/enabled"]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceVisibility":{"url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancevisibility","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceVisibility","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2UserGuidanceVisibility","kind":"identifier"}],"abstract":[{"text":"Determines the visibility mode for the document capturing user guidance labels.","type":"text"}],"title":"SBSDKUI2UserGuidanceVisibility","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2UserGuidanceVisibility","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceVisibility/enabled":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Enabled for both ‘auto snapping’ and ‘manual snapping’ modes."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancevisibility\/enabled","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceVisibility\/enabled","title":"SBSDKUI2UserGuidanceVisibility.enabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibilityEnabled"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2UserGuidanceVisibilityEnabled"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2UserGuidanceVisibilityEnabled","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibilityEnabled"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceVisibility\/title","op":"replace","value":"SBSDKUI2UserGuidanceVisibility"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceVisibility\/fragments","value":[{"text":"SBSDKUI2UserGuidanceVisibility","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceVisibility~1enabled\/title","op":"replace","value":"SBSDKUI2UserGuidanceVisibilityEnabled"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceVisibility~1enabled\/fragments","op":"replace","value":[{"text":"SBSDKUI2UserGuidanceVisibilityEnabled","kind":"identifier"}]}]}]}