{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didMoveToWindow"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGradientPolygonView(im)didMoveToWindow","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","title":"didMoveToWindow","navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgradientpolygonview\/didmovetowindow"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView\/didMoveToWindow"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonView/didMoveToWindow":{"fragments":[{"text":"- ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonview\/didmovetowindow","title":"didMoveToWindow","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView\/didMoveToWindow","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGradientPolygonView","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKGradientPolygonView"}],"abstract":[{"type":"text","text":"A view that displays a polygon (bezier path) stroked with a gradient. The gradient can be animated and the drawing style is customizable."}],"url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonview","kind":"symbol","title":"SBSDKGradientPolygonView","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonView","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView\/title","value":"SBSDKGradientPolygonView","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView\/fragments","value":[{"text":"SBSDKGradientPolygonView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonView\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGradientPolygonView"}],"op":"replace"}]}]}