{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemInfoPosition\/above","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Display the barcode info box above the overlay polygon.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemInfoPosition"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"above","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeiteminfoposition\/above"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeiteminfoposition\/above"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodeItemInfoPosition@SBSDKUI2BarcodeItemInfoPositionAbove","title":"SBSDKUI2BarcodeItemInfoPosition.above","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"above","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemInfoPositionAbove"}],"role":"symbol","roleHeading":"Case"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemInfoPosition":{"type":"topic","navigatorTitle":[{"text":"SBSDKUI2BarcodeItemInfoPosition","kind":"identifier"}],"title":"SBSDKUI2BarcodeItemInfoPosition","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeItemInfoPosition","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemInfoPosition","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeiteminfoposition","abstract":[{"text":"Where to display the barcode info box in the camera preview.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemInfoPosition/above":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemInfoPositionAbove"}],"type":"topic","title":"SBSDKUI2BarcodeItemInfoPosition.above","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeiteminfoposition\/above","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"above","kind":"identifier"}],"abstract":[{"text":"Display the barcode info box above the overlay polygon.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemInfoPosition\/above","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"SBSDKUI2BarcodeItemInfoPositionAbove","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemInfoPositionAbove"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemInfoPositionAbove"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemInfoPosition\/title","op":"replace","value":"SBSDKUI2BarcodeItemInfoPosition"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeItemInfoPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemInfoPosition\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemInfoPosition\/navigatorTitle","value":[{"text":"SBSDKUI2BarcodeItemInfoPosition","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2BarcodeItemInfoPositionAbove","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemInfoPosition~1above\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemInfoPosition~1above\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemInfoPositionAbove"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}