{"metadata":{"roleHeading":"Case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGenericDocumentCommonFieldType@SBSDKGenericDocumentCommonFieldTypeCardAccessNumber","title":"SBSDKGenericDocumentCommonFieldType.cardAccessNumber","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeCardAccessNumber"}],"role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"cardAccessNumber","kind":"identifier"}]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Card access number field."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cardAccessNumber","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentcommonfieldtype\/cardaccessnumber"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentcommonfieldtype\/cardaccessnumber"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentCommonFieldType"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentCommonFieldType\/cardAccessNumber","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 6.1.0"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentCommonFieldType/cardAccessNumber":{"title":"SBSDKGenericDocumentCommonFieldType.cardAccessNumber","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentcommonfieldtype\/cardaccessnumber","type":"topic","abstract":[{"type":"text","text":"Card access number field."}],"navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypeCardAccessNumber","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentCommonFieldType\/cardAccessNumber","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cardAccessNumber","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentCommonFieldType":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentcommonfieldtype","navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentCommonFieldType","abstract":[{"text":"Common field types.","type":"text"}],"title":"SBSDKGenericDocumentCommonFieldType","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKGenericDocumentCommonFieldTypeCardAccessNumber"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKGenericDocumentCommonFieldTypeCardAccessNumber","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKGenericDocumentCommonFieldTypeCardAccessNumber","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentCommonFieldType~1cardAccessNumber\/title","value":"SBSDKGenericDocumentCommonFieldTypeCardAccessNumber"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentCommonFieldType~1cardAccessNumber\/fragments","op":"replace","value":[{"text":"SBSDKGenericDocumentCommonFieldTypeCardAccessNumber","kind":"identifier"}]},{"value":"SBSDKGenericDocumentCommonFieldType","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentCommonFieldType\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentCommonFieldType\/fragments","value":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentCommonFieldType\/navigatorTitle"}]}]}