{"abstract":[{"type":"text","text":"Pseudonym field."}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentcommonfieldtype\/pseudonym"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentcommonfieldtype\/pseudonym"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"pseudonym","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentCommonFieldType\/pseudonym","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"pseudonym","kind":"identifier"}],"title":"SBSDKGenericDocumentCommonFieldType.pseudonym","roleHeading":"Case","navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypePseudonym","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGenericDocumentCommonFieldType@SBSDKGenericDocumentCommonFieldTypePseudonym","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentCommonFieldType"]]},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentCommonFieldType":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentcommonfieldtype","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentCommonFieldType","title":"SBSDKGenericDocumentCommonFieldType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"abstract":[{"text":"Common field types.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentCommonFieldType/pseudonym":{"title":"SBSDKGenericDocumentCommonFieldType.pseudonym","abstract":[{"type":"text","text":"Pseudonym field."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentCommonFieldType\/pseudonym","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentcommonfieldtype\/pseudonym","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypePseudonym","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pseudonym"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKGenericDocumentCommonFieldTypePseudonym"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypePseudonym"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKGenericDocumentCommonFieldTypePseudonym","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentCommonFieldType\/title","op":"replace","value":"SBSDKGenericDocumentCommonFieldType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentCommonFieldType\/fragments","value":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentCommonFieldType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentCommonFieldType~1pseudonym\/title","value":"SBSDKGenericDocumentCommonFieldTypePseudonym"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypePseudonym"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentCommonFieldType~1pseudonym\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}