{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraUIConfiguration\/enableCameraButtonColor","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"The color of the ","type":"text"},{"code":"Enable Camera","type":"codeVoice"},{"text":" button. Defaults to white.","type":"text"}],"metadata":{"roleHeading":"Instance Property","title":"enableCameraButtonColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableCameraButtonColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"property","navigatorTitle":[{"text":"enableCameraButtonColor","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIEnableCameraUIConfiguration(py)enableCameraButtonColor","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableCameraButtonColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraUIConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuienablecamerauiconfiguration\/enablecamerabuttoncolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuienablecamerauiconfiguration\/enablecamerabuttoncolor"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIEnableCameraUIConfiguration":{"abstract":[{"text":"Configuration for the user interface of camera based view controllers.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuienablecamerauiconfiguration","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}],"title":"SBSDKUIEnableCameraUIConfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraUIConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.4","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIEnableCameraUIConfiguration/enableCameraButtonColor":{"navigatorTitle":[{"text":"enableCameraButtonColor","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuienablecamerauiconfiguration\/enablecamerabuttoncolor","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableCameraButtonColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"title":"enableCameraButtonColor","abstract":[{"type":"text","text":"The color of the "},{"code":"Enable Camera","type":"codeVoice"},{"type":"text","text":" button. Defaults to white."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIEnableCameraUIConfiguration\/enableCameraButtonColor"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"enableCameraButtonColor","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"enableCameraButtonColor"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"enableCameraButtonColor"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUIEnableCameraUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraUIConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraUIConfiguration\/fragments"},{"value":[{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraUIConfiguration\/navigatorTitle"},{"op":"replace","value":"enableCameraButtonColor","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraUIConfiguration~1enableCameraButtonColor\/title"},{"op":"replace","value":[{"kind":"identifier","text":"enableCameraButtonColor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIEnableCameraUIConfiguration~1enableCameraButtonColor\/fragments"}]}]}