{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topUserGuidance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","text":"SBSDKUI2UserGuidanceConfiguration"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerScreenConfiguration(py)topUserGuidance","symbolKind":"property","title":"topUserGuidance","modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"text":"topUserGuidance","kind":"identifier"}],"roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Configuration of the top user guidance."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreenconfiguration\/topuserguidance"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreenconfiguration\/topuserguidance"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration\/topUserGuidance"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"topUserGuidance","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier","text":"SBSDKUI2UserGuidanceConfiguration"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerScreenConfiguration":{"abstract":[{"text":"Configuration of the screen for detecting MRZ (Machine-readable zones) of various documents.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreenconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration","title":"SBSDKUI2MRZScannerScreenConfiguration","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MRZScannerScreenConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2MRZScannerScreenConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceConfiguration":{"title":"SBSDKUI2UserGuidanceConfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidanceconfiguration","abstract":[{"type":"text","text":"Configuration of the hint guiding users through the scanning process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerScreenConfiguration/topUserGuidance":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreenconfiguration\/topuserguidance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"topUserGuidance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"topUserGuidance"}],"title":"topUserGuidance","abstract":[{"text":"Configuration of the top user guidance.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration\/topUserGuidance","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"topUserGuidance"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"topUserGuidance"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SBSDKUI2UserGuidanceConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration"},{"text":" * ","kind":"text"},{"text":"topUserGuidance","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration\/title","value":"SBSDKUI2MRZScannerScreenConfiguration"},{"value":[{"text":"SBSDKUI2MRZScannerScreenConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerScreenConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/title","value":"SBSDKUI2UserGuidanceConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration~1topUserGuidance\/title","value":"topUserGuidance"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration~1topUserGuidance\/fragments","value":[{"text":"topUserGuidance","kind":"identifier"}]}]}]}