{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Optional.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Informs the delegate that the document scanner has processed a video frame. Called on main thread."}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:didsamplevideoframe:scanningresult:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:didsamplevideoframe:scanningresult:)"]}],"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentScannerViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSampleVideoFrame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"scanningResult","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionResult"},{"text":"?)","kind":"text"}],"symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKDocumentScannerViewControllerDelegate(im)documentScannerViewController:didSampleVideoFrame:scanningResult:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"documentScannerViewController:didSampleVideoFrame:scanningResult:","kind":"identifier"}],"role":"symbol","title":"documentScannerViewController(_:didSampleVideoFrame:scanningResult:)","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentScannerViewController"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentScannerViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController"},{"kind":"text","text":", "},{"text":"didSampleVideoFrame","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"videoFrameImage","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scanningResult"},{"text":" ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionResult","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult"},{"text":"?)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The document scanner controller that called this function."}]}],"name":"controller"},{"name":"videoFrameImage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An UIImage with the contents of the video frame."}]}]},{"name":"result","content":[{"inlineContent":[{"text":"The result of the document scanning done on this video frame.","type":"text"}],"type":"paragraph"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewControllerDelegate\/documentScannerViewController(_:didSampleVideoFrame:scanningResult:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewControllerDelegate"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewControllerDelegate/documentScannerViewController(_:didSampleVideoFrame:scanningResult:)":{"navigatorTitle":[{"kind":"identifier","text":"documentScannerViewController:didSampleVideoFrame:scanningResult:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:didsamplevideoframe:scanningresult:)","title":"documentScannerViewController(_:didSampleVideoFrame:scanningResult:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentScannerViewController","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController","kind":"typeIdentifier","text":"SBSDKDocumentScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSampleVideoFrame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":", ","kind":"text"},{"text":"scanningResult","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionResult"},{"text":"?)","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewControllerDelegate\/documentScannerViewController(_:didSampleVideoFrame:scanningResult:)","abstract":[{"text":"Optional.","type":"text"},{"type":"text","text":" "},{"text":"Informs the delegate that the document scanner has processed a video frame. Called on main thread.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"title":"SBSDKDocumentScannerViewController","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"abstract":[{"text":"A UIViewController subclass to show a camera screen and run a user guiding document scanner.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewControllerDelegate":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewControllerDelegate","navigatorTitle":[{"text":"SBSDKDocumentScannerViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontrollerdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKDocumentScannerViewControllerDelegate","kind":"identifier"}],"type":"topic","title":"SBSDKDocumentScannerViewControllerDelegate","abstract":[{"type":"text","text":"The delegate protocol of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController"},{"text":".","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionResult":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"abstract":[{"type":"text","text":"Result of the document contour detection."}],"title":"SBSDKDocumentDetectionResult","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult","role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"documentScannerViewController:didSampleVideoFrame:scanningResult:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"documentScannerViewController:didSampleVideoFrame:scanningResult:"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"documentScannerViewController:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"controller","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didSampleVideoFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"text":"videoFrameImage","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanningResult:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectionResult","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionResult"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The document scanner controller that called this function."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An UIImage with the contents of the video frame."}]}],"name":"videoFrameImage"},{"name":"result","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the document scanning done on this video frame."}]}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewControllerDelegate~1documentScannerViewController(_:didSampleVideoFrame:scanningResult:)\/title","value":"documentScannerViewController:didSampleVideoFrame:scanningResult:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"documentScannerViewController:didSampleVideoFrame:scanningResult:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewControllerDelegate~1documentScannerViewController(_:didSampleVideoFrame:scanningResult:)\/fragments","op":"replace"},{"value":"SBSDKDocumentScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/title"},{"value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}]},{"value":"SBSDKDocumentScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewControllerDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewControllerDelegate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewControllerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKDocumentScannerViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/title","value":"SBSDKDocumentDetectionResult"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"op":"replace"}]}]}