{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"version"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"screen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"palette"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Palette","text":"SBSDKUI2Palette"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2TopBarConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2TopBarConfiguration","text":"SBSDKUI2TopBarConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"actionBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ActionBarConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ActionBarConfiguration","text":"SBSDKUI2ActionBarConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewFinder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ViewFinderConfiguration","text":"SBSDKUI2ViewFinderConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userGuidance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","text":"SBSDKUI2UserGuidanceConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPermission"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraPermissionScreen","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2CameraPermissionScreen","text":"SBSDKUI2CameraPermissionScreen"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2CameraConfiguration","text":"SBSDKUI2CameraConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recognizerConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeRecognizerConfiguration","text":"SBSDKUI2BarcodeRecognizerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useCase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeUseCase","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeUseCase","text":"SBSDKUI2BarcodeUseCase"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sound","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Sound","text":"SBSDKUI2Sound"},{"kind":"text","text":", "},{"kind":"externalParam","text":"vibration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Vibration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Vibration","text":"SBSDKUI2Vibration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timeouts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Timeouts","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Timeouts","text":"SBSDKUI2Timeouts"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerconfiguration\/init(version:screen:palette:backgroundcolor:topbar:actionbar:viewfinder:userguidance:camerapermission:cameraconfiguration:recognizerconfiguration:usecase:sound:vibration:timeouts:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerconfiguration\/init(version:screen:palette:backgroundcolor:topbar:actionbar:viewfinder:userguidance:camerapermission:cameraconfiguration:recognizerconfiguration:usecase:sound:vibration:timeouts:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerConfiguration\/init(version:screen:palette:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Designated initializer."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"version"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"screen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"palette"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Palette","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Palette"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2TopBarConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2TopBarConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"actionBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ActionBarConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ActionBarConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewFinder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ViewFinderConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userGuidance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPermission"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2CameraPermissionScreen","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2CameraPermissionScreen"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2CameraConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2CameraConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recognizerConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeRecognizerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useCase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeUseCase","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeUseCase"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Sound","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Sound"},{"kind":"text","text":", "},{"kind":"externalParam","text":"vibration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Vibration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Vibration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timeouts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Timeouts","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Timeouts"},{"kind":"text","text":")"}],"title":"init(version:screen:palette:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeScannerConfiguration(im)initWithVersion:screen:palette:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithVersion:screen:palette:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerConfiguration"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Timeouts":{"role":"symbol","title":"SBSDKUI2Timeouts","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Timeouts"}],"abstract":[{"type":"text","text":"Configuration of timeouts."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Timeouts","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Timeouts"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2timeouts"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraPermissionScreen":{"role":"symbol","title":"SBSDKUI2CameraPermissionScreen","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}],"abstract":[{"type":"text","text":"Configuration of the camera permission request view."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraPermissionScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2camerapermissionscreen"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette":{"role":"symbol","title":"SBSDKUI2Palette","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Palette"}],"abstract":[{"type":"text","text":"Value palette describing the colors of the scanner screens."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Palette"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ActionBarConfiguration":{"role":"symbol","title":"SBSDKUI2ActionBarConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ActionBarConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the buttons available in the action bar."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ActionBarConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ActionBarConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2actionbarconfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeUseCase":{"role":"symbol","title":"SBSDKUI2BarcodeUseCase","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeUseCase"}],"abstract":[{"type":"text","text":"Configuration of the barcode scanner screen’s behavior."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeUseCase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeUseCase"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeusecase"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Vibration":{"role":"symbol","title":"SBSDKUI2Vibration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Vibration"}],"abstract":[{"type":"text","text":"Vibration configuration."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Vibration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Vibration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2vibration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Sound":{"role":"symbol","title":"SBSDKUI2Sound","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Sound"}],"abstract":[{"type":"text","text":"Sound configuration."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Sound"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sound"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeScannerConfiguration/init(version:screen:palette:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:)":{"role":"symbol","title":"init(version:screen:palette:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"version"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"screen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"palette"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Palette","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Palette"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2TopBarConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2TopBarConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"actionBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ActionBarConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ActionBarConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewFinder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ViewFinderConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userGuidance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPermission"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2CameraPermissionScreen","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2CameraPermissionScreen"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2CameraConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2CameraConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recognizerConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeRecognizerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useCase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeUseCase","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeUseCase"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Sound","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Sound"},{"kind":"text","text":", "},{"kind":"externalParam","text":"vibration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Vibration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Vibration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timeouts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Timeouts","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Timeouts"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Designated initializer."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerConfiguration\/init(version:screen:palette:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithVersion:screen:palette:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerconfiguration\/init(version:screen:palette:backgroundcolor:topbar:actionbar:viewfinder:userguidance:camerapermission:cameraconfiguration:recognizerconfiguration:usecase:sound:vibration:timeouts:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeScannerConfiguration":{"role":"symbol","title":"SBSDKUI2BarcodeScannerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the barcode scanner screen."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerconfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2UserGuidanceConfiguration":{"role":"symbol","title":"SBSDKUI2UserGuidanceConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the hint guiding users through the scanning process."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2UserGuidanceConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2userguidanceconfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2TopBarConfiguration":{"role":"symbol","title":"SBSDKUI2TopBarConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the top screen bar’s appearance."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2TopBarConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2topbarconfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Color":{"role":"symbol","title":"SBSDKUI2Color","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Color"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2color"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraConfiguration":{"role":"symbol","title":"SBSDKUI2CameraConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the camera settings to be used while scanning."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameraconfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeRecognizerConfiguration":{"role":"symbol","title":"SBSDKUI2BarcodeRecognizerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the scanning behavior."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcoderecognizerconfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ViewFinderConfiguration":{"role":"symbol","title":"SBSDKUI2ViewFinderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ViewFinderConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the scanning interface’s viewfinder, serving as guidance to the user."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ViewFinderConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ViewFinderConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2viewfinderconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithVersion:screen:palette:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVersion:screen:palette:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithVersion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"version"},{"kind":"text","text":" "},{"kind":"identifier","text":"screen:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"screen"},{"kind":"text","text":" "},{"kind":"identifier","text":"palette:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Palette","text":"SBSDKUI2Palette"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"palette"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backgroundColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBar:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2TopBarConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2TopBarConfiguration","text":"SBSDKUI2TopBarConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topBar"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionBar:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ActionBarConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ActionBarConfiguration","text":"SBSDKUI2ActionBarConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"actionBar"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewFinder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ViewFinderConfiguration","text":"SBSDKUI2ViewFinderConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewFinder"},{"kind":"text","text":" "},{"kind":"identifier","text":"userGuidance:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","text":"SBSDKUI2UserGuidanceConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userGuidance"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermission:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraPermissionScreen","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2CameraPermissionScreen","text":"SBSDKUI2CameraPermissionScreen"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraPermission"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2CameraConfiguration","text":"SBSDKUI2CameraConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraConfiguration"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognizerConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeRecognizerConfiguration","text":"SBSDKUI2BarcodeRecognizerConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"recognizerConfiguration"},{"kind":"text","text":" "},{"kind":"identifier","text":"useCase:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeUseCase","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeUseCase","text":"SBSDKUI2BarcodeUseCase"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"useCase"},{"kind":"text","text":" "},{"kind":"identifier","text":"sound:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sound","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Sound","text":"SBSDKUI2Sound"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sound"},{"kind":"text","text":" "},{"kind":"identifier","text":"vibration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Vibration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Vibration","text":"SBSDKUI2Vibration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"vibration"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeouts:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Timeouts","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Timeouts","text":"SBSDKUI2Timeouts"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"timeouts"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Timeouts\/title","value":"SBSDKUI2Timeouts"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Timeouts\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Timeouts"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraPermissionScreen\/title","value":"SBSDKUI2CameraPermissionScreen"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraPermissionScreen\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette\/title","value":"SBSDKUI2Palette"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Palette"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ActionBarConfiguration\/title","value":"SBSDKUI2ActionBarConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ActionBarConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ActionBarConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeUseCase\/title","value":"SBSDKUI2BarcodeUseCase"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeUseCase\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeUseCase"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Vibration\/title","value":"SBSDKUI2Vibration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Vibration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Vibration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sound\/title","value":"SBSDKUI2Sound"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sound\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Sound"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration~1init(version:screen:palette:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:)\/title","value":"initWithVersion:screen:palette:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration~1init(version:screen:palette:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVersion:screen:palette:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration\/title","value":"SBSDKUI2BarcodeScannerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2UserGuidanceConfiguration\/title","value":"SBSDKUI2UserGuidanceConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2UserGuidanceConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2TopBarConfiguration\/title","value":"SBSDKUI2TopBarConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2TopBarConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/title","value":"SBSDKUI2Color"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Color"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraConfiguration\/title","value":"SBSDKUI2CameraConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/title","value":"SBSDKUI2BarcodeRecognizerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ViewFinderConfiguration\/title","value":"SBSDKUI2ViewFinderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ViewFinderConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ViewFinderConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}