{"sections":[],"abstract":[{"type":"text","text":"If "},{"type":"codeVoice","code":"true"},{"text":" and extractedDocumentFormats is not empty, then barcodes that do not decode to one of the accepted","type":"text"},{"type":"text","text":" "},{"text":"document formats will be ignored.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerconfiguration\/onlyacceptdocuments"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerconfiguration\/onlyacceptdocuments"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlyAcceptDocuments"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is false"}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerConfiguration\/onlyAcceptDocuments","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerConfiguration"]]},"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onlyAcceptDocuments","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"onlyAcceptDocuments","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeScannerConfiguration(py)onlyAcceptDocuments","roleHeading":"Instance Property","navigatorTitle":[{"text":"onlyAcceptDocuments","kind":"identifier"}],"role":"symbol","symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeScannerConfiguration/onlyAcceptDocuments":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onlyAcceptDocuments"}],"type":"topic","title":"onlyAcceptDocuments","kind":"symbol","abstract":[{"type":"text","text":"If "},{"type":"codeVoice","code":"true"},{"type":"text","text":" and extractedDocumentFormats is not empty, then barcodes that do not decode to one of the accepted"},{"type":"text","text":" "},{"type":"text","text":"document formats will be ignored."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerconfiguration\/onlyacceptdocuments","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onlyAcceptDocuments"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerConfiguration\/onlyAcceptDocuments"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeScannerConfiguration":{"abstract":[{"type":"text","text":"Configuration of the scanning behavior."}],"title":"SBSDKUI2BarcodeScannerConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeScannerConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerConfiguration","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerConfiguration","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"onlyAcceptDocuments","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"onlyAcceptDocuments","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"onlyAcceptDocuments","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration~1onlyAcceptDocuments\/title","value":"onlyAcceptDocuments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration~1onlyAcceptDocuments\/fragments","op":"replace","value":[{"kind":"identifier","text":"onlyAcceptDocuments"}]},{"op":"replace","value":"SBSDKUI2BarcodeScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration\/title"},{"value":[{"text":"SBSDKUI2BarcodeScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2BarcodeScannerConfiguration","kind":"identifier"}]}]}]}