{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagefileformat\/png"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagefileformat\/png"]}],"metadata":{"symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"SBSDKImageFileFormatPNG","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKImageFileFormat.PNG","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PNG","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat@SBSDKImageFileFormatPNG"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat\/PNG","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PNG"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"The image file is a PNG."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFileFormat/PNG":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat\/PNG","type":"topic","abstract":[{"text":"The image file is a PNG.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKImageFileFormatPNG","kind":"identifier"}],"kind":"symbol","title":"SBSDKImageFileFormat.PNG","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"PNG","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefileformat\/png"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFileFormat":{"role":"symbol","navigatorTitle":[{"text":"SBSDKImageFileFormat","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFileFormat"}],"type":"topic","title":"SBSDKImageFileFormat","url":"\/documentation\/scanbotsdk\/sbsdkimagefileformat","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat","abstract":[{"text":"Enumeration of supported image file types.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKImageFileFormatPNG","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"SBSDKImageFileFormatPNG","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"SBSDKImageFileFormatPNG","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKImageFileFormatPNG","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat~1PNG\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageFileFormatPNG"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat~1PNG\/fragments","op":"replace"},{"value":"SBSDKImageFileFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat\/fragments","op":"replace","value":[{"text":"SBSDKImageFileFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat\/navigatorTitle","value":[{"text":"SBSDKImageFileFormat","kind":"identifier"}]}]}]}