{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidZoom"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"scrollView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIScrollView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/UIScrollViewDelegate-Implementations"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview\/scrollviewdidzoom(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview\/scrollviewdidzoom(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIScrollViewDelegate.scrollViewDidZoom(_:)"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/scrollViewDidZoom(_:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"navigatorTitle":[{"text":"scrollViewDidZoom:","kind":"identifier"}],"role":"symbol","extendedModule":"ScanbotBarcodeScannerSDK","externalID":"c:@CM@ScanbotBarcodeScannerSDK@objc(cs)SBSDKZoomingImageScrollView(im)scrollViewDidZoom:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"scrollViewDidZoom(_:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollViewDidZoom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIScrollView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView"},{"text":")","kind":"text"}],"symbolKind":"method"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKZoomingImageScrollView":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview","title":"SBSDKZoomingImageScrollView","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView","role":"symbol","navigatorTitle":[{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}],"abstract":[{"type":"text","text":"A scrollable and zoomable "},{"code":"UIScrollView","type":"codeVoice"},{"type":"text","text":" subclass that displays images and an overlay view."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKZoomingImageScrollView/UIScrollViewDelegate-Implementations":{"kind":"article","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview\/uiscrollviewdelegate-implementations","role":"collectionGroup","title":"UIScrollViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/UIScrollViewDelegate-Implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKZoomingImageScrollView/scrollViewDidZoom(_:)":{"navigatorTitle":[{"text":"scrollViewDidZoom:","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/scrollViewDidZoom(_:)","role":"symbol","abstract":[],"title":"scrollViewDidZoom(_:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview\/scrollviewdidzoom(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scrollViewDidZoom","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"scrollViewDidZoom:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"scrollViewDidZoom:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"scrollViewDidZoom:"},{"kind":"text","text":"("},{"text":"UIScrollView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SBSDKZoomingImageScrollView","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView\/fragments","value":[{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}]},{"value":[{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView~1scrollViewDidZoom(_:)\/title","op":"replace","value":"scrollViewDidZoom:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView~1scrollViewDidZoom(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"scrollViewDidZoom:","kind":"identifier"}]}]}]}