{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationelement\/europeanhealthinsurancecardconfiguration()"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"europeanHealthInsuranceCardConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardConfiguration","text":"SBSDKEuropeanHealthInsuranceCardConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardConfiguration"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement\/europeanHealthInsuranceCardConfiguration()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"europeanHealthInsuranceCardConfiguration()","externalID":"s:10ScanbotSDK46SBSDKDocumentDataExtractorConfigurationElementC027europeanHealthInsuranceCardF0AA013SBSDKEuropeanijkF0CyFZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"europeanHealthInsuranceCardConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardConfiguration","kind":"typeIdentifier"}],"roleHeading":"Type Method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardConfiguration":{"abstract":[{"text":"European Health Insurance Card (EHIC) configuration element. Add to extractor configuration to scan EHICs.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardConfiguration","kind":"identifier"}],"type":"topic","title":"SBSDKEuropeanHealthInsuranceCardConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardconfiguration","navigatorTitle":[{"text":"SBSDKEuropeanHealthInsuranceCardConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationElement":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement","title":"SBSDKDocumentDataExtractorConfigurationElement","abstract":[{"type":"text","text":"Base class for all generic document configuration elements."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationelement","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationElement/europeanHealthInsuranceCardConfiguration()":{"abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationelement\/europeanhealthinsurancecardconfiguration()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement\/europeanHealthInsuranceCardConfiguration()","type":"topic","title":"europeanHealthInsuranceCardConfiguration()","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"europeanHealthInsuranceCardConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardConfiguration","text":"SBSDKEuropeanHealthInsuranceCardConfiguration","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardConfiguration\/title","value":"SBSDKEuropeanHealthInsuranceCardConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardConfiguration\/fragments","value":[{"text":"SBSDKEuropeanHealthInsuranceCardConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardConfiguration\/navigatorTitle","value":[{"text":"SBSDKEuropeanHealthInsuranceCardConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/title","value":"SBSDKDocumentDataExtractorConfigurationElement","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/navigatorTitle"}]}]}