{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCard\/uid","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"The child document of type “UID”."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCard"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"uid","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCardUID","kind":"typeIdentifier","text":"SBSDKBarcodeDocumentModelVCardUID","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardUID"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcard\/uid"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcard\/uid"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"uid","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCard(py)uid","symbolKind":"property","title":"uid","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"uid"},{"kind":"text","text":": "},{"text":"SBSDKBarcodeDocumentModelVCardUID","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCardUID","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCardUID":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardUID","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelVCardUID","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcarduid","title":"SBSDKBarcodeDocumentModelVCardUID","abstract":[{"type":"text","text":"UID"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentModelVCardUID","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCard":{"abstract":[{"type":"text","text":"VCard"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCard","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelVCard","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelVCard","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcard","title":"SBSDKBarcodeDocumentModelVCard"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCard/uid":{"abstract":[{"text":"The child document of type “UID”.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCard\/uid","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcard\/uid","navigatorTitle":[{"text":"uid","kind":"identifier"}],"kind":"symbol","title":"uid","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"uid"},{"kind":"text","text":": "},{"text":"SBSDKBarcodeDocumentModelVCardUID","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCardUID"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"uid","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"uid"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCardUID","text":"SBSDKBarcodeDocumentModelVCardUID","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardUID"},{"kind":"text","text":" * "},{"kind":"identifier","text":"uid"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKBarcodeDocumentModelVCardUID","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardUID\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardUID\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardUID"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardUID\/navigatorTitle","value":[{"text":"SBSDKBarcodeDocumentModelVCardUID","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCard\/title","value":"SBSDKBarcodeDocumentModelVCard"},{"op":"replace","value":[{"text":"SBSDKBarcodeDocumentModelVCard","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCard\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCard\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCard"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCard~1uid\/title","value":"uid","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCard~1uid\/fragments","value":[{"kind":"identifier","text":"uid"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}