{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"symbolKind":"property","navigatorTitle":[{"text":"paymentReferenceType","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentSwissQR(py)paymentReferenceType","role":"symbol","roleHeading":"Instance Property","title":"paymentReferenceType","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentReferenceType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentSwissQR"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentswissqr\/paymentreferencetype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentswissqr\/paymentreferencetype"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentSwissQR\/paymentReferenceType","interfaceLanguage":"swift"},"abstract":[{"text":"Payment Reference Type.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"paymentReferenceType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"abstract":[{"type":"text","text":"A generic document field."}],"title":"SBSDKGenericDocumentField","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","navigatorTitle":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentSwissQR/paymentReferenceType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentSwissQR\/paymentReferenceType","abstract":[{"type":"text","text":"Payment Reference Type."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentswissqr\/paymentreferencetype","title":"paymentReferenceType","navigatorTitle":[{"text":"paymentReferenceType","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentReferenceType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentSwissQR":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentSwissQR","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentSwissQR","kind":"identifier"}],"title":"SBSDKBarcodeDocumentSwissQR","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentswissqr","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentSwissQR","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"SwissQR."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"paymentReferenceType","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"paymentReferenceType","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField"},{"text":" * ","kind":"text"},{"text":"paymentReferenceType","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title","value":"SBSDKGenericDocumentField","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments","op":"replace","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},{"value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentSwissQR~1paymentReferenceType\/title","value":"paymentReferenceType","op":"replace"},{"op":"replace","value":[{"text":"paymentReferenceType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentSwissQR~1paymentReferenceType\/fragments"},{"value":"SBSDKBarcodeDocumentSwissQR","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentSwissQR\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentSwissQR\/fragments","value":[{"text":"SBSDKBarcodeDocumentSwissQR","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentSwissQR\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentSwissQR"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}