{"kind":"symbol","metadata":{"roleHeading":"Case","title":"SBSDKBarcodeOverlayFormat.codeAndType","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeOverlayFormatCodeAndType","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeOverlayFormat@SBSDKBarcodeOverlayFormatCodeAndType","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"codeAndType"}],"symbolKind":"case"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/codeAndType","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeoverlayformat\/codeandtype"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeoverlayformat\/codeandtype"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"Shows the barcode value with the barcode format.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"codeAndType","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeOverlayFormat/codeAndType":{"abstract":[{"text":"Shows the barcode value with the barcode format.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeoverlayformat\/codeandtype","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"codeAndType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/codeAndType","title":"SBSDKBarcodeOverlayFormat.codeAndType","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeOverlayFormatCodeAndType"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeOverlayFormat":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeOverlayFormat","kind":"identifier"}],"abstract":[{"text":"The barcode overlay text format.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeOverlayFormat","kind":"identifier"}],"title":"SBSDKBarcodeOverlayFormat","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeoverlayformat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"SBSDKBarcodeOverlayFormatCodeAndType","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeOverlayFormatCodeAndType"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKBarcodeOverlayFormatCodeAndType"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeOverlayFormat~1codeAndType\/title","value":"SBSDKBarcodeOverlayFormatCodeAndType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeOverlayFormat~1codeAndType\/fragments","value":[{"text":"SBSDKBarcodeOverlayFormatCodeAndType","kind":"identifier"}]},{"value":"SBSDKBarcodeOverlayFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeOverlayFormat\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeOverlayFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeOverlayFormat"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}