{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/code","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat"]]},"abstract":[{"type":"text","text":"Shows the barcode value."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeoverlayformat\/code"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeoverlayformat\/code"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"code","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeOverlayFormat@SBSDKBarcodeOverlayFormatCode","symbolKind":"case","role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeOverlayFormatCode"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKBarcodeOverlayFormat.code","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"code","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeOverlayFormat":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeoverlayformat","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeOverlayFormat"}],"abstract":[{"text":"The barcode overlay text format.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeOverlayFormat"}],"title":"SBSDKBarcodeOverlayFormat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeOverlayFormat/code":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeoverlayformat\/code","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/code","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"code","kind":"identifier"}],"abstract":[{"text":"Shows the barcode value.","type":"text"}],"navigatorTitle":[{"text":"SBSDKBarcodeOverlayFormatCode","kind":"identifier"}],"title":"SBSDKBarcodeOverlayFormat.code"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodeOverlayFormatCode"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeOverlayFormatCode"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKBarcodeOverlayFormatCode","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"SBSDKBarcodeOverlayFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeOverlayFormat\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeOverlayFormat"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeOverlayFormat\/fragments","op":"replace"},{"value":"SBSDKBarcodeOverlayFormatCode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeOverlayFormat~1code\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeOverlayFormatCode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeOverlayFormat~1code\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}