{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingConfiguration\/init(version:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingConfiguration"]]},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithVersion:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"version","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"screen","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"palette","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Palette","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Palette"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"documentUuid"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"pageUuid","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"localization"},{"kind":"text","text":": "},{"text":"SBSDKUI2CroppingTextLocalization","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingTextLocalization","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"appearance"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingAppearanceConfiguration","text":"SBSDKUI2CroppingAppearanceConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"cropping","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingScreenConfiguration"},{"text":", ","kind":"text"},{"text":"documentAnalysisMode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2DocumentAnalysisMode","text":"SBSDKUI2DocumentAnalysisMode"},{"text":")","kind":"text"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingConfiguration(im)initWithVersion:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:","title":"init(version:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:)","role":"symbol","roleHeading":"Initializer"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingconfiguration\/init(version:screen:palette:documentuuid:pageuuid:localization:appearance:cropping:documentanalysismode:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingconfiguration\/init(version:screen:palette:documentuuid:pageuuid:localization:appearance:cropping:documentanalysismode:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"version"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" = \"1.0\", "},{"text":"screen","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" = \"CroppingConfiguration\", ","kind":"text"},{"kind":"externalParam","text":"palette"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Palette","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Palette","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Palette"},{"kind":"text","text":" = SBSDKUI2Palette(sbColorPrimary: SBSDKUI2Color(colorString: \"#C8193C\",\n                                                                                         isArgb: false),\n                                                           sbColorPrimaryDisabled: SBSDKUI2Color(colorString: \"#F5F5F5\",\n                                                                                                 isArgb: false),\n                                                           sbColorNegative: SBSDKUI2Color(colorString: \"#FF3737\",\n                                                                                          isArgb: false),\n                                                           sbColorPositive: SBSDKUI2Color(colorString: \"#4EFFB4\",\n                                                                                          isArgb: false),\n                                                           sbColorWarning: SBSDKUI2Color(colorString: \"#FFCE5C\",\n                                                                                         isArgb: false),\n                                                           sbColorSecondary: SBSDKUI2Color(colorString: \"#FFEDEE\",\n                                                                                           isArgb: false),\n                                                           sbColorSecondaryDisabled: SBSDKUI2Color(colorString: \"#F5F5F5\",\n                                                                                                   isArgb: false),\n                                                           sbColorOnPrimary: SBSDKUI2Color(colorString: \"#FFFFFF\",\n                                                                                           isArgb: false),\n                                                           sbColorOnSecondary: SBSDKUI2Color(colorString: \"#C8193C\",\n                                                                                             isArgb: false),\n                                                           sbColorSurface: SBSDKUI2Color(colorString: \"#FFFFFF\",\n                                                                                         isArgb: false),\n                                                           sbColorOutline: SBSDKUI2Color(colorString: \"#EFEFEF\",\n                                                                                         isArgb: false),\n                                                           sbColorOnSurfaceVariant: SBSDKUI2Color(colorString: \"#707070\",\n                                                                                                  isArgb: false),\n                                                           sbColorOnSurface: SBSDKUI2Color(colorString: \"#000000\",\n                                                                                           isArgb: false),\n                                                           sbColorSurfaceLow: SBSDKUI2Color(colorString: \"#00000026\",\n                                                                                            isArgb: false),\n                                                           sbColorSurfaceHigh: SBSDKUI2Color(colorString: \"#0000007A\",\n                                                                                             isArgb: false),\n                                                           sbColorModalOverlay: SBSDKUI2Color(colorString: \"#000000A3\",\n                                                                                              isArgb: false)), "},{"kind":"externalParam","text":"documentUuid"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageUuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"localization"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization","kind":"typeIdentifier","text":"SBSDKUI2CroppingTextLocalization","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingTextLocalization"},{"text":" = SBSDKUI2CroppingTextLocalization(), ","kind":"text"},{"text":"appearance","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingAppearanceConfiguration","text":"SBSDKUI2CroppingAppearanceConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingAppearanceConfiguration"},{"kind":"text","text":" = SBSDKUI2CroppingAppearanceConfiguration(), "},{"kind":"externalParam","text":"cropping"},{"kind":"text","text":": "},{"text":"SBSDKUI2CroppingScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingScreenConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingScreenConfiguration","kind":"typeIdentifier"},{"text":" = SBSDKUI2CroppingScreenConfiguration(), ","kind":"text"},{"text":"documentAnalysisMode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2DocumentAnalysisMode","text":"SBSDKUI2DocumentAnalysisMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentAnalysisMode","kind":"typeIdentifier"},{"text":" = SBSDKUI2DocumentAnalysisMode.unfilteredDocument)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentAnalysisMode":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentanalysismode","title":"SBSDKUI2DocumentAnalysisMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentAnalysisMode"}],"abstract":[{"type":"text","text":"Determines if the quality analysis for the acknowledgement mode will run on the filtered or the unfiltered image."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentAnalysisMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentAnalysisMode","type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingConfiguration":{"abstract":[{"text":"Configuration of the standalone cropping screen.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingconfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CroppingConfiguration"}],"title":"SBSDKUI2CroppingConfiguration","navigatorTitle":[{"text":"SBSDKUI2CroppingConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingConfiguration/init(version:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:)":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithVersion:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:"}],"title":"init(version:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingConfiguration\/init(version:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingconfiguration\/init(version:screen:palette:documentuuid:pageuuid:localization:appearance:cropping:documentanalysismode:)","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"version","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"screen"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"palette","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Palette","kind":"typeIdentifier","text":"SBSDKUI2Palette"},{"text":", ","kind":"text"},{"text":"documentUuid","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageUuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"localization","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2CroppingTextLocalization","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingTextLocalization"},{"text":", ","kind":"text"},{"text":"appearance","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2CroppingAppearanceConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingAppearanceConfiguration"},{"text":", ","kind":"text"},{"text":"cropping","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingScreenConfiguration","kind":"typeIdentifier","text":"SBSDKUI2CroppingScreenConfiguration"},{"kind":"text","text":", "},{"text":"documentAnalysisMode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2DocumentAnalysisMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2DocumentAnalysisMode"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingAppearanceConfiguration":{"abstract":[{"type":"text","text":"Configuration of the general appearance for the cropping screen."}],"type":"topic","title":"SBSDKUI2CroppingAppearanceConfiguration","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingappearanceconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingAppearanceConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CroppingAppearanceConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingAppearanceConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization":{"title":"SBSDKUI2CroppingTextLocalization","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization","abstract":[{"type":"text","text":"Configuration of all the strings for the standalone cropping screen."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingScreenConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingscreenconfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingScreenConfiguration","title":"SBSDKUI2CroppingScreenConfiguration","navigatorTitle":[{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the screen for cropping the scanned pages."}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Palette":{"abstract":[{"text":"Value palette describing the colors of the scanner screens.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2palette","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Palette","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2Palette"}],"title":"SBSDKUI2Palette","navigatorTitle":[{"text":"SBSDKUI2Palette","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithVersion:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithVersion:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"initWithVersion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"version"},{"kind":"text","text":" "},{"text":"screen:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"screen","kind":"internalParam"},{"kind":"text","text":" "},{"text":"palette:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUI2Palette","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Palette","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Palette","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"palette"},{"text":" ","kind":"text"},{"text":"documentUuid:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"documentUuid","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pageUuid:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pageUuid"},{"kind":"text","text":" "},{"text":"localization:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2CroppingTextLocalization","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingTextLocalization","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"localization"},{"kind":"text","text":" "},{"text":"appearance:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2CroppingAppearanceConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingAppearanceConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingAppearanceConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"appearance"},{"kind":"text","text":" "},{"kind":"identifier","text":"cropping:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingScreenConfiguration","kind":"typeIdentifier","text":"SBSDKUI2CroppingScreenConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingScreenConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cropping"},{"kind":"text","text":" "},{"text":"documentAnalysisMode:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentAnalysisMode","kind":"typeIdentifier","text":"SBSDKUI2DocumentAnalysisMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2DocumentAnalysisMode"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"documentAnalysisMode"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","value":"SBSDKUI2DocumentAnalysisMode","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentAnalysisMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentAnalysisMode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentAnalysisMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentAnalysisMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentAnalysisMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingConfiguration\/title","op":"replace","value":"SBSDKUI2CroppingConfiguration"},{"op":"replace","value":[{"text":"SBSDKUI2CroppingConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2CroppingConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingConfiguration~1init(version:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:)\/title","value":"initWithVersion:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithVersion:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingConfiguration~1init(version:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingAppearanceConfiguration\/title","value":"SBSDKUI2CroppingAppearanceConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CroppingAppearanceConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingAppearanceConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingAppearanceConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CroppingAppearanceConfiguration"}]},{"value":"SBSDKUI2CroppingTextLocalization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2CroppingTextLocalization"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2CroppingTextLocalization"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingScreenConfiguration\/title","value":"SBSDKUI2CroppingScreenConfiguration","op":"replace"},{"value":[{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingScreenConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingScreenConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2Palette","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Palette\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Palette\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Palette"}]},{"value":[{"text":"SBSDKUI2Palette","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Palette\/navigatorTitle"}]}]}