{"abstract":[{"text":"Initializes mock data for a simulated camera device from ressource names of the application bundle.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSimulatedCameraMockData\/init(label:imageName:capturedImageName:refreshOnEachFrame:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(initWithLabel:imageName:capturedImageName:refreshOnEachFrame:) ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"capturedImageName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"refreshOnEachFrame"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"label","content":[{"inlineContent":[{"text":"The label to describe the mock data.","type":"text"}],"type":"paragraph"}]},{"name":"imageName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The case-sensitive name of the image resource in the application bundle that provides the simulated frames."}]}]},{"name":"capturedImageName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The case-sensitive name of the  image resource in the application bundle that is used when capturing still images. If ‘nil’ the current frame of the "},{"type":"codeVoice","code":"imageName"},{"text":" is returned when capturing a still image.","type":"text"}]}]},{"name":"refreshOnEachFrame","content":[{"type":"paragraph","inlineContent":[{"text":"If set to ","type":"text"},{"code":"True","type":"codeVoice"},{"text":" the image is reloaded\/downloaded after each frame. Otherwise the image is loaded only once and reused per frame.","type":"text"}]}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdksimulatedcameramockdata\/init(label:imagename:capturedimagename:refreshoneachframe:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdksimulatedcameramockdata\/init(label:imagename:capturedimagename:refreshoneachframe:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:"}],"title":"init(label:imageName:capturedImageName:refreshOnEachFrame:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSimulatedCameraMockData(im)initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"imageName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"capturedImageName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"refreshOnEachFrame"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"init","roleHeading":"Initializer"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSimulatedCameraMockData"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSimulatedCameraMockData/init(label:imageName:capturedImageName:refreshOnEachFrame:)":{"abstract":[{"text":"Initializes mock data for a simulated camera device from ressource names of the application bundle.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSimulatedCameraMockData\/init(label:imageName:capturedImageName:refreshOnEachFrame:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"label"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"imageName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"capturedImageName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"refreshOnEachFrame"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdksimulatedcameramockdata\/init(label:imagename:capturedimagename:refreshoneachframe:)","title":"init(label:imageName:capturedImageName:refreshOnEachFrame:)","navigatorTitle":[{"text":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSimulatedCameraMockData":{"navigatorTitle":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A class to describe the mocking data that is fed to a simulated camera device.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"title":"SBSDKSimulatedCameraMockData","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdksimulatedcameramockdata","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSimulatedCameraMockData"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithLabel:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"label"},{"kind":"text","text":" "},{"text":"imageName:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"imageName","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"capturedImageName:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"capturedImageName"},{"text":" ","kind":"text"},{"text":"refreshOnEachFrame:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"refreshOnEachFrame"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"label","content":[{"inlineContent":[{"text":"The label to describe the mock data.","type":"text"}],"type":"paragraph"}]},{"name":"imageName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The case-sensitive name of the image resource in the application bundle that provides the simulated frames."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The case-sensitive name of the  image resource in the application bundle that is used when capturing still images. If ‘nil’ the current frame of the "},{"code":"imageName","type":"codeVoice"},{"text":" is returned when capturing a still image.","type":"text"}],"type":"paragraph"}],"name":"capturedImageName"},{"name":"refreshOnEachFrame","content":[{"inlineContent":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":" the image is reloaded\/downloaded after each frame. Otherwise the image is loaded only once and reused per frame."}],"type":"paragraph"}]}],"kind":"parameters"}},{"value":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSimulatedCameraMockData~1init(label:imageName:capturedImageName:refreshOnEachFrame:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSimulatedCameraMockData~1init(label:imageName:capturedImageName:refreshOnEachFrame:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSimulatedCameraMockData\/title","op":"replace","value":"SBSDKSimulatedCameraMockData"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSimulatedCameraMockData\/fragments","value":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSimulatedCameraMockData\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}