{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionResult"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithStatus:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentRecognitionStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKGenericDocumentRecognitionStatus"},{"text":") ","kind":"text"},{"text":"status","kind":"internalParam"},{"kind":"text","text":" "},{"text":"document:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","kind":"typeIdentifier","text":"SBSDKGenericDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"document"},{"kind":"text","text":" "},{"text":"croppedImage:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"text":"croppedImage","kind":"internalParam"},{"kind":"text","text":";"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionresult\/initwithstatus:document:croppedimage:"]}],"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognitionResult(im)initWithStatus:document:croppedImage:","title":"initWithStatus:document:croppedImage:","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithStatus:document:croppedImage:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStatus:document:croppedImage:"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionResult\/initWithStatus:document:croppedImage:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionResult":{"abstract":[{"type":"text","text":"The recognition result of the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionResult","type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionResult","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionresult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionResult"}],"kind":"symbol","title":"SBSDKGenericDocumentRecognitionResult","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionStatus","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The status of the generic document recognition."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatus"}],"title":"SBSDKGenericDocumentRecognitionStatus","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"abstract":[{"type":"text","text":"Represents a generic document with fields and sub-documents used for document recognition."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","title":"SBSDKGenericDocument","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizer":{"title":"SBSDKGenericDocumentRecognizer","abstract":[{"type":"text","text":"A class to recognize and detect the data fields from specific documents,"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizer"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentRecognizer","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionResult/initWithStatus:document:croppedImage:":{"type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStatus:document:croppedImage:"}],"abstract":[],"title":"initWithStatus:document:croppedImage:","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionresult\/initwithstatus:document:croppedimage:","navigatorTitle":[{"kind":"identifier","text":"initWithStatus:document:croppedImage:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionResult\/initWithStatus:document:croppedImage:","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKGenericDocumentRecognitionResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionResult\/title"},{"value":[{"text":"SBSDKGenericDocumentRecognitionResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionResult\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus\/title","op":"replace","value":"SBSDKGenericDocumentRecognitionStatus"},{"value":[{"text":"SBSDKGenericDocumentRecognitionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","op":"replace","value":"SBSDKGenericDocument"},{"value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments"},{"op":"replace","value":"SBSDKGenericDocumentRecognizer","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizer"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}