{"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2CheckScannerViewController instead."}]}],"metadata":{"roleHeading":"Type Method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUICheckScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"text":"SBSDKUICheckScannerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUICheckScannerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SBSDKUICheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerViewController"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerViewController(cm)createWithConfiguration:delegate:","navigatorTitle":[{"kind":"identifier","text":"createWithConfiguration:delegate:"}],"platforms":[],"title":"create(configuration:delegate:)","symbolKind":"method"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/create(configuration:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/create(configuration:delegate:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/create(configuration:delegate:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(createWithConfiguration:delegate:) "},{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUICheckScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerConfiguration"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUICheckScannerViewControllerDelegate","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewControllerDelegate","text":"SBSDKUICheckScannerViewControllerDelegate"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUICheckScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerViewController"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"inlineContent":[{"text":"The configuration to define look and feel of the new detection view controller.","type":"text"}],"type":"paragraph"}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate of the new detection view controller.","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","isActive":true},{"type":"text","text":"."}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerConfiguration":{"role":"symbol","navigatorTitle":[{"text":"SBSDKUICheckScannerConfiguration","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckScannerConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerConfiguration","title":"SBSDKUICheckScannerConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerconfiguration","type":"topic","abstract":[{"text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI check scanner.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewController/create(configuration:delegate:)":{"navigatorTitle":[{"kind":"identifier","text":"createWithConfiguration:delegate:"}],"deprecated":true,"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/create(configuration:delegate:)","abstract":[{"text":"Creates a new instance of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/create(configuration:delegate:)","title":"create(configuration:delegate:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerConfiguration","text":"SBSDKUICheckScannerConfiguration"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUICheckScannerViewControllerDelegate","text":"SBSDKUICheckScannerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"text":"SBSDKUICheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerViewController","kind":"typeIdentifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewControllerDelegate":{"navigatorTitle":[{"text":"SBSDKUICheckScannerViewControllerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"The delegation protocol for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController"},{"text":".","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontrollerdelegate","title":"SBSDKUICheckScannerViewControllerDelegate","kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICheckScannerViewControllerDelegate"}],"deprecated":true,"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewControllerDelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller","deprecated":true,"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"kind":"symbol","title":"SBSDKUICheckScannerViewController","abstract":[{"text":"A Ready-To-Use viewController to scan checks using the camera.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"createWithConfiguration:delegate:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithConfiguration:delegate:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerViewController","kind":"typeIdentifier","text":"SBSDKUICheckScannerViewController"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createWithConfiguration:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerConfiguration","kind":"typeIdentifier","text":"SBSDKUICheckScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"configuration"},{"text":" ","kind":"text"},{"text":"delegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SBSDKUICheckScannerViewControllerDelegate>","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKUICheckScannerViewControllerDelegate","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"configuration","content":[{"inlineContent":[{"text":"The configuration to define look and feel of the new detection view controller.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The delegate of the new detection view controller."}],"type":"paragraph"}],"name":"delegate"}]}},{"op":"replace","value":{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"A new instance of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","type":"reference"},{"text":".","type":"text"}]}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerConfiguration\/title","value":"SBSDKUICheckScannerConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUICheckScannerConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUICheckScannerConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController~1create(configuration:delegate:)\/title","value":"createWithConfiguration:delegate:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithConfiguration:delegate:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController~1create(configuration:delegate:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewControllerDelegate\/title","op":"replace","value":"SBSDKUICheckScannerViewControllerDelegate"},{"value":[{"kind":"identifier","text":"SBSDKUICheckScannerViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewControllerDelegate\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUICheckScannerViewControllerDelegate","kind":"identifier"}]},{"value":"SBSDKUICheckScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/title"},{"value":[{"text":"SBSDKUICheckScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"op":"replace"}]}]}