{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUIDocumentDataExtractorViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIDocumentDataExtractorViewControllerDelegate"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"title":"delegate","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorViewController(py)delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUIDocumentDataExtractorViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIDocumentDataExtractorViewControllerDelegate"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"kind":"symbol","abstract":[{"text":"The receivers delegate.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller\/delegate"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController\/delegate"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewController":{"role":"symbol","navigatorTitle":[{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}],"title":"SBSDKUIDocumentDataExtractorViewController","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to extract generic documents data."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewController/delegate":{"title":"delegate","type":"topic","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIDocumentDataExtractorViewControllerDelegate","text":"SBSDKUIDocumentDataExtractorViewControllerDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController\/delegate","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller\/delegate","abstract":[{"text":"The receivers delegate.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewControllerDelegate":{"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontrollerdelegate","title":"SBSDKUIDocumentDataExtractorViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewControllerDelegate","kind":"symbol","type":"topic","abstract":[{"text":"The delegate protocol for ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentDataExtractorViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewControllerDelegate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"delegate"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKUIDocumentDataExtractorViewControllerDelegate","text":"id<SBSDKUIDocumentDataExtractorViewControllerDelegate>"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKUIDocumentDataExtractorViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/title"},{"value":[{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/navigatorTitle"},{"value":"delegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController~1delegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"op":"replace","value":"SBSDKUIDocumentDataExtractorViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewControllerDelegate\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewControllerDelegate\/fragments","value":[{"text":"SBSDKUIDocumentDataExtractorViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewControllerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}