{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller\/sbsdkdocumentdataextractorviewcontrollerdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller\/sbsdkdocumentdataextractorviewcontrollerdelegate-implementations"]}],"metadata":{"role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKDocumentDataExtractorViewControllerDelegate Implementations"},"sections":[],"kind":"article","topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController\/documentDataExtractorViewController(_:didExtract:on:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController\/SBSDKDocumentDataExtractorViewControllerDelegate-Implementations"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewController/documentDataExtractorViewController(_:didExtract:on:)":{"abstract":[{"text":"Informs the delegate that a document has been extracted successfully.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"documentDataExtractorViewController:didExtractResult:onImage:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataExtractorViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorViewController","text":"SBSDKDocumentDataExtractorViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didExtract","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractionResult","text":"SBSDKDocumentDataExtractionResult","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController\/documentDataExtractorViewController(_:didExtract:on:)","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller\/documentdataextractorviewcontroller(_:didextract:on:)","title":"documentDataExtractorViewController(_:didExtract:on:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewController":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}],"title":"SBSDKUIDocumentDataExtractorViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to extract generic documents data."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController\/documentDataExtractorViewController(_:didExtract:on:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController~1documentDataExtractorViewController(_:didExtract:on:)\/title","op":"replace","value":"documentDataExtractorViewController:didExtractResult:onImage:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController~1documentDataExtractorViewController(_:didExtract:on:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentDataExtractorViewController:didExtractResult:onImage:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/title","op":"replace","value":"SBSDKUIDocumentDataExtractorViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}