{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController\/willShowEnableCameraView","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller\/willshowenablecameraview"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"willShowEnableCameraView"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorViewController(im)willShowEnableCameraView","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willShowEnableCameraView"}],"navigatorTitle":[{"text":"willShowEnableCameraView","kind":"identifier"}],"symbolKind":"method","title":"willShowEnableCameraView","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewController":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}],"title":"SBSDKUIDocumentDataExtractorViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to extract generic documents data."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewController/willShowEnableCameraView":{"navigatorTitle":[{"kind":"identifier","text":"willShowEnableCameraView"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController\/willShowEnableCameraView","title":"willShowEnableCameraView","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller\/willshowenablecameraview","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willShowEnableCameraView"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/title","op":"replace","value":"SBSDKUIDocumentDataExtractorViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}