{"abstract":[{"text":"When this property is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", the zoom can be toggled between the minimum and maximum zoom factor, defined in the zoomRange property, by just double-tapping anywhere in the base scanner view controllers view.","type":"text"},{"text":" ","type":"text"},{"text":"If set to ","type":"text"},{"code":"false","type":"codeVoice"},{"text":", zooming by double-tapping will be disabled.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"dynamic","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDoubleTapToZoomEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerzoomconfiguration\/isdoubletaptozoomenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerzoomconfiguration\/isdoubletaptozoomenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"isDoubleTapToZoomEnabled","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerZoomConfiguration(py)isDoubleTapToZoomEnabled","symbolKind":"property","title":"isDoubleTapToZoomEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDoubleTapToZoomEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerZoomConfiguration"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerZoomConfiguration\/isDoubleTapToZoomEnabled"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerZoomConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"abstract":[{"text":"The zoom configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"},{"text":" ","type":"text"},{"text":"‘SBSDKBaseScannerViewController’ and subclasses allow the user to zoom the camera.","type":"text"},{"text":" ","type":"text"},{"text":"This class lets you customize the zooming user experience.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerzoomconfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerZoomConfiguration","role":"symbol","kind":"symbol","title":"SBSDKBaseScannerZoomConfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerZoomConfiguration/isDoubleTapToZoomEnabled":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerZoomConfiguration\/isDoubleTapToZoomEnabled","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerzoomconfiguration\/isdoubletaptozoomenabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDoubleTapToZoomEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[{"text":"When this property is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":", the zoom can be toggled between the minimum and maximum zoom factor, defined in the zoomRange property, by just double-tapping anywhere in the base scanner view controllers view."},{"type":"text","text":" "},{"type":"text","text":"If set to "},{"type":"codeVoice","code":"false"},{"type":"text","text":", zooming by double-tapping will be disabled."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"title":"isDoubleTapToZoomEnabled","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isDoubleTapToZoomEnabled"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"isDoubleTapToZoomEnabled","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"isDoubleTapToZoomEnabled","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDoubleTapToZoomEnabled"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerZoomConfiguration\/title","value":"SBSDKBaseScannerZoomConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerZoomConfiguration\/fragments","value":[{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerZoomConfiguration\/navigatorTitle","value":[{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerZoomConfiguration~1isDoubleTapToZoomEnabled\/title","value":"isDoubleTapToZoomEnabled","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerZoomConfiguration~1isDoubleTapToZoomEnabled\/fragments","value":[{"kind":"identifier","text":"isDoubleTapToZoomEnabled"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}