{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvaDocumentFormat"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AAMVADocumentFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2AAMVADocumentFormat","text":"SBSDKUI2AAMVADocumentFormat"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2basedocumentformat\/aamvadocumentformat()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2basedocumentformat\/aamvadocumentformat()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BaseDocumentFormat\/aamvaDocumentFormat()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvaDocumentFormat"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKUI2AAMVADocumentFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2AAMVADocumentFormat"}],"title":"aamvaDocumentFormat()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BaseDocumentFormat(cm)aamvaDocumentFormat","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"aamvaDocumentFormat"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BaseDocumentFormat"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2AAMVADocumentFormat":{"role":"symbol","title":"SBSDKUI2AAMVADocumentFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AAMVADocumentFormat"}],"abstract":[{"type":"text","text":"AAMVA Document Format"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AAMVADocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AAMVADocumentFormat"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aamvadocumentformat"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BaseDocumentFormat/aamvaDocumentFormat()":{"role":"symbol","title":"aamvaDocumentFormat()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvaDocumentFormat"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKUI2AAMVADocumentFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2AAMVADocumentFormat"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BaseDocumentFormat\/aamvaDocumentFormat()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"aamvaDocumentFormat"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2basedocumentformat\/aamvadocumentformat()"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BaseDocumentFormat":{"role":"symbol","title":"SBSDKUI2BaseDocumentFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BaseDocumentFormat"}],"abstract":[{"type":"text","text":"Base Document Format"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BaseDocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BaseDocumentFormat"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2basedocumentformat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"aamvaDocumentFormat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"aamvaDocumentFormat"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AAMVADocumentFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2AAMVADocumentFormat","text":"SBSDKUI2AAMVADocumentFormat"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"aamvaDocumentFormat"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AAMVADocumentFormat\/title","value":"SBSDKUI2AAMVADocumentFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AAMVADocumentFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AAMVADocumentFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BaseDocumentFormat~1aamvaDocumentFormat()\/title","value":"aamvaDocumentFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BaseDocumentFormat~1aamvaDocumentFormat()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"aamvaDocumentFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BaseDocumentFormat\/title","value":"SBSDKUI2BaseDocumentFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BaseDocumentFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BaseDocumentFormat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}