{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckmagneticinkstripscanningstatus\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:10ScanbotSDK40SBSDKCheckMagneticInkStripScanningStatusO8rawValueACSgSi_tcfc","roleHeading":"Initializer","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(rawValue:)","symbolKind":"init","modules":[{"name":"ScanbotSDK"}]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckMagneticInkStripScanningStatus\/init(rawValue:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckMagneticInkStripScanningStatus"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckMagneticInkStripScanningStatus":{"title":"SBSDKCheckMagneticInkStripScanningStatus","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckMagneticInkStripScanningStatus"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Check magnetic ink (MICR) strip scanning status."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCheckMagneticInkStripScanningStatus","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckMagneticInkStripScanningStatus","url":"\/documentation\/scanbotsdk\/sbsdkcheckmagneticinkstripscanningstatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckMagneticInkStripScanningStatus/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckMagneticInkStripScanningStatus\/init(rawValue:)","role":"symbol","type":"topic","abstract":[],"title":"init(rawValue:)","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckmagneticinkstripscanningstatus\/init(rawvalue:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKCheckMagneticInkStripScanningStatus","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckMagneticInkStripScanningStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckMagneticInkStripScanningStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckMagneticInkStripScanningStatus\/fragments"},{"value":[{"text":"SBSDKCheckMagneticInkStripScanningStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckMagneticInkStripScanningStatus\/navigatorTitle"}]}]}