{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"generateKey","kind":"identifier"},{"text":"(","kind":"text"},{"text":"keyLength","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyLength"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"keyLength","content":[{"inlineContent":[{"type":"text","text":"The length of the generated key."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The newly generated encryption key."}]}],"kind":"content"}],"metadata":{"role":"symbol","roleHeading":"Instance Method","title":"generateKey(keyLength:)","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"generateKeyWithLength:WithError:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKRandomKeyGenerator(im)generateKeyWithLength:WithError:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"generateKey","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"keyLength"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRandomKeyGenerator"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkrandomkeygenerator\/generatekey(keylength:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkrandomkeygenerator\/generatekey(keylength:)"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRandomKeyGenerator\/generateKey(keyLength:)"},"kind":"symbol","abstract":[{"type":"text","text":"Generates a new encryption key."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRandomKeyGenerator":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRandomKeyGenerator","title":"SBSDKRandomKeyGenerator","url":"\/documentation\/scanbotsdk\/sbsdkrandomkeygenerator","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A class that generates secure, random keys for storage encryption."},{"text":" ","type":"text"},{"text":"They keys are generated using the ","type":"text"},{"type":"codeVoice","code":"SecRandomCopyBytes"},{"type":"text","text":" function."}],"navigatorTitle":[{"text":"SBSDKRandomKeyGenerator","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKRandomKeyGenerator","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRandomKeyGenerator/generateKey(keyLength:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"generateKey"},{"text":"(","kind":"text"},{"text":"keyLength","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRandomKeyGenerator\/generateKey(keyLength:)","role":"symbol","abstract":[{"type":"text","text":"Generates a new encryption key."}],"title":"generateKey(keyLength:)","navigatorTitle":[{"kind":"identifier","text":"generateKeyWithLength:WithError:"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkrandomkeygenerator\/generatekey(keylength:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyLength":{"navigatorTitle":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeylength","title":"SBSDKStorageCryptingKeyLength","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyLength","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"The length of the encryption key.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"generateKeyWithLength:WithError:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"generateKeyWithLength:WithError:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"generateKeyWithLength:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"keyLength"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WithError:"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"keyLength","content":[{"inlineContent":[{"type":"text","text":"The length of the generated key."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"On output, a pointer to an error object that describes why the method failed, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}],"type":"paragraph"}],"name":"error"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"The newly generated encryption key.","type":"text"},{"type":"text","text":" On failure, this method returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRandomKeyGenerator\/title","value":"SBSDKRandomKeyGenerator"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRandomKeyGenerator\/fragments","op":"replace","value":[{"text":"SBSDKRandomKeyGenerator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRandomKeyGenerator\/navigatorTitle","op":"replace","value":[{"text":"SBSDKRandomKeyGenerator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRandomKeyGenerator~1generateKey(keyLength:)\/title","op":"replace","value":"generateKeyWithLength:WithError:"},{"value":[{"text":"- ","kind":"text"},{"text":"generateKeyWithLength:WithError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRandomKeyGenerator~1generateKey(keyLength:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyLength\/title","value":"SBSDKStorageCryptingKeyLength"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyLength\/fragments","value":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyLength\/navigatorTitle","op":"replace","value":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}