{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomContentValidator"]]},"metadata":{"roleHeading":"Instance Property","title":"hash","fragments":[{"kind":"identifier","text":"hash"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCustomContentValidator(py)hash","role":"symbol","modules":[{"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomContentValidator\/hash","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcustomcontentvalidator\/hash"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCustomContentValidator/hash":{"url":"\/documentation\/scanbotsdk\/sbsdkcustomcontentvalidator\/hash","kind":"symbol","abstract":[],"role":"symbol","title":"hash","fragments":[{"text":"hash","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomContentValidator\/hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCustomContentValidator":{"title":"SBSDKCustomContentValidator","url":"\/documentation\/scanbotsdk\/sbsdkcustomcontentvalidator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCustomContentValidator","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKCustomContentValidator"}],"abstract":[{"type":"text","text":"Custom content validator."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomContentValidator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomContentValidator\/title","value":"SBSDKCustomContentValidator","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCustomContentValidator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomContentValidator\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomContentValidator\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCustomContentValidator"}],"op":"replace"}]}]}