{"abstract":[{"type":"text","text":"Returns a copy of the receivers current configuration."}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorViewController(im)copyCurrentConfiguration","roleHeading":"Instance Method","symbolKind":"method","title":"copyCurrentConfiguration()","navigatorTitle":[{"kind":"identifier","text":"copyCurrentConfiguration"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copyCurrentConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKDocumentDataExtractorConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfiguration","kind":"typeIdentifier"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copyCurrentConfiguration"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfiguration","kind":"typeIdentifier","text":"SBSDKDocumentDataExtractorConfiguration"}]}],"kind":"declarations"},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"The current configuration.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorviewcontroller\/copycurrentconfiguration()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorviewcontroller\/copycurrentconfiguration()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewController\/copyCurrentConfiguration()","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorViewController/copyCurrentConfiguration()":{"kind":"symbol","abstract":[{"text":"Returns a copy of the receivers current configuration.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"copyCurrentConfiguration"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewController\/copyCurrentConfiguration()","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorviewcontroller\/copycurrentconfiguration()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copyCurrentConfiguration"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfiguration","kind":"typeIdentifier","text":"SBSDKDocumentDataExtractorConfiguration"}],"role":"symbol","title":"copyCurrentConfiguration()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfiguration","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDataExtractorConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Configuration for the document data extractor."}],"title":"SBSDKDocumentDataExtractorConfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorViewController":{"title":"SBSDKDocumentDataExtractorViewController","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorviewcontroller","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractorViewController"}],"abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to extract documents data, e.g. German passports, ID cards and driver’s licenses on video frames.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorViewController"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"copyCurrentConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"copyCurrentConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"SBSDKDocumentDataExtractorConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfiguration"},{"text":" *) ","kind":"text"},{"text":"copyCurrentConfiguration","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The current configuration."}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"copyCurrentConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewController~1copyCurrentConfiguration()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyCurrentConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewController~1copyCurrentConfiguration()\/fragments"},{"value":"SBSDKDocumentDataExtractorConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfiguration\/navigatorTitle"},{"value":"SBSDKDocumentDataExtractorViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewController\/title"},{"value":[{"text":"SBSDKDocumentDataExtractorViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewController\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}