{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/init()"]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCodabarConfiguration(im)init","symbolKind":"init","title":"init()","roleHeading":"Initializer"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/init()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatCodabarConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatCodabarConfiguration"}],"role":"symbol","abstract":[{"text":"Codabar barcode configuration. Add to scanner configuration to scan Codabar barcodes.","type":"text"}],"type":"topic","title":"SBSDKBarcodeFormatCodabarConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration/init()":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","title":"init()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/init()","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/init()","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration\/title","value":"SBSDKBarcodeFormatCodabarConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCodabarConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatCodabarConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]}]}]}