{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeAdditionalParameters"]]},"abstract":[{"type":"text","text":"The checksum algorithms for MSI Plessey barcodes."}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"msiPlesseyChecksumAlgorithm"}],"role":"symbol","title":"msiPlesseyChecksumAlgorithm","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"msiPlesseyChecksumAlgorithm"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm","text":"SBSDKMSIPlesseyChecksumAlgorithm"},{"kind":"text","text":"]"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeAdditionalParameters(py)msiPlesseyChecksumAlgorithm"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"msiPlesseyChecksumAlgorithm"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm","text":"SBSDKMSIPlesseyChecksumAlgorithm"},{"kind":"text","text":"]"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Defaults to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm\/mod10"},{"type":"text","text":"."}],"type":"paragraph"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodeadditionalparameters\/msiplesseychecksumalgorithm"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodeadditionalparameters\/msiplesseychecksumalgorithm"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeAdditionalParameters\/msiPlesseyChecksumAlgorithm"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeAdditionalParameters":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeAdditionalParameters","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeadditionalparameters","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeAdditionalParameters","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIBarcodeAdditionalParameters","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A class that contains additional parameters for barcodes scanning and filtering."}],"title":"SBSDKUIBarcodeAdditionalParameters"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeAdditionalParameters/msiPlesseyChecksumAlgorithm":{"abstract":[{"text":"The checksum algorithms for MSI Plessey barcodes.","type":"text"}],"title":"msiPlesseyChecksumAlgorithm","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeadditionalparameters\/msiplesseychecksumalgorithm","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"msiPlesseyChecksumAlgorithm"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm","text":"SBSDKMSIPlesseyChecksumAlgorithm"},{"kind":"text","text":"]"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"msiPlesseyChecksumAlgorithm"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeAdditionalParameters\/msiPlesseyChecksumAlgorithm","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMSIPlesseyChecksumAlgorithm/mod10":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mod10"}],"abstract":[{"text":"Modulo 10.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm\/mod10","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mod10"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm","text":"SBSDKMSIPlesseyChecksumAlgorithm"}],"url":"\/documentation\/scanbotsdk\/sbsdkmsiplesseychecksumalgorithm\/mod10","type":"topic","title":"mod10"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMSIPlesseyChecksumAlgorithm":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm","navigatorTitle":[{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"abstract":[{"text":"Checksum algorithm for MSI_PLESSEY.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkmsiplesseychecksumalgorithm","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"type":"topic","title":"SBSDKMSIPlesseyChecksumAlgorithm","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"msiPlesseyChecksumAlgorithm","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"msiPlesseyChecksumAlgorithm","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<SBSDKMSIPlesseyChecksumAlgorithm *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"msiPlesseyChecksumAlgorithm","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeAdditionalParameters\/title","value":"SBSDKUIBarcodeAdditionalParameters","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeAdditionalParameters\/fragments","value":[{"text":"SBSDKUIBarcodeAdditionalParameters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeAdditionalParameters\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIBarcodeAdditionalParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeAdditionalParameters~1msiPlesseyChecksumAlgorithm\/title","op":"replace","value":"msiPlesseyChecksumAlgorithm"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeAdditionalParameters~1msiPlesseyChecksumAlgorithm\/fragments","op":"replace","value":[{"text":"msiPlesseyChecksumAlgorithm","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm~1mod10\/title","op":"replace","value":"mod10"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm~1mod10\/fragments","op":"replace","value":[{"kind":"identifier","text":"mod10"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/title","op":"replace","value":"SBSDKMSIPlesseyChecksumAlgorithm"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/fragments","op":"replace","value":[{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKMSIPlesseyChecksumAlgorithm"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}