{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setAddressDatabaseURL(_:forDocumentTypes:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/setaddressdatabaseurl(_:fordocumenttypes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/setaddressdatabaseurl(_:fordocumenttypes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Lets you specify the address database URL for the address parser. The address parser uses a database to extract accurate address information from documents."},{"type":"text","text":" "},{"type":"text","text":"Currently the address database only supports german addresses."}],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfigurationBuilder(im)setAddressDatabaseURL:forDocumentTypes:","navigatorTitle":[{"text":"setAddressDatabaseURL:forDocumentTypes:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAddressDatabaseURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"forDocumentTypes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKDocumentsModelRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelRootType","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}],"title":"setAddressDatabaseURL(_:forDocumentTypes:)","roleHeading":"Instance Method","symbolKind":"method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAddressDatabaseURL"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forDocumentTypes"},{"kind":"text","text":" "},{"kind":"internalParam","text":"documentTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType","text":"SBSDKDocumentsModelRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelRootType"},{"kind":"text","text":"]?)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"url","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The file URL of the address database file. If nil, no address parsing will be performed."}]}]},{"name":"documentTypes","content":[{"inlineContent":[{"type":"text","text":"The document types for which the address database parsing should be enabled. If nil, the address database parsing will be enabled for all accepted document types."}],"type":"paragraph"}]}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelRootType":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelRootType"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelRootType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelroottype","title":"SBSDKDocumentsModelRootType","abstract":[{"type":"text","text":"Root document type."}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractor":{"title":"SBSDKDocumentDataExtractor","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A class to extract generic documents data on various image sources."},{"type":"text","text":" "},{"type":"text","text":"Extracts the sub-documents, field names and field values from many types of documents e.g. German passports, ID cards, driver’s licenses."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder/setAddressDatabaseURL(_:forDocumentTypes:)":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/setaddressdatabaseurl(_:fordocumenttypes:)","kind":"symbol","title":"setAddressDatabaseURL(_:forDocumentTypes:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAddressDatabaseURL","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"forDocumentTypes","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelRootType","text":"SBSDKDocumentsModelRootType","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}],"navigatorTitle":[{"text":"setAddressDatabaseURL:forDocumentTypes:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setAddressDatabaseURL(_:forDocumentTypes:)","abstract":[{"type":"text","text":"Lets you specify the address database URL for the address parser. The address parser uses a database to extract accurate address information from documents."},{"type":"text","text":" "},{"type":"text","text":"Currently the address database only supports german addresses."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder","navigatorTitle":[{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"}],"type":"topic","title":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"symbol","abstract":[{"text":"A builder class to help with assembling the configuration for ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor","isActive":true,"type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"setAddressDatabaseURL:forDocumentTypes:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAddressDatabaseURL:forDocumentTypes:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setAddressDatabaseURL:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"url"},{"kind":"text","text":" "},{"kind":"identifier","text":"forDocumentTypes:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKDocumentsModelRootType *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"documentTypes"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"url","content":[{"type":"paragraph","inlineContent":[{"text":"The file URL of the address database file. If nil, no address parsing will be performed.","type":"text"}]}]},{"name":"documentTypes","content":[{"inlineContent":[{"type":"text","text":"The document types for which the address database parsing should be enabled. If nil, the address database parsing will be enabled for all accepted document types."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType\/title","value":"SBSDKDocumentsModelRootType","op":"replace"},{"value":[{"text":"SBSDKDocumentsModelRootType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocumentsModelRootType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType\/navigatorTitle","op":"replace"},{"value":"SBSDKDocumentDataExtractor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/navigatorTitle","op":"replace"},{"value":"setAddressDatabaseURL:forDocumentTypes:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setAddressDatabaseURL(_:forDocumentTypes:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setAddressDatabaseURL:forDocumentTypes:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setAddressDatabaseURL(_:forDocumentTypes:)\/fragments","op":"replace"},{"value":"SBSDKDocumentDataExtractorConfigurationBuilder","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}