{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEuropeanHealthInsuranceCardConfiguration"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardConfiguration","kind":"typeIdentifier","text":"SBSDKEuropeanHealthInsuranceCardConfiguration"},{"kind":"text","text":")"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfigurationBuilder(im)setEuropeanHealthInsuranceCardConfiguration:","title":"setEuropeanHealthInsuranceCardConfiguration(_:)","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"setEuropeanHealthInsuranceCardConfiguration:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setEuropeanHealthInsuranceCardConfiguration(_:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder"]]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Lets you fine-tune the recognition of EU health insurance cards. Setting this property will automatically add the document type "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType\/europeanHealthInsuranceCard"},{"type":"text","text":" to the accepted document types."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setEuropeanHealthInsuranceCardConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"config","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardConfiguration","text":"SBSDKEuropeanHealthInsuranceCardConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"config","content":[{"inlineContent":[{"text":"The machine-readable-zone-based generic document recognizer configuration.","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/seteuropeanhealthinsurancecardconfiguration(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/seteuropeanhealthinsurancecardconfiguration(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractor":{"title":"SBSDKDocumentDataExtractor","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A class to extract generic documents data on various image sources."},{"type":"text","text":" "},{"type":"text","text":"Extracts the sub-documents, field names and field values from many types of documents e.g. German passports, ID cards, driver’s licenses."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder/setEuropeanHealthInsuranceCardConfiguration(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setEuropeanHealthInsuranceCardConfiguration(_:)","abstract":[{"text":"Lets you fine-tune the recognition of EU health insurance cards. Setting this property will automatically add the document type ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType\/europeanHealthInsuranceCard"},{"text":" to the accepted document types.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setEuropeanHealthInsuranceCardConfiguration:"}],"type":"topic","title":"setEuropeanHealthInsuranceCardConfiguration(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEuropeanHealthInsuranceCardConfiguration"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardConfiguration","kind":"typeIdentifier","text":"SBSDKEuropeanHealthInsuranceCardConfiguration"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/seteuropeanhealthinsurancecardconfiguration(_:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelRootType/europeanHealthInsuranceCard":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"europeanHealthInsuranceCard"}],"role":"symbol","abstract":[{"text":"EuropeanHealthInsuranceCard document type.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType\/europeanHealthInsuranceCard","title":"europeanHealthInsuranceCard","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelroottype\/europeanhealthinsurancecard","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"europeanHealthInsuranceCard"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelRootType","kind":"typeIdentifier","text":"SBSDKDocumentsModelRootType"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardConfiguration","title":"SBSDKEuropeanHealthInsuranceCardConfiguration","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKEuropeanHealthInsuranceCardConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"European Health Insurance Card (EHIC) configuration element. Add to extractor configuration to scan EHICs."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder","navigatorTitle":[{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"}],"type":"topic","title":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"symbol","abstract":[{"text":"A builder class to help with assembling the configuration for ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor","isActive":true,"type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"setEuropeanHealthInsuranceCardConfiguration:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"setEuropeanHealthInsuranceCardConfiguration:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setEuropeanHealthInsuranceCardConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardConfiguration"},{"text":" *) ","kind":"text"},{"text":"config","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The machine-readable-zone-based generic document recognizer configuration.","type":"text"}]}],"name":"config"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SBSDKDocumentDataExtractor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/title"},{"op":"replace","value":[{"text":"SBSDKDocumentDataExtractor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentDataExtractor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/navigatorTitle"},{"op":"replace","value":"setEuropeanHealthInsuranceCardConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setEuropeanHealthInsuranceCardConfiguration(_:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setEuropeanHealthInsuranceCardConfiguration(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setEuropeanHealthInsuranceCardConfiguration:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType~1europeanHealthInsuranceCard\/title","value":"europeanHealthInsuranceCard","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType~1europeanHealthInsuranceCard\/fragments","value":[{"kind":"identifier","text":"europeanHealthInsuranceCard"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardConfiguration\/title","value":"SBSDKEuropeanHealthInsuranceCardConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder\/title","value":"SBSDKDocumentDataExtractorConfigurationBuilder","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder\/fragments","value":[{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder\/navigatorTitle","value":[{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"}],"op":"replace"}]}]}