{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternintrocustomimage\/hash"]}],"metadata":{"fragments":[{"text":"hash","kind":"identifier"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternIntroCustomImage(py)hash","modules":[{"name":"ScanbotSDK"}],"title":"hash","role":"symbol","roleHeading":"Instance Property"},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroCustomImage\/hash","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroCustomImage"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternIntroCustomImage/hash":{"type":"topic","role":"symbol","title":"hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroCustomImage\/hash","fragments":[{"text":"hash","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternintrocustomimage\/hash","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternIntroCustomImage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TextPatternIntroCustomImage","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A custom image for the introduction screen."}],"navigatorTitle":[{"text":"SBSDKUI2TextPatternIntroCustomImage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroCustomImage","title":"SBSDKUI2TextPatternIntroCustomImage","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternintrocustomimage","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternIntroCustomImage\/title","op":"replace","value":"SBSDKUI2TextPatternIntroCustomImage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternIntroCustomImage\/fragments","op":"replace","value":[{"text":"SBSDKUI2TextPatternIntroCustomImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternIntroCustomImage\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2TextPatternIntroCustomImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}