{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKCameraLiveScannerResolution) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","title":"SBSDKCameraLiveScannerResolution","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"roleHeading":"Enumeration","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCameraLiveScannerResolution","symbolKind":"enum"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcameralivescannerresolution"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcameralivescannerresolution"]}],"abstract":[{"type":"text","text":"The size of the image from camera which would be sent to the scanner for live scanning."}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"sections":[],"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution\/auto","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution\/fullHd","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution\/uhd"]},{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution\/init(rawValue:)"]},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution\/RawRepresentable-Implementations"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"},"doc://net.doo.ScanbotDocumentScannerSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraLiveScannerResolution/fullHd":{"role":"symbol","title":"SBSDKCameraLiveScannerResolution.fullHd","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullHd"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolutionFullHd"}],"type":"topic","abstract":[{"type":"text","text":"The image is in Full HD resolution. 1920x1080 pixels or close to it."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameralivescannerresolution\/fullhd","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution\/fullHd","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraLiveScannerResolution/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","type":"topic","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameralivescannerresolution\/equatable-implementations","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution\/Equatable-Implementations","kind":"article"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraLiveScannerResolution/init(rawValue:)":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(rawValue:)","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameralivescannerresolution\/init(rawvalue:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraLiveScannerResolution/uhd":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uhd","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKCameraLiveScannerResolutionUhd","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution\/uhd","abstract":[{"text":"The image is in UHD resolution. 3840x2160 pixels or close to it.","type":"text"}],"role":"symbol","title":"SBSDKCameraLiveScannerResolution.uhd","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameralivescannerresolution\/uhd"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraLiveScannerResolution/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameralivescannerresolution\/rawrepresentable-implementations","role":"collectionGroup","abstract":[],"kind":"article","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://net.doo.ScanbotDocumentScannerSDK/s12CaseIterableP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s12CaseIterableP","type":"unresolvable","title":"Swift.CaseIterable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraLiveScannerResolution":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolution"}],"type":"topic","title":"SBSDKCameraLiveScannerResolution","abstract":[{"type":"text","text":"The size of the image from camera which would be sent to the scanner for live scanning."}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameralivescannerresolution","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraLiveScannerResolution"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraLiveScannerResolution/auto":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameralivescannerresolution\/auto","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution\/auto","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"auto"}],"abstract":[{"type":"text","text":"Select to the image resolution automatically based on device specifics."}],"title":"SBSDKCameraLiveScannerResolution.auto","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolutionAuto"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKCameraLiveScannerResolution","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolution"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution\/auto","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution\/fullHd","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution\/uhd"],"generated":true,"anchor":"Enumeration-Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraLiveScannerResolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKCameraLiveScannerResolutionFullHd","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraLiveScannerResolution~1fullHd\/title"},{"op":"replace","value":[{"text":"SBSDKCameraLiveScannerResolutionFullHd","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraLiveScannerResolution~1fullHd\/fragments"},{"op":"replace","value":"SBSDKCameraLiveScannerResolutionUhd","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraLiveScannerResolution~1uhd\/title"},{"op":"replace","value":[{"text":"SBSDKCameraLiveScannerResolutionUhd","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraLiveScannerResolution~1uhd\/fragments"},{"op":"replace","value":"SBSDKCameraLiveScannerResolution","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraLiveScannerResolution\/title"},{"op":"replace","value":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraLiveScannerResolution\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolution"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraLiveScannerResolution\/navigatorTitle"},{"op":"replace","value":"SBSDKCameraLiveScannerResolutionAuto","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraLiveScannerResolution~1auto\/title"},{"op":"replace","value":[{"text":"SBSDKCameraLiveScannerResolutionAuto","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraLiveScannerResolution~1auto\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}