{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2CapturePhotoQualityPrioritization) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturephotoqualityprioritization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturephotoqualityprioritization"]}],"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/balanced","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/quality","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/speed"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"metadata":{"title":"SBSDKUI2CapturePhotoQualityPrioritization","navigatorTitle":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"symbolKind":"enum","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CapturePhotoQualityPrioritization","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Enumeration"},"abstract":[{"type":"text","text":"Determines the prioritization of still image quality and capturing speed."}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"],"type":"conformsTo","kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CapturePhotoQualityPrioritization/init(rawValue:)":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/init(rawValue:)","title":"init(rawValue:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturephotoqualityprioritization\/init(rawvalue:)","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE"},"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotDocumentScannerSDK/s12CaseIterableP":{"type":"unresolvable","title":"Swift.CaseIterable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s12CaseIterableP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CapturePhotoQualityPrioritization/balanced":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"balanced"}],"title":"SBSDKUI2CapturePhotoQualityPrioritization.balanced","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/balanced","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritizationBalanced"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturephotoqualityprioritization\/balanced","type":"topic","abstract":[{"type":"text","text":"Balances capturing speed and image quality equally. This is the default value."}]},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CapturePhotoQualityPrioritization":{"kind":"symbol","type":"topic","role":"symbol","title":"SBSDKUI2CapturePhotoQualityPrioritization","abstract":[{"type":"text","text":"Determines the prioritization of still image quality and capturing speed."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturephotoqualityprioritization"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CapturePhotoQualityPrioritization/quality":{"type":"topic","title":"SBSDKUI2CapturePhotoQualityPrioritization.quality","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturephotoqualityprioritization\/quality","abstract":[{"text":"Captures a still image with the best possible quality in terms of noise, frozen motion and detail in low light. The speed of the capturing might be reduced.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2CapturePhotoQualityPrioritizationQuality","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quality","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/quality"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CapturePhotoQualityPrioritization/speed":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturephotoqualityprioritization\/speed","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CapturePhotoQualityPrioritizationSpeed","kind":"identifier"}],"abstract":[{"text":"Captures a still image at the highest possible speed. The quality of the image may be degraded.","type":"text"}],"title":"SBSDKUI2CapturePhotoQualityPrioritization.speed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"speed","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/speed"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CapturePhotoQualityPrioritization/RawRepresentable-Implementations":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturephotoqualityprioritization\/rawrepresentable-implementations","title":"RawRepresentable Implementations","kind":"article","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/RawRepresentable-Implementations","type":"topic","abstract":[],"role":"collectionGroup"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CapturePhotoQualityPrioritization/Equatable-Implementations":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturephotoqualityprioritization\/equatable-implementations","kind":"article","title":"Equatable Implementations","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/Equatable-Implementations","role":"collectionGroup","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUI2CapturePhotoQualityPrioritization"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/balanced","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/quality","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/speed"]}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CapturePhotoQualityPrioritization~1balanced\/title","op":"replace","value":"SBSDKUI2CapturePhotoQualityPrioritizationBalanced"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CapturePhotoQualityPrioritization~1balanced\/fragments","op":"replace","value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritizationBalanced","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/title","op":"replace","value":"SBSDKUI2CapturePhotoQualityPrioritization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/fragments","op":"replace","value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CapturePhotoQualityPrioritization~1quality\/title","op":"replace","value":"SBSDKUI2CapturePhotoQualityPrioritizationQuality"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CapturePhotoQualityPrioritization~1quality\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritizationQuality"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CapturePhotoQualityPrioritization~1speed\/title","op":"replace","value":"SBSDKUI2CapturePhotoQualityPrioritizationSpeed"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CapturePhotoQualityPrioritization~1speed\/fragments","op":"replace","value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritizationSpeed","kind":"identifier"}]}]}]}