{"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKScanbotBinarizationFilter"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScanbotBinarizationFilter"}],"title":"SBSDKScanbotBinarizationFilter","symbolKind":"class","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScanbotBinarizationFilter","roleHeading":"Class"},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/init()"],"title":"Initializers","anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/outputMode"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/toJson(configuration:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"abstract":[{"type":"text","text":"Automatic binarization filter. This filter is a good starting point for most use cases."}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKScanbotBinarizationFilter) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScanbotBinarizationFilter"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscanbotbinarizationfilter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscanbotbinarizationfilter"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScanbotBinarizationFilter":{"abstract":[{"type":"text","text":"Automatic binarization filter. This filter is a good starting point for most use cases."}],"navigatorTitle":[{"text":"SBSDKScanbotBinarizationFilter","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanbotbinarizationfilter","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScanbotBinarizationFilter","kind":"identifier"}],"title":"SBSDKScanbotBinarizationFilter"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScanbotBinarizationFilter/outputMode":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/outputMode","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanbotbinarizationfilter\/outputmode","type":"topic","title":"outputMode","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"outputMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKOutputMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKOutputMode"}],"navigatorTitle":[{"text":"outputMode","kind":"identifier"}],"abstract":[{"text":"Output mode of the filter. BINARY will return a black and white image, GRAYSCALE will return an antialiased grayscale image.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter":{"navigatorTitle":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Base class for all parametric filters."}],"title":"SBSDKParametricFilter","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKParametricFilter","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScanbotBinarizationFilter/hash":{"fragments":[{"text":"hash","kind":"identifier"}],"role":"symbol","type":"topic","title":"hash","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/hash","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanbotbinarizationfilter\/hash","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScanbotBinarizationFilter/fromJsonWithJson:":{"type":"topic","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanbotbinarizationfilter\/fromjsonwithjson:","role":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/fromJsonWithJson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScanbotBinarizationFilter/toJson(configuration:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/toJson(configuration:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanbotbinarizationfilter\/tojson(configuration:)","title":"toJson(configuration:)","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScanbotBinarizationFilter/copyWithZone:":{"kind":"symbol","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanbotbinarizationfilter\/copywithzone:","title":"copyWithZone:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/copyWithZone:","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScanbotBinarizationFilter/init()":{"kind":"symbol","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanbotbinarizationfilter\/init()","title":"init()","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScanbotBinarizationFilter/isEqual:":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanbotbinarizationfilter\/isequal:","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/isEqual:","type":"topic","title":"isEqual:"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScanbotBinarizationFilter/initWithOutputMode:":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/initWithOutputMode:","type":"topic","kind":"symbol","title":"initWithOutputMode:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOutputMode:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithOutputMode:"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanbotbinarizationfilter\/initwithoutputmode:"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","title":"Swift.Decodable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKScanbotBinarizationFilter","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKScanbotBinarizationFilter"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKScanbotBinarizationFilter","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/hash","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/outputMode"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/copyWithZone:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/init()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/initWithOutputMode:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/isEqual:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/toJson(configuration:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter\/fromJsonWithJson:"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScanbotBinarizationFilter"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","kind":"typeIdentifier","text":"SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKScanbotBinarizationFilter","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScanbotBinarizationFilter\/title"},{"value":[{"text":"SBSDKScanbotBinarizationFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScanbotBinarizationFilter\/fragments","op":"replace"},{"value":[{"text":"SBSDKScanbotBinarizationFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScanbotBinarizationFilter\/navigatorTitle","op":"replace"},{"value":"outputMode","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScanbotBinarizationFilter~1outputMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"outputMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScanbotBinarizationFilter~1outputMode\/fragments","op":"replace"},{"value":"SBSDKParametricFilter","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/title","op":"replace"},{"value":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/navigatorTitle","op":"replace"},{"value":"toJsonWithConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScanbotBinarizationFilter~1toJson(configuration:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScanbotBinarizationFilter~1toJson(configuration:)\/fragments","op":"replace"},{"value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScanbotBinarizationFilter~1init()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScanbotBinarizationFilter~1init()\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}