{"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"roleHeading":"Enumeration","navigatorTitle":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"role":"symbol","title":"SBSDKUI2CameraPreviewMode","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraPreviewMode","symbolKind":"enum","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"sections":[],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode\/fillIn","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode\/fitIn"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode\/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2CameraPreviewMode) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerapreviewmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerapreviewmode"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Configuration of the camera preview mode.","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraPreviewMode":{"type":"topic","navigatorTitle":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"kind":"symbol","title":"SBSDKUI2CameraPreviewMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the camera preview mode."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerapreviewmode","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraPreviewMode/fillIn":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewModeFillIn"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerapreviewmode\/fillin","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode\/fillIn","abstract":[{"type":"text","text":"In this mode, the camera preview frames fill the entire layout view - the preview frames may contain additional content at the edges that are not visible in the preview layout."}],"kind":"symbol","title":"SBSDKUI2CameraPreviewMode.fillIn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fillIn"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraPreviewMode/init(rawValue:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerapreviewmode\/init(rawvalue:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode\/init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","title":"init(rawValue:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraPreviewMode/RawRepresentable-Implementations":{"abstract":[],"role":"collectionGroup","kind":"article","title":"RawRepresentable Implementations","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode\/RawRepresentable-Implementations","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerapreviewmode\/rawrepresentable-implementations","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotDocumentScannerSDK/s12CaseIterableP":{"title":"Swift.CaseIterable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s12CaseIterableP","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraPreviewMode/fitIn":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fitIn","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerapreviewmode\/fitin","abstract":[{"type":"text","text":"In this mode, the camera preview frames will be scaled to fit inside the layout view size - the full preview frame content will be visible, but unused edges might appear in the preview layout."}],"title":"SBSDKUI2CameraPreviewMode.fitIn","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode\/fitIn","navigatorTitle":[{"text":"SBSDKUI2CameraPreviewModeFitIn","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraPreviewMode/Equatable-Implementations":{"title":"Equatable Implementations","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerapreviewmode\/equatable-implementations","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode\/Equatable-Implementations","role":"collectionGroup","type":"topic","abstract":[],"kind":"article"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUI2CameraPreviewMode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode\/fillIn","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode\/fitIn"],"generated":true,"anchor":"Enumeration-Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPreviewMode\/title","op":"replace","value":"SBSDKUI2CameraPreviewMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPreviewMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPreviewMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPreviewMode~1fillIn\/title","op":"replace","value":"SBSDKUI2CameraPreviewModeFillIn"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPreviewMode~1fillIn\/fragments","op":"replace","value":[{"text":"SBSDKUI2CameraPreviewModeFillIn","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPreviewMode~1fitIn\/title","op":"replace","value":"SBSDKUI2CameraPreviewModeFitIn"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPreviewMode~1fitIn\/fragments","op":"replace","value":[{"text":"SBSDKUI2CameraPreviewModeFitIn","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}