{"metadata":{"role":"symbol","navigatorTitle":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKKeyedImageStorage"}],"title":"SBSDKKeyedImageStorage","roleHeading":"Class","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKKeyedImageStorage"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/init(storageLocation:cryptingProvider:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/init(storageLocation:fileFormat:encryptionMode:cryptingProvider:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/cryptingProvider","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/encryptionMode","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/fileFormat","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/imageCount","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/imageKeys","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/imageURLs","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/jpegCompressionQuality"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/image(for:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/imageURL(for:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/removeAll()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/removeImage(for:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/removeImages(matchingPrefix:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/set(image:for:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/waitUntilWritingCompleted()"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/temporary"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKKeyedImageStorage","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage"]}],"abstract":[{"text":"A simple thread-safe multiple-reader-single-writer key-value fashioned disk image cache class.","type":"text"},{"text":" ","type":"text"},{"text":"Manages images in a dictionary-like fashion.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/removeAll()":{"abstract":[{"text":"Removes all stored images from the receiver as well as from the file system.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/removeall()","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/removeAll()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAll"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"removeAllImages"}],"kind":"symbol","title":"removeAll()"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/image(for:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/image(for:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/image(for:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRef","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"imageForKey:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Returns the image for given key.","type":"text"}],"title":"image(for:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncryptionMode/disabled":{"abstract":[{"type":"text","text":"Encryption is not used when loading or saving images. Trying to load an encrypted image will fail."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKEncryptionModeDisabled"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencryptionmode\/disabled","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/disabled","title":"SBSDKEncryptionMode.disabled"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/set(image:for:)":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"setImage:forKey:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/set(image:for:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/set(image:for:)","title":"set(image:for:)","abstract":[{"text":"Stores an image at the given key.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRef"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/imageKeys":{"title":"imageKeys","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/imagekeys","abstract":[{"type":"text","text":"Array of all stored keys."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageKeys"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/imageKeys","navigatorTitle":[{"kind":"identifier","text":"imageKeys"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/cryptingProvider":{"title":"cryptingProvider","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/cryptingprovider","abstract":[{"type":"text","text":"If non-nil, overrides the default image encryption provider."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cryptingProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider","text":"SBSDKStorageCryptingProvider","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/cryptingProvider","navigatorTitle":[{"text":"cryptingProvider","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/waitUntilWritingCompleted()":{"abstract":[{"type":"text","text":"Blocks the current thread until all enqueued writing operations have been finished."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"waitUntilWritingCompleted"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/waituntilwritingcompleted()","type":"topic","title":"waitUntilWritingCompleted()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitUntilWritingCompleted"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/waitUntilWritingCompleted()"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/fileFormat":{"abstract":[{"type":"text","text":"Image file format to be used to store the managed images."}],"title":"fileFormat","navigatorTitle":[{"kind":"identifier","text":"fileFormat"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/fileformat","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/fileFormat","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileFormat"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat","kind":"typeIdentifier","text":"SBSDKImageFileFormat"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/removeImages(matchingPrefix:)":{"navigatorTitle":[{"kind":"identifier","text":"removeImagesForKeysMatchingPrefix:"}],"role":"symbol","abstract":[{"type":"text","text":"Removes the images at keys from the receiver as well as from the file system, which keys prefix match the prefix string."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeImages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"matchingPrefix"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"type":"topic","title":"removeImages(matchingPrefix:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/removeImages(matchingPrefix:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/removeimages(matchingprefix:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/encryptionMode":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/encryptionmode","navigatorTitle":[{"text":"encryptionMode","kind":"identifier"}],"kind":"symbol","title":"encryptionMode","abstract":[{"type":"text","text":"The encryption mode for the stored images. Defaults to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/disabled"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encryptionMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKEncryptionMode","text":"SBSDKEncryptionMode","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/encryptionMode"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/init(storageLocation:cryptingProvider:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/init(storageLocation:cryptingProvider:)","title":"init(storageLocation:cryptingProvider:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/init(storagelocation:cryptingprovider:)","kind":"symbol","abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"SBSDKKeyedImageStorage"},{"type":"text","text":" at the given storage location."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithStorageLocation:cryptingProvider:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"storageLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"cryptingProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/temporary":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"temporary","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKKeyedImageStorage","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKKeyedImageStorage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"temporary","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/temporary","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/temporary","type":"topic","navigatorTitle":[{"text":"temporary","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A new "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage","isActive":true},{"type":"text","text":" at a temporary location (application caches folder)."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/init(storageLocation:fileFormat:encryptionMode:cryptingProvider:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/init(storageLocation:fileFormat:encryptionMode:cryptingProvider:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"storageLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"fileFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"encryptionMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKEncryptionMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKEncryptionMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cryptingProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"initWithStorageLocation:fileFormat:encryptionMode:cryptingProvider:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"SBSDKKeyedImageStorage"},{"type":"text","text":" at the given storage location with given image file format."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/init(storagelocation:fileformat:encryptionmode:cryptingprovider:)","role":"symbol","title":"init(storageLocation:fileFormat:encryptionMode:cryptingProvider:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/imageURL(for:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/imageURL(for:)","title":"imageURL(for:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/imageurl(for:)","kind":"symbol","abstract":[{"type":"text","text":"Returns the image file URL for given key."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageURLForKey:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/imageURLs":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/imageURLs","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/imageurls","abstract":[{"type":"text","text":"Array of all stored images URLs (values)."},{"type":"text","text":" "},{"type":"text","text":"Note: If the storage is encrypted, the data at these URLs are encrypted and must be properly"},{"type":"text","text":" "},{"type":"text","text":"decrypted before being used."}],"role":"symbol","navigatorTitle":[{"text":"imageURLs","kind":"identifier"}],"kind":"symbol","title":"imageURLs","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageURLs","kind":"identifier"},{"text":": [","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"title":"SBSDKKeyedImageStorage","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage","abstract":[{"type":"text","text":"A simple thread-safe multiple-reader-single-writer key-value fashioned disk image cache class."},{"type":"text","text":" "},{"type":"text","text":"Manages images in a dictionary-like fashion."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/imageCount":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The number of stored images."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/imageCount","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/imagecount","title":"imageCount","navigatorTitle":[{"kind":"identifier","text":"imageCount"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/removeImage(for:)":{"title":"removeImage(for:)","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/removeimage(for:)","kind":"symbol","abstract":[{"type":"text","text":"Removes the image at the given key from the receiver as well as from the file system."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/removeImage(for:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"removeImageForKey:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/jpegCompressionQuality":{"navigatorTitle":[{"text":"jpegCompressionQuality","kind":"identifier"}],"abstract":[{"text":"The JPEG compression if JPEG file format is used. Range: 0.0 - 1.0.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/jpegcompressionquality","title":"jpegCompressionQuality","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/jpegCompressionQuality","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpegCompressionQuality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKKeyedImageStorage"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/cryptingProvider","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/encryptionMode","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/fileFormat","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/imageCount","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/imageKeys","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/imageURLs","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/jpegCompressionQuality"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/image(for:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/imageURL(for:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/init(storageLocation:cryptingProvider:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/init(storageLocation:fileFormat:encryptionMode:cryptingProvider:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/removeAll()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/removeImage(for:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/removeImages(matchingPrefix:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/set(image:for:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/waitUntilWritingCompleted()"],"anchor":"Instance-Methods"},{"title":"Type Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/temporary"],"anchor":"Type-Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKKeyedImageStorage"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1removeAll()\/title","op":"replace","value":"removeAllImages"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1removeAll()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeAllImages"}]},{"op":"replace","value":"imageForKey:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1image(for:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imageForKey:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1image(for:)\/fragments"},{"op":"replace","value":"SBSDKEncryptionModeDisabled","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode~1disabled\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKEncryptionModeDisabled"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode~1disabled\/fragments"},{"op":"replace","value":"setImage:forKey:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1set(image:for:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setImage:forKey:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1set(image:for:)\/fragments"},{"op":"replace","value":"imageKeys","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1imageKeys\/title"},{"op":"replace","value":[{"kind":"identifier","text":"imageKeys"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1imageKeys\/fragments"},{"op":"replace","value":"cryptingProvider","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1cryptingProvider\/title"},{"op":"replace","value":[{"text":"cryptingProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1cryptingProvider\/fragments"},{"op":"replace","value":"waitUntilWritingCompleted","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1waitUntilWritingCompleted()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"waitUntilWritingCompleted","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1waitUntilWritingCompleted()\/fragments"},{"op":"replace","value":"fileFormat","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1fileFormat\/title"},{"op":"replace","value":[{"text":"fileFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1fileFormat\/fragments"},{"op":"replace","value":"removeImagesForKeysMatchingPrefix:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1removeImages(matchingPrefix:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeImagesForKeysMatchingPrefix:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1removeImages(matchingPrefix:)\/fragments"},{"op":"replace","value":"encryptionMode","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1encryptionMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"encryptionMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1encryptionMode\/fragments"},{"op":"replace","value":"initWithStorageLocation:cryptingProvider:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1init(storageLocation:cryptingProvider:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStorageLocation:cryptingProvider:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1init(storageLocation:cryptingProvider:)\/fragments"},{"op":"replace","value":"temporary","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1temporary\/title"},{"op":"replace","value":[{"text":"temporary","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1temporary\/fragments"},{"op":"replace","value":"initWithStorageLocation:fileFormat:encryptionMode:cryptingProvider:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1init(storageLocation:fileFormat:encryptionMode:cryptingProvider:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithStorageLocation:fileFormat:encryptionMode:cryptingProvider:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1init(storageLocation:fileFormat:encryptionMode:cryptingProvider:)\/fragments"},{"op":"replace","value":"imageURLForKey:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1imageURL(for:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageURLForKey:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1imageURL(for:)\/fragments"},{"op":"replace","value":"imageURLs","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1imageURLs\/title"},{"op":"replace","value":[{"kind":"identifier","text":"imageURLs"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1imageURLs\/fragments"},{"op":"replace","value":"SBSDKKeyedImageStorage","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKKeyedImageStorage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage\/fragments"},{"op":"replace","value":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage\/navigatorTitle"},{"op":"replace","value":"imageCount","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1imageCount\/title"},{"op":"replace","value":[{"kind":"identifier","text":"imageCount"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1imageCount\/fragments"},{"op":"replace","value":"removeImageForKey:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1removeImage(for:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeImageForKey:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1removeImage(for:)\/fragments"},{"value":"jpegCompressionQuality","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1jpegCompressionQuality\/title"},{"value":[{"text":"jpegCompressionQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1jpegCompressionQuality\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}