{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","title":"deleteKeyForContext(_:keyLength:)","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVolatileKeyProvider(im)deleteKeyForContext:keyLength:","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteKeyForContext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"keyLength","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"deleteKeyForContext:keyLength:","kind":"identifier"}],"roleHeading":"Instance Method"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/deleteKeyForContext(_:keyLength:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider"]]},"abstract":[{"text":"Deletes the key for the given context and key length.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvolatilekeyprovider\/deletekeyforcontext(_:keylength:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvolatilekeyprovider\/deletekeyforcontext(_:keylength:)"]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteKeyForContext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"context","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"keyLength","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyLength","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The context to generate or load the key for. For most applications in Scanbot SDK the context is derived from the URL of the file to encrypted or decrypted by calling the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Foundation\/URL\/sbsdk_encryptionContext","type":"reference","isActive":true},{"text":" property on the URL.","type":"text"}],"type":"paragraph"}],"name":"context"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The length of the key to be deleted."}]}],"name":"keyLength"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":" if a key was found and deleted, "},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise."}],"type":"paragraph"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Foundation/URL/sbsdk_encryptionContext":{"url":"\/documentation\/scanbotsdk\/foundation\/url\/sbsdk_encryptioncontext","title":"sbsdk_encryptionContext","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sbsdk_encryptionContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","abstract":[{"type":"text","text":"The encryption context of the URL."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Foundation\/URL\/sbsdk_encryptionContext"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVolatileKeyProvider":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvolatilekeyprovider","title":"SBSDKVolatileKeyProvider","abstract":[{"type":"text","text":"A volatile key provider that generates and stores keys in memory."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider","navigatorTitle":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyLength":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeylength","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"abstract":[{"type":"text","text":"The length of the encryption key."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyLength","role":"symbol","title":"SBSDKStorageCryptingKeyLength"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVolatileKeyProvider/deleteKeyForContext(_:keyLength:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"deleteKeyForContext:keyLength:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/deleteKeyForContext(_:keyLength:)","title":"deleteKeyForContext(_:keyLength:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteKeyForContext"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"keyLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","type":"topic","abstract":[{"text":"Deletes the key for the given context and key length.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkvolatilekeyprovider\/deletekeyforcontext(_:keylength:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"deleteKeyForContext:keyLength:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"deleteKeyForContext:keyLength:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"deleteKeyForContext:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"context","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"keyLength:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"keyLength","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The context to generate or load the key for. For most applications in Scanbot SDK the context is derived from the URL of the file to encrypted or decrypted by calling the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Foundation\/URL\/sbsdk_encryptionContext"},{"type":"text","text":" property on the URL."}],"type":"paragraph"}],"name":"context"},{"content":[{"inlineContent":[{"type":"text","text":"The length of the key to be deleted."}],"type":"paragraph"}],"name":"keyLength"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"text":"","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if a key was found and deleted, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" otherwise.","type":"text"}],"type":"paragraph"}]},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"SBSDKVolatileKeyProvider","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKVolatileKeyProvider"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider\/fragments","op":"replace"},{"value":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider\/navigatorTitle","op":"replace"},{"value":"SBSDKStorageCryptingKeyLength","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyLength\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyLength\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyLength\/navigatorTitle","op":"replace"},{"value":"deleteKeyForContext:keyLength:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider~1deleteKeyForContext(_:keyLength:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"deleteKeyForContext:keyLength:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider~1deleteKeyForContext(_:keyLength:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}