var searchData=
[
  ['scanbot_20sdk_20documentation',['Scanbot SDK Documentation',['../index.html',1,'']]],
  ['sbsdk_5fimagebyprocessingwithrotations_3apolygon_3afilter_3acompression_3alenscameraproperties_3aimagescale_3a',['sbsdk_imageByProcessingWithRotations:polygon:filter:compression:lensCameraProperties:imageScale:',['../category_u_i_image_07_s_b_s_d_k_08.html#a29715e3b1a88e8bb823bf0b88c7e2a3a',1,'UIImage(SBSDK)']]],
  ['sbsdk_5fimagedatabyapplyingfilter_3acompression_3a',['sbsdk_imageDataByApplyingFilter:compression:',['../category_u_i_image_07_s_b_s_d_k_08.html#a44a07f23ce5561dc99b9938f34c56686',1,'UIImage(SBSDK)']]],
  ['sbsdk_5fimagedatabyprocessingwithrotations_3apolygon_3afilter_3acompression_3alenscameraproperties_3aimagescale_3a',['sbsdk_imageDataByProcessingWithRotations:polygon:filter:compression:lensCameraProperties:imageScale:',['../category_u_i_image_07_s_b_s_d_k_08.html#af91a7771fbc1258788bd87e5c37e8613',1,'UIImage(SBSDK)']]],
  ['sbsdk_5fimagedatawithfixedorientation_3a',['sbsdk_imageDataWithFixedOrientation:',['../category_u_i_image_07_s_b_s_d_k_08.html#a970c7365a4d3a32fc51e5d9cb13086c5',1,'UIImage(SBSDK)']]],
  ['sbsdk_5fimagefilteredbyfilter_3a',['sbsdk_imageFilteredByFilter:',['../category_u_i_image_07_s_b_s_d_k_08.html#ab5e484241fdb6ac0944ad57ef083ee91',1,'UIImage(SBSDK)']]],
  ['sbsdk_5fimagefromsamplebuffer_3a',['sbsdk_imageFromSampleBuffer:',['../category_u_i_image_07_s_b_s_d_k_08.html#ade3bf53ea62b3d050f1de316db3f621b',1,'UIImage(SBSDK)']]],
  ['sbsdk_5fimagerotatedbydegrees_3a',['sbsdk_imageRotatedByDegrees:',['../category_u_i_image_07_s_b_s_d_k_08.html#abb6035f6893d7771bb33b516b39160da',1,'UIImage(SBSDK)']]],
  ['sbsdk_5fimagerotatedclockwise_3a',['sbsdk_imageRotatedClockwise:',['../category_u_i_image_07_s_b_s_d_k_08.html#a6af2e7619d03301a777af6cdf23e8d86',1,'UIImage(SBSDK)']]],
  ['sbsdk_5fimagerotatedcounterclockwise_3a',['sbsdk_imageRotatedCounterClockwise:',['../category_u_i_image_07_s_b_s_d_k_08.html#a7eca53a4a00869f85bb91ffdb9f9ae22',1,'UIImage(SBSDK)']]],
  ['sbsdk_5fimagewarpedbypolygon_3aandfilteredby_3aimagescale_3a',['sbsdk_imageWarpedByPolygon:andFilteredBy:imageScale:',['../category_u_i_image_07_s_b_s_d_k_08.html#a5b2bf4d035a95a06fb2cdc74b94f5ea5',1,'UIImage(SBSDK)']]],
  ['sbsdk_5fimagewarpedbypolygon_3aandfilteredby_3alenscameraproperties_3aimagescale_3a',['sbsdk_imageWarpedByPolygon:andFilteredBy:lensCameraProperties:imageScale:',['../category_u_i_image_07_s_b_s_d_k_08.html#a17ff6ed99f873247901bd3e3b2cc9d66',1,'UIImage(SBSDK)']]],
  ['sbsdk_5fimagewarpedbypolygon_3aimagescale_3a',['sbsdk_imageWarpedByPolygon:imageScale:',['../category_u_i_image_07_s_b_s_d_k_08.html#a44fc9c370d9ec23fd5bcfd564bab2d91',1,'UIImage(SBSDK)']]],
  ['sbsdk_5fimagewarpedbypolygon_3alenscameraproperties_3aimagescale_3a',['sbsdk_imageWarpedByPolygon:lensCameraProperties:imageScale:',['../category_u_i_image_07_s_b_s_d_k_08.html#ae19e48afb58ebfd32856936278baecc8',1,'UIImage(SBSDK)']]],
  ['sbsdk_5fimagewithfixedorientation',['sbsdk_imageWithFixedOrientation',['../category_u_i_image_07_s_b_s_d_k_08.html#a33afdf919f7f446ebbc4182a09240f8a',1,'UIImage(SBSDK)']]],
  ['sbsdk_5fimagewithstrippedalpha',['sbsdk_imageWithStrippedAlpha',['../category_u_i_image_07_s_b_s_d_k_08.html#ae88dc32fd3951aede841259fb7dfa505',1,'UIImage(SBSDK)']]],
  ['sbsdk_5finitfromsamplebuffer_3a',['sbsdk_initFromSampleBuffer:',['../category_u_i_image_07_s_b_s_d_k_08.html#a1d7b8a5bcb69c7b9fc01d3a3fad6d028',1,'UIImage(SBSDK)']]],
  ['sbsdkcamerasession',['SBSDKCameraSession',['../interface_s_b_s_d_k_camera_session.html',1,'']]],
  ['sbsdkcamerasessiondelegate_20_2dp',['SBSDKCameraSessionDelegate -p',['../protocol_s_b_s_d_k_camera_session_delegate_01-p.html',1,'']]],
  ['sbsdkchequerecognizer',['SBSDKChequeRecognizer',['../interface_s_b_s_d_k_cheque_recognizer.html',1,'']]],
  ['sbsdkchequerecognizerresult',['SBSDKChequeRecognizerResult',['../interface_s_b_s_d_k_cheque_recognizer_result.html',1,'']]],
  ['sbsdkcreditcardrecognizer',['SBSDKCreditCardRecognizer',['../interface_s_b_s_d_k_credit_card_recognizer.html',1,'']]],
  ['sbsdkcreditcardrecognizerresult',['SBSDKCreditCardRecognizerResult',['../interface_s_b_s_d_k_credit_card_recognizer_result.html',1,'']]],
  ['sbsdkcropviewcontroller',['SBSDKCropViewController',['../interface_s_b_s_d_k_crop_view_controller.html',1,'']]],
  ['sbsdkcropviewcontrollerdelegate_20_2dp',['SBSDKCropViewControllerDelegate -p',['../protocol_s_b_s_d_k_crop_view_controller_delegate_01-p.html',1,'']]],
  ['sbsdkdetectionstatuslabel',['SBSDKDetectionStatusLabel',['../interface_s_b_s_d_k_detection_status_label.html',1,'']]],
  ['sbsdkdeviceinformation',['SBSDKDeviceInformation',['../interface_s_b_s_d_k_device_information.html',1,'']]],
  ['sbsdkdocumentdetector',['SBSDKDocumentDetector',['../interface_s_b_s_d_k_document_detector.html',1,'']]],
  ['sbsdkdocumentdetectorresult',['SBSDKDocumentDetectorResult',['../interface_s_b_s_d_k_document_detector_result.html',1,'']]],
  ['sbsdkdocumentsdetectorresult',['SBSDKDocumentsDetectorResult',['../interface_s_b_s_d_k_documents_detector_result.html',1,'']]],
  ['sbsdkimagemetadata',['SBSDKImageMetadata',['../interface_s_b_s_d_k_image_metadata.html',1,'']]],
  ['sbsdkimagemetadataprocessor',['SBSDKImageMetadataProcessor',['../interface_s_b_s_d_k_image_metadata_processor.html',1,'']]],
  ['sbsdkimageprocessor',['SBSDKImageProcessor',['../interface_s_b_s_d_k_image_processor.html',1,'']]],
  ['sbsdkimageprocessor_28nsurl_29',['SBSDKImageProcessor(NSURL)',['../category_s_b_s_d_k_image_processor_07_n_s_u_r_l_08.html',1,'']]],
  ['sbsdkimagestorage',['SBSDKImageStorage',['../interface_s_b_s_d_k_image_storage.html',1,'']]],
  ['sbsdkinvoicerecognizer',['SBSDKInvoiceRecognizer',['../interface_s_b_s_d_k_invoice_recognizer.html',1,'']]],
  ['sbsdkinvoicerecognizerresult',['SBSDKInvoiceRecognizerResult',['../interface_s_b_s_d_k_invoice_recognizer_result.html',1,'']]],
  ['sbsdkinvoicerecognizerresultfield',['SBSDKInvoiceRecognizerResultField',['../interface_s_b_s_d_k_invoice_recognizer_result_field.html',1,'']]],
  ['sbsdklenscameraproperties',['SBSDKLensCameraProperties',['../interface_s_b_s_d_k_lens_camera_properties.html',1,'']]],
  ['sbsdkmachinereadablezonerecognizer',['SBSDKMachineReadableZoneRecognizer',['../interface_s_b_s_d_k_machine_readable_zone_recognizer.html',1,'']]],
  ['sbsdkmachinereadablezonerecognizerresult',['SBSDKMachineReadableZoneRecognizerResult',['../interface_s_b_s_d_k_machine_readable_zone_recognizer_result.html',1,'']]],
  ['sbsdkmultipledocumentsdetector',['SBSDKMultipleDocumentsDetector',['../interface_s_b_s_d_k_multiple_documents_detector.html',1,'']]],
  ['sbsdkocrresult',['SBSDKOCRResult',['../interface_s_b_s_d_k_o_c_r_result.html',1,'']]],
  ['sbsdkocrresultblock',['SBSDKOCRResultBlock',['../interface_s_b_s_d_k_o_c_r_result_block.html',1,'']]],
  ['sbsdkopticaltextrecognizer',['SBSDKOpticalTextRecognizer',['../interface_s_b_s_d_k_optical_text_recognizer.html',1,'']]],
  ['sbsdkopticaltextrecognizerdelegate_20_2dp',['SBSDKOpticalTextRecognizerDelegate -p',['../protocol_s_b_s_d_k_optical_text_recognizer_delegate_01-p.html',1,'']]],
  ['sbsdkpageanalyzerresult',['SBSDKPageAnalyzerResult',['../interface_s_b_s_d_k_page_analyzer_result.html',1,'']]],
  ['sbsdkpayformdetectedbox',['SBSDKPayFormDetectedBox',['../interface_s_b_s_d_k_pay_form_detected_box.html',1,'']]],
  ['sbsdkpayformdetectionresult',['SBSDKPayFormDetectionResult',['../interface_s_b_s_d_k_pay_form_detection_result.html',1,'']]],
  ['sbsdkpayformpolygon',['SBSDKPayFormPolygon',['../interface_s_b_s_d_k_pay_form_polygon.html',1,'']]],
  ['sbsdkpayformrecognitionresult',['SBSDKPayFormRecognitionResult',['../interface_s_b_s_d_k_pay_form_recognition_result.html',1,'']]],
  ['sbsdkpayformrecognizedfield',['SBSDKPayFormRecognizedField',['../interface_s_b_s_d_k_pay_form_recognized_field.html',1,'']]],
  ['sbsdkpayformresult',['SBSDKPayFormResult',['../interface_s_b_s_d_k_pay_form_result.html',1,'']]],
  ['sbsdkpayformscanner',['SBSDKPayFormScanner',['../interface_s_b_s_d_k_pay_form_scanner.html',1,'']]],
  ['sbsdkpayformtoken',['SBSDKPayFormToken',['../interface_s_b_s_d_k_pay_form_token.html',1,'']]],
  ['sbsdkpdfrenderer',['SBSDKPDFRenderer',['../interface_s_b_s_d_k_p_d_f_renderer.html',1,'']]],
  ['sbsdkpolygon',['SBSDKPolygon',['../interface_s_b_s_d_k_polygon.html',1,'']]],
  ['sbsdkpolygonedge',['SBSDKPolygonEdge',['../interface_s_b_s_d_k_polygon_edge.html',1,'']]],
  ['sbsdkpolygonlayer',['SBSDKPolygonLayer',['../interface_s_b_s_d_k_polygon_layer.html',1,'']]],
  ['sbsdkprocessingqueuefactory',['SBSDKProcessingQueueFactory',['../interface_s_b_s_d_k_processing_queue_factory.html',1,'']]],
  ['sbsdkprogress',['SBSDKProgress',['../interface_s_b_s_d_k_progress.html',1,'']]],
  ['sbsdkscannerviewcontroller',['SBSDKScannerViewController',['../interface_s_b_s_d_k_scanner_view_controller.html',1,'']]],
  ['sbsdkscannerviewcontrollerdelegate_20_2dp',['SBSDKScannerViewControllerDelegate -p',['../protocol_s_b_s_d_k_scanner_view_controller_delegate_01-p.html',1,'']]],
  ['sbsdkshutterbutton',['SBSDKShutterButton',['../interface_s_b_s_d_k_shutter_button.html',1,'']]],
  ['sbsdkstillimagecapturer',['SBSDKStillImageCapturer',['../interface_s_b_s_d_k_still_image_capturer.html',1,'']]],
  ['sbsdkstillimagecapturer_5fios10',['SBSDKStillImageCapturer_iOS10',['../interface_s_b_s_d_k_still_image_capturer__i_o_s10.html',1,'']]],
  ['scanbotsdk',['ScanbotSDK',['../interface_scanbot_s_d_k.html',1,'']]],
  ['scannercontroller_3adidcapturedocumentimage_3a',['scannerController:didCaptureDocumentImage:',['../protocol_s_b_s_d_k_scanner_view_controller_delegate_01-p.html#abdf349d7006d86c7d33cf5b638623e2f',1,'SBSDKScannerViewControllerDelegate -p']]],
  ['scannercontroller_3adidcaptureimage_3a',['scannerController:didCaptureImage:',['../protocol_s_b_s_d_k_scanner_view_controller_delegate_01-p.html#abad51f9a299539e1fb932dfed358ab74',1,'SBSDKScannerViewControllerDelegate -p']]],
  ['scannercontroller_3adiddetectpolygon_3awithstatus_3a',['scannerController:didDetectPolygon:withStatus:',['../protocol_s_b_s_d_k_scanner_view_controller_delegate_01-p.html#abd0f52ba79f72dd639e8c9d1ac38f003',1,'SBSDKScannerViewControllerDelegate -p']]],
  ['scannercontroller_3adidfailcapturingimage_3a',['scannerController:didFailCapturingImage:',['../protocol_s_b_s_d_k_scanner_view_controller_delegate_01-p.html#a40e8002fb1a61346b657d1638b56f2f8',1,'SBSDKScannerViewControllerDelegate -p']]],
  ['scannercontroller_3adidtoggleautoshutter_3a',['scannerController:didToggleAutoShutter:',['../protocol_s_b_s_d_k_scanner_view_controller_delegate_01-p.html#a39057035a227f042c195b53a203498b3',1,'SBSDKScannerViewControllerDelegate -p']]],
  ['scannercontroller_3adrawpolygonpoints_3awithdetectionstatus_3aonlayer_3a',['scannerController:drawPolygonPoints:withDetectionStatus:onLayer:',['../protocol_s_b_s_d_k_scanner_view_controller_delegate_01-p.html#a5a282d5a527a9b08af009bb110c3808a',1,'SBSDKScannerViewControllerDelegate -p']]],
  ['scannercontroller_3alocalizedtextfordetectionstatus_3a',['scannerController:localizedTextForDetectionStatus:',['../protocol_s_b_s_d_k_scanner_view_controller_delegate_01-p.html#a5049f18f394a378b8d4d1445f866507c',1,'SBSDKScannerViewControllerDelegate -p']]],
  ['scannercontroller_3apolygoncolorfordetectionstatus_3a',['scannerController:polygonColorForDetectionStatus:',['../protocol_s_b_s_d_k_scanner_view_controller_delegate_01-p.html#a82aa0a5532cb3359daba7d6ddf1034bf',1,'SBSDKScannerViewControllerDelegate -p']]],
  ['scannercontroller_3ashouldautocapturewithpolygon_3aandstatus_3a',['scannerController:shouldAutoCaptureWithPolygon:andStatus:',['../protocol_s_b_s_d_k_scanner_view_controller_delegate_01-p.html#aa8d53e786b334591646aa2c17e5ca28e',1,'SBSDKScannerViewControllerDelegate -p']]],
  ['scannercontroller_3ashouldrotateinterfacefordeviceorientation_3atransform_3a',['scannerController:shouldRotateInterfaceForDeviceOrientation:transform:',['../protocol_s_b_s_d_k_scanner_view_controller_delegate_01-p.html#a1f1e471a1450bc2d5aec6c4126058b01',1,'SBSDKScannerViewControllerDelegate -p']]],
  ['scannercontroller_3aviewfordetectionstatus_3a',['scannerController:viewForDetectionStatus:',['../protocol_s_b_s_d_k_scanner_view_controller_delegate_01-p.html#abb7e734d92a3d4d4f5334ecdb323ec50',1,'SBSDKScannerViewControllerDelegate -p']]],
  ['scannercontrollercenterforshutterbutton_3a',['scannerControllerCenterForShutterButton:',['../protocol_s_b_s_d_k_scanner_view_controller_delegate_01-p.html#ae698a7d00906a09466035e52fa0ab091',1,'SBSDKScannerViewControllerDelegate -p']]],
  ['scannercontrollercustomshutterbutton_3a',['scannerControllerCustomShutterButton:',['../protocol_s_b_s_d_k_scanner_view_controller_delegate_01-p.html#a42a0e55275d79b238b15dcb4a2f708d7',1,'SBSDKScannerViewControllerDelegate -p']]],
  ['scannercontrollerdidchangedeviceorientation_3ato_3atransform_3a',['scannerControllerDidChangeDeviceOrientation:to:transform:',['../protocol_s_b_s_d_k_scanner_view_controller_delegate_01-p.html#a3e8433416f30d3530e2381565ea515af',1,'SBSDKScannerViewControllerDelegate -p']]],
  ['scannercontrollerscaleforshutterbutton_3a',['scannerControllerScaleForShutterButton:',['../protocol_s_b_s_d_k_scanner_view_controller_delegate_01-p.html#a3bb961e7412e145666b332aa996f0bf0',1,'SBSDKScannerViewControllerDelegate -p']]],
  ['scannercontrollershouldanalysevideoframe_3a',['scannerControllerShouldAnalyseVideoFrame:',['../protocol_s_b_s_d_k_scanner_view_controller_delegate_01-p.html#ad35ec1a6e6f3060a5ac1bac9ae036e9f',1,'SBSDKScannerViewControllerDelegate -p']]],
  ['scannercontrollerwillcapturestillimage_3a',['scannerControllerWillCaptureStillImage:',['../protocol_s_b_s_d_k_scanner_view_controller_delegate_01-p.html#adbc7ab3cef4832b865f223535c9b9ad7',1,'SBSDKScannerViewControllerDelegate -p']]],
  ['scannerstatus',['scannerStatus',['../interface_s_b_s_d_k_scanner_view_controller.html#a616ab230b9294e57b64475c067c36c3e',1,'SBSDKScannerViewController::scannerStatus()'],['../interface_s_b_s_d_k_shutter_button.html#a60ed42aae4520abb1ed78dce385db6be',1,'SBSDKShutterButton::scannerStatus()']]],
  ['sensoraspectratio',['sensorAspectRatio',['../interface_s_b_s_d_k_lens_camera_properties.html#a9a0f836a5cb63948f67ca82188ec3dca',1,'SBSDKLensCameraProperties']]],
  ['sensordiagonal',['sensorDiagonal',['../interface_s_b_s_d_k_lens_camera_properties.html#a87b3f0e9821b66753adbbc3da353aee4',1,'SBSDKLensCameraProperties']]],
  ['sensorsize',['sensorSize',['../interface_s_b_s_d_k_lens_camera_properties.html#a013526d6126b6454389bcd5162f86657',1,'SBSDKLensCameraProperties']]],
  ['serialimageprocessingqueue',['serialImageProcessingQueue',['../interface_s_b_s_d_k_processing_queue_factory.html#a4942cd090eb2c4685278b2220b00058e',1,'SBSDKProcessingQueueFactory']]],
  ['serialtextprocessingqueue',['serialTextProcessingQueue',['../interface_s_b_s_d_k_processing_queue_factory.html#a888b50871e582bb401e3e4a2d645105f',1,'SBSDKProcessingQueueFactory']]],
  ['setabsolutepoint_3awithsize_3aforindex_3a',['setAbsolutePoint:withSize:forIndex:',['../interface_s_b_s_d_k_polygon.html#a1e330390093893bbc28da28d97c2a455',1,'SBSDKPolygon']]],
  ['setlicense_3a',['setLicense:',['../interface_scanbot_s_d_k.html#a67c702de287af6d0a56ab03b476ede7c',1,'ScanbotSDK']]],
  ['setloggingenabled_3a',['setLoggingEnabled:',['../interface_scanbot_s_d_k.html#ab87a41d64e7eb39566e60284cc810a1c',1,'ScanbotSDK']]],
  ['setnormalizedpoint_3aforindex_3a',['setNormalizedPoint:forIndex:',['../interface_s_b_s_d_k_polygon.html#a2d29707fef3de7993a1821a2d529ce55',1,'SBSDKPolygon']]],
  ['setpageanalyzerresult_3a',['setPageAnalyzerResult:',['../interface_s_b_s_d_k_o_c_r_result.html#a0544ab27036be3191b820642174f6374',1,'SBSDKOCRResult']]],
  ['shutterbuttonhidden',['shutterButtonHidden',['../interface_s_b_s_d_k_scanner_view_controller.html#aa765f8d286949cc34f97cf5711364963',1,'SBSDKScannerViewController']]],
  ['shuttermode',['shutterMode',['../interface_s_b_s_d_k_scanner_view_controller.html#abfb26f67f836f08520370601fe9014d7',1,'SBSDKScannerViewController']]],
  ['sortclockwise',['sortClockwise',['../interface_s_b_s_d_k_polygon.html#a3db88554b67f61c9f2ae25bc37f07861',1,'SBSDKPolygon']]],
  ['standarddeviationtopolygon_3a',['standardDeviationToPolygon:',['../interface_s_b_s_d_k_polygon.html#afe286e1fc52f842aa90a4c67b49b6260',1,'SBSDKPolygon']]],
  ['startsession',['startSession',['../interface_s_b_s_d_k_camera_session.html#a3cbc6fe27a0eb2b258050ec589368e9a',1,'SBSDKCameraSession']]],
  ['status',['status',['../interface_s_b_s_d_k_documents_detector_result.html#a674cc8385bb45f25c1609f159d7e1b84',1,'SBSDKDocumentsDetectorResult::status()'],['../interface_s_b_s_d_k_document_detector_result.html#a1058d10a89415b34b7811d46a8099e5f',1,'SBSDKDocumentDetectorResult::status()']]],
  ['stopsession',['stopSession',['../interface_s_b_s_d_k_camera_session.html#a68c3b52e8d9825b4ba7a87345d90d9c1',1,'SBSDKCameraSession']]],
  ['stringrepresentation',['stringRepresentation',['../interface_s_b_s_d_k_invoice_recognizer_result.html#abf91c9a68b36e38931a674fa0c514350',1,'SBSDKInvoiceRecognizerResult::stringRepresentation()'],['../interface_s_b_s_d_k_machine_readable_zone_recognizer_result.html#a640258ee13ed0258faa024f7986b40c5',1,'SBSDKMachineReadableZoneRecognizerResult::stringRepresentation()']]]
];
