{"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKBinarization@SBSDKBinarizationEnabledIfBinarizationFilterSet","role":"symbol","navigatorTitle":[{"text":"SBSDKBinarizationEnabledIfBinarizationFilterSet","kind":"identifier"}],"title":"SBSDKBinarization.enabledIfBinarizationFilterSet","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enabledIfBinarizationFilterSet"}]},"abstract":[{"type":"text","text":"Same behavior as ENABLED if a binarization filter (TIFFGeneratorParameters.binarizationFilter) is set,"},{"type":"text","text":" "},{"type":"text","text":"otherwise same behavior as DISABLED. This is the default."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabledIfBinarizationFilterSet"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbinarization\/enabledifbinarizationfilterset"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbinarization\/enabledifbinarizationfilterset"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarization"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarization\/enabledIfBinarizationFilterSet"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBinarization":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarization","role":"symbol","abstract":[{"text":"Binarization behavior to apply when adding pages to a TIFF.","type":"text"}],"title":"SBSDKBinarization","navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarization"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKBinarization","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbinarization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBinarization/enabledIfBinarizationFilterSet":{"abstract":[{"text":"Same behavior as ENABLED if a binarization filter (TIFFGeneratorParameters.binarizationFilter) is set,","type":"text"},{"type":"text","text":" "},{"text":"otherwise same behavior as DISABLED. This is the default.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbinarization\/enabledifbinarizationfilterset","type":"topic","kind":"symbol","title":"SBSDKBinarization.enabledIfBinarizationFilterSet","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabledIfBinarizationFilterSet"}],"navigatorTitle":[{"text":"SBSDKBinarizationEnabledIfBinarizationFilterSet","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarization\/enabledIfBinarizationFilterSet"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"SBSDKBinarizationEnabledIfBinarizationFilterSet","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKBinarizationEnabledIfBinarizationFilterSet","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKBinarizationEnabledIfBinarizationFilterSet"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"SBSDKBinarization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarization\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarization\/fragments","value":[{"text":"SBSDKBinarization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarization\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBinarization"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarization~1enabledIfBinarizationFilterSet\/title","value":"SBSDKBinarizationEnabledIfBinarizationFilterSet","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarization~1enabledIfBinarizationFilterSet\/fragments","value":[{"text":"SBSDKBinarizationEnabledIfBinarizationFilterSet","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}