{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/Scanbot\/setupDefaultLicenseFailureHandler(completion:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(setupDefaultLicenseFailureHandlerWithCompletion:) "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupDefaultLicenseFailureHandler"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> ())?)"}],"languages":["swift"]}]},{"parameters":[{"name":"completion","content":[{"inlineContent":[{"text":"An optional block being executed after the user pressed the OK-button in the alert.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/Scanbot"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"setupDefaultLicenseFailureHandlerWithCompletion:"}],"role":"symbol","symbolKind":"method","roleHeading":"Type Method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)Scanbot(cm)setupDefaultLicenseFailureHandlerWithCompletion:","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setupDefaultLicenseFailureHandler"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (() -> ())?)","kind":"text"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"setupDefaultLicenseFailureHandler(completion:)"},"kind":"symbol","abstract":[{"type":"text","text":"Sets up the default license failure handler which is being called when the license or trial time expired."},{"type":"text","text":" "},{"text":"The default handler shows an alert to inform your users about the expired license or trial period.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/scanbot\/setupdefaultlicensefailurehandler(completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/scanbot\/setupdefaultlicensefailurehandler(completion:)"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/Scanbot":{"title":"Scanbot","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/scanbot","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/Scanbot","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Scanbot","kind":"identifier"}],"abstract":[{"text":"Main class of Scanbot SDK. Lets you install the license and allows basic configuration.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"Scanbot","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/Scanbot/setupDefaultLicenseFailureHandler(completion:)":{"url":"\/documentation\/scanbotbarcodescannersdk\/scanbot\/setupdefaultlicensefailurehandler(completion:)","role":"symbol","title":"setupDefaultLicenseFailureHandler(completion:)","type":"topic","abstract":[{"text":"Sets up the default license failure handler which is being called when the license or trial time expired.","type":"text"},{"text":" ","type":"text"},{"text":"The default handler shows an alert to inform your users about the expired license or trial period.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (() -> ())?)","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/Scanbot\/setupDefaultLicenseFailureHandler(completion:)","navigatorTitle":[{"kind":"identifier","text":"setupDefaultLicenseFailureHandlerWithCompletion:"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"setupDefaultLicenseFailureHandlerWithCompletion:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"setupDefaultLicenseFailureHandlerWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setupDefaultLicenseFailureHandlerWithCompletion:"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")()) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"An optional block being executed after the user pressed the OK-button in the alert."}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1Scanbot\/title","value":"Scanbot","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1Scanbot\/fragments","value":[{"text":"Scanbot","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1Scanbot\/navigatorTitle","value":[{"kind":"identifier","text":"Scanbot"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1Scanbot~1setupDefaultLicenseFailureHandler(completion:)\/title","op":"replace","value":"setupDefaultLicenseFailureHandlerWithCompletion:"},{"value":[{"text":"+ ","kind":"text"},{"text":"setupDefaultLicenseFailureHandlerWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1Scanbot~1setupDefaultLicenseFailureHandler(completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}