{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewScreenConfiguration\/topBarMoreButton","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewScreenConfiguration"]]},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ReviewScreenConfiguration(py)topBarMoreButton","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarMoreButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2IconButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconButton"}],"navigatorTitle":[{"kind":"identifier","text":"topBarMoreButton"}],"title":"topBarMoreButton","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarMoreButton","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IconButton","text":"SBSDKUI2IconButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconButton"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewscreenconfiguration\/topbarmorebutton"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewscreenconfiguration\/topbarmorebutton"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Configuration of the ‘more’ button, located in the top bar."}],"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewScreenConfiguration":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewScreenConfiguration","abstract":[{"text":"Configuration of the screen for reviewing the scanned pages.","type":"text"}],"role":"symbol","title":"SBSDKUI2ReviewScreenConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewscreenconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ReviewScreenConfiguration"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ReviewScreenConfiguration"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewScreenConfiguration/topBarMoreButton":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewScreenConfiguration\/topBarMoreButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarMoreButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconButton"}],"title":"topBarMoreButton","kind":"symbol","abstract":[{"text":"Configuration of the ‘more’ button, located in the top bar.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewscreenconfiguration\/topbarmorebutton","role":"symbol","navigatorTitle":[{"text":"topBarMoreButton","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2IconButton":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2iconbutton","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2IconButton","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2IconButton","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IconButton","abstract":[{"type":"text","text":"Configuration of the icon appearance on a button."}],"title":"SBSDKUI2IconButton","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"topBarMoreButton","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"topBarMoreButton","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconButton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IconButton","text":"SBSDKUI2IconButton","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"topBarMoreButton","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUI2ReviewScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewScreenConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2ReviewScreenConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewScreenConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewScreenConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ReviewScreenConfiguration"}]},{"value":"topBarMoreButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewScreenConfiguration~1topBarMoreButton\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewScreenConfiguration~1topBarMoreButton\/fragments","value":[{"text":"topBarMoreButton","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IconButton\/title","value":"SBSDKUI2IconButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IconButton\/fragments","value":[{"text":"SBSDKUI2IconButton","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IconButton\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2IconButton"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}