{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"acknowledgment","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility\/acknowledgment\/retake","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility\/acknowledgment\/useScan"],"generated":true,"anchor":"Type-Properties"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneraccessibility\/acknowledgment"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility\/acknowledgment"},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"acknowledgment","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","roleHeading":"Class","symbolKind":"class","title":"SBSDKUI2DocumentScannerAccessibility.acknowledgment","externalID":"s:25ScanbotDocumentScannerSDK08SBSDKUI2bC13AccessibilityC14acknowledgmentC","navigatorTitle":[{"text":"acknowledgment","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerAccessibility/acknowledgment/retake":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retake","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility\/acknowledgment\/retake","type":"topic","title":"retake","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneraccessibility\/acknowledgment\/retake","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerAccessibility/acknowledgment/useScan":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"useScan"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneraccessibility\/acknowledgment\/usescan","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility\/acknowledgment\/useScan","title":"useScan"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerAccessibility":{"type":"topic","role":"symbol","title":"SBSDKUI2DocumentScannerAccessibility","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerAccessibility"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerAccessibility"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneraccessibility","abstract":[{"type":"text","text":"Accessibility identifiers to be used in UI tests for the document scanner RTU-UI V2."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerAccessibility/acknowledgment":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneraccessibility\/acknowledgment","abstract":[],"role":"symbol","title":"SBSDKUI2DocumentScannerAccessibility.acknowledgment","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerAccessibility\/acknowledgment","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"acknowledgment"}],"navigatorTitle":[{"kind":"identifier","text":"acknowledgment"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2DocumentScannerAccessibility","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerAccessibility\/title"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentScannerAccessibility","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerAccessibility\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentScannerAccessibility","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerAccessibility\/navigatorTitle"}]}]}