{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerviewcontroller\/didfinish"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewController\/didFinish","interfaceLanguage":"occ"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"didFinish"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"didFinish","kind":"identifier"}],"navigatorTitle":[{"text":"didFinish","kind":"identifier"}],"title":"didFinish","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerViewController(im)didFinish","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerviewcontroller","role":"symbol","kind":"symbol","title":"SBSDKUIFinderDocumentScannerViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewController","navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}],"abstract":[{"text":"A highly customizable camera-based view controller to scan a single documents of a certain aspect ratio.","type":"text"}],"type":"topic","deprecated":true},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerViewController/didFinish":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerviewcontroller\/didfinish","title":"didFinish","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerViewController\/didFinish","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFinish"}],"navigatorTitle":[{"kind":"identifier","text":"didFinish"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerViewController\/title","value":"SBSDKUIFinderDocumentScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerViewController\/fragments","value":[{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}