{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isViewFinderEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration\/isViewFinderEnabled","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":" to enable and display the region of interest, to "},{"type":"codeVoice","code":"False"},{"type":"text","text":" otherwise."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerbehaviorconfiguration\/isviewfinderenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerbehaviorconfiguration\/isviewfinderenabled"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"ScanbotSDK"}],"platforms":[],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerBehaviorConfiguration(py)isViewFinderEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isViewFinderEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property","role":"symbol","title":"isViewFinderEnabled","navigatorTitle":[{"text":"isViewFinderEnabled","kind":"identifier"}]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerBehaviorConfiguration/isViewFinderEnabled":{"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerbehaviorconfiguration\/isviewfinderenabled","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration\/isViewFinderEnabled","title":"isViewFinderEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isViewFinderEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set to "},{"code":"True","type":"codeVoice"},{"type":"text","text":" to enable and display the region of interest, to "},{"code":"False","type":"codeVoice"},{"type":"text","text":" otherwise."}],"navigatorTitle":[{"kind":"identifier","text":"isViewFinderEnabled"}],"type":"topic","role":"symbol","kind":"symbol","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerBehaviorConfiguration":{"title":"SBSDKUIBarcodeScannerBehaviorConfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodeScannerBehaviorConfiguration"}],"type":"topic","abstract":[{"type":"text","text":"The configuration for the behavior of the RTU-UI barcode scanner."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerBehaviorConfiguration"}],"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerbehaviorconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"isViewFinderEnabled","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"isViewFinderEnabled","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isViewFinderEnabled"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"isViewFinderEnabled","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration~1isViewFinderEnabled\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isViewFinderEnabled"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration~1isViewFinderEnabled\/fragments"},{"value":"SBSDKUIBarcodeScannerBehaviorConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerBehaviorConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration\/fragments"},{"value":[{"text":"SBSDKUIBarcodeScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}