{"metadata":{"symbolKind":"case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Case","role":"symbol","title":"SBSDKUIBarcodesExtensionFilter.onlyWithoutExtensions","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUIBarcodesExtensionFilter@SBSDKUIBarcodesExtensionFilterOnlyWithoutExtensions","navigatorTitle":[{"text":"SBSDKUIBarcodesExtensionFilterOnlyWithoutExtensions","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onlyWithoutExtensions"}]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesExtensionFilter\/onlyWithoutExtensions"},"abstract":[{"type":"text","text":"Only EAN and UPC barcoded without extensions will be returned."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesExtensionFilter"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"onlyWithoutExtensions","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesextensionfilter\/onlywithoutextensions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesextensionfilter\/onlywithoutextensions"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesExtensionFilter/onlyWithoutExtensions":{"abstract":[{"text":"Only EAN and UPC barcoded without extensions will be returned.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesextensionfilter\/onlywithoutextensions","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onlyWithoutExtensions"}],"title":"SBSDKUIBarcodesExtensionFilter.onlyWithoutExtensions","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesExtensionFilter\/onlyWithoutExtensions","navigatorTitle":[{"text":"SBSDKUIBarcodesExtensionFilterOnlyWithoutExtensions","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesExtensionFilter":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilter"}],"title":"SBSDKUIBarcodesExtensionFilter","type":"topic","abstract":[{"text":"Filter for extended EAN and UPC barcodes.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesextensionfilter","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesExtensionFilter","navigatorTitle":[{"text":"SBSDKUIBarcodesExtensionFilter","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKUIBarcodesExtensionFilterOnlyWithoutExtensions","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"SBSDKUIBarcodesExtensionFilterOnlyWithoutExtensions","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilterOnlyWithoutExtensions"}]}]},"op":"replace"},{"value":"SBSDKUIBarcodesExtensionFilterOnlyWithoutExtensions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesExtensionFilter~1onlyWithoutExtensions\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesExtensionFilter~1onlyWithoutExtensions\/fragments","op":"replace","value":[{"text":"SBSDKUIBarcodesExtensionFilterOnlyWithoutExtensions","kind":"identifier"}]},{"value":"SBSDKUIBarcodesExtensionFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesExtensionFilter\/title"},{"value":[{"text":"SBSDKUIBarcodesExtensionFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesExtensionFilter\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesExtensionFilter\/navigatorTitle"}]}]}