{"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier","text":"_NSZone"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/copyWithZone:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickBadgeConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2findandpickbadgeconfiguration\/copywithzone:"]}],"kind":"symbol","sections":[],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FindAndPickBadgeConfiguration(im)copyWithZone:","title":"copyWithZone:","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickBadgeConfiguration/copyWithZone:":{"title":"copyWithZone:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickbadgeconfiguration\/copywithzone:","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickBadgeConfiguration":{"title":"SBSDKUI2FindAndPickBadgeConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickbadgeconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2FindAndPickBadgeConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Configuration of the round badge on find and pick ar layer.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickBadgeConfiguration","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/title","value":"SBSDKUI2FindAndPickBadgeConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2FindAndPickBadgeConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/navigatorTitle","op":"replace"}]}]}