{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"copyWithZone:","kind":"identifier"},{"kind":"text","text":"("},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone","text":"_NSZone"},{"kind":"text","text":" *) "},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonconfiguration\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Method","title":"copyWithZone:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCommonConfiguration(im)copyWithZone:"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonConfiguration\/copyWithZone:","interfaceLanguage":"occ"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonConfiguration"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonConfiguration":{"navigatorTitle":[{"text":"SBSDKBarcodeFormatCommonConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Convenience configuration for enabling the scanning of multiple barcode formats with a common configuration.","type":"text"},{"type":"text","text":" "},{"text":"Add to scanner configuration to enable and configure the scanning of multiple barcodes.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeFormatCommonConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonConfiguration","title":"SBSDKBarcodeFormatCommonConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonConfiguration/copyWithZone:":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonconfiguration\/copywithzone:","type":"topic","title":"copyWithZone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonConfiguration\/copyWithZone:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKBarcodeFormatCommonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}