{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ShutterButton\/initWithEnabledInAutoSnappingMode:accessibilityDescription:outerColor:innerColor:","interfaceLanguage":"occ"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ShutterButton(im)initWithEnabledInAutoSnappingMode:accessibilityDescription:outerColor:innerColor:","title":"initWithEnabledInAutoSnappingMode:accessibilityDescription:outerColor:innerColor:","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEnabledInAutoSnappingMode:accessibilityDescription:outerColor:innerColor:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithEnabledInAutoSnappingMode:accessibilityDescription:outerColor:innerColor:"}],"modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ShutterButton"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithEnabledInAutoSnappingMode:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"enabledInAutoSnappingMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescription:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescription","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outerColor:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"outerColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"innerColor:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"innerColor","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2shutterbutton\/initwithenabledinautosnappingmode:accessibilitydescription:outercolor:innercolor:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ShutterButton/initWithEnabledInAutoSnappingMode:accessibilityDescription:outerColor:innerColor:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2shutterbutton\/initwithenabledinautosnappingmode:accessibilitydescription:outercolor:innercolor:","navigatorTitle":[{"text":"initWithEnabledInAutoSnappingMode:accessibilityDescription:outerColor:innerColor:","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","title":"initWithEnabledInAutoSnappingMode:accessibilityDescription:outerColor:innerColor:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ShutterButton\/initWithEnabledInAutoSnappingMode:accessibilityDescription:outerColor:innerColor:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithEnabledInAutoSnappingMode:accessibilityDescription:outerColor:innerColor:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ShutterButton":{"url":"\/documentation\/scanbotsdk\/sbsdkui2shutterbutton","title":"SBSDKUI2ShutterButton","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ShutterButton","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ShutterButton","navigatorTitle":[{"text":"SBSDKUI2ShutterButton","kind":"identifier"}],"abstract":[{"text":"Configuration of the ‘shutter’ button.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"role":"symbol","title":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2color","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2ShutterButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ShutterButton\/title"},{"op":"replace","value":[{"text":"SBSDKUI2ShutterButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ShutterButton\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2ShutterButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ShutterButton\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2Color","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}