{"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"initWithFrame:","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKZoomingImageScrollView(im)initWithFrame:","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"symbolKind":"method"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"frame","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview\/initwithframe:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView\/initWithFrame:","interfaceLanguage":"occ"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKZoomingImageScrollView":{"abstract":[{"text":"A scrollable and zoomable ","type":"text"},{"type":"codeVoice","code":"UIScrollView"},{"type":"text","text":" subclass that displays images and an overlay view."}],"url":"\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview","type":"topic","kind":"symbol","role":"symbol","title":"SBSDKZoomingImageScrollView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKZoomingImageScrollView/initWithFrame:":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview\/initwithframe:","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"title":"initWithFrame:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView\/initWithFrame:","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKZoomingImageScrollView","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView\/fragments","value":[{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView\/navigatorTitle","value":[{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}],"op":"replace"}]}]}