{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview\/scrollviewdidendzooming(_:with:atscale:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview\/scrollviewdidendzooming(_:with:atscale:)"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView\/scrollViewDidEndZooming(_:with:atScale:)","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UIScrollViewDelegate.scrollViewDidEndZooming(_:with:atScale:)","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"extendedModule":"ScanbotSDK","roleHeading":"Instance Method","title":"scrollViewDidEndZooming(_:with:atScale:)","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollViewDidEndZooming","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"atScale","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"text":"scrollViewDidEndZooming:withView:atScale:","kind":"identifier"}],"externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKZoomingImageScrollView(im)scrollViewDidEndZooming:withView:atScale:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView\/UIScrollViewDelegate-Implementations"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndZooming"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView","text":"UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"atScale"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKZoomingImageScrollView/scrollViewDidEndZooming(_:with:atScale:)":{"title":"scrollViewDidEndZooming(_:with:atScale:)","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview\/scrollviewdidendzooming(_:with:atscale:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollViewDidEndZooming","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"atScale","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"scrollViewDidEndZooming:withView:atScale:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView\/scrollViewDidEndZooming(_:with:atScale:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKZoomingImageScrollView/UIScrollViewDelegate-Implementations":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview\/uiscrollviewdelegate-implementations","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView\/UIScrollViewDelegate-Implementations","kind":"article","type":"topic","title":"UIScrollViewDelegate Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKZoomingImageScrollView":{"abstract":[{"text":"A scrollable and zoomable ","type":"text"},{"type":"codeVoice","code":"UIScrollView"},{"type":"text","text":" subclass that displays images and an overlay view."}],"url":"\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview","type":"topic","kind":"symbol","role":"symbol","title":"SBSDKZoomingImageScrollView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"scrollViewDidEndZooming:withView:atScale:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndZooming:withView:atScale:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"scrollViewDidEndZooming:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":" "},{"kind":"identifier","text":"withView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"view"},{"kind":"text","text":" "},{"kind":"identifier","text":"atScale:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"scale"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView~1scrollViewDidEndZooming(_:with:atScale:)\/title","value":"scrollViewDidEndZooming:withView:atScale:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView~1scrollViewDidEndZooming(_:with:atScale:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scrollViewDidEndZooming:withView:atScale:","kind":"identifier"}]},{"op":"replace","value":"SBSDKZoomingImageScrollView","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView\/navigatorTitle"}]}]}