{"metadata":{"title":"init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackingOverlayConfiguration(im)init","symbolKind":"method","role":"symbol","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayConfiguration\/init","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayConfiguration"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlayconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackingOverlayController":{"kind":"symbol","title":"SBSDKBarcodeTrackingOverlayController","abstract":[{"type":"text","text":"A class that represents an overlay used for visualizing detected barcodes."},{"text":" ","type":"text"},{"type":"text","text":"It provides a customizable user interface for displaying barcodes and supports interaction with them."},{"text":" ","type":"text"},{"type":"text","text":"The overlay can be used to highlight and select barcodes based on user input."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlaycontroller","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.1"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackingOverlayConfiguration":{"type":"topic","title":"SBSDKBarcodeTrackingOverlayConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayConfiguration","abstract":[{"text":"A class that represents the configuration options for a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This overlay is used to visualize the detected barcodes on the screen."},{"text":" ","type":"text"},{"text":"The class provides various customization options for the appearance and behavior of the overlay.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlayconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackingOverlayConfiguration/init":{"title":"init","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlayconfiguration\/init","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayConfiguration\/init","abstract":[],"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKBarcodeTrackingOverlayController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}]},{"value":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayConfiguration\/title","value":"SBSDKBarcodeTrackingOverlayConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayConfiguration\/fragments","value":[{"text":"SBSDKBarcodeTrackingOverlayConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeTrackingOverlayConfiguration","kind":"identifier"}]}]}]}