{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"auto","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Select to the image resolution automatically based on device specifics."}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution\/auto"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution\/auto"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKCameraLiveScannerResolution@SBSDKCameraLiveScannerResolutionAuto","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"auto"}],"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"SBSDKCameraLiveScannerResolutionAuto","kind":"identifier"}],"title":"SBSDKCameraLiveScannerResolution.auto"},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/auto","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraLiveScannerResolution":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution","navigatorTitle":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"title":"SBSDKCameraLiveScannerResolution","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution","abstract":[{"text":"The size of the image from camera which would be sent to the scanner for live scanning.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraLiveScannerResolution/auto":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"auto"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolutionAuto"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution\/auto","abstract":[{"type":"text","text":"Select to the image resolution automatically based on device specifics."}],"title":"SBSDKCameraLiveScannerResolution.auto","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/auto"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKCameraLiveScannerResolutionAuto"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKCameraLiveScannerResolutionAuto","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolutionAuto"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKCameraLiveScannerResolution","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolution"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution\/fragments"},{"op":"replace","value":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution\/navigatorTitle"},{"op":"replace","value":"SBSDKCameraLiveScannerResolutionAuto","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution~1auto\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolutionAuto"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution~1auto\/fragments"}]}]}