{"abstract":[{"type":"text","text":"The image is in Full HD resolution. 1920x1080 pixels or close to it."}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/fullHd","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullHd","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution\/fullhd"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution\/fullhd"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullHd","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKCameraLiveScannerResolution@SBSDKCameraLiveScannerResolutionFullHd","title":"SBSDKCameraLiveScannerResolution.fullHd","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolutionFullHd"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraLiveScannerResolution/fullHd":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution\/fullhd","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/fullHd","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullHd","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCameraLiveScannerResolutionFullHd","kind":"identifier"}],"abstract":[{"text":"The image is in Full HD resolution. 1920x1080 pixels or close to it.","type":"text"}],"title":"SBSDKCameraLiveScannerResolution.fullHd"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraLiveScannerResolution":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution","title":"SBSDKCameraLiveScannerResolution","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"abstract":[{"text":"The size of the image from camera which would be sent to the scanner for live scanning.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKCameraLiveScannerResolutionFullHd"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolutionFullHd"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKCameraLiveScannerResolutionFullHd","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution~1fullHd\/title","op":"replace","value":"SBSDKCameraLiveScannerResolutionFullHd"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution~1fullHd\/fragments","op":"replace","value":[{"text":"SBSDKCameraLiveScannerResolutionFullHd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution\/title","op":"replace","value":"SBSDKCameraLiveScannerResolution"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolution"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolution"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}