{"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKCameraLiveScannerResolution@SBSDKCameraLiveScannerResolutionUhd","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"uhd"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","title":"SBSDKCameraLiveScannerResolution.uhd","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolutionUhd"}]},"abstract":[{"type":"text","text":"The image is in UHD resolution. 3840x2160 pixels or close to it."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uhd","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution\/uhd"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution\/uhd"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/uhd"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraLiveScannerResolution/uhd":{"title":"SBSDKCameraLiveScannerResolution.uhd","abstract":[{"type":"text","text":"The image is in UHD resolution. 3840x2160 pixels or close to it."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/uhd","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uhd","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution\/uhd","navigatorTitle":[{"text":"SBSDKCameraLiveScannerResolutionUhd","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraLiveScannerResolution":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution","title":"SBSDKCameraLiveScannerResolution","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"abstract":[{"text":"The size of the image from camera which would be sent to the scanner for live scanning.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKCameraLiveScannerResolutionUhd","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKCameraLiveScannerResolutionUhd","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolutionUhd"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution~1uhd\/title","value":"SBSDKCameraLiveScannerResolutionUhd","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution~1uhd\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolutionUhd"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution\/title","value":"SBSDKCameraLiveScannerResolution","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution\/fragments","value":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution\/navigatorTitle","value":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}