{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkprocessingmode\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Initializer","title":"init(rawValue:)","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"s:10ScanbotSDK19SBSDKProcessingModeO8rawValueACSgSi_tcfc"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode\/init(rawValue:)"},"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessingMode":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Scanners typically can produce better results from a single image if they are allowed to spend a longer time analyzing it."},{"type":"text","text":" "},{"type":"text","text":"On the other hand, scanners can produce even better results if they can analyze multiple images of the same subject and cross-check and combine the results."},{"type":"text","text":" "},{"type":"text","text":"The processing mode tells the scanner whether to optimize for single or multiple images of a subject."}],"navigatorTitle":[{"text":"SBSDKProcessingMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProcessingMode","kind":"identifier"}],"title":"SBSDKProcessingMode","url":"\/documentation\/scanbotsdk\/sbsdkprocessingmode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessingMode/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkprocessingmode\/init(rawvalue:)","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode\/init(rawValue:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/title","op":"replace","value":"SBSDKProcessingMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/fragments","op":"replace","value":[{"text":"SBSDKProcessingMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKProcessingMode"}]}]}]}