{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/disabled"},"abstract":[{"type":"text","text":"Auto-snapping and user guidance are disabled."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkautosnappingmode\/disabled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkautosnappingmode\/disabled"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disabled"}]}]}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKAutoSnappingModeDisabled"}],"roleHeading":"Case","title":"SBSDKAutoSnappingMode.disabled","symbolKind":"case","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"disabled","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKAutoSnappingMode@SBSDKAutoSnappingModeDisabled"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAutoSnappingMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode","url":"\/documentation\/scanbotsdk\/sbsdkautosnappingmode","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKAutoSnappingMode","kind":"identifier"}],"abstract":[{"text":"The Auto-snapping mode handles different auto-snap scenarios.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKAutoSnappingMode"}],"title":"SBSDKAutoSnappingMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAutoSnappingMode/disabled":{"kind":"symbol","title":"SBSDKAutoSnappingMode.disabled","url":"\/documentation\/scanbotsdk\/sbsdkautosnappingmode\/disabled","navigatorTitle":[{"text":"SBSDKAutoSnappingModeDisabled","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}],"type":"topic","abstract":[{"type":"text","text":"Auto-snapping and user guidance are disabled."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/disabled","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"SBSDKAutoSnappingModeDisabled","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKAutoSnappingModeDisabled"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKAutoSnappingModeDisabled","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode\/title","value":"SBSDKAutoSnappingMode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode\/fragments","value":[{"kind":"identifier","text":"SBSDKAutoSnappingMode"}]},{"value":[{"kind":"identifier","text":"SBSDKAutoSnappingMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode~1disabled\/title","op":"replace","value":"SBSDKAutoSnappingModeDisabled"},{"value":[{"text":"SBSDKAutoSnappingModeDisabled","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode~1disabled\/fragments","op":"replace"}]}]}