{"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ForegroundStyle\/hash"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ForegroundStyle"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2foregroundstyle\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","title":"hash","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ForegroundStyle(py)hash","fragments":[{"text":"hash","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ForegroundStyle/hash":{"kind":"symbol","abstract":[],"role":"symbol","title":"hash","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ForegroundStyle\/hash","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2foregroundstyle\/hash","type":"topic","fragments":[{"kind":"identifier","text":"hash"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ForegroundStyle":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2foregroundstyle","abstract":[{"type":"text","text":"Configuration of the appearance of foreground elements (e.g. text and\/or icons on buttons, etc)."}],"type":"topic","title":"SBSDKUI2ForegroundStyle","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2ForegroundStyle","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ForegroundStyle"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ForegroundStyle"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2ForegroundStyle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ForegroundStyle\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ForegroundStyle\/fragments","value":[{"text":"SBSDKUI2ForegroundStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ForegroundStyle\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ForegroundStyle"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}