{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagemetadata\/digitalizationdate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimagemetadata\/digitalizationdate"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"digitalizationDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"digitalizationDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"digitalizationDate"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageMetadata(py)digitalizationDate","title":"digitalizationDate"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata"]]},"abstract":[{"type":"text","text":"The date of when the image was digitized."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/digitalizationDate"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadataProcessor":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadataProcessor","url":"\/documentation\/scanbotsdk\/sbsdkimagemetadataprocessor","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}],"title":"SBSDKImageMetadataProcessor","kind":"symbol","abstract":[{"type":"text","text":"Helper class to extract or inject image metadata, e.g. EXIF, TIFF, JFIF from  image data."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata":{"title":"SBSDKImageMetadata","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageMetadata"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata","abstract":[{"type":"text","text":"Encapsulates image metadata, e.g. EXIF, TIFF, JFIF in a convenient way."},{"type":"text","text":" "},{"type":"text","text":"Use "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadataProcessor","isActive":true,"type":"reference"},{"type":"text","text":" to extract metadata from and inject changed metadata into image data."}],"url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageMetadata","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/digitalizationDate":{"title":"digitalizationDate","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"digitalizationDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/digitalizationDate","url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/digitalizationdate","navigatorTitle":[{"kind":"identifier","text":"digitalizationDate"}],"type":"topic","abstract":[{"type":"text","text":"The date of when the image was digitized."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"digitalizationDate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"digitalizationDate","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSDate","kind":"typeIdentifier","text":"NSDate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"digitalizationDate"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadataProcessor\/title","value":"SBSDKImageMetadataProcessor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadataProcessor\/fragments","value":[{"kind":"identifier","text":"SBSDKImageMetadataProcessor"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadataProcessor\/navigatorTitle","value":[{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata\/title","value":"SBSDKImageMetadata"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata\/fragments","value":[{"text":"SBSDKImageMetadata","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata\/navigatorTitle","value":[{"text":"SBSDKImageMetadata","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1digitalizationDate\/title","value":"digitalizationDate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1digitalizationDate\/fragments","value":[{"kind":"identifier","text":"digitalizationDate"}]}]}]}