{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A document was detected, but not all of its corners are visible and the document is too close to the camera."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/errorpartiallyvisibletooclose"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/errorpartiallyvisibletooclose"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/errorPartiallyVisibleTooClose","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorPartiallyVisibleTooClose"}],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusErrorPartiallyVisibleTooClose"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorPartiallyVisibleTooClose"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKDocumentDetectionStatus.errorPartiallyVisibleTooClose","roleHeading":"Case","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectionStatus@SBSDKDocumentDetectionStatusErrorPartiallyVisibleTooClose"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Status of the document detection.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus","title":"SBSDKDocumentDetectionStatus","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/errorPartiallyVisibleTooClose":{"title":"SBSDKDocumentDetectionStatus.errorPartiallyVisibleTooClose","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorPartiallyVisibleTooClose"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusErrorPartiallyVisibleTooClose"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/errorpartiallyvisibletooclose","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/errorPartiallyVisibleTooClose","abstract":[{"type":"text","text":"A document was detected, but not all of its corners are visible and the document is too close to the camera."}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKDocumentDetectionStatusErrorPartiallyVisibleTooClose","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKDocumentDetectionStatusErrorPartiallyVisibleTooClose","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKDocumentDetectionStatusErrorPartiallyVisibleTooClose","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/title","value":"SBSDKDocumentDetectionStatus","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/fragments","value":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1errorPartiallyVisibleTooClose\/title","value":"SBSDKDocumentDetectionStatusErrorPartiallyVisibleTooClose","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1errorPartiallyVisibleTooClose\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusErrorPartiallyVisibleTooClose"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}