{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"structuredAppendInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo","text":"SBSDKStructuredAppendInfo","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStructuredAppendInfo"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeitem\/structuredappendinfo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeitem\/structuredappendinfo"]}],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"structuredAppendInfo","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","title":"structuredAppendInfo","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem(py)structuredAppendInfo","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"structuredAppendInfo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKStructuredAppendInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStructuredAppendInfo"},{"text":"?","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem"]]},"sections":[],"abstract":[{"text":"If this barcode is part of a structured append sequence, this field contains information about the sequence.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem\/structuredAppendInfo","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeItem":{"abstract":[{"type":"text","text":"A single barcode found in the input image. Barcodes with the same content but different locations in the image are considered separate barcodes."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeitem","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeItem","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeItem","kind":"identifier"}],"type":"topic","title":"SBSDKBarcodeItem","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeItem/structuredAppendInfo":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeitem\/structuredappendinfo","title":"structuredAppendInfo","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem\/structuredAppendInfo","navigatorTitle":[{"kind":"identifier","text":"structuredAppendInfo"}],"abstract":[{"text":"If this barcode is part of a structured append sequence, this field contains information about the sequence.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"structuredAppendInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStructuredAppendInfo","text":"SBSDKStructuredAppendInfo"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStructuredAppendInfo":{"url":"\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo","navigatorTitle":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"title":"SBSDKStructuredAppendInfo","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"type":"topic","abstract":[{"text":"The structured append mode can be used to split a message across multiple barcodes.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"structuredAppendInfo","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"structuredAppendInfo","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStructuredAppendInfo","text":"SBSDKStructuredAppendInfo","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo"},{"text":" * ","kind":"text"},{"text":"structuredAppendInfo","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/title","op":"replace","value":"SBSDKBarcodeItem"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem~1structuredAppendInfo\/title","op":"replace","value":"structuredAppendInfo"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem~1structuredAppendInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"structuredAppendInfo"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/title","op":"replace","value":"SBSDKStructuredAppendInfo"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/fragments","op":"replace","value":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/navigatorTitle","value":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}]}]}]}