{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDisplacement\/upperLeft","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDisplacement"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"upperLeft","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"upperLeft"}],"navigatorTitle":[{"text":"SBSDKDocumentDisplacementUpperLeft","kind":"identifier"}],"title":"SBSDKDocumentDisplacement.upperLeft","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentDisplacement@SBSDKDocumentDisplacementUpperLeft"},"abstract":[{"text":"The document is partially visible. Move the camera up and to the left to capture the full document.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdisplacement\/upperleft"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdisplacement\/upperleft"]}],"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 8.0.4","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDisplacement/upperLeft":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdisplacement\/upperleft","title":"SBSDKDocumentDisplacement.upperLeft","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDisplacement\/upperLeft","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"upperLeft"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDisplacementUpperLeft"}],"abstract":[{"text":"The document is partially visible. Move the camera up and to the left to capture the full document.","type":"text"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDisplacement":{"abstract":[{"text":"The direction towards the center of the document if the document is partially visible.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdisplacement","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDisplacement"}],"type":"topic","title":"SBSDKDocumentDisplacement","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDisplacement","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDisplacement"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKDocumentDisplacementUpperLeft","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDisplacementUpperLeft"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"SBSDKDocumentDisplacementUpperLeft","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKDocumentDisplacementUpperLeft","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDisplacement~1upperLeft\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDisplacementUpperLeft"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDisplacement~1upperLeft\/fragments","op":"replace"},{"value":"SBSDKDocumentDisplacement","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDisplacement\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentDisplacement","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDisplacement\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDisplacement"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDisplacement\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}