{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmationSheetEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2singlescanningmode\/confirmationsheetenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2singlescanningmode\/confirmationsheetenabled"]}],"metadata":{"symbolKind":"property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SingleScanningMode(py)confirmationSheetEnabled","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"confirmationSheetEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"confirmationSheetEnabled","kind":"identifier"}],"title":"confirmationSheetEnabled"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SingleScanningMode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SingleScanningMode\/confirmationSheetEnabled"},"abstract":[{"type":"text","text":"If enabled, the confirmation sheet will be shown after the barcode has been scanned."},{"text":" ","type":"text"},{"text":"Default is false","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SingleScanningMode/confirmationSheetEnabled":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2singlescanningmode\/confirmationsheetenabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmationSheetEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"confirmationSheetEnabled","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SingleScanningMode\/confirmationSheetEnabled","title":"confirmationSheetEnabled","kind":"symbol","abstract":[{"text":"If enabled, the confirmation sheet will be shown after the barcode has been scanned.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is false"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SingleScanningMode":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2SingleScanningMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2singlescanningmode","navigatorTitle":[{"text":"SBSDKUI2SingleScanningMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the single barcode scanning mode."}],"role":"symbol","kind":"symbol","type":"topic","title":"SBSDKUI2SingleScanningMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SingleScanningMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"confirmationSheetEnabled","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"confirmationSheetEnabled"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"confirmationSheetEnabled","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SingleScanningMode~1confirmationSheetEnabled\/title","op":"replace","value":"confirmationSheetEnabled"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SingleScanningMode~1confirmationSheetEnabled\/fragments","op":"replace","value":[{"text":"confirmationSheetEnabled","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SingleScanningMode\/title","value":"SBSDKUI2SingleScanningMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SingleScanningMode\/fragments","value":[{"text":"SBSDKUI2SingleScanningMode","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKUI2SingleScanningMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SingleScanningMode\/navigatorTitle"}]}]}