{"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","roleHeading":"Type Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SingleScanningMode(cm)fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"role":"symbol","title":"fromJsonWithJson:"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2singlescanningmode\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SingleScanningMode\/fromJsonWithJson:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SingleScanningMode"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2SingleScanningMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SingleScanningMode","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SingleScanningMode"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SingleScanningMode/fromJsonWithJson:":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2singlescanningmode\/fromjsonwithjson:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SingleScanningMode\/fromJsonWithJson:","type":"topic","title":"fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"text":"fromJsonWithJson:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SingleScanningMode":{"abstract":[{"text":"Configuration of the single barcode scanning mode.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2singlescanningmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SingleScanningMode","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2SingleScanningMode"}],"title":"SBSDKUI2SingleScanningMode","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SingleScanningMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2SingleScanningMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SingleScanningMode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SingleScanningMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2SingleScanningMode"}]},{"value":[{"text":"SBSDKUI2SingleScanningMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SingleScanningMode\/navigatorTitle"}]}]}