{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"confirmationSheetEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"barcodeImageVisible"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = true, ","kind":"text"},{"kind":"externalParam","text":"sheetColor"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"kind":"text","text":" = SBSDKUI2Color(colorString: \"?sbColorSurface\", isArgb: false), "},{"text":"dividerColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"text":" = SBSDKUI2Color(colorString: \"?sbColorOutline\", isArgb: false), ","kind":"text"},{"text":"modalOverlayColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":" = SBSDKUI2Color(colorString: \"?sbColorModalOverlay\", isArgb: false), ","kind":"text"},{"text":"barcodeTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText"},{"text":" = SBSDKUI2StyledText(text: \"BARCODE_TITLE\",\n                                                                      color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                           isArgb: false)), ","kind":"text"},{"text":"barcodeSubtitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2StyledText(text: \"BARCODE_SUBTITLE\",\n                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                              isArgb: false)), "},{"kind":"externalParam","text":"submitButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" = SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                        text: \"?sheetSubmitButton\",\n                                                                                        background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                       isArgb: false),\n                                                                                                                            fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                     isArgb: false),\n                                                                                                                            strokeWidth: 1.0),\n                                                                                        foreground: SBSDKUI2ForegroundStyle(iconVisible: true,\n                                                                                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                 isArgb: false))), "},{"text":"cancelButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" = SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                        text: \"?singleModeConfirmationCancelButton\",\n                                                                                        background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                       isArgb: false),\n                                                                                                                            fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                     isArgb: false),\n                                                                                                                            strokeWidth: 1.0),\n                                                                                        foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                            color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                 isArgb: false))), "},{"text":"barcodeInfoMapping","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeInfoMapping","text":"SBSDKUI2BarcodeInfoMapping","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping"},{"kind":"text","text":" = SBSDKUI2BarcodeInfoMapping(sheetColor: SBSDKUI2Color(colorString: \"?sbColorSurface\", isArgb: false),\n                                               dividerColor: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                           isArgb: false),\n                                               modalOverlayColor: SBSDKUI2Color(colorString: \"?sbColorModalOverlay\",\n                                                                                isArgb: false),\n                                               loadingMessage: SBSDKUI2StyledText(text: \"?barcodeInfoMappingLoadingMessage\",\n                                                                                  color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                       isArgb: false)),\n                                               errorState: SBSDKUI2BarcodeItemErrorState(title: SBSDKUI2StyledText(text: \"?barcodeInfoMappingErrorStateTitle\",\n                                                                                                                   color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                        isArgb: false)),\n                                                                                         subtitle: SBSDKUI2StyledText(text: \"?barcodeInfoMappingErrorStateSubtitle\",\n                                                                                                                      color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                                                           isArgb: false)),\n                                                                                         retryButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                                                                  text: \"?barcodeInfoMappingErrorStateRetryButton\",\n                                                                                                                                  background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                                                                 isArgb: false),\n                                                                                                                                                                      fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                                                               isArgb: false),\n                                                                                                                                                                      strokeWidth: 1.0),\n                                                                                                                                  foreground: SBSDKUI2ForegroundStyle(iconVisible: true,\n                                                                                                                                                                      color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                                                           isArgb: false))),\n                                                                                         cancelButton: SBSDKUI2ButtonConfiguration(text: \"?barcodeInfoMappingErrorStateCancelButton\",\n                                                                                                                                   background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                                  isArgb: false),\n                                                                                                                                                                       fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                                isArgb: false),\n                                                                                                                                                                       strokeWidth: 1.0),\n                                                                                                                                   foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                                                                       color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                                                            isArgb: false))))), "},{"kind":"externalParam","text":"arOverlay"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration","text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration"},{"text":" = SBSDKUI2ArOverlayGeneralConfiguration(visible: false,\n                                                                                                         counterBadge: SBSDKUI2BadgeStyle(visible: true,\n                                                                                                                                          background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#000000FF\",\n                                                                                                                                                                                                         isArgb: false),\n                                                                                                                                                                              fillColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                                                                                                       isArgb: false),\n                                                                                                                                                                              strokeWidth: 0.0),\n                                                                                                                                          foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                                                         isArgb: false)),\n                                                                                                         automaticSelectionEnabled: false,\n                                                                                                         barcodeItemInfoPosition: SBSDKUI2BarcodeItemInfoPosition\n                                                                                                             .below,\n                                                                                                         polygon: SBSDKUI2ArOverlayPolygonConfiguration(visible: true,\n                                                                                                                                                        deselected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                                                                                                                    isArgb: false),\n                                                                                                                                                                                         fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                                                  isArgb: false),\n                                                                                                                                                                                         strokeWidth: 3.0,\n                                                                                                                                                                                         cornerRadius: 5.0),\n                                                                                                                                                        selected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                                                                                                                  isArgb: false),\n                                                                                                                                                                                       fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                                                isArgb: false),\n                                                                                                                                                                                       strokeWidth: 3.0,\n                                                                                                                                                                                       cornerRadius: 5.0)),\n                                                                                                         barcodeItemConfiguration: SBSDKUI2BarcodeItemConfiguration(imageVisible: true,\n                                                                                                                                                                    titleSelected: SBSDKUI2StyledText(text: \"BARCODE_TITLE\",\n                                                                                                                                                                                                      color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                                                                                                           isArgb: false)),\n                                                                                                                                                                    subtitleSelected: SBSDKUI2StyledText(text: \"BARCODE_SUBTITLE\",\n                                                                                                                                                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                                                                                                                                              isArgb: false)),\n                                                                                                                                                                    titleDeselected: SBSDKUI2StyledText(text: \"BARCODE_TITLE\",\n                                                                                                                                                                                                        color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                                                                                                             isArgb: false)),\n                                                                                                                                                                    subtitleDeselected: SBSDKUI2StyledText(visible: true,\n                                                                                                                                                                                                           text: \"BARCODE_SUBTITLE\",\n                                                                                                                                                                                                           color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                                                                                                                                                isArgb: false),\n                                                                                                                                                                                                           useShadow: false),\n                                                                                                                                                                    backgroundSelected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                                                                                                                                        isArgb: false),\n                                                                                                                                                                                                             fillColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                                                                                                                                      isArgb: false),\n                                                                                                                                                                                                             strokeWidth: 1.0,\n                                                                                                                                                                                                             cornerRadius: 5.0),\n                                                                                                                                                                    backgroundDeselected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                                                                                                                                          isArgb: false),\n                                                                                                                                                                                                               fillColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                                                                                                                                        isArgb: false),\n                                                                                                                                                                                                               strokeWidth: 1.0,\n                                                                                                                                                                                                               cornerRadius: 5.0))))","kind":"text"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"init","title":"init(confirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SingleScanningMode(im)initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:","roleHeading":"Initializer","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"confirmationSheetEnabled"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcodeImageVisible"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"sheetColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dividerColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"modalOverlayColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"barcodeTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"barcodeSubtitle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"submitButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"text":", ","kind":"text"},{"text":"cancelButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":", "},{"text":"barcodeInfoMapping","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeInfoMapping","text":"SBSDKUI2BarcodeInfoMapping","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"arOverlay"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"},{"text":")","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2singlescanningmode\/init(confirmationsheetenabled:barcodeimagevisible:sheetcolor:dividercolor:modaloverlaycolor:barcodetitle:barcodesubtitle:submitbutton:cancelbutton:barcodeinfomapping:aroverlay:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2singlescanningmode\/init(confirmationsheetenabled:barcodeimagevisible:sheetcolor:dividercolor:modaloverlaycolor:barcodetitle:barcodesubtitle:submitbutton:cancelbutton:barcodeinfomapping:aroverlay:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SingleScanningMode"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SingleScanningMode\/init(confirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SingleScanningMode/init(confirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:)":{"title":"init(confirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:)","url":"\/documentation\/scanbotsdk\/sbsdkui2singlescanningmode\/init(confirmationsheetenabled:barcodeimagevisible:sheetcolor:dividercolor:modaloverlaycolor:barcodetitle:barcodesubtitle:submitbutton:cancelbutton:barcodeinfomapping:aroverlay:)","abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SingleScanningMode\/init(confirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:)","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"confirmationSheetEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcodeImageVisible"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sheetColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dividerColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"modalOverlayColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcodeTitle"},{"text":": ","kind":"text"},{"text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"barcodeSubtitle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"submitButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cancelButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"text":", ","kind":"text"},{"text":"barcodeInfoMapping","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeInfoMapping","text":"SBSDKUI2BarcodeInfoMapping"},{"kind":"text","text":", "},{"text":"arOverlay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ButtonConfiguration":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2buttonconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"title":"SBSDKUI2ButtonConfiguration","abstract":[{"text":"Button configuration.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayGeneralConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"title":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"symbol","abstract":[{"text":"Configuration of the AR overlay displayed on top of barcodes in the camera preview.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeInfoMapping":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}],"title":"SBSDKUI2BarcodeInfoMapping","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the barcode data mapping."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeinfomapping","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SingleScanningMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SingleScanningMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SingleScanningMode"}],"title":"SBSDKUI2SingleScanningMode","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the single barcode scanning mode."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2SingleScanningMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2singlescanningmode","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","title":"SBSDKUI2Color","url":"\/documentation\/scanbotsdk\/sbsdkui2color","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Color"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","role":"symbol","title":"SBSDKUI2StyledText","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithConfirmationSheetEnabled:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"confirmationSheetEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeImageVisible:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"barcodeImageVisible"},{"kind":"text","text":" "},{"text":"sheetColor:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"kind":"text","text":" *) "},{"text":"sheetColor","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dividerColor:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"dividerColor"},{"text":" ","kind":"text"},{"text":"modalOverlayColor:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"kind":"text","text":" *) "},{"text":"modalOverlayColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodeTitle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"text":"barcodeTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeSubtitle:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"barcodeSubtitle"},{"kind":"text","text":" "},{"text":"submitButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"submitButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"cancelButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"barcodeInfoMapping:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUI2BarcodeInfoMapping","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeInfoMapping","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping"},{"text":" *) ","kind":"text"},{"text":"barcodeInfoMapping","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"arOverlay:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ArOverlayGeneralConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration"},{"kind":"text","text":" *) "},{"text":"arOverlay","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SingleScanningMode~1init(confirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SingleScanningMode~1init(confirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/title","value":"SBSDKUI2ButtonConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/title","op":"replace","value":"SBSDKUI2ArOverlayGeneralConfiguration"},{"value":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping\/title","op":"replace","value":"SBSDKUI2BarcodeInfoMapping"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping\/fragments","value":[{"text":"SBSDKUI2BarcodeInfoMapping","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SingleScanningMode\/title","value":"SBSDKUI2SingleScanningMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SingleScanningMode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SingleScanningMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","op":"replace","value":"SBSDKUI2Color"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title","value":"SBSDKUI2StyledText"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}