{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"setConfigurationWithConfiguration:error:"}],"title":"setConfiguration(configuration:)","roleHeading":"Instance Method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScanner(im)setConfigurationWithConfiguration:error:","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerConfiguration"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScanner"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerConfiguration","text":"SBSDKDocumentScannerConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerConfiguration"},{"text":" = SBSDKDocumentScannerConfiguration(  )) ","kind":"text"},{"text":"throws","kind":"keyword"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The configuration for the document detector."}],"type":"paragraph"}],"name":"configuration"}],"kind":"parameters"},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"aside","style":"note","name":"Throws","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKError","isActive":true},{"type":"text","text":" in case of an error."}],"type":"paragraph"}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScanner\/setConfiguration(configuration:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"text":"Inplace reconfigures the API instance with new settings.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscanner\/setconfiguration(configuration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscanner\/setconfiguration(configuration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScanner/setConfiguration(configuration:)":{"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerConfiguration"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScanner\/setConfiguration(configuration:)","role":"symbol","abstract":[{"type":"text","text":"Inplace reconfigures the API instance with new settings."}],"navigatorTitle":[{"text":"setConfigurationWithConfiguration:error:","kind":"identifier"}],"title":"setConfiguration(configuration:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscanner\/setconfiguration(configuration:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerConfiguration":{"title":"SBSDKDocumentScannerConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerconfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Configuration for the document scanner.","type":"text"}],"navigatorTitle":[{"text":"SBSDKDocumentScannerConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScanner":{"abstract":[{"text":"API for document detection and scanning.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScanner","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscanner","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScanner","kind":"identifier"}],"title":"SBSDKDocumentScanner","navigatorTitle":[{"text":"SBSDKDocumentScanner","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKError":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKError","kind":"identifier"}],"title":"SBSDKError","abstract":[{"text":"Represents errors that can occur within the Scanbot SDK.","type":"text"}],"navigatorTitle":[{"text":"SBSDKError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerror","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"setConfigurationWithConfiguration:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"setConfigurationWithConfiguration:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"setConfigurationWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The configuration for the document detector.","type":"text"}],"type":"paragraph"}],"name":"configuration"},{"content":[{"inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}],"type":"paragraph"}],"name":"error"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"codeVoice","code":"YES"},{"type":"text","text":" if the method succeeded, otherwise "},{"type":"codeVoice","code":"NO"},{"type":"text","text":"."}],"type":"paragraph"}]},"op":"add","path":"\/primaryContentSections\/2"},{"value":"setConfigurationWithConfiguration:error:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScanner~1setConfiguration(configuration:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"setConfigurationWithConfiguration:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScanner~1setConfiguration(configuration:)\/fragments"},{"value":"SBSDKDocumentScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerConfiguration\/title"},{"value":[{"text":"SBSDKDocumentScannerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerConfiguration\/navigatorTitle"},{"value":"SBSDKDocumentScanner","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScanner\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScanner"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScanner\/fragments"},{"value":[{"text":"SBSDKDocumentScanner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScanner\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}