{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView\/View-Implementations"]]},"metadata":{"modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotSDK"}],"roleHeading":"Instance Method","extendedModule":"SwiftUICore","title":"actionSheet(isPresented:content:)","externalID":"s:7SwiftUI4ViewPAAE11actionSheet11isPresented7contentQrAA7BindingVySbG_AA06ActionE0VyXEtF::SYNTHESIZED::s:10ScanbotSDK24SBSDKUI2CheckScannerViewV","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionSheet"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isPresented"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Binding","preciseIdentifier":"s:7SwiftUI7BindingV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI11ActionSheetV","text":"ActionSheet"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"platforms":[{"unavailable":false,"introducedAt":"13.0","deprecated":false,"beta":false,"message":"use `confirmationDialog(title:isPresented:titleVisibility:presenting::actions:)`instead.","name":"iOS","deprecatedAt":"100000.0"},{"unavailable":false,"introducedAt":"13.0","deprecated":false,"beta":false,"message":"use `confirmationDialog(title:isPresented:titleVisibility:presenting::actions:)`instead.","name":"iPadOS","deprecatedAt":"100000.0"},{"unavailable":false,"introducedAt":"13.0","deprecated":false,"beta":false,"message":"use `confirmationDialog(title:isPresented:titleVisibility:presenting::actions:)`instead.","name":"Mac Catalyst","deprecatedAt":"100000.0"},{"unavailable":false,"introducedAt":"13.0","deprecated":false,"beta":false,"message":"use `confirmationDialog(title:isPresented:titleVisibility:presenting:actions:)`instead.","name":"tvOS","deprecatedAt":"100000.0"},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"beta":false,"message":"use `confirmationDialog(title:isPresented:titleVisibility:presenting:actions:)`instead.","name":"visionOS","deprecatedAt":"100000.0"},{"unavailable":false,"introducedAt":"6.0","deprecated":false,"beta":false,"message":"use `confirmationDialog(title:isPresented:titleVisibility:presenting:actions:)`instead.","name":"watchOS","deprecatedAt":"100000.0"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"nonisolated"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionSheet"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isPresented"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Binding","preciseIdentifier":"s:7SwiftUI7BindingV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"ActionSheet","preciseIdentifier":"s:7SwiftUI11ActionSheetV"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"},{"kind":"text","text":"\n"}],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView\/actionSheet(isPresented:content:)"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"use `confirmationDialog(title:isPresented:titleVisibility:presenting:actions:)`instead."}]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.actionSheet(isPresented:content:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerview\/actionsheet(ispresented:content:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerView/View-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerview\/view-implementations","type":"topic","abstract":[],"kind":"article","role":"collectionGroup","title":"View Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView\/View-Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerView/actionSheet(isPresented:content:)":{"kind":"symbol","abstract":[],"role":"symbol","title":"actionSheet(isPresented:content:)","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerview\/actionsheet(ispresented:content:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionSheet","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isPresented","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI11ActionSheetV","text":"ActionSheet","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView\/actionSheet(isPresented:content:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerView":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CheckScannerView"}],"title":"SBSDKUI2CheckScannerView","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerview","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView","role":"symbol","abstract":[{"text":"The SwiftUI wrapper for ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController","type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CheckScannerView"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerViewController":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CheckScannerViewController"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerviewcontroller","role":"symbol","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan check data.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CheckScannerViewController"}],"title":"SBSDKUI2CheckScannerViewController"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2CheckScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CheckScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CheckScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}