{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscanneruiresult\/initwithrawtext:wordboxes:symbolboxes:confidence:"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerUIResult"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerUIResult\/initWithRawText:wordBoxes:symbolBoxes:confidence:","interfaceLanguage":"occ"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRawText:wordBoxes:symbolBoxes:confidence:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"initWithRawText:wordBoxes:symbolBoxes:confidence:","kind":"identifier"}],"title":"initWithRawText:wordBoxes:symbolBoxes:confidence:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerUIResult(im)initWithRawText:wordBoxes:symbolBoxes:confidence:"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithRawText:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"rawText","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"wordBoxes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKWordBox *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"wordBoxes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"symbolBoxes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKSymbolBox *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"symbolBoxes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"confidence:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"confidence","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerUIResult/initWithRawText:wordBoxes:symbolBoxes:confidence:":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscanneruiresult\/initwithrawtext:wordboxes:symbolboxes:confidence:","abstract":[],"title":"initWithRawText:wordBoxes:symbolBoxes:confidence:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRawText:wordBoxes:symbolBoxes:confidence:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithRawText:wordBoxes:symbolBoxes:confidence:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerUIResult\/initWithRawText:wordBoxes:symbolBoxes:confidence:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerUIResult":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerUIResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerUIResult"}],"type":"topic","title":"SBSDKUI2TextPatternScannerUIResult","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscanneruiresult","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextPatternScannerUIResult"}],"abstract":[{"text":"Configuration of the generic text scanner RTU UI result.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2TextPatternScannerUIResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerUIResult\/title"},{"op":"replace","value":[{"text":"SBSDKUI2TextPatternScannerUIResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerUIResult\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2TextPatternScannerUIResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerUIResult\/navigatorTitle"}]}]}