{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CheckIntroImage(py)hash","fragments":[{"kind":"identifier","text":"hash"}],"title":"hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Property"},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CheckIntroImage\/hash"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CheckIntroImage"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2checkintroimage\/hash"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CheckIntroImage/hash":{"kind":"symbol","title":"hash","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2checkintroimage\/hash","abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CheckIntroImage\/hash","fragments":[{"text":"hash","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CheckIntroImage":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CheckIntroImage","title":"SBSDKUI2CheckIntroImage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CheckIntroImage","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2CheckIntroImage","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"The image for the introduction screen with a check template.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2checkintroimage"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2CheckIntroImage","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CheckIntroImage\/title"},{"op":"replace","value":[{"text":"SBSDKUI2CheckIntroImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CheckIntroImage\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2CheckIntroImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CheckIntroImage\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}