{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingView\/fullScreenCover(isPresented:onDismiss:content:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingview\/fullscreencover(ispresented:ondismiss:content:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullScreenCover"},{"text":"<","kind":"text"},{"text":"Content","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"isPresented","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Binding","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV"},{"kind":"text","text":"<"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":">, "},{"text":"onDismiss","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")? = nil, ","kind":"text"},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"ViewBuilder","preciseIdentifier":"s:7SwiftUI11ViewBuilderV"},{"kind":"text","text":" "},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" () -> "},{"text":"Content","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"},{"text":" ","kind":"text"},{"kind":"keyword","text":"where"},{"text":" ","kind":"text"},{"text":"Content","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"},{"text":"\n","kind":"text"}],"languages":["swift"]}]}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fullScreenCover","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Content","kind":"genericParameter"},{"text":">(","kind":"text"},{"kind":"externalParam","text":"isPresented"},{"kind":"text","text":": "},{"text":"Binding","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":">, "},{"text":"onDismiss","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?, ","kind":"text"},{"text":"content","kind":"externalParam"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Content"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"title":"fullScreenCover(isPresented:onDismiss:content:)","platforms":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"14.0","beta":false},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"14.0","name":"iPadOS"},{"unavailable":false,"beta":false,"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false},{"deprecated":false,"introducedAt":"14.0","unavailable":false,"beta":false,"name":"tvOS"},{"unavailable":false,"beta":false,"name":"watchOS","deprecated":false,"introducedAt":"7.0"}],"role":"symbol","roleHeading":"Instance Method","externalID":"s:7SwiftUI4ViewPAAE15fullScreenCover11isPresented9onDismiss7contentQrAA7BindingVySbG_yycSgqd__yctAaBRd__lF::SYNTHESIZED::s:10ScanbotSDK20SBSDKUI2CroppingViewV","modules":[{"name":"ScanbotSDK","relatedModules":["SwiftUICore"]}],"symbolKind":"method","extendedModule":"SwiftUICore"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"View.fullScreenCover(isPresented:onDismiss:content:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingView\/View-Implementations"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingView/fullScreenCover(isPresented:onDismiss:content:)":{"title":"fullScreenCover(isPresented:onDismiss:content:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullScreenCover","kind":"identifier"},{"kind":"text","text":"<"},{"text":"Content","kind":"genericParameter"},{"text":">(","kind":"text"},{"kind":"externalParam","text":"isPresented"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding"},{"text":"<","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":">, ","kind":"text"},{"text":"onDismiss","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"content"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Content"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingview\/fullscreencover(ispresented:ondismiss:content:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingView\/fullScreenCover(isPresented:onDismiss:content:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingView":{"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingview","title":"SBSDKUI2CroppingView","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CroppingView","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingView","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingView","abstract":[{"type":"text","text":"The SwiftUI wrapper for "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController","isActive":true,"type":"reference"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingViewController":{"title":"SBSDKUI2CroppingViewController","type":"topic","abstract":[{"type":"text","text":"A highly customizable view controller to edit the page polygon or the page orientation."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CroppingViewController"}],"navigatorTitle":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingView/View-Implementations":{"title":"View Implementations","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingView\/View-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingview\/view-implementations","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController\/title","value":"SBSDKUI2CroppingViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController\/fragments","value":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController\/navigatorTitle","value":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}