{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"Scans a machine-readable zone and also detects it if needed from a ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"symbolKind":"method","title":"scan(from:useLiveMode:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"text":"useLiveMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"SBSDKMRZScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerResult"},{"text":"?","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScanner(im)scanFromImage:useLiveMode:","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"scanFromImage:useLiveMode:","kind":"identifier"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscanner\/scan(from:uselivemode:)-59j7r"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscanner\/scan(from:uselivemode:)-59j7r"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(scanFromImage:useLiveMode:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"text":"useLiveMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false) -> ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerResult","text":"SBSDKMRZScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerResult"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image to scan (and detect) from."}]}]},{"name":"useLiveMode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":", the scanner will use live mode for scanning."}]}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The scan result."}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/scan(from:useLiveMode:)-59j7r"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerResult":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMRZScannerResult","kind":"identifier"}],"abstract":[{"type":"text","text":"Container for result of MRZ scanning attempt."}],"navigatorTitle":[{"text":"SBSDKMRZScannerResult","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerresult","title":"SBSDKMRZScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerResult","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScanner/scan(from:useLiveMode:)-59j7r":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/scan(from:useLiveMode:)-59j7r","role":"symbol","kind":"symbol","title":"scan(from:useLiveMode:)","url":"\/documentation\/scanbotsdk\/sbsdkmrzscanner\/scan(from:uselivemode:)-59j7r","abstract":[{"type":"text","text":"Scans a machine-readable zone and also detects it if needed from a "},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"scanFromImage:useLiveMode:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scan"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useLiveMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKMRZScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerResult"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScanner":{"type":"topic","title":"SBSDKMRZScanner","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZScanner"}],"abstract":[{"type":"text","text":"A class to scan machine-readable zones on various image sources."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzscanner","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZScanner"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"scanFromImage:useLiveMode:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"scanFromImage:useLiveMode:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"SBSDKMRZScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"scanFromImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"useLiveMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"useLiveMode","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"text":"The image to scan (and detect) from.","type":"text"}]}]},{"name":"useLiveMode","content":[{"type":"paragraph","inlineContent":[{"text":"If set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", the scanner will use live mode for scanning.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The scan result."}]}]},"path":"\/primaryContentSections\/2"},{"value":"SBSDKMRZScannerResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerResult\/title"},{"value":[{"text":"SBSDKMRZScannerResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerResult\/fragments"},{"value":[{"text":"SBSDKMRZScannerResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerResult\/navigatorTitle"},{"value":"scanFromImage:useLiveMode:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1scan(from:useLiveMode:)-59j7r\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scanFromImage:useLiveMode:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1scan(from:useLiveMode:)-59j7r\/fragments"},{"value":"SBSDKMRZScanner","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner\/title"},{"value":[{"text":"SBSDKMRZScanner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKMRZScanner"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner\/navigatorTitle"}]}]}