{"sections":[],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"title":"copyWithZone:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorIntroImage(im)copyWithZone:"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/copyWithZone:"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier","text":"_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroImage/copyWithZone:":{"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage\/copywithzone:","type":"topic","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/copyWithZone:","title":"copyWithZone:","kind":"symbol","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroImage":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage","title":"SBSDKUI2DocumentDataExtractorIntroImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorIntroImage"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorIntroImage"}],"role":"symbol","abstract":[{"text":"The image for the introduction screen of a document data extractor screen.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2DocumentDataExtractorIntroImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentDataExtractorIntroImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorIntroImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage\/navigatorTitle"}]}]}