{"abstract":[{"text":"The acknowledgement screen will always be shown after each snap, regardless of the scanned page’s quality.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"always","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKUI2AcknowledgementMode.always","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2AcknowledgementMode@SBSDKUI2AcknowledgementModeAlways","roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"text":"SBSDKUI2AcknowledgementModeAlways","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"always"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode\/always"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode\/always"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/always"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementMode":{"url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode","title":"SBSDKUI2AcknowledgementMode","abstract":[{"type":"text","text":"Determines, after each page is snapped, whether the acknowledgment screen should be displayed or not."}],"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2AcknowledgementMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2AcknowledgementMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementMode/always":{"type":"topic","title":"SBSDKUI2AcknowledgementMode.always","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/always","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"always","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2AcknowledgementModeAlways","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode\/always","abstract":[{"type":"text","text":"The acknowledgement screen will always be shown after each snap, regardless of the scanned page’s quality."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUI2AcknowledgementModeAlways"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKUI2AcknowledgementModeAlways","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementModeAlways"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode\/title","op":"replace","value":"SBSDKUI2AcknowledgementMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode\/fragments","op":"replace","value":[{"text":"SBSDKUI2AcknowledgementMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2AcknowledgementMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode~1always\/title","op":"replace","value":"SBSDKUI2AcknowledgementModeAlways"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode~1always\/fragments","op":"replace","value":[{"text":"SBSDKUI2AcknowledgementModeAlways","kind":"identifier"}]}]}]}