{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BottomBarModeGradient"}],"title":"SBSDKUI2BottomBarMode.gradient","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2BottomBarMode@SBSDKUI2BottomBarModeGradient","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"gradient"}],"roleHeading":"Case","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2bottombarmode\/gradient"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2bottombarmode\/gradient"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Display the bottom bar with a gradient background color or a gradient with transparency. The buttons will still be visible."}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BottomBarMode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BottomBarMode\/gradient"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gradient"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 8.0.4","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2BottomBarMode/gradient":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BottomBarMode\/gradient","role":"symbol","type":"topic","title":"SBSDKUI2BottomBarMode.gradient","navigatorTitle":[{"text":"SBSDKUI2BottomBarModeGradient","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2bottombarmode\/gradient","abstract":[{"type":"text","text":"Display the bottom bar with a gradient background color or a gradient with transparency. The buttons will still be visible."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gradient","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2BottomBarMode":{"role":"symbol","abstract":[{"text":"The visual mode used for the bottom bar.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BottomBarMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BottomBarMode","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2bottombarmode","navigatorTitle":[{"text":"SBSDKUI2BottomBarMode","kind":"identifier"}],"title":"SBSDKUI2BottomBarMode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUI2BottomBarModeGradient"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKUI2BottomBarModeGradient","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2BottomBarModeGradient"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BottomBarMode~1gradient\/title","op":"replace","value":"SBSDKUI2BottomBarModeGradient"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BottomBarMode~1gradient\/fragments","op":"replace","value":[{"text":"SBSDKUI2BottomBarModeGradient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BottomBarMode\/title","op":"replace","value":"SBSDKUI2BottomBarMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BottomBarMode\/fragments","op":"replace","value":[{"text":"SBSDKUI2BottomBarMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BottomBarMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2BottomBarMode","kind":"identifier"}]}]}]}