{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/decode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/decode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/decode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Same as VALIDATE, except that GS1 strings are converted to the human-readable format,"},{"type":"text","text":" "},{"type":"text","text":"instead"},{"type":"text","text":" "},{"type":"text","text":"(with parentheses used to wrap AI keys, e.g. “(01)123456789”). The \\x1D character is"},{"type":"text","text":" "},{"type":"text","text":"never used in this representation."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decode"}],"title":"SBSDKGS1Handling.decode","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGS1Handling@SBSDKGS1HandlingDecode","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1HandlingDecode"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling":{"role":"symbol","title":"SBSDKGS1Handling","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGS1Handling"}],"abstract":[{"type":"text","text":"GS1 message handling options. The GS1 standard defines a"},{"type":"text","text":" "},{"type":"text","text":"a key-value format for business-centric data"},{"type":"text","text":" "},{"type":"text","text":"that can be encoded into many 1D and 2D barcode types."},{"type":"text","text":" "},{"type":"text","text":"https:\/\/ref.gs1.org\/standards\/genspecs\/"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling/decode":{"role":"symbol","title":"SBSDKGS1Handling.decode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decode"}],"abstract":[{"type":"text","text":"Same as VALIDATE, except that GS1 strings are converted to the human-readable format,"},{"type":"text","text":" "},{"type":"text","text":"instead"},{"type":"text","text":" "},{"type":"text","text":"(with parentheses used to wrap AI keys, e.g. “(01)123456789”). The \\x1D character is"},{"type":"text","text":" "},{"type":"text","text":"never used in this representation."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/decode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1HandlingDecode"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/decode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKGS1HandlingDecode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKGS1HandlingDecode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKGS1HandlingDecode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/title","value":"SBSDKGS1Handling"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/fragments","value":[{"kind":"identifier","text":"SBSDKGS1Handling"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling~1decode\/title","value":"SBSDKGS1HandlingDecode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling~1decode\/fragments","value":[{"kind":"identifier","text":"SBSDKGS1HandlingDecode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}