{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/parse"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/parse"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/parse"},"abstract":[{"type":"text","text":"This is the default. GS1 messages are converted to the machine-readable format per"},{"type":"text","text":" "},{"text":"the GS1 spec (the special FNC1 character is converted to ASCII \\x1D).","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The implied 01 AI key is prepended to DataBar results."},{"text":" ","type":"text"},{"text":"No validation is performed.","type":"text"}],"metadata":{"title":"SBSDKGS1Handling.parse","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGS1Handling@SBSDKGS1HandlingParse","navigatorTitle":[{"text":"SBSDKGS1HandlingParse","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"parse","kind":"identifier"}],"roleHeading":"Case"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parse","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling":{"abstract":[{"text":"GS1 message handling options. The GS1 standard defines a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"a key-value format for business-centric data"},{"text":" ","type":"text"},{"text":"that can be encoded into many 1D and 2D barcode types.","type":"text"},{"text":" ","type":"text"},{"text":"https:\/\/ref.gs1.org\/standards\/genspecs\/","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKGS1Handling","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling","title":"SBSDKGS1Handling","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling","kind":"symbol","navigatorTitle":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","kind":"symbol","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling/parse":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/parse","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"parse","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1HandlingParse"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"This is the default. GS1 messages are converted to the machine-readable format per"},{"type":"text","text":" "},{"text":"the GS1 spec (the special FNC1 character is converted to ASCII \\x1D).","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The implied 01 AI key is prepended to DataBar results."},{"type":"text","text":" "},{"type":"text","text":"No validation is performed."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/parse","type":"topic","title":"SBSDKGS1Handling.parse"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKGS1HandlingParse"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKGS1HandlingParse","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKGS1HandlingParse"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/title","value":"SBSDKGS1Handling","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGS1Handling"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/navigatorTitle","value":[{"text":"SBSDKGS1Handling","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling~1parse\/title","value":"SBSDKGS1HandlingParse"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling~1parse\/fragments","value":[{"text":"SBSDKGS1HandlingParse","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}