{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeResidencePermitBack\/mrz"},"abstract":[{"text":"The child document of type “MRZ”.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeResidencePermitBack"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrz","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentsModelMRZ","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMRZ","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMRZ"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrz","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentsModelMRZ","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMRZ"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"mrz","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelDeResidencePermitBack(py)mrz","modules":[{"name":"ScanbotSDK"}],"title":"mrz"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelderesidencepermitback\/mrz"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelderesidencepermitback\/mrz"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelMRZ":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelMRZ"}],"title":"SBSDKDocumentsModelMRZ","kind":"symbol","abstract":[{"type":"text","text":"MRZ part of the document"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMRZ","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmrz","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelMRZ"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeResidencePermitBack/mrz":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The child document of type “MRZ”."}],"title":"mrz","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeResidencePermitBack\/mrz","kind":"symbol","navigatorTitle":[{"text":"mrz","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelderesidencepermitback\/mrz","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrz","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentsModelMRZ","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMRZ","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeResidencePermitBack":{"kind":"symbol","title":"SBSDKDocumentsModelDeResidencePermitBack","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeResidencePermitBack","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelderesidencepermitback","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelDeResidencePermitBack","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentsModelDeResidencePermitBack","kind":"identifier"}],"abstract":[{"type":"text","text":"German Residence Permit (Aufenthaltstitel), Back side"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"mrz","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"mrz"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMRZ","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMRZ","text":"SBSDKDocumentsModelMRZ","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"mrz","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentsModelMRZ","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMRZ\/title"},{"value":[{"text":"SBSDKDocumentsModelMRZ","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMRZ\/fragments"},{"value":[{"text":"SBSDKDocumentsModelMRZ","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMRZ\/navigatorTitle"},{"value":"mrz","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeResidencePermitBack~1mrz\/title"},{"value":[{"kind":"identifier","text":"mrz"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeResidencePermitBack~1mrz\/fragments"},{"value":"SBSDKDocumentsModelDeResidencePermitBack","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeResidencePermitBack\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentsModelDeResidencePermitBack"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeResidencePermitBack\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentsModelDeResidencePermitBack"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeResidencePermitBack\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}