{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneruiconfiguration\/finderenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneruiconfiguration\/finderenabled"]}],"abstract":[{"text":"Whether the view finder is enabled or not.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"title":"finderEnabled","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerUIConfiguration(py)finderEnabled","role":"symbol","navigatorTitle":[{"text":"finderEnabled","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"finderEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","symbolKind":"property","platforms":[]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerUIConfiguration\/finderEnabled"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerUIConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finderEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Defaults to disabled.","type":"text"}]}]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2DocumentScannerViewController instead."}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerUIConfiguration/finderEnabled":{"kind":"symbol","abstract":[{"type":"text","text":"Whether the view finder is enabled or not."}],"navigatorTitle":[{"text":"finderEnabled","kind":"identifier"}],"role":"symbol","deprecated":true,"title":"finderEnabled","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerUIConfiguration\/finderEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"finderEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneruiconfiguration\/finderenabled","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerUIConfiguration":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIFinderDocumentScannerUIConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerUIConfiguration","abstract":[{"text":"Configuration for the user interface of the document scanning screen.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerUIConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneruiconfiguration","kind":"symbol","title":"SBSDKUIFinderDocumentScannerUIConfiguration","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"finderEnabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"finderEnabled","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"finderEnabled","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"value":"finderEnabled","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerUIConfiguration~1finderEnabled\/title","op":"replace"},{"value":[{"text":"finderEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerUIConfiguration~1finderEnabled\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerUIConfiguration\/title","op":"replace","value":"SBSDKUIFinderDocumentScannerUIConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerUIConfiguration\/fragments","value":[{"text":"SBSDKUIFinderDocumentScannerUIConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerUIConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIFinderDocumentScannerUIConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}