{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerUIConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerUIConfiguration\/init"},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerUIConfiguration(im)init","symbolKind":"method"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneruiconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerUIConfiguration/init":{"title":"init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerUIConfiguration\/init","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneruiconfiguration\/init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerUIConfiguration":{"abstract":[{"type":"text","text":"Configuration for the user interface of the document scanning screen."}],"title":"SBSDKUIFinderDocumentScannerUIConfiguration","kind":"symbol","navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerUIConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneruiconfiguration","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerUIConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerUIConfiguration"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUIFinderDocumentScannerUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerUIConfiguration\/title"},{"value":[{"text":"SBSDKUIFinderDocumentScannerUIConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerUIConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerUIConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerUIConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}