{"kind":"symbol","abstract":[{"text":"The sensitivity of auto-snapping. Values are clamped to the range 0.0 - 1.0.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoSnappingSensitivity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"A value of 1.0 triggers automatic snapping immediately, a value of 0.0 delays the automatic by 3 seconds.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/autosnappingsensitivity"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/autosnappingsensitivity"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController\/autoSnappingSensitivity","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"autoSnappingSensitivity"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSnappingSensitivity"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"modules":[{"name":"ScanbotSDK"}],"title":"autoSnappingSensitivity","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController(py)autoSnappingSensitivity","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController/autoSnappingSensitivity":{"navigatorTitle":[{"kind":"identifier","text":"autoSnappingSensitivity"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSnappingSensitivity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"abstract":[{"text":"The sensitivity of auto-snapping. Values are clamped to the range 0.0 - 1.0.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController\/autoSnappingSensitivity","type":"topic","kind":"symbol","title":"autoSnappingSensitivity","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/autosnappingsensitivity"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController":{"abstract":[{"type":"text","text":"A UIViewController subclass to show a camera screen and run a user guiding document scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","kind":"symbol","title":"SBSDKDocumentScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"autoSnappingSensitivity"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"autoSnappingSensitivity"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"autoSnappingSensitivity","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController~1autoSnappingSensitivity\/title","value":"autoSnappingSensitivity"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController~1autoSnappingSensitivity\/fragments","value":[{"kind":"identifier","text":"autoSnappingSensitivity"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/title","value":"SBSDKDocumentScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/fragments","value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/navigatorTitle","value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}]}]}]}