{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOutputMode\/antialiased"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKOutputMode@SBSDKOutputModeAntialiased","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"antialiased","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKOutputModeAntialiased"}],"title":"SBSDKOutputMode.antialiased","roleHeading":"Case"},"kind":"symbol","abstract":[{"text":"ANTIALIASED - When the source image is a document photo, this mode","type":"text"},{"text":" ","type":"text"},{"text":"will produce nice, smooth, antialiased text in grayscale, which is typically more readable","type":"text"},{"type":"text","text":" "},{"type":"text","text":"than the text in BINARY mode. Antialiasing requires extra processing,"},{"type":"text","text":" "},{"type":"text","text":"which makes this mode slower than BINARY mode."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOutputMode"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkoutputmode\/antialiased"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkoutputmode\/antialiased"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"antialiased"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOutputMode":{"url":"\/documentation\/scanbotsdk\/sbsdkoutputmode","title":"SBSDKOutputMode","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOutputMode","kind":"symbol","abstract":[{"type":"text","text":"Output mode of binarization filter."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKOutputMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKOutputMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOutputMode/antialiased":{"abstract":[{"text":"ANTIALIASED - When the source image is a document photo, this mode","type":"text"},{"type":"text","text":" "},{"text":"will produce nice, smooth, antialiased text in grayscale, which is typically more readable","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"than the text in BINARY mode. Antialiasing requires extra processing,"},{"type":"text","text":" "},{"text":"which makes this mode slower than BINARY mode.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOutputMode\/antialiased","navigatorTitle":[{"text":"SBSDKOutputModeAntialiased","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkoutputmode\/antialiased","type":"topic","title":"SBSDKOutputMode.antialiased","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"antialiased"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKOutputModeAntialiased","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"text":"SBSDKOutputModeAntialiased","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKOutputModeAntialiased"}]}]},"op":"replace"},{"value":"SBSDKOutputMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOutputMode\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOutputMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKOutputMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOutputMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKOutputMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOutputMode~1antialiased\/title","op":"replace","value":"SBSDKOutputModeAntialiased"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOutputMode~1antialiased\/fragments","value":[{"text":"SBSDKOutputModeAntialiased","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}