{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkrandomkeygenerator\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKRandomKeyGenerator\/init","interfaceLanguage":"occ"},"sections":[],"metadata":{"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKRandomKeyGenerator(im)init","role":"symbol","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKRandomKeyGenerator"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKRandomKeyGenerator":{"abstract":[{"text":"A class that generates secure, random keys for storage encryption.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"They keys are generated using the "},{"type":"codeVoice","code":"SecRandomCopyBytes"},{"type":"text","text":" function."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKRandomKeyGenerator","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKRandomKeyGenerator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKRandomKeyGenerator"}],"title":"SBSDKRandomKeyGenerator","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkrandomkeygenerator"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKRandomKeyGenerator/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKRandomKeyGenerator\/init","title":"init","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkrandomkeygenerator\/init","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","title":"ScanbotDocumentScannerSDK"}},"variantOverrides":[{"patch":[{"value":"SBSDKRandomKeyGenerator","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKRandomKeyGenerator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKRandomKeyGenerator"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKRandomKeyGenerator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKRandomKeyGenerator\/navigatorTitle","value":[{"text":"SBSDKRandomKeyGenerator","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}