{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenTextConfiguration\/init","interfaceLanguage":"occ"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreentextconfiguration\/init"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenTextConfiguration(im)init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenTextConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenTextConfiguration/init":{"title":"init","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreentextconfiguration\/init","abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenTextConfiguration\/init","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenTextConfiguration":{"deprecated":true,"abstract":[{"type":"text","text":"Configuration for the textual content of the page cropping screen."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingScreenTextConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreentextconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenTextConfiguration","type":"topic","kind":"symbol","title":"SBSDKUICroppingScreenTextConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICroppingScreenTextConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenTextConfiguration\/title","op":"replace","value":"SBSDKUICroppingScreenTextConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenTextConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUICroppingScreenTextConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUICroppingScreenTextConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenTextConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}