{"topicSections":[{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/topBar\/cancel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/topBar\/info"],"anchor":"Type-Properties"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/topBar","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/topbar"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBar","kind":"identifier"}]}]}],"metadata":{"externalID":"s:10ScanbotSDK32SBSDKUI2DataCaptureAccessibilityC6topBarC","symbolKind":"class","role":"symbol","roleHeading":"Class","navigatorTitle":[{"text":"topBar","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBar","kind":"identifier"}],"title":"SBSDKUI2DataCaptureAccessibility.topBar"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility/topBar/cancel":{"type":"topic","role":"symbol","kind":"symbol","title":"cancel","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/topBar\/cancel","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/topbar\/cancel"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility":{"title":"SBSDKUI2DataCaptureAccessibility","url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DataCaptureAccessibility"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility","abstract":[{"type":"text","text":"Accessibility identifiers to be used in UI tests for the data capture scanner RTU-UI V2 (MRZ, credit card, text pattern).."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DataCaptureAccessibility"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility/topBar":{"navigatorTitle":[{"text":"topBar","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/topbar","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/topBar","type":"topic","title":"SBSDKUI2DataCaptureAccessibility.topBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBar","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility/topBar/info":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/topbar\/info","abstract":[],"type":"topic","kind":"symbol","title":"info","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/topBar\/info"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2DataCaptureAccessibility","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DataCaptureAccessibility\/title"},{"value":[{"text":"SBSDKUI2DataCaptureAccessibility","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DataCaptureAccessibility\/fragments"},{"value":[{"text":"SBSDKUI2DataCaptureAccessibility","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DataCaptureAccessibility\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}