{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController\/magneticEdgeColor"},"kind":"symbol","abstract":[{"text":"The rendering color of magnetically snapped edges.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller\/magneticedgecolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller\/magneticedgecolor"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController(py)magneticEdgeColor","title":"magneticEdgeColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"magneticEdgeColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"magneticEdgeColor"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"magneticEdgeColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Must be called on the main-thread!"}],"type":"paragraph"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewController":{"type":"topic","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show and edit an image."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","title":"SBSDKImageEditingViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewController/magneticEdgeColor":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController\/magneticEdgeColor","url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller\/magneticedgecolor","title":"magneticEdgeColor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"magneticEdgeColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"magneticEdgeColor","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The rendering color of magnetically snapped edges."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"magneticEdgeColor","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"magneticEdgeColor","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" * ","kind":"text"},{"text":"magneticEdgeColor","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/title","value":"SBSDKImageEditingViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/fragments","value":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/navigatorTitle"},{"op":"replace","value":"magneticEdgeColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController~1magneticEdgeColor\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController~1magneticEdgeColor\/fragments","value":[{"text":"magneticEdgeColor","kind":"identifier"}],"op":"replace"}]}]}