{"abstract":[{"type":"text","text":"Mapped info about barcode. Is filled via "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerMapping","isActive":true},{"type":"text","text":" protocol."}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"platforms":[],"title":"mappedData","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mappedData","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUIBarcodeMappedData","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeMappedData"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"mappedData"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeMappedResult(py)mappedData"},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeMappedResult\/mappedData","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodemappedresult\/mappeddata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodemappedresult\/mappeddata"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeMappedResult"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mappedData"},{"text":": ","kind":"text"},{"text":"SBSDKUIBarcodeMappedData","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeMappedData","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeMappedData"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Can be ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]}],"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeMappedData":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeMappedData","deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeMappedData"}],"kind":"symbol","role":"symbol","type":"topic","title":"SBSDKUIBarcodeMappedData","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeMappedData"}],"abstract":[{"type":"text","text":"Class that contains barcode name and description."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodemappeddata"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeMappedResult":{"abstract":[{"type":"text","text":"Class that contains barcode result and mapped data."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodemappedresult","navigatorTitle":[{"text":"SBSDKUIBarcodeMappedResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeMappedResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeMappedResult"}],"deprecated":true,"title":"SBSDKUIBarcodeMappedResult"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController":{"deprecated":true,"type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller","title":"SBSDKUIBarcodesBatchScannerViewController","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan barcodes batches."}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeMappedResult/mappedData":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodemappedresult\/mappeddata","type":"topic","title":"mappedData","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mappedData","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUIBarcodeMappedData","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeMappedData"},{"text":"?","kind":"text"}],"abstract":[{"text":"Mapped info about barcode. Is filled via ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerMapping","type":"reference"},{"type":"text","text":" protocol."}],"kind":"symbol","navigatorTitle":[{"text":"mappedData","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeMappedResult\/mappedData","deprecated":true},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerMapping":{"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerMapping","kind":"symbol","navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerMapping","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannermapping","type":"topic","title":"SBSDKUIBarcodesBatchScannerMapping","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodesBatchScannerMapping","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Protocol for the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController"},{"type":"text","text":" barcode results mapping."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"mappedData","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"mappedData","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeMappedData","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeMappedData","text":"SBSDKUIBarcodeMappedData"},{"text":" * ","kind":"text"},{"text":"mappedData","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"SBSDKUIBarcodeMappedData","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeMappedData\/title"},{"op":"replace","value":[{"text":"SBSDKUIBarcodeMappedData","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeMappedData\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeMappedData\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIBarcodeMappedData"}],"op":"replace"},{"value":"SBSDKUIBarcodeMappedResult","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeMappedResult\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeMappedResult\/fragments","value":[{"text":"SBSDKUIBarcodeMappedResult","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeMappedResult\/navigatorTitle","value":[{"text":"SBSDKUIBarcodeMappedResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController\/title","value":"SBSDKUIBarcodesBatchScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}]},{"op":"replace","value":"mappedData","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeMappedResult~1mappedData\/title"},{"value":[{"kind":"identifier","text":"mappedData"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeMappedResult~1mappedData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerMapping\/title","value":"SBSDKUIBarcodesBatchScannerMapping"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerMapping\/fragments","value":[{"text":"SBSDKUIBarcodesBatchScannerMapping","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerMapping\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIBarcodesBatchScannerMapping","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}