{"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraScreenConfiguration(im)isEqual:","roleHeading":"Instance Method","title":"isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isEqual:"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration\/isEqual:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraScreenConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration","type":"topic","navigatorTitle":[{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CameraScreenConfiguration"}],"role":"symbol","abstract":[{"type":"text","text":"Configuration of the screen for scanning the pages with the camera."}],"title":"SBSDKUI2CameraScreenConfiguration","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraScreenConfiguration/isEqual:":{"kind":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/isequal:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration\/isEqual:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/title","op":"replace","value":"SBSDKUI2CameraScreenConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKUI2CameraScreenConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraScreenConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/navigatorTitle"}]}]}