{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkwordbox\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"title":"hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKWordBox(py)hash","fragments":[{"kind":"identifier","text":"hash"}],"symbolKind":"property"},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWordBox\/hash","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWordBox"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWordBox":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKWordBox"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKWordBox"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWordBox","abstract":[{"text":"Structure containing recognized word text and bounds.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkwordbox","title":"SBSDKWordBox"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWordBox/hash":{"title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkwordbox\/hash","kind":"symbol","fragments":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWordBox\/hash","type":"topic","role":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWordBox\/title","op":"replace","value":"SBSDKWordBox"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWordBox\/fragments","op":"replace","value":[{"text":"SBSDKWordBox","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWordBox\/navigatorTitle","op":"replace","value":[{"text":"SBSDKWordBox","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}