{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenTextLocalization"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2CheckScannerScreenTextLocalization","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerScreenTextLocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenTextLocalization"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenTextLocalization\/fromJsonWithJson:","interfaceLanguage":"occ"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreentextlocalization\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"roleHeading":"Type Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerScreenTextLocalization(cm)fromJsonWithJson:","title":"fromJsonWithJson:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerScreenTextLocalization/fromJsonWithJson:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreentextlocalization\/fromjsonwithjson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenTextLocalization\/fromJsonWithJson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"abstract":[],"title":"fromJsonWithJson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerScreenTextLocalization":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CheckScannerScreenTextLocalization"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CheckScannerScreenTextLocalization"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreentextlocalization","abstract":[{"type":"text","text":"Configuration of the all strings for check scanner screen."}],"type":"topic","kind":"symbol","title":"SBSDKUI2CheckScannerScreenTextLocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenTextLocalization"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2CheckScannerScreenTextLocalization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenTextLocalization\/title"},{"value":[{"text":"SBSDKUI2CheckScannerScreenTextLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenTextLocalization\/fragments"},{"value":[{"text":"SBSDKUI2CheckScannerScreenTextLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenTextLocalization\/navigatorTitle"}]}]}