{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullName:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"fullName"},{"kind":"text","text":" "},{"text":"normalizedName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"normalizedName","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"commonType:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType","text":"SBSDKCommonFieldType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCommonFieldType"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"commonType"},{"text":" ","kind":"text"},{"text":"listIndex:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"listIndex"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldType"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldtype\/initwithname:fullname:normalizedname:commontype:listindex:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"title":"initWithName:fullName:normalizedName:commonType:listIndex:","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldType(im)initWithName:fullName:normalizedName:commonType:listIndex:","navigatorTitle":[{"kind":"identifier","text":"initWithName:fullName:normalizedName:commonType:listIndex:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:fullName:normalizedName:commonType:listIndex:"}],"role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldType\/initWithName:fullName:normalizedName:commonType:listIndex:","interfaceLanguage":"occ"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldType/initWithName:fullName:normalizedName:commonType:listIndex:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldType\/initWithName:fullName:normalizedName:commonType:listIndex:","fragments":[{"kind":"text","text":"- "},{"text":"initWithName:fullName:normalizedName:commonType:listIndex:","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldtype\/initwithname:fullname:normalizedname:commontype:listindex:","type":"topic","title":"initWithName:fullName:normalizedName:commonType:listIndex:","navigatorTitle":[{"kind":"identifier","text":"initWithName:fullName:normalizedName:commonType:listIndex:"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCommonFieldType":{"url":"\/documentation\/scanbotsdk\/sbsdkcommonfieldtype","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKCommonFieldType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKCommonFieldType"}],"kind":"symbol","title":"SBSDKCommonFieldType","abstract":[{"type":"text","text":"Common field types."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldType":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldtype","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentFieldType"}],"type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocumentFieldType","kind":"identifier"}],"kind":"symbol","title":"SBSDKGenericDocumentFieldType","abstract":[{"type":"text","text":"Generic Document Type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCommonFieldType\/title","op":"replace","value":"SBSDKCommonFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCommonFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKCommonFieldType"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCommonFieldType\/navigatorTitle","value":[{"text":"SBSDKCommonFieldType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldType\/title","value":"SBSDKGenericDocumentFieldType","op":"replace"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldType\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentFieldType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldType\/navigatorTitle","op":"replace"}]}]}