{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate"]]},"metadata":{"title":"imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKImageEditingViewControllerDelegate(im)imageEditingViewControllerRotateCounterClockwiseToolbarItem:","navigatorTitle":[{"text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:","kind":"identifier"}],"role":"symbol"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Asks the delegate for a "},{"type":"codeVoice","code":"UIBarButtonItem"},{"type":"text","text":" to for rotating the image counter-clockwise."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerrotatecounterclockwisetoolbaritem(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerrotatecounterclockwisetoolbaritem(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"editingViewController","kind":"internalParam"},{"kind":"text","text":": "},{"text":"SBSDKImageEditingViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIBarButtonItem","text":"UIBarButtonItem","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]},{"parameters":[{"name":"editingViewController","content":[{"inlineContent":[{"type":"text","text":"The calling "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"code":"UIBarButtonItem","type":"codeVoice"},{"text":" for rotating the image counter-clockwise.","type":"text"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewController":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"title":"SBSDKImageEditingViewController","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to show and edit an image.","type":"text"}],"navigatorTitle":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate":{"type":"topic","kind":"symbol","abstract":[{"text":"A delegate protocol to inform an object about changes in ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","type":"reference","isActive":true},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate","title":"SBSDKImageEditingViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerrotatecounterclockwisetoolbaritem(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKImageEditingViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIBarButtonItem","kind":"typeIdentifier","text":"UIBarButtonItem"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)","type":"topic","abstract":[{"type":"text","text":"Asks the delegate for a "},{"type":"codeVoice","code":"UIBarButtonItem"},{"text":" to for rotating the image counter-clockwise.","type":"text"}],"title":"imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBarButtonItem","text":"UIBarButtonItem"},{"kind":"text","text":" *) "},{"text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","kind":"typeIdentifier","text":"SBSDKImageEditingViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController"},{"text":" *) ","kind":"text"},{"text":"editingViewController","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"SBSDKImageEditingViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/fragments","value":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"op":"replace"},{"value":"SBSDKImageEditingViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate\/fragments","op":"replace","value":[{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}]},{"value":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:","kind":"identifier"}]}]}]}