{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerDidCancelChanges(_:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","title":"imageEditingViewControllerDidCancelChanges(_:)","required":true,"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKImageEditingViewControllerDelegate(im)imageEditingViewControllerDidCancelChanges:","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageEditingViewControllerDidCancelChanges"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"imageEditingViewControllerDidCancelChanges:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerDidCancelChanges"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"editingViewController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"editingViewController","content":[{"type":"paragraph","inlineContent":[{"text":"The calling ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController"},{"type":"text","text":"."}]}]}],"kind":"parameters"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerdidcancelchanges(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerdidcancelchanges(_:)"]}],"abstract":[{"type":"text","text":"Informs the delegate that the image editing view controllers cancel button was hit."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate":{"url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate","title":"SBSDKImageEditingViewControllerDelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"type":"topic","abstract":[{"text":"A delegate protocol to inform an object about changes in ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller","abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show and edit an image."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","type":"topic","title":"SBSDKImageEditingViewController","navigatorTitle":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerDidCancelChanges(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerdidcancelchanges(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerDidCancelChanges(_:)","type":"topic","role":"symbol","kind":"symbol","title":"imageEditingViewControllerDidCancelChanges(_:)","required":true,"abstract":[{"type":"text","text":"Informs the delegate that the image editing view controllers cancel button was hit."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerDidCancelChanges"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerDidCancelChanges:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"imageEditingViewControllerDidCancelChanges:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"imageEditingViewControllerDidCancelChanges:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"imageEditingViewControllerDidCancelChanges:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController"},{"text":" *) ","kind":"text"},{"text":"editingViewController","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"editingViewController","content":[{"inlineContent":[{"text":"The calling ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","value":"SBSDKImageEditingViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}]},{"value":"SBSDKImageEditingViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/fragments","value":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}]},{"value":"imageEditingViewControllerDidCancelChanges:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerDidCancelChanges(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"imageEditingViewControllerDidCancelChanges:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerDidCancelChanges(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}