{"sections":[],"kind":"symbol","abstract":[{"text":"Initializes a new image processor with the given ","type":"text"},{"type":"codeVoice","code":"CMSampleBuffer"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithSampleBuffer:) ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sampleBuffer"},{"kind":"text","text":": "},{"text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The input image of the new image processor."}]}],"name":"sampleBuffer"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"init(sampleBuffer:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageProcessor(im)initWithSampleBuffer:","role":"symbol","roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSampleBuffer:"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"sampleBuffer","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimageprocessor\/init(samplebuffer:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimageprocessor\/init(samplebuffer:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/init(sampleBuffer:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/init(sampleBuffer:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"sampleBuffer","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"text":"Initializes a new image processor with the given ","type":"text"},{"code":"CMSampleBuffer","type":"codeVoice"},{"type":"text","text":"."}],"title":"init(sampleBuffer:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/init(sampleBuffer:)","role":"symbol","navigatorTitle":[{"text":"initWithSampleBuffer:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/init(samplebuffer:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor","title":"SBSDKImageProcessor","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor","abstract":[{"type":"text","text":"A class to process images."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageProcessor"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageProcessor"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithSampleBuffer:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithSampleBuffer:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithSampleBuffer:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"opaqueCMSampleBuffer","preciseIdentifier":"c:@S@opaqueCMSampleBuffer","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sampleBuffer","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1init(sampleBuffer:)\/title","op":"replace","value":"initWithSampleBuffer:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithSampleBuffer:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1init(sampleBuffer:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/title","op":"replace","value":"SBSDKImageProcessor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/fragments","value":[{"kind":"identifier","text":"SBSDKImageProcessor"}]}]}]}