{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageprocessor\/init(samplebuffer:videoorientation:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageprocessor\/init(samplebuffer:videoorientation:)"]}],"abstract":[{"type":"text","text":"Initializes a new image processor with the given "},{"type":"codeVoice","code":"CMSampleBuffer"},{"text":" and video orientation.","type":"text"}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageProcessor(im)initWithSampleBuffer:videoOrientation:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sampleBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"text":", ","kind":"text"},{"text":"videoOrientation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVCaptureVideoOrientation","preciseIdentifier":"c:@E@AVCaptureVideoOrientation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithSampleBuffer:videoOrientation:","kind":"identifier"}],"title":"init(sampleBuffer:videoOrientation:)","role":"symbol","roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/init(sampleBuffer:videoOrientation:)"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithSampleBuffer:videoOrientation:) ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"sampleBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"videoOrientation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AVCaptureVideoOrientation","text":"AVCaptureVideoOrientation"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The input image of the new image processor.","type":"text"}]}],"name":"sampleBuffer"},{"name":"videoOrientation","content":[{"inlineContent":[{"text":"The original orientation of the video the sample buffer was extracted from.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor","title":"SBSDKImageProcessor","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor","abstract":[{"type":"text","text":"A class to process images."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageProcessor"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageProcessor"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/init(sampleBuffer:videoOrientation:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sampleBuffer"},{"kind":"text","text":": "},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"text":", ","kind":"text"},{"text":"videoOrientation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVCaptureVideoOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@AVCaptureVideoOrientation"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/init(sampleBuffer:videoOrientation:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/init(samplebuffer:videoorientation:)","navigatorTitle":[{"text":"initWithSampleBuffer:videoOrientation:","kind":"identifier"}],"title":"init(sampleBuffer:videoOrientation:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Initializes a new image processor with the given "},{"type":"codeVoice","code":"CMSampleBuffer"},{"text":" and video orientation.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"initWithSampleBuffer:videoOrientation:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithSampleBuffer:videoOrientation:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithSampleBuffer:","kind":"identifier"},{"kind":"text","text":"("},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@opaqueCMSampleBuffer","text":"opaqueCMSampleBuffer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sampleBuffer"},{"kind":"text","text":" "},{"text":"videoOrientation:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@AVCaptureVideoOrientation","kind":"typeIdentifier","text":"AVCaptureVideoOrientation"},{"kind":"text","text":") "},{"kind":"internalParam","text":"videoOrientation"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKImageProcessor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/title","op":"replace"},{"value":[{"text":"SBSDKImageProcessor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/fragments","op":"replace"},{"value":"initWithSampleBuffer:videoOrientation:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1init(sampleBuffer:videoOrientation:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1init(sampleBuffer:videoOrientation:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithSampleBuffer:videoOrientation:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}