{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarization"]]},"abstract":[{"type":"text","text":"Same behavior as ENABLED if a binarization filter (TIFFGeneratorParameters.binarizationFilter) is set,"},{"type":"text","text":" "},{"type":"text","text":"otherwise same behavior as DISABLED. This is the default."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarization\/enabledIfBinarizationFilterSet","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enabledIfBinarizationFilterSet"}],"roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"text":"SBSDKBinarizationEnabledIfBinarizationFilterSet","kind":"identifier"}],"role":"symbol","title":"SBSDKBinarization.enabledIfBinarizationFilterSet","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKBinarization@SBSDKBinarizationEnabledIfBinarizationFilterSet"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabledIfBinarizationFilterSet","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarization\/enabledifbinarizationfilterset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarization\/enabledifbinarizationfilterset"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBinarization":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarization","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarization","abstract":[{"type":"text","text":"Binarization behavior to apply when adding pages to a TIFF."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBinarization","kind":"identifier"}],"title":"SBSDKBinarization","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKBinarization","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBinarization/enabledIfBinarizationFilterSet":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarization\/enabledifbinarizationfilterset","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"enabledIfBinarizationFilterSet","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKBinarizationEnabledIfBinarizationFilterSet","kind":"identifier"}],"abstract":[{"type":"text","text":"Same behavior as ENABLED if a binarization filter (TIFFGeneratorParameters.binarizationFilter) is set,"},{"type":"text","text":" "},{"type":"text","text":"otherwise same behavior as DISABLED. This is the default."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarization\/enabledIfBinarizationFilterSet","title":"SBSDKBinarization.enabledIfBinarizationFilterSet"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"SBSDKBinarizationEnabledIfBinarizationFilterSet","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKBinarizationEnabledIfBinarizationFilterSet","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKBinarizationEnabledIfBinarizationFilterSet","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKBinarization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarization\/title"},{"value":[{"text":"SBSDKBinarization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarization\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarization\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBinarization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarization~1enabledIfBinarizationFilterSet\/title","value":"SBSDKBinarizationEnabledIfBinarizationFilterSet","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBinarizationEnabledIfBinarizationFilterSet"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarization~1enabledIfBinarizationFilterSet\/fragments"}]}]}