{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelISRCheck\/branchNumber"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"branchNumber","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelisrcheck\/branchnumber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelisrcheck\/branchnumber"]}],"abstract":[{"text":"Branch number","type":"text"}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentModelISRCheck(py)branchNumber","modules":[{"name":"ScanbotSDK"}],"title":"branchNumber","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"branchNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"branchNumber","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelISRCheck"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelISRCheck/branchNumber":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"branchNumber","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"title":"branchNumber","abstract":[{"type":"text","text":"Branch number"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelISRCheck\/branchNumber","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelisrcheck\/branchnumber","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"branchNumber","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelISRCheck":{"type":"topic","title":"SBSDKCheckDocumentModelISRCheck","abstract":[{"type":"text","text":"A check format commonly used in Israel"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelISRCheck","navigatorTitle":[{"text":"SBSDKCheckDocumentModelISRCheck","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckDocumentModelISRCheck","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelisrcheck"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","navigatorTitle":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Generic document field.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","type":"topic","kind":"symbol","title":"SBSDKGenericDocumentField"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"branchNumber","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"branchNumber"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"branchNumber","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"branchNumber","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelISRCheck~1branchNumber\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelISRCheck~1branchNumber\/fragments","value":[{"kind":"identifier","text":"branchNumber"}]},{"value":"SBSDKCheckDocumentModelISRCheck","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelISRCheck\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelISRCheck\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckDocumentModelISRCheck"}]},{"value":[{"text":"SBSDKCheckDocumentModelISRCheck","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelISRCheck\/navigatorTitle","op":"replace"},{"value":"SBSDKGenericDocumentField","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments","op":"replace","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}