{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeMappedData"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodemappeddata\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeMappedData\/copyWithZone:"},"sections":[],"metadata":{"fragments":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeMappedData(im)copyWithZone:","title":"copyWithZone:","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"_NSZone","preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeMappedData/copyWithZone:":{"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeMappedData\/copyWithZone:","role":"symbol","title":"copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodemappeddata\/copywithzone:","fragments":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeMappedData":{"title":"SBSDKUI2BarcodeMappedData","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodemappeddata","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeMappedData","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeMappedData","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeMappedData"}],"abstract":[{"type":"text","text":"Format of the mapped barcode data."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2BarcodeMappedData","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeMappedData\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeMappedData\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeMappedData"}]},{"value":[{"text":"SBSDKUI2BarcodeMappedData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeMappedData\/navigatorTitle"}]}]}