{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpageimagetype\/document"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpageimagetype\/document"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPageImageType"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPageImageType\/document","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"The fully processed, rotated, cropped and filtered image.","type":"text"}],"metadata":{"roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"}],"title":"SBSDKScannedPageImageType.document","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKScannedPageImageType@SBSDKScannedPageImageTypeDocument","symbolKind":"case","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPageImageTypeDocument"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"document","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedPageImageType/document":{"title":"SBSDKScannedPageImageType.document","type":"topic","abstract":[{"type":"text","text":"The fully processed, rotated, cropped and filtered image."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpageimagetype\/document","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"document"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPageImageType\/document","role":"symbol","navigatorTitle":[{"text":"SBSDKScannedPageImageTypeDocument","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedPageImageType":{"type":"topic","title":"SBSDKScannedPageImageType","kind":"symbol","abstract":[{"type":"text","text":"An enum representing the different types of images a scanned page has."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKScannedPageImageType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPageImageType","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpageimagetype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKScannedPageImageType"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKScannedPageImageTypeDocument"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKScannedPageImageTypeDocument","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"SBSDKScannedPageImageTypeDocument","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"SBSDKScannedPageImageTypeDocument","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPageImageType~1document\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPageImageType~1document\/fragments","value":[{"text":"SBSDKScannedPageImageTypeDocument","kind":"identifier"}],"op":"replace"},{"value":"SBSDKScannedPageImageType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPageImageType\/title"},{"op":"replace","value":[{"text":"SBSDKScannedPageImageType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPageImageType\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPageImageType\/navigatorTitle","op":"replace","value":[{"text":"SBSDKScannedPageImageType","kind":"identifier"}]}]}]}