{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/documentpreviewimagesizelimit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/documentpreviewimagesizelimit"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"SBSDKThreadSafe"},{"text":" ","kind":"text"},{"kind":"keyword","text":"dynamic"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentPreviewImageSizeLimit"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"inlineContent":[{"text":"Key-Value Observable. Defaults to ","type":"text"},{"code":"CGSize.zero","type":"codeVoice"},{"type":"text","text":" (ignored)."}],"type":"paragraph"}]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPage(py)documentPreviewImageSizeLimit","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"documentPreviewImageSizeLimit"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentPreviewImageSizeLimit"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"title":"documentPreviewImageSizeLimit"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentPreviewImageSizeLimit","interfaceLanguage":"swift"},"abstract":[{"text":"Limits the maximum size of the document preview image. If width or height are zero, this property is effectively ignored.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/documentPreviewImageSizeLimit":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/documentpreviewimagesizelimit","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentPreviewImageSizeLimit","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentPreviewImageSizeLimit","navigatorTitle":[{"text":"documentPreviewImageSizeLimit","kind":"identifier"}],"abstract":[{"text":"Limits the maximum size of the document preview image. If width or height are zero, this property is effectively ignored.","type":"text"}],"role":"symbol","title":"documentPreviewImageSizeLimit"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"navigatorTitle":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"role":"symbol","abstract":[{"text":"This class represents a scanned documents page.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentPage"}],"title":"SBSDKDocumentPage","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"documentPreviewImageSizeLimit"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"documentPreviewImageSizeLimit","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"documentPreviewImageSizeLimit","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"documentPreviewImageSizeLimit","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentPreviewImageSizeLimit\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentPreviewImageSizeLimit\/fragments","value":[{"text":"documentPreviewImageSizeLimit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title","value":"SBSDKDocumentPage"},{"op":"replace","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/navigatorTitle","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"op":"replace"}]}]}