{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet\/initWithMode:collapsedVisibleHeight:listButton:","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2sheet\/initwithmode:collapsedvisibleheight:listbutton:"]}],"metadata":{"title":"initWithMode:collapsedVisibleHeight:listButton:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithMode:collapsedVisibleHeight:listButton:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet(im)initWithMode:collapsedVisibleHeight:listButton:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithMode:collapsedVisibleHeight:listButton:"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithMode:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2SheetMode","text":"SBSDKUI2SheetMode"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"mode"},{"kind":"text","text":" "},{"kind":"identifier","text":"collapsedVisibleHeight:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CollapsedVisibleHeight","text":"SBSDKUI2CollapsedVisibleHeight","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CollapsedVisibleHeight"},{"kind":"text","text":") "},{"text":"collapsedVisibleHeight","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"listButton:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgedButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgedButton","text":"SBSDKUI2BadgedButton","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"listButton","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CollapsedVisibleHeight":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CollapsedVisibleHeight","title":"SBSDKUI2CollapsedVisibleHeight","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CollapsedVisibleHeight","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2CollapsedVisibleHeight","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the barcodes result sheet’s height while collapsed."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2collapsedvisibleheight"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sheet/initWithMode:collapsedVisibleHeight:listButton:":{"type":"topic","title":"initWithMode:collapsedVisibleHeight:listButton:","fragments":[{"kind":"text","text":"- "},{"text":"initWithMode:collapsedVisibleHeight:listButton:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithMode:collapsedVisibleHeight:listButton:","kind":"identifier"}],"abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2sheet\/initwithmode:collapsedvisibleheight:listbutton:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet\/initWithMode:collapsedVisibleHeight:listButton:","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetMode","title":"SBSDKUI2SheetMode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2SheetMode","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2SheetMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the barcode result sheet’s default visibility state."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetmode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sheet":{"type":"topic","title":"SBSDKUI2Sheet","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2Sheet"}],"navigatorTitle":[{"text":"SBSDKUI2Sheet","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the preview mode for scanning multiple barcodes."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2sheet","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BadgedButton":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgedButton","title":"SBSDKUI2BadgedButton","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2BadgedButton","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2BadgedButton","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the button with a badge."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2badgedbutton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2CollapsedVisibleHeight","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CollapsedVisibleHeight\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CollapsedVisibleHeight\/fragments","value":[{"text":"SBSDKUI2CollapsedVisibleHeight","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKUI2CollapsedVisibleHeight","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CollapsedVisibleHeight\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetMode\/title","op":"replace","value":"SBSDKUI2SheetMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetMode\/fragments","value":[{"text":"SBSDKUI2SheetMode","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2SheetMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetMode\/navigatorTitle"},{"value":"SBSDKUI2Sheet","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Sheet"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Sheet"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgedButton\/title","value":"SBSDKUI2BadgedButton"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgedButton\/fragments","value":[{"text":"SBSDKUI2BadgedButton","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKUI2BadgedButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgedButton\/navigatorTitle"}]}]}