{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"metadata":{"title":"isEqual:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCode128Configuration(im)isEqual:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode128Configuration"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode128Configuration\/isEqual:","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode128configuration\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode128Configuration/isEqual:":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode128Configuration\/isEqual:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode128configuration\/isequal:","title":"isEqual:","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode128Configuration":{"navigatorTitle":[{"text":"SBSDKBarcodeFormatCode128Configuration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode128Configuration","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCode128Configuration","kind":"identifier"}],"abstract":[{"text":"Code 128 barcode configuration. Add to scanner configuration to scan Code 128 barcodes.","type":"text"}],"title":"SBSDKBarcodeFormatCode128Configuration","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode128configuration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode128Configuration\/title","value":"SBSDKBarcodeFormatCode128Configuration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode128Configuration\/fragments","value":[{"text":"SBSDKBarcodeFormatCode128Configuration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode128Configuration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode128Configuration"}]}]}]}