{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/setbarcodeformats(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/setbarcodeformats(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setBarcodeFormats","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"formats","kind":"internalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormat","text":"SBSDKBarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The barcode formats to be scanned."}],"type":"paragraph"}],"name":"formats"}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/setBarcodeFormats(_:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration"]]},"metadata":{"extendedModule":"ScanbotSDK","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBarcodeFormats"},{"kind":"text","text":"(["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat","kind":"typeIdentifier","text":"SBSDKBarcodeFormat"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"setBarcodeFormats:"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKBarcodeScannerConfiguration(im)setBarcodeFormats:","modules":[{"name":"ScanbotSDK"}],"title":"setBarcodeFormats(_:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Overwrites the barcode formats to be scanned. Previously added barcode formats  and barcode format configurations will be removed.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration":{"navigatorTitle":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration","title":"SBSDKBarcodeScannerConfiguration","abstract":[{"text":"Configuration for the barcode scanner.","type":"text"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/setBarcodeFormats(_:)":{"navigatorTitle":[{"kind":"identifier","text":"setBarcodeFormats:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBarcodeFormats"},{"kind":"text","text":"(["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat","kind":"typeIdentifier","text":"SBSDKBarcodeFormat"},{"kind":"text","text":"])"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/setBarcodeFormats(_:)","title":"setBarcodeFormats(_:)","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/setbarcodeformats(_:)","role":"symbol","abstract":[{"type":"text","text":"Overwrites the barcode formats to be scanned. Previously added barcode formats  and barcode format configurations will be removed."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormat":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormat"}],"abstract":[{"type":"text","text":"Enumerates barcode formats."}],"role":"symbol","kind":"symbol","title":"SBSDKBarcodeFormat","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormat"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormat"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"setBarcodeFormats:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBarcodeFormats:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setBarcodeFormats:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKBarcodeFormat *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"formats","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The barcode formats to be scanned."}]}],"name":"formats"}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/title","op":"replace","value":"SBSDKBarcodeScannerConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1setBarcodeFormats(_:)\/title","op":"replace","value":"setBarcodeFormats:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1setBarcodeFormats(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setBarcodeFormats:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat\/title","op":"replace","value":"SBSDKBarcodeFormat"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormat"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormat"}]}]}]}