{"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKApplicationState@SBSDKApplicationStateBackground","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"background","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKApplicationStateBackground","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","roleHeading":"Case","title":"SBSDKApplicationState.background"},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/background","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState"]]},"abstract":[{"text":"The app is in background.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"background","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkapplicationstate\/background"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkapplicationstate\/background"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKApplicationState":{"title":"SBSDKApplicationState","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An enum describing the current state of the app."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState","navigatorTitle":[{"kind":"identifier","text":"SBSDKApplicationState"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKApplicationState"}],"url":"\/documentation\/scanbotsdk\/sbsdkapplicationstate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKApplicationState/background":{"title":"SBSDKApplicationState.background","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkapplicationstate\/background","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/background","navigatorTitle":[{"kind":"identifier","text":"SBSDKApplicationStateBackground"}],"abstract":[{"text":"The app is in background.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"background"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"SBSDKApplicationStateBackground","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKApplicationStateBackground"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKApplicationStateBackground"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKApplicationState","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState\/title","op":"replace"},{"value":[{"text":"SBSDKApplicationState","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState\/fragments","op":"replace"},{"value":[{"text":"SBSDKApplicationState","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState\/navigatorTitle","op":"replace"},{"value":"SBSDKApplicationStateBackground","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState~1background\/title","op":"replace"},{"value":[{"text":"SBSDKApplicationStateBackground","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState~1background\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}