{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerconfiguration\/initwithenginemode:parameters:"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerConfiguration\/initWithEngineMode:parameters:","interfaceLanguage":"occ"},"sections":[],"metadata":{"symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEngineMode:parameters:"}],"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerConfiguration(im)initWithEngineMode:parameters:","title":"initWithEngineMode:parameters:","navigatorTitle":[{"text":"initWithEngineMode:parameters:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithEngineMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentScannerEngineMode","kind":"typeIdentifier","text":"SBSDKDocumentScannerEngineMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerEngineMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"engineMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"parameters:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerParameters","kind":"typeIdentifier","text":"SBSDKDocumentScannerParameters","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerParameters"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"parameters"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerParameters":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerParameters"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerParameters","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerparameters","type":"topic","role":"symbol","title":"SBSDKDocumentScannerParameters","abstract":[{"type":"text","text":"Parameters for the document scanner."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerParameters"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerConfiguration/initWithEngineMode:parameters:":{"title":"initWithEngineMode:parameters:","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerconfiguration\/initwithenginemode:parameters:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerConfiguration\/initWithEngineMode:parameters:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithEngineMode:parameters:","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"initWithEngineMode:parameters:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerConfiguration","title":"SBSDKDocumentScannerConfiguration","role":"symbol","kind":"symbol","abstract":[{"text":"Configuration for the document scanner.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerconfiguration","navigatorTitle":[{"text":"SBSDKDocumentScannerConfiguration","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerEngineMode":{"title":"SBSDKDocumentScannerEngineMode","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerenginemode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerEngineMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerEngineMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Engines for document scanning."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentScannerEngineMode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKDocumentScannerParameters","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerParameters"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters\/navigatorTitle","op":"replace"},{"value":"SBSDKDocumentScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocumentScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerConfiguration\/navigatorTitle","op":"replace"},{"value":"SBSDKDocumentScannerEngineMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerEngineMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerEngineMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerEngineMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerEngineMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerEngineMode\/navigatorTitle","op":"replace"}]}]}