{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFrameAccumulationConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAccumulatedResultsVerifierConfiguration","text":"SBSDKAccumulatedResultsVerifierConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"frameAccumulationConfiguration"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableDetection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enableDetection"},{"kind":"text","text":" "},{"kind":"identifier","text":"incompleteResultHandling:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMRZIncompleteResultHandling","text":"SBSDKMRZIncompleteResultHandling","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling"},{"kind":"text","text":") "},{"kind":"internalParam","text":"incompleteResultHandling"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnCrops:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"returnCrops"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerConfiguration\/initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscannerconfiguration\/initwithframeaccumulationconfiguration:enabledetection:incompleteresulthandling:returncrops:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:"}],"title":"initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerConfiguration(im)initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:","symbolKind":"method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerConfiguration/initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:"}],"abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerconfiguration\/initwithframeaccumulationconfiguration:enabledetection:incompleteresulthandling:returncrops:","title":"initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerConfiguration\/initWithFrameAccumulationConfiguration:enableDetection:incompleteResultHandling:returnCrops:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAccumulatedResultsVerifierConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkaccumulatedresultsverifierconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAccumulatedResultsVerifierConfiguration"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Configure the frame accumulation process.","type":"text"}],"title":"SBSDKAccumulatedResultsVerifierConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKAccumulatedResultsVerifierConfiguration"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZIncompleteResultHandling":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzincompleteresulthandling","type":"topic","navigatorTitle":[{"text":"SBSDKMRZIncompleteResultHandling","kind":"identifier"}],"abstract":[{"text":"Defines how to handle incomplete MRZ results (e.g. caused by failed validation).","type":"text"}],"title":"SBSDKMRZIncompleteResultHandling","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMRZIncompleteResultHandling","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerConfiguration":{"title":"SBSDKMRZScannerConfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerConfiguration","navigatorTitle":[{"text":"SBSDKMRZScannerConfiguration","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMRZScannerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerconfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration for MRZ scanner."}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration\/title","op":"replace","value":"SBSDKAccumulatedResultsVerifierConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKAccumulatedResultsVerifierConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKAccumulatedResultsVerifierConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/title","op":"replace","value":"SBSDKMRZIncompleteResultHandling"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMRZIncompleteResultHandling"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKMRZIncompleteResultHandling"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerConfiguration\/title","op":"replace","value":"SBSDKMRZScannerConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKMRZScannerConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKMRZScannerConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}