{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"property","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"modules":[{"name":"ScanbotSDK","relatedModules":["Swift"]}],"roleHeading":"Instance Property","extendedModule":"Swift","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"hashValue","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@ScanbotSDK@E@SBSDKMRZIncompleteResultHandling","role":"symbol"},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling\/hashValue"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling\/RawRepresentable-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzincompleteresulthandling\/hashvalue"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZIncompleteResultHandling/RawRepresentable-Implementations":{"abstract":[],"role":"collectionGroup","type":"topic","kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","url":"\/documentation\/scanbotsdk\/sbsdkmrzincompleteresulthandling\/rawrepresentable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZIncompleteResultHandling/hashValue":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzincompleteresulthandling\/hashvalue","type":"topic","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling\/hashValue","kind":"symbol","abstract":[],"title":"hashValue","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZIncompleteResultHandling":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzincompleteresulthandling","title":"SBSDKMRZIncompleteResultHandling","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZIncompleteResultHandling"}],"abstract":[{"type":"text","text":"Defines how to handle incomplete MRZ results (e.g. caused by failed validation)."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZIncompleteResultHandling"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKMRZIncompleteResultHandling","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/title"},{"value":[{"text":"SBSDKMRZIncompleteResultHandling","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/fragments"},{"value":[{"text":"SBSDKMRZIncompleteResultHandling","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/navigatorTitle"}]}]}