{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode","text":"SBSDKUI2CameraPreviewMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2cameraconfiguration\/camerapreviewmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2cameraconfiguration\/camerapreviewmode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration\/cameraPreviewMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Which camera preview mode to use."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode"}],"title":"cameraPreviewMode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraConfiguration(py)cameraPreviewMode","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"cameraPreviewMode"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraConfiguration":{"role":"symbol","title":"SBSDKUI2CameraConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the camera settings to be used while scanning."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2cameraconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPreviewMode":{"role":"symbol","title":"SBSDKUI2CameraPreviewMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}],"abstract":[{"type":"text","text":"Configuration of the camera preview mode."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerapreviewmode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.2"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraConfiguration/cameraPreviewMode":{"role":"symbol","title":"cameraPreviewMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode"}],"abstract":[{"type":"text","text":"Which camera preview mode to use."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration\/cameraPreviewMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraPreviewMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2cameraconfiguration\/camerapreviewmode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"cameraPreviewMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cameraPreviewMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode","text":"SBSDKUI2CameraPreviewMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewMode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration\/title","value":"SBSDKUI2CameraConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPreviewMode\/title","value":"SBSDKUI2CameraPreviewMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPreviewMode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration~1cameraPreviewMode\/title","value":"cameraPreviewMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration~1cameraPreviewMode\/fragments","value":[{"kind":"identifier","text":"cameraPreviewMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}