{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2cameraconfiguration\/init(cameramodule:zoomsteps:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:orientationlockmode:camerapreviewmode:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2cameraconfiguration\/init(cameramodule:zoomsteps:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:orientationlockmode:camerapreviewmode:)"]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration\/init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraConfiguration(im)initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:","roleHeading":"Initializer","title":"init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"cameraModule","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule","text":"SBSDKUI2CameraModule"},{"text":", ","kind":"text"},{"text":"zoomSteps","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"defaultZoomFactor"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"flashEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"minFocusDistanceLock","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pinchToZoomEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientationLockMode"},{"kind":"text","text":": "},{"text":"SBSDKUI2OrientationLockMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2OrientationLockMode"},{"kind":"text","text":", "},{"text":"cameraPreviewMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraPreviewMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode"},{"kind":"text","text":")"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"init","navigatorTitle":[{"text":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"cameraModule","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule"},{"kind":"text","text":" = SBSDKUI2CameraModule.back, "},{"text":"zoomSteps","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":"] = [1.0, 2.0, 5.0], ","kind":"text"},{"text":"defaultZoomFactor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":" = 1.0, "},{"kind":"externalParam","text":"flashEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"text":"minFocusDistanceLock","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"pinchToZoomEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = true, ","kind":"text"},{"text":"orientationLockMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2OrientationLockMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2OrientationLockMode"},{"kind":"text","text":" = SBSDKUI2OrientationLockMode.none, "},{"kind":"externalParam","text":"cameraPreviewMode"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode","text":"SBSDKUI2CameraPreviewMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode"},{"text":" = SBSDKUI2CameraPreviewMode.fillIn)","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2OrientationLockMode":{"url":"\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode","kind":"symbol","title":"SBSDKUI2OrientationLockMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode","abstract":[{"type":"text","text":"Configure the orientation of the interface."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPreviewMode":{"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the camera preview mode."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode","title":"SBSDKUI2CameraPreviewMode","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerapreviewmode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraConfiguration":{"title":"SBSDKUI2CameraConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2cameraconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Configuration of the camera settings to be used while scanning.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraConfiguration/init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)":{"navigatorTitle":[{"text":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cameraModule"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"zoomSteps"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"defaultZoomFactor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"flashEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minFocusDistanceLock"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"pinchToZoomEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"orientationLockMode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2OrientationLockMode","text":"SBSDKUI2OrientationLockMode","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"cameraPreviewMode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode","text":"SBSDKUI2CameraPreviewMode"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration\/init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2cameraconfiguration\/init(cameramodule:zoomsteps:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:orientationlockmode:camerapreviewmode:)","title":"init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraModule":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"abstract":[{"type":"text","text":"Determine which camera module to use on start-up."}],"kind":"symbol","title":"SBSDKUI2CameraModule","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2cameramodule","navigatorTitle":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithCameraModule:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule","text":"SBSDKUI2CameraModule","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"cameraModule","kind":"internalParam"},{"kind":"text","text":" "},{"text":"zoomSteps:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"zoomSteps","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"defaultZoomFactor:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"text":"defaultZoomFactor","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"flashEnabled:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"flashEnabled"},{"text":" ","kind":"text"},{"text":"minFocusDistanceLock:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"minFocusDistanceLock","kind":"internalParam"},{"kind":"text","text":" "},{"text":"pinchToZoomEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"pinchToZoomEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientationLockMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2OrientationLockMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2OrientationLockMode"},{"text":") ","kind":"text"},{"text":"orientationLockMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPreviewMode:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2CameraPreviewMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode"},{"text":") ","kind":"text"},{"text":"cameraPreviewMode","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUI2OrientationLockMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode\/fragments","value":[{"text":"SBSDKUI2OrientationLockMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPreviewMode\/title","op":"replace","value":"SBSDKUI2CameraPreviewMode"},{"value":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPreviewMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration\/title","value":"SBSDKUI2CameraConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}]},{"value":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration~1init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration~1init(cameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/title","value":"SBSDKUI2CameraModule"},{"op":"replace","value":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/fragments"}]}]}