{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/a3","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"a3","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/a3"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/a3"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize@SBSDKPDFRendererPageSizeA3","title":"SBSDKPDFRendererPageSize.a3","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"a3","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"text":"SBSDKPDFRendererPageSizeA3","kind":"identifier"}],"role":"symbol","roleHeading":"Case"},"kind":"symbol","abstract":[{"type":"text","text":"The page has A3 size: 297x420 mm. The image is fitted and centered within the page."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageSize":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize","title":"SBSDKPDFRendererPageSize","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRendererPageSize","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageSize"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize","abstract":[{"type":"text","text":"Specifies the desired page size (media box size) for PDF rendering operations."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageSize/a3":{"type":"topic","role":"symbol","abstract":[{"text":"The page has A3 size: 297x420 mm. The image is fitted and centered within the page.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/a3","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/a3","title":"SBSDKPDFRendererPageSize.a3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"a3","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageSizeA3"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKPDFRendererPageSizeA3","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKPDFRendererPageSizeA3","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKPDFRendererPageSizeA3","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/title","value":"SBSDKPDFRendererPageSize"},{"op":"replace","value":[{"text":"SBSDKPDFRendererPageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/fragments"},{"op":"replace","value":[{"text":"SBSDKPDFRendererPageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/navigatorTitle"},{"op":"replace","value":"SBSDKPDFRendererPageSizeA3","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize~1a3\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize~1a3\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFRendererPageSizeA3"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}