{"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize@SBSDKPDFRendererPageSizeA5","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"a5"}],"navigatorTitle":[{"text":"SBSDKPDFRendererPageSizeA5","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","role":"symbol","title":"SBSDKPDFRendererPageSize.a5"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/a5"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/a5"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"a5"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The page has A5 size: 148x210 mm. The image is fitted and centered within the page."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/a5","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageSize/a5":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"a5"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/a5","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageSizeA5"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/a5","abstract":[{"text":"The page has A5 size: 148x210 mm. The image is fitted and centered within the page.","type":"text"}],"title":"SBSDKPDFRendererPageSize.a5"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageSize":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFRendererPageSize"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKPDFRendererPageSize","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize","abstract":[{"text":"Specifies the desired page size (media box size) for PDF rendering operations.","type":"text"}],"title":"SBSDKPDFRendererPageSize"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"SBSDKPDFRendererPageSizeA5","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFRendererPageSizeA5"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKPDFRendererPageSizeA5","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKPDFRendererPageSizeA5","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize~1a5\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize~1a5\/fragments","value":[{"text":"SBSDKPDFRendererPageSizeA5","kind":"identifier"}]},{"op":"replace","value":"SBSDKPDFRendererPageSize","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/title"},{"value":[{"text":"SBSDKPDFRendererPageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}