{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/us4x6"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/us4x6"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"us4x6"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/us4x6"},"metadata":{"role":"symbol","roleHeading":"Case","title":"SBSDKPDFRendererPageSize.us4x6","externalID":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize@SBSDKPDFRendererPageSizeUs4x6","symbolKind":"case","navigatorTitle":[{"text":"SBSDKPDFRendererPageSizeUs4x6","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"us4x6"}],"modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize"]]},"sections":[],"abstract":[{"type":"text","text":"The page has US 4x6 size: 4x6 inches. The image is fitted and centered within the page."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageSize":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFRendererPageSize"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKPDFRendererPageSize","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize","abstract":[{"text":"Specifies the desired page size (media box size) for PDF rendering operations.","type":"text"}],"title":"SBSDKPDFRendererPageSize"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageSize/us4x6":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"us4x6"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/us4x6","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKPDFRendererPageSizeUs4x6","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/us4x6","abstract":[{"text":"The page has US 4x6 size: 4x6 inches. The image is fitted and centered within the page.","type":"text"}],"title":"SBSDKPDFRendererPageSize.us4x6"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKPDFRendererPageSizeUs4x6"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKPDFRendererPageSizeUs4x6","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKPDFRendererPageSizeUs4x6"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKPDFRendererPageSize","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/fragments","value":[{"text":"SBSDKPDFRendererPageSize","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize~1us4x6\/title","value":"SBSDKPDFRendererPageSizeUs4x6"},{"value":[{"kind":"identifier","text":"SBSDKPDFRendererPageSizeUs4x6"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize~1us4x6\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}