{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/us4x8","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"us4x8"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize@SBSDKPDFRendererPageSizeUs4x8","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageSizeUs4x8"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"us4x8"}],"roleHeading":"Case","title":"SBSDKPDFRendererPageSize.us4x8","modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"case"},"abstract":[{"type":"text","text":"The page has US 4x8 size: 4x8 inches. The image is fitted and centered within the page."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/us4x8"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/us4x8"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageSize/us4x8":{"navigatorTitle":[{"text":"SBSDKPDFRendererPageSizeUs4x8","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"us4x8"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/us4x8","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/us4x8","role":"symbol","abstract":[{"type":"text","text":"The page has US 4x8 size: 4x8 inches. The image is fitted and centered within the page."}],"title":"SBSDKPDFRendererPageSize.us4x8"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageSize":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize","navigatorTitle":[{"text":"SBSDKPDFRendererPageSize","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Specifies the desired page size (media box size) for PDF rendering operations.","type":"text"}],"title":"SBSDKPDFRendererPageSize","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRendererPageSize","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKPDFRendererPageSizeUs4x8","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKPDFRendererPageSizeUs4x8","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKPDFRendererPageSizeUs4x8"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize~1us4x8\/title","value":"SBSDKPDFRendererPageSizeUs4x8","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize~1us4x8\/fragments","value":[{"text":"SBSDKPDFRendererPageSizeUs4x8","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/title","value":"SBSDKPDFRendererPageSize"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFRendererPageSize"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPDFRendererPageSize"}]}]}]}