{"metadata":{"roleHeading":"Case","title":"SBSDKHealthInsuranceCardDetectionStatus.failedDetection","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedDetection"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKHealthInsuranceCardDetectionStatus@SBSDKHealthInsuranceCardDetectionStatusFailedDetection","role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardDetectionStatusFailedDetection","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"failedDetection","kind":"identifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardDetectionStatus\/failedDetection"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecarddetectionstatus\/faileddetection"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecarddetectionstatus\/faileddetection"]}],"kind":"symbol","abstract":[{"text":"No document found or the document doesn’t look like the back of a health insurance card.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardDetectionStatus"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardDetectionStatus":{"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecarddetectionstatus","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKHealthInsuranceCardDetectionStatus","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardDetectionStatus","kind":"identifier"}],"title":"SBSDKHealthInsuranceCardDetectionStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardDetectionStatus","role":"symbol","abstract":[{"type":"text","text":"The health insurance card detection status."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardDetectionStatus/failedDetection":{"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecarddetectionstatus\/faileddetection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardDetectionStatus\/failedDetection","type":"topic","role":"symbol","kind":"symbol","title":"SBSDKHealthInsuranceCardDetectionStatus.failedDetection","abstract":[{"type":"text","text":"No document found or the document doesn’t look like the back of a health insurance card."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"failedDetection","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardDetectionStatusFailedDetection","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"SBSDKHealthInsuranceCardDetectionStatusFailedDetection","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"text":"SBSDKHealthInsuranceCardDetectionStatusFailedDetection","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardDetectionStatusFailedDetection"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardDetectionStatus\/title","value":"SBSDKHealthInsuranceCardDetectionStatus","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardDetectionStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardDetectionStatus\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardDetectionStatus\/navigatorTitle","value":[{"text":"SBSDKHealthInsuranceCardDetectionStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardDetectionStatus~1failedDetection\/title","op":"replace","value":"SBSDKHealthInsuranceCardDetectionStatusFailedDetection"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardDetectionStatus~1failedDetection\/fragments","value":[{"text":"SBSDKHealthInsuranceCardDetectionStatusFailedDetection","kind":"identifier"}],"op":"replace"}]}]}