{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecarddetectionstatus\/incompletevalidation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecarddetectionstatus\/incompletevalidation"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","roleHeading":"Case","title":"SBSDKHealthInsuranceCardDetectionStatus.incompleteValidation","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"incompleteValidation"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardDetectionStatusIncompleteValidation"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKHealthInsuranceCardDetectionStatus@SBSDKHealthInsuranceCardDetectionStatusIncompleteValidation"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardDetectionStatus"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardDetectionStatus\/incompleteValidation","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incompleteValidation","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"text":"A potential health insurance card was found but one or more fields failed validation.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardDetectionStatus/incompleteValidation":{"abstract":[{"text":"A potential health insurance card was found but one or more fields failed validation.","type":"text"}],"type":"topic","title":"SBSDKHealthInsuranceCardDetectionStatus.incompleteValidation","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"incompleteValidation"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardDetectionStatus\/incompleteValidation","navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardDetectionStatusIncompleteValidation"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecarddetectionstatus\/incompletevalidation","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardDetectionStatus":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardDetectionStatus"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardDetectionStatus"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardDetectionStatus","title":"SBSDKHealthInsuranceCardDetectionStatus","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecarddetectionstatus","abstract":[{"type":"text","text":"The health insurance card detection status."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKHealthInsuranceCardDetectionStatusIncompleteValidation","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKHealthInsuranceCardDetectionStatusIncompleteValidation","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"SBSDKHealthInsuranceCardDetectionStatusIncompleteValidation","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"SBSDKHealthInsuranceCardDetectionStatusIncompleteValidation","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardDetectionStatus~1incompleteValidation\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardDetectionStatus~1incompleteValidation\/fragments","op":"replace","value":[{"text":"SBSDKHealthInsuranceCardDetectionStatusIncompleteValidation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardDetectionStatus\/title","op":"replace","value":"SBSDKHealthInsuranceCardDetectionStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardDetectionStatus\/fragments","value":[{"text":"SBSDKHealthInsuranceCardDetectionStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardDetectionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardDetectionStatus"}],"op":"replace"}]}]}