{"kind":"symbol","metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthDate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentDeIdCardFront(py)birthDate","title":"birthDate","navigatorTitle":[{"kind":"identifier","text":"birthDate"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeIdCardFront"]]},"abstract":[{"type":"text","text":"Birth date."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"birthDate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentdeidcardfront\/birthdate"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentdeidcardfront\/birthdate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeIdCardFront\/birthDate"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentDeIdCardFront":{"title":"SBSDKGenericDocumentDeIdCardFront","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeIdCardFront","abstract":[{"type":"text","text":"German ID card, front side."}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentDeIdCardFront"}],"type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocumentDeIdCardFront","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentdeidcardfront"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentDeIdCardFront/birthDate":{"abstract":[{"type":"text","text":"Birth date."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentdeidcardfront\/birthdate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"birthDate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic","title":"birthDate","navigatorTitle":[{"kind":"identifier","text":"birthDate"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeIdCardFront\/birthDate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"type":"topic","abstract":[{"text":"A generic document field.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","kind":"symbol","role":"symbol","title":"SBSDKGenericDocumentField"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"birthDate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"birthDate"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"birthDate"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeIdCardFront\/title","value":"SBSDKGenericDocumentDeIdCardFront","op":"replace"},{"value":[{"text":"SBSDKGenericDocumentDeIdCardFront","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeIdCardFront\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeIdCardFront~1birthDate\/title","value":"birthDate","op":"replace"},{"value":[{"text":"birthDate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeIdCardFront~1birthDate\/fragments","op":"replace"},{"op":"replace","value":"SBSDKGenericDocumentField","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}]}]}]}