{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraBottomBar\/initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:"},"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:"}],"title":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CameraBottomBar(im)initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraBottomBar"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerabottombar\/initwithimportbutton:autosnappingmodebutton:manualsnappingmodebutton:shutterbutton:torchonbutton:torchoffbutton:previewbutton:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithImportButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"importButton"},{"text":" ","kind":"text"},{"text":"autoSnappingModeButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"autoSnappingModeButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"manualSnappingModeButton:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"manualSnappingModeButton"},{"kind":"text","text":" "},{"text":"shutterButton:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ShutterButton","kind":"typeIdentifier","text":"SBSDKUI2ShutterButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ShutterButton"},{"text":" *) ","kind":"text"},{"text":"shutterButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"torchOnButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","text":"SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"torchOnButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"torchOffButton:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"torchOffButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewButton:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PreviewButton","kind":"typeIdentifier","text":"SBSDKUI2PreviewButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PreviewButton"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"previewButton"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2BarButtonConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the button located on a bar."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2barbuttonconfiguration","kind":"symbol","type":"topic","title":"SBSDKUI2BarButtonConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraBottomBar/initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerabottombar\/initwithimportbutton:autosnappingmodebutton:manualsnappingmodebutton:shutterbutton:torchonbutton:torchoffbutton:previewbutton:","abstract":[],"title":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraBottomBar\/initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","navigatorTitle":[{"text":"initWithImportButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraBottomBar":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}],"abstract":[{"type":"text","text":"Configuration of the bottom bar for the camera screen."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerabottombar","kind":"symbol","type":"topic","title":"SBSDKUI2CameraBottomBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2CameraBottomBar","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraBottomBar"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ShutterButton":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2ShutterButton","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2shutterbutton","abstract":[{"type":"text","text":"Configuration of the ‘shutter’ button."}],"title":"SBSDKUI2ShutterButton","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ShutterButton","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ShutterButton"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PreviewButton":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PreviewButton"}],"abstract":[{"type":"text","text":"Configuration of the ‘preview’ button."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2previewbutton","kind":"symbol","type":"topic","title":"SBSDKUI2PreviewButton","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2PreviewButton"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PreviewButton"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BarButtonConfiguration\/title","value":"SBSDKUI2BarButtonConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BarButtonConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BarButtonConfiguration\/navigatorTitle","op":"replace"},{"op":"replace","value":"SBSDKUI2CameraBottomBar","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraBottomBar\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraBottomBar\/fragments","op":"replace","value":[{"text":"SBSDKUI2CameraBottomBar","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraBottomBar\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ShutterButton\/title","op":"replace","value":"SBSDKUI2ShutterButton"},{"value":[{"text":"SBSDKUI2ShutterButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ShutterButton\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ShutterButton\/navigatorTitle","value":[{"text":"SBSDKUI2ShutterButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PreviewButton\/title","value":"SBSDKUI2PreviewButton","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2PreviewButton"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PreviewButton\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2PreviewButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PreviewButton\/navigatorTitle"}]}]}