{"sections":[],"abstract":[{"type":"text","text":"Interpolate between seen values to generate the most likely true value."},{"text":" ","type":"text"},{"type":"text","text":"E.g. if the seen values are “John X. Doe”, “John B.”, “B. Doe” then the most likely true value"},{"text":" ","type":"text"},{"text":"can be interpolated to be “John B. Doe”.","type":"text"},{"text":" ","type":"text"},{"text":"The interpolated value is considered CONFIRMED if each character","type":"text"},{"type":"text","text":" "},{"text":"in it has been seen at least minConfirmations times.","type":"text"}],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKConfirmationMethod@SBSDKConfirmationMethodInterpolate","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interpolate"}],"roleHeading":"Case","role":"symbol","symbolKind":"case","title":"SBSDKConfirmationMethod.interpolate","navigatorTitle":[{"text":"SBSDKConfirmationMethodInterpolate","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkconfirmationmethod\/interpolate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkconfirmationmethod\/interpolate"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"interpolate"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod\/interpolate"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConfirmationMethod/interpolate":{"role":"symbol","navigatorTitle":[{"text":"SBSDKConfirmationMethodInterpolate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod\/interpolate","url":"\/documentation\/scanbotsdk\/sbsdkconfirmationmethod\/interpolate","type":"topic","abstract":[{"text":"Interpolate between seen values to generate the most likely true value.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"E.g. if the seen values are “John X. Doe”, “John B.”, “B. Doe” then the most likely true value"},{"text":" ","type":"text"},{"text":"can be interpolated to be “John B. Doe”.","type":"text"},{"text":" ","type":"text"},{"text":"The interpolated value is considered CONFIRMED if each character","type":"text"},{"text":" ","type":"text"},{"text":"in it has been seen at least minConfirmations times.","type":"text"}],"title":"SBSDKConfirmationMethod.interpolate","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interpolate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConfirmationMethod":{"kind":"symbol","type":"topic","title":"SBSDKConfirmationMethod","url":"\/documentation\/scanbotsdk\/sbsdkconfirmationmethod","abstract":[{"text":"Method used to confirm a result.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKConfirmationMethod"}],"navigatorTitle":[{"text":"SBSDKConfirmationMethod","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKConfirmationMethodInterpolate","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKConfirmationMethodInterpolate","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKConfirmationMethodInterpolate"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod~1interpolate\/title","value":"SBSDKConfirmationMethodInterpolate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod~1interpolate\/fragments","value":[{"kind":"identifier","text":"SBSDKConfirmationMethodInterpolate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod\/title","value":"SBSDKConfirmationMethod"},{"value":[{"text":"SBSDKConfirmationMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod\/navigatorTitle","value":[{"text":"SBSDKConfirmationMethod","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}