{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateIntroImage\/fromJsonWithJson:","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateIntroImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MedicalCertificateIntroImage","text":"SBSDKUI2MedicalCertificateIntroImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromJsonWithJson:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"json"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"role":"symbol","title":"fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MedicalCertificateIntroImage(cm)fromJsonWithJson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateIntroImage"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2medicalcertificateintroimage\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateIntroImage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MedicalCertificateIntroImage","kind":"identifier"}],"abstract":[{"text":"The image for the introduction screen with a medical certificate template.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateIntroImage","type":"topic","title":"SBSDKUI2MedicalCertificateIntroImage","url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificateintroimage","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2MedicalCertificateIntroImage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateIntroImage/fromJsonWithJson:":{"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateIntroImage\/fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificateintroimage\/fromjsonwithjson:","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"type":"topic","title":"fromJsonWithJson:","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateIntroImage\/title","value":"SBSDKUI2MedicalCertificateIntroImage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateIntroImage\/fragments","value":[{"text":"SBSDKUI2MedicalCertificateIntroImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateIntroImage\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateIntroImage"}],"op":"replace"}]}]}