{"abstract":[{"type":"text","text":"Cleans up the background and tries to preserve photos within the image."},{"type":"text","text":" "},{"type":"text","text":"Usecase: magazine pages, flyers."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/backgroundclean"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/backgroundclean"]}],"metadata":{"roleHeading":"Case","platforms":[],"role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFilterType@SBSDKImageFilterTypeBackgroundClean","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundClean"}],"title":"SBSDKImageFilterType.backgroundClean","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeBackgroundClean"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/backgroundClean","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundClean","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please consider using the new class-based SBSDKParametricFilters."}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/backgroundClean":{"title":"SBSDKImageFilterType.backgroundClean","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/backgroundClean","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/backgroundclean","role":"symbol","deprecated":true,"kind":"symbol","abstract":[{"type":"text","text":"Cleans up the background and tries to preserve photos within the image."},{"type":"text","text":" "},{"type":"text","text":"Usecase: magazine pages, flyers."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundClean","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKImageFilterTypeBackgroundClean","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType":{"title":"SBSDKImageFilterType","abstract":[{"type":"text","text":"The ScanbotSDK image filter types."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFilterType"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"type":"topic","deprecated":true}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKImageFilterTypeBackgroundClean"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeBackgroundClean"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKImageFilterTypeBackgroundClean"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1backgroundClean\/title","value":"SBSDKImageFilterTypeBackgroundClean"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1backgroundClean\/fragments","value":[{"text":"SBSDKImageFilterTypeBackgroundClean","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/title","value":"SBSDKImageFilterType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/fragments","value":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}