{"sections":[],"abstract":[{"type":"text","text":"Standard grayscale filter. Creates a grayscaled 8-bit image and optimizes contrast and dynamic range."}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/gray"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/gray"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType"]]},"metadata":{"symbolKind":"case","roleHeading":"Case","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFilterType@SBSDKImageFilterTypeGray","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeGray"}],"title":"SBSDKImageFilterType.gray","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gray"}],"platforms":[]},"kind":"symbol","deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please consider using the new class-based SBSDKParametricFilters."}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/gray","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gray","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType":{"title":"SBSDKImageFilterType","abstract":[{"type":"text","text":"The ScanbotSDK image filter types."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFilterType"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"type":"topic","deprecated":true},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/gray":{"abstract":[{"text":"Standard grayscale filter. Creates a grayscaled 8-bit image and optimizes contrast and dynamic range.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/gray","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/gray","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeGray"}],"title":"SBSDKImageFilterType.gray","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gray"}],"type":"topic","deprecated":true},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKImageFilterTypeGray"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKImageFilterTypeGray","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKImageFilterTypeGray","kind":"identifier"}],"languages":["occ"]}]}},{"value":"SBSDKImageFilterType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/title"},{"value":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/fragments"},{"value":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/navigatorTitle"},{"value":"SBSDKImageFilterTypeGray","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1gray\/title"},{"value":[{"text":"SBSDKImageFilterTypeGray","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1gray\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}