{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardIntroImage","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKUI2CreditCardIntroImage","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CreditCardIntroImage","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CreditCardIntroImage"}],"languages":["swift"]}]}],"kind":"symbol","metadata":{"symbolKind":"method","title":"creditCardIntroImage()","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardIntroImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKUI2CreditCardIntroImage","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CreditCardIntroImage","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"creditCardIntroImage","kind":"identifier"}],"roleHeading":"Type Method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IntroImage(cm)creditCardIntroImage","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2introimage\/creditcardintroimage()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2introimage\/creditcardintroimage()"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IntroImage"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IntroImage\/creditCardIntroImage()","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.1.1","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2IntroImage/creditCardIntroImage()":{"title":"creditCardIntroImage()","navigatorTitle":[{"text":"creditCardIntroImage","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IntroImage\/creditCardIntroImage()","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2introimage\/creditcardintroimage()","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardIntroImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CreditCardIntroImage","text":"SBSDKUI2CreditCardIntroImage","kind":"typeIdentifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2IntroImage":{"title":"SBSDKUI2IntroImage","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IntroImage","role":"symbol","abstract":[{"type":"text","text":"Determines the image for the introduction screen."}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2IntroImage","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2introimage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IntroImage"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CreditCardIntroImage":{"role":"symbol","title":"SBSDKUI2CreditCardIntroImage","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2creditcardintroimage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardIntroImage"}],"abstract":[{"text":"The image for the introduction screen with a credit card template.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CreditCardIntroImage","navigatorTitle":[{"text":"SBSDKUI2CreditCardIntroImage","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"creditCardIntroImage","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"text":"creditCardIntroImage","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CreditCardIntroImage","text":"SBSDKUI2CreditCardIntroImage","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CreditCardIntroImage"},{"kind":"text","text":" *) "},{"text":"creditCardIntroImage","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IntroImage~1creditCardIntroImage()\/title","value":"creditCardIntroImage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IntroImage~1creditCardIntroImage()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"creditCardIntroImage","kind":"identifier"}]},{"value":"SBSDKUI2IntroImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IntroImage\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IntroImage\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IntroImage"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2IntroImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IntroImage\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CreditCardIntroImage\/title","op":"replace","value":"SBSDKUI2CreditCardIntroImage"},{"value":[{"kind":"identifier","text":"SBSDKUI2CreditCardIntroImage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CreditCardIntroImage\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CreditCardIntroImage\/navigatorTitle","value":[{"text":"SBSDKUI2CreditCardIntroImage","kind":"identifier"}],"op":"replace"}]}]}