{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ccittrle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode","text":"SBSDKCompressionMode","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Type Property","symbolKind":"property","title":"ccittrle","role":"symbol","navigatorTitle":[{"text":"ccittrle","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ccittrle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCompressionMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode(cpy)ccittrle"},"sections":[],"abstract":[{"text":"CCITT modified Huffman RLE. For binarized images only.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode\/ccittrle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode\/ccittrle"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/ccittrle","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCompressionMode":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCompressionMode","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"TIFF compression type.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode","navigatorTitle":[{"text":"SBSDKCompressionMode","kind":"identifier"}],"title":"SBSDKCompressionMode","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCompressionMode/ccittrle":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode\/ccittrle","abstract":[{"text":"CCITT modified Huffman RLE. For binarized images only.","type":"text"}],"title":"ccittrle","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/ccittrle","navigatorTitle":[{"kind":"identifier","text":"ccittrle"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ccittrle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCompressionMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"ccittrle","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ccittrle","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode","text":"SBSDKCompressionMode"},{"kind":"text","text":" * "},{"kind":"identifier","text":"ccittrle"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode\/title","op":"replace","value":"SBSDKCompressionMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCompressionMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKCompressionMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1ccittrle\/title","op":"replace","value":"ccittrle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1ccittrle\/fragments","op":"replace","value":[{"text":"ccittrle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}