{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"importedImageQualityResult"}],"title":"importedImageQualityResult","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAnalyticsEventFactory(cpy)importedImageQualityResult","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Type Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"importedImageQualityResult"},{"text":": ","kind":"text"},{"text":"SBSDKAnalyticsEvent","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAnalyticsEvent","kind":"typeIdentifier"}]},"kind":"symbol","abstract":[{"type":"text","text":"A predefined analytics event."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsEventFactory\/importedImageQualityResult","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsEventFactory"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"importedImageQualityResult","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsEvent","kind":"typeIdentifier","text":"SBSDKAnalyticsEvent","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAnalyticsEvent"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticseventfactory\/importedimagequalityresult"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticseventfactory\/importedimagequalityresult"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAnalyticsEvent":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsEvent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKAnalyticsEvent","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKAnalyticsEvent"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticsevent","title":"SBSDKAnalyticsEvent","abstract":[{"type":"text","text":"The event that is being tracked."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAnalyticsEventFactory/importedImageQualityResult":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsEventFactory\/importedImageQualityResult","abstract":[{"text":"A predefined analytics event.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"importedImageQualityResult","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticseventfactory\/importedimagequalityresult","type":"topic","title":"importedImageQualityResult","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"importedImageQualityResult","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKAnalyticsEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAnalyticsEvent"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAnalyticsEventFactory":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKAnalyticsEventFactory"}],"abstract":[{"text":"A predefined analytics event.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKAnalyticsEventFactory"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticseventfactory","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsEventFactory","title":"SBSDKAnalyticsEventFactory"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"importedImageQualityResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"importedImageQualityResult","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsEvent","kind":"typeIdentifier","text":"SBSDKAnalyticsEvent","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAnalyticsEvent"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"importedImageQualityResult"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKAnalyticsEvent","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsEvent\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsEvent\/fragments","value":[{"kind":"identifier","text":"SBSDKAnalyticsEvent"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsEvent\/navigatorTitle","value":[{"text":"SBSDKAnalyticsEvent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsEventFactory~1importedImageQualityResult\/title","value":"importedImageQualityResult","op":"replace"},{"op":"replace","value":[{"text":"importedImageQualityResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsEventFactory~1importedImageQualityResult\/fragments"},{"value":"SBSDKAnalyticsEventFactory","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsEventFactory\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsEventFactory\/fragments","value":[{"text":"SBSDKAnalyticsEventFactory","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKAnalyticsEventFactory"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsEventFactory\/navigatorTitle"}]}]}