{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriteruserdefinedfieldtype\/numeric"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriteruserdefinedfieldtype\/numeric"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"A numeric field type."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterUserDefinedFieldType"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"numeric"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterUserDefinedFieldType\/numeric","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"SBSDKTIFFImageWriterUserDefinedFieldTypeNumeric","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKTIFFImageWriterUserDefinedFieldType@SBSDKTIFFImageWriterUserDefinedFieldTypeNumeric","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numeric","kind":"identifier"}],"role":"symbol","title":"SBSDKTIFFImageWriterUserDefinedFieldType.numeric"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterUserDefinedFieldType":{"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriteruserdefinedfieldtype","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterUserDefinedFieldType","title":"SBSDKTIFFImageWriterUserDefinedFieldType","role":"symbol","navigatorTitle":[{"text":"SBSDKTIFFImageWriterUserDefinedFieldType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTIFFImageWriterUserDefinedFieldType"}],"abstract":[{"text":"Custom TIFF field type.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterUserDefinedFieldType/numeric":{"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriteruserdefinedfieldtype\/numeric","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterUserDefinedFieldType\/numeric","navigatorTitle":[{"text":"SBSDKTIFFImageWriterUserDefinedFieldTypeNumeric","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"numeric","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"SBSDKTIFFImageWriterUserDefinedFieldType.numeric","abstract":[{"type":"text","text":"A numeric field type."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKTIFFImageWriterUserDefinedFieldTypeNumeric"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterUserDefinedFieldTypeNumeric"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKTIFFImageWriterUserDefinedFieldTypeNumeric","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedFieldType\/title","op":"replace","value":"SBSDKTIFFImageWriterUserDefinedFieldType"},{"value":[{"text":"SBSDKTIFFImageWriterUserDefinedFieldType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedFieldType\/fragments"},{"op":"replace","value":"SBSDKTIFFImageWriterUserDefinedFieldTypeNumeric","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedFieldType~1numeric\/title"},{"value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterUserDefinedFieldTypeNumeric"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedFieldType~1numeric\/fragments"}]}]}