{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterUserDefinedFieldType\/string","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Case","title":"SBSDKTIFFImageWriterUserDefinedFieldType.string","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"string"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterUserDefinedFieldTypeString"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKTIFFImageWriterUserDefinedFieldType@SBSDKTIFFImageWriterUserDefinedFieldTypeString","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"string","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterUserDefinedFieldType"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriteruserdefinedfieldtype\/string"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriteruserdefinedfieldtype\/string"]}],"kind":"symbol","abstract":[{"text":"A string based field type.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterUserDefinedFieldType/string":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"string"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriteruserdefinedfieldtype\/string","abstract":[{"text":"A string based field type.","type":"text"}],"role":"symbol","title":"SBSDKTIFFImageWriterUserDefinedFieldType.string","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterUserDefinedFieldType\/string","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterUserDefinedFieldTypeString"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterUserDefinedFieldType":{"title":"SBSDKTIFFImageWriterUserDefinedFieldType","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriteruserdefinedfieldtype","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterUserDefinedFieldType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFImageWriterUserDefinedFieldType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKTIFFImageWriterUserDefinedFieldType","kind":"identifier"}],"type":"topic","abstract":[{"text":"Custom TIFF field type.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"SBSDKTIFFImageWriterUserDefinedFieldTypeString","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"SBSDKTIFFImageWriterUserDefinedFieldTypeString","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKTIFFImageWriterUserDefinedFieldTypeString","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedFieldType~1string\/title","value":"SBSDKTIFFImageWriterUserDefinedFieldTypeString"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedFieldType~1string\/fragments","value":[{"text":"SBSDKTIFFImageWriterUserDefinedFieldTypeString","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedFieldType\/title","value":"SBSDKTIFFImageWriterUserDefinedFieldType"},{"value":[{"text":"SBSDKTIFFImageWriterUserDefinedFieldType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedFieldType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}