{"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"wordBoxesLineColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"wordBoxesLineColor","kind":"identifier"}],"symbolKind":"property","title":"wordBoxesLineColor","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerViewController(py)wordBoxesLineColor","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"text":"The color of word boxes border lines.","type":"text"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"wordBoxesLineColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController\/wordBoxesLineColor","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontroller\/wordboxeslinecolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontroller\/wordboxeslinecolor"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericTextLineRecognizerViewController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewController"}],"title":"SBSDKGenericTextLineRecognizerViewController","abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show a camera screen with the text line recognizer."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerViewController/wordBoxesLineColor":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController\/wordBoxesLineColor","navigatorTitle":[{"text":"wordBoxesLineColor","kind":"identifier"}],"type":"topic","title":"wordBoxesLineColor","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontroller\/wordboxeslinecolor","role":"symbol","abstract":[{"type":"text","text":"The color of word boxes border lines."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"wordBoxesLineColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"wordBoxesLineColor","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"wordBoxesLineColor","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"wordBoxesLineColor","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController\/title","value":"SBSDKGenericTextLineRecognizerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewController"}]},{"value":[{"text":"SBSDKGenericTextLineRecognizerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController~1wordBoxesLineColor\/title","op":"replace","value":"wordBoxesLineColor"},{"value":[{"text":"wordBoxesLineColor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController~1wordBoxesLineColor\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}