{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerPolygonConfiguration"]]},"abstract":[{"text":"The radius to use when drawing rounded corners of the polygon.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Defaults to 8.0."}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerPolygonConfiguration\/cornerRadius"},"metadata":{"role":"symbol","navigatorTitle":[{"text":"cornerRadius","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"cornerRadius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerPolygonConfiguration(py)cornerRadius","roleHeading":"Instance Property","symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerpolygonconfiguration\/cornerradius"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerpolygonconfiguration\/cornerradius"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerPolygonConfiguration":{"abstract":[{"text":"Configuration for the polygon displayed over the scanned document.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerPolygonConfiguration"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerPolygonConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerPolygonConfiguration","type":"topic","title":"SBSDKDocumentScannerPolygonConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerpolygonconfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","abstract":[{"text":"Version: 8.0.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerPolygonConfiguration/cornerRadius":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerpolygonconfiguration\/cornerradius","abstract":[{"text":"The radius to use when drawing rounded corners of the polygon.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cornerRadius"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerPolygonConfiguration\/cornerRadius","title":"cornerRadius","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"cornerRadius","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"cornerRadius"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"text":" ","kind":"text"},{"text":"cornerRadius","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKDocumentScannerPolygonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerPolygonConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKDocumentScannerPolygonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerPolygonConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentScannerPolygonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerPolygonConfiguration\/navigatorTitle"},{"op":"replace","value":"cornerRadius","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerPolygonConfiguration~1cornerRadius\/title"},{"op":"replace","value":[{"text":"cornerRadius","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerPolygonConfiguration~1cornerRadius\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}