{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/cancelButtonTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/errorAlertButtonText","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/errorAlertMessage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/errorAlertTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/flashButtonTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/userGuidanceTitleEnergySaving","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/userGuidanceTitleSearching","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/userGuidanceTitleStartScanning"],"anchor":"Instance-Properties","title":"Instance Properties"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUICheckScannerTextConfiguration","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUICheckScannerTextConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckScannerTextConfiguration"}],"roleHeading":"Class","symbolKind":"class","title":"SBSDKUICheckScannerTextConfiguration","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerTextConfiguration","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","abstract":[{"type":"text","text":"Configuration for the textual contents of the  RTU-UI check scanner."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannertextconfiguration"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannertextconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerTextConfiguration/userGuidanceTitleEnergySaving":{"navigatorTitle":[{"kind":"identifier","text":"userGuidanceTitleEnergySaving"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userGuidanceTitleEnergySaving"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannertextconfiguration\/userguidancetitleenergysaving","title":"userGuidanceTitleEnergySaving","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/userGuidanceTitleEnergySaving","abstract":[{"type":"text","text":"String being displayed when energy saving is active."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerTextConfiguration/cancelButtonTitle":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancelButtonTitle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannertextconfiguration\/cancelbuttontitle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/cancelButtonTitle","navigatorTitle":[{"kind":"identifier","text":"cancelButtonTitle"}],"kind":"symbol","abstract":[{"type":"text","text":"String being displayed on the cancel button."}],"title":"cancelButtonTitle","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerTextConfiguration/errorAlertMessage":{"type":"topic","abstract":[{"type":"text","text":"String being displayed as the message in the error alert that may occur when the scanning fails on captured high-resolution images."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorAlertMessage"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"errorAlertMessage"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/errorAlertMessage","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannertextconfiguration\/erroralertmessage","title":"errorAlertMessage","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerTextConfiguration/userGuidanceTitleSearching":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userGuidanceTitleSearching"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannertextconfiguration\/userguidancetitlesearching","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/userGuidanceTitleSearching","navigatorTitle":[{"text":"userGuidanceTitleSearching","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"String being displayed when searching for a medical certificate."}],"title":"userGuidanceTitleSearching","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerTextConfiguration":{"type":"topic","abstract":[{"type":"text","text":"Configuration for the textual contents of the  RTU-UI check scanner."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUICheckScannerTextConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckScannerTextConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannertextconfiguration","title":"SBSDKUICheckScannerTextConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerTextConfiguration/userGuidanceTitleStartScanning":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"userGuidanceTitleStartScanning","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannertextconfiguration\/userguidancetitlestartscanning","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/userGuidanceTitleStartScanning","navigatorTitle":[{"text":"userGuidanceTitleStartScanning","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"String being displayed when starting scanning for a medical certificate. Lasts 3 secs."}],"title":"userGuidanceTitleStartScanning","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerTextConfiguration/init":{"type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/init","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannertextconfiguration\/init","title":"init","kind":"symbol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerTextConfiguration/errorAlertButtonText":{"type":"topic","abstract":[{"type":"text","text":"String being displayed as the button text in the error alert that may occur when the scanning fails on captured high-resolution images."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorAlertButtonText"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"errorAlertButtonText","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/errorAlertButtonText","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannertextconfiguration\/erroralertbuttontext","title":"errorAlertButtonText","kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIEnableCameraTextConfiguration":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuienablecameratextconfiguration","abstract":[{"text":"Configuration for the textual contents of camera based view controllers.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"title":"SBSDKUIEnableCameraTextConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerTextConfiguration/flashButtonTitle":{"type":"topic","abstract":[{"type":"text","text":"String being displayed on the flash button."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"flashButtonTitle"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"flashButtonTitle"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/flashButtonTitle","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannertextconfiguration\/flashbuttontitle","title":"flashButtonTitle","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerTextConfiguration/errorAlertTitle":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorAlertTitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannertextconfiguration\/erroralerttitle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/errorAlertTitle","navigatorTitle":[{"text":"errorAlertTitle","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"String being displayed as the title in the error alert that may occur when the scannning fails on captured high-resolution images."}],"title":"errorAlertTitle","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUICheckScannerTextConfiguration"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUICheckScannerTextConfiguration"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUICheckScannerTextConfiguration","kind":"identifier"}],"op":"replace"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/cancelButtonTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/errorAlertButtonText","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/errorAlertMessage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/errorAlertTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/flashButtonTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/userGuidanceTitleEnergySaving","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/userGuidanceTitleSearching","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/userGuidanceTitleStartScanning"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/init"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration"],"type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICheckScannerTextConfiguration"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIEnableCameraTextConfiguration","text":"SBSDKUIEnableCameraTextConfiguration","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration~1userGuidanceTitleEnergySaving\/title","value":"userGuidanceTitleEnergySaving"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration~1userGuidanceTitleEnergySaving\/fragments","value":[{"kind":"identifier","text":"userGuidanceTitleEnergySaving"}]},{"value":"cancelButtonTitle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration~1cancelButtonTitle\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration~1cancelButtonTitle\/fragments","value":[{"text":"cancelButtonTitle","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"errorAlertMessage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration~1errorAlertMessage\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration~1errorAlertMessage\/fragments","value":[{"text":"errorAlertMessage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration~1userGuidanceTitleSearching\/title","value":"userGuidanceTitleSearching","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration~1userGuidanceTitleSearching\/fragments","value":[{"kind":"identifier","text":"userGuidanceTitleSearching"}],"op":"replace"},{"value":"SBSDKUICheckScannerTextConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUICheckScannerTextConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUICheckScannerTextConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration~1userGuidanceTitleStartScanning\/title","op":"replace","value":"userGuidanceTitleStartScanning"},{"value":[{"text":"userGuidanceTitleStartScanning","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration~1userGuidanceTitleStartScanning\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration~1errorAlertButtonText\/title","op":"replace","value":"errorAlertButtonText"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration~1errorAlertButtonText\/fragments","op":"replace","value":[{"kind":"identifier","text":"errorAlertButtonText"}]},{"value":"SBSDKUIEnableCameraTextConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}]},{"op":"replace","value":"flashButtonTitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration~1flashButtonTitle\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration~1flashButtonTitle\/fragments","value":[{"text":"flashButtonTitle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration~1errorAlertTitle\/title","value":"errorAlertTitle"},{"op":"replace","value":[{"text":"errorAlertTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration~1errorAlertTitle\/fragments"}]}]}