{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelCheck"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelcheck"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelcheck"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"],"type":"inheritsFrom"},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelCANCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelFRACheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelINDCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelISRCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelKWTCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelUAECheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelUSACheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelUnknownCheck"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCheckDocumentModelCheck"}]}]}],"kind":"symbol","topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelCheck\/fontType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelCheck\/rawString"],"generated":true}],"metadata":{"title":"SBSDKCheckDocumentModelCheck","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentModelCheck","modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckDocumentModelCheck"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCheckDocumentModelCheck","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"type":"text","text":"Check Document"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentWrapper":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","abstract":[{"text":"Base class for strongly-typed ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"},{"type":"text","text":" wrappers."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"type":"topic","role":"symbol","title":"SBSDKGenericDocumentWrapper"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelUSACheck":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckDocumentModelUSACheck","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCheckDocumentModelUSACheck","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelusacheck","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelUSACheck","role":"symbol","abstract":[{"text":"A check compatible with the ASC X9 standard used in the USA","type":"text"}],"type":"topic","title":"SBSDKCheckDocumentModelUSACheck"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelISRCheck":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckDocumentModelISRCheck"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelISRCheck","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelisrcheck","navigatorTitle":[{"text":"SBSDKCheckDocumentModelISRCheck","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"A check format commonly used in Israel","type":"text"}],"title":"SBSDKCheckDocumentModelISRCheck"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelKWTCheck":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelkwtcheck","type":"topic","abstract":[{"text":"A check format commonly used in Kuwait","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckDocumentModelKWTCheck"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckDocumentModelKWTCheck","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"SBSDKCheckDocumentModelKWTCheck","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelKWTCheck"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelFRACheck":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelfracheck","role":"symbol","abstract":[{"type":"text","text":"A check format commonly used in France"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCheckDocumentModelFRACheck"}],"title":"SBSDKCheckDocumentModelFRACheck","navigatorTitle":[{"text":"SBSDKCheckDocumentModelFRACheck","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelFRACheck","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","type":"topic","abstract":[{"type":"text","text":"Generic document."}],"title":"SBSDKGenericDocument","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelAUSCheck":{"abstract":[{"text":"A check compatible with the Australian Paper Clearing System cheque standard","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck","navigatorTitle":[{"text":"SBSDKCheckDocumentModelAUSCheck","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelauscheck","title":"SBSDKCheckDocumentModelAUSCheck","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckDocumentModelAUSCheck","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelUAECheck":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelUAECheck","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodeluaecheck","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckDocumentModelUAECheck"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckDocumentModelUAECheck"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A check format commonly used in the United Arab Emirates"}],"title":"SBSDKCheckDocumentModelUAECheck"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelCheck":{"kind":"symbol","title":"SBSDKCheckDocumentModelCheck","abstract":[{"text":"Check Document","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckDocumentModelCheck"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckDocumentModelCheck"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelCheck","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelcheck","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelUnknownCheck":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelunknowncheck","kind":"symbol","type":"topic","abstract":[{"text":"A check that doesn’t conform to any supported standard","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelUnknownCheck","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckDocumentModelUnknownCheck"}],"navigatorTitle":[{"text":"SBSDKCheckDocumentModelUnknownCheck","kind":"identifier"}],"title":"SBSDKCheckDocumentModelUnknownCheck"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelCheck/fontType":{"title":"fontType","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelcheck\/fonttype","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fontType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"fontType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelCheck\/fontType","abstract":[{"text":"type of check font","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelCheck/initWithGenericDocument:":{"abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelcheck\/initwithgenericdocument:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelCheck\/initWithGenericDocument:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithGenericDocument:"}],"type":"topic","title":"initWithGenericDocument:","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelCheck/rawString":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelcheck\/rawstring","abstract":[{"text":"Detected raw string","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelCheck\/rawString","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawString","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"type":"topic","title":"rawString","navigatorTitle":[{"kind":"identifier","text":"rawString"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelCANCheck":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKCheckDocumentModelCANCheck","kind":"identifier"}],"title":"SBSDKCheckDocumentModelCANCheck","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelCANCheck","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckDocumentModelCANCheck"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelcancheck","abstract":[{"text":"A check format commonly used in Canada","type":"text"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelINDCheck":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelindcheck","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelINDCheck","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckDocumentModelINDCheck"}],"title":"SBSDKCheckDocumentModelINDCheck","abstract":[{"type":"text","text":"A check compatible with the CTS-2010 standard issued by the Reserve Bank of India in 2012"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckDocumentModelINDCheck"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"SBSDKCheckDocumentModelCheck","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckDocumentModelCheck"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKCheckDocumentModelCheck","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelCheck\/fontType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelCheck\/rawString"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelCheck\/initWithGenericDocument:"],"anchor":"Instance-Methods"}]},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"],"kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelCANCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelFRACheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelINDCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelISRCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelKWTCheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelUAECheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelUSACheck","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelUnknownCheck"],"kind":"relationships","type":"inheritedBy","title":"Inherited By"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKCheckDocumentModelCheck","kind":"identifier"},{"kind":"text","text":" : "},{"text":"SBSDKGenericDocumentWrapper","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentWrapper","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKGenericDocumentWrapper","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/title","op":"replace"},{"value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/fragments","op":"replace"},{"value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelUSACheck\/title","value":"SBSDKCheckDocumentModelUSACheck","op":"replace"},{"value":[{"text":"SBSDKCheckDocumentModelUSACheck","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelUSACheck\/fragments"},{"value":[{"text":"SBSDKCheckDocumentModelUSACheck","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelUSACheck\/navigatorTitle","op":"replace"},{"op":"replace","value":"SBSDKCheckDocumentModelISRCheck","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelISRCheck\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelISRCheck\/fragments","value":[{"text":"SBSDKCheckDocumentModelISRCheck","kind":"identifier"}]},{"value":[{"text":"SBSDKCheckDocumentModelISRCheck","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelISRCheck\/navigatorTitle"},{"value":"SBSDKCheckDocumentModelKWTCheck","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelKWTCheck\/title"},{"value":[{"text":"SBSDKCheckDocumentModelKWTCheck","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelKWTCheck\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelKWTCheck\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCheckDocumentModelKWTCheck"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelFRACheck\/title","value":"SBSDKCheckDocumentModelFRACheck"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelFRACheck\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckDocumentModelFRACheck"}]},{"value":[{"text":"SBSDKCheckDocumentModelFRACheck","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelFRACheck\/navigatorTitle"},{"value":"SBSDKGenericDocument","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments"},{"value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","op":"replace"},{"value":"SBSDKCheckDocumentModelAUSCheck","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelAUSCheck\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelAUSCheck\/fragments","value":[{"text":"SBSDKCheckDocumentModelAUSCheck","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelAUSCheck\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCheckDocumentModelAUSCheck"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelUAECheck\/title","op":"replace","value":"SBSDKCheckDocumentModelUAECheck"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelUAECheck\/fragments","op":"replace","value":[{"text":"SBSDKCheckDocumentModelUAECheck","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKCheckDocumentModelUAECheck"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelUAECheck\/navigatorTitle"},{"op":"replace","value":"SBSDKCheckDocumentModelCheck","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelCheck\/title"},{"value":[{"kind":"identifier","text":"SBSDKCheckDocumentModelCheck"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelCheck\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCheckDocumentModelCheck"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelCheck\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelUnknownCheck\/title","value":"SBSDKCheckDocumentModelUnknownCheck","op":"replace"},{"value":[{"text":"SBSDKCheckDocumentModelUnknownCheck","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelUnknownCheck\/fragments"},{"value":[{"text":"SBSDKCheckDocumentModelUnknownCheck","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelUnknownCheck\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelCheck~1fontType\/title","value":"fontType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelCheck~1fontType\/fragments","value":[{"kind":"identifier","text":"fontType"}]},{"op":"replace","value":"rawString","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelCheck~1rawString\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelCheck~1rawString\/fragments","value":[{"text":"rawString","kind":"identifier"}],"op":"replace"},{"value":"SBSDKCheckDocumentModelCANCheck","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelCANCheck\/title","op":"replace"},{"value":[{"text":"SBSDKCheckDocumentModelCANCheck","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelCANCheck\/fragments","op":"replace"},{"value":[{"text":"SBSDKCheckDocumentModelCANCheck","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelCANCheck\/navigatorTitle"},{"value":"SBSDKCheckDocumentModelINDCheck","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelINDCheck\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelINDCheck\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckDocumentModelINDCheck"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelINDCheck\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCheckDocumentModelINDCheck"}],"op":"replace"}]}]}