{"topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocumentObserver\/scannedDocumentDidChange(_:)"],"title":"Instance Methods"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkscanneddocumentobserver"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkscanneddocumentobserver"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKScannedDocumentObserver","kind":"identifier"}],"roleHeading":"Protocol","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKScannedDocumentObserver","title":"SBSDKScannedDocumentObserver","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScannedDocumentObserver"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocumentObserver","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"A delegation-like protocol for observing changes on an instance of "},{"code":"SBSDKScannedDocument","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedDocumentObserver","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocumentObserver":{"title":"SBSDKScannedDocumentObserver","abstract":[{"text":"A delegation-like protocol for observing changes on an instance of ","type":"text"},{"code":"SBSDKScannedDocument","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkscanneddocumentobserver","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKScannedDocumentObserver","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocumentObserver","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKScannedDocumentObserver","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocumentObserver/scannedDocumentDidChange(_:)":{"title":"scannedDocumentDidChange(_:)","abstract":[{"type":"text","text":"Informs the observers that the document or one of its pages has been changed."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkscanneddocumentobserver\/scanneddocumentdidchange(_:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scannedDocumentDidChange:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocumentObserver\/scannedDocumentDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scannedDocumentDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKScannedDocumentObserver"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKScannedDocumentObserver"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKScannedDocumentObserver","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocumentObserver\/scannedDocumentDidChange(_:)"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScannedDocumentObserver"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKScannedDocumentObserver","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocumentObserver\/title","op":"replace"},{"value":[{"text":"SBSDKScannedDocumentObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocumentObserver\/fragments","op":"replace"},{"value":[{"text":"SBSDKScannedDocumentObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocumentObserver\/navigatorTitle","op":"replace"},{"value":"scannedDocumentDidChange:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocumentObserver~1scannedDocumentDidChange(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"scannedDocumentDidChange:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocumentObserver~1scannedDocumentDidChange(_:)\/fragments","op":"replace"}]}]}