{"metadata":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIEnableCameraTextConfiguration","title":"SBSDKUIEnableCameraTextConfiguration","roleHeading":"Class","navigatorTitle":[{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}],"symbolKind":"class"},"abstract":[{"text":"Configuration for the textual contents of camera based view controllers.","type":"text"}],"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Inherited By","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerTextConfiguration"],"type":"inheritedBy","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration\/enableCameraButtonTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration\/enableCameraExplanationText"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuienablecameratextconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuienablecameratextconfiguration"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerTextConfiguration":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMRZScannerTextConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMRZScannerTextConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannertextconfiguration","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerTextConfiguration","role":"symbol","title":"SBSDKUIMRZScannerTextConfiguration","abstract":[{"type":"text","text":"Configuration for the textual contents of the scanner screens for machine readable zones."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerTextConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannertextconfiguration","kind":"symbol","navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerTextConfiguration","kind":"identifier"}],"title":"SBSDKUIFinderDocumentScannerTextConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerTextConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for the textual contents of the document scanning screen."}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerTextConfiguration","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerTextConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerTextConfiguration"}],"title":"SBSDKUIHealthInsuranceCardRecognizerTextConfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizertextconfiguration","abstract":[{"text":"Configuration for the textual contents of the detector RTU-UI screen for Health Insurance Card scanner.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerTextConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerTextConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerTextConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerTextConfiguration"}],"role":"symbol","title":"SBSDKUIMedicalCertificateScannerTextConfiguration","abstract":[{"type":"text","text":"Configuration for the textual contents of the medical certificate recognizer."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannertextconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerTextConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIEnableCameraTextConfiguration/enableCameraButtonTitle":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableCameraButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"enableCameraButtonTitle","kind":"identifier"}],"title":"enableCameraButtonTitle","abstract":[{"type":"text","text":"The string being displayed on the button to request camera access."}],"url":"\/documentation\/scanbotsdk\/sbsdkuienablecameratextconfiguration\/enablecamerabuttontitle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration\/enableCameraButtonTitle","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIEnableCameraTextConfiguration/enableCameraExplanationText":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableCameraExplanationText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","title":"enableCameraExplanationText","abstract":[{"type":"text","text":"The string being displayed on the label describing the camera access requirement."}],"url":"\/documentation\/scanbotsdk\/sbsdkuienablecameratextconfiguration\/enablecameraexplanationtext","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"enableCameraExplanationText"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration\/enableCameraExplanationText"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIEnableCameraTextConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for the textual contents of camera based view controllers."}],"url":"\/documentation\/scanbotsdk\/sbsdkuienablecameratextconfiguration","type":"topic","role":"symbol","kind":"symbol","title":"SBSDKUIEnableCameraTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerTextConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerTextConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuivinscannertextconfiguration","title":"SBSDKUIVINScannerTextConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIVINScannerTextConfiguration"}],"abstract":[{"text":"The configuration for the textual contents of the RTU-UI vehicle identification number scanner.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIVINScannerTextConfiguration"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorTextConfiguration":{"type":"topic","title":"SBSDKUIDocumentDataExtractorTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractortextconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentDataExtractorTextConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUIDocumentDataExtractorTextConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorTextConfiguration","abstract":[{"text":"The configuration for the textual contents of the RTU-UI document data extractor screen.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIEnableCameraTextConfiguration/init":{"abstract":[],"type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration\/init","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuienablecameratextconfiguration\/init"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerTextConfiguration":{"role":"symbol","deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeScannerTextConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerTextConfiguration","title":"SBSDKUIBarcodeScannerTextConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannertextconfiguration","abstract":[{"text":"The configuration for the textual contents of the RTU-UI barcode scanner.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUIBarcodeScannerTextConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerTextConfiguration":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannertextconfiguration","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerTextConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUITextPatternScannerTextConfiguration","kind":"identifier"}],"title":"SBSDKUITextPatternScannerTextConfiguration","abstract":[{"type":"text","text":"Configuration for the textual contents of the RTU-UI text pattern scanner."}],"type":"topic","navigatorTitle":[{"text":"SBSDKUITextPatternScannerTextConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerTextConfiguration":{"abstract":[{"type":"text","text":"Configuration for the textual contents of the document scanning screen."}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannertextconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerTextConfiguration","role":"symbol","deprecated":true,"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerTextConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerTextConfiguration"}],"title":"SBSDKUIDocumentScannerTextConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerTextConfiguration":{"type":"topic","title":"SBSDKUICheckScannerTextConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckScannerTextConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration","navigatorTitle":[{"text":"SBSDKUICheckScannerTextConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for the textual contents of the  RTU-UI check scanner."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannertextconfiguration"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerTextConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerTextConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerTextConfiguration"}],"title":"SBSDKUIBarcodesBatchScannerTextConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerTextConfiguration"}],"type":"topic","deprecated":true,"abstract":[{"type":"text","text":"The configuration for the textual contents of the RTU-UI batch barcode scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannertextconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKUIEnableCameraTextConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration\/enableCameraButtonTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration\/enableCameraExplanationText"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration\/init"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerTextConfiguration"],"type":"inheritedBy"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerTextConfiguration\/title","value":"SBSDKUIMRZScannerTextConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerTextConfiguration\/fragments","value":[{"text":"SBSDKUIMRZScannerTextConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerTextConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIMRZScannerTextConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerTextConfiguration\/title","value":"SBSDKUIFinderDocumentScannerTextConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerTextConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerTextConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIFinderDocumentScannerTextConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerTextConfiguration\/title","value":"SBSDKUIHealthInsuranceCardRecognizerTextConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerTextConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerTextConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerTextConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerTextConfiguration\/title","value":"SBSDKUIMedicalCertificateScannerTextConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerTextConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerTextConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIMedicalCertificateScannerTextConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration~1enableCameraButtonTitle\/title","value":"enableCameraButtonTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration~1enableCameraButtonTitle\/fragments","value":[{"text":"enableCameraButtonTitle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration~1enableCameraExplanationText\/title","value":"enableCameraExplanationText","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration~1enableCameraExplanationText\/fragments","value":[{"text":"enableCameraExplanationText","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/title","value":"SBSDKUIEnableCameraTextConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerTextConfiguration\/title","value":"SBSDKUIVINScannerTextConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIVINScannerTextConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerTextConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIVINScannerTextConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorTextConfiguration\/title","value":"SBSDKUIDocumentDataExtractorTextConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorTextConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorTextConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorTextConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerTextConfiguration\/title","value":"SBSDKUIBarcodeScannerTextConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerTextConfiguration\/fragments","value":[{"text":"SBSDKUIBarcodeScannerTextConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerTextConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIBarcodeScannerTextConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerTextConfiguration\/title","value":"SBSDKUITextPatternScannerTextConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerTextConfiguration\/fragments","value":[{"text":"SBSDKUITextPatternScannerTextConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerTextConfiguration\/navigatorTitle","value":[{"text":"SBSDKUITextPatternScannerTextConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerTextConfiguration\/title","value":"SBSDKUIDocumentScannerTextConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerTextConfiguration\/fragments","value":[{"text":"SBSDKUIDocumentScannerTextConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerTextConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIDocumentScannerTextConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration\/title","value":"SBSDKUICheckScannerTextConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUICheckScannerTextConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration\/navigatorTitle","value":[{"text":"SBSDKUICheckScannerTextConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerTextConfiguration\/title","value":"SBSDKUIBarcodesBatchScannerTextConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerTextConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerTextConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIBarcodesBatchScannerTextConfiguration","kind":"identifier"}],"op":"replace"}]}]}