{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice"},"abstract":[{"text":"The camera device to be used with a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession"},{"text":".","type":"text"}],"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/device","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/devicePosition","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/deviceType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/name"],"title":"Instance Properties"},{"generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/availableDevices","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/defaultBackFacingCamera","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/defaultFrontFacingCamera","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/widestAvailableBackFacingCamera"],"title":"Type Properties"},{"generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/availableDevices(for:)-16nqr","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/availableDevices(for:)-9q6l6","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/availableDevices(for:position:)"],"title":"Type Methods"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevice"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevice"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDevice"}],"roleHeading":"Class","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraDevice","kind":"identifier"}],"title":"SBSDKCameraDevice","symbolKind":"class"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraDevice"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"inlineContent":[{"type":"text","text":"To retrieve a list of available devices you can pass to many of SDKs classic or RTU-UI component please use"},{"type":"text","text":" "},{"type":"text","text":"the class functions starting with availableDevices…"}],"type":"paragraph"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On iOS simulators fake devices are returned to allow your code to be tested."}]}],"name":"Note","style":"note"}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","type":"conformsTo"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice/isEqual:":{"role":"symbol","kind":"symbol","type":"topic","title":"isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/isEqual:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcameradevice\/isequal:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice/deviceType":{"url":"\/documentation\/scanbotsdk\/sbsdkcameradevice\/devicetype","type":"topic","kind":"symbol","role":"symbol","title":"deviceType","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCameraDeviceType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDeviceType"}],"navigatorTitle":[{"text":"deviceType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/deviceType","abstract":[{"text":"The type of the camera: triple, dual, dual-wide, wide angle, telephoto, ultra-wide, etc. Readonly.","type":"text"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession","type":"topic","abstract":[{"type":"text","text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the"},{"type":"text","text":" "},{"type":"text","text":"camera device and the preview layer. Provides functionality to capture still images."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKCameraSession","kind":"identifier"}],"title":"SBSDKCameraSession","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraSession","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice/defaultFrontFacingCamera":{"url":"\/documentation\/scanbotsdk\/sbsdkcameradevice\/defaultfrontfacingcamera","abstract":[{"text":"Returns the default front side camera, which in most cases is the frontside, wide angle camera.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultFrontFacingCamera"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice","kind":"typeIdentifier","text":"SBSDKCameraDevice"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/defaultFrontFacingCamera","type":"topic","role":"symbol","kind":"symbol","title":"defaultFrontFacingCamera","navigatorTitle":[{"kind":"identifier","text":"defaultFrontFacingCamera"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice/device":{"url":"\/documentation\/scanbotsdk\/sbsdkcameradevice\/device","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/device","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"device","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCaptureDevice","text":"AVCaptureDevice","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"device","kind":"identifier"}],"abstract":[{"text":"The AVFoundation capture device.","type":"text"}],"kind":"symbol","title":"device","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice":{"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcameradevice","abstract":[{"type":"text","text":"The camera device to be used with a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession"},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraDevice"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDevice"}],"title":"SBSDKCameraDevice"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice/devicePosition":{"url":"\/documentation\/scanbotsdk\/sbsdkcameradevice\/deviceposition","abstract":[{"type":"text","text":"The position of the camera: front side or back side of the device. Readonly."}],"type":"topic","title":"devicePosition","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"devicePosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDevicePosition","text":"SBSDKCameraDevicePosition"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/devicePosition","navigatorTitle":[{"kind":"identifier","text":"devicePosition"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice/availableDevices":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableDevices","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKCameraDevice","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice"},{"text":"]","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcameradevice\/availabledevices","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/availableDevices","abstract":[{"type":"text","text":"Returns a list of all available and supported cameras of the device."}],"role":"symbol","title":"availableDevices","navigatorTitle":[{"text":"availableDevices","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice/availableDevices(for:position:)":{"abstract":[{"text":"Returns a list of all available and supported cameras of the device of the given type and position.","type":"text"}],"title":"availableDevices(for:position:)","navigatorTitle":[{"text":"availableDevicesForType:andPosition:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcameradevice\/availabledevices(for:position:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/availableDevices(for:position:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableDevices","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCameraDeviceType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDeviceType"},{"text":", ","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCameraDevicePosition","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDevicePosition","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"text":"SBSDKCameraDevice","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice/availableDevices(for:)-16nqr":{"abstract":[{"text":"Returns a list of all available and supported cameras of the device of the given type.","type":"text"}],"title":"availableDevices(for:)","navigatorTitle":[{"text":"availableDevicesForType:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/availableDevices(for:)-16nqr","url":"\/documentation\/scanbotsdk\/sbsdkcameradevice\/availabledevices(for:)-16nqr","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableDevices","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCameraDeviceType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDeviceType"},{"text":") -> [","kind":"text"},{"text":"SBSDKCameraDevice","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice"},{"text":"]","kind":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice/widestAvailableBackFacingCamera":{"abstract":[{"text":"Returns the back side camera with the widest lens available.","type":"text"}],"title":"widestAvailableBackFacingCamera","navigatorTitle":[{"text":"widestAvailableBackFacingCamera","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/widestAvailableBackFacingCamera","url":"\/documentation\/scanbotsdk\/sbsdkcameradevice\/widestavailablebackfacingcamera","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"widestAvailableBackFacingCamera","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCameraDevice","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice/name":{"abstract":[{"text":"The name of the camera, e.g. “Front camera - Wide”.","type":"text"}],"title":"name","navigatorTitle":[{"text":"name","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcameradevice\/name","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/name","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice/availableDevices(for:)-9q6l6":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/availableDevices(for:)-9q6l6","title":"availableDevices(for:)","type":"topic","abstract":[{"text":"Returns a list of all available and supported cameras of the device at the given position.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"availableDevicesForPosition:"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcameradevice\/availabledevices(for:)-9q6l6","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableDevices","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCameraDevicePosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDevicePosition"},{"text":") -> [","kind":"text"},{"text":"SBSDKCameraDevice","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice"},{"text":"]","kind":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice/defaultBackFacingCamera":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultBackFacingCamera","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice","text":"SBSDKCameraDevice","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcameradevice\/defaultbackfacingcamera","abstract":[{"type":"text","text":"Returns the default back side camera, which in most cases is the triple or dual camera."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/defaultBackFacingCamera","type":"topic","title":"defaultBackFacingCamera","navigatorTitle":[{"text":"defaultBackFacingCamera","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKCameraDevice","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCameraDevice"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SBSDKCameraDevice","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/device","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/devicePosition","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/deviceType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/name"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/isEqual:"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/availableDevices","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/defaultBackFacingCamera","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/defaultFrontFacingCamera","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/widestAvailableBackFacingCamera"],"generated":true,"anchor":"Type-Properties"},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/availableDevices(for:)-16nqr","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/availableDevices(for:)-9q6l6","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/availableDevices(for:position:)"],"generated":true,"anchor":"Type-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraDevice","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"deviceType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1deviceType\/title","op":"replace"},{"value":[{"text":"deviceType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1deviceType\/fragments","op":"replace"},{"value":"SBSDKCameraSession","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCameraSession"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/fragments","op":"replace"},{"value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/navigatorTitle","op":"replace"},{"value":"defaultFrontFacingCamera","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1defaultFrontFacingCamera\/title","op":"replace"},{"value":[{"kind":"identifier","text":"defaultFrontFacingCamera"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1defaultFrontFacingCamera\/fragments","op":"replace"},{"value":"device","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1device\/title","op":"replace"},{"value":[{"kind":"identifier","text":"device"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1device\/fragments","op":"replace"},{"value":"SBSDKCameraDevice","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCameraDevice"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCameraDevice"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice\/navigatorTitle","op":"replace"},{"value":"devicePosition","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1devicePosition\/title","op":"replace"},{"value":[{"text":"devicePosition","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1devicePosition\/fragments","op":"replace"},{"value":"availableDevices","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1availableDevices\/title","op":"replace"},{"value":[{"text":"availableDevices","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1availableDevices\/fragments","op":"replace"},{"value":"availableDevicesForType:andPosition:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1availableDevices(for:position:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"availableDevicesForType:andPosition:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1availableDevices(for:position:)\/fragments","op":"replace"},{"value":"availableDevicesForType:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1availableDevices(for:)-16nqr\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"availableDevicesForType:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1availableDevices(for:)-16nqr\/fragments","op":"replace"},{"value":"widestAvailableBackFacingCamera","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1widestAvailableBackFacingCamera\/title","op":"replace"},{"value":[{"kind":"identifier","text":"widestAvailableBackFacingCamera"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1widestAvailableBackFacingCamera\/fragments","op":"replace"},{"value":"name","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1name\/title","op":"replace"},{"value":[{"kind":"identifier","text":"name"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1name\/fragments","op":"replace"},{"value":"availableDevicesForPosition:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1availableDevices(for:)-9q6l6\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"availableDevicesForPosition:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1availableDevices(for:)-9q6l6\/fragments","op":"replace"},{"value":"defaultBackFacingCamera","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1defaultBackFacingCamera\/title","op":"replace"},{"value":[{"kind":"identifier","text":"defaultBackFacingCamera"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1defaultBackFacingCamera\/fragments","op":"replace"}]}]}