{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGradientPolygonStyle"}],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"class","roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKGradientPolygonStyle","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGradientPolygonStyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGradientPolygonStyle"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKGradientPolygonStyle","kind":"identifier"}]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/blur","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/boundsRectCornerRadius","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/drawBoundsRect","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/fillColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/glowColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/glowOpacity","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/glowRadius","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/lineWidth","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/startAngle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/strokeColors"],"anchor":"Instance-Properties","generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/ObservableObject-Implementations"]}],"kind":"symbol","abstract":[{"text":"The drawing style for a gradient polygon view.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgradientpolygonstyle"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgradientpolygonstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/7Combine16ObservableObjectP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonStyle/ObservableObject-Implementations":{"title":"ObservableObject Implementations","role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonstyle\/observableobject-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/ObservableObject-Implementations","abstract":[]},"doc://net.doo.ScanbotSDK/7Combine16ObservableObjectP":{"title":"Combine.ObservableObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/7Combine16ObservableObjectP"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonStyle/blur":{"url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonstyle\/blur","navigatorTitle":[{"kind":"identifier","text":"blur"}],"abstract":[{"type":"text","text":"The blur radius of the drawn polygon."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/blur","title":"blur","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"blur"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"type":"topic"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonStyle/glowRadius":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonstyle\/glowradius","title":"glowRadius","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"glowRadius"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"glowRadius"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/glowRadius","abstract":[{"type":"text","text":"The radius of the glow effect."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonStyle/lineWidth":{"role":"symbol","title":"lineWidth","url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonstyle\/linewidth","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"lineWidth","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"lineWidth","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/lineWidth","kind":"symbol","type":"topic","abstract":[{"text":"The line width of the drawn polygon.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonStyle/strokeColors":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"strokeColors"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":"]"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonstyle\/strokecolors","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/strokeColors","navigatorTitle":[{"kind":"identifier","text":"strokeColors"}],"kind":"symbol","abstract":[{"type":"text","text":"The colors used to create the gradient when stroking the polygon."}],"title":"strokeColors","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonStyle/drawBoundsRect":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"If ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" a rounded rectangle is drawn when the path is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":". Otherwise nothing is drawn.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"drawBoundsRect"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/drawBoundsRect","navigatorTitle":[{"kind":"identifier","text":"drawBoundsRect"}],"url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonstyle\/drawboundsrect","title":"drawBoundsRect"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonStyle/fillColor":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fillColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"fillColor","kind":"identifier"}],"abstract":[{"type":"text","text":"The fill color of the polygon."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/fillColor","url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonstyle\/fillcolor","title":"fillColor","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonStyle/glowOpacity":{"kind":"symbol","abstract":[{"text":"The opacity of the glow effect.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"glowOpacity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/glowOpacity","type":"topic","role":"symbol","title":"glowOpacity","url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonstyle\/glowopacity","navigatorTitle":[{"text":"glowOpacity","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonStyle":{"kind":"symbol","type":"topic","title":"SBSDKGradientPolygonStyle","abstract":[{"type":"text","text":"The drawing style for a gradient polygon view."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKGradientPolygonStyle","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGradientPolygonStyle"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonstyle"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonStyle/startAngle":{"url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonstyle\/startangle","navigatorTitle":[{"kind":"identifier","text":"startAngle"}],"abstract":[{"text":"The starting angle of the gradient in degrees.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/startAngle","title":"startAngle","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"startAngle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonStyle/boundsRectCornerRadius":{"title":"boundsRectCornerRadius","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"boundsRectCornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"type":"topic","abstract":[{"type":"text","text":"The corner radius of the rounded rectangle that is drawn when the path is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" and "},{"code":"drawBoundsRect","type":"codeVoice"},{"type":"text","text":" is "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonstyle\/boundsrectcornerradius","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/boundsRectCornerRadius","navigatorTitle":[{"kind":"identifier","text":"boundsRectCornerRadius"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonStyle/glowColor":{"title":"glowColor","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"glowColor"}],"url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonstyle\/glowcolor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/glowColor","abstract":[{"type":"text","text":"The color of the glow effect."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"glowColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGradientPolygonStyle/init":{"abstract":[],"title":"init","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgradientpolygonstyle\/init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKGradientPolygonStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGradientPolygonStyle"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKGradientPolygonStyle","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/blur","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/boundsRectCornerRadius","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/drawBoundsRect","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/fillColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/glowColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/glowOpacity","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/glowRadius","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/lineWidth","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/startAngle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/strokeColors"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGradientPolygonStyle\/init"],"generated":true}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGradientPolygonStyle"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1blur\/title","value":"blur","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1blur\/fragments","value":[{"text":"blur","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1glowRadius\/title","value":"glowRadius"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1glowRadius\/fragments","value":[{"kind":"identifier","text":"glowRadius"}]},{"op":"replace","value":"lineWidth","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1lineWidth\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1lineWidth\/fragments","value":[{"kind":"identifier","text":"lineWidth"}]},{"value":"strokeColors","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1strokeColors\/title"},{"value":[{"text":"strokeColors","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1strokeColors\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1drawBoundsRect\/title","op":"replace","value":"drawBoundsRect"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1drawBoundsRect\/fragments","value":[{"kind":"identifier","text":"drawBoundsRect"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1fillColor\/title","value":"fillColor","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1fillColor\/fragments","value":[{"text":"fillColor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1glowOpacity\/title","op":"replace","value":"glowOpacity"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1glowOpacity\/fragments","op":"replace","value":[{"kind":"identifier","text":"glowOpacity"}]},{"op":"replace","value":"SBSDKGradientPolygonStyle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle\/fragments","op":"replace","value":[{"text":"SBSDKGradientPolygonStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGradientPolygonStyle"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1startAngle\/title","value":"startAngle"},{"value":[{"kind":"identifier","text":"startAngle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1startAngle\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1boundsRectCornerRadius\/title","value":"boundsRectCornerRadius","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1boundsRectCornerRadius\/fragments","value":[{"text":"boundsRectCornerRadius","kind":"identifier"}]},{"value":"glowColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1glowColor\/title","op":"replace"},{"value":[{"text":"glowColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGradientPolygonStyle~1glowColor\/fragments"}]}]}