{"metadata":{"roleHeading":"Protocol","role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKCheckScannerViewControllerDelegate","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckScannerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCheckScannerViewControllerDelegate","kind":"identifier"}],"title":"SBSDKCheckScannerViewControllerDelegate"},"abstract":[{"type":"text","text":"The delegation protocol for the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","isActive":true},{"type":"text","text":" class."}],"relationshipsSections":[{"type":"conformingTypes","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController"],"title":"Conforming Types"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckScannerViewControllerDelegate","kind":"identifier"}],"languages":["swift"]}]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate\/checkScannerViewController(_:didChangeState:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate\/checkScannerViewController(_:didScanCheck:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate\/checkScannerViewControllerShouldScan(_:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewController":{"type":"topic","navigatorTitle":[{"text":"SBSDKUICheckScannerViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","kind":"symbol","title":"SBSDKUICheckScannerViewController","abstract":[{"type":"text","text":"A Ready-To-Use viewController to scan checks using the camera."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewControllerDelegate/checkScannerViewController(_:didChangeState:)":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontrollerdelegate\/checkscannerviewcontroller(_:didchangestate:)","type":"topic","abstract":[{"type":"text","text":"Informs the delegate, that the check scanner has changed its scanning state. Optional."}],"title":"checkScannerViewController(_:didChangeState:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKCheckScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController"},{"text":", ","kind":"text"},{"text":"didChangeState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCheckScannerState","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckScannerState"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"checkScannerViewController:didChangeState:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate\/checkScannerViewController(_:didChangeState:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewController":{"title":"SBSDKCheckScannerViewController","abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan bank checks."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","navigatorTitle":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewControllerDelegate/checkScannerViewControllerShouldScan(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate\/checkScannerViewControllerShouldScan(_:)","type":"topic","title":"checkScannerViewControllerShouldScan(_:)","abstract":[{"text":"Asks the delegate if the check scanner should scan the next video frame. Optional.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontrollerdelegate\/checkscannerviewcontrollershouldscan(_:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkScannerViewControllerShouldScan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKCheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"checkScannerViewControllerShouldScan:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewControllerDelegate/checkScannerViewController(_:didScanCheck:)":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontrollerdelegate\/checkscannerviewcontroller(_:didscancheck:)","navigatorTitle":[{"kind":"identifier","text":"checkScannerViewController:didScanCheck:"}],"title":"checkScannerViewController(_:didScanCheck:)","required":true,"abstract":[{"type":"text","text":"Informs the delegate, that the check scanner has successfully scanned a check."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkScannerViewController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController","kind":"typeIdentifier","text":"SBSDKCheckScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didScanCheck"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanningResult","kind":"typeIdentifier","text":"SBSDKCheckScanningResult"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate\/checkScannerViewController(_:didScanCheck:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewControllerDelegate":{"abstract":[{"type":"text","text":"The delegation protocol for the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController"},{"type":"text","text":" class."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate","type":"topic","title":"SBSDKCheckScannerViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckScannerViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckScannerViewControllerDelegate"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontrollerdelegate","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKCheckScannerViewControllerDelegate","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckScannerViewControllerDelegate"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKCheckScannerViewControllerDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate\/checkScannerViewController(_:didChangeState:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate\/checkScannerViewController(_:didScanCheck:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate\/checkScannerViewControllerShouldScan(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController"],"type":"conformingTypes"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckScannerViewControllerDelegate","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUICheckScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/title"},{"op":"replace","value":[{"text":"SBSDKUICheckScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/navigatorTitle"},{"op":"replace","value":"checkScannerViewController:didChangeState:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate~1checkScannerViewController(_:didChangeState:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"checkScannerViewController:didChangeState:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate~1checkScannerViewController(_:didChangeState:)\/fragments"},{"op":"replace","value":"SBSDKCheckScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/title"},{"op":"replace","value":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/navigatorTitle"},{"op":"replace","value":"checkScannerViewControllerShouldScan:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate~1checkScannerViewControllerShouldScan(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"checkScannerViewControllerShouldScan:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate~1checkScannerViewControllerShouldScan(_:)\/fragments"},{"op":"replace","value":"checkScannerViewController:didScanCheck:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate~1checkScannerViewController(_:didScanCheck:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkScannerViewController:didScanCheck:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate~1checkScannerViewController(_:didScanCheck:)\/fragments"},{"op":"replace","value":"SBSDKCheckScannerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate\/title"},{"op":"replace","value":[{"text":"SBSDKCheckScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate\/fragments"},{"op":"replace","value":[{"text":"SBSDKCheckScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}