{"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager"},"kind":"symbol","abstract":[{"text":"Helper class to manage trained data files for the Tesseract OCR engine.","type":"text"}],"topicSections":[{"anchor":"Type-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/customLanguagesFolderURL","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installedLanguages","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installedLanguagesThreeLetterCodes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/isOCRDataBundleInstalled"],"generated":true,"title":"Type Properties"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installCustomLanguagesFrom(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installLanguages()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/removeCustomLanguages()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/resetInstalledLanguages()"],"anchor":"Type-Methods","title":"Type Methods"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCRLanguagesManager","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKOCRLanguagesManager"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKOCRLanguagesManager","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRLanguagesManager","title":"SBSDKOCRLanguagesManager","role":"symbol","roleHeading":"Class","symbolKind":"class"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager/installLanguages()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installLanguages()","url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/installlanguages()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"installLanguages","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"installLanguages","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Installs the default and custom OCR language files and prepares them for usage."}],"title":"installLanguages()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager/isOCRDataBundleInstalled":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isOCRDataBundleInstalled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"isOCRDataBundleInstalled","kind":"identifier"}],"abstract":[{"text":"Returns ","type":"text"},{"code":"True","type":"codeVoice"},{"text":" if the OCR data bundle (ScanbotSDKOCRData.bundle) was found within the app. ","type":"text"},{"type":"codeVoice","code":"False"},{"type":"text","text":" otherwise."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/isOCRDataBundleInstalled","url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/isocrdatabundleinstalled","type":"topic","kind":"symbol","title":"isOCRDataBundleInstalled"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager/installCustomLanguagesFrom(_:)":{"navigatorTitle":[{"text":"installCustomLanguagesFrom:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/installcustomlanguagesfrom(_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"installCustomLanguagesFrom"},{"text":"([","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"]) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A helper function to easily install custom OCR languages."}],"title":"installCustomLanguagesFrom(_:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installCustomLanguagesFrom(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager/installedLanguagesThreeLetterCodes":{"url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/installedlanguagesthreelettercodes","abstract":[{"type":"text","text":"An array of three-letter language codes of the currently installed languages."}],"kind":"symbol","title":"installedLanguagesThreeLetterCodes","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"installedLanguagesThreeLetterCodes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installedLanguagesThreeLetterCodes","navigatorTitle":[{"kind":"identifier","text":"installedLanguagesThreeLetterCodes"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager/installedLanguagesFolderURL":{"role":"symbol","fragments":[{"text":"installedLanguagesFolderURL","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installedLanguagesFolderURL","url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/installedlanguagesfolderurl","type":"topic","kind":"symbol","title":"installedLanguagesFolderURL"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager/removeCustomLanguages()":{"abstract":[{"type":"text","text":"Removes the language files from the custom languages folder and resets the installed languages."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"removeCustomLanguages","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/removecustomlanguages()","title":"removeCustomLanguages()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/removeCustomLanguages()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeCustomLanguages","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCRLanguagesManager","kind":"identifier"}],"title":"SBSDKOCRLanguagesManager","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager","abstract":[{"type":"text","text":"Helper class to manage trained data files for the Tesseract OCR engine."}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKOCRLanguagesManager","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager/installedLanguages":{"abstract":[{"type":"text","text":"An array of two-letter language codes of the currently installed languages."}],"navigatorTitle":[{"kind":"identifier","text":"installedLanguages"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/installedlanguages","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installedLanguages","kind":"symbol","title":"installedLanguages","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"installedLanguages"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager/resetInstalledLanguages()":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/resetinstalledlanguages()","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetInstalledLanguages"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"resetInstalledLanguages","kind":"identifier"}],"title":"resetInstalledLanguages()","role":"symbol","abstract":[{"type":"text","text":"Removes all installed OCR languages and reinstalls them."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/resetInstalledLanguages()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager/customLanguagesFolderURL":{"navigatorTitle":[{"text":"customLanguagesFolderURL","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/customlanguagesfolderurl","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"customLanguagesFolderURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"}],"abstract":[{"type":"text","text":"The URL of the folder for custom language trained data files."}],"title":"customLanguagesFolderURL","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/customLanguagesFolderURL"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKOCRLanguagesManager"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKOCRLanguagesManager","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKOCRLanguagesManager","kind":"identifier"}]},{"value":[{"anchor":"Type-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/customLanguagesFolderURL","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installedLanguages","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installedLanguagesFolderURL","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installedLanguagesThreeLetterCodes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/isOCRDataBundleInstalled"],"generated":true,"title":"Type Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installCustomLanguagesFrom(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installLanguages()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/removeCustomLanguages()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/resetInstalledLanguages()"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCRLanguagesManager","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"value":"installLanguages","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1installLanguages()\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"installLanguages","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1installLanguages()\/fragments"},{"value":"isOCRDataBundleInstalled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1isOCRDataBundleInstalled\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1isOCRDataBundleInstalled\/fragments","value":[{"kind":"identifier","text":"isOCRDataBundleInstalled"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1installCustomLanguagesFrom(_:)\/title","op":"replace","value":"installCustomLanguagesFrom:"},{"value":[{"kind":"text","text":"+ "},{"text":"installCustomLanguagesFrom:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1installCustomLanguagesFrom(_:)\/fragments"},{"value":"installedLanguagesThreeLetterCodes","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1installedLanguagesThreeLetterCodes\/title"},{"value":[{"kind":"identifier","text":"installedLanguagesThreeLetterCodes"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1installedLanguagesThreeLetterCodes\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1removeCustomLanguages()\/title","op":"replace","value":"removeCustomLanguages"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"removeCustomLanguages"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1removeCustomLanguages()\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager\/title","value":"SBSDKOCRLanguagesManager","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKOCRLanguagesManager"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKOCRLanguagesManager"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager\/navigatorTitle","op":"replace"},{"value":"installedLanguages","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1installedLanguages\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1installedLanguages\/fragments","value":[{"text":"installedLanguages","kind":"identifier"}]},{"value":"resetInstalledLanguages","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1resetInstalledLanguages()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"resetInstalledLanguages","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1resetInstalledLanguages()\/fragments"},{"op":"replace","value":"customLanguagesFolderURL","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1customLanguagesFolderURL\/title"},{"value":[{"kind":"identifier","text":"customLanguagesFolderURL"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1customLanguagesFolderURL\/fragments"}]}]}