{"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZScanner"}],"title":"SBSDKMRZScanner","symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScanner","roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZScanner"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscanner"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscanner"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"type":"text","text":"A class to scan machine-readable zones on various image sources."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMRZScanner","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"text":"Detects a machine-readable zone if needed, extracts the text, parses and creates a generic document if suitable and returns the result.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/init(configuration:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/copyCurrentConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/scan(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/scan(from:orientation:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/scan(from:useLiveMode:)-59j7r","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/scan(from:useLiveMode:)-tyiw","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/setConfiguration(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScanner/scan(from:orientation:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/scan(from:orientation:)","url":"\/documentation\/scanbotsdk\/sbsdkmrzscanner\/scan(from:orientation:)","role":"symbol","title":"scan(from:orientation:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVCaptureVideoOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@AVCaptureVideoOrientation"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerResult","kind":"typeIdentifier","text":"SBSDKMRZScannerResult"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Scans a machine-readable zone and also detects it if needed from a "},{"type":"codeVoice","code":"CMSampleBuffer"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"scanFromBuffer:orientation:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScanner":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner","url":"\/documentation\/scanbotsdk\/sbsdkmrzscanner","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKMRZScanner","kind":"identifier"}],"abstract":[{"type":"text","text":"A class to scan machine-readable zones on various image sources."}],"title":"SBSDKMRZScanner","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMRZScanner","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerFrame":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerFrame"}],"abstract":[{"type":"text","text":"A wrapper class for video frames."}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerframe","kind":"symbol","title":"SBSDKBaseScannerFrame","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerFrame"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScanner/copyCurrentConfiguration()":{"abstract":[{"type":"text","text":"Returns a copy of the receivers current configuration."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/copyCurrentConfiguration()","title":"copyCurrentConfiguration()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copyCurrentConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKMRZScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerConfiguration","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzscanner\/copycurrentconfiguration()","navigatorTitle":[{"text":"copyCurrentConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScanner/init(configuration:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/init(configuration:)","url":"\/documentation\/scanbotsdk\/sbsdkmrzscanner\/init(configuration:)","role":"symbol","title":"init(configuration:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKMRZScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerConfiguration"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Designated initializer."}],"navigatorTitle":[{"text":"initWithConfiguration:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScanner/scan(from:useLiveMode:)-tyiw":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzscanner\/scan(from:uselivemode:)-tyiw","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/scan(from:useLiveMode:)-tyiw","role":"symbol","title":"scan(from:useLiveMode:)","navigatorTitle":[{"text":"scanFromFrame:useLiveMode:","kind":"identifier"}],"abstract":[{"text":"Scans a machine-readable zone and also detects it if needed from a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame","type":"reference"},{"text":".","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerFrame","text":"SBSDKBaseScannerFrame","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"useLiveMode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerResult","text":"SBSDKMRZScannerResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScanner/scan(from:useLiveMode:)-59j7r":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"useLiveMode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerResult","text":"SBSDKMRZScannerResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzscanner\/scan(from:uselivemode:)-59j7r","type":"topic","abstract":[{"type":"text","text":"Scans a machine-readable zone and also detects it if needed from a "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":"."}],"kind":"symbol","title":"scan(from:useLiveMode:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/scan(from:useLiveMode:)-59j7r","navigatorTitle":[{"text":"scanFromImage:useLiveMode:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScanner/scan(from:)":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzscanner\/scan(from:)","abstract":[{"type":"text","text":"Parses a string for machine readable zone data."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/scan(from:)","title":"scan(from:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerResult","text":"SBSDKMRZScannerResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"scanFromString:","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScanner/init()":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/init()","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzscanner\/init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[{"type":"text","text":"Designated initializer. Creates an instance of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner"},{"type":"text","text":" with the default configuration."}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScanner/setConfiguration(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzscanner\/setconfiguration(_:)","kind":"symbol","title":"setConfiguration(_:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/setConfiguration(_:)","role":"symbol","abstract":[{"type":"text","text":"Sets the configuration of the receiver."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMRZScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerConfiguration"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setConfiguration:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKMRZScanner","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKMRZScanner","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKMRZScanner"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/copyCurrentConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/init(configuration:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/scan(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/scan(from:orientation:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/scan(from:useLiveMode:)-59j7r","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/scan(from:useLiveMode:)-tyiw","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/setConfiguration(_:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMRZScanner","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"scanFromBuffer:orientation:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1scan(from:orientation:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1scan(from:orientation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scanFromBuffer:orientation:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner\/title","value":"SBSDKMRZScanner"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner\/fragments","value":[{"text":"SBSDKMRZScanner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMRZScanner"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerFrame\/title","value":"SBSDKBaseScannerFrame"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerFrame\/fragments","value":[{"text":"SBSDKBaseScannerFrame","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerFrame\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBaseScannerFrame"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1copyCurrentConfiguration()\/title","value":"copyCurrentConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1copyCurrentConfiguration()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"copyCurrentConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1init(configuration:)\/title","value":"initWithConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1init(configuration:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1scan(from:useLiveMode:)-tyiw\/title","value":"scanFromFrame:useLiveMode:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1scan(from:useLiveMode:)-tyiw\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scanFromFrame:useLiveMode:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1scan(from:useLiveMode:)-59j7r\/title","value":"scanFromImage:useLiveMode:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1scan(from:useLiveMode:)-59j7r\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scanFromImage:useLiveMode:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1scan(from:)\/title","value":"scanFromString:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1scan(from:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scanFromString:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1setConfiguration(_:)\/title","value":"setConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1setConfiguration(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setConfiguration:","kind":"identifier"}]}]}]}