{"metadata":{"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2Gs1Handling@SBSDKUI2Gs1HandlingDecodeStructure","title":"SBSDKUI2Gs1Handling.decodeStructure","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeStructure"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKUI2Gs1HandlingDecodeStructure","kind":"identifier"}]},"abstract":[{"text":"Same as VALIDATE_STRUCTURE, except that GS1 strings are converted to the human-readable format, instead (with","type":"text"},{"text":" ","type":"text"},{"text":"parentheses used to wrap AI keys, e.g. (01)123456789). The \\x1D character is never used in this representation.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/decodestructure"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/decodestructure"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodeStructure","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/decodeStructure","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling","title":"SBSDKUI2Gs1Handling","abstract":[{"type":"text","text":"GS1_COMPOSITE barcode type handling"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling/decodeStructure":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeStructure"}],"abstract":[{"type":"text","text":"Same as VALIDATE_STRUCTURE, except that GS1 strings are converted to the human-readable format, instead (with"},{"type":"text","text":" "},{"type":"text","text":"parentheses used to wrap AI keys, e.g. (01)123456789). The \\x1D character is never used in this representation."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/decodestructure","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingDecodeStructure"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/decodeStructure","title":"SBSDKUI2Gs1Handling.decodeStructure","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2Gs1HandlingDecodeStructure"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2Gs1HandlingDecodeStructure","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingDecodeStructure"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/title","value":"SBSDKUI2Gs1Handling"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/fragments","value":[{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/navigatorTitle","value":[{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1decodeStructure\/title","value":"SBSDKUI2Gs1HandlingDecodeStructure"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1decodeStructure\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingDecodeStructure"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}