{"kind":"symbol","metadata":{"role":"symbol","title":"SBSDKUI2Gs1Handling.validateStructure","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validateStructure"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKUI2Gs1Handling@SBSDKUI2Gs1HandlingValidateStructure","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"SBSDKUI2Gs1HandlingValidateStructure","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/validateStructure","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/validatestructure"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/validatestructure"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Same as PARSE. Additionally, messages containing unknown AI keys, or containing values of incorrect format for"},{"type":"text","text":" "},{"text":"known keys, are not returned.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"validateStructure","kind":"identifier"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling/validateStructure":{"title":"SBSDKUI2Gs1Handling.validateStructure","abstract":[{"type":"text","text":"Same as PARSE. Additionally, messages containing unknown AI keys, or containing values of incorrect format for"},{"text":" ","type":"text"},{"type":"text","text":"known keys, are not returned."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/validatestructure","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"validateStructure","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/validateStructure","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingValidateStructure"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling":{"abstract":[{"type":"text","text":"GS1_COMPOSITE barcode type handling"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling","title":"SBSDKUI2Gs1Handling","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKUI2Gs1HandlingValidateStructure","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2Gs1HandlingValidateStructure","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingValidateStructure"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1validateStructure\/title","value":"SBSDKUI2Gs1HandlingValidateStructure","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1validateStructure\/fragments","op":"replace","value":[{"text":"SBSDKUI2Gs1HandlingValidateStructure","kind":"identifier"}]},{"value":"SBSDKUI2Gs1Handling","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/title"},{"value":[{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}],"op":"replace"}]}]}