{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/copyWithZone:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKStructuredAppendInfo(im)copyWithZone:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStructuredAppendInfo":{"title":"SBSDKStructuredAppendInfo","abstract":[{"text":"The structured append mode can be used to split a message across multiple barcodes.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStructuredAppendInfo/copyWithZone:":{"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo\/copywithzone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/copyWithZone:","title":"copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/title","value":"SBSDKStructuredAppendInfo"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/fragments","value":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/navigatorTitle","value":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}]}]}]}