{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagefileformat\/equatable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations","modules":[{"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat\/!=(_:_:)"],"title":"Operators","anchor":"Operators","generated":true}],"sections":[],"kind":"article","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFileFormat/!=(_:_:)":{"type":"topic","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkimagefileformat\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"!=(_:_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat\/!=(_:_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFileFormat":{"role":"symbol","kind":"symbol","abstract":[{"text":"Enumeration of supported image file types.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageFileFormat","kind":"identifier"}],"title":"SBSDKImageFileFormat","type":"topic","navigatorTitle":[{"text":"SBSDKImageFileFormat","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefileformat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKImageFileFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat\/title"},{"value":[{"text":"SBSDKImageFileFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat\/fragments"},{"value":[{"text":"SBSDKImageFileFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat\/navigatorTitle"}]}]}