{"abstract":[{"type":"text","text":"Minimum number of accumulated frames that have equal result."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/minimumNumberOfRequiredFramesWithEqualScanningResult"},"metadata":{"symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerConfiguration(py)minimumNumberOfRequiredFramesWithEqualScanningResult","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"minimumNumberOfRequiredFramesWithEqualScanningResult"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/minimumnumberofrequiredframeswithequalscanningresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/minimumnumberofrequiredframeswithequalscanningresult"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"Default is 2","type":"text"}],"type":"paragraph"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration/minimumNumberOfRequiredFramesWithEqualScanningResult":{"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/minimumnumberofrequiredframeswithequalscanningresult","type":"topic","role":"symbol","abstract":[{"text":"Minimum number of accumulated frames that have equal result.","type":"text"}],"navigatorTitle":[{"text":"minimumNumberOfRequiredFramesWithEqualScanningResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/minimumNumberOfRequiredFramesWithEqualScanningResult","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"kind":"symbol","title":"minimumNumberOfRequiredFramesWithEqualScanningResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration":{"abstract":[{"text":"Configuration for the VIN scanner.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKVINScannerConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVINScannerConfiguration"}],"title":"SBSDKVINScannerConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"minimumNumberOfRequiredFramesWithEqualScanningResult","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"minimumNumberOfRequiredFramesWithEqualScanningResult","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"minimumNumberOfRequiredFramesWithEqualScanningResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration~1minimumNumberOfRequiredFramesWithEqualScanningResult\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration~1minimumNumberOfRequiredFramesWithEqualScanningResult\/fragments","value":[{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration\/title","value":"SBSDKVINScannerConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKVINScannerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVINScannerConfiguration"}]}]}]}