{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScanAndCountPolygonStyle\/cornerRadius","interfaceLanguage":"swift"},"abstract":[{"text":"The corner radius of the barcode polygons outline.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkscanandcountpolygonstyle\/cornerradius"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkscanandcountpolygonstyle\/cornerradius"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cornerRadius","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cornerRadius","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKScanAndCountPolygonStyle(py)cornerRadius","title":"cornerRadius","symbolKind":"property","navigatorTitle":[{"text":"cornerRadius","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScanAndCountPolygonStyle"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScanAndCountPolygonStyle/cornerRadius":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScanAndCountPolygonStyle\/cornerRadius","type":"topic","kind":"symbol","abstract":[{"text":"The corner radius of the barcode polygons outline.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"cornerRadius"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"title":"cornerRadius","url":"\/documentation\/scanbotsdk\/sbsdkscanandcountpolygonstyle\/cornerradius"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScanAndCountPolygonStyle":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScanAndCountPolygonStyle","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScanAndCountPolygonStyle","url":"\/documentation\/scanbotsdk\/sbsdkscanandcountpolygonstyle","kind":"symbol","abstract":[{"type":"text","text":"A class that represents the style of the polygon rendered around a barcode in "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController","isActive":true},{"type":"text","text":"."}],"type":"topic","title":"SBSDKScanAndCountPolygonStyle","navigatorTitle":[{"text":"SBSDKScanAndCountPolygonStyle","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewController":{"title":"SBSDKBarcodeScanAndCountViewController","abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to show a camera screen with the barcode scanner.","type":"text"},{"text":" ","type":"text"},{"text":"Screen also shows snap, scan more and reset buttons.","type":"text"},{"text":" ","type":"text"},{"text":"The snap button starts the scanning when tapped.","type":"text"},{"text":" ","type":"text"},{"text":"The snap button resets the scanning when tapped again.","type":"text"},{"text":" ","type":"text"},{"text":"Instead it is installing itself as a child view controller onto a given parent view controller.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"cornerRadius","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cornerRadius"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"cornerRadius","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanAndCountPolygonStyle~1cornerRadius\/title","op":"replace","value":"cornerRadius"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanAndCountPolygonStyle~1cornerRadius\/fragments","op":"replace","value":[{"text":"cornerRadius","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanAndCountPolygonStyle\/title","value":"SBSDKScanAndCountPolygonStyle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanAndCountPolygonStyle\/fragments","value":[{"text":"SBSDKScanAndCountPolygonStyle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScanAndCountPolygonStyle\/navigatorTitle","value":[{"text":"SBSDKScanAndCountPolygonStyle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/title","value":"SBSDKBarcodeScanAndCountViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/navigatorTitle","value":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}