{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewFinderRectDidChangeHandler","kind":"identifier"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> ())?"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller\/viewfinderrectdidchangehandler"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller\/viewfinderrectdidchangehandler"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController\/viewFinderRectDidChangeHandler","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"viewFinderRectDidChangeHandler","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerViewController(py)viewFinderRectDidChangeHandler","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewFinderRectDidChangeHandler"},{"kind":"text","text":": (("},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":") -> ())?"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"viewFinderRectDidChangeHandler"},"abstract":[{"text":"A block being called whenever the view finder rectangle changes.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Can be uses to layout UI elements with respect to the view finder position. Defaults to "},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Equals to CGRectZero, if the view finder is not active."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewController/viewFinderRectDidChangeHandler":{"abstract":[{"type":"text","text":"A block being called whenever the view finder rectangle changes."},{"type":"text","text":" "},{"text":"Can be uses to layout UI elements with respect to the view finder position. Defaults to ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Equals to CGRectZero, if the view finder is not active.","type":"text"}],"role":"symbol","title":"viewFinderRectDidChangeHandler","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller\/viewfinderrectdidchangehandler","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewFinderRectDidChangeHandler"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":") -> ())?","kind":"text"}],"navigatorTitle":[{"text":"viewFinderRectDidChangeHandler","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController\/viewFinderRectDidChangeHandler"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller","title":"SBSDKBaseScannerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"abstract":[{"type":"text","text":"A highly customizable camera view controller that delivers a basic camera functionality along with video"},{"text":" ","type":"text"},{"type":"text","text":"frame extraction and preprocessing, orientation correction and still image capturing."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"viewFinderRectDidChangeHandler","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"viewFinderRectDidChangeHandler","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"kind":"identifier","text":"viewFinderRectDidChangeHandler"},{"kind":"text","text":")("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":" "},{"text":"","kind":"internalParam"},{"text":");","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"viewFinderRectDidChangeHandler","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController~1viewFinderRectDidChangeHandler\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController~1viewFinderRectDidChangeHandler\/fragments","value":[{"text":"viewFinderRectDidChangeHandler","kind":"identifier"}],"op":"replace"},{"value":"SBSDKBaseScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"op":"replace"}]}]}