{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller\/viewfinderconfiguration"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller\/viewfinderconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController\/viewFinderConfiguration"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The view finder configuration of the receiver. Lets you enable and customize the view finder."},{"type":"text","text":" "},{"type":"text","text":"It is copied on setting, so mutating the configuration after setting will not change the behavior."},{"type":"text","text":" "},{"type":"text","text":"Instead, re-configure your instance and set it again."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewFinderConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration","text":"SBSDKBaseScannerViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewFinderConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration","text":"SBSDKBaseScannerViewFinderConfiguration","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerViewController(py)viewFinderConfiguration","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"viewFinderConfiguration","navigatorTitle":[{"text":"viewFinderConfiguration","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewController/viewFinderConfiguration":{"abstract":[{"text":"The view finder configuration of the receiver. Lets you enable and customize the view finder.","type":"text"},{"text":" ","type":"text"},{"text":"It is copied on setting, so mutating the configuration after setting will not change the behavior.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Instead, re-configure your instance and set it again."}],"type":"topic","kind":"symbol","role":"symbol","title":"viewFinderConfiguration","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewFinderConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration"}],"navigatorTitle":[{"text":"viewFinderConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller\/viewfinderconfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController\/viewFinderConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller","title":"SBSDKBaseScannerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"abstract":[{"type":"text","text":"A highly customizable camera view controller that delivers a basic camera functionality along with video"},{"text":" ","type":"text"},{"type":"text","text":"frame extraction and preprocessing, orientation correction and still image capturing."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}],"navigatorTitle":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration","title":"SBSDKBaseScannerViewFinderConfiguration","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The view finder configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"text":" ","type":"text"},{"type":"text","text":"Sometimes it is necessary to limit a live video frame detection or recognition to a certain rectangular area with"},{"text":" ","type":"text"},{"type":"text","text":"a specific aspect ratio: the region or rectangle of interest. This is where a view finder comes in."},{"type":"text","text":" "},{"type":"text","text":"It crops the video frame to that region of interest before passing it to any scanner. Usually"},{"type":"text","text":" "},{"text":"the performance of scanners gain a benefit from it because less pixels must be processed.","type":"text"},{"text":" ","type":"text"},{"text":"Additionally, to guide the user, the view finder visualizes the region of interest by drawing a rectangle around","type":"text"},{"type":"text","text":" "},{"type":"text","text":"on the user interface."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"viewFinderConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"viewFinderConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration","text":"SBSDKBaseScannerViewFinderConfiguration"},{"kind":"text","text":" * "},{"text":"viewFinderConfiguration","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"viewFinderConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController~1viewFinderConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"viewFinderConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController~1viewFinderConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/title","value":"SBSDKBaseScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/fragments","value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/title","value":"SBSDKBaseScannerViewFinderConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}]},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}