{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDevicePosition\/back","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The camera is located on the back side of the device.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"back","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradeviceposition\/back"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradeviceposition\/back"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDevicePosition"]]},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Case","symbolKind":"case","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCameraDevicePosition@SBSDKCameraDevicePositionBack","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"back"}],"navigatorTitle":[{"text":"SBSDKCameraDevicePositionBack","kind":"identifier"}],"title":"SBSDKCameraDevicePosition.back"},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDevicePosition":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDevicePosition","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradeviceposition","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDevicePosition"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraDevicePosition"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"An enum to describe the physical position of a camera device."}],"title":"SBSDKCameraDevicePosition"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDevicePosition/back":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDevicePosition\/back","title":"SBSDKCameraDevicePosition.back","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradeviceposition\/back","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"back"}],"abstract":[{"text":"The camera is located on the back side of the device.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDevicePositionBack"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKCameraDevicePositionBack","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKCameraDevicePositionBack","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKCameraDevicePositionBack","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKCameraDevicePosition","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevicePosition\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraDevicePosition"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevicePosition\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraDevicePosition"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevicePosition\/navigatorTitle"},{"op":"replace","value":"SBSDKCameraDevicePositionBack","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevicePosition~1back\/title"},{"op":"replace","value":[{"text":"SBSDKCameraDevicePositionBack","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevicePosition~1back\/fragments"}]}]}