{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFImageExtractor(im)initWithScaleFactor:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"scaleFactor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}],"title":"init(scaleFactor:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithScaleFactor:"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"init","roleHeading":"Initializer"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFImageExtractor\/init(scaleFactor:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfimageextractor\/init(scalefactor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfimageextractor\/init(scalefactor:)"]}],"sections":[],"abstract":[{"text":"Designated initializer.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFImageExtractor"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"scaleFactor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":" = 1.0)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The scale factor applied to the PDF media box frame while extracting images. Defaults to 1.0.","type":"text"}],"type":"paragraph"}],"name":"scaleFactor"}],"kind":"parameters"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFImageExtractor":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFImageExtractor"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFImageExtractor"}],"title":"SBSDKPDFImageExtractor","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfimageextractor","abstract":[{"type":"text","text":"Class used to extract images from a PDF file and returns them in various ways."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFImageExtractor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFImageExtractor/init(scaleFactor:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"scaleFactor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":")"}],"title":"init(scaleFactor:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFImageExtractor\/init(scaleFactor:)","abstract":[{"type":"text","text":"Designated initializer."}],"navigatorTitle":[{"kind":"identifier","text":"initWithScaleFactor:"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfimageextractor\/init(scalefactor:)","type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithScaleFactor:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithScaleFactor:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithScaleFactor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"text":") ","kind":"text"},{"text":"scaleFactor","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"scaleFactor","content":[{"inlineContent":[{"type":"text","text":"The scale factor applied to the PDF media box frame while extracting images. Defaults to 1.0."}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFImageExtractor\/title","value":"SBSDKPDFImageExtractor","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFImageExtractor\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFImageExtractor"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFImageExtractor\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPDFImageExtractor"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFImageExtractor~1init(scaleFactor:)\/title","value":"initWithScaleFactor:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFImageExtractor~1init(scaleFactor:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithScaleFactor:","kind":"identifier"}],"op":"replace"}]}]}