{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconUserGuidanceConfiguration\/background"},"sections":[],"abstract":[{"text":"Configuration of the background appearance for the user guidance hints.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"background"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BackgroundStyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BackgroundStyle","kind":"typeIdentifier","text":"SBSDKUI2BackgroundStyle"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2iconuserguidanceconfiguration\/background"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2iconuserguidanceconfiguration\/background"]}],"metadata":{"role":"symbol","symbolKind":"property","title":"background","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2IconUserGuidanceConfiguration(py)background","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"background"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BackgroundStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BackgroundStyle","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"background","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconUserGuidanceConfiguration"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IconUserGuidanceConfiguration/background":{"abstract":[{"text":"Configuration of the background appearance for the user guidance hints.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2iconuserguidanceconfiguration\/background","navigatorTitle":[{"kind":"identifier","text":"background"}],"title":"background","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"background"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BackgroundStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BackgroundStyle"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconUserGuidanceConfiguration\/background"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BackgroundStyle":{"abstract":[{"type":"text","text":"Configuration of the background appearance for buttons and hints."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BackgroundStyle"}],"title":"SBSDKUI2BackgroundStyle","navigatorTitle":[{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2backgroundstyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BackgroundStyle","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IconUserGuidanceConfiguration":{"abstract":[{"text":"Configuration of the hint (containing an icon) guiding users through the scanning process.","type":"text"}],"title":"SBSDKUI2IconUserGuidanceConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IconUserGuidanceConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IconUserGuidanceConfiguration"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2iconuserguidanceconfiguration","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconUserGuidanceConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"background"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"background"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKUI2BackgroundStyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BackgroundStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BackgroundStyle"},{"text":" * ","kind":"text"},{"text":"background","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"background","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconUserGuidanceConfiguration~1background\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconUserGuidanceConfiguration~1background\/fragments","value":[{"kind":"identifier","text":"background"}],"op":"replace"},{"value":"SBSDKUI2BackgroundStyle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BackgroundStyle\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BackgroundStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BackgroundStyle"}]},{"op":"replace","value":[{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BackgroundStyle\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconUserGuidanceConfiguration\/title","value":"SBSDKUI2IconUserGuidanceConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconUserGuidanceConfiguration\/fragments","value":[{"text":"SBSDKUI2IconUserGuidanceConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconUserGuidanceConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2IconUserGuidanceConfiguration"}],"op":"replace"}]}]}