{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerUIConfiguration"]]},"abstract":[{"text":"The style of the confirmation dialogs retry button.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerUIConfiguration\/confirmationDialogRetryButtonStyle","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmationDialogRetryButtonStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUIDialogButtonStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogButtonStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogButtonStyle","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescanneruiconfiguration\/confirmationdialogretrybuttonstyle"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescanneruiconfiguration\/confirmationdialogretrybuttonstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"title":"confirmationDialogRetryButtonStyle","platforms":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"confirmationDialogRetryButtonStyle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogButtonStyle","text":"SBSDKUIDialogButtonStyle"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerUIConfiguration(py)confirmationDialogRetryButtonStyle","role":"symbol","navigatorTitle":[{"text":"confirmationDialogRetryButtonStyle","kind":"identifier"}]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerUIConfiguration/confirmationDialogRetryButtonStyle":{"navigatorTitle":[{"text":"confirmationDialogRetryButtonStyle","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The style of the confirmation dialogs retry button."}],"kind":"symbol","deprecated":true,"title":"confirmationDialogRetryButtonStyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmationDialogRetryButtonStyle"},{"kind":"text","text":": "},{"text":"SBSDKUIDialogButtonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogButtonStyle"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescanneruiconfiguration\/confirmationdialogretrybuttonstyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerUIConfiguration\/confirmationDialogRetryButtonStyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerUIConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerUIConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeScannerUIConfiguration"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescanneruiconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerUIConfiguration"}],"abstract":[{"text":"The configuration for user interface of the RTU-UI barcode scanner.","type":"text"}],"deprecated":true,"kind":"symbol","title":"SBSDKUIBarcodeScannerUIConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDialogButtonStyle":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogButtonStyle","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDialogButtonStyle"}],"abstract":[{"text":"The general style for an action button in a ScanbotSDK alert. Used to customize certain result alerts in SBSDKUI components.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidialogbuttonstyle","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIDialogButtonStyle","kind":"identifier"}],"role":"symbol","title":"SBSDKUIDialogButtonStyle"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"confirmationDialogRetryButtonStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"confirmationDialogRetryButtonStyle"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogButtonStyle","kind":"typeIdentifier","text":"SBSDKUIDialogButtonStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogButtonStyle"},{"text":" * ","kind":"text"},{"text":"confirmationDialogRetryButtonStyle","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerUIConfiguration~1confirmationDialogRetryButtonStyle\/title","value":"confirmationDialogRetryButtonStyle","op":"replace"},{"value":[{"text":"confirmationDialogRetryButtonStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerUIConfiguration~1confirmationDialogRetryButtonStyle\/fragments"},{"op":"replace","value":"SBSDKUIBarcodeScannerUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerUIConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerUIConfiguration\/fragments","value":[{"text":"SBSDKUIBarcodeScannerUIConfiguration","kind":"identifier"}]},{"value":"SBSDKUIDialogButtonStyle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogButtonStyle\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogButtonStyle\/fragments","value":[{"kind":"identifier","text":"SBSDKUIDialogButtonStyle"}],"op":"replace"}]}]}