{"kind":"symbol","abstract":[{"type":"text","text":"Allowed orientations for automatic interface rotations."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationLockMode"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock","text":"SBSDKOrientationLock","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescanneruiconfiguration\/orientationlockmode"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescanneruiconfiguration\/orientationlockmode"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerUIConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerUIConfiguration\/orientationLockMode","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"orientationLockMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock","text":"SBSDKOrientationLock","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerUIConfiguration(py)orientationLockMode","platforms":[],"role":"symbol","title":"orientationLockMode","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"orientationLockMode","kind":"identifier"}]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOrientationLock":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOrientationLock","kind":"identifier"}],"title":"SBSDKOrientationLock","abstract":[{"type":"text","text":"This enum describes the available orientation lock modes for the user interface."}],"url":"\/documentation\/scanbotsdk\/sbsdkorientationlock","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock","type":"topic","navigatorTitle":[{"text":"SBSDKOrientationLock","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerUIConfiguration/orientationLockMode":{"abstract":[{"text":"Allowed orientations for automatic interface rotations.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"orientationLockMode","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerUIConfiguration\/orientationLockMode","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescanneruiconfiguration\/orientationlockmode","title":"orientationLockMode","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"orientationLockMode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock","text":"SBSDKOrientationLock"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerUIConfiguration":{"kind":"symbol","abstract":[{"type":"text","text":"The configuration for user interface of the RTU-UI barcode scanner."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerUIConfiguration"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerUIConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodeScannerUIConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescanneruiconfiguration","type":"topic","title":"SBSDKUIBarcodeScannerUIConfiguration"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"orientationLockMode","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"orientationLockMode","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKOrientationLock","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock"},{"kind":"text","text":" "},{"text":"orientationLockMode","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock\/title","op":"replace","value":"SBSDKOrientationLock"},{"value":[{"kind":"identifier","text":"SBSDKOrientationLock"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock\/navigatorTitle","value":[{"text":"SBSDKOrientationLock","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerUIConfiguration~1orientationLockMode\/title","value":"orientationLockMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerUIConfiguration~1orientationLockMode\/fragments","value":[{"text":"orientationLockMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerUIConfiguration\/title","op":"replace","value":"SBSDKUIBarcodeScannerUIConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerUIConfiguration\/fragments","value":[{"text":"SBSDKUIBarcodeScannerUIConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKUIBarcodeScannerUIConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerUIConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}