{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfield"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfield"]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKMedicalCertificateRecognizerResultPatientField","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientField"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKMedicalCertificateRecognizerResultPatientField","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerResultPatientField","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientField"}],"roleHeading":"Class","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerResultPatientField"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientField\/recognitionConfidence","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientField\/type","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientField\/value"]}],"abstract":[{"type":"text","text":"This class represents one entry of patient information recognized by medical certificate recognition."}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResultPatientField/value":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfield\/value","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"value","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientField\/value","role":"symbol","abstract":[{"type":"text","text":"The raw string value of the field."}],"navigatorTitle":[{"text":"value","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResultPatientField/type":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfield\/type","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerResultPatientFieldType","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldType"}],"title":"type","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientField\/type","role":"symbol","abstract":[{"text":"The type of the field.","type":"text"}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResultPatientField":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientField","title":"SBSDKMedicalCertificateRecognizerResultPatientField","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerResultPatientField","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfield","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientField"}],"kind":"symbol","abstract":[{"type":"text","text":"This class represents one entry of patient information recognized by medical certificate recognition."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResultPatientField/recognitionConfidence":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfield\/recognitionconfidence","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"recognitionConfidence","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"recognitionConfidence","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientField\/recognitionConfidence","role":"symbol","abstract":[{"text":"The confidence value of the character recognition.","type":"text"}],"navigatorTitle":[{"text":"recognitionConfidence","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResultPatientField/init":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfield\/init","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientField\/init","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalCertificateRecognizerResultPatientField"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientField"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificateRecognizerResultPatientField","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientField\/recognitionConfidence","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientField\/type","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientField\/value"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientField\/init"],"title":"Instance Methods"}]},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientField"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]}},{"op":"replace","value":"value","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientField~1value\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientField~1value\/fragments","value":[{"kind":"identifier","text":"value"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientField~1type\/title","value":"type","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientField~1type\/fragments","value":[{"text":"type","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKMedicalCertificateRecognizerResultPatientField","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientField\/title"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientField"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientField\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientField~1recognitionConfidence\/title","value":"recognitionConfidence"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientField~1recognitionConfidence\/fragments","value":[{"kind":"identifier","text":"recognitionConfidence"}],"op":"replace"}]}]}