{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"],"type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelSwissQR","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr"]}],"metadata":{"symbolKind":"class","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentModelSwissQR","kind":"identifier"}],"roleHeading":"Class","title":"SBSDKBarcodeDocumentModelSwissQR","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelSwissQR"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelSwissQR"},"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/additionalBillingInformation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/additionalInfoTrailer","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/additionalInfoUnstructured","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/alternativeProcedureParameter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/amount","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/currency","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorAddressType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorBuildingOrAddressLine2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorCountry","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorPlace","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorPostalCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorStreetOrAddressLine1","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/dueDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/encoding","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeeAddressType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeeBuildingOrAddressLine2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeeCountry","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeeName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeePlace","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeePostalCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeeStreetOrAddressLine1","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/iban","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/majorVersion","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeeAddressType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeeBuildingOrAddressLine2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeeCountry","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeeName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeePlace","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeePostalCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeeStreetOrAddressLine1","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/paymentReference","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/paymentReferenceType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/requiredDocumentType"],"title":"Instance Properties"}],"kind":"symbol","abstract":[{"type":"text","text":"SwissQR"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/finalPayeeAddressType":{"kind":"symbol","type":"topic","abstract":[{"text":"Final Payee Address Type","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/finalpayeeaddresstype","title":"finalPayeeAddressType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeeAddressType","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finalPayeeAddressType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"finalPayeeAddressType","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","abstract":[{"text":"Generic document.","type":"text"}],"title":"SBSDKGenericDocument","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocument"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/debtorAddressType":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debtorAddressType","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/debtoraddresstype","title":"debtorAddressType","abstract":[{"text":"Debtor Address Type","type":"text"}],"navigatorTitle":[{"text":"debtorAddressType","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorAddressType","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/debtorCountry":{"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"debtorCountry","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"text":"Debtor Country","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"debtorCountry"}],"title":"debtorCountry","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorCountry","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/debtorcountry"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/finalPayeeCountry":{"abstract":[{"type":"text","text":"Final Payee Country"}],"navigatorTitle":[{"kind":"identifier","text":"finalPayeeCountry"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeeCountry","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finalPayeeCountry","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"finalPayeeCountry","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/finalpayeecountry"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/payeeBuildingOrAddressLine2":{"kind":"symbol","title":"payeeBuildingOrAddressLine2","abstract":[{"text":"Payee Building Or Address Line 2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeeBuildingOrAddressLine2","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/payeebuildingoraddressline2","navigatorTitle":[{"kind":"identifier","text":"payeeBuildingOrAddressLine2"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"payeeBuildingOrAddressLine2"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/majorVersion":{"navigatorTitle":[{"kind":"identifier","text":"majorVersion"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/majorversion","abstract":[{"text":"Major Version","type":"text"}],"title":"majorVersion","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/majorVersion","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"majorVersion","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/paymentReference":{"title":"paymentReference","type":"topic","role":"symbol","abstract":[{"text":"Payment Reference","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentReference","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/paymentreference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/paymentReference","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentReference"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/debtorPlace":{"navigatorTitle":[{"kind":"identifier","text":"debtorPlace"}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"debtorPlace"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"title":"debtorPlace","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorPlace","abstract":[{"type":"text","text":"Debtor Place"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/debtorplace"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/finalPayeeStreetOrAddressLine1":{"type":"topic","title":"finalPayeeStreetOrAddressLine1","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/finalpayeestreetoraddressline1","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeeStreetOrAddressLine1","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"finalPayeeStreetOrAddressLine1","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"finalPayeeStreetOrAddressLine1","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"text":"Final Payee Street Or Address Line 1","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/payeePlace":{"title":"payeePlace","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/payeeplace","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeePlace","abstract":[{"type":"text","text":"Payee Place"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"payeePlace"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"payeePlace"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/finalPayeePostalCode":{"title":"finalPayeePostalCode","abstract":[{"text":"Final Payee Postal Code","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeePostalCode","navigatorTitle":[{"text":"finalPayeePostalCode","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalPayeePostalCode"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/finalpayeepostalcode","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR":{"type":"topic","role":"symbol","abstract":[{"text":"SwissQR","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr","title":"SBSDKBarcodeDocumentModelSwissQR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelSwissQR"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelSwissQR"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/debtorBuildingOrAddressLine2":{"role":"symbol","navigatorTitle":[{"text":"debtorBuildingOrAddressLine2","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Debtor Building Or Address Line 2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorBuildingOrAddressLine2","title":"debtorBuildingOrAddressLine2","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/debtorbuildingoraddressline2","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debtorBuildingOrAddressLine2"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/payeeAddressType":{"navigatorTitle":[{"text":"payeeAddressType","kind":"identifier"}],"kind":"symbol","title":"payeeAddressType","abstract":[{"text":"Payee Address Type","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payeeAddressType","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/payeeaddresstype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeeAddressType","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/iban":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/iban","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"iban"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"iban","kind":"identifier"}],"abstract":[{"type":"text","text":"IBAN"}],"kind":"symbol","type":"topic","title":"iban","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/iban","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/encoding":{"abstract":[{"type":"text","text":"Encoding"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"encoding"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/encoding","title":"encoding","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/encoding","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"encoding"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/payeePostalCode":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeePostalCode","type":"topic","title":"payeePostalCode","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/payeepostalcode","abstract":[{"type":"text","text":"Payee Postal Code"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"payeePostalCode"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"payeePostalCode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/initWithGenericDocument:":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/initwithgenericdocument:","title":"initWithGenericDocument:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithGenericDocument:"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/initWithGenericDocument:","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"role":"symbol","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/debtorStreetOrAddressLine1":{"title":"debtorStreetOrAddressLine1","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorStreetOrAddressLine1","kind":"symbol","abstract":[{"type":"text","text":"Debtor Street Or Address Line 1"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/debtorstreetoraddressline1","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debtorStreetOrAddressLine1"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"debtorStreetOrAddressLine1"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/currency":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Currency"}],"navigatorTitle":[{"text":"currency","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/currency","title":"currency","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/currency","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/paymentReferenceType":{"abstract":[{"type":"text","text":"Payment Reference Type"}],"navigatorTitle":[{"text":"paymentReferenceType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/paymentReferenceType","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentReferenceType"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"kind":"symbol","title":"paymentReferenceType","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/paymentreferencetype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/additionalInfoTrailer":{"navigatorTitle":[{"kind":"identifier","text":"additionalInfoTrailer"}],"title":"additionalInfoTrailer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"additionalInfoTrailer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"type":"text","text":"Additional Info Trailer"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/additionalInfoTrailer","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/additionalinfotrailer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/payeeName":{"abstract":[{"type":"text","text":"Payee Name"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeeName","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"payeeName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"payeeName","kind":"identifier"}],"kind":"symbol","title":"payeeName","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/payeename","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/requiredDocumentType":{"abstract":[{"type":"text","text":"The name of the wrapped document type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/requiredDocumentType","type":"topic","title":"requiredDocumentType","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"requiredDocumentType"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/requireddocumenttype","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/amount":{"abstract":[{"text":"Amount","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"amount"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/amount","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"amount","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"kind":"symbol","title":"amount","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/amount"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/additionalInfoUnstructured":{"abstract":[{"type":"text","text":"Additional Info Unstructured"}],"navigatorTitle":[{"text":"additionalInfoUnstructured","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/additionalInfoUnstructured","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"additionalInfoUnstructured"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"title":"additionalInfoUnstructured","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/additionalinfounstructured"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/payeeCountry":{"role":"symbol","kind":"symbol","title":"payeeCountry","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/payeecountry","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"payeeCountry","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"payeeCountry"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeeCountry","abstract":[{"type":"text","text":"Payee Country"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/additionalBillingInformation":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/additionalBillingInformation","abstract":[{"type":"text","text":"Additional Billing Information"}],"title":"additionalBillingInformation","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"additionalBillingInformation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"additionalBillingInformation"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/additionalbillinginformation","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/debtorName":{"role":"symbol","title":"debtorName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"debtorName"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorName","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/debtorname","navigatorTitle":[{"text":"debtorName","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Debtor Name","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/finalPayeePlace":{"abstract":[{"type":"text","text":"Final Payee Place"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeePlace","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"finalPayeePlace","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"finalPayeePlace","kind":"identifier"}],"kind":"symbol","title":"finalPayeePlace","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/finalpayeeplace","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/debtorPostalCode":{"abstract":[{"text":"Debtor Postal Code","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorPostalCode","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debtorPostalCode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"debtorPostalCode"}],"kind":"symbol","title":"debtorPostalCode","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/debtorpostalcode","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/finalPayeeBuildingOrAddressLine2":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeeBuildingOrAddressLine2","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/finalpayeebuildingoraddressline2","abstract":[{"text":"Final Payee Building Or Address Line 2","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalPayeeBuildingOrAddressLine2"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"finalPayeeBuildingOrAddressLine2","kind":"identifier"}],"title":"finalPayeeBuildingOrAddressLine2"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentWrapper":{"abstract":[{"type":"text","text":"Base class for strongly-typed "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","isActive":true,"type":"reference"},{"type":"text","text":" wrappers."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"title":"SBSDKGenericDocumentWrapper","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/finalPayeeName":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeeName","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"finalPayeeName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/finalpayeename","abstract":[{"type":"text","text":"Final Payee Name"}],"title":"finalPayeeName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"finalPayeeName"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/alternativeProcedureParameter":{"title":"alternativeProcedureParameter","navigatorTitle":[{"kind":"identifier","text":"alternativeProcedureParameter"}],"abstract":[{"type":"text","text":"Alternative Procedure Parameter"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/alternativeProcedureParameter","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/alternativeprocedureparameter","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"alternativeProcedureParameter","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/payeeStreetOrAddressLine1":{"abstract":[{"text":"Payee Street Or Address Line 1","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"payeeStreetOrAddressLine1","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/payeestreetoraddressline1","title":"payeeStreetOrAddressLine1","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payeeStreetOrAddressLine1","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeeStreetOrAddressLine1"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelSwissQR/dueDate":{"abstract":[{"text":"Due Date","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/dueDate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dueDate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelswissqr\/duedate","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"dueDate"}],"title":"dueDate"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKBarcodeDocumentModelSwissQR","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKBarcodeDocumentModelSwissQR","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelSwissQR"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/additionalBillingInformation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/additionalInfoTrailer","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/additionalInfoUnstructured","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/alternativeProcedureParameter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/amount","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/currency","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorAddressType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorBuildingOrAddressLine2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorCountry","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorPlace","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorPostalCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/debtorStreetOrAddressLine1","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/dueDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/encoding","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeeAddressType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeeBuildingOrAddressLine2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeeCountry","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeeName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeePlace","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeePostalCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/finalPayeeStreetOrAddressLine1","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/iban","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/majorVersion","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeeAddressType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeeBuildingOrAddressLine2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeeCountry","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeeName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeePlace","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeePostalCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/payeeStreetOrAddressLine1","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/paymentReference","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/paymentReferenceType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/requiredDocumentType"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelSwissQR\/initWithGenericDocument:"]}]},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentModelSwissQR","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentWrapper","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","text":"SBSDKGenericDocumentWrapper","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"finalPayeeAddressType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1finalPayeeAddressType\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1finalPayeeAddressType\/fragments","op":"replace","value":[{"text":"finalPayeeAddressType","kind":"identifier"}]},{"op":"replace","value":"SBSDKGenericDocument","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"op":"replace"},{"value":"debtorAddressType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1debtorAddressType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1debtorAddressType\/fragments","value":[{"kind":"identifier","text":"debtorAddressType"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1debtorCountry\/title","op":"replace","value":"debtorCountry"},{"value":[{"kind":"identifier","text":"debtorCountry"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1debtorCountry\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1finalPayeeCountry\/title","op":"replace","value":"finalPayeeCountry"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1finalPayeeCountry\/fragments","op":"replace","value":[{"kind":"identifier","text":"finalPayeeCountry"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1payeeBuildingOrAddressLine2\/title","value":"payeeBuildingOrAddressLine2"},{"value":[{"text":"payeeBuildingOrAddressLine2","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1payeeBuildingOrAddressLine2\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1majorVersion\/title","value":"majorVersion"},{"value":[{"text":"majorVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1majorVersion\/fragments","op":"replace"},{"op":"replace","value":"paymentReference","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1paymentReference\/title"},{"op":"replace","value":[{"kind":"identifier","text":"paymentReference"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1paymentReference\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1debtorPlace\/title","value":"debtorPlace","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1debtorPlace\/fragments","op":"replace","value":[{"kind":"identifier","text":"debtorPlace"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1finalPayeeStreetOrAddressLine1\/title","value":"finalPayeeStreetOrAddressLine1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1finalPayeeStreetOrAddressLine1\/fragments","value":[{"text":"finalPayeeStreetOrAddressLine1","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1payeePlace\/title","value":"payeePlace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1payeePlace\/fragments","value":[{"kind":"identifier","text":"payeePlace"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1finalPayeePostalCode\/title","value":"finalPayeePostalCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1finalPayeePostalCode\/fragments","value":[{"kind":"identifier","text":"finalPayeePostalCode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR\/title","value":"SBSDKBarcodeDocumentModelSwissQR","op":"replace"},{"value":[{"text":"SBSDKBarcodeDocumentModelSwissQR","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeDocumentModelSwissQR","kind":"identifier"}]},{"value":"debtorBuildingOrAddressLine2","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1debtorBuildingOrAddressLine2\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1debtorBuildingOrAddressLine2\/fragments","value":[{"text":"debtorBuildingOrAddressLine2","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1payeeAddressType\/title","value":"payeeAddressType","op":"replace"},{"value":[{"kind":"identifier","text":"payeeAddressType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1payeeAddressType\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1iban\/title","op":"replace","value":"iban"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1iban\/fragments","value":[{"kind":"identifier","text":"iban"}]},{"value":"encoding","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1encoding\/title"},{"value":[{"text":"encoding","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1encoding\/fragments"},{"value":"payeePostalCode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1payeePostalCode\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1payeePostalCode\/fragments","value":[{"kind":"identifier","text":"payeePostalCode"}]},{"value":"debtorStreetOrAddressLine1","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1debtorStreetOrAddressLine1\/title","op":"replace"},{"op":"replace","value":[{"text":"debtorStreetOrAddressLine1","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1debtorStreetOrAddressLine1\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1currency\/title","value":"currency","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1currency\/fragments","value":[{"kind":"identifier","text":"currency"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1paymentReferenceType\/title","op":"replace","value":"paymentReferenceType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1paymentReferenceType\/fragments","op":"replace","value":[{"kind":"identifier","text":"paymentReferenceType"}]},{"op":"replace","value":"additionalInfoTrailer","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1additionalInfoTrailer\/title"},{"value":[{"text":"additionalInfoTrailer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1additionalInfoTrailer\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1payeeName\/title","op":"replace","value":"payeeName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1payeeName\/fragments","value":[{"text":"payeeName","kind":"identifier"}]},{"value":"requiredDocumentType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1requiredDocumentType\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1requiredDocumentType\/fragments","value":[{"text":"requiredDocumentType","kind":"identifier"}]},{"value":"amount","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1amount\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1amount\/fragments","value":[{"text":"amount","kind":"identifier"}]},{"value":"additionalInfoUnstructured","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1additionalInfoUnstructured\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1additionalInfoUnstructured\/fragments","value":[{"text":"additionalInfoUnstructured","kind":"identifier"}],"op":"replace"},{"value":"payeeCountry","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1payeeCountry\/title"},{"value":[{"kind":"identifier","text":"payeeCountry"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1payeeCountry\/fragments"},{"value":"additionalBillingInformation","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1additionalBillingInformation\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1additionalBillingInformation\/fragments","value":[{"kind":"identifier","text":"additionalBillingInformation"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1debtorName\/title","op":"replace","value":"debtorName"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1debtorName\/fragments","op":"replace","value":[{"kind":"identifier","text":"debtorName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1finalPayeePlace\/title","value":"finalPayeePlace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1finalPayeePlace\/fragments","value":[{"text":"finalPayeePlace","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1debtorPostalCode\/title","value":"debtorPostalCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1debtorPostalCode\/fragments","value":[{"kind":"identifier","text":"debtorPostalCode"}]},{"value":"finalPayeeBuildingOrAddressLine2","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1finalPayeeBuildingOrAddressLine2\/title"},{"op":"replace","value":[{"kind":"identifier","text":"finalPayeeBuildingOrAddressLine2"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1finalPayeeBuildingOrAddressLine2\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/title","value":"SBSDKGenericDocumentWrapper"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1finalPayeeName\/title","op":"replace","value":"finalPayeeName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1finalPayeeName\/fragments","value":[{"kind":"identifier","text":"finalPayeeName"}]},{"op":"replace","value":"alternativeProcedureParameter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1alternativeProcedureParameter\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1alternativeProcedureParameter\/fragments","op":"replace","value":[{"kind":"identifier","text":"alternativeProcedureParameter"}]},{"op":"replace","value":"payeeStreetOrAddressLine1","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1payeeStreetOrAddressLine1\/title"},{"op":"replace","value":[{"kind":"identifier","text":"payeeStreetOrAddressLine1"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1payeeStreetOrAddressLine1\/fragments"},{"value":"dueDate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1dueDate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelSwissQR~1dueDate\/fragments","value":[{"text":"dueDate","kind":"identifier"}]}]}]}