{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerbehaviorconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerbehaviorconfiguration"]}],"metadata":{"title":"SBSDKUITextDataScannerBehaviorConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUITextDataScannerBehaviorConfiguration"}],"navigatorTitle":[{"text":"SBSDKUITextDataScannerBehaviorConfiguration","kind":"identifier"}],"symbolKind":"class","role":"symbol","roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerBehaviorConfiguration"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUITextDataScannerBehaviorConfiguration"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configuration for the behavior of RTU-UI text data scanner."}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/isFlashEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/maximumNumberOfAccumulatedFrames","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/minimumNumberOfRequiredFramesWithEqualRecognitionResult","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/ocrResolutionLimit","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/recognitionStep","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/wordBoxHighlightEnabled"],"anchor":"Instance-Properties","title":"Instance Properties"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerBehaviorConfiguration/wordBoxHighlightEnabled":{"navigatorTitle":[{"text":"wordBoxHighlightEnabled","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerbehaviorconfiguration\/wordboxhighlightenabled","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/wordBoxHighlightEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wordBoxHighlightEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"wordBoxHighlightEnabled","abstract":[{"type":"text","text":"Whether the word boxes should be shown."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerBehaviorConfiguration/isFlashEnabled":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isFlashEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerbehaviorconfiguration\/isflashenabled","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/isFlashEnabled","role":"symbol","abstract":[{"type":"text","text":"Whether flash is toggled on or off."}],"title":"isFlashEnabled","kind":"symbol","navigatorTitle":[{"text":"isFlashEnabled","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerBehaviorConfiguration/minimumNumberOfRequiredFramesWithEqualRecognitionResult":{"type":"topic","abstract":[{"type":"text","text":"The minimum equal results in accumulated video frames to count as valid."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/minimumNumberOfRequiredFramesWithEqualRecognitionResult","navigatorTitle":[{"text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"title":"minimumNumberOfRequiredFramesWithEqualRecognitionResult","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerbehaviorconfiguration\/minimumnumberofrequiredframeswithequalrecognitionresult","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerBehaviorConfiguration/maximumNumberOfAccumulatedFrames":{"title":"maximumNumberOfAccumulatedFrames","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/maximumNumberOfAccumulatedFrames","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerbehaviorconfiguration\/maximumnumberofaccumulatedframes","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The maximum number of accumulated video frames before the current recognition result is returned."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerBehaviorConfiguration":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUITextDataScannerBehaviorConfiguration"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUITextDataScannerBehaviorConfiguration"}],"title":"SBSDKUITextDataScannerBehaviorConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerbehaviorconfiguration","abstract":[{"type":"text","text":"Configuration for the behavior of RTU-UI text data scanner."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerBehaviorConfiguration/recognitionStep":{"kind":"symbol","title":"recognitionStep","navigatorTitle":[{"kind":"identifier","text":"recognitionStep"}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerbehaviorconfiguration\/recognitionstep","abstract":[{"text":"The data scanner recognition step.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"recognitionStep","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUITextDataScannerStep","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerStep","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/recognitionStep"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerBehaviorConfiguration/init":{"abstract":[],"role":"symbol","title":"init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerbehaviorconfiguration\/init"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerBehaviorConfiguration/ocrResolutionLimit":{"kind":"symbol","title":"ocrResolutionLimit","navigatorTitle":[{"kind":"identifier","text":"ocrResolutionLimit"}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerbehaviorconfiguration\/ocrresolutionlimit","abstract":[{"text":"Maximum image side length (height or width) for OCR processing. If the initial image has longer side - it will be downscaled to the limit.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ocrResolutionLimit","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/ocrResolutionLimit"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"SBSDKUITextDataScannerBehaviorConfiguration","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUITextDataScannerBehaviorConfiguration","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKUITextDataScannerBehaviorConfiguration","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/isFlashEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/maximumNumberOfAccumulatedFrames","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/minimumNumberOfRequiredFramesWithEqualRecognitionResult","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/ocrResolutionLimit","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/recognitionStep","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/wordBoxHighlightEnabled"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/init"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUITextDataScannerBehaviorConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration~1wordBoxHighlightEnabled\/title","op":"replace","value":"wordBoxHighlightEnabled"},{"value":[{"kind":"identifier","text":"wordBoxHighlightEnabled"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration~1wordBoxHighlightEnabled\/fragments"},{"op":"replace","value":"isFlashEnabled","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration~1isFlashEnabled\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration~1isFlashEnabled\/fragments","value":[{"kind":"identifier","text":"isFlashEnabled"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration~1minimumNumberOfRequiredFramesWithEqualRecognitionResult\/title","value":"minimumNumberOfRequiredFramesWithEqualRecognitionResult","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration~1minimumNumberOfRequiredFramesWithEqualRecognitionResult\/fragments","value":[{"text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration~1maximumNumberOfAccumulatedFrames\/title","value":"maximumNumberOfAccumulatedFrames","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration~1maximumNumberOfAccumulatedFrames\/fragments","value":[{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration\/title","value":"SBSDKUITextDataScannerBehaviorConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUITextDataScannerBehaviorConfiguration"}]},{"value":[{"kind":"identifier","text":"SBSDKUITextDataScannerBehaviorConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration~1recognitionStep\/title","op":"replace","value":"recognitionStep"},{"op":"replace","value":[{"text":"recognitionStep","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration~1recognitionStep\/fragments"},{"op":"replace","value":"ocrResolutionLimit","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration~1ocrResolutionLimit\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration~1ocrResolutionLimit\/fragments","value":[{"kind":"identifier","text":"ocrResolutionLimit"}],"op":"replace"}]}]}