{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontrollerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontrollerdelegate"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"type":"text","text":"The delegate protocol for the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","isActive":true},{"text":".","type":"text"}],"kind":"symbol","relationshipsSections":[{"type":"conformingTypes","title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicensePlateScannerViewControllerDelegate"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicensePlateScannerViewControllerDelegate","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKLicensePlateScannerViewControllerDelegate","title":"SBSDKLicensePlateScannerViewControllerDelegate","roleHeading":"Protocol","symbolKind":"protocol","modules":[{"name":"ScanbotSDK"}]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate\/licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate\/licensePlateScannerViewControllerShouldRecognize(_:)"],"title":"Instance Methods"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLicensePlateScannerViewControllerDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewController":{"title":"SBSDKLicensePlateScannerViewController","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","navigatorTitle":[{"text":"SBSDKLicensePlateScannerViewController","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to scan for license plates with the camera.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLicensePlateScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController":{"title":"SBSDKUILicensePlateScannerViewController","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController","navigatorTitle":[{"text":"SBSDKUILicensePlateScannerViewController","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan vehicle license plates in realtime."}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUILicensePlateScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewControllerDelegate/licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)":{"title":"licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate\/licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)","navigatorTitle":[{"text":"licensePlateScannerViewController:didRecognizeLicensePlate:on:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"licensePlateScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerViewController","kind":"typeIdentifier","text":"SBSDKLicensePlateScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRecognizeLicensePlate"},{"text":": ","kind":"text"},{"text":"SBSDKLicensePlateScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontrollerdelegate\/licenseplatescannerviewcontroller(_:didrecognizelicenseplate:on:)","required":true,"type":"topic","abstract":[{"type":"text","text":"Informs the delegate that a license plate has been recognized successfully."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewControllerDelegate/licensePlateScannerViewControllerShouldRecognize(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontrollerdelegate\/licenseplatescannerviewcontrollershouldrecognize(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"licensePlateScannerViewControllerShouldRecognize"},{"kind":"text","text":"("},{"text":"SBSDKLicensePlateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"licensePlateScannerViewControllerShouldRecognize:"}],"abstract":[{"type":"text","text":"Asks the delegate whether the next video frame should be scanned or not."}],"title":"licensePlateScannerViewControllerShouldRecognize(_:)","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate\/licensePlateScannerViewControllerShouldRecognize(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewControllerDelegate":{"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontrollerdelegate","kind":"symbol","abstract":[{"text":"The delegate protocol for the ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKLicensePlateScannerViewControllerDelegate","kind":"identifier"}],"title":"SBSDKLicensePlateScannerViewControllerDelegate","role":"symbol","navigatorTitle":[{"text":"SBSDKLicensePlateScannerViewControllerDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKLicensePlateScannerViewControllerDelegate"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerViewControllerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerViewControllerDelegate"}]},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate\/licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate\/licensePlateScannerViewControllerShouldRecognize(_:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"conformingTypes","kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"SBSDKLicensePlateScannerViewControllerDelegate","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController\/title","value":"SBSDKLicensePlateScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController\/fragments","value":[{"text":"SBSDKLicensePlateScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/title","value":"SBSDKUILicensePlateScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewControllerDelegate~1licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)\/title","value":"licensePlateScannerViewController:didRecognizeLicensePlate:on:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"licensePlateScannerViewController:didRecognizeLicensePlate:on:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewControllerDelegate~1licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewControllerDelegate~1licensePlateScannerViewControllerShouldRecognize(_:)\/title","op":"replace","value":"licensePlateScannerViewControllerShouldRecognize:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewControllerDelegate~1licensePlateScannerViewControllerShouldRecognize(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"licensePlateScannerViewControllerShouldRecognize:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewControllerDelegate\/title","value":"SBSDKLicensePlateScannerViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewControllerDelegate\/fragments","value":[{"text":"SBSDKLicensePlateScannerViewControllerDelegate","kind":"identifier"}]}]}]}