{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"title":"SBSDKDocumentPageImageSource","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentPageImageSource","modules":[{"name":"ScanbotSDK"}],"symbolKind":"enum","roleHeading":"Enumeration"},"abstract":[{"text":"The source from where the image of the page originated from.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/autoSnap","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/imported","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/manualSnap","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/undefined","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/videoFrame"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource/imported":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/imported","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imported"}],"kind":"symbol","type":"topic","title":"SBSDKDocumentPageImageSource.imported","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/imported","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceImported"}],"role":"symbol","abstract":[{"text":"If the source image was imported from external source.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource/manualSnap":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/manualsnap","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/manualSnap","title":"SBSDKDocumentPageImageSource.manualSnap","abstract":[{"type":"text","text":"If the source image was captured manually. For example, when the user pressed a snap button."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"manualSnap"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceManualSnap"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource/autoSnap":{"abstract":[{"type":"text","text":"If the source image was captured automatically. For example, by auto snapping functions."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/autoSnap","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/autosnap","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoSnap","kind":"identifier"}],"title":"SBSDKDocumentPageImageSource.autoSnap","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceAutoSnap"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource":{"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource","title":"SBSDKDocumentPageImageSource","navigatorTitle":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"abstract":[{"type":"text","text":"The source from where the image of the page originated from."}]},"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource/Equatable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/equatable-implementations","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations","abstract":[],"kind":"article"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource/init(rawValue:)":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/init(rawValue:)","title":"init(rawValue:)","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/init(rawvalue:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource/undefined":{"navigatorTitle":[{"text":"SBSDKDocumentPageImageSourceUndefined","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/undefined","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"undefined","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"SBSDKDocumentPageImageSource.undefined","abstract":[{"type":"text","text":"Used by default. If the source is not defined."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/undefined"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/RawRepresentable-Implementations","role":"collectionGroup","abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/rawrepresentable-implementations","title":"RawRepresentable Implementations","kind":"article"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource/videoFrame":{"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoFrame","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/videoFrame","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/videoframe","title":"SBSDKDocumentPageImageSource.videoFrame","navigatorTitle":[{"text":"SBSDKDocumentPageImageSourceVideoFrame","kind":"identifier"}],"abstract":[{"type":"text","text":"If the source image was taken from the video frame."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKDocumentPageImageSource"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/autoSnap","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/imported","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/manualSnap","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/undefined","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/videoFrame"],"title":"Enumeration Cases"}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageImageSource","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentPageImageSourceImported","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1imported\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1imported\/fragments","op":"replace","value":[{"text":"SBSDKDocumentPageImageSourceImported","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1manualSnap\/title","value":"SBSDKDocumentPageImageSourceManualSnap"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1manualSnap\/fragments","value":[{"text":"SBSDKDocumentPageImageSourceManualSnap","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1autoSnap\/title","value":"SBSDKDocumentPageImageSourceAutoSnap"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1autoSnap\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceAutoSnap"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource\/title","value":"SBSDKDocumentPageImageSource"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource\/fragments","value":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1undefined\/title","value":"SBSDKDocumentPageImageSourceUndefined"},{"value":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceUndefined"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1undefined\/fragments","op":"replace"},{"value":"SBSDKDocumentPageImageSourceVideoFrame","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1videoFrame\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1videoFrame\/fragments","value":[{"text":"SBSDKDocumentPageImageSourceVideoFrame","kind":"identifier"}]}]}]}