{"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"title":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerAccessibilityConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Class","symbolKind":"class"},"abstract":[{"type":"text","text":"Configuration for the accessibility labels and hints."}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/cancelButtonAccessibilityHint","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/cancelButtonAccessibilityLabel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/flashButtonAccessibilityHint","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/flashButtonAccessibilityLabel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/shutterButtonAccessibilityHint","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/shutterButtonAccessibilityLabel"],"title":"Instance Properties"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerAccessibilityConfiguration/shutterButtonAccessibilityLabel":{"abstract":[{"text":"Text, that is used as an accessibility label for the shutter button.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/shutterButtonAccessibilityLabel","title":"shutterButtonAccessibilityLabel","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"shutterButtonAccessibilityLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"shutterButtonAccessibilityLabel","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration\/shutterbuttonaccessibilitylabel","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerAccessibilityConfiguration/shutterButtonAccessibilityHint":{"title":"shutterButtonAccessibilityHint","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Text, that is used as an accessibility hint for the shutter button."}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration\/shutterbuttonaccessibilityhint","navigatorTitle":[{"text":"shutterButtonAccessibilityHint","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"shutterButtonAccessibilityHint","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/shutterButtonAccessibilityHint"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerAccessibilityConfiguration/cancelButtonAccessibilityHint":{"title":"cancelButtonAccessibilityHint","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/cancelButtonAccessibilityHint","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration\/cancelbuttonaccessibilityhint","abstract":[{"type":"text","text":"Text, that is used as an accessibility hint for the cancel button."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cancelButtonAccessibilityHint","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"cancelButtonAccessibilityHint"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerAccessibilityConfiguration/cancelButtonAccessibilityLabel":{"title":"cancelButtonAccessibilityLabel","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration\/cancelbuttonaccessibilitylabel","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/cancelButtonAccessibilityLabel","abstract":[{"text":"Text, that is used as an accessibility label for the cancel button.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancelButtonAccessibilityLabel"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"cancelButtonAccessibilityLabel"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerAccessibilityConfiguration":{"title":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"symbol","role":"symbol","abstract":[{"text":"Configuration for the accessibility labels and hints.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration","navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerAccessibilityConfiguration/flashButtonAccessibilityLabel":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/flashButtonAccessibilityLabel","title":"flashButtonAccessibilityLabel","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration\/flashbuttonaccessibilitylabel","navigatorTitle":[{"kind":"identifier","text":"flashButtonAccessibilityLabel"}],"abstract":[{"type":"text","text":"Text, that is used as an accessibility label for the flash button."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"flashButtonAccessibilityLabel"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerAccessibilityConfiguration/flashButtonAccessibilityHint":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/flashButtonAccessibilityHint","title":"flashButtonAccessibilityHint","abstract":[{"text":"Text, that is used as an accessibility hint for the flash button.","type":"text"}],"navigatorTitle":[{"text":"flashButtonAccessibilityHint","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration\/flashbuttonaccessibilityhint","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"flashButtonAccessibilityHint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerAccessibilityConfiguration/init":{"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration\/init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/init","type":"topic","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"kind":"symbol","title":"init"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/cancelButtonAccessibilityHint","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/cancelButtonAccessibilityLabel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/flashButtonAccessibilityHint","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/flashButtonAccessibilityLabel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/shutterButtonAccessibilityHint","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/shutterButtonAccessibilityLabel"],"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/init"],"title":"Instance Methods"}],"op":"replace"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration~1shutterButtonAccessibilityLabel\/title","op":"replace","value":"shutterButtonAccessibilityLabel"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration~1shutterButtonAccessibilityLabel\/fragments","value":[{"kind":"identifier","text":"shutterButtonAccessibilityLabel"}]},{"op":"replace","value":"shutterButtonAccessibilityHint","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration~1shutterButtonAccessibilityHint\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration~1shutterButtonAccessibilityHint\/fragments","value":[{"kind":"identifier","text":"shutterButtonAccessibilityHint"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration~1cancelButtonAccessibilityHint\/title","op":"replace","value":"cancelButtonAccessibilityHint"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration~1cancelButtonAccessibilityHint\/fragments","value":[{"text":"cancelButtonAccessibilityHint","kind":"identifier"}]},{"value":"cancelButtonAccessibilityLabel","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration~1cancelButtonAccessibilityLabel\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration~1cancelButtonAccessibilityLabel\/fragments","value":[{"kind":"identifier","text":"cancelButtonAccessibilityLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/title","value":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/fragments","value":[{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration~1flashButtonAccessibilityLabel\/title","value":"flashButtonAccessibilityLabel"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration~1flashButtonAccessibilityLabel\/fragments","value":[{"text":"flashButtonAccessibilityLabel","kind":"identifier"}]},{"value":"flashButtonAccessibilityHint","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration~1flashButtonAccessibilityHint\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration~1flashButtonAccessibilityHint\/fragments","value":[{"kind":"identifier","text":"flashButtonAccessibilityHint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}