{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/create(with:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/present(on:configuration:completion:)"],"title":"Type Methods"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/SBSDKImageEditingViewControllerDelegate-Implementations"],"title":"Default Implementations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Class","title":"SBSDKUI2CroppingViewController","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingViewController"},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)UIViewController"],"title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/s8SendableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring","doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"abstract":[{"text":"A highly customizable view controller to edit the page polygon or the page orientation.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}]}]}],"references":{"doc://net.doo.ScanbotSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://net.doo.ScanbotSDK/objc(cs)UIViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)UIViewController","type":"unresolvable","title":"UIViewController"},"doc://net.doo.ScanbotSDK/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate":{"title":"SBSDKImageEditingViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"abstract":[{"text":"A delegate protocol to inform an object about changes in ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","type":"reference"},{"text":".","type":"text"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingViewController/supportedInterfaceOrientations":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/supportedInterfaceOrientations","abstract":[],"title":"supportedInterfaceOrientations","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller\/supportedinterfaceorientations","role":"symbol","fragments":[{"text":"supportedInterfaceOrientations","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingViewController":{"abstract":[{"type":"text","text":"A highly customizable view controller to edit the page polygon or the page orientation."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"title":"SBSDKUI2CroppingViewController","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingViewController/SBSDKImageEditingViewControllerDelegate-Implementations":{"kind":"article","role":"collectionGroup","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller\/sbsdkimageeditingviewcontrollerdelegate-implementations","type":"topic","title":"SBSDKImageEditingViewControllerDelegate Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/SBSDKImageEditingViewControllerDelegate-Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingViewController/initWithNibName:bundle:":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller\/initwithnibname:bundle:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/initWithNibName:bundle:","title":"initWithNibName:bundle:"},"doc://net.doo.ScanbotSDK/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingViewController/present(on:configuration:completion:)":{"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller\/present(on:configuration:completion:)","role":"symbol","abstract":[{"type":"text","text":"Creates a new instance of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController"},{"text":" and presents it modally.","type":"text"}],"title":"present(on:configuration:completion:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/present(on:configuration:completion:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"presentOn:configuration:completion:"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2CroppingConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingResult","text":"SBSDKUI2CroppingResult"},{"kind":"text","text":") -> ())?)"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingViewController/preferredStatusBarStyle":{"title":"preferredStatusBarStyle","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/preferredStatusBarStyle","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller\/preferredstatusbarstyle","abstract":[],"fragments":[{"text":"preferredStatusBarStyle","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingViewController/create(with:completion:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/create(with:completion:)","abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController","isActive":true},{"type":"text","text":" and returns it to be presented modally."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller\/create(with:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createWith:completion:"}],"type":"topic","kind":"symbol","title":"create(with:completion:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingConfiguration","kind":"typeIdentifier","text":"SBSDKUI2CroppingConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"SBSDKUI2CroppingResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingResult","kind":"typeIdentifier"},{"text":") -> ())?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingViewController","kind":"typeIdentifier","text":"SBSDKUI2CroppingViewController"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"navigatorTitle":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","kind":"symbol","title":"SBSDKImageEditingViewController","role":"symbol","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show and edit an image."}],"url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller"},"doc://net.doo.ScanbotSDK/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer"},"doc://net.doo.ScanbotSDK/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingViewController/initWithCoder:":{"title":"initWithCoder:","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/initWithCoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller\/initwithcoder:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/s8SendableP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://net.doo.ScanbotSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://net.doo.ScanbotSDK/objc(pl)NSCoding":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://net.doo.ScanbotSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingViewController/prefersStatusBarHidden":{"title":"prefersStatusBarHidden","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/prefersStatusBarHidden","kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller\/prefersstatusbarhidden","fragments":[{"text":"prefersStatusBarHidden","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingViewController/viewDidLoad":{"title":"viewDidLoad","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/viewDidLoad","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller\/viewdidload","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUI2CroppingViewController"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CroppingViewController"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/preferredStatusBarStyle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/prefersStatusBarHidden","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/supportedInterfaceOrientations"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/initWithCoder:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/initWithNibName:bundle:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/viewDidLoad"]},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/create(with:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/present(on:configuration:completion:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/SBSDKImageEditingViewControllerDelegate-Implementations"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)UIViewController"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CroppingViewController"},{"kind":"text","text":" : "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate\/title","value":"SBSDKImageEditingViewControllerDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController\/title","op":"replace","value":"SBSDKUI2CroppingViewController"},{"value":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController~1present(on:configuration:completion:)\/title","value":"presentOn:configuration:completion:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController~1present(on:configuration:completion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"presentOn:configuration:completion:","kind":"identifier"}]},{"op":"replace","value":"createWith:completion:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController~1create(with:completion:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController~1create(with:completion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWith:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/title","value":"SBSDKImageEditingViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKImageEditingViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}