{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Medical Certificate Document Field Type"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType"}],"title":"SBSDKUI2MedicalCertificateDocumentFieldType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2MedicalCertificateDocumentFieldType","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/accident","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/assignedToAccidentInsuranceDoctor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/birthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/diagnose","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/diagnosedOn","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/doctorNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/documentDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/firstName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/healthInsuranceNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/incapableOfWorkSince","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/incapableOfWorkUntil","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/initialCertificate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/insuredPersonNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/lastName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/placeOfOperationNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/renewedCertificate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/requiresCare","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/requiresCareFrom","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/requiresCareUntil","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/status","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/unknown","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/workAccident"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/renewedCertificate":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.renewedCertificate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"renewedCertificate"}],"abstract":[{"type":"text","text":"Renewed Certificate"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/renewedCertificate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeRenewedCertificate"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/renewedcertificate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/assignedToAccidentInsuranceDoctor":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.assignedToAccidentInsuranceDoctor","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"assignedToAccidentInsuranceDoctor"}],"abstract":[{"type":"text","text":"Assigned To Accident Insurance Doctor"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/assignedToAccidentInsuranceDoctor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeAssignedToAccidentInsuranceDoctor"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/assignedtoaccidentinsurancedoctor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/requiresCareUntil":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.requiresCareUntil","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresCareUntil"}],"abstract":[{"type":"text","text":"Requires Care Until"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/requiresCareUntil","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeRequiresCareUntil"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/requirescareuntil"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/birthDate":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.birthDate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthDate"}],"abstract":[{"type":"text","text":"Birth Date"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/birthDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeBirthDate"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/birthdate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/healthInsuranceNumber":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.healthInsuranceNumber","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"healthInsuranceNumber"}],"abstract":[{"type":"text","text":"Health Insurance Number"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/healthInsuranceNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeHealthInsuranceNumber"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/healthinsurancenumber"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/rawrepresentable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/incapableOfWorkSince":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.incapableOfWorkSince","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"incapableOfWorkSince"}],"abstract":[{"type":"text","text":"Incapable Of Work Since"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/incapableOfWorkSince","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeIncapableOfWorkSince"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/incapableofworksince"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/incapableOfWorkUntil":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.incapableOfWorkUntil","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"incapableOfWorkUntil"}],"abstract":[{"type":"text","text":"Incapable Of Work Until"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/incapableOfWorkUntil","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeIncapableOfWorkUntil"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/incapableofworkuntil"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/insuredPersonNumber":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.insuredPersonNumber","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"insuredPersonNumber"}],"abstract":[{"type":"text","text":"Insured Person Number"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/insuredPersonNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeInsuredPersonNumber"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/insuredpersonnumber"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/requiresCare":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.requiresCare","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresCare"}],"abstract":[{"type":"text","text":"Requires Care"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/requiresCare","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeRequiresCare"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/requirescare"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/doctorNumber":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.doctorNumber","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"doctorNumber"}],"abstract":[{"type":"text","text":"Doctor Number"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/doctorNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeDoctorNumber"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/doctornumber"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/init(rawvalue:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/diagnosedOn":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.diagnosedOn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"diagnosedOn"}],"abstract":[{"type":"text","text":"Diagnosed On"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/diagnosedOn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeDiagnosedOn"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/diagnosedon"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/diagnose":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.diagnose","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"diagnose"}],"abstract":[{"type":"text","text":"Diagnose"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/diagnose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeDiagnose"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/diagnose"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/unknown":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"Unknown"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeUnknown"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/unknown"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/workAccident":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.workAccident","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"workAccident"}],"abstract":[{"type":"text","text":"Work Accident"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/workAccident","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeWorkAccident"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/workaccident"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType"}],"abstract":[{"type":"text","text":"Medical Certificate Document Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/accident":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.accident","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"accident"}],"abstract":[{"type":"text","text":"Accident"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/accident","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeAccident"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/accident"},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/lastName":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.lastName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastName"}],"abstract":[{"type":"text","text":"Last Name"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/lastName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeLastName"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/lastname"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/equatable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/requiresCareFrom":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.requiresCareFrom","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresCareFrom"}],"abstract":[{"type":"text","text":"Requires Care From"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/requiresCareFrom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeRequiresCareFrom"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/requirescarefrom"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/placeOfOperationNumber":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.placeOfOperationNumber","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeOfOperationNumber"}],"abstract":[{"type":"text","text":"Place Of Operation Number"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/placeOfOperationNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypePlaceOfOperationNumber"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/placeofoperationnumber"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/initialCertificate":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.initialCertificate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialCertificate"}],"abstract":[{"type":"text","text":"Initial Certificate"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/initialCertificate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeInitialCertificate"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/initialcertificate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/documentDate":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.documentDate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDate"}],"abstract":[{"type":"text","text":"Document Date"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/documentDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeDocumentDate"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/documentdate"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/status":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.status","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"}],"abstract":[{"type":"text","text":"Status"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/status","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeStatus"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/status"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/firstName":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.firstName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstName"}],"abstract":[{"type":"text","text":"First Name"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/firstName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeFirstName"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/firstname"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/accident","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/assignedToAccidentInsuranceDoctor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/birthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/diagnose","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/diagnosedOn","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/doctorNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/documentDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/firstName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/healthInsuranceNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/incapableOfWorkSince","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/incapableOfWorkUntil","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/initialCertificate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/insuredPersonNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/lastName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/placeOfOperationNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/renewedCertificate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/requiresCare","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/requiresCareFrom","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/requiresCareUntil","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/status","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/unknown","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/workAccident"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1renewedCertificate\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeRenewedCertificate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1renewedCertificate\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeRenewedCertificate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1assignedToAccidentInsuranceDoctor\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeAssignedToAccidentInsuranceDoctor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1assignedToAccidentInsuranceDoctor\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeAssignedToAccidentInsuranceDoctor"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1requiresCareUntil\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeRequiresCareUntil"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1requiresCareUntil\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeRequiresCareUntil"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1birthDate\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeBirthDate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1birthDate\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeBirthDate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1healthInsuranceNumber\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeHealthInsuranceNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1healthInsuranceNumber\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeHealthInsuranceNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1incapableOfWorkSince\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeIncapableOfWorkSince"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1incapableOfWorkSince\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeIncapableOfWorkSince"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1incapableOfWorkUntil\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeIncapableOfWorkUntil"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1incapableOfWorkUntil\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeIncapableOfWorkUntil"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1insuredPersonNumber\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeInsuredPersonNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1insuredPersonNumber\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeInsuredPersonNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1requiresCare\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeRequiresCare"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1requiresCare\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeRequiresCare"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1doctorNumber\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeDoctorNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1doctorNumber\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeDoctorNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1diagnosedOn\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeDiagnosedOn"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1diagnosedOn\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeDiagnosedOn"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1diagnose\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeDiagnose"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1diagnose\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeDiagnose"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1unknown\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeUnknown"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1unknown\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1workAccident\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeWorkAccident"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1workAccident\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeWorkAccident"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1accident\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeAccident"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1accident\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeAccident"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1lastName\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeLastName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1lastName\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeLastName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1requiresCareFrom\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeRequiresCareFrom"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1requiresCareFrom\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeRequiresCareFrom"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1placeOfOperationNumber\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypePlaceOfOperationNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1placeOfOperationNumber\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypePlaceOfOperationNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1initialCertificate\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeInitialCertificate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1initialCertificate\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeInitialCertificate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1documentDate\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeDocumentDate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1documentDate\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeDocumentDate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1status\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1status\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1firstName\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeFirstName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1firstName\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeFirstName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}