{"metadata":{"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckRecognizerTextConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUICheckRecognizerTextConfiguration","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerTextConfiguration","modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","title":"SBSDKUICheckRecognizerTextConfiguration","role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships"}],"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/cancelButtonTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/errorAlertButtonText","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/errorAlertMessage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/errorAlertTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/flashButtonTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/userGuidanceTitleEnergySaving","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/userGuidanceTitleSearching","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/userGuidanceTitleStartScanning"]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizertextconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizertextconfiguration"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckRecognizerTextConfiguration","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Configuration for the textual contents of the  RTU-UI check scanner.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerTextConfiguration/errorAlertMessage":{"title":"errorAlertMessage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/errorAlertMessage","kind":"symbol","abstract":[{"text":"String being displayed as the message in the error alert that may occur when the recognition fails on captured high-resolution images.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"errorAlertMessage","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"errorAlertMessage"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizertextconfiguration\/erroralertmessage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerTextConfiguration":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckRecognizerTextConfiguration"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizertextconfiguration","type":"topic","title":"SBSDKUICheckRecognizerTextConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckRecognizerTextConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for the textual contents of the  RTU-UI check scanner."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerTextConfiguration/userGuidanceTitleEnergySaving":{"kind":"symbol","navigatorTitle":[{"text":"userGuidanceTitleEnergySaving","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/userGuidanceTitleEnergySaving","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizertextconfiguration\/userguidancetitleenergysaving","type":"topic","title":"userGuidanceTitleEnergySaving","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userGuidanceTitleEnergySaving"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"String being displayed when energy saving is active."}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerTextConfiguration/userGuidanceTitleStartScanning":{"abstract":[{"text":"String being displayed when starting scanning for a medical certificate. Lasts 3 secs.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userGuidanceTitleStartScanning"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"userGuidanceTitleStartScanning","kind":"identifier"}],"title":"userGuidanceTitleStartScanning","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/userGuidanceTitleStartScanning","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizertextconfiguration\/userguidancetitlestartscanning"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerTextConfiguration/userGuidanceTitleSearching":{"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizertextconfiguration\/userguidancetitlesearching","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"userGuidanceTitleSearching","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"userGuidanceTitleSearching","kind":"identifier"}],"title":"userGuidanceTitleSearching","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/userGuidanceTitleSearching","abstract":[{"text":"String being displayed when searching for a medical certificate.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerTextConfiguration/errorAlertTitle":{"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizertextconfiguration\/erroralerttitle","title":"errorAlertTitle","abstract":[{"text":"String being displayed as the title in the error alert that may occur when the recognition fails on captured high-resolution images.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/errorAlertTitle","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorAlertTitle"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"errorAlertTitle"}]},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerTextConfiguration/flashButtonTitle":{"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizertextconfiguration\/flashbuttontitle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"flashButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"flashButtonTitle","kind":"identifier"}],"title":"flashButtonTitle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/flashButtonTitle","abstract":[{"text":"String being displayed on the flash button.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerTextConfiguration/errorAlertButtonText":{"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizertextconfiguration\/erroralertbuttontext","navigatorTitle":[{"text":"errorAlertButtonText","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/errorAlertButtonText","abstract":[{"type":"text","text":"String being displayed as the button text in the error alert that may occur when the recognition fails on captured high-resolution images."}],"role":"symbol","type":"topic","title":"errorAlertButtonText","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorAlertButtonText"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIEnableCameraTextConfiguration":{"role":"symbol","abstract":[{"text":"Configuration for the textual contents of camera based view controllers.","type":"text"}],"title":"SBSDKUIEnableCameraTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuienablecameratextconfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerTextConfiguration/init":{"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizertextconfiguration\/init","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"title":"init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/init","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerTextConfiguration/cancelButtonTitle":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/cancelButtonTitle","type":"topic","abstract":[{"text":"String being displayed on the cancel button.","type":"text"}],"title":"cancelButtonTitle","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizertextconfiguration\/cancelbuttontitle","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cancelButtonTitle"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelButtonTitle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUICheckRecognizerTextConfiguration"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKUICheckRecognizerTextConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUICheckRecognizerTextConfiguration","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/cancelButtonTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/errorAlertButtonText","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/errorAlertMessage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/errorAlertTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/flashButtonTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/userGuidanceTitleEnergySaving","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/userGuidanceTitleSearching","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/userGuidanceTitleStartScanning"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration\/init"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration"],"kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICheckRecognizerTextConfiguration"},{"kind":"text","text":" : "},{"text":"SBSDKUIEnableCameraTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIEnableCameraTextConfiguration"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"errorAlertMessage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration~1errorAlertMessage\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration~1errorAlertMessage\/fragments","value":[{"kind":"identifier","text":"errorAlertMessage"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration\/title","value":"SBSDKUICheckRecognizerTextConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKUICheckRecognizerTextConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration~1userGuidanceTitleEnergySaving\/title","value":"userGuidanceTitleEnergySaving","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration~1userGuidanceTitleEnergySaving\/fragments","value":[{"text":"userGuidanceTitleEnergySaving","kind":"identifier"}]},{"op":"replace","value":"userGuidanceTitleStartScanning","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration~1userGuidanceTitleStartScanning\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration~1userGuidanceTitleStartScanning\/fragments","value":[{"text":"userGuidanceTitleStartScanning","kind":"identifier"}]},{"op":"replace","value":"userGuidanceTitleSearching","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration~1userGuidanceTitleSearching\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration~1userGuidanceTitleSearching\/fragments","value":[{"kind":"identifier","text":"userGuidanceTitleSearching"}]},{"value":"errorAlertTitle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration~1errorAlertTitle\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration~1errorAlertTitle\/fragments","value":[{"kind":"identifier","text":"errorAlertTitle"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration~1flashButtonTitle\/title","value":"flashButtonTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration~1flashButtonTitle\/fragments","value":[{"kind":"identifier","text":"flashButtonTitle"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration~1errorAlertButtonText\/title","value":"errorAlertButtonText","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration~1errorAlertButtonText\/fragments","value":[{"text":"errorAlertButtonText","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKUIEnableCameraTextConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration~1cancelButtonTitle\/title","value":"cancelButtonTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration~1cancelButtonTitle\/fragments","op":"replace","value":[{"text":"cancelButtonTitle","kind":"identifier"}]}]}]}