{"relationshipsSections":[{"title":"Conforming Types","kind":"relationships","type":"conformingTypes","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController"]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"SBSDKCheckRecognizerViewControllerDelegate","symbolKind":"protocol","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKCheckRecognizerViewControllerDelegate","role":"symbol","navigatorTitle":[{"text":"SBSDKCheckRecognizerViewControllerDelegate","kind":"identifier"}],"roleHeading":"Protocol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKCheckRecognizerViewControllerDelegate","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCheckRecognizerViewControllerDelegate"}],"platforms":["iOS"]}]}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate\/checkRecognizerViewController(_:didChangeState:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate\/checkRecognizerViewController(_:didRecognizeCheck:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate\/checkRecognizerViewControllerShouldRecognize(_:)"],"title":"Instance Methods"}],"sections":[],"abstract":[{"type":"text","text":"The delegation protocol for the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController"},{"text":" class.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewControllerDelegate/checkRecognizerViewControllerShouldRecognize(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate\/checkrecognizerviewcontrollershouldrecognize(_:)","type":"topic","abstract":[{"text":"Asks the delegate if the check recognizer should scan the next video frame. Optional.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkRecognizerViewControllerShouldRecognize","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController","text":"SBSDKCheckRecognizerViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate\/checkRecognizerViewControllerShouldRecognize(_:)","navigatorTitle":[{"kind":"identifier","text":"checkRecognizerViewControllerShouldRecognize:"}],"role":"symbol","title":"checkRecognizerViewControllerShouldRecognize(_:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewControllerDelegate/checkRecognizerViewController(_:didChangeState:)":{"title":"checkRecognizerViewController(_:didChangeState:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"checkRecognizerViewController:didChangeState:"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkRecognizerViewController"},{"kind":"text","text":"("},{"text":"SBSDKCheckRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didChangeState","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckRecognizerState","text":"SBSDKCheckRecognizerState"},{"text":")","kind":"text"}],"abstract":[{"text":"Informs the delegate, that the check scanner has changed its detection\/recognition state. Optional.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate\/checkRecognizerViewController(_:didChangeState:)","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate\/checkrecognizerviewcontroller(_:didchangestate:)","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewControllerDelegate/checkRecognizerViewController(_:didRecognizeCheck:)":{"title":"checkRecognizerViewController(_:didRecognizeCheck:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate\/checkRecognizerViewController(_:didRecognizeCheck:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkRecognizerViewController"},{"text":"(","kind":"text"},{"text":"SBSDKCheckRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didRecognizeCheck"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerResult","kind":"typeIdentifier","text":"SBSDKCheckRecognizerResult"},{"kind":"text","text":")"}],"required":true,"type":"topic","navigatorTitle":[{"text":"checkRecognizerViewController:didRecognizeCheck:","kind":"identifier"}],"abstract":[{"text":"Informs the delegate, that the check scanner has successfully detected and recognized a check.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate\/checkrecognizerviewcontroller(_:didrecognizecheck:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewControllerDelegate":{"type":"topic","title":"SBSDKCheckRecognizerViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate","role":"symbol","abstract":[{"text":"The delegation protocol for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","type":"reference","isActive":true},{"text":" class.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerViewControllerDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckRecognizerViewControllerDelegate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerViewController":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController","type":"topic","title":"SBSDKUICheckRecognizerViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICheckRecognizerViewController"}],"navigatorTitle":[{"text":"SBSDKUICheckRecognizerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A Ready-To-Use viewController to recognize checks using the camera."}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewController":{"role":"symbol","title":"SBSDKCheckRecognizerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerViewController"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckRecognizerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller","type":"topic","abstract":[{"text":"Classic UI view controller that can be used to detect and recognize bank checks.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"SBSDKCheckRecognizerViewControllerDelegate","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"SBSDKCheckRecognizerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCheckRecognizerViewControllerDelegate"}]},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate\/checkRecognizerViewController(_:didChangeState:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate\/checkRecognizerViewController(_:didRecognizeCheck:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate\/checkRecognizerViewControllerShouldRecognize(_:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Conforming Types","kind":"relationships","type":"conformingTypes","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"SBSDKCheckRecognizerViewControllerDelegate","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate~1checkRecognizerViewControllerShouldRecognize(_:)\/title","value":"checkRecognizerViewControllerShouldRecognize:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate~1checkRecognizerViewControllerShouldRecognize(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"checkRecognizerViewControllerShouldRecognize:","kind":"identifier"}]},{"value":"checkRecognizerViewController:didChangeState:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate~1checkRecognizerViewController(_:didChangeState:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"checkRecognizerViewController:didChangeState:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate~1checkRecognizerViewController(_:didChangeState:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate~1checkRecognizerViewController(_:didRecognizeCheck:)\/title","op":"replace","value":"checkRecognizerViewController:didRecognizeCheck:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate~1checkRecognizerViewController(_:didRecognizeCheck:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkRecognizerViewController:didRecognizeCheck:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate\/title","value":"SBSDKCheckRecognizerViewControllerDelegate"},{"op":"replace","value":[{"text":"SBSDKCheckRecognizerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController\/title","value":"SBSDKUICheckRecognizerViewController","op":"replace"},{"value":[{"text":"SBSDKUICheckRecognizerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/title","value":"SBSDKCheckRecognizerViewController","op":"replace"},{"value":[{"text":"SBSDKCheckRecognizerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/fragments"}]}]}