{"sections":[],"abstract":[{"type":"text","text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI check scanner."}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/init(json:partial:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)"],"title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/behaviorConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/textConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/uiConfiguration"],"title":"Instance Properties"},{"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/defaultConfiguration"]}],"kind":"symbol","relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIConfiguration"]},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICheckRecognizerConfiguration"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/defaultConfiguration"},{"text":" class property to retrieve an instance and modify it as needed.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration"]}],"metadata":{"symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckRecognizerConfiguration"}],"roleHeading":"Class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICheckRecognizerConfiguration"}],"title":"SBSDKUICheckRecognizerConfiguration","modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerConfiguration/textConfiguration":{"kind":"symbol","role":"symbol","title":"textConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/textConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration\/textconfiguration","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"textConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerTextConfiguration","text":"SBSDKUICheckRecognizerTextConfiguration"}],"abstract":[{"type":"text","text":"The configuration for displayed texts."}],"navigatorTitle":[{"kind":"identifier","text":"textConfiguration"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerConfiguration/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)":{"abstract":[{"type":"text","text":"Designated initializer. Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration","isActive":true},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","kind":"symbol","role":"symbol","title":"init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:cameraconfiguration:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"uiConfiguration"},{"text":": ","kind":"text"},{"text":"SBSDKUICheckRecognizerUIConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerUIConfiguration"},{"text":", ","kind":"text"},{"text":"textConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerTextConfiguration","kind":"typeIdentifier","text":"SBSDKUICheckRecognizerTextConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"behaviorConfiguration"},{"text":": ","kind":"text"},{"text":"SBSDKUICheckRecognizerBehaviorConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerBehaviorConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"cameraConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUICameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerConfiguration/uiConfiguration":{"navigatorTitle":[{"text":"uiConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration\/uiconfiguration","abstract":[{"type":"text","text":"The user interface subconfiguration."}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"uiConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerUIConfiguration","text":"SBSDKUICheckRecognizerUIConfiguration","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/uiConfiguration","title":"uiConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerConfiguration":{"abstract":[{"type":"text","text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI check scanner."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration","kind":"symbol","role":"symbol","title":"SBSDKUICheckRecognizerConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICheckRecognizerConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckRecognizerConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerConfiguration/init":{"role":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/init","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration\/init","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerConfiguration/init(json:partial:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"json","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"partial","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithJson:partial:","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/init(json:partial:)","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration\/init(json:partial:)","title":"init(json:partial:)","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerConfiguration/defaultConfiguration":{"navigatorTitle":[{"text":"defaultConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration\/defaultconfiguration","abstract":[{"type":"text","text":"The default configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUICheckRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/defaultConfiguration","title":"defaultConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIConfiguration":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuiconfiguration","type":"topic","abstract":[{"type":"text","text":"The general configuration class for all RTU-UI components."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIConfiguration","kind":"identifier"}],"title":"SBSDKUIConfiguration","navigatorTitle":[{"text":"SBSDKUIConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerConfiguration/behaviorConfiguration":{"title":"behaviorConfiguration","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/behaviorConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration\/behaviorconfiguration","abstract":[{"type":"text","text":"The configuration controlling the scanning screens behavior."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"behaviorConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerBehaviorConfiguration","text":"SBSDKUICheckRecognizerBehaviorConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"behaviorConfiguration"}],"type":"topic"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUICheckRecognizerConfiguration"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKUICheckRecognizerConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUICheckRecognizerConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/behaviorConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/textConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/uiConfiguration"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/init","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/init(json:partial:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/defaultConfiguration"],"title":"Type Properties"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIConfiguration"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICheckRecognizerConfiguration"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIConfiguration","text":"SBSDKUIConfiguration","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration~1textConfiguration\/title","value":"textConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration~1textConfiguration\/fragments","value":[{"kind":"identifier","text":"textConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)\/title","value":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration~1uiConfiguration\/title","value":"uiConfiguration"},{"value":[{"kind":"identifier","text":"uiConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration~1uiConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration\/title","value":"SBSDKUICheckRecognizerConfiguration","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUICheckRecognizerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration~1init(json:partial:)\/title","op":"replace","value":"initWithJson:partial:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration~1init(json:partial:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithJson:partial:"}]},{"value":"defaultConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration~1defaultConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration~1defaultConfiguration\/fragments","value":[{"text":"defaultConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIConfiguration\/title","op":"replace","value":"SBSDKUIConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIConfiguration\/fragments","value":[{"text":"SBSDKUIConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration~1behaviorConfiguration\/title","value":"behaviorConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration~1behaviorConfiguration\/fragments","value":[{"text":"behaviorConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}