{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeygenerator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeygenerator"]}],"abstract":[{"type":"text","text":"Protocol for generating encryption keys."}],"metadata":{"symbolKind":"protocol","navigatorTitle":[{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}],"roleHeading":"Protocol","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKStorageCryptingKeyGenerator","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyGenerator"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyGenerator","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyGenerator\/generateKey(keyLength:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHKDFKeyGenerator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPBKDF2KeyGenerator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRandomKeyGenerator"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKStorageCryptingKeyGenerator"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRandomKeyGenerator":{"url":"\/documentation\/scanbotsdk\/sbsdkrandomkeygenerator","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRandomKeyGenerator","type":"topic","abstract":[{"type":"text","text":"A class that generates secure, random keys for storage encryption."},{"text":" ","type":"text"},{"text":"They keys are generated using the ","type":"text"},{"code":"SecRandomCopyBytes","type":"codeVoice"},{"type":"text","text":" function."}],"navigatorTitle":[{"text":"SBSDKRandomKeyGenerator","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKRandomKeyGenerator"}],"title":"SBSDKRandomKeyGenerator","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPBKDF2KeyGenerator":{"kind":"symbol","abstract":[{"type":"text","text":"A key generator that uses the PBKDF2 algorithm to derive a key from a password and a salt."},{"type":"text","text":" "},{"text":"See https:\/\/en.wikipedia.org\/wiki\/PBKDF2 for more information.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPBKDF2KeyGenerator"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpbkdf2keygenerator","title":"SBSDKPBKDF2KeyGenerator","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPBKDF2KeyGenerator"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyGenerator/generateKey(keyLength:)":{"role":"symbol","kind":"symbol","title":"generateKey(keyLength:)","url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeygenerator\/generatekey(keylength:)","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"generateKey","kind":"identifier"},{"kind":"text","text":"("},{"text":"keyLength","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyGenerator\/generateKey(keyLength:)","navigatorTitle":[{"text":"generateKeyWithLength:WithError:","kind":"identifier"}],"abstract":[{"text":"Generates a new encryption key.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyGenerator":{"kind":"symbol","type":"topic","title":"SBSDKStorageCryptingKeyGenerator","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyGenerator","url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeygenerator","abstract":[{"text":"Protocol for generating encryption keys.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHKDFKeyGenerator":{"abstract":[{"text":"A key generator that uses the HMAC based HKDF algorithm to generate a new encryption key. SHA512 is used as the hash function.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The key generation consists of two phases: extraction and expansion."},{"type":"text","text":" "},{"text":"During the extraction a pseudo random key is generated from the input key material and an optional salt.","type":"text"},{"text":" ","type":"text"},{"text":"The expansion phase uses the pseudo random key and the info data block to derive the final key.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHKDFKeyGenerator","title":"SBSDKHKDFKeyGenerator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKHKDFKeyGenerator"}],"navigatorTitle":[{"text":"SBSDKHKDFKeyGenerator","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkhkdfkeygenerator","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"op":"replace","value":"SBSDKStorageCryptingKeyGenerator","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"value":[{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyGenerator"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyGenerator\/generateKey(keyLength:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHKDFKeyGenerator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPBKDF2KeyGenerator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRandomKeyGenerator"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKStorageCryptingKeyGenerator"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRandomKeyGenerator\/title","value":"SBSDKRandomKeyGenerator"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRandomKeyGenerator\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKRandomKeyGenerator"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRandomKeyGenerator\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKRandomKeyGenerator"}],"op":"replace"},{"value":"SBSDKPBKDF2KeyGenerator","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPBKDF2KeyGenerator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPBKDF2KeyGenerator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPBKDF2KeyGenerator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPBKDF2KeyGenerator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPBKDF2KeyGenerator\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyGenerator~1generateKey(keyLength:)\/title","value":"generateKeyWithLength:WithError:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyGenerator~1generateKey(keyLength:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"generateKeyWithLength:WithError:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyGenerator\/title","op":"replace","value":"SBSDKStorageCryptingKeyGenerator"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyGenerator\/fragments","value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyGenerator"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyGenerator\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyGenerator"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHKDFKeyGenerator\/title","value":"SBSDKHKDFKeyGenerator"},{"value":[{"text":"SBSDKHKDFKeyGenerator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHKDFKeyGenerator\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHKDFKeyGenerator\/navigatorTitle","value":[{"text":"SBSDKHKDFKeyGenerator","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}