{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarCodeScannerDocumentFormat"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerdocumentformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerdocumentformat"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVADocumentFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBoardingPassDocumentFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1DocumentFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIDCardPDF417DocumentFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDocumentFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanDocumentFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSEPADocumentFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSwissQRCodeDocumentFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVCardDocumentFormat"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarCodeScannerDocumentFormat","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Base class for describing recognized and parsed barcode information."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarCodeScannerDocumentFormat"}],"title":"SBSDKBarCodeScannerDocumentFormat","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKBarCodeScannerDocumentFormat","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarCodeScannerDocumentFormat"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarCodeScannerDocumentFormat\/init(string:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarCodeScannerDocumentFormat\/parsedSuccessful","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarCodeScannerDocumentFormat\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarCodeScannerDocumentFormat\/toJSON()"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanDocumentFormat":{"role":"symbol","title":"SBSDKMedicalPlanDocumentFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanDocumentFormat"}],"abstract":[{"type":"text","text":"The german medical plan document description structure."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanDocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanDocumentFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalplandocumentformat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.2"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBoardingPassDocumentFormat":{"role":"symbol","title":"SBSDKBoardingPassDocumentFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBoardingPassDocumentFormat"}],"abstract":[{"type":"text","text":"The boarding pass document description."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBoardingPassDocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkboardingpassdocumentformat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSEPADocumentFormat":{"role":"symbol","title":"SBSDKSEPADocumentFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSEPADocumentFormat"}],"abstract":[{"type":"text","text":"The SEPA parsed document information."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSEPADocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSEPADocumentFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdksepadocumentformat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1DocumentFormat":{"role":"symbol","title":"SBSDKGS1DocumentFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGS1DocumentFormat"}],"abstract":[{"type":"text","text":"The document format of a GS1 code."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1DocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1DocumentFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkgs1documentformat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIDCardPDF417DocumentFormat":{"role":"symbol","title":"SBSDKIDCardPDF417DocumentFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFormat"}],"abstract":[{"type":"text","text":"The ID card document description."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIDCardPDF417DocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKIDCardPDF417DocumentFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkidcardpdf417documentformat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSwissQRCodeDocumentFormat":{"role":"symbol","title":"SBSDKSwissQRCodeDocumentFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSwissQRCodeDocumentFormat"}],"abstract":[{"type":"text","text":"The document format of a Swiss QR code."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSwissQRCodeDocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSwissQRCodeDocumentFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkswissqrcodedocumentformat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarCodeScannerDocumentFormat/init(string:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithString:"}],"role":"symbol","title":"init(string:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"string"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The initializer."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarCodeScannerDocumentFormat\/init(string:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerdocumentformat\/init(string:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVCardDocumentFormat":{"role":"symbol","title":"SBSDKVCardDocumentFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVCardDocumentFormat"}],"abstract":[{"type":"text","text":"The vCard document description."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVCardDocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKVCardDocumentFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkvcarddocumentformat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarCodeScannerDocumentFormat/type":{"navigatorTitle":[{"kind":"identifier","text":"type"}],"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeDocumentType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentType"}],"abstract":[{"type":"text","text":"The type of the barcode document."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarCodeScannerDocumentFormat\/type","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerdocumentformat\/type"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarCodeScannerDocumentFormat":{"role":"symbol","title":"SBSDKBarCodeScannerDocumentFormat","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarCodeScannerDocumentFormat"}],"abstract":[{"type":"text","text":"Base class for describing recognized and parsed barcode information."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarCodeScannerDocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarCodeScannerDocumentFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerdocumentformat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAAMVADocumentFormat":{"role":"symbol","title":"SBSDKAAMVADocumentFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAAMVADocumentFormat"}],"abstract":[{"type":"text","text":"The AAMVA document information."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVADocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKAAMVADocumentFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkaamvadocumentformat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarCodeScannerDocumentFormat/toJSON()":{"role":"symbol","title":"toJSON()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJSON"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarCodeScannerDocumentFormat\/toJSON()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"toJSON"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerdocumentformat\/tojson()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarCodeScannerDocumentFormat/parsedSuccessful":{"navigatorTitle":[{"kind":"identifier","text":"parsedSuccessful"}],"role":"symbol","title":"parsedSuccessful","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parsedSuccessful"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Indicates, whether parsing was successful."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarCodeScannerDocumentFormat\/parsedSuccessful","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerdocumentformat\/parsedsuccessful"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDocumentFormat":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFormat"}],"abstract":[{"type":"text","text":"Class for parsing data obtained from QR code on medical certificates."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedocumentformat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarCodeScannerDocumentFormat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBarCodeScannerDocumentFormat"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarCodeScannerDocumentFormat"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarCodeScannerDocumentFormat\/parsedSuccessful","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarCodeScannerDocumentFormat\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarCodeScannerDocumentFormat\/init(string:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarCodeScannerDocumentFormat\/toJSON()"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarCodeScannerDocumentFormat"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarCodeScannerDocumentFormat~1init(string:)\/title","value":"initWithString:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarCodeScannerDocumentFormat~1init(string:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithString:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarCodeScannerDocumentFormat~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarCodeScannerDocumentFormat~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarCodeScannerDocumentFormat\/title","value":"SBSDKBarCodeScannerDocumentFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarCodeScannerDocumentFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKBarCodeScannerDocumentFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarCodeScannerDocumentFormat~1toJSON()\/title","value":"toJSON"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarCodeScannerDocumentFormat~1toJSON()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJSON"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarCodeScannerDocumentFormat~1parsedSuccessful\/title","value":"parsedSuccessful"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarCodeScannerDocumentFormat~1parsedSuccessful\/fragments","value":[{"kind":"identifier","text":"parsedSuccessful"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}