{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2DocumentFlowAppearanceConfiguration) ","kind":"text"},{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentFlowAppearanceConfiguration","kind":"identifier"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/init(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/init(statusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:)"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/bottomBarBackgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/orientationLockMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/statusBarMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/topBarBackgroundColor"],"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/toJson()"],"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"SBSDKUI2DocumentFlowAppearanceConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentFlowAppearanceConfiguration"}],"roleHeading":"Class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentFlowAppearanceConfiguration","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentFlowAppearanceConfiguration"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"abstract":[{"type":"text","text":"Configuration of the general appearance."}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentFlowAppearanceConfiguration/bottomBarBackgroundColor":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bottomBarBackgroundColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/bottomBarBackgroundColor","kind":"symbol","title":"bottomBarBackgroundColor","url":"\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration\/bottombarbackgroundcolor","role":"symbol","abstract":[{"text":"The background color of the bottom bar.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is “?sbColorPrimary”"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"bottomBarBackgroundColor"}]},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentFlowAppearanceConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentFlowAppearanceConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration","kind":"symbol","title":"SBSDKUI2DocumentFlowAppearanceConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration of the general appearance."}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2DocumentFlowAppearanceConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentFlowAppearanceConfiguration/topBarBackgroundColor":{"abstract":[{"type":"text","text":"The background color of the top bar. Only applicable when the visual mode is specified as ‘SOLID’, otherwise"},{"text":" ","type":"text"},{"type":"text","text":"ignored."},{"text":" ","type":"text"},{"type":"text","text":"Default is “?sbColorPrimary”"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration\/topbarbackgroundcolor","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/topBarBackgroundColor","navigatorTitle":[{"kind":"identifier","text":"topBarBackgroundColor"}],"type":"topic","title":"topBarBackgroundColor","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"topBarBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentFlowAppearanceConfiguration/isEqual:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"abstract":[],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/isEqual:","kind":"symbol","title":"isEqual:","url":"\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration\/isequal:","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentFlowAppearanceConfiguration/init()":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init()","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/init()","type":"topic","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentFlowAppearanceConfiguration/hash":{"title":"hash","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"hash"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration\/hash","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentFlowAppearanceConfiguration/toJson()":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/toJson()","navigatorTitle":[{"text":"toJson","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration\/tojson()","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"title":"toJson()","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Node"}],"abstract":[{"type":"text","text":"Abstract class for all the configurations."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","url":"\/documentation\/scanbotsdk\/sbsdkui2node","type":"topic","title":"SBSDKUI2Node","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Node"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentFlowAppearanceConfiguration/init(statusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:)":{"title":"init(statusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:)","url":"\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration\/init(statusbarmode:topbarbackgroundcolor:bottombarbackgroundcolor:orientationlockmode:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"statusBarMode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2StatusBarMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2StatusBarMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topBarBackgroundColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bottomBarBackgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"orientationLockMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2OrientationLockMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2OrientationLockMode","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/init(statusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:)","navigatorTitle":[{"text":"initWithStatusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentFlowAppearanceConfiguration/orientationLockMode":{"title":"orientationLockMode","abstract":[{"type":"text","text":"Which mode to use when orientation should be locked to landscape or portrait."},{"type":"text","text":" "},{"type":"text","text":"Default is NONE"}],"navigatorTitle":[{"kind":"identifier","text":"orientationLockMode"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationLockMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2OrientationLockMode","kind":"typeIdentifier","text":"SBSDKUI2OrientationLockMode"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration\/orientationlockmode","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/orientationLockMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentFlowAppearanceConfiguration/statusBarMode":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"statusBarMode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2StatusBarMode","text":"SBSDKUI2StatusBarMode"}],"abstract":[{"text":"Determines the visual mode used for the status bar icons.","type":"text"},{"text":" ","type":"text"},{"text":"Default is LIGHT","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration\/statusbarmode","type":"topic","title":"statusBarMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/statusBarMode","role":"symbol","navigatorTitle":[{"text":"statusBarMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentFlowAppearanceConfiguration/init(from:)":{"title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier","text":"Decoder"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration\/init(from:)","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/init(from:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUI2DocumentFlowAppearanceConfiguration"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentFlowAppearanceConfiguration"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentFlowAppearanceConfiguration"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/bottomBarBackgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/orientationLockMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/statusBarMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/topBarBackgroundColor"],"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/init(statusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/toJson()"],"title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"]}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentFlowAppearanceConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","text":"SBSDKUI2Node","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"bottomBarBackgroundColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration~1bottomBarBackgroundColor\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration~1bottomBarBackgroundColor\/fragments","value":[{"kind":"identifier","text":"bottomBarBackgroundColor"}]},{"value":"SBSDKUI2DocumentFlowAppearanceConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentFlowAppearanceConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration\/fragments"},{"op":"replace","value":"topBarBackgroundColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration~1topBarBackgroundColor\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration~1topBarBackgroundColor\/fragments","value":[{"text":"topBarBackgroundColor","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration~1init()\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"toJson","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration~1toJson()\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration~1toJson()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJson"}]},{"value":"SBSDKUI2Node","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments","value":[{"text":"SBSDKUI2Node","kind":"identifier"}]},{"value":"initWithStatusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration~1init(statusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration~1init(statusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStatusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration~1orientationLockMode\/title","value":"orientationLockMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration~1orientationLockMode\/fragments","value":[{"text":"orientationLockMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration~1statusBarMode\/title","value":"statusBarMode"},{"value":[{"text":"statusBarMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration~1statusBarMode\/fragments"}]}]}