{"abstract":[{"type":"text","text":"Configuration of the output settings."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings"},"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/init(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/init(pagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/defaultFilter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/documentAnalysisMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/documentImageSizeLimit","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/pagesScanLimit"]},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/toJson()"],"generated":true}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKUI2DocumentScannerOutputSettings) "},{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"identifier"}]}]}],"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings"]}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerOutputSettings"}],"title":"SBSDKUI2DocumentScannerOutputSettings","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerOutputSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","roleHeading":"Class"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerOutputSettings/isEqual:":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings\/isequal:","abstract":[],"role":"symbol","type":"topic","title":"isEqual:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/isEqual:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Node","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Node"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","abstract":[{"type":"text","text":"Abstract class for all the configurations."}],"title":"SBSDKUI2Node","url":"\/documentation\/scanbotsdk\/sbsdkui2node"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerOutputSettings":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings","role":"symbol","abstract":[{"type":"text","text":"Configuration of the output settings."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2DocumentScannerOutputSettings"}],"navigatorTitle":[{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"identifier"}],"title":"SBSDKUI2DocumentScannerOutputSettings","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerOutputSettings/documentImageSizeLimit":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/documentImageSizeLimit","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings\/documentimagesizelimit","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"documentImageSizeLimit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"documentImageSizeLimit"}],"role":"symbol","title":"documentImageSizeLimit","abstract":[{"type":"text","text":"The limit of the size of the cropped document images. If one of the dimensions of the cropped image is larger"},{"text":" ","type":"text"},{"type":"text","text":"than the limit, the image is downscaled so that its longer dimension matches the limit. The default is 0 (no"},{"text":" ","type":"text"},{"text":"limit).","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is 0"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerOutputSettings/init(from:)":{"role":"symbol","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings\/init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/init(from:)","title":"init(from:)"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerOutputSettings/init()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/init()","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"role":"symbol","type":"topic","title":"init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings\/init()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerOutputSettings/hash":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings\/hash","kind":"symbol","title":"hash","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/hash","abstract":[],"fragments":[{"text":"hash","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerOutputSettings/toJson()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/toJson()","title":"toJson()","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings\/tojson()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"toJson","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"toJson","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerOutputSettings/fromJsonWithJson:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/fromJsonWithJson:","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings\/fromjsonwithjson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerOutputSettings/pagesScanLimit":{"navigatorTitle":[{"text":"pagesScanLimit","kind":"identifier"}],"title":"pagesScanLimit","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/pagesScanLimit","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The limit of the number of pages that can be scanned. Default is 0 (no limit)."},{"type":"text","text":" "},{"text":"Default is 0","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings\/pagesscanlimit","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pagesScanLimit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerOutputSettings/documentAnalysisMode":{"abstract":[{"text":"Determines if the quality analysis for the acknowledgement mode will run on the filtered or the unfiltered","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"image."},{"type":"text","text":" "},{"type":"text","text":"Default is UNFILTERED_DOCUMENT"}],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAnalysisMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2DocumentAnalysisMode","kind":"typeIdentifier","text":"SBSDKUI2DocumentAnalysisMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/documentAnalysisMode","navigatorTitle":[{"kind":"identifier","text":"documentAnalysisMode"}],"title":"documentAnalysisMode","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings\/documentanalysismode"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerOutputSettings/defaultFilter":{"abstract":[{"type":"text","text":"Determines the image filter to apply by default."}],"title":"defaultFilter","navigatorTitle":[{"kind":"identifier","text":"defaultFilter"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings\/defaultfilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"defaultFilter","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/defaultFilter","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerOutputSettings/init(pagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:)":{"abstract":[],"navigatorTitle":[{"text":"initWithPagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pagesScanLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"documentImageSizeLimit","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"documentAnalysisMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2DocumentAnalysisMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2DocumentAnalysisMode"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"defaultFilter"},{"text":": ","kind":"text"},{"text":"SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"init(pagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/init(pagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings\/init(pagesscanlimit:documentimagesizelimit:documentanalysismode:defaultfilter:)"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"SBSDKUI2DocumentScannerOutputSettings","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/defaultFilter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/documentAnalysisMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/documentImageSizeLimit","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/pagesScanLimit"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/init(pagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/toJson()"]},{"generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/fromJsonWithJson:"],"title":"Type Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2DocumentScannerOutputSettings"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node","text":"SBSDKUI2Node"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title","value":"SBSDKUI2Node","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Node"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Node"}],"op":"replace"},{"value":"SBSDKUI2DocumentScannerOutputSettings","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings\/fragments","value":[{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerOutputSettings"}]},{"op":"replace","value":"documentImageSizeLimit","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings~1documentImageSizeLimit\/title"},{"op":"replace","value":[{"text":"documentImageSizeLimit","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings~1documentImageSizeLimit\/fragments"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings~1init()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings~1init()\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings~1toJson()\/title","value":"toJson","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings~1toJson()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJson"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings~1pagesScanLimit\/title","value":"pagesScanLimit"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings~1pagesScanLimit\/fragments","value":[{"text":"pagesScanLimit","kind":"identifier"}]},{"op":"replace","value":"documentAnalysisMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings~1documentAnalysisMode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings~1documentAnalysisMode\/fragments","op":"replace","value":[{"text":"documentAnalysisMode","kind":"identifier"}]},{"value":"defaultFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings~1defaultFilter\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings~1defaultFilter\/fragments","value":[{"text":"defaultFilter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings~1init(pagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:)\/title","value":"initWithPagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings~1init(pagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:"}],"op":"replace"}]}]}