{"abstract":[{"type":"text","text":"A class to store and remove barcode images from "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","isActive":true},{"type":"text","text":"."}],"kind":"symbol","metadata":{"title":"SBSDKUIBarcodeImageStorage","modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodeImageStorage","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeImageStorage"}],"roleHeading":"Class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeImageStorage","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodeimagestorage"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodeimagestorage"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeImageStorage","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/init(imageFileFormat:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/init(imageFileFormat:location:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/init(jpegFileFormatAndCompressionQuality:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/init(jpegFileFormatAndCompressionQuality:location:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/allImageURLs","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/writingImageFileFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/writingJpegImageCompressionQuality"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/removeAll()"]},{"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/default"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/setDefault(_:)"],"title":"Type Methods"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeImageStorage/setDefault(_:)":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setDefault","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeImageStorage","text":"SBSDKUIBarcodeImageStorage","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"setDefaultStorage:","kind":"identifier"}],"type":"topic","title":"setDefault(_:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/setDefault(_:)","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeimagestorage\/setdefault(_:)","abstract":[{"type":"text","text":"Set default storage. If not used, default storage will be created with default parameters."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeImageStorage":{"title":"SBSDKUIBarcodeImageStorage","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeimagestorage","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodeImageStorage"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeImageStorage"}],"abstract":[{"type":"text","text":"A class to store and remove barcode images from "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController"},{"type":"text","text":"."}],"type":"topic"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","role":"symbol","deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller","abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to detect QR and barcodes."}],"title":"SBSDKUIBarcodeScannerViewController","type":"topic"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeImageStorage/allImageURLs":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allImageURLs"},{"text":": [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"allImageURLs","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/allImageURLs","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeimagestorage\/allimageurls","title":"allImageURLs","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeImageStorage/default":{"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/default","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`default`","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUIBarcodeImageStorage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeImageStorage"}],"abstract":[{"type":"text","text":"The default instance of this class."}],"title":"default","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeimagestorage\/default","navigatorTitle":[{"text":"defaultStorage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeImageStorage/removeAll()":{"title":"removeAll()","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeimagestorage\/removeall()","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/removeAll()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAll"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"removeAll"}],"abstract":[{"type":"text","text":"It clears the receiver. Removes all stored images files from disk."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeImageStorage/init(jpegFileFormatAndCompressionQuality:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/init(jpegFileFormatAndCompressionQuality:)","kind":"symbol","title":"init(jpegFileFormatAndCompressionQuality:)","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeimagestorage\/init(jpegfileformatandcompressionquality:)","navigatorTitle":[{"text":"initWithJpegFileFormatAndCompressionQuality:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Initializes storage with JPEG image file format and given JPEG compression quality using the default storage location.","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"jpegFileFormatAndCompressionQuality"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeImageStorage/init(imageFileFormat:location:)":{"kind":"symbol","title":"init(imageFileFormat:location:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"imageFileFormat","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat","kind":"typeIdentifier","text":"SBSDKImageFileFormat"},{"text":", ","kind":"text"},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation","text":"SBSDKStorageLocation"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"initWithImageFileFormat:location:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeimagestorage\/init(imagefileformat:location:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/init(imageFileFormat:location:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Initializes storage with given image file format and default JPEG compression quality."}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFileFormat/JPEG":{"role":"symbol","abstract":[{"text":"The image file is a JPEG.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"JPEG","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKImageFileFormatJPEG","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat\/JPEG","kind":"symbol","type":"topic","title":"SBSDKImageFileFormat.JPEG","url":"\/documentation\/scanbotsdk\/sbsdkimagefileformat\/jpeg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeImageStorage/init(jpegFileFormatAndCompressionQuality:location:)":{"title":"init(jpegFileFormatAndCompressionQuality:location:)","abstract":[{"text":"Initializes storage with JPEG image file format and given JPEG compression quality.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeimagestorage\/init(jpegfileformatandcompressionquality:location:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"jpegFileFormatAndCompressionQuality"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"location","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithJpegFileFormatAndCompressionQuality:location:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/init(jpegFileFormatAndCompressionQuality:location:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeImageStorage/writingJpegImageCompressionQuality":{"navigatorTitle":[{"text":"writingJpegImageCompressionQuality","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/writingJpegImageCompressionQuality","kind":"symbol","abstract":[{"text":"If file format is set to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat\/JPEG"},{"text":", this property holds the compression quality of the stored images. Read-only.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"writingJpegImageCompressionQuality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"role":"symbol","title":"writingJpegImageCompressionQuality","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeimagestorage\/writingjpegimagecompressionquality","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeImageStorage/init(imageFileFormat:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"imageFileFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeimagestorage\/init(imagefileformat:)","abstract":[{"text":"Initializes storage with given image file format and default JPEG compression quality using the default storage location.","type":"text"}],"navigatorTitle":[{"text":"initWithImageFileFormat:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/init(imageFileFormat:)","type":"topic","title":"init(imageFileFormat:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeImageStorage/writingImageFileFormat":{"role":"symbol","abstract":[{"type":"text","text":"File format of the stored images."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"writingImageFileFormat","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat","text":"SBSDKImageFileFormat","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"writingImageFileFormat","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/writingImageFileFormat","kind":"symbol","type":"topic","title":"writingImageFileFormat","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeimagestorage\/writingimagefileformat"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"SBSDKUIBarcodeImageStorage","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKUIBarcodeImageStorage","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIBarcodeImageStorage"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/allImageURLs","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/writingImageFileFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/writingJpegImageCompressionQuality"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/init(imageFileFormat:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/init(imageFileFormat:location:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/init(jpegFileFormatAndCompressionQuality:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/init(jpegFileFormatAndCompressionQuality:location:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/removeAll()"]},{"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/default"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeImageStorage\/setDefault(_:)"],"title":"Type Methods"}],"op":"replace"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeImageStorage"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1setDefault(_:)\/title","value":"setDefaultStorage:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1setDefault(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setDefaultStorage:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage\/title","value":"SBSDKUIBarcodeImageStorage"},{"value":[{"text":"SBSDKUIBarcodeImageStorage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage\/fragments"},{"value":"SBSDKUIBarcodeScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/title","op":"replace"},{"value":[{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/fragments"},{"op":"replace","value":"allImageURLs","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1allImageURLs\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1allImageURLs\/fragments","op":"replace","value":[{"kind":"identifier","text":"allImageURLs"}]},{"value":"defaultStorage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1default\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1default\/fragments","op":"replace","value":[{"kind":"identifier","text":"defaultStorage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1removeAll()\/title","value":"removeAll"},{"value":[{"text":"- ","kind":"text"},{"text":"removeAll","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1removeAll()\/fragments"},{"value":"initWithJpegFileFormatAndCompressionQuality:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1init(jpegFileFormatAndCompressionQuality:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1init(jpegFileFormatAndCompressionQuality:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithJpegFileFormatAndCompressionQuality:"}]},{"value":"initWithImageFileFormat:location:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1init(imageFileFormat:location:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1init(imageFileFormat:location:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithImageFileFormat:location:"}]},{"value":"SBSDKImageFileFormatJPEG","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat~1JPEG\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat~1JPEG\/fragments","op":"replace","value":[{"text":"SBSDKImageFileFormatJPEG","kind":"identifier"}]},{"value":"initWithJpegFileFormatAndCompressionQuality:location:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1init(jpegFileFormatAndCompressionQuality:location:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithJpegFileFormatAndCompressionQuality:location:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1init(jpegFileFormatAndCompressionQuality:location:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1writingJpegImageCompressionQuality\/title","value":"writingJpegImageCompressionQuality"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1writingJpegImageCompressionQuality\/fragments","value":[{"text":"writingJpegImageCompressionQuality","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1init(imageFileFormat:)\/title","value":"initWithImageFileFormat:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1init(imageFileFormat:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageFileFormat:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1writingImageFileFormat\/title","value":"writingImageFileFormat","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeImageStorage~1writingImageFileFormat\/fragments","op":"replace","value":[{"kind":"identifier","text":"writingImageFileFormat"}]}]}]}