{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckDocumentConstants","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"text":"SBSDKCheckDocumentConstants","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","roleHeading":"Class","title":"SBSDKCheckDocumentConstants","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCheckDocumentConstants","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentConstants"},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/ausCheckAccountNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/ausCheckAuxDomesticFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/ausCheckBSBFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/ausCheckDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/ausCheckExtraAuxDomesticFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/ausCheckTransactionCodeFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckAccountNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckBankNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckChequeNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckDesignationNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckTransactionCodeFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckTransitNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/checkDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/checkFontTypeFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/checkRawStringFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/fraCheckAccountNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/fraCheckChequeNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/fraCheckDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/fraCheckRoutingNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/indCheckAccountNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/indCheckDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/indCheckSerialNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/indCheckSortNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/indCheckTransactionCodeFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/isrCheckAccountNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/isrCheckBankNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/isrCheckBranchNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/isrCheckChequeNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/isrCheckDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/kwtCheckAccountNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/kwtCheckChequeNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/kwtCheckDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/kwtCheckSortCodeFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/uaeCheckAccountNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/uaeCheckChequeNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/uaeCheckDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/uaeCheckRoutingNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/unknownCheckDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/usaCheckAccountNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/usaCheckAuxiliaryOnUsFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/usaCheckDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/usaCheckTransitNumberFieldNormalizedName"],"title":"Type Properties"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/fraCheckDocumentType":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/fracheckdocumenttype","abstract":[{"text":"Document type name of the “FRACheck” document type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"fraCheckDocumentType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/fraCheckDocumentType","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fraCheckDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"fraCheckDocumentType","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/indCheckDocumentType":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/indcheckdocumenttype","abstract":[{"text":"Document type name of the “INDCheck” document type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"indCheckDocumentType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/indCheckDocumentType","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indCheckDocumentType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"indCheckDocumentType","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/ausCheckBSBFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/auscheckbsbfieldnormalizedname","abstract":[{"type":"text","text":"Normalized full name of the “BSB” field type in document type “AUSCheck”."}],"navigatorTitle":[{"text":"ausCheckBSBFieldNormalizedName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/ausCheckBSBFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ausCheckBSBFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"ausCheckBSBFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/isrCheckChequeNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/isrcheckchequenumberfieldnormalizedname","navigatorTitle":[{"kind":"identifier","text":"isrCheckChequeNumberFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/isrCheckChequeNumberFieldNormalizedName","kind":"symbol","abstract":[{"type":"text","text":"Normalized full name of the “ChequeNumber” field type in document type “ISRCheck”."}],"role":"symbol","title":"isrCheckChequeNumberFieldNormalizedName","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isrCheckChequeNumberFieldNormalizedName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/indCheckSerialNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/indcheckserialnumberfieldnormalizedname","abstract":[{"text":"Normalized full name of the “SerialNumber” field type in document type “INDCheck”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"indCheckSerialNumberFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/indCheckSerialNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indCheckSerialNumberFieldNormalizedName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"indCheckSerialNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/isrCheckBankNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/isrcheckbanknumberfieldnormalizedname","abstract":[{"text":"Normalized full name of the “BankNumber” field type in document type “ISRCheck”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"isrCheckBankNumberFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/isrCheckBankNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isrCheckBankNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"isrCheckBankNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/fraCheckRoutingNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/fracheckroutingnumberfieldnormalizedname","abstract":[{"type":"text","text":"Normalized full name of the “RoutingNumber” field type in document type “FRACheck”."}],"navigatorTitle":[{"text":"fraCheckRoutingNumberFieldNormalizedName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/fraCheckRoutingNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fraCheckRoutingNumberFieldNormalizedName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"fraCheckRoutingNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/usaCheckTransitNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/usachecktransitnumberfieldnormalizedname","abstract":[{"text":"Normalized full name of the “TransitNumber” field type in document type “USACheck”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"usaCheckTransitNumberFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/usaCheckTransitNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"usaCheckTransitNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"usaCheckTransitNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/canCheckDesignationNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/cancheckdesignationnumberfieldnormalizedname","abstract":[{"text":"Normalized full name of the “DesignationNumber” field type in document type “CANCheck”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"canCheckDesignationNumberFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckDesignationNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canCheckDesignationNumberFieldNormalizedName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"canCheckDesignationNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/canCheckChequeNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/cancheckchequenumberfieldnormalizedname","abstract":[{"type":"text","text":"Normalized full name of the “ChequeNumber” field type in document type “CANCheck”."}],"navigatorTitle":[{"text":"canCheckChequeNumberFieldNormalizedName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckChequeNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canCheckChequeNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"canCheckChequeNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/canCheckAccountNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/cancheckaccountnumberfieldnormalizedname","abstract":[{"text":"Normalized full name of the “AccountNumber” field type in document type “CANCheck”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"canCheckAccountNumberFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckAccountNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canCheckAccountNumberFieldNormalizedName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"canCheckAccountNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/indCheckTransactionCodeFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/indchecktransactioncodefieldnormalizedname","abstract":[{"text":"Normalized full name of the “TransactionCode” field type in document type “INDCheck”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"indCheckTransactionCodeFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/indCheckTransactionCodeFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indCheckTransactionCodeFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"indCheckTransactionCodeFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/checkRawStringFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/checkrawstringfieldnormalizedname","abstract":[{"type":"text","text":"Normalized full name of the “RawString” field type in document type “Check”."}],"navigatorTitle":[{"text":"checkRawStringFieldNormalizedName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/checkRawStringFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkRawStringFieldNormalizedName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"checkRawStringFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/isrCheckBranchNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/isrcheckbranchnumberfieldnormalizedname","abstract":[{"text":"Normalized full name of the “BranchNumber” field type in document type “ISRCheck”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"isrCheckBranchNumberFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/isrCheckBranchNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isrCheckBranchNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"isrCheckBranchNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/usaCheckAuxiliaryOnUsFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/usacheckauxiliaryonusfieldnormalizedname","abstract":[{"text":"Normalized full name of the “AuxiliaryOnUs” field type in document type “USACheck”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"usaCheckAuxiliaryOnUsFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/usaCheckAuxiliaryOnUsFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"usaCheckAuxiliaryOnUsFieldNormalizedName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"usaCheckAuxiliaryOnUsFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/usaCheckAccountNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/usacheckaccountnumberfieldnormalizedname","abstract":[{"type":"text","text":"Normalized full name of the “AccountNumber” field type in document type “USACheck”."}],"navigatorTitle":[{"text":"usaCheckAccountNumberFieldNormalizedName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/usaCheckAccountNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"usaCheckAccountNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"usaCheckAccountNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/fraCheckChequeNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/fracheckchequenumberfieldnormalizedname","abstract":[{"text":"Normalized full name of the “ChequeNumber” field type in document type “FRACheck”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"fraCheckChequeNumberFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/fraCheckChequeNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fraCheckChequeNumberFieldNormalizedName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"fraCheckChequeNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/kwtCheckSortCodeFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/kwtchecksortcodefieldnormalizedname","abstract":[{"text":"Normalized full name of the “SortCode” field type in document type “KWTCheck”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"kwtCheckSortCodeFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/kwtCheckSortCodeFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kwtCheckSortCodeFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"kwtCheckSortCodeFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/uaeCheckDocumentType":{"navigatorTitle":[{"kind":"identifier","text":"uaeCheckDocumentType"}],"abstract":[{"text":"Document type name of the “UAECheck” document type.","type":"text"}],"title":"uaeCheckDocumentType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/uaeCheckDocumentType","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/uaecheckdocumenttype","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"uaeCheckDocumentType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/kwtCheckChequeNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/kwtcheckchequenumberfieldnormalizedname","abstract":[{"type":"text","text":"Normalized full name of the “ChequeNumber” field type in document type “KWTCheck”."}],"navigatorTitle":[{"text":"kwtCheckChequeNumberFieldNormalizedName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/kwtCheckChequeNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kwtCheckChequeNumberFieldNormalizedName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"kwtCheckChequeNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/isrCheckAccountNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/isrcheckaccountnumberfieldnormalizedname","abstract":[{"type":"text","text":"Normalized full name of the “AccountNumber” field type in document type “ISRCheck”."}],"navigatorTitle":[{"text":"isrCheckAccountNumberFieldNormalizedName","kind":"identifier"}],"title":"isrCheckAccountNumberFieldNormalizedName","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isrCheckAccountNumberFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/isrCheckAccountNumberFieldNormalizedName","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/uaeCheckRoutingNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/uaecheckroutingnumberfieldnormalizedname","abstract":[{"text":"Normalized full name of the “RoutingNumber” field type in document type “UAECheck”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"uaeCheckRoutingNumberFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/uaeCheckRoutingNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uaeCheckRoutingNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"uaeCheckRoutingNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/canCheckDocumentType":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/cancheckdocumenttype","abstract":[{"text":"Document type name of the “CANCheck” document type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"canCheckDocumentType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckDocumentType","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canCheckDocumentType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"canCheckDocumentType","kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/canCheckTransactionCodeFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/canchecktransactioncodefieldnormalizedname","abstract":[{"type":"text","text":"Normalized full name of the “TransactionCode” field type in document type “CANCheck”."}],"navigatorTitle":[{"text":"canCheckTransactionCodeFieldNormalizedName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckTransactionCodeFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canCheckTransactionCodeFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"canCheckTransactionCodeFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/kwtCheckDocumentType":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/kwtcheckdocumenttype","abstract":[{"text":"Document type name of the “KWTCheck” document type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"kwtCheckDocumentType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/kwtCheckDocumentType","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kwtCheckDocumentType"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"kwtCheckDocumentType","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/canCheckBankNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/cancheckbanknumberfieldnormalizedname","abstract":[{"text":"Normalized full name of the “BankNumber” field type in document type “CANCheck”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"canCheckBankNumberFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckBankNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canCheckBankNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"canCheckBankNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/ausCheckAuxDomesticFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/auscheckauxdomesticfieldnormalizedname","abstract":[{"type":"text","text":"Normalized full name of the “AuxDomestic” field type in document type “AUSCheck”."}],"navigatorTitle":[{"text":"ausCheckAuxDomesticFieldNormalizedName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/ausCheckAuxDomesticFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ausCheckAuxDomesticFieldNormalizedName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"ausCheckAuxDomesticFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants","abstract":[],"navigatorTitle":[{"text":"SBSDKCheckDocumentConstants","kind":"identifier"}],"title":"SBSDKCheckDocumentConstants","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCheckDocumentConstants"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/indCheckAccountNumberFieldNormalizedName":{"type":"topic","title":"indCheckAccountNumberFieldNormalizedName","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"indCheckAccountNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"indCheckAccountNumberFieldNormalizedName","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/indcheckaccountnumberfieldnormalizedname","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/indCheckAccountNumberFieldNormalizedName","abstract":[{"type":"text","text":"Normalized full name of the “AccountNumber” field type in document type “INDCheck”."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/checkDocumentType":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/checkdocumenttype","abstract":[{"text":"Document type name of the “Check” document type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"checkDocumentType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/checkDocumentType","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"checkDocumentType","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/ausCheckAccountNumberFieldNormalizedName":{"abstract":[{"text":"Normalized full name of the “AccountNumber” field type in document type “AUSCheck”.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ausCheckAccountNumberFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/ausCheckAccountNumberFieldNormalizedName","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/auscheckaccountnumberfieldnormalizedname","kind":"symbol","title":"ausCheckAccountNumberFieldNormalizedName","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ausCheckAccountNumberFieldNormalizedName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/ausCheckDocumentType":{"role":"symbol","abstract":[{"type":"text","text":"Document type name of the “AUSCheck” document type."}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/auscheckdocumenttype","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"ausCheckDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"ausCheckDocumentType","navigatorTitle":[{"kind":"identifier","text":"ausCheckDocumentType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/ausCheckDocumentType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/usaCheckDocumentType":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/usacheckdocumenttype","abstract":[{"text":"Document type name of the “USACheck” document type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"usaCheckDocumentType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/usaCheckDocumentType","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"usaCheckDocumentType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"usaCheckDocumentType","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/ausCheckExtraAuxDomesticFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/auscheckextraauxdomesticfieldnormalizedname","abstract":[{"type":"text","text":"Normalized full name of the “ExtraAuxDomestic” field type in document type “AUSCheck”."}],"navigatorTitle":[{"text":"ausCheckExtraAuxDomesticFieldNormalizedName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/ausCheckExtraAuxDomesticFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ausCheckExtraAuxDomesticFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"ausCheckExtraAuxDomesticFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/ausCheckTransactionCodeFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/auschecktransactioncodefieldnormalizedname","abstract":[{"text":"Normalized full name of the “TransactionCode” field type in document type “AUSCheck”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ausCheckTransactionCodeFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/ausCheckTransactionCodeFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ausCheckTransactionCodeFieldNormalizedName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"ausCheckTransactionCodeFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/indCheckSortNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/indchecksortnumberfieldnormalizedname","abstract":[{"text":"Normalized full name of the “SortNumber” field type in document type “INDCheck”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"indCheckSortNumberFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/indCheckSortNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indCheckSortNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"indCheckSortNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/uaeCheckAccountNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/uaecheckaccountnumberfieldnormalizedname","abstract":[{"type":"text","text":"Normalized full name of the “AccountNumber” field type in document type “UAECheck”."}],"navigatorTitle":[{"text":"uaeCheckAccountNumberFieldNormalizedName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/uaeCheckAccountNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"uaeCheckAccountNumberFieldNormalizedName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"uaeCheckAccountNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/checkFontTypeFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/checkfonttypefieldnormalizedname","abstract":[{"text":"Normalized full name of the “FontType” field type in document type “Check”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"checkFontTypeFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/checkFontTypeFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkFontTypeFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"checkFontTypeFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/kwtCheckAccountNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/kwtcheckaccountnumberfieldnormalizedname","abstract":[{"text":"Normalized full name of the “AccountNumber” field type in document type “KWTCheck”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"kwtCheckAccountNumberFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/kwtCheckAccountNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kwtCheckAccountNumberFieldNormalizedName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"kwtCheckAccountNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/init":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/init","title":"init","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/fraCheckAccountNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/fracheckaccountnumberfieldnormalizedname","abstract":[{"type":"text","text":"Normalized full name of the “AccountNumber” field type in document type “FRACheck”."}],"navigatorTitle":[{"text":"fraCheckAccountNumberFieldNormalizedName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/fraCheckAccountNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fraCheckAccountNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"fraCheckAccountNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/canCheckTransitNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/canchecktransitnumberfieldnormalizedname","abstract":[{"text":"Normalized full name of the “TransitNumber” field type in document type “CANCheck”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"canCheckTransitNumberFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckTransitNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canCheckTransitNumberFieldNormalizedName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"canCheckTransitNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/unknownCheckDocumentType":{"title":"unknownCheckDocumentType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/unknownCheckDocumentType","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/unknowncheckdocumenttype","type":"topic","abstract":[{"type":"text","text":"Document type name of the “UnknownCheck” document type."}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownCheckDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"unknownCheckDocumentType"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/isrCheckDocumentType":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/isrcheckdocumenttype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/isrCheckDocumentType","navigatorTitle":[{"text":"isrCheckDocumentType","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"isrCheckDocumentType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","title":"isrCheckDocumentType","abstract":[{"type":"text","text":"Document type name of the “ISRCheck” document type."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentConstants/uaeCheckChequeNumberFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentconstants\/uaecheckchequenumberfieldnormalizedname","abstract":[{"text":"Normalized full name of the “ChequeNumber” field type in document type “UAECheck”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"uaeCheckChequeNumberFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/uaeCheckChequeNumberFieldNormalizedName","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uaeCheckChequeNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"uaeCheckChequeNumberFieldNormalizedName","kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"SBSDKCheckDocumentConstants","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckDocumentConstants"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKCheckDocumentConstants"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/init"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/ausCheckAccountNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/ausCheckAuxDomesticFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/ausCheckBSBFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/ausCheckDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/ausCheckExtraAuxDomesticFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/ausCheckTransactionCodeFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckAccountNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckBankNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckChequeNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckDesignationNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckTransactionCodeFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/canCheckTransitNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/checkDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/checkFontTypeFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/checkRawStringFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/fraCheckAccountNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/fraCheckChequeNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/fraCheckDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/fraCheckRoutingNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/indCheckAccountNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/indCheckDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/indCheckSerialNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/indCheckSortNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/indCheckTransactionCodeFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/isrCheckAccountNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/isrCheckBankNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/isrCheckBranchNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/isrCheckChequeNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/isrCheckDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/kwtCheckAccountNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/kwtCheckChequeNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/kwtCheckDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/kwtCheckSortCodeFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/uaeCheckAccountNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/uaeCheckChequeNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/uaeCheckDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/uaeCheckRoutingNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/unknownCheckDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/usaCheckAccountNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/usaCheckAuxiliaryOnUsFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/usaCheckDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentConstants\/usaCheckTransitNumberFieldNormalizedName"],"title":"Type Properties"}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCheckDocumentConstants"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1fraCheckDocumentType\/title","op":"replace","value":"fraCheckDocumentType"},{"value":[{"kind":"identifier","text":"fraCheckDocumentType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1fraCheckDocumentType\/fragments"},{"op":"replace","value":"indCheckDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1indCheckDocumentType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"indCheckDocumentType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1indCheckDocumentType\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1ausCheckBSBFieldNormalizedName\/title","value":"ausCheckBSBFieldNormalizedName","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1ausCheckBSBFieldNormalizedName\/fragments","value":[{"kind":"identifier","text":"ausCheckBSBFieldNormalizedName"}],"op":"replace"},{"value":"isrCheckChequeNumberFieldNormalizedName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1isrCheckChequeNumberFieldNormalizedName\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1isrCheckChequeNumberFieldNormalizedName\/fragments","value":[{"text":"isrCheckChequeNumberFieldNormalizedName","kind":"identifier"}],"op":"replace"},{"value":"indCheckSerialNumberFieldNormalizedName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1indCheckSerialNumberFieldNormalizedName\/title","op":"replace"},{"op":"replace","value":[{"text":"indCheckSerialNumberFieldNormalizedName","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1indCheckSerialNumberFieldNormalizedName\/fragments"},{"value":"isrCheckBankNumberFieldNormalizedName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1isrCheckBankNumberFieldNormalizedName\/title","op":"replace"},{"value":[{"text":"isrCheckBankNumberFieldNormalizedName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1isrCheckBankNumberFieldNormalizedName\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1fraCheckRoutingNumberFieldNormalizedName\/title","op":"replace","value":"fraCheckRoutingNumberFieldNormalizedName"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1fraCheckRoutingNumberFieldNormalizedName\/fragments","value":[{"text":"fraCheckRoutingNumberFieldNormalizedName","kind":"identifier"}],"op":"replace"},{"value":"usaCheckTransitNumberFieldNormalizedName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1usaCheckTransitNumberFieldNormalizedName\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1usaCheckTransitNumberFieldNormalizedName\/fragments","op":"replace","value":[{"kind":"identifier","text":"usaCheckTransitNumberFieldNormalizedName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1canCheckDesignationNumberFieldNormalizedName\/title","value":"canCheckDesignationNumberFieldNormalizedName"},{"value":[{"kind":"identifier","text":"canCheckDesignationNumberFieldNormalizedName"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1canCheckDesignationNumberFieldNormalizedName\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1canCheckChequeNumberFieldNormalizedName\/title","value":"canCheckChequeNumberFieldNormalizedName"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1canCheckChequeNumberFieldNormalizedName\/fragments","value":[{"kind":"identifier","text":"canCheckChequeNumberFieldNormalizedName"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1canCheckAccountNumberFieldNormalizedName\/title","value":"canCheckAccountNumberFieldNormalizedName","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1canCheckAccountNumberFieldNormalizedName\/fragments","op":"replace","value":[{"text":"canCheckAccountNumberFieldNormalizedName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1indCheckTransactionCodeFieldNormalizedName\/title","value":"indCheckTransactionCodeFieldNormalizedName","op":"replace"},{"op":"replace","value":[{"text":"indCheckTransactionCodeFieldNormalizedName","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1indCheckTransactionCodeFieldNormalizedName\/fragments"},{"op":"replace","value":"checkRawStringFieldNormalizedName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1checkRawStringFieldNormalizedName\/title"},{"value":[{"text":"checkRawStringFieldNormalizedName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1checkRawStringFieldNormalizedName\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1isrCheckBranchNumberFieldNormalizedName\/title","value":"isrCheckBranchNumberFieldNormalizedName"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1isrCheckBranchNumberFieldNormalizedName\/fragments","value":[{"text":"isrCheckBranchNumberFieldNormalizedName","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1usaCheckAuxiliaryOnUsFieldNormalizedName\/title","value":"usaCheckAuxiliaryOnUsFieldNormalizedName"},{"value":[{"text":"usaCheckAuxiliaryOnUsFieldNormalizedName","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1usaCheckAuxiliaryOnUsFieldNormalizedName\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1usaCheckAccountNumberFieldNormalizedName\/title","value":"usaCheckAccountNumberFieldNormalizedName","op":"replace"},{"value":[{"kind":"identifier","text":"usaCheckAccountNumberFieldNormalizedName"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1usaCheckAccountNumberFieldNormalizedName\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1fraCheckChequeNumberFieldNormalizedName\/title","value":"fraCheckChequeNumberFieldNormalizedName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1fraCheckChequeNumberFieldNormalizedName\/fragments","value":[{"kind":"identifier","text":"fraCheckChequeNumberFieldNormalizedName"}]},{"value":"kwtCheckSortCodeFieldNormalizedName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1kwtCheckSortCodeFieldNormalizedName\/title"},{"value":[{"text":"kwtCheckSortCodeFieldNormalizedName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1kwtCheckSortCodeFieldNormalizedName\/fragments"},{"value":"uaeCheckDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1uaeCheckDocumentType\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1uaeCheckDocumentType\/fragments","value":[{"text":"uaeCheckDocumentType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1kwtCheckChequeNumberFieldNormalizedName\/title","value":"kwtCheckChequeNumberFieldNormalizedName"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1kwtCheckChequeNumberFieldNormalizedName\/fragments","value":[{"text":"kwtCheckChequeNumberFieldNormalizedName","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1isrCheckAccountNumberFieldNormalizedName\/title","value":"isrCheckAccountNumberFieldNormalizedName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1isrCheckAccountNumberFieldNormalizedName\/fragments","value":[{"kind":"identifier","text":"isrCheckAccountNumberFieldNormalizedName"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1uaeCheckRoutingNumberFieldNormalizedName\/title","value":"uaeCheckRoutingNumberFieldNormalizedName","op":"replace"},{"value":[{"kind":"identifier","text":"uaeCheckRoutingNumberFieldNormalizedName"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1uaeCheckRoutingNumberFieldNormalizedName\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1canCheckDocumentType\/title","value":"canCheckDocumentType","op":"replace"},{"value":[{"kind":"identifier","text":"canCheckDocumentType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1canCheckDocumentType\/fragments"},{"value":"canCheckTransactionCodeFieldNormalizedName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1canCheckTransactionCodeFieldNormalizedName\/title"},{"value":[{"kind":"identifier","text":"canCheckTransactionCodeFieldNormalizedName"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1canCheckTransactionCodeFieldNormalizedName\/fragments"},{"value":"kwtCheckDocumentType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1kwtCheckDocumentType\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1kwtCheckDocumentType\/fragments","op":"replace","value":[{"kind":"identifier","text":"kwtCheckDocumentType"}]},{"value":"canCheckBankNumberFieldNormalizedName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1canCheckBankNumberFieldNormalizedName\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1canCheckBankNumberFieldNormalizedName\/fragments","value":[{"text":"canCheckBankNumberFieldNormalizedName","kind":"identifier"}],"op":"replace"},{"value":"ausCheckAuxDomesticFieldNormalizedName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1ausCheckAuxDomesticFieldNormalizedName\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1ausCheckAuxDomesticFieldNormalizedName\/fragments","value":[{"text":"ausCheckAuxDomesticFieldNormalizedName","kind":"identifier"}]},{"value":"SBSDKCheckDocumentConstants","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants\/title"},{"value":[{"text":"SBSDKCheckDocumentConstants","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1indCheckAccountNumberFieldNormalizedName\/title","value":"indCheckAccountNumberFieldNormalizedName","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1indCheckAccountNumberFieldNormalizedName\/fragments","value":[{"text":"indCheckAccountNumberFieldNormalizedName","kind":"identifier"}]},{"value":"checkDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1checkDocumentType\/title","op":"replace"},{"op":"replace","value":[{"text":"checkDocumentType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1checkDocumentType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1ausCheckAccountNumberFieldNormalizedName\/title","value":"ausCheckAccountNumberFieldNormalizedName"},{"op":"replace","value":[{"kind":"identifier","text":"ausCheckAccountNumberFieldNormalizedName"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1ausCheckAccountNumberFieldNormalizedName\/fragments"},{"value":"ausCheckDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1ausCheckDocumentType\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1ausCheckDocumentType\/fragments","op":"replace","value":[{"kind":"identifier","text":"ausCheckDocumentType"}]},{"value":"usaCheckDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1usaCheckDocumentType\/title","op":"replace"},{"value":[{"text":"usaCheckDocumentType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1usaCheckDocumentType\/fragments"},{"op":"replace","value":"ausCheckExtraAuxDomesticFieldNormalizedName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1ausCheckExtraAuxDomesticFieldNormalizedName\/title"},{"value":[{"text":"ausCheckExtraAuxDomesticFieldNormalizedName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1ausCheckExtraAuxDomesticFieldNormalizedName\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1ausCheckTransactionCodeFieldNormalizedName\/title","op":"replace","value":"ausCheckTransactionCodeFieldNormalizedName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1ausCheckTransactionCodeFieldNormalizedName\/fragments","value":[{"text":"ausCheckTransactionCodeFieldNormalizedName","kind":"identifier"}]},{"value":"indCheckSortNumberFieldNormalizedName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1indCheckSortNumberFieldNormalizedName\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1indCheckSortNumberFieldNormalizedName\/fragments","value":[{"text":"indCheckSortNumberFieldNormalizedName","kind":"identifier"}],"op":"replace"},{"value":"uaeCheckAccountNumberFieldNormalizedName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1uaeCheckAccountNumberFieldNormalizedName\/title"},{"value":[{"text":"uaeCheckAccountNumberFieldNormalizedName","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1uaeCheckAccountNumberFieldNormalizedName\/fragments","op":"replace"},{"value":"checkFontTypeFieldNormalizedName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1checkFontTypeFieldNormalizedName\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1checkFontTypeFieldNormalizedName\/fragments","value":[{"kind":"identifier","text":"checkFontTypeFieldNormalizedName"}],"op":"replace"},{"op":"replace","value":"kwtCheckAccountNumberFieldNormalizedName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1kwtCheckAccountNumberFieldNormalizedName\/title"},{"op":"replace","value":[{"kind":"identifier","text":"kwtCheckAccountNumberFieldNormalizedName"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1kwtCheckAccountNumberFieldNormalizedName\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1fraCheckAccountNumberFieldNormalizedName\/title","value":"fraCheckAccountNumberFieldNormalizedName","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"fraCheckAccountNumberFieldNormalizedName"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1fraCheckAccountNumberFieldNormalizedName\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1canCheckTransitNumberFieldNormalizedName\/title","value":"canCheckTransitNumberFieldNormalizedName","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1canCheckTransitNumberFieldNormalizedName\/fragments","value":[{"text":"canCheckTransitNumberFieldNormalizedName","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1unknownCheckDocumentType\/title","value":"unknownCheckDocumentType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1unknownCheckDocumentType\/fragments","value":[{"kind":"identifier","text":"unknownCheckDocumentType"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1isrCheckDocumentType\/title","op":"replace","value":"isrCheckDocumentType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1isrCheckDocumentType\/fragments","value":[{"text":"isrCheckDocumentType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1uaeCheckChequeNumberFieldNormalizedName\/title","value":"uaeCheckChequeNumberFieldNormalizedName","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentConstants~1uaeCheckChequeNumberFieldNormalizedName\/fragments","value":[{"kind":"identifier","text":"uaeCheckChequeNumberFieldNormalizedName"}]}]}]}