{"abstract":[{"text":"The status of the generic document recognition.","type":"text"}],"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionStatus","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKGenericDocumentRecognitionStatus","role":"symbol","roleHeading":"Enumeration","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentRecognitionStatus","kind":"identifier"}],"title":"SBSDKGenericDocumentRecognitionStatus","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/errorBadCrop","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/errorNothingFound","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/errorUnacceptableDocument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/errorUnknownDocument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/incompleteValidation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/success"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentRecognitionStatus","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus/errorBadCrop":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/errorbadcrop","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionStatusErrorBadCrop","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"A document was detected, but it was at an angle\/distance that was too large.","type":"text"}],"title":"SBSDKGenericDocumentRecognitionStatus.errorBadCrop","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/errorBadCrop","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorBadCrop","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentRecognitionStatus","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The status of the generic document recognition."}],"navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionStatus","kind":"identifier"}],"title":"SBSDKGenericDocumentRecognitionStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus/incompleteValidation":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/incompletevalidation","title":"SBSDKGenericDocumentRecognitionStatus.incompleteValidation","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatusIncompleteValidation"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"All fields were recognized, but some of them failed validation."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"incompleteValidation","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/incompleteValidation"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus/success":{"title":"SBSDKGenericDocumentRecognitionStatus.success","abstract":[{"text":"The document was recognized successfully.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"success"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/success","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionStatusSuccess","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/success","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/rawrepresentable-implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/RawRepresentable-Implementations","kind":"article"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus/errorNothingFound":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"errorNothingFound","kind":"identifier"}],"abstract":[{"type":"text","text":"No document was detected."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatusErrorNothingFound"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/errorNothingFound","title":"SBSDKGenericDocumentRecognitionStatus.errorNothingFound","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/errornothingfound","kind":"symbol"},"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/equatable-implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/Equatable-Implementations","kind":"article"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus/errorUnacceptableDocument":{"title":"SBSDKGenericDocumentRecognitionStatus.errorUnacceptableDocument","abstract":[{"text":"A document was detected as a supported document, but it was not part of the accepted","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"documents."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorUnacceptableDocument","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/errorunacceptabledocument","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionStatusErrorUnacceptableDocument","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/errorUnacceptableDocument","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus/errorUnknownDocument":{"title":"SBSDKGenericDocumentRecognitionStatus.errorUnknownDocument","abstract":[{"type":"text","text":"A document was detected, but it was not recognized as a supported document."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorUnknownDocument","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/errorunknowndocument","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionStatusErrorUnknownDocument","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/errorUnknownDocument","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus/init(rawValue:)":{"title":"init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/init(rawvalue:)","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/init(rawValue:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKGenericDocumentRecognitionStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKGenericDocumentRecognitionStatus","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatus"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/errorBadCrop","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/errorNothingFound","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/errorUnacceptableDocument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/errorUnknownDocument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/incompleteValidation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/success"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatus"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKGenericDocumentRecognitionStatusErrorBadCrop","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1errorBadCrop\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1errorBadCrop\/fragments","value":[{"text":"SBSDKGenericDocumentRecognitionStatusErrorBadCrop","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus\/title","value":"SBSDKGenericDocumentRecognitionStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus\/fragments","value":[{"text":"SBSDKGenericDocumentRecognitionStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1incompleteValidation\/title","value":"SBSDKGenericDocumentRecognitionStatusIncompleteValidation"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatusIncompleteValidation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1incompleteValidation\/fragments","op":"replace"},{"value":"SBSDKGenericDocumentRecognitionStatusSuccess","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1success\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1success\/fragments","value":[{"text":"SBSDKGenericDocumentRecognitionStatusSuccess","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1errorNothingFound\/title","value":"SBSDKGenericDocumentRecognitionStatusErrorNothingFound"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1errorNothingFound\/fragments","value":[{"text":"SBSDKGenericDocumentRecognitionStatusErrorNothingFound","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1errorUnacceptableDocument\/title","op":"replace","value":"SBSDKGenericDocumentRecognitionStatusErrorUnacceptableDocument"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatusErrorUnacceptableDocument"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1errorUnacceptableDocument\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1errorUnknownDocument\/title","value":"SBSDKGenericDocumentRecognitionStatusErrorUnknownDocument"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1errorUnknownDocument\/fragments","value":[{"text":"SBSDKGenericDocumentRecognitionStatusErrorUnknownDocument","kind":"identifier"}]}]}]}