{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFinderViewDelegate","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewDelegate"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewDelegate\/finderView(_:didChangeRect:)"]}],"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"title":"SBSDKFinderViewDelegate","navigatorTitle":[{"text":"SBSDKFinderViewDelegate","kind":"identifier"}],"role":"symbol","roleHeading":"Protocol","symbolKind":"protocol","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKFinderViewDelegate","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"text":"The delegate protocol for the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView"},{"type":"text","text":" class."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkfinderviewdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkfinderviewdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller","navigatorTitle":[{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the vehicle identification number scanner."}],"title":"SBSDKVINScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller","title":"SBSDKMedicalCertificateScannerViewController","navigatorTitle":[{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"The classic UI view controller that can be used to detect and scan medical certificates. Can be configured to scan on video frames or,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for better accuracy, on high-res photos that are automatically captured."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderViewDelegate":{"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKFinderViewDelegate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewDelegate","abstract":[{"text":"The delegate protocol for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","isActive":true,"type":"reference"},{"type":"text","text":" class."}],"navigatorTitle":[{"text":"SBSDKFinderViewDelegate","kind":"identifier"}],"title":"SBSDKFinderViewDelegate","url":"\/documentation\/scanbotsdk\/sbsdkfinderviewdelegate","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorViewController":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewController","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to extract documents data, e.g. German passports, ID cards and driver’s licenses on video frames.","type":"text"}],"navigatorTitle":[{"text":"SBSDKDocumentDataExtractorViewController","kind":"identifier"}],"title":"SBSDKDocumentDataExtractorViewController","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorviewcontroller","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","navigatorTitle":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"title":"SBSDKDocumentScannerViewController","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller","role":"symbol","abstract":[{"text":"A UIViewController subclass to show a camera screen and run a user guiding document scanner.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerViewController":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCreditCardScannerViewController"}],"abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan credit cards."}],"title":"SBSDKCreditCardScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKCreditCardScannerViewController"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewController":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode scanner."},{"type":"text","text":" "},{"type":"text","text":"Screen also shows snap, scan more and reset buttons."},{"type":"text","text":" "},{"text":"The snap button starts the scanning when tapped.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The snap button resets the scanning when tapped again."},{"text":" ","type":"text"},{"type":"text","text":"Instead it is installing itself as a child view controller onto a given parent view controller."}],"title":"SBSDKBarcodeScanAndCountViewController","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontroller","navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerViewController":{"title":"SBSDKTextPatternScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the text pattern scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView":{"role":"symbol","abstract":[{"text":"A ","type":"text"},{"code":"UIView","type":"codeVoice"},{"text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","url":"\/documentation\/scanbotsdk\/sbsdkfinderview","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKFinderView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKFinderView"}],"type":"topic","title":"SBSDKFinderView","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderViewDelegate/finderView(_:didChangeRect:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewDelegate\/finderView(_:didChangeRect:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"finderView","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKFinderView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didChangeRect"},{"kind":"text","text":": "},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"finderView(_:didChangeRect:)","url":"\/documentation\/scanbotsdk\/sbsdkfinderviewdelegate\/finderview(_:didchangerect:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"finderView:didChangeRect:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Informs the delegate, that the finder view has changed its finder rectangle.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Optional."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerViewController":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerViewController"}],"deprecated":true,"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKHealthInsuranceCardRecognizerViewController","kind":"identifier"}],"title":"SBSDKHealthInsuranceCardRecognizerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewController","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerviewcontroller","role":"symbol","abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to scan health insurance cards with the camera.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewController":{"abstract":[{"text":"Classic UI view controller that can be used to scan bank checks.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"title":"SBSDKCheckScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewController":{"title":"SBSDKMRZScannerViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZScannerViewController"}],"kind":"symbol","abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan machine-readable zones."}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","type":"topic","navigatorTitle":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewController":{"navigatorTitle":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A highly customizable camera view controller that delivers a basic camera functionality along with video"},{"type":"text","text":" "},{"type":"text","text":"frame extraction and preprocessing, orientation correction and still image capturing."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController","title":"SBSDKBaseScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"title":"SBSDKBarcodeScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKFinderViewDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKFinderViewDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewDelegate\/finderView(_:didChangeRect:)"]}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Conforming Types","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"],"kind":"relationships","type":"conformingTypes"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKFinderViewDelegate","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/title","value":"SBSDKVINScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/fragments","value":[{"text":"SBSDKVINScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVINScannerViewController"}]},{"value":"SBSDKMedicalCertificateScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}]},{"value":"SBSDKFinderViewDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate\/fragments","op":"replace","value":[{"text":"SBSDKFinderViewDelegate","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate\/navigatorTitle"},{"op":"replace","value":"SBSDKDocumentDataExtractorViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewController\/fragments","value":[{"text":"SBSDKDocumentDataExtractorViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/title","value":"SBSDKDocumentScannerViewController","op":"replace"},{"value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController\/title","op":"replace","value":"SBSDKCreditCardScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCreditCardScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController\/navigatorTitle","value":[{"text":"SBSDKCreditCardScannerViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/title","value":"SBSDKBarcodeScanAndCountViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/navigatorTitle","value":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/title","value":"SBSDKTextPatternScannerViewController","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/title","value":"SBSDKFinderView","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/fragments","value":[{"kind":"identifier","text":"SBSDKFinderView"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFinderView"}],"op":"replace"},{"value":"finderView:didChangeRect:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate~1finderView(_:didChangeRect:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate~1finderView(_:didChangeRect:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"finderView:didChangeRect:","kind":"identifier"}]},{"value":"SBSDKHealthInsuranceCardRecognizerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewController\/fragments","value":[{"text":"SBSDKHealthInsuranceCardRecognizerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKHealthInsuranceCardRecognizerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/title","value":"SBSDKCheckScannerViewController","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCheckScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/title","value":"SBSDKMRZScannerViewController"},{"value":[{"kind":"identifier","text":"SBSDKMRZScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/fragments","op":"replace"},{"value":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/title","value":"SBSDKBaseScannerViewController"},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}]},{"value":"SBSDKBarcodeScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}]},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}