{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVehicleIdentificationNumberScannerResult","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerresult"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerresult"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScannerResult"}],"symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerResult","title":"SBSDKVehicleIdentificationNumberScannerResult","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScannerResult"}],"modules":[{"name":"ScanbotSDK"}]},"abstract":[{"text":"A class describing the result of the vehicle identification number scanner.","type":"text"}],"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult\/confidenceValue","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult\/isValidationSuccessful","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult\/text"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerResult":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKVehicleIdentificationNumberScannerResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScannerResult"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult","type":"topic","title":"SBSDKVehicleIdentificationNumberScannerResult","url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerresult","abstract":[{"text":"A class describing the result of the vehicle identification number scanner.","type":"text"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerResult/confidenceValue":{"navigatorTitle":[{"text":"confidenceValue","kind":"identifier"}],"title":"confidenceValue","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult\/confidenceValue","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerresult\/confidencevalue","abstract":[{"text":"The scanned results confidence value.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidenceValue"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerResult/initWithIsValidationSuccessful:text:confidenceValue:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult\/initWithIsValidationSuccessful:text:confidenceValue:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithIsValidationSuccessful:text:confidenceValue:","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"title":"initWithIsValidationSuccessful:text:confidenceValue:","navigatorTitle":[{"kind":"identifier","text":"initWithIsValidationSuccessful:text:confidenceValue:"}],"url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerresult\/initwithisvalidationsuccessful:text:confidencevalue:"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerResult/isValidationSuccessful":{"navigatorTitle":[{"kind":"identifier","text":"isValidationSuccessful"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"isValidationSuccessful","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"isValidationSuccessful","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerresult\/isvalidationsuccessful","abstract":[{"code":"True","type":"codeVoice"},{"type":"text","text":" if the result has been validated, "},{"code":"False","type":"codeVoice"},{"text":" otherwise.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult\/isValidationSuccessful"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerResult/text":{"title":"text","url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerresult\/text","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"text"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult\/text","type":"topic","kind":"symbol","abstract":[{"text":"The scanned vehicle identification number string.","type":"text"}],"navigatorTitle":[{"text":"text","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"SBSDKVehicleIdentificationNumberScannerResult","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKVehicleIdentificationNumberScannerResult","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKVehicleIdentificationNumberScannerResult","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult\/confidenceValue","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult\/isValidationSuccessful","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult\/text"],"anchor":"Instance-Properties","generated":true},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult\/initWithIsValidationSuccessful:text:confidenceValue:"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVehicleIdentificationNumberScannerResult","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKVehicleIdentificationNumberScannerResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerResult\/title"},{"op":"replace","value":[{"text":"SBSDKVehicleIdentificationNumberScannerResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerResult\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScannerResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerResult\/navigatorTitle"},{"value":"confidenceValue","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerResult~1confidenceValue\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerResult~1confidenceValue\/fragments","value":[{"text":"confidenceValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerResult~1isValidationSuccessful\/title","value":"isValidationSuccessful","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerResult~1isValidationSuccessful\/fragments","value":[{"text":"isValidationSuccessful","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerResult~1text\/title","value":"text"},{"op":"replace","value":[{"text":"text","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerResult~1text\/fragments"}]}]}