{"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/dual","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/dualWide","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/simulated","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/tele","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/triple","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/ultraWide","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/wide"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/RawRepresentable-Implementations"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDeviceType"}],"roleHeading":"Enumeration","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKCameraDeviceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"role":"symbol","symbolKind":"enum","title":"SBSDKCameraDeviceType"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevicetype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevicetype"]}],"sections":[],"abstract":[{"text":"An enum to describe the different types of camera lenses\/devices.","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCameraDeviceType"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType/triple":{"url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/triple","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"triple","kind":"identifier"}],"abstract":[{"text":"The triple lens\/device (ultra-wide + wide + tele).","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/triple","kind":"symbol","type":"topic","title":"SBSDKCameraDeviceType.triple","role":"symbol","navigatorTitle":[{"text":"SBSDKCameraDeviceTypeTriple","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType/simulated":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/simulated","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/simulated","abstract":[{"type":"text","text":"A simulated camera that can simulate a video stream by looping a video or a single image."},{"text":" ","type":"text"},{"text":"Also used on iPhone\/iPad simulators without providing a video stream.","type":"text"}],"title":"SBSDKCameraDeviceType.simulated","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"simulated"}],"navigatorTitle":[{"text":"SBSDKCameraDeviceTypeSimulated","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType/tele":{"abstract":[{"type":"text","text":"The telephoto lens\/device."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/tele","title":"SBSDKCameraDeviceType.tele","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/tele","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tele"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeTele"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCameraDeviceType"}],"navigatorTitle":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType","abstract":[{"type":"text","text":"An enum to describe the different types of camera lenses\/devices."}],"role":"symbol","title":"SBSDKCameraDeviceType","url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType/init(rawValue:)":{"url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/init(rawvalue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/init(rawValue:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType/dualWide":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/dualwide","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/dualWide","abstract":[{"type":"text","text":"The dual-wide lens\/device (wide + ultra-wide)."}],"title":"SBSDKCameraDeviceType.dualWide","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"dualWide","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeDualWide"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType/Equatable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/equatable-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/Equatable-Implementations","abstract":[],"role":"collectionGroup","title":"Equatable Implementations","kind":"article","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType/dual":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/dual","title":"SBSDKCameraDeviceType.dual","type":"topic","navigatorTitle":[{"text":"SBSDKCameraDeviceTypeDual","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dual"}],"abstract":[{"text":"The dual lens\/device (wide + tele).","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/dual","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/rawrepresentable-implementations","type":"topic","kind":"article"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType/wide":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/wide","title":"SBSDKCameraDeviceType.wide","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"wide"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/wide","abstract":[{"text":"The wide angle lens\/device.","type":"text"}],"navigatorTitle":[{"text":"SBSDKCameraDeviceTypeWide","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType/ultraWide":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/ultrawide","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ultraWide"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/ultraWide","title":"SBSDKCameraDeviceType.ultraWide","abstract":[{"text":"The ultra-wide lens\/device.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeUltraWide"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","value":"SBSDKCameraDeviceType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCameraDeviceType"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/dual","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/dualWide","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/simulated","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/tele","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/triple","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/ultraWide","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/wide"],"title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCameraDeviceType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKCameraDeviceTypeTriple","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1triple\/title","op":"replace"},{"value":[{"text":"SBSDKCameraDeviceTypeTriple","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1triple\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1simulated\/title","op":"replace","value":"SBSDKCameraDeviceTypeSimulated"},{"op":"replace","value":[{"text":"SBSDKCameraDeviceTypeSimulated","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1simulated\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1tele\/title","value":"SBSDKCameraDeviceTypeTele"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1tele\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeTele"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/title","value":"SBSDKCameraDeviceType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/fragments","value":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1dualWide\/title","value":"SBSDKCameraDeviceTypeDualWide"},{"value":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeDualWide"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1dualWide\/fragments","op":"replace"},{"value":"SBSDKCameraDeviceTypeDual","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1dual\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1dual\/fragments","op":"replace","value":[{"text":"SBSDKCameraDeviceTypeDual","kind":"identifier"}]},{"op":"replace","value":"SBSDKCameraDeviceTypeWide","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1wide\/title"},{"value":[{"text":"SBSDKCameraDeviceTypeWide","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1wide\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1ultraWide\/title","value":"SBSDKCameraDeviceTypeUltraWide"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1ultraWide\/fragments","value":[{"text":"SBSDKCameraDeviceTypeUltraWide","kind":"identifier"}],"op":"replace"}]}]}