{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"kind":"symbol","abstract":[{"type":"text","text":"A class that converts images to (multipage) TIFF images."},{"type":"text","text":" "},{"type":"text","text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc."},{"type":"text","text":" "},{"type":"text","text":"When passing an encrypter the generated TIFF images will be encrypted."}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKTIFFImageWriter","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriter","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"symbolKind":"class"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter"},"sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/init(parameters:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/init(parameters:encrypter:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/encrypter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/parameters"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/tiffData(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/tiffData(from:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFF(document:toFile:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFF(document:toFile:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFF(from:toFile:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFF(from:toFile:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFF(with:toFile:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFF(with:toFile:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(document:toFile:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(from:toFile:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(with:toFile:)"],"title":"Instance Methods"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriter"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter/writeTIFF(document:toFile:completion:)":{"kind":"symbol","abstract":[{"type":"text","text":"Asynchronously converts the document to a multipage-TIFF file and writes it to the specified URL."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"writeTIFF"},{"kind":"text","text":"("},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument"},{"text":", ","kind":"text"},{"text":"toFile","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?) -> ())","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFF(document:toFile:completion:)","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/writetiff(document:tofile:completion:)","navigatorTitle":[{"kind":"identifier","text":"writeTIFFWithDocument:toFile:completion:"}],"type":"topic","title":"writeTIFF(document:toFile:completion:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter/writeTIFFAsync(document:toFile:)":{"kind":"symbol","abstract":[{"text":"Asynchronously converts the document to a multipage-TIFF file and writes it to the specified URL.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"writeTIFFAsync","kind":"identifier"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","text":"SBSDKDocument","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"toFile","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(document:toFile:)","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/writetiffasync(document:tofile:)","navigatorTitle":[{"kind":"identifier","text":"writeTIFFAsyncWithDocument:toFile:completionHandler:"}],"type":"topic","title":"writeTIFFAsync(document:toFile:)","role":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter/encrypter":{"kind":"symbol","abstract":[{"type":"text","text":"The encrypter used to write TIFF images. Readonly, optional."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"encrypter"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/encrypter","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/encrypter","navigatorTitle":[{"text":"encrypter","kind":"identifier"}],"type":"topic","title":"encrypter","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter":{"title":"SBSDKTIFFImageWriter","abstract":[{"text":"A class that converts images to (multipage) TIFF images.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc."},{"text":" ","type":"text"},{"type":"text","text":"When passing an encrypter the generated TIFF images will be encrypted."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTIFFImageWriter"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter/writeTIFFAsync(with:toFile:)":{"title":"writeTIFFAsync(with:toFile:)","abstract":[{"type":"text","text":"Asynchronously converts the given images to a multipage-TIFF file and writes it to the specified URL."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"writeTIFFAsyncWith:toFile:completionHandler:"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/writetiffasync(with:tofile:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"writeTIFFAsync","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": [","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"toFile","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(with:toFile:)"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter/writeTIFFAsync(from:toFile:)":{"title":"writeTIFFAsync(from:toFile:)","abstract":[{"text":"Asynchronously converts the images at the given image URLs to a multipage-TIFF file and writes it to the specified URL.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"writeTIFFAsyncFrom:toFile:completionHandler:"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/writetiffasync(from:tofile:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"writeTIFFAsync","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": [","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"toFile","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(from:toFile:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter/writeTIFF(from:toFile:completion:)":{"title":"writeTIFF(from:toFile:completion:)","abstract":[{"text":"Asynchronously converts the images at the given image URLs to a multipage-TIFF file and writes it to the specified URL.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"writeTIFFFrom:toFile:completion:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/writetiff(from:tofile:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"writeTIFF","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": [","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"toFile","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?) -> ())"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFF(from:toFile:completion:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter/writeTIFF(from:toFile:)":{"title":"writeTIFF(from:toFile:)","abstract":[{"type":"text","text":"Synchronously converts the images at the given image URLs to a multipage-TIFF file and writes it to the specified URL."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"writeTIFFFrom:toFile:"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/writetiff(from:tofile:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"writeTIFF","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": [","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"toFile","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFF(from:toFile:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter/tiffData(from:)":{"title":"tiffData(from:)","abstract":[{"text":"Synchronously converts the given images into multipage-TIFF data and returns it.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"tiffDataFrom:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/tiffdata(from:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tiffData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/tiffData(from:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter/init(parameters:encrypter:)":{"title":"init(parameters:encrypter:)","abstract":[{"type":"text","text":"Initializes a new TIFF image writer with the specified parameters and encrypter."}],"role":"symbol","navigatorTitle":[{"text":"initWithParameters:encrypter:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/init(parameters:encrypter:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"parameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKTIFFImageWriterParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriterParameters"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting"},{"text":"?)","kind":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/init(parameters:encrypter:)"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter/writeTIFF(with:toFile:completion:)":{"title":"writeTIFF(with:toFile:completion:)","abstract":[{"text":"Asynchronously converts the given images to a multipage-TIFF file and writes it to the specified URL.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"writeTIFFWith:toFile:completion:"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/writetiff(with:tofile:completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"writeTIFF","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"toFile","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?) -> ())","kind":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFF(with:toFile:completion:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter/writeTIFF(with:toFile:)":{"title":"writeTIFF(with:toFile:)","abstract":[{"text":"Synchronously converts the given images to a multipage-TIFF file and writes it to the specified URL.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"writeTIFFWith:toFile:"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/writetiff(with:tofile:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"writeTIFF"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"toFile","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFF(with:toFile:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter/writeTIFF(document:toFile:)":{"title":"writeTIFF(document:toFile:)","abstract":[{"type":"text","text":"Synchronously converts the document to a multipage-TIFF file and writes it to the specified URL."}],"role":"symbol","navigatorTitle":[{"text":"writeTIFFWithDocument:toFile:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/writetiff(document:tofile:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"writeTIFF","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"document"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","text":"SBSDKDocument","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"toFile","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFF(document:toFile:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter/tiffData(from:completion:)":{"title":"tiffData(from:completion:)","abstract":[{"text":"Asynchronously converts the given images into multipage-TIFF data and returns it.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"tiffDataFrom:completion:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/tiffdata(from:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tiffData"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?) -> ())","kind":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/tiffData(from:completion:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter/init(parameters:)":{"title":"init(parameters:)","abstract":[{"type":"text","text":"Initializes a new TIFF image writer with the specified parameters and no encrypter."}],"role":"symbol","navigatorTitle":[{"text":"initWithParameters:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/init(parameters:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parameters","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKTIFFImageWriterParameters","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriterParameters","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/init(parameters:)"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter/init()":{"title":"init()","abstract":[{"type":"text","text":"Initializes a new TIFF image writer with no encrypter, using the default parameters for binarized images."}],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/init()","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/init()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriter/parameters":{"title":"parameters","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parameters","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKTIFFImageWriterParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriterParameters"}],"abstract":[{"text":"The TIFF writing parameters used to write TIFF images. Readonly.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/parameters","role":"symbol","type":"topic","navigatorTitle":[{"text":"parameters","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriter\/parameters"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKTIFFImageWriter"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/encrypter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/parameters"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/init(parameters:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/init(parameters:encrypter:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/tiffData(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/tiffData(from:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFF(document:toFile:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFF(document:toFile:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFF(from:toFile:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFF(from:toFile:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFF(with:toFile:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFF(with:toFile:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(document:toFile:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(from:toFile:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(with:toFile:)"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFImageWriter"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"writeTIFFWithDocument:toFile:completion:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFF(document:toFile:completion:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFF(document:toFile:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"writeTIFFWithDocument:toFile:completion:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(document:toFile:)\/title","value":"writeTIFFAsyncWithDocument:toFile:completionHandler:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(document:toFile:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"writeTIFFAsyncWithDocument:toFile:completionHandler:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1encrypter\/title","value":"encrypter"},{"value":[{"kind":"identifier","text":"encrypter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1encrypter\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter\/title","value":"SBSDKTIFFImageWriter","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKTIFFImageWriter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter\/fragments"},{"value":"writeTIFFAsyncWith:toFile:completionHandler:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(with:toFile:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(with:toFile:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"writeTIFFAsyncWith:toFile:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(from:toFile:)\/title","value":"writeTIFFAsyncFrom:toFile:completionHandler:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(from:toFile:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"writeTIFFAsyncFrom:toFile:completionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFF(from:toFile:completion:)\/title","value":"writeTIFFFrom:toFile:completion:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"writeTIFFFrom:toFile:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFF(from:toFile:completion:)\/fragments","op":"replace"},{"value":"writeTIFFFrom:toFile:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFF(from:toFile:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"writeTIFFFrom:toFile:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFF(from:toFile:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1tiffData(from:)\/title","value":"tiffDataFrom:"},{"value":[{"text":"- ","kind":"text"},{"text":"tiffDataFrom:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1tiffData(from:)\/fragments","op":"replace"},{"value":"initWithParameters:encrypter:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1init(parameters:encrypter:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1init(parameters:encrypter:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithParameters:encrypter:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFF(with:toFile:completion:)\/title","op":"replace","value":"writeTIFFWith:toFile:completion:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFF(with:toFile:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"writeTIFFWith:toFile:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFF(with:toFile:)\/title","value":"writeTIFFWith:toFile:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFF(with:toFile:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"writeTIFFWith:toFile:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFF(document:toFile:)\/title","value":"writeTIFFWithDocument:toFile:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"writeTIFFWithDocument:toFile:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1writeTIFF(document:toFile:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1tiffData(from:completion:)\/title","op":"replace","value":"tiffDataFrom:completion:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1tiffData(from:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tiffDataFrom:completion:"}],"op":"replace"},{"op":"replace","value":"initWithParameters:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1init(parameters:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"initWithParameters:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1init(parameters:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1init()\/title","op":"replace","value":"init"},{"value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1init()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1parameters\/title","op":"replace","value":"parameters"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriter~1parameters\/fragments","op":"replace","value":[{"text":"parameters","kind":"identifier"}]}]}]}