{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2BarcodeTextLocalization) ","kind":"text"},{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Configuration of the all strings for barcode scanner."}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeTextLocalization","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"role":"symbol","title":"SBSDKUI2BarcodeTextLocalization","symbolKind":"class","roleHeading":"Class"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/init(from:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingErrorStateCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingErrorStateRetryButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingErrorStateSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingErrorStateTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingLoadingMessage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/cameraPermissionCloseButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/cameraPermissionEnableCameraButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/cameraPermissionEnableCameraExplanation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/cameraPermissionEnableCameraTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickCompleteAlertCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickCompleteAlertSubmitButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickCompleteAlertSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickCompleteAlertTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickPartialAlertCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickPartialAlertSubmitButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickPartialAlertSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickPartialAlertTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickSheetBarcodeItemSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickSheetTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/manualCountEditDialogCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/manualCountEditDialogInfo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/manualCountEditDialogTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/manualCountEditDialogUpdateButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/multipleModeSheetTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetClearAllButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetPlaceholderSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetPlaceholderTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetResetButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetStartScanningButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetSubmitButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/singleModeConfirmationCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/topBarCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/topBarTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/userGuidance"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/toJson()"],"anchor":"Instance-Methods","title":"Instance Methods"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:)":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/init(camerapermissionenablecameratitle:camerapermissionenablecameraexplanation:camerapermissionenablecamerabutton:camerapermissionclosebutton:topbarcancelbutton:topbartitle:userguidance:barcodeinfomappingloadingmessage:barcodeinfomappingerr-5o628","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"cameraPermissionEnableCameraTitle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"cameraPermissionEnableCameraExplanation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"cameraPermissionEnableCameraButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraPermissionCloseButton"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"topBarCancelButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topBarTitle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userGuidance"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"barcodeInfoMappingLoadingMessage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"barcodeInfoMappingErrorStateTitle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"barcodeInfoMappingErrorStateSubtitle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barcodeInfoMappingErrorStateRetryButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"barcodeInfoMappingErrorStateCancelButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"manualCountEditDialogTitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"manualCountEditDialogInfo","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"manualCountEditDialogUpdateButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"manualCountEditDialogCancelButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"sheetResetButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sheetClearAllButton"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"sheetSubmitButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sheetStartScanningButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sheetPlaceholderTitle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sheetPlaceholderSubtitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"singleModeConfirmationCancelButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"multipleModeSheetTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"findAndPickSheetTitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"findAndPickSheetBarcodeItemSubtitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"findAndPickPartialAlertTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"findAndPickPartialAlertSubtitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"findAndPickPartialAlertCancelButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"findAndPickPartialAlertSubmitButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"findAndPickCompleteAlertTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"findAndPickCompleteAlertSubtitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"findAndPickCompleteAlertCancelButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"findAndPickCompleteAlertSubmitButton"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:)","navigatorTitle":[{"kind":"identifier","text":"initWithCameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:"}],"title":"init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:)","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/findAndPickCompleteAlertCancelButton":{"navigatorTitle":[{"text":"findAndPickCompleteAlertCancelButton","kind":"identifier"}],"abstract":[{"text":"Cancel button text for the find and pick complete alert.","type":"text"},{"type":"text","text":" "},{"text":"Default is “Dismiss”","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickCompleteAlertCancelButton","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/findandpickcompletealertcancelbutton","title":"findAndPickCompleteAlertCancelButton","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"findAndPickCompleteAlertCancelButton"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/barcodeInfoMappingErrorStateCancelButton":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeInfoMappingErrorStateCancelButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/barcodeinfomappingerrorstatecancelbutton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingErrorStateCancelButton","navigatorTitle":[{"text":"barcodeInfoMappingErrorStateCancelButton","kind":"identifier"}],"title":"barcodeInfoMappingErrorStateCancelButton","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Cancel button text for the barcode info mapping error state."},{"text":" ","type":"text"},{"text":"Default is “Cancel”","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/userGuidance":{"navigatorTitle":[{"text":"userGuidance","kind":"identifier"}],"abstract":[{"text":"User guidance text.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is “Move the finder over a barcode”"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/userGuidance","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/userguidance","title":"userGuidance","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"userGuidance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/sheetPlaceholderTitle":{"role":"symbol","abstract":[{"text":"Title for the barcode sheet placeholder.","type":"text"},{"type":"text","text":" "},{"text":"Default is “No barcodes here!”","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sheetPlaceholderTitle"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"sheetPlaceholderTitle","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetPlaceholderTitle","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/sheetplaceholdertitle","kind":"symbol","title":"sheetPlaceholderTitle"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/sheetPlaceholderSubtitle":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/sheetplaceholdersubtitle","type":"topic","title":"sheetPlaceholderSubtitle","navigatorTitle":[{"text":"sheetPlaceholderSubtitle","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sheetPlaceholderSubtitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"type":"text","text":"Subtitle for the barcode sheet placeholder."},{"type":"text","text":" "},{"text":"Default is “The barcode list is currently empty. Close this sheet and scan your items to add them.”","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetPlaceholderSubtitle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/barcodeInfoMappingErrorStateSubtitle":{"abstract":[{"text":"Subtitle for the barcode info mapping error state.","type":"text"},{"text":" ","type":"text"},{"text":"Default is “There was an issue and the data requested was not fetched. You could try again or discard this","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"result to start a new scan.”"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeInfoMappingErrorStateSubtitle"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"barcodeInfoMappingErrorStateSubtitle"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/barcodeinfomappingerrorstatesubtitle","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingErrorStateSubtitle","title":"barcodeInfoMappingErrorStateSubtitle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2Node","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Node"}],"title":"SBSDKUI2Node","abstract":[{"text":"Abstract class for all the configurations.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2node","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/sheetResetButton":{"role":"symbol","abstract":[{"type":"text","text":"Reset button text for the barcode sheet."},{"text":" ","type":"text"},{"text":"Default is “Reset”","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sheetResetButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"sheetResetButton","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetResetButton","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/sheetresetbutton","kind":"symbol","title":"sheetResetButton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/isEqual:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"role":"symbol","abstract":[],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/isEqual:","kind":"symbol","title":"isEqual:","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/isequal:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/cameraPermissionEnableCameraTitle":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/cameraPermissionEnableCameraTitle","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/camerapermissionenablecameratitle","kind":"symbol","type":"topic","abstract":[{"text":"Title for the camera permission dialog.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is “Camera permission denied!”"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cameraPermissionEnableCameraTitle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"cameraPermissionEnableCameraTitle","navigatorTitle":[{"kind":"identifier","text":"cameraPermissionEnableCameraTitle"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/manualCountEditDialogTitle":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/manualcounteditdialogtitle","kind":"symbol","abstract":[{"text":"Title for the manual count edit dialog.","type":"text"},{"type":"text","text":" "},{"text":"Default is “Update count”","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"manualCountEditDialogTitle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"manualCountEditDialogTitle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/manualCountEditDialogTitle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"manualCountEditDialogTitle"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/findAndPickSheetBarcodeItemSubtitle":{"navigatorTitle":[{"kind":"identifier","text":"findAndPickSheetBarcodeItemSubtitle"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/findandpicksheetbarcodeitemsubtitle","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickSheetBarcodeItemSubtitle","title":"findAndPickSheetBarcodeItemSubtitle","abstract":[{"type":"text","text":"Subtitle for the find and pick barcode sheet."},{"text":" ","type":"text"},{"type":"text","text":"Default is “%d\/%d added”"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"findAndPickSheetBarcodeItemSubtitle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/toJson()":{"title":"toJson()","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/toJson()","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/tojson()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"toJson","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"toJson","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/cameraPermissionCloseButton":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"cameraPermissionCloseButton","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/camerapermissionclosebutton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPermissionCloseButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Close button text for the camera permission dialog."},{"type":"text","text":" "},{"type":"text","text":"Default is “Close”"}],"title":"cameraPermissionCloseButton","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/cameraPermissionCloseButton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/findAndPickPartialAlertCancelButton":{"title":"findAndPickPartialAlertCancelButton","abstract":[{"type":"text","text":"Cancel button text for the find and pick partial alert."},{"type":"text","text":" "},{"text":"Default is “Cancel”","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/findandpickpartialalertcancelbutton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickPartialAlertCancelButton","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"findAndPickPartialAlertCancelButton"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"findAndPickPartialAlertCancelButton"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/sheetClearAllButton":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetClearAllButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sheetClearAllButton","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/sheetclearallbutton","title":"sheetClearAllButton","role":"symbol","abstract":[{"text":"Clear all button text for the barcode sheet.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is “Clear all”"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sheetClearAllButton"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/findAndPickSheetTitle":{"abstract":[{"type":"text","text":"Title for the find and pick barcode sheet."},{"type":"text","text":" "},{"type":"text","text":"Default is “%d\/%d scanned”"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"findAndPickSheetTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/findandpicksheettitle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickSheetTitle","kind":"symbol","title":"findAndPickSheetTitle","role":"symbol","navigatorTitle":[{"text":"findAndPickSheetTitle","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/manualCountEditDialogCancelButton":{"navigatorTitle":[{"kind":"identifier","text":"manualCountEditDialogCancelButton"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/manualcounteditdialogcancelbutton","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/manualCountEditDialogCancelButton","title":"manualCountEditDialogCancelButton","abstract":[{"type":"text","text":"Cancel button text for the manual count edit dialog."},{"type":"text","text":" "},{"text":"Default is “Cancel”","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"manualCountEditDialogCancelButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/init()":{"role":"symbol","title":"init()","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/init()","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/barcodeInfoMappingLoadingMessage":{"navigatorTitle":[{"text":"barcodeInfoMappingLoadingMessage","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/barcodeinfomappingloadingmessage","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingLoadingMessage","title":"barcodeInfoMappingLoadingMessage","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"barcodeInfoMappingLoadingMessage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Loading message for barcode info mapping."},{"text":" ","type":"text"},{"text":"Default is “Loading details…”","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/barcodeInfoMappingErrorStateTitle":{"abstract":[{"type":"text","text":"Title for the barcode info mapping error state."},{"text":" ","type":"text"},{"text":"Default is “Connection Error!”","type":"text"}],"title":"barcodeInfoMappingErrorStateTitle","navigatorTitle":[{"text":"barcodeInfoMappingErrorStateTitle","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingErrorStateTitle","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/barcodeinfomappingerrorstatetitle","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"barcodeInfoMappingErrorStateTitle","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/findAndPickCompleteAlertTitle":{"abstract":[{"text":"Title for the find and pick complete alert.","type":"text"},{"text":" ","type":"text"},{"text":"Default is “All codes found!”","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickCompleteAlertTitle","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/findandpickcompletealerttitle","title":"findAndPickCompleteAlertTitle","type":"topic","kind":"symbol","navigatorTitle":[{"text":"findAndPickCompleteAlertTitle","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"findAndPickCompleteAlertTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/findAndPickPartialAlertTitle":{"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"findAndPickPartialAlertTitle","kind":"identifier"}],"title":"findAndPickPartialAlertTitle","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"findAndPickPartialAlertTitle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/findandpickpartialalerttitle","abstract":[{"text":"Title for the find and pick partial alert.","type":"text"},{"type":"text","text":" "},{"text":"Default is “Incomplete scan!”","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickPartialAlertTitle"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/sheetSubmitButton":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sheetSubmitButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetSubmitButton","kind":"symbol","abstract":[{"type":"text","text":"Submit button text for the barcode sheet."},{"type":"text","text":" "},{"type":"text","text":"Default is “Submit”"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/sheetsubmitbutton","role":"symbol","navigatorTitle":[{"text":"sheetSubmitButton","kind":"identifier"}],"title":"sheetSubmitButton"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/findAndPickCompleteAlertSubtitle":{"title":"findAndPickCompleteAlertSubtitle","abstract":[{"text":"Subtitle for the find and pick complete alert.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is “You have successfully scanned all codes. Proceed with submission?”"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/findandpickcompletealertsubtitle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"findAndPickCompleteAlertSubtitle"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"findAndPickCompleteAlertSubtitle","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickCompleteAlertSubtitle","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/init(from:)":{"kind":"symbol","title":"init(from:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/init(from:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/init(from:)","role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/sheetStartScanningButton":{"abstract":[{"type":"text","text":"Start scanning button text for the barcode sheet."},{"type":"text","text":" "},{"type":"text","text":"Default is “Start scanning”"}],"title":"sheetStartScanningButton","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/sheetstartscanningbutton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetStartScanningButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sheetStartScanningButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"sheetStartScanningButton","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/topBarTitle":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/topbartitle","kind":"symbol","title":"topBarTitle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/topBarTitle","abstract":[{"type":"text","text":"Title for the top bar."},{"text":" ","type":"text"},{"text":"Default is “Scan Item”","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topBarTitle"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"topBarTitle","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/findAndPickPartialAlertSubtitle":{"navigatorTitle":[{"text":"findAndPickPartialAlertSubtitle","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"findAndPickPartialAlertSubtitle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickPartialAlertSubtitle","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/findandpickpartialalertsubtitle","role":"symbol","abstract":[{"type":"text","text":"Subtitle for the find and pick partial alert."},{"type":"text","text":" "},{"type":"text","text":"Default is “Some codes are yet to be scanned. Proceed with submission anyway?”"}],"title":"findAndPickPartialAlertSubtitle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/manualCountEditDialogInfo":{"navigatorTitle":[{"text":"manualCountEditDialogInfo","kind":"identifier"}],"abstract":[{"text":"Info for the manual count edit dialog.","type":"text"},{"type":"text","text":" "},{"text":"Default is “Adjust the number of items you scanned.”","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"manualCountEditDialogInfo","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/manualcounteditdialoginfo","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/manualCountEditDialogInfo","kind":"symbol","title":"manualCountEditDialogInfo"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/multipleModeSheetTitle":{"abstract":[{"type":"text","text":"Title for the multiple mode barcode sheet."},{"text":" ","type":"text"},{"type":"text","text":"Default is “%d items”"}],"title":"multipleModeSheetTitle","navigatorTitle":[{"kind":"identifier","text":"multipleModeSheetTitle"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/multipleModeSheetTitle","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/multiplemodesheettitle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"multipleModeSheetTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/findAndPickPartialAlertSubmitButton":{"role":"symbol","abstract":[{"type":"text","text":"Submit button text for the find and pick partial alert."},{"text":" ","type":"text"},{"text":"Default is “Yes, Submit”","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"findAndPickPartialAlertSubmitButton"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"findAndPickPartialAlertSubmitButton","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickPartialAlertSubmitButton","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/findandpickpartialalertsubmitbutton","kind":"symbol","title":"findAndPickPartialAlertSubmitButton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/cameraPermissionEnableCameraExplanation":{"title":"cameraPermissionEnableCameraExplanation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/cameraPermissionEnableCameraExplanation","abstract":[{"text":"Explanation for the camera permission dialog.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is “Please allow the usage of the camera to start the scanning process.”"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/camerapermissionenablecameraexplanation","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraPermissionEnableCameraExplanation"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/hash":{"title":"hash","fragments":[{"text":"hash","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/hash","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/findAndPickCompleteAlertSubmitButton":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickCompleteAlertSubmitButton","title":"findAndPickCompleteAlertSubmitButton","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/findandpickcompletealertsubmitbutton","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"findAndPickCompleteAlertSubmitButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Submit button text for the find and pick complete alert."},{"type":"text","text":" "},{"type":"text","text":"Default is “Submit”"}],"navigatorTitle":[{"kind":"identifier","text":"findAndPickCompleteAlertSubmitButton"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/topBarCancelButton":{"title":"topBarCancelButton","abstract":[{"text":"Cancel button text for the top bar.","type":"text"},{"type":"text","text":" "},{"text":"Default is “Cancel”","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/topbarcancelbutton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarCancelButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"topBarCancelButton"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/topBarCancelButton","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/cameraPermissionEnableCameraButton":{"role":"symbol","abstract":[{"type":"text","text":"Button text for the camera permission dialog."},{"text":" ","type":"text"},{"text":"Default is “Grant permission”","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPermissionEnableCameraButton"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"cameraPermissionEnableCameraButton","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/cameraPermissionEnableCameraButton","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/camerapermissionenablecamerabutton","kind":"symbol","title":"cameraPermissionEnableCameraButton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/manualCountEditDialogUpdateButton":{"type":"topic","title":"manualCountEditDialogUpdateButton","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"manualCountEditDialogUpdateButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/manualCountEditDialogUpdateButton","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/manualcounteditdialogupdatebutton","abstract":[{"text":"Update button text for the manual count edit dialog.","type":"text"},{"type":"text","text":" "},{"text":"Default is “Update”","type":"text"}],"navigatorTitle":[{"text":"manualCountEditDialogUpdateButton","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/fromJsonWithJson:":{"type":"topic","role":"symbol","title":"fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"text":"fromJsonWithJson:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/fromjsonwithjson:","abstract":[],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/fromJsonWithJson:","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization":{"type":"topic","abstract":[{"type":"text","text":"Configuration of the all strings for barcode scanner."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"title":"SBSDKUI2BarcodeTextLocalization","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/barcodeInfoMappingErrorStateRetryButton":{"abstract":[{"type":"text","text":"Retry button text for the barcode info mapping error state."},{"type":"text","text":" "},{"type":"text","text":"Default is “Retry”"}],"type":"topic","title":"barcodeInfoMappingErrorStateRetryButton","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeInfoMappingErrorStateRetryButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingErrorStateRetryButton","navigatorTitle":[{"kind":"identifier","text":"barcodeInfoMappingErrorStateRetryButton"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/barcodeinfomappingerrorstateretrybutton","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/singleModeConfirmationCancelButton":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/singleModeConfirmationCancelButton","abstract":[{"text":"Cancel button text for the single mode confirmation dialog.","type":"text"},{"type":"text","text":" "},{"text":"Default is “Close”","type":"text"}],"title":"singleModeConfirmationCancelButton","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/singlemodeconfirmationcancelbutton","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"singleModeConfirmationCancelButton"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"singleModeConfirmationCancelButton","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"SBSDKUI2BarcodeTextLocalization","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingErrorStateCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingErrorStateRetryButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingErrorStateSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingErrorStateTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingLoadingMessage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/cameraPermissionCloseButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/cameraPermissionEnableCameraButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/cameraPermissionEnableCameraExplanation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/cameraPermissionEnableCameraTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickCompleteAlertCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickCompleteAlertSubmitButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickCompleteAlertSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickCompleteAlertTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickPartialAlertCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickPartialAlertSubmitButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickPartialAlertSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickPartialAlertTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickSheetBarcodeItemSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickSheetTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/manualCountEditDialogCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/manualCountEditDialogInfo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/manualCountEditDialogTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/manualCountEditDialogUpdateButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/multipleModeSheetTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetClearAllButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetPlaceholderSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetPlaceholderTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetResetButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetStartScanningButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetSubmitButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/singleModeConfirmationCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/topBarCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/topBarTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/userGuidance"],"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/toJson()"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true},{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/fromJsonWithJson:"]}]},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"},{"kind":"text","text":" : "},{"text":"SBSDKUI2Node","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:)\/title","value":"initWithCameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithCameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1init(cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:topBarCancelButton:topBarTitle:userGuidance:barcodeInfoMappingLoadingMessage:barcodeInfoMappingErrorStateTitle:barcodeInfoMappingErrorStateSubtitle:barcodeInfoMappingErrorStateRetryButton:barcodeInfoMappingErrorStateCancelButton:manualCountEditDialogTitle:manualCountEditDialogInfo:manualCountEditDialogUpdateButton:manualCountEditDialogCancelButton:sheetResetButton:sheetClearAllButton:sheetSubmitButton:sheetStartScanningButton:sheetPlaceholderTitle:sheetPlaceholderSubtitle:singleModeConfirmationCancelButton:multipleModeSheetTitle:findAndPickSheetTitle:findAndPickSheetBarcodeItemSubtitle:findAndPickPartialAlertTitle:findAndPickPartialAlertSubtitle:findAndPickPartialAlertCancelButton:findAndPickPartialAlertSubmitButton:findAndPickCompleteAlertTitle:findAndPickCompleteAlertSubtitle:findAndPickCompleteAlertCancelButton:findAndPickCompleteAlertSubmitButton:)\/fragments","op":"replace"},{"value":"findAndPickCompleteAlertCancelButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickCompleteAlertCancelButton\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickCompleteAlertCancelButton\/fragments","value":[{"text":"findAndPickCompleteAlertCancelButton","kind":"identifier"}],"op":"replace"},{"value":"barcodeInfoMappingErrorStateCancelButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1barcodeInfoMappingErrorStateCancelButton\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1barcodeInfoMappingErrorStateCancelButton\/fragments","value":[{"kind":"identifier","text":"barcodeInfoMappingErrorStateCancelButton"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1userGuidance\/title","value":"userGuidance"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1userGuidance\/fragments","value":[{"text":"userGuidance","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1sheetPlaceholderTitle\/title","value":"sheetPlaceholderTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1sheetPlaceholderTitle\/fragments","value":[{"text":"sheetPlaceholderTitle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1sheetPlaceholderSubtitle\/title","value":"sheetPlaceholderSubtitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1sheetPlaceholderSubtitle\/fragments","value":[{"kind":"identifier","text":"sheetPlaceholderSubtitle"}],"op":"replace"},{"op":"replace","value":"barcodeInfoMappingErrorStateSubtitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1barcodeInfoMappingErrorStateSubtitle\/title"},{"value":[{"text":"barcodeInfoMappingErrorStateSubtitle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1barcodeInfoMappingErrorStateSubtitle\/fragments"},{"op":"replace","value":"SBSDKUI2Node","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Node"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Node"}]},{"value":"sheetResetButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1sheetResetButton\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1sheetResetButton\/fragments","value":[{"kind":"identifier","text":"sheetResetButton"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1cameraPermissionEnableCameraTitle\/title","value":"cameraPermissionEnableCameraTitle"},{"op":"replace","value":[{"text":"cameraPermissionEnableCameraTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1cameraPermissionEnableCameraTitle\/fragments"},{"op":"replace","value":"manualCountEditDialogTitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1manualCountEditDialogTitle\/title"},{"op":"replace","value":[{"text":"manualCountEditDialogTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1manualCountEditDialogTitle\/fragments"},{"value":"findAndPickSheetBarcodeItemSubtitle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickSheetBarcodeItemSubtitle\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickSheetBarcodeItemSubtitle\/fragments","value":[{"text":"findAndPickSheetBarcodeItemSubtitle","kind":"identifier"}]},{"op":"replace","value":"toJson","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1toJson()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJson"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1toJson()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1cameraPermissionCloseButton\/title","value":"cameraPermissionCloseButton"},{"value":[{"text":"cameraPermissionCloseButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1cameraPermissionCloseButton\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickPartialAlertCancelButton\/title","value":"findAndPickPartialAlertCancelButton","op":"replace"},{"value":[{"text":"findAndPickPartialAlertCancelButton","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickPartialAlertCancelButton\/fragments"},{"op":"replace","value":"sheetClearAllButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1sheetClearAllButton\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1sheetClearAllButton\/fragments","value":[{"text":"sheetClearAllButton","kind":"identifier"}]},{"value":"findAndPickSheetTitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickSheetTitle\/title","op":"replace"},{"value":[{"text":"findAndPickSheetTitle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickSheetTitle\/fragments"},{"op":"replace","value":"manualCountEditDialogCancelButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1manualCountEditDialogCancelButton\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1manualCountEditDialogCancelButton\/fragments","value":[{"text":"manualCountEditDialogCancelButton","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1init()\/title","value":"init"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1init()\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1barcodeInfoMappingLoadingMessage\/title","value":"barcodeInfoMappingLoadingMessage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1barcodeInfoMappingLoadingMessage\/fragments","op":"replace","value":[{"kind":"identifier","text":"barcodeInfoMappingLoadingMessage"}]},{"value":"barcodeInfoMappingErrorStateTitle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1barcodeInfoMappingErrorStateTitle\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1barcodeInfoMappingErrorStateTitle\/fragments","value":[{"text":"barcodeInfoMappingErrorStateTitle","kind":"identifier"}],"op":"replace"},{"value":"findAndPickCompleteAlertTitle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickCompleteAlertTitle\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickCompleteAlertTitle\/fragments","value":[{"text":"findAndPickCompleteAlertTitle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickPartialAlertTitle\/title","value":"findAndPickPartialAlertTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickPartialAlertTitle\/fragments","op":"replace","value":[{"kind":"identifier","text":"findAndPickPartialAlertTitle"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1sheetSubmitButton\/title","value":"sheetSubmitButton","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1sheetSubmitButton\/fragments","value":[{"kind":"identifier","text":"sheetSubmitButton"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickCompleteAlertSubtitle\/title","value":"findAndPickCompleteAlertSubtitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickCompleteAlertSubtitle\/fragments","op":"replace","value":[{"text":"findAndPickCompleteAlertSubtitle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1sheetStartScanningButton\/title","value":"sheetStartScanningButton","op":"replace"},{"value":[{"text":"sheetStartScanningButton","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1sheetStartScanningButton\/fragments"},{"value":"topBarTitle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1topBarTitle\/title"},{"value":[{"kind":"identifier","text":"topBarTitle"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1topBarTitle\/fragments"},{"op":"replace","value":"findAndPickPartialAlertSubtitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickPartialAlertSubtitle\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickPartialAlertSubtitle\/fragments","value":[{"text":"findAndPickPartialAlertSubtitle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1manualCountEditDialogInfo\/title","value":"manualCountEditDialogInfo","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1manualCountEditDialogInfo\/fragments","value":[{"text":"manualCountEditDialogInfo","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1multipleModeSheetTitle\/title","value":"multipleModeSheetTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1multipleModeSheetTitle\/fragments","value":[{"text":"multipleModeSheetTitle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickPartialAlertSubmitButton\/title","op":"replace","value":"findAndPickPartialAlertSubmitButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickPartialAlertSubmitButton\/fragments","value":[{"kind":"identifier","text":"findAndPickPartialAlertSubmitButton"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1cameraPermissionEnableCameraExplanation\/title","value":"cameraPermissionEnableCameraExplanation"},{"value":[{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1cameraPermissionEnableCameraExplanation\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickCompleteAlertSubmitButton\/title","op":"replace","value":"findAndPickCompleteAlertSubmitButton"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickCompleteAlertSubmitButton\/fragments","value":[{"kind":"identifier","text":"findAndPickCompleteAlertSubmitButton"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1topBarCancelButton\/title","value":"topBarCancelButton"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1topBarCancelButton\/fragments","value":[{"text":"topBarCancelButton","kind":"identifier"}]},{"value":"cameraPermissionEnableCameraButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1cameraPermissionEnableCameraButton\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1cameraPermissionEnableCameraButton\/fragments","value":[{"kind":"identifier","text":"cameraPermissionEnableCameraButton"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1manualCountEditDialogUpdateButton\/title","value":"manualCountEditDialogUpdateButton"},{"value":[{"kind":"identifier","text":"manualCountEditDialogUpdateButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1manualCountEditDialogUpdateButton\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/title","value":"SBSDKUI2BarcodeTextLocalization","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/navigatorTitle"},{"value":"barcodeInfoMappingErrorStateRetryButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1barcodeInfoMappingErrorStateRetryButton\/title"},{"value":[{"kind":"identifier","text":"barcodeInfoMappingErrorStateRetryButton"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1barcodeInfoMappingErrorStateRetryButton\/fragments"},{"value":"singleModeConfirmationCancelButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1singleModeConfirmationCancelButton\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1singleModeConfirmationCancelButton\/fragments","value":[{"text":"singleModeConfirmationCancelButton","kind":"identifier"}]}]}]}