{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVARegistrationData","symbolKind":"class","roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVARegistrationData"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentAAMVARegistrationData","kind":"identifier"}],"title":"SBSDKBarcodeDocumentAAMVARegistrationData"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVARegistrationData"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Registration Data. File type “RG”."}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/addressCity","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/addressJurisdictionCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/addressStreet","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/addressZipCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/axles","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/businessName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/fuel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/grossVehicleWeight","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrantFamilyName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrantGivenName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrationExpiryDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrationIssueDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrationPlateNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrationWindowStickerDecal","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrationYear","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleBodyStyle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleIdentificationNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleMake","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleModel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleModelYear","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleUse"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/initWithGenericDocument:":{"navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/initwithgenericdocument:","role":"symbol","title":"initWithGenericDocument:","kind":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/initWithGenericDocument:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/addressStreet":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"addressStreet"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addressStreet"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/addressStreet","abstract":[{"type":"text","text":"Data element ID “RBI”. Street portion of the owner’s address."}],"title":"addressStreet","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/addressstreet"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/registrationIssueDate":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/registrationissuedate","kind":"symbol","navigatorTitle":[{"text":"registrationIssueDate","kind":"identifier"}],"abstract":[{"text":"Data element ID “RBB”. The date in which the registration was issued. The format is ISO8601 with delimiters.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrationIssueDate","title":"registrationIssueDate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registrationIssueDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","title":"SBSDKGenericDocument","type":"topic","abstract":[{"type":"text","text":"Represents a generic document with fields and sub-documents used for document recognition."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/vehicleModelYear":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/vehiclemodelyear","abstract":[{"text":"Data element ID “VAL”. The year which is assigned to a vehicle by the manufacturer. The format is CCYY.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vehicleModelYear"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"title":"vehicleModelYear","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"vehicleModelYear"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleModelYear"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/registrationPlateNumber":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrationPlateNumber","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/registrationplatenumber","kind":"symbol","role":"symbol","type":"topic","title":"registrationPlateNumber","navigatorTitle":[{"kind":"identifier","text":"registrationPlateNumber"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"registrationPlateNumber","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"text":"Data element ID “RAM”. The characters assigned to a registration plate or tag affixed to the vehicle, assigned by the jurisdiction.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/addressZipCode":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/addresszipcode","navigatorTitle":[{"kind":"identifier","text":"addressZipCode"}],"title":"addressZipCode","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addressZipCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/addressZipCode","abstract":[{"type":"text","text":"Data element ID “RBM”. The Zip code or Postal code of the vehicle owner’s residence address."}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/axles":{"navigatorTitle":[{"kind":"identifier","text":"axles"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/axles","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"axles","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"text":"Data element ID “VBC”. The number of common axles of rotation of one or more wheels of a vehicle, whether power driven or freely rotating.","type":"text"}],"role":"symbol","kind":"symbol","title":"axles","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/axles","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/grossVehicleWeight":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/grossvehicleweight","abstract":[{"type":"text","text":"Data element ID “VAT”. The unladen weight of the vehicle (e.g., the single-unit truck, truck combination) plus the weight of the load being carried at a specific point in time."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"grossVehicleWeight"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"title":"grossVehicleWeight","role":"symbol","navigatorTitle":[{"text":"grossVehicleWeight","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/grossVehicleWeight"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/vehicleMake":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/vehiclemake","abstract":[{"text":"Data element ID “VAK”. The distinctive (coded) name applied to a group of vehicles by a manufacturer.","type":"text"}],"navigatorTitle":[{"text":"vehicleMake","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleMake","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"vehicleMake","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"title":"vehicleMake"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/vehicleModel":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleModel","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"vehicleModel"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"vehicleModel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/vehiclemodel","kind":"symbol","title":"vehicleModel","abstract":[{"type":"text","text":"Data element ID “VAM”. A code denoting a family of vehicles (within a make), which has a degree of similarity in construction, such as body, chassis, etc. The field does not necessarily contain a standard code; it may contain a value provided by the originator of the field."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/fuel":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/fuel","abstract":[{"text":"Data element ID “FUL”. The type of fuel used by the vehicle. In most cases, the fuel type would be diesel.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fuel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"title":"fuel","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fuel"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/fuel"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/registrationWindowStickerDecal":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/registrationwindowstickerdecal","title":"registrationWindowStickerDecal","navigatorTitle":[{"kind":"identifier","text":"registrationWindowStickerDecal"}],"abstract":[{"type":"text","text":"Data element ID “RBU”. A unique number printed on the tab\/decal and stored as part of the registration record."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"registrationWindowStickerDecal","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrationWindowStickerDecal"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/vehicleColor":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vehicleColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"vehicleColor","abstract":[{"type":"text","text":"Data element ID “VBD”. Where the vehicle is one color, this is the appropriate code describing that color. When the vehicle is two colors, this is the code for the top-most or front-most color."}],"navigatorTitle":[{"text":"vehicleColor","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleColor","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/vehiclecolor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/vehicleIdentificationNumber":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/vehicleidentificationnumber","navigatorTitle":[{"kind":"identifier","text":"vehicleIdentificationNumber"}],"title":"vehicleIdentificationNumber","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleIdentificationNumber","role":"symbol","abstract":[{"type":"text","text":"Data element ID “VAD”. A unique combination of alphanumeric characters that identifies a specific vehicle or component. The VIN is affixed to the vehicle in specific locations and formulated by the manufacturer. State agencies under some controlled instances my assign a VIN to a vehicle."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vehicleIdentificationNumber","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/businessName":{"title":"businessName","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/businessName","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/businessname","role":"symbol","navigatorTitle":[{"text":"businessName","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"businessName"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Data element ID “BBC”. The business name of the first registrant of a vehicle."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/registrantFamilyName":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/registrantfamilyname","abstract":[{"type":"text","text":"Data element ID “RBD”. Family name (commonly called surname or last name) of the registered owner of a vehicle."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registrantFamilyName"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"title":"registrantFamilyName","role":"symbol","navigatorTitle":[{"text":"registrantFamilyName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrantFamilyName"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/registrationExpiryDate":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registrationExpiryDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"registrationExpiryDate"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrationExpiryDate","abstract":[{"text":"Data element ID “RAG”. The date in which the registration expired. The format is ISO8601 with delimiters.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/registrationexpirydate","title":"registrationExpiryDate","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/registrationYear":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/registrationyear","title":"registrationYear","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrationYear","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registrationYear"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"registrationYear"}],"abstract":[{"type":"text","text":"Data element ID “RBT”. The year of registration."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentWrapper":{"navigatorTitle":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","title":"SBSDKGenericDocumentWrapper","type":"topic","abstract":[{"type":"text","text":"Base class for strongly-typed "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"},{"text":" wrappers.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/addressJurisdictionCode":{"type":"topic","role":"symbol","title":"addressJurisdictionCode","abstract":[{"type":"text","text":"Data element ID “RBL”. Jurisdiction portion of the owner’s address."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/addressJurisdictionCode","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressJurisdictionCode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"addressJurisdictionCode"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/addressjurisdictioncode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData":{"abstract":[{"text":"Registration Data. File type “RG”.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVARegistrationData"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVARegistrationData"}],"kind":"symbol","title":"SBSDKBarcodeDocumentAAMVARegistrationData"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/vehicleBodyStyle":{"type":"topic","abstract":[{"type":"text","text":"Data element ID “VAO”. The general configuration or shape of a vehicle distinguished by characteristics such as number of doors, seats, windows, roofline, and type of top. The vehicle body type is 2-character alphanumeric."}],"title":"vehicleBodyStyle","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleBodyStyle","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/vehiclebodystyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vehicleBodyStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"vehicleBodyStyle","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/requiredDocumentType":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/requireddocumenttype","abstract":[{"type":"text","text":"The name of the wrapped document type."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/requiredDocumentType","navigatorTitle":[{"text":"requiredDocumentType","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"requiredDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","title":"requiredDocumentType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/vehicleUse":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vehicleUse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"vehicleUse"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleUse","abstract":[{"type":"text","text":"Data element ID “VPC”. Indicates the use of the vehicle."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/vehicleuse","title":"vehicleUse","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/addressCity":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/addresscity","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addressCity"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"addressCity"}],"abstract":[{"type":"text","text":"Data element ID “RBK”. City portion of the owner’s address."}],"title":"addressCity","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/addressCity"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVARegistrationData/registrantGivenName":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registrantGivenName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"registrantGivenName","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrantGivenName","abstract":[{"type":"text","text":"Data element ID “RBE”. Given name or names (includes all of what are commonly referred to as first and middle names) of the registered owner of a vehicle."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvaregistrationdata\/registrantgivenname","title":"registrantGivenName","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKBarcodeDocumentAAMVARegistrationData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVARegistrationData"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVARegistrationData"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/addressCity","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/addressJurisdictionCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/addressStreet","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/addressZipCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/axles","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/businessName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/fuel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/grossVehicleWeight","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrantFamilyName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrantGivenName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrationExpiryDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrationIssueDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrationPlateNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrationWindowStickerDecal","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/registrationYear","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleBodyStyle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleIdentificationNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleMake","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleModel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleModelYear","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/vehicleUse"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVARegistrationData\/initWithGenericDocument:"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"],"type":"inheritsFrom","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVARegistrationData"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentWrapper","text":"SBSDKGenericDocumentWrapper"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"addressStreet","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1addressStreet\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1addressStreet\/fragments","value":[{"kind":"identifier","text":"addressStreet"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1registrationIssueDate\/title","op":"replace","value":"registrationIssueDate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1registrationIssueDate\/fragments","value":[{"text":"registrationIssueDate","kind":"identifier"}]},{"value":"SBSDKGenericDocument","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1vehicleModelYear\/title","value":"vehicleModelYear"},{"value":[{"kind":"identifier","text":"vehicleModelYear"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1vehicleModelYear\/fragments","op":"replace"},{"op":"replace","value":"registrationPlateNumber","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1registrationPlateNumber\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1registrationPlateNumber\/fragments","value":[{"text":"registrationPlateNumber","kind":"identifier"}],"op":"replace"},{"value":"addressZipCode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1addressZipCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1addressZipCode\/fragments","value":[{"kind":"identifier","text":"addressZipCode"}]},{"value":"axles","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1axles\/title"},{"value":[{"text":"axles","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1axles\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1grossVehicleWeight\/title","value":"grossVehicleWeight"},{"op":"replace","value":[{"text":"grossVehicleWeight","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1grossVehicleWeight\/fragments"},{"value":"vehicleMake","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1vehicleMake\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1vehicleMake\/fragments","op":"replace","value":[{"kind":"identifier","text":"vehicleMake"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1vehicleModel\/title","value":"vehicleModel"},{"op":"replace","value":[{"kind":"identifier","text":"vehicleModel"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1vehicleModel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1fuel\/title","value":"fuel"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1fuel\/fragments","value":[{"kind":"identifier","text":"fuel"}]},{"value":"registrationWindowStickerDecal","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1registrationWindowStickerDecal\/title","op":"replace"},{"op":"replace","value":[{"text":"registrationWindowStickerDecal","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1registrationWindowStickerDecal\/fragments"},{"value":"vehicleColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1vehicleColor\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1vehicleColor\/fragments","op":"replace","value":[{"kind":"identifier","text":"vehicleColor"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1vehicleIdentificationNumber\/title","value":"vehicleIdentificationNumber","op":"replace"},{"value":[{"kind":"identifier","text":"vehicleIdentificationNumber"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1vehicleIdentificationNumber\/fragments"},{"value":"businessName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1businessName\/title"},{"op":"replace","value":[{"kind":"identifier","text":"businessName"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1businessName\/fragments"},{"op":"replace","value":"registrantFamilyName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1registrantFamilyName\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1registrantFamilyName\/fragments","value":[{"kind":"identifier","text":"registrantFamilyName"}]},{"value":"registrationExpiryDate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1registrationExpiryDate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1registrationExpiryDate\/fragments","value":[{"text":"registrationExpiryDate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1registrationYear\/title","op":"replace","value":"registrationYear"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1registrationYear\/fragments","op":"replace","value":[{"kind":"identifier","text":"registrationYear"}]},{"value":"SBSDKGenericDocumentWrapper","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/fragments"},{"value":"addressJurisdictionCode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1addressJurisdictionCode\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1addressJurisdictionCode\/fragments","value":[{"text":"addressJurisdictionCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData\/title","op":"replace","value":"SBSDKBarcodeDocumentAAMVARegistrationData"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVARegistrationData"}]},{"op":"replace","value":"vehicleBodyStyle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1vehicleBodyStyle\/title"},{"value":[{"text":"vehicleBodyStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1vehicleBodyStyle\/fragments"},{"value":"requiredDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1requiredDocumentType\/title","op":"replace"},{"value":[{"text":"requiredDocumentType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1requiredDocumentType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1vehicleUse\/title","value":"vehicleUse"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1vehicleUse\/fragments","value":[{"kind":"identifier","text":"vehicleUse"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1addressCity\/title","value":"addressCity","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1addressCity\/fragments","value":[{"text":"addressCity","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1registrantGivenName\/title","value":"registrantGivenName","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVARegistrationData~1registrantGivenName\/fragments","value":[{"kind":"identifier","text":"registrantGivenName"}]}]}]}