{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult"]}],"abstract":[{"type":"text","text":"Represents a result of the "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer","type":"reference"},{"type":"text","text":"."}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextLayoutRecognizerResult","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Contains the page orientation, the writing direction, the text line order and the de-skew angle."},{"type":"text","text":" "},{"text":"This result can be used to process the input image before running an OCR operation on it, e.g.","type":"text"}]}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/init(orientation:writingDirection:textlineOrder:deskewAngle:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/deskewAngle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/orientation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/textlineOrder","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/writingDirection"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"SBSDKTextLayoutRecognizerResult","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTextLayoutRecognizerResult"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult","title":"SBSDKTextLayoutRecognizerResult"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizerResult":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTextLayoutRecognizerResult"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTextLayoutRecognizerResult"}],"title":"SBSDKTextLayoutRecognizerResult","abstract":[{"type":"text","text":"Represents a result of the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult","type":"topic"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizerResult/init(orientation:writingDirection:textlineOrder:deskewAngle:)":{"abstract":[{"type":"text","text":"Designated initializer."}],"navigatorTitle":[{"kind":"identifier","text":"initWithOrientation:writingDirection:textlineOrder:deskewAngle:"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/init(orientation:writingDirection:textlineOrder:deskewAngle:)","title":"init(orientation:writingDirection:textlineOrder:deskewAngle:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextOrientation","text":"SBSDKTextOrientation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"writingDirection"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKWritingDirection","text":"SBSDKWritingDirection"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textlineOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextlineOrder","text":"SBSDKTextlineOrder"},{"kind":"text","text":", "},{"text":"deskewAngle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult\/init(orientation:writingdirection:textlineorder:deskewangle:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizerResult/textlineOrder":{"abstract":[{"text":"The order of text lines.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"textlineOrder"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/textlineOrder","title":"textlineOrder","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"textlineOrder","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextlineOrder","text":"SBSDKTextlineOrder"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult\/textlineorder"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizerResult/deskewAngle":{"abstract":[{"type":"text","text":"The angle in radians the image needs to be rotated to achieve perfectly aligned text lines."}],"navigatorTitle":[{"text":"deskewAngle","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/deskewAngle","title":"deskewAngle","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"deskewAngle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult\/deskewangle"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizerResult/writingDirection":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"writingDirection","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKWritingDirection","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKWritingDirection"}],"navigatorTitle":[{"text":"writingDirection","kind":"identifier"}],"title":"writingDirection","abstract":[{"type":"text","text":"The writing direction of the text lines in the image."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult\/writingdirection","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/writingDirection","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizer":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}],"title":"SBSDKTextLayoutRecognizer","abstract":[{"type":"text","text":"Analyzes an image and returns basic text layout features."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizerResult/copyWithZone:":{"abstract":[],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/copyWithZone:","title":"copyWithZone:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult\/copywithzone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizerResult/orientation":{"abstract":[{"text":"The general orientation of the text in the image.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"orientation"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/orientation","title":"orientation","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"orientation","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKTextOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextOrientation"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult\/orientation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKTextLayoutRecognizerResult","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKTextLayoutRecognizerResult"}]},{"value":[{"kind":"identifier","text":"SBSDKTextLayoutRecognizerResult"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/deskewAngle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/orientation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/textlineOrder","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/writingDirection"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/init(orientation:writingDirection:textlineOrder:deskewAngle:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"title":"Conforms To"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKTextLayoutRecognizerResult","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]}},{"value":"SBSDKTextLayoutRecognizerResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKTextLayoutRecognizerResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult~1init(orientation:writingDirection:textlineOrder:deskewAngle:)\/title","value":"initWithOrientation:writingDirection:textlineOrder:deskewAngle:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult~1init(orientation:writingDirection:textlineOrder:deskewAngle:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithOrientation:writingDirection:textlineOrder:deskewAngle:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult~1textlineOrder\/title","value":"textlineOrder","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult~1textlineOrder\/fragments","op":"replace","value":[{"text":"textlineOrder","kind":"identifier"}]},{"op":"replace","value":"deskewAngle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult~1deskewAngle\/title"},{"op":"replace","value":[{"kind":"identifier","text":"deskewAngle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult~1deskewAngle\/fragments"},{"op":"replace","value":"writingDirection","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult~1writingDirection\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult~1writingDirection\/fragments","value":[{"text":"writingDirection","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/title","op":"replace","value":"SBSDKTextLayoutRecognizer"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/fragments","value":[{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}]},{"op":"replace","value":"orientation","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult~1orientation\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult~1orientation\/fragments","value":[{"text":"orientation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}