{"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration"],"type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerTextConfiguration\/cancelButtonTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerTextConfiguration\/flashButtonTitle"],"title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUITextDataScannerTextConfiguration","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerTextConfiguration"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"sections":[],"abstract":[{"text":"Configuration for the textual contents of the RTU-UI text data scanner.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannertextconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannertextconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUITextDataScannerTextConfiguration","kind":"identifier"}],"symbolKind":"class","navigatorTitle":[{"text":"SBSDKUITextDataScannerTextConfiguration","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerTextConfiguration","roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKUITextDataScannerTextConfiguration"},"references":{"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerTextConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerTextConfiguration","abstract":[{"type":"text","text":"Configuration for the textual contents of the RTU-UI text data scanner."}],"role":"symbol","title":"SBSDKUITextDataScannerTextConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUITextDataScannerTextConfiguration"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUITextDataScannerTextConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannertextconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerTextConfiguration/cancelButtonTitle":{"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannertextconfiguration\/cancelbuttontitle","abstract":[{"text":"String being displayed on the cancel button.","type":"text"}],"role":"symbol","title":"cancelButtonTitle","navigatorTitle":[{"kind":"identifier","text":"cancelButtonTitle"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cancelButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerTextConfiguration\/cancelButtonTitle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIEnableCameraTextConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuienablecameratextconfiguration","title":"SBSDKUIEnableCameraTextConfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration for the textual contents of camera based view controllers."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerTextConfiguration/flashButtonTitle":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"flashButtonTitle"}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannertextconfiguration\/flashbuttontitle","role":"symbol","abstract":[{"text":"String being displayed on the flash button.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerTextConfiguration\/flashButtonTitle","title":"flashButtonTitle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"flashButtonTitle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerTextConfiguration/init":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannertextconfiguration\/init","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerTextConfiguration\/init","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUITextDataScannerTextConfiguration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKUITextDataScannerTextConfiguration","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUITextDataScannerTextConfiguration"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerTextConfiguration\/cancelButtonTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerTextConfiguration\/flashButtonTitle"],"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerTextConfiguration\/init"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration"]}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUITextDataScannerTextConfiguration"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIEnableCameraTextConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration","text":"SBSDKUIEnableCameraTextConfiguration"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerTextConfiguration\/title","value":"SBSDKUITextDataScannerTextConfiguration","op":"replace"},{"value":[{"text":"SBSDKUITextDataScannerTextConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerTextConfiguration\/fragments"},{"op":"replace","value":"cancelButtonTitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerTextConfiguration~1cancelButtonTitle\/title"},{"value":[{"kind":"identifier","text":"cancelButtonTitle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerTextConfiguration~1cancelButtonTitle\/fragments","op":"replace"},{"op":"replace","value":"SBSDKUIEnableCameraTextConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/fragments"},{"value":"flashButtonTitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerTextConfiguration~1flashButtonTitle\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerTextConfiguration~1flashButtonTitle\/fragments","value":[{"text":"flashButtonTitle","kind":"identifier"}]}]}]}