{"kind":"symbol","relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitMode"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageFitMode","title":"SBSDKPDFRendererPageFitMode","roleHeading":"Enumeration","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPDFRendererPageFitMode"}]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/fillIn","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/fitIn","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/none","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/stretch"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/RawRepresentable-Implementations"]}],"sections":[],"abstract":[{"type":"text","text":"An enum describing the mode of how images are fitted into a PDF page."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode","title":"SBSDKPDFRendererPageFitMode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFRendererPageFitMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode","type":"topic","abstract":[{"text":"An enum describing the mode of how images are fitted into a PDF page.","type":"text"}]},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode/RawRepresentable-Implementations":{"kind":"article","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/rawrepresentable-implementations","type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode/stretch":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stretch","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPDFRendererPageFitModeStretch","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/stretch","role":"symbol","type":"topic","kind":"symbol","title":"SBSDKPDFRendererPageFitMode.stretch","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/stretch"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode/init(rawValue:)":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/init(rawValue:)","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/init(rawvalue:)","role":"symbol","title":"init(rawValue:)","abstract":[],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode/Equatable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/equatable-implementations","abstract":[],"title":"Equatable Implementations","role":"collectionGroup","type":"topic","kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/Equatable-Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode/none":{"title":"SBSDKPDFRendererPageFitMode.none","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitModeNone"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/none","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/none","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode/fillIn":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"fillIn","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/fillin","navigatorTitle":[{"text":"SBSDKPDFRendererPageFitModeFillIn","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/fillIn","title":"SBSDKPDFRendererPageFitMode.fillIn"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode/fitIn":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitModeFitIn"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/fitin","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fitIn","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"SBSDKPDFRendererPageFitMode.fitIn","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/fitIn"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKPDFRendererPageFitMode"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitMode"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/fillIn","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/fitIn","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/none","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/stretch"],"title":"Enumeration Cases"}]},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPDFRendererPageFitMode"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode\/title","op":"replace","value":"SBSDKPDFRendererPageFitMode"},{"value":[{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode~1stretch\/title","op":"replace","value":"SBSDKPDFRendererPageFitModeStretch"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode~1stretch\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitModeStretch"}],"op":"replace"},{"value":"SBSDKPDFRendererPageFitModeNone","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode~1none\/title"},{"value":[{"text":"SBSDKPDFRendererPageFitModeNone","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode~1none\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode~1fillIn\/title","value":"SBSDKPDFRendererPageFitModeFillIn"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode~1fillIn\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitModeFillIn"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode~1fitIn\/title","op":"replace","value":"SBSDKPDFRendererPageFitModeFitIn"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode~1fitIn\/fragments","value":[{"text":"SBSDKPDFRendererPageFitModeFitIn","kind":"identifier"}]}]}]}