{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewControllerDelegate","interfaceLanguage":"swift"},"abstract":[{"text":"Delegate protocol for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewController"},{"type":"text","text":"."}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewControllerDelegate\/vinScannerViewController(_:didFinishWith:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewControllerDelegate\/vinScannerViewControllerDidCancel(_:)"],"title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIVINScannerViewControllerDelegate"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate","text":"SBSDKUIViewControllerDelegate","kind":"typeIdentifier"}]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscannerviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscannerviewcontrollerdelegate"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate"],"type":"inheritsFrom"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"title":"SBSDKUIVINScannerViewControllerDelegate","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUIVINScannerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIVINScannerViewControllerDelegate"}],"symbolKind":"protocol","role":"symbol","roleHeading":"Protocol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIVINScannerViewControllerDelegate"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerViewControllerDelegate/vinScannerViewController(_:didFinishWith:)":{"title":"vinScannerViewController(_:didFinishWith:)","url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerviewcontrollerdelegate\/vinscannerviewcontroller(_:didfinishwith:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"vinScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerViewController","text":"SBSDKUIVINScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerResult","text":"SBSDKVehicleIdentificationNumberScannerResult"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewControllerDelegate\/vinScannerViewController(_:didFinishWith:)","role":"symbol","abstract":[{"type":"text","text":"Informs the delegate that the vehicle identification number has been scanned and validated."}],"required":true,"navigatorTitle":[{"text":"vinScannerViewController:didFinishWithResult:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIVINScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerviewcontroller","kind":"symbol","title":"SBSDKUIVINScannerViewController","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to recognize and validate vehicle identification numbers in realtime."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewController","role":"symbol","navigatorTitle":[{"text":"SBSDKUIVINScannerViewController","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerViewControllerDelegate/vinScannerViewControllerDidCancel(_:)":{"title":"vinScannerViewControllerDidCancel(_:)","url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerviewcontrollerdelegate\/vinscannerviewcontrollerdidcancel(_:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"vinScannerViewControllerDidCancel"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerViewController","text":"SBSDKUIVINScannerViewController"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewControllerDelegate\/vinScannerViewControllerDidCancel(_:)","role":"symbol","abstract":[{"text":"Informs the delegate that the ‘SBSDKUIVINScannerViewController’ has been cancelled and dismissed.","type":"text"}],"navigatorTitle":[{"text":"vinScannerViewControllerDidCancel:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerViewControllerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIVINScannerViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerviewcontrollerdelegate","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewControllerDelegate","abstract":[{"type":"text","text":"Delegate protocol for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewController"},{"text":".","type":"text"}],"title":"SBSDKUIVINScannerViewControllerDelegate","role":"symbol","navigatorTitle":[{"text":"SBSDKUIVINScannerViewControllerDelegate","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewControllerDelegate":{"url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontrollerdelegate","abstract":[{"type":"text","text":"The general delegate protocol for "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","isActive":true},{"text":"-based classes.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate","kind":"symbol","title":"SBSDKUIViewControllerDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIViewControllerDelegate"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewController":{"abstract":[{"text":"An abstract base class for RTU-UI view controllers.","type":"text"}],"title":"SBSDKUIViewController","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIViewController"}],"navigatorTitle":[{"text":"SBSDKUIViewController","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUIVINScannerViewControllerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIVINScannerViewControllerDelegate"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIVINScannerViewControllerDelegate"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewControllerDelegate\/vinScannerViewController(_:didFinishWith:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewControllerDelegate\/vinScannerViewControllerDidCancel(_:)"]}]},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"SBSDKUIVINScannerViewControllerDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate","text":"SBSDKUIViewControllerDelegate","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"}},{"value":"vinScannerViewController:didFinishWithResult:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewControllerDelegate~1vinScannerViewController(_:didFinishWith:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"vinScannerViewController:didFinishWithResult:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewControllerDelegate~1vinScannerViewController(_:didFinishWith:)\/fragments","op":"replace"},{"op":"replace","value":"SBSDKUIVINScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKUIVINScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewControllerDelegate~1vinScannerViewControllerDidCancel(_:)\/title","value":"vinScannerViewControllerDidCancel:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewControllerDelegate~1vinScannerViewControllerDidCancel(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"vinScannerViewControllerDidCancel:","kind":"identifier"}]},{"op":"replace","value":"SBSDKUIVINScannerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUIVINScannerViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewControllerDelegate\/title","value":"SBSDKUIViewControllerDelegate"},{"value":[{"text":"SBSDKUIViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewControllerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/title","value":"SBSDKUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/fragments","value":[{"text":"SBSDKUIViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}