{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate","interfaceLanguage":"swift"},"abstract":[{"text":"A delegate protocol to inform an object about changes in ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","type":"reference"},{"text":".","type":"text"}],"relationshipsSections":[{"title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController"],"type":"conformingTypes"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"role":"symbol","roleHeading":"Protocol","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKImageEditingViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}],"symbolKind":"protocol","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKImageEditingViewControllerDelegate"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewController(_:didApplyChangesWith:croppedImage:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerApplyButtonItem(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerCancelButtonItem(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerDidCancelChanges(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerDidChangePolygon(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerRotateClockwiseToolbarItem(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarItemTintColor(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarStyle(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarTintColor(_:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerDidCancelChanges(_:)":{"role":"symbol","abstract":[{"type":"text","text":"Informs the delegate that the image editing view controllers cancel button was hit."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"imageEditingViewControllerDidCancelChanges","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerDidCancelChanges(_:)","url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerdidcancelchanges(_:)","navigatorTitle":[{"text":"imageEditingViewControllerDidCancelChanges:","kind":"identifier"}],"kind":"symbol","type":"topic","title":"imageEditingViewControllerDidCancelChanges(_:)","required":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerDidChangePolygon(_:)":{"role":"symbol","abstract":[{"text":"Informs the delegate that the image editing view controllers polygon was changed by user interaction.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerDidChangePolygon"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerDidChangePolygon(_:)","url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerdidchangepolygon(_:)","navigatorTitle":[{"text":"imageEditingViewControllerDidChangePolygon:","kind":"identifier"}],"kind":"symbol","type":"topic","title":"imageEditingViewControllerDidChangePolygon(_:)","required":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingViewController":{"abstract":[{"text":"A highly customizable view controller to edit a pages polygon or the page’s orientation.","type":"text"}],"title":"SBSDKUICroppingViewController","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUICroppingViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewController(_:didApplyChangesWith:croppedImage:)":{"abstract":[{"type":"text","text":"Informs the delegate that the image editing view controllers apply button was hit."}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageEditingViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController"},{"kind":"text","text":", "},{"text":"didApplyChangesWith","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"croppedImage"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"imageEditingViewController:didApplyChangesWith:croppedImage:","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewController(_:didApplyChangesWith:croppedImage:)","kind":"symbol","title":"imageEditingViewController(_:didApplyChangesWith:croppedImage:)","url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontroller(_:didapplychangeswith:croppedimage:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerrotatecounterclockwisetoolbaritem(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKImageEditingViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIBarButtonItem","kind":"typeIdentifier","text":"UIBarButtonItem"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)","type":"topic","abstract":[{"type":"text","text":"Asks the delegate for a "},{"type":"codeVoice","code":"UIBarButtonItem"},{"text":" to for rotating the image counter-clockwise.","type":"text"}],"title":"imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerToolbarTintColor(_:)":{"abstract":[{"text":"Asks the delegate for the background tint color of the bottom toolbar.","type":"text"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageEditingViewControllerToolbarTintColor"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","kind":"typeIdentifier","text":"SBSDKImageEditingViewController"},{"kind":"text","text":") -> "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"imageEditingViewControllerToolbarTintColor:","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarTintColor(_:)","kind":"symbol","title":"imageEditingViewControllerToolbarTintColor(_:)","url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollertoolbartintcolor(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerCancelButtonItem(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollercancelbuttonitem(_:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"imageEditingViewControllerCancelButtonItem","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKImageEditingViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController"},{"text":") -> ","kind":"text"},{"text":"UIBarButtonItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerCancelButtonItem:"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerCancelButtonItem(_:)","type":"topic","abstract":[{"text":"Asks the delegate for a ","type":"text"},{"code":"UIBarButtonItem","type":"codeVoice"},{"text":" to cancel the actual editing.","type":"text"}],"title":"imageEditingViewControllerCancelButtonItem(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate":{"type":"topic","kind":"symbol","abstract":[{"text":"A delegate protocol to inform an object about changes in ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","type":"reference","isActive":true},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate","title":"SBSDKImageEditingViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerApplyButtonItem(_:)":{"abstract":[{"text":"Asks the delegate for a `UIBarButtonItem to apply the actual editing.","type":"text"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageEditingViewControllerApplyButtonItem"},{"kind":"text","text":"("},{"text":"SBSDKImageEditingViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController"},{"text":") -> ","kind":"text"},{"text":"UIBarButtonItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"imageEditingViewControllerApplyButtonItem:","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerApplyButtonItem(_:)","kind":"symbol","title":"imageEditingViewControllerApplyButtonItem(_:)","url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerapplybuttonitem(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerToolbarStyle(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollertoolbarstyle(_:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageEditingViewControllerToolbarStyle"},{"kind":"text","text":"("},{"text":"SBSDKImageEditingViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController"},{"text":") -> ","kind":"text"},{"text":"UIBarStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarStyle"}],"navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerToolbarStyle:"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarStyle(_:)","type":"topic","abstract":[{"type":"text","text":"Asks the delegate for a "},{"code":"UIBarStyle","type":"codeVoice"},{"type":"text","text":" for the bottom toolbar."}],"title":"imageEditingViewControllerToolbarStyle(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewController":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"title":"SBSDKImageEditingViewController","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to show and edit an image.","type":"text"}],"navigatorTitle":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerRotateClockwiseToolbarItem(_:)":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Asks the delegate for a "},{"type":"codeVoice","code":"UIBarButtonItem"},{"text":" to for rotating the image clockwise.","type":"text"}],"required":true,"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerrotateclockwisetoolbaritem(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageEditingViewControllerRotateClockwiseToolbarItem"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBarButtonItem","text":"UIBarButtonItem","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerRotateClockwiseToolbarItem(_:)","title":"imageEditingViewControllerRotateClockwiseToolbarItem(_:)","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerRotateClockwiseToolbarItem:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerToolbarItemTintColor(_:)":{"abstract":[{"type":"text","text":"Asks the delegate for the item tint color of the bottom toolbar."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageEditingViewControllerToolbarItemTintColor"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"imageEditingViewControllerToolbarItemTintColor:","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarItemTintColor(_:)","kind":"symbol","title":"imageEditingViewControllerToolbarItemTintColor(_:)","url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollertoolbaritemtintcolor(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKImageEditingViewControllerDelegate"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewController(_:didApplyChangesWith:croppedImage:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerApplyButtonItem(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerCancelButtonItem(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerDidCancelChanges(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerDidChangePolygon(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerRotateClockwiseToolbarItem(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarItemTintColor(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarStyle(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarTintColor(_:)"]}]},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"imageEditingViewControllerDidCancelChanges:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerDidCancelChanges(_:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerDidCancelChanges(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"imageEditingViewControllerDidCancelChanges:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerDidChangePolygon(_:)\/title","value":"imageEditingViewControllerDidChangePolygon:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"imageEditingViewControllerDidChangePolygon:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerDidChangePolygon(_:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewController\/title","op":"replace","value":"SBSDKUICroppingViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUICroppingViewController"}],"op":"replace"},{"value":"imageEditingViewController:didApplyChangesWith:croppedImage:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewController(_:didApplyChangesWith:croppedImage:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewController:didApplyChangesWith:croppedImage:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewController(_:didApplyChangesWith:croppedImage:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)\/title","value":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerRotateCounterClockwiseToolbarItem(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerRotateCounterClockwiseToolbarItem:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerToolbarTintColor(_:)\/title","value":"imageEditingViewControllerToolbarTintColor:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"imageEditingViewControllerToolbarTintColor:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerToolbarTintColor(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerCancelButtonItem(_:)\/title","value":"imageEditingViewControllerCancelButtonItem:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerCancelButtonItem:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerCancelButtonItem(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate\/title","value":"SBSDKImageEditingViewControllerDelegate"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerApplyButtonItem(_:)\/title","value":"imageEditingViewControllerApplyButtonItem:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"imageEditingViewControllerApplyButtonItem:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerApplyButtonItem(_:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerToolbarStyle(_:)\/title","op":"replace","value":"imageEditingViewControllerToolbarStyle:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerToolbarStyle(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerToolbarStyle:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/title","value":"SBSDKImageEditingViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/fragments","value":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerRotateClockwiseToolbarItem(_:)\/title","value":"imageEditingViewControllerRotateClockwiseToolbarItem:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerRotateClockwiseToolbarItem(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"imageEditingViewControllerRotateClockwiseToolbarItem:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerToolbarItemTintColor(_:)\/title","value":"imageEditingViewControllerToolbarItemTintColor:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerToolbarItemTintColor(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"imageEditingViewControllerToolbarItemTintColor:","kind":"identifier"}]}]}]}