{"abstract":[{"text":"European Health Insurance Card (EHIC). Supports formats with both four and five lines of data.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/barcode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/birthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/cardNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/countryCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/expiryDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/givenNames","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/issuerName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/issuerNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/personalNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/signature","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/surname"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentEuropeanHealthInsuranceCard","kind":"identifier"}]}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentEuropeanHealthInsuranceCard","title":"SBSDKGenericDocumentEuropeanHealthInsuranceCard","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentEuropeanHealthInsuranceCard"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentEuropeanHealthInsuranceCard"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","roleHeading":"Class","role":"symbol"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumenteuropeanhealthinsurancecard"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumenteuropeanhealthinsurancecard"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentEuropeanHealthInsuranceCard/barcode":{"navigatorTitle":[{"text":"barcode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumenteuropeanhealthinsurancecard\/barcode","abstract":[{"type":"text","text":"Barcode image (only present in some formats)"}],"type":"topic","title":"barcode","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/barcode","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"barcode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentEuropeanHealthInsuranceCard/initWithGenericDocument:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithGenericDocument:"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumenteuropeanhealthinsurancecard\/initwithgenericdocument:","kind":"symbol","type":"topic","title":"initWithGenericDocument:","abstract":[],"navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/initWithGenericDocument:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentEuropeanHealthInsuranceCard/cardNumber":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/cardNumber","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cardNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"text":"cardNumber","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumenteuropeanhealthinsurancecard\/cardnumber","title":"cardNumber","kind":"symbol","type":"topic","abstract":[{"text":"Card number.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentEuropeanHealthInsuranceCard/expiryDate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/expiryDate","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumenteuropeanhealthinsurancecard\/expirydate","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"expiryDate","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"expiryDate"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"title":"expiryDate","abstract":[{"text":"Expiry date.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentEuropeanHealthInsuranceCard/givenNames":{"navigatorTitle":[{"text":"givenNames","kind":"identifier"}],"kind":"symbol","title":"givenNames","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumenteuropeanhealthinsurancecard\/givennames","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"givenNames","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/givenNames","abstract":[{"type":"text","text":"Given names."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentEuropeanHealthInsuranceCard/personalNumber":{"title":"personalNumber","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/personalNumber","navigatorTitle":[{"text":"personalNumber","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumenteuropeanhealthinsurancecard\/personalnumber","abstract":[{"type":"text","text":"Personal number."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"personalNumber"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentEuropeanHealthInsuranceCard":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentEuropeanHealthInsuranceCard"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentEuropeanHealthInsuranceCard","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumenteuropeanhealthinsurancecard","role":"symbol","title":"SBSDKGenericDocumentEuropeanHealthInsuranceCard","abstract":[{"type":"text","text":"European Health Insurance Card (EHIC). Supports formats with both four and five lines of data."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentEuropeanHealthInsuranceCard/surname":{"navigatorTitle":[{"kind":"identifier","text":"surname"}],"title":"surname","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumenteuropeanhealthinsurancecard\/surname","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/surname","abstract":[{"type":"text","text":"Surname."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"surname"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentWrapper":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper","role":"symbol","title":"SBSDKGenericDocumentWrapper","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"abstract":[{"type":"text","text":"Base class for strongly-typed "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","isActive":true},{"type":"text","text":" wrappers."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentEuropeanHealthInsuranceCard/issuerName":{"title":"issuerName","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumenteuropeanhealthinsurancecard\/issuername","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/issuerName","abstract":[{"type":"text","text":"Issuer name."}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"issuerName"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"issuerName","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentEuropeanHealthInsuranceCard/requiredDocumentType":{"abstract":[{"text":"The name of the wrapped document type.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/requiredDocumentType","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumenteuropeanhealthinsurancecard\/requireddocumenttype","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"requiredDocumentType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"requiredDocumentType"}],"kind":"symbol","title":"requiredDocumentType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","abstract":[{"type":"text","text":"Represents a generic document with fields and sub-documents used for document recognition."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocument"}],"role":"symbol","title":"SBSDKGenericDocument","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentEuropeanHealthInsuranceCard/issuerNumber":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuerNumber"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"issuerNumber","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumenteuropeanhealthinsurancecard\/issuernumber","role":"symbol","kind":"symbol","abstract":[{"text":"Issuer number.","type":"text"}],"title":"issuerNumber","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/issuerNumber"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentEuropeanHealthInsuranceCard/signature":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/signature","abstract":[{"type":"text","text":"Signature image."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumenteuropeanhealthinsurancecard\/signature","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"signature","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"signature","kind":"identifier"}],"kind":"symbol","type":"topic","title":"signature"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentEuropeanHealthInsuranceCard/countryCode":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumenteuropeanhealthinsurancecard\/countrycode","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"countryCode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/countryCode","title":"countryCode","abstract":[{"text":"Country code (ISO 3166-1 alpha-2)","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"countryCode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentEuropeanHealthInsuranceCard/birthDate":{"navigatorTitle":[{"text":"birthDate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/birthDate","role":"symbol","title":"birthDate","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumenteuropeanhealthinsurancecard\/birthdate","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"birthDate","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"text":"Birth date.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKGenericDocumentEuropeanHealthInsuranceCard","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKGenericDocumentEuropeanHealthInsuranceCard","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocumentEuropeanHealthInsuranceCard"}],"op":"replace"},{"value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/barcode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/birthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/cardNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/countryCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/expiryDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/givenNames","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/issuerName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/issuerNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/personalNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/signature","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/surname"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentEuropeanHealthInsuranceCard\/initWithGenericDocument:"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"]}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentEuropeanHealthInsuranceCard","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentWrapper","text":"SBSDKGenericDocumentWrapper","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"barcode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1barcode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"barcode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1barcode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1cardNumber\/title","value":"cardNumber"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1cardNumber\/fragments","value":[{"text":"cardNumber","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1expiryDate\/title","value":"expiryDate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1expiryDate\/fragments","value":[{"kind":"identifier","text":"expiryDate"}]},{"value":"givenNames","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1givenNames\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1givenNames\/fragments","op":"replace","value":[{"text":"givenNames","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1personalNumber\/title","value":"personalNumber","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1personalNumber\/fragments","value":[{"kind":"identifier","text":"personalNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard\/title","value":"SBSDKGenericDocumentEuropeanHealthInsuranceCard"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentEuropeanHealthInsuranceCard"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentEuropeanHealthInsuranceCard","kind":"identifier"}]},{"value":"surname","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1surname\/title","op":"replace"},{"value":[{"kind":"identifier","text":"surname"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1surname\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/title","value":"SBSDKGenericDocumentWrapper"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/fragments","value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1issuerName\/title","op":"replace","value":"issuerName"},{"value":[{"text":"issuerName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1issuerName\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1requiredDocumentType\/title","value":"requiredDocumentType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1requiredDocumentType\/fragments","op":"replace","value":[{"kind":"identifier","text":"requiredDocumentType"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","op":"replace","value":"SBSDKGenericDocument"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments"},{"value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","op":"replace"},{"op":"replace","value":"issuerNumber","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1issuerNumber\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1issuerNumber\/fragments","value":[{"kind":"identifier","text":"issuerNumber"}]},{"op":"replace","value":"signature","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1signature\/title"},{"value":[{"text":"signature","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1signature\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1countryCode\/title","value":"countryCode"},{"op":"replace","value":[{"text":"countryCode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1countryCode\/fragments"},{"value":"birthDate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1birthDate\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentEuropeanHealthInsuranceCard~1birthDate\/fragments","value":[{"kind":"identifier","text":"birthDate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}