{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The type classifier for machine-readable-zone document types."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentType"}],"title":"SBSDKMachineReadableZoneRecognizerResultDocumentType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerResultDocumentType","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentType"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/crewMemberCertificate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/idCard","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/passport","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/swissDriverLicense","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/undefined","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/visa"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType/idCard":{"role":"symbol","title":"SBSDKMachineReadableZoneRecognizerResultDocumentType.idCard","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"idCard"}],"abstract":[{"type":"text","text":"The document is an ID card."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/idCard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeIdCard"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/idcard"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/rawrepresentable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.2.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/init(rawvalue:)"},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType/passport":{"role":"symbol","title":"SBSDKMachineReadableZoneRecognizerResultDocumentType.passport","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"passport"}],"abstract":[{"type":"text","text":"The document is a passport."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/passport","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypePassport"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/passport"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType":{"role":"symbol","title":"SBSDKMachineReadableZoneRecognizerResultDocumentType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentType"}],"abstract":[{"type":"text","text":"The type classifier for machine-readable-zone document types."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentType"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType/undefined":{"role":"symbol","title":"SBSDKMachineReadableZoneRecognizerResultDocumentType.undefined","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"undefined"}],"abstract":[{"type":"text","text":"The document type is unknown."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/undefined","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeUndefined"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/undefined"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType/swissDriverLicense":{"role":"symbol","title":"SBSDKMachineReadableZoneRecognizerResultDocumentType.swissDriverLicense","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"swissDriverLicense"}],"abstract":[{"type":"text","text":"The document is a Swiss driver license."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/swissDriverLicense","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeSwissDriverLicense"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/swissdriverlicense"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType/crewMemberCertificate":{"role":"symbol","title":"SBSDKMachineReadableZoneRecognizerResultDocumentType.crewMemberCertificate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"crewMemberCertificate"}],"abstract":[{"type":"text","text":"The document is a crew member certificate."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/crewMemberCertificate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeCrewMemberCertificate"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/crewmembercertificate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/equatable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType/visa":{"role":"symbol","title":"SBSDKMachineReadableZoneRecognizerResultDocumentType.visa","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"visa"}],"abstract":[{"type":"text","text":"The document is a visa."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/visa","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeVisa"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/visa"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMachineReadableZoneRecognizerResultDocumentType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/crewMemberCertificate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/idCard","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/passport","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/swissDriverLicense","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/undefined","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/visa"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1idCard\/title","value":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeIdCard"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1idCard\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeIdCard"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1passport\/title","value":"SBSDKMachineReadableZoneRecognizerResultDocumentTypePassport"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1passport\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypePassport"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType\/title","value":"SBSDKMachineReadableZoneRecognizerResultDocumentType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1undefined\/title","value":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeUndefined"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1undefined\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeUndefined"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1swissDriverLicense\/title","value":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeSwissDriverLicense"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1swissDriverLicense\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeSwissDriverLicense"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1crewMemberCertificate\/title","value":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeCrewMemberCertificate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1crewMemberCertificate\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeCrewMemberCertificate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1visa\/title","value":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeVisa"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1visa\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeVisa"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}