{"abstract":[{"text":"A delegate protocol to handle the barcode results from ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController","isActive":true},{"type":"text","text":"."}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:didDetectBarcodes:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:filterResults:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:overlayForBarcode:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:polygonStyleForBarcode:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCountControllerDidStartScanning(_:)"]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKBarcodeScanAndCountViewControllerDelegate","symbolKind":"protocol","role":"symbol","roleHeading":"Protocol","title":"SBSDKBarcodeScanAndCountViewControllerDelegate"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewControllerDelegate"}]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontrollerdelegate"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewController":{"title":"SBSDKBarcodeScanAndCountViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode detector."},{"text":" ","type":"text"},{"text":"Screen also shows snap, scan more and reset buttons.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The snap button starts the scanning when tapped."},{"text":" ","type":"text"},{"type":"text","text":"The snap button resets the scanning when tapped again."},{"type":"text","text":" "},{"type":"text","text":"Instead it is installing itself as a child view controller onto a given parent view controller."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewControllerDelegate":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontrollerdelegate","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewControllerDelegate"}],"type":"topic","abstract":[{"text":"A delegate protocol to handle the barcode results from ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController","type":"reference","isActive":true},{"text":".","type":"text"}],"title":"SBSDKBarcodeScanAndCountViewControllerDelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewControllerDelegate/barcodeScanAndCount(_:polygonStyleForBarcode:)":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontrollerdelegate\/barcodescanandcount(_:polygonstyleforbarcode:)","required":true,"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeScanAndCount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKBarcodeScanAndCountViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScanAndCountViewController"},{"kind":"text","text":", "},{"text":"polygonStyleForBarcode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult"},{"text":") -> ","kind":"text"},{"text":"SBSDKScanAndCountPolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScanAndCountPolygonStyle"}],"abstract":[{"text":"Asks the delegate to provide a custom barcode overlay polygon style for the given barcode.","type":"text"}],"title":"barcodeScanAndCount(_:polygonStyleForBarcode:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:polygonStyleForBarcode:)","navigatorTitle":[{"text":"barcodeScanAndCountController:polygonStyleForBarcode:","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewControllerDelegate/barcodeScanAndCountControllerDidStartScanning(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontrollerdelegate\/barcodescanandcountcontrollerdidstartscanning(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeScanAndCountControllerDidStartScanning","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScanAndCountViewController","text":"SBSDKBarcodeScanAndCountViewController"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"barcodeScanAndCountControllerDidStartScanning:"}],"abstract":[{"type":"text","text":"Informs the delegate when it starts scanning."}],"title":"barcodeScanAndCountControllerDidStartScanning(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCountControllerDidStartScanning(_:)","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewControllerDelegate/barcodeScanAndCount(_:filterResults:)":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontrollerdelegate\/barcodescanandcount(_:filterresults:)","required":true,"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeScanAndCount"},{"kind":"text","text":"("},{"text":"SBSDKBarcodeScanAndCountViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScanAndCountViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"filterResults","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKBarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult"},{"kind":"text","text":"]) -> ["},{"text":"SBSDKBarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Asks the delegate to filter the detected barcodes."}],"title":"barcodeScanAndCount(_:filterResults:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:filterResults:)","navigatorTitle":[{"kind":"identifier","text":"barcodeScanAndCountController:filterResults:"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewControllerDelegate/barcodeScanAndCount(_:overlayForBarcode:)":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontrollerdelegate\/barcodescanandcount(_:overlayforbarcode:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:overlayForBarcode:)","kind":"symbol","abstract":[{"text":"Asks the delegate to provide the overlay view for a given code.","type":"text"}],"navigatorTitle":[{"text":"barcodeScanAndCountController:overlayForBarcode:","kind":"identifier"}],"type":"topic","title":"barcodeScanAndCount(_:overlayForBarcode:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeScanAndCount"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScanAndCountViewController","text":"SBSDKBarcodeScanAndCountViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"overlayForBarcode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult","kind":"typeIdentifier","text":"SBSDKBarcodeScannerResult"},{"text":") -> ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewControllerDelegate/barcodeScanAndCount(_:didDetectBarcodes:)":{"title":"barcodeScanAndCount(_:didDetectBarcodes:)","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontrollerdelegate\/barcodescanandcount(_:diddetectbarcodes:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeScanAndCount"},{"kind":"text","text":"("},{"text":"SBSDKBarcodeScanAndCountViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScanAndCountViewController"},{"text":", ","kind":"text"},{"text":"didDetectBarcodes","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKBarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult"},{"kind":"text","text":"])"}],"required":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:didDetectBarcodes:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"barcodeScanAndCountController:didDetectBarcodes:"}],"abstract":[{"type":"text","text":"Informs the delegate that the receiver has detected some barcodes."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKBarcodeScanAndCountViewControllerDelegate"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewControllerDelegate"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewControllerDelegate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:didDetectBarcodes:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:filterResults:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:overlayForBarcode:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:polygonStyleForBarcode:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCountControllerDidStartScanning(_:)"],"title":"Instance Methods"}]},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/title","value":"SBSDKBarcodeScanAndCountViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/fragments","value":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}]},{"op":"replace","value":"SBSDKBarcodeScanAndCountViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate\/fragments"},{"value":"barcodeScanAndCountController:polygonStyleForBarcode:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCount(_:polygonStyleForBarcode:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"barcodeScanAndCountController:polygonStyleForBarcode:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCount(_:polygonStyleForBarcode:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCountControllerDidStartScanning(_:)\/title","value":"barcodeScanAndCountControllerDidStartScanning:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCountControllerDidStartScanning(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodeScanAndCountControllerDidStartScanning:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCount(_:filterResults:)\/title","op":"replace","value":"barcodeScanAndCountController:filterResults:"},{"value":[{"text":"- ","kind":"text"},{"text":"barcodeScanAndCountController:filterResults:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCount(_:filterResults:)\/fragments","op":"replace"},{"op":"replace","value":"barcodeScanAndCountController:overlayForBarcode:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCount(_:overlayForBarcode:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodeScanAndCountController:overlayForBarcode:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCount(_:overlayForBarcode:)\/fragments"},{"op":"replace","value":"barcodeScanAndCountController:didDetectBarcodes:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCount(_:didDetectBarcodes:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCount(_:didDetectBarcodes:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"barcodeScanAndCountController:didDetectBarcodes:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}