{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController"},"kind":"symbol","sections":[],"abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to scan for license plates with the camera.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewDelegate","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring","doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo","title":"Conforms To"}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/init(configuration:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/init(parentViewController:parentView:configuration:delegate:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/configuration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/delegate"]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLicensePlateScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicensePlateScannerViewController"}],"title":"SBSDKLicensePlateScannerViewController","role":"symbol","roleHeading":"Class","symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerViewController"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKLicensePlateScannerViewController","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontroller"]}],"references":{"doc://net.doo.ScanbotSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewController/viewDidLoad":{"fragments":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/viewDidLoad","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontroller\/viewdidload","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"title":"viewDidLoad","role":"symbol","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewController/configuration":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerConfiguration","text":"SBSDKLicensePlateScannerConfiguration","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/configuration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontroller\/configuration","navigatorTitle":[{"kind":"identifier","text":"configuration"}],"title":"configuration","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The receivers configuration."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://net.doo.ScanbotSDK/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://net.doo.ScanbotSDK/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView":{"navigatorTitle":[{"text":"SBSDKFinderView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","url":"\/documentation\/scanbotsdk\/sbsdkfinderview","abstract":[{"type":"text","text":"A "},{"code":"UIView","type":"codeVoice"},{"type":"text","text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio."}],"title":"SBSDKFinderView","role":"symbol","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewController/init(configuration:delegate:)":{"title":"init(configuration:delegate:)","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontroller\/init(configuration:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKLicensePlateScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKLicensePlateScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKLicensePlateScannerViewControllerDelegate"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/init(configuration:delegate:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:delegate:"}],"abstract":[{"text":"Creates a new instance of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController"},{"text":".","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewController":{"title":"SBSDKBaseScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"abstract":[{"type":"text","text":"A highly customizable camera view controller that delivers a basic camera functionality along with video"},{"type":"text","text":" "},{"type":"text","text":"frame extraction and preprocessing, orientation correction and still image capturing."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSessionDelegate":{"title":"SBSDKCameraSessionDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSessionDelegate"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionDelegate","type":"topic","abstract":[{"type":"text","text":"The  delegate protocol for "},{"type":"codeVoice","code":"SBSDKCameraSession"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasessiondelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCameraSessionDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewController/init()":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontroller\/init()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"title":"init()","abstract":[{"text":"Initializes an instance of this class with the default configuration.","type":"text"}]},"doc://net.doo.ScanbotSDK/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewController/init(parentViewController:parentView:configuration:delegate:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/init(parentViewController:parentView:configuration:delegate:)","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontroller\/init(parentviewcontroller:parentview:configuration:delegate:)","navigatorTitle":[{"text":"initWithParentViewController:parentView:configuration:delegate:","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"parentViewController","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"parentView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerConfiguration","text":"SBSDKLicensePlateScannerConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKLicensePlateScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKLicensePlateScannerViewControllerDelegate"},{"text":"?)","kind":"text"}],"title":"init(parentViewController:parentView:configuration:delegate:)","abstract":[{"text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area.","type":"text"}]},"doc://net.doo.ScanbotSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderViewDelegate":{"url":"\/documentation\/scanbotsdk\/sbsdkfinderviewdelegate","title":"SBSDKFinderViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKFinderViewDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewDelegate","navigatorTitle":[{"text":"SBSDKFinderViewDelegate","kind":"identifier"}],"abstract":[{"text":"The delegate protocol for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","type":"reference","isActive":true},{"type":"text","text":" class."}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSessionObserving":{"abstract":[{"type":"text","text":"A multicast-oberserver protocol that informs its oberservers about state changes of a camera session."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCameraSessionObserving","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSessionObserving"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasessionobserving","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving","title":"SBSDKCameraSessionObserving","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewController":{"title":"SBSDKLicensePlateScannerViewController","navigatorTitle":[{"text":"SBSDKLicensePlateScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","type":"topic","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to scan for license plates with the camera.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLicensePlateScannerViewController"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewController/delegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKLicensePlateScannerViewControllerDelegate","text":"SBSDKLicensePlateScannerViewControllerDelegate"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontroller\/delegate","abstract":[{"text":"The delegate.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/delegate","title":"delegate","role":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKLicensePlateScannerViewController"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKLicensePlateScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKLicensePlateScannerViewController","kind":"identifier"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/configuration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/delegate"],"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/init(configuration:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/init(parentViewController:parentView:configuration:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/viewDidLoad"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"],"type":"inheritsFrom","title":"Inherits From"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicensePlateScannerViewController"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKBaseScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"}]}]},"op":"replace"},{"value":"configuration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController~1configuration\/title"},{"value":[{"text":"configuration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController~1configuration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/title","value":"SBSDKFinderView"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKFinderView"}]},{"value":"initWithConfiguration:delegate:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController~1init(configuration:delegate:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController~1init(configuration:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithConfiguration:delegate:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKBaseScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionDelegate\/title","value":"SBSDKCameraSessionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraSessionDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController~1init()\/title","value":"init","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController~1init()\/fragments"},{"value":"initWithParentViewController:parentView:configuration:delegate:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController~1init(parentViewController:parentView:configuration:delegate:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController~1init(parentViewController:parentView:configuration:delegate:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithParentViewController:parentView:configuration:delegate:"}]},{"op":"replace","value":"SBSDKFinderViewDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate\/fragments","op":"replace","value":[{"text":"SBSDKFinderViewDelegate","kind":"identifier"}]},{"op":"replace","value":"SBSDKCameraSessionObserving","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving\/fragments","value":[{"text":"SBSDKCameraSessionObserving","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKLicensePlateScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController~1delegate\/title","value":"delegate","op":"replace"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController~1delegate\/fragments","op":"replace"}]}]}