{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2gs1handling"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2gs1handling"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/decodeFull","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/decodeStructure","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/none","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/parse","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/validateFull","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/validateStructure"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"type":"text","text":"GS1_COMPOSITE barcode type handling"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(SBSDKUI2Gs1Handling) "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}]}]}],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2Gs1Handling","title":"SBSDKUI2Gs1Handling","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}],"navigatorTitle":[{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}],"symbolKind":"enum","roleHeading":"Enumeration"},"references":{"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling/parse":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingParse"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/parse","type":"topic","abstract":[{"type":"text","text":"GS1 messages are converted to the machine-readable format per the GS1 spec (the special FNC1 character is"},{"type":"text","text":" "},{"text":"converted to ASCII \\x1D). The implied 01 AI key is prepended to DataBar results. No validation is performed.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"parse","kind":"identifier"}],"title":"SBSDKUI2Gs1Handling.parse","url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/parse"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/init(rawValue:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/init(rawvalue:)","title":"init(rawValue:)","kind":"symbol","role":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling","type":"topic","abstract":[{"text":"GS1_COMPOSITE barcode type handling","type":"text"}],"title":"SBSDKUI2Gs1Handling","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling/decodeFull":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeFull"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingDecodeFull"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/decodeFull","url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/decodefull","title":"SBSDKUI2Gs1Handling.decodeFull","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Same as DECODE_STRUCTURE, but with full validation."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling/validateFull":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/validateFull","url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/validatefull","abstract":[{"type":"text","text":"Full validation including linting and checksums. This is the most strict mode."}],"role":"symbol","kind":"symbol","title":"SBSDKUI2Gs1Handling.validateFull","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validateFull"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingValidateFull"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling/RawRepresentable-Implementations":{"role":"collectionGroup","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/rawrepresentable-implementations","kind":"article","abstract":[],"title":"RawRepresentable Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/RawRepresentable-Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling/decodeStructure":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingDecodeStructure"}],"title":"SBSDKUI2Gs1Handling.decodeStructure","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/decodeStructure","url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/decodestructure","abstract":[{"text":"Same as VALIDATE_STRUCTURE, except that GS1 strings are converted to the human-readable format, instead (with","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"parentheses used to wrap AI keys, e.g. (01)123456789). The \\x1D character is never used in this representation."}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"decodeStructure","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling/none":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Gs1HandlingNone","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/none","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/none","title":"SBSDKUI2Gs1Handling.none","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The (FNC1) character is simply stripped from the result in barcodes that implement this mode. Do not use. Will"},{"type":"text","text":" "},{"type":"text","text":"be removed in a future release."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling/validateStructure":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/validateStructure","type":"topic","abstract":[{"type":"text","text":"Same as PARSE. Additionally, messages containing unknown AI keys, or containing values of incorrect format for"},{"text":" ","type":"text"},{"type":"text","text":"known keys, are not returned."}],"title":"SBSDKUI2Gs1Handling.validateStructure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"validateStructure"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/validatestructure","navigatorTitle":[{"text":"SBSDKUI2Gs1HandlingValidateStructure","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling/Equatable-Implementations":{"kind":"article","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/Equatable-Implementations","type":"topic","title":"Equatable Implementations","url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/equatable-implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"SBSDKUI2Gs1Handling","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/decodeFull","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/decodeStructure","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/none","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/parse","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/validateFull","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/validateStructure"],"title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2Gs1Handling"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUI2Gs1HandlingParse","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1parse\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingParse"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1parse\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/title","value":"SBSDKUI2Gs1Handling"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1decodeFull\/title","value":"SBSDKUI2Gs1HandlingDecodeFull"},{"value":[{"text":"SBSDKUI2Gs1HandlingDecodeFull","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1decodeFull\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1validateFull\/title","op":"replace","value":"SBSDKUI2Gs1HandlingValidateFull"},{"value":[{"text":"SBSDKUI2Gs1HandlingValidateFull","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1validateFull\/fragments","op":"replace"},{"op":"replace","value":"SBSDKUI2Gs1HandlingDecodeStructure","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1decodeStructure\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1decodeStructure\/fragments","value":[{"text":"SBSDKUI2Gs1HandlingDecodeStructure","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2Gs1HandlingNone","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1none\/title","op":"replace"},{"value":[{"text":"SBSDKUI2Gs1HandlingNone","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1none\/fragments","op":"replace"},{"value":"SBSDKUI2Gs1HandlingValidateStructure","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1validateStructure\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1validateStructure\/fragments","value":[{"text":"SBSDKUI2Gs1HandlingValidateStructure","kind":"identifier"}]}]}]}