{"abstract":[{"text":"The barcode overlay text format.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeoverlayformat"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeoverlayformat"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"SBSDKBarcodeOverlayFormat","kind":"identifier"}],"roleHeading":"Enumeration","symbolKind":"enum","title":"SBSDKBarcodeOverlayFormat","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeOverlayFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeOverlayFormat"}],"modules":[{"name":"ScanbotSDK"}]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/code","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/codeAndType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/none"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeOverlayFormat","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeOverlayFormat/code":{"abstract":[{"type":"text","text":"Shows the barcode value."}],"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"code"}],"role":"symbol","title":"SBSDKBarcodeOverlayFormat.code","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/code","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeoverlayformat\/code","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeOverlayFormatCode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeOverlayFormat":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeOverlayFormat","kind":"identifier"}],"title":"SBSDKBarcodeOverlayFormat","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeoverlayformat","type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeOverlayFormat","kind":"identifier"}],"abstract":[{"text":"The barcode overlay text format.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeOverlayFormat/codeAndType":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"codeAndType"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeoverlayformat\/codeandtype","abstract":[{"type":"text","text":"Shows the barcode value with the barcode format."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeOverlayFormatCodeAndType"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/codeAndType","type":"topic","title":"SBSDKBarcodeOverlayFormat.codeAndType","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeOverlayFormat/none":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeoverlayformat\/none","title":"SBSDKBarcodeOverlayFormat.none","abstract":[{"type":"text","text":"Shows the barcode overlay frame only."}],"navigatorTitle":[{"text":"SBSDKBarcodeOverlayFormatNone","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/none"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeOverlayFormat/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeoverlayformat\/equatable-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/Equatable-Implementations","kind":"article","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeOverlayFormat/init(rawValue:)":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","title":"init(rawValue:)","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeoverlayformat\/init(rawvalue:)","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeOverlayFormat/RawRepresentable-Implementations":{"kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/RawRepresentable-Implementations","role":"collectionGroup","title":"RawRepresentable Implementations","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeoverlayformat\/rawrepresentable-implementations","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodeOverlayFormat"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKBarcodeOverlayFormat","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeOverlayFormat"}],"op":"replace"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/code","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/codeAndType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeOverlayFormat\/none"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeOverlayFormat"},{"kind":"text","text":": "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKBarcodeOverlayFormatCode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeOverlayFormat~1code\/title"},{"op":"replace","value":[{"text":"SBSDKBarcodeOverlayFormatCode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeOverlayFormat~1code\/fragments"},{"value":"SBSDKBarcodeOverlayFormat","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeOverlayFormat\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeOverlayFormat\/fragments","value":[{"text":"SBSDKBarcodeOverlayFormat","kind":"identifier"}]},{"value":"SBSDKBarcodeOverlayFormatCodeAndType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeOverlayFormat~1codeAndType\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeOverlayFormat~1codeAndType\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeOverlayFormatCodeAndType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeOverlayFormat~1none\/title","value":"SBSDKBarcodeOverlayFormatNone","op":"replace"},{"value":[{"text":"SBSDKBarcodeOverlayFormatNone","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeOverlayFormat~1none\/fragments","op":"replace"}]}]}