{"sections":[],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/birthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/checkDigitBirthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/checkDigitDocumentNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/checkDigitExpiryDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/checkDigitGeneral","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/checkDigitPersonalNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/dateOfIssuance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/documentNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/documentTypeCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/expiryDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/gender","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/givenNames","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/issuingAuthority","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/languageCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/nationality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/officeOfIssuance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/optional1","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/optional2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/personalNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/pinCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/surname","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/travelDocType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/travelDocTypeVariant","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/unknown","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/versionNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/visaOptional"],"title":"Instance Properties"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"MRZ part of the document."}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"],"type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentMRZ","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentMRZ"}],"roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentMRZ","title":"SBSDKGenericDocumentMRZ","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentMRZ","kind":"identifier"}],"symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/checkDigitDocumentNumber":{"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkDigitDocumentNumber","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"abstract":[{"text":"Check digit document number.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/checkdigitdocumentnumber","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/checkDigitDocumentNumber","type":"topic","title":"checkDigitDocumentNumber","navigatorTitle":[{"text":"checkDigitDocumentNumber","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentMRZ","kind":"identifier"}],"title":"SBSDKGenericDocumentMRZ","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz","kind":"symbol","abstract":[{"type":"text","text":"MRZ part of the document."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentMRZ","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/visaOptional":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visaOptional"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"text":"MRV-A\/MRV-B (Travel Visa) Optional field.","type":"text"}],"title":"visaOptional","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/visaOptional","role":"symbol","type":"topic","navigatorTitle":[{"text":"visaOptional","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/visaoptional"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"title":"SBSDKGenericDocument","abstract":[{"text":"Represents a generic document with fields and sub-documents used for document recognition.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/languageCode":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"languageCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Language code."}],"title":"languageCode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/languageCode","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"languageCode"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/languagecode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/versionNumber":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"versionNumber"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Version number."}],"title":"versionNumber","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/versionNumber","role":"symbol","type":"topic","navigatorTitle":[{"text":"versionNumber","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/versionnumber"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/nationality":{"navigatorTitle":[{"text":"nationality","kind":"identifier"}],"title":"nationality","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/nationality","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/nationality","abstract":[{"type":"text","text":"Nationality."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nationality"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/officeOfIssuance":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"officeOfIssuance"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"text":"Office of issuance.","type":"text"}],"title":"officeOfIssuance","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/officeOfIssuance","role":"symbol","type":"topic","navigatorTitle":[{"text":"officeOfIssuance","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/officeofissuance"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/checkDigitExpiryDate":{"navigatorTitle":[{"kind":"identifier","text":"checkDigitExpiryDate"}],"title":"checkDigitExpiryDate","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/checkDigitExpiryDate","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/checkdigitexpirydate","abstract":[{"text":"Check digit expiry date.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkDigitExpiryDate"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/checkDigitGeneral":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkDigitGeneral"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Check  digit general."}],"title":"checkDigitGeneral","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/checkDigitGeneral","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"checkDigitGeneral"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/checkdigitgeneral"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/optional1":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/optional1","role":"symbol","title":"optional1","abstract":[{"type":"text","text":"TD1 Optional field (line 2)"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"optional1"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"optional1","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/optional1"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/gender":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/gender","title":"gender","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/gender","role":"symbol","abstract":[{"type":"text","text":"Gender."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"gender","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"gender"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/travelDocType":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"travelDocType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/travelDocType","title":"travelDocType","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/traveldoctype","type":"topic","navigatorTitle":[{"text":"travelDocType","kind":"identifier"}],"abstract":[{"type":"text","text":"Travel document type."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/documentNumber":{"role":"symbol","kind":"symbol","title":"documentNumber","abstract":[{"type":"text","text":"Document number."}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"documentNumber","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/documentnumber","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/documentNumber","navigatorTitle":[{"text":"documentNumber","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/checkDigitPersonalNumber":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"checkDigitPersonalNumber","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/checkdigitpersonalnumber","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/checkDigitPersonalNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkDigitPersonalNumber"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Check digit personal number."}],"title":"checkDigitPersonalNumber"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/personalNumber":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"personalNumber"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Personal number."}],"title":"personalNumber","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/personalNumber","role":"symbol","type":"topic","navigatorTitle":[{"text":"personalNumber","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/personalnumber"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/surname":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"surname"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"text":"Surname.","type":"text"}],"title":"surname","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/surname","role":"symbol","type":"topic","navigatorTitle":[{"text":"surname","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/surname"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/checkDigitBirthDate":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/checkdigitbirthdate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/checkDigitBirthDate","navigatorTitle":[{"kind":"identifier","text":"checkDigitBirthDate"}],"title":"checkDigitBirthDate","abstract":[{"type":"text","text":"Check digit birth date."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkDigitBirthDate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/documentTypeCode":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentTypeCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Document type code."}],"title":"documentTypeCode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/documentTypeCode","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentTypeCode"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/documenttypecode"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/issuingAuthority":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"issuingAuthority"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"title":"issuingAuthority","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/issuingAuthority","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/issuingauthority","kind":"symbol","abstract":[{"type":"text","text":"Issuing authority."}],"role":"symbol","navigatorTitle":[{"text":"issuingAuthority","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentWrapper":{"title":"SBSDKGenericDocumentWrapper","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Base class for strongly-typed ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","isActive":true},{"type":"text","text":" wrappers."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/expiryDate":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"expiryDate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Expiry date."}],"title":"expiryDate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/expiryDate","role":"symbol","type":"topic","navigatorTitle":[{"text":"expiryDate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/expirydate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/initWithGenericDocument:":{"kind":"symbol","abstract":[],"title":"initWithGenericDocument:","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/initwithgenericdocument:","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGenericDocument:"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/initWithGenericDocument:","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/requiredDocumentType":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/requireddocumenttype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/requiredDocumentType","navigatorTitle":[{"kind":"identifier","text":"requiredDocumentType"}],"title":"requiredDocumentType","abstract":[{"type":"text","text":"The name of the wrapped document type."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiredDocumentType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/dateOfIssuance":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateOfIssuance"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"text":"Date of issuance.","type":"text"}],"title":"dateOfIssuance","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/dateOfIssuance","role":"symbol","type":"topic","navigatorTitle":[{"text":"dateOfIssuance","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/dateofissuance"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/birthDate":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"birthDate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Birth date."}],"title":"birthDate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/birthDate","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"birthDate"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/birthdate"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/givenNames":{"role":"symbol","navigatorTitle":[{"text":"givenNames","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/givenNames","title":"givenNames","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/givennames","type":"topic","abstract":[{"type":"text","text":"Given names."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"givenNames","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/unknown":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Unknown."}],"title":"unknown","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/unknown","role":"symbol","type":"topic","navigatorTitle":[{"text":"unknown","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/unknown"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/travelDocTypeVariant":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"travelDocTypeVariant","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Travel document type variant."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/traveldoctypevariant","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/travelDocTypeVariant","type":"topic","title":"travelDocTypeVariant","navigatorTitle":[{"kind":"identifier","text":"travelDocTypeVariant"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/optional2":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"optional2"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"text":"TD1 Optional field (line 3)","type":"text"}],"title":"optional2","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/optional2","role":"symbol","type":"topic","navigatorTitle":[{"text":"optional2","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/optional2"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentMRZ/pinCode":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pinCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"PIN code."}],"title":"pinCode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/pinCode","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pinCode"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentmrz\/pincode"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKGenericDocumentMRZ"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentMRZ"}],"path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKGenericDocumentMRZ","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/birthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/checkDigitBirthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/checkDigitDocumentNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/checkDigitExpiryDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/checkDigitGeneral","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/checkDigitPersonalNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/dateOfIssuance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/documentNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/documentTypeCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/expiryDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/gender","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/givenNames","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/issuingAuthority","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/languageCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/nationality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/officeOfIssuance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/optional1","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/optional2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/personalNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/pinCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/surname","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/travelDocType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/travelDocTypeVariant","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/unknown","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/versionNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/visaOptional"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentMRZ\/initWithGenericDocument:"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"]}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentMRZ","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentWrapper","text":"SBSDKGenericDocumentWrapper"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1checkDigitDocumentNumber\/title","value":"checkDigitDocumentNumber"},{"op":"replace","value":[{"text":"checkDigitDocumentNumber","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1checkDigitDocumentNumber\/fragments"},{"value":"SBSDKGenericDocumentMRZ","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ\/title"},{"value":[{"text":"SBSDKGenericDocumentMRZ","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1visaOptional\/title","value":"visaOptional"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1visaOptional\/fragments","value":[{"text":"visaOptional","kind":"identifier"}]},{"value":"SBSDKGenericDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title"},{"op":"replace","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments"},{"op":"replace","value":"languageCode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1languageCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1languageCode\/fragments","value":[{"kind":"identifier","text":"languageCode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1versionNumber\/title","value":"versionNumber"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1versionNumber\/fragments","op":"replace","value":[{"kind":"identifier","text":"versionNumber"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1nationality\/title","value":"nationality","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1nationality\/fragments","value":[{"text":"nationality","kind":"identifier"}]},{"op":"replace","value":"officeOfIssuance","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1officeOfIssuance\/title"},{"value":[{"text":"officeOfIssuance","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1officeOfIssuance\/fragments"},{"value":"checkDigitExpiryDate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1checkDigitExpiryDate\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1checkDigitExpiryDate\/fragments","value":[{"text":"checkDigitExpiryDate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1checkDigitGeneral\/title","value":"checkDigitGeneral","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1checkDigitGeneral\/fragments","op":"replace","value":[{"text":"checkDigitGeneral","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1optional1\/title","value":"optional1"},{"value":[{"text":"optional1","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1optional1\/fragments"},{"op":"replace","value":"gender","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1gender\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1gender\/fragments","value":[{"kind":"identifier","text":"gender"}],"op":"replace"},{"value":"travelDocType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1travelDocType\/title","op":"replace"},{"op":"replace","value":[{"text":"travelDocType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1travelDocType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1documentNumber\/title","value":"documentNumber"},{"value":[{"text":"documentNumber","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1documentNumber\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1checkDigitPersonalNumber\/title","value":"checkDigitPersonalNumber","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1checkDigitPersonalNumber\/fragments","value":[{"kind":"identifier","text":"checkDigitPersonalNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1personalNumber\/title","value":"personalNumber"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1personalNumber\/fragments","op":"replace","value":[{"kind":"identifier","text":"personalNumber"}]},{"value":"surname","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1surname\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1surname\/fragments","value":[{"text":"surname","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1checkDigitBirthDate\/title","value":"checkDigitBirthDate","op":"replace"},{"value":[{"kind":"identifier","text":"checkDigitBirthDate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1checkDigitBirthDate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1documentTypeCode\/title","value":"documentTypeCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1documentTypeCode\/fragments","value":[{"kind":"identifier","text":"documentTypeCode"}]},{"value":"issuingAuthority","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1issuingAuthority\/title","op":"replace"},{"value":[{"kind":"identifier","text":"issuingAuthority"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1issuingAuthority\/fragments"},{"value":"SBSDKGenericDocumentWrapper","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"op":"replace"},{"op":"replace","value":"expiryDate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1expiryDate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"expiryDate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1expiryDate\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1requiredDocumentType\/title","op":"replace","value":"requiredDocumentType"},{"value":[{"text":"requiredDocumentType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1requiredDocumentType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1dateOfIssuance\/title","value":"dateOfIssuance"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1dateOfIssuance\/fragments","value":[{"text":"dateOfIssuance","kind":"identifier"}]},{"value":"birthDate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1birthDate\/title"},{"value":[{"kind":"identifier","text":"birthDate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1birthDate\/fragments"},{"op":"replace","value":"givenNames","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1givenNames\/title"},{"value":[{"kind":"identifier","text":"givenNames"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1givenNames\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1unknown\/title","value":"unknown","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1unknown\/fragments","value":[{"text":"unknown","kind":"identifier"}],"op":"replace"},{"value":"travelDocTypeVariant","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1travelDocTypeVariant\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1travelDocTypeVariant\/fragments","value":[{"kind":"identifier","text":"travelDocTypeVariant"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1optional2\/title","value":"optional2"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1optional2\/fragments","value":[{"text":"optional2","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1pinCode\/title","op":"replace","value":"pinCode"},{"value":[{"kind":"identifier","text":"pinCode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentMRZ~1pinCode\/fragments"}]}]}