{"sections":[],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships","title":"Conforms To"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions"},"abstract":[{"type":"text","text":"The TIFF compression algorithms."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"SBSDKTIFFImageWriterCompressionOptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Enumeration","symbolKind":"enum","externalID":"c:@M@ScanbotSDK@E@SBSDKTIFFImageWriterCompressionOptions"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/adobe_deflate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccitt_t4","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccitt_t6","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittrle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittrlew","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/deflate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/lzw","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/none","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/packbits"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterCompressionOptions/deflate":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/deflate","role":"symbol","abstract":[{"type":"text","text":"For both colored and binarized images."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"deflate","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions\/deflate","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsDeflate"}],"title":"SBSDKTIFFImageWriterCompressionOptions.deflate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterCompressionOptions/ccittrle":{"type":"topic","abstract":[{"text":"For binarized images only.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions\/ccittrle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittrle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ccittrle"}],"kind":"symbol","title":"SBSDKTIFFImageWriterCompressionOptions.ccittrle","navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcittrle","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterCompressionOptions/packbits":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/packbits","role":"symbol","abstract":[{"type":"text","text":"For both colored and binarized images."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"packbits","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions\/packbits","navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptionsPackbits","kind":"identifier"}],"title":"SBSDKTIFFImageWriterCompressionOptions.packbits"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterCompressionOptions/RawRepresentable-Implementations":{"role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/RawRepresentable-Implementations","abstract":[],"type":"topic","kind":"article"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterCompressionOptions/init(rawValue:)":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/init(rawValue:)","role":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions\/init(rawvalue:)","title":"init(rawValue:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterCompressionOptions/ccitt_t6":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccitt_t6","role":"symbol","abstract":[{"text":"For binarized images only.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ccitt_t6","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions\/ccitt_t6","navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcitt_t6","kind":"identifier"}],"title":"SBSDKTIFFImageWriterCompressionOptions.ccitt_t6"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterCompressionOptions/none":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/none","role":"symbol","abstract":[{"text":"For both colored and binarized images.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions\/none","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsNone"}],"title":"SBSDKTIFFImageWriterCompressionOptions.none"},"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterCompressionOptions/ccittrlew":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittrlew","role":"symbol","abstract":[{"text":"For binarized images only.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ccittrlew","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions\/ccittrlew","navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcittrlew","kind":"identifier"}],"title":"SBSDKTIFFImageWriterCompressionOptions.ccittrlew"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterCompressionOptions/adobe_deflate":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/adobe_deflate","role":"symbol","abstract":[{"text":"For both colored and binarized images.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"adobe_deflate","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions\/adobe_deflate","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsAdobe_deflate"}],"title":"SBSDKTIFFImageWriterCompressionOptions.adobe_deflate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterCompressionOptions":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions","title":"SBSDKTIFFImageWriterCompressionOptions","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions","kind":"symbol","abstract":[{"text":"The TIFF compression algorithms.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterCompressionOptions/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/Equatable-Implementations","role":"collectionGroup","abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions\/equatable-implementations","title":"Equatable Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterCompressionOptions/lzw":{"type":"topic","abstract":[{"text":"For both colored and binarized images.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions\/lzw","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/lzw","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lzw"}],"kind":"symbol","title":"SBSDKTIFFImageWriterCompressionOptions.lzw","navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptionsLzw","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterCompressionOptions/ccitt_t4":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ccitt_t4","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccitt_t4","abstract":[{"type":"text","text":"For binarized images only."}],"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions\/ccitt_t4","navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcitt_t4","kind":"identifier"}],"title":"SBSDKTIFFImageWriterCompressionOptions.ccitt_t4","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKTIFFImageWriterCompressionOptions"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/adobe_deflate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccitt_t4","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccitt_t6","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittrle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittrlew","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/deflate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/lzw","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/none","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/packbits"]}],"path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"SBSDKTIFFImageWriterCompressionOptionsDeflate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1deflate\/title"},{"value":[{"text":"SBSDKTIFFImageWriterCompressionOptionsDeflate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1deflate\/fragments"},{"value":"SBSDKTIFFImageWriterCompressionOptionsCcittrle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccittrle\/title"},{"value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsCcittrle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccittrle\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1packbits\/title","op":"replace","value":"SBSDKTIFFImageWriterCompressionOptionsPackbits"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1packbits\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsPackbits"}]},{"op":"replace","value":"SBSDKTIFFImageWriterCompressionOptionsCcitt_t6","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccitt_t6\/title"},{"op":"replace","value":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcitt_t6","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccitt_t6\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1none\/title","value":"SBSDKTIFFImageWriterCompressionOptionsNone"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1none\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsNone"}]},{"value":"SBSDKTIFFImageWriterCompressionOptionsCcittrlew","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccittrlew\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccittrlew\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsCcittrlew"}]},{"op":"replace","value":"SBSDKTIFFImageWriterCompressionOptionsAdobe_deflate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1adobe_deflate\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1adobe_deflate\/fragments","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsAdobe_deflate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions\/title","value":"SBSDKTIFFImageWriterCompressionOptions","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1lzw\/title","op":"replace","value":"SBSDKTIFFImageWriterCompressionOptionsLzw"},{"value":[{"text":"SBSDKTIFFImageWriterCompressionOptionsLzw","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1lzw\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccitt_t4\/title","value":"SBSDKTIFFImageWriterCompressionOptionsCcitt_t4"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccitt_t4\/fragments","value":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcitt_t4","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}