{"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesB\/requiredDocumentType"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategory"],"kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB"}]}],"kind":"declarations"}],"metadata":{"title":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB","navigatorTitle":[{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB","kind":"identifier"}],"symbolKind":"class","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelDeDriverLicenseBackCategoriesB","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Class"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategoriesb"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategoriesb"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"DeDriverLicenseBack.Categories.B"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesB"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseBackCategoriesB":{"title":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB","kind":"identifier"}],"abstract":[{"text":"DeDriverLicenseBack.Categories.B","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategoriesb","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesB"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseBackCategoriesB/requiredDocumentType":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategoriesb\/requireddocumenttype","navigatorTitle":[{"text":"requiredDocumentType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"requiredDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesB\/requiredDocumentType","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The name of the wrapped document type."}],"title":"requiredDocumentType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseBackCategory":{"title":"SBSDKDocumentsModelDeDriverLicenseBackCategory","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategory","kind":"identifier"}],"abstract":[{"type":"text","text":"A category row from the categories table"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategory","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategory","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategory"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseBackCategoriesB/initWithGenericDocument:":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategoriesb\/initwithgenericdocument:","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesB\/initWithGenericDocument:","kind":"symbol","role":"symbol","abstract":[],"title":"initWithGenericDocument:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesB\/requiredDocumentType"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesB\/initWithGenericDocument:"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategory"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategory","text":"SBSDKDocumentsModelDeDriverLicenseBackCategory","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelDeDriverLicenseBackCategory"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesB\/title","value":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesB\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesB\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesB~1requiredDocumentType\/title","value":"requiredDocumentType","op":"replace"},{"value":[{"kind":"identifier","text":"requiredDocumentType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesB~1requiredDocumentType\/fragments","op":"replace"},{"value":"SBSDKDocumentsModelDeDriverLicenseBackCategory","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategory\/title"},{"value":[{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategory\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategory\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseBackCategory"}]}]}]}