{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"type":"text","text":"The country types to be used with the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters","isActive":true},{"type":"text","text":"."}],"topicSections":[{"title":"Type Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/allTypes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/austria","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/belgium","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/bulgaria","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/croatia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/cyprus","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/czechRepublic","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/denmark","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/estonia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/finland","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/france","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/germany","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/greece","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/hungary","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/ireland","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/italy","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/latvia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/lithuania","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/luxembourg","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/malta","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/netherlands","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/poland","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/portugal","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/romania","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/slovakia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/slovenia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/spain","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/sweden","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/switzerland"],"anchor":"Type-Properties"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","kind":"relationships"}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Class","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"identifier"}],"title":"SBSDKHealthInsuranceCardCountryType","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","role":"symbol","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardCountryType","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardCountryType"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/finland":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"finland","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/finland","kind":"symbol","title":"finland","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/finland","abstract":[{"text":"The country named Finland.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"finland"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/austria":{"abstract":[{"type":"text","text":"The country named Austria."}],"type":"topic","title":"austria","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"austria"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"austria","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/austria","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/austria"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/germany":{"navigatorTitle":[{"text":"germany","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/germany","abstract":[{"text":"The country named Germany.","type":"text"}],"title":"germany","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/germany","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"germany","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/belgium":{"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/belgium","title":"belgium","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"belgium"},{"text":": ","kind":"text"},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"navigatorTitle":[{"text":"belgium","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"The country named Belgium.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/belgium"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/latvia":{"abstract":[{"type":"text","text":"The country named Latvia."}],"type":"topic","title":"latvia","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"latvia"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"latvia","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/latvia","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/latvia"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/slovakia":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"slovakia"},{"kind":"text","text":": "},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/slovakia","role":"symbol","title":"slovakia","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/slovakia","abstract":[{"text":"The country named Slovakia.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"slovakia"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType","navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardCountryType"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype","abstract":[{"type":"text","text":"The country types to be used with the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters","isActive":true},{"text":".","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardCountryType"}],"kind":"symbol","title":"SBSDKHealthInsuranceCardCountryType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/italy":{"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/italy","title":"italy","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"italy","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"navigatorTitle":[{"text":"italy","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"The country named Italy.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/italy"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/netherlands":{"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/netherlands","navigatorTitle":[{"kind":"identifier","text":"netherlands"}],"title":"netherlands","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/netherlands","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"netherlands","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"role":"symbol","abstract":[{"type":"text","text":"The country named Netherlands."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/estonia":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"estonia"},{"text":": ","kind":"text"},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/estonia","kind":"symbol","title":"estonia","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/estonia","abstract":[{"text":"The country named Estonia.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"estonia","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/slovenia":{"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/slovenia","title":"slovenia","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"slovenia","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"navigatorTitle":[{"text":"slovenia","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"The country named Slovenia.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/slovenia"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/romania":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"romania"},{"text":": ","kind":"text"},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/romania","kind":"symbol","title":"romania","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/romania","abstract":[{"text":"The country named Romania.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"romania"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/portugal":{"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/portugal","title":"portugal","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"portugal","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"navigatorTitle":[{"text":"portugal","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"The country named Portugal.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/portugal"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/name":{"type":"topic","fragments":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/name","kind":"symbol","title":"name","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/name","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/poland":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/poland","title":"poland","navigatorTitle":[{"text":"poland","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/poland","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"poland","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","text":"SBSDKHealthInsuranceCardCountryType"}],"abstract":[{"text":"The country named Poland.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerParameters":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters","title":"SBSDKHealthInsuranceCardRecognizerParameters","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters","abstract":[{"type":"text","text":"The health insurance card recognizer configuration."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerParameters"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerParameters"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/france":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"france"},{"text":": ","kind":"text"},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/france","kind":"symbol","title":"france","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/france","abstract":[{"text":"The country named France.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"france","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/lithuania":{"navigatorTitle":[{"kind":"identifier","text":"lithuania"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lithuania","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardCountryType"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/lithuania","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/lithuania","kind":"symbol","abstract":[{"text":"The country named Lithuania.","type":"text"}],"title":"lithuania"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/hungary":{"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/hungary","title":"hungary","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"hungary","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"navigatorTitle":[{"text":"hungary","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"The country named Hungary.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/hungary"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/czechRepublic":{"title":"czechRepublic","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"czechRepublic","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/czechRepublic","navigatorTitle":[{"kind":"identifier","text":"czechRepublic"}],"abstract":[{"text":"The country named Czech Republic.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/czechrepublic","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/greece":{"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/greece","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/greece","abstract":[{"type":"text","text":"The country named Greece."}],"title":"greece","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"greece"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"greece"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/bulgaria":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/bulgaria","title":"bulgaria","navigatorTitle":[{"text":"bulgaria","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/bulgaria","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"bulgaria","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardCountryType"}],"abstract":[{"type":"text","text":"The country named Bulgaria."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/malta":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/malta","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/malta","kind":"symbol","abstract":[{"text":"The country named Malta.","type":"text"}],"title":"malta","navigatorTitle":[{"text":"malta","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"malta"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/luxembourg":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"luxembourg"},{"text":": ","kind":"text"},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/luxembourg","kind":"symbol","title":"luxembourg","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/luxembourg","abstract":[{"text":"The country named Luxembourg.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"luxembourg"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/ireland":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ireland","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/ireland","type":"topic","title":"ireland","kind":"symbol","navigatorTitle":[{"text":"ireland","kind":"identifier"}],"abstract":[{"text":"The country named Ireland.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/ireland","role":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/sweden":{"abstract":[{"text":"The country named Sweden.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"sweden","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","text":"SBSDKHealthInsuranceCardCountryType"}],"role":"symbol","navigatorTitle":[{"text":"sweden","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/sweden","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/sweden","kind":"symbol","title":"sweden"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/switzerland":{"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/switzerland","title":"switzerland","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"switzerland","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"navigatorTitle":[{"text":"switzerland","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"The country named Switzerland.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/switzerland"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/value":{"type":"topic","fragments":[{"kind":"identifier","text":"value"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/value","kind":"symbol","title":"value","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/value","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/croatia":{"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/croatia","title":"croatia","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"croatia"},{"text":": ","kind":"text"},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"navigatorTitle":[{"text":"croatia","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"The country named Croatia.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/croatia"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/cyprus":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"cyprus","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/cyprus","kind":"symbol","title":"cyprus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/cyprus","abstract":[{"text":"The country named Cyprus.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"cyprus","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/spain":{"navigatorTitle":[{"kind":"identifier","text":"spain"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"spain","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/spain","abstract":[{"text":"The country named Spain.","type":"text"}],"title":"spain","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/spain"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/allTypes":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allTypes"},{"text":": [","kind":"text"},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"},{"kind":"text","text":"]"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/alltypes","navigatorTitle":[{"text":"allTypes","kind":"identifier"}],"abstract":[{"text":"Returns an array of all countries.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/allTypes","role":"symbol","title":"allTypes"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/denmark":{"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/denmark","title":"denmark","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"denmark"},{"text":": ","kind":"text"},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"navigatorTitle":[{"text":"denmark","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"The country named Denmark.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/denmark"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"SBSDKHealthInsuranceCardCountryType","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKHealthInsuranceCardCountryType","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardCountryType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/name","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/value"],"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/allTypes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/austria","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/belgium","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/bulgaria","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/croatia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/cyprus","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/czechRepublic","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/denmark","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/estonia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/finland","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/france","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/germany","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/greece","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/hungary","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/ireland","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/italy","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/latvia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/lithuania","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/luxembourg","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/malta","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/netherlands","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/poland","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/portugal","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/romania","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/slovakia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/slovenia","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/spain","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/sweden","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/switzerland"],"generated":true,"title":"Type Properties","anchor":"Type-Properties"}]},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"finland","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1finland\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1finland\/fragments","value":[{"kind":"identifier","text":"finland"}]},{"value":"austria","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1austria\/title","op":"replace"},{"op":"replace","value":[{"text":"austria","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1austria\/fragments"},{"op":"replace","value":"germany","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1germany\/title"},{"op":"replace","value":[{"text":"germany","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1germany\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1belgium\/title","value":"belgium"},{"value":[{"kind":"identifier","text":"belgium"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1belgium\/fragments"},{"op":"replace","value":"latvia","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1latvia\/title"},{"value":[{"text":"latvia","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1latvia\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1slovakia\/title","value":"slovakia"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1slovakia\/fragments","value":[{"text":"slovakia","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType\/title","value":"SBSDKHealthInsuranceCardCountryType"},{"value":[{"text":"SBSDKHealthInsuranceCardCountryType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType\/navigatorTitle","value":[{"text":"SBSDKHealthInsuranceCardCountryType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1italy\/title","value":"italy","op":"replace"},{"value":[{"text":"italy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1italy\/fragments"},{"op":"replace","value":"netherlands","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1netherlands\/title"},{"op":"replace","value":[{"text":"netherlands","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1netherlands\/fragments"},{"op":"replace","value":"estonia","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1estonia\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1estonia\/fragments","op":"replace","value":[{"text":"estonia","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1slovenia\/title","value":"slovenia","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1slovenia\/fragments","value":[{"kind":"identifier","text":"slovenia"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1romania\/title","op":"replace","value":"romania"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1romania\/fragments","value":[{"kind":"identifier","text":"romania"}],"op":"replace"},{"value":"portugal","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1portugal\/title"},{"value":[{"text":"portugal","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1portugal\/fragments"},{"value":"poland","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1poland\/title"},{"op":"replace","value":[{"text":"poland","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1poland\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/title","op":"replace","value":"SBSDKHealthInsuranceCardRecognizerParameters"},{"value":[{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerParameters"}],"op":"replace"},{"value":"france","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1france\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1france\/fragments","value":[{"kind":"identifier","text":"france"}],"op":"replace"},{"value":"lithuania","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1lithuania\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1lithuania\/fragments","value":[{"kind":"identifier","text":"lithuania"}]},{"value":"hungary","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1hungary\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1hungary\/fragments","value":[{"text":"hungary","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"czechRepublic","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1czechRepublic\/title"},{"value":[{"text":"czechRepublic","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1czechRepublic\/fragments","op":"replace"},{"value":"greece","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1greece\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1greece\/fragments","value":[{"kind":"identifier","text":"greece"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1bulgaria\/title","op":"replace","value":"bulgaria"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1bulgaria\/fragments","value":[{"text":"bulgaria","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1malta\/title","value":"malta"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1malta\/fragments","op":"replace","value":[{"kind":"identifier","text":"malta"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1luxembourg\/title","value":"luxembourg","op":"replace"},{"value":[{"text":"luxembourg","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1luxembourg\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1ireland\/title","op":"replace","value":"ireland"},{"op":"replace","value":[{"kind":"identifier","text":"ireland"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1ireland\/fragments"},{"value":"sweden","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1sweden\/title"},{"value":[{"text":"sweden","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1sweden\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1switzerland\/title","op":"replace","value":"switzerland"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1switzerland\/fragments","value":[{"kind":"identifier","text":"switzerland"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1croatia\/title","value":"croatia"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1croatia\/fragments","value":[{"text":"croatia","kind":"identifier"}]},{"value":"cyprus","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1cyprus\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1cyprus\/fragments","value":[{"text":"cyprus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1spain\/title","value":"spain","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1spain\/fragments","value":[{"kind":"identifier","text":"spain"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1allTypes\/title","op":"replace","value":"allTypes"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1allTypes\/fragments","value":[{"kind":"identifier","text":"allTypes"}],"op":"replace"},{"op":"replace","value":"denmark","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1denmark\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1denmark\/fragments","value":[{"text":"denmark","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}