{"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/displayedAspectRatio","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/finderDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/finderRect","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/finderSafeArea","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/ignoresSafeAreaInsets","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/isAnimatingChanges","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/lineColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/lineCornerRadius","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/lineWidth","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/minimumInset","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/offset","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/preferredHeight","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/secondaryAspectRatio","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/secondaryFinderRect","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/secondaryMinimumInset","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/style-swift.property"],"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/bezierPathConvertedToView(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)"],"generated":true,"anchor":"Type-Methods"},{"title":"Enumerations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum"],"generated":true,"anchor":"Enumerations"}],"abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIView"},{"text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkfinderview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfinderview"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)UIView"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/objc(pl)CALayerDelegate","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/s8SendableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearance","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UICoordinateSpace","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIDynamicItem","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusItem","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusItemContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFinderView"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"class","roleHeading":"Class","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView","title":"SBSDKFinderView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKFinderView","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView"},"references":{"doc://net.doo.ScanbotSDK/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIKit.UICoordinateSpace"},"doc://net.doo.ScanbotSDK/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/preferredHeight":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/preferredHeight","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/preferredheight","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"preferredHeight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"If positive, the receiver will try to maintain the preferred height and the aspect ratio for the finder by dynamically"},{"text":" ","type":"text"},{"type":"text","text":"changing the inset. If negative this property will be ignored."}],"navigatorTitle":[{"kind":"identifier","text":"preferredHeight"}],"title":"preferredHeight"},"doc://net.doo.ScanbotSDK/objc(pl)UIFocusItem":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/finderDelegate":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/finderDelegate","title":"finderDelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKFinderViewDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKFinderViewDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"finderDelegate"}],"abstract":[{"type":"text","text":"The receivers delegate."}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/finderdelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/layoutSubviews":{"navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/layoutSubviews","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/layoutsubviews","title":"layoutSubviews","fragments":[{"kind":"text","text":"- "},{"text":"layoutSubviews","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/finderSafeArea":{"kind":"symbol","type":"topic","role":"symbol","title":"finderSafeArea","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/finderSafeArea","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderSafeArea","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"finderSafeArea"}],"abstract":[{"text":"The area where the finder should be placed in the coordinate system of the receiver.","type":"text"},{"text":" ","type":"text"},{"text":"Is ignored if finder safe area is empty (zero height or width).","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/findersafearea"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/displayedAspectRatio":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayedAspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"abstract":[{"type":"text","text":"The aspect ratio of the viewport (cutout), if set to -1.0, no cutout is drawn."}],"navigatorTitle":[{"kind":"identifier","text":"displayedAspectRatio"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/displayedaspectratio","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/displayedAspectRatio","type":"topic","role":"symbol","title":"displayedAspectRatio"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/init","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/init","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/ignoresSafeAreaInsets":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ignoresSafeAreaInsets","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"If set to "},{"code":"False","type":"codeVoice"},{"text":", the finder is inset by the safe area insets.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Otherwise the safe area inset is ignored."}],"navigatorTitle":[{"text":"ignoresSafeAreaInsets","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/ignoressafeareainsets","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/ignoresSafeAreaInsets","type":"topic","role":"symbol","title":"ignoresSafeAreaInsets"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/lineWidth":{"navigatorTitle":[{"text":"lineWidth","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/lineWidth","title":"lineWidth","abstract":[{"text":"The line width of the receivers border line.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/linewidth","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"lineWidth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}]},"doc://net.doo.ScanbotSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)CALayerDelegate","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/Style-swift.enum":{"navigatorTitle":[{"kind":"identifier","text":"Style"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/style-swift.enum","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Style","kind":"identifier"}],"title":"SBSDKFinderView.Style","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum","role":"symbol","abstract":[{"type":"text","text":"The enum that defines the drawing styles of the finder view."}]},"doc://net.doo.ScanbotSDK/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/secondaryMinimumInset":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"secondaryMinimumInset"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"}],"abstract":[{"text":"Minimum inset of the secondary viewport, related to the primary viewport.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"secondaryMinimumInset"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/secondaryminimuminset","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/secondaryMinimumInset","type":"topic","role":"symbol","title":"secondaryMinimumInset"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/drawRect:":{"navigatorTitle":[{"text":"drawRect:","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/drawRect:","title":"drawRect:","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/drawrect:","fragments":[{"kind":"text","text":"- "},{"text":"drawRect:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/style-swift.property":{"navigatorTitle":[{"text":"style","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/style-swift.property","title":"style","abstract":[{"text":"The drawing style of the finder view.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/style-swift.property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ScanbotSDK15SBSDKFinderViewC5StyleO","text":"Style"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/finderRect":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/finderRect","navigatorTitle":[{"text":"finderRect","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The current rect of the finders viewport in the local coordinate system."}],"title":"finderRect","url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/finderrect","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"finderRect","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/safeAreaInsetsDidChange":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"safeAreaInsetsDidChange"}],"abstract":[],"navigatorTitle":[{"text":"safeAreaInsetsDidChange","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/safeareainsetsdidchange","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/safeAreaInsetsDidChange","type":"topic","role":"symbol","title":"safeAreaInsetsDidChange"},"doc://net.doo.ScanbotSDK/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UILargeContentViewerItem"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/bezierPathConvertedToView(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bezierPathConvertedToView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier","text":"UIBezierPath"},{"kind":"text","text":"?"}],"abstract":[{"text":"Creates a bezier path describing the view finders rectangle in the specified views coordinate system.","type":"text"}],"navigatorTitle":[{"text":"bezierPathConvertedToView:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/bezierpathconvertedtoview(_:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/bezierPathConvertedToView(_:)","type":"topic","role":"symbol","title":"bezierPathConvertedToView(_:)"},"doc://net.doo.ScanbotSDK/objc(cs)UIView":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)UIView","title":"UIView"},"doc://net.doo.ScanbotSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://net.doo.ScanbotSDK/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://net.doo.ScanbotSDK/s8SendableP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://net.doo.ScanbotSDK/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusItemContainer","type":"unresolvable","title":"UIKit.UIFocusItemContainer"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/minimumInset":{"navigatorTitle":[{"text":"minimumInset","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/minimumInset","title":"minimumInset","abstract":[{"type":"text","text":"Parameter that defines minimum inset of viewport from edge of the screen."}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/minimuminset","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minimumInset","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/secondaryAspectRatio":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"secondaryAspectRatio"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The secondary aspect ratio of the viewport (cutout), if set to -1.0, no cutout is drawn."}],"navigatorTitle":[{"kind":"identifier","text":"secondaryAspectRatio"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/secondaryaspectratio","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/secondaryAspectRatio","type":"topic","role":"symbol","title":"secondaryAspectRatio"},"doc://net.doo.ScanbotSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/offset":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"offset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"}],"abstract":[{"type":"text","text":"The offset when drawing the finder."}],"navigatorTitle":[{"kind":"identifier","text":"offset"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/offset","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/offset","type":"topic","role":"symbol","title":"offset"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/lineCornerRadius":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lineCornerRadius","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/linecornerradius","title":"lineCornerRadius","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/lineCornerRadius","abstract":[{"text":"The corner radius of the receivers border line.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"lineCornerRadius"}]},"doc://net.doo.ScanbotSDK/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/isAnimatingChanges":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isAnimatingChanges","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":" finder changes will be animated, otherwise no animations will happen."}],"navigatorTitle":[{"text":"isAnimatingChanges","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/isanimatingchanges","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/isAnimatingChanges","type":"topic","role":"symbol","title":"isAnimatingChanges"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/secondaryFinderRect":{"title":"secondaryFinderRect","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"secondaryFinderRect","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"secondaryFinderRect","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The current rect of the finders secondary viewport in the local coordinate system.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/secondaryFinderRect","url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/secondaryfinderrect","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView":{"navigatorTitle":[{"text":"SBSDKFinderView","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIView"},{"text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","type":"topic","title":"SBSDKFinderView","role":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/lineColor":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/linecolor","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/lineColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lineColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"lineColor","abstract":[{"text":"The color of the receivers border line.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"lineColor"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/initWithCoder:":{"title":"initWithCoder:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/initWithCoder:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/initwithcoder:","abstract":[],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)":{"navigatorTitle":[{"text":"potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:offset:","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)","abstract":[{"type":"text","text":"A function, that returns a rect of a finder, if it will be placed in view with certain bounds, with given aspect ratio and insets. Useful for pre-calculations in some animation cases"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/potentialviewfinderrectwithbounds(_:findersafearea:aspectratio:minimuminsets:offset:)","title":"potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"potentialViewFinderRectWithBounds","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"text":"finderSafeArea","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"aspectRatio"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minimumInsets"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"offset","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSCoding":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/initWithFrame:":{"navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/initwithframe:","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/initWithFrame:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"}],"title":"initWithFrame:","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKFinderView"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKFinderView"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFinderView"}],"op":"replace"},{"value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/displayedAspectRatio","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/finderDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/finderRect","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/finderSafeArea","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/ignoresSafeAreaInsets","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/isAnimatingChanges","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/lineColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/lineCornerRadius","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/lineWidth","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/minimumInset","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/offset","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/preferredHeight","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/secondaryAspectRatio","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/secondaryFinderRect","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/secondaryMinimumInset","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/style-swift.property"],"title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/bezierPathConvertedToView(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/drawRect:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/init","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/initWithCoder:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/initWithFrame:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/layoutSubviews","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/safeAreaInsetsDidChange"],"anchor":"Instance-Methods","title":"Instance Methods"},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)"],"generated":true}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)UIView"],"kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"preferredHeight","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1preferredHeight\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1preferredHeight\/fragments","op":"replace","value":[{"text":"preferredHeight","kind":"identifier"}]},{"value":"finderDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1finderDelegate\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1finderDelegate\/fragments","value":[{"text":"finderDelegate","kind":"identifier"}],"op":"replace"},{"value":"finderSafeArea","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1finderSafeArea\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1finderSafeArea\/fragments","value":[{"text":"finderSafeArea","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1displayedAspectRatio\/title","value":"displayedAspectRatio","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1displayedAspectRatio\/fragments","value":[{"kind":"identifier","text":"displayedAspectRatio"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1ignoresSafeAreaInsets\/title","value":"ignoresSafeAreaInsets","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1ignoresSafeAreaInsets\/fragments","value":[{"kind":"identifier","text":"ignoresSafeAreaInsets"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1lineWidth\/title","value":"lineWidth","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1lineWidth\/fragments","value":[{"kind":"identifier","text":"lineWidth"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1secondaryMinimumInset\/title","value":"secondaryMinimumInset","op":"replace"},{"value":[{"kind":"identifier","text":"secondaryMinimumInset"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1secondaryMinimumInset\/fragments"},{"value":"style","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1style-swift.property\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1style-swift.property\/fragments","value":[{"kind":"identifier","text":"style"}]},{"value":"finderRect","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1finderRect\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1finderRect\/fragments","value":[{"text":"finderRect","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1bezierPathConvertedToView(_:)\/title","op":"replace","value":"bezierPathConvertedToView:"},{"value":[{"text":"- ","kind":"text"},{"text":"bezierPathConvertedToView:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1bezierPathConvertedToView(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1minimumInset\/title","value":"minimumInset"},{"value":[{"kind":"identifier","text":"minimumInset"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1minimumInset\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1secondaryAspectRatio\/title","value":"secondaryAspectRatio","op":"replace"},{"op":"replace","value":[{"text":"secondaryAspectRatio","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1secondaryAspectRatio\/fragments"},{"value":"offset","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1offset\/title","op":"replace"},{"op":"replace","value":[{"text":"offset","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1offset\/fragments"},{"value":"lineCornerRadius","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1lineCornerRadius\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1lineCornerRadius\/fragments","value":[{"kind":"identifier","text":"lineCornerRadius"}]},{"value":"isAnimatingChanges","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1isAnimatingChanges\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1isAnimatingChanges\/fragments","value":[{"text":"isAnimatingChanges","kind":"identifier"}],"op":"replace"},{"value":"secondaryFinderRect","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1secondaryFinderRect\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1secondaryFinderRect\/fragments","value":[{"text":"secondaryFinderRect","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/title","op":"replace","value":"SBSDKFinderView"},{"value":[{"kind":"identifier","text":"SBSDKFinderView"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKFinderView"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1lineColor\/title","value":"lineColor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1lineColor\/fragments","value":[{"text":"lineColor","kind":"identifier"}]},{"value":"potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:offset:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:offset:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)\/fragments"}]}]}