{"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/init(polygon:type:barcodeImage:sourceImage:rawTextString:rawBytes:metadata:)"],"title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/age","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/barcodeImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/dateOfDetection","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/extension","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/metadata","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/parsedDocument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/polygon","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/rawBytes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/rawTextString","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/rawTextStringWithExtension","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/sourceImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/type"],"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/SBSDKBarcodeMetadataDatabarStacksizeKey","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/SBSDKBarcodeMetadataEANUPCExtensionKey","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/SBSDKBarcodeMetadataGS1Composite2DTypeKey","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/SBSDKBarcodeMetadataIsGS1MessageKey"],"title":"Type Properties"}],"abstract":[{"type":"text","text":"This class encapsulates the result of a barcode detection."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult"]}],"metadata":{"title":"SBSDKBarcodeScannerResult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Class","symbolKind":"class"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult","interfaceLanguage":"swift"},"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","type":"conformsTo"}],"references":{"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/rawBytes":{"abstract":[{"text":"The raw content bytes of the found barcode.","type":"text"}],"navigatorTitle":[{"text":"rawBytes","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/rawbytes","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/rawBytes","title":"rawBytes","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBytes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/init(polygon:type:barcodeImage:sourceImage:rawTextString:rawBytes:metadata:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/init(polygon:type:barcodeImage:sourceImage:rawTextString:rawBytes:metadata:)","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/init(polygon:type:barcodeimage:sourceimage:rawtextstring:rawbytes:metadata:)","title":"init(polygon:type:barcodeImage:sourceImage:rawTextString:rawBytes:metadata:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"polygon","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeType"},{"kind":"text","text":", "},{"text":"barcodeImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":", ","kind":"text"},{"text":"sourceImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"rawTextString"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"rawBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SD","text":"Dictionary"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":">)","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"initWithPolygon:type:barcodeImage:sourceImage:rawTextString:rawBytes:metadata:","kind":"identifier"}],"abstract":[{"type":"text","text":"Initializer."}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/hash":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/hash","kind":"symbol","title":"hash","fragments":[{"text":"hash","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/hash","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/extension":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"`extension`"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/extension","role":"symbol","abstract":[{"type":"text","text":"The barcodes extension string or nil."}],"type":"topic","title":"extension","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/extension","navigatorTitle":[{"text":"extension","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/dateOfDetection":{"title":"dateOfDetection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/dateOfDetection","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/dateofdetection","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dateOfDetection","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"role":"symbol","navigatorTitle":[{"text":"dateOfDetection","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The date when this barcode has been detected the last time."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/SBSDKBarcodeMetadataDatabarStacksizeKey":{"title":"SBSDKBarcodeMetadataDatabarStacksizeKey","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/SBSDKBarcodeMetadataDatabarStacksizeKey","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/sbsdkbarcodemetadatadatabarstacksizekey","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeMetadataDatabarStacksizeKey","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeMetadataDatabarStacksizeKey","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The barcode metadata key for the Databar stack size."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/barcodeImage":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/barcodeImage","kind":"symbol","title":"barcodeImage","abstract":[{"type":"text","text":"A perspective corrected image of the barcode."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/barcodeimage","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"barcodeImage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/metadata":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/metadata","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/metadata","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"metadata","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata"},{"text":": ","kind":"text"},{"text":"Dictionary","preciseIdentifier":"s:SD","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">","kind":"text"}],"abstract":[{"type":"text","text":"The metadata of the found barcode."}],"type":"topic","title":"metadata"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/SBSDKBarcodeMetadataEANUPCExtensionKey":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/SBSDKBarcodeMetadataEANUPCExtensionKey","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/sbsdkbarcodemetadataeanupcextensionkey","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeMetadataEANUPCExtensionKey","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The barcode metadata key for the EAN\/UPC extensions."}],"navigatorTitle":[{"text":"SBSDKBarcodeMetadataEANUPCExtensionKey","kind":"identifier"}],"title":"SBSDKBarcodeMetadataEANUPCExtensionKey"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/polygon":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/polygon","abstract":[{"type":"text","text":"SBSDKPolygon instance where the barcode was found."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/polygon","title":"polygon","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"polygon"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"}],"navigatorTitle":[{"kind":"identifier","text":"polygon"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/parsedDocument":{"title":"parsedDocument","abstract":[{"text":"The parsed known document format (if parsed successfully).","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/parseddocument","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"parsedDocument","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","kind":"typeIdentifier","text":"SBSDKGenericDocument"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/parsedDocument","kind":"symbol","navigatorTitle":[{"text":"parsedDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/type":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/type","abstract":[{"type":"text","text":"The barcodes type."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeType"}],"type":"topic","navigatorTitle":[{"text":"type","kind":"identifier"}],"title":"type","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/type"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/isEqual:":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/isequal:","title":"isEqual:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/isEqual:","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/SBSDKBarcodeMetadataIsGS1MessageKey":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/sbsdkbarcodemetadataisgs1messagekey","abstract":[{"type":"text","text":"The barcode metadata key for the GS1 messages."}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeMetadataIsGS1MessageKey","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeMetadataIsGS1MessageKey","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/SBSDKBarcodeMetadataIsGS1MessageKey","kind":"symbol","title":"SBSDKBarcodeMetadataIsGS1MessageKey"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/SBSDKBarcodeMetadataGS1Composite2DTypeKey":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/sbsdkbarcodemetadatags1composite2dtypekey","abstract":[{"text":"The barcode metadata key for the GS1 Composite 2D type.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeMetadataGS1Composite2DTypeKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeMetadataGS1Composite2DTypeKey","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/SBSDKBarcodeMetadataGS1Composite2DTypeKey","kind":"symbol","title":"SBSDKBarcodeMetadataGS1Composite2DTypeKey"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/rawTextString":{"kind":"symbol","abstract":[{"type":"text","text":"The raw content value of the found barcode."}],"navigatorTitle":[{"text":"rawTextString","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawTextString"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"rawTextString","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/rawtextstring","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/rawTextString"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/sourceImage":{"title":"sourceImage","abstract":[{"text":"The source image where the barcode has been detected on.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/sourceImage","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"sourceImage","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sourceImage"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/sourceimage","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult","title":"SBSDKBarcodeScannerResult","type":"topic","abstract":[{"type":"text","text":"This class encapsulates the result of a barcode detection."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/age":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/age","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/age","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"age","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"navigatorTitle":[{"text":"age","kind":"identifier"}],"title":"age","abstract":[{"text":"Time interval since the last detection.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/rawTextStringWithExtension":{"title":"rawTextStringWithExtension","type":"topic","abstract":[{"type":"text","text":"The raw content value of the found barcode including an eventual extension from the metadata."}],"role":"symbol","navigatorTitle":[{"text":"rawTextStringWithExtension","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/rawtextstringwithextension","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/rawTextStringWithExtension","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"rawTextStringWithExtension","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKBarcodeScannerResult","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/age","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/barcodeImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/dateOfDetection","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/extension","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/metadata","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/parsedDocument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/polygon","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/rawBytes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/rawTextString","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/rawTextStringWithExtension","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/sourceImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/type"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/init(polygon:type:barcodeImage:sourceImage:rawTextString:rawBytes:metadata:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/isEqual:"]},{"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/SBSDKBarcodeMetadataDatabarStacksizeKey","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/SBSDKBarcodeMetadataEANUPCExtensionKey","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/SBSDKBarcodeMetadataGS1Composite2DTypeKey","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/SBSDKBarcodeMetadataIsGS1MessageKey"]}]},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerResult","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1rawBytes\/title","value":"rawBytes"},{"value":[{"text":"rawBytes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1rawBytes\/fragments"},{"value":"initWithPolygon:type:barcodeImage:sourceImage:rawTextString:rawBytes:metadata:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1init(polygon:type:barcodeImage:sourceImage:rawTextString:rawBytes:metadata:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPolygon:type:barcodeImage:sourceImage:rawTextString:rawBytes:metadata:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1init(polygon:type:barcodeImage:sourceImage:rawTextString:rawBytes:metadata:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1extension\/title","value":"extension"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1extension\/fragments","value":[{"text":"extension","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1dateOfDetection\/title","value":"dateOfDetection"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1dateOfDetection\/fragments","op":"replace","value":[{"text":"dateOfDetection","kind":"identifier"}]},{"value":"SBSDKBarcodeMetadataDatabarStacksizeKey","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1SBSDKBarcodeMetadataDatabarStacksizeKey\/title"},{"value":[{"text":"SBSDKBarcodeMetadataDatabarStacksizeKey","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1SBSDKBarcodeMetadataDatabarStacksizeKey\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1barcodeImage\/title","value":"barcodeImage","op":"replace"},{"value":[{"text":"barcodeImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1barcodeImage\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1metadata\/title","value":"metadata","op":"replace"},{"value":[{"kind":"identifier","text":"metadata"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1metadata\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1SBSDKBarcodeMetadataEANUPCExtensionKey\/title","op":"replace","value":"SBSDKBarcodeMetadataEANUPCExtensionKey"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1SBSDKBarcodeMetadataEANUPCExtensionKey\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeMetadataEANUPCExtensionKey"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1polygon\/title","op":"replace","value":"polygon"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1polygon\/fragments","value":[{"kind":"identifier","text":"polygon"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1parsedDocument\/title","op":"replace","value":"parsedDocument"},{"value":[{"text":"parsedDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1parsedDocument\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1type\/title","value":"type","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1type\/fragments","value":[{"kind":"identifier","text":"type"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1SBSDKBarcodeMetadataIsGS1MessageKey\/title","value":"SBSDKBarcodeMetadataIsGS1MessageKey"},{"value":[{"text":"SBSDKBarcodeMetadataIsGS1MessageKey","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1SBSDKBarcodeMetadataIsGS1MessageKey\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1SBSDKBarcodeMetadataGS1Composite2DTypeKey\/title","value":"SBSDKBarcodeMetadataGS1Composite2DTypeKey","op":"replace"},{"value":[{"text":"SBSDKBarcodeMetadataGS1Composite2DTypeKey","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1SBSDKBarcodeMetadataGS1Composite2DTypeKey\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1rawTextString\/title","value":"rawTextString","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1rawTextString\/fragments","value":[{"text":"rawTextString","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1sourceImage\/title","op":"replace","value":"sourceImage"},{"op":"replace","value":[{"kind":"identifier","text":"sourceImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1sourceImage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/title","value":"SBSDKBarcodeScannerResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1age\/title","value":"age","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1age\/fragments","value":[{"text":"age","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1rawTextStringWithExtension\/title","value":"rawTextStringWithExtension","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1rawTextStringWithExtension\/fragments","value":[{"text":"rawTextStringWithExtension","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}