{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalplanstandardsubheadingfieldtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalplanstandardsubheadingfieldtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The german medical plan document subheading information description field type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType"}],"title":"SBSDKMedicalPlanStandardSubheadingFieldType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalPlanStandardSubheadingFieldType","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType\/keyWords","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType\/subheadingFreeText"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType\/init(rawValue:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType\/encode(to:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanStandardSubheadingFieldType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalplanstandardsubheadingfieldtype\/equatable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanStandardSubheadingFieldType":{"role":"symbol","title":"SBSDKMedicalPlanStandardSubheadingFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType"}],"abstract":[{"type":"text","text":"The german medical plan document subheading information description field type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalplanstandardsubheadingfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanStandardSubheadingFieldType/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalplanstandardsubheadingfieldtype\/encode(to:)"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanStandardSubheadingFieldType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalplanstandardsubheadingfieldtype\/rawrepresentable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanStandardSubheadingFieldType/subheadingFreeText":{"role":"symbol","title":"SBSDKMedicalPlanStandardSubheadingFieldType.subheadingFreeText","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subheadingFreeText"}],"abstract":[{"type":"text","text":"The free text."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType\/subheadingFreeText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldTypeSubheadingFreeText"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalplanstandardsubheadingfieldtype\/subheadingfreetext"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanStandardSubheadingFieldType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalplanstandardsubheadingfieldtype\/init(rawvalue:)"},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanStandardSubheadingFieldType/keyWords":{"role":"symbol","title":"SBSDKMedicalPlanStandardSubheadingFieldType.keyWords","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyWords"}],"abstract":[{"type":"text","text":"The keywords."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType\/keyWords","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldTypeKeyWords"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalplanstandardsubheadingfieldtype\/keywords"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalPlanStandardSubheadingFieldType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType\/keyWords","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType\/subheadingFreeText"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanStandardSubheadingFieldType\/title","value":"SBSDKMedicalPlanStandardSubheadingFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanStandardSubheadingFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanStandardSubheadingFieldType~1subheadingFreeText\/title","value":"SBSDKMedicalPlanStandardSubheadingFieldTypeSubheadingFreeText"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanStandardSubheadingFieldType~1subheadingFreeText\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldTypeSubheadingFreeText"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanStandardSubheadingFieldType~1keyWords\/title","value":"SBSDKMedicalPlanStandardSubheadingFieldTypeKeyWords"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanStandardSubheadingFieldType~1keyWords\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldTypeKeyWords"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}