{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStepResult","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerStepResult","symbolKind":"class","role":"symbol","title":"SBSDKUITextDataScannerStepResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUITextDataScannerStepResult"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUITextDataScannerStepResult"}]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStepResult\/confidence","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStepResult\/stepTag","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStepResult\/text"],"title":"Instance Properties"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUITextDataScannerStepResult","kind":"identifier"}]}],"kind":"declarations"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"kind":"symbol","abstract":[{"text":"Encapsulates the result of the text recognition of a ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","isActive":true},{"type":"text","text":"s workflow step."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerstepresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerstepresult"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController":{"abstract":[{"text":"A highly customizable camera-based view controller to recognize and validate a small rectangular text area in realtime.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller","role":"symbol","title":"SBSDKUITextDataScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerStepResult/stepTag":{"abstract":[{"type":"text","text":"The tag of the workflow step."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStepResult\/stepTag","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerstepresult\/steptag","role":"symbol","title":"stepTag","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"stepTag","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","navigatorTitle":[{"text":"stepTag","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerStepResult/text":{"abstract":[{"text":"The recognized and validated text.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStepResult\/text","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerstepresult\/text","type":"topic","role":"symbol","title":"text","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerStepResult":{"abstract":[{"type":"text","text":"Encapsulates the result of the text recognition of a "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","isActive":true,"type":"reference"},{"type":"text","text":"s workflow step."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStepResult","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerstepresult","role":"symbol","title":"SBSDKUITextDataScannerStepResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUITextDataScannerStepResult"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUITextDataScannerStepResult","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerStepResult/confidence":{"abstract":[{"text":"The confidence of the text recognition.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStepResult\/confidence","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerstepresult\/confidence","role":"symbol","title":"confidence","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"confidence","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"confidence"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"SBSDKUITextDataScannerStepResult","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUITextDataScannerStepResult"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUITextDataScannerStepResult","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStepResult\/confidence","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStepResult\/stepTag","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStepResult\/text"]}],"op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKUITextDataScannerStepResult","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"op":"replace","value":"SBSDKUITextDataScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/fragments"},{"value":"stepTag","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStepResult~1stepTag\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStepResult~1stepTag\/fragments","value":[{"text":"stepTag","kind":"identifier"}],"op":"replace"},{"value":"text","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStepResult~1text\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStepResult~1text\/fragments","op":"replace","value":[{"text":"text","kind":"identifier"}]},{"value":"SBSDKUITextDataScannerStepResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStepResult\/title","op":"replace"},{"value":[{"text":"SBSDKUITextDataScannerStepResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStepResult\/fragments"},{"value":"confidence","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStepResult~1confidence\/title"},{"op":"replace","value":[{"kind":"identifier","text":"confidence"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStepResult~1confidence\/fragments"}]}]}