{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPDFAttributes","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"inlineContent":[{"type":"text","text":"Can read PDF metadata from existing PDF files and store modified PDF metadata to existing PDF files."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"Represents the metadata attributes of PDF files, e.g. author, creator, title etc."}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/init(author:creator:title:subject:keywords:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/init(pdfURL:)"],"title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/author","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/creator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/keywords","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/keywordsString","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/subject","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/title"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/saveToPDFFile(at:)"]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfattributes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfattributes"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"SBSDKPDFAttributes","navigatorTitle":[{"text":"SBSDKPDFAttributes","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFAttributes","roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFAttributes"}]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"references":{"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFAttributes/saveToPDFFile(at:)":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfattributes\/savetopdffile(at:)","type":"topic","role":"symbol","abstract":[{"text":"Overwrites an existing PDF files metadata with the receiver. Throws an error if the file could not be found or contains other than PDF data.","type":"text"}],"title":"saveToPDFFile(at:)","navigatorTitle":[{"text":"saveToPDFFileAt:error:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/saveToPDFFile(at:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"saveToPDFFile"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFAttributes/init(author:creator:title:subject:keywords:)":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfattributes\/init(author:creator:title:subject:keywords:)","title":"init(author:creator:title:subject:keywords:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/init(author:creator:title:subject:keywords:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Designated initializer."}],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"author","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"creator","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"subject","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"keywords","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]?)"}],"navigatorTitle":[{"text":"initWithAuthor:creator:title:subject:keywords:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFAttributes/creator":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfattributes\/creator","title":"creator","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/creator","role":"symbol","abstract":[{"text":"The creator of the PDF. Optional.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"creator"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"creator","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFAttributes/keywords":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfattributes\/keywords","title":"keywords","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/keywords","type":"topic","role":"symbol","abstract":[{"text":"The keywords of the PDF. Optional","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"keywords","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"text":"keywords","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFAttributes/init(pdfURL:)":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfattributes\/init(pdfurl:)","title":"init(pdfURL:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/init(pdfURL:)","type":"topic","role":"symbol","abstract":[{"text":"Reads the metadata attributes from an existing PDF file. Returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the file could not be found or contains other than PDF data.","type":"text"}],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"pdfURL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPdfURL:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFAttributes/author":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"author","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfattributes\/author","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/author","title":"author","navigatorTitle":[{"kind":"identifier","text":"author"}],"abstract":[{"type":"text","text":"The author of the PDF. Optional."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFAttributes/keywordsString":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"keywordsString","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/keywordsString","navigatorTitle":[{"kind":"identifier","text":"keywordsString"}],"title":"keywordsString","url":"\/documentation\/scanbotsdk\/sbsdkpdfattributes\/keywordsstring","abstract":[{"type":"text","text":"The receivers keywords as comma-separated string. Optional. Readonly."}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFAttributes/title":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfattributes\/title","title":"title","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/title","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The title of the PDF. Optional."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"title"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"title","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFAttributes":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFAttributes"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFAttributes"}],"title":"SBSDKPDFAttributes","url":"\/documentation\/scanbotsdk\/sbsdkpdfattributes","abstract":[{"type":"text","text":"Represents the metadata attributes of PDF files, e.g. author, creator, title etc."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFAttributes/subject":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfattributes\/subject","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/subject","navigatorTitle":[{"text":"subject","kind":"identifier"}],"title":"subject","abstract":[{"type":"text","text":"The subject of the PDF. Optional."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"subject"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"SBSDKPDFAttributes","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKPDFAttributes","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFAttributes"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/author","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/creator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/keywords","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/keywordsString","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/subject","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/title"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/init(author:creator:title:subject:keywords:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/init(pdfURL:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/saveToPDFFile(at:)"],"title":"Instance Methods"}]},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"SBSDKPDFAttributes","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1saveToPDFFile(at:)\/title","op":"replace","value":"saveToPDFFileAt:error:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"saveToPDFFileAt:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1saveToPDFFile(at:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1init(author:creator:title:subject:keywords:)\/title","value":"initWithAuthor:creator:title:subject:keywords:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithAuthor:creator:title:subject:keywords:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1init(author:creator:title:subject:keywords:)\/fragments"},{"value":"creator","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1creator\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1creator\/fragments","value":[{"kind":"identifier","text":"creator"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1keywords\/title","value":"keywords"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1keywords\/fragments","value":[{"text":"keywords","kind":"identifier"}]},{"op":"replace","value":"initWithPdfURL:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1init(pdfURL:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1init(pdfURL:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPdfURL:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1author\/title","value":"author"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1author\/fragments","value":[{"kind":"identifier","text":"author"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1keywordsString\/title","value":"keywordsString","op":"replace"},{"value":[{"text":"keywordsString","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1keywordsString\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1title\/title","op":"replace","value":"title"},{"value":[{"text":"title","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1title\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/title","value":"SBSDKPDFAttributes","op":"replace"},{"value":[{"text":"SBSDKPDFAttributes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/fragments"},{"op":"replace","value":"subject","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1subject\/title"},{"value":[{"text":"subject","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes~1subject\/fragments"}]}]}