{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2IntroductionScreenConfiguration) ","kind":"text"},{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2IntroductionScreenConfiguration","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Class","title":"SBSDKUI2IntroductionScreenConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IntroductionScreenConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2IntroductionScreenConfiguration","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IntroductionScreenConfiguration","symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/init(backgroundColor:dividerColor:handlerColor:showAutomatically:topBarDoneButton:title:subtitle:items:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/init(from:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/backgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/dividerColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/handlerColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/items","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/showAutomatically","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/subtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/title","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/topBarDoneButton"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/toJson()"],"anchor":"Instance-Methods","generated":true}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"sections":[],"abstract":[{"type":"text","text":"Configuration of the introduction screen for the document scanner."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration/fromJsonWithJson:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration\/fromjsonwithjson:","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"abstract":[],"title":"fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/fromJsonWithJson:","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration/title":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/title","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration\/title","role":"symbol","navigatorTitle":[{"text":"title","kind":"identifier"}],"abstract":[{"text":"The title of the introduction screen, located in the top bar.","type":"text"}],"title":"title","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration/handlerColor":{"url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration\/handlercolor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/handlerColor","role":"symbol","abstract":[{"text":"The handle color of the introduction screen.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is “?sbColorOutline”"}],"navigatorTitle":[{"kind":"identifier","text":"handlerColor"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handlerColor"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"}],"type":"topic","kind":"symbol","title":"handlerColor"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration/init()":{"url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"title":"init()","kind":"symbol","type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/init()","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration/toJson()":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration\/tojson()","title":"toJson()","kind":"symbol","navigatorTitle":[{"text":"toJson","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/toJson()","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration/subtitle":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"subtitle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"}],"role":"symbol","abstract":[{"text":"The subtitle of the introduction screen.","type":"text"}],"navigatorTitle":[{"text":"subtitle","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration\/subtitle","kind":"symbol","title":"subtitle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/subtitle"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration/topBarDoneButton":{"navigatorTitle":[{"text":"topBarDoneButton","kind":"identifier"}],"abstract":[{"text":"Configuration of the ‘done’ button, located in the top bar.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration\/topbardonebutton","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topBarDoneButton"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration"}],"title":"topBarDoneButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/topBarDoneButton","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration/showAutomatically":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration\/showautomatically","title":"showAutomatically","role":"symbol","navigatorTitle":[{"text":"showAutomatically","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/showAutomatically","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAutomatically"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"Determines whether the introduction screen should automatically be shown or not when the scanning session","type":"text"},{"text":" ","type":"text"},{"text":"starts.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is false"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration/init(backgroundColor:dividerColor:handlerColor:showAutomatically:topBarDoneButton:title:subtitle:items:)":{"url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration\/init(backgroundcolor:dividercolor:handlercolor:showautomatically:topbardonebutton:title:subtitle:items:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBackgroundColor:dividerColor:handlerColor:showAutomatically:topBarDoneButton:title:subtitle:items:"}],"abstract":[],"title":"init(backgroundColor:dividerColor:handlerColor:showAutomatically:topBarDoneButton:title:subtitle:items:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dividerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"handlerColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showAutomatically"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topBarDoneButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration"},{"text":", ","kind":"text"},{"text":"title","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"subtitle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"items"},{"text":": [","kind":"text"},{"text":"SBSDKUI2IntroListEntry","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IntroListEntry"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/init(backgroundColor:dividerColor:handlerColor:showAutomatically:topBarDoneButton:title:subtitle:items:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration/isEqual:":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/isEqual:","type":"topic","title":"isEqual:","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration\/isequal:"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration/dividerColor":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration\/dividercolor","title":"dividerColor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dividerColor"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/dividerColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dividerColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"}],"abstract":[{"text":"The divider color of the introduction screen.","type":"text"},{"text":" ","type":"text"},{"text":"Default is “?sbColorOutline”","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration/init(from:)":{"abstract":[],"kind":"symbol","title":"init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier","text":"Decoder"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration\/init(from:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/init(from:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration/hash":{"url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration\/hash","type":"topic","role":"symbol","abstract":[],"title":"hash","fragments":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/hash","kind":"symbol"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Node","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Node"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","abstract":[{"type":"text","text":"Abstract class for all the configurations."}],"title":"SBSDKUI2Node","url":"\/documentation\/scanbotsdk\/sbsdkui2node"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration/backgroundColor":{"url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration\/backgroundcolor","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"backgroundColor"}],"abstract":[{"text":"The background color of the introduction screen.","type":"text"},{"text":" ","type":"text"},{"text":"Default is “?sbColorSurface”","type":"text"}],"title":"backgroundColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"backgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/backgroundColor","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration/items":{"role":"symbol","abstract":[{"text":"Configure the scanning steps of the introduction screen.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration\/items","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/items","navigatorTitle":[{"kind":"identifier","text":"items"}],"title":"items","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"items"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IntroListEntry","kind":"typeIdentifier","text":"SBSDKUI2IntroListEntry"},{"kind":"text","text":"]"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration":{"title":"SBSDKUI2IntroductionScreenConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IntroductionScreenConfiguration"}],"navigatorTitle":[{"text":"SBSDKUI2IntroductionScreenConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration","abstract":[{"type":"text","text":"Configuration of the introduction screen for the document scanner."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKUI2IntroductionScreenConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2IntroductionScreenConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUI2IntroductionScreenConfiguration","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/backgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/dividerColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/handlerColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/items","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/showAutomatically","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/subtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/title","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/topBarDoneButton"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/init(backgroundColor:dividerColor:handlerColor:showAutomatically:topBarDoneButton:title:subtitle:items:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/toJson()"],"anchor":"Instance-Methods","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/fromJsonWithJson:"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2IntroductionScreenConfiguration","kind":"identifier"},{"kind":"text","text":" : "},{"text":"SBSDKUI2Node","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1title\/title","value":"title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1title\/fragments","op":"replace","value":[{"text":"title","kind":"identifier"}]},{"value":"handlerColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1handlerColor\/title"},{"op":"replace","value":[{"kind":"identifier","text":"handlerColor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1handlerColor\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1init()\/title","value":"init","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1toJson()\/title","op":"replace","value":"toJson"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJson"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1toJson()\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1subtitle\/title","op":"replace","value":"subtitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1subtitle\/fragments","value":[{"kind":"identifier","text":"subtitle"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1topBarDoneButton\/title","value":"topBarDoneButton","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1topBarDoneButton\/fragments","value":[{"kind":"identifier","text":"topBarDoneButton"}],"op":"replace"},{"value":"showAutomatically","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1showAutomatically\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1showAutomatically\/fragments","value":[{"kind":"identifier","text":"showAutomatically"}]},{"value":"initWithBackgroundColor:dividerColor:handlerColor:showAutomatically:topBarDoneButton:title:subtitle:items:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1init(backgroundColor:dividerColor:handlerColor:showAutomatically:topBarDoneButton:title:subtitle:items:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1init(backgroundColor:dividerColor:handlerColor:showAutomatically:topBarDoneButton:title:subtitle:items:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBackgroundColor:dividerColor:handlerColor:showAutomatically:topBarDoneButton:title:subtitle:items:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1dividerColor\/title","value":"dividerColor"},{"value":[{"kind":"identifier","text":"dividerColor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1dividerColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title","value":"SBSDKUI2Node"},{"value":[{"kind":"identifier","text":"SBSDKUI2Node"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2Node","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1backgroundColor\/title","op":"replace","value":"backgroundColor"},{"value":[{"text":"backgroundColor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1backgroundColor\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1items\/title","op":"replace","value":"items"},{"value":[{"text":"items","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1items\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration\/title","value":"SBSDKUI2IntroductionScreenConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IntroductionScreenConfiguration"}]},{"op":"replace","value":[{"text":"SBSDKUI2IntroductionScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration\/navigatorTitle"}]}]}