{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Delegate protocol for "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate"],"title":"Inherits From","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeScannerViewControllerDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIViewControllerDelegate","text":"SBSDKUIViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate"}]}],"kind":"declarations"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontrollerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontrollerdelegate"]}],"metadata":{"roleHeading":"Protocol","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUIBarcodeScannerViewControllerDelegate","role":"symbol","platforms":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewControllerDelegate"}],"symbolKind":"protocol","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKUIBarcodeScannerViewControllerDelegate","navigatorTitle":[{"text":"SBSDKUIBarcodeScannerViewControllerDelegate","kind":"identifier"}]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate\/qrBarcodeDetectionViewController(_:didDetect:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate\/qrBarcodeDetectionViewController(_:shouldHighlightResult:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate\/qrBarcodeDetectionViewControllerDidCancel(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate\/qrBarcodeDetectionViewControllerDidTimeout(_:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewControllerDelegate/qrBarcodeDetectionViewControllerDidTimeout(_:)":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate\/qrBarcodeDetectionViewControllerDidTimeout(_:)","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontrollerdelegate\/qrbarcodedetectionviewcontrollerdidtimeout(_:)","navigatorTitle":[{"kind":"identifier","text":"qrBarcodeDetectionViewControllerDidTimeout:"}],"abstract":[{"text":"Informs the delegate that the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController"},{"type":"text","text":" has been cancelled and dismissed by timeout."}],"type":"topic","title":"qrBarcodeDetectionViewControllerDidTimeout(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"qrBarcodeDetectionViewControllerDidTimeout"},{"text":"(","kind":"text"},{"text":"SBSDKUIBarcodeScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerViewController"},{"text":")","kind":"text"}],"role":"symbol","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewControllerDelegate/qrBarcodeDetectionViewControllerDidCancel(_:)":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate\/qrBarcodeDetectionViewControllerDidCancel(_:)","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontrollerdelegate\/qrbarcodedetectionviewcontrollerdidcancel(_:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"qrBarcodeDetectionViewControllerDidCancel:"}],"abstract":[{"text":"Informs the delegate that the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController"},{"text":" has been cancelled and dismissed.","type":"text"}],"type":"topic","title":"qrBarcodeDetectionViewControllerDidCancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"qrBarcodeDetectionViewControllerDidCancel"},{"text":"(","kind":"text"},{"text":"SBSDKUIBarcodeScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewControllerDelegate":{"title":"SBSDKUIViewControllerDelegate","navigatorTitle":[{"text":"SBSDKUIViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKUIViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontrollerdelegate","abstract":[{"text":"The general delegate protocol for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController"},{"type":"text","text":"-based classes."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewController":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontroller","abstract":[{"text":"An abstract base class for RTU-UI view controllers.","type":"text"}],"title":"SBSDKUIViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIViewController"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewControllerDelegate/qrBarcodeDetectionViewController(_:shouldHighlightResult:)":{"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontrollerdelegate\/qrbarcodedetectionviewcontroller(_:shouldhighlightresult:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate\/qrBarcodeDetectionViewController(_:shouldHighlightResult:)","abstract":[{"text":"Asks the delegate whether to highlight a barcode on the selection overlay or not.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"qrBarcodeDetectionViewController","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerViewController","text":"SBSDKUIBarcodeScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldHighlightResult","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult","kind":"typeIdentifier","text":"SBSDKBarcodeScannerResult"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"deprecated":true,"title":"qrBarcodeDetectionViewController(_:shouldHighlightResult:)","navigatorTitle":[{"text":"qrBarcodeDetectionViewController:shouldHighlightResult:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewControllerDelegate":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate","deprecated":true,"title":"SBSDKUIBarcodeScannerViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodeScannerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewControllerDelegate"}],"kind":"symbol","abstract":[{"type":"text","text":"Delegate protocol for "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewControllerDelegate/qrBarcodeDetectionViewController(_:didDetect:)":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontrollerdelegate\/qrbarcodedetectionviewcontroller(_:diddetect:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate\/qrBarcodeDetectionViewController(_:didDetect:)","deprecated":true,"title":"qrBarcodeDetectionViewController(_:didDetect:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"qrBarcodeDetectionViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUIBarcodeScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerViewController"},{"kind":"text","text":", "},{"text":"didDetect","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKBarcodeScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult"},{"kind":"text","text":"])"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"qrBarcodeDetectionViewController:didDetectResults:"}],"kind":"symbol","abstract":[{"type":"text","text":"Informs the delegate that one or more barcodes have been detected."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewController":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller","deprecated":true,"title":"SBSDKUIBarcodeScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to detect QR and barcodes."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"SBSDKUIBarcodeScannerViewControllerDelegate","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"SBSDKUIBarcodeScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKUIBarcodeScannerViewControllerDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate\/qrBarcodeDetectionViewController(_:didDetect:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate\/qrBarcodeDetectionViewController(_:shouldHighlightResult:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate\/qrBarcodeDetectionViewControllerDidCancel(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate\/qrBarcodeDetectionViewControllerDidTimeout(_:)"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate"],"title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewControllerDelegate"},{"kind":"text","text":" <"},{"text":"SBSDKUIViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIViewControllerDelegate","kind":"typeIdentifier"},{"text":">","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"qrBarcodeDetectionViewControllerDidTimeout:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate~1qrBarcodeDetectionViewControllerDidTimeout(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"qrBarcodeDetectionViewControllerDidTimeout:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate~1qrBarcodeDetectionViewControllerDidTimeout(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate~1qrBarcodeDetectionViewControllerDidCancel(_:)\/title","value":"qrBarcodeDetectionViewControllerDidCancel:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate~1qrBarcodeDetectionViewControllerDidCancel(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"qrBarcodeDetectionViewControllerDidCancel:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewControllerDelegate\/title","value":"SBSDKUIViewControllerDelegate","op":"replace"},{"value":[{"text":"SBSDKUIViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewControllerDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/title","value":"SBSDKUIViewController","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate~1qrBarcodeDetectionViewController(_:shouldHighlightResult:)\/title","value":"qrBarcodeDetectionViewController:shouldHighlightResult:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate~1qrBarcodeDetectionViewController(_:shouldHighlightResult:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"qrBarcodeDetectionViewController:shouldHighlightResult:"}],"op":"replace"},{"value":"SBSDKUIBarcodeScannerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate~1qrBarcodeDetectionViewController(_:didDetect:)\/title","value":"qrBarcodeDetectionViewController:didDetectResults:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate~1qrBarcodeDetectionViewController(_:didDetect:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"qrBarcodeDetectionViewController:didDetectResults:"}],"op":"replace"},{"value":"SBSDKUIBarcodeScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}]}]}]}