{"abstract":[{"text":"Represents the results of an optical character recognition (OCR) operation for a single page.","type":"text"}],"kind":"symbol","sections":[],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/init(text:paragraphs:lines:words:)"],"title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/lines","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/paragraphs","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/text","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/textLayoutRecognizerResult","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/words"],"title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCRPage","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"It contains the recognized text, and arrays for each type of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock","isActive":true},{"text":",","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"as well as an optional result from a page layout analysis."}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"symbolKind":"class","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKOCRPage","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRPage","navigatorTitle":[{"kind":"identifier","text":"SBSDKOCRPage"}],"title":"SBSDKOCRPage"},"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkocrpage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkocrpage"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRPage/lines":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrpage\/lines","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/lines","abstract":[{"text":"The line blocks of the page.","type":"text"}],"title":"lines","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"lines","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKOCRResultBlock","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"lines"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlock":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock","title":"SBSDKOCRResultBlock","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrresultblock","abstract":[{"text":"The partial result of an optical character recognition.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKOCRResultBlock"}],"navigatorTitle":[{"text":"SBSDKOCRResultBlock","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRPage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKOCRPage"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKOCRPage","kind":"identifier"}],"title":"SBSDKOCRPage","abstract":[{"type":"text","text":"Represents the results of an optical character recognition (OCR) operation for a single page."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkocrpage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRPage/init(text:paragraphs:lines:words:)":{"navigatorTitle":[{"text":"initWithText:paragraphs:lines:words:","kind":"identifier"}],"abstract":[{"type":"text","text":"Designated initializer."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/init(text:paragraphs:lines:words:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrpage\/init(text:paragraphs:lines:words:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"paragraphs","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SBSDKOCRResultBlock","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"lines","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SBSDKOCRResultBlock","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"words","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKOCRResultBlock","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock"},{"text":"])","kind":"text"}],"title":"init(text:paragraphs:lines:words:)"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRPage/textLayoutRecognizerResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/textLayoutRecognizerResult","type":"topic","title":"textLayoutRecognizerResult","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textLayoutRecognizerResult","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult","text":"SBSDKTextLayoutRecognizerResult"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The result of the text layout recognition that is sometimes executed before the OCR operation."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkocrpage\/textlayoutrecognizerresult","navigatorTitle":[{"kind":"identifier","text":"textLayoutRecognizerResult"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRPage/text":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/text","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrpage\/text","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The recognized text of the page."}],"navigatorTitle":[{"text":"text","kind":"identifier"}],"title":"text"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRPage/copyWithZone:":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/copyWithZone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrpage\/copywithzone:","role":"symbol","abstract":[],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRPage/paragraphs":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/paragraphs","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paragraphs","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKOCRResultBlock","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrpage\/paragraphs","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The paragraph blocks of the page."}],"navigatorTitle":[{"text":"paragraphs","kind":"identifier"}],"title":"paragraphs"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRPage/words":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/words","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"words","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock","text":"SBSDKOCRResultBlock","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrpage\/words","role":"symbol","abstract":[{"type":"text","text":"The word blocks of the page."}],"navigatorTitle":[{"text":"words","kind":"identifier"}],"title":"words"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"SBSDKOCRPage","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKOCRPage"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKOCRPage","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/lines","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/paragraphs","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/text","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/textLayoutRecognizerResult","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/words"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRPage\/init(text:paragraphs:lines:words:)"]}],"path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"type":"conformsTo"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCRPage","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"lines","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage~1lines\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage~1lines\/fragments","value":[{"kind":"identifier","text":"lines"}],"op":"replace"},{"op":"replace","value":"SBSDKOCRResultBlock","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock\/title"},{"value":[{"kind":"identifier","text":"SBSDKOCRResultBlock"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage\/title","op":"replace","value":"SBSDKOCRPage"},{"value":[{"text":"SBSDKOCRPage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage~1init(text:paragraphs:lines:words:)\/title","value":"initWithText:paragraphs:lines:words:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage~1init(text:paragraphs:lines:words:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithText:paragraphs:lines:words:"}]},{"value":"textLayoutRecognizerResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage~1textLayoutRecognizerResult\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage~1textLayoutRecognizerResult\/fragments","op":"replace","value":[{"text":"textLayoutRecognizerResult","kind":"identifier"}]},{"value":"text","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage~1text\/title"},{"value":[{"kind":"identifier","text":"text"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage~1text\/fragments"},{"value":"paragraphs","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage~1paragraphs\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage~1paragraphs\/fragments","value":[{"kind":"identifier","text":"paragraphs"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage~1words\/title","value":"words"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRPage~1words\/fragments","value":[{"text":"words","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}