{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeTrackedViewPolygonStyle"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeTrackedViewPolygonStyle"}],"title":"SBSDKBarcodeTrackedViewPolygonStyle","navigatorTitle":[{"text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Class","role":"symbol","symbolKind":"class"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle","interfaceLanguage":"swift"},"abstract":[{"text":"A class that represents the style of the polygon rendered around a barcode in ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController"},{"text":".","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/borderWidth","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/cornerRadius","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonBackgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonBackgroundSelectedColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonDrawingEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonSelectedColor"],"title":"Instance Properties"}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"references":{"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewPolygonStyle/polygonSelectedColor":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonSelectedColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"title":"polygonSelectedColor","navigatorTitle":[{"text":"polygonSelectedColor","kind":"identifier"}],"abstract":[{"text":"The color of the barcode polygon when selected.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle\/polygonselectedcolor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonSelectedColor","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewPolygonStyle/polygonBackgroundSelectedColor":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"polygonBackgroundSelectedColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"polygonBackgroundSelectedColor","navigatorTitle":[{"text":"polygonBackgroundSelectedColor","kind":"identifier"}],"abstract":[{"text":"The color of the barcode polygon’s background when selected.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle\/polygonbackgroundselectedcolor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonBackgroundSelectedColor","type":"topic"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayController":{"abstract":[{"type":"text","text":"A class that represents an overlay used for visualizing detected barcodes."},{"text":" ","type":"text"},{"text":"It provides a customizable user interface for displaying barcodes and supports interaction with them.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The overlay can be used to highlight and select barcodes based on user input."}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontroller","title":"SBSDKBarcodeTrackingOverlayController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewPolygonStyle/cornerRadius":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"title":"cornerRadius","navigatorTitle":[{"text":"cornerRadius","kind":"identifier"}],"abstract":[{"text":"The corner radius of the border around the barcode polygon.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle\/cornerradius","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/cornerRadius","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewPolygonStyle/borderWidth":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"borderWidth","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"borderWidth","navigatorTitle":[{"text":"borderWidth","kind":"identifier"}],"abstract":[{"text":"The width of the border around the barcode polygon.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle\/borderwidth","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/borderWidth","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewPolygonStyle":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeTrackedViewPolygonStyle"}],"type":"topic","abstract":[{"text":"A class that represents the style of the polygon rendered around a barcode in ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","isActive":true},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"identifier"}],"kind":"symbol","title":"SBSDKBarcodeTrackedViewPolygonStyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewPolygonStyle/polygonBackgroundColor":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonBackgroundColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"title":"polygonBackgroundColor","navigatorTitle":[{"text":"polygonBackgroundColor","kind":"identifier"}],"abstract":[{"text":"The color of the barcode polygon’s background when not selected.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle\/polygonbackgroundcolor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonBackgroundColor","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewPolygonStyle/init":{"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle\/init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/init","type":"topic"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewPolygonStyle/polygonDrawingEnabled":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygonDrawingEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"polygonDrawingEnabled","navigatorTitle":[{"text":"polygonDrawingEnabled","kind":"identifier"}],"abstract":[{"type":"text","text":"Turns polygon drawing on or off."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle\/polygondrawingenabled","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonDrawingEnabled"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewPolygonStyle/polygonColor":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"title":"polygonColor","navigatorTitle":[{"text":"polygonColor","kind":"identifier"}],"abstract":[{"type":"text","text":"The color of the barcode polygon when not selected."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle\/polygoncolor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonColor","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodeTrackedViewPolygonStyle"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeTrackedViewPolygonStyle"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackedViewPolygonStyle"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/borderWidth","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/cornerRadius","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonBackgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonBackgroundSelectedColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonDrawingEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonSelectedColor"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/init"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"polygonSelectedColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle~1polygonSelectedColor\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle~1polygonSelectedColor\/fragments","value":[{"text":"polygonSelectedColor","kind":"identifier"}],"op":"replace"},{"value":"polygonBackgroundSelectedColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle~1polygonBackgroundSelectedColor\/title","op":"replace"},{"value":[{"kind":"identifier","text":"polygonBackgroundSelectedColor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle~1polygonBackgroundSelectedColor\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/title","value":"SBSDKBarcodeTrackingOverlayController"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/fragments"},{"op":"replace","value":"cornerRadius","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle~1cornerRadius\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle~1cornerRadius\/fragments","value":[{"text":"cornerRadius","kind":"identifier"}]},{"value":"borderWidth","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle~1borderWidth\/title"},{"op":"replace","value":[{"kind":"identifier","text":"borderWidth"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle~1borderWidth\/fragments"},{"value":"SBSDKBarcodeTrackedViewPolygonStyle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeTrackedViewPolygonStyle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle~1polygonBackgroundColor\/title","value":"polygonBackgroundColor","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle~1polygonBackgroundColor\/fragments","op":"replace","value":[{"text":"polygonBackgroundColor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle~1polygonDrawingEnabled\/title","value":"polygonDrawingEnabled"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle~1polygonDrawingEnabled\/fragments","value":[{"text":"polygonDrawingEnabled","kind":"identifier"}],"op":"replace"},{"value":"polygonColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle~1polygonColor\/title","op":"replace"},{"value":[{"text":"polygonColor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle~1polygonColor\/fragments","op":"replace"}]}]}