{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"abstract":[{"text":"The general delegate protocol for ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","isActive":true},{"type":"text","text":"-based classes."}],"metadata":{"title":"SBSDKUIViewControllerDelegate","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIViewControllerDelegate"}],"symbolKind":"protocol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIViewControllerDelegate"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUIViewControllerDelegate","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"relationshipsSections":[{"kind":"relationships","type":"inheritedBy","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewControllerDelegate"],"title":"Inherited By"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuiviewcontrollerdelegate"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuiviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate\/viewControllerShouldCancel(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate\/viewControllerShouldFinish(_:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIViewControllerDelegate"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewControllerDelegate":{"type":"topic","kind":"symbol","title":"SBSDKUILicensePlateScannerViewControllerDelegate","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewControllerDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol for "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontrollerdelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerViewControllerDelegate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewControllerDelegate","type":"topic","title":"SBSDKUIDocumentScannerViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontrollerdelegate","abstract":[{"type":"text","text":"Delegate protocol for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIDocumentScannerViewControllerDelegate"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUIDocumentScannerViewControllerDelegate","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewControllerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeScannerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewControllerDelegate"}],"title":"SBSDKUIBarcodeScannerViewControllerDelegate","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontrollerdelegate","role":"symbol","abstract":[{"text":"Delegate protocol for ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController":{"type":"topic","title":"SBSDKUITextDataScannerViewController","navigatorTitle":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller","kind":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to recognize and validate a small rectangular text area in realtime."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController","type":"topic","navigatorTitle":[{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}],"kind":"symbol","title":"SBSDKUIDocumentScannerViewController","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewControllerDelegate/viewControllerShouldCancel(_:)":{"required":true,"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate\/viewControllerShouldCancel(_:)","title":"viewControllerShouldCancel(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewControllerShouldCancel"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIViewController","kind":"typeIdentifier","text":"SBSDKUIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"viewControllerShouldCancel:"}],"url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontrollerdelegate\/viewcontrollershouldcancel(_:)","abstract":[{"type":"text","text":"Informs the delegate, that the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController"},{"text":" wants to cancel.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewControllerDelegate":{"title":"SBSDKUIViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontrollerdelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate","navigatorTitle":[{"text":"SBSDKUIViewControllerDelegate","kind":"identifier"}],"abstract":[{"text":"The general delegate protocol for ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","isActive":true,"type":"reference"},{"text":"-based classes.","type":"text"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewControllerDelegate":{"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIFinderDocumentScannerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerViewControllerDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewControllerDelegate","title":"SBSDKUIFinderDocumentScannerViewControllerDelegate","type":"topic","abstract":[{"text":"Delegate protocol for ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController","type":"reference"},{"type":"text","text":"."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewController":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller","role":"symbol","deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"title":"SBSDKUIBarcodesBatchScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","type":"topic","abstract":[{"text":"A highly customizable camera-based view controller to detect barcodes batches.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingViewControllerDelegate":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingViewControllerDelegate"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICroppingViewControllerDelegate","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"SBSDKUICroppingViewControllerDelegate","abstract":[{"type":"text","text":"Delegate protocol for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController"},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewControllerDelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewControllerDelegate/viewControllerShouldFinish(_:)":{"type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"viewControllerShouldFinish:"}],"abstract":[{"text":"Informs the delegate, that the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController"},{"type":"text","text":" wants to finish."}],"title":"viewControllerShouldFinish(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate\/viewControllerShouldFinish(_:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontrollerdelegate\/viewcontrollershouldfinish(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewControllerShouldFinish","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIViewController"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewControllerDelegate":{"type":"topic","kind":"symbol","title":"SBSDKUIMRZScannerViewControllerDelegate","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIMRZScannerViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMRZScannerViewControllerDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol for "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontrollerdelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan a single documents of a certain aspect ratio."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}],"kind":"symbol","title":"SBSDKUIFinderDocumentScannerViewController","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to detect QR and barcodes.","type":"text"}],"title":"SBSDKUIBarcodeScannerViewController","deprecated":true,"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewControllerDelegate":{"title":"SBSDKUITextDataScannerViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontrollerdelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUITextDataScannerViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewControllerDelegate","navigatorTitle":[{"text":"SBSDKUITextDataScannerViewControllerDelegate","kind":"identifier"}],"abstract":[{"text":"Delegate protocol for ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewControllerDelegate":{"navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontrollerdelegate","role":"symbol","deprecated":true,"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","kind":"identifier"}],"title":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate","type":"topic","abstract":[{"text":"Delegate protocol for ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","isActive":true},{"type":"text","text":"."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerViewControllerDelegate":{"type":"topic","kind":"symbol","title":"SBSDKUIVINScannerViewControllerDelegate","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIVINScannerViewControllerDelegate"}],"navigatorTitle":[{"text":"SBSDKUIVINScannerViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerviewcontrollerdelegate","abstract":[{"text":"Delegate protocol for ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewController","type":"reference","isActive":true},{"type":"text","text":"."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","title":"SBSDKUIGenericDocumentRecognizerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller","kind":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to recognize generic documents."}],"navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewController"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewController":{"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIViewController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontroller","title":"SBSDKUIViewController","navigatorTitle":[{"text":"SBSDKUIViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"An abstract base class for RTU-UI view controllers."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerViewController":{"title":"SBSDKUIVINScannerViewController","type":"topic","abstract":[{"text":"A highly customizable camera-based view controller to recognize and validate vehicle identification numbers in realtime.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUIVINScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIVINScannerViewController"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerViewControllerDelegate":{"type":"topic","deprecated":true,"kind":"symbol","title":"SBSDKUIHealthInsuranceCardScannerViewControllerDelegate","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKUIHealthInsuranceCardScannerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIHealthInsuranceCardScannerViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannerviewcontrollerdelegate","abstract":[{"type":"text","text":"Delegate protocol for "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController","type":"reference","isActive":true},{"type":"text","text":"."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingViewController":{"type":"topic","kind":"symbol","title":"SBSDKUICroppingViewController","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICroppingViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingViewController"}],"abstract":[{"text":"A highly customizable view controller to edit a pages polygon or the page’s orientation.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewController":{"title":"SBSDKUIMRZScannerViewController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}],"navigatorTitle":[{"text":"SBSDKUIMRZScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to detect machine readable zones."}],"url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerViewController":{"navigatorTitle":[{"text":"SBSDKUIHealthInsuranceCardScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController","role":"symbol","title":"SBSDKUIHealthInsuranceCardScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIHealthInsuranceCardScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannerviewcontroller","kind":"symbol","type":"topic","deprecated":true,"abstract":[{"text":"A view controller for camera-based detection of health insurance cards.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewControllerDelegate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontrollerdelegate","title":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","kind":"symbol","abstract":[{"text":"The delegate protocol for ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController":{"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan vehicle license plates in realtime."}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController","type":"topic","title":"SBSDKUILicensePlateScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUIViewControllerDelegate"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKUIViewControllerDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUIViewControllerDelegate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate\/viewControllerShouldCancel(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewControllerDelegate\/viewControllerShouldFinish(_:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","type":"inheritedBy","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewControllerDelegate"],"title":"Inherited By"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIViewControllerDelegate"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewControllerDelegate\/title","value":"SBSDKUILicensePlateScannerViewControllerDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewControllerDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewControllerDelegate\/title","value":"SBSDKUIDocumentScannerViewControllerDelegate"},{"value":[{"text":"SBSDKUIDocumentScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewControllerDelegate\/fragments"},{"value":"SBSDKUIBarcodeScannerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/title","value":"SBSDKUITextDataScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/fragments","value":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController\/title","value":"SBSDKUIDocumentScannerViewController","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewControllerDelegate~1viewControllerShouldCancel(_:)\/title","value":"viewControllerShouldCancel:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewControllerDelegate~1viewControllerShouldCancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewControllerShouldCancel:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewControllerDelegate\/title","value":"SBSDKUIViewControllerDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewControllerDelegate\/title","value":"SBSDKUIFinderDocumentScannerViewControllerDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewControllerDelegate"}]},{"value":"SBSDKUIBarcodesBatchScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/fragments","value":[{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewControllerDelegate\/title","value":"SBSDKUICroppingViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUICroppingViewControllerDelegate"}],"op":"replace"},{"value":"viewControllerShouldFinish:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewControllerDelegate~1viewControllerShouldFinish(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewControllerDelegate~1viewControllerShouldFinish(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewControllerShouldFinish:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewControllerDelegate\/title","value":"SBSDKUIMRZScannerViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUIMRZScannerViewControllerDelegate"}],"op":"replace"},{"value":"SBSDKUIFinderDocumentScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController\/fragments","value":[{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/title","value":"SBSDKUIBarcodeScannerViewController"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/fragments"},{"value":"SBSDKUITextDataScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUITextDataScannerViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewControllerDelegate\/title","op":"replace","value":"SBSDKUIBarcodesBatchScannerViewControllerDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewControllerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate"}]},{"value":"SBSDKUIVINScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewControllerDelegate\/title"},{"op":"replace","value":[{"text":"SBSDKUIVINScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewControllerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/title","value":"SBSDKUIGenericDocumentRecognizerViewController"},{"value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/fragments","op":"replace"},{"value":"SBSDKUIViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIViewController"}]},{"op":"replace","value":"SBSDKUIVINScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIVINScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewControllerDelegate\/title","value":"SBSDKUIHealthInsuranceCardScannerViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerViewControllerDelegate"}]},{"value":"SBSDKUICroppingViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKUICroppingViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewController\/fragments"},{"value":"SBSDKUIMRZScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKUIMRZScannerViewController","kind":"identifier"}]},{"value":"SBSDKUIHealthInsuranceCardScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewController\/title"},{"value":[{"text":"SBSDKUIHealthInsuranceCardScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewControllerDelegate\/title","value":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/title","value":"SBSDKUILicensePlateScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}],"op":"replace"}]}]}