{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Swiss QR Code Document Field Type"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldType"}],"title":"SBSDKUI2SwissQRCodeDocumentFieldType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2SwissQRCodeDocumentFieldType","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldType"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/additionalBillingInformation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/additionalInfoTrailer","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/additionalInfoUnstructured","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/alternativeProcedureParameter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/amount","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/currency","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorAddressType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorCountry","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorPlace","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorPostalCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorStreetOrAddressLine1","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorStreetOrAddressLine2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/dueDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/encoding","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeeAddressType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeeBuildingOrAddressLine2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeeCountry","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeeName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeePlace","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeePostalCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeeStreetOrAddressLine1","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/iban","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeeAddressType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeeBuildingOrAddressLine2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeeCountry","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeeName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeePlace","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeePostalCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeeStreetOrAddressLine1","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/paymentReference","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/paymentReferenceType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/unknown"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/dueDate":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.dueDate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dueDate"}],"abstract":[{"type":"text","text":"Due Date"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/dueDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDueDate"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/duedate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/debtorName":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.debtorName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debtorName"}],"abstract":[{"type":"text","text":"Debtor Name"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorName"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/debtorname"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/debtorStreetOrAddressLine2":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.debtorStreetOrAddressLine2","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debtorStreetOrAddressLine2"}],"abstract":[{"type":"text","text":"Debtor Street Or Address Line 2"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorStreetOrAddressLine2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorStreetOrAddressLine2"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/debtorstreetoraddressline2"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/paymentReference":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.paymentReference","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentReference"}],"abstract":[{"type":"text","text":"Payment Reference"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/paymentReference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypePaymentReference"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/paymentreference"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/debtorPlace":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.debtorPlace","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debtorPlace"}],"abstract":[{"type":"text","text":"Debtor Place"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorPlace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPlace"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/debtorplace"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/finalPayeePlace":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.finalPayeePlace","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalPayeePlace"}],"abstract":[{"type":"text","text":"Final Payee Place"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeePlace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeePlace"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/finalpayeeplace"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/currency":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.currency","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency"}],"abstract":[{"type":"text","text":"Currency"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/currency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeCurrency"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/currency"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/finalPayeeName":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.finalPayeeName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalPayeeName"}],"abstract":[{"type":"text","text":"Final Payee Name"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeeName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeeName"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/finalpayeename"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.2"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/equatable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/init(rawvalue:)"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/payeeAddressType":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.payeeAddressType","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"payeeAddressType"}],"abstract":[{"type":"text","text":"Payee Address Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeeAddressType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeeAddressType"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/payeeaddresstype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/rawrepresentable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/amount":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.amount","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"amount"}],"abstract":[{"type":"text","text":"Amount"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/amount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeAmount"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/amount"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldType"}],"abstract":[{"type":"text","text":"Swiss QR Code Document Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/payeeCountry":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.payeeCountry","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"payeeCountry"}],"abstract":[{"type":"text","text":"Payee Country"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeeCountry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeeCountry"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/payeecountry"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/debtorCountry":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.debtorCountry","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debtorCountry"}],"abstract":[{"type":"text","text":"Debtor Country"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorCountry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorCountry"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/debtorcountry"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/debtorAddressType":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.debtorAddressType","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debtorAddressType"}],"abstract":[{"type":"text","text":"Debtor Address Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorAddressType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorAddressType"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/debtoraddresstype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/payeeBuildingOrAddressLine2":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.payeeBuildingOrAddressLine2","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"payeeBuildingOrAddressLine2"}],"abstract":[{"type":"text","text":"Payee Building Or Address Line 2"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeeBuildingOrAddressLine2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeeBuildingOrAddressLine2"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/payeebuildingoraddressline2"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/iban":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.iban","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"iban"}],"abstract":[{"type":"text","text":"Iban"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/iban","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeIban"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/iban"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/finalPayeeBuildingOrAddressLine2":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.finalPayeeBuildingOrAddressLine2","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalPayeeBuildingOrAddressLine2"}],"abstract":[{"type":"text","text":"Final Payee Building Or Address Line 2"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeeBuildingOrAddressLine2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeeBuildingOrAddressLine2"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/finalpayeebuildingoraddressline2"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/payeePostalCode":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.payeePostalCode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"payeePostalCode"}],"abstract":[{"type":"text","text":"Payee Postal Code"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeePostalCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeePostalCode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/payeepostalcode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/payeePlace":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.payeePlace","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"payeePlace"}],"abstract":[{"type":"text","text":"Payee Place"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeePlace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeePlace"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/payeeplace"},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/debtorPostalCode":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.debtorPostalCode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debtorPostalCode"}],"abstract":[{"type":"text","text":"Debtor Postal Code"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorPostalCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPostalCode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/debtorpostalcode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/additionalInfoUnstructured":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.additionalInfoUnstructured","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalInfoUnstructured"}],"abstract":[{"type":"text","text":"Additional Info Unstructured"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/additionalInfoUnstructured","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeAdditionalInfoUnstructured"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/additionalinfounstructured"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/finalPayeeStreetOrAddressLine1":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.finalPayeeStreetOrAddressLine1","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalPayeeStreetOrAddressLine1"}],"abstract":[{"type":"text","text":"Final Payee Street Or Address Line 1"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeeStreetOrAddressLine1","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeeStreetOrAddressLine1"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/finalpayeestreetoraddressline1"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/finalPayeeAddressType":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.finalPayeeAddressType","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalPayeeAddressType"}],"abstract":[{"type":"text","text":"Final Payee Address Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeeAddressType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeeAddressType"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/finalpayeeaddresstype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/finalPayeePostalCode":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.finalPayeePostalCode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalPayeePostalCode"}],"abstract":[{"type":"text","text":"Final Payee Postal Code"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeePostalCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeePostalCode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/finalpayeepostalcode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/additionalInfoTrailer":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.additionalInfoTrailer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalInfoTrailer"}],"abstract":[{"type":"text","text":"Additional Info Trailer"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/additionalInfoTrailer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeAdditionalInfoTrailer"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/additionalinfotrailer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/payeeName":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.payeeName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"payeeName"}],"abstract":[{"type":"text","text":"Payee Name"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeeName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeeName"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/payeename"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/encoding":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.encoding","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encoding"}],"abstract":[{"type":"text","text":"Encoding"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/encoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeEncoding"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/encoding"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/alternativeProcedureParameter":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.alternativeProcedureParameter","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alternativeProcedureParameter"}],"abstract":[{"type":"text","text":"Alternative Procedure Parameter"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/alternativeProcedureParameter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeAlternativeProcedureParameter"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/alternativeprocedureparameter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/unknown":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"Unknown"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeUnknown"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/unknown"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/debtorStreetOrAddressLine1":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.debtorStreetOrAddressLine1","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debtorStreetOrAddressLine1"}],"abstract":[{"type":"text","text":"Debtor Street Or Address Line 1"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorStreetOrAddressLine1","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorStreetOrAddressLine1"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/debtorstreetoraddressline1"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/finalPayeeCountry":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.finalPayeeCountry","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalPayeeCountry"}],"abstract":[{"type":"text","text":"Final Payee Country"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeeCountry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeeCountry"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/finalpayeecountry"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/paymentReferenceType":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.paymentReferenceType","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentReferenceType"}],"abstract":[{"type":"text","text":"Payment Reference Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/paymentReferenceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypePaymentReferenceType"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/paymentreferencetype"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/payeeStreetOrAddressLine1":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.payeeStreetOrAddressLine1","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"payeeStreetOrAddressLine1"}],"abstract":[{"type":"text","text":"Payee Street Or Address Line 1"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeeStreetOrAddressLine1","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeeStreetOrAddressLine1"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/payeestreetoraddressline1"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/additionalBillingInformation":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.additionalBillingInformation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalBillingInformation"}],"abstract":[{"type":"text","text":"Additional Billing Information"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/additionalBillingInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeAdditionalBillingInformation"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/additionalbillinginformation"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/additionalBillingInformation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/additionalInfoTrailer","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/additionalInfoUnstructured","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/alternativeProcedureParameter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/amount","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/currency","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorAddressType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorCountry","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorPlace","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorPostalCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorStreetOrAddressLine1","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorStreetOrAddressLine2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/dueDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/encoding","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeeAddressType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeeBuildingOrAddressLine2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeeCountry","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeeName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeePlace","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeePostalCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/finalPayeeStreetOrAddressLine1","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/iban","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeeAddressType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeeBuildingOrAddressLine2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeeCountry","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeeName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeePlace","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeePostalCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/payeeStreetOrAddressLine1","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/paymentReference","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/paymentReferenceType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/unknown"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1dueDate\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeDueDate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1dueDate\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDueDate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1debtorName\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1debtorName\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1debtorStreetOrAddressLine2\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorStreetOrAddressLine2"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1debtorStreetOrAddressLine2\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorStreetOrAddressLine2"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1paymentReference\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypePaymentReference"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1paymentReference\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypePaymentReference"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1debtorPlace\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPlace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1debtorPlace\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPlace"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1finalPayeePlace\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeePlace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1finalPayeePlace\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeePlace"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1currency\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeCurrency"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1currency\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeCurrency"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1finalPayeeName\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeeName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1finalPayeeName\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeeName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1payeeAddressType\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeeAddressType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1payeeAddressType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeeAddressType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1amount\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeAmount"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1amount\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeAmount"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1payeeCountry\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeeCountry"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1payeeCountry\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeeCountry"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1debtorCountry\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorCountry"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1debtorCountry\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorCountry"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1debtorAddressType\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorAddressType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1debtorAddressType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorAddressType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1payeeBuildingOrAddressLine2\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeeBuildingOrAddressLine2"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1payeeBuildingOrAddressLine2\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeeBuildingOrAddressLine2"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1iban\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeIban"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1iban\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeIban"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1finalPayeeBuildingOrAddressLine2\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeeBuildingOrAddressLine2"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1finalPayeeBuildingOrAddressLine2\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeeBuildingOrAddressLine2"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1payeePostalCode\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeePostalCode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1payeePostalCode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeePostalCode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1payeePlace\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeePlace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1payeePlace\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeePlace"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1debtorPostalCode\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPostalCode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1debtorPostalCode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPostalCode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1additionalInfoUnstructured\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeAdditionalInfoUnstructured"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1additionalInfoUnstructured\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeAdditionalInfoUnstructured"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1finalPayeeStreetOrAddressLine1\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeeStreetOrAddressLine1"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1finalPayeeStreetOrAddressLine1\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeeStreetOrAddressLine1"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1finalPayeeAddressType\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeeAddressType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1finalPayeeAddressType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeeAddressType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1finalPayeePostalCode\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeePostalCode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1finalPayeePostalCode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeePostalCode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1additionalInfoTrailer\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeAdditionalInfoTrailer"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1additionalInfoTrailer\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeAdditionalInfoTrailer"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1payeeName\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeeName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1payeeName\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeeName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1encoding\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeEncoding"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1encoding\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeEncoding"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1alternativeProcedureParameter\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeAlternativeProcedureParameter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1alternativeProcedureParameter\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeAlternativeProcedureParameter"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1unknown\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeUnknown"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1unknown\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1debtorStreetOrAddressLine1\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorStreetOrAddressLine1"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1debtorStreetOrAddressLine1\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorStreetOrAddressLine1"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1finalPayeeCountry\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeeCountry"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1finalPayeeCountry\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeFinalPayeeCountry"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1paymentReferenceType\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypePaymentReferenceType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1paymentReferenceType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypePaymentReferenceType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1payeeStreetOrAddressLine1\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeeStreetOrAddressLine1"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1payeeStreetOrAddressLine1\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypePayeeStreetOrAddressLine1"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1additionalBillingInformation\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeAdditionalBillingInformation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1additionalBillingInformation\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeAdditionalBillingInformation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}