{"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKBarcodeScannerViewControllerDelegate","roleHeading":"Protocol","modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"protocol","title":"SBSDKBarcodeScannerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}]},"relationshipsSections":[{"title":"Conforming Types","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController"],"type":"conformingTypes","kind":"relationships"}],"abstract":[{"text":"The delegate protocol of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController"},{"text":" that provides methods for","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"enabling\/disabling detection and managing detected barcodes."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontrollerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontrollerdelegate"]}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate\/barcodeScannerController(_:didDetectBarcodes:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate\/barcodeScannerController(_:filterResults:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate\/barcodeScannerControllerShouldDetectBarcodes(_:)"],"anchor":"Instance-Methods","generated":true}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewControllerDelegate/barcodeScannerController(_:filterResults:)":{"type":"topic","kind":"symbol","abstract":[{"text":"Asks the delegate to filter the detected barcodes.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate\/barcodeScannerController(_:filterResults:)","required":true,"role":"symbol","title":"barcodeScannerController(_:filterResults:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeScannerController"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController"},{"text":", ","kind":"text"},{"text":"filterResults","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult","kind":"typeIdentifier","text":"SBSDKBarcodeScannerResult"},{"text":"]) -> [","kind":"text"},{"text":"SBSDKBarcodeScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult"},{"kind":"text","text":"]"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontrollerdelegate\/barcodescannercontroller(_:filterresults:)","navigatorTitle":[{"kind":"identifier","text":"barcodeScannerController:filterResults:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewControllerDelegate/barcodeScannerControllerShouldDetectBarcodes(_:)":{"title":"barcodeScannerControllerShouldDetectBarcodes(_:)","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontrollerdelegate\/barcodescannercontrollershoulddetectbarcodes(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate\/barcodeScannerControllerShouldDetectBarcodes(_:)","abstract":[{"type":"text","text":"Asks the delegate if the receiver should detect barcodes on the next video frame."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"barcodeScannerControllerShouldDetectBarcodes","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController","kind":"typeIdentifier","text":"SBSDKBarcodeScannerViewController"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"barcodeScannerControllerShouldDetectBarcodes:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController":{"title":"SBSDKBarcodeScannerViewController","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller","type":"topic","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to show a camera screen with the barcode detector.","type":"text"}],"navigatorTitle":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewControllerDelegate":{"title":"SBSDKBarcodeScannerViewControllerDelegate","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate","type":"topic","abstract":[{"type":"text","text":"The delegate protocol of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController"},{"text":" that provides methods for","type":"text"},{"text":" ","type":"text"},{"text":"enabling\/disabling detection and managing detected barcodes.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewControllerDelegate"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewController":{"kind":"symbol","title":"SBSDKUIBarcodeScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"type":"topic","role":"symbol","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to detect QR and barcodes.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewController":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller","role":"symbol","deprecated":true,"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to detect barcodes batches."}],"title":"SBSDKUIBarcodesBatchScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewControllerDelegate/barcodeScannerController(_:didDetectBarcodes:)":{"navigatorTitle":[{"kind":"identifier","text":"barcodeScannerController:didDetectBarcodes:"}],"title":"barcodeScannerController(_:didDetectBarcodes:)","required":true,"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontrollerdelegate\/barcodescannercontroller(_:diddetectbarcodes:)","abstract":[{"type":"text","text":"Informs the delegate that the receiver has detected some barcodes."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate\/barcodeScannerController(_:didDetectBarcodes:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeScannerController"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController","text":"SBSDKBarcodeScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDetectBarcodes"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult","text":"SBSDKBarcodeScannerResult"},{"text":"])","kind":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKBarcodeScannerViewControllerDelegate"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewControllerDelegate"}]},{"value":[{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate\/barcodeScannerController(_:didDetectBarcodes:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate\/barcodeScannerController(_:filterResults:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate\/barcodeScannerControllerShouldDetectBarcodes(_:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"op":"replace"},{"op":"replace","value":[{"title":"Conforming Types","kind":"relationships","type":"conformingTypes","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}]}]}},{"value":"barcodeScannerController:filterResults:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate~1barcodeScannerController(_:filterResults:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"barcodeScannerController:filterResults:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate~1barcodeScannerController(_:filterResults:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate~1barcodeScannerControllerShouldDetectBarcodes(_:)\/title","op":"replace","value":"barcodeScannerControllerShouldDetectBarcodes:"},{"value":[{"kind":"text","text":"- "},{"text":"barcodeScannerControllerShouldDetectBarcodes:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate~1barcodeScannerControllerShouldDetectBarcodes(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/title","value":"SBSDKBarcodeScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/fragments","value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate\/title","value":"SBSDKBarcodeScannerViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewControllerDelegate"}]},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate\/navigatorTitle"},{"value":"SBSDKUIBarcodeScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/title","value":"SBSDKUIBarcodesBatchScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/fragments","value":[{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate~1barcodeScannerController(_:didDetectBarcodes:)\/title","op":"replace","value":"barcodeScannerController:didDetectBarcodes:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"barcodeScannerController:didDetectBarcodes:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate~1barcodeScannerController(_:didDetectBarcodes:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}