{"metadata":{"title":"SBSDKHealthInsuranceCardScannerViewControllerDelegate","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKHealthInsuranceCardScannerViewControllerDelegate"}],"roleHeading":"Protocol","role":"symbol","platforms":[],"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardScannerViewControllerDelegate","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKHealthInsuranceCardScannerViewControllerDelegate"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The delegation protocol for the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardScannerViewController","isActive":true},{"text":" class.","type":"text"}],"deprecationSummary":[{"inlineContent":[{"text":"Please consider using SBSDKGenericDocumentRecognizerViewController.","type":"text"}],"type":"paragraph"}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardScannerViewControllerDelegate\/healthInsuranceCardScannerViewController(_:didScanHealthInsuranceCard:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardScannerViewControllerDelegate\/healthInsuranceCardScannerViewControllerShouldRecognize(_:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardScannerViewControllerDelegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController"],"type":"conformingTypes","title":"Conforming Types"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardScannerViewControllerDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardscannerviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardscannerviewcontrollerdelegate"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardScannerViewController":{"title":"SBSDKHealthInsuranceCardScannerViewController","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to scan health insurance cards with the camera.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardScannerViewController"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardScannerViewController","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardscannerviewcontroller","deprecated":true,"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardScannerViewControllerDelegate/healthInsuranceCardScannerViewController(_:didScanHealthInsuranceCard:)":{"required":true,"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardscannerviewcontrollerdelegate\/healthinsurancecardscannerviewcontroller(_:didscanhealthinsurancecard:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"healthInsuranceCardScannerViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKHealthInsuranceCardScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardScannerViewController"},{"kind":"text","text":", "},{"text":"didScanHealthInsuranceCard","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognitionResult","text":"SBSDKHealthInsuranceCardRecognitionResult"},{"text":")","kind":"text"}],"role":"symbol","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardScannerViewControllerDelegate\/healthInsuranceCardScannerViewController(_:didScanHealthInsuranceCard:)","navigatorTitle":[{"kind":"identifier","text":"healthInsuranceCardScannerViewController:didScanHealthInsuranceCard:"}],"abstract":[{"text":"Informs the delegate that a health insurance card has been scanned.","type":"text"}],"type":"topic","title":"healthInsuranceCardScannerViewController(_:didScanHealthInsuranceCard:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardScannerViewControllerDelegate":{"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardscannerviewcontrollerdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardScannerViewControllerDelegate"}],"deprecated":true,"title":"SBSDKHealthInsuranceCardScannerViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardScannerViewControllerDelegate","role":"symbol","abstract":[{"text":"The delegation protocol for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardScannerViewController","type":"reference","isActive":true},{"type":"text","text":" class."}],"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardScannerViewControllerDelegate","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerViewController":{"deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerViewController"}],"type":"topic","title":"SBSDKUIHealthInsuranceCardScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerViewController"}],"kind":"symbol","abstract":[{"text":"A view controller for camera-based detection of health insurance cards.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardScannerViewControllerDelegate/healthInsuranceCardScannerViewControllerShouldRecognize(_:)":{"title":"healthInsuranceCardScannerViewControllerShouldRecognize(_:)","navigatorTitle":[{"kind":"identifier","text":"healthInsuranceCardScannerViewControllerShouldRecognize:"}],"abstract":[{"text":"Asks the delegate if the health insurance card scanner should scan the next video frame. Optional.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"healthInsuranceCardScannerViewControllerShouldRecognize","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKHealthInsuranceCardScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardScannerViewController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardScannerViewControllerDelegate\/healthInsuranceCardScannerViewControllerShouldRecognize(_:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardscannerviewcontrollerdelegate\/healthinsurancecardscannerviewcontrollershouldrecognize(_:)","deprecated":true,"type":"topic","required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKHealthInsuranceCardScannerViewControllerDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"value":[{"text":"SBSDKHealthInsuranceCardScannerViewControllerDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"text":"SBSDKHealthInsuranceCardScannerViewControllerDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardScannerViewControllerDelegate\/healthInsuranceCardScannerViewController(_:didScanHealthInsuranceCard:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardScannerViewControllerDelegate\/healthInsuranceCardScannerViewControllerShouldRecognize(_:)"],"title":"Instance Methods"}]},{"value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController"],"type":"conformingTypes","title":"Conforming Types"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKHealthInsuranceCardScannerViewControllerDelegate"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardScannerViewController\/title","value":"SBSDKHealthInsuranceCardScannerViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardScannerViewController\/fragments","value":[{"text":"SBSDKHealthInsuranceCardScannerViewController","kind":"identifier"}]},{"value":"healthInsuranceCardScannerViewController:didScanHealthInsuranceCard:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardScannerViewControllerDelegate~1healthInsuranceCardScannerViewController(_:didScanHealthInsuranceCard:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"healthInsuranceCardScannerViewController:didScanHealthInsuranceCard:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardScannerViewControllerDelegate~1healthInsuranceCardScannerViewController(_:didScanHealthInsuranceCard:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardScannerViewControllerDelegate\/title","value":"SBSDKHealthInsuranceCardScannerViewControllerDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardScannerViewControllerDelegate"}],"op":"replace"},{"value":"SBSDKUIHealthInsuranceCardScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerViewController"}],"op":"replace"},{"value":"healthInsuranceCardScannerViewControllerShouldRecognize:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardScannerViewControllerDelegate~1healthInsuranceCardScannerViewControllerShouldRecognize(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardScannerViewControllerDelegate~1healthInsuranceCardScannerViewControllerShouldRecognize(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"healthInsuranceCardScannerViewControllerShouldRecognize:"}]}]}]}