{"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionAddress","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionAirPollutionDeviceConditions","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionFacilityIdentifier","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionFormOrStickerNumberCurrent","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionFormOrStickerNumberPrevious","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionSmogCertificateIndicator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionStationNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectorIdentificationNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/odometerReadingAtInspection","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/vehicleBodyType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/vehicleMake","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/vehicleModelYear"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Class","symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","title":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"text":"Vehicle Safety Inspection Data. File type “VS”.","type":"text"}],"sections":[],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocument","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"SBSDKGenericDocument","abstract":[{"type":"text","text":"Represents a generic document with fields and sub-documents used for document recognition."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData/inspectionFormOrStickerNumberCurrent":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionFormOrStickerNumberCurrent","navigatorTitle":[{"text":"inspectionFormOrStickerNumberCurrent","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inspectionFormOrStickerNumberCurrent","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/inspectionformorstickernumbercurrent","abstract":[{"text":"Data element ID “INC”. A unique number assigned to a current vehicle inspection form for identification purposes or a preprinted unique number on the motor vehicle inspection sticker currently issued to a motor vehicle which has passed inspection.","type":"text"}],"title":"inspectionFormOrStickerNumberCurrent","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData/initWithGenericDocument:":{"role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithGenericDocument:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/initWithGenericDocument:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/initwithgenericdocument:","title":"initWithGenericDocument:","type":"topic","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData/inspectionFacilityIdentifier":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"inspectionFacilityIdentifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inspectionFacilityIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/inspectionfacilityidentifier","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionFacilityIdentifier","title":"inspectionFacilityIdentifier","abstract":[{"type":"text","text":"Data element ID “IFI”. The unique number assigned to an inspection facility."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData/inspectionAddress":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionAddress","abstract":[{"type":"text","text":"Data element ID “IAN”. The street name and number, city, state and zip code of the inspection facility."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/inspectionaddress","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"inspectionAddress"}],"kind":"symbol","type":"topic","title":"inspectionAddress","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inspectionAddress"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData":{"navigatorTitle":[{"text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata","title":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","abstract":[{"type":"text","text":"Vehicle Safety Inspection Data. File type “VS”."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData/vehicleBodyType":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/vehicleBodyType","abstract":[{"type":"text","text":"Data element ID “VAO”. The general configuration or shape of a vehicle distinguished by characteristics such as number of doors, seats, windows, roofline, and type of top. The vehicle body type is 2- character alphanumeric."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"vehicleBodyType"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"vehicleBodyType","navigatorTitle":[{"text":"vehicleBodyType","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/vehiclebodytype","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData/inspectionFormOrStickerNumberPrevious":{"navigatorTitle":[{"text":"inspectionFormOrStickerNumberPrevious","kind":"identifier"}],"title":"inspectionFormOrStickerNumberPrevious","abstract":[{"type":"text","text":"Data element ID “INP”. The number of the last inspection form excluding the current inspection or the certification number of the last inspection sticker, excluding the current inspection."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/inspectionformorstickernumberprevious","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"inspectionFormOrStickerNumberPrevious","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionFormOrStickerNumberPrevious","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData/inspectionStationNumber":{"navigatorTitle":[{"kind":"identifier","text":"inspectionStationNumber"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/inspectionstationnumber","title":"inspectionStationNumber","abstract":[{"text":"Data element ID “ISN”. Station number performing the inspection.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inspectionStationNumber"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionStationNumber","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData/odometerReadingAtInspection":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/odometerReadingAtInspection","abstract":[{"text":"Data element ID “ORI”. The vehicle’s odometer reading (to the nearest mile or kilometer) at the time of inspection.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/odometerreadingatinspection","role":"symbol","navigatorTitle":[{"text":"odometerReadingAtInspection","kind":"identifier"}],"type":"topic","kind":"symbol","title":"odometerReadingAtInspection","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"odometerReadingAtInspection"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentWrapper":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","kind":"symbol","abstract":[{"type":"text","text":"Base class for strongly-typed "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"},{"text":" wrappers.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"title":"SBSDKGenericDocumentWrapper","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData/vehicleMake":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/vehicleMake","abstract":[{"text":"Data element ID “VAK”. The distinctive (coded) name applied to a group of vehicles by a manufacturer.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"vehicleMake","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"title":"vehicleMake","navigatorTitle":[{"kind":"identifier","text":"vehicleMake"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/vehiclemake","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData/inspectionSmogCertificateIndicator":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionSmogCertificateIndicator","abstract":[{"type":"text","text":"Data element ID “ISC”. An indicator that specifies whether or not the vehicle has a current smog certificate."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inspectionSmogCertificateIndicator"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"inspectionSmogCertificateIndicator","navigatorTitle":[{"text":"inspectionSmogCertificateIndicator","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/inspectionsmogcertificateindicator","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData/requiredDocumentType":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/requiredDocumentType","navigatorTitle":[{"kind":"identifier","text":"requiredDocumentType"}],"title":"requiredDocumentType","type":"topic","abstract":[{"text":"The name of the wrapped document type.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredDocumentType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/requireddocumenttype","kind":"symbol"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData/inspectionAirPollutionDeviceConditions":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionAirPollutionDeviceConditions","abstract":[{"text":"Data element ID “IPD”. Identifies whether the pollution control devices meet the minimum inspection criteria.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"inspectionAirPollutionDeviceConditions","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"title":"inspectionAirPollutionDeviceConditions","navigatorTitle":[{"kind":"identifier","text":"inspectionAirPollutionDeviceConditions"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/inspectionairpollutiondeviceconditions","role":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData/inspectorIdentificationNumber":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inspectorIdentificationNumber"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectorIdentificationNumber","type":"topic","kind":"symbol","title":"inspectorIdentificationNumber","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"inspectorIdentificationNumber"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/inspectoridentificationnumber","abstract":[{"type":"text","text":"Data element ID “IIN”. A unique number assigned to each licensed vehicle inspector."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData/vehicleModelYear":{"type":"topic","title":"vehicleModelYear","abstract":[{"text":"Data element ID “VAL”. The year which is assigned to a vehicle by the manufacturer. The format is CCYY.","type":"text"}],"navigatorTitle":[{"text":"vehicleModelYear","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehiclesafetyinspectiondata\/vehiclemodelyear","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"vehicleModelYear"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/vehicleModelYear"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionAddress","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionAirPollutionDeviceConditions","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionFacilityIdentifier","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionFormOrStickerNumberCurrent","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionFormOrStickerNumberPrevious","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionSmogCertificateIndicator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectionStationNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/inspectorIdentificationNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/odometerReadingAtInspection","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/vehicleBodyType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/vehicleMake","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/vehicleModelYear"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/initWithGenericDocument:"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"],"title":"Inherits From"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentWrapper","text":"SBSDKGenericDocumentWrapper"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","value":"SBSDKGenericDocument","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","op":"replace","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}]},{"value":"inspectionFormOrStickerNumberCurrent","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1inspectionFormOrStickerNumberCurrent\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1inspectionFormOrStickerNumberCurrent\/fragments","value":[{"text":"inspectionFormOrStickerNumberCurrent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1inspectionFacilityIdentifier\/title","value":"inspectionFacilityIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1inspectionFacilityIdentifier\/fragments","value":[{"text":"inspectionFacilityIdentifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1inspectionAddress\/title","op":"replace","value":"inspectionAddress"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1inspectionAddress\/fragments","value":[{"kind":"identifier","text":"inspectionAddress"}],"op":"replace"},{"value":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData\/fragments"},{"op":"replace","value":"vehicleBodyType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1vehicleBodyType\/title"},{"value":[{"text":"vehicleBodyType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1vehicleBodyType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1inspectionFormOrStickerNumberPrevious\/title","op":"replace","value":"inspectionFormOrStickerNumberPrevious"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1inspectionFormOrStickerNumberPrevious\/fragments","value":[{"kind":"identifier","text":"inspectionFormOrStickerNumberPrevious"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1inspectionStationNumber\/title","value":"inspectionStationNumber","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"inspectionStationNumber"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1inspectionStationNumber\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1odometerReadingAtInspection\/title","value":"odometerReadingAtInspection"},{"value":[{"kind":"identifier","text":"odometerReadingAtInspection"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1odometerReadingAtInspection\/fragments"},{"value":"SBSDKGenericDocumentWrapper","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/title","op":"replace"},{"value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/fragments","op":"replace"},{"value":"vehicleMake","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1vehicleMake\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"vehicleMake"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1vehicleMake\/fragments"},{"op":"replace","value":"inspectionSmogCertificateIndicator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1inspectionSmogCertificateIndicator\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1inspectionSmogCertificateIndicator\/fragments","value":[{"kind":"identifier","text":"inspectionSmogCertificateIndicator"}]},{"value":"requiredDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1requiredDocumentType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"requiredDocumentType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1requiredDocumentType\/fragments","op":"replace"},{"value":"inspectionAirPollutionDeviceConditions","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1inspectionAirPollutionDeviceConditions\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1inspectionAirPollutionDeviceConditions\/fragments","value":[{"text":"inspectionAirPollutionDeviceConditions","kind":"identifier"}]},{"value":"inspectorIdentificationNumber","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1inspectorIdentificationNumber\/title"},{"value":[{"kind":"identifier","text":"inspectorIdentificationNumber"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1inspectorIdentificationNumber\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1vehicleModelYear\/title","value":"vehicleModelYear"},{"value":[{"kind":"identifier","text":"vehicleModelYear"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleSafetyInspectionData~1vehicleModelYear\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}