{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"role":"symbol","title":"SBSDKImageFilterType","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFilterType"}],"symbolKind":"enum","externalID":"c:@M@ScanbotSDK@E@SBSDKImageFilterType","modules":[{"name":"ScanbotSDK"}],"platforms":[]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please consider using the new class-based SBSDKParametricFilters."}]}],"abstract":[{"type":"text","text":"The ScanbotSDK image filter types."}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/backgroundClean","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/binarized","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/blackAndWhite","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/color","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/colorDocument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/deepBinarization","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/edgeHighlight","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/gray","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/lowLightBinarization","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/lowLightBinarization2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/none","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/otsuBinarization","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/pureBinarized","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/pureGray","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/sensitiveBinarization"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/RawRepresentable-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagefiltertype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimagefiltertype"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFilterType"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/binarized":{"deprecated":true,"role":"symbol","title":"SBSDKImageFilterType.binarized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"binarized"}],"abstract":[{"type":"text","text":"Standard binarization filter with contrast optimization. Creates a grayscaled 8-bit image with mostly black or white pixels."},{"type":"text","text":" "},{"type":"text","text":"Usecase: Preparation for optical character recognition."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/binarized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeBinarized"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/binarized"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/colorDocument":{"deprecated":true,"role":"symbol","title":"SBSDKImageFilterType.colorDocument","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorDocument"}],"abstract":[{"type":"text","text":"Fixes white-balance and cleans up the background."},{"type":"text","text":" "},{"type":"text","text":"Usecase: images of paper documents."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/colorDocument","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeColorDocument"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/colordocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/pureGray":{"deprecated":true,"role":"symbol","title":"SBSDKImageFilterType.pureGray","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pureGray"}],"abstract":[{"type":"text","text":"Standard grayscale filter. Creates a grayscaled 8-bit image."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/pureGray","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypePureGray"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/puregray"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/backgroundClean":{"deprecated":true,"role":"symbol","title":"SBSDKImageFilterType.backgroundClean","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundClean"}],"abstract":[{"type":"text","text":"Cleans up the background and tries to preserve photos within the image."},{"type":"text","text":" "},{"type":"text","text":"Usecase: magazine pages, flyers."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/backgroundClean","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeBackgroundClean"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/backgroundclean"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/sensitiveBinarization":{"deprecated":true,"role":"symbol","title":"SBSDKImageFilterType.sensitiveBinarization","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sensitiveBinarization"}],"abstract":[{"type":"text","text":"Binarization filter for poor quality printed papers."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/sensitiveBinarization","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeSensitiveBinarization"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/sensitivebinarization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/pureBinarized":{"deprecated":true,"role":"symbol","title":"SBSDKImageFilterType.pureBinarized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pureBinarized"}],"abstract":[{"type":"text","text":"A filter for binarizing an image. Creates an 8-bit image with pixel values set to eiter 0 or 255."},{"type":"text","text":" "},{"type":"text","text":"Usecase: Preparation for optical character recognition."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/pureBinarized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypePureBinarized"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/purebinarized"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/none":{"deprecated":true,"role":"symbol","title":"SBSDKImageFilterType.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"Passthrough filter. Does not alter the image."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeNone"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/none"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/edgeHighlight":{"deprecated":true,"role":"symbol","title":"SBSDKImageFilterType.edgeHighlight","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"edgeHighlight"}],"abstract":[{"type":"text","text":"A filter that enhances edges in low-contrast documents."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/edgeHighlight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeEdgeHighlight"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/edgehighlight"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/deepBinarization":{"deprecated":true,"role":"symbol","title":"SBSDKImageFilterType.deepBinarization","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deepBinarization"}],"abstract":[{"type":"text","text":"A filter for black and white conversion primary used for low-contrast documents."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/deepBinarization","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeDeepBinarization"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/deepbinarization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType":{"deprecated":true,"role":"symbol","title":"SBSDKImageFilterType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFilterType"}],"abstract":[{"type":"text","text":"The ScanbotSDK image filter types."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/gray":{"deprecated":true,"role":"symbol","title":"SBSDKImageFilterType.gray","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gray"}],"abstract":[{"type":"text","text":"Standard grayscale filter. Creates a grayscaled 8-bit image and optimizes contrast and dynamic range."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/gray","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeGray"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/gray"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/blackAndWhite":{"deprecated":true,"role":"symbol","title":"SBSDKImageFilterType.blackAndWhite","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"blackAndWhite"}],"abstract":[{"type":"text","text":"Black and white filter with background cleaning. Creates a grayscaled 8-bit image with mostly black or white pixels."},{"type":"text","text":" "},{"type":"text","text":"Usecase: Textual documents or documents with black and white illustrations."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/blackAndWhite","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeBlackAndWhite"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/blackandwhite"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/init(rawValue:)","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/init(rawvalue:)"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/rawrepresentable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/otsuBinarization":{"deprecated":true,"role":"symbol","title":"SBSDKImageFilterType.otsuBinarization","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"otsuBinarization"}],"abstract":[{"type":"text","text":"A filter for black and white conversion using OTSU binarization."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/otsuBinarization","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeOtsuBinarization"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/otsubinarization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/equatable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/color":{"deprecated":true,"role":"symbol","title":"SBSDKImageFilterType.color","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"color"}],"abstract":[{"type":"text","text":"Optimizes colors, contrast and brightness."},{"type":"text","text":" "},{"type":"text","text":"Usecase: photos."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/color","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeColor"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/color"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/lowLightBinarization":{"deprecated":true,"role":"symbol","title":"SBSDKImageFilterType.lowLightBinarization","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowLightBinarization"}],"abstract":[{"type":"text","text":"Binarization filter primary inteded to use on low-contrast documents with heavy shadows."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/lowLightBinarization","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeLowLightBinarization"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/lowlightbinarization"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/lowLightBinarization2":{"deprecated":true,"role":"symbol","title":"SBSDKImageFilterType.lowLightBinarization2","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowLightBinarization2"}],"abstract":[{"type":"text","text":"Binarization filter primary intended to use on low-contrast documents with heavy shadows."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/lowLightBinarization2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeLowLightBinarization2"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/lowlightbinarization2"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKImageFilterType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageFilterType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/backgroundClean","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/binarized","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/blackAndWhite","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/color","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/colorDocument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/deepBinarization","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/edgeHighlight","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/gray","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/lowLightBinarization","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/lowLightBinarization2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/none","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/otsuBinarization","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/pureBinarized","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/pureGray","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/sensitiveBinarization"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFilterType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1binarized\/title","value":"SBSDKImageFilterTypeBinarized"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1binarized\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeBinarized"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1colorDocument\/title","value":"SBSDKImageFilterTypeColorDocument"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1colorDocument\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeColorDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1pureGray\/title","value":"SBSDKImageFilterTypePureGray"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1pureGray\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypePureGray"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1backgroundClean\/title","value":"SBSDKImageFilterTypeBackgroundClean"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1backgroundClean\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeBackgroundClean"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1sensitiveBinarization\/title","value":"SBSDKImageFilterTypeSensitiveBinarization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1sensitiveBinarization\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeSensitiveBinarization"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1pureBinarized\/title","value":"SBSDKImageFilterTypePureBinarized"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1pureBinarized\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypePureBinarized"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1none\/title","value":"SBSDKImageFilterTypeNone"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1none\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeNone"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1edgeHighlight\/title","value":"SBSDKImageFilterTypeEdgeHighlight"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1edgeHighlight\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeEdgeHighlight"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1deepBinarization\/title","value":"SBSDKImageFilterTypeDeepBinarization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1deepBinarization\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeDeepBinarization"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/title","value":"SBSDKImageFilterType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1gray\/title","value":"SBSDKImageFilterTypeGray"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1gray\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeGray"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1blackAndWhite\/title","value":"SBSDKImageFilterTypeBlackAndWhite"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1blackAndWhite\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeBlackAndWhite"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1otsuBinarization\/title","value":"SBSDKImageFilterTypeOtsuBinarization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1otsuBinarization\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeOtsuBinarization"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1color\/title","value":"SBSDKImageFilterTypeColor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1color\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeColor"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1lowLightBinarization\/title","value":"SBSDKImageFilterTypeLowLightBinarization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1lowLightBinarization\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeLowLightBinarization"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1lowLightBinarization2\/title","value":"SBSDKImageFilterTypeLowLightBinarization2"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1lowLightBinarization2\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeLowLightBinarization2"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}