{"metadata":{"role":"symbol","roleHeading":"Class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentDEMedicalPlanPatient","modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","title":"SBSDKBarcodeDocumentDEMedicalPlanPatient","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlanPatient"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentDEMedicalPlanPatient","kind":"identifier"}]},"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/allergiesAndIntolerances","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/birthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/breastFeeding","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/creatinineValue","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/firstName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/gender","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/height","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/lastName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/patientFreeText","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/patientID","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/preName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/pregnant","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/suffix","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/title","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/weight"]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentDEMedicalPlanPatient","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Patient."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient"},"references":{"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentDEMedicalPlanPatient":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentDEMedicalPlanPatient","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient","abstract":[{"type":"text","text":"Patient."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlanPatient"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient","role":"symbol","title":"SBSDKBarcodeDocumentDEMedicalPlanPatient"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentWrapper":{"title":"SBSDKGenericDocumentWrapper","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Base class for strongly-typed ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","isActive":true},{"type":"text","text":" wrappers."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentDEMedicalPlanPatient/weight":{"navigatorTitle":[{"text":"weight","kind":"identifier"}],"abstract":[{"type":"text","text":"Weight."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient\/weight","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/weight","title":"weight","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"weight"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentDEMedicalPlanPatient/creatinineValue":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"creatinineValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/creatinineValue","abstract":[{"type":"text","text":"Creatinine Value."}],"role":"symbol","title":"creatinineValue","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient\/creatininevalue","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"creatinineValue"}],"type":"topic"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"title":"SBSDKGenericDocument","abstract":[{"text":"Represents a generic document with fields and sub-documents used for document recognition.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentDEMedicalPlanPatient/preName":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preName"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"title":"preName","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient\/prename","kind":"symbol","navigatorTitle":[{"text":"preName","kind":"identifier"}],"abstract":[{"text":"Pre Name.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/preName","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentDEMedicalPlanPatient/title":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient\/title","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/title","navigatorTitle":[{"kind":"identifier","text":"title"}],"title":"title","abstract":[{"text":"Title.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentDEMedicalPlanPatient/gender":{"abstract":[{"text":"Gender.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"gender","kind":"identifier"}],"title":"gender","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/gender","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient\/gender","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentDEMedicalPlanPatient/lastName":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"lastName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"title":"lastName","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient\/lastname","kind":"symbol","navigatorTitle":[{"text":"lastName","kind":"identifier"}],"abstract":[{"text":"Last Name.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/lastName","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentDEMedicalPlanPatient/patientID":{"navigatorTitle":[{"text":"patientID","kind":"identifier"}],"title":"patientID","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/patientID","abstract":[{"type":"text","text":"Patient ID."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient\/patientid","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"patientID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentDEMedicalPlanPatient/breastFeeding":{"navigatorTitle":[{"kind":"identifier","text":"breastFeeding"}],"abstract":[{"text":"Breast Feeding.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/breastFeeding","kind":"symbol","title":"breastFeeding","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient\/breastfeeding","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"breastFeeding"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentDEMedicalPlanPatient/birthDate":{"type":"topic","abstract":[{"type":"text","text":"Birth Date."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"birthDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/birthDate","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient\/birthdate","title":"birthDate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"birthDate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentDEMedicalPlanPatient/requiredDocumentType":{"kind":"symbol","title":"requiredDocumentType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/requiredDocumentType","abstract":[{"text":"The name of the wrapped document type.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"requiredDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"requiredDocumentType","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient\/requireddocumenttype","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentDEMedicalPlanPatient/patientFreeText":{"abstract":[{"text":"Patient Free Text.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"patientFreeText"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"patientFreeText","navigatorTitle":[{"kind":"identifier","text":"patientFreeText"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient\/patientfreetext","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/patientFreeText","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentDEMedicalPlanPatient/firstName":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/firstName","navigatorTitle":[{"text":"firstName","kind":"identifier"}],"title":"firstName","abstract":[{"text":"First Name.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstName","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient\/firstname"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentDEMedicalPlanPatient/pregnant":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/pregnant","title":"pregnant","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient\/pregnant","type":"topic","abstract":[{"type":"text","text":"Pregnant."}],"navigatorTitle":[{"text":"pregnant","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pregnant","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentDEMedicalPlanPatient/suffix":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/suffix","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"suffix","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"type":"topic","title":"suffix","kind":"symbol","abstract":[{"type":"text","text":"Name Suffix."}],"navigatorTitle":[{"kind":"identifier","text":"suffix"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient\/suffix"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentDEMedicalPlanPatient/height":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","title":"height","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient\/height","abstract":[{"text":"Height.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"height"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/height"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentDEMedicalPlanPatient/initWithGenericDocument:":{"role":"symbol","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGenericDocument:"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient\/initwithgenericdocument:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/initWithGenericDocument:","type":"topic","title":"initWithGenericDocument:","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentDEMedicalPlanPatient/allergiesAndIntolerances":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allergiesAndIntolerances"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/allergiesAndIntolerances","abstract":[{"type":"text","text":"Allergies And Intolerances."}],"navigatorTitle":[{"kind":"identifier","text":"allergiesAndIntolerances"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentdemedicalplanpatient\/allergiesandintolerances","role":"symbol","title":"allergiesAndIntolerances"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKBarcodeDocumentDEMedicalPlanPatient","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeDocumentDEMedicalPlanPatient","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKBarcodeDocumentDEMedicalPlanPatient","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/allergiesAndIntolerances","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/birthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/breastFeeding","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/creatinineValue","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/firstName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/gender","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/height","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/lastName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/patientFreeText","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/patientID","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/preName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/pregnant","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/suffix","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/title","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/weight"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentDEMedicalPlanPatient\/initWithGenericDocument:"]}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentDEMedicalPlanPatient","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"SBSDKGenericDocumentWrapper","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentWrapper"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient\/title","value":"SBSDKBarcodeDocumentDEMedicalPlanPatient"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlanPatient"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient\/fragments"},{"value":"SBSDKGenericDocumentWrapper","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/title","op":"replace"},{"value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/fragments"},{"value":"weight","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1weight\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1weight\/fragments","value":[{"kind":"identifier","text":"weight"}]},{"value":"creatinineValue","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1creatinineValue\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1creatinineValue\/fragments","value":[{"text":"creatinineValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","value":"SBSDKGenericDocument"},{"value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments"},{"value":"preName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1preName\/title"},{"op":"replace","value":[{"text":"preName","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1preName\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1title\/title","value":"title"},{"value":[{"text":"title","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1title\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1gender\/title","value":"gender"},{"value":[{"kind":"identifier","text":"gender"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1gender\/fragments"},{"value":"lastName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1lastName\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1lastName\/fragments","value":[{"kind":"identifier","text":"lastName"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1patientID\/title","value":"patientID","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1patientID\/fragments","value":[{"kind":"identifier","text":"patientID"}]},{"value":"breastFeeding","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1breastFeeding\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1breastFeeding\/fragments","op":"replace","value":[{"kind":"identifier","text":"breastFeeding"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1birthDate\/title","op":"replace","value":"birthDate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1birthDate\/fragments","value":[{"text":"birthDate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1requiredDocumentType\/title","value":"requiredDocumentType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1requiredDocumentType\/fragments","value":[{"text":"requiredDocumentType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1patientFreeText\/title","value":"patientFreeText","op":"replace"},{"op":"replace","value":[{"text":"patientFreeText","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1patientFreeText\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1firstName\/title","value":"firstName"},{"value":[{"text":"firstName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1firstName\/fragments"},{"op":"replace","value":"pregnant","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1pregnant\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1pregnant\/fragments","value":[{"kind":"identifier","text":"pregnant"}]},{"value":"suffix","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1suffix\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1suffix\/fragments","value":[{"text":"suffix","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1height\/title","value":"height","op":"replace"},{"op":"replace","value":[{"text":"height","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1height\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1allergiesAndIntolerances\/title","value":"allergiesAndIntolerances","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentDEMedicalPlanPatient~1allergiesAndIntolerances\/fragments","value":[{"kind":"identifier","text":"allergiesAndIntolerances"}]}]}]}