{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalplansubheadingprescriptionfieldtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalplansubheadingprescriptionfieldtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The german medical plan document subheading prescription information description field type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"}],"title":"SBSDKMedicalPlanSubheadingPrescriptionFieldType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalPlanSubheadingPrescriptionFieldType","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType\/generalInformation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType\/prescriptionFreeText"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType\/init(rawValue:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType\/encode(to:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanSubheadingPrescriptionFieldType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalplansubheadingprescriptionfieldtype\/init(rawvalue:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanSubheadingPrescriptionFieldType/encode(to:)":{"role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType\/encode(to:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalplansubheadingprescriptionfieldtype\/encode(to:)"},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanSubheadingPrescriptionFieldType/prescriptionFreeText":{"role":"symbol","title":"SBSDKMedicalPlanSubheadingPrescriptionFieldType.prescriptionFreeText","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"prescriptionFreeText"}],"abstract":[{"type":"text","text":"The prescription free text."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType\/prescriptionFreeText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalplansubheadingprescriptionfieldtype\/prescriptionfreetext"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanSubheadingPrescriptionFieldType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalplansubheadingprescriptionfieldtype\/equatable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanSubheadingPrescriptionFieldType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalplansubheadingprescriptionfieldtype\/rawrepresentable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanSubheadingPrescriptionFieldType/generalInformation":{"role":"symbol","title":"SBSDKMedicalPlanSubheadingPrescriptionFieldType.generalInformation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"generalInformation"}],"abstract":[{"type":"text","text":"The general information."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType\/generalInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldTypeGeneralInformation"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalplansubheadingprescriptionfieldtype\/generalinformation"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanSubheadingPrescriptionFieldType":{"role":"symbol","title":"SBSDKMedicalPlanSubheadingPrescriptionFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"}],"abstract":[{"type":"text","text":"The german medical plan document subheading prescription information description field type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalplansubheadingprescriptionfieldtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType\/generalInformation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanSubheadingPrescriptionFieldType\/prescriptionFreeText"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanSubheadingPrescriptionFieldType~1prescriptionFreeText\/title","value":"SBSDKMedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanSubheadingPrescriptionFieldType~1prescriptionFreeText\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanSubheadingPrescriptionFieldType~1generalInformation\/title","value":"SBSDKMedicalPlanSubheadingPrescriptionFieldTypeGeneralInformation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanSubheadingPrescriptionFieldType~1generalInformation\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldTypeGeneralInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanSubheadingPrescriptionFieldType\/title","value":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanSubheadingPrescriptionFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanSubheadingPrescriptionFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}