{"abstract":[{"type":"text","text":"A class to recognize one line of text in a small area and run validation on the result."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericTextLineRecognizer"}]}],"kind":"declarations"},{"content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"It is intended to be a very generic text-based live video recognizer for tasks that can’t be accomplished with the specialized recognizers in ScanbotSDK.","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizer"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizer"]}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer\/init(configuration:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer\/configuration"],"generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer\/clearFrameAccumulator()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer\/recognize(on:in:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer\/recognize(on:orientation:in:)"],"generated":true,"anchor":"Instance-Methods"}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Class","navigatorTitle":[{"text":"SBSDKGenericTextLineRecognizer","kind":"identifier"}],"symbolKind":"class","title":"SBSDKGenericTextLineRecognizer","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericTextLineRecognizer","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizer"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizer":{"navigatorTitle":[{"text":"SBSDKGenericTextLineRecognizer","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericTextLineRecognizer","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizer","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer","abstract":[{"text":"A class to recognize one line of text in a small area and run validation on the result.","type":"text"}],"title":"SBSDKGenericTextLineRecognizer"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizer/recognize(on:in:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer\/recognize(on:in:)","title":"recognize(on:in:)","navigatorTitle":[{"kind":"identifier","text":"recognizeOnImage:inRect:"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizer\/recognize(on:in:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKGenericTextLineRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResult"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"text":"Recognizes text information on the given image. Intended for usage with still image detection.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizer/recognize(on:orientation:in:)":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer\/recognize(on:orientation:in:)","navigatorTitle":[{"kind":"identifier","text":"recognizeOnSampleBuffer:orientation:inRect:"}],"abstract":[{"text":"Recognizes text information on the given sample buffer. Intended for usage with live detection.","type":"text"}],"title":"recognize(on:orientation:in:)","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizer\/recognize(on:orientation:in:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"recognize","kind":"identifier"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"orientation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@AVCaptureVideoOrientation","text":"AVCaptureVideoOrientation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":") -> ","kind":"text"},{"text":"SBSDKGenericTextLineRecognizerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResult"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizer/init(configuration:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer\/init(configuration:)","title":"init(configuration:)","navigatorTitle":[{"text":"initWithConfiguration:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizer\/init(configuration:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerConfiguration","text":"SBSDKGenericTextLineRecognizerConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Designated initializer."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizer/clearFrameAccumulator()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer\/clearFrameAccumulator()","title":"clearFrameAccumulator()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearFrameAccumulator"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizer\/clearframeaccumulator()","abstract":[{"text":"Clears the frame accumulator of the recognizer.","type":"text"}],"navigatorTitle":[{"text":"clearFrameAccumulator","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizer/configuration":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer\/configuration","navigatorTitle":[{"kind":"identifier","text":"configuration"}],"abstract":[{"type":"text","text":"The configuration of the generic text line recognizer."}],"title":"configuration","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizer\/configuration","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configuration"},{"text":": ","kind":"text"},{"text":"SBSDKGenericTextLineRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerConfiguration","kind":"typeIdentifier"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"SBSDKGenericTextLineRecognizer","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizer"}],"path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKGenericTextLineRecognizer","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer\/configuration"],"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer\/clearFrameAccumulator()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer\/init(configuration:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer\/recognize(on:in:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer\/recognize(on:orientation:in:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericTextLineRecognizer","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer\/title","value":"SBSDKGenericTextLineRecognizer"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer\/fragments","value":[{"text":"SBSDKGenericTextLineRecognizer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizer"}]},{"value":"recognizeOnImage:inRect:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer~1recognize(on:in:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"recognizeOnImage:inRect:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer~1recognize(on:in:)\/fragments"},{"value":"recognizeOnSampleBuffer:orientation:inRect:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer~1recognize(on:orientation:in:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer~1recognize(on:orientation:in:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"recognizeOnSampleBuffer:orientation:inRect:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer~1init(configuration:)\/title","op":"replace","value":"initWithConfiguration:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithConfiguration:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer~1init(configuration:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer~1clearFrameAccumulator()\/title","value":"clearFrameAccumulator"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"clearFrameAccumulator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer~1clearFrameAccumulator()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer~1configuration\/title","value":"configuration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer~1configuration\/fragments","value":[{"kind":"identifier","text":"configuration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}