{"metadata":{"role":"symbol","roleHeading":"Enumeration","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKOpticalCharacterRecognitionMode","symbolKind":"enum","title":"SBSDKOpticalCharacterRecognitionMode","navigatorTitle":[{"text":"SBSDKOpticalCharacterRecognitionMode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOpticalCharacterRecognitionMode","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKOpticalCharacterRecognitionMode","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/scanbotOCR","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/tesseract"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/init(rawValue:)"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"text":"An enum describing the modes of the optical character recognition.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognitionMode/tesseract":{"abstract":[{"type":"text","text":"The legacy OCR mode using Tesseract. Slower, more error prone, but it supports more languages."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tesseract"}],"title":"SBSDKOpticalCharacterRecognitionMode.tesseract","navigatorTitle":[{"text":"SBSDKOpticalCharacterRecognitionModeTesseract","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode\/tesseract","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/tesseract","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognitionMode/init(rawValue:)":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode\/init(rawvalue:)","abstract":[],"type":"topic","role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/init(rawValue:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognitionMode/RawRepresentable-Implementations":{"kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/RawRepresentable-Implementations","type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode\/rawrepresentable-implementations","title":"RawRepresentable Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognitionMode/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode\/equatable-implementations","kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/Equatable-Implementations","title":"Equatable Implementations","type":"topic","role":"collectionGroup"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognitionMode":{"abstract":[{"type":"text","text":"An enum describing the modes of the optical character recognition."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKOpticalCharacterRecognitionMode","kind":"identifier"}],"title":"SBSDKOpticalCharacterRecognitionMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognitionMode"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode","type":"topic"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognitionMode/scanbotOCR":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/scanbotOCR","title":"SBSDKOpticalCharacterRecognitionMode.scanbotOCR","abstract":[{"type":"text","text":"The new machine-learning based mode made by Scanbot SDK GmbH. Faster, less errors, but currently only"},{"type":"text","text":" "},{"text":"supports languages with latin letters.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanbotOCR","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognitionModeScanbotOCR"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode\/scanbotocr","kind":"symbol"},"doc://net.doo.ScanbotSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKOpticalCharacterRecognitionMode","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognitionMode"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKOpticalCharacterRecognitionMode","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/scanbotOCR","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/tesseract"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKOpticalCharacterRecognitionMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKOpticalCharacterRecognitionModeTesseract","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode~1tesseract\/title"},{"value":[{"text":"SBSDKOpticalCharacterRecognitionModeTesseract","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode~1tesseract\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode\/title","value":"SBSDKOpticalCharacterRecognitionMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognitionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode~1scanbotOCR\/title","value":"SBSDKOpticalCharacterRecognitionModeScanbotOCR"},{"value":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognitionModeScanbotOCR"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode~1scanbotOCR\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}