{"sections":[],"metadata":{"roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizer","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKMedicalCertificateRecognizer","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizer","kind":"identifier"}]},"abstract":[{"type":"text","text":"A class to recognize medical certificates in a "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" or "},{"code":"CMSampleBuffer","type":"codeVoice"},{"type":"text","text":"."}],"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer\/init(configurationOptions:)"]},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer\/recognitionOptions"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer\/recognize(from:detectDocument:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer\/recognize(from:orientation:detectDocument:)"]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizer"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizer"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizer"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizer/init":{"title":"init","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizer\/init","type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer\/init","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizer/recognitionOptions":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer\/recognitionOptions","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recognitionOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerConfigurationOptions","text":"SBSDKMedicalCertificateRecognizerConfigurationOptions"}],"type":"topic","abstract":[{"text":"The options to be used with the medical certificates recognizer.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizer\/recognitionoptions","kind":"symbol","title":"recognitionOptions","navigatorTitle":[{"kind":"identifier","text":"recognitionOptions"}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizer/recognize(from:orientation:detectDocument:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVCaptureVideoOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@AVCaptureVideoOrientation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"detectDocument"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKMedicalCertificateRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerResult"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizer\/recognize(from:orientation:detectdocument:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer\/recognize(from:orientation:detectDocument:)","role":"symbol","kind":"symbol","title":"recognize(from:orientation:detectDocument:)","abstract":[{"text":"Detects the document and acquires all available information from a sample buffer reference.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"recognizeFromSampleBuffer:orientation:detectDocument:"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizer":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizer","kind":"identifier"}],"title":"SBSDKMedicalCertificateRecognizer","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizer"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizer","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer","abstract":[{"text":"A class to recognize medical certificates in a ","type":"text"},{"type":"codeVoice","code":"UIImage"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"CMSampleBuffer"},{"text":".","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizer/init(configurationOptions:)":{"abstract":[{"text":"The designated initializer.","type":"text"}],"type":"topic","title":"init(configurationOptions:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"configurationOptions","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerConfigurationOptions","kind":"typeIdentifier","text":"SBSDKMedicalCertificateRecognizerConfigurationOptions"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer\/init(configurationOptions:)","navigatorTitle":[{"text":"initWithConfigurationOptions:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizer\/init(configurationoptions:)","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizer/recognize(from:detectDocument:)":{"navigatorTitle":[{"kind":"identifier","text":"recognizeFromImage:detectDocument:"}],"abstract":[{"text":"Acquires all available information from an ","type":"text"},{"type":"codeVoice","code":"UIImage"},{"text":" instance.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"detectDocument"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerResult","kind":"typeIdentifier","text":"SBSDKMedicalCertificateRecognizerResult"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer\/recognize(from:detectDocument:)","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizer\/recognize(from:detectdocument:)","title":"recognize(from:detectDocument:)","kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalCertificateRecognizer"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKMedicalCertificateRecognizer","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizer"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer\/recognitionOptions"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer\/init","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer\/init(configurationOptions:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer\/recognize(from:detectDocument:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer\/recognize(from:orientation:detectDocument:)"]}]},{"value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizer","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"recognitionOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer~1recognitionOptions\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer~1recognitionOptions\/fragments","value":[{"kind":"identifier","text":"recognitionOptions"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer~1recognize(from:orientation:detectDocument:)\/title","value":"recognizeFromSampleBuffer:orientation:detectDocument:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"recognizeFromSampleBuffer:orientation:detectDocument:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer~1recognize(from:orientation:detectDocument:)\/fragments"},{"op":"replace","value":"SBSDKMedicalCertificateRecognizer","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer\/title"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizer"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificateRecognizer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer~1init(configurationOptions:)\/title","op":"replace","value":"initWithConfigurationOptions:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer~1init(configurationOptions:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConfigurationOptions:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer~1recognize(from:detectDocument:)\/title","op":"replace","value":"recognizeFromImage:detectDocument:"},{"value":[{"text":"- ","kind":"text"},{"text":"recognizeFromImage:detectDocument:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer~1recognize(from:detectDocument:)\/fragments","op":"replace"}]}]}