{"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/init(options:encrypter:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/encrypter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/options"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderDocument(_:output:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderDocument(_:output:progress:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderDocumentAsync(_:output:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderImageStorage(_:indexSet:output:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderImageStorage(_:indexSet:output:progress:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderImageStorageAsync(_:indexSet:output:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderScannedDocument(_:output:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderScannedDocument(_:output:progress:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderScannedDocumentAsync(_:output:)"],"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKPDFRenderer","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFRenderer"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRenderer"}],"roleHeading":"Class","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRenderer"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer"},"abstract":[{"type":"text","text":"A class to render an ordered collection of images with or without performing HOCR."}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPDFRenderer","kind":"identifier"}],"languages":["swift"]}]},{"content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"inlineContent":[{"type":"text","text":"HOCR is the process of adding an invisible text layer on top of each PDF page, containing the text extracted by"},{"type":"text","text":" "},{"type":"text","text":"the optical character recognizer. A PDF with HOCR is searchable and the text can be selected and copy-pasted."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrenderer"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrenderer"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer/options":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/options","title":"options","abstract":[{"type":"text","text":"The rendering options."}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRendererOptions","text":"SBSDKPDFRendererOptions"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/options","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"options"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer/renderImageStorage(_:indexSet:output:completion:)":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderimagestorage(_:indexset:output:completion:)","title":"renderImageStorage(_:indexSet:output:completion:)","abstract":[{"type":"text","text":"Asynchronously renders the images at the specified indices from the image storage into a PDF file"},{"type":"text","text":" "},{"type":"text","text":"with the given page size, saves the PDF to the specified URL and calls the completion handler when finished."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"renderImageStorage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKImageStoring","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring"},{"text":", ","kind":"text"},{"text":"indexSet","kind":"externalParam"},{"kind":"text","text":": "},{"text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"output"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> ()) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderImageStorage(_:indexSet:output:completion:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"renderImageStorage:indexSet:output:completion:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer/renderScannedDocument(_:output:completion:)":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderscanneddocument(_:output:completion:)","title":"renderScannedDocument(_:output:completion:)","abstract":[{"type":"text","text":"Asynchronously renders the scanned document into a PDF file"},{"text":" ","type":"text"},{"type":"text","text":"with the given page size, saves the PDF to the specified URL and calls the completion handler when finished."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"renderScannedDocument"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","text":"SBSDKScannedDocument"},{"kind":"text","text":", "},{"text":"output","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ()) -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderScannedDocument(_:output:completion:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"renderScannedDocument:output:completion:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer/renderScannedDocument(_:output:progress:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"renderScannedDocument:output:progress:error:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderScannedDocument"},{"kind":"text","text":"("},{"text":"SBSDKScannedDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument"},{"text":", ","kind":"text"},{"text":"output","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKProgress","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"throws"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderScannedDocument(_:output:progress:)","url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderscanneddocument(_:output:progress:)","type":"topic","title":"renderScannedDocument(_:output:progress:)","abstract":[{"type":"text","text":"Synchronously renders the scanned document into a PDF file"},{"type":"text","text":" "},{"text":"with the given page size, and saves the PDF to the specified URL.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer/renderDocumentAsync(_:output:)":{"kind":"symbol","title":"renderDocumentAsync(_:output:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renderDocumentAsync","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"output"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderdocumentasync(_:output:)","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderDocumentAsync(_:output:)","navigatorTitle":[{"kind":"identifier","text":"renderDocumentAsync:output:completionHandler:"}],"abstract":[{"type":"text","text":"Asynchronously renders the document into a PDF file and saves it to the specified URL."},{"type":"text","text":" "},{"text":"Each page is made up of one image.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer/renderImageStorageAsync(_:indexSet:output:)":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderimagestorageasync(_:indexset:output:)","title":"renderImageStorageAsync(_:indexSet:output:)","abstract":[{"text":"Asynchronously renders the images at the specified indices from the image storage into a PDF file and saves it to the specified URL.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Each page is made up of one image."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renderImageStorageAsync","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKImageStoring","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"indexSet"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"output"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderImageStorageAsync(_:indexSet:output:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"renderImageStorageAsync:indexSet:output:completionHandler:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRenderer"}],"abstract":[{"type":"text","text":"A class to render an ordered collection of images with or without performing HOCR."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPDFRenderer","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer","title":"SBSDKPDFRenderer","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer/renderScannedDocumentAsync(_:output:)":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderscanneddocumentasync(_:output:)","title":"renderScannedDocumentAsync(_:output:)","abstract":[{"type":"text","text":"Asynchronously renders the scanned document into a PDF file and saves it to the specified URL."},{"text":" ","type":"text"},{"type":"text","text":"Each page is made up of one image."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderScannedDocumentAsync"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","text":"SBSDKScannedDocument"},{"kind":"text","text":", "},{"kind":"externalParam","text":"output"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderScannedDocumentAsync(_:output:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"renderScannedDocumentAsync:output:completionHandler:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer/renderDocument(_:output:progress:)":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderdocument(_:output:progress:)","title":"renderDocument(_:output:progress:)","abstract":[{"type":"text","text":"Synchronously renders the document into a PDF file"},{"type":"text","text":" "},{"type":"text","text":"with the given page size, and saves the PDF to the specified URL."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderDocument"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","text":"SBSDKDocument","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"output"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"text":"progress","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress"},{"kind":"text","text":"?) "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderDocument(_:output:progress:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"renderDocument:output:progress:error:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer/renderImageStorage(_:indexSet:output:progress:)":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderimagestorage(_:indexset:output:progress:)","navigatorTitle":[{"kind":"identifier","text":"renderImageStorage:indexSet:output:progress:error:"}],"abstract":[{"text":"Synchronously renders the images at the specified indices from the image storage into a PDF file","type":"text"},{"type":"text","text":" "},{"type":"text","text":"with the given page size, and saves the PDF to the specified URL."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"renderImageStorage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageStoring","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring"},{"kind":"text","text":", "},{"text":"indexSet","kind":"externalParam"},{"kind":"text","text":": "},{"text":"IndexSet","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV"},{"text":"?, ","kind":"text"},{"text":"output","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progress"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKProgress","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderImageStorage(_:indexSet:output:progress:)","title":"renderImageStorage(_:indexSet:output:progress:)","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer/init(options:encrypter:)":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/init(options:encrypter:)","abstract":[{"type":"text","text":"Designated initializer."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/init(options:encrypter:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithOptions:encrypter:"}],"title":"init(options:encrypter:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPDFRendererOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRendererOptions"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer/renderDocument(_:output:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"renderDocument"},{"kind":"text","text":"("},{"text":"SBSDKDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument"},{"kind":"text","text":", "},{"kind":"externalParam","text":"output"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ()) -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Asynchronously renders the document into a PDF file"},{"text":" ","type":"text"},{"type":"text","text":"with the given page size, saves the PDF to the specified URL and calls the completion handler when finished."}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderdocument(_:output:completion:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderDocument(_:output:completion:)","title":"renderDocument(_:output:completion:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"renderDocument:output:completion:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer/encrypter":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/encrypter","kind":"symbol","navigatorTitle":[{"text":"encrypter","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/encrypter","title":"encrypter","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The encryptor used to encrypt the PDF file. Or "},{"type":"codeVoice","code":"nil"},{"text":" if no encryption should be used.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"encrypter","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"SBSDKPDFRenderer","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKPDFRenderer","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKPDFRenderer"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/encrypter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/options"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/init(options:encrypter:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderDocument(_:output:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderDocument(_:output:progress:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderDocumentAsync(_:output:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderImageStorage(_:indexSet:output:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderImageStorage(_:indexSet:output:progress:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderImageStorageAsync(_:indexSet:output:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderScannedDocument(_:output:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderScannedDocument(_:output:progress:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderScannedDocumentAsync(_:output:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPDFRenderer"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"value":"options","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1options\/title"},{"op":"replace","value":[{"text":"options","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1options\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderImageStorage(_:indexSet:output:completion:)\/title","op":"replace","value":"renderImageStorage:indexSet:output:completion:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderImageStorage(_:indexSet:output:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"renderImageStorage:indexSet:output:completion:"}]},{"op":"replace","value":"renderScannedDocument:output:completion:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderScannedDocument(_:output:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderScannedDocument(_:output:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"renderScannedDocument:output:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderScannedDocument(_:output:progress:)\/title","value":"renderScannedDocument:output:progress:error:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderScannedDocument(_:output:progress:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"renderScannedDocument:output:progress:error:","kind":"identifier"}]},{"value":"renderDocumentAsync:output:completionHandler:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderDocumentAsync(_:output:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderDocumentAsync(_:output:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"renderDocumentAsync:output:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderImageStorageAsync(_:indexSet:output:)\/title","value":"renderImageStorageAsync:indexSet:output:completionHandler:"},{"value":[{"text":"- ","kind":"text"},{"text":"renderImageStorageAsync:indexSet:output:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderImageStorageAsync(_:indexSet:output:)\/fragments"},{"value":"SBSDKPDFRenderer","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFRenderer"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderScannedDocumentAsync(_:output:)\/title","op":"replace","value":"renderScannedDocumentAsync:output:completionHandler:"},{"value":[{"kind":"text","text":"- "},{"text":"renderScannedDocumentAsync:output:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderScannedDocumentAsync(_:output:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderDocument(_:output:progress:)\/title","op":"replace","value":"renderDocument:output:progress:error:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"renderDocument:output:progress:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderDocument(_:output:progress:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderImageStorage(_:indexSet:output:progress:)\/title","value":"renderImageStorage:indexSet:output:progress:error:"},{"value":[{"text":"- ","kind":"text"},{"text":"renderImageStorage:indexSet:output:progress:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderImageStorage(_:indexSet:output:progress:)\/fragments"},{"value":"initWithOptions:encrypter:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1init(options:encrypter:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithOptions:encrypter:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1init(options:encrypter:)\/fragments"},{"value":"renderDocument:output:completion:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderDocument(_:output:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderDocument(_:output:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"renderDocument:output:completion:"}]},{"value":"encrypter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1encrypter\/title"},{"value":[{"text":"encrypter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1encrypter\/fragments","op":"replace"}]}]}