{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/init()"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/languages","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/recognitionMode"],"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/scanbotOCR()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/tesseract(with:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/tesseract(withLanguageString:)"],"title":"Type Methods"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"role":"symbol","title":"SBSDKOpticalCharacterRecognizerConfiguration","symbolKind":"class","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKOpticalCharacterRecognizerConfiguration","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration"},"sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"type":"text","text":"A class describing the configuration of the optical character recognizer (OCR)."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognizerConfiguration/copyWithZone:":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/copyWithZone:","title":"copyWithZone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration\/copywithzone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognizerConfiguration/tesseract(withLanguageString:)":{"navigatorTitle":[{"text":"tesseractWithLanguageString:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration\/tesseract(withlanguagestring:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/tesseract(withLanguageString:)","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tesseract"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLanguageString"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKOpticalCharacterRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration"}],"abstract":[{"text":"Creates an OCR configuration using the mode ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/tesseract","isActive":true,"type":"reference"},{"type":"text","text":"."}],"kind":"symbol","title":"tesseract(withLanguageString:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognitionMode/tesseract":{"title":"SBSDKOpticalCharacterRecognitionMode.tesseract","abstract":[{"type":"text","text":"The legacy OCR mode using Tesseract. Slower, more error prone, but it supports more languages."}],"navigatorTitle":[{"text":"SBSDKOpticalCharacterRecognitionModeTesseract","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/tesseract","url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode\/tesseract","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"tesseract","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognizerConfiguration/init()":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration\/init()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/init()","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Designated initializer."}],"kind":"symbol","title":"init()","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognizerConfiguration/scanbotOCR()":{"navigatorTitle":[{"text":"scanbotOCR","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration\/scanbotocr()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/scanbotOCR()","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scanbotOCR"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"abstract":[{"type":"text","text":"Creates an OCR configuration using the mode "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/scanbotOCR","isActive":true},{"text":".","type":"text"}],"kind":"symbol","title":"scanbotOCR()","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognizerConfiguration/recognitionMode":{"navigatorTitle":[{"text":"recognitionMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration\/recognitionmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/recognitionMode","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognitionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOpticalCharacterRecognitionMode","text":"SBSDKOpticalCharacterRecognitionMode"}],"abstract":[{"text":"The recognition mode.","type":"text"}],"kind":"symbol","title":"recognitionMode","role":"symbol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognitionMode/scanbotOCR":{"navigatorTitle":[{"text":"SBSDKOpticalCharacterRecognitionModeScanbotOCR","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognitionmode\/scanbotocr","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/scanbotOCR","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"scanbotOCR","kind":"identifier"}],"abstract":[{"type":"text","text":"The new machine-learning based mode made by Scanbot SDK GmbH. Faster, less errors, but currently only"},{"text":" ","type":"text"},{"type":"text","text":"supports languages with latin letters."}],"kind":"symbol","title":"SBSDKOpticalCharacterRecognitionMode.scanbotOCR","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognizerConfiguration":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration","title":"SBSDKOpticalCharacterRecognizerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"abstract":[{"text":"A class describing the configuration of the optical character recognizer (OCR).","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognizerConfiguration/languages":{"navigatorTitle":[{"kind":"identifier","text":"languages"}],"url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration\/languages","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/languages","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"languages","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"An array of two-letter ISO 639-1 language code strings that are being used by the character recognizer."}],"kind":"symbol","title":"languages","role":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","type":"unresolvable","title":"NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognizerConfiguration/tesseract(with:)":{"abstract":[{"text":"Creates an OCR configuration using the mode ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognitionMode\/tesseract","type":"reference","isActive":true},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/tesseract(with:)","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tesseract"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration","kind":"typeIdentifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"title":"tesseract(with:)","navigatorTitle":[{"kind":"identifier","text":"tesseractWith:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration\/tesseract(with:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"SBSDKOpticalCharacterRecognizerConfiguration","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/languages","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/recognitionMode"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/init()"]},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/scanbotOCR()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/tesseract(with:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration\/tesseract(withLanguageString:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKOpticalCharacterRecognizerConfiguration","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"}},{"value":"tesseractWithLanguageString:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1tesseract(withLanguageString:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1tesseract(withLanguageString:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"tesseractWithLanguageString:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode~1tesseract\/title","value":"SBSDKOpticalCharacterRecognitionModeTesseract","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognitionModeTesseract"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode~1tesseract\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1init()\/title","op":"replace","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1scanbotOCR()\/title","value":"scanbotOCR","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1scanbotOCR()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"scanbotOCR"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1recognitionMode\/title","op":"replace","value":"recognitionMode"},{"op":"replace","value":[{"kind":"identifier","text":"recognitionMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1recognitionMode\/fragments"},{"value":"SBSDKOpticalCharacterRecognitionModeScanbotOCR","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode~1scanbotOCR\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognitionMode~1scanbotOCR\/fragments","value":[{"text":"SBSDKOpticalCharacterRecognitionModeScanbotOCR","kind":"identifier"}]},{"value":"SBSDKOpticalCharacterRecognizerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1languages\/title","op":"replace","value":"languages"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1languages\/fragments","op":"replace","value":[{"text":"languages","kind":"identifier"}]},{"value":"tesseractWith:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1tesseract(with:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration~1tesseract(with:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"tesseractWith:","kind":"identifier"}]}]}]}