{"abstract":[{"type":"text","text":"Configuration for the user interface of the document scanning screen."}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerUIConfiguration","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentScannerUIConfiguration","kind":"identifier"}],"platforms":[],"roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"SBSDKUIDocumentScannerUIConfiguration","kind":"identifier"}],"title":"SBSDKUIDocumentScannerUIConfiguration","role":"symbol"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/bottomBarBackgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/bottomBarButtonsColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/cameraBackgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isAutoSnappingButtonHidden","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isCancelButtonHidden","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isFlashButtonHidden","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isMultiPageButtonHidden","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isPolygonAutoSnapProgressEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isShutterButtonHidden","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/orientationLockMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonAutoSnapProgressColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonAutoSnapProgressLineWidth","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonBackgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonBackgroundColorOK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonColorOK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonCornerRadius","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonLineWidth","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/shutterButtonAutoInnerColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/shutterButtonAutoOuterColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/shutterButtonIndicatorColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/shutterButtonManualInnerColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/shutterButtonManualOuterColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/topBarBackgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/topBarButtonsActiveColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/topBarButtonsInactiveColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/userGuidanceBackgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/userGuidanceTextColor"],"title":"Instance Properties"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentScannerUIConfiguration","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration"]}],"references":{"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/orientationLockMode":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"orientationLockMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKOrientationLock","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock"}],"abstract":[{"type":"text","text":"Allowed orientations for automatic interface rotations."}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/orientationlockmode","role":"symbol","title":"orientationLockMode","navigatorTitle":[{"kind":"identifier","text":"orientationLockMode"}],"deprecated":true,"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/orientationLockMode","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/isPolygonAutoSnapProgressEnabled":{"navigatorTitle":[{"kind":"identifier","text":"isPolygonAutoSnapProgressEnabled"}],"abstract":[{"text":"Whether polygon auto snap progress animation is enabled or no.","type":"text"}],"kind":"symbol","deprecated":true,"title":"isPolygonAutoSnapProgressEnabled","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isPolygonAutoSnapProgressEnabled","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/ispolygonautosnapprogressenabled","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPolygonAutoSnapProgressEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/polygonCornerRadius":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonCornerRadius","abstract":[{"type":"text","text":"The radius to use when drawing rounded corners of the detected documents polygon."}],"type":"topic","navigatorTitle":[{"text":"polygonCornerRadius","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/polygoncornerradius","title":"polygonCornerRadius","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygonCornerRadius","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/topBarBackgroundColor":{"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/topbarbackgroundcolor","kind":"symbol","title":"topBarBackgroundColor","abstract":[{"text":"Background color of the top bar.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarBackgroundColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/topBarBackgroundColor","deprecated":true,"role":"symbol","navigatorTitle":[{"text":"topBarBackgroundColor","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/isCancelButtonHidden":{"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/iscancelbuttonhidden","title":"isCancelButtonHidden","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isCancelButtonHidden"}],"abstract":[{"type":"text","text":"Whether the cancel button is hidden or not."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isCancelButtonHidden","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","deprecated":true,"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isCancelButtonHidden"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/shutterButtonManualInnerColor":{"abstract":[{"type":"text","text":"Color of the shutter buttons inner ring in manual-capture mode."}],"type":"topic","title":"shutterButtonManualInnerColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shutterButtonManualInnerColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/shutterButtonManualInnerColor","navigatorTitle":[{"text":"shutterButtonManualInnerColor","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/shutterbuttonmanualinnercolor","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/polygonBackgroundColorOK":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/polygonbackgroundcolorok","abstract":[{"type":"text","text":"Background color of the detected documents polygon, when the polygons quality is acceptable."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"polygonBackgroundColorOK","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"kind":"identifier","text":"polygonBackgroundColorOK"}],"deprecated":true,"title":"polygonBackgroundColorOK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonBackgroundColorOK","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/topBarButtonsInactiveColor":{"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/topbarbuttonsinactivecolor","navigatorTitle":[{"text":"topBarButtonsInactiveColor","kind":"identifier"}],"type":"topic","deprecated":true,"title":"topBarButtonsInactiveColor","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/topBarButtonsInactiveColor","abstract":[{"type":"text","text":"Foreground color of disabled items in the top bar."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"topBarButtonsInactiveColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/polygonAutoSnapProgressLineWidth":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"polygonAutoSnapProgressLineWidth"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/polygonautosnapprogresslinewidth","abstract":[{"text":"Line width of polygon auto snap progress animation.","type":"text"}],"navigatorTitle":[{"text":"polygonAutoSnapProgressLineWidth","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonAutoSnapProgressLineWidth","type":"topic","role":"symbol","deprecated":true,"title":"polygonAutoSnapProgressLineWidth"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/bottomBarBackgroundColor":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/bottombarbackgroundcolor","abstract":[{"type":"text","text":"Background color of the bottom bar."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bottomBarBackgroundColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"navigatorTitle":[{"text":"bottomBarBackgroundColor","kind":"identifier"}],"deprecated":true,"title":"bottomBarBackgroundColor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/bottomBarBackgroundColor","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/polygonAutoSnapProgressColor":{"navigatorTitle":[{"text":"polygonAutoSnapProgressColor","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/polygonautosnapprogresscolor","title":"polygonAutoSnapProgressColor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonAutoSnapProgressColor","role":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"polygonAutoSnapProgressColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"kind":"symbol","abstract":[{"type":"text","text":"Stroke color of polygon auto snap progress animation."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/polygonBackgroundColor":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygonBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"title":"polygonBackgroundColor","abstract":[{"type":"text","text":"Background color of the detected documents polygon, when the polygons quality is not acceptable."}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/polygonbackgroundcolor","role":"symbol","type":"topic","navigatorTitle":[{"text":"polygonBackgroundColor","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonBackgroundColor","kind":"symbol"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/userGuidanceBackgroundColor":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/userguidancebackgroundcolor","abstract":[{"text":"Background color of the user guidance label.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userGuidanceBackgroundColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"userGuidanceBackgroundColor","kind":"identifier"}],"deprecated":true,"title":"userGuidanceBackgroundColor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/userGuidanceBackgroundColor","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/polygonColorOK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonColorOK","navigatorTitle":[{"text":"polygonColorOK","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/polygoncolorok","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"polygonColorOK","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"title":"polygonColorOK","abstract":[{"type":"text","text":"Foreground color of the detected documents polygon, when the polygons quality is acceptable."}],"kind":"symbol","role":"symbol","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration","navigatorTitle":[{"text":"SBSDKUIDocumentScannerUIConfiguration","kind":"identifier"}],"role":"symbol","title":"SBSDKUIDocumentScannerUIConfiguration","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIDocumentScannerUIConfiguration"}],"deprecated":true,"abstract":[{"type":"text","text":"Configuration for the user interface of the document scanning screen."}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/shutterButtonAutoOuterColor":{"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/shutterbuttonautooutercolor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/shutterButtonAutoOuterColor","role":"symbol","navigatorTitle":[{"text":"shutterButtonAutoOuterColor","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shutterButtonAutoOuterColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Color of the shutter buttons outer ring in auto-capture mode."}],"type":"topic","deprecated":true,"title":"shutterButtonAutoOuterColor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/polygonColor":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonColor","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/polygoncolor","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Foreground color of the detected documents polygon, when the polygons quality is not acceptable."}],"title":"polygonColor","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"polygonColor"}],"deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/isAutoSnappingButtonHidden":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAutoSnappingButtonHidden"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"isAutoSnappingButtonHidden","kind":"identifier"}],"abstract":[{"type":"text","text":"Whether the auto-snapping button is hidden or not."},{"type":"text","text":" "},{"text":"Has no effect, if ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isShutterButtonHidden","isActive":true},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":"."}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isAutoSnappingButtonHidden","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/isautosnappingbuttonhidden","title":"isAutoSnappingButtonHidden","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/shutterButtonAutoInnerColor":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/shutterbuttonautoinnercolor","navigatorTitle":[{"kind":"identifier","text":"shutterButtonAutoInnerColor"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/shutterButtonAutoInnerColor","title":"shutterButtonAutoInnerColor","role":"symbol","abstract":[{"type":"text","text":"Color of the shutter buttons inner ring in auto-capture mode."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutterButtonAutoInnerColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/topBarButtonsActiveColor":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/topBarButtonsActiveColor","title":"topBarButtonsActiveColor","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/topbarbuttonsactivecolor","type":"topic","navigatorTitle":[{"kind":"identifier","text":"topBarButtonsActiveColor"}],"deprecated":true,"abstract":[{"text":"Foreground color of enabled items in the top bar.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarButtonsActiveColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/bottomBarButtonsColor":{"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/bottombarbuttonscolor","title":"bottomBarButtonsColor","kind":"symbol","navigatorTitle":[{"text":"bottomBarButtonsColor","kind":"identifier"}],"abstract":[{"text":"Foreground color of the buttons in the bottom bar.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBarButtonsColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"role":"symbol","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/bottomBarButtonsColor","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/polygonLineWidth":{"navigatorTitle":[{"kind":"identifier","text":"polygonLineWidth"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonLineWidth","title":"polygonLineWidth","role":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"polygonLineWidth","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"abstract":[{"type":"text","text":"Width of the detected documents polygon in points."}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/polygonlinewidth","type":"topic"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/isFlashButtonHidden":{"navigatorTitle":[{"text":"isFlashButtonHidden","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Whether the flash button is hidden or not."}],"deprecated":true,"title":"isFlashButtonHidden","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isFlashButtonHidden","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/isflashbuttonhidden","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFlashButtonHidden","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/shutterButtonIndicatorColor":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/shutterButtonIndicatorColor","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/shutterbuttonindicatorcolor","kind":"symbol","role":"symbol","deprecated":true,"abstract":[{"type":"text","text":"Color of the shutter buttons activity indicator when capturing an image."}],"navigatorTitle":[{"text":"shutterButtonIndicatorColor","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shutterButtonIndicatorColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"type":"topic","title":"shutterButtonIndicatorColor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/cameraBackgroundColor":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cameraBackgroundColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"cameraBackgroundColor","role":"symbol","deprecated":true,"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/cameraBackgroundColor","abstract":[{"text":"Background color of the camera view.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"cameraBackgroundColor"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/camerabackgroundcolor","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/shutterButtonManualOuterColor":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/shutterButtonManualOuterColor","navigatorTitle":[{"kind":"identifier","text":"shutterButtonManualOuterColor"}],"kind":"symbol","type":"topic","title":"shutterButtonManualOuterColor","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/shutterbuttonmanualoutercolor","abstract":[{"type":"text","text":"Color of the shutter buttons outer ring in manual-capture mode."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shutterButtonManualOuterColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","title":"init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/init","kind":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/init","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/isMultiPageButtonHidden":{"type":"topic","kind":"symbol","title":"isMultiPageButtonHidden","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/ismultipagebuttonhidden","role":"symbol","navigatorTitle":[{"text":"isMultiPageButtonHidden","kind":"identifier"}],"deprecated":true,"abstract":[{"text":"Whether the multi-page button is hidden or not.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isMultiPageButtonHidden","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isMultiPageButtonHidden","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/isShutterButtonHidden":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isShutterButtonHidden","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/isshutterbuttonhidden","deprecated":true,"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isShutterButtonHidden","title":"isShutterButtonHidden","navigatorTitle":[{"kind":"identifier","text":"isShutterButtonHidden"}],"abstract":[{"type":"text","text":"Hides the shutter button if set to "},{"code":"True","type":"codeVoice"},{"text":". Shows it otherwise.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/userGuidanceTextColor":{"kind":"symbol","role":"symbol","deprecated":true,"navigatorTitle":[{"text":"userGuidanceTextColor","kind":"identifier"}],"title":"userGuidanceTextColor","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/userguidancetextcolor","abstract":[{"type":"text","text":"Foreground\/text color of the user guidance label."}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"userGuidanceTextColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/userGuidanceTextColor"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[],"op":"replace","path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKUIDocumentScannerUIConfiguration","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKUIDocumentScannerUIConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerUIConfiguration"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/bottomBarBackgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/bottomBarButtonsColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/cameraBackgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isAutoSnappingButtonHidden","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isCancelButtonHidden","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isFlashButtonHidden","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isMultiPageButtonHidden","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isPolygonAutoSnapProgressEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/isShutterButtonHidden","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/orientationLockMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonAutoSnapProgressColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonAutoSnapProgressLineWidth","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonBackgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonBackgroundColorOK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonColorOK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonCornerRadius","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/polygonLineWidth","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/shutterButtonAutoInnerColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/shutterButtonAutoOuterColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/shutterButtonIndicatorColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/shutterButtonManualInnerColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/shutterButtonManualOuterColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/topBarBackgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/topBarButtonsActiveColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/topBarButtonsInactiveColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/userGuidanceBackgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/userGuidanceTextColor"],"generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/init"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerUIConfiguration"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1orientationLockMode\/title","value":"orientationLockMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1orientationLockMode\/fragments","value":[{"kind":"identifier","text":"orientationLockMode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1isPolygonAutoSnapProgressEnabled\/title","value":"isPolygonAutoSnapProgressEnabled"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1isPolygonAutoSnapProgressEnabled\/fragments","value":[{"text":"isPolygonAutoSnapProgressEnabled","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1polygonCornerRadius\/title","value":"polygonCornerRadius"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1polygonCornerRadius\/fragments","value":[{"kind":"identifier","text":"polygonCornerRadius"}]},{"value":"topBarBackgroundColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1topBarBackgroundColor\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1topBarBackgroundColor\/fragments","op":"replace","value":[{"text":"topBarBackgroundColor","kind":"identifier"}]},{"op":"replace","value":"isCancelButtonHidden","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1isCancelButtonHidden\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1isCancelButtonHidden\/fragments","value":[{"kind":"identifier","text":"isCancelButtonHidden"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1shutterButtonManualInnerColor\/title","op":"replace","value":"shutterButtonManualInnerColor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1shutterButtonManualInnerColor\/fragments","value":[{"text":"shutterButtonManualInnerColor","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1polygonBackgroundColorOK\/title","value":"polygonBackgroundColorOK","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1polygonBackgroundColorOK\/fragments","value":[{"kind":"identifier","text":"polygonBackgroundColorOK"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1topBarButtonsInactiveColor\/title","value":"topBarButtonsInactiveColor","op":"replace"},{"value":[{"text":"topBarButtonsInactiveColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1topBarButtonsInactiveColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1polygonAutoSnapProgressLineWidth\/title","value":"polygonAutoSnapProgressLineWidth"},{"value":[{"text":"polygonAutoSnapProgressLineWidth","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1polygonAutoSnapProgressLineWidth\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1bottomBarBackgroundColor\/title","value":"bottomBarBackgroundColor"},{"value":[{"kind":"identifier","text":"bottomBarBackgroundColor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1bottomBarBackgroundColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1polygonAutoSnapProgressColor\/title","value":"polygonAutoSnapProgressColor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1polygonAutoSnapProgressColor\/fragments","value":[{"kind":"identifier","text":"polygonAutoSnapProgressColor"}],"op":"replace"},{"op":"replace","value":"polygonBackgroundColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1polygonBackgroundColor\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1polygonBackgroundColor\/fragments","value":[{"text":"polygonBackgroundColor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1userGuidanceBackgroundColor\/title","value":"userGuidanceBackgroundColor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1userGuidanceBackgroundColor\/fragments","value":[{"kind":"identifier","text":"userGuidanceBackgroundColor"}],"op":"replace"},{"value":"polygonColorOK","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1polygonColorOK\/title","op":"replace"},{"value":[{"kind":"identifier","text":"polygonColorOK"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1polygonColorOK\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration\/title","value":"SBSDKUIDocumentScannerUIConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerUIConfiguration"}],"op":"replace"},{"value":[{"text":"SBSDKUIDocumentScannerUIConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1shutterButtonAutoOuterColor\/title","op":"replace","value":"shutterButtonAutoOuterColor"},{"value":[{"text":"shutterButtonAutoOuterColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1shutterButtonAutoOuterColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1polygonColor\/title","value":"polygonColor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1polygonColor\/fragments","value":[{"text":"polygonColor","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1isAutoSnappingButtonHidden\/title","op":"replace","value":"isAutoSnappingButtonHidden"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1isAutoSnappingButtonHidden\/fragments","op":"replace","value":[{"text":"isAutoSnappingButtonHidden","kind":"identifier"}]},{"op":"replace","value":"shutterButtonAutoInnerColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1shutterButtonAutoInnerColor\/title"},{"value":[{"kind":"identifier","text":"shutterButtonAutoInnerColor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1shutterButtonAutoInnerColor\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1topBarButtonsActiveColor\/title","op":"replace","value":"topBarButtonsActiveColor"},{"value":[{"text":"topBarButtonsActiveColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1topBarButtonsActiveColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1bottomBarButtonsColor\/title","value":"bottomBarButtonsColor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1bottomBarButtonsColor\/fragments","value":[{"text":"bottomBarButtonsColor","kind":"identifier"}],"op":"replace"},{"value":"polygonLineWidth","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1polygonLineWidth\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1polygonLineWidth\/fragments","value":[{"text":"polygonLineWidth","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1isFlashButtonHidden\/title","op":"replace","value":"isFlashButtonHidden"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1isFlashButtonHidden\/fragments","op":"replace","value":[{"kind":"identifier","text":"isFlashButtonHidden"}]},{"op":"replace","value":"shutterButtonIndicatorColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1shutterButtonIndicatorColor\/title"},{"value":[{"kind":"identifier","text":"shutterButtonIndicatorColor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1shutterButtonIndicatorColor\/fragments"},{"value":"cameraBackgroundColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1cameraBackgroundColor\/title"},{"value":[{"text":"cameraBackgroundColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1cameraBackgroundColor\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1shutterButtonManualOuterColor\/title","op":"replace","value":"shutterButtonManualOuterColor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1shutterButtonManualOuterColor\/fragments","value":[{"kind":"identifier","text":"shutterButtonManualOuterColor"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1isMultiPageButtonHidden\/title","value":"isMultiPageButtonHidden"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1isMultiPageButtonHidden\/fragments","op":"replace","value":[{"kind":"identifier","text":"isMultiPageButtonHidden"}]},{"value":"isShutterButtonHidden","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1isShutterButtonHidden\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1isShutterButtonHidden\/fragments","value":[{"kind":"identifier","text":"isShutterButtonHidden"}]},{"value":"userGuidanceTextColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1userGuidanceTextColor\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1userGuidanceTextColor\/fragments","value":[{"text":"userGuidanceTextColor","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}