{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"type":"text","text":"Configure the orientation of the interface."}],"topicSections":[{"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/landscape","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/none","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/portrait"]},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/init(rawValue:)"],"anchor":"Initializers"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2OrientationLockMode) ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2OrientationLockMode","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode"]}],"metadata":{"roleHeading":"Enumeration","title":"SBSDKUI2OrientationLockMode","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2OrientationLockMode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2OrientationLockMode","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKUI2OrientationLockMode","kind":"identifier"}],"symbolKind":"enum"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2OrientationLockMode/RawRepresentable-Implementations":{"kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode\/rawrepresentable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2OrientationLockMode/landscape":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/landscape","title":"SBSDKUI2OrientationLockMode.landscape","type":"topic","role":"symbol","abstract":[{"text":"Lock the orientation to landscape.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape"}],"navigatorTitle":[{"text":"SBSDKUI2OrientationLockModeLandscape","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode\/landscape","kind":"symbol"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2OrientationLockMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode","title":"SBSDKUI2OrientationLockMode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode","abstract":[{"type":"text","text":"Configure the orientation of the interface."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2OrientationLockMode/portrait":{"kind":"symbol","abstract":[{"type":"text","text":"Lock the orientation to portrait."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/portrait","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"portrait","kind":"identifier"}],"title":"SBSDKUI2OrientationLockMode.portrait","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2OrientationLockModePortrait"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode\/portrait"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2OrientationLockMode/Equatable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/Equatable-Implementations","title":"Equatable Implementations","type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode\/equatable-implementations","kind":"article"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2OrientationLockMode/none":{"kind":"symbol","abstract":[{"type":"text","text":"Do not restrict the interface’s orientation."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/none","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"title":"SBSDKUI2OrientationLockMode.none","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2OrientationLockModeNone","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode\/none"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2OrientationLockMode/init(rawValue:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/init(rawValue:)","title":"init(rawValue:)","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode\/init(rawvalue:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"SBSDKUI2OrientationLockMode","path":"\/metadata\/title","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/landscape","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/none","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/portrait"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2OrientationLockMode","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"SBSDKUI2OrientationLockModeLandscape","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode~1landscape\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode~1landscape\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2OrientationLockModeLandscape"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode\/title","op":"replace","value":"SBSDKUI2OrientationLockMode"},{"value":[{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode~1portrait\/title","op":"replace","value":"SBSDKUI2OrientationLockModePortrait"},{"value":[{"kind":"identifier","text":"SBSDKUI2OrientationLockModePortrait"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode~1portrait\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode~1none\/title","op":"replace","value":"SBSDKUI2OrientationLockModeNone"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode~1none\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2OrientationLockModeNone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}