{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/delegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/isRecognitionEnabled"]},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/create(configuration:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/present(on:configuration:delegate:)"]},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/SBSDKMedicalCertificateScannerViewControllerDelegate-Implementations"],"title":"Default Implementations"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController"],"title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/s8SendableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring","doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewController"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller"]}],"abstract":[{"text":"A Ready-To-Use viewController to scan medical certificates.","type":"text"}],"kind":"symbol","metadata":{"title":"SBSDKUIMedicalCertificateScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewController"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","role":"symbol","roleHeading":"Class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewController"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/create(configuration:delegate:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/create(configuration:delegate:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"SBSDKUIMedicalCertificateScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIMedicalCertificateScannerViewControllerDelegate","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerViewController","text":"SBSDKUIMedicalCertificateScannerViewController"}],"navigatorTitle":[{"text":"createWithConfiguration:delegate:","kind":"identifier"}],"abstract":[{"type":"text","text":"Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/create(configuration:delegate:)","kind":"symbol","type":"topic","role":"symbol","title":"create(configuration:delegate:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/willShowEnableCameraView":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/willShowEnableCameraView","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willShowEnableCameraView"}],"navigatorTitle":[{"kind":"identifier","text":"willShowEnableCameraView"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/willshowenablecameraview","abstract":[],"kind":"symbol","type":"topic","role":"symbol","title":"willShowEnableCameraView"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewController"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller","title":"SBSDKUIMedicalCertificateScannerViewController","abstract":[{"text":"A Ready-To-Use viewController to scan medical certificates.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/initWithCoder:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/initwithcoder:","kind":"symbol","type":"topic","role":"symbol","title":"initWithCoder:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/viewWillAppear:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/viewWillAppear:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}],"navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/viewwillappear:","abstract":[],"kind":"symbol","type":"topic","role":"symbol","title":"viewWillAppear:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/SBSDKMedicalCertificateScannerViewControllerDelegate-Implementations":{"type":"topic","kind":"article","role":"collectionGroup","title":"SBSDKMedicalCertificateScannerViewControllerDelegate Implementations","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/sbsdkmedicalcertificatescannerviewcontrollerdelegate-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/SBSDKMedicalCertificateScannerViewControllerDelegate-Implementations","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/isRecognitionEnabled":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/isRecognitionEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isRecognitionEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isRecognitionEnabled","kind":"identifier"}],"abstract":[{"type":"text","text":"Enables or disables the recognition."}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/isrecognitionenabled","kind":"symbol","type":"topic","role":"symbol","title":"isRecognitionEnabled"},"doc://net.doo.ScanbotSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/supportedInterfaceOrientations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/supportedInterfaceOrientations","fragments":[{"text":"supportedInterfaceOrientations","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/supportedinterfaceorientations","kind":"symbol","type":"topic","role":"symbol","title":"supportedInterfaceOrientations"},"doc://net.doo.ScanbotSDK/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling"},"doc://net.doo.ScanbotSDK/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/delegate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/delegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIMedicalCertificateScannerViewControllerDelegate","text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/delegate","abstract":[{"text":"The receivers delegate.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","title":"delegate"},"doc://net.doo.ScanbotSDK/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer"},"doc://net.doo.ScanbotSDK/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment"},"doc://net.doo.ScanbotSDK/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s8SendableP"},"doc://net.doo.ScanbotSDK/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/enableCameraTextConfiguration":{"fragments":[{"text":"enableCameraTextConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","title":"enableCameraTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/enablecameratextconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/enableCameraTextConfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewController":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIViewController"}],"abstract":[{"text":"An abstract base class for RTU-UI view controllers.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","type":"topic","title":"SBSDKUIViewController","url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontroller","role":"symbol","navigatorTitle":[{"text":"SBSDKUIViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/present(on:configuration:delegate:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/present(on:configuration:delegate:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"SBSDKUIMedicalCertificateScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIMedicalCertificateScannerViewControllerDelegate"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerViewController","kind":"typeIdentifier","text":"SBSDKUIMedicalCertificateScannerViewController"}],"navigatorTitle":[{"text":"presentOn:configuration:delegate:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/present(on:configuration:delegate:)","abstract":[{"text":"Creates a new instance of ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","isActive":true},{"type":"text","text":" and presents it modally."}],"kind":"symbol","type":"topic","role":"symbol","title":"present(on:configuration:delegate:)"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/didHideEnableCameraView":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/didHideEnableCameraView","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didHideEnableCameraView"}],"navigatorTitle":[{"text":"didHideEnableCameraView","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/didhideenablecameraview","kind":"symbol","type":"topic","role":"symbol","title":"didHideEnableCameraView"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller","title":"SBSDKMedicalCertificateScannerViewController","kind":"symbol","abstract":[{"text":"The classic UI view controller that can be used to detect and recognize medical certificates. Can be configured to recognize on video frames or,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"for better accuracy, on high-res photos that are automatically captured."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/updateLayout":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/updateLayout","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateLayout"}],"navigatorTitle":[{"kind":"identifier","text":"updateLayout"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/updatelayout","kind":"symbol","type":"topic","role":"symbol","title":"updateLayout"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/enableCameraUIConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/enableCameraUIConfiguration","fragments":[{"kind":"identifier","text":"enableCameraUIConfiguration"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/enablecamerauiconfiguration","kind":"symbol","type":"topic","role":"symbol","title":"enableCameraUIConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewControllerDelegate":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontrollerdelegate","title":"SBSDKMedicalCertificateScannerViewControllerDelegate","kind":"symbol","abstract":[{"text":"The delegation protocol for the ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController","isActive":true},{"text":" class.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewControllerDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateScannerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewControllerDelegate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/viewDidAppear:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/viewDidAppear:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}],"navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/viewdidappear:","abstract":[],"kind":"symbol","type":"topic","role":"symbol","title":"viewDidAppear:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraViewController":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICameraViewController","kind":"identifier"}],"abstract":[{"text":"A ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","isActive":true,"type":"reference"},{"text":" subclass which adds support for enabled and disabled camera permission.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController","type":"topic","title":"SBSDKUICameraViewController","url":"\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller","role":"symbol","navigatorTitle":[{"text":"SBSDKUICameraViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/updateFlashButton":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/updateFlashButton","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateFlashButton"}],"navigatorTitle":[{"kind":"identifier","text":"updateFlashButton"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/updateflashbutton","abstract":[],"kind":"symbol","type":"topic","role":"symbol","title":"updateFlashButton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/containerForEnableCameraView":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/containerForEnableCameraView","fragments":[{"kind":"identifier","text":"containerForEnableCameraView"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/containerforenablecameraview","kind":"symbol","type":"topic","role":"symbol","title":"containerForEnableCameraView"},"doc://net.doo.ScanbotSDK/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://net.doo.ScanbotSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/viewDidLoad":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/viewDidLoad","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/viewdidload","abstract":[],"kind":"symbol","type":"topic","role":"symbol","title":"viewDidLoad"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/cameraAccessDidChange:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/cameraAccessDidChange:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cameraAccessDidChange:"}],"navigatorTitle":[{"kind":"identifier","text":"cameraAccessDidChange:"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/cameraaccessdidchange:","kind":"symbol","type":"topic","role":"symbol","title":"cameraAccessDidChange:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUIMedicalCertificateScannerViewController"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewController"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/containerForEnableCameraView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/delegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/enableCameraTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/enableCameraUIConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/isRecognitionEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/supportedInterfaceOrientations"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/cameraAccessDidChange:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/didHideEnableCameraView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/initWithCoder:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/updateFlashButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/updateLayout","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/viewDidAppear:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/viewDidLoad","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/viewWillAppear:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/willShowEnableCameraView"]},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/create(configuration:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/present(on:configuration:delegate:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/SBSDKMedicalCertificateScannerViewControllerDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController"]},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewControllerDelegate"],"title":"Conforms To"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewController"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraViewController","kind":"typeIdentifier","text":"SBSDKUICameraViewController"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"createWithConfiguration:delegate:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController~1create(configuration:delegate:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController~1create(configuration:delegate:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithConfiguration:delegate:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/title","value":"SBSDKUIMedicalCertificateScannerViewController"},{"value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/fragments"},{"value":"isRecognitionEnabled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController~1isRecognitionEnabled\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController~1isRecognitionEnabled\/fragments","value":[{"text":"isRecognitionEnabled","kind":"identifier"}]},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController~1delegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/title","value":"SBSDKUIViewController"},{"value":[{"kind":"identifier","text":"SBSDKUIViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController~1present(on:configuration:delegate:)\/title","value":"presentOn:configuration:delegate:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController~1present(on:configuration:delegate:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"presentOn:configuration:delegate:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/title","value":"SBSDKMedicalCertificateScannerViewController"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewControllerDelegate\/title","value":"SBSDKMedicalCertificateScannerViewControllerDelegate","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewControllerDelegate\/fragments"},{"value":"SBSDKUICameraViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/title"},{"value":[{"text":"SBSDKUICameraViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/fragments"}]}]}