{"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/noFilter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/onlyWithExtensions","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/onlyWithoutExtensions"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/init(rawValue:)"]},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodesextensionfilter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodesextensionfilter"]}],"metadata":{"title":"SBSDKBarcodesExtensionFilter","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodesExtensionFilter","symbolKind":"enum","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodesExtensionFilter","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodesExtensionFilter","kind":"identifier"}],"roleHeading":"Enumeration"},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter"},"abstract":[{"text":"Filter for extended EAN and UPC barcodes.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKBarcodesExtensionFilter","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodesExtensionFilter/onlyWithExtensions":{"role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodesExtensionFilterOnlyWithExtensions","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodesextensionfilter\/onlywithextensions","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/onlyWithExtensions","title":"SBSDKBarcodesExtensionFilter.onlyWithExtensions","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onlyWithExtensions","kind":"identifier"}],"abstract":[{"type":"text","text":"Only EAN and UPC barcoded with extensions will be returned."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodesExtensionFilter/init(rawValue:)":{"title":"init(rawValue:)","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/init(rawValue:)","url":"\/documentation\/scanbotsdk\/sbsdkbarcodesextensionfilter\/init(rawvalue:)","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodesExtensionFilter/noFilter":{"navigatorTitle":[{"text":"SBSDKBarcodesExtensionFilterNoFilter","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noFilter","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodesextensionfilter\/nofilter","abstract":[{"type":"text","text":"EAN and UPC barcoded with or without extensions will be returned."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/noFilter","title":"SBSDKBarcodesExtensionFilter.noFilter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodesExtensionFilter/onlyWithoutExtensions":{"title":"SBSDKBarcodesExtensionFilter.onlyWithoutExtensions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilterOnlyWithoutExtensions"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"onlyWithoutExtensions","kind":"identifier"}],"abstract":[{"type":"text","text":"Only EAN and UPC barcoded without extensions will be returned."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/onlyWithoutExtensions","url":"\/documentation\/scanbotsdk\/sbsdkbarcodesextensionfilter\/onlywithoutextensions","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodesExtensionFilter/Equatable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodesextensionfilter\/equatable-implementations","type":"topic","title":"Equatable Implementations","role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/Equatable-Implementations"},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodesExtensionFilter":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodesextensionfilter","type":"topic","title":"SBSDKBarcodesExtensionFilter","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodesExtensionFilter","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Filter for extended EAN and UPC barcodes."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter","navigatorTitle":[{"text":"SBSDKBarcodesExtensionFilter","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodesExtensionFilter/RawRepresentable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodesextensionfilter\/rawrepresentable-implementations","abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodesExtensionFilter"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","value":[{"text":"SBSDKBarcodesExtensionFilter","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilter"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/noFilter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/onlyWithExtensions","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/onlyWithoutExtensions"],"title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodesExtensionFilter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKBarcodesExtensionFilterOnlyWithExtensions","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodesExtensionFilter~1onlyWithExtensions\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilterOnlyWithExtensions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodesExtensionFilter~1onlyWithExtensions\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodesExtensionFilter~1noFilter\/title","op":"replace","value":"SBSDKBarcodesExtensionFilterNoFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodesExtensionFilter~1noFilter\/fragments","value":[{"text":"SBSDKBarcodesExtensionFilterNoFilter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodesExtensionFilter~1onlyWithoutExtensions\/title","value":"SBSDKBarcodesExtensionFilterOnlyWithoutExtensions"},{"value":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilterOnlyWithoutExtensions"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodesExtensionFilter~1onlyWithoutExtensions\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodesExtensionFilter\/title","value":"SBSDKBarcodesExtensionFilter"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodesExtensionFilter\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}