{"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"type":"conformsTo","kind":"relationships"}],"sections":[],"abstract":[{"text":"The block type of an OCR fragment.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/line","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/paragraph","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/word"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKOCRResultBlockType","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"inlineContent":[{"type":"text","text":"When an OCR operation finishes it returns an array of result blocks containing e.g. the position and type of recognized text fragment."},{"type":"text","text":" "},{"type":"text","text":"Each of the result blocks has a specific type."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrresultblocktype"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkocrresultblocktype"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKOCRResultBlockType","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Enumeration","navigatorTitle":[{"text":"SBSDKOCRResultBlockType","kind":"identifier"}],"title":"SBSDKOCRResultBlockType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKOCRResultBlockType","kind":"identifier"}],"symbolKind":"enum","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlockType/line":{"url":"\/documentation\/scanbotsdk\/sbsdkocrresultblocktype\/line","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKOCRResultBlockTypeLine","kind":"identifier"}],"title":"SBSDKOCRResultBlockType.line","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/line","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"line","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The result block represents a text line."}]},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlockType/RawRepresentable-Implementations":{"kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkocrresultblocktype\/rawrepresentable-implementations","abstract":[],"type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/RawRepresentable-Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlockType/Equatable-Implementations":{"type":"topic","abstract":[],"kind":"article","role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/Equatable-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkocrresultblocktype\/equatable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlockType/paragraph":{"url":"\/documentation\/scanbotsdk\/sbsdkocrresultblocktype\/paragraph","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKOCRResultBlockTypeParagraph","kind":"identifier"}],"title":"SBSDKOCRResultBlockType.paragraph","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/paragraph","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"paragraph","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The result block represents a text paragraph."}]},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlockType/word":{"url":"\/documentation\/scanbotsdk\/sbsdkocrresultblocktype\/word","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKOCRResultBlockTypeWord","kind":"identifier"}],"title":"SBSDKOCRResultBlockType.word","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/word","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"word","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The result block represents a word."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlockType":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType","title":"SBSDKOCRResultBlockType","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrresultblocktype","abstract":[{"type":"text","text":"The block type of an OCR fragment."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCRResultBlockType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKOCRResultBlockType","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlockType/init(rawValue:)":{"url":"\/documentation\/scanbotsdk\/sbsdkocrresultblocktype\/init(rawvalue:)","type":"topic","kind":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKOCRResultBlockType"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKOCRResultBlockType","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKOCRResultBlockType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/line","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/paragraph","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/word"],"title":"Enumeration Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKOCRResultBlockType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType~1line\/title","value":"SBSDKOCRResultBlockTypeLine","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKOCRResultBlockTypeLine"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType~1line\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType~1paragraph\/title","value":"SBSDKOCRResultBlockTypeParagraph"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType~1paragraph\/fragments","op":"replace","value":[{"text":"SBSDKOCRResultBlockTypeParagraph","kind":"identifier"}]},{"op":"replace","value":"SBSDKOCRResultBlockTypeWord","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType~1word\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType~1word\/fragments","value":[{"kind":"identifier","text":"SBSDKOCRResultBlockTypeWord"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType\/title","value":"SBSDKOCRResultBlockType"},{"value":[{"kind":"identifier","text":"SBSDKOCRResultBlockType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}