{"sections":[],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/cancelButtonAccessibilityHint","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/cancelButtonAccessibilityLabel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/detectButtonAccessibilityHint","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/detectButtonAccessibilityLabel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/doneButtonAccessibilityHint","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/doneButtonAccessibilityLabel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/resetButtonAccessibilityHint","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/resetButtonAccessibilityLabel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/rotateButtonAccessibilityHint","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/rotateButtonAccessibilityLabel"],"generated":true,"title":"Instance Properties"}],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenAccessibilityConfiguration","symbolKind":"class","title":"SBSDKUICroppingScreenAccessibilityConfiguration","modules":[{"name":"ScanbotSDK"}],"platforms":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUICroppingScreenAccessibilityConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingScreenAccessibilityConfiguration"}],"roleHeading":"Class"},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration"]}],"abstract":[{"type":"text","text":"Configuration for the accessibility labels and hints."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICroppingScreenAccessibilityConfiguration"}]}],"kind":"declarations"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2CroppingViewController instead.","type":"text"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenAccessibilityConfiguration/cancelButtonAccessibilityLabel":{"role":"symbol","type":"topic","deprecated":true,"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/cancelButtonAccessibilityLabel","title":"cancelButtonAccessibilityLabel","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cancelButtonAccessibilityLabel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"cancelButtonAccessibilityLabel"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/cancelbuttonaccessibilitylabel","abstract":[{"text":"Text, that is used as an accessibility label for the cancel button.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenAccessibilityConfiguration/detectButtonAccessibilityHint":{"abstract":[{"type":"text","text":"Text, that is used as an accessibility hint for the detect button."}],"navigatorTitle":[{"kind":"identifier","text":"detectButtonAccessibilityHint"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"detectButtonAccessibilityHint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/detectbuttonaccessibilityhint","kind":"symbol","title":"detectButtonAccessibilityHint","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/detectButtonAccessibilityHint","deprecated":true,"type":"topic"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenAccessibilityConfiguration/doneButtonAccessibilityHint":{"role":"symbol","type":"topic","deprecated":true,"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/doneButtonAccessibilityHint","title":"doneButtonAccessibilityHint","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"doneButtonAccessibilityHint"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"doneButtonAccessibilityHint","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/donebuttonaccessibilityhint","abstract":[{"text":"Text, that is used as an accessibility hint for the done button.","type":"text"}]},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenAccessibilityConfiguration":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICroppingScreenAccessibilityConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration","role":"symbol","deprecated":true,"abstract":[{"type":"text","text":"Configuration for the accessibility labels and hints."}],"navigatorTitle":[{"text":"SBSDKUICroppingScreenAccessibilityConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration","title":"SBSDKUICroppingScreenAccessibilityConfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenAccessibilityConfiguration/resetButtonAccessibilityLabel":{"abstract":[{"text":"Text, that is used as an accessibility label for the reset button.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/resetbuttonaccessibilitylabel","title":"resetButtonAccessibilityLabel","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/resetButtonAccessibilityLabel","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"resetButtonAccessibilityLabel"}],"deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"resetButtonAccessibilityLabel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenAccessibilityConfiguration/cancelButtonAccessibilityHint":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/cancelbuttonaccessibilityhint","navigatorTitle":[{"text":"cancelButtonAccessibilityHint","kind":"identifier"}],"abstract":[{"text":"Text, that is used as an accessibility hint for the cancel button.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cancelButtonAccessibilityHint","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/cancelButtonAccessibilityHint","deprecated":true,"title":"cancelButtonAccessibilityHint"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenAccessibilityConfiguration/init":{"abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/init","title":"init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/init","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenAccessibilityConfiguration/rotateButtonAccessibilityHint":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/rotatebuttonaccessibilityhint","navigatorTitle":[{"text":"rotateButtonAccessibilityHint","kind":"identifier"}],"abstract":[{"text":"Text, that is used as an accessibility hint for the rotate button.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"rotateButtonAccessibilityHint","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/rotateButtonAccessibilityHint","deprecated":true,"title":"rotateButtonAccessibilityHint"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenAccessibilityConfiguration/doneButtonAccessibilityLabel":{"abstract":[{"text":"Text, that is used as an accessibility label for the done button.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/donebuttonaccessibilitylabel","title":"doneButtonAccessibilityLabel","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/doneButtonAccessibilityLabel","role":"symbol","navigatorTitle":[{"text":"doneButtonAccessibilityLabel","kind":"identifier"}],"deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"doneButtonAccessibilityLabel","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenAccessibilityConfiguration/detectButtonAccessibilityLabel":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/detectbuttonaccessibilitylabel","navigatorTitle":[{"text":"detectButtonAccessibilityLabel","kind":"identifier"}],"abstract":[{"text":"Text, that is used as an accessibility label for the detect button.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"detectButtonAccessibilityLabel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/detectButtonAccessibilityLabel","deprecated":true,"title":"detectButtonAccessibilityLabel"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenAccessibilityConfiguration/resetButtonAccessibilityHint":{"abstract":[{"text":"Text, that is used as an accessibility hint for the reset button.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/resetbuttonaccessibilityhint","title":"resetButtonAccessibilityHint","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/resetButtonAccessibilityHint","role":"symbol","navigatorTitle":[{"text":"resetButtonAccessibilityHint","kind":"identifier"}],"deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"resetButtonAccessibilityHint","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenAccessibilityConfiguration/rotateButtonAccessibilityLabel":{"abstract":[{"text":"Text, that is used as an accessibility label for the rotate button.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/rotatebuttonaccessibilitylabel","title":"rotateButtonAccessibilityLabel","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/rotateButtonAccessibilityLabel","role":"symbol","navigatorTitle":[{"text":"rotateButtonAccessibilityLabel","kind":"identifier"}],"deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"rotateButtonAccessibilityLabel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[],"op":"replace","path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUICroppingScreenAccessibilityConfiguration"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUICroppingScreenAccessibilityConfiguration","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUICroppingScreenAccessibilityConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/cancelButtonAccessibilityHint","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/cancelButtonAccessibilityLabel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/detectButtonAccessibilityHint","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/detectButtonAccessibilityLabel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/doneButtonAccessibilityHint","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/doneButtonAccessibilityLabel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/resetButtonAccessibilityHint","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/resetButtonAccessibilityLabel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/rotateButtonAccessibilityHint","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/rotateButtonAccessibilityLabel"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/init"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICroppingScreenAccessibilityConfiguration","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1cancelButtonAccessibilityLabel\/title","op":"replace","value":"cancelButtonAccessibilityLabel"},{"op":"replace","value":[{"kind":"identifier","text":"cancelButtonAccessibilityLabel"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1cancelButtonAccessibilityLabel\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1detectButtonAccessibilityHint\/title","op":"replace","value":"detectButtonAccessibilityHint"},{"value":[{"text":"detectButtonAccessibilityHint","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1detectButtonAccessibilityHint\/fragments"},{"op":"replace","value":"doneButtonAccessibilityHint","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1doneButtonAccessibilityHint\/title"},{"value":[{"text":"doneButtonAccessibilityHint","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1doneButtonAccessibilityHint\/fragments","op":"replace"},{"value":"SBSDKUICroppingScreenAccessibilityConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUICroppingScreenAccessibilityConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUICroppingScreenAccessibilityConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration\/navigatorTitle"},{"value":"resetButtonAccessibilityLabel","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1resetButtonAccessibilityLabel\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1resetButtonAccessibilityLabel\/fragments","value":[{"kind":"identifier","text":"resetButtonAccessibilityLabel"}]},{"value":"cancelButtonAccessibilityHint","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1cancelButtonAccessibilityHint\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1cancelButtonAccessibilityHint\/fragments","value":[{"kind":"identifier","text":"cancelButtonAccessibilityHint"}]},{"op":"replace","value":"rotateButtonAccessibilityHint","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1rotateButtonAccessibilityHint\/title"},{"value":[{"text":"rotateButtonAccessibilityHint","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1rotateButtonAccessibilityHint\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1doneButtonAccessibilityLabel\/title","value":"doneButtonAccessibilityLabel"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1doneButtonAccessibilityLabel\/fragments","op":"replace","value":[{"text":"doneButtonAccessibilityLabel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1detectButtonAccessibilityLabel\/title","op":"replace","value":"detectButtonAccessibilityLabel"},{"op":"replace","value":[{"kind":"identifier","text":"detectButtonAccessibilityLabel"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1detectButtonAccessibilityLabel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1resetButtonAccessibilityHint\/title","value":"resetButtonAccessibilityHint"},{"value":[{"kind":"identifier","text":"resetButtonAccessibilityHint"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1resetButtonAccessibilityHint\/fragments"},{"value":"rotateButtonAccessibilityLabel","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1rotateButtonAccessibilityLabel\/title"},{"value":[{"kind":"identifier","text":"rotateButtonAccessibilityLabel"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1rotateButtonAccessibilityLabel\/fragments"}]}]}