{"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerSettings","title":"SBSDKUIDocumentScannerSettings","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentScannerSettings","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerSettings"}],"roleHeading":"Class","platforms":[]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2DocumentScannerViewController instead."}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"A snapshot of the current settings of an ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController","type":"reference"},{"text":" instance.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerSettings"}]}]},{"content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"inlineContent":[{"type":"text","text":"Can be used to persist and restore changes made by the user."}],"type":"paragraph"}],"kind":"content"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerSettings"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerSettings\/autoSnappingEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerSettings\/flashEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerSettings\/multiPageEnabled"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannersettings"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannersettings"]}],"references":{"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerSettings":{"deprecated":true,"abstract":[{"text":"A snapshot of the current settings of an ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController","type":"reference"},{"type":"text","text":" instance."}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannersettings","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIDocumentScannerSettings"}],"title":"SBSDKUIDocumentScannerSettings","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerSettings","navigatorTitle":[{"text":"SBSDKUIDocumentScannerSettings","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerSettings/multiPageEnabled":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerSettings\/multiPageEnabled","kind":"symbol","title":"multiPageEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"multiPageEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"Whether multi-page capturing is enabled or not.","type":"text"}],"deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"multiPageEnabled"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannersettings\/multipageenabled"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerSettings/init":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerSettings\/init","kind":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannersettings\/init"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerViewController":{"title":"SBSDKUIDocumentScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController","role":"symbol","type":"topic","deprecated":true},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerSettings/autoSnappingEnabled":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerSettings\/autoSnappingEnabled","kind":"symbol","title":"autoSnappingEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"autoSnappingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"text":"Whether automatic image capturing is enabled or not.","type":"text"}],"deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"autoSnappingEnabled"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannersettings\/autosnappingenabled"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerSettings/flashEnabled":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"flashEnabled"}],"abstract":[{"type":"text","text":"Whether the flash light is enabled or not."}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannersettings\/flashenabled","title":"flashEnabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"flashEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"deprecated":true,"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerSettings\/flashEnabled","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKUIDocumentScannerSettings","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerSettings"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerSettings"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerSettings\/autoSnappingEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerSettings\/flashEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerSettings\/multiPageEnabled"],"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerSettings\/init"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentScannerSettings","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerSettings\/title","value":"SBSDKUIDocumentScannerSettings","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerSettings"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerSettings\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerSettings~1multiPageEnabled\/title","value":"multiPageEnabled","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerSettings~1multiPageEnabled\/fragments","value":[{"text":"multiPageEnabled","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUIDocumentScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerSettings~1autoSnappingEnabled\/title","op":"replace","value":"autoSnappingEnabled"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerSettings~1autoSnappingEnabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"autoSnappingEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerSettings~1flashEnabled\/title","value":"flashEnabled"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerSettings~1flashEnabled\/fragments","value":[{"text":"flashEnabled","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}