{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseFront"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"German driver license (Führerschein), front side","type":"text"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/birthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/birthplace","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/expiryDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/givenNames","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/id","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/issueDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/issuingAuthority","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/licenseCategories","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/photo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/serialNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/signature","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/surname"],"title":"Instance Properties"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensefront"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensefront"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKDocumentsModelDeDriverLicenseFront","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentsModelDeDriverLicenseFront","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelDeDriverLicenseFront","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentsModelDeDriverLicenseFront","kind":"identifier"}]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseFront/id":{"kind":"symbol","type":"topic","title":"id","abstract":[{"type":"text","text":"Document ID number (in the top-right corner, Field 5.)"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/id","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensefront\/id","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"id"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseFront/serialNumber":{"title":"serialNumber","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/serialNumber","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"serialNumber","kind":"identifier"}],"abstract":[{"text":"Serial number (Field 5b. on Driver Qualification Card)","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensefront\/serialnumber","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"serialNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseFront/surname":{"kind":"symbol","type":"topic","title":"surname","abstract":[{"type":"text","text":"Surname (Field 1.)"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"surname","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/surname","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensefront\/surname","role":"symbol","navigatorTitle":[{"text":"surname","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseFront/birthDate":{"title":"birthDate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/birthDate","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"birthDate","kind":"identifier"}],"abstract":[{"type":"text","text":"Birth date (Field 3.)"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensefront\/birthdate","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"birthDate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentWrapper":{"abstract":[{"type":"text","text":"Base class for strongly-typed "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","isActive":true,"type":"reference"},{"type":"text","text":" wrappers."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"title":"SBSDKGenericDocumentWrapper","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseFront/photo":{"title":"photo","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/photo","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"photo","kind":"identifier"}],"abstract":[{"type":"text","text":"Photo image"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensefront\/photo","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"photo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseFront":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseFront"}],"type":"topic","title":"SBSDKDocumentsModelDeDriverLicenseFront","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensefront","abstract":[{"type":"text","text":"German driver license (Führerschein), front side"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelDeDriverLicenseFront","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseFront/requiredDocumentType":{"kind":"symbol","title":"requiredDocumentType","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredDocumentType"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/requiredDocumentType","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensefront\/requireddocumenttype","abstract":[{"text":"The name of the wrapped document type.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"requiredDocumentType","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseFront/expiryDate":{"kind":"symbol","type":"topic","title":"expiryDate","abstract":[{"type":"text","text":"Expiry date (Field 4b.)"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"expiryDate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/expiryDate","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensefront\/expirydate","role":"symbol","navigatorTitle":[{"text":"expiryDate","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","abstract":[{"text":"Generic document.","type":"text"}],"title":"SBSDKGenericDocument","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocument"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseFront/givenNames":{"title":"givenNames","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"givenNames","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensefront\/givennames","abstract":[{"type":"text","text":"Given names (Field 2.)"}],"kind":"symbol","navigatorTitle":[{"text":"givenNames","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/givenNames"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseFront/birthplace":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/birthplace","abstract":[{"type":"text","text":"Birthplace (Field 3.)"}],"title":"birthplace","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"birthplace"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"birthplace","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensefront\/birthplace","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseFront/initWithGenericDocument:":{"kind":"symbol","type":"topic","title":"initWithGenericDocument:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/initWithGenericDocument:","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensefront\/initwithgenericdocument:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithGenericDocument:"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseFront/signature":{"title":"signature","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"signature","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensefront\/signature","abstract":[{"type":"text","text":"Signature image (Field 7.)"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"signature"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/signature"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseFront/licenseCategories":{"kind":"symbol","type":"topic","title":"licenseCategories","abstract":[{"type":"text","text":"Driver’s license categories (Field 9.)"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licenseCategories","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/licenseCategories","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensefront\/licensecategories","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"licenseCategories"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseFront/issuingAuthority":{"title":"issuingAuthority","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"issuingAuthority"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensefront\/issuingauthority","abstract":[{"text":"Issuing authority (Field 4c.)","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"issuingAuthority"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/issuingAuthority"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseFront/issueDate":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensefront\/issuedate","kind":"symbol","abstract":[{"text":"Issue date (Field 4a.)","type":"text"}],"navigatorTitle":[{"text":"issueDate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/issueDate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"issueDate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","title":"issueDate"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKDocumentsModelDeDriverLicenseFront","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseFront"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKDocumentsModelDeDriverLicenseFront","kind":"identifier"}]},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/birthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/birthplace","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/expiryDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/givenNames","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/id","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/issueDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/issuingAuthority","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/licenseCategories","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/photo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/serialNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/signature","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/surname"],"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseFront\/initWithGenericDocument:"],"title":"Instance Methods"}],"op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseFront"},{"text":" : ","kind":"text"},{"text":"SBSDKGenericDocumentWrapper","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentWrapper"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"id","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1id\/title","op":"replace"},{"value":[{"text":"id","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1id\/fragments","op":"replace"},{"value":"serialNumber","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1serialNumber\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1serialNumber\/fragments","value":[{"text":"serialNumber","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"surname","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1surname\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1surname\/fragments","value":[{"kind":"identifier","text":"surname"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1birthDate\/title","value":"birthDate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1birthDate\/fragments","value":[{"text":"birthDate","kind":"identifier"}],"op":"replace"},{"value":"SBSDKGenericDocumentWrapper","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/title"},{"value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/fragments","op":"replace"},{"value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/navigatorTitle","op":"replace"},{"value":"photo","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1photo\/title"},{"value":[{"kind":"identifier","text":"photo"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1photo\/fragments"},{"value":"SBSDKDocumentsModelDeDriverLicenseFront","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront\/title"},{"op":"replace","value":[{"text":"SBSDKDocumentsModelDeDriverLicenseFront","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront\/navigatorTitle","value":[{"text":"SBSDKDocumentsModelDeDriverLicenseFront","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1requiredDocumentType\/title","value":"requiredDocumentType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1requiredDocumentType\/fragments","value":[{"kind":"identifier","text":"requiredDocumentType"}],"op":"replace"},{"op":"replace","value":"expiryDate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1expiryDate\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1expiryDate\/fragments","value":[{"kind":"identifier","text":"expiryDate"}],"op":"replace"},{"value":"SBSDKGenericDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title"},{"value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments"},{"value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1givenNames\/title","value":"givenNames"},{"op":"replace","value":[{"text":"givenNames","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1givenNames\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1birthplace\/title","op":"replace","value":"birthplace"},{"value":[{"kind":"identifier","text":"birthplace"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1birthplace\/fragments"},{"value":"signature","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1signature\/title","op":"replace"},{"value":[{"kind":"identifier","text":"signature"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1signature\/fragments"},{"value":"licenseCategories","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1licenseCategories\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1licenseCategories\/fragments","value":[{"text":"licenseCategories","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1issuingAuthority\/title","op":"replace","value":"issuingAuthority"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1issuingAuthority\/fragments","op":"replace","value":[{"text":"issuingAuthority","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1issueDate\/title","op":"replace","value":"issueDate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseFront~1issueDate\/fragments","value":[{"text":"issueDate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}