{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2CameraModule) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"title":"Conforms To","type":"conformsTo"}],"metadata":{"navigatorTitle":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"roleHeading":"Enumeration","modules":[{"name":"ScanbotSDK"}],"symbolKind":"enum","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"role":"symbol","title":"SBSDKUI2CameraModule"},"kind":"symbol","abstract":[{"type":"text","text":"Determine which camera module to use on start-up."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2cameramodule"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2cameramodule"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule\/back","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule\/backWidest","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule\/front"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule\/RawRepresentable-Implementations"],"generated":true}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraModule/init(rawValue:)":{"url":"\/documentation\/scanbotsdk\/sbsdkui2cameramodule\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","kind":"symbol","title":"init(rawValue:)","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule\/init(rawValue:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraModule/back":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraModuleBack"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2cameramodule\/back","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"back"}],"type":"topic","role":"symbol","kind":"symbol","title":"SBSDKUI2CameraModule.back","abstract":[{"type":"text","text":"Use the default back camera."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule\/back"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraModule/backWidest":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraModuleBackWidest"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2cameramodule\/backwidest","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"backWidest","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"SBSDKUI2CameraModule.backWidest","abstract":[{"type":"text","text":"Use the back camera with the widest available angle."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule\/backWidest"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraModule":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"abstract":[{"type":"text","text":"Determine which camera module to use on start-up."}],"kind":"symbol","title":"SBSDKUI2CameraModule","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2cameramodule","navigatorTitle":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraModule/front":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraModuleFront"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2cameramodule\/front","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"front"}],"type":"topic","role":"symbol","kind":"symbol","title":"SBSDKUI2CameraModule.front","abstract":[{"type":"text","text":"Use the front camera."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule\/front"},"doc://net.doo.ScanbotSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraModule/Equatable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkui2cameramodule\/equatable-implementations","type":"topic","role":"collectionGroup","kind":"article","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule\/Equatable-Implementations"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraModule/RawRepresentable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkui2cameramodule\/rawrepresentable-implementations","type":"topic","role":"collectionGroup","kind":"article","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule\/RawRepresentable-Implementations"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"SBSDKUI2CameraModule","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraModule"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule\/back","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule\/backWidest","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule\/front"],"title":"Enumeration Cases"}]},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule~1back\/title","value":"SBSDKUI2CameraModuleBack"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule~1back\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraModuleBack"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule~1backWidest\/title","value":"SBSDKUI2CameraModuleBackWidest"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule~1backWidest\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraModuleBackWidest"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/title","value":"SBSDKUI2CameraModule"},{"op":"replace","value":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule~1front\/title","value":"SBSDKUI2CameraModuleFront","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CameraModuleFront"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule~1front\/fragments"}]}]}