{"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate\/vinScannerViewController(_:didScanValidResult:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate\/vinScannerViewControllerShouldDetect(_:)"],"title":"Instance Methods"}],"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKVINScannerViewControllerDelegate","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKVINScannerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVINScannerViewControllerDelegate"}],"roleHeading":"Protocol","title":"SBSDKVINScannerViewControllerDelegate","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVINScannerViewControllerDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontrollerdelegate"]}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewController"],"type":"conformingTypes"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The delegation protocol for "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","type":"reference","isActive":true},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerViewController":{"kind":"symbol","abstract":[{"text":"A highly customizable camera-based view controller to recognize and validate vehicle identification numbers in realtime.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIVINScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuivinscannerviewcontroller","navigatorTitle":[{"text":"SBSDKUIVINScannerViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewController","type":"topic","title":"SBSDKUIVINScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewControllerDelegate/vinScannerViewControllerShouldDetect(_:)":{"type":"topic","required":true,"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"vinScannerViewControllerShouldDetect","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKVINScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate\/vinScannerViewControllerShouldDetect(_:)","navigatorTitle":[{"text":"vinScannerViewControllerShouldDetect:","kind":"identifier"}],"title":"vinScannerViewControllerShouldDetect(_:)","abstract":[{"text":"Asks the delegate whether the next video frame should be scanned or not.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Can be used to skip frames or pause scanning for a while."}],"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontrollerdelegate\/vinscannerviewcontrollershoulddetect(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewControllerDelegate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKVINScannerViewControllerDelegate","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontrollerdelegate","navigatorTitle":[{"text":"SBSDKVINScannerViewControllerDelegate","kind":"identifier"}],"abstract":[{"text":"The delegation protocol for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController"},{"type":"text","text":"."}],"kind":"symbol","title":"SBSDKVINScannerViewControllerDelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewControllerDelegate/vinScannerViewController(_:didScanValidResult:)":{"type":"topic","required":true,"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"vinScannerViewController","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerViewController","kind":"typeIdentifier","text":"SBSDKVINScannerViewController"},{"kind":"text","text":", "},{"text":"didScanValidResult","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerResult","text":"SBSDKVehicleIdentificationNumberScannerResult"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate\/vinScannerViewController(_:didScanValidResult:)","navigatorTitle":[{"kind":"identifier","text":"vinScannerViewController:didScanValidResult:"}],"title":"vinScannerViewController(_:didScanValidResult:)","abstract":[{"type":"text","text":"Informs the delegate that a vehicle identification number has been scanned and validated, and passes the result."}],"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontrollerdelegate\/vinscannerviewcontroller(_:didscanvalidresult:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller","title":"SBSDKVINScannerViewController","role":"symbol","navigatorTitle":[{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show a camera screen with the vehicle identification number scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKVINScannerViewControllerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"SBSDKVINScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVINScannerViewControllerDelegate"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate\/vinScannerViewController(_:didScanValidResult:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate\/vinScannerViewControllerShouldDetect(_:)"]}],"op":"replace"},{"value":[{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerViewController"],"type":"conformingTypes"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKVINScannerViewControllerDelegate"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewController\/title","value":"SBSDKUIVINScannerViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerViewController\/fragments","value":[{"text":"SBSDKUIVINScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate~1vinScannerViewControllerShouldDetect(_:)\/title","value":"vinScannerViewControllerShouldDetect:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"vinScannerViewControllerShouldDetect:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate~1vinScannerViewControllerShouldDetect(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate\/title","value":"SBSDKVINScannerViewControllerDelegate"},{"value":[{"kind":"identifier","text":"SBSDKVINScannerViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate\/fragments"},{"value":"vinScannerViewController:didScanValidResult:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate~1vinScannerViewController(_:didScanValidResult:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"vinScannerViewController:didScanValidResult:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate~1vinScannerViewController(_:didScanValidResult:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/title","op":"replace","value":"SBSDKVINScannerViewController"},{"value":[{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/fragments","op":"replace"}]}]}