{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Helper class, that gathers the image, camera and detection metadata of a document scan."}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/detectionResult","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/imageMetadata","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/lensCameraProperties","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/pageImageSource"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"metadata":{"title":"SBSDKCaptureInfo","navigatorTitle":[{"text":"SBSDKCaptureInfo","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCaptureInfo","roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCaptureInfo"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCaptureInfo","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcaptureinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcaptureinfo"]}],"references":{"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCaptureInfo/imageMetadata":{"navigatorTitle":[{"text":"imageMetadata","kind":"identifier"}],"abstract":[{"text":"The image metadata of the captured image.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcaptureinfo\/imagemetadata","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/imageMetadata","title":"imageMetadata","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageMetadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageMetadata","text":"SBSDKImageMetadata"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCaptureInfo":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo","kind":"symbol","abstract":[{"type":"text","text":"Helper class, that gathers the image, camera and detection metadata of a document scan."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCaptureInfo"}],"navigatorTitle":[{"text":"SBSDKCaptureInfo","kind":"identifier"}],"title":"SBSDKCaptureInfo","url":"\/documentation\/scanbotsdk\/sbsdkcaptureinfo"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCaptureInfo/pageImageSource":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/pageImageSource","type":"topic","abstract":[{"text":"The source the image was received from.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"pageImageSource","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageImageSource","text":"SBSDKPageImageSource","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"pageImageSource"}],"title":"pageImageSource","url":"\/documentation\/scanbotsdk\/sbsdkcaptureinfo\/pageimagesource"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCaptureInfo/lensCameraProperties":{"navigatorTitle":[{"text":"lensCameraProperties","kind":"identifier"}],"abstract":[{"type":"text","text":"The lens and camera properties of the camera system the image was captured with."}],"url":"\/documentation\/scanbotsdk\/sbsdkcaptureinfo\/lenscameraproperties","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/lensCameraProperties","title":"lensCameraProperties","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"lensCameraProperties","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKLensCameraProperties","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLensCameraProperties"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCaptureInfo/init":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcaptureinfo\/init","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/init","title":"init"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCaptureInfo/detectionResult":{"type":"topic","abstract":[{"type":"text","text":"The document detector result of the captured image."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectionResult"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/detectionResult","url":"\/documentation\/scanbotsdk\/sbsdkcaptureinfo\/detectionresult","title":"detectionResult","role":"symbol","navigatorTitle":[{"text":"detectionResult","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKCaptureInfo","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKCaptureInfo","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKCaptureInfo","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/detectionResult","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/imageMetadata","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/lensCameraProperties","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/pageImageSource"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/init"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCaptureInfo"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo~1imageMetadata\/title","value":"imageMetadata","op":"replace"},{"value":[{"kind":"identifier","text":"imageMetadata"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo~1imageMetadata\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo\/title","value":"SBSDKCaptureInfo","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo\/fragments","value":[{"text":"SBSDKCaptureInfo","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo~1pageImageSource\/title","value":"pageImageSource"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo~1pageImageSource\/fragments","value":[{"text":"pageImageSource","kind":"identifier"}],"op":"replace"},{"value":"lensCameraProperties","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo~1lensCameraProperties\/title","op":"replace"},{"value":[{"kind":"identifier","text":"lensCameraProperties"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo~1lensCameraProperties\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo~1detectionResult\/title","op":"replace","value":"detectionResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo~1detectionResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"detectionResult"}]}]}]}