{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState","interfaceLanguage":"swift"},"abstract":[{"text":"The live recognition state of the check scanner.","type":"text"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/capturing","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/energySaving","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/paused","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/recognizing","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/searching"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"]}],"kind":"symbol","metadata":{"symbolKind":"enum","roleHeading":"Enumeration","title":"SBSDKCheckRecognizerState","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckRecognizerState"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKCheckRecognizerState","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKCheckRecognizerState"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKCheckRecognizerState","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerState/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate\/init(rawvalue:)","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/init(rawValue:)","abstract":[],"title":"init(rawValue:)"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerState/energySaving":{"kind":"symbol","title":"SBSDKCheckRecognizerState.energySaving","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"energySaving","kind":"identifier"}],"abstract":[{"type":"text","text":"The check scanner is in energy saving mode."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKCheckRecognizerStateEnergySaving","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate\/energysaving","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/energySaving"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerState/RawRepresentable-Implementations":{"role":"collectionGroup","type":"topic","kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/RawRepresentable-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate\/rawrepresentable-implementations","title":"RawRepresentable Implementations","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerState/searching":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/searching","title":"SBSDKCheckRecognizerState.searching","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"searching","kind":"identifier"}],"abstract":[{"text":"The check scanner is searching for a check.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKCheckRecognizerStateSearching","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate\/searching","kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerState/paused":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/paused","title":"SBSDKCheckRecognizerState.paused","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paused","kind":"identifier"}],"abstract":[{"text":"The check scanner paused the detection and recognition.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerStatePaused"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate\/paused","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerState/capturing":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate\/capturing","kind":"symbol","abstract":[{"text":"The check scanner is capturing a high-res photo of a check.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"capturing"}],"type":"topic","title":"SBSDKCheckRecognizerState.capturing","navigatorTitle":[{"text":"SBSDKCheckRecognizerStateCapturing","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/capturing","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerState/recognizing":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recognizing"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate\/recognizing","type":"topic","role":"symbol","title":"SBSDKCheckRecognizerState.recognizing","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/recognizing","abstract":[{"type":"text","text":"The check scanner is recognizing a check."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerStateRecognizing"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerState":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKCheckRecognizerState","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate","type":"topic","role":"symbol","title":"SBSDKCheckRecognizerState","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState","abstract":[{"type":"text","text":"The live recognition state of the check scanner."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerState"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerState/Equatable-Implementations":{"kind":"article","title":"Equatable Implementations","abstract":[],"type":"topic","role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerstate\/equatable-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/Equatable-Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKCheckRecognizerState","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckRecognizerState"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKCheckRecognizerState","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/capturing","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/energySaving","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/paused","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/recognizing","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerState\/searching"],"title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCheckRecognizerState","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState~1energySaving\/title","op":"replace","value":"SBSDKCheckRecognizerStateEnergySaving"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState~1energySaving\/fragments","value":[{"text":"SBSDKCheckRecognizerStateEnergySaving","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState~1searching\/title","value":"SBSDKCheckRecognizerStateSearching","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState~1searching\/fragments","value":[{"text":"SBSDKCheckRecognizerStateSearching","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState~1paused\/title","value":"SBSDKCheckRecognizerStatePaused","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState~1paused\/fragments","value":[{"text":"SBSDKCheckRecognizerStatePaused","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState~1capturing\/title","value":"SBSDKCheckRecognizerStateCapturing","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState~1capturing\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckRecognizerStateCapturing"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState~1recognizing\/title","op":"replace","value":"SBSDKCheckRecognizerStateRecognizing"},{"value":[{"kind":"identifier","text":"SBSDKCheckRecognizerStateRecognizing"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState~1recognizing\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState\/title","value":"SBSDKCheckRecognizerState","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerState\/fragments","value":[{"text":"SBSDKCheckRecognizerState","kind":"identifier"}],"op":"replace"}]}]}