{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(SBSDKUI2SheetContent) "},{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Configuration of the list containing the barcodes that have already been scanned."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2sheetcontent"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2sheetcontent"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/init(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/init(sheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/barcodeItemImageVisible","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/barcodeItemSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/barcodeItemTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/clearAllButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/dividerColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/manualCountChangeColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/manualCountChangeEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/manualCountOutlineColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/placeholderIcon","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/placeholderIconBackground","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/placeholderSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/placeholderTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/sheetColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/startScanningButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/submitButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/swipeToDelete","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/title"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/toJson()"],"title":"Instance Methods"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent","roleHeading":"Class","title":"SBSDKUI2SheetContent","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2SheetContent","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"symbolKind":"class","role":"symbol"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/startScanningButton":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/startScanningButton","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startScanningButton"}],"title":"startScanningButton","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"startScanningButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/startscanningbutton","role":"symbol","abstract":[{"text":"Configuration of the button to start scanning displayed in an empty barcode list.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/barcodeItemImageVisible":{"abstract":[{"text":"Visibility of the barcode image in a barcode list entry.","type":"text"},{"type":"text","text":" "},{"text":"Default is true","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/barcodeItemImageVisible","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/barcodeitemimagevisible","title":"barcodeItemImageVisible","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeItemImageVisible"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"barcodeItemImageVisible","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/init(sheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:)":{"navigatorTitle":[{"text":"initWithSheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/init(sheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:)","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/init(sheetcolor:dividercolor:manualcountchangeenabled:manualcountoutlinecolor:manualcountchangecolor:title:clearallbutton:barcodeitemtitle:barcodeitemsubtitle:barcodeitemimagevisible:submitbutton:startscanningbutton:placeholdertitle:placeho-8iyg5","title":"init(sheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:)","abstract":[],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"sheetColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"dividerColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"manualCountChangeEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"manualCountOutlineColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"manualCountChangeColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"kind":"text","text":", "},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clearAllButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":", "},{"text":"barcodeItemTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcodeItemSubtitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":", "},{"text":"barcodeItemImageVisible","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"submitButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"startScanningButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"text":", ","kind":"text"},{"text":"placeholderTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderSubtitle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderIconBackground"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderIcon"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconStyle","text":"SBSDKUI2IconStyle","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"swipeToDelete"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SwipeToDelete","text":"SBSDKUI2SwipeToDelete","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/title":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"title","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"title"}],"abstract":[{"text":"Configuration of the barcode list’s title. By default displays the total number of scanned barcodes.","type":"text"}],"title":"title","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/title","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/title"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/placeholderIconBackground":{"abstract":[{"text":"Background color of the icon displayed in an empty barcode list.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is “?sbColorOutline”"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/placeholdericonbackground","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholderIconBackground","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"}],"type":"topic","title":"placeholderIconBackground","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/placeholderIconBackground","navigatorTitle":[{"kind":"identifier","text":"placeholderIconBackground"}]},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/manualCountChangeColor":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/manualCountChangeColor","type":"topic","title":"manualCountChangeColor","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/manualcountchangecolor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"manualCountChangeColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Color of the buttons for manually changing the barcode count."},{"text":" ","type":"text"},{"text":"Default is “?sbColorPrimary”","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"manualCountChangeColor"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/init()":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"title":"init()","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/init()","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/init()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/toJson()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"() -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/toJson()","role":"symbol","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"type":"topic","title":"toJson()","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/tojson()","navigatorTitle":[{"text":"toJson","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/isEqual:":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/isequal:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"type":"topic","role":"symbol","kind":"symbol","title":"isEqual:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/isEqual:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/barcodeItemSubtitle":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"barcodeItemSubtitle","kind":"identifier"}],"title":"barcodeItemSubtitle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeItemSubtitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"}],"role":"symbol","abstract":[{"type":"text","text":"Configuration of the subtitle of a barcode list entry (displaying the barcode’s symbology)."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/barcodeItemSubtitle","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/barcodeitemsubtitle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/dividerColor":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/dividerColor","title":"dividerColor","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/dividercolor","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The color of the dividers in the list sheet."},{"type":"text","text":" "},{"type":"text","text":"Default is “?sbColorOutline”"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dividerColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"}],"navigatorTitle":[{"kind":"identifier","text":"dividerColor"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/placeholderTitle":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/placeholderTitle","type":"topic","navigatorTitle":[{"kind":"identifier","text":"placeholderTitle"}],"title":"placeholderTitle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholderTitle","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/placeholdertitle","role":"symbol","abstract":[{"text":"Configuration of the title displayed in an empty barcode list.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/submitButton":{"abstract":[{"text":"Configuration of the barcode list’s submit button.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/submitbutton","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"submitButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"}],"type":"topic","title":"submitButton","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/submitButton","navigatorTitle":[{"text":"submitButton","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/hash":{"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/hash","title":"hash","role":"symbol","fragments":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/placeholderIcon":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/placeholderIcon","abstract":[{"text":"Configuration of the icon displayed in an empty barcode list.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"placeholderIcon","kind":"identifier"}],"title":"placeholderIcon","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"placeholderIcon","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconStyle","kind":"typeIdentifier","text":"SBSDKUI2IconStyle"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/placeholdericon"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/placeholderSubtitle":{"url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/placeholdersubtitle","abstract":[{"type":"text","text":"Configuration of the subtitle displayed in an empty barcode list."}],"role":"symbol","title":"placeholderSubtitle","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/placeholderSubtitle","navigatorTitle":[{"text":"placeholderSubtitle","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"placeholderSubtitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/swipeToDelete":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/swipeToDelete","type":"topic","navigatorTitle":[{"kind":"identifier","text":"swipeToDelete"}],"title":"swipeToDelete","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"swipeToDelete","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2SwipeToDelete","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SwipeToDelete"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/swipetodelete","role":"symbol","abstract":[{"text":"The style of the swipe-to-delete button.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"url":"\/documentation\/scanbotsdk\/sbsdkui2node","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Node","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Node","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","title":"SBSDKUI2Node","type":"topic","abstract":[{"type":"text","text":"Abstract class for all the configurations."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/manualCountOutlineColor":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/manualCountOutlineColor","abstract":[{"text":"The color of the outline of the manual counting buttons in the list sheet.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is “?sbColorOutline”"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/manualcountoutlinecolor","navigatorTitle":[{"text":"manualCountOutlineColor","kind":"identifier"}],"title":"manualCountOutlineColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"manualCountOutlineColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/init(from:)":{"url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"type":"topic","role":"symbol","kind":"symbol","title":"init(from:)","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/init(from:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/clearAllButton":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearAllButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration"}],"abstract":[{"text":"Configuration of the button for clearing the barcode list.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearAllButton"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/clearAllButton","title":"clearAllButton","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/clearallbutton","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/sheetColor":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/sheetColor","type":"topic","title":"sheetColor","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/sheetcolor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"sheetColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"}],"abstract":[{"text":"Color of the list’s background.","type":"text"},{"type":"text","text":" "},{"text":"Default is “?sbColorSurface”","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"sheetColor"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"title":"SBSDKUI2SheetContent","role":"symbol","abstract":[{"text":"Configuration of the list containing the barcodes that have already been scanned.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/barcodeItemTitle":{"navigatorTitle":[{"text":"barcodeItemTitle","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/barcodeitemtitle","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"barcodeItemTitle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"}],"type":"topic","role":"symbol","kind":"symbol","title":"barcodeItemTitle","abstract":[{"type":"text","text":"Configuration of the title of a barcode list entry (displaying the barcode’s value)."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/barcodeItemTitle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/manualCountChangeEnabled":{"navigatorTitle":[{"kind":"identifier","text":"manualCountChangeEnabled"}],"title":"manualCountChangeEnabled","abstract":[{"type":"text","text":"Enables the user to change the number of scanned items by pressing +,-, or changing the number using a keyboard."},{"text":" ","type":"text"},{"text":"Default is true","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"manualCountChangeEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/manualCountChangeEnabled","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/manualcountchangeenabled"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKUI2SheetContent","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2SheetContent","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/barcodeItemImageVisible","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/barcodeItemSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/barcodeItemTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/clearAllButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/dividerColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/manualCountChangeColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/manualCountChangeEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/manualCountOutlineColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/placeholderIcon","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/placeholderIconBackground","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/placeholderSubtitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/placeholderTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/sheetColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/startScanningButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/submitButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/swipeToDelete","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/title"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/init(sheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/toJson()"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2SheetContent"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node","text":"SBSDKUI2Node","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1startScanningButton\/title","value":"startScanningButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1startScanningButton\/fragments","value":[{"text":"startScanningButton","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"barcodeItemImageVisible","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1barcodeItemImageVisible\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1barcodeItemImageVisible\/fragments","value":[{"text":"barcodeItemImageVisible","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1init(sheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:)\/title","op":"replace","value":"initWithSheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1init(sheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:)\/fragments"},{"value":"title","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1title\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1title\/fragments","value":[{"kind":"identifier","text":"title"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1placeholderIconBackground\/title","op":"replace","value":"placeholderIconBackground"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1placeholderIconBackground\/fragments","op":"replace","value":[{"kind":"identifier","text":"placeholderIconBackground"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1manualCountChangeColor\/title","value":"manualCountChangeColor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1manualCountChangeColor\/fragments","value":[{"text":"manualCountChangeColor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1init()\/title","value":"init"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1init()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1toJson()\/title","value":"toJson"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1toJson()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toJson","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1barcodeItemSubtitle\/title","value":"barcodeItemSubtitle"},{"op":"replace","value":[{"kind":"identifier","text":"barcodeItemSubtitle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1barcodeItemSubtitle\/fragments"},{"op":"replace","value":"dividerColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1dividerColor\/title"},{"op":"replace","value":[{"text":"dividerColor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1dividerColor\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1placeholderTitle\/title","value":"placeholderTitle","op":"replace"},{"value":[{"text":"placeholderTitle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1placeholderTitle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1submitButton\/title","value":"submitButton"},{"op":"replace","value":[{"kind":"identifier","text":"submitButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1submitButton\/fragments"},{"value":"placeholderIcon","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1placeholderIcon\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1placeholderIcon\/fragments","value":[{"kind":"identifier","text":"placeholderIcon"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1placeholderSubtitle\/title","value":"placeholderSubtitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1placeholderSubtitle\/fragments","value":[{"text":"placeholderSubtitle","kind":"identifier"}]},{"op":"replace","value":"swipeToDelete","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1swipeToDelete\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1swipeToDelete\/fragments","value":[{"text":"swipeToDelete","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title","op":"replace","value":"SBSDKUI2Node"},{"value":[{"kind":"identifier","text":"SBSDKUI2Node"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1manualCountOutlineColor\/title","value":"manualCountOutlineColor","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1manualCountOutlineColor\/fragments","op":"replace","value":[{"text":"manualCountOutlineColor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1clearAllButton\/title","value":"clearAllButton"},{"value":[{"text":"clearAllButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1clearAllButton\/fragments","op":"replace"},{"value":"sheetColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1sheetColor\/title","op":"replace"},{"op":"replace","value":[{"text":"sheetColor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1sheetColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent\/title","value":"SBSDKUI2SheetContent"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1barcodeItemTitle\/title","value":"barcodeItemTitle","op":"replace"},{"value":[{"kind":"identifier","text":"barcodeItemTitle"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1barcodeItemTitle\/fragments"},{"value":"manualCountChangeEnabled","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1manualCountChangeEnabled\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1manualCountChangeEnabled\/fragments","value":[{"kind":"identifier","text":"manualCountChangeEnabled"}],"op":"replace"}]}]}