{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller"]}],"metadata":{"roleHeading":"Class","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"symbolKind":"class","title":"SBSDKBarcodeScannerViewController"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/init(parentViewController:parentView:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/init(parentViewController:parentView:delegate:)"],"title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/acceptedBarcodeTypes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/acceptedDocumentTypes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/additionalDetectionParameters","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/barcodeImageGenerationType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/delegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/engineMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/extensionFilter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/isTrackingOverlayEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/regularExpressionPattern","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/trackingOverlayController"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/resetAccumulation()"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewDelegate","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/s8SendableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring","doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring"]}],"abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode detector."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewControllerDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScannerViewControllerDelegate"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate","navigatorTitle":[{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The delegate protocol of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","type":"reference","isActive":true},{"text":" that provides methods for","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"enabling\/disabling detection and managing detected barcodes."}],"title":"SBSDKBarcodeScannerViewControllerDelegate","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontrollerdelegate"},"doc://net.doo.ScanbotSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSessionDelegate":{"title":"SBSDKCameraSessionDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSessionDelegate"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionDelegate","type":"topic","abstract":[{"type":"text","text":"The  delegate protocol for "},{"type":"codeVoice","code":"SBSDKCameraSession"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasessiondelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCameraSessionDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/acceptedBarcodeTypes":{"abstract":[{"type":"text","text":"Machine code types (EAN, DataMatrix, Aztec, QR, etc) that can be returned in "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate\/barcodeScannerController(_:didDetectBarcodes:)","isActive":true,"type":"reference"},{"type":"text","text":" delegate method."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/acceptedbarcodetypes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"acceptedBarcodeTypes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKBarcodeType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeType"},{"kind":"text","text":"]"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"acceptedBarcodeTypes"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/acceptedBarcodeTypes","title":"acceptedBarcodeTypes"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/viewDidAppear:":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/viewdidappear:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/viewDidAppear:","kind":"symbol","title":"viewDidAppear:","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidAppear:"}]},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/isTrackingOverlayEnabled":{"abstract":[{"type":"text","text":"Displays an augmented reality view that draws the frames, content and type text of the found barcodes when it finds them."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/istrackingoverlayenabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isTrackingOverlayEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"isTrackingOverlayEnabled","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/isTrackingOverlayEnabled","title":"isTrackingOverlayEnabled"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s8SendableP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/init()":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/init()","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"abstract":[{"text":"Initializes an instance of this class with the default configuration.","type":"text"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","title":"init()","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/init()"},"doc://net.doo.ScanbotSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/delegate":{"abstract":[{"type":"text","text":"The weak delegate. See "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate","isActive":true,"type":"reference"},{"text":" protocol.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKBarcodeScannerViewControllerDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/delegate","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/delegate","type":"topic","kind":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"title":"delegate"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/additionalDetectionParameters":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"additionalDetectionParameters","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeAdditionalParameters","kind":"typeIdentifier","text":"SBSDKBarcodeAdditionalParameters"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/additionalDetectionParameters","navigatorTitle":[{"kind":"identifier","text":"additionalDetectionParameters"}],"role":"symbol","kind":"symbol","type":"topic","title":"additionalDetectionParameters","abstract":[{"type":"text","text":"Additional parameters for tweaking the detection of barcodes."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/additionaldetectionparameters"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/isRecognitionEnabled":{"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/isrecognitionenabled","fragments":[{"text":"isRecognitionEnabled","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/isRecognitionEnabled","title":"isRecognitionEnabled"},"doc://net.doo.ScanbotSDK/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/barcodeImageGenerationType":{"abstract":[{"text":"Specifies the way of barcode images generation or disables this generation at all.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/barcodeimagegenerationtype","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeImageGenerationType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKBarcodeImageGenerationType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodeImageGenerationType"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"barcodeImageGenerationType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/barcodeImageGenerationType","title":"barcodeImageGenerationType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSessionObserving":{"abstract":[{"type":"text","text":"A multicast-oberserver protocol that informs its oberservers about state changes of a camera session."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCameraSessionObserving","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSessionObserving"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasessionobserving","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving","title":"SBSDKCameraSessionObserving","role":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewController":{"title":"SBSDKBaseScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"abstract":[{"type":"text","text":"A highly customizable camera view controller that delivers a basic camera functionality along with video"},{"type":"text","text":" "},{"type":"text","text":"frame extraction and preprocessing, orientation correction and still image capturing."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/init(parentViewController:parentView:delegate:)":{"abstract":[{"text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area.","type":"text"}],"navigatorTitle":[{"text":"initWithParentViewController:parentView:delegate:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/init(parentViewController:parentView:delegate:)","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/init(parentviewcontroller:parentview:delegate:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"parentViewController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":", "},{"text":"parentView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKBarcodeScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKBarcodeScannerViewControllerDelegate"},{"kind":"text","text":"?)"}],"type":"topic","title":"init(parentViewController:parentView:delegate:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView":{"navigatorTitle":[{"text":"SBSDKFinderView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","url":"\/documentation\/scanbotsdk\/sbsdkfinderview","abstract":[{"type":"text","text":"A "},{"code":"UIView","type":"codeVoice"},{"type":"text","text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio."}],"title":"SBSDKFinderView","role":"symbol","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/viewDidLoad":{"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/viewdidload","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}],"kind":"symbol","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/viewDidLoad","title":"viewDidLoad"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/viewDidDisappear:":{"abstract":[],"role":"symbol","title":"viewDidDisappear:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/viewDidDisappear:","fragments":[{"text":"- ","kind":"text"},{"text":"viewDidDisappear:","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/viewdiddisappear:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewControllerDelegate/barcodeScannerController(_:didDetectBarcodes:)":{"abstract":[{"text":"Informs the delegate that the receiver has detected some barcodes.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontrollerdelegate\/barcodescannercontroller(_:diddetectbarcodes:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"barcodeScannerController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController","text":"SBSDKBarcodeScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didDetectBarcodes","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult","kind":"typeIdentifier","text":"SBSDKBarcodeScannerResult"},{"text":"])","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"barcodeScannerController:didDetectBarcodes:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate\/barcodeScannerController(_:didDetectBarcodes:)","required":true,"title":"barcodeScannerController(_:didDetectBarcodes:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderViewDelegate":{"url":"\/documentation\/scanbotsdk\/sbsdkfinderviewdelegate","title":"SBSDKFinderViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKFinderViewDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewDelegate","navigatorTitle":[{"text":"SBSDKFinderViewDelegate","kind":"identifier"}],"abstract":[{"text":"The delegate protocol for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","type":"reference","isActive":true},{"type":"text","text":" class."}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/trackingOverlayController":{"abstract":[{"text":"The barcode tracking overlay controller that shows the detected barcodes.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/trackingoverlaycontroller","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackingOverlayController","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController"},{"text":"!","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"trackingOverlayController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/trackingOverlayController","title":"trackingOverlayController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/resetAccumulation()":{"abstract":[{"type":"text","text":"Resets the barcode results accumulator that is used for smoother results."},{"type":"text","text":" "},{"text":"It is recommended to explicitly reset it, when there is the intention to scan for another barcode.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/resetaccumulation()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resetAccumulation"},{"text":"()","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"resetAccumulation","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/resetAccumulation()","title":"resetAccumulation()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller","title":"SBSDKBarcodeScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show a camera screen with the barcode detector."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/viewWillDisappear:":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/viewwilldisappear:","title":"viewWillDisappear:","fragments":[{"kind":"text","text":"- "},{"text":"viewWillDisappear:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/viewWillDisappear:","role":"symbol","navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/regularExpressionPattern":{"abstract":[{"type":"text","text":"Regular expression pattern to limit detection results."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/regularexpressionpattern","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"regularExpressionPattern","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"regularExpressionPattern","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/regularExpressionPattern","title":"regularExpressionPattern"},"doc://net.doo.ScanbotSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/engineMode":{"title":"engineMode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"engineMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeEngineMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodeEngineMode"}],"navigatorTitle":[{"kind":"identifier","text":"engineMode"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/engineMode","abstract":[{"type":"text","text":"The barcode detectors engine mode."}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/enginemode"},"doc://net.doo.ScanbotSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/init(parentViewController:parentView:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"parentViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"parentView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/init(parentViewController:parentView:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/init(parentviewcontroller:parentview:)","navigatorTitle":[{"text":"initWithParentViewController:parentView:","kind":"identifier"}],"title":"init(parentViewController:parentView:)","role":"symbol","kind":"symbol","abstract":[{"text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/extensionFilter":{"abstract":[{"type":"text","text":"Filter for extended EAN and UPC barcodes."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/extensionfilter","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extensionFilter","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodesExtensionFilter","kind":"typeIdentifier","text":"SBSDKBarcodesExtensionFilter"}],"kind":"symbol","navigatorTitle":[{"text":"extensionFilter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/extensionFilter","title":"extensionFilter"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/acceptedDocumentTypes":{"abstract":[{"text":"Barcode document types to limit detection results to.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/accepteddocumenttypes","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"acceptedDocumentTypes","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentRootType","text":"SBSDKBarcodeDocumentRootType","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"acceptedDocumentTypes","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/acceptedDocumentTypes","title":"acceptedDocumentTypes"},"doc://net.doo.ScanbotSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodeScannerViewController"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/acceptedBarcodeTypes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/acceptedDocumentTypes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/additionalDetectionParameters","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/barcodeImageGenerationType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/delegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/engineMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/extensionFilter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/isRecognitionEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/isTrackingOverlayEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/regularExpressionPattern","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/trackingOverlayController"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/init(parentViewController:parentView:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/init(parentViewController:parentView:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/resetAccumulation()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/viewDidAppear:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/viewDidDisappear:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/viewDidLoad","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/viewWillDisappear:"],"title":"Instance Methods"}]},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController","text":"SBSDKBaseScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerViewController","kind":"typeIdentifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate\/title","op":"replace","value":"SBSDKBarcodeScannerViewControllerDelegate"},{"value":[{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate\/fragments","op":"replace"},{"value":"SBSDKCameraSessionDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionDelegate\/title"},{"value":[{"kind":"identifier","text":"SBSDKCameraSessionDelegate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionDelegate\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1acceptedBarcodeTypes\/title","value":"acceptedBarcodeTypes","op":"replace"},{"value":[{"kind":"identifier","text":"acceptedBarcodeTypes"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1acceptedBarcodeTypes\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1isTrackingOverlayEnabled\/title","value":"isTrackingOverlayEnabled"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1isTrackingOverlayEnabled\/fragments","value":[{"kind":"identifier","text":"isTrackingOverlayEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1init()\/title","value":"init"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1init()\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1delegate\/title","value":"delegate","op":"replace"},{"op":"replace","value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1delegate\/fragments"},{"op":"replace","value":"additionalDetectionParameters","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1additionalDetectionParameters\/title"},{"op":"replace","value":[{"text":"additionalDetectionParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1additionalDetectionParameters\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1barcodeImageGenerationType\/title","value":"barcodeImageGenerationType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1barcodeImageGenerationType\/fragments","value":[{"kind":"identifier","text":"barcodeImageGenerationType"}]},{"op":"replace","value":"SBSDKCameraSessionObserving","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraSessionObserving"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/title","value":"SBSDKBaseScannerViewController","op":"replace"},{"value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/fragments","op":"replace"},{"op":"replace","value":"initWithParentViewController:parentView:delegate:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1init(parentViewController:parentView:delegate:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParentViewController:parentView:delegate:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1init(parentViewController:parentView:delegate:)\/fragments"},{"value":"SBSDKFinderView","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/fragments","value":[{"text":"SBSDKFinderView","kind":"identifier"}]},{"op":"replace","value":"barcodeScannerController:didDetectBarcodes:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate~1barcodeScannerController(_:didDetectBarcodes:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodeScannerController:didDetectBarcodes:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate~1barcodeScannerController(_:didDetectBarcodes:)\/fragments","op":"replace"},{"op":"replace","value":"SBSDKFinderViewDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1trackingOverlayController\/title","value":"trackingOverlayController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1trackingOverlayController\/fragments","op":"replace","value":[{"text":"trackingOverlayController","kind":"identifier"}]},{"value":"resetAccumulation","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1resetAccumulation()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1resetAccumulation()\/fragments","value":[{"kind":"text","text":"- "},{"text":"resetAccumulation","kind":"identifier"}]},{"value":"SBSDKBarcodeScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1regularExpressionPattern\/title","value":"regularExpressionPattern"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1regularExpressionPattern\/fragments","op":"replace","value":[{"kind":"identifier","text":"regularExpressionPattern"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1engineMode\/title","value":"engineMode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1engineMode\/fragments","value":[{"kind":"identifier","text":"engineMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1init(parentViewController:parentView:)\/title","op":"replace","value":"initWithParentViewController:parentView:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1init(parentViewController:parentView:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithParentViewController:parentView:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1extensionFilter\/title","value":"extensionFilter","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1extensionFilter\/fragments","value":[{"kind":"identifier","text":"extensionFilter"}]},{"value":"acceptedDocumentTypes","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1acceptedDocumentTypes\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1acceptedDocumentTypes\/fragments","value":[{"kind":"identifier","text":"acceptedDocumentTypes"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}