{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontrollerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontrollerdelegate"]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewControllerDelegate","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Protocol","title":"SBSDKGenericDocumentRecognizerViewControllerDelegate","symbolKind":"protocol","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKGenericDocumentRecognizerViewControllerDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerViewControllerDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerViewControllerDelegate"}]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewControllerDelegate\/documentRecognizerViewController(_:didRecognize:on:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewControllerDelegate\/genericDocumentRecognizerViewControllerShouldRecognize(_:)"],"title":"Instance Methods"}],"abstract":[{"type":"text","text":"The delegate protocol for the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController"],"type":"conformingTypes","kind":"relationships","title":"Conforming Types"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerViewControllerDelegate/genericDocumentRecognizerViewControllerShouldRecognize(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontrollerdelegate\/genericdocumentrecognizerviewcontrollershouldrecognize(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"genericDocumentRecognizerViewControllerShouldRecognize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerViewController","text":"SBSDKGenericDocumentRecognizerViewController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"genericDocumentRecognizerViewControllerShouldRecognize(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewControllerDelegate\/genericDocumentRecognizerViewControllerShouldRecognize(_:)","role":"symbol","abstract":[{"type":"text","text":"Asks the delegate if the generic document recognizer should scan the next video frame."}],"navigatorTitle":[{"text":"genericDocumentRecognizerViewControllerShouldRecognize:","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerViewController":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController","title":"SBSDKGenericDocumentRecognizerViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentRecognizerViewController","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontroller","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognizerViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to recognize documents, e.g. German passports, ID cards and driver’s licenses on video frames."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerViewControllerDelegate":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewControllerDelegate","title":"SBSDKGenericDocumentRecognizerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontrollerdelegate","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The delegate protocol for the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController"},{"type":"text","text":"."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to recognize generic documents."}],"title":"SBSDKUIGenericDocumentRecognizerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerViewControllerDelegate/documentRecognizerViewController(_:didRecognize:on:)":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontrollerdelegate\/documentrecognizerviewcontroller(_:didrecognize:on:)","type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentRecognizerViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerViewController"},{"kind":"text","text":", "},{"text":"didRecognize","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentRecognitionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognitionResult"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"documentRecognizerViewController(_:didRecognize:on:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewControllerDelegate\/documentRecognizerViewController(_:didRecognize:on:)","role":"symbol","abstract":[{"type":"text","text":"Informs the delegate that a document has been recognized successfully."}],"navigatorTitle":[{"text":"documentRecognizerViewController:didRecognizeResult:onImage:","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKGenericDocumentRecognizerViewControllerDelegate"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerViewControllerDelegate"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerViewControllerDelegate"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewControllerDelegate\/documentRecognizerViewController(_:didRecognize:on:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewControllerDelegate\/genericDocumentRecognizerViewControllerShouldRecognize(_:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController"],"type":"conformingTypes","kind":"relationships","title":"Conforming Types"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"genericDocumentRecognizerViewControllerShouldRecognize:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewControllerDelegate~1genericDocumentRecognizerViewControllerShouldRecognize(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"genericDocumentRecognizerViewControllerShouldRecognize:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewControllerDelegate~1genericDocumentRecognizerViewControllerShouldRecognize(_:)\/fragments"},{"op":"replace","value":"SBSDKGenericDocumentRecognizerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController\/fragments","value":[{"text":"SBSDKGenericDocumentRecognizerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewControllerDelegate\/title","op":"replace","value":"SBSDKGenericDocumentRecognizerViewControllerDelegate"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewControllerDelegate\/fragments"},{"value":"SBSDKUIGenericDocumentRecognizerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/fragments"},{"value":"documentRecognizerViewController:didRecognizeResult:onImage:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewControllerDelegate~1documentRecognizerViewController(_:didRecognize:on:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewControllerDelegate~1documentRecognizerViewController(_:didRecognize:on:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentRecognizerViewController:didRecognizeResult:onImage:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}