{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A view finder like rectangle shows the area where the license plate is recognized."},{"type":"text","text":" "},{"type":"text","text":"Once a license plate has been recognized within the view finder area, the result is delivered to the receivers delegate."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/s8SendableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan vehicle license plates in realtime."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}],"title":"SBSDKUILicensePlateScannerViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerViewController","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/delegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/isRecognitionEnabled"]},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/create(configuration:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/present(on:configuration:delegate:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/SBSDKLicensePlateScannerViewControllerDelegate-Implementations"],"generated":true}],"references":{"doc://net.doo.ScanbotSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://net.doo.ScanbotSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/viewDidLoad":{"role":"symbol","title":"viewDidLoad","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/viewDidLoad","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/viewdidload"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/containerForEnableCameraView":{"role":"symbol","title":"containerForEnableCameraView","fragments":[{"kind":"identifier","text":"containerForEnableCameraView"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/containerForEnableCameraView","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/containerforenablecameraview"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/supportedInterfaceOrientations":{"role":"symbol","title":"supportedInterfaceOrientations","fragments":[{"kind":"identifier","text":"supportedInterfaceOrientations"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/supportedInterfaceOrientations","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/supportedinterfaceorientations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController":{"role":"symbol","title":"SBSDKUILicensePlateScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}],"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan vehicle license plates in realtime."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraViewController":{"role":"symbol","title":"SBSDKUICameraViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICameraViewController"}],"abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController"},{"type":"text","text":" subclass which adds support for enabled and disabled camera permission."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICameraViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/present(on:configuration:delegate:)":{"role":"symbol","title":"present(on:configuration:delegate:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUILicensePlateScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUILicensePlateScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUILicensePlateScannerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SBSDKUILicensePlateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerViewController"}],"abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController"},{"type":"text","text":" and presents it modally."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/present(on:configuration:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentOn:configuration:delegate:"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/present(on:configuration:delegate:)"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/updateFlashButton":{"role":"symbol","title":"updateFlashButton","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateFlashButton"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/updateFlashButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateFlashButton"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/updateflashbutton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/didHideEnableCameraView":{"role":"symbol","title":"didHideEnableCameraView","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didHideEnableCameraView"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/didHideEnableCameraView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didHideEnableCameraView"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/didhideenablecameraview"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/isRecognitionEnabled":{"role":"symbol","title":"isRecognitionEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRecognitionEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Enables or disables the recognition if license plates."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/isRecognitionEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isRecognitionEnabled"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/isrecognitionenabled"},"doc://net.doo.ScanbotSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.3"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewControllerDelegate":{"role":"symbol","title":"SBSDKLicensePlateScannerViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicensePlateScannerViewControllerDelegate"}],"abstract":[{"type":"text","text":"The delegate protocol for the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicensePlateScannerViewControllerDelegate"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontrollerdelegate"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s8SendableP"},"doc://net.doo.ScanbotSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/enableCameraTextConfiguration":{"role":"symbol","title":"enableCameraTextConfiguration","fragments":[{"kind":"identifier","text":"enableCameraTextConfiguration"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/enableCameraTextConfiguration","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/enablecameratextconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/SBSDKLicensePlateScannerViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"SBSDKLicensePlateScannerViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/SBSDKLicensePlateScannerViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/sbsdklicenseplatescannerviewcontrollerdelegate-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewController":{"role":"symbol","title":"SBSDKLicensePlateScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicensePlateScannerViewController"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to scan for license plates with the camera."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicensePlateScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontroller"},"doc://net.doo.ScanbotSDK/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/enableCameraUIConfiguration":{"role":"symbol","title":"enableCameraUIConfiguration","fragments":[{"kind":"identifier","text":"enableCameraUIConfiguration"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/enableCameraUIConfiguration","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/enablecamerauiconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/create(configuration:delegate:)":{"role":"symbol","title":"create(configuration:delegate:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUILicensePlateScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUILicensePlateScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUILicensePlateScannerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SBSDKUILicensePlateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerViewController"}],"abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/create(configuration:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createNewWithConfiguration:delegate:"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/create(configuration:delegate:)"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewController":{"role":"symbol","title":"SBSDKUIViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIViewController"}],"abstract":[{"type":"text","text":"An abstract base class for RTU-UI view controllers."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontroller"},"doc://net.doo.ScanbotSDK/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUILicensePlateScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUILicensePlateScannerViewControllerDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The receivers delegate."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/delegate"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/updateLayout":{"role":"symbol","title":"updateLayout","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateLayout"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/updateLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateLayout"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/updatelayout"},"doc://net.doo.ScanbotSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/willShowEnableCameraView":{"role":"symbol","title":"willShowEnableCameraView","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willShowEnableCameraView"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/willShowEnableCameraView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"willShowEnableCameraView"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/willshowenablecameraview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUILicensePlateScannerViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/containerForEnableCameraView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/delegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/enableCameraTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/enableCameraUIConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/isRecognitionEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/supportedInterfaceOrientations"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/didHideEnableCameraView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/updateFlashButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/updateLayout","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/viewDidLoad","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/willShowEnableCameraView"]},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/create(configuration:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/present(on:configuration:delegate:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/SBSDKLicensePlateScannerViewControllerDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewControllerDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraViewController","text":"SBSDKUICameraViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/title","value":"SBSDKUILicensePlateScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/title","value":"SBSDKUICameraViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUICameraViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController~1present(on:configuration:delegate:)\/title","value":"presentOn:configuration:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController~1present(on:configuration:delegate:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"presentOn:configuration:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController~1isRecognitionEnabled\/title","value":"isRecognitionEnabled"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController~1isRecognitionEnabled\/fragments","value":[{"kind":"identifier","text":"isRecognitionEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewControllerDelegate\/title","value":"SBSDKLicensePlateScannerViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController\/title","value":"SBSDKLicensePlateScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController~1create(configuration:delegate:)\/title","value":"createNewWithConfiguration:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController~1create(configuration:delegate:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createNewWithConfiguration:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/title","value":"SBSDKUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}