{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration"},"abstract":[{"text":"The general configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"navigatorTitle":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerGeneralConfiguration","modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Class","symbolKind":"class","title":"SBSDKBaseScannerGeneralConfiguration"},"kind":"symbol","sections":[],"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/focusLockPosition","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/initialScanDelay","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/isFocusLockEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/minimumTimeWithoutDeviceMotionBeforeDetection","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/photoQualityPrioritization","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/playFlashAnimation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/stopsCameraSessionWhenDisappeared","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/videoContentMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/videoFlipMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/videoFrameResolution"]},{"anchor":"Type-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/defaultConfiguration"],"title":"Type Properties","generated":true}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/photoQualityPrioritization":{"url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/photoqualityprioritization","type":"topic","title":"photoQualityPrioritization","navigatorTitle":[{"kind":"identifier","text":"photoQualityPrioritization"}],"abstract":[{"type":"text","text":"The prioritization of still image quality and capturing speed."},{"type":"text","text":" "},{"text":"Defaults to ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced","isActive":true,"type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"If you experience lots of blurry still images try to set this property to SBSDKCapturePhotoQualityPrioritization.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"photoQualityPrioritization","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCapturePhotoQualityPrioritization","text":"SBSDKCapturePhotoQualityPrioritization"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/photoQualityPrioritization","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFrameResolution/auto":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution\/auto","role":"symbol","navigatorTitle":[{"text":"SBSDKVideoFrameResolutionAuto","kind":"identifier"}],"title":"SBSDKVideoFrameResolution.auto","url":"\/documentation\/scanbotsdk\/sbsdkvideoframeresolution\/auto","abstract":[{"text":"Select the video resolution automatically based on device specifics.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"auto","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/stopsCameraSessionWhenDisappeared":{"url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/stopscamerasessionwhendisappeared","abstract":[{"text":"If set to ","type":"text"},{"code":"True","type":"codeVoice"},{"text":", the camera session will be stopped entirely, when the base scanner view controller disappears and restarts when it reappears.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The base scanner view controller will cause no CPU load after it disappeared."},{"type":"text","text":" "},{"text":"Setting it to ","type":"text"},{"code":"False","type":"codeVoice"},{"type":"text","text":" will NOT stop the camera session, but pauses the delivery of video frames from the camera session to the base scanner view controller."},{"text":" ","type":"text"},{"type":"text","text":"There is some low CPU activity while the base scanner view controller is not on screen, but there is also no delay when the receiver returns to the screen."}],"type":"topic","title":"stopsCameraSessionWhenDisappeared","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"stopsCameraSessionWhenDisappeared","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/stopsCameraSessionWhenDisappeared","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"stopsCameraSessionWhenDisappeared"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/playFlashAnimation":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/playflashanimation","navigatorTitle":[{"text":"playFlashAnimation","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/playFlashAnimation","title":"playFlashAnimation","role":"symbol","abstract":[{"type":"text","text":"Whether the receiver plays a flash-light animation when capturing images or not. Defaults to "},{"code":"False","type":"codeVoice"},{"text":". *\/","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playFlashAnimation","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/isFocusLockEnabled":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/isFocusLockEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFocusLockEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/isfocuslockenabled","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isFocusLockEnabled"}],"abstract":[{"type":"text","text":"Disables auto-focus and locks the lens at the specified focus lens position. The default value is "},{"type":"codeVoice","code":"False"},{"text":".","type":"text"}],"title":"isFocusLockEnabled","kind":"symbol"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/videoFlipMode":{"url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/videoflipmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/videoFlipMode","abstract":[{"text":"Defines how video frames, still images and the camera previer layer are flipped.","type":"text"}],"role":"symbol","title":"videoFlipMode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"videoFlipMode"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoFlipMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoFlipMode","text":"SBSDKVideoFlipMode"}],"type":"topic"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/focusLockPosition":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/focuslockposition","navigatorTitle":[{"text":"focusLockPosition","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/focusLockPosition","title":"focusLockPosition","role":"symbol","abstract":[{"text":"The position of the lens. Values can be between 0.0 (minimum focusing distance) and 1.0 (maximum focusing distance). The value will be clamped to [0.0, 1.0].","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to 0.0.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"focusLockPosition","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCapturePhotoQualityPrioritization/balanced":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced","url":"\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization\/balanced","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKCapturePhotoQualityPrioritizationBalanced","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"balanced","kind":"identifier"}],"title":"SBSDKCapturePhotoQualityPrioritization.balanced","abstract":[{"type":"text","text":"Balances capturing speed and image quality equally. This is the default value."}],"type":"topic"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/defaultConfiguration":{"title":"defaultConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/defaultConfiguration","abstract":[{"type":"text","text":"This is the default configuration with the properties initialized as mentioned in their description."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/defaultconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBaseScannerGeneralConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerGeneralConfiguration"}],"type":"topic","navigatorTitle":[{"text":"defaultConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/init":{"url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/init","kind":"symbol","title":"init"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/videoContentMode":{"url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/videocontentmode","type":"topic","role":"symbol","navigatorTitle":[{"text":"videoContentMode","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The content mode of the video preview layer: fit-in or fill-in. Defaults to ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode\/fillIn","isActive":true},{"type":"text","text":"."}],"title":"videoContentMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/videoContentMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"videoContentMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKVideoContentMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoContentMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration":{"abstract":[{"text":"The general configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration","type":"topic","title":"SBSDKBaseScannerGeneralConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/minimumTimeWithoutDeviceMotionBeforeDetection":{"navigatorTitle":[{"kind":"identifier","text":"minimumTimeWithoutDeviceMotionBeforeDetection"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/minimumtimewithoutdevicemotionbeforedetection","abstract":[{"text":"To prevent blurred images before the video frame is sent to the detector, the device must have registered no significant motion for a certain amount of time.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This property defines this amount of time."},{"text":" ","type":"text"},{"type":"text","text":"By default it is set to 0.0 seconds for the most scanners."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/minimumTimeWithoutDeviceMotionBeforeDetection","title":"minimumTimeWithoutDeviceMotionBeforeDetection","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimumTimeWithoutDeviceMotionBeforeDetection"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"type":"topic"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/initialScanDelay":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/initialscandelay","navigatorTitle":[{"text":"initialScanDelay","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/initialScanDelay","title":"initialScanDelay","role":"symbol","abstract":[{"text":"The delay of recognition after appearance in seconds. Defaults to 0 seconds.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialScanDelay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/videoFrameResolution":{"abstract":[{"type":"text","text":"The video frame resolution of the preview layer."},{"type":"text","text":" "},{"text":"Defaults to ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution\/auto","isActive":true},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Higher resolutions may improve scanning results but slow down the scanning performance."},{"text":" ","type":"text"},{"text":"In some cases a higher resolution may even decrease the scanning quality.","type":"text"},{"text":" ","type":"text"},{"text":"It is therefore recommended to keep this setting at ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution\/auto"},{"type":"text","text":"."}],"type":"topic","title":"videoFrameResolution","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoFrameResolution"},{"kind":"text","text":": "},{"text":"SBSDKVideoFrameResolution","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoFrameResolution"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/videoFrameResolution","navigatorTitle":[{"kind":"identifier","text":"videoFrameResolution"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/videoframeresolution","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoContentMode/fillIn":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode\/fillIn","url":"\/documentation\/scanbotsdk\/sbsdkvideocontentmode\/fillin","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoContentModeFillIn"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillIn","kind":"identifier"}],"abstract":[{"type":"text","text":"The video layers content is filled into the video layer."},{"type":"text","text":" "},{"type":"text","text":"No visible borders. Video may be cropped to the visible screen area."}],"type":"topic","title":"SBSDKVideoContentMode.fillIn"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"SBSDKBaseScannerGeneralConfiguration","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/focusLockPosition","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/initialScanDelay","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/isFocusLockEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/minimumTimeWithoutDeviceMotionBeforeDetection","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/photoQualityPrioritization","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/playFlashAnimation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/stopsCameraSessionWhenDisappeared","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/videoContentMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/videoFlipMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/videoFrameResolution"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/init"],"generated":true,"title":"Instance Methods"},{"anchor":"Type-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/defaultConfiguration"],"title":"Type Properties","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1photoQualityPrioritization\/title","value":"photoQualityPrioritization"},{"value":[{"text":"photoQualityPrioritization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1photoQualityPrioritization\/fragments"},{"value":"SBSDKVideoFrameResolutionAuto","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution~1auto\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution~1auto\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionAuto"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1stopsCameraSessionWhenDisappeared\/title","value":"stopsCameraSessionWhenDisappeared"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1stopsCameraSessionWhenDisappeared\/fragments","value":[{"text":"stopsCameraSessionWhenDisappeared","kind":"identifier"}]},{"value":"playFlashAnimation","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1playFlashAnimation\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1playFlashAnimation\/fragments","op":"replace","value":[{"kind":"identifier","text":"playFlashAnimation"}]},{"value":"isFocusLockEnabled","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1isFocusLockEnabled\/title","op":"replace"},{"value":[{"kind":"identifier","text":"isFocusLockEnabled"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1isFocusLockEnabled\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1videoFlipMode\/title","value":"videoFlipMode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1videoFlipMode\/fragments","value":[{"kind":"identifier","text":"videoFlipMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1focusLockPosition\/title","value":"focusLockPosition"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1focusLockPosition\/fragments","op":"replace","value":[{"text":"focusLockPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization~1balanced\/title","value":"SBSDKCapturePhotoQualityPrioritizationBalanced"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization~1balanced\/fragments","value":[{"text":"SBSDKCapturePhotoQualityPrioritizationBalanced","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1defaultConfiguration\/title","value":"defaultConfiguration"},{"value":[{"kind":"identifier","text":"defaultConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1defaultConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1videoContentMode\/title","value":"videoContentMode","op":"replace"},{"value":[{"kind":"identifier","text":"videoContentMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1videoContentMode\/fragments"},{"value":"SBSDKBaseScannerGeneralConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/navigatorTitle","value":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1minimumTimeWithoutDeviceMotionBeforeDetection\/title","op":"replace","value":"minimumTimeWithoutDeviceMotionBeforeDetection"},{"op":"replace","value":[{"text":"minimumTimeWithoutDeviceMotionBeforeDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1minimumTimeWithoutDeviceMotionBeforeDetection\/fragments"},{"value":"initialScanDelay","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1initialScanDelay\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1initialScanDelay\/fragments","op":"replace","value":[{"kind":"identifier","text":"initialScanDelay"}]},{"op":"replace","value":"videoFrameResolution","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1videoFrameResolution\/title"},{"value":[{"text":"videoFrameResolution","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1videoFrameResolution\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode~1fillIn\/title","op":"replace","value":"SBSDKVideoContentModeFillIn"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode~1fillIn\/fragments","value":[{"text":"SBSDKVideoContentModeFillIn","kind":"identifier"}]}]}]}