{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"text":"Health insurance card field type.","type":"text"}],"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/cardCountry","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/cardExpirationDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/cardNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/dateOfBirth","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/givenName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/institutionName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/institutionNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/personalIdentificationNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/surname"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/init(rawValue:)"]},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKHealthInsuranceCardFieldType","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType"},"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKHealthInsuranceCardFieldType","navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldType"}],"roleHeading":"Enumeration","symbolKind":"enum","role":"symbol","title":"SBSDKHealthInsuranceCardFieldType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKHealthInsuranceCardFieldType","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType/institutionNumber":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/institutionNumber","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/institutionnumber","type":"topic","title":"SBSDKHealthInsuranceCardFieldType.institutionNumber","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"institutionNumber"}],"abstract":[{"text":"Field 7 (part before dash): institution number","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldTypeInstitutionNumber"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldType"}],"abstract":[{"type":"text","text":"Health insurance card field type."}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardFieldType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType","title":"SBSDKHealthInsuranceCardFieldType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType/dateOfBirth":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/dateOfBirth","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/dateofbirth","type":"topic","title":"SBSDKHealthInsuranceCardFieldType.dateOfBirth","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth"}],"abstract":[{"type":"text","text":"Field 5: date of birth"}],"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardFieldTypeDateOfBirth","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType/cardNumber":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/cardNumber","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/cardnumber","type":"topic","title":"SBSDKHealthInsuranceCardFieldType.cardNumber","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardNumber"}],"abstract":[{"type":"text","text":"Field 8: card number"}],"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardFieldTypeCardNumber","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/RawRepresentable-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/rawrepresentable-implementations","type":"topic","title":"RawRepresentable Implementations","kind":"article","role":"collectionGroup","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType/institutionName":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/institutionName","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/institutionname","type":"topic","title":"SBSDKHealthInsuranceCardFieldType.institutionName","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"institutionName"}],"abstract":[{"text":"Field 7 (part after dash): institution name or abbreviation","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldTypeInstitutionName"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType/personalIdentificationNumber":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/personalIdentificationNumber","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/personalidentificationnumber","type":"topic","title":"SBSDKHealthInsuranceCardFieldType.personalIdentificationNumber","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"personalIdentificationNumber"}],"abstract":[{"type":"text","text":"Field 6: personal identification number"}],"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardFieldTypePersonalIdentificationNumber","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType/cardCountry":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/cardCountry","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/cardcountry","type":"topic","title":"SBSDKHealthInsuranceCardFieldType.cardCountry","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardCountry"}],"abstract":[{"type":"text","text":"Field 10: card country"}],"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardFieldTypeCardCountry","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType/init(rawValue:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/init(rawValue:)","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/init(rawvalue:)","type":"topic","title":"init(rawValue:)","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType/cardExpirationDate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/cardExpirationDate","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/cardexpirationdate","type":"topic","title":"SBSDKHealthInsuranceCardFieldType.cardExpirationDate","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardExpirationDate"}],"abstract":[{"text":"Field 9: card expiration date","type":"text"}],"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardFieldTypeCardExpirationDate","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType/givenName":{"title":"SBSDKHealthInsuranceCardFieldType.givenName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"givenName","kind":"identifier"}],"abstract":[{"text":"Field 4: given names","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/givenname","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardFieldTypeGivenName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/givenName","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType/Equatable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/Equatable-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/equatable-implementations","type":"topic","title":"Equatable Implementations","kind":"article","role":"collectionGroup","abstract":[]},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType/surname":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/surname","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/surname","navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldTypeSurname"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"surname","kind":"identifier"}],"title":"SBSDKHealthInsuranceCardFieldType.surname","abstract":[{"type":"text","text":"Field 3: surname"}]},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","value":"SBSDKHealthInsuranceCardFieldType","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKHealthInsuranceCardFieldType","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKHealthInsuranceCardFieldType","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/cardCountry","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/cardExpirationDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/cardNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/dateOfBirth","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/givenName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/institutionName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/institutionNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/personalIdentificationNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/surname"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKHealthInsuranceCardFieldType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1institutionNumber\/title","op":"replace","value":"SBSDKHealthInsuranceCardFieldTypeInstitutionNumber"},{"value":[{"text":"SBSDKHealthInsuranceCardFieldTypeInstitutionNumber","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1institutionNumber\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType\/title","value":"SBSDKHealthInsuranceCardFieldType"},{"value":[{"text":"SBSDKHealthInsuranceCardFieldType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType\/fragments"},{"op":"replace","value":"SBSDKHealthInsuranceCardFieldTypeDateOfBirth","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1dateOfBirth\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1dateOfBirth\/fragments","op":"replace","value":[{"text":"SBSDKHealthInsuranceCardFieldTypeDateOfBirth","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1cardNumber\/title","op":"replace","value":"SBSDKHealthInsuranceCardFieldTypeCardNumber"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1cardNumber\/fragments","op":"replace","value":[{"text":"SBSDKHealthInsuranceCardFieldTypeCardNumber","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1institutionName\/title","value":"SBSDKHealthInsuranceCardFieldTypeInstitutionName"},{"value":[{"text":"SBSDKHealthInsuranceCardFieldTypeInstitutionName","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1institutionName\/fragments","op":"replace"},{"op":"replace","value":"SBSDKHealthInsuranceCardFieldTypePersonalIdentificationNumber","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1personalIdentificationNumber\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1personalIdentificationNumber\/fragments","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldTypePersonalIdentificationNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1cardCountry\/title","value":"SBSDKHealthInsuranceCardFieldTypeCardCountry"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1cardCountry\/fragments","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldTypeCardCountry"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1cardExpirationDate\/title","value":"SBSDKHealthInsuranceCardFieldTypeCardExpirationDate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1cardExpirationDate\/fragments","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldTypeCardExpirationDate"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1givenName\/title","value":"SBSDKHealthInsuranceCardFieldTypeGivenName","op":"replace"},{"value":[{"text":"SBSDKHealthInsuranceCardFieldTypeGivenName","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1givenName\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1surname\/title","value":"SBSDKHealthInsuranceCardFieldTypeSurname"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1surname\/fragments","value":[{"text":"SBSDKHealthInsuranceCardFieldTypeSurname","kind":"identifier"}]}]}]}