{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"A "},{"code":"UIView","type":"codeVoice"},{"type":"text","text":" that conforms to the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTrackedBarcodeInfoViewable"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKTrackedBarcodeInfoView","roleHeading":"Type Alias","navigatorTitle":[{"text":"SBSDKTrackedBarcodeInfoView","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTrackedBarcodeInfoView"}],"role":"symbol","externalID":"s:10ScanbotSDK27SBSDKTrackedBarcodeInfoViewa","symbolKind":"typealias"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SBSDKTrackedBarcodeInfoView","kind":"identifier"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKTrackedBarcodeInfoViewable","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTrackedBarcodeInfoViewable","text":"SBSDKTrackedBarcodeInfoViewable"},{"kind":"text","text":")"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTrackedBarcodeInfoView"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktrackedbarcodeinfoview"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayConfiguration":{"title":"SBSDKBarcodeTrackingOverlayConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayConfiguration"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayConfiguration"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlayconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayConfiguration","kind":"symbol","abstract":[{"type":"text","text":"A class that represents the configuration options for a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"This overlay is used to visualize the detected barcodes on the screen."},{"type":"text","text":" "},{"type":"text","text":"The class provides various customization options for the appearance and behavior of the overlay."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTrackedBarcodeInfoViewable":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTrackedBarcodeInfoViewable"}],"url":"\/documentation\/scanbotsdk\/sbsdktrackedbarcodeinfoviewable","title":"SBSDKTrackedBarcodeInfoViewable","navigatorTitle":[{"kind":"identifier","text":"SBSDKTrackedBarcodeInfoViewable"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTrackedBarcodeInfoViewable","kind":"symbol","abstract":[{"type":"text","text":"A protocol that defines the methods and properties required for a custom tracking view to be displayed over detected barcodes using the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayConfiguration"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The custom view must conform to this protocol in order to be used as an overlay on top of the detected barcodes."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTrackedBarcodeInfoView":{"title":"SBSDKTrackedBarcodeInfoView","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"SBSDKTrackedBarcodeInfoView","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKTrackedBarcodeInfoView","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktrackedbarcodeinfoview","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTrackedBarcodeInfoView","kind":"symbol","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":" that conforms to the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTrackedBarcodeInfoViewable"},{"type":"text","text":"."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"SBSDKBarcodeTrackingOverlayConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayConfiguration\/title"},{"value":[{"text":"SBSDKBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeTrackingOverlayConfiguration","kind":"identifier"}]},{"value":"SBSDKTrackedBarcodeInfoViewable","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTrackedBarcodeInfoViewable\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTrackedBarcodeInfoViewable\/fragments","value":[{"text":"SBSDKTrackedBarcodeInfoViewable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTrackedBarcodeInfoViewable\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKTrackedBarcodeInfoViewable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}