{"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2BarcodeRecognizerConfiguration) ","kind":"text"},{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration"]}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/init(from:)"],"title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/acceptedDocumentFormats","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/australiaPostCustomerFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/barcodeFormats","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/barcodesExtensionFilter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/barcodesRegexFilter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/gs1Handling","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/maximumTextLength","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/minimum1DBarcodesQuietZone","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/minimumTextLength","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/msiPlesseyChecksumAlgorithm","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/stripCheckDigits","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/useCode11Checksum","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/useIATA2OF5Checksum"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/toJson()"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"navigatorTitle":[{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeRecognizerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"role":"symbol","title":"SBSDKUI2BarcodeRecognizerConfiguration"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Configuration of the scanning behavior."}],"references":{"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/isEqual:":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/isequal:","fragments":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[],"title":"isEqual:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/isEqual:"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/stripCheckDigits":{"abstract":[{"type":"text","text":"If "},{"type":"codeVoice","code":"true"},{"type":"text","text":", check digits for UPC, EAN and MSI Plessey codes are removed from the result. Has no effect if both"},{"type":"text","text":" "},{"text":"single and double digit MSI Plessey checksums are enabled. The default is ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Default is false"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/stripcheckdigits","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stripCheckDigits","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","title":"stripCheckDigits","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/stripCheckDigits","navigatorTitle":[{"kind":"identifier","text":"stripCheckDigits"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/toJson()":{"kind":"symbol","title":"toJson()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/toJson()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"toJson"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/tojson()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration":{"abstract":[{"type":"text","text":"Configuration of the scanning behavior."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"type":"topic","title":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration","navigatorTitle":[{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/hash":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/hash","fragments":[{"text":"hash","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[],"title":"hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/hash"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/init()":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/init()","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[],"title":"init()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/init()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/minimum1DBarcodesQuietZone":{"navigatorTitle":[{"text":"minimum1DBarcodesQuietZone","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/minimum1dbarcodesquietzone","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimum1DBarcodesQuietZone"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","role":"symbol","kind":"symbol","title":"minimum1DBarcodesQuietZone","abstract":[{"type":"text","text":"Optional minimum required quiet zone on the barcode. Measured in modules (the smallest bar size on a barcode)."},{"text":" ","type":"text"},{"type":"text","text":"The default is 10. NOTE - This feature works on ITF barcodes only."},{"type":"text","text":" "},{"type":"text","text":"Default is 10"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/minimum1DBarcodesQuietZone"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/barcodeFormats":{"navigatorTitle":[{"kind":"identifier","text":"barcodeFormats"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/barcodeformats","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"barcodeFormats","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat","text":"SBSDKUI2BarcodeFormat"},{"text":"]","kind":"text"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"List of accepted barcode symbologies."}],"title":"barcodeFormats","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/barcodeFormats"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"url":"\/documentation\/scanbotsdk\/sbsdkui2node","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Node","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Node","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","title":"SBSDKUI2Node","type":"topic","abstract":[{"type":"text","text":"Abstract class for all the configurations."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/acceptedDocumentFormats":{"navigatorTitle":[{"kind":"identifier","text":"acceptedDocumentFormats"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/accepteddocumentformats","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptedDocumentFormats"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeDocumentFormat","kind":"typeIdentifier","text":"SBSDKUI2BarcodeDocumentFormat"},{"text":"]","kind":"text"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"List of accepted barcode document formats."}],"title":"acceptedDocumentFormats","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/acceptedDocumentFormats"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/barcodesRegexFilter":{"navigatorTitle":[{"kind":"identifier","text":"barcodesRegexFilter"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/barcodesregexfilter","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"barcodesRegexFilter","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"barcodesRegexFilter","abstract":[{"type":"text","text":"Regular expression filter for barcode text. If the barcode text does not match the regular expression, it will"},{"type":"text","text":" "},{"type":"text","text":"not be scanned. The default is an empty string (setting is turned off). This option overrides"},{"text":" ","type":"text"},{"code":"barcodesExtensionFilter","type":"codeVoice"},{"type":"text","text":" option."},{"type":"text","text":" "},{"type":"text","text":"Default is “”"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/barcodesRegexFilter"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/useCode11Checksum":{"navigatorTitle":[{"text":"useCode11Checksum","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/usecode11checksum","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useCode11Checksum","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","role":"symbol","kind":"symbol","title":"useCode11Checksum","abstract":[{"type":"text","text":"If "},{"code":"true","type":"codeVoice"},{"type":"text","text":", the optional check digit for CODE_11 codes is used in validation. The default is "},{"code":"true","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is true"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/useCode11Checksum"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/msiPlesseyChecksumAlgorithm":{"navigatorTitle":[{"text":"msiPlesseyChecksumAlgorithm","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/msiplesseychecksumalgorithm","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"msiPlesseyChecksumAlgorithm","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}],"type":"topic","role":"symbol","kind":"symbol","title":"msiPlesseyChecksumAlgorithm","abstract":[{"type":"text","text":"Checksum algorithm used for MSI Plessey barcodes. The default value is MOD_10."},{"type":"text","text":" "},{"text":"Default is MOD_10","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/msiPlesseyChecksumAlgorithm"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/barcodesExtensionFilter":{"navigatorTitle":[{"text":"barcodesExtensionFilter","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/barcodesextensionfilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"barcodesExtensionFilter","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodesExtensionFilter","text":"SBSDKUI2BarcodesExtensionFilter"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Filter for extended EAN and UPC barcodes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is NO_FILTER"}],"title":"barcodesExtensionFilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/barcodesExtensionFilter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/minimumTextLength":{"navigatorTitle":[{"text":"minimumTextLength","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/minimumtextlength","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumTextLength"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","role":"symbol","kind":"symbol","title":"minimumTextLength","abstract":[{"type":"text","text":"Optional minimum required text length of the detected barcode. The default is 0 (setting is turned off). NOTE -"},{"type":"text","text":" "},{"text":"This feature works on ITF barcodes only.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is 0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/minimumTextLength"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/init(accepteddocumentformats:barcodesextensionfilter:barcodesregexfilter:minimumtextlength:maximumtextlength:minimum1dbarcodesquietzone:stripcheckdigits:useiata2of5checksum:usecode11checksum:barcodeformats:msiplesseychecksumalgorithm:austra-872c0","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"acceptedDocumentFormats","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SBSDKUI2BarcodeDocumentFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeDocumentFormat"},{"text":"], ","kind":"text"},{"text":"barcodesExtensionFilter","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodesExtensionFilter","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodesExtensionFilter"},{"text":", ","kind":"text"},{"text":"barcodesRegexFilter","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minimumTextLength"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"maximumTextLength"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"minimum1DBarcodesQuietZone","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"stripCheckDigits"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"useIATA2OF5Checksum","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"useCode11Checksum","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"barcodeFormats","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat","text":"SBSDKUI2BarcodeFormat"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"msiPlesseyChecksumAlgorithm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"},{"text":", ","kind":"text"},{"text":"australiaPostCustomerFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2AustraliaPostCustomerFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2AustraliaPostCustomerFormat"},{"text":", ","kind":"text"},{"text":"gs1Handling","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Gs1Handling","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2Gs1Handling","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[],"title":"init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/australiaPostCustomerFormat":{"navigatorTitle":[{"text":"australiaPostCustomerFormat","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/australiapostcustomerformat","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"australiaPostCustomerFormat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2AustraliaPostCustomerFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2AustraliaPostCustomerFormat"}],"type":"topic","role":"symbol","kind":"symbol","title":"australiaPostCustomerFormat","abstract":[{"text":"The customer format used in AUSTRALIA_POST codes. The default value is ALPHA_NUMERIC.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is ALPHA_NUMERIC"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/australiaPostCustomerFormat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/gs1Handling":{"navigatorTitle":[{"text":"gs1Handling","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/gs1handling","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gs1Handling","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Gs1Handling","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2Gs1Handling"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The expected way of handling GS1_COMPOSITE barcodes."},{"type":"text","text":" "},{"text":"Default is PARSE","type":"text"}],"title":"gs1Handling","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/gs1Handling"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/init(from:)":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/init(from:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","role":"symbol","kind":"symbol","title":"init(from:)","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/init(from:)"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/useIATA2OF5Checksum":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/useIATA2OF5Checksum","title":"useIATA2OF5Checksum","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"useIATA2OF5Checksum","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","navigatorTitle":[{"text":"useIATA2OF5Checksum","kind":"identifier"}],"abstract":[{"type":"text","text":"If "},{"code":"true","type":"codeVoice"},{"text":", the optional check digit for IATA_2_OF_5 codes is used in validation. The default is ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"Default is true","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/useiata2of5checksum","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/maximumTextLength":{"navigatorTitle":[{"kind":"identifier","text":"maximumTextLength"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/maximumtextlength","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"maximumTextLength","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Optional maximum text length of the detected barcode. The default is 0 (setting is turned off). NOTE - This"},{"type":"text","text":" "},{"text":"feature works on ITF barcodes only.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is 0"}],"title":"maximumTextLength","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/maximumTextLength"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"SBSDKUI2BarcodeRecognizerConfiguration","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}],"op":"replace"},{"value":[{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/acceptedDocumentFormats","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/australiaPostCustomerFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/barcodeFormats","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/barcodesExtensionFilter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/barcodesRegexFilter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/gs1Handling","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/maximumTextLength","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/minimum1DBarcodesQuietZone","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/minimumTextLength","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/msiPlesseyChecksumAlgorithm","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/stripCheckDigits","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/useCode11Checksum","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/useIATA2OF5Checksum"],"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/toJson()"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"kind":"relationships"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node","text":"SBSDKUI2Node"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1stripCheckDigits\/title","value":"stripCheckDigits"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1stripCheckDigits\/fragments","value":[{"kind":"identifier","text":"stripCheckDigits"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1toJson()\/title","value":"toJson","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1toJson()\/fragments","value":[{"kind":"text","text":"- "},{"text":"toJson","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/title","value":"SBSDKUI2BarcodeRecognizerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/fragments","value":[{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1init()\/title","op":"replace","value":"init"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1init()\/fragments"},{"op":"replace","value":"minimum1DBarcodesQuietZone","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1minimum1DBarcodesQuietZone\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1minimum1DBarcodesQuietZone\/fragments","value":[{"kind":"identifier","text":"minimum1DBarcodesQuietZone"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1barcodeFormats\/title","value":"barcodeFormats"},{"value":[{"kind":"identifier","text":"barcodeFormats"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1barcodeFormats\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title","value":"SBSDKUI2Node","op":"replace"},{"value":[{"text":"SBSDKUI2Node","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments","op":"replace"},{"value":"acceptedDocumentFormats","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1acceptedDocumentFormats\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1acceptedDocumentFormats\/fragments","value":[{"kind":"identifier","text":"acceptedDocumentFormats"}]},{"op":"replace","value":"barcodesRegexFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1barcodesRegexFilter\/title"},{"value":[{"kind":"identifier","text":"barcodesRegexFilter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1barcodesRegexFilter\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1useCode11Checksum\/title","op":"replace","value":"useCode11Checksum"},{"value":[{"kind":"identifier","text":"useCode11Checksum"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1useCode11Checksum\/fragments"},{"op":"replace","value":"msiPlesseyChecksumAlgorithm","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1msiPlesseyChecksumAlgorithm\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1msiPlesseyChecksumAlgorithm\/fragments","value":[{"kind":"identifier","text":"msiPlesseyChecksumAlgorithm"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1barcodesExtensionFilter\/title","value":"barcodesExtensionFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1barcodesExtensionFilter\/fragments","value":[{"text":"barcodesExtensionFilter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1minimumTextLength\/title","value":"minimumTextLength","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1minimumTextLength\/fragments","op":"replace","value":[{"text":"minimumTextLength","kind":"identifier"}]},{"value":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1australiaPostCustomerFormat\/title","value":"australiaPostCustomerFormat"},{"value":[{"text":"australiaPostCustomerFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1australiaPostCustomerFormat\/fragments","op":"replace"},{"value":"gs1Handling","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1gs1Handling\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1gs1Handling\/fragments","value":[{"kind":"identifier","text":"gs1Handling"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1useIATA2OF5Checksum\/title","value":"useIATA2OF5Checksum","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1useIATA2OF5Checksum\/fragments","value":[{"text":"useIATA2OF5Checksum","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1maximumTextLength\/title","value":"maximumTextLength"},{"value":[{"kind":"identifier","text":"maximumTextLength"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1maximumTextLength\/fragments","op":"replace"}]}]}