{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKMRZDocumentType) "},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZDocumentType"}],"platforms":["iOS"],"languages":["swift"]}]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/rawValue"],"generated":true,"anchor":"Instance-Properties"},{"title":"Type Properties","anchor":"Type-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/chDrivingLicense","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/crewMemberCertificate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/idCard","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/passport","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/unknown","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/visa"],"generated":true},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/enumValue(from:)"],"anchor":"Type-Methods","title":"Type Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"title":"SBSDKMRZDocumentType","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKMRZDocumentType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMRZDocumentType","kind":"identifier"}],"roleHeading":"Class","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType","modules":[{"name":"ScanbotSDK"}],"symbolKind":"class"},"sections":[],"abstract":[{"type":"text","text":"Type of document containing the MRZ."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZDocumentType/rawValue":{"title":"rawValue","url":"\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype\/rawvalue","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/rawValue","role":"symbol","abstract":[{"type":"text","text":"The raw value integer of the current "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType","isActive":true,"type":"reference"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rawValue"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZDocumentType/passport":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype\/passport","navigatorTitle":[{"text":"passport","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"passport"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType","text":"SBSDKMRZDocumentType","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/passport","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Passport."}],"title":"passport"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZDocumentType/idCard":{"abstract":[{"type":"text","text":"ID card."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/idCard","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype\/idcard","type":"topic","role":"symbol","title":"idCard","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"idCard","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKMRZDocumentType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType"}],"navigatorTitle":[{"text":"idCard","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZDocumentType/chDrivingLicense":{"abstract":[{"text":"Swiss driver license.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/chDrivingLicense","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype\/chdrivinglicense","type":"topic","role":"symbol","title":"chDrivingLicense","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chDrivingLicense"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType","text":"SBSDKMRZDocumentType","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"chDrivingLicense"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZDocumentType/crewMemberCertificate":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype\/crewmembercertificate","navigatorTitle":[{"text":"crewMemberCertificate","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"crewMemberCertificate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKMRZDocumentType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/crewMemberCertificate","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Crew member certificate."}],"title":"crewMemberCertificate"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZDocumentType/unknown":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype\/unknown","navigatorTitle":[{"text":"unknown","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType","text":"SBSDKMRZDocumentType","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/unknown","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Undefined."}],"title":"unknown"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZDocumentType/visa":{"abstract":[{"type":"text","text":"Visa card."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/visa","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype\/visa","type":"topic","role":"symbol","title":"visa","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"visa","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKMRZDocumentType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType"}],"navigatorTitle":[{"text":"visa","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZDocumentType/enumValue(from:)":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype\/enumvalue(from:)","navigatorTitle":[{"kind":"identifier","text":"enumValueFrom:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"enumValue","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKMRZDocumentType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/enumValue(from:)","kind":"symbol","role":"symbol","abstract":[{"text":"Returns an instance of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType"},{"text":" based on the provided raw value.","type":"text"}],"title":"enumValue(from:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZDocumentType/isEqual:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/isEqual:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype\/isequal:","type":"topic","role":"symbol","title":"isEqual:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZDocumentType/hash":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/hash","title":"hash","fragments":[{"text":"hash","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype\/hash","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZDocumentType":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZDocumentType"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMRZDocumentType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType","kind":"symbol","role":"symbol","abstract":[{"text":"Type of document containing the MRZ.","type":"text"}],"title":"SBSDKMRZDocumentType"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKMRZDocumentType","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKMRZDocumentType","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKMRZDocumentType","kind":"identifier"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/rawValue"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/isEqual:"],"title":"Instance Methods","generated":true},{"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/chDrivingLicense","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/crewMemberCertificate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/idCard","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/passport","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/unknown","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/visa"],"generated":true,"anchor":"Type-Properties"},{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/enumValue(from:)"],"title":"Type Methods"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"SBSDKMRZDocumentType","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"rawValue","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1rawValue\/title"},{"op":"replace","value":[{"text":"rawValue","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1rawValue\/fragments"},{"value":"passport","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1passport\/title","op":"replace"},{"value":[{"text":"passport","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1passport\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1idCard\/title","value":"idCard"},{"value":[{"kind":"identifier","text":"idCard"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1idCard\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1chDrivingLicense\/title","value":"chDrivingLicense"},{"value":[{"kind":"identifier","text":"chDrivingLicense"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1chDrivingLicense\/fragments"},{"op":"replace","value":"crewMemberCertificate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1crewMemberCertificate\/title"},{"op":"replace","value":[{"text":"crewMemberCertificate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1crewMemberCertificate\/fragments"},{"op":"replace","value":"unknown","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1unknown\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1unknown\/fragments","op":"replace","value":[{"text":"unknown","kind":"identifier"}]},{"value":"visa","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1visa\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1visa\/fragments","value":[{"kind":"identifier","text":"visa"}],"op":"replace"},{"value":"enumValueFrom:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1enumValue(from:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"enumValueFrom:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1enumValue(from:)\/fragments"},{"value":"SBSDKMRZDocumentType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType\/title"},{"value":[{"kind":"identifier","text":"SBSDKMRZDocumentType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKMRZDocumentType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType\/navigatorTitle"}]}]}