{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"class","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentBoardingPassLeg","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentBoardingPassLeg","role":"symbol","title":"SBSDKBarcodeDocumentBoardingPassLeg","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentBoardingPassLeg"}],"modules":[{"name":"ScanbotSDK"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg"},"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"]},{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","kind":"relationships"}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/airlineDesignatorOfBoardingPassIssuer","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/airlineNumericCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/baggageTagLicensePlateNumbers","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/checkInSequenceNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/compartmentCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/dateOfBoardingPassIssuanceJulian","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/dateOfFlightJulian","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/departureAirportCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/destinationAirportCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/documentFormSerialNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/documentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/fastTrack","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/firstNonConsecutiveBaggageTagLicensePlateNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/flightNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/forIndividualAirlineUse","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/freeBaggageAllowance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/frequentFlyerAirlineDesignator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/frequentFlyerNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/idadIndicator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/internationalDocumentationVerification","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/marketingCarrierDesignator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/operatingCarrierDesignator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/operatingCarrierPNRCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/passengerDescription","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/passengerStatus","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/seatNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/secondNonConsecutiveBaggageTagLicensePlateNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/selecteeIndicator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/sourceOfBoardingPassIssuance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/sourceOfCheckIn","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/versionNumber"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentBoardingPassLeg","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg"]}],"abstract":[{"text":"Leg of the journey.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/firstNonConsecutiveBaggageTagLicensePlateNumber":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"firstNonConsecutiveBaggageTagLicensePlateNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/firstNonConsecutiveBaggageTagLicensePlateNumber","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/firstnonconsecutivebaggagetaglicenseplatenumber","navigatorTitle":[{"text":"firstNonConsecutiveBaggageTagLicensePlateNumber","kind":"identifier"}],"type":"topic","abstract":[{"text":"First Non Consecutive Baggage Tag License Plate Number.","type":"text"}],"kind":"symbol","title":"firstNonConsecutiveBaggageTagLicensePlateNumber"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/checkInSequenceNumber":{"title":"checkInSequenceNumber","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkInSequenceNumber","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/checkInSequenceNumber","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/checkinsequencenumber","kind":"symbol","abstract":[{"type":"text","text":"Check In Sequence Number."}],"role":"symbol","navigatorTitle":[{"text":"checkInSequenceNumber","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/departureAirportCode":{"navigatorTitle":[{"kind":"identifier","text":"departureAirportCode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/departureAirportCode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"departureAirportCode"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/departureairportcode","title":"departureAirportCode","abstract":[{"type":"text","text":"Departure Airport Code."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg":{"title":"SBSDKBarcodeDocumentBoardingPassLeg","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentBoardingPassLeg","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentBoardingPassLeg","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg","abstract":[{"type":"text","text":"Leg of the journey."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/internationalDocumentationVerification":{"title":"internationalDocumentationVerification","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"internationalDocumentationVerification","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/internationalDocumentationVerification","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/internationaldocumentationverification","abstract":[{"type":"text","text":"International Documentation Verification."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"internationalDocumentationVerification","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/requiredDocumentType":{"navigatorTitle":[{"text":"requiredDocumentType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/requiredDocumentType","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/requireddocumenttype","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredDocumentType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","abstract":[{"text":"The name of the wrapped document type.","type":"text"}],"title":"requiredDocumentType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/frequentFlyerNumber":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/frequentflyernumber","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"frequentFlyerNumber"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Frequent Flyer Number."}],"title":"frequentFlyerNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frequentFlyerNumber"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/frequentFlyerNumber","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/sourceOfCheckIn":{"kind":"symbol","navigatorTitle":[{"text":"sourceOfCheckIn","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/sourceOfCheckIn","abstract":[{"type":"text","text":"Source Of Check In."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/sourceofcheckin","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sourceOfCheckIn"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"title":"sourceOfCheckIn"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/documentFormSerialNumber":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentFormSerialNumber"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"text":"Document Form Serial Number.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/documentFormSerialNumber","title":"documentFormSerialNumber","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/documentformserialnumber","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentFormSerialNumber"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/secondNonConsecutiveBaggageTagLicensePlateNumber":{"role":"symbol","abstract":[{"type":"text","text":"Second Non Consecutive Baggage Tag License Plate Number."}],"kind":"symbol","navigatorTitle":[{"text":"secondNonConsecutiveBaggageTagLicensePlateNumber","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/secondNonConsecutiveBaggageTagLicensePlateNumber","title":"secondNonConsecutiveBaggageTagLicensePlateNumber","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/secondnonconsecutivebaggagetaglicenseplatenumber","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"secondNonConsecutiveBaggageTagLicensePlateNumber","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentWrapper":{"abstract":[{"type":"text","text":"Base class for strongly-typed "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","type":"reference"},{"type":"text","text":" wrappers."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper","title":"SBSDKGenericDocumentWrapper","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/seatNumber":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"seatNumber"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/seatnumber","title":"seatNumber","role":"symbol","abstract":[{"type":"text","text":"Seat Number."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/seatNumber","navigatorTitle":[{"kind":"identifier","text":"seatNumber"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/versionNumber":{"abstract":[{"type":"text","text":"VersionNumber."}],"role":"symbol","kind":"symbol","title":"versionNumber","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/versionnumber","navigatorTitle":[{"kind":"identifier","text":"versionNumber"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/versionNumber","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"versionNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/airlineDesignatorOfBoardingPassIssuer":{"abstract":[{"type":"text","text":"Airline Designator Of Boarding Pass Issuer."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/airlineDesignatorOfBoardingPassIssuer","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"airlineDesignatorOfBoardingPassIssuer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/airlinedesignatorofboardingpassissuer","navigatorTitle":[{"kind":"identifier","text":"airlineDesignatorOfBoardingPassIssuer"}],"title":"airlineDesignatorOfBoardingPassIssuer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/dateOfFlightJulian":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dateOfFlightJulian","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/dateofflightjulian","navigatorTitle":[{"text":"dateOfFlightJulian","kind":"identifier"}],"title":"dateOfFlightJulian","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/dateOfFlightJulian","abstract":[{"type":"text","text":"Date Of Flight Julian."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/selecteeIndicator":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/selecteeIndicator","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/selecteeindicator","abstract":[{"text":"Selectee Indicator.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selecteeIndicator"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"selecteeIndicator","kind":"identifier"}],"title":"selecteeIndicator"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/forIndividualAirlineUse":{"abstract":[{"text":"For Individual Airline Use.","type":"text"}],"kind":"symbol","title":"forIndividualAirlineUse","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"forIndividualAirlineUse","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"forIndividualAirlineUse"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/forindividualairlineuse","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/forIndividualAirlineUse","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/idadIndicator":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"idadIndicator","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"idadIndicator"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/idadIndicator","kind":"symbol","title":"idadIndicator","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/idadindicator","abstract":[{"type":"text","text":"IDAD Indicator."}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/fastTrack":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fastTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/fastTrack","type":"topic","title":"fastTrack","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"fastTrack"}],"abstract":[{"text":"Fast Track.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/fasttrack","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/freeBaggageAllowance":{"abstract":[{"type":"text","text":"Free Baggage Allowance."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/freebaggageallowance","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/freeBaggageAllowance","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"freeBaggageAllowance","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"title":"freeBaggageAllowance","navigatorTitle":[{"text":"freeBaggageAllowance","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/frequentFlyerAirlineDesignator":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/frequentFlyerAirlineDesignator","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/frequentflyerairlinedesignator","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"frequentFlyerAirlineDesignator"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Frequent Flyer Airline Designator."}],"title":"frequentFlyerAirlineDesignator","navigatorTitle":[{"text":"frequentFlyerAirlineDesignator","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/airlineNumericCode":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Airline Numeric Code."}],"navigatorTitle":[{"kind":"identifier","text":"airlineNumericCode"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/airlinenumericcode","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"airlineNumericCode"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/airlineNumericCode","title":"airlineNumericCode"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/baggageTagLicensePlateNumbers":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/baggageTagLicensePlateNumbers","navigatorTitle":[{"text":"baggageTagLicensePlateNumbers","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"baggageTagLicensePlateNumbers"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/baggagetaglicenseplatenumbers","title":"baggageTagLicensePlateNumbers","abstract":[{"text":"Baggage Tag License Plate Numbers.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/operatingCarrierPNRCode":{"role":"symbol","kind":"symbol","abstract":[{"text":"Operating Carrier PNR Code.","type":"text"}],"navigatorTitle":[{"text":"operatingCarrierPNRCode","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/operatingcarrierpnrcode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"operatingCarrierPNRCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"title":"operatingCarrierPNRCode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/operatingCarrierPNRCode"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocument"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","title":"SBSDKGenericDocument","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","kind":"symbol","abstract":[{"type":"text","text":"Represents a generic document with fields and sub-documents used for document recognition."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/dateOfBoardingPassIssuanceJulian":{"abstract":[{"text":"Date Of Boarding Pass Issuance Julian.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/dateofboardingpassissuancejulian","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBoardingPassIssuanceJulian"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"dateOfBoardingPassIssuanceJulian","kind":"identifier"}],"title":"dateOfBoardingPassIssuanceJulian","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/dateOfBoardingPassIssuanceJulian"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/flightNumber":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"flightNumber","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"flightNumber","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Flight Number."}],"title":"flightNumber","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/flightNumber","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/flightnumber"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/initWithGenericDocument:":{"role":"symbol","title":"initWithGenericDocument:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/initwithgenericdocument:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithGenericDocument:"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/initWithGenericDocument:","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/passengerDescription":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passengerDescription","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/passengerdescription","title":"passengerDescription","role":"symbol","abstract":[{"type":"text","text":"Passenger Description."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/passengerDescription","navigatorTitle":[{"text":"passengerDescription","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/destinationAirportCode":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/destinationairportcode","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"destinationAirportCode","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"destinationAirportCode","abstract":[{"type":"text","text":"Destination Airport Code."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/destinationAirportCode","navigatorTitle":[{"kind":"identifier","text":"destinationAirportCode"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/compartmentCode":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"compartmentCode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"text":"Compartment Code.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/compartmentCode","title":"compartmentCode","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/compartmentcode","role":"symbol","navigatorTitle":[{"text":"compartmentCode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/documentType":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"title":"documentType","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/documenttype","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Document Type."}],"navigatorTitle":[{"text":"documentType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/documentType","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/operatingCarrierDesignator":{"navigatorTitle":[{"kind":"identifier","text":"operatingCarrierDesignator"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/operatingCarrierDesignator","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"operatingCarrierDesignator"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/operatingcarrierdesignator","title":"operatingCarrierDesignator","abstract":[{"text":"Operating Carrier Designator.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/marketingCarrierDesignator":{"role":"symbol","type":"topic","title":"marketingCarrierDesignator","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/marketingCarrierDesignator","abstract":[{"type":"text","text":"Marketing Carrier Designator."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/marketingcarrierdesignator","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"marketingCarrierDesignator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"marketingCarrierDesignator"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/passengerStatus":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/passengerStatus","title":"passengerStatus","abstract":[{"type":"text","text":"Passenger Status."}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"passengerStatus"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/passengerstatus","type":"topic","navigatorTitle":[{"kind":"identifier","text":"passengerStatus"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/sourceOfBoardingPassIssuance":{"navigatorTitle":[{"text":"sourceOfBoardingPassIssuance","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/sourceofboardingpassissuance","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/sourceOfBoardingPassIssuance","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceOfBoardingPassIssuance"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"kind":"symbol","title":"sourceOfBoardingPassIssuance","abstract":[{"type":"text","text":"Source Of Boarding Pass Issuance."}],"type":"topic"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"SBSDKBarcodeDocumentBoardingPassLeg","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","value":[{"text":"SBSDKBarcodeDocumentBoardingPassLeg","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentBoardingPassLeg"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/airlineDesignatorOfBoardingPassIssuer","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/airlineNumericCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/baggageTagLicensePlateNumbers","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/checkInSequenceNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/compartmentCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/dateOfBoardingPassIssuanceJulian","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/dateOfFlightJulian","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/departureAirportCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/destinationAirportCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/documentFormSerialNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/documentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/fastTrack","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/firstNonConsecutiveBaggageTagLicensePlateNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/flightNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/forIndividualAirlineUse","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/freeBaggageAllowance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/frequentFlyerAirlineDesignator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/frequentFlyerNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/idadIndicator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/internationalDocumentationVerification","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/marketingCarrierDesignator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/operatingCarrierDesignator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/operatingCarrierPNRCode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/passengerDescription","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/passengerStatus","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/seatNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/secondNonConsecutiveBaggageTagLicensePlateNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/selecteeIndicator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/sourceOfBoardingPassIssuance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/sourceOfCheckIn","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/versionNumber"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/initWithGenericDocument:"],"generated":true,"title":"Instance Methods"}]},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"],"kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentBoardingPassLeg","kind":"identifier"},{"kind":"text","text":" : "},{"text":"SBSDKGenericDocumentWrapper","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentWrapper"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1firstNonConsecutiveBaggageTagLicensePlateNumber\/title","value":"firstNonConsecutiveBaggageTagLicensePlateNumber","op":"replace"},{"value":[{"kind":"identifier","text":"firstNonConsecutiveBaggageTagLicensePlateNumber"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1firstNonConsecutiveBaggageTagLicensePlateNumber\/fragments","op":"replace"},{"value":"checkInSequenceNumber","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1checkInSequenceNumber\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1checkInSequenceNumber\/fragments","op":"replace","value":[{"text":"checkInSequenceNumber","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1departureAirportCode\/title","value":"departureAirportCode"},{"value":[{"kind":"identifier","text":"departureAirportCode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1departureAirportCode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg\/title","value":"SBSDKBarcodeDocumentBoardingPassLeg","op":"replace"},{"value":[{"text":"SBSDKBarcodeDocumentBoardingPassLeg","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg\/fragments"},{"op":"replace","value":[{"text":"SBSDKBarcodeDocumentBoardingPassLeg","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1internationalDocumentationVerification\/title","value":"internationalDocumentationVerification"},{"op":"replace","value":[{"kind":"identifier","text":"internationalDocumentationVerification"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1internationalDocumentationVerification\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1requiredDocumentType\/title","value":"requiredDocumentType","op":"replace"},{"value":[{"kind":"identifier","text":"requiredDocumentType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1requiredDocumentType\/fragments","op":"replace"},{"value":"frequentFlyerNumber","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1frequentFlyerNumber\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1frequentFlyerNumber\/fragments","value":[{"kind":"identifier","text":"frequentFlyerNumber"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1sourceOfCheckIn\/title","value":"sourceOfCheckIn","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1sourceOfCheckIn\/fragments","value":[{"text":"sourceOfCheckIn","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1documentFormSerialNumber\/title","op":"replace","value":"documentFormSerialNumber"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1documentFormSerialNumber\/fragments","op":"replace","value":[{"text":"documentFormSerialNumber","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1secondNonConsecutiveBaggageTagLicensePlateNumber\/title","value":"secondNonConsecutiveBaggageTagLicensePlateNumber","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1secondNonConsecutiveBaggageTagLicensePlateNumber\/fragments","value":[{"text":"secondNonConsecutiveBaggageTagLicensePlateNumber","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/title","op":"replace","value":"SBSDKGenericDocumentWrapper"},{"value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"op":"replace"},{"value":"seatNumber","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1seatNumber\/title"},{"value":[{"kind":"identifier","text":"seatNumber"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1seatNumber\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1versionNumber\/title","op":"replace","value":"versionNumber"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1versionNumber\/fragments","value":[{"text":"versionNumber","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1airlineDesignatorOfBoardingPassIssuer\/title","value":"airlineDesignatorOfBoardingPassIssuer","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1airlineDesignatorOfBoardingPassIssuer\/fragments","value":[{"text":"airlineDesignatorOfBoardingPassIssuer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1dateOfFlightJulian\/title","value":"dateOfFlightJulian","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1dateOfFlightJulian\/fragments","value":[{"kind":"identifier","text":"dateOfFlightJulian"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1selecteeIndicator\/title","value":"selecteeIndicator","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1selecteeIndicator\/fragments","value":[{"text":"selecteeIndicator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1forIndividualAirlineUse\/title","value":"forIndividualAirlineUse","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1forIndividualAirlineUse\/fragments","value":[{"text":"forIndividualAirlineUse","kind":"identifier"}]},{"op":"replace","value":"idadIndicator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1idadIndicator\/title"},{"value":[{"text":"idadIndicator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1idadIndicator\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1fastTrack\/title","op":"replace","value":"fastTrack"},{"value":[{"text":"fastTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1fastTrack\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1freeBaggageAllowance\/title","value":"freeBaggageAllowance","op":"replace"},{"value":[{"text":"freeBaggageAllowance","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1freeBaggageAllowance\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1frequentFlyerAirlineDesignator\/title","value":"frequentFlyerAirlineDesignator","op":"replace"},{"value":[{"text":"frequentFlyerAirlineDesignator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1frequentFlyerAirlineDesignator\/fragments","op":"replace"},{"op":"replace","value":"airlineNumericCode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1airlineNumericCode\/title"},{"value":[{"text":"airlineNumericCode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1airlineNumericCode\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1baggageTagLicensePlateNumbers\/title","value":"baggageTagLicensePlateNumbers"},{"value":[{"kind":"identifier","text":"baggageTagLicensePlateNumbers"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1baggageTagLicensePlateNumbers\/fragments"},{"op":"replace","value":"operatingCarrierPNRCode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1operatingCarrierPNRCode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1operatingCarrierPNRCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"operatingCarrierPNRCode"}]},{"value":"SBSDKGenericDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1dateOfBoardingPassIssuanceJulian\/title","value":"dateOfBoardingPassIssuanceJulian"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1dateOfBoardingPassIssuanceJulian\/fragments","value":[{"text":"dateOfBoardingPassIssuanceJulian","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1flightNumber\/title","value":"flightNumber","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1flightNumber\/fragments","value":[{"text":"flightNumber","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1passengerDescription\/title","value":"passengerDescription","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1passengerDescription\/fragments","value":[{"kind":"identifier","text":"passengerDescription"}]},{"value":"destinationAirportCode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1destinationAirportCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1destinationAirportCode\/fragments","value":[{"text":"destinationAirportCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1compartmentCode\/title","value":"compartmentCode","op":"replace"},{"value":[{"kind":"identifier","text":"compartmentCode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1compartmentCode\/fragments"},{"op":"replace","value":"documentType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1documentType\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1documentType\/fragments","value":[{"kind":"identifier","text":"documentType"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1operatingCarrierDesignator\/title","op":"replace","value":"operatingCarrierDesignator"},{"op":"replace","value":[{"text":"operatingCarrierDesignator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1operatingCarrierDesignator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1marketingCarrierDesignator\/title","value":"marketingCarrierDesignator"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1marketingCarrierDesignator\/fragments","op":"replace","value":[{"kind":"identifier","text":"marketingCarrierDesignator"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1passengerStatus\/title","value":"passengerStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1passengerStatus\/fragments","value":[{"text":"passengerStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"sourceOfBoardingPassIssuance","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1sourceOfBoardingPassIssuance\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1sourceOfBoardingPassIssuance\/fragments","value":[{"text":"sourceOfBoardingPassIssuance","kind":"identifier"}]}]}]}