{"metadata":{"symbolKind":"enum","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType"}],"title":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Enumeration","externalID":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerResultCheckDigitType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"MRZ check-digit types."}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/dateOfBirth","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/documentNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/expirationDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/general","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/personalNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/undefined"],"generated":true},{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigitType/personalNumber":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"personalNumber","kind":"identifier"}],"title":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType.personalNumber","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype\/personalnumber","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypePersonalNumber"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/personalNumber","abstract":[{"text":"Personal number validation check-digit.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigitType/expirationDate":{"type":"topic","abstract":[{"type":"text","text":"Document expiration date validation check-digit."}],"role":"symbol","title":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType.expirationDate","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"expirationDate","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeExpirationDate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/expirationDate","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype\/expirationdate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigitType/general":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"general","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeGeneral","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype\/general","type":"topic","title":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType.general","abstract":[{"text":"General document validation check-digit.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/general","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigitType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype\/rawrepresentable-implementations","abstract":[],"kind":"article","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/RawRepresentable-Implementations"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigitType/init(rawValue:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/init(rawValue:)","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype\/init(rawvalue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","title":"init(rawValue:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigitType/documentNumber":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeDocumentNumber"}],"type":"topic","title":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType.documentNumber","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"documentNumber","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Document number validation check-digit.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/documentNumber","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype\/documentnumber"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigitType/undefined":{"role":"symbol","title":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType.undefined","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeUndefined"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"undefined"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype\/undefined","abstract":[{"text":"Undefined.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/undefined"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigitType":{"abstract":[{"type":"text","text":"MRZ check-digit types."}],"type":"topic","title":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigitType/dateOfBirth":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/dateOfBirth","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeDateOfBirth","kind":"identifier"}],"abstract":[{"text":"Date of birth validation check-digit.","type":"text"}],"title":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType.dateOfBirth","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype\/dateofbirth"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigitType/Equatable-Implementations":{"type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/Equatable-Implementations","role":"collectionGroup","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype\/equatable-implementations","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"value":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","value":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/dateOfBirth","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/documentNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/expirationDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/general","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/personalNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/undefined"]}],"op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypePersonalNumber","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType~1personalNumber\/title"},{"value":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypePersonalNumber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType~1personalNumber\/fragments"},{"value":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeExpirationDate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType~1expirationDate\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType~1expirationDate\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeExpirationDate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType~1general\/title","value":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeGeneral"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType~1general\/fragments","op":"replace","value":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeGeneral","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType~1documentNumber\/title","value":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeDocumentNumber","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType~1documentNumber\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeDocumentNumber"}],"op":"replace"},{"value":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeUndefined","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType~1undefined\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType~1undefined\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeUndefined","kind":"identifier"}],"op":"replace"},{"value":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/title"},{"value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType"}]},{"value":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeDateOfBirth","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType~1dateOfBirth\/title"},{"value":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeDateOfBirth","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType~1dateOfBirth\/fragments"}]}]}