{"sections":[],"metadata":{"navigatorTitle":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerViewController","roleHeading":"Class","symbolKind":"class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"title":"SBSDKUITextDataScannerViewController"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller"]}],"abstract":[{"text":"A highly customizable camera-based view controller to recognize and validate a small rectangular text area in realtime.","type":"text"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewControllerDelegate","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s8CopyableP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/s8SendableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring","doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/delegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/isRecognitionEnabled"],"title":"Instance Properties","generated":true},{"generated":true,"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/create(configuration:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/present(on:configuration:delegate:)"]},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/SBSDKGenericTextLineRecognizerViewControllerDelegate-Implementations"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"platforms":["iOS"]}]},{"content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A view finder like rectangle shows the area where text is recognized. The camera is zoomed in and out automatically."},{"type":"text","text":" "},{"type":"text","text":"Once text has been recognized within the view finder area the result is delivered to the receivers delegate."}]}],"kind":"content"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/didHideEnableCameraView":{"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/didhideenablecameraview","navigatorTitle":[{"text":"didHideEnableCameraView","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didHideEnableCameraView"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/didHideEnableCameraView","type":"topic","abstract":[],"title":"didHideEnableCameraView"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","title":"SBSDKUITextDataScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to recognize and validate a small rectangular text area in realtime."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/viewDidLoad":{"abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/viewdidload","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/viewDidLoad","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"title":"viewDidLoad"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/containerForEnableCameraView":{"fragments":[{"kind":"identifier","text":"containerForEnableCameraView"}],"abstract":[],"title":"containerForEnableCameraView","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/containerforenablecameraview","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/containerForEnableCameraView","role":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/SBSDKGenericTextLineRecognizerViewControllerDelegate-Implementations":{"type":"topic","kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/SBSDKGenericTextLineRecognizerViewControllerDelegate-Implementations","role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/sbsdkgenerictextlinerecognizerviewcontrollerdelegate-implementations","title":"SBSDKGenericTextLineRecognizerViewControllerDelegate Implementations","abstract":[]},"doc://net.doo.ScanbotSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://net.doo.ScanbotSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://net.doo.ScanbotSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://net.doo.ScanbotSDK/objc(pl)UIStateRestoring":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/enableCameraTextConfiguration":{"kind":"symbol","fragments":[{"kind":"identifier","text":"enableCameraTextConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/enableCameraTextConfiguration","abstract":[],"type":"topic","title":"enableCameraTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/enablecameratextconfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/create(configuration:delegate:)":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/create(configuration:delegate:)","abstract":[{"text":"Creates a new instance of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/create(configuration:delegate:)","title":"create(configuration:delegate:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerConfiguration","text":"SBSDKUITextDataScannerConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUITextDataScannerViewControllerDelegate","text":"SBSDKUITextDataScannerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"text":"SBSDKUITextDataScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerViewController"}],"navigatorTitle":[{"text":"createWithConfiguration:delegate:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewController"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKGenericTextLineRecognizerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to show a camera screen with the text line recognizer.","type":"text"}],"type":"topic","title":"SBSDKGenericTextLineRecognizerViewController","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontroller","role":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/enableCameraUIConfiguration":{"type":"topic","fragments":[{"text":"enableCameraUIConfiguration","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/enablecamerauiconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/enableCameraUIConfiguration","title":"enableCameraUIConfiguration","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/supportedInterfaceOrientations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/supportedInterfaceOrientations","role":"symbol","title":"supportedInterfaceOrientations","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/supportedinterfaceorientations","kind":"symbol","fragments":[{"kind":"identifier","text":"supportedInterfaceOrientations"}],"type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/updateFlashButton":{"kind":"symbol","title":"updateFlashButton","navigatorTitle":[{"text":"updateFlashButton","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/updateflashbutton","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateFlashButton"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/updateFlashButton","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/delegate":{"type":"topic","title":"delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/delegate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUITextDataScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUITextDataScannerViewControllerDelegate"},{"kind":"text","text":"?"}],"abstract":[{"text":"The receivers delegate.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/delegate"},"doc://net.doo.ScanbotSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s8SendableP","title":"Swift.Sendable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/willShowEnableCameraView":{"role":"symbol","navigatorTitle":[{"text":"willShowEnableCameraView","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"willShowEnableCameraView","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/willshowenablecameraview","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/willShowEnableCameraView","title":"willShowEnableCameraView","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraViewController":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController","kind":"symbol","abstract":[{"type":"text","text":"A "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController"},{"text":" subclass which adds support for enabled and disabled camera permission.","type":"text"}],"role":"symbol","title":"SBSDKUICameraViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUICameraViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller","navigatorTitle":[{"text":"SBSDKUICameraViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerViewControllerDelegate":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewControllerDelegate","abstract":[{"type":"text","text":"The delegation protocol for "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController","isActive":true},{"type":"text","text":"."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewControllerDelegate"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontrollerdelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewControllerDelegate"}],"title":"SBSDKGenericTextLineRecognizerViewControllerDelegate","kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://net.doo.ScanbotSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewController":{"navigatorTitle":[{"text":"SBSDKUIViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIViewController","kind":"identifier"}],"title":"SBSDKUIViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","type":"topic","abstract":[{"type":"text","text":"An abstract base class for RTU-UI view controllers."}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s8CopyableP","title":"Swift.Copyable"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/isRecognitionEnabled":{"abstract":[{"type":"text","text":"Enables or disables the recognition."}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/isRecognitionEnabled","navigatorTitle":[{"text":"isRecognitionEnabled","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isRecognitionEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isRecognitionEnabled","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/isrecognitionenabled"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/present(on:configuration:delegate:)":{"role":"symbol","title":"present(on:configuration:delegate:)","navigatorTitle":[{"kind":"identifier","text":"presentOn:configuration:delegate:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUITextDataScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerConfiguration"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUITextDataScannerViewControllerDelegate","text":"SBSDKUITextDataScannerViewControllerDelegate","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUITextDataScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/present(on:configuration:delegate:)","abstract":[{"type":"text","text":"Creates a new instance of "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","type":"reference"},{"type":"text","text":" and presents it modally."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/present(on:configuration:delegate:)"},"doc://net.doo.ScanbotSDK/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUITextDataScannerViewController"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/containerForEnableCameraView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/delegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/enableCameraTextConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/enableCameraUIConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/isRecognitionEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/supportedInterfaceOrientations"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/didHideEnableCameraView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/updateFlashButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/viewDidLoad","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/willShowEnableCameraView"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/create(configuration:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/present(on:configuration:delegate:)"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/SBSDKGenericTextLineRecognizerViewControllerDelegate-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewControllerDelegate"]}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraViewController","text":"SBSDKUICameraViewController","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/title","value":"SBSDKUITextDataScannerViewController"},{"op":"replace","value":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/fragments"},{"value":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController~1create(configuration:delegate:)\/title","value":"createWithConfiguration:delegate:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController~1create(configuration:delegate:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithConfiguration:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController\/title","value":"SBSDKGenericTextLineRecognizerViewController"},{"value":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController\/navigatorTitle","value":[{"text":"SBSDKGenericTextLineRecognizerViewController","kind":"identifier"}]},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController~1delegate\/title"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController~1delegate\/fragments"},{"op":"replace","value":"SBSDKUICameraViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUICameraViewController"}]},{"op":"replace","value":[{"text":"SBSDKUICameraViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewControllerDelegate\/title","value":"SBSDKGenericTextLineRecognizerViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewControllerDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKGenericTextLineRecognizerViewControllerDelegate","kind":"identifier"}]},{"value":"SBSDKUIViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/navigatorTitle","value":[{"text":"SBSDKUIViewController","kind":"identifier"}]},{"value":"isRecognitionEnabled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController~1isRecognitionEnabled\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController~1isRecognitionEnabled\/fragments","value":[{"kind":"identifier","text":"isRecognitionEnabled"}]},{"value":"presentOn:configuration:delegate:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController~1present(on:configuration:delegate:)\/title","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"presentOn:configuration:delegate:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController~1present(on:configuration:delegate:)\/fragments"}]}]}