{"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultType"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerDateResultType","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultType"}],"roleHeading":"Enumeration","title":"SBSDKMedicalCertificateRecognizerDateResultType","symbolKind":"enum","role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerDateResultType","kind":"identifier"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"type":"text","text":"Type classifiers for dates recognized on medical certificates."}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/birthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/childNeedsCareFrom","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/childNeedsCareUntil","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/diagnosedOn","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/documentDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/incapableOfWorkSince","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/incapableOfWorkUntil","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/undefined"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/RawRepresentable-Implementations"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType/documentDate":{"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/documentDate","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeDocumentDate","kind":"identifier"}],"title":"SBSDKMedicalCertificateRecognizerDateResultType.documentDate","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/documentdate","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"documentDate","kind":"identifier"}],"abstract":[{"type":"text","text":"Document date."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/RawRepresentable-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/rawrepresentable-implementations","role":"collectionGroup","title":"RawRepresentable Implementations","kind":"article","abstract":[],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType/birthDate":{"title":"SBSDKMedicalCertificateRecognizerDateResultType.birthDate","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/birthdate","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeBirthDate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/birthDate","abstract":[{"text":"Patient birth date.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"birthDate","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType/incapableOfWorkSince":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"incapableOfWorkSince","kind":"identifier"}],"abstract":[{"type":"text","text":"The date describes since when the employee is incapable of work."}],"title":"SBSDKMedicalCertificateRecognizerDateResultType.incapableOfWorkSince","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/incapableofworksince","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultTypeIncapableOfWorkSince"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/incapableOfWorkSince","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType/diagnosedOn":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/diagnosedOn","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diagnosedOn","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultTypeDiagnosedOn"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/diagnosedon","abstract":[{"type":"text","text":"The date describes the day of diagnosis."}],"title":"SBSDKMedicalCertificateRecognizerDateResultType.diagnosedOn","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType":{"abstract":[{"type":"text","text":"Type classifiers for dates recognized on medical certificates."}],"title":"SBSDKMedicalCertificateRecognizerDateResultType","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerDateResultType","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultType"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType"},"doc://net.doo.ScanbotSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType/childNeedsCareFrom":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"childNeedsCareFrom","kind":"identifier"}],"abstract":[{"type":"text","text":"The date since when the child needs care."}],"title":"SBSDKMedicalCertificateRecognizerDateResultType.childNeedsCareFrom","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/childneedscarefrom","type":"topic","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeChildNeedsCareFrom","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/childNeedsCareFrom","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType/init(rawValue:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/init(rawvalue:)","abstract":[],"title":"init(rawValue:)","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType/Equatable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/equatable-implementations","abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/Equatable-Implementations","type":"topic","role":"collectionGroup","kind":"article"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType/childNeedsCareUntil":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/childNeedsCareUntil","role":"symbol","abstract":[{"text":"The date until the child needs care.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"childNeedsCareUntil"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/childneedscareuntil","kind":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeChildNeedsCareUntil","kind":"identifier"}],"type":"topic","title":"SBSDKMedicalCertificateRecognizerDateResultType.childNeedsCareUntil"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType/incapableOfWorkUntil":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultTypeIncapableOfWorkUntil"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/incapableOfWorkUntil","role":"symbol","title":"SBSDKMedicalCertificateRecognizerDateResultType.incapableOfWorkUntil","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/incapableofworkuntil","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"incapableOfWorkUntil","kind":"identifier"}],"abstract":[{"text":"The date describes until when the employee is incapable of work.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType/undefined":{"abstract":[{"text":"The date could not be classified.","type":"text"}],"type":"topic","title":"SBSDKMedicalCertificateRecognizerDateResultType.undefined","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/undefined","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"undefined","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/undefined","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultTypeUndefined"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"value":"SBSDKMedicalCertificateRecognizerDateResultType","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateRecognizerDateResultType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKMedicalCertificateRecognizerDateResultType","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/birthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/childNeedsCareFrom","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/childNeedsCareUntil","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/diagnosedOn","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/documentDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/incapableOfWorkSince","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/incapableOfWorkUntil","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/undefined"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"SBSDKMedicalCertificateRecognizerDateResultTypeDocumentDate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1documentDate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1documentDate\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultTypeDocumentDate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1birthDate\/title","value":"SBSDKMedicalCertificateRecognizerDateResultTypeBirthDate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1birthDate\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultTypeBirthDate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1incapableOfWorkSince\/title","value":"SBSDKMedicalCertificateRecognizerDateResultTypeIncapableOfWorkSince"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1incapableOfWorkSince\/fragments","value":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeIncapableOfWorkSince","kind":"identifier"}]},{"op":"replace","value":"SBSDKMedicalCertificateRecognizerDateResultTypeDiagnosedOn","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1diagnosedOn\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultTypeDiagnosedOn"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1diagnosedOn\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType\/title","op":"replace","value":"SBSDKMedicalCertificateRecognizerDateResultType"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificateRecognizerDateResultType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1childNeedsCareFrom\/title","value":"SBSDKMedicalCertificateRecognizerDateResultTypeChildNeedsCareFrom"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1childNeedsCareFrom\/fragments","value":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeChildNeedsCareFrom","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1childNeedsCareUntil\/title","value":"SBSDKMedicalCertificateRecognizerDateResultTypeChildNeedsCareUntil"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1childNeedsCareUntil\/fragments","op":"replace","value":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeChildNeedsCareUntil","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1incapableOfWorkUntil\/title","value":"SBSDKMedicalCertificateRecognizerDateResultTypeIncapableOfWorkUntil"},{"value":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeIncapableOfWorkUntil","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1incapableOfWorkUntil\/fragments"},{"op":"replace","value":"SBSDKMedicalCertificateRecognizerDateResultTypeUndefined","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1undefined\/title"},{"value":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeUndefined","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1undefined\/fragments"}]}]}