{"kind":"symbol","relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"]}],"abstract":[{"text":"Determines the prioritization of still image quality and capturing speed.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2CapturePhotoQualityPrioritization) ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization"},"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/balanced","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/quality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/speed"],"generated":true},{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/init(rawValue:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization"]}],"sections":[],"metadata":{"roleHeading":"Enumeration","title":"SBSDKUI2CapturePhotoQualityPrioritization","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKUI2CapturePhotoQualityPrioritization","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"symbolKind":"enum"},"references":{"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization":{"url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization","title":"SBSDKUI2CapturePhotoQualityPrioritization","navigatorTitle":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Determines the prioritization of still image quality and capturing speed."}]},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization/balanced":{"url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization\/balanced","title":"SBSDKUI2CapturePhotoQualityPrioritization.balanced","navigatorTitle":[{"text":"SBSDKUI2CapturePhotoQualityPrioritizationBalanced","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/balanced","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"balanced"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Balances capturing speed and image quality equally. This is the default value."}]},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization/speed":{"url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization\/speed","title":"SBSDKUI2CapturePhotoQualityPrioritization.speed","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/speed","kind":"symbol","abstract":[{"type":"text","text":"Captures a still image at the highest possible speed. The quality of the image may be degraded."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"speed","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CapturePhotoQualityPrioritizationSpeed","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization/Equatable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization\/equatable-implementations","title":"Equatable Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/Equatable-Implementations","kind":"article","type":"topic","role":"collectionGroup","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization/init(rawValue:)":{"url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization\/init(rawvalue:)","title":"init(rawValue:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/init(rawValue:)","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization/quality":{"url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization\/quality","title":"SBSDKUI2CapturePhotoQualityPrioritization.quality","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/quality","kind":"symbol","abstract":[{"text":"Captures a still image with the best possible quality in terms of noise, frozen motion and detail in low light.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The speed of the capturing might be reduced."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"quality","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CapturePhotoQualityPrioritizationQuality","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization/RawRepresentable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/RawRepresentable-Implementations","kind":"article","type":"topic","role":"collectionGroup","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2CapturePhotoQualityPrioritization"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}]},{"op":"replace","value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/balanced","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/quality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/speed"]}],"path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"SBSDKUI2CapturePhotoQualityPrioritization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/title"},{"value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/fragments"},{"value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/navigatorTitle"},{"value":"SBSDKUI2CapturePhotoQualityPrioritizationBalanced","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization~1balanced\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization~1balanced\/fragments","value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritizationBalanced","kind":"identifier"}]},{"value":"SBSDKUI2CapturePhotoQualityPrioritizationSpeed","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization~1speed\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritizationSpeed"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization~1speed\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization~1quality\/title","value":"SBSDKUI2CapturePhotoQualityPrioritizationQuality"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization~1quality\/fragments","value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritizationQuality","kind":"identifier"}],"op":"replace"}]}]}