{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"SBSDKPDFPagesExtractor","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFPagesExtractor","symbolKind":"class","roleHeading":"Class"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"inlineContent":[{"type":"text","text":"The synchronous functions of this class are running in the same thread that they are called from, so it is up to you to control the concurrency."},{"text":" ","type":"text"},{"text":"The asynchronous functions run in a shared queue to prevent memory pressure when running multiple extractions at the same time.","type":"text"},{"type":"text","text":" "},{"text":"It is recommended to use background queues in most cases.","type":"text"},{"type":"text","text":" "},{"text":"Currently the flattening of the PDF document is user’s responsibility. So if the document will have unflattened annotations (except signs), they will not be exported.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"Class used to extract pages from a PDF file and returns them in various ways."}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/document(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/document(from:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:compression:outputDirectory:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:outputDirectory:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:scaling:compression:encrypter:outputDirectory:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLsAsync(from:scaling:compression:encrypter:outputDirectory:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/images(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/images(from:scaling:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/scannedDocument(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/scannedDocument(from:completion:)"],"title":"Instance Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument":{"title":"SBSDKScannedDocument","kind":"symbol","role":"symbol","abstract":[{"text":"An automatically persisted, thread-safe and observable document-page model for a document with multiple scanned pages.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedDocument"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor/scannedDocument(from:)":{"title":"scannedDocument(from:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Extracts pages from PDF and returns them as "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","isActive":true},{"text":". Each page of the PDF will be a separate ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage","type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Runs in the same thread, as it is called from.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/scannedDocument(from:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/scanneddocument(from:)","navigatorTitle":[{"kind":"identifier","text":"scannedDocumentFromPDF:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scannedDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKScannedDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor/imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)":{"title":"imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)","kind":"symbol","role":"symbol","abstract":[{"text":"Asynchronously extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL.","type":"text"},{"text":" ","type":"text"},{"text":"The array of URLs is passed within the completion handler.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/imageurls(from:scaling:compression:encrypter:outputdirectory:completion:)","navigatorTitle":[{"text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageURLs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"scaling"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"text":", ","kind":"text"},{"text":"compression","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"encrypter"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"outputDirectory"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ([","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor/imageURLsAsync(from:scaling:compression:encrypter:outputDirectory:)":{"title":"imageURLsAsync(from:scaling:compression:encrypter:outputDirectory:)","kind":"symbol","role":"symbol","abstract":[{"text":"Asynchronously extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLsAsync(from:scaling:compression:encrypter:outputDirectory:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/imageurlsasync(from:scaling:compression:encrypter:outputdirectory:)","navigatorTitle":[{"kind":"identifier","text":"imageURLsAsyncFrom:scaling:compression:encrypter:outputDirectory:completionHandler:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageURLsAsync","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"scaling","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"text":"compression","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"outputDirectory"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"]"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor/document(from:completion:)":{"title":"document(from:completion:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Asynchronously extracts pages from PDF and returns them as "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument","isActive":true,"type":"reference"},{"type":"text","text":" in the completion handler."},{"type":"text","text":" "},{"text":"Each page of the PDF will be a separate ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","type":"reference","isActive":true},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Runs in the same thread, as it is called from.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/document(from:completion:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/document(from:completion:)","navigatorTitle":[{"text":"documentFromPDF:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","text":"SBSDKDocument","kind":"typeIdentifier"},{"text":") -> ()) -> ","kind":"text"},{"text":"SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor/imageURLs(from:compression:outputDirectory:)":{"title":"imageURLs(from:compression:outputDirectory:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL. Runs in the same thread that it is called from."},{"text":" ","type":"text"},{"text":"No encryption is used here. Media box scale value is 2.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:compression:outputDirectory:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/imageurls(from:compression:outputdirectory:)","navigatorTitle":[{"kind":"identifier","text":"imageURLsFromPDF:compression:outputDirectory:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageURLs"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"compression","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"outputDirectory","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> ["},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"]"}]},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"title":"SBSDKDocumentPage","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentPage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor/scannedDocument(from:completion:)":{"title":"scannedDocument(from:completion:)","kind":"symbol","role":"symbol","abstract":[{"text":"Asynchronously extracts pages from PDF and returns them as ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","type":"reference","isActive":true},{"text":" in the completion handler.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Each page of the PDF will be a separate "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Runs in the same thread, as it is called from."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/scannedDocument(from:completion:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/scanneddocument(from:completion:)","navigatorTitle":[{"kind":"identifier","text":"scannedDocumentFromPDF:completion:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scannedDocument"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"SBSDKScannedDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument"},{"text":") -> ()) -> ","kind":"text"},{"text":"SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor/imageURLs(from:outputDirectory:)":{"title":"imageURLs(from:outputDirectory:)","kind":"symbol","role":"symbol","abstract":[{"text":"Extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL. Runs in the same thread that it is called from.","type":"text"},{"type":"text","text":" "},{"text":"No encryption is used here. The compression is set to 1.0. Media box scale value is 2.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:outputDirectory:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/imageurls(from:outputdirectory:)","navigatorTitle":[{"text":"imageURLsFromPDF:outputDirectory:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageURLs","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputDirectory"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> ["},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor/images(from:)":{"title":"images(from:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Extracts pages from PDF and converts them to an array of "},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":". Nothing is written to disk during this operation. Runs in the same thread, as it is called from."},{"text":" ","type":"text"},{"type":"text","text":"The scaling of the media box is set to 2."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/images(from:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/images(from:)","navigatorTitle":[{"text":"imagesFromPDF:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"images","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":") -> ["},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"]","kind":"text"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor/document(from:)":{"title":"document(from:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Extracts pages from PDF and returns them as "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument","type":"reference"},{"type":"text","text":". Each page of the PDF will be a separate "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","isActive":true},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"Runs in the same thread, as it is called from."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/document(from:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/document(from:)","navigatorTitle":[{"text":"documentFromPDF:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":") -> ","kind":"text"},{"text":"SBSDKDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocument":{"title":"SBSDKDocument","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A thread-safe, mutable container for scanned pages of type "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","type":"reference","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocument","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocument"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor/images(from:scaling:)":{"title":"images(from:scaling:)","kind":"symbol","role":"symbol","abstract":[{"text":"Extracts pages from PDF and converts them to an array of ","type":"text"},{"type":"codeVoice","code":"UIImage"},{"text":". Nothing is written to disk during this operation. Runs in the same thread, as it is called from.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/images(from:scaling:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/images(from:scaling:)","navigatorTitle":[{"kind":"identifier","text":"imagesFromPDF:scaling:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"images","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scaling"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":") -> ["},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"]","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor/imageURLs(from:scaling:compression:encrypter:outputDirectory:)":{"title":"imageURLs(from:scaling:compression:encrypter:outputDirectory:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL. Runs in the same thread that it is called from."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:scaling:compression:encrypter:outputDirectory:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/imageurls(from:scaling:compression:encrypter:outputdirectory:)","navigatorTitle":[{"text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageURLs","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"scaling"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"compression"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?, "},{"text":"outputDirectory","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> [","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPage"}],"kind":"symbol","abstract":[{"text":"A scanned page (","type":"text"},{"code":"SBSDKScannedPage","type":"codeVoice"},{"type":"text","text":") is a representation of a scanned documents page in digital form."},{"type":"text","text":" "},{"type":"text","text":"Each page consists of an original image of the scan, various editing properties like cropping polygon, rotation and filters, some metadata properties like the document detection status and the document quality analyzer result and a number of processed images in different stages."}],"type":"topic","title":"SBSDKScannedPage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKScannedPage"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor":{"title":"SBSDKPDFPagesExtractor","kind":"symbol","role":"symbol","abstract":[{"text":"Class used to extract pages from a PDF file and returns them in various ways.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor/init":{"title":"init","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/init","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKPDFPagesExtractor"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/document(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/document(from:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:compression:outputDirectory:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:outputDirectory:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:scaling:compression:encrypter:outputDirectory:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLsAsync(from:scaling:compression:encrypter:outputDirectory:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/images(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/images(from:scaling:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/init","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/scannedDocument(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/scannedDocument(from:completion:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKPDFPagesExtractor","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/title","value":"SBSDKScannedDocument","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/fragments","value":[{"text":"SBSDKScannedDocument","kind":"identifier"}]},{"value":"scannedDocumentFromPDF:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1scannedDocument(from:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"scannedDocumentFromPDF:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1scannedDocument(from:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)\/title","value":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)\/fragments"},{"value":"imageURLsAsyncFrom:scaling:compression:encrypter:outputDirectory:completionHandler:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1imageURLsAsync(from:scaling:compression:encrypter:outputDirectory:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1imageURLsAsync(from:scaling:compression:encrypter:outputDirectory:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"imageURLsAsyncFrom:scaling:compression:encrypter:outputDirectory:completionHandler:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"documentFromPDF:completion:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1document(from:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentFromPDF:completion:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1document(from:completion:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:compression:outputDirectory:)\/title","op":"replace","value":"imageURLsFromPDF:compression:outputDirectory:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"imageURLsFromPDF:compression:outputDirectory:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:compression:outputDirectory:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title","value":"SBSDKDocumentPage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"scannedDocumentFromPDF:completion:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1scannedDocument(from:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scannedDocumentFromPDF:completion:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1scannedDocument(from:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:outputDirectory:)\/title","value":"imageURLsFromPDF:outputDirectory:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:outputDirectory:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"imageURLsFromPDF:outputDirectory:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1images(from:)\/title","value":"imagesFromPDF:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"imagesFromPDF:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1images(from:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1document(from:)\/title","value":"documentFromPDF:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1document(from:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"documentFromPDF:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/title","value":"SBSDKDocument"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/fragments","op":"replace","value":[{"text":"SBSDKDocument","kind":"identifier"}]},{"value":"imagesFromPDF:scaling:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1images(from:scaling:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1images(from:scaling:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imagesFromPDF:scaling:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:scaling:compression:encrypter:outputDirectory:)\/title","value":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:scaling:compression:encrypter:outputDirectory:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/title","value":"SBSDKScannedPage"},{"value":[{"text":"SBSDKScannedPage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/fragments"},{"value":"SBSDKPDFPagesExtractor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor\/title"},{"value":[{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}