{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICheckRecognizerViewControllerDelegate"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontrollerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontrollerdelegate"]}],"sections":[],"metadata":{"symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckRecognizerViewControllerDelegate","kind":"identifier"}],"role":"symbol","title":"SBSDKUICheckRecognizerViewControllerDelegate","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUICheckRecognizerViewControllerDelegate","navigatorTitle":[{"text":"SBSDKUICheckRecognizerViewControllerDelegate","kind":"identifier"}],"roleHeading":"Protocol","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewControllerDelegate\/checkRecognizerViewController(_:didRecognizeCheck:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewControllerDelegate\/checkRecognizerViewControllerDidCancel(_:)"]}],"abstract":[{"text":"The delegation protocol for ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewControllerDelegate"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerViewController":{"title":"SBSDKUICheckRecognizerViewController","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckRecognizerViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckRecognizerViewController"}],"abstract":[{"type":"text","text":"A Ready-To-Use viewController to recognize checks using the camera."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerViewControllerDelegate/checkRecognizerViewControllerDidCancel(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontrollerdelegate\/checkrecognizerviewcontrollerdidcancel(_:)","title":"checkRecognizerViewControllerDidCancel(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkRecognizerViewControllerDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerViewController","text":"SBSDKUICheckRecognizerViewController"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewControllerDelegate\/checkRecognizerViewControllerDidCancel(_:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"checkRecognizerViewControllerDidCancel:","kind":"identifier"}],"abstract":[{"type":"text","text":"Informs the delegate that the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController"},{"type":"text","text":" has been cancelled. Optional."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerViewControllerDelegate":{"navigatorTitle":[{"text":"SBSDKUICheckRecognizerViewControllerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckRecognizerViewControllerDelegate","kind":"identifier"}],"abstract":[{"text":"The delegation protocol for ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontrollerdelegate","title":"SBSDKUICheckRecognizerViewControllerDelegate","role":"symbol","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerViewControllerDelegate/checkRecognizerViewController(_:didRecognizeCheck:)":{"title":"checkRecognizerViewController(_:didRecognizeCheck:)","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontrollerdelegate\/checkrecognizerviewcontroller(_:didrecognizecheck:)","navigatorTitle":[{"kind":"identifier","text":"checkRecognizerViewController:didRecognizeCheck:"}],"type":"topic","abstract":[{"type":"text","text":"Informs the delegate that the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController"},{"text":" has recognized a check.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewControllerDelegate\/checkRecognizerViewController(_:didRecognizeCheck:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"checkRecognizerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUICheckRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didRecognizeCheck"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerResult","kind":"typeIdentifier","text":"SBSDKCheckRecognizerResult"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"value":"SBSDKUICheckRecognizerViewControllerDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKUICheckRecognizerViewControllerDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SBSDKUICheckRecognizerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewControllerDelegate\/checkRecognizerViewController(_:didRecognizeCheck:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewControllerDelegate\/checkRecognizerViewControllerDidCancel(_:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICheckRecognizerViewControllerDelegate"}],"languages":["occ"]}]},"op":"replace"},{"value":"SBSDKUICheckRecognizerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUICheckRecognizerViewController"}]},{"value":"checkRecognizerViewControllerDidCancel:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewControllerDelegate~1checkRecognizerViewControllerDidCancel(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"checkRecognizerViewControllerDidCancel:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewControllerDelegate~1checkRecognizerViewControllerDidCancel(_:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewControllerDelegate\/title","value":"SBSDKUICheckRecognizerViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewControllerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUICheckRecognizerViewControllerDelegate"}]},{"value":"checkRecognizerViewController:didRecognizeCheck:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewControllerDelegate~1checkRecognizerViewController(_:didRecognizeCheck:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewControllerDelegate~1checkRecognizerViewController(_:didRecognizeCheck:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"checkRecognizerViewController:didRecognizeCheck:"}]}]}]}