{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Configuration for the behavior of the RTU-UI medical certificates scanner."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerbehaviorconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerbehaviorconfiguration"]}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/captureHighResolutionImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/isFlashEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/isPatientInfoExtracted","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/returnCroppedDocumentImage"],"title":"Instance Properties"}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerBehaviorConfiguration","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration","kind":"identifier"}],"role":"symbol"},"references":{"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerBehaviorConfiguration/captureHighResolutionImage":{"title":"captureHighResolutionImage","abstract":[{"text":"If set to ","type":"text"},{"type":"codeVoice","code":"True"},{"text":" a high-resolution photo of the medical certificate is captured to run the recognition on.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/captureHighResolutionImage","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"captureHighResolutionImage","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerbehaviorconfiguration\/capturehighresolutionimage","navigatorTitle":[{"kind":"identifier","text":"captureHighResolutionImage"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerBehaviorConfiguration/returnCroppedDocumentImage":{"title":"returnCroppedDocumentImage","abstract":[{"type":"text","text":"Determines whether the SDK should return a cropped document image or not."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/returnCroppedDocumentImage","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"returnCroppedDocumentImage","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerbehaviorconfiguration\/returncroppeddocumentimage","navigatorTitle":[{"kind":"identifier","text":"returnCroppedDocumentImage"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerBehaviorConfiguration":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration","kind":"identifier"}],"title":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration for the behavior of the RTU-UI medical certificates scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerbehaviorconfiguration","navigatorTitle":[{"text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerBehaviorConfiguration/init":{"title":"init","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerbehaviorconfiguration\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerBehaviorConfiguration/isPatientInfoExtracted":{"title":"isPatientInfoExtracted","abstract":[{"type":"text","text":"Whether the information of the patient (name, address) are extracted or not."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/isPatientInfoExtracted","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isPatientInfoExtracted","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerbehaviorconfiguration\/ispatientinfoextracted","navigatorTitle":[{"kind":"identifier","text":"isPatientInfoExtracted"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerBehaviorConfiguration/isFlashEnabled":{"title":"isFlashEnabled","abstract":[{"type":"text","text":"Whether flash is toggled on or off."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/isFlashEnabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFlashEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerbehaviorconfiguration\/isflashenabled","navigatorTitle":[{"text":"isFlashEnabled","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration"}]},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/captureHighResolutionImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/isFlashEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/isPatientInfoExtracted","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/returnCroppedDocumentImage"],"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/init"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"captureHighResolutionImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerBehaviorConfiguration~1captureHighResolutionImage\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerBehaviorConfiguration~1captureHighResolutionImage\/fragments","value":[{"kind":"identifier","text":"captureHighResolutionImage"}],"op":"replace"},{"value":"returnCroppedDocumentImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerBehaviorConfiguration~1returnCroppedDocumentImage\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerBehaviorConfiguration~1returnCroppedDocumentImage\/fragments","op":"replace","value":[{"text":"returnCroppedDocumentImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/title","value":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration","kind":"identifier"}]},{"value":"isPatientInfoExtracted","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerBehaviorConfiguration~1isPatientInfoExtracted\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerBehaviorConfiguration~1isPatientInfoExtracted\/fragments","value":[{"text":"isPatientInfoExtracted","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"isFlashEnabled","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerBehaviorConfiguration~1isFlashEnabled\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerBehaviorConfiguration~1isFlashEnabled\/fragments","op":"replace","value":[{"text":"isFlashEnabled","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}