{"variants":[{"paths":["\/documentation\/scanbotsdk\/scanbot"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/scanbot"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot"},"metadata":{"navigatorTitle":[{"text":"Scanbot","kind":"identifier"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Scanbot"}],"role":"symbol","title":"Scanbot","roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)Scanbot"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Scanbot"}]}]}],"abstract":[{"text":"Main class of Scanbot SDK. Lets you install the license and allows basic configuration.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"kind":"symbol","topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/backupImageStoragesEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/isLicenseValid","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/licenseExpirationDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/licenseStatus","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/resourceBundle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/sharedApplication","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/testData"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/applyConfiguration(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultLicenseFailureHandler()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setLicense(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setLicenseFailureHandler(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setLicenseLoggingEnabled(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setLoggingEnabled(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setupDefaultLicenseFailureHandler()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setupDefaultLicenseFailureHandler(completion:)"],"title":"Type Methods"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTestData":{"navigatorTitle":[{"text":"SBSDKTestData","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktestdata","title":"SBSDKTestData","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTestData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKTestData","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A container for test data, e.g. simulated camera mock data.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/defaultLicenseFailureHandler()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultLicenseFailureHandler()","navigatorTitle":[{"kind":"identifier","text":"defaultLicenseFailureHandler"}],"type":"topic","role":"symbol","title":"defaultLicenseFailureHandler()","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultLicenseFailureHandler"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:10ScanbotSDK26SBSDKLicenseFailureHandlera","text":"SBSDKLicenseFailureHandler","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/scanbot\/defaultlicensefailurehandler()","abstract":[{"text":"The default license failure handler.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/setLoggingEnabled(_:)":{"title":"setLoggingEnabled(_:)","url":"\/documentation\/scanbotsdk\/scanbot\/setloggingenabled(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setLoggingEnabled","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setLoggingEnabled(_:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"setLoggingEnabled:","kind":"identifier"}],"abstract":[{"text":"Enables or disables the Scanbot logging. If enabled Scanbot logs various warnings, errors and info to the console.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/resourceBundle":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/resourceBundle","title":"resourceBundle","navigatorTitle":[{"text":"resourceBundle","kind":"identifier"}],"abstract":[{"type":"text","text":"The bundle that ScanbotSDK searches for its additional data bundles."},{"text":" ","type":"text"},{"type":"text","text":"Defaults is "},{"type":"codeVoice","code":"Bundle.main"},{"text":".","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/scanbot\/resourcebundle","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"resourceBundle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/licenseStatus":{"url":"\/documentation\/scanbotsdk\/scanbot\/licensestatus","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"licenseStatus","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKLicenseStatus","text":"SBSDKLicenseStatus","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"licenseStatus","kind":"identifier"}],"title":"licenseStatus","type":"topic","abstract":[{"text":"The current license status.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/licenseStatus","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/setLicense(_:)":{"abstract":[{"text":"Installs the Scanbot SDK license from a string.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/scanbot\/setlicense(_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setLicense","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","navigatorTitle":[{"text":"setLicense:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setLicense(_:)","title":"setLicense(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/isLicenseValid":{"title":"isLicenseValid","url":"\/documentation\/scanbotsdk\/scanbot\/islicensevalid","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isLicenseValid","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/isLicenseValid","type":"topic","role":"symbol","navigatorTitle":[{"text":"isLicenseValid","kind":"identifier"}],"abstract":[{"text":"Checks the active license.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/backupImageStoragesEnabled":{"title":"backupImageStoragesEnabled","url":"\/documentation\/scanbotsdk\/scanbot\/backupimagestoragesenabled","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"backupImageStoragesEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/backupImageStoragesEnabled","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"backupImageStoragesEnabled"}],"abstract":[{"text":"Setting this value to ","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":" will include the default image storages in backups of the app to iCloud or iTunes."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/setupDefaultLicenseFailureHandler()":{"title":"setupDefaultLicenseFailureHandler()","url":"\/documentation\/scanbotsdk\/scanbot\/setupdefaultlicensefailurehandler()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setupDefaultLicenseFailureHandler"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setupDefaultLicenseFailureHandler()","type":"topic","role":"symbol","navigatorTitle":[{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"}],"abstract":[{"type":"text","text":"Sets up the default license failure handler which is being called when the license or trial time expired."},{"text":" ","type":"text"},{"text":"The default handler shows an alert to inform your users about the expired license or trial period.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/setLicenseFailureHandler(_:)":{"title":"setLicenseFailureHandler(_:)","url":"\/documentation\/scanbotsdk\/scanbot\/setlicensefailurehandler(_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLicenseFailureHandler"},{"text":"(","kind":"text"},{"text":"SBSDKLicenseFailureHandler","kind":"typeIdentifier","preciseIdentifier":"s:10ScanbotSDK26SBSDKLicenseFailureHandlera"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setLicenseFailureHandler(_:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setLicenseFailureHandler:"}],"abstract":[{"text":"Sets a closure to handle license failures, such as expiration or invalid licenses.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/sharedApplication":{"title":"sharedApplication","url":"\/documentation\/scanbotsdk\/scanbot\/sharedapplication","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sharedApplication"},{"kind":"text","text":": "},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/sharedApplication","type":"topic","role":"symbol","navigatorTitle":[{"text":"sharedApplication","kind":"identifier"}],"abstract":[{"type":"text","text":"The current UIApplication object set to the Scanbot SDK."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/licenseExpirationDate":{"title":"licenseExpirationDate","url":"\/documentation\/scanbotsdk\/scanbot\/licenseexpirationdate","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"licenseExpirationDate"},{"kind":"text","text":": "},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/licenseExpirationDate","type":"topic","role":"symbol","navigatorTitle":[{"text":"licenseExpirationDate","kind":"identifier"}],"abstract":[{"text":"The expiration date for license.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot":{"title":"Scanbot","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Scanbot"}],"url":"\/documentation\/scanbotsdk\/scanbot","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Scanbot"}],"abstract":[{"type":"text","text":"Main class of Scanbot SDK. Lets you install the license and allows basic configuration."}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/applyConfiguration(_:)":{"title":"applyConfiguration(_:)","url":"\/documentation\/scanbotsdk\/scanbot\/applyconfiguration(_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"applyConfiguration"},{"text":"(","kind":"text"},{"text":"ScanbotSDKConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)ScanbotSDKConfiguration"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/applyConfiguration(_:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"applyConfiguration:"}],"abstract":[{"text":"Applies a configuration to the Scanbot SDK.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/setupDefaultLicenseFailureHandler(completion:)":{"title":"setupDefaultLicenseFailureHandler(completion:)","url":"\/documentation\/scanbotsdk\/scanbot\/setupdefaultlicensefailurehandler(completion:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupDefaultLicenseFailureHandler"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (() -> ())?)","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setupDefaultLicenseFailureHandler(completion:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"setupDefaultLicenseFailureHandlerWithCompletion:","kind":"identifier"}],"abstract":[{"text":"Sets up the default license failure handler which is being called when the license or trial time expired.","type":"text"},{"text":" ","type":"text"},{"text":"The default handler shows an alert to inform your users about the expired license or trial period.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/init":{"title":"init","url":"\/documentation\/scanbotsdk\/scanbot\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/init","type":"topic","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/setLicenseLoggingEnabled(_:)":{"title":"setLicenseLoggingEnabled(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setLicenseLoggingEnabled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/scanbot\/setlicenseloggingenabled(_:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setLicenseLoggingEnabled(_:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"setLicenseLoggingEnabled:","kind":"identifier"}],"abstract":[{"type":"text","text":"Enables or disables the Scanbot SDK license logging."},{"type":"text","text":" "},{"type":"text","text":"If enabled Scanbot SDK logs information about the license to the console."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/testData":{"title":"testData","url":"\/documentation\/scanbotsdk\/scanbot\/testdata","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"testData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKTestData","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTestData"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/testData","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"testData"}],"abstract":[{"text":"Container for data used for testing.","type":"text"},{"text":" ","type":"text"},{"text":"See ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTestData","isActive":true},{"text":" for further information.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"Scanbot","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Scanbot"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"Scanbot","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/init"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/backupImageStoragesEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/isLicenseValid","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/licenseExpirationDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/licenseStatus","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/resourceBundle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/sharedApplication","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/testData"],"title":"Type Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/applyConfiguration(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultLicenseFailureHandler()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setLicense(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setLicenseFailureHandler(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setLicenseLoggingEnabled(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setLoggingEnabled(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setupDefaultLicenseFailureHandler()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setupDefaultLicenseFailureHandler(completion:)"],"title":"Type Methods"}]},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Scanbot"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]}},{"value":"SBSDKTestData","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTestData\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTestData\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKTestData"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1defaultLicenseFailureHandler()\/title","value":"defaultLicenseFailureHandler","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1defaultLicenseFailureHandler()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"defaultLicenseFailureHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1setLoggingEnabled(_:)\/title","value":"setLoggingEnabled:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"setLoggingEnabled:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1setLoggingEnabled(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1resourceBundle\/title","value":"resourceBundle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1resourceBundle\/fragments","value":[{"text":"resourceBundle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1licenseStatus\/title","op":"replace","value":"licenseStatus"},{"value":[{"text":"licenseStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1licenseStatus\/fragments"},{"value":"setLicense:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1setLicense(_:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setLicense:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1setLicense(_:)\/fragments"},{"value":"isLicenseValid","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1isLicenseValid\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1isLicenseValid\/fragments","op":"replace","value":[{"text":"isLicenseValid","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1backupImageStoragesEnabled\/title","op":"replace","value":"backupImageStoragesEnabled"},{"value":[{"text":"backupImageStoragesEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1backupImageStoragesEnabled\/fragments"},{"value":"setupDefaultLicenseFailureHandler","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1setupDefaultLicenseFailureHandler()\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1setupDefaultLicenseFailureHandler()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"}]},{"op":"replace","value":"setLicenseFailureHandler:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1setLicenseFailureHandler(_:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"setLicenseFailureHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1setLicenseFailureHandler(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1sharedApplication\/title","op":"replace","value":"sharedApplication"},{"op":"replace","value":[{"text":"sharedApplication","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1sharedApplication\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1licenseExpirationDate\/title","op":"replace","value":"licenseExpirationDate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1licenseExpirationDate\/fragments","op":"replace","value":[{"kind":"identifier","text":"licenseExpirationDate"}]},{"value":"Scanbot","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/title"},{"value":[{"text":"Scanbot","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1applyConfiguration(_:)\/title","value":"applyConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1applyConfiguration(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"applyConfiguration:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1setupDefaultLicenseFailureHandler(completion:)\/title","value":"setupDefaultLicenseFailureHandlerWithCompletion:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setupDefaultLicenseFailureHandlerWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1setupDefaultLicenseFailureHandler(completion:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1setLicenseLoggingEnabled(_:)\/title","op":"replace","value":"setLicenseLoggingEnabled:"},{"value":[{"text":"+ ","kind":"text"},{"text":"setLicenseLoggingEnabled:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1setLicenseLoggingEnabled(_:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1testData\/title","op":"replace","value":"testData"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1testData\/fragments","value":[{"text":"testData","kind":"identifier"}],"op":"replace"}]}]}