{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/documentDataIntroDefaultImage()","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataIntroDefaultImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKUI2DocumentDataIntroDefaultImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataIntroDefaultImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataIntroDefaultImage"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Type Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorIntroImage(cm)documentDataIntroDefaultImage","navigatorTitle":[{"kind":"identifier","text":"documentDataIntroDefaultImage"}],"title":"documentDataIntroDefaultImage()","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataIntroDefaultImage","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"SBSDKUI2DocumentDataIntroDefaultImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataIntroDefaultImage"}]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage\/documentdataintrodefaultimage()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage\/documentdataintrodefaultimage()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroImage":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorIntroImage"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage","abstract":[{"type":"text","text":"The image for the introduction screen of a document data extractor screen."}],"title":"SBSDKUI2DocumentDataExtractorIntroImage","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentDataExtractorIntroImage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroImage/documentDataIntroDefaultImage()":{"title":"documentDataIntroDefaultImage()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentDataIntroDefaultImage"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentDataIntroDefaultImage","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"SBSDKUI2DocumentDataIntroDefaultImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataIntroDefaultImage"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage\/documentdataintrodefaultimage()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/documentDataIntroDefaultImage()","role":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataIntroDefaultImage":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentDataIntroDefaultImage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataIntroDefaultImage","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2DocumentDataIntroDefaultImage","kind":"identifier"}],"title":"SBSDKUI2DocumentDataIntroDefaultImage","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataintrodefaultimage","abstract":[{"text":"The image for the introduction screen featuring a document.","type":"text"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"documentDataIntroDefaultImage"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"documentDataIntroDefaultImage","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataIntroDefaultImage","text":"SBSDKUI2DocumentDataIntroDefaultImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataIntroDefaultImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"documentDataIntroDefaultImage"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"SBSDKUI2DocumentDataExtractorIntroImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage\/fragments","value":[{"text":"SBSDKUI2DocumentDataExtractorIntroImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorIntroImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage~1documentDataIntroDefaultImage()\/title","op":"replace","value":"documentDataIntroDefaultImage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage~1documentDataIntroDefaultImage()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"documentDataIntroDefaultImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataIntroDefaultImage\/title","value":"SBSDKUI2DocumentDataIntroDefaultImage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataIntroDefaultImage\/fragments","op":"replace","value":[{"text":"SBSDKUI2DocumentDataIntroDefaultImage","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataIntroDefaultImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataIntroDefaultImage\/navigatorTitle"}]}]}