{"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithOverlayColor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"overlayColor","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"metadata":{"title":"initWithOverlayColor:","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PageSnapFunnelAnimation(im)initWithOverlayColor:","symbolKind":"method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithOverlayColor:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithOverlayColor:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFunnelAnimation"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFunnelAnimation\/initWithOverlayColor:"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2pagesnapfunnelanimation\/initwithoverlaycolor:"]}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PageSnapFunnelAnimation":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2pagesnapfunnelanimation","abstract":[{"type":"text","text":"Configuration of the funnel animation."}],"kind":"symbol","role":"symbol","title":"SBSDKUI2PageSnapFunnelAnimation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2PageSnapFunnelAnimation"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PageSnapFunnelAnimation"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFunnelAnimation"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PageSnapFunnelAnimation/initWithOverlayColor:":{"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOverlayColor:"}],"type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFunnelAnimation\/initWithOverlayColor:","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2pagesnapfunnelanimation\/initwithoverlaycolor:","navigatorTitle":[{"kind":"identifier","text":"initWithOverlayColor:"}],"title":"initWithOverlayColor:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2color","title":"SBSDKUI2Color","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2PageSnapFunnelAnimation","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFunnelAnimation\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2PageSnapFunnelAnimation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFunnelAnimation\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2PageSnapFunnelAnimation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFunnelAnimation\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2Color","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle","op":"replace"}]}]}