{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerBehaviorConfiguration\/engineMode","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"engineMode"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentScannerEngineMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentScannerEngineMode"}],"navigatorTitle":[{"kind":"identifier","text":"engineMode"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerBehaviorConfiguration(py)engineMode","symbolKind":"property","platforms":[],"roleHeading":"Instance Property","title":"engineMode","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerBehaviorConfiguration"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}]}],"abstract":[{"type":"text","text":"The mode of the document scanner to be used for document outline detection."}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"engineMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentScannerEngineMode","text":"SBSDKDocumentScannerEngineMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerEngineMode"}]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Defaults to ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerEngineMode\/ml"},{"text":".","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerbehaviorconfiguration\/enginemode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerbehaviorconfiguration\/enginemode"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerEngineMode/ml":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerEngineMode\/ml","abstract":[{"type":"text","text":"Use the ML document scanner."}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerenginemode\/ml","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"ml","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerEngineModeMl"}],"title":"SBSDKDocumentScannerEngineMode.ml"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerBehaviorConfiguration/engineMode":{"navigatorTitle":[{"text":"engineMode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerBehaviorConfiguration\/engineMode","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerbehaviorconfiguration\/enginemode","role":"symbol","deprecated":true,"abstract":[{"type":"text","text":"The mode of the document scanner to be used for document outline detection."}],"kind":"symbol","title":"engineMode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"engineMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKDocumentScannerEngineMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentScannerEngineMode"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerEngineMode":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerenginemode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerEngineMode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerEngineMode","kind":"identifier"}],"type":"topic","title":"SBSDKDocumentScannerEngineMode","navigatorTitle":[{"text":"SBSDKDocumentScannerEngineMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Engines for document scanning."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerBehaviorConfiguration":{"type":"topic","deprecated":true,"title":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerBehaviorConfiguration","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerbehaviorconfiguration","abstract":[{"type":"text","text":"Configuration for the behavior of the document scanning screen."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"engineMode","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"engineMode","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerEngineMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerEngineMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentScannerEngineMode"},{"text":" ","kind":"text"},{"kind":"identifier","text":"engineMode"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerEngineMode~1ml\/title","value":"SBSDKDocumentScannerEngineModeMl","op":"replace"},{"value":[{"text":"SBSDKDocumentScannerEngineModeMl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerEngineMode~1ml\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerBehaviorConfiguration~1engineMode\/title","op":"replace","value":"engineMode"},{"value":[{"text":"engineMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerBehaviorConfiguration~1engineMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerEngineMode\/title","value":"SBSDKDocumentScannerEngineMode"},{"value":[{"text":"SBSDKDocumentScannerEngineMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerEngineMode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerEngineMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentScannerEngineMode","kind":"identifier"}]},{"value":"SBSDKUIDocumentScannerBehaviorConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}]}]}]}