{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TopBarMode\/solid","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2topbarmode\/solid"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2topbarmode\/solid"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TopBarMode"]]},"kind":"symbol","abstract":[{"text":"Display the top bar with a background color or with transparency.","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TopBarModeSolid"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"solid"}],"role":"symbol","title":"SBSDKUI2TopBarMode.solid","symbolKind":"case","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2TopBarMode@SBSDKUI2TopBarModeSolid","roleHeading":"Case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"solid","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2TopBarMode/solid":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"solid","kind":"identifier"}],"title":"SBSDKUI2TopBarMode.solid","abstract":[{"type":"text","text":"Display the top bar with a background color or with transparency."}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2topbarmode\/solid","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TopBarMode\/solid","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2TopBarModeSolid","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2TopBarMode":{"abstract":[{"type":"text","text":"The visual mode used for the top bar."}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2topbarmode","role":"symbol","title":"SBSDKUI2TopBarMode","navigatorTitle":[{"text":"SBSDKUI2TopBarMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TopBarMode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TopBarMode"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKUI2TopBarModeSolid","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2TopBarModeSolid","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKUI2TopBarModeSolid","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TopBarMode~1solid\/title","value":"SBSDKUI2TopBarModeSolid"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TopBarMode~1solid\/fragments","value":[{"text":"SBSDKUI2TopBarModeSolid","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2TopBarMode","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TopBarMode\/title","op":"replace"},{"value":[{"text":"SBSDKUI2TopBarMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TopBarMode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TopBarMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2TopBarMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}