{"abstract":[{"type":"text","text":"CanvasColor color to use when converting images with alpha channel to images without alpha channel."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferImageLoadOptions\/canvasColor"},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBufferImageLoadOptions(py)canvasColor","navigatorTitle":[{"kind":"identifier","text":"canvasColor"}],"title":"canvasColor","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canvasColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCanvasColor","text":"SBSDKCanvasColor","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferImageLoadOptions"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canvasColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCanvasColor","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCanvasColor","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCanvasColor"}]}]},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is WHITE"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbufferimageloadoptions\/canvascolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbufferimageloadoptions\/canvascolor"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCanvasColor":{"type":"topic","title":"SBSDKCanvasColor","abstract":[{"type":"text","text":"Canvas color to use when converting images with alpha channel to images without alpha channel."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCanvasColor"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCanvasColor","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcanvascolor","navigatorTitle":[{"kind":"identifier","text":"SBSDKCanvasColor"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBufferImageLoadOptions":{"type":"topic","abstract":[{"type":"text","text":"Options for loading image from buffer."}],"navigatorTitle":[{"text":"SBSDKBufferImageLoadOptions","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferImageLoadOptions","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBufferImageLoadOptions","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbufferimageloadoptions","kind":"symbol","title":"SBSDKBufferImageLoadOptions"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBufferImageLoadOptions/canvasColor":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbufferimageloadoptions\/canvascolor","type":"topic","title":"canvasColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canvasColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCanvasColor","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCanvasColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"canvasColor","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferImageLoadOptions\/canvasColor","role":"symbol","abstract":[{"text":"CanvasColor color to use when converting images with alpha channel to images without alpha channel.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"canvasColor","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"canvasColor"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCanvasColor","text":"SBSDKCanvasColor","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCanvasColor","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"canvasColor","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCanvasColor\/title","value":"SBSDKCanvasColor","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCanvasColor\/fragments","value":[{"text":"SBSDKCanvasColor","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCanvasColor\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCanvasColor"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferImageLoadOptions\/title","value":"SBSDKBufferImageLoadOptions"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferImageLoadOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBufferImageLoadOptions"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferImageLoadOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBufferImageLoadOptions"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferImageLoadOptions~1canvasColor\/title","op":"replace","value":"canvasColor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferImageLoadOptions~1canvasColor\/fragments","op":"replace","value":[{"text":"canvasColor","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}