{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstName","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/firstname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/firstname"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/firstName","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstName","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","title":"SBSDKMedicalCertificatePatientInfoFieldType.firstName","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificatePatientInfoFieldType@SBSDKMedicalCertificatePatientInfoFieldTypeFirstName","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeFirstName"}],"role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"First name (Vorname des Versicherten).","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType","abstract":[{"text":"Type of a field in the patient info box.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","title":"SBSDKMedicalCertificatePatientInfoFieldType","navigatorTitle":[{"text":"SBSDKMedicalCertificatePatientInfoFieldType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificatePatientInfoFieldType","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/firstName":{"title":"SBSDKMedicalCertificatePatientInfoFieldType.firstName","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKMedicalCertificatePatientInfoFieldTypeFirstName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/firstName","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/firstname","abstract":[{"type":"text","text":"First name (Vorname des Versicherten)."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstName","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalCertificatePatientInfoFieldTypeFirstName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKMedicalCertificatePatientInfoFieldTypeFirstName","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKMedicalCertificatePatientInfoFieldTypeFirstName","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType\/title","value":"SBSDKMedicalCertificatePatientInfoFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType\/fragments","value":[{"text":"SBSDKMedicalCertificatePatientInfoFieldType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificatePatientInfoFieldType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1firstName\/title","value":"SBSDKMedicalCertificatePatientInfoFieldTypeFirstName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1firstName\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeFirstName"}]}]}]}