{"metadata":{"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"SBSDKImageRotationClockwise90","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKImageRotation@SBSDKImageRotationClockwise90","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"clockwise90","kind":"identifier"}],"title":"SBSDKImageRotation.clockwise90","role":"symbol","modules":[{"name":"ScanbotSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation\/clockwise90"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clockwise90"}],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagerotation\/clockwise90"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagerotation\/clockwise90"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation"]]},"abstract":[{"type":"text","text":"A 90 degrees clockwise rotation is applied to the image."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRotation/clockwise90":{"kind":"symbol","abstract":[{"text":"A 90 degrees clockwise rotation is applied to the image.","type":"text"}],"title":"SBSDKImageRotation.clockwise90","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagerotation\/clockwise90","navigatorTitle":[{"text":"SBSDKImageRotationClockwise90","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clockwise90"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation\/clockwise90"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRotation":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKImageRotation","kind":"identifier"}],"title":"SBSDKImageRotation","abstract":[{"text":"An enum describing the rotation of an image.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagerotation","navigatorTitle":[{"text":"SBSDKImageRotation","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"SBSDKImageRotationClockwise90","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"SBSDKImageRotationClockwise90","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKImageRotationClockwise90"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation~1clockwise90\/title","value":"SBSDKImageRotationClockwise90","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation~1clockwise90\/fragments","value":[{"text":"SBSDKImageRotationClockwise90","kind":"identifier"}],"op":"replace"},{"value":"SBSDKImageRotation","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageRotation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/fragments","op":"replace"}]}]}