{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation\/none","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","role":"symbol","title":"SBSDKImageRotation.none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKImageRotation@SBSDKImageRotationNone","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRotationNone"}],"roleHeading":"Case"},"sections":[],"kind":"symbol","abstract":[{"text":"No rotation is applied to the image.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagerotation\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimagerotation\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRotation":{"abstract":[{"type":"text","text":"An enum describing the rotation of an image."}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKImageRotation","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageRotation","kind":"identifier"}],"title":"SBSDKImageRotation","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagerotation"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRotation/none":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"role":"symbol","title":"SBSDKImageRotation.none","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagerotation\/none","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation\/none","abstract":[{"text":"No rotation is applied to the image.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKImageRotationNone","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKImageRotationNone"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKImageRotationNone","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKImageRotationNone"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/title","value":"SBSDKImageRotation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/fragments","value":[{"text":"SBSDKImageRotation","kind":"identifier"}]},{"value":"SBSDKImageRotationNone","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation~1none\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation~1none\/fragments","value":[{"kind":"identifier","text":"SBSDKImageRotationNone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}