{"metadata":{"navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVAVehicleData(im)initWithGenericDocument:","title":"initWithGenericDocument:","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithGenericDocument:","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleData\/initWithGenericDocument:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKGenericDocument","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehicledata\/initwithgenericdocument:"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleData"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleData/initWithGenericDocument:":{"title":"initWithGenericDocument:","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleData\/initWithGenericDocument:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGenericDocument:"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehicledata\/initwithgenericdocument:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithGenericDocument:"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleData":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehicledata","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Vehicle Data. File type “VH”."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleData","title":"SBSDKBarcodeDocumentAAMVAVehicleData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVAVehicleData"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVAVehicleData"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"abstract":[{"text":"Represents a generic document with fields and sub-documents used for document recognition.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocument","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","title":"SBSDKGenericDocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleData\/title","op":"replace","value":"SBSDKBarcodeDocumentAAMVAVehicleData"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleData\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeDocumentAAMVAVehicleData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleData\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeDocumentAAMVAVehicleData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","op":"replace","value":"SBSDKGenericDocument"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","op":"replace","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}]}]}]}