{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewControllerDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Informs the delegate that the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","isActive":true},{"type":"text","text":" has been cancelled and dismissed."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewControllerDelegate\/documentDataExtractorViewControllerDidCancel(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataExtractorViewControllerDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUIDocumentDataExtractorViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","isActive":true},{"type":"text","text":" that did dismiss."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Optional.","type":"text"}]}]}],"metadata":{"navigatorTitle":[{"text":"documentDataExtractorViewControllerDidCancel:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataExtractorViewControllerDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorViewController"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUIDocumentDataExtractorViewControllerDelegate(im)documentDataExtractorViewControllerDidCancel:","title":"documentDataExtractorViewControllerDidCancel(_:)","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontrollerdelegate\/documentdataextractorviewcontrollerdidcancel(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontrollerdelegate\/documentdataextractorviewcontrollerdidcancel(_:)"]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewControllerDelegate":{"abstract":[{"type":"text","text":"The delegate protocol for "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}],"title":"SBSDKUIDocumentDataExtractorViewControllerDelegate","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewControllerDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewControllerDelegate"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontrollerdelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewControllerDelegate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewController":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}],"title":"SBSDKUIDocumentDataExtractorViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to extract generic documents data."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewControllerDelegate/documentDataExtractorViewControllerDidCancel(_:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentDataExtractorViewControllerDidCancel:"}],"abstract":[{"text":"Informs the delegate that the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","isActive":true,"type":"reference"},{"text":" has been cancelled and dismissed.","type":"text"}],"kind":"symbol","title":"documentDataExtractorViewControllerDidCancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDataExtractorViewControllerDidCancel"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorViewController","kind":"typeIdentifier","text":"SBSDKUIDocumentDataExtractorViewController"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewControllerDelegate\/documentDataExtractorViewControllerDidCancel(_:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontrollerdelegate\/documentdataextractorviewcontrollerdidcancel(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"documentDataExtractorViewControllerDidCancel:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentDataExtractorViewControllerDidCancel:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"documentDataExtractorViewControllerDidCancel:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","text":"SBSDKUIDocumentDataExtractorViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","type":"reference"},{"text":" that did dismiss.","type":"text"}],"type":"paragraph"}],"name":"viewController"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SBSDKUIDocumentDataExtractorViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewControllerDelegate\/title"},{"op":"replace","value":[{"text":"SBSDKUIDocumentDataExtractorViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewControllerDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewControllerDelegate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewControllerDelegate\/navigatorTitle"},{"op":"replace","value":"SBSDKUIDocumentDataExtractorViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/title"},{"op":"replace","value":[{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/fragments"},{"op":"replace","value":[{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/navigatorTitle"},{"op":"replace","value":"documentDataExtractorViewControllerDidCancel:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewControllerDelegate~1documentDataExtractorViewControllerDidCancel(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"documentDataExtractorViewControllerDidCancel:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewControllerDelegate~1documentDataExtractorViewControllerDidCancel(_:)\/fragments"}]}]}