{"abstract":[{"text":"Document Form Serial Number","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"documentFormSerialNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"metadata":{"role":"symbol","title":"documentFormSerialNumber","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentFormSerialNumber"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"documentFormSerialNumber","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelBoardingPassLeg(py)documentFormSerialNumber","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelboardingpassleg\/documentformserialnumber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelboardingpassleg\/documentformserialnumber"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelBoardingPassLeg"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelBoardingPassLeg\/documentFormSerialNumber"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelBoardingPassLeg":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelBoardingPassLeg","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelboardingpassleg","type":"topic","title":"SBSDKBarcodeDocumentModelBoardingPassLeg","abstract":[{"text":"Leg of the journey","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentModelBoardingPassLeg","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelBoardingPassLeg","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"title":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","abstract":[{"type":"text","text":"Generic document field."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelBoardingPassLeg/documentFormSerialNumber":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelBoardingPassLeg\/documentFormSerialNumber","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentFormSerialNumber"}],"title":"documentFormSerialNumber","abstract":[{"type":"text","text":"Document Form Serial Number"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelboardingpassleg\/documentformserialnumber","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentFormSerialNumber"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"documentFormSerialNumber"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"documentFormSerialNumber"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField"},{"kind":"text","text":" * "},{"kind":"identifier","text":"documentFormSerialNumber"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKBarcodeDocumentModelBoardingPassLeg","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelBoardingPassLeg\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelBoardingPassLeg"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelBoardingPassLeg\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelBoardingPassLeg\/navigatorTitle","value":[{"text":"SBSDKBarcodeDocumentModelBoardingPassLeg","kind":"identifier"}]},{"value":"SBSDKGenericDocumentField","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelBoardingPassLeg~1documentFormSerialNumber\/title","value":"documentFormSerialNumber"},{"value":[{"kind":"identifier","text":"documentFormSerialNumber"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelBoardingPassLeg~1documentFormSerialNumber\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}