{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration\/initWithUseDocumentDetector:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:processingMode:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithUseDocumentDetector:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:processingMode:"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerConfiguration(im)initWithUseDocumentDetector:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:processingMode:","symbolKind":"method","title":"initWithUseDocumentDetector:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:processingMode:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithUseDocumentDetector:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:processingMode:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithUseDocumentDetector:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"useDocumentDetector"},{"kind":"text","text":" "},{"kind":"identifier","text":"requireExpiryDate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"requireExpiryDate"},{"kind":"text","text":" "},{"kind":"identifier","text":"requireCardholderName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"requireCardholderName"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultAccumulationConfig:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKResultAccumulationConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration","text":"SBSDKResultAccumulationConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"resultAccumulationConfig"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnCreditCardImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"returnCreditCardImage"},{"kind":"text","text":" "},{"kind":"identifier","text":"processingMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKProcessingMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode","text":"SBSDKProcessingMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"processingMode"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscannerconfiguration\/initwithusedocumentdetector:requireexpirydate:requirecardholdername:resultaccumulationconfig:returncreditcardimage:processingmode:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResultAccumulationConfiguration":{"abstract":[{"text":"Configuration for how to accumulate results.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}],"title":"SBSDKResultAccumulationConfiguration","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkresultaccumulationconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerConfiguration":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerconfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCreditCardScannerConfiguration"}],"title":"SBSDKCreditCardScannerConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKCreditCardScannerConfiguration"}],"role":"symbol","abstract":[{"type":"text","text":"Configuration for the credit card scanner."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerConfiguration/initWithUseDocumentDetector:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:processingMode:":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithUseDocumentDetector:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:processingMode:"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration\/initWithUseDocumentDetector:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:processingMode:","kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerconfiguration\/initwithusedocumentdetector:requireexpirydate:requirecardholdername:resultaccumulationconfig:returncreditcardimage:processingmode:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUseDocumentDetector:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:processingMode:"}],"title":"initWithUseDocumentDetector:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:processingMode:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessingMode":{"kind":"symbol","abstract":[{"type":"text","text":"Scanners typically can produce better results from a single image if they are allowed to spend a longer time analyzing it."},{"type":"text","text":" "},{"type":"text","text":"On the other hand, scanners can produce even better results if they can analyze multiple images of the same subject and cross-check and combine the results."},{"type":"text","text":" "},{"type":"text","text":"The processing mode tells the scanner whether to optimize for single or multiple images of a subject."}],"title":"SBSDKProcessingMode","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessingMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkprocessingmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProcessingMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/title","op":"replace","value":"SBSDKResultAccumulationConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/title","op":"replace","value":"SBSDKCreditCardScannerConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCreditCardScannerConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKCreditCardScannerConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/title","op":"replace","value":"SBSDKProcessingMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKProcessingMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKProcessingMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}