{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus"]]},"abstract":[{"text":"Returns an instance of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus","isActive":true,"type":"reference"},{"text":" based on the provided raw value.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus\/enumvalue(from:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus\/enumvalue(from:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"enumValue","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentFieldValidationStatus","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An integer representing the raw value of the"},{"text":" ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus","type":"reference","isActive":true},{"type":"text","text":"."}]}],"name":"rawValue"}],"kind":"parameters"},{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"text":"An instance of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus"},{"type":"text","text":" corresponding to the provided raw value,"},{"text":" ","type":"text"},{"type":"text","text":"or "},{"type":"codeVoice","code":"nil"},{"text":" if no match is found.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enumValue"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"text":"SBSDKGenericDocumentFieldValidationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus"},{"text":"?","kind":"text"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus(cm)enumValueFrom:","title":"enumValue(from:)","symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"enumValueFrom:","kind":"identifier"}],"role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/enumValue(from:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldValidationStatus":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus","kind":"symbol","role":"symbol","title":"SBSDKGenericDocumentFieldValidationStatus","type":"topic","abstract":[{"type":"text","text":"Field validation status."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentFieldValidationStatus","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentFieldValidationStatus","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldValidationStatus/enumValue(from:)":{"abstract":[{"type":"text","text":"Returns an instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus","isActive":true,"type":"reference"},{"text":" based on the provided raw value.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enumValue"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus","text":"SBSDKGenericDocumentFieldValidationStatus","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldvalidationstatus\/enumvalue(from:)","title":"enumValue(from:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus\/enumValue(from:)","kind":"symbol","navigatorTitle":[{"text":"enumValueFrom:","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"enumValueFrom:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"enumValueFrom:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus","kind":"typeIdentifier","text":"SBSDKGenericDocumentFieldValidationStatus","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus"},{"kind":"text","text":" *) "},{"text":"enumValueFrom:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"rawValue","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"rawValue","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An integer representing the raw value of the"},{"text":" ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus","isActive":true},{"text":".","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An instance of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldValidationStatus"},{"text":" corresponding to the provided raw value,","type":"text"},{"text":" ","type":"text"},{"text":"or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no match is found."}]}]},"path":"\/primaryContentSections\/2","op":"replace"},{"op":"replace","value":"SBSDKGenericDocumentFieldValidationStatus","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentFieldValidationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocumentFieldValidationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1enumValue(from:)\/title","value":"enumValueFrom:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldValidationStatus~1enumValue(from:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"enumValueFrom:","kind":"identifier"}]}]}]}