{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult\/averageBrightness","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"averageBrightness"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"the whole image, if no document was detected","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"the document crop, if a document was detected","type":"text"},{"text":" ","type":"text"},{"text":"Ranges from 0 to 255.","type":"text"}],"type":"paragraph"}]}]},{"inlineContent":[{"type":"text","text":"Default is 0"}],"type":"paragraph"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Average brightness, calculated as the average"},{"text":" ","type":"text"},{"text":"of the Value channel in the HSV color space of:","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult\/averagebrightness"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult\/averagebrightness"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult(py)averageBrightness","title":"averageBrightness","navigatorTitle":[{"text":"averageBrightness","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"averageBrightness","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"symbolKind":"property","roleHeading":"Instance Property"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionResult":{"navigatorTitle":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult","type":"topic","abstract":[{"text":"Result of the document contour detection.","type":"text"}],"title":"SBSDKDocumentDetectionResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionResult/averageBrightness":{"abstract":[{"type":"text","text":"Average brightness, calculated as the average"},{"text":" ","type":"text"},{"type":"text","text":"of the Value channel in the HSV color space of:"}],"role":"symbol","navigatorTitle":[{"text":"averageBrightness","kind":"identifier"}],"title":"averageBrightness","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult\/averagebrightness","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult\/averageBrightness","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"averageBrightness"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"averageBrightness","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"averageBrightness"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"text":"averageBrightness","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/title","op":"replace","value":"SBSDKDocumentDetectionResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/navigatorTitle","value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}]},{"value":"averageBrightness","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult~1averageBrightness\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult~1averageBrightness\/fragments","value":[{"text":"averageBrightness","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}