{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"debugDescription"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegment\/debugDescription"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"debugDescription","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegment(py)debugDescription","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"identifier","text":"debugDescription"}],"navigatorTitle":[{"kind":"identifier","text":"debugDescription"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdklinesegment\/debugdescription"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegment"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegment":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdklinesegment","abstract":[{"text":"Helper class that encapsulates a line segment and provides geometric helper methods.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKLineSegment","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegment","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLineSegment","kind":"identifier"}],"title":"SBSDKLineSegment"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegment/debugDescription":{"fragments":[{"kind":"identifier","text":"debugDescription"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegment\/debugDescription","abstract":[],"title":"debugDescription","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklinesegment\/debugdescription"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegment\/title","value":"SBSDKLineSegment"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegment\/fragments","value":[{"kind":"identifier","text":"SBSDKLineSegment"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegment\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKLineSegment"}]}]}]}