{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithText:confidence:roi:"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGlyph(im)initWithText:confidence:roi:","title":"initWithText:confidence:roi:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithText:confidence:roi:","kind":"identifier"}]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGlyph\/initWithText:confidence:roi:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkglyph\/initwithtext:confidence:roi:"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithText:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"text"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidence:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"text":") ","kind":"text"},{"text":"confidence","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"roi:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSValue *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"roi","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGlyph"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGlyph":{"abstract":[{"type":"text","text":"Represents a single glyph, i.e. a character."}],"type":"topic","title":"SBSDKGlyph","url":"\/documentation\/scanbotsdk\/sbsdkglyph","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGlyph","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGlyph"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGlyph"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGlyph/initWithText:confidence:roi:":{"type":"topic","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithText:confidence:roi:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGlyph\/initWithText:confidence:roi:","kind":"symbol","title":"initWithText:confidence:roi:","url":"\/documentation\/scanbotsdk\/sbsdkglyph\/initwithtext:confidence:roi:","role":"symbol","navigatorTitle":[{"text":"initWithText:confidence:roi:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKGlyph","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGlyph\/title"},{"op":"replace","value":[{"text":"SBSDKGlyph","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGlyph\/fragments"},{"op":"replace","value":[{"text":"SBSDKGlyph","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGlyph\/navigatorTitle"}]}]}