{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionIntroScreenDoneButton"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionIntroScreenDoneButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is “Start VIN scanning”"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptionintroscreendonebutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptionintroscreendonebutton"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization"]]},"abstract":[{"type":"text","text":"Accessibility description for the ‘done’\/‘start scanning’ button in the introduction screen."}],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"accessibilityDescriptionIntroScreenDoneButton","role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionIntroScreenDoneButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerScreenTextLocalization(py)accessibilityDescriptionIntroScreenDoneButton","navigatorTitle":[{"kind":"identifier","text":"accessibilityDescriptionIntroScreenDoneButton"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/accessibilityDescriptionIntroScreenDoneButton":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionIntroScreenDoneButton","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionIntroScreenDoneButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptionintroscreendonebutton","navigatorTitle":[{"kind":"identifier","text":"accessibilityDescriptionIntroScreenDoneButton"}],"abstract":[{"type":"text","text":"Accessibility description for the ‘done’\/‘start scanning’ button in the introduction screen."}],"kind":"symbol","title":"accessibilityDescriptionIntroScreenDoneButton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization","navigatorTitle":[{"text":"SBSDKUI2VINScannerScreenTextLocalization","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization","type":"topic","title":"SBSDKUI2VINScannerScreenTextLocalization","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2VINScannerScreenTextLocalization","kind":"identifier"}],"abstract":[{"text":"Configuration of the all strings for generic text scanner screen.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"accessibilityDescriptionIntroScreenDoneButton"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"accessibilityDescriptionIntroScreenDoneButton","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"accessibilityDescriptionIntroScreenDoneButton","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"accessibilityDescriptionIntroScreenDoneButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionIntroScreenDoneButton\/title"},{"op":"replace","value":[{"kind":"identifier","text":"accessibilityDescriptionIntroScreenDoneButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionIntroScreenDoneButton\/fragments"},{"op":"replace","value":"SBSDKUI2VINScannerScreenTextLocalization","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization\/title"},{"op":"replace","value":[{"text":"SBSDKUI2VINScannerScreenTextLocalization","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2VINScannerScreenTextLocalization","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization\/navigatorTitle"}]}]}