{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/ignoressafeareainsets"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/ignoressafeareainsets"]}],"abstract":[{"text":"If set to ","type":"text"},{"type":"codeVoice","code":"False"},{"text":", the finder is inset by the safe area insets. Otherwise the safe area inset is ignored.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"False"},{"text":";","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ignoresSafeAreaInsets","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/ignoresSafeAreaInsets"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration"]]},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration(py)ignoresSafeAreaInsets","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"ignoresSafeAreaInsets","kind":"identifier"}],"title":"ignoresSafeAreaInsets","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ignoresSafeAreaInsets","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration","navigatorTitle":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration","title":"SBSDKBaseScannerViewFinderConfiguration","abstract":[{"type":"text","text":"The view finder configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"type":"text","text":" "},{"type":"text","text":"Sometimes it is necessary to limit a live video frame detection or recognition to a certain rectangular area with"},{"type":"text","text":" "},{"type":"text","text":"a specific aspect ratio: the region or rectangle of interest. This is where a view finder comes in."},{"type":"text","text":" "},{"type":"text","text":"It crops the video frame to that region of interest before passing it to any scanner. Usually"},{"type":"text","text":" "},{"type":"text","text":"the performance of scanners gain a benefit from it because less pixels must be processed."},{"type":"text","text":" "},{"type":"text","text":"Additionally, to guide the user, the view finder visualizes the region of interest by drawing a rectangle around"},{"type":"text","text":" "},{"type":"text","text":"on the user interface."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewFinderConfiguration/ignoresSafeAreaInsets":{"title":"ignoresSafeAreaInsets","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewfinderconfiguration\/ignoressafeareainsets","abstract":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"False"},{"type":"text","text":", the finder is inset by the safe area insets. Otherwise the safe area inset is ignored."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"False"},{"type":"text","text":";"}],"navigatorTitle":[{"kind":"identifier","text":"ignoresSafeAreaInsets"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/ignoresSafeAreaInsets","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignoresSafeAreaInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ignoresSafeAreaInsets","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ignoresSafeAreaInsets","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignoresSafeAreaInsets"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKBaseScannerViewFinderConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/title"},{"value":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1ignoresSafeAreaInsets\/title","value":"ignoresSafeAreaInsets"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1ignoresSafeAreaInsets\/fragments","value":[{"text":"ignoresSafeAreaInsets","kind":"identifier"}]}]}]}