{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomRange\/init","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkzoomrange\/init"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomRange"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKZoomRange(im)init","title":"init"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKZoomRange/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomRange\/init","title":"init","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkzoomrange\/init","role":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKZoomRange":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomRange","navigatorTitle":[{"kind":"identifier","text":"SBSDKZoomRange"}],"title":"SBSDKZoomRange","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKZoomRange","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkzoomrange","role":"symbol","abstract":[{"text":"Helper class to define a range for zooming.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKZoomRange","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomRange\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKZoomRange"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomRange\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKZoomRange"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomRange\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}