{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:polygonstylefor:proposedstyle:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:polygonstylefor:proposedstyle:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Asks the delegate to provide a custom style for a tracked barcodes polygon. Is called when drawing the polygon"},{"type":"text","text":" "},{"type":"text","text":"view for the tracked barcode."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeTrackingOverlay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController"},{"text":", ","kind":"text"},{"text":"polygonStyleFor","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"barcode","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeItem","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem"},{"text":", ","kind":"text"},{"text":"proposedStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewPolygonStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle"},{"text":") -> ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewPolygonStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"controller","content":[{"inlineContent":[{"text":"The barcode tracking overlay controller that the tracked barcode view belongs to.","type":"text"}],"type":"paragraph"}]},{"name":"barcode","content":[{"inlineContent":[{"type":"text","text":"The barcode that should be drawn on the overlay."}],"type":"paragraph"}]},{"name":"proposedStyle","content":[{"inlineContent":[{"text":"The proposed polygon style that will be used by default.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The polygon style to be used when drawing the polygon for the tracked barcode."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:polygonStyleFor:proposedStyle:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeTrackingOverlay","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController","text":"SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"polygonStyleFor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem","text":"SBSDKBarcodeItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"proposedStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle","text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle","text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKBarcodeTrackingOverlayControllerDelegate(im)barcodeTrackingOverlay:polygonStyleFor:proposedStyle:","title":"barcodeTrackingOverlay(_:polygonStyleFor:proposedStyle:)","roleHeading":"Instance Method","navigatorTitle":[{"text":"barcodeTrackingOverlay:polygonStyleFor:proposedStyle:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","required":true},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeItem":{"kind":"symbol","role":"symbol","abstract":[{"text":"A single barcode found in the input image. Barcodes with the same content but different locations in the image are","type":"text"},{"text":" ","type":"text"},{"text":"considered separate barcodes.","type":"text"}],"title":"SBSDKBarcodeItem","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeItem"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeitem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeItem"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayControllerDelegate":{"kind":"symbol","role":"symbol","abstract":[{"text":"The delegation protocol for the barcode tracking overlay controller.","type":"text"}],"title":"SBSDKBarcodeTrackingOverlayControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate","type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayController":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontroller","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}],"abstract":[{"text":"A class that represents an overlay used for visualizing scanned barcodes.","type":"text"},{"text":" ","type":"text"},{"text":"It provides a customizable user interface for displaying barcodes and supports interaction with them.","type":"text"},{"text":" ","type":"text"},{"text":"The overlay can be used to highlight and select barcodes based on user input.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","kind":"symbol","title":"SBSDKBarcodeTrackingOverlayController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayControllerDelegate/barcodeTrackingOverlay(_:polygonStyleFor:proposedStyle:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:polygonStyleFor:proposedStyle:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeTrackingOverlay"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKBarcodeTrackingOverlayController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"polygonStyleFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"proposedStyle"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle"},{"text":") -> ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:polygonstylefor:proposedstyle:)","title":"barcodeTrackingOverlay(_:polygonStyleFor:proposedStyle:)","navigatorTitle":[{"text":"barcodeTrackingOverlay:polygonStyleFor:proposedStyle:","kind":"identifier"}],"abstract":[{"text":"Asks the delegate to provide a custom style for a tracked barcodes polygon. Is called when drawing the polygon","type":"text"},{"text":" ","type":"text"},{"text":"view for the tracked barcode.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewPolygonStyle":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeTrackedViewPolygonStyle"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeTrackedViewPolygonStyle"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle","type":"topic","abstract":[{"text":"A class that represents the style of the polygon rendered around a barcode in ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","type":"reference"},{"text":".","type":"text"}],"kind":"symbol","title":"SBSDKBarcodeTrackedViewPolygonStyle","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"barcodeTrackingOverlay:polygonStyleFor:proposedStyle:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"barcodeTrackingOverlay:polygonStyleFor:proposedStyle:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle"},{"text":" *) ","kind":"text"},{"text":"barcodeTrackingOverlay:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"polygonStyleFor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem","text":"SBSDKBarcodeItem","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem"},{"text":" *) ","kind":"text"},{"text":"barcode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"proposedStyle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle","text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle"},{"text":" *) ","kind":"text"},{"text":"proposedStyle","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The barcode tracking overlay controller that the tracked barcode view belongs to."}],"type":"paragraph"}],"name":"controller"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The barcode that should be drawn on the overlay.","type":"text"}]}],"name":"barcode"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The proposed polygon style that will be used by default."}]}],"name":"proposedStyle"}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The polygon style to be used when drawing the polygon for the tracked barcode."}],"type":"paragraph"}],"kind":"content"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/title","op":"replace","value":"SBSDKBarcodeItem"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/title","op":"replace","value":"SBSDKBarcodeTrackingOverlayControllerDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayControllerDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayControllerDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/title","op":"replace","value":"SBSDKBarcodeTrackingOverlayController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:polygonStyleFor:proposedStyle:)\/title","op":"replace","value":"barcodeTrackingOverlay:polygonStyleFor:proposedStyle:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:polygonStyleFor:proposedStyle:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"barcodeTrackingOverlay:polygonStyleFor:proposedStyle:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle\/title","op":"replace","value":"SBSDKBarcodeTrackedViewPolygonStyle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackedViewPolygonStyle"}]}]}]}