{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"crewMemberCertificate","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType","kind":"typeIdentifier","text":"SBSDKMRZDocumentType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/crewMemberCertificate"},"abstract":[{"text":"Crew member certificate.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType(cpy)crewMemberCertificate","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"crewMemberCertificate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType","kind":"typeIdentifier","text":"SBSDKMRZDocumentType"}],"title":"crewMemberCertificate","navigatorTitle":[{"kind":"identifier","text":"crewMemberCertificate"}],"roleHeading":"Type Property","modules":[{"name":"ScanbotSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype\/crewmembercertificate"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype\/crewmembercertificate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZDocumentType":{"title":"SBSDKMRZDocumentType","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMRZDocumentType"}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType","type":"topic","abstract":[{"type":"text","text":"Type of document containing the MRZ."}],"navigatorTitle":[{"text":"SBSDKMRZDocumentType","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZDocumentType/crewMemberCertificate":{"abstract":[{"type":"text","text":"Crew member certificate."}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"crewMemberCertificate"},{"text":": ","kind":"text"},{"text":"SBSDKMRZDocumentType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType"}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype\/crewmembercertificate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType\/crewMemberCertificate","type":"topic","kind":"symbol","role":"symbol","title":"crewMemberCertificate","navigatorTitle":[{"text":"crewMemberCertificate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"crewMemberCertificate","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"crewMemberCertificate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType","text":"SBSDKMRZDocumentType","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"crewMemberCertificate","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType\/title","op":"replace","value":"SBSDKMRZDocumentType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMRZDocumentType"}]},{"value":[{"text":"SBSDKMRZDocumentType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1crewMemberCertificate\/title","value":"crewMemberCertificate","op":"replace"},{"value":[{"text":"crewMemberCertificate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType~1crewMemberCertificate\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}