{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIConfiguration"]]},"metadata":{"title":"init(cameraConfiguration:)","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cameraConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUICameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICameraConfiguration"},{"text":")","kind":"text"}],"symbolKind":"init","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIConfiguration(im)initWithCameraConfiguration:","navigatorTitle":[{"kind":"identifier","text":"initWithCameraConfiguration:"}],"roleHeading":"Initializer"},"sections":[],"abstract":[{"type":"text","text":"Designated initializer. Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIConfiguration","isActive":true},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"cameraConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICameraConfiguration","text":"SBSDKUICameraConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICameraConfiguration"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"cameraConfiguration","content":[{"type":"paragraph","inlineContent":[{"text":"A configuration for the camera device.","type":"text"}]}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIConfiguration\/init(cameraConfiguration:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuiconfiguration\/init(cameraconfiguration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuiconfiguration\/init(cameraconfiguration:)"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.2.1"}],"type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICameraConfiguration":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUICameraConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUICameraConfiguration","kind":"identifier"}],"title":"SBSDKUICameraConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICameraConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicameraconfiguration","abstract":[{"text":"Configuration for the camera of all RTU-UI components.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIConfiguration":{"abstract":[{"type":"text","text":"The general configuration class for all RTU-UI components."}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIConfiguration","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuiconfiguration","title":"SBSDKUIConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIConfiguration/init(cameraConfiguration:)":{"title":"init(cameraConfiguration:)","abstract":[{"type":"text","text":"Designated initializer. Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIConfiguration","isActive":true,"type":"reference"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuiconfiguration\/init(cameraconfiguration:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"cameraConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUICameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICameraConfiguration"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"text":"initWithCameraConfiguration:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIConfiguration\/init(cameraConfiguration:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"initWithCameraConfiguration:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCameraConfiguration:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithCameraConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUICameraConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICameraConfiguration"},{"kind":"text","text":" *) "},{"text":"cameraConfiguration","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICameraConfiguration\/title","value":"SBSDKUICameraConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICameraConfiguration\/fragments","value":[{"text":"SBSDKUICameraConfiguration","kind":"identifier"}]},{"value":"SBSDKUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKUIConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIConfiguration~1init(cameraConfiguration:)\/title","value":"initWithCameraConfiguration:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIConfiguration~1init(cameraConfiguration:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCameraConfiguration:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}