{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeimagegenerationtype\/capturedimage"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeimagegenerationtype\/capturedimage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeImageGenerationType\/capturedImage","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"capturedImage"}],"languages":["swift"]}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeImageGenerationType@SBSDKBarcodeImageGenerationTypeCapturedImage","title":"SBSDKBarcodeImageGenerationType.capturedImage","navigatorTitle":[{"text":"SBSDKBarcodeImageGenerationTypeCapturedImage","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"capturedImage"}],"symbolKind":"case"},"abstract":[{"type":"text","text":"Generating a barcode image from separately captured frame. Higher resolution, but might have a slight delay."}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeImageGenerationType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeImageGenerationType/capturedImage":{"title":"SBSDKBarcodeImageGenerationType.capturedImage","navigatorTitle":[{"text":"SBSDKBarcodeImageGenerationTypeCapturedImage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeImageGenerationType\/capturedImage","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Generating a barcode image from separately captured frame. Higher resolution, but might have a slight delay."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeimagegenerationtype\/capturedimage","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"capturedImage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeImageGenerationType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeImageGenerationType","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeimagegenerationtype","abstract":[{"text":"The type of the barcode image generation.","type":"text"}],"navigatorTitle":[{"text":"SBSDKBarcodeImageGenerationType","kind":"identifier"}],"role":"symbol","title":"SBSDKBarcodeImageGenerationType","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeImageGenerationType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKBarcodeImageGenerationTypeCapturedImage","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"SBSDKBarcodeImageGenerationTypeCapturedImage","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKBarcodeImageGenerationTypeCapturedImage"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType~1capturedImage\/title","value":"SBSDKBarcodeImageGenerationTypeCapturedImage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType~1capturedImage\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeImageGenerationTypeCapturedImage"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType\/title","value":"SBSDKBarcodeImageGenerationType","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeImageGenerationType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeImageGenerationType"}],"op":"replace"}]}]}