{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"SBSDKBarcodeImageGenerationType.fromVideoFrame","externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeImageGenerationType@SBSDKBarcodeImageGenerationTypeFromVideoFrame","role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"fromVideoFrame","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"SBSDKBarcodeImageGenerationTypeFromVideoFrame","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeImageGenerationType\/fromVideoFrame","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Generating a barcode image from the last video frame. Faster, but has lower resolution."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeImageGenerationType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromVideoFrame"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeimagegenerationtype\/fromvideoframe"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeimagegenerationtype\/fromvideoframe"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeImageGenerationType/fromVideoFrame":{"navigatorTitle":[{"text":"SBSDKBarcodeImageGenerationTypeFromVideoFrame","kind":"identifier"}],"title":"SBSDKBarcodeImageGenerationType.fromVideoFrame","abstract":[{"text":"Generating a barcode image from the last video frame. Faster, but has lower resolution.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeimagegenerationtype\/fromvideoframe","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromVideoFrame"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeImageGenerationType\/fromVideoFrame"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeImageGenerationType":{"title":"SBSDKBarcodeImageGenerationType","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeimagegenerationtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeImageGenerationType"}],"navigatorTitle":[{"text":"SBSDKBarcodeImageGenerationType","kind":"identifier"}],"type":"topic","abstract":[{"text":"The type of the barcode image generation.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeImageGenerationType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodeImageGenerationTypeFromVideoFrame"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeImageGenerationTypeFromVideoFrame"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKBarcodeImageGenerationTypeFromVideoFrame","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType~1fromVideoFrame\/title","op":"replace","value":"SBSDKBarcodeImageGenerationTypeFromVideoFrame"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType~1fromVideoFrame\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeImageGenerationTypeFromVideoFrame","kind":"identifier"}]},{"value":"SBSDKBarcodeImageGenerationType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeImageGenerationType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeImageGenerationType"}]}]}]}