{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeImageGenerationType"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeImageGenerationType\/none"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"No barcode image generation."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKBarcodeImageGenerationTypeNone","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"role":"symbol","title":"SBSDKBarcodeImageGenerationType.none","externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeImageGenerationType@SBSDKBarcodeImageGenerationTypeNone","roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeimagegenerationtype\/none"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeimagegenerationtype\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeImageGenerationType/none":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"navigatorTitle":[{"text":"SBSDKBarcodeImageGenerationTypeNone","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeimagegenerationtype\/none","abstract":[{"type":"text","text":"No barcode image generation."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeImageGenerationType\/none","title":"SBSDKBarcodeImageGenerationType.none"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeImageGenerationType":{"abstract":[{"type":"text","text":"The type of the barcode image generation."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeImageGenerationType","type":"topic","title":"SBSDKBarcodeImageGenerationType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeImageGenerationType","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeImageGenerationType"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeimagegenerationtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKBarcodeImageGenerationTypeNone","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKBarcodeImageGenerationTypeNone","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKBarcodeImageGenerationTypeNone","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType~1none\/title","value":"SBSDKBarcodeImageGenerationTypeNone"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType~1none\/fragments","value":[{"text":"SBSDKBarcodeImageGenerationTypeNone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType\/title","value":"SBSDKBarcodeImageGenerationType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeImageGenerationType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKBarcodeImageGenerationType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeImageGenerationType\/navigatorTitle","op":"replace"}]}]}