{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/viewDidAppear(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController(im)viewDidAppear:","title":"viewDidAppear(_:)","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller\/viewdidappear(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller\/viewdidappear(_:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController/viewDidAppear(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/viewDidAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"title":"viewDidAppear(_:)","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller\/viewdidappear(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}],"abstract":[{"text":"The classic UI view controller that can be used to detect and scan medical certificates. Can be configured to scan on video frames or,","type":"text"},{"text":" ","type":"text"},{"text":"for better accuracy, on high-res photos that are automatically captured.","type":"text"}],"title":"SBSDKMedicalCertificateScannerViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"viewDidAppear:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"viewDidAppear:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"viewDidAppear:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"viewDidAppear:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController~1viewDidAppear(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"viewDidAppear:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController~1viewDidAppear(_:)\/fragments"},{"value":"SBSDKMedicalCertificateScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/fragments"},{"value":[{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/navigatorTitle"}]}]}