{"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Sheet(im)initWithMode:collapsedVisibleHeight:listButton:","symbolKind":"method","title":"initWithMode:collapsedVisibleHeight:listButton:","navigatorTitle":[{"kind":"identifier","text":"initWithMode:collapsedVisibleHeight:listButton:"}],"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMode:collapsedVisibleHeight:listButton:"}],"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sheet\/initWithMode:collapsedVisibleHeight:listButton:"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheet\/initwithmode:collapsedvisibleheight:listbutton:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sheet"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2SheetMode","text":"SBSDKUI2SheetMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetMode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"mode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"collapsedVisibleHeight:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2CollapsedVisibleHeight","text":"SBSDKUI2CollapsedVisibleHeight","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CollapsedVisibleHeight","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"collapsedVisibleHeight","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"listButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BadgedButton","text":"SBSDKUI2BadgedButton","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BadgedButton","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"listButton","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BadgedButton":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BadgedButton","abstract":[{"text":"Configuration of the button with a badge.","type":"text"}],"title":"SBSDKUI2BadgedButton","navigatorTitle":[{"text":"SBSDKUI2BadgedButton","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2badgedbutton","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BadgedButton","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CollapsedVisibleHeight":{"navigatorTitle":[{"text":"SBSDKUI2CollapsedVisibleHeight","kind":"identifier"}],"title":"SBSDKUI2CollapsedVisibleHeight","abstract":[{"text":"Configuration of the barcodes result sheet’s height while collapsed.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CollapsedVisibleHeight","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2collapsedvisibleheight","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CollapsedVisibleHeight","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Sheet/initWithMode:collapsedVisibleHeight:listButton:":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sheet\/initWithMode:collapsedVisibleHeight:listButton:","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheet\/initwithmode:collapsedvisibleheight:listbutton:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMode:collapsedVisibleHeight:listButton:"}],"role":"symbol","title":"initWithMode:collapsedVisibleHeight:listButton:","navigatorTitle":[{"kind":"identifier","text":"initWithMode:collapsedVisibleHeight:listButton:"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Sheet":{"title":"SBSDKUI2Sheet","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheet","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Sheet"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Sheet"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sheet","type":"topic","kind":"symbol","abstract":[{"text":"Configuration of the preview mode for scanning multiple barcodes.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SheetMode":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetMode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SheetMode"}],"type":"topic","abstract":[{"type":"text","text":"Configuration of the barcode result sheet’s default visibility state."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2SheetMode"}],"title":"SBSDKUI2SheetMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheetmode","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2BadgedButton","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BadgedButton\/title","op":"replace"},{"value":[{"text":"SBSDKUI2BadgedButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BadgedButton\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2BadgedButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BadgedButton\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2CollapsedVisibleHeight","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CollapsedVisibleHeight\/title","op":"replace"},{"value":[{"text":"SBSDKUI2CollapsedVisibleHeight","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CollapsedVisibleHeight\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeight"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CollapsedVisibleHeight\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2Sheet","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet\/title","op":"replace"},{"value":[{"text":"SBSDKUI2Sheet","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2Sheet","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2SheetMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2SheetMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetMode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2SheetMode","kind":"identifier"}]}]}]}