{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrengine\/recognize(from:)-32iyb"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngine\/recognize(from:)-32iyb","interfaceLanguage":"swift"},"metadata":{"externalID":"s:10ScanbotSDK14SBSDKOCREngineC9recognize4fromAA14SBSDKOCRResultCAA20SBSDKScannedDocumentC_tYaKF","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"recognize","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","text":"SBSDKScannedDocument","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"SBSDKOCRResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult","kind":"typeIdentifier"}],"title":"recognize(from:)","role":"symbol"},"abstract":[{"type":"text","text":"Asynchronously recognizes characters on all pages of the scanned document and returns the result, or throws an error otherwise."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@nonobjc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"scannedDocument"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","kind":"typeIdentifier","text":"SBSDKScannedDocument"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResult","kind":"typeIdentifier","text":"SBSDKOCRResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult"}],"languages":["swift"]}]},{"parameters":[{"name":"scannedDocument","content":[{"inlineContent":[{"type":"text","text":"The scanned document containing the pages to run the optical character recognition on."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"The OCR result object.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"In Swift language it is used with structured concurrency (async\/await).","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngine"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument":{"url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","title":"SBSDKScannedDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedDocument","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"An automatically persisted, thread-safe and observable document-page model for a document with multiple scanned pages.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngine/recognize(from:)-32iyb":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"SBSDKScannedDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"SBSDKOCRResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"Asynchronously recognizes characters on all pages of the scanned document and returns the result, or throws an error otherwise.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngine\/recognize(from:)-32iyb","url":"\/documentation\/scanbotsdk\/sbsdkocrengine\/recognize(from:)-32iyb","title":"recognize(from:)","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngine":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngine","navigatorTitle":[{"kind":"identifier","text":"SBSDKOCREngine"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrengine","title":"SBSDKOCREngine","abstract":[{"text":"A class to perform optical character recognition (text) on an image (OCR).","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCREngine"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResult","navigatorTitle":[{"text":"SBSDKOCRResult","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrresult","title":"SBSDKOCRResult","abstract":[{"text":"The result of an optical character recognition.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCRResult","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/title","op":"replace","value":"SBSDKScannedDocument"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/fragments","value":[{"kind":"identifier","text":"SBSDKScannedDocument"}]},{"op":"replace","value":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/navigatorTitle"},{"value":"SBSDKOCREngine","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngine\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngine\/fragments","value":[{"text":"SBSDKOCREngine","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngine\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKOCREngine"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResult\/title","op":"replace","value":"SBSDKOCRResult"},{"op":"replace","value":[{"text":"SBSDKOCRResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResult\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResult\/navigatorTitle","value":[{"text":"SBSDKOCRResult","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}