{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2foregroundstyle\/isequal:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ForegroundStyle"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ForegroundStyle(im)isEqual:"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ForegroundStyle\/isEqual:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ForegroundStyle":{"title":"SBSDKUI2ForegroundStyle","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ForegroundStyle","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2foregroundstyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ForegroundStyle","type":"topic","abstract":[{"type":"text","text":"Configuration of the appearance for foreground elements (e.g. text and\/or icons, etc)."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ForegroundStyle"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ForegroundStyle/isEqual:":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2foregroundstyle\/isequal:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ForegroundStyle\/isEqual:","title":"isEqual:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ForegroundStyle\/title","op":"replace","value":"SBSDKUI2ForegroundStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ForegroundStyle\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ForegroundStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ForegroundStyle\/navigatorTitle","value":[{"text":"SBSDKUI2ForegroundStyle","kind":"identifier"}]}]}]}