{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)Scanbot(cm)applyConfiguration:","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"applyConfiguration"},{"text":"(","kind":"text"},{"text":"ScanbotSDKConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)ScanbotSDKConfiguration"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Type Method","role":"symbol","symbolKind":"method","title":"applyConfiguration(_:)","navigatorTitle":[{"kind":"identifier","text":"applyConfiguration:"}],"modules":[{"name":"ScanbotSDK"}]},"abstract":[{"text":"Applies a configuration to the Scanbot SDK.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)ScanbotSDKConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotSDKConfiguration","text":"ScanbotSDKConfiguration"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"ScanbotSDKConfiguration"},{"type":"text","text":" instance containing the desired configuration settings."}]}]}]},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A Boolean value indicating whether the configuration was successfully applied.","type":"text"},{"type":"text","text":" "},{"text":"If the license is valid after applying the configuration, it returns ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":". Otherwise, it returns "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/scanbot\/applyconfiguration(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/scanbot\/applyconfiguration(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/applyConfiguration(_:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/applyConfiguration(_:)":{"type":"topic","url":"\/documentation\/scanbotsdk\/scanbot\/applyconfiguration(_:)","title":"applyConfiguration(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/applyConfiguration(_:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"applyConfiguration"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)ScanbotSDKConfiguration","text":"ScanbotSDKConfiguration"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Applies a configuration to the Scanbot SDK."}],"navigatorTitle":[{"text":"applyConfiguration:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot":{"title":"Scanbot","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot","abstract":[{"type":"text","text":"Main class of Scanbot SDK. Lets you install the license and allows basic configuration."}],"navigatorTitle":[{"text":"Scanbot","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Scanbot"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/scanbot"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/ScanbotSDKConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ScanbotSDKConfiguration"}],"abstract":[{"code":"ScanbotSDKConfiguration","type":"codeVoice"},{"text":" is a configuration class that allows you to customize various settings and behavior of the Scanbot SDK.","type":"text"}],"url":"\/documentation\/scanbotsdk\/scanbotsdkconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotSDKConfiguration","kind":"symbol","role":"symbol","title":"ScanbotSDKConfiguration","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","value":"applyConfiguration:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"applyConfiguration:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"applyConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)ScanbotSDKConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotSDKConfiguration","text":"ScanbotSDKConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"code":"ScanbotSDKConfiguration","type":"codeVoice"},{"type":"text","text":" instance containing the desired configuration settings."}]}],"name":"configuration"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"A Boolean value indicating whether the configuration was successfully applied."},{"type":"text","text":" "},{"text":"If the license is valid after applying the configuration, it returns ","type":"text"},{"type":"codeVoice","code":"true"},{"text":". Otherwise, it returns ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"type":"paragraph"}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1applyConfiguration(_:)\/title","value":"applyConfiguration:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"applyConfiguration:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1applyConfiguration(_:)\/fragments"},{"op":"replace","value":"Scanbot","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/title"},{"value":[{"kind":"identifier","text":"Scanbot"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/fragments"},{"value":[{"kind":"identifier","text":"Scanbot"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/navigatorTitle"},{"op":"replace","value":"ScanbotSDKConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotSDKConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotSDKConfiguration\/fragments","op":"replace","value":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}]},{"op":"replace","value":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotSDKConfiguration\/navigatorTitle"}]}]}