{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MultipleScanningMode(py)sheet","navigatorTitle":[{"text":"sheet","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sheet","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Sheet","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"sheet"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode"]]},"abstract":[{"text":"Configuration of the preview mode for scanning multiple barcodes.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sheet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet","text":"SBSDKUI2Sheet"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/sheet","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/sheet"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/sheet"]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/sheet":{"title":"sheet","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sheet","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Sheet","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"sheet","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/sheet","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Configuration of the preview mode for scanning multiple barcodes."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/sheet"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}],"abstract":[{"text":"Configuration of the mode for scanning multiple barcodes.","type":"text"}],"title":"SBSDKUI2MultipleScanningMode","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sheet":{"url":"\/documentation\/scanbotsdk\/sbsdkui2sheet","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Sheet"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Configuration of the preview mode for scanning multiple barcodes."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Sheet"}],"type":"topic","title":"SBSDKUI2Sheet"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"sheet"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sheet"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKUI2Sheet","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"sheet","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1sheet\/title","value":"sheet"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1sheet\/fragments","value":[{"kind":"identifier","text":"sheet"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/title","value":"SBSDKUI2MultipleScanningMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MultipleScanningMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2MultipleScanningMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/title","value":"SBSDKUI2Sheet"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Sheet"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Sheet"}]}]}]}