{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDialogButtonStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogButtonStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogButtonStyle","text":"SBSDKUIDialogButtonStyle","kind":"typeIdentifier"}],"languages":["swift"]}]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"errorDialogButtonStyle","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","title":"errorDialogButtonStyle","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerUIConfiguration(py)errorDialogButtonStyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDialogButtonStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUIDialogButtonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogButtonStyle"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerUIConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerUIConfiguration\/errorDialogButtonStyle"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"The style of the dialogs\/alerts OK button in case of error.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscanneruiconfiguration\/errordialogbuttonstyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscanneruiconfiguration\/errordialogbuttonstyle"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerUIConfiguration":{"abstract":[{"text":"Configuration for the user interface of the RTU-UI check scanner.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckscanneruiconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerUIConfiguration","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckScannerUIConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICheckScannerUIConfiguration"}],"title":"SBSDKUICheckScannerUIConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDialogButtonStyle":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogButtonStyle","url":"\/documentation\/scanbotsdk\/sbsdkuidialogbuttonstyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIDialogButtonStyle","kind":"identifier"}],"kind":"symbol","title":"SBSDKUIDialogButtonStyle","navigatorTitle":[{"text":"SBSDKUIDialogButtonStyle","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The general style for an action button in a ScanbotSDK alert. Used to customize certain result alerts in SBSDKUI components."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerUIConfiguration/errorDialogButtonStyle":{"abstract":[{"text":"The style of the dialogs\/alerts OK button in case of error.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerUIConfiguration\/errorDialogButtonStyle","kind":"symbol","type":"topic","title":"errorDialogButtonStyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDialogButtonStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUIDialogButtonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogButtonStyle"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckscanneruiconfiguration\/errordialogbuttonstyle","role":"symbol","navigatorTitle":[{"text":"errorDialogButtonStyle","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"errorDialogButtonStyle","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"errorDialogButtonStyle","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKUIDialogButtonStyle","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogButtonStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogButtonStyle"},{"text":" * ","kind":"text"},{"text":"errorDialogButtonStyle","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUICheckScannerUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUICheckScannerUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration\/navigatorTitle","value":[{"text":"SBSDKUICheckScannerUIConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogButtonStyle\/title","value":"SBSDKUIDialogButtonStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogButtonStyle\/fragments","value":[{"kind":"identifier","text":"SBSDKUIDialogButtonStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogButtonStyle\/navigatorTitle","value":[{"text":"SBSDKUIDialogButtonStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration~1errorDialogButtonStyle\/title","value":"errorDialogButtonStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration~1errorDialogButtonStyle\/fragments","value":[{"kind":"identifier","text":"errorDialogButtonStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}