{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscanneruiconfiguration\/topbarbackgroundcolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscanneruiconfiguration\/topbarbackgroundcolor"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerUIConfiguration"]]},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"topBarBackgroundColor","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerUIConfiguration(py)topBarBackgroundColor","role":"symbol","title":"topBarBackgroundColor","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"ScanbotSDK"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerUIConfiguration\/topBarBackgroundColor"},"kind":"symbol","abstract":[{"text":"Background color of the top bar.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerUIConfiguration/topBarBackgroundColor":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckscanneruiconfiguration\/topbarbackgroundcolor","abstract":[{"text":"Background color of the top bar.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerUIConfiguration\/topBarBackgroundColor","type":"topic","title":"topBarBackgroundColor","navigatorTitle":[{"text":"topBarBackgroundColor","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerUIConfiguration":{"abstract":[{"text":"Configuration for the user interface of the RTU-UI check scanner.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckscanneruiconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerUIConfiguration","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckScannerUIConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICheckScannerUIConfiguration"}],"title":"SBSDKUICheckScannerUIConfiguration","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"topBarBackgroundColor"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"topBarBackgroundColor","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"topBarBackgroundColor"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration~1topBarBackgroundColor\/title","op":"replace","value":"topBarBackgroundColor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration~1topBarBackgroundColor\/fragments","op":"replace","value":[{"kind":"identifier","text":"topBarBackgroundColor"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration\/title","op":"replace","value":"SBSDKUICheckScannerUIConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUICheckScannerUIConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUICheckScannerUIConfiguration","kind":"identifier"}]}]}]}