{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"hash","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZFinderLayoutPreset(py)hash","title":"hash","fragments":[{"text":"hash","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/hash","interfaceLanguage":"occ"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/hash"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2MRZFinderLayoutPreset","kind":"identifier"}],"abstract":[{"text":"Source of the text for the MRZ finder example overlay.","type":"text"}],"role":"symbol","title":"SBSDKUI2MRZFinderLayoutPreset","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MRZFinderLayoutPreset","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset/hash":{"type":"topic","role":"symbol","abstract":[],"title":"hash","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/hash","fragments":[{"text":"hash","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2MRZFinderLayoutPreset","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/title","op":"replace"},{"value":[{"text":"SBSDKUI2MRZFinderLayoutPreset","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/navigatorTitle","op":"replace"}]}]}