{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureHighResolutionImage"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"captureHighResolutionImage"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController(py)captureHighResolutionImage","role":"symbol","title":"captureHighResolutionImage"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller\/capturehighresolutionimage"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller\/capturehighresolutionimage"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureHighResolutionImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"True"},{"type":"text","text":"."}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController\/captureHighResolutionImage"},"abstract":[{"text":"If set to ","type":"text"},{"code":"True","type":"codeVoice"},{"type":"text","text":" a high-resolution photo of the check is captured to run the recognition on."},{"type":"text","text":" "},{"type":"text","text":"Upon successful recognition the recognition result also contains a high-resolution image of the check."},{"text":" ","type":"text"},{"type":"text","text":"If set to "},{"code":"False","type":"codeVoice"},{"type":"text","text":", the video frames will be used for recognition and result image delivery."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerViewController"}],"abstract":[{"type":"text","text":"Classic UI view controller that can be used to detect and recognize bank checks."}],"title":"SBSDKCheckRecognizerViewController","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckRecognizerViewController","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewController/captureHighResolutionImage":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller\/capturehighresolutionimage","title":"captureHighResolutionImage","type":"topic","kind":"symbol","navigatorTitle":[{"text":"captureHighResolutionImage","kind":"identifier"}],"role":"symbol","abstract":[{"text":"If set to ","type":"text"},{"type":"codeVoice","code":"True"},{"text":" a high-resolution photo of the check is captured to run the recognition on.","type":"text"},{"type":"text","text":" "},{"text":"Upon successful recognition the recognition result also contains a high-resolution image of the check.","type":"text"},{"text":" ","type":"text"},{"text":"If set to ","type":"text"},{"code":"False","type":"codeVoice"},{"text":", the video frames will be used for recognition and result image delivery.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController\/captureHighResolutionImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"captureHighResolutionImage","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"captureHighResolutionImage","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"captureHighResolutionImage","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureHighResolutionImage"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/title","value":"SBSDKCheckRecognizerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/fragments","value":[{"text":"SBSDKCheckRecognizerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController~1captureHighResolutionImage\/title","op":"replace","value":"captureHighResolutionImage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController~1captureHighResolutionImage\/fragments","value":[{"text":"captureHighResolutionImage","kind":"identifier"}]}]}]}