{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController\/delegate"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKCheckRecognizerViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate","text":"SBSDKCheckRecognizerViewControllerDelegate"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"The delegate of the receiver.","type":"text"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"role":"symbol","symbolKind":"property","title":"delegate","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController(py)delegate","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCheckRecognizerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKCheckRecognizerViewControllerDelegate"},{"text":"?","kind":"text"}]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewController/delegate":{"title":"delegate","role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKCheckRecognizerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKCheckRecognizerViewControllerDelegate"},{"kind":"text","text":"?"}],"abstract":[{"text":"The delegate of the receiver.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController\/delegate","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller\/delegate","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewControllerDelegate":{"type":"topic","title":"SBSDKCheckRecognizerViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate","role":"symbol","abstract":[{"text":"The delegation protocol for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","type":"reference","isActive":true},{"text":" class.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerViewControllerDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckRecognizerViewControllerDelegate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewController":{"role":"symbol","title":"SBSDKCheckRecognizerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerViewController"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckRecognizerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller","type":"topic","abstract":[{"text":"Classic UI view controller that can be used to detect and recognize bank checks.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKCheckRecognizerViewControllerDelegate","text":"id<SBSDKCheckRecognizerViewControllerDelegate>","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"delegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController~1delegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}],"op":"replace"},{"op":"replace","value":"SBSDKCheckRecognizerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate\/title"},{"value":[{"text":"SBSDKCheckRecognizerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/title","value":"SBSDKCheckRecognizerViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/fragments","value":[{"text":"SBSDKCheckRecognizerViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}