{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller\/ignoreinvalidresults"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller\/ignoreinvalidresults"]}],"metadata":{"navigatorTitle":[{"text":"ignoreInvalidResults","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController(py)ignoreInvalidResults","roleHeading":"Instance Property","symbolKind":"property","title":"ignoreInvalidResults","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ignoreInvalidResults","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController\/ignoreInvalidResults","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ignoreInvalidResults"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"True"},{"type":"text","text":"."}],"type":"paragraph"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"True"},{"text":", check recognition results that failed their validation will not be provided to the delegate.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Set to "},{"type":"codeVoice","code":"False"},{"type":"text","text":", if you are interested also in invalid results."}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewController":{"title":"SBSDKCheckRecognizerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","kind":"symbol","abstract":[{"type":"text","text":"Classic UI view controller that can be used to detect and recognize bank checks."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKCheckRecognizerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckRecognizerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewController/ignoreInvalidResults":{"abstract":[{"text":"If set to ","type":"text"},{"code":"True","type":"codeVoice"},{"type":"text","text":", check recognition results that failed their validation will not be provided to the delegate."},{"text":" ","type":"text"},{"type":"text","text":"Set to "},{"code":"False","type":"codeVoice"},{"type":"text","text":", if you are interested also in invalid results."}],"navigatorTitle":[{"text":"ignoreInvalidResults","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller\/ignoreinvalidresults","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController\/ignoreInvalidResults","type":"topic","kind":"symbol","title":"ignoreInvalidResults","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ignoreInvalidResults","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ignoreInvalidResults","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ignoreInvalidResults","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"ignoreInvalidResults","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"SBSDKCheckRecognizerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckRecognizerViewController"}],"op":"replace"},{"op":"replace","value":"ignoreInvalidResults","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController~1ignoreInvalidResults\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController~1ignoreInvalidResults\/fragments","op":"replace","value":[{"text":"ignoreInvalidResults","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}