{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController\/init(parentViewController:parentView:delegate:)"},"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController(im)initWithParentViewController:parentView:delegate:","symbolKind":"init","roleHeading":"Initializer","title":"init(parentViewController:parentView:delegate:)","navigatorTitle":[{"kind":"identifier","text":"initWithParentViewController:parentView:delegate:"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"parentViewController","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"text":"parentView","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKCheckRecognizerViewControllerDelegate","text":"SBSDKCheckRecognizerViewControllerDelegate"},{"kind":"text","text":"?)"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller\/init(parentviewcontroller:parentview:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller\/init(parentviewcontroller:parentview:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController"]]},"sections":[],"kind":"symbol","abstract":[{"text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"text":"parentViewController","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"parentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate","kind":"typeIdentifier","text":"SBSDKCheckRecognizerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKCheckRecognizerViewControllerDelegate"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"parentViewController","content":[{"inlineContent":[{"text":"The view controller the newly created instance is embedded into.","type":"text"}],"type":"paragraph"}]},{"name":"parentView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view the newly created instance is embedded into."}]}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate of the receiver.","type":"text"}]}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewController":{"role":"symbol","title":"SBSDKCheckRecognizerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerViewController"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckRecognizerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller","type":"topic","abstract":[{"text":"Classic UI view controller that can be used to detect and recognize bank checks.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewControllerDelegate":{"type":"topic","title":"SBSDKCheckRecognizerViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewControllerDelegate","role":"symbol","abstract":[{"text":"The delegation protocol for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController","type":"reference","isActive":true},{"text":" class.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerViewControllerDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckRecognizerViewControllerDelegate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerViewController/init(parentViewController:parentView:delegate:)":{"role":"symbol","abstract":[{"type":"text","text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area."}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"parentViewController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"text":"parentView","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"text":"SBSDKCheckRecognizerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKCheckRecognizerViewControllerDelegate"},{"text":"?)","kind":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"initWithParentViewController:parentView:delegate:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerviewcontroller\/init(parentviewcontroller:parentview:delegate:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerViewController\/init(parentViewController:parentView:delegate:)","title":"init(parentViewController:parentView:delegate:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithParentViewController:parentView:delegate:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithParentViewController:parentView:delegate:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithParentViewController:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"parentViewController"},{"kind":"text","text":" "},{"text":"parentView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"parentView","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"text":"(","kind":"text"},{"text":"id<SBSDKCheckRecognizerViewControllerDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKCheckRecognizerViewControllerDelegate"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"delegate"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/title","value":"SBSDKCheckRecognizerViewController","op":"replace"},{"value":[{"text":"SBSDKCheckRecognizerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate\/title","op":"replace","value":"SBSDKCheckRecognizerViewControllerDelegate"},{"value":[{"text":"SBSDKCheckRecognizerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewControllerDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController~1init(parentViewController:parentView:delegate:)\/title","value":"initWithParentViewController:parentView:delegate:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerViewController~1init(parentViewController:parentView:delegate:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithParentViewController:parentView:delegate:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}