{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"kind":"symbol","metadata":{"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2NavigationBarMode","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"SBSDKUI2NavigationBarMode","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2NavigationBarMode","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2NavigationBarMode"}]},"sections":[],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"kind":"relationships"}],"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode\/dark","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode\/hidden","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode\/light"],"generated":true},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode\/init(rawValue:)"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode\/RawRepresentable-Implementations"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"The visual mode used for the navigation bar icons. Android only.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKUI2NavigationBarMode) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2NavigationBarMode"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2navigationbarmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2navigationbarmode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2NavigationBarMode/RawRepresentable-Implementations":{"kind":"article","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2navigationbarmode\/rawrepresentable-implementations","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2NavigationBarMode":{"abstract":[{"type":"text","text":"The visual mode used for the navigation bar icons. Android only."}],"kind":"symbol","type":"topic","title":"SBSDKUI2NavigationBarMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2navigationbarmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2NavigationBarMode"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2NavigationBarMode"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2NavigationBarMode/hidden":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2navigationbarmode\/hidden","type":"topic","abstract":[{"type":"text","text":"Hide the navigation bar."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2NavigationBarModeHidden","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode\/hidden","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hidden","kind":"identifier"}],"title":"SBSDKUI2NavigationBarMode.hidden"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2NavigationBarMode/dark":{"title":"SBSDKUI2NavigationBarMode.dark","abstract":[{"type":"text","text":"Display all icons in the navigation bar in black."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"dark","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2navigationbarmode\/dark","type":"topic","navigatorTitle":[{"text":"SBSDKUI2NavigationBarModeDark","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode\/dark","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/s12CaseIterableP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s12CaseIterableP","title":"Swift.CaseIterable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2NavigationBarMode/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2navigationbarmode\/equatable-implementations","role":"collectionGroup","kind":"article","type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode\/Equatable-Implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2NavigationBarMode/light":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"light"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode\/light","abstract":[{"text":"Display all icons in the navigation bar in white.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2NavigationBarModeLight"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2navigationbarmode\/light","title":"SBSDKUI2NavigationBarMode.light"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2NavigationBarMode/init(rawValue:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode\/init(rawValue:)","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2navigationbarmode\/init(rawvalue:)","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUI2NavigationBarMode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2NavigationBarMode"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2NavigationBarMode","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode\/dark","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode\/hidden","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode\/light"],"anchor":"Enumeration-Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2NavigationBarMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2NavigationBarMode\/title","op":"replace","value":"SBSDKUI2NavigationBarMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2NavigationBarMode\/fragments","op":"replace","value":[{"text":"SBSDKUI2NavigationBarMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2NavigationBarMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2NavigationBarMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2NavigationBarMode~1hidden\/title","op":"replace","value":"SBSDKUI2NavigationBarModeHidden"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2NavigationBarMode~1hidden\/fragments","op":"replace","value":[{"text":"SBSDKUI2NavigationBarModeHidden","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2NavigationBarMode~1dark\/title","op":"replace","value":"SBSDKUI2NavigationBarModeDark"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2NavigationBarMode~1dark\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2NavigationBarModeDark"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2NavigationBarMode~1light\/title","op":"replace","value":"SBSDKUI2NavigationBarModeLight"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2NavigationBarMode~1light\/fragments","op":"replace","value":[{"text":"SBSDKUI2NavigationBarModeLight","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}