{"topicSections":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelAAMVADriverLicense\/requiredDocumentType"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelAAMVADriverLicense"},"metadata":{"navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelAAMVADriverLicense","kind":"identifier"}],"title":"SBSDKBarcodeDocumentModelAAMVADriverLicense","symbolKind":"class","roleHeading":"Class","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentModelAAMVADriverLicense","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelAAMVADriverLicense"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelaamvadriverlicense"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelaamvadriverlicense"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Driver License. File type “DL”."}],"sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelAAMVADLID"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelAAMVADriverLicense"}]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelAAMVADLID":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelAAMVADLID","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelAAMVADLID"}],"kind":"symbol","abstract":[{"type":"text","text":"Driver License Or ID Document"}],"title":"SBSDKBarcodeDocumentModelAAMVADLID","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelaamvadlid","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelAAMVADLID","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelAAMVADriverLicense/initWithGenericDocument:":{"abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelAAMVADriverLicense\/initWithGenericDocument:","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"type":"topic","title":"initWithGenericDocument:","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelaamvadriverlicense\/initwithgenericdocument:"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelAAMVADriverLicense":{"navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelAAMVADriverLicense","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelAAMVADriverLicense","abstract":[{"type":"text","text":"Driver License. File type “DL”."}],"title":"SBSDKBarcodeDocumentModelAAMVADriverLicense","type":"topic","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelaamvadriverlicense","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelAAMVADriverLicense","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelAAMVADriverLicense/requiredDocumentType":{"type":"topic","abstract":[{"text":"The name of the wrapped document type.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"requiredDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"requiredDocumentType","kind":"identifier"}],"title":"requiredDocumentType","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelaamvadriverlicense\/requireddocumenttype","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelAAMVADriverLicense\/requiredDocumentType","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodeDocumentModelAAMVADriverLicense"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelAAMVADriverLicense"}]},{"value":[{"text":"SBSDKBarcodeDocumentModelAAMVADriverLicense","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelAAMVADriverLicense\/requiredDocumentType"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelAAMVADriverLicense\/initWithGenericDocument:"],"title":"Instance Methods","anchor":"Instance-Methods"}]},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelAAMVADLID"],"type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelAAMVADriverLicense","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelAAMVADLID","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentModelAAMVADLID","text":"SBSDKBarcodeDocumentModelAAMVADLID","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKBarcodeDocumentModelAAMVADLID","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelAAMVADLID\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelAAMVADLID"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelAAMVADLID\/fragments"},{"op":"replace","value":[{"text":"SBSDKBarcodeDocumentModelAAMVADLID","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelAAMVADLID\/navigatorTitle"},{"op":"replace","value":"SBSDKBarcodeDocumentModelAAMVADriverLicense","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelAAMVADriverLicense\/title"},{"op":"replace","value":[{"text":"SBSDKBarcodeDocumentModelAAMVADriverLicense","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelAAMVADriverLicense\/fragments"},{"op":"replace","value":[{"text":"SBSDKBarcodeDocumentModelAAMVADriverLicense","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelAAMVADriverLicense\/navigatorTitle"},{"op":"replace","value":"requiredDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelAAMVADriverLicense~1requiredDocumentType\/title"},{"op":"replace","value":[{"text":"requiredDocumentType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelAAMVADriverLicense~1requiredDocumentType\/fragments"}]}]}