{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"identifier"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"ScanbotSDK comes with a built-in AES encryptor that currently supports AES128 and AES256. If these algorithms"},{"type":"text","text":" "},{"type":"text","text":"are not meeting your requirements you can create and use your own encryption classes in ScanbotSDKs image storages"},{"type":"text","text":" "},{"type":"text","text":"by simply conforming to this protocol and implementing the two methods."}]}]}],"metadata":{"title":"SBSDKStorageCrypting","roleHeading":"Protocol","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCrypting"}],"symbolKind":"protocol","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypter","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESGCMEncrypter"],"title":"Conforming Types","type":"conformingTypes"}],"sections":[],"abstract":[{"text":"Protocol for implementing encryption and decryption of (streamed) data.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"topicSections":[{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/beginStreamingDecrypt(context:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/beginStreamingEncrypt(context:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/decrypt(data:context:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/decryptDataFromURL(_:)-2uocl","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/encrypt(data:context:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/provideContext(for:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/streamingCryptChunk(data:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/streamingCryptComplete()"],"title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecrypting"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecrypting"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAESGCMEncrypter":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAESGCMEncrypter"}],"role":"symbol","kind":"symbol","title":"SBSDKAESGCMEncrypter","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESGCMEncrypter","abstract":[{"text":"A data encrypter implementing the AES128-GCM and AES256-GCM standards, with a configurable encryption key provider.","type":"text"},{"text":" ","type":"text"},{"text":"Supports encryption and decryption of single data blocks as well as streaming data.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKAESGCMEncrypter"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaesgcmencrypter","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCrypting/decryptDataFromURL(_:)-2uocl":{"navigatorTitle":[{"text":"decryptDataFromURL:error:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decryptDataFromURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/decryptDataFromURL(_:)-2uocl","abstract":[{"type":"text","text":"Decrypts the data at the given URL and returns it."}],"title":"decryptDataFromURL(_:)","required":true,"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecrypting\/decryptdatafromurl(_:)-2uocl","type":"topic","defaultImplementations":1},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCrypting/streamingCryptChunk(data:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/streamingCryptChunk(data:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"streamingCryptChunk","kind":"identifier"},{"text":"(","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"required":true,"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecrypting\/streamingcryptchunk(data:)","navigatorTitle":[{"text":"streamingCryptChunk:error:","kind":"identifier"}],"kind":"symbol","title":"streamingCryptChunk(data:)","abstract":[{"text":"Performs streaming encryption or decryption on a data chunk.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCrypting/streamingCryptComplete()":{"abstract":[{"text":"Finalizes streaming encryption or decryption.","type":"text"}],"title":"streamingCryptComplete()","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecrypting\/streamingcryptcomplete()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamingCryptComplete"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"navigatorTitle":[{"kind":"identifier","text":"streamingCryptCompleteWithError:"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/streamingCryptComplete()","type":"topic","kind":"symbol","required":true,"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCrypting/encrypt(data:context:)":{"navigatorTitle":[{"kind":"identifier","text":"encryptData:context:error:"}],"title":"encrypt(data:context:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/encrypt(data:context:)","type":"topic","abstract":[{"type":"text","text":"Encrypts the given data blob and returns the encrypted data blob."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encrypt","kind":"identifier"},{"text":"(","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecrypting\/encrypt(data:context:)","required":true,"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCrypting/provideContext(for:)":{"role":"symbol","abstract":[{"type":"text","text":"Provide context that should be used for crypting file at the given url"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"provideContextFor:"}],"title":"provideContext(for:)","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecrypting\/providecontext(for:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provideContext"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/provideContext(for:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCrypting/beginStreamingDecrypt(context:)":{"required":true,"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecrypting\/beginstreamingdecrypt(context:)","title":"beginStreamingDecrypt(context:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/beginStreamingDecrypt(context:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"beginStreamingDecrypt","kind":"identifier"},{"text":"(","kind":"text"},{"text":"context","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Begins streamed decrypting."}],"navigatorTitle":[{"kind":"identifier","text":"beginStreamingDecryptWithContext:error:"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCrypting/beginStreamingEncrypt(context:)":{"required":true,"abstract":[{"text":"Begins streamed encrypting.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"beginStreamingEncrypt","kind":"identifier"},{"text":"(","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecrypting\/beginstreamingencrypt(context:)","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/beginStreamingEncrypt(context:)","navigatorTitle":[{"text":"beginStreamingEncryptWithContext:error:","kind":"identifier"}],"kind":"symbol","title":"beginStreamingEncrypt(context:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAESEncrypter":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypter","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaesencrypter","navigatorTitle":[{"kind":"identifier","text":"SBSDKAESEncrypter"}],"kind":"symbol","abstract":[{"type":"text","text":"ScanbotSDK’s default data encrypter. Provides AES128 and AES 256 encryption to your data."},{"type":"text","text":" "},{"type":"text","text":"All data is encrypted and decrypted with the same key."},{"type":"text","text":" "},{"type":"text","text":"The context being passed to the encrypt\/decrypt methods is ignored."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAESEncrypter"}],"title":"SBSDKAESEncrypter"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCrypting/decrypt(data:context:)":{"title":"decrypt(data:context:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecrypting\/decrypt(data:context:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/decrypt(data:context:)","required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decrypt"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"navigatorTitle":[{"text":"decryptData:context:error:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Decrypts the given encrypted data blob and returns the decrypted data blob."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCrypting":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"SBSDKStorageCrypting","abstract":[{"type":"text","text":"Protocol for implementing encryption and decryption of (streamed) data."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecrypting","navigatorTitle":[{"text":"SBSDKStorageCrypting","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKStorageCrypting","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/beginStreamingDecrypt(context:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/beginStreamingEncrypt(context:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/decrypt(data:context:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/decryptDataFromURL(_:)-2uocl","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/encrypt(data:context:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/provideContext(for:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/streamingCryptChunk(data:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting\/streamingCryptComplete()"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypter","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESGCMEncrypter"],"type":"conformingTypes"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKAESGCMEncrypter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESGCMEncrypter\/title"},{"value":[{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESGCMEncrypter\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKAESGCMEncrypter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESGCMEncrypter\/navigatorTitle"},{"value":"decryptDataFromURL:error:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting~1decryptDataFromURL(_:)-2uocl\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"decryptDataFromURL:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting~1decryptDataFromURL(_:)-2uocl\/fragments"},{"value":"streamingCryptChunk:error:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting~1streamingCryptChunk(data:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"streamingCryptChunk:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting~1streamingCryptChunk(data:)\/fragments"},{"value":"streamingCryptCompleteWithError:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting~1streamingCryptComplete()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"streamingCryptCompleteWithError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting~1streamingCryptComplete()\/fragments"},{"value":"encryptData:context:error:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting~1encrypt(data:context:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"encryptData:context:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting~1encrypt(data:context:)\/fragments"},{"value":"provideContextFor:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting~1provideContext(for:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"provideContextFor:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting~1provideContext(for:)\/fragments"},{"value":"beginStreamingDecryptWithContext:error:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting~1beginStreamingDecrypt(context:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"beginStreamingDecryptWithContext:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting~1beginStreamingDecrypt(context:)\/fragments"},{"value":"beginStreamingEncryptWithContext:error:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting~1beginStreamingEncrypt(context:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"beginStreamingEncryptWithContext:error:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting~1beginStreamingEncrypt(context:)\/fragments"},{"value":"SBSDKAESEncrypter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypter\/title"},{"value":[{"kind":"identifier","text":"SBSDKAESEncrypter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypter\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKAESEncrypter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypter\/navigatorTitle"},{"value":"decryptData:context:error:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting~1decrypt(data:context:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"decryptData:context:error:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting~1decrypt(data:context:)\/fragments"},{"value":"SBSDKStorageCrypting","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting\/title"},{"value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}