{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKTrackedBarcodeInfoViewable","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKTrackedBarcodeInfoViewable\/update(barcodeFrame:isHighlighted:textStyle:polygonStyle:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKTrackedBarcodeInfoViewable\/make(withBarcode:)"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdktrackedbarcodeinfoviewable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdktrackedbarcodeinfoviewable"]}],"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKTrackedBarcodeInfoViewable","title":"SBSDKTrackedBarcodeInfoViewable","role":"symbol","roleHeading":"Protocol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTrackedBarcodeInfoViewable"}],"symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"SBSDKTrackedBarcodeInfoViewable"}]},"abstract":[{"text":"A protocol that defines the methods and properties required for a custom tracking view to be displayed over scanned barcodes using the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayConfiguration"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The custom view must conform to this protocol in order to be used as an overlay on top of the scanned barcodes.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTrackedBarcodeInfoViewable","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackingOverlayConfiguration":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlayconfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayConfiguration","kind":"symbol","title":"SBSDKBarcodeTrackingOverlayConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"text":"A class that represents the configuration options for a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This overlay is used to visualize the scanned barcodes on the screen."},{"type":"text","text":" "},{"type":"text","text":"The class provides various customization options for the appearance and behavior of the overlay."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKTrackedBarcodeInfoViewable/make(withBarcode:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKTrackedBarcodeInfoViewable\/make(withBarcode:)","required":true,"abstract":[{"text":"Creates and returns an instance of the conforming ","type":"text"},{"type":"codeVoice","code":"SBSDKTrackedBarcodeInfoView"},{"text":".","type":"text"}],"title":"make(withBarcode:)","navigatorTitle":[{"kind":"identifier","text":"makeWithBarcode:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdktrackedbarcodeinfoviewable\/make(withbarcode:)","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"make","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withBarcode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKTrackedBarcodeInfoView","preciseIdentifier":"s:24ScanbotBarcodeScannerSDK012SBSDKTrackedB8InfoViewa","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKTrackedBarcodeInfoViewable/update(barcodeFrame:isHighlighted:textStyle:polygonStyle:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"update"},{"kind":"text","text":"("},{"kind":"externalParam","text":"barcodeFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isHighlighted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeTrackedViewTextStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"polygonStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeTrackedViewPolygonStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle"},{"kind":"text","text":")"}],"title":"update(barcodeFrame:isHighlighted:textStyle:polygonStyle:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdktrackedbarcodeinfoviewable\/update(barcodeframe:ishighlighted:textstyle:polygonstyle:)","role":"symbol","abstract":[{"text":"Updates the frame of the tracking view to match the position and size of the associated barcode.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"updateWithBarcodeFrame:isHighlighted:textStyle:polygonStyle:"}],"required":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKTrackedBarcodeInfoViewable\/update(barcodeFrame:isHighlighted:textStyle:polygonStyle:)","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKTrackedBarcodeInfoViewable":{"abstract":[{"type":"text","text":"A protocol that defines the methods and properties required for a custom tracking view to be displayed over scanned barcodes using the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayConfiguration"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The custom view must conform to this protocol in order to be used as an overlay on top of the scanned barcodes."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdktrackedbarcodeinfoviewable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKTrackedBarcodeInfoViewable","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTrackedBarcodeInfoViewable","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKTrackedBarcodeInfoViewable","kind":"identifier"}],"title":"SBSDKTrackedBarcodeInfoViewable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackingOverlayController":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController","title":"SBSDKBarcodeTrackingOverlayController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A class that represents an overlay used for visualizing scanned barcodes."},{"type":"text","text":" "},{"type":"text","text":"It provides a customizable user interface for displaying barcodes and supports interaction with them."},{"type":"text","text":" "},{"type":"text","text":"The overlay can be used to highlight and select barcodes based on user input."}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlaycontroller","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKTrackedBarcodeInfoViewable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKTrackedBarcodeInfoViewable"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKTrackedBarcodeInfoViewable","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKTrackedBarcodeInfoViewable\/update(barcodeFrame:isHighlighted:textStyle:polygonStyle:)"],"title":"Instance Methods"},{"generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKTrackedBarcodeInfoViewable\/make(withBarcode:)"],"title":"Type Methods"}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTrackedBarcodeInfoViewable","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayConfiguration\/title","value":"SBSDKBarcodeTrackingOverlayConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeTrackingOverlayConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKTrackedBarcodeInfoViewable~1make(withBarcode:)\/title","value":"makeWithBarcode:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKTrackedBarcodeInfoViewable~1make(withBarcode:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"makeWithBarcode:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKTrackedBarcodeInfoViewable~1update(barcodeFrame:isHighlighted:textStyle:polygonStyle:)\/title","value":"updateWithBarcodeFrame:isHighlighted:textStyle:polygonStyle:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKTrackedBarcodeInfoViewable~1update(barcodeFrame:isHighlighted:textStyle:polygonStyle:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updateWithBarcodeFrame:isHighlighted:textStyle:polygonStyle:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKTrackedBarcodeInfoViewable\/title","value":"SBSDKTrackedBarcodeInfoViewable"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKTrackedBarcodeInfoViewable"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKTrackedBarcodeInfoViewable\/fragments"},{"op":"replace","value":[{"text":"SBSDKTrackedBarcodeInfoViewable","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKTrackedBarcodeInfoViewable\/navigatorTitle"},{"op":"replace","value":"SBSDKBarcodeTrackingOverlayController","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/title"},{"op":"replace","value":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/fragments"},{"op":"replace","value":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/navigatorTitle"}]}]}