{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkadditionalframeprocessing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkadditionalframeprocessing"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}],"title":"SBSDKAdditionalFrameProcessing","symbolKind":"protocol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKAdditionalFrameProcessing","roleHeading":"Protocol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAdditionalFrameProcessing","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAdditionalFrameProcessing\/process(frame:)"],"anchor":"Instance-Methods"}],"abstract":[{"text":"A protocol that allows to perform additional processing of frames before they are passed to the main scanner.","type":"text"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAdditionalFrameProcessing/process(frame:)":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkadditionalframeprocessing\/process(frame:)","kind":"symbol","abstract":[{"text":"Performs additional processing of the frame, e.g. running other scanners on the frame.","type":"text"}],"type":"topic","title":"process(frame:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"process","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRef"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAdditionalFrameProcessing\/process(frame:)","navigatorTitle":[{"text":"processWithFrame:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAdditionalFrameProcessing":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkadditionalframeprocessing","kind":"symbol","abstract":[{"text":"A protocol that allows to perform additional processing of frames before they are passed to the main scanner.","type":"text"}],"type":"topic","title":"SBSDKAdditionalFrameProcessing","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAdditionalFrameProcessing"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKAdditionalFrameProcessing"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKAdditionalFrameProcessing"}]},{"value":[{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAdditionalFrameProcessing\/process(frame:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"processWithFrame:","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAdditionalFrameProcessing~1process(frame:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"processWithFrame:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAdditionalFrameProcessing~1process(frame:)\/fragments","op":"replace"},{"op":"replace","value":"SBSDKAdditionalFrameProcessing","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAdditionalFrameProcessing\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAdditionalFrameProcessing"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAdditionalFrameProcessing\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAdditionalFrameProcessing"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAdditionalFrameProcessing\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}