{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BottomBarMode"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BottomBarMode\/gradient","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BottomBarMode\/hidden","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BottomBarMode\/solid"],"anchor":"Enumeration-Cases"},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BottomBarMode\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BottomBarMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BottomBarMode\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2BottomBarMode) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BottomBarMode","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"The visual mode used for the bottom bar."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2bottombarmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2bottombarmode"]}],"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BottomBarMode","kind":"identifier"}],"roleHeading":"Enumeration","navigatorTitle":[{"text":"SBSDKUI2BottomBarMode","kind":"identifier"}],"symbolKind":"enum","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2BottomBarMode","title":"SBSDKUI2BottomBarMode"},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"kind":"relationships"}],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/s12CaseIterableP":{"type":"unresolvable","title":"Swift.CaseIterable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s12CaseIterableP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BottomBarMode/solid":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2bottombarmode\/solid","abstract":[{"text":"Display the bottom bar with a background color or with transparency.","type":"text"}],"type":"topic","title":"SBSDKUI2BottomBarMode.solid","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"solid","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BottomBarModeSolid"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BottomBarMode\/solid"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BottomBarMode/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BottomBarMode\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2bottombarmode\/rawrepresentable-implementations","kind":"article","abstract":[],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BottomBarMode/init(rawValue:)":{"type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BottomBarMode\/init(rawValue:)","title":"init(rawValue:)","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2bottombarmode\/init(rawvalue:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BottomBarMode/gradient":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BottomBarMode\/gradient","type":"topic","abstract":[{"type":"text","text":"Display the bottom bar with a gradient background color or a gradient with transparency. The buttons will still be visible."}],"navigatorTitle":[{"text":"SBSDKUI2BottomBarModeGradient","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2bottombarmode\/gradient","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gradient","kind":"identifier"}],"title":"SBSDKUI2BottomBarMode.gradient"},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE"},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BottomBarMode/Equatable-Implementations":{"kind":"article","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2bottombarmode\/equatable-implementations","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BottomBarMode\/Equatable-Implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BottomBarMode":{"role":"symbol","abstract":[{"text":"The visual mode used for the bottom bar.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BottomBarMode"}],"title":"SBSDKUI2BottomBarMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2bottombarmode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BottomBarMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BottomBarMode"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BottomBarMode/hidden":{"abstract":[{"type":"text","text":"Hide the bottom bar completely."}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2BottomBarModeHidden","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BottomBarMode\/hidden","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2bottombarmode\/hidden","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hidden","kind":"identifier"}],"title":"SBSDKUI2BottomBarMode.hidden","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKUI2BottomBarMode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BottomBarMode"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2BottomBarMode"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BottomBarMode\/gradient","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BottomBarMode\/hidden","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BottomBarMode\/solid"],"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BottomBarMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BottomBarMode~1solid\/title","value":"SBSDKUI2BottomBarModeSolid","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BottomBarMode~1solid\/fragments","value":[{"text":"SBSDKUI2BottomBarModeSolid","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BottomBarMode~1gradient\/title","value":"SBSDKUI2BottomBarModeGradient","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BottomBarMode~1gradient\/fragments","value":[{"text":"SBSDKUI2BottomBarModeGradient","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BottomBarMode\/title","value":"SBSDKUI2BottomBarMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BottomBarMode\/fragments","value":[{"text":"SBSDKUI2BottomBarMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BottomBarMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2BottomBarMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BottomBarMode~1hidden\/title","value":"SBSDKUI2BottomBarModeHidden","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BottomBarMode~1hidden\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BottomBarModeHidden"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}