{"metadata":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"symbolKind":"enum","roleHeading":"Enumeration","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"SBSDKOneDConfirmationMode","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKOneDConfirmationMode"},"kind":"symbol","abstract":[{"text":"Allows to select the balance between result accuracy (precision) and missed barcodes (recall) for linear barcodes.","type":"text"},{"text":" ","type":"text"},{"text":"Some barcode types are naturally prone to false positives (e.g. MSI Plessey).","type":"text"},{"text":" ","type":"text"},{"text":"For those barcode types false positives can be drastically reduced (precision can be increased) by requiring that multiple scan-lines in the input scan to the same result.","type":"text"},{"text":" ","type":"text"},{"text":"However, this stronger condition can lead to missed barcodes (lower recall).","type":"text"},{"text":" ","type":"text"},{"text":"Confirmation is avoided for barcode types, which are by design resistant to false positives, (e.g. Code128) to maximize recall.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkonedconfirmationmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkonedconfirmationmode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/minimal","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/moderate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/none","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/thorough"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKOneDConfirmationMode) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOneDConfirmationMode"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOneDConfirmationMode/thorough":{"type":"topic","abstract":[{"text":"Recommended. Thorough confirmation is performed. Almost completely eliminates false positives, at the cost of an additional slight decrease in recall.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/thorough","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkonedconfirmationmode\/thorough","title":"SBSDKOneDConfirmationMode.thorough","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKOneDConfirmationModeThorough"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"thorough"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOneDConfirmationMode/init(rawValue:)":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkonedconfirmationmode\/init(rawvalue:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOneDConfirmationMode/RawRepresentable-Implementations":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkonedconfirmationmode\/rawrepresentable-implementations","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/RawRepresentable-Implementations","type":"topic","abstract":[],"title":"RawRepresentable Implementations","kind":"article","role":"collectionGroup"},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOneDConfirmationMode/moderate":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkonedconfirmationmode\/moderate","abstract":[{"text":"Moderate confirmation is performed. Compared to minimal confirmation, it provides an additional decrease in false positives, at the cost of a slight decrease in recall.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKOneDConfirmationModeModerate"}],"title":"SBSDKOneDConfirmationMode.moderate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"moderate"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/moderate","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOneDConfirmationMode":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkonedconfirmationmode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode","role":"symbol","title":"SBSDKOneDConfirmationMode","abstract":[{"type":"text","text":"Allows to select the balance between result accuracy (precision) and missed barcodes (recall) for linear barcodes."},{"type":"text","text":" "},{"type":"text","text":"Some barcode types are naturally prone to false positives (e.g. MSI Plessey)."},{"text":" ","type":"text"},{"text":"For those barcode types false positives can be drastically reduced (precision can be increased) by requiring that multiple scan-lines in the input scan to the same result.","type":"text"},{"text":" ","type":"text"},{"text":"However, this stronger condition can lead to missed barcodes (lower recall).","type":"text"},{"text":" ","type":"text"},{"text":"Confirmation is avoided for barcode types, which are by design resistant to false positives, (e.g. Code128) to maximize recall.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOneDConfirmationMode/none":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkonedconfirmationmode\/none","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/none","kind":"symbol","navigatorTitle":[{"text":"SBSDKOneDConfirmationModeNone","kind":"identifier"}],"role":"symbol","type":"topic","title":"SBSDKOneDConfirmationMode.none","abstract":[{"type":"text","text":"No confirmation is required. This mode is the most prone to generating false positives."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOneDConfirmationMode/minimal":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkonedconfirmationmode\/minimal","navigatorTitle":[{"text":"SBSDKOneDConfirmationModeMinimal","kind":"identifier"}],"abstract":[{"type":"text","text":"Minimal confirmation is performed. Compared to no confirmation, it provides a substantial decrease in false positives (increased precision), at the cost of a minimal decrease in recall."}],"title":"SBSDKOneDConfirmationMode.minimal","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/minimal","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimal","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOneDConfirmationMode/Equatable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/Equatable-Implementations","type":"topic","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkonedconfirmationmode\/equatable-implementations","kind":"article","role":"collectionGroup","title":"Equatable Implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/s12CaseIterableP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s12CaseIterableP","title":"Swift.CaseIterable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"SBSDKOneDConfirmationMode","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKOneDConfirmationMode"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKOneDConfirmationMode"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/minimal","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/moderate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/none","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode\/thorough"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOneDConfirmationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKOneDConfirmationModeThorough","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode~1thorough\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKOneDConfirmationModeThorough","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode~1thorough\/fragments"},{"op":"replace","value":"SBSDKOneDConfirmationModeModerate","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode~1moderate\/title"},{"op":"replace","value":[{"text":"SBSDKOneDConfirmationModeModerate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode~1moderate\/fragments"},{"op":"replace","value":"SBSDKOneDConfirmationMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKOneDConfirmationMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode\/fragments"},{"op":"replace","value":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode\/navigatorTitle"},{"op":"replace","value":"SBSDKOneDConfirmationModeNone","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode~1none\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKOneDConfirmationModeNone"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode~1none\/fragments"},{"op":"replace","value":"SBSDKOneDConfirmationModeMinimal","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode~1minimal\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKOneDConfirmationModeMinimal"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode~1minimal\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}