{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The size of the image from camera which would be sent to the scanner for live scanning.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKCameraLiveScannerResolution) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution"},"metadata":{"roleHeading":"Enumeration","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"SBSDKCameraLiveScannerResolution","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKCameraLiveScannerResolution","role":"symbol","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/auto","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/fullHd","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/uhd"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"kind":"relationships"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraLiveScannerResolution/RawRepresentable-Implementations":{"kind":"article","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution\/rawrepresentable-implementations","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup","title":"RawRepresentable Implementations","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotBarcodeScannerSDK/s12CaseIterableP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s12CaseIterableP","type":"unresolvable","title":"Swift.CaseIterable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraLiveScannerResolution/fullHd":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution\/fullhd","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/fullHd","title":"SBSDKCameraLiveScannerResolution.fullHd","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullHd","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The image is in Full HD resolution. 1920x1080 pixels or close to it.","type":"text"}],"navigatorTitle":[{"text":"SBSDKCameraLiveScannerResolutionFullHd","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraLiveScannerResolution":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution","navigatorTitle":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"title":"SBSDKCameraLiveScannerResolution","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution","abstract":[{"text":"The size of the image from camera which would be sent to the scanner for live scanning.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraLiveScannerResolution/Equatable-Implementations":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution\/equatable-implementations","kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/Equatable-Implementations","title":"Equatable Implementations","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraLiveScannerResolution/uhd":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolutionUhd"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution\/uhd","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/uhd","role":"symbol","type":"topic","title":"SBSDKCameraLiveScannerResolution.uhd","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"uhd"}],"abstract":[{"type":"text","text":"The image is in UHD resolution. 3840x2160 pixels or close to it."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraLiveScannerResolution/auto":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"auto"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolutionAuto"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution\/auto","abstract":[{"type":"text","text":"Select to the image resolution automatically based on device specifics."}],"title":"SBSDKCameraLiveScannerResolution.auto","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/auto"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraLiveScannerResolution/init(rawValue:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcameralivescannerresolution\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/init(rawValue:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKCameraLiveScannerResolution"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolution"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/auto","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/fullHd","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraLiveScannerResolution\/uhd"],"anchor":"Enumeration-Cases","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution~1fullHd\/title","value":"SBSDKCameraLiveScannerResolutionFullHd"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution~1fullHd\/fragments","value":[{"text":"SBSDKCameraLiveScannerResolutionFullHd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution\/title","value":"SBSDKCameraLiveScannerResolution"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolution"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution\/navigatorTitle","value":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution~1uhd\/title","value":"SBSDKCameraLiveScannerResolutionUhd"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution~1uhd\/fragments","value":[{"text":"SBSDKCameraLiveScannerResolutionUhd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution~1auto\/title","value":"SBSDKCameraLiveScannerResolutionAuto"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraLiveScannerResolution~1auto\/fragments","value":[{"text":"SBSDKCameraLiveScannerResolutionAuto","kind":"identifier"}]}]}]}