{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDeviceDeregistrationError(im)initWithDeviceId:errorMessage:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"initWithDeviceId:errorMessage:","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDeviceId:errorMessage:"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithDeviceId:errorMessage:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceDeregistrationError\/initWithDeviceId:errorMessage:"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDeviceId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"deviceId"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"errorMessage"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceDeregistrationError"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdevicederegistrationerror\/initwithdeviceid:errormessage:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceDeregistrationError/initWithDeviceId:errorMessage:":{"type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdevicederegistrationerror\/initwithdeviceid:errormessage:","title":"initWithDeviceId:errorMessage:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceDeregistrationError\/initWithDeviceId:errorMessage:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDeviceId:errorMessage:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithDeviceId:errorMessage:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceDeregistrationError":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceDeregistrationError","url":"\/documentation\/scanbotsdk\/sbsdkdevicederegistrationerror","kind":"symbol","title":"SBSDKDeviceDeregistrationError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}],"abstract":[{"text":"Description of error that occurred during device deregistration.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceDeregistrationError\/title","value":"SBSDKDeviceDeregistrationError"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceDeregistrationError\/fragments","value":[{"kind":"identifier","text":"SBSDKDeviceDeregistrationError"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceDeregistrationError\/navigatorTitle","value":[{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}]}]}]}