{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorNothingFound","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanningstatus\/errornothingfound"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanningstatus\/errornothingfound"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningStatus\/errorNothingFound"},"metadata":{"role":"symbol","navigatorTitle":[{"text":"SBSDKCreditCardScanningStatusErrorNothingFound","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKCreditCardScanningStatus.errorNothingFound","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorNothingFound","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKCreditCardScanningStatus@SBSDKCreditCardScanningStatusErrorNothingFound"},"sections":[],"abstract":[{"text":"No credit card was detected.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningStatus/errorNothingFound":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKCreditCardScanningStatusErrorNothingFound","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningstatus\/errornothingfound","kind":"symbol","title":"SBSDKCreditCardScanningStatus.errorNothingFound","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningStatus\/errorNothingFound","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorNothingFound","kind":"identifier"}],"abstract":[{"text":"No credit card was detected.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningStatus":{"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningstatus","title":"SBSDKCreditCardScanningStatus","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKCreditCardScanningStatus","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningStatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCreditCardScanningStatus"}],"role":"symbol","abstract":[{"text":"The status of the scanning process.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKCreditCardScanningStatusErrorNothingFound"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKCreditCardScanningStatusErrorNothingFound","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKCreditCardScanningStatusErrorNothingFound"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningStatus~1errorNothingFound\/title","op":"replace","value":"SBSDKCreditCardScanningStatusErrorNothingFound"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningStatus~1errorNothingFound\/fragments","op":"replace","value":[{"text":"SBSDKCreditCardScanningStatusErrorNothingFound","kind":"identifier"}]},{"value":"SBSDKCreditCardScanningStatus","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningStatus\/title"},{"value":[{"text":"SBSDKCreditCardScanningStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningStatus\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningStatus\/navigatorTitle","value":[{"text":"SBSDKCreditCardScanningStatus","kind":"identifier"}],"op":"replace"}]}]}