{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerBehaviorConfiguration(py)requiredNumberOfEqualAccumulatedResults","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","title":"requiredNumberOfEqualAccumulatedResults","navigatorTitle":[{"kind":"identifier","text":"requiredNumberOfEqualAccumulatedResults"}],"modules":[{"name":"ScanbotSDK"}],"platforms":[]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/requiredNumberOfEqualAccumulatedResults","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}]}]},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"This sets the first part of the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/requiredNumberOfEqualAccumulatedResults"},{"text":" of ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/maxNumberOfAccumulatedResults","isActive":true},{"type":"text","text":" selector,"},{"text":" ","type":"text"},{"text":"e.g. 2 of 4 results must be equal.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"To get fewer false positive results, make the selector more strict by selecting a higher value, e.g. 3 of 4 or even 4 of 4."},{"type":"text","text":" "},{"type":"text","text":"Setting a value higher than "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/maxNumberOfAccumulatedResults","type":"reference","isActive":true},{"type":"text","text":" will throw an exception."},{"type":"text","text":" "},{"type":"text","text":"Values less-than-or-equal to 0, will effectively turn off the result accumulation."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Defaults to 2.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2MRZScannerViewController instead.","type":"text"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The minimum number of equal results in the accumulator when live-recognizing machine-readable zones on sample buffers.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscannerbehaviorconfiguration\/requirednumberofequalaccumulatedresults"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscannerbehaviorconfiguration\/requirednumberofequalaccumulatedresults"]}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerBehaviorConfiguration/requiredNumberOfEqualAccumulatedResults":{"title":"requiredNumberOfEqualAccumulatedResults","role":"symbol","deprecated":true,"abstract":[{"text":"The minimum number of equal results in the accumulator when live-recognizing machine-readable zones on sample buffers.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiredNumberOfEqualAccumulatedResults"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerbehaviorconfiguration\/requirednumberofequalaccumulatedresults","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/requiredNumberOfEqualAccumulatedResults","navigatorTitle":[{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerBehaviorConfiguration/maxNumberOfAccumulatedResults":{"navigatorTitle":[{"kind":"identifier","text":"maxNumberOfAccumulatedResults"}],"role":"symbol","title":"maxNumberOfAccumulatedResults","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/maxNumberOfAccumulatedResults","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerbehaviorconfiguration\/maxnumberofaccumulatedresults","abstract":[{"text":"The maximum number of results to be accumulated when live-recognizing machine-readable zones on sample buffers.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxNumberOfAccumulatedResults"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerBehaviorConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration","abstract":[{"text":"Configuration for the behavior of the machine readable zone scanner.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMRZScannerBehaviorConfiguration"}],"title":"SBSDKUIMRZScannerBehaviorConfiguration","deprecated":true,"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerbehaviorconfiguration","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMRZScannerBehaviorConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"requiredNumberOfEqualAccumulatedResults","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"text":" ","kind":"text"},{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"requiredNumberOfEqualAccumulatedResults","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration~1requiredNumberOfEqualAccumulatedResults\/title"},{"value":[{"kind":"identifier","text":"requiredNumberOfEqualAccumulatedResults"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration~1requiredNumberOfEqualAccumulatedResults\/fragments"},{"value":"maxNumberOfAccumulatedResults","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration~1maxNumberOfAccumulatedResults\/title"},{"value":[{"kind":"identifier","text":"maxNumberOfAccumulatedResults"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration~1maxNumberOfAccumulatedResults\/fragments"},{"value":"SBSDKUIMRZScannerBehaviorConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIMRZScannerBehaviorConfiguration"}]},{"op":"replace","value":[{"text":"SBSDKUIMRZScannerBehaviorConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}