{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerConfiguration\/maximumNumberOfAccumulatedFrames","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The maximum number of subsequent video frames being analyzed and accumulated when scanning for license plates."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerConfiguration"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Defaults to 3"}],"type":"paragraph"}]}],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"}],"roleHeading":"Instance Property","title":"maximumNumberOfAccumulatedFrames","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerConfiguration(py)maximumNumberOfAccumulatedFrames","symbolKind":"property"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerconfiguration\/maximumnumberofaccumulatedframes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerconfiguration\/maximumnumberofaccumulatedframes"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerConfiguration":{"kind":"symbol","title":"SBSDKLicensePlateScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLicensePlateScannerConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicensePlateScannerConfiguration"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerconfiguration","abstract":[{"text":"A class being used to configure the license plate scanner.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerConfiguration/maximumNumberOfAccumulatedFrames":{"abstract":[{"type":"text","text":"The maximum number of subsequent video frames being analyzed and accumulated when scanning for license plates."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerconfiguration\/maximumnumberofaccumulatedframes","title":"maximumNumberOfAccumulatedFrames","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerConfiguration\/maximumNumberOfAccumulatedFrames","role":"symbol","navigatorTitle":[{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"maximumNumberOfAccumulatedFrames"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SBSDKLicensePlateScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerConfiguration\/fragments","value":[{"text":"SBSDKLicensePlateScannerConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKLicensePlateScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerConfiguration\/navigatorTitle"},{"value":"maximumNumberOfAccumulatedFrames","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerConfiguration~1maximumNumberOfAccumulatedFrames\/title"},{"op":"replace","value":[{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerConfiguration~1maximumNumberOfAccumulatedFrames\/fragments"}]}]}