{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerConfiguration\/minimumNumberOfRequiredFramesWithEqualScanningResult","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minimumNumberOfRequiredFramesWithEqualScanningResult","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}]}]},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Defaults to 2","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerconfiguration\/minimumnumberofrequiredframeswithequalscanningresult"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerconfiguration\/minimumnumberofrequiredframeswithequalscanningresult"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerConfiguration(py)minimumNumberOfRequiredFramesWithEqualScanningResult","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"title":"minimumNumberOfRequiredFramesWithEqualScanningResult","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}]},"abstract":[{"text":"The minimum number of accumulated video frames with equal results to trigger a successful license plate scan.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerConfiguration/minimumNumberOfRequiredFramesWithEqualScanningResult":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerconfiguration\/minimumnumberofrequiredframeswithequalscanningresult","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"minimumNumberOfRequiredFramesWithEqualScanningResult","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"abstract":[{"text":"The minimum number of accumulated video frames with equal results to trigger a successful license plate scan.","type":"text"}],"role":"symbol","title":"minimumNumberOfRequiredFramesWithEqualScanningResult","navigatorTitle":[{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerConfiguration\/minimumNumberOfRequiredFramesWithEqualScanningResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerConfiguration","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLicensePlateScannerConfiguration"}],"abstract":[{"type":"text","text":"A class being used to configure the license plate scanner."}],"role":"symbol","title":"SBSDKLicensePlateScannerConfiguration","navigatorTitle":[{"text":"SBSDKLicensePlateScannerConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"minimumNumberOfRequiredFramesWithEqualScanningResult"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"text":" ","kind":"text"},{"text":"minimumNumberOfRequiredFramesWithEqualScanningResult","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerConfiguration~1minimumNumberOfRequiredFramesWithEqualScanningResult\/title","value":"minimumNumberOfRequiredFramesWithEqualScanningResult","op":"replace"},{"value":[{"text":"minimumNumberOfRequiredFramesWithEqualScanningResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerConfiguration~1minimumNumberOfRequiredFramesWithEqualScanningResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerConfiguration\/title","value":"SBSDKLicensePlateScannerConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}