{"abstract":[{"text":"The strategy being used to find a license plate in an image.","type":"text"}],"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"strategy","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKLicensePlateScannerStrategy","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKLicensePlateScannerStrategy"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"strategy"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerConfiguration(py)strategy","title":"strategy","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"strategy","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerStrategy","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKLicensePlateScannerStrategy","text":"SBSDKLicensePlateScannerStrategy"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Defaults to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerStrategy\/ML"},{"type":"text","text":"."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerconfiguration\/strategy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerconfiguration\/strategy"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerConfiguration\/strategy","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerConfiguration","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLicensePlateScannerConfiguration"}],"abstract":[{"type":"text","text":"A class being used to configure the license plate scanner."}],"role":"symbol","title":"SBSDKLicensePlateScannerConfiguration","navigatorTitle":[{"text":"SBSDKLicensePlateScannerConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerStrategy/ML":{"navigatorTitle":[{"text":"SBSDKLicensePlateScannerStrategyML","kind":"identifier"}],"title":"SBSDKLicensePlateScannerStrategy.ML","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerstrategy\/ml","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ML"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerStrategy\/ML","abstract":[{"text":"Machine learning based strategy using neural networks to find a license plate in an image.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerConfiguration/strategy":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerConfiguration\/strategy","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerconfiguration\/strategy","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"strategy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKLicensePlateScannerStrategy","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKLicensePlateScannerStrategy"}],"abstract":[{"type":"text","text":"The strategy being used to find a license plate in an image."}],"role":"symbol","title":"strategy","navigatorTitle":[{"text":"strategy","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerStrategy":{"abstract":[{"text":"The strategy being used to scan a license plate. *\/","type":"text"}],"title":"SBSDKLicensePlateScannerStrategy","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicensePlateScannerStrategy","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKLicensePlateScannerStrategy","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerStrategy","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerstrategy","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"strategy"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"strategy","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKLicensePlateScannerStrategy","text":"SBSDKLicensePlateScannerStrategy","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerStrategy","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"strategy","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKLicensePlateScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerStrategy~1ML\/title","value":"SBSDKLicensePlateScannerStrategyML"},{"value":[{"text":"SBSDKLicensePlateScannerStrategyML","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerStrategy~1ML\/fragments"},{"op":"replace","value":"strategy","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerConfiguration~1strategy\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerConfiguration~1strategy\/fragments","value":[{"text":"strategy","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerStrategy\/title","op":"replace","value":"SBSDKLicensePlateScannerStrategy"},{"value":[{"text":"SBSDKLicensePlateScannerStrategy","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerStrategy\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}