{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ifAvailable","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncryptionMode\/ifAvailable","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncryptionMode"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkencryptionmode\/ifavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkencryptionmode\/ifavailable"]}],"abstract":[{"text":"Encryption\/Decryption is used when loading\/saving an image if a crypting provider is set using","type":"text"},{"type":"text","text":" "},{"code":"ImageRef.setStorageCryptingProvider","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKEncryptionMode@SBSDKEncryptionModeIfAvailable","role":"symbol","title":"SBSDKEncryptionMode.ifAvailable","roleHeading":"Case","navigatorTitle":[{"text":"SBSDKEncryptionModeIfAvailable","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ifAvailable"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"case"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKEncryptionMode":{"navigatorTitle":[{"text":"SBSDKEncryptionMode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncryptionMode","title":"SBSDKEncryptionMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkencryptionmode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEncryptionMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Encryption\/Decryption mode to be used when an image is loaded\/saved."}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKEncryptionMode/ifAvailable":{"navigatorTitle":[{"text":"SBSDKEncryptionModeIfAvailable","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncryptionMode\/ifAvailable","title":"SBSDKEncryptionMode.ifAvailable","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkencryptionmode\/ifavailable","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ifAvailable","kind":"identifier"}],"abstract":[{"text":"Encryption\/Decryption is used when loading\/saving an image if a crypting provider is set using","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"ImageRef.setStorageCryptingProvider"},{"type":"text","text":"."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKEncryptionModeIfAvailable"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKEncryptionModeIfAvailable","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKEncryptionModeIfAvailable"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode\/title","value":"SBSDKEncryptionMode","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKEncryptionMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKEncryptionMode"}]},{"op":"replace","value":"SBSDKEncryptionModeIfAvailable","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode~1ifAvailable\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode~1ifAvailable\/fragments","value":[{"text":"SBSDKEncryptionModeIfAvailable","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}