{"metadata":{"navigatorTitle":[{"text":"barcodeInfoMappingErrorStateTitle","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeTextLocalization(py)barcodeInfoMappingErrorStateTitle","roleHeading":"Instance Property","title":"barcodeInfoMappingErrorStateTitle","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeInfoMappingErrorStateTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingErrorStateTitle","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeInfoMappingErrorStateTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is “Connection Error!”"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization"]]},"abstract":[{"text":"Title for the barcode info mapping error state.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/barcodeinfomappingerrorstatetitle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/barcodeinfomappingerrorstatetitle"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the all strings for barcode scanner."}],"title":"SBSDKUI2BarcodeTextLocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization","navigatorTitle":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/barcodeInfoMappingErrorStateTitle":{"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/barcodeInfoMappingErrorStateTitle","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/barcodeinfomappingerrorstatetitle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeInfoMappingErrorStateTitle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"barcodeInfoMappingErrorStateTitle"}],"abstract":[{"type":"text","text":"Title for the barcode info mapping error state."}],"title":"barcodeInfoMappingErrorStateTitle","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"barcodeInfoMappingErrorStateTitle","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"barcodeInfoMappingErrorStateTitle","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"barcodeInfoMappingErrorStateTitle","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/title","value":"SBSDKUI2BarcodeTextLocalization","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/fragments","value":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1barcodeInfoMappingErrorStateTitle\/title","value":"barcodeInfoMappingErrorStateTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1barcodeInfoMappingErrorStateTitle\/fragments","value":[{"text":"barcodeInfoMappingErrorStateTitle","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}