{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentpolygonconfiguration\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentPolygonConfiguration\/copyWithZone:","interfaceLanguage":"occ"},"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"title":"copyWithZone:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentPolygonConfiguration(im)copyWithZone:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentPolygonConfiguration"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone","text":"_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentPolygonConfiguration/copyWithZone:":{"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentPolygonConfiguration\/copyWithZone:","title":"copyWithZone:","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentpolygonconfiguration\/copywithzone:","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentPolygonConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentPolygonConfiguration"}],"abstract":[{"text":"Configuration of the document contour detection polygon.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentPolygonConfiguration","title":"SBSDKUI2DocumentPolygonConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentPolygonConfiguration"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentpolygonconfiguration","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2DocumentPolygonConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentPolygonConfiguration\/title"},{"value":[{"text":"SBSDKUI2DocumentPolygonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentPolygonConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentPolygonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentPolygonConfiguration\/navigatorTitle"}]}]}