{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation\/hash","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"hash","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRotation(py)hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"role":"symbol","title":"hash","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagerotation\/hash"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRotation":{"role":"symbol","title":"SBSDKImageRotation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation","abstract":[{"type":"text","text":"Image rotation."}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagerotation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRotation"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRotation"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRotation/hash":{"type":"topic","abstract":[],"kind":"symbol","title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkimagerotation\/hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation\/hash","role":"symbol","fragments":[{"kind":"identifier","text":"hash"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/title","op":"replace","value":"SBSDKImageRotation"},{"value":[{"kind":"identifier","text":"SBSDKImageRotation"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/fragments"},{"value":[{"text":"SBSDKImageRotation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/navigatorTitle"}]}]}