{"metadata":{"role":"symbol","title":"copyWithZone:","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerGuidanceStates(im)copyWithZone:","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/copyWithZone:","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone","text":"_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates":{"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates","role":"symbol","type":"topic","title":"SBSDKUI2CreditCardScannerGuidanceStates","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates","abstract":[{"type":"text","text":"Configure the captions of the user guidance hints for different scanning states."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerGuidanceStates"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerGuidanceStates"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates/copyWithZone:":{"kind":"symbol","type":"topic","title":"copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/copywithzone:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/copyWithZone:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2CreditCardScannerGuidanceStates","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates\/title"},{"op":"replace","value":[{"text":"SBSDKUI2CreditCardScannerGuidanceStates","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerGuidanceStates"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates\/navigatorTitle"}]}]}