{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNoCardFound:scanningProgress:tooDark:tooSmall:badPerspective:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithNoCardFound:scanningProgress:tooDark:tooSmall:badPerspective:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerGuidanceStates(im)initWithNoCardFound:scanningProgress:tooDark:tooSmall:badPerspective:","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"title":"initWithNoCardFound:scanningProgress:tooDark:tooSmall:badPerspective:"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/initWithNoCardFound:scanningProgress:tooDark:tooSmall:badPerspective:","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithNoCardFound:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"noCardFound"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanningProgress:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"scanningProgress"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooDark:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tooDark"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooSmall:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tooSmall"},{"kind":"text","text":" "},{"kind":"identifier","text":"badPerspective:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"badPerspective"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/initwithnocardfound:scanningprogress:toodark:toosmall:badperspective:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates/initWithNoCardFound:scanningProgress:tooDark:tooSmall:badPerspective:":{"title":"initWithNoCardFound:scanningProgress:tooDark:tooSmall:badPerspective:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNoCardFound:scanningProgress:tooDark:tooSmall:badPerspective:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/initWithNoCardFound:scanningProgress:tooDark:tooSmall:badPerspective:","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/initwithnocardfound:scanningprogress:toodark:toosmall:badperspective:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNoCardFound:scanningProgress:tooDark:tooSmall:badPerspective:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates":{"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates","role":"symbol","type":"topic","title":"SBSDKUI2CreditCardScannerGuidanceStates","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates","abstract":[{"type":"text","text":"Configure the captions of the user guidance hints for different scanning states."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerGuidanceStates"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerGuidanceStates"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2CreditCardScannerGuidanceStates","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates\/title"},{"value":[{"text":"SBSDKUI2CreditCardScannerGuidanceStates","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates\/fragments"},{"value":[{"text":"SBSDKUI2CreditCardScannerGuidanceStates","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}