{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/willShowEnableCameraView"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerViewController(im)willShowEnableCameraView","fragments":[{"kind":"text","text":"- "},{"text":"willShowEnableCameraView","kind":"identifier"}],"title":"willShowEnableCameraView","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"willShowEnableCameraView"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/willshowenablecameraview"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"willShowEnableCameraView","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/willShowEnableCameraView":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/willshowenablecameraview","navigatorTitle":[{"text":"willShowEnableCameraView","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/willShowEnableCameraView","title":"willShowEnableCameraView","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"willShowEnableCameraView"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewController"}],"navigatorTitle":[{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}],"kind":"symbol","title":"SBSDKUIMedicalCertificateScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","role":"symbol","abstract":[{"type":"text","text":"A Ready-To-Use viewController to scan medical certificates."}]}},"variantOverrides":[{"patch":[{"value":"SBSDKUIMedicalCertificateScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/fragments","op":"replace"},{"value":[{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}