{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/vertical","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"The edge is oriented vertically.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vertical","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"title":"SBSDKLineSegmentOrientation.vertical","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKLineSegmentOrientation@SBSDKLineSegmentOrientationVertical","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vertical","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKLineSegmentOrientationVertical","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklinesegmentorientation\/vertical"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdklinesegmentorientation\/vertical"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegmentOrientation":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLineSegmentOrientation"}],"kind":"symbol","title":"SBSDKLineSegmentOrientation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation","navigatorTitle":[{"kind":"identifier","text":"SBSDKLineSegmentOrientation"}],"url":"\/documentation\/scanbotsdk\/sbsdklinesegmentorientation","abstract":[{"type":"text","text":"An enum describing the orientation of a polygon edge."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegmentOrientation/vertical":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vertical","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklinesegmentorientation\/vertical","type":"topic","abstract":[{"type":"text","text":"The edge is oriented vertically."}],"title":"SBSDKLineSegmentOrientation.vertical","navigatorTitle":[{"text":"SBSDKLineSegmentOrientationVertical","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/vertical"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKLineSegmentOrientationVertical","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKLineSegmentOrientationVertical","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKLineSegmentOrientationVertical","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKLineSegmentOrientation","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLineSegmentOrientation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLineSegmentOrientation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation\/navigatorTitle"},{"op":"replace","value":"SBSDKLineSegmentOrientationVertical","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation~1vertical\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLineSegmentOrientationVertical"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation~1vertical\/fragments"}]}]}