{"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"behaviorConfiguration","role":"symbol","navigatorTitle":[{"text":"behaviorConfiguration","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerConfiguration(py)behaviorConfiguration","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"behaviorConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerBehaviorConfiguration","text":"SBSDKUILicensePlateScannerBehaviorConfiguration","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/behaviorConfiguration","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"behaviorConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerBehaviorConfiguration","text":"SBSDKUILicensePlateScannerBehaviorConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerBehaviorConfiguration"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerconfiguration\/behaviorconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerconfiguration\/behaviorconfiguration"]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The configuration controlling the scanning screens behavior."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUILicensePlateScannerConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUILicensePlateScannerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerconfiguration","title":"SBSDKUILicensePlateScannerConfiguration","abstract":[{"type":"text","text":"This class describes the look and feel, the behavior and the textual contents of the detection RTU-UI screen for license plate scanner."}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerConfiguration/behaviorConfiguration":{"title":"behaviorConfiguration","type":"topic","abstract":[{"type":"text","text":"The configuration controlling the scanning screens behavior."}],"role":"symbol","navigatorTitle":[{"text":"behaviorConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerconfiguration\/behaviorconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/behaviorConfiguration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"behaviorConfiguration"},{"kind":"text","text":": "},{"text":"SBSDKUILicensePlateScannerBehaviorConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerBehaviorConfiguration"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerBehaviorConfiguration":{"type":"topic","title":"SBSDKUILicensePlateScannerBehaviorConfiguration","abstract":[{"text":"Configuration for the behavior of the RTU-UI license plate scanner.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUILicensePlateScannerBehaviorConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerbehaviorconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerBehaviorConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUILicensePlateScannerBehaviorConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"behaviorConfiguration","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"behaviorConfiguration","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerBehaviorConfiguration","text":"SBSDKUILicensePlateScannerBehaviorConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerBehaviorConfiguration"},{"text":" * ","kind":"text"},{"text":"behaviorConfiguration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration\/title","op":"replace","value":"SBSDKUILicensePlateScannerConfiguration"},{"op":"replace","value":[{"text":"SBSDKUILicensePlateScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration\/fragments"},{"value":"behaviorConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration~1behaviorConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration~1behaviorConfiguration\/fragments","value":[{"text":"behaviorConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerBehaviorConfiguration\/title","value":"SBSDKUILicensePlateScannerBehaviorConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerBehaviorConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUILicensePlateScannerBehaviorConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}