{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"uiConfiguration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerUIConfiguration","text":"SBSDKUILicensePlateScannerUIConfiguration","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/uiConfiguration"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uiConfiguration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerUIConfiguration","text":"SBSDKUILicensePlateScannerUIConfiguration","kind":"typeIdentifier"}],"role":"symbol","title":"uiConfiguration","navigatorTitle":[{"kind":"identifier","text":"uiConfiguration"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerConfiguration(py)uiConfiguration"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","abstract":[{"text":"The user interface sub-configuration.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerconfiguration\/uiconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerconfiguration\/uiconfiguration"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerUIConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUILicensePlateScannerUIConfiguration","kind":"identifier"}],"title":"SBSDKUILicensePlateScannerUIConfiguration","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescanneruiconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerUIConfiguration","abstract":[{"text":"Configuration for the user interface look and feel of the RTU-UI license plate scanner.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUILicensePlateScannerUIConfiguration","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerConfiguration/uiConfiguration":{"type":"topic","title":"uiConfiguration","navigatorTitle":[{"kind":"identifier","text":"uiConfiguration"}],"abstract":[{"type":"text","text":"The user interface sub-configuration."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration\/uiConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerconfiguration\/uiconfiguration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uiConfiguration"},{"text":": ","kind":"text"},{"text":"SBSDKUILicensePlateScannerUIConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerUIConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerConfiguration":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerconfiguration","kind":"symbol","abstract":[{"text":"This class describes the look and feel, the behavior and the textual contents of the detection RTU-UI screen for license plate scanner.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerConfiguration","title":"SBSDKUILicensePlateScannerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUILicensePlateScannerConfiguration"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"uiConfiguration","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"uiConfiguration","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerUIConfiguration","text":"SBSDKUILicensePlateScannerUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerUIConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"uiConfiguration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerUIConfiguration\/title","value":"SBSDKUILicensePlateScannerUIConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerUIConfiguration\/fragments"},{"value":"uiConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration~1uiConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration~1uiConfiguration\/fragments","op":"replace","value":[{"text":"uiConfiguration","kind":"identifier"}]},{"value":"SBSDKUILicensePlateScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerConfiguration\/fragments","value":[{"text":"SBSDKUILicensePlateScannerConfiguration","kind":"identifier"}]}]}]}