{"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Timeouts(im)initWithAutoCancelTimeout:initialScanDelay:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithAutoCancelTimeout:initialScanDelay:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithAutoCancelTimeout:initialScanDelay:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"initWithAutoCancelTimeout:initialScanDelay:"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2timeouts\/initwithautocanceltimeout:initialscandelay:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Timeouts"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Timeouts\/initWithAutoCancelTimeout:initialScanDelay:","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithAutoCancelTimeout:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"autoCancelTimeout","kind":"internalParam"},{"kind":"text","text":" "},{"text":"initialScanDelay:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"initialScanDelay"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Timeouts/initWithAutoCancelTimeout:initialScanDelay:":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2timeouts\/initwithautocanceltimeout:initialscandelay:","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithAutoCancelTimeout:initialScanDelay:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Timeouts\/initWithAutoCancelTimeout:initialScanDelay:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithAutoCancelTimeout:initialScanDelay:","kind":"identifier"}],"title":"initWithAutoCancelTimeout:initialScanDelay:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Timeouts":{"abstract":[{"type":"text","text":"Configuration of timeouts."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2timeouts","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2Timeouts","kind":"identifier"}],"title":"SBSDKUI2Timeouts","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2Timeouts","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Timeouts"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Timeouts\/title","op":"replace","value":"SBSDKUI2Timeouts"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Timeouts\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Timeouts"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Timeouts\/navigatorTitle","value":[{"text":"SBSDKUI2Timeouts","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}