{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"barcodesExtensionFilter","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodesExtensionFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2BarcodesExtensionFilter","text":"SBSDKUI2BarcodesExtensionFilter"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Filter for extended EAN and UPC barcodes."},{"text":" ","type":"text"},{"type":"text","text":"Default is NO_FILTER"}],"sections":[],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"barcodesExtensionFilter","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodesExtensionFilter","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2BarcodesExtensionFilter"}],"navigatorTitle":[{"text":"barcodesExtensionFilter","kind":"identifier"}],"title":"barcodesExtensionFilter","symbolKind":"property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeRecognizerConfiguration(py)barcodesExtensionFilter"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcoderecognizerconfiguration\/barcodesextensionfilter"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcoderecognizerconfiguration\/barcodesextensionfilter"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/barcodesExtensionFilter"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeRecognizerConfiguration/barcodesExtensionFilter":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"barcodesExtensionFilter","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2BarcodesExtensionFilter","text":"SBSDKUI2BarcodesExtensionFilter","kind":"typeIdentifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"barcodesExtensionFilter","abstract":[{"type":"text","text":"Filter for extended EAN and UPC barcodes."},{"text":" ","type":"text"},{"text":"Default is NO_FILTER","type":"text"}],"navigatorTitle":[{"text":"barcodesExtensionFilter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/barcodesExtensionFilter","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcoderecognizerconfiguration\/barcodesextensionfilter"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeRecognizerConfiguration":{"abstract":[{"text":"Configuration of the scanning behavior.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}],"title":"SBSDKUI2BarcodeRecognizerConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcoderecognizerconfiguration","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodesExtensionFilter":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodesextensionfilter","title":"SBSDKUI2BarcodesExtensionFilter","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodesExtensionFilter","navigatorTitle":[{"text":"SBSDKUI2BarcodesExtensionFilter","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilter"}],"role":"symbol","abstract":[{"text":"Filter for extended EAN and UPC barcodes.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"barcodesExtensionFilter","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"barcodesExtensionFilter"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodesExtensionFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2BarcodesExtensionFilter","text":"SBSDKUI2BarcodesExtensionFilter"},{"text":" ","kind":"text"},{"text":"barcodesExtensionFilter","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1barcodesExtensionFilter\/title","value":"barcodesExtensionFilter","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"barcodesExtensionFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1barcodesExtensionFilter\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/title","value":"SBSDKUI2BarcodeRecognizerConfiguration","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/navigatorTitle"},{"value":"SBSDKUI2BarcodesExtensionFilter","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodesExtensionFilter\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodesExtensionFilter\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodesExtensionFilter\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}