{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"setStorageCryptingProviderWithProvider:error:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef(cm)setStorageCryptingProviderWithProvider:error:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"setStorageCryptingProvider(provider:)","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setStorageCryptingProvider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"provider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingProvider"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageref\/setstoragecryptingprovider(provider:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageref\/setstoragecryptingprovider(provider:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setStorageCryptingProvider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"provider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingProvider"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"]}]}],"abstract":[{"text":"Sets crypting provider that is used when an image is read\/written from\/to disk.","type":"text"},{"text":" ","type":"text"},{"text":"The provider is used both when images are hibernated and when they are saved\/loaded from disk with saveImage\/fromPath.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/setStorageCryptingProvider(provider:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef":{"abstract":[{"text":"Image ref class.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRef"}],"type":"topic","title":"SBSDKImageRef","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","url":"\/documentation\/scanbotsdk\/sbsdkimageref","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRef"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingProvider":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingProvider","title":"SBSDKStorageCryptingProvider","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingprovider","abstract":[{"text":"Protocol for providing a storage crypting object.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/setStorageCryptingProvider(provider:)":{"title":"setStorageCryptingProvider(provider:)","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/setstoragecryptingprovider(provider:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setStorageCryptingProvider"},{"kind":"text","text":"("},{"kind":"externalParam","text":"provider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCryptingProvider","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingProvider"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Sets crypting provider that is used when an image is read\/written from\/to disk."},{"type":"text","text":" "},{"type":"text","text":"The provider is used both when images are hibernated and when they are saved\/loaded from disk with saveImage\/fromPath."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/setStorageCryptingProvider(provider:)","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setStorageCryptingProviderWithProvider:error:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"setStorageCryptingProviderWithProvider:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"setStorageCryptingProviderWithProvider:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setStorageCryptingProviderWithProvider:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SBSDKStorageCryptingProvider>","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingProvider","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"provider","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKImageRef","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/title"},{"value":[{"text":"SBSDKImageRef","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/fragments"},{"value":[{"text":"SBSDKImageRef","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/navigatorTitle"},{"value":"SBSDKStorageCryptingProvider","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingProvider\/title"},{"value":[{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingProvider\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKStorageCryptingProvider"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingProvider\/navigatorTitle"},{"value":"setStorageCryptingProviderWithProvider:error:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1setStorageCryptingProvider(provider:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setStorageCryptingProviderWithProvider:error:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1setStorageCryptingProvider(provider:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}