{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"For binarized images only."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittrle"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions"]]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions\/ccittrle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions\/ccittrle"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ccittrle"}]}]}],"kind":"symbol","metadata":{"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKTIFFImageWriterCompressionOptions@SBSDKTIFFImageWriterCompressionOptionsCcittrle","title":"SBSDKTIFFImageWriterCompressionOptions.ccittrle","navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcittrle","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"ccittrle","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterCompressionOptions":{"navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions","title":"SBSDKTIFFImageWriterCompressionOptions","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"The TIFF compression algorithms.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterCompressionOptions/ccittrle":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittrle","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions\/ccittrle","title":"SBSDKTIFFImageWriterCompressionOptions.ccittrle","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ccittrle"}],"navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcittrle","kind":"identifier"}],"abstract":[{"text":"For binarized images only.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKTIFFImageWriterCompressionOptionsCcittrle","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsCcittrle"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsCcittrle"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions\/title","value":"SBSDKTIFFImageWriterCompressionOptions"},{"value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccittrle\/title","value":"SBSDKTIFFImageWriterCompressionOptionsCcittrle"},{"value":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcittrle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccittrle\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}