{"metadata":{"symbolKind":"case","title":"SBSDKTIFFImageWriterCompressionOptions.packbits","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"packbits","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptionsPackbits","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKTIFFImageWriterCompressionOptions@SBSDKTIFFImageWriterCompressionOptionsPackbits","roleHeading":"Case"},"abstract":[{"text":"For both colored and binarized images.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/packbits","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"packbits","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions\/packbits"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions\/packbits"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterCompressionOptions/packbits":{"navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptionsPackbits","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions\/packbits","kind":"symbol","type":"topic","title":"SBSDKTIFFImageWriterCompressionOptions.packbits","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"packbits"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions\/packbits","abstract":[{"text":"For both colored and binarized images.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterCompressionOptions":{"navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions","title":"SBSDKTIFFImageWriterCompressionOptions","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"The TIFF compression algorithms.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKTIFFImageWriterCompressionOptionsPackbits"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKTIFFImageWriterCompressionOptionsPackbits","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKTIFFImageWriterCompressionOptionsPackbits","kind":"identifier"}]}],"kind":"declarations"}},{"value":"SBSDKTIFFImageWriterCompressionOptionsPackbits","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1packbits\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions~1packbits\/fragments","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsPackbits"}]},{"value":"SBSDKTIFFImageWriterCompressionOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions\/title"},{"value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"}]}]}]}