{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerconfiguration\/behaviorconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerconfiguration\/behaviorconfiguration"]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","title":"behaviorConfiguration","navigatorTitle":[{"text":"behaviorConfiguration","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerConfiguration(py)behaviorConfiguration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"behaviorConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","kind":"typeIdentifier","text":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerConfiguration\/behaviorConfiguration","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"behaviorConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","kind":"typeIdentifier","text":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerBehaviorConfiguration"}]}]}],"abstract":[{"type":"text","text":"The configuration for the behavior."}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerConfiguration":{"abstract":[{"type":"text","text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI generic document recognizers screen."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerconfiguration","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerConfiguration","title":"SBSDKUIGenericDocumentRecognizerConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerConfiguration"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerBehaviorConfiguration":{"title":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","role":"symbol","abstract":[{"text":"The configuration for the behavior of the RTU-UI generic document recognizer.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerbehaviorconfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerConfiguration/behaviorConfiguration":{"type":"topic","title":"behaviorConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"behaviorConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"behaviorConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerConfiguration\/behaviorConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerconfiguration\/behaviorconfiguration","abstract":[{"type":"text","text":"The configuration for the behavior."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"behaviorConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"behaviorConfiguration","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","kind":"typeIdentifier","text":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerBehaviorConfiguration"},{"text":" * ","kind":"text"},{"text":"behaviorConfiguration","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerConfiguration\/title","value":"SBSDKUIGenericDocumentRecognizerConfiguration"},{"op":"replace","value":[{"text":"SBSDKUIGenericDocumentRecognizerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIGenericDocumentRecognizerConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerBehaviorConfiguration\/title","value":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerBehaviorConfiguration\/fragments","value":[{"text":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerBehaviorConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerConfiguration~1behaviorConfiguration\/title","value":"behaviorConfiguration"},{"value":[{"text":"behaviorConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerConfiguration~1behaviorConfiguration\/fragments"}]}]}