{"abstract":[{"type":"text","text":"Designated initializer."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:cameraconfiguration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:cameraconfiguration:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"uiConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"textConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerTextConfiguration","text":"SBSDKUIGenericDocumentRecognizerTextConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"behaviorConfiguration"},{"text":": ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerBehaviorConfiguration"},{"text":", ","kind":"text"},{"text":"cameraConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration","text":"SBSDKUICameraConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerConfiguration","isActive":true,"type":"reference"},{"type":"text","text":"."}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"uiConfiguration: A configuration for the user interface. Defines colors and sizes."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"textConfiguration: A configuration for the text being displayed in the scanner screen.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"behaviorConfiguration: A configuration for the scanners behavior.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"cameraConfiguration: A configuration for the scanners camera."}],"type":"paragraph"}]}],"type":"unorderedList"}],"kind":"content"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"uiConfiguration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerUIConfiguration","text":"SBSDKUIGenericDocumentRecognizerUIConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textConfiguration"},{"kind":"text","text":": "},{"text":"SBSDKUIGenericDocumentRecognizerTextConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerTextConfiguration"},{"kind":"text","text":", "},{"text":"behaviorConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerBehaviorConfiguration"},{"kind":"text","text":", "},{"text":"cameraConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration","kind":"typeIdentifier","text":"SBSDKUICameraConfiguration"},{"text":")","kind":"text"}],"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:","kind":"identifier"}],"title":"init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerConfiguration(im)initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:","symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerConfiguration":{"kind":"symbol","abstract":[{"text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI generic document recognizers screen.","type":"text"}],"title":"SBSDKUIGenericDocumentRecognizerConfiguration","navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerconfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIGenericDocumentRecognizerConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerConfiguration","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerBehaviorConfiguration":{"kind":"symbol","title":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerbehaviorconfiguration","navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","abstract":[{"text":"The configuration for the behavior of the RTU-UI generic document recognizer.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUICameraConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUICameraConfiguration","kind":"identifier"}],"title":"SBSDKUICameraConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicameraconfiguration","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configuration for the camera of all RTU-UI components."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerConfiguration/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"uiConfiguration"},{"text":": ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerUIConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerUIConfiguration"},{"text":", ","kind":"text"},{"text":"textConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerTextConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerTextConfiguration"},{"kind":"text","text":", "},{"text":"behaviorConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","text":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration","text":"SBSDKUICameraConfiguration"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:","kind":"identifier"}],"title":"init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:cameraconfiguration:)","abstract":[{"type":"text","text":"Designated initializer."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerUIConfiguration":{"title":"SBSDKUIGenericDocumentRecognizerUIConfiguration","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizeruiconfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerUIConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"The configuration for the user interface of the RTU-UI generic document recognizer screens."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerUIConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerTextConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerTextConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizertextconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerTextConfiguration"}],"abstract":[{"text":"The configuration for the textual contents of the RTU-UI generic document recognizer screen.","type":"text"}],"kind":"symbol","title":"SBSDKUIGenericDocumentRecognizerTextConfiguration","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithUiConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerUIConfiguration","text":"SBSDKUIGenericDocumentRecognizerUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerUIConfiguration"},{"kind":"text","text":" *) "},{"text":"uiConfiguration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"textConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerTextConfiguration","text":"SBSDKUIGenericDocumentRecognizerTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textConfiguration"},{"text":" ","kind":"text"},{"text":"behaviorConfiguration:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerBehaviorConfiguration"},{"text":" *) ","kind":"text"},{"text":"behaviorConfiguration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration","text":"SBSDKUICameraConfiguration"},{"kind":"text","text":" *) "},{"text":"cameraConfiguration","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerConfiguration\/title","value":"SBSDKUIGenericDocumentRecognizerConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerConfiguration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerBehaviorConfiguration\/title","value":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerBehaviorConfiguration\/fragments","value":[{"text":"SBSDKUIGenericDocumentRecognizerBehaviorConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraConfiguration\/title","value":"SBSDKUICameraConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUICameraConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)\/title","value":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"}]},{"value":"SBSDKUIGenericDocumentRecognizerUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerUIConfiguration\/fragments","value":[{"text":"SBSDKUIGenericDocumentRecognizerUIConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration\/title","value":"SBSDKUIGenericDocumentRecognizerTextConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerTextConfiguration"}]}]}]}