{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ThreeLineMRZFinderLayoutPreset"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2threelinemrzfinderlayoutpreset\/mrztextline1"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2threelinemrzfinderlayoutpreset\/mrztextline1"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mrzTextLine1"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is “I<USA2342353464<<<<<<<<<<<<<<<”"}]}],"kind":"content"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The first line of the MRZ text."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ThreeLineMRZFinderLayoutPreset\/mrzTextLine1","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ThreeLineMRZFinderLayoutPreset(py)mrzTextLine1","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrzTextLine1","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"mrzTextLine1","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"mrzTextLine1"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ThreeLineMRZFinderLayoutPreset/mrzTextLine1":{"role":"symbol","navigatorTitle":[{"text":"mrzTextLine1","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2threelinemrzfinderlayoutpreset\/mrztextline1","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mrzTextLine1","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The first line of the MRZ text."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ThreeLineMRZFinderLayoutPreset\/mrzTextLine1","type":"topic","kind":"symbol","title":"mrzTextLine1"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ThreeLineMRZFinderLayoutPreset":{"type":"topic","title":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","abstract":[{"text":"A ready-to-use preset 3-line text to be displayed.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ThreeLineMRZFinderLayoutPreset","navigatorTitle":[{"text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2threelinemrzfinderlayoutpreset"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"mrzTextLine1","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"mrzTextLine1","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"mrzTextLine1","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"value":"mrzTextLine1","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset~1mrzTextLine1\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset~1mrzTextLine1\/fragments","value":[{"text":"mrzTextLine1","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset\/fragments"},{"value":[{"text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset\/navigatorTitle","op":"replace"}]}]}