{"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerconfiguration\/initwithqualitythresholds:qualityindices:detectorientation:inspectsmalltext:maximagesize:minestimatednumberofsymbolsfordocument:processbytileconfiguration:minrequiredorientationconfidence:returnqualityheatmap:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithQualityThresholds:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKDocumentQualityThreshold *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"qualityThresholds"},{"text":" ","kind":"text"},{"text":"qualityIndices:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKDocumentQuality *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"qualityIndices","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"detectOrientation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"detectOrientation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"inspectSmallText:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"inspectSmallText","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maxImageSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"maxImageSize","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minEstimatedNumberOfSymbolsForDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"minEstimatedNumberOfSymbolsForDocument","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"processByTileConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProcessByTileConfiguration","text":"SBSDKProcessByTileConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration"},{"text":" *) ","kind":"text"},{"text":"processByTileConfiguration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minRequiredOrientationConfidence:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"minRequiredOrientationConfidence","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"returnQualityHeatmap:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"returnQualityHeatmap","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQualityAnalyzerConfiguration(im)initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:","kind":"identifier"}],"roleHeading":"Instance Method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzerConfiguration":{"title":"SBSDKDocumentQualityAnalyzerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Document Quality Analyzer configuration.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzerConfiguration/initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:":{"type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:","navigatorTitle":[{"text":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:","kind":"identifier"}],"title":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:","url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerconfiguration\/initwithqualitythresholds:qualityindices:detectorientation:inspectsmalltext:maximagesize:minestimatednumberofsymbolsfordocument:processbytileconfiguration:minrequiredorientationconfidence:returnqualityheatmap:","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessByTileConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"title":"SBSDKProcessByTileConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration","kind":"symbol","type":"topic","abstract":[{"text":"Configuration for processing image by tiles.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This can be used to make the document quality analyzer processing faster with lower memory consumption,"},{"type":"text","text":" "},{"type":"text","text":"but prediction can be less accurate."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKDocumentQualityAnalyzerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/title","op":"replace","value":"SBSDKProcessByTileConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKProcessByTileConfiguration"}]}]}]}