{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encryptionMode","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode","text":"SBSDKEncryptionMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKEncryptionMode","kind":"typeIdentifier"},{"text":" { get }","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKIndexedImageStorage(py)encryptionMode","navigatorTitle":[{"kind":"identifier","text":"encryptionMode"}],"modules":[{"name":"ScanbotSDK"}],"title":"encryptionMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKEncryptionMode","text":"SBSDKEncryptionMode"}],"role":"symbol"},"abstract":[{"type":"text","text":"The encryption mode for the stored images. Defaults to "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode\/disabled","type":"reference","isActive":true},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/encryptionmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/encryptionmode"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/encryptionMode","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/encryptionMode":{"navigatorTitle":[{"text":"encryptionMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/encryptionmode","kind":"symbol","role":"symbol","title":"encryptionMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/encryptionMode","abstract":[{"text":"The encryption mode for the stored images. Defaults to ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode\/disabled","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encryptionMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKEncryptionMode","text":"SBSDKEncryptionMode","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage":{"url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage","type":"topic","title":"SBSDKIndexedImageStorage","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage","abstract":[{"type":"text","text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class."},{"text":" ","type":"text"},{"text":"Manages images in an array-like fashion.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEncryptionMode/disabled":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}],"url":"\/documentation\/scanbotsdk\/sbsdkencryptionmode\/disabled","title":"SBSDKEncryptionMode.disabled","abstract":[{"text":"Encryption is not used when loading or saving images. Trying to load an encrypted image will fail.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode\/disabled","navigatorTitle":[{"kind":"identifier","text":"SBSDKEncryptionModeDisabled"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEncryptionMode":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode","url":"\/documentation\/scanbotsdk\/sbsdkencryptionmode","abstract":[{"text":"Encryption\/Decryption mode to be used when an image is loaded\/saved.","type":"text"}],"title":"SBSDKEncryptionMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEncryptionMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKEncryptionMode"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"encryptionMode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"encryptionMode","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKEncryptionMode","kind":"typeIdentifier","text":"SBSDKEncryptionMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptionMode"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1encryptionMode\/title","value":"encryptionMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1encryptionMode\/fragments","value":[{"text":"encryptionMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/title","value":"SBSDKIndexedImageStorage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/fragments","value":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode~1disabled\/title","value":"SBSDKEncryptionModeDisabled","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode~1disabled\/fragments","value":[{"kind":"identifier","text":"SBSDKEncryptionModeDisabled"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode\/title","value":"SBSDKEncryptionMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode\/fragments","value":[{"text":"SBSDKEncryptionMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKEncryptionMode"}],"op":"replace"}]}]}