{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoOrientation"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoorientation\/landscapeleft"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoorientation\/landscapeleft"]}],"kind":"symbol","abstract":[{"type":"text","text":"Landscape left orientation."}],"metadata":{"title":"SBSDKVideoOrientation.landscapeLeft","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscapeLeft"}],"navigatorTitle":[{"text":"SBSDKVideoOrientationLandscapeLeft","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKVideoOrientation@SBSDKVideoOrientationLandscapeLeft","symbolKind":"case","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoOrientation\/landscapeLeft","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"landscapeLeft","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoOrientation/landscapeLeft":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"landscapeLeft","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKVideoOrientationLandscapeLeft","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoOrientation\/landscapeLeft","abstract":[{"text":"Landscape left orientation.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoorientation\/landscapeleft","title":"SBSDKVideoOrientation.landscapeLeft","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoOrientation":{"title":"SBSDKVideoOrientation","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoorientation","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoOrientation"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoOrientation"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoOrientation","abstract":[{"type":"text","text":"An enum describing the orientation of a video frame."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKVideoOrientationLandscapeLeft","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKVideoOrientationLandscapeLeft"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKVideoOrientationLandscapeLeft","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKVideoOrientationLandscapeLeft","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoOrientation~1landscapeLeft\/title"},{"value":[{"kind":"identifier","text":"SBSDKVideoOrientationLandscapeLeft"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoOrientation~1landscapeLeft\/fragments"},{"value":"SBSDKVideoOrientation","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoOrientation\/title"},{"value":[{"text":"SBSDKVideoOrientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoOrientation\/fragments"},{"value":[{"text":"SBSDKVideoOrientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoOrientation\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}