{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"SBSDKVideoOrientationPortraitUpsideDown","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKVideoOrientation@SBSDKVideoOrientationPortraitUpsideDown","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portraitUpsideDown"}],"role":"symbol","symbolKind":"case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"SBSDKVideoOrientation.portraitUpsideDown"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoOrientation"]]},"abstract":[{"text":"Portrait upside down orientation.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"portraitUpsideDown","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoorientation\/portraitupsidedown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoorientation\/portraitupsidedown"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoOrientation\/portraitUpsideDown","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoOrientation":{"abstract":[{"type":"text","text":"An enum describing the orientation of a video frame."}],"navigatorTitle":[{"text":"SBSDKVideoOrientation","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoorientation","title":"SBSDKVideoOrientation","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoOrientation","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoOrientation","role":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoOrientation/portraitUpsideDown":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoOrientationPortraitUpsideDown"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoOrientation\/portraitUpsideDown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portraitUpsideDown"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoorientation\/portraitupsidedown","title":"SBSDKVideoOrientation.portraitUpsideDown","kind":"symbol","type":"topic","abstract":[{"text":"Portrait upside down orientation.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKVideoOrientationPortraitUpsideDown"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKVideoOrientationPortraitUpsideDown","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKVideoOrientationPortraitUpsideDown"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoOrientation\/title","op":"replace","value":"SBSDKVideoOrientation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoOrientation\/fragments","op":"replace","value":[{"text":"SBSDKVideoOrientation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoOrientation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoOrientation"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoOrientation~1portraitUpsideDown\/title","op":"replace","value":"SBSDKVideoOrientationPortraitUpsideDown"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoOrientation~1portraitUpsideDown\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoOrientationPortraitUpsideDown"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}