{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelboardingpass\/initwithgenericdocument:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelBoardingPass"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"method","title":"initWithGenericDocument:","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentModelBoardingPass(im)initWithGenericDocument:","fragments":[{"kind":"text","text":"- "},{"text":"initWithGenericDocument:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"initWithGenericDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocument","text":"SBSDKGenericDocument","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocument","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"document"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelBoardingPass\/initWithGenericDocument:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocument":{"type":"topic","title":"SBSDKGenericDocument","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocument","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocument","abstract":[{"type":"text","text":"Generic document."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocument","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelBoardingPass":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentModelBoardingPass","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelBoardingPass","kind":"identifier"}],"title":"SBSDKBarcodeDocumentModelBoardingPass","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelBoardingPass","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelboardingpass","abstract":[{"type":"text","text":"Boarding Pass"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelBoardingPass/initWithGenericDocument:":{"fragments":[{"kind":"text","text":"- "},{"text":"initWithGenericDocument:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelboardingpass\/initwithgenericdocument:","title":"initWithGenericDocument:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelBoardingPass\/initWithGenericDocument:","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKGenericDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/title"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/navigatorTitle","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelBoardingPass\/title","value":"SBSDKBarcodeDocumentModelBoardingPass","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelBoardingPass\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelBoardingPass"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelBoardingPass\/navigatorTitle","value":[{"text":"SBSDKBarcodeDocumentModelBoardingPass","kind":"identifier"}]}]}]}