{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameDuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"frameDuration","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","title":"frameDuration","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFrameLimiter(py)frameDuration","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/frameDuration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The minimum time in seconds that must pass by before processing the next frame (1.0 \/ fpsCount)."}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkframelimiter\/frameduration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkframelimiter\/frameduration"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameDuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"text":" { get }","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFrameLimiter":{"title":"SBSDKFrameLimiter","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKFrameLimiter"}],"url":"\/documentation\/scanbotsdk\/sbsdkframelimiter","abstract":[{"type":"text","text":"A frame limiter class. An object can use this class to limit the number of events fired per second."}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKFrameLimiter","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFrameLimiter/frameDuration":{"abstract":[{"type":"text","text":"The minimum time in seconds that must pass by before processing the next frame (1.0 \/ fpsCount)."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameDuration"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/frameDuration","role":"symbol","navigatorTitle":[{"text":"frameDuration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkframelimiter\/frameduration","title":"frameDuration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"frameDuration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"frameDuration","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"text":" ","kind":"text"},{"kind":"identifier","text":"frameDuration"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","value":"SBSDKFrameLimiter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter\/fragments","value":[{"text":"SBSDKFrameLimiter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter\/navigatorTitle","op":"replace","value":[{"text":"SBSDKFrameLimiter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter~1frameDuration\/title","value":"frameDuration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter~1frameDuration\/fragments","value":[{"kind":"identifier","text":"frameDuration"}],"op":"replace"}]}]}