{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkframelimiter\/init(fpscount:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkframelimiter\/init(fpscount:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"init(fpsCount:)","navigatorTitle":[{"kind":"identifier","text":"initWithFPSCount:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFrameLimiter(im)initWithFPSCount:","symbolKind":"init","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fpsCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Initializer"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/init(fpsCount:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithFPSCount:) ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"fpsCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"fpsCount","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The desired frame rate in frames per second."}]}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter"]]},"kind":"symbol","sections":[],"abstract":[{"text":"Creates a new instance of the frame limiter.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFrameLimiter":{"title":"SBSDKFrameLimiter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFrameLimiter"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFrameLimiter"}],"url":"\/documentation\/scanbotsdk\/sbsdkframelimiter","abstract":[{"type":"text","text":"A frame limiter class. An object can use this class to limit the number of events fired per second."}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFrameLimiter/init(fpsCount:)":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkframelimiter\/init(fpscount:)","title":"init(fpsCount:)","navigatorTitle":[{"text":"initWithFPSCount:","kind":"identifier"}],"abstract":[{"type":"text","text":"Creates a new instance of the frame limiter."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFrameLimiter\/init(fpsCount:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fpsCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithFPSCount:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithFPSCount:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFPSCount:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"fpsCount"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"fpsCount","content":[{"type":"paragraph","inlineContent":[{"text":"The desired frame rate in frames per second.","type":"text"}]}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter\/title","op":"replace","value":"SBSDKFrameLimiter"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter\/fragments","op":"replace","value":[{"text":"SBSDKFrameLimiter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter\/navigatorTitle","op":"replace","value":[{"text":"SBSDKFrameLimiter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter~1init(fpsCount:)\/title","op":"replace","value":"initWithFPSCount:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFrameLimiter~1init(fpsCount:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFPSCount:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}