{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithOverallConsistency:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKValueConsistency","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKValueConsistency"},{"text":") ","kind":"text"},{"text":"overallConsistency","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fieldDetails:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKFieldConsistencyVerificationReport *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"fieldDetails","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkconsistencyverificationreport\/initwithoverallconsistency:fielddetails:"]}],"metadata":{"title":"initWithOverallConsistency:fieldDetails:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOverallConsistency:fieldDetails:"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithOverallConsistency:fieldDetails:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKConsistencyVerificationReport(im)initWithOverallConsistency:fieldDetails:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport\/initWithOverallConsistency:fieldDetails:"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConsistencyVerificationReport":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport","abstract":[{"text":"Report of the document consistency verification. Shows whether information in the fields that correspond to the same","type":"text"},{"text":" ","type":"text"},{"text":"logical field is consistent.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkconsistencyverificationreport","navigatorTitle":[{"text":"SBSDKConsistencyVerificationReport","kind":"identifier"}],"type":"topic","title":"SBSDKConsistencyVerificationReport","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKConsistencyVerificationReport","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency":{"role":"symbol","abstract":[{"text":"The status of the consistency verification.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency","url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency","navigatorTitle":[{"text":"SBSDKValueConsistency","kind":"identifier"}],"type":"topic","title":"SBSDKValueConsistency","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKValueConsistency","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConsistencyVerificationReport/initWithOverallConsistency:fieldDetails:":{"kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOverallConsistency:fieldDetails:"}],"url":"\/documentation\/scanbotsdk\/sbsdkconsistencyverificationreport\/initwithoverallconsistency:fielddetails:","title":"initWithOverallConsistency:fieldDetails:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithOverallConsistency:fieldDetails:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport\/initWithOverallConsistency:fieldDetails:","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKConsistencyVerificationReport","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKConsistencyVerificationReport"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport\/fragments","op":"replace"},{"value":[{"text":"SBSDKConsistencyVerificationReport","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport\/navigatorTitle","op":"replace"},{"value":"SBSDKValueConsistency","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKValueConsistency"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/fragments","op":"replace"},{"value":[{"text":"SBSDKValueConsistency","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/navigatorTitle","op":"replace"}]}]}