{"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Case","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentDetectionStatus@SBSDKDocumentDetectionStatusOk","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ok","kind":"identifier"}],"title":"SBSDKDocumentDetectionStatus.ok","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk"}],"symbolKind":"case","role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus\/ok"},"abstract":[{"text":"An acceptable polygon was detected.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus\/ok"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus\/ok"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ok"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus"]]},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionStatus/ok":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ok"}],"type":"topic","abstract":[{"type":"text","text":"An acceptable polygon was detected."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus\/ok","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatusOk","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus\/ok","title":"SBSDKDocumentDetectionStatus.ok"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 5.0.0"}],"title":"ScanbotDocumentScannerSDK","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionStatus":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"title":"SBSDKDocumentDetectionStatus","abstract":[{"type":"text","text":"The status of the latest document detection."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKDocumentDetectionStatusOk"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk"}]}]},"op":"replace"},{"value":"SBSDKDocumentDetectionStatusOk","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus~1ok\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus~1ok\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus\/title","op":"replace","value":"SBSDKDocumentDetectionStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}