{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus"]]},"abstract":[{"text":"A polygon was detected, but it has too much perspective distortion.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus\/ok_badangles"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus\/ok_badangles"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"ok_BadAngles","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"SBSDKDocumentDetectionStatus.ok_BadAngles","role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ok_BadAngles"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentDetectionStatus@SBSDKDocumentDetectionStatusOk_BadAngles","symbolKind":"case","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatusOk_BadAngles","kind":"identifier"}]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus\/ok_BadAngles","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 5.2.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"abstract":[{"text":"The status of the latest document detection.","type":"text"}],"navigatorTitle":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus","title":"SBSDKDocumentDetectionStatus","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionStatus/ok_BadAngles":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus\/ok_BadAngles","abstract":[{"text":"A polygon was detected, but it has too much perspective distortion.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk_BadAngles"}],"type":"topic","kind":"symbol","title":"SBSDKDocumentDetectionStatus.ok_BadAngles","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ok_BadAngles"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus\/ok_badangles"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKDocumentDetectionStatusOk_BadAngles","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk_BadAngles"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKDocumentDetectionStatusOk_BadAngles","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus\/title","op":"replace","value":"SBSDKDocumentDetectionStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus\/fragments","value":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus~1ok_BadAngles\/title","op":"replace","value":"SBSDKDocumentDetectionStatusOk_BadAngles"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus~1ok_BadAngles\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk_BadAngles"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}