{"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentDetectionStatus@SBSDKDocumentDetectionStatusOk_BadAspectRatio","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"ok_BadAspectRatio","kind":"identifier"}],"title":"SBSDKDocumentDetectionStatus.ok_BadAspectRatio","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatusOk_BadAspectRatio","kind":"identifier"}],"symbolKind":"case"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus\/ok_BadAspectRatio","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"A polygon was detected, but its aspect ratio should be landscape\/portrait but is portrait\/landscape."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus\/ok_badaspectratio"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus\/ok_badaspectratio"]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ok_BadAspectRatio","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 5.0.0"}],"title":"ScanbotDocumentScannerSDK","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionStatus":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"title":"SBSDKDocumentDetectionStatus","abstract":[{"type":"text","text":"The status of the latest document detection."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionStatus/ok_BadAspectRatio":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ok_BadAspectRatio"}],"type":"topic","abstract":[{"type":"text","text":"A polygon was detected, but its aspect ratio should be landscape\/portrait but is portrait\/landscape."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus\/ok_BadAspectRatio","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk_BadAspectRatio"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus\/ok_badaspectratio","title":"SBSDKDocumentDetectionStatus.ok_BadAspectRatio"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKDocumentDetectionStatusOk_BadAspectRatio"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk_BadAspectRatio"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKDocumentDetectionStatusOk_BadAspectRatio","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus\/title","value":"SBSDKDocumentDetectionStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus\/fragments","value":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus~1ok_BadAspectRatio\/title","value":"SBSDKDocumentDetectionStatusOk_BadAspectRatio","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus~1ok_BadAspectRatio\/fragments","value":[{"text":"SBSDKDocumentDetectionStatusOk_BadAspectRatio","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}