{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkocrresultblock\/init(text:polygon:boundingboxwithimagesize:confidencevalue:blocktype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkocrresultblock\/init(text:polygon:boundingboxwithimagesize:confidencevalue:blocktype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock(im)initWithText:polygon:boundingBoxWithImageSize:confidenceValue:blockType:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"polygon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"kind":"text","text":", "},{"text":"boundingBoxWithImageSize","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"text":"confidenceValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"text":"blockType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKOCRResultBlockType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOCRResultBlockType"},{"text":")","kind":"text"}],"title":"init(text:polygon:boundingBoxWithImageSize:confidenceValue:blockType:)","navigatorTitle":[{"kind":"identifier","text":"initWithText:polygon:boundingBoxWithImageSize:confidenceValue:blockType:"}],"roleHeading":"Initializer","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock\/init(text:polygon:boundingBoxWithImageSize:confidenceValue:blockType:)"},"abstract":[{"text":"Designated initializer.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"polygon","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"boundingBoxWithImageSize","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"confidenceValue"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"blockType"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType","text":"SBSDKOCRResultBlockType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOCRResultBlockType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"text","content":[{"inlineContent":[{"text":"The recognized text within the receivers bounding box.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The bounding polygon of the receiver in normalized unit coordinate space."}],"type":"paragraph"}],"name":"polygon"},{"name":"boundingBoxWithImageSize","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The bounding box of the receiver in absolute image coordinate system."}]}]},{"name":"confidenceValue","content":[{"type":"paragraph","inlineContent":[{"text":"The confidence value describes how confident the OCR engine was when detecting the letters and words.","type":"text"}]}]},{"name":"blockType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of the block or text fragment."}]}]}]}],"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"abstract":[{"text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}.","type":"text"}],"title":"SBSDKPolygon","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPolygon"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlock":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKOCRResultBlock"}],"kind":"symbol","abstract":[{"text":"The partial result of an optical character recognition.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrresultblock","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCRResultBlock"}],"title":"SBSDKOCRResultBlock"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlock/init(text:polygon:boundingBoxWithImageSize:confidenceValue:blockType:)":{"role":"symbol","title":"init(text:polygon:boundingBoxWithImageSize:confidenceValue:blockType:)","navigatorTitle":[{"kind":"identifier","text":"initWithText:polygon:boundingBoxWithImageSize:confidenceValue:blockType:"}],"abstract":[{"type":"text","text":"Designated initializer."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock\/init(text:polygon:boundingBoxWithImageSize:confidenceValue:blockType:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"text","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"boundingBoxWithImageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":", ","kind":"text"},{"text":"confidenceValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"blockType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOCRResultBlockType","text":"SBSDKOCRResultBlockType"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrresultblock\/init(text:polygon:boundingboxwithimagesize:confidencevalue:blocktype:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlockType":{"url":"\/documentation\/scanbotsdk\/sbsdkocrresultblocktype","kind":"symbol","type":"topic","title":"SBSDKOCRResultBlockType","role":"symbol","navigatorTitle":[{"text":"SBSDKOCRResultBlockType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCRResultBlockType"}],"abstract":[{"type":"text","text":"The block type of an OCR fragment."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithText:polygon:boundingBoxWithImageSize:confidenceValue:blockType:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithText:polygon:boundingBoxWithImageSize:confidenceValue:blockType:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithText:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"text","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"polygon:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"polygon"},{"text":" ","kind":"text"},{"kind":"identifier","text":"boundingBoxWithImageSize:"},{"kind":"text","text":"("},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"boundingBoxWithImageSize","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidenceValue:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"confidenceValue","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"blockType:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOCRResultBlockType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType","text":"SBSDKOCRResultBlockType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"blockType","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"text","content":[{"inlineContent":[{"type":"text","text":"The recognized text within the receivers bounding box."}],"type":"paragraph"}]},{"name":"polygon","content":[{"type":"paragraph","inlineContent":[{"text":"The bounding polygon of the receiver in normalized unit coordinate space.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The bounding box of the receiver in absolute image coordinate system."}],"type":"paragraph"}],"name":"boundingBoxWithImageSize"},{"name":"confidenceValue","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The confidence value describes how confident the OCR engine was when detecting the letters and words."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The type of the block or text fragment.","type":"text"}]}],"name":"blockType"}]},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title","value":"SBSDKPolygon","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPolygon"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/navigatorTitle","value":[{"text":"SBSDKPolygon","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock\/title","value":"SBSDKOCRResultBlock"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock\/fragments","value":[{"text":"SBSDKOCRResultBlock","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKOCRResultBlock"}],"op":"replace"},{"op":"replace","value":"initWithText:polygon:boundingBoxWithImageSize:confidenceValue:blockType:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock~1init(text:polygon:boundingBoxWithImageSize:confidenceValue:blockType:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithText:polygon:boundingBoxWithImageSize:confidenceValue:blockType:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock~1init(text:polygon:boundingBoxWithImageSize:confidenceValue:blockType:)\/fragments"},{"op":"replace","value":"SBSDKOCRResultBlockType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType\/title"},{"op":"replace","value":[{"text":"SBSDKOCRResultBlockType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType\/navigatorTitle","value":[{"text":"SBSDKOCRResultBlockType","kind":"identifier"}]}]}]}