{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerUserGuidance\/statesTitles","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscanneruserguidance\/statestitles"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscanneruserguidance\/statestitles"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statesTitles"},{"text":": ","kind":"text"},{"text":"SBSDKUI2UserGuidanceStates","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceStates","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerUserGuidance"]]},"abstract":[{"text":"Configure the titles of the user guidance hints for different states.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerUserGuidance(py)statesTitles","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"statesTitles"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"statesTitles"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2UserGuidanceStates","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceStates"}],"symbolKind":"property","title":"statesTitles"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerUserGuidance/statesTitles":{"kind":"symbol","type":"topic","abstract":[{"text":"Configure the titles of the user guidance hints for different states.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneruserguidance\/statestitles","role":"symbol","navigatorTitle":[{"text":"statesTitles","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"statesTitles","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceStates","text":"SBSDKUI2UserGuidanceStates"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerUserGuidance\/statesTitles","title":"statesTitles"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerUserGuidance":{"abstract":[{"type":"text","text":"Configuration of the hints guiding users through the scanning process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2DocumentScannerUserGuidance"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneruserguidance","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerUserGuidance","title":"SBSDKUI2DocumentScannerUserGuidance","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerUserGuidance","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates","type":"topic","abstract":[{"text":"Configure the titles of the user guidance hints for different states.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates","title":"SBSDKUI2UserGuidanceStates"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"statesTitles"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"statesTitles","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceStates","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates","text":"SBSDKUI2UserGuidanceStates"},{"kind":"text","text":" * "},{"kind":"identifier","text":"statesTitles"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"statesTitles","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerUserGuidance~1statesTitles\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerUserGuidance~1statesTitles\/fragments","value":[{"text":"statesTitles","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerUserGuidance\/title","op":"replace","value":"SBSDKUI2DocumentScannerUserGuidance"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerUserGuidance\/fragments","op":"replace","value":[{"text":"SBSDKUI2DocumentScannerUserGuidance","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerUserGuidance"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerUserGuidance\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates\/title","value":"SBSDKUI2UserGuidanceStates","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates\/fragments","value":[{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceStates"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}