{"metadata":{"roleHeading":"Instance Property","title":"title","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"title"}],"role":"symbol","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerUserGuidance(py)title"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerUserGuidance"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscanneruserguidance\/title"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscanneruserguidance\/title"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerUserGuidance\/title","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configure the text style for the user guidance hints."}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerUserGuidance/title":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerUserGuidance\/title","kind":"symbol","title":"title","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Configure the text style for the user guidance hints."}],"navigatorTitle":[{"text":"title","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneruserguidance\/title"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerUserGuidance":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerUserGuidance","kind":"symbol","title":"SBSDKUI2DocumentScannerUserGuidance","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentScannerUserGuidance","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the hints guiding users through the scanning process."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerUserGuidance"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneruserguidance"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"role":"symbol","title":"SBSDKUI2StyledText"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"title","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"title","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"title"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerUserGuidance~1title\/title","op":"replace","value":"title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerUserGuidance~1title\/fragments","value":[{"text":"title","kind":"identifier"}]},{"op":"replace","value":"SBSDKUI2DocumentScannerUserGuidance","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerUserGuidance\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerUserGuidance\/fragments","op":"replace","value":[{"text":"SBSDKUI2DocumentScannerUserGuidance","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title","op":"replace","value":"SBSDKUI2StyledText"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"op":"replace"}]}]}