{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer"]]},"abstract":[{"text":"Synchronously recognizes the text orientation on an UIImage.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer\/recognizetextorientation(on:)-413mi"]},{"paths":["\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer\/recognizetextorientation(on:)-413mi"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(recognizeTextOrientationOnImage:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"recognizeTextOrientation","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"text":" ","kind":"text"},{"text":"image","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextOrientation","kind":"typeIdentifier","text":"SBSDKTextOrientation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextOrientation"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The image to recognize the text orientation on.","type":"text"}],"type":"paragraph"}],"name":"image"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"The recognized text orientation."}],"type":"paragraph"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer\/recognizeTextOrientation(on:)-413mi","interfaceLanguage":"swift"},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"recognizeTextOrientation","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"SBSDKTextOrientation","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextOrientation","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizer(im)recognizeTextOrientationOnImage:","symbolKind":"method","title":"recognizeTextOrientation(on:)","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"recognizeTextOrientationOnImage:","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizer":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}],"title":"SBSDKTextLayoutRecognizer","abstract":[{"type":"text","text":"Analyzes an image and returns basic text layout features."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizer/recognizeTextOrientation(on:)-413mi":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer\/recognizeTextOrientation(on:)-413mi","navigatorTitle":[{"text":"recognizeTextOrientationOnImage:","kind":"identifier"}],"title":"recognizeTextOrientation(on:)","role":"symbol","abstract":[{"type":"text","text":"Synchronously recognizes the text orientation on an UIImage."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"recognizeTextOrientation","kind":"identifier"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextOrientation","text":"SBSDKTextOrientation"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer\/recognizetextorientation(on:)-413mi"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextOrientation":{"navigatorTitle":[{"text":"SBSDKTextOrientation","kind":"identifier"}],"title":"SBSDKTextOrientation","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextOrientation","url":"\/documentation\/scanbotsdk\/sbsdktextorientation","abstract":[{"text":"An enum to describes the detected orientation of text in an image.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextOrientation","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"recognizeTextOrientationOnImage:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"recognizeTextOrientationOnImage:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextOrientation","kind":"typeIdentifier","text":"SBSDKTextOrientation","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextOrientation"},{"kind":"text","text":") "},{"text":"recognizeTextOrientationOnImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"SBSDKTextLayoutRecognizer","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/title","op":"replace"},{"value":[{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/fragments","op":"replace"},{"value":"recognizeTextOrientationOnImage:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer~1recognizeTextOrientation(on:)-413mi\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"recognizeTextOrientationOnImage:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer~1recognizeTextOrientation(on:)-413mi\/fragments"},{"op":"replace","value":"SBSDKTextOrientation","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextOrientation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKTextOrientation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextOrientation\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}