{"abstract":[{"text":"Asynchronously recognizes the text layout on an UIImage.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer\/recognizelayoutasync(on:)-7ce7h"]},{"paths":["\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer\/recognizelayoutasync(on:)-7ce7h"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer\/recognizeLayoutAsync(on:)-7ce7h"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(recognizeLayoutAsyncOnImage:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognizeLayoutAsync"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"image","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult","text":"SBSDKTextLayoutRecognizerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult"},{"kind":"text","text":"?"}]}]},{"parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image to recognize the text layout on."}]}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The result object of type "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult"},{"type":"text","text":" or "},{"code":"nil","type":"codeVoice"},{"text":" if the operation failed.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"In Swift language it is used with structured concurrency (async\/await).","type":"text"}]}]}],"metadata":{"title":"recognizeLayoutAsync(on:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizer(im)recognizeLayoutAsyncOnImage:completion:","navigatorTitle":[{"text":"recognizeLayoutAsyncOnImage:completion:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognizeLayoutAsync"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult","text":"SBSDKTextLayoutRecognizerResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"method","modules":[{"name":"ScanbotSDK"}]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizerResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTextLayoutRecognizerResult"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult","navigatorTitle":[{"text":"SBSDKTextLayoutRecognizerResult","kind":"identifier"}],"abstract":[{"text":"Represents a result of the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer","isActive":true,"type":"reference"},{"text":".","type":"text"}],"kind":"symbol","title":"SBSDKTextLayoutRecognizerResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizer/recognizeLayoutAsync(on:)-7ce7h":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"recognizeLayoutAsync","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult","text":"SBSDKTextLayoutRecognizerResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"recognizeLayoutAsyncOnImage:completion:","kind":"identifier"}],"type":"topic","title":"recognizeLayoutAsync(on:)","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer\/recognizelayoutasync(on:)-7ce7h","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer\/recognizeLayoutAsync(on:)-7ce7h","kind":"symbol","abstract":[{"type":"text","text":"Asynchronously recognizes the text layout on an UIImage."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizer":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTextLayoutRecognizer"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer","navigatorTitle":[{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}],"abstract":[{"text":"Analyzes an image and returns basic text layout features.","type":"text"}],"kind":"symbol","title":"SBSDKTextLayoutRecognizer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"recognizeLayoutAsyncOnImage:completion:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"recognizeLayoutAsyncOnImage:completion:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"recognizeLayoutAsyncOnImage:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult","kind":"typeIdentifier","text":"SBSDKTextLayoutRecognizerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult\/title","op":"replace","value":"SBSDKTextLayoutRecognizerResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKTextLayoutRecognizerResult"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer~1recognizeLayoutAsync(on:)-7ce7h\/title","value":"recognizeLayoutAsyncOnImage:completion:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer~1recognizeLayoutAsync(on:)-7ce7h\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"recognizeLayoutAsyncOnImage:completion:"}],"op":"replace"},{"value":"SBSDKTextLayoutRecognizer","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}