{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer"]]},"abstract":[{"text":"Asynchronously recognizes the text layout on an image at the specified file URL.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(recognizeLayoutAsyncOnImageUrl:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"recognizeLayoutAsync","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":" ","kind":"text"},{"text":"imageURL","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKTextLayoutRecognizerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The file url of the image to recognize the text layout on.","type":"text"}],"type":"paragraph"}],"name":"imageURL"}],"kind":"parameters"},{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The result object of type ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult"},{"text":" or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the operation failed.","type":"text"}]}],"kind":"content"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"In Swift language it is used with structured concurrency (async\/await).","type":"text"}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer\/recognizelayoutasync(on:)-2sm2a"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer\/recognizelayoutasync(on:)-2sm2a"]}],"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizer(im)recognizeLayoutAsyncOnImageUrl:completion:","navigatorTitle":[{"text":"recognizeLayoutAsyncOnImageUrl:completion:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"recognizeLayoutAsync","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult","text":"SBSDKTextLayoutRecognizerResult","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"recognizeLayoutAsync(on:)","symbolKind":"method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer\/recognizeLayoutAsync(on:)-2sm2a","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizer":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTextLayoutRecognizer"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer","navigatorTitle":[{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}],"abstract":[{"text":"Analyzes an image and returns basic text layout features.","type":"text"}],"kind":"symbol","title":"SBSDKTextLayoutRecognizer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizer/recognizeLayoutAsync(on:)-2sm2a":{"navigatorTitle":[{"kind":"identifier","text":"recognizeLayoutAsyncOnImageUrl:completion:"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer\/recognizelayoutasync(on:)-2sm2a","abstract":[{"type":"text","text":"Asynchronously recognizes the text layout on an image at the specified file URL."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"recognizeLayoutAsync","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult","text":"SBSDKTextLayoutRecognizerResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer\/recognizeLayoutAsync(on:)-2sm2a","title":"recognizeLayoutAsync(on:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizerResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTextLayoutRecognizerResult"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult","navigatorTitle":[{"text":"SBSDKTextLayoutRecognizerResult","kind":"identifier"}],"abstract":[{"text":"Represents a result of the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer","isActive":true,"type":"reference"},{"text":".","type":"text"}],"kind":"symbol","title":"SBSDKTextLayoutRecognizerResult"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"recognizeLayoutAsyncOnImageUrl:completion:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"recognizeLayoutAsyncOnImageUrl:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"recognizeLayoutAsyncOnImageUrl:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"imageURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult","text":"SBSDKTextLayoutRecognizerResult","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"SBSDKTextLayoutRecognizer","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKTextLayoutRecognizer"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/fragments"},{"op":"replace","value":"recognizeLayoutAsyncOnImageUrl:completion:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer~1recognizeLayoutAsync(on:)-2sm2a\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer~1recognizeLayoutAsync(on:)-2sm2a\/fragments","value":[{"text":"- ","kind":"text"},{"text":"recognizeLayoutAsyncOnImageUrl:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult\/title","op":"replace","value":"SBSDKTextLayoutRecognizerResult"},{"op":"replace","value":[{"text":"SBSDKTextLayoutRecognizerResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}