{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer\/recognizelayout(on:completion:)-827m7"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer\/recognizelayout(on:completion:)-827m7"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Asynchronously recognizes the text layout on an UIImage."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"title":"recognizeLayout(on:completion:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizer(im)recognizeLayoutOnImage:completion:","role":"symbol","navigatorTitle":[{"text":"recognizeLayoutOnImage:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recognizeLayout"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"SBSDKTextLayoutRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ())","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer\/recognizeLayout(on:completion:)-827m7"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(recognizeLayoutOnImage:completion:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognizeLayout","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"kind":"text","text":" "},{"kind":"internalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult","text":"SBSDKTextLayoutRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ())","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image to recognize the text layout on."}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The completion block that is called when the operation has finished."},{"text":" ","type":"text"},{"type":"text","text":"Delivers either the result or an error as a parameter to the main thread."}],"type":"paragraph"}]}],"kind":"parameters"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizer/recognizeLayout(on:completion:)-827m7":{"title":"recognizeLayout(on:completion:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer\/recognizeLayout(on:completion:)-827m7","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recognizeLayout"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"SBSDKTextLayoutRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ())","kind":"text"}],"navigatorTitle":[{"text":"recognizeLayoutOnImage:completion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Asynchronously recognizes the text layout on an UIImage."}],"url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer\/recognizelayout(on:completion:)-827m7"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizerResult":{"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult","type":"topic","title":"SBSDKTextLayoutRecognizerResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTextLayoutRecognizerResult"}],"navigatorTitle":[{"text":"SBSDKTextLayoutRecognizerResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult","abstract":[{"type":"text","text":"Represents a result of the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer"},{"type":"text","text":"."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizer":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer","title":"SBSDKTextLayoutRecognizer","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}],"abstract":[{"type":"text","text":"Analyzes an image and returns basic text layout features."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTextLayoutRecognizer"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"recognizeLayoutOnImage:completion:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"recognizeLayoutOnImage:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"recognizeLayoutOnImage:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult","text":"SBSDKTextLayoutRecognizerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"image","content":[{"inlineContent":[{"type":"text","text":"The image to recognize the text layout on."}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"The completion block that is called when the operation has finished.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Delivers either the result or an error as a parameter to the main thread."}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"recognizeLayoutOnImage:completion:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer~1recognizeLayout(on:completion:)-827m7\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer~1recognizeLayout(on:completion:)-827m7\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"recognizeLayoutOnImage:completion:"}],"op":"replace"},{"op":"replace","value":"SBSDKTextLayoutRecognizerResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult\/title"},{"value":[{"text":"SBSDKTextLayoutRecognizerResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKTextLayoutRecognizerResult"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/title","value":"SBSDKTextLayoutRecognizer"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/fragments","value":[{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}]},{"value":[{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/navigatorTitle","op":"replace"}]}]}