{"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizer(im)recognizeLayoutOnImageURL:completion:","symbolKind":"method","title":"recognizeLayout(on:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognizeLayout"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult","kind":"typeIdentifier","text":"SBSDKTextLayoutRecognizerResult"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ())","kind":"text"}],"navigatorTitle":[{"text":"recognizeLayoutOnImageURL:completion:","kind":"identifier"}]},"abstract":[{"type":"text","text":"Asynchronously recognizes the text layout on an image at the specified file URL."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(recognizeLayoutOnImageURL:completion:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recognizeLayout"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"imageURL","kind":"internalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"text":"SBSDKTextLayoutRecognizerResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ())","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"imageURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The file url of the image to recognize the text layout on."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The completion block that is called when the operation has finished.","type":"text"},{"text":" ","type":"text"},{"text":"Delivers either the result or an error as a parameter to the main thread.","type":"text"}]}],"name":"completion"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer\/recognizeLayout(on:completion:)-5iyok","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer\/recognizelayout(on:completion:)-5iyok"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer\/recognizelayout(on:completion:)-5iyok"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizerResult":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult","abstract":[{"type":"text","text":"Represents a result of the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer"},{"text":".","type":"text"}],"type":"topic","kind":"symbol","title":"SBSDKTextLayoutRecognizerResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKTextLayoutRecognizerResult","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKTextLayoutRecognizerResult","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizer":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer","abstract":[{"type":"text","text":"Analyzes an image and returns basic text layout features."}],"type":"topic","kind":"symbol","title":"SBSDKTextLayoutRecognizer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizer/recognizeLayout(on:completion:)-5iyok":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer\/recognizeLayout(on:completion:)-5iyok","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer\/recognizelayout(on:completion:)-5iyok","abstract":[{"text":"Asynchronously recognizes the text layout on an image at the specified file URL.","type":"text"}],"type":"topic","kind":"symbol","title":"recognizeLayout(on:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognizeLayout","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"SBSDKTextLayoutRecognizerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> ())"}],"navigatorTitle":[{"text":"recognizeLayoutOnImageURL:completion:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"recognizeLayoutOnImageURL:completion:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"recognizeLayoutOnImageURL:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"recognizeLayoutOnImageURL:"},{"text":"(","kind":"text"},{"text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"imageURL","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult","text":"SBSDKTextLayoutRecognizerResult","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult\/title","value":"SBSDKTextLayoutRecognizerResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult\/fragments","op":"replace","value":[{"text":"SBSDKTextLayoutRecognizerResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/title","value":"SBSDKTextLayoutRecognizer","op":"replace"},{"value":[{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer~1recognizeLayout(on:completion:)-5iyok\/title","value":"recognizeLayoutOnImageURL:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"recognizeLayoutOnImageURL:completion:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer~1recognizeLayout(on:completion:)-5iyok\/fragments"}]}]}