{"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer\/recognizetextorientation(on:)-7h6z0"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer\/recognizetextorientation(on:)-7h6z0"]}],"abstract":[{"type":"text","text":"Synchronously recognizes the text orientation on an image at the given URL."}],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizer(im)recognizeTextOrientationOnImageURL:","navigatorTitle":[{"text":"recognizeTextOrientationOnImageURL:","kind":"identifier"}],"title":"recognizeTextOrientation(on:)","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recognizeTextOrientation"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextOrientation","text":"SBSDKTextOrientation"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(recognizeTextOrientationOnImageURL:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognizeTextOrientation"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":" ","kind":"text"},{"text":"imageURL","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKTextOrientation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextOrientation","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextOrientation"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The file url of the image to recognize the text orientation on.","type":"text"}],"type":"paragraph"}],"name":"imageURL"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The recognized text orientation."}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer\/recognizeTextOrientation(on:)-7h6z0","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizer":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer","title":"SBSDKTextLayoutRecognizer","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer","abstract":[{"text":"Analyzes an image and returns basic text layout features.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizer/recognizeTextOrientation(on:)-7h6z0":{"url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer\/recognizetextorientation(on:)-7h6z0","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Synchronously recognizes the text orientation on an image at the given URL."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer\/recognizeTextOrientation(on:)-7h6z0","title":"recognizeTextOrientation(on:)","navigatorTitle":[{"kind":"identifier","text":"recognizeTextOrientationOnImageURL:"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"recognizeTextOrientation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":") -> "},{"text":"SBSDKTextOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextOrientation"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextOrientation":{"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextOrientation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTextOrientation"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextorientation","title":"SBSDKTextOrientation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextOrientation","abstract":[{"text":"An enum to describes the detected orientation of text in an image.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"recognizeTextOrientationOnImageURL:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"recognizeTextOrientationOnImageURL:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextOrientation","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextOrientation","text":"SBSDKTextOrientation"},{"text":") ","kind":"text"},{"text":"recognizeTextOrientationOnImageURL:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"imageURL"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"value":"SBSDKTextLayoutRecognizer","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/title","op":"replace"},{"value":[{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer~1recognizeTextOrientation(on:)-7h6z0\/title","value":"recognizeTextOrientationOnImageURL:"},{"value":[{"kind":"text","text":"- "},{"text":"recognizeTextOrientationOnImageURL:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer~1recognizeTextOrientation(on:)-7h6z0\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextOrientation\/title","op":"replace","value":"SBSDKTextOrientation"},{"op":"replace","value":[{"text":"SBSDKTextOrientation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextOrientation\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}