{"metadata":{"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKPageDirection@SBSDKPageDirectionPortrait","symbolKind":"case","title":"SBSDKPageDirection.portrait","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"portrait","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPageDirectionPortrait"}],"modules":[{"name":"ScanbotSDK"}]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpagedirection\/portrait"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagedirection\/portrait"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"portrait","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection\/portrait","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Portrait."}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageDirection/portrait":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection\/portrait","url":"\/documentation\/scanbotsdk\/sbsdkpagedirection\/portrait","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKPageDirectionPortrait","kind":"identifier"}],"abstract":[{"text":"Portrait.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"portrait","kind":"identifier"}],"title":"SBSDKPageDirection.portrait"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageDirection":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageDirection","url":"\/documentation\/scanbotsdk\/sbsdkpagedirection","kind":"symbol","type":"topic","title":"SBSDKPageDirection","abstract":[{"text":"Page direction.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPageDirection"}],"navigatorTitle":[{"text":"SBSDKPageDirection","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKPageDirectionPortrait"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKPageDirectionPortrait","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKPageDirectionPortrait","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKPageDirectionPortrait","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection~1portrait\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection~1portrait\/fragments","value":[{"kind":"identifier","text":"SBSDKPageDirectionPortrait"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection\/title","value":"SBSDKPageDirection","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPageDirection"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKPageDirection"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageDirection\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}