{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration\/validator"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration\/validator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration\/validator"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validator","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKContentValidator","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKContentValidator","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerConfiguration(py)validator","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"validator"}],"title":"validator","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"validator"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKContentValidator","kind":"typeIdentifier","text":"SBSDKContentValidator"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Content validator."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidator":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator","url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidator","title":"SBSDKContentValidator","navigatorTitle":[{"text":"SBSDKContentValidator","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKContentValidator","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Base class for content validators."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerConfiguration/validator":{"title":"validator","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration\/validator","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validator","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKContentValidator","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKContentValidator"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration\/validator","role":"symbol","navigatorTitle":[{"text":"validator","kind":"identifier"}],"abstract":[{"text":"Content validator.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerConfiguration":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextPatternScannerConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for the text pattern scanner."}],"role":"symbol","kind":"symbol","title":"SBSDKTextPatternScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration","navigatorTitle":[{"text":"SBSDKTextPatternScannerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"validator","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"validator","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKContentValidator","text":"SBSDKContentValidator","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"validator","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKContentValidator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKContentValidator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKContentValidator"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration~1validator\/title","value":"validator","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration~1validator\/fragments","value":[{"kind":"identifier","text":"validator"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/title","value":"SBSDKTextPatternScannerConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/navigatorTitle","value":[{"text":"SBSDKTextPatternScannerConfiguration","kind":"identifier"}],"op":"replace"}]}]}