{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2DocumentScannerViewController instead."}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerUIConfiguration\/isShutterButtonHidden"},"metadata":{"platforms":[],"title":"isShutterButtonHidden","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerUIConfiguration(py)isShutterButtonHidden","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isShutterButtonHidden","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isShutterButtonHidden"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerUIConfiguration"]]},"abstract":[{"type":"text","text":"Hides the shutter button if set to "},{"code":"True","type":"codeVoice"},{"text":". Shows it otherwise.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isShutterButtonHidden"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"True"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"If set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":", auto-snapping is enabled and the property"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/isAutoSnappingEnabled"},{"text":" of the behavior configuration will have no effect.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Also the auto-snapping button will be hidden."}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneruiconfiguration\/isshutterbuttonhidden"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneruiconfiguration\/isshutterbuttonhidden"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/isAutoSnappingEnabled":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/isAutoSnappingEnabled","title":"isAutoSnappingEnabled","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAutoSnappingEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isAutoSnappingEnabled"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/isautosnappingenabled","deprecated":true,"abstract":[{"text":"Whether auto-snapping is enabled or not.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerUIConfiguration":{"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerUIConfiguration","title":"SBSDKUIFinderDocumentScannerUIConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerUIConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerUIConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneruiconfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration for the user interface of the document scanning screen."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerUIConfiguration/isShutterButtonHidden":{"deprecated":true,"title":"isShutterButtonHidden","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerUIConfiguration\/isShutterButtonHidden","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneruiconfiguration\/isshutterbuttonhidden","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isShutterButtonHidden"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Hides the shutter button if set to "},{"code":"True","type":"codeVoice"},{"type":"text","text":". Shows it otherwise."}],"role":"symbol","navigatorTitle":[{"text":"isShutterButtonHidden","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"isShutterButtonHidden"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"isShutterButtonHidden","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isShutterButtonHidden"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"isAutoSnappingEnabled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1isAutoSnappingEnabled\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1isAutoSnappingEnabled\/fragments","value":[{"text":"isAutoSnappingEnabled","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKUIFinderDocumentScannerUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerUIConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerUIConfiguration\/fragments"},{"value":[{"text":"SBSDKUIFinderDocumentScannerUIConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerUIConfiguration\/navigatorTitle"},{"value":"isShutterButtonHidden","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerUIConfiguration~1isShutterButtonHidden\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerUIConfiguration~1isShutterButtonHidden\/fragments","op":"replace","value":[{"kind":"identifier","text":"isShutterButtonHidden"}]}]}]}