{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentRootType\/supportedBarcodeTypes(for:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentroottype\/supportedbarcodetypes(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentroottype\/supportedbarcodetypes(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"Retrieves the supported barcode types for a given array of barcode document formats.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"supportedBarcodeTypes","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":" ","kind":"text"},{"text":"documentFormats","kind":"internalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentRootType","kind":"typeIdentifier","text":"SBSDKBarcodeDocumentRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentRootType"},{"text":"]) -> [","kind":"text"},{"text":"SBSDKBarcodeType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeType","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeType"},{"kind":"text","text":"]"}]}]},{"kind":"parameters","parameters":[{"name":"documentFormats","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of barcode document formats."}]}]}]},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"text":"An array of supported barcode types.","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentRootType"]]},"metadata":{"navigatorTitle":[{"text":"supportedBarcodeTypesFor:","kind":"identifier"}],"roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentRootType(cm)supportedBarcodeTypesFor:","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"supportedBarcodeTypes","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SBSDKBarcodeDocumentRootType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentRootType"},{"text":"]) -> [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKBarcodeType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeType"},{"kind":"text","text":"]"}],"role":"symbol","title":"supportedBarcodeTypes(for:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeType":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeType"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetype","title":"SBSDKBarcodeType","abstract":[{"type":"text","text":"Class that represents a barcode type."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentRootType":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentroottype","title":"SBSDKBarcodeDocumentRootType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentRootType","abstract":[{"type":"text","text":"Root document type."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentRootType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentRootType","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentRootType/supportedBarcodeTypes(for:)":{"navigatorTitle":[{"kind":"identifier","text":"supportedBarcodeTypesFor:"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentroottype\/supportedbarcodetypes(for:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"supportedBarcodeTypes","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentRootType","text":"SBSDKBarcodeDocumentRootType"},{"kind":"text","text":"]) -> ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeType","kind":"typeIdentifier","text":"SBSDKBarcodeType"},{"text":"]","kind":"text"}],"type":"topic","role":"symbol","kind":"symbol","title":"supportedBarcodeTypes(for:)","abstract":[{"type":"text","text":"Retrieves the supported barcode types for a given array of barcode document formats."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentRootType\/supportedBarcodeTypes(for:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","value":"supportedBarcodeTypesFor:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"supportedBarcodeTypesFor:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<SBSDKBarcodeType *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"supportedBarcodeTypesFor:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<SBSDKBarcodeDocumentRootType *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"documentFormats","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKBarcodeType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeType\/title"},{"value":[{"text":"SBSDKBarcodeType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentRootType\/title","value":"SBSDKBarcodeDocumentRootType"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentRootType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentRootType\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentRootType~1supportedBarcodeTypes(for:)\/title","value":"supportedBarcodeTypesFor:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentRootType~1supportedBarcodeTypes(for:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"supportedBarcodeTypesFor:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}