{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessingqueuefactory\/serialtextprocessingqueue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessingqueuefactory\/serialtextprocessingqueue"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessingQueueFactory\/serialTextProcessingQueue"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessingQueueFactory"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"serialTextProcessingQueue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue","kind":"typeIdentifier"}]}],"kind":"declarations"}],"sections":[],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProcessingQueueFactory(cpy)serialTextProcessingQueue","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"serialTextProcessingQueue","kind":"identifier"},{"kind":"text","text":": "},{"text":"DispatchQueue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"}],"roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"serialTextProcessingQueue"}],"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"serialTextProcessingQueue","symbolKind":"property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The serial text processing queue."},{"type":"text","text":" "},{"type":"text","text":"If you perform additonal tasks that consume a lot of CPU power you should consider using this queue."},{"type":"text","text":" "},{"type":"text","text":"Otherwise text processing operations can take a very long time."}],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProcessingQueueFactory":{"kind":"symbol","title":"SBSDKProcessingQueueFactory","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessingQueueFactory"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessingQueueFactory","abstract":[{"type":"text","text":"Factory class providing different instances of"},{"code":"NSOperationQueue","type":"codeVoice"},{"type":"text","text":" to work on."},{"type":"text","text":" "},{"type":"text","text":"There are 2 main queues:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessingqueuefactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKProcessingQueueFactory","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.1.1","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProcessingQueueFactory/serialTextProcessingQueue":{"kind":"symbol","type":"topic","title":"serialTextProcessingQueue","navigatorTitle":[{"text":"serialTextProcessingQueue","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessingQueueFactory\/serialTextProcessingQueue","abstract":[{"text":"The serial text processing queue.","type":"text"},{"text":" ","type":"text"},{"text":"If you perform additonal tasks that consume a lot of CPU power you should consider using this queue.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Otherwise text processing operations can take a very long time."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessingqueuefactory\/serialtextprocessingqueue","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"serialTextProcessingQueue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"value":"serialTextProcessingQueue","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"serialTextProcessingQueue"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue","text":"NSObject<OS_dispatch_queue>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"serialTextProcessingQueue"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessingQueueFactory\/title","op":"replace","value":"SBSDKProcessingQueueFactory"},{"value":[{"kind":"identifier","text":"SBSDKProcessingQueueFactory"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessingQueueFactory\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKProcessingQueueFactory"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessingQueueFactory\/navigatorTitle","op":"replace"},{"op":"replace","value":"serialTextProcessingQueue","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessingQueueFactory~1serialTextProcessingQueue\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessingQueueFactory~1serialTextProcessingQueue\/fragments","value":[{"kind":"identifier","text":"serialTextProcessingQueue"}]}]}]}