{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serialImageProcessingQueue","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSOperationQueue","kind":"typeIdentifier","text":"OperationQueue"}],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessingqueuefactory\/serialimageprocessingqueue"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessingqueuefactory\/serialimageprocessingqueue"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessingQueueFactory"]]},"sections":[],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProcessingQueueFactory(cpy)serialImageProcessingQueue","title":"serialImageProcessingQueue","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"serialImageProcessingQueue","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSOperationQueue","kind":"typeIdentifier","text":"OperationQueue"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Type Property","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"serialImageProcessingQueue","kind":"identifier"}]},"abstract":[{"type":"text","text":"The serial image processing queue."},{"text":" ","type":"text"},{"text":"If you do additional image processing on large images or other tasks that consumes a lot of memory.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"it is highly recommended to use this queue."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessingQueueFactory\/serialImageProcessingQueue","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProcessingQueueFactory":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessingqueuefactory","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessingQueueFactory","abstract":[{"type":"text","text":"Factory class providing different instances of"},{"type":"codeVoice","code":"NSOperationQueue"},{"text":" to work on.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"There are 2 main queues:"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProcessingQueueFactory","kind":"identifier"}],"title":"SBSDKProcessingQueueFactory","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKProcessingQueueFactory","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProcessingQueueFactory/serialImageProcessingQueue":{"kind":"symbol","role":"symbol","title":"serialImageProcessingQueue","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"serialImageProcessingQueue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSOperationQueue","text":"OperationQueue"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessingqueuefactory\/serialimageprocessingqueue","abstract":[{"text":"The serial image processing queue.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If you do additional image processing on large images or other tasks that consumes a lot of memory."},{"text":" ","type":"text"},{"text":"it is highly recommended to use this queue.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessingQueueFactory\/serialImageProcessingQueue","navigatorTitle":[{"kind":"identifier","text":"serialImageProcessingQueue"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"value":"serialImageProcessingQueue","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"serialImageProcessingQueue","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSOperationQueue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSOperationQueue"},{"kind":"text","text":" * "},{"kind":"identifier","text":"serialImageProcessingQueue"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessingQueueFactory\/title","value":"SBSDKProcessingQueueFactory"},{"op":"replace","value":[{"text":"SBSDKProcessingQueueFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessingQueueFactory\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessingQueueFactory\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKProcessingQueueFactory"}]},{"value":"serialImageProcessingQueue","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessingQueueFactory~1serialImageProcessingQueue\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessingQueueFactory~1serialImageProcessingQueue\/fragments","op":"replace","value":[{"kind":"identifier","text":"serialImageProcessingQueue"}]}]}]}