{"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"streamingCryptCompleteWithError:"}],"role":"symbol","roleHeading":"Instance Method","title":"streamingCryptCompleteWithError:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"streamingCryptCompleteWithError:"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAESGCMEncrypter(im)streamingCryptCompleteWithError:","symbolKind":"method"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkaesgcmencrypter\/streamingcryptcompletewitherror:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESGCMEncrypter"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"streamingCryptCompleteWithError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESGCMEncrypter\/streamingCryptCompleteWithError:","interfaceLanguage":"occ"},"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAESGCMEncrypter":{"title":"SBSDKAESGCMEncrypter","type":"topic","navigatorTitle":[{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"A data encrypter implementing the AES128-GCM and AES256-GCM standards, with a configurable encryption key provider.","type":"text"},{"text":" ","type":"text"},{"text":"Supports encryption and decryption of single data blocks as well as streaming data.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaesgcmencrypter","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESGCMEncrypter"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.0","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAESGCMEncrypter/streamingCryptCompleteWithError:":{"fragments":[{"text":"- ","kind":"text"},{"text":"streamingCryptCompleteWithError:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaesgcmencrypter\/streamingcryptcompletewitherror:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESGCMEncrypter\/streamingCryptCompleteWithError:","kind":"symbol","title":"streamingCryptCompleteWithError:","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"text":"streamingCryptCompleteWithError:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESGCMEncrypter\/title","value":"SBSDKAESGCMEncrypter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESGCMEncrypter\/fragments","value":[{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESGCMEncrypter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKAESGCMEncrypter"}]}]}]}