{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"initWithSelectedZoomFactor:items:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSelectedZoomFactor:items:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerUIResult(im)initWithSelectedZoomFactor:items:","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithSelectedZoomFactor:items:"}]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithSelectedZoomFactor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"selectedZoomFactor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"items:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKUI2BarcodeScannerUIItem *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"items","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerUIResult"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerUIResult\/initWithSelectedZoomFactor:items:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescanneruiresult\/initwithselectedzoomfactor:items:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerUIResult/initWithSelectedZoomFactor:items:":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescanneruiresult\/initwithselectedzoomfactor:items:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerUIResult\/initWithSelectedZoomFactor:items:","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithSelectedZoomFactor:items:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSelectedZoomFactor:items:"}],"title":"initWithSelectedZoomFactor:items:","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerUIResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerUIResult","abstract":[{"type":"text","text":"Results of the barcode scan."}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescanneruiresult","role":"symbol","title":"SBSDKUI2BarcodeScannerUIResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerUIResult"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeScannerUIResult"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2BarcodeScannerUIResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerUIResult\/title"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeScannerUIResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerUIResult\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeScannerUIResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerUIResult\/navigatorTitle"}]}]}