{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2actionbarconfiguration\/flipcamerabutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2actionbarconfiguration\/flipcamerabutton"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration"]]},"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"flipCameraButton"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ActionBarConfiguration(py)flipCameraButton","roleHeading":"Instance Property","title":"flipCameraButton","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"flipCameraButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2RoundButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Appearance of the flip camera button."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"flipCameraButton","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton","text":"SBSDKUI2RoundButton","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration\/flipCameraButton"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ActionBarConfiguration/flipCameraButton":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"flipCameraButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration\/flipCameraButton","url":"\/documentation\/scanbotsdk\/sbsdkui2actionbarconfiguration\/flipcamerabutton","navigatorTitle":[{"text":"flipCameraButton","kind":"identifier"}],"title":"flipCameraButton","abstract":[{"type":"text","text":"Appearance of the flip camera button."}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2RoundButton":{"title":"SBSDKUI2RoundButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2RoundButton","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton","url":"\/documentation\/scanbotsdk\/sbsdkui2roundbutton","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the round button."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2RoundButton","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ActionBarConfiguration":{"title":"SBSDKUI2ActionBarConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ActionBarConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2actionbarconfiguration","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the buttons available in the action bar."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2ActionBarConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"flipCameraButton","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"flipCameraButton"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton","kind":"typeIdentifier","text":"SBSDKUI2RoundButton"},{"kind":"text","text":" * "},{"kind":"identifier","text":"flipCameraButton"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration~1flipCameraButton\/title","op":"replace","value":"flipCameraButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration~1flipCameraButton\/fragments","op":"replace","value":[{"kind":"identifier","text":"flipCameraButton"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2RoundButton\/title","value":"SBSDKUI2RoundButton"},{"value":[{"text":"SBSDKUI2RoundButton","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2RoundButton\/fragments"},{"op":"replace","value":"SBSDKUI2ActionBarConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration\/title"},{"value":[{"text":"SBSDKUI2ActionBarConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration\/fragments","op":"replace"}]}]}