{"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"flashButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"zoomButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton"},{"text":", ","kind":"text"},{"text":"flipCameraButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2RoundButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton"},{"kind":"text","text":")"}],"title":"init(flashButton:zoomButton:flipCameraButton:)","role":"symbol","roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"initWithFlashButton:zoomButton:flipCameraButton:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ActionBarConfiguration(im)initWithFlashButton:zoomButton:flipCameraButton:"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration\/init(flashButton:zoomButton:flipCameraButton:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"flashButton","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton","kind":"typeIdentifier","text":"SBSDKUI2RoundButton"},{"kind":"text","text":" = SBSDKUI2RoundButton(visible: true,\n                                                                       backgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                      isArgb: false),\n                                                                       foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                      isArgb: false),\n                                                                       activeBackgroundColor: SBSDKUI2Color(colorString: \"?sbColorWarning\",\n                                                                                                            isArgb: false),\n                                                                       activeForegroundColor: SBSDKUI2Color(colorString: \"#1C1B1F\",\n                                                                                                            isArgb: false)), "},{"text":"zoomButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton","text":"SBSDKUI2RoundButton"},{"kind":"text","text":" = SBSDKUI2RoundButton(visible: true,\n                                                                      backgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                     isArgb: false),\n                                                                      foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                     isArgb: false),\n                                                                      activeBackgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                           isArgb: false),\n                                                                      activeForegroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                           isArgb: false)), "},{"kind":"externalParam","text":"flipCameraButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2RoundButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton"},{"text":" = SBSDKUI2RoundButton(visible: true,\n                                                                            backgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                           isArgb: false),\n                                                                            foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                           isArgb: false),\n                                                                            activeBackgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                                 isArgb: false),\n                                                                            activeForegroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                 isArgb: false)))","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2actionbarconfiguration\/init(flashbutton:zoombutton:flipcamerabutton:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2actionbarconfiguration\/init(flashbutton:zoombutton:flipcamerabutton:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ActionBarConfiguration/init(flashButton:zoomButton:flipCameraButton:)":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2actionbarconfiguration\/init(flashbutton:zoombutton:flipcamerabutton:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration\/init(flashButton:zoomButton:flipCameraButton:)","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"flashButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoomButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton","text":"SBSDKUI2RoundButton","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"flipCameraButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton","text":"SBSDKUI2RoundButton","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithFlashButton:zoomButton:flipCameraButton:","kind":"identifier"}],"role":"symbol","title":"init(flashButton:zoomButton:flipCameraButton:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ActionBarConfiguration":{"title":"SBSDKUI2ActionBarConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2actionbarconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ActionBarConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ActionBarConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the buttons available in the action bar."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2RoundButton":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2roundbutton","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2RoundButton"}],"abstract":[{"text":"Configuration of the round button.","type":"text"}],"type":"topic","title":"SBSDKUI2RoundButton","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2RoundButton"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithFlashButton:zoomButton:flipCameraButton:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFlashButton:zoomButton:flipCameraButton:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithFlashButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton","text":"SBSDKUI2RoundButton"},{"kind":"text","text":" *) "},{"text":"flashButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"zoomButton:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton","text":"SBSDKUI2RoundButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zoomButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"flipCameraButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton","kind":"typeIdentifier","text":"SBSDKUI2RoundButton"},{"text":" *) ","kind":"text"},{"text":"flipCameraButton","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithFlashButton:zoomButton:flipCameraButton:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration~1init(flashButton:zoomButton:flipCameraButton:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"initWithFlashButton:zoomButton:flipCameraButton:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration~1init(flashButton:zoomButton:flipCameraButton:)\/fragments"},{"value":"SBSDKUI2ActionBarConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration\/fragments","value":[{"text":"SBSDKUI2ActionBarConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2ActionBarConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2RoundButton\/title","value":"SBSDKUI2RoundButton","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2RoundButton\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2RoundButton"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2RoundButton\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2RoundButton","kind":"identifier"}]}]}]}