{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerScreenConfiguration(py)confirmationAlertDialogEnabled","title":"confirmationAlertDialogEnabled","navigatorTitle":[{"text":"confirmationAlertDialogEnabled","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmationAlertDialogEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"ScanbotSDK"}]},"abstract":[{"type":"text","text":"If the confirmation alert dialog is enabled."}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenConfiguration\/confirmationAlertDialogEnabled","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreenconfiguration\/confirmationalertdialogenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreenconfiguration\/confirmationalertdialogenabled"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmationAlertDialogEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is false"}]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2VINScannerScreenConfiguration","kind":"identifier"}],"title":"SBSDKUI2VINScannerScreenConfiguration","type":"topic","navigatorTitle":[{"text":"SBSDKUI2VINScannerScreenConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreenconfiguration","abstract":[{"type":"text","text":"Configuration of the screen for detecting VIN data."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenConfiguration/confirmationAlertDialogEnabled":{"navigatorTitle":[{"kind":"identifier","text":"confirmationAlertDialogEnabled"}],"title":"confirmationAlertDialogEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmationAlertDialogEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreenconfiguration\/confirmationalertdialogenabled","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenConfiguration\/confirmationAlertDialogEnabled","role":"symbol","abstract":[{"text":"If the confirmation alert dialog is enabled.","type":"text"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"confirmationAlertDialogEnabled","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"confirmationAlertDialogEnabled"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"confirmationAlertDialogEnabled","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2VINScannerScreenConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2VINScannerScreenConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2VINScannerScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenConfiguration\/navigatorTitle","op":"replace"},{"value":"confirmationAlertDialogEnabled","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenConfiguration~1confirmationAlertDialogEnabled\/title","op":"replace"},{"value":[{"kind":"identifier","text":"confirmationAlertDialogEnabled"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenConfiguration~1confirmationAlertDialogEnabled\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}