{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithBarcodes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKBarcodeItem *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"barcodes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"success:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"success","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithBarcodes:success:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithBarcodes:success:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult(im)initWithBarcodes:success:","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"initWithBarcodes:success:"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/initwithbarcodes:success:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/initWithBarcodes:success:"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult":{"title":"SBSDKBarcodeScannerResult","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"abstract":[{"type":"text","text":"The result of barcode scanning."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/initWithBarcodes:success:":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBarcodes:success:"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/initwithbarcodes:success:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/initWithBarcodes:success:","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBarcodes:success:"}],"title":"initWithBarcodes:success:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"value":"SBSDKBarcodeScannerResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/title"},{"value":[{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}