{"abstract":[{"text":"Maximum text length. 0 implies no maximum. Applied only to linear barcode formats that allow variable length.","type":"text"}],"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCode11Configuration(py)maximumTextLength","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maximumTextLength"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"text":"maximumTextLength","kind":"identifier"}],"title":"maximumTextLength","symbolKind":"property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode11Configuration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maximumTextLength"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Default is 0","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode11configuration\/maximumtextlength"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode11configuration\/maximumtextlength"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode11Configuration\/maximumTextLength"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode11Configuration/maximumTextLength":{"navigatorTitle":[{"kind":"identifier","text":"maximumTextLength"}],"title":"maximumTextLength","abstract":[{"type":"text","text":"Maximum text length. 0 implies no maximum. Applied only to linear barcode formats that allow variable length."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumTextLength"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode11configuration\/maximumtextlength","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode11Configuration\/maximumTextLength"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode11Configuration":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode11configuration","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode11Configuration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode11Configuration"}],"title":"SBSDKBarcodeFormatCode11Configuration","role":"symbol","abstract":[{"text":"Code 11 barcode configuration. Add to scanner configuration to scan Code 11 barcodes.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatCode11Configuration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"maximumTextLength"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"maximumTextLength"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumTextLength"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode11Configuration~1maximumTextLength\/title","value":"maximumTextLength"},{"value":[{"text":"maximumTextLength","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode11Configuration~1maximumTextLength\/fragments"},{"op":"replace","value":"SBSDKBarcodeFormatCode11Configuration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode11Configuration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode11Configuration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode11Configuration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode11Configuration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatCode11Configuration","kind":"identifier"}],"op":"replace"}]}]}