{"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"borderWidthFraction"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKGrayscaleFilter(py)borderWidthFraction","navigatorTitle":[{"text":"borderWidthFraction","kind":"identifier"}],"symbolKind":"property","title":"borderWidthFraction"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"borderWidthFraction"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter\/borderWidthFraction","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter"]]},"sections":[],"abstract":[{"type":"text","text":"Ignore this fraction of pixels at the edge of the image when calculating statistics."},{"text":" ","type":"text"},{"text":"Pixels at the edge of the image typically have poor statistics. Ignoring them","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and using only the inner pixels when calculating certain statistics can"},{"text":" ","type":"text"},{"text":"substantially improve the quality of the result.","type":"text"},{"type":"text","text":" "},{"text":"The value must be less than 0.5 but usually good values are between 0 and 0.15.","type":"text"},{"text":" ","type":"text"},{"text":"Default is 0.06","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkgrayscalefilter\/borderwidthfraction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkgrayscalefilter\/borderwidthfraction"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKGrayscaleFilter/borderWidthFraction":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"borderWidthFraction","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"borderWidthFraction"}],"type":"topic","title":"borderWidthFraction","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter\/borderWidthFraction","abstract":[{"type":"text","text":"Ignore this fraction of pixels at the edge of the image when calculating statistics."},{"text":" ","type":"text"},{"type":"text","text":"Pixels at the edge of the image typically have poor statistics. Ignoring them"},{"type":"text","text":" "},{"type":"text","text":"and using only the inner pixels when calculating certain statistics can"},{"type":"text","text":" "},{"type":"text","text":"substantially improve the quality of the result."},{"text":" ","type":"text"},{"text":"The value must be less than 0.5 but usually good values are between 0 and 0.15.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is 0.06"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkgrayscalefilter\/borderwidthfraction"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKGrayscaleFilter":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkgrayscalefilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGrayscaleFilter"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter","abstract":[{"type":"text","text":"Converts color images to grayscale and applies autocontrast."}],"title":"SBSDKGrayscaleFilter","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKGrayscaleFilter","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"borderWidthFraction","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"borderWidthFraction","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"borderWidthFraction","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter~1borderWidthFraction\/title","op":"replace","value":"borderWidthFraction"},{"value":[{"text":"borderWidthFraction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter~1borderWidthFraction\/fragments"},{"value":"SBSDKGrayscaleFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter\/title"},{"value":[{"text":"SBSDKGrayscaleFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter\/fragments"},{"value":[{"text":"SBSDKGrayscaleFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}