{"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"whiteOutliersFraction"}],"symbolKind":"property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"whiteOutliersFraction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"title":"whiteOutliersFraction","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKGrayscaleFilter(py)whiteOutliersFraction"},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter\/whiteOutliersFraction","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter"]]},"sections":[],"abstract":[{"type":"text","text":"Clip this fraction of the brightest pixels in operations such as autocontrast."},{"type":"text","text":" "},{"type":"text","text":"Increasing the range of middle gray levels at the expense of the brightest and darkest levels"},{"type":"text","text":" "},{"type":"text","text":"may improve the overall contrast and quality of the result."},{"type":"text","text":" "},{"type":"text","text":"Sum of blackOutliersFraction and whiteOutliersFraction must be less than 1 but usually"},{"type":"text","text":" "},{"type":"text","text":"good values for the parameters do not exceed 0.05;"},{"type":"text","text":" "},{"type":"text","text":"Default is 0.02"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"whiteOutliersFraction"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkgrayscalefilter\/whiteoutliersfraction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkgrayscalefilter\/whiteoutliersfraction"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKGrayscaleFilter":{"abstract":[{"text":"Converts color images to grayscale and applies autocontrast.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkgrayscalefilter","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGrayscaleFilter","kind":"identifier"}],"role":"symbol","title":"SBSDKGrayscaleFilter","navigatorTitle":[{"text":"SBSDKGrayscaleFilter","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKGrayscaleFilter/whiteOutliersFraction":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"whiteOutliersFraction","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkgrayscalefilter\/whiteoutliersfraction","title":"whiteOutliersFraction","kind":"symbol","abstract":[{"text":"Clip this fraction of the brightest pixels in operations such as autocontrast.","type":"text"},{"text":" ","type":"text"},{"text":"Increasing the range of middle gray levels at the expense of the brightest and darkest levels","type":"text"},{"text":" ","type":"text"},{"text":"may improve the overall contrast and quality of the result.","type":"text"},{"text":" ","type":"text"},{"text":"Sum of blackOutliersFraction and whiteOutliersFraction must be less than 1 but usually","type":"text"},{"text":" ","type":"text"},{"text":"good values for the parameters do not exceed 0.05;","type":"text"},{"text":" ","type":"text"},{"text":"Default is 0.02","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter\/whiteOutliersFraction","type":"topic","navigatorTitle":[{"text":"whiteOutliersFraction","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.2.0","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"whiteOutliersFraction","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"whiteOutliersFraction","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"whiteOutliersFraction","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKGrayscaleFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter\/title"},{"value":[{"kind":"identifier","text":"SBSDKGrayscaleFilter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKGrayscaleFilter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter\/navigatorTitle"},{"value":"whiteOutliersFraction","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter~1whiteOutliersFraction\/title"},{"value":[{"kind":"identifier","text":"whiteOutliersFraction"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter~1whiteOutliersFraction\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}