{"abstract":[{"text":"Configuration for how to accumulate results.","type":"text"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resultAccumulationConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKResultAccumulationConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKResultAccumulationConfiguration"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","title":"resultAccumulationConfig","navigatorTitle":[{"text":"resultAccumulationConfig","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerConfiguration(py)resultAccumulationConfig","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscannerconfiguration\/resultaccumulationconfig"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscannerconfiguration\/resultaccumulationconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration\/resultAccumulationConfig"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resultAccumulationConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKResultAccumulationConfiguration","text":"SBSDKResultAccumulationConfiguration"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerConfiguration":{"title":"SBSDKCreditCardScannerConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCreditCardScannerConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCreditCardScannerConfiguration"}],"abstract":[{"text":"Configuration for the credit card scanner.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerconfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResultAccumulationConfiguration":{"abstract":[{"type":"text","text":"Configuration for how to accumulate results."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkresultaccumulationconfiguration","title":"SBSDKResultAccumulationConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerConfiguration/resultAccumulationConfig":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultAccumulationConfig"},{"kind":"text","text":": "},{"text":"SBSDKResultAccumulationConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKResultAccumulationConfiguration"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration\/resultAccumulationConfig","abstract":[{"text":"Configuration for how to accumulate results.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerconfiguration\/resultaccumulationconfig","navigatorTitle":[{"kind":"identifier","text":"resultAccumulationConfig"}],"title":"resultAccumulationConfig"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"resultAccumulationConfig","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"resultAccumulationConfig","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKResultAccumulationConfiguration","text":"SBSDKResultAccumulationConfiguration"},{"text":" * ","kind":"text"},{"text":"resultAccumulationConfig","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKCreditCardScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCreditCardScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/fragments"},{"value":[{"text":"SBSDKCreditCardScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/title","op":"replace","value":"SBSDKResultAccumulationConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/navigatorTitle","value":[{"text":"SBSDKResultAccumulationConfiguration","kind":"identifier"}],"op":"replace"},{"value":"resultAccumulationConfig","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration~1resultAccumulationConfig\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration~1resultAccumulationConfig\/fragments","value":[{"text":"resultAccumulationConfig","kind":"identifier"}],"op":"replace"}]}]}