{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontrollerdelegate\/checkscannerviewcontroller(_:didchangestate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontrollerdelegate\/checkscannerviewcontroller(_:didchangestate:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCheckScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didChangeState","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"state","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCheckScannerState","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerState","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckScannerState","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The check scanner viewController that changed its state."}],"type":"paragraph"}],"name":"controller"},{"content":[{"inlineContent":[{"type":"text","text":"The current state of the check scanner."}],"type":"paragraph"}],"name":"state"}],"kind":"parameters"}],"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkScannerViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController","text":"SBSDKCheckScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckScannerState","text":"SBSDKCheckScannerState"},{"kind":"text","text":")"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"checkScannerViewController:didChangeState:"}],"title":"checkScannerViewController(_:didChangeState:)","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKCheckScannerViewControllerDelegate(im)checkScannerViewController:didChangeState:"},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate\/checkScannerViewController(_:didChangeState:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Informs the delegate, that the check scanner has changed its scanning state. Optional."}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewControllerDelegate/checkScannerViewController(_:didChangeState:)":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontrollerdelegate\/checkscannerviewcontroller(_:didchangestate:)","type":"topic","abstract":[{"type":"text","text":"Informs the delegate, that the check scanner has changed its scanning state. Optional."}],"title":"checkScannerViewController(_:didChangeState:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKCheckScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController"},{"text":", ","kind":"text"},{"text":"didChangeState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCheckScannerState","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckScannerState"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"checkScannerViewController:didChangeState:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate\/checkScannerViewController(_:didChangeState:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerState":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerState","abstract":[{"type":"text","text":"The live scanning state of the check scanner."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerstate","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckScannerState","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKCheckScannerState","kind":"identifier"}],"type":"topic","title":"SBSDKCheckScannerState"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewController":{"title":"SBSDKCheckScannerViewController","abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan bank checks."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","navigatorTitle":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewControllerDelegate":{"abstract":[{"type":"text","text":"The delegation protocol for the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController"},{"type":"text","text":" class."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate","type":"topic","title":"SBSDKCheckScannerViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckScannerViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckScannerViewControllerDelegate"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontrollerdelegate","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"checkScannerViewController:didChangeState:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"checkScannerViewController:didChangeState:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"checkScannerViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKCheckScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didChangeState:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckScannerState","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerState","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckScannerState","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"state","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The check scanner viewController that changed its state."}],"type":"paragraph"}],"name":"controller"},{"content":[{"inlineContent":[{"text":"The current state of the check scanner.","type":"text"}],"type":"paragraph"}],"name":"state"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate~1checkScannerViewController(_:didChangeState:)\/title","op":"replace","value":"checkScannerViewController:didChangeState:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkScannerViewController:didChangeState:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate~1checkScannerViewController(_:didChangeState:)\/fragments","op":"replace"},{"value":"SBSDKCheckScannerState","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerState\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCheckScannerState"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerState\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCheckScannerState"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerState\/navigatorTitle","op":"replace"},{"value":"SBSDKCheckScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCheckScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/fragments","op":"replace"},{"value":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/navigatorTitle","op":"replace"},{"value":"SBSDKCheckScannerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate\/title","op":"replace"},{"value":[{"text":"SBSDKCheckScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCheckScannerViewControllerDelegate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate\/navigatorTitle","op":"replace"}]}]}