{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/isEqual:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"title":"isEqual:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZFinderLayoutPreset(im)isEqual:","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset/isEqual:":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/isequal:","role":"symbol","title":"isEqual:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}],"abstract":[{"type":"text","text":"Source of the text for the MRZ finder example overlay."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset","kind":"symbol","title":"SBSDKUI2MRZFinderLayoutPreset"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/title","op":"replace","value":"SBSDKUI2MRZFinderLayoutPreset"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2MRZFinderLayoutPreset","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}