{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotSDKConfiguration\/fileStorageBaseDirectory"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fileStorageBaseDirectory","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/scanbotsdkconfiguration\/filestoragebasedirectory"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/scanbotsdkconfiguration\/filestoragebasedirectory"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotSDKConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The base directory for storing scanned files. Defaults to "},{"type":"codeVoice","code":"nil"},{"text":", which uses the application’s documents directory.","type":"text"}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"fileStorageBaseDirectory"}],"externalID":"c:@M@ScanbotSDK@objc(cs)ScanbotSDKConfiguration(py)fileStorageBaseDirectory","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileStorageBaseDirectory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"title":"fileStorageBaseDirectory","symbolKind":"property","role":"symbol"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/ScanbotSDKConfiguration/fileStorageBaseDirectory":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fileStorageBaseDirectory"}],"type":"topic","title":"fileStorageBaseDirectory","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"fileStorageBaseDirectory","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/scanbotsdkconfiguration\/filestoragebasedirectory","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotSDKConfiguration\/fileStorageBaseDirectory","abstract":[{"text":"The base directory for storing scanned files. Defaults to ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":", which uses the application’s documents directory."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/ScanbotSDKConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"ScanbotSDKConfiguration"}],"title":"ScanbotSDKConfiguration","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotSDKConfiguration","abstract":[{"type":"codeVoice","code":"ScanbotSDKConfiguration"},{"type":"text","text":" is a configuration class that allows you to customize various settings and behavior of the Scanbot SDK."}],"url":"\/documentation\/scanbotsdk\/scanbotsdkconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanbotSDKConfiguration"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"fileStorageBaseDirectory","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"fileStorageBaseDirectory"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"fileStorageBaseDirectory","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotSDKConfiguration~1fileStorageBaseDirectory\/title","value":"fileStorageBaseDirectory","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotSDKConfiguration~1fileStorageBaseDirectory\/fragments","value":[{"text":"fileStorageBaseDirectory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotSDKConfiguration\/title","value":"ScanbotSDKConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotSDKConfiguration\/fragments","value":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}