{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)ScanbotSDKConfiguration(py)licenseLoggingEnabled","navigatorTitle":[{"kind":"identifier","text":"licenseLoggingEnabled"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"licenseLoggingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"licenseLoggingEnabled"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotSDKConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotSDKConfiguration\/licenseLoggingEnabled"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"licenseLoggingEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/scanbotsdkconfiguration\/licenseloggingenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/scanbotsdkconfiguration\/licenseloggingenabled"]}],"abstract":[{"type":"text","text":"A Boolean value that controls whether license-related logs are enabled. Defaults to "},{"code":"True","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/ScanbotSDKConfiguration/licenseLoggingEnabled":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"licenseLoggingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"licenseLoggingEnabled"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotSDKConfiguration\/licenseLoggingEnabled","abstract":[{"type":"text","text":"A Boolean value that controls whether license-related logs are enabled. Defaults to "},{"code":"True","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/scanbotsdkconfiguration\/licenseloggingenabled","kind":"symbol","title":"licenseLoggingEnabled"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/ScanbotSDKConfiguration":{"title":"ScanbotSDKConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotSDKConfiguration","role":"symbol","navigatorTitle":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"abstract":[{"code":"ScanbotSDKConfiguration","type":"codeVoice"},{"text":" is a configuration class that allows you to customize various settings and behavior of the Scanbot SDK.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/scanbotsdkconfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanbotSDKConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"licenseLoggingEnabled"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"licenseLoggingEnabled","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"licenseLoggingEnabled","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotSDKConfiguration~1licenseLoggingEnabled\/title","value":"licenseLoggingEnabled","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotSDKConfiguration~1licenseLoggingEnabled\/fragments","value":[{"kind":"identifier","text":"licenseLoggingEnabled"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotSDKConfiguration\/title","op":"replace","value":"ScanbotSDKConfiguration"},{"value":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotSDKConfiguration\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}