{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Configuration of the barcode info box displayed in the camera preview.","type":"text"}],"sections":[],"metadata":{"navigatorTitle":[{"text":"barcodeItemConfiguration","kind":"identifier"}],"symbolKind":"property","title":"barcodeItemConfiguration","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeItemConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeItemConfiguration","kind":"typeIdentifier","text":"SBSDKUI2BarcodeItemConfiguration"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration(py)barcodeItemConfiguration"},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayGeneralConfiguration\/barcodeItemConfiguration","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaygeneralconfiguration\/barcodeitemconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaygeneralconfiguration\/barcodeitemconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeItemConfiguration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeItemConfiguration","text":"SBSDKUI2BarcodeItemConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemConfiguration","kind":"typeIdentifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayGeneralConfiguration"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayGeneralConfiguration/barcodeItemConfiguration":{"abstract":[{"text":"Configuration of the barcode info box displayed in the camera preview.","type":"text"}],"type":"topic","kind":"symbol","title":"barcodeItemConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayGeneralConfiguration\/barcodeItemConfiguration","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeItemConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeItemConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeItemConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaygeneralconfiguration\/barcodeitemconfiguration","navigatorTitle":[{"text":"barcodeItemConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeItemConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemConfiguration","title":"SBSDKUI2BarcodeItemConfiguration","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the barcode info box displayed in the camera preview."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeitemconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeItemConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayGeneralConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"text":"Configuration of the AR overlay displayed on top of barcodes in the camera preview.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayGeneralConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaygeneralconfiguration","title":"SBSDKUI2ArOverlayGeneralConfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 6.1.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"barcodeItemConfiguration","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"barcodeItemConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKUI2BarcodeItemConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeItemConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"barcodeItemConfiguration"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"barcodeItemConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayGeneralConfiguration~1barcodeItemConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayGeneralConfiguration~1barcodeItemConfiguration\/fragments","value":[{"text":"barcodeItemConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemConfiguration\/title","value":"SBSDKUI2BarcodeItemConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}]},{"op":"replace","value":"SBSDKUI2ArOverlayGeneralConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}],"op":"replace"}]}]}