{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiverIBAN"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdksepadocumentfieldtype\/receiveriban"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdksepadocumentfieldtype\/receiveriban"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSEPADocumentFieldType\/receiverIBAN","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The receiver’s IBAN."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiverIBAN"}],"title":"SBSDKSEPADocumentFieldType.receiverIBAN","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKSEPADocumentFieldType@SBSDKSEPADocumentFieldTypeReceiverIBAN","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeReceiverIBAN"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSEPADocumentFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSEPADocumentFieldType/receiverIBAN":{"role":"symbol","title":"SBSDKSEPADocumentFieldType.receiverIBAN","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiverIBAN"}],"abstract":[{"type":"text","text":"The receiver’s IBAN."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSEPADocumentFieldType\/receiverIBAN","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeReceiverIBAN"}],"url":"\/documentation\/scanbotsdk\/sbsdksepadocumentfieldtype\/receiveriban"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSEPADocumentFieldType":{"role":"symbol","title":"SBSDKSEPADocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSEPADocumentFieldType"}],"abstract":[{"type":"text","text":"The SEPA document field types."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSEPADocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdksepadocumentfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKSEPADocumentFieldTypeReceiverIBAN"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeReceiverIBAN"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeReceiverIBAN"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSEPADocumentFieldType~1receiverIBAN\/title","value":"SBSDKSEPADocumentFieldTypeReceiverIBAN"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSEPADocumentFieldType~1receiverIBAN\/fragments","value":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldTypeReceiverIBAN"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSEPADocumentFieldType\/title","value":"SBSDKSEPADocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSEPADocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKSEPADocumentFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}