{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataframeextractionparameters\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"SBSDKDocumentDataFrameExtractionParameters","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataFrameExtractionParameters","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataFrameExtractionParameters"},{"kind":"text","text":" *) "},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataFrameExtractionParameters"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataFrameExtractionParameters(cm)fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"roleHeading":"Type Method","role":"symbol","symbolKind":"method","title":"fromJsonWithJson:","modules":[{"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataFrameExtractionParameters\/fromJsonWithJson:","interfaceLanguage":"occ"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataFrameExtractionParameters":{"title":"SBSDKDocumentDataFrameExtractionParameters","abstract":[{"type":"text","text":"Parameters for the extraction process."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataframeextractionparameters","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataFrameExtractionParameters","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataFrameExtractionParameters"}],"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataFrameExtractionParameters"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataFrameExtractionParameters/fromJsonWithJson:":{"abstract":[],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataFrameExtractionParameters\/fromJsonWithJson:","role":"symbol","title":"fromJsonWithJson:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataframeextractionparameters\/fromjsonwithjson:","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataFrameExtractionParameters\/title","value":"SBSDKDocumentDataFrameExtractionParameters"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataFrameExtractionParameters\/fragments","value":[{"text":"SBSDKDocumentDataFrameExtractionParameters","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataFrameExtractionParameters\/navigatorTitle","value":[{"text":"SBSDKDocumentDataFrameExtractionParameters","kind":"identifier"}]}]}]}