{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageInfo"}],"title":"SBSDKImageInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageInfo"}],"roleHeading":"Class","role":"symbol","symbolKind":"class","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageInfo"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageinfo"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Image Info.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKImageInfo) "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKImageInfo","kind":"identifier"}]}],"kind":"declarations"}],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/height","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/maxByteSize","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/width"],"generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/toJson(configuration:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageInfo/hash":{"title":"hash","role":"symbol","type":"topic","fragments":[{"text":"hash","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageinfo\/hash","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/hash"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageInfo/toJson(configuration:)":{"navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"title":"toJson(configuration:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageinfo\/tojson(configuration:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/toJson(configuration:)","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageInfo/height":{"navigatorTitle":[{"text":"height","kind":"identifier"}],"title":"height","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageinfo\/height","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/height","abstract":[{"text":"Image height in pixels.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageInfo":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageInfo","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo","role":"symbol","abstract":[{"type":"text","text":"Image Info."}],"title":"SBSDKImageInfo","navigatorTitle":[{"text":"SBSDKImageInfo","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageinfo"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageInfo/width":{"navigatorTitle":[{"text":"width","kind":"identifier"}],"title":"width","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageinfo\/width","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/width","abstract":[{"text":"Image width in pixels.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageInfo/copyWithZone:":{"type":"topic","title":"copyWithZone:","kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageinfo\/copywithzone:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSCopying":{"title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageInfo/maxByteSize":{"type":"topic","title":"maxByteSize","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxByteSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageinfo\/maxbytesize","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/maxByteSize","navigatorTitle":[{"text":"maxByteSize","kind":"identifier"}],"abstract":[{"text":"Byte size of the non-hibernating image.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageInfo/isEqual:":{"type":"topic","title":"isEqual:","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageinfo\/isequal:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/isEqual:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotDocumentScannerSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageInfo/fromJsonWithJson:":{"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"title":"fromJsonWithJson:","kind":"symbol","type":"topic","fragments":[{"kind":"text","text":"+ "},{"text":"fromJsonWithJson:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageinfo\/fromjsonwithjson:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/fromJsonWithJson:","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageInfo/initWithHeight:width:maxByteSize:":{"type":"topic","title":"initWithHeight:width:maxByteSize:","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithHeight:width:maxByteSize:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageinfo\/initwithheight:width:maxbytesize:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/initWithHeight:width:maxByteSize:","navigatorTitle":[{"text":"initWithHeight:width:maxByteSize:","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKImageInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageInfo"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKImageInfo","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/hash","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/height","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/maxByteSize","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/width"]},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/copyWithZone:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/initWithHeight:width:maxByteSize:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/isEqual:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/toJson(configuration:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageInfo\/fromJsonWithJson:"],"title":"Type Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying"],"title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"SBSDKImageInfo","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageInfo~1toJson(configuration:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageInfo~1toJson(configuration:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageInfo~1height\/title","value":"height"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageInfo~1height\/fragments","op":"replace","value":[{"text":"height","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageInfo\/title","op":"replace","value":"SBSDKImageInfo"},{"op":"replace","value":[{"text":"SBSDKImageInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageInfo\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageInfo~1width\/title","value":"width"},{"value":[{"text":"width","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageInfo~1width\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageInfo~1maxByteSize\/title","value":"maxByteSize","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageInfo~1maxByteSize\/fragments","value":[{"kind":"identifier","text":"maxByteSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}