{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"text":"json","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"partial"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true)"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerConfiguration\/init(json:partial:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","roleHeading":"Initializer","title":"init(json:partial:)","externalID":"c:@CM@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerConfiguration(im)initWithJson:partial:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"json","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"partial"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"symbolKind":"init","extendedModule":"ScanbotDocumentScannerSDK","navigatorTitle":[{"text":"initWithJson:partial:","kind":"identifier"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerconfiguration\/init(json:partial:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerconfiguration\/init(json:partial:)"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerConfiguration/init(json:partial:)":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"json","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"partial"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerConfiguration\/init(json:partial:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithJson:partial:"}],"title":"init(json:partial:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerconfiguration\/init(json:partial:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerConfiguration","abstract":[{"text":"This class describes the look and feel, the behavior, as well as the textual contents of the detection screen for documents.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerConfiguration"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerconfiguration","title":"SBSDKUIFinderDocumentScannerConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 5.0.2","type":"text"}],"role":"collection","type":"topic","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithJson:partial:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithJson:partial:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithJson:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"kind":"text","text":" "},{"text":"partial:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"partial"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerConfiguration~1init(json:partial:)\/title","op":"replace","value":"initWithJson:partial:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithJson:partial:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerConfiguration~1init(json:partial:)\/fragments"},{"value":"SBSDKUIFinderDocumentScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerConfiguration\/fragments","value":[{"text":"SBSDKUIFinderDocumentScannerConfiguration","kind":"identifier"}]}]}]}