{"sections":[],"abstract":[{"type":"text","text":"The quad of barcode is interpolated by the camera movement. This option is recommended when the camera is"},{"type":"text","text":" "},{"type":"text","text":"moving, but the scanned object is not."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeAccumulationMethod"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeaccumulationmethod\/interpolatebycamera"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeaccumulationmethod\/interpolatebycamera"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"case","roleHeading":"Case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"SBSDKBarcodeAccumulationMethod.interpolateByCamera","navigatorTitle":[{"text":"SBSDKBarcodeAccumulationMethodInterpolateByCamera","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"interpolateByCamera","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodeAccumulationMethod@SBSDKBarcodeAccumulationMethodInterpolateByCamera","role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeAccumulationMethod\/interpolateByCamera","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interpolateByCamera","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeAccumulationMethod/interpolateByCamera":{"abstract":[{"text":"The quad of barcode is interpolated by the camera movement. This option is recommended when the camera is","type":"text"},{"type":"text","text":" "},{"type":"text","text":"moving, but the scanned object is not."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeAccumulationMethodInterpolateByCamera","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeaccumulationmethod\/interpolatebycamera","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeAccumulationMethod\/interpolateByCamera","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interpolateByCamera","kind":"identifier"}],"type":"topic","title":"SBSDKBarcodeAccumulationMethod.interpolateByCamera"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeAccumulationMethod":{"abstract":[{"type":"text","text":"The method how to display barcodes from previous frames."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeAccumulationMethod","kind":"identifier"}],"role":"symbol","title":"SBSDKBarcodeAccumulationMethod","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethod"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeaccumulationmethod","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeAccumulationMethod","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodeAccumulationMethodInterpolateByCamera"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKBarcodeAccumulationMethodInterpolateByCamera","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKBarcodeAccumulationMethodInterpolateByCamera","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAccumulationMethod~1interpolateByCamera\/title","value":"SBSDKBarcodeAccumulationMethodInterpolateByCamera","op":"replace"},{"value":[{"text":"SBSDKBarcodeAccumulationMethodInterpolateByCamera","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAccumulationMethod~1interpolateByCamera\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAccumulationMethod\/title","value":"SBSDKBarcodeAccumulationMethod"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethod"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAccumulationMethod\/fragments"},{"value":[{"text":"SBSDKBarcodeAccumulationMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAccumulationMethod\/navigatorTitle"}]}]}