{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detectionScores"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectionScores","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionScores","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionScores"},{"kind":"text","text":", "},{"kind":"externalParam","text":"points"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"horizontalLines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKLineSegmentInt","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegmentInt","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentInt"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"verticalLines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKLineSegmentInt","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegmentInt","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentInt"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"pointsNormalized"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"horizontalLinesNormalized"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKLineSegmentFloat","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegmentFloat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentFloat"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"verticalLinesNormalized"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKLineSegmentFloat","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegmentFloat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentFloat"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"aspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult\/init(detectionscores:points:horizontallines:verticallines:pointsnormalized:horizontallinesnormalized:verticallinesnormalized:aspectratio:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult\/init(detectionscores:points:horizontallines:verticallines:pointsnormalized:horizontallinesnormalized:verticallinesnormalized:aspectratio:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult\/init(detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detectionScores","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionScores","text":"SBSDKDocumentDetectionScores","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"points","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"horizontalLines","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKLineSegmentInt","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentInt"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"verticalLines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKLineSegmentInt","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentInt"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"pointsNormalized"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"horizontalLinesNormalized"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKLineSegmentFloat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentFloat"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"verticalLinesNormalized"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKLineSegmentFloat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentFloat"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"aspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionResult(im)initWithDetectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDetectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:"}],"title":"init(detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:)","roleHeading":"Initializer","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegmentFloat":{"title":"SBSDKLineSegmentFloat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLineSegmentFloat","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegmentfloat","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegmentFloat","type":"topic","abstract":[{"text":"Represents a line segment in 2D space.","type":"text"}],"navigatorTitle":[{"text":"SBSDKLineSegmentFloat","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionResult/init(detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:)":{"navigatorTitle":[{"text":"initWithDetectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detectionScores","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDetectionScores","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionScores","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"points","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"horizontalLines","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKLineSegmentInt","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentInt","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"verticalLines","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKLineSegmentInt","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentInt","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"pointsNormalized","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"horizontalLinesNormalized","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKLineSegmentFloat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentFloat","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"verticalLinesNormalized","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKLineSegmentFloat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentFloat","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"aspectRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult\/init(detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:)","type":"topic","abstract":[],"title":"init(detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult\/init(detectionscores:points:horizontallines:verticallines:pointsnormalized:horizontallinesnormalized:verticallinesnormalized:aspectratio:)","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionResult":{"abstract":[{"type":"text","text":"Result of the document contour detection."}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult","kind":"symbol","title":"SBSDKDocumentDetectionResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionScores":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionscores","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionScores"}],"title":"SBSDKDocumentDetectionScores","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectionScores"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionScores","kind":"symbol","abstract":[{"text":"The total and partial scores for the detected document contour.","type":"text"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegmentInt":{"title":"SBSDKLineSegmentInt","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegmentint","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLineSegmentInt","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegmentInt","abstract":[{"type":"text","text":"Represents a line segment in 2D space."}],"navigatorTitle":[{"text":"SBSDKLineSegmentInt","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithDetectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDetectionScores:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionScores","kind":"typeIdentifier","text":"SBSDKDocumentDetectionScores","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionScores"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detectionScores"},{"kind":"text","text":" "},{"kind":"identifier","text":"points:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"points"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontalLines:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBSDKLineSegmentInt *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"horizontalLines"},{"kind":"text","text":" "},{"kind":"identifier","text":"verticalLines:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBSDKLineSegmentInt *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"verticalLines"},{"kind":"text","text":" "},{"kind":"identifier","text":"pointsNormalized:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pointsNormalized"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontalLinesNormalized:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBSDKLineSegmentFloat *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"horizontalLinesNormalized"},{"kind":"text","text":" "},{"kind":"identifier","text":"verticalLinesNormalized:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBSDKLineSegmentFloat *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"verticalLinesNormalized"},{"kind":"text","text":" "},{"kind":"identifier","text":"aspectRatio:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"aspectRatio"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKLineSegmentFloat","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentFloat\/title","op":"replace"},{"value":[{"text":"SBSDKLineSegmentFloat","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentFloat\/fragments","op":"replace"},{"op":"replace","value":[{"text":"SBSDKLineSegmentFloat","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentFloat\/navigatorTitle"},{"op":"replace","value":"initWithDetectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult~1init(detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithDetectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult~1init(detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:)\/fragments"},{"op":"replace","value":"SBSDKDocumentDetectionResult","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/navigatorTitle"},{"op":"replace","value":"SBSDKDocumentDetectionScores","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionScores\/title"},{"op":"replace","value":[{"text":"SBSDKDocumentDetectionScores","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionScores\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentDetectionScores","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionScores\/navigatorTitle"},{"op":"replace","value":"SBSDKLineSegmentInt","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentInt\/title"},{"op":"replace","value":[{"text":"SBSDKLineSegmentInt","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentInt\/fragments"},{"op":"replace","value":[{"text":"SBSDKLineSegmentInt","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentInt\/navigatorTitle"}]}]}