{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.confirmationDialog(_:isPresented:titleVisibility:presenting:actions:message:)"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"nonisolated"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmationDialog","kind":"identifier"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"A"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"M"},{"text":", ","kind":"text"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"titleKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"LocalizedStringKey","preciseIdentifier":"s:7SwiftUI18LocalizedStringKeyV"},{"kind":"text","text":", "},{"text":"isPresented","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Binding","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV"},{"kind":"text","text":"<"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"text":"titleVisibility","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Visibility","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI10VisibilityO"},{"text":" = .automatic, ","kind":"text"},{"kind":"externalParam","text":"presenting"},{"kind":"text","text":" "},{"text":"data","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:7SwiftUI11ViewBuilderV","text":"ViewBuilder","kind":"attribute"},{"kind":"text","text":" "},{"text":"actions","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"A","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:7SwiftUI11ViewBuilderV","text":"ViewBuilder","kind":"attribute"},{"kind":"text","text":" "},{"text":"message","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":") -> "},{"text":"M","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"},{"text":" ","kind":"text"},{"kind":"keyword","text":"where"},{"text":" ","kind":"text"},{"text":"A","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"},{"text":", ","kind":"text"},{"text":"M","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"},{"text":"\n","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerview\/confirmationdialog(_:ispresented:titlevisibility:presenting:actions:message:)-7iiu2"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"symbolKind":"method","extendedModule":"SwiftUICore","role":"symbol","externalID":"s:7SwiftUI4ViewPAAE18confirmationDialog_11isPresented15titleVisibility10presenting7actions7messageQrAA18LocalizedStringKeyV_AA7BindingVySbGAA0I0Oqd_1_Sgqd__qd_1_XEqd_0_qd_1_XEtAaBRd__AaBRd_0_r1_lF::SYNTHESIZED::s:10ScanbotSDK26SBSDKUI2BarcodeScannerViewV","roleHeading":"Instance Method","platforms":[{"introducedAt":"15.0","beta":false,"unavailable":false,"deprecated":false,"name":"iOS"},{"name":"iPadOS","deprecated":false,"introducedAt":"15.0","unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"15.0","beta":false,"deprecated":false,"unavailable":false},{"deprecated":false,"introducedAt":"12.0","beta":false,"name":"macOS","unavailable":false},{"introducedAt":"15.0","unavailable":false,"deprecated":false,"beta":false,"name":"tvOS"},{"introducedAt":"8.0","beta":false,"deprecated":false,"unavailable":false,"name":"watchOS"}],"title":"confirmationDialog(_:isPresented:titleVisibility:presenting:actions:message:)","modules":[{"name":"ScanbotSDK","relatedModules":["SwiftUICore"]}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmationDialog"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"A"},{"text":", ","kind":"text"},{"kind":"genericParameter","text":"M"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"LocalizedStringKey","preciseIdentifier":"s:7SwiftUI18LocalizedStringKeyV"},{"kind":"text","text":", "},{"text":"isPresented","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Binding","preciseIdentifier":"s:7SwiftUI7BindingV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"titleVisibility"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI10VisibilityO","text":"Visibility","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"presenting"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"T"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"actions"},{"text":": (","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"A","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":") -> "},{"text":"M","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView\/confirmationDialog(_:isPresented:titleVisibility:presenting:actions:message:)-7iiu2","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView\/View-Implementations"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerView/View-Implementations":{"role":"collectionGroup","abstract":[],"kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerview\/view-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView\/View-Implementations","title":"View Implementations","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerView/confirmationDialog(_:isPresented:titleVisibility:presenting:actions:message:)-7iiu2":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView\/confirmationDialog(_:isPresented:titleVisibility:presenting:actions:message:)-7iiu2","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"confirmationDialog","kind":"identifier"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"A"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"M"},{"text":", ","kind":"text"},{"kind":"genericParameter","text":"T"},{"text":">(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI18LocalizedStringKeyV","text":"LocalizedStringKey"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isPresented"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":">, ","kind":"text"},{"text":"titleVisibility","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI10VisibilityO","text":"Visibility","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"presenting","kind":"externalParam"},{"kind":"text","text":": "},{"text":"T","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"actions"},{"kind":"text","text":": ("},{"text":"T","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"A","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": ("},{"text":"T","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"M"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"title":"confirmationDialog(_:isPresented:titleVisibility:presenting:actions:message:)","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerview\/confirmationdialog(_:ispresented:titlevisibility:presenting:actions:message:)-7iiu2"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerviewcontroller","title":"SBSDKUI2BarcodeScannerViewController","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerViewController","navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerViewController","kind":"identifier"}],"type":"topic","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to detect QR and barcodes.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerView":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerview","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeScannerView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerView"}],"abstract":[{"type":"text","text":"The SwiftUI wrapper for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerViewController"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView","role":"symbol","type":"topic","title":"SBSDKUI2BarcodeScannerView"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController\/title","value":"SBSDKUI2BarcodeScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerViewController"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}