{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerIntroScreenConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerIntroScreenConfiguration\/initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","interfaceLanguage":"occ"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerIntroImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerIntroImage","text":"SBSDKUI2VINScannerIntroImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backgroundColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"dividerColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dividerColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlerColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"handlerColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAutomatically:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"showAutomatically","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"title:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"title","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"explanation:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"explanation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"doneButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"doneButton","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerintroscreenconfiguration\/initwithimage:backgroundcolor:dividercolor:handlercolor:showautomatically:title:explanation:donebutton:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","kind":"identifier"}],"title":"initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerIntroScreenConfiguration(im)initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","title":"SBSDKUI2StyledText","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2color","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"title":"SBSDKUI2Color","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerIntroScreenConfiguration":{"abstract":[{"type":"text","text":"Configuration of the introduction screen for the VIN scanner."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerIntroScreenConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2VINScannerIntroScreenConfiguration","kind":"identifier"}],"title":"SBSDKUI2VINScannerIntroScreenConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerintroscreenconfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2VINScannerIntroScreenConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerIntroImage":{"navigatorTitle":[{"text":"SBSDKUI2VINScannerIntroImage","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerintroimage","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2VINScannerIntroImage","kind":"identifier"}],"abstract":[{"type":"text","text":"The image for the introduction screen of a VIN scanner screen."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerIntroImage","title":"SBSDKUI2VINScannerIntroImage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ButtonConfiguration":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2buttonconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","abstract":[{"type":"text","text":"Configuration of the button."}],"type":"topic","title":"SBSDKUI2ButtonConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerIntroScreenConfiguration/initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:":{"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerintroscreenconfiguration\/initwithimage:backgroundcolor:dividercolor:handlercolor:showautomatically:title:explanation:donebutton:","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerIntroScreenConfiguration\/initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","title":"initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2StyledText","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2Color","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","op":"replace"},{"value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2VINScannerIntroScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerIntroScreenConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2VINScannerIntroScreenConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerIntroScreenConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2VINScannerIntroScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerIntroScreenConfiguration\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2VINScannerIntroImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerIntroImage\/title","op":"replace"},{"value":[{"text":"SBSDKUI2VINScannerIntroImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerIntroImage\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2VINScannerIntroImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerIntroImage\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2ButtonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle","op":"replace"}]}]}