{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","platforms":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxNumberOfAccumulatedResults","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerBehaviorConfiguration(py)maxNumberOfAccumulatedResults","title":"maxNumberOfAccumulatedResults","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"maxNumberOfAccumulatedResults","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"abstract":[{"text":"The maximum number of results to be accumulated when live-recognizing machine-readable zones on sample buffers.","type":"text"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2MRZScannerViewController instead.","type":"text"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscannerbehaviorconfiguration\/maxnumberofaccumulatedresults"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscannerbehaviorconfiguration\/maxnumberofaccumulatedresults"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/maxNumberOfAccumulatedResults","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxNumberOfAccumulatedResults","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"This sets the second part of the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/requiredNumberOfEqualAccumulatedResults","type":"reference","isActive":true},{"text":" of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/maxNumberOfAccumulatedResults","type":"reference","isActive":true},{"text":" selector,","type":"text"},{"text":" ","type":"text"},{"text":"e.g. 2 of 4 results must be equal.","type":"text"},{"text":" ","type":"text"},{"text":"To make the selector less strict, select a higher value, e.g. 2 of 5 or even 2 of 6.","type":"text"},{"text":" ","type":"text"},{"text":"Setting a value lower than the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/requiredNumberOfEqualAccumulatedResults","type":"reference","isActive":true},{"text":" will throw an exception.","type":"text"},{"text":" ","type":"text"},{"text":"Values less-than-or-equal to 0, will effectively turn off the result accumulation.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to 4."}]}],"kind":"content"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerBehaviorConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerbehaviorconfiguration","navigatorTitle":[{"text":"SBSDKUIMRZScannerBehaviorConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIMRZScannerBehaviorConfiguration","kind":"identifier"}],"deprecated":true,"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration","title":"SBSDKUIMRZScannerBehaviorConfiguration","abstract":[{"type":"text","text":"Configuration for the behavior of the machine readable zone scanner."}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerBehaviorConfiguration/requiredNumberOfEqualAccumulatedResults":{"type":"topic","abstract":[{"type":"text","text":"The minimum number of equal results in the accumulator when live-recognizing machine-readable zones on sample buffers."}],"url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerbehaviorconfiguration\/requirednumberofequalaccumulatedresults","role":"symbol","title":"requiredNumberOfEqualAccumulatedResults","navigatorTitle":[{"kind":"identifier","text":"requiredNumberOfEqualAccumulatedResults"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/requiredNumberOfEqualAccumulatedResults","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredNumberOfEqualAccumulatedResults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerBehaviorConfiguration/maxNumberOfAccumulatedResults":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxNumberOfAccumulatedResults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"title":"maxNumberOfAccumulatedResults","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"maxNumberOfAccumulatedResults"}],"abstract":[{"type":"text","text":"The maximum number of results to be accumulated when live-recognizing machine-readable zones on sample buffers."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/maxNumberOfAccumulatedResults","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerbehaviorconfiguration\/maxnumberofaccumulatedresults","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"maxNumberOfAccumulatedResults"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"maxNumberOfAccumulatedResults","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"maxNumberOfAccumulatedResults","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration\/title","op":"replace","value":"SBSDKUIMRZScannerBehaviorConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUIMRZScannerBehaviorConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIMRZScannerBehaviorConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration~1requiredNumberOfEqualAccumulatedResults\/title","op":"replace","value":"requiredNumberOfEqualAccumulatedResults"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration~1requiredNumberOfEqualAccumulatedResults\/fragments","op":"replace","value":[{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration~1maxNumberOfAccumulatedResults\/title","op":"replace","value":"maxNumberOfAccumulatedResults"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration~1maxNumberOfAccumulatedResults\/fragments","op":"replace","value":[{"kind":"identifier","text":"maxNumberOfAccumulatedResults"}]}]}]}