{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultParameters","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKTIFFGeneratorParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGeneratorParameters","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/defaultparameters"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters"]]},"abstract":[{"text":"The default parameters for TIFF generating.","type":"text"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKTIFFGeneratorParameters","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGeneratorParameters"}],"externalID":"s:10ScanbotSDK28SBSDKTIFFGeneratorParametersC07defaultD0ACvpZ","symbolKind":"property","extendedModule":"ScanbotSDK","title":"defaultParameters","roleHeading":"Type Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/defaultParameters"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters","navigatorTitle":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"role":"symbol","title":"SBSDKTIFFGeneratorParameters","type":"topic","abstract":[{"type":"text","text":"TIFF generator parameters."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/defaultParameters":{"abstract":[{"text":"The default parameters for TIFF generating.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKTIFFGeneratorParameters","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGeneratorParameters"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/defaultParameters","title":"defaultParameters","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/defaultparameters"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/title","value":"SBSDKTIFFGeneratorParameters"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/fragments","value":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}