{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategories"]]},"sections":[],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"d1E"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","roleHeading":"Instance Property","title":"d1E","navigatorTitle":[{"kind":"identifier","text":"d1E"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelDeDriverLicenseBackCategories(py)d1E","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"type":"text","text":"The child document of type “D1E”."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"d1E"},{"kind":"text","text":": "},{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategories\/d1e"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategories\/d1e"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategories\/d1E","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategoriesd1e","role":"symbol","abstract":[{"text":"DeDriverLicenseBack.Categories.D1E","type":"text"}],"navigatorTitle":[{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E","kind":"identifier"}],"kind":"symbol","title":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseBackCategories":{"title":"SBSDKDocumentsModelDeDriverLicenseBackCategories","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategories","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategories","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategories","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategories","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Categories table row container","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseBackCategories/d1E":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategories\/d1e","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"d1E","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategories\/d1E","title":"d1E","abstract":[{"type":"text","text":"The child document of type “D1E”."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"d1E"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"d1E","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"d1E"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E"},{"text":" * ","kind":"text"},{"text":"d1E","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E\/fragments","op":"replace","value":[{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesD1E\/navigatorTitle"},{"op":"replace","value":"SBSDKDocumentsModelDeDriverLicenseBackCategories","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategories\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategories\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseBackCategories"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategories\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseBackCategories"}],"op":"replace"},{"value":"d1E","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategories~1d1E\/title"},{"value":[{"text":"d1E","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategories~1d1E\/fragments","op":"replace"}]}]}