{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/sbsdkgenerictextlinerecognizerviewcontrollerdelegate-implementations"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/sbsdkgenerictextlinerecognizerviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/textLineRecognizerViewController(_:didValidate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/textLineRecognizerViewControllerShouldRecognize(_:)"]}],"kind":"article","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"API Collection","title":"SBSDKGenericTextLineRecognizerViewControllerDelegate Implementations","role":"collectionGroup","modules":[{"name":"ScanbotSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/SBSDKGenericTextLineRecognizerViewControllerDelegate-Implementations"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/textLineRecognizerViewController(_:didValidate:)":{"type":"topic","title":"textLineRecognizerViewController(_:didValidate:)","navigatorTitle":[{"kind":"identifier","text":"textLineRecognizerViewController:didValidateResult:"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/textlinerecognizerviewcontroller(_:didvalidate:)","abstract":[{"type":"text","text":"Informs the delegate that text line(s) has been recognized and validated and passes the result."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"textLineRecognizerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerViewController","kind":"typeIdentifier","text":"SBSDKGenericTextLineRecognizerViewController"},{"text":", ","kind":"text"},{"text":"didValidate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKGenericTextLineRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResult","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/textLineRecognizerViewController(_:didValidate:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController":{"type":"topic","title":"SBSDKUITextDataScannerViewController","navigatorTitle":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller","kind":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to recognize and validate a small rectangular text area in realtime."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/textLineRecognizerViewControllerShouldRecognize(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/textlinerecognizerviewcontrollershouldrecognize(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textLineRecognizerViewControllerShouldRecognize"},{"kind":"text","text":"("},{"text":"SBSDKGenericTextLineRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerViewController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","navigatorTitle":[{"text":"textLineRecognizerViewControllerShouldRecognize:","kind":"identifier"}],"abstract":[{"type":"text","text":"Optional. Asks the delegate whether the next video frame should be recognized or not."}],"title":"textLineRecognizerViewControllerShouldRecognize(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/textLineRecognizerViewControllerShouldRecognize(_:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/textLineRecognizerViewController(_:didValidate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/textLineRecognizerViewControllerShouldRecognize(_:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController~1textLineRecognizerViewController(_:didValidate:)\/title","value":"textLineRecognizerViewController:didValidateResult:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textLineRecognizerViewController:didValidateResult:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController~1textLineRecognizerViewController(_:didValidate:)\/fragments","op":"replace"},{"value":"SBSDKUITextDataScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController~1textLineRecognizerViewControllerShouldRecognize(_:)\/title","value":"textLineRecognizerViewControllerShouldRecognize:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"textLineRecognizerViewControllerShouldRecognize:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController~1textLineRecognizerViewControllerShouldRecognize(_:)\/fragments"}]}]}