{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/textlinerecognizerviewcontrollershouldrecognize(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/textlinerecognizerviewcontrollershouldrecognize(_:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/SBSDKGenericTextLineRecognizerViewControllerDelegate-Implementations"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/textLineRecognizerViewControllerShouldRecognize(_:)"},"metadata":{"title":"textLineRecognizerViewControllerShouldRecognize(_:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"textLineRecognizerViewControllerShouldRecognize:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textLineRecognizerViewControllerShouldRecognize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerViewController","text":"SBSDKGenericTextLineRecognizerViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Instance Method","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUITextDataScannerViewController(im)textLineRecognizerViewControllerShouldRecognize:","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"textLineRecognizerViewControllerShouldRecognize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController","kind":"typeIdentifier","text":"SBSDKGenericTextLineRecognizerViewController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController"},{"text":" that wants to recognize the video frame.","type":"text"}]}]}]},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":", if you want to recognize the next video frame, "},{"type":"codeVoice","code":"False"},{"text":" otherwise.","type":"text"}]}],"kind":"content"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"Use to skip frames or pause recognition for a while.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"Optional. Asks the delegate whether the next video frame should be recognized or not."}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/SBSDKGenericTextLineRecognizerViewControllerDelegate-Implementations":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/sbsdkgenerictextlinerecognizerviewcontrollerdelegate-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/SBSDKGenericTextLineRecognizerViewControllerDelegate-Implementations","type":"topic","kind":"article","title":"SBSDKGenericTextLineRecognizerViewControllerDelegate Implementations","role":"collectionGroup"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerViewController":{"abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show a camera screen with the text line recognizer."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController","type":"topic","kind":"symbol","title":"SBSDKGenericTextLineRecognizerViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/textLineRecognizerViewControllerShouldRecognize(_:)":{"abstract":[{"type":"text","text":"Optional. Asks the delegate whether the next video frame should be recognized or not."}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/textlinerecognizerviewcontrollershouldrecognize(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"textLineRecognizerViewControllerShouldRecognize","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerViewController","kind":"typeIdentifier","text":"SBSDKGenericTextLineRecognizerViewController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/textLineRecognizerViewControllerShouldRecognize(_:)","type":"topic","kind":"symbol","title":"textLineRecognizerViewControllerShouldRecognize(_:)","role":"symbol","navigatorTitle":[{"text":"textLineRecognizerViewControllerShouldRecognize:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController":{"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to recognize and validate a small rectangular text area in realtime."}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","type":"topic","kind":"symbol","title":"SBSDKUITextDataScannerViewController","role":"symbol","navigatorTitle":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"textLineRecognizerViewControllerShouldRecognize:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textLineRecognizerViewControllerShouldRecognize:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"textLineRecognizerViewControllerShouldRecognize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKGenericTextLineRecognizerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"value":"SBSDKGenericTextLineRecognizerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController\/title"},{"value":[{"text":"SBSDKGenericTextLineRecognizerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController~1textLineRecognizerViewControllerShouldRecognize(_:)\/title","op":"replace","value":"textLineRecognizerViewControllerShouldRecognize:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController~1textLineRecognizerViewControllerShouldRecognize(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"textLineRecognizerViewControllerShouldRecognize:","kind":"identifier"}]},{"value":"SBSDKUITextDataScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"op":"replace"}]}]}