{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"textLineRecognizerViewController:didValidateResult:"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUITextDataScannerViewController(im)textLineRecognizerViewController:didValidateResult:","role":"symbol","title":"textLineRecognizerViewController(_:didValidate:)","modules":[{"name":"ScanbotSDK"}],"extendedModule":"ScanbotSDK","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"textLineRecognizerViewController","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerViewController","text":"SBSDKGenericTextLineRecognizerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didValidate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResult","kind":"typeIdentifier","text":"SBSDKGenericTextLineRecognizerResult"},{"text":")","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/textlinerecognizerviewcontroller(_:didvalidate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/textlinerecognizerviewcontroller(_:didvalidate:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/SBSDKGenericTextLineRecognizerViewControllerDelegate-Implementations"]]},"abstract":[{"type":"text","text":"Informs the delegate that text line(s) has been recognized and validated and passes the result."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/textLineRecognizerViewController(_:didValidate:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"textLineRecognizerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"controller","kind":"internalParam"},{"kind":"text","text":": "},{"text":"SBSDKGenericTextLineRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController"},{"kind":"text","text":", "},{"text":"didValidate","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"result"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResult","text":"SBSDKGenericTextLineRecognizerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResult"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController"},{"text":" that has recognized and validated the text line(s).","type":"text"}]}]},{"name":"result","content":[{"inlineContent":[{"type":"text","text":"The result of the recognition."}],"type":"paragraph"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController":{"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to recognize and validate a small rectangular text area in realtime."}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","type":"topic","kind":"symbol","title":"SBSDKUITextDataScannerViewController","role":"symbol","navigatorTitle":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/textLineRecognizerViewController(_:didValidate:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textLineRecognizerViewController"},{"kind":"text","text":"("},{"text":"SBSDKGenericTextLineRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerViewController"},{"text":", ","kind":"text"},{"text":"didValidate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResult","kind":"typeIdentifier","text":"SBSDKGenericTextLineRecognizerResult"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/textLineRecognizerViewController(_:didValidate:)","kind":"symbol","type":"topic","role":"symbol","title":"textLineRecognizerViewController(_:didValidate:)","navigatorTitle":[{"text":"textLineRecognizerViewController:didValidateResult:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/textlinerecognizerviewcontroller(_:didvalidate:)","abstract":[{"type":"text","text":"Informs the delegate that text line(s) has been recognized and validated and passes the result."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController/SBSDKGenericTextLineRecognizerViewControllerDelegate-Implementations":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller\/sbsdkgenerictextlinerecognizerviewcontrollerdelegate-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController\/SBSDKGenericTextLineRecognizerViewControllerDelegate-Implementations","type":"topic","kind":"article","title":"SBSDKGenericTextLineRecognizerViewControllerDelegate Implementations","role":"collectionGroup"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerViewController":{"abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show a camera screen with the text line recognizer."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController","type":"topic","kind":"symbol","title":"SBSDKGenericTextLineRecognizerViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerResult":{"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerresult","kind":"symbol","abstract":[{"type":"text","text":"A class describing the result of the generic text line recognizer."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResult","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerResult"}],"navigatorTitle":[{"text":"SBSDKGenericTextLineRecognizerResult","kind":"identifier"}],"title":"SBSDKGenericTextLineRecognizerResult"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"textLineRecognizerViewController:didValidateResult:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"textLineRecognizerViewController:didValidateResult:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"textLineRecognizerViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerViewController","text":"SBSDKGenericTextLineRecognizerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didValidateResult:"},{"kind":"text","text":"("},{"text":"SBSDKGenericTextLineRecognizerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResult"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/title","value":"SBSDKUITextDataScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/fragments","value":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}]},{"value":"textLineRecognizerViewController:didValidateResult:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController~1textLineRecognizerViewController(_:didValidate:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController~1textLineRecognizerViewController(_:didValidate:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"textLineRecognizerViewController:didValidateResult:","kind":"identifier"}]},{"value":"SBSDKGenericTextLineRecognizerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKGenericTextLineRecognizerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController\/fragments"},{"value":"SBSDKGenericTextLineRecognizerResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerResult\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerResult"}],"op":"replace"}]}]}