{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessByTileConfiguration\/minProcessedFraction"},"abstract":[{"type":"text","text":"At least this fraction of the image will be processed, range is from 0 to 1."},{"type":"text","text":" "},{"type":"text","text":"Decreasing this value below 1.0 can lead to faster processing but may result in"},{"type":"text","text":" "},{"type":"text","text":"less accurate prediction, as only a subset of the image tiles will be analyzed."}],"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Property","title":"minProcessedFraction","navigatorTitle":[{"kind":"identifier","text":"minProcessedFraction"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProcessByTileConfiguration(py)minProcessedFraction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minProcessedFraction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"symbolKind":"property"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessbytileconfiguration\/minprocessedfraction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessbytileconfiguration\/minprocessedfraction"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minProcessedFraction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Default is 1","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessByTileConfiguration"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProcessByTileConfiguration":{"role":"symbol","navigatorTitle":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"title":"SBSDKProcessByTileConfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessByTileConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessbytileconfiguration","abstract":[{"text":"Configuration for processing image by tiles.","type":"text"},{"text":" ","type":"text"},{"text":"This can be used to make the document quality analyzer processing faster with lower memory consumption,","type":"text"},{"text":" ","type":"text"},{"text":"but prediction can be less accurate.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProcessByTileConfiguration/minProcessedFraction":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessbytileconfiguration\/minprocessedfraction","abstract":[{"text":"At least this fraction of the image will be processed, range is from 0 to 1.","type":"text"},{"text":" ","type":"text"},{"text":"Decreasing this value below 1.0 can lead to faster processing but may result in","type":"text"},{"text":" ","type":"text"},{"text":"less accurate prediction, as only a subset of the image tiles will be analyzed.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessByTileConfiguration\/minProcessedFraction","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minProcessedFraction","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"minProcessedFraction","kind":"identifier"}],"title":"minProcessedFraction"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","abstract":[{"text":"Version: 8.0.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"minProcessedFraction","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"minProcessedFraction","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"minProcessedFraction"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessByTileConfiguration\/title","op":"replace","value":"SBSDKProcessByTileConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessByTileConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessByTileConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessByTileConfiguration~1minProcessedFraction\/title","op":"replace","value":"minProcessedFraction"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessByTileConfiguration~1minProcessedFraction\/fragments","op":"replace","value":[{"kind":"identifier","text":"minProcessedFraction"}]}]}]}