{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/scanninginprogressstillfocusing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/scanninginprogressstillfocusing"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/scanningInProgressStillFocusing","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanningInProgressStillFocusing","kind":"identifier"}],"title":"SBSDKDocumentDataExtractionStatus.scanningInProgressStillFocusing","roleHeading":"Case","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDataExtractionStatus@SBSDKDocumentDataExtractionStatusScanningInProgressStillFocusing","navigatorTitle":[{"text":"SBSDKDocumentDataExtractionStatusScanningInProgressStillFocusing","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus"]]},"abstract":[{"text":"Document data extraction in progress. Waiting for camera to finish focusing.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanningInProgressStillFocusing"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus/scanningInProgressStillFocusing":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanningInProgressStillFocusing"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusScanningInProgressStillFocusing"}],"abstract":[{"text":"Document data extraction in progress. Waiting for camera to finish focusing.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/scanningInProgressStillFocusing","kind":"symbol","title":"SBSDKDocumentDataExtractionStatus.scanningInProgressStillFocusing","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/scanninginprogressstillfocusing"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatus"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatus"}],"type":"topic","title":"SBSDKDocumentDataExtractionStatus","kind":"symbol","abstract":[{"type":"text","text":"The status of the extraction process."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKDocumentDataExtractionStatusScanningInProgressStillFocusing","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusScanningInProgressStillFocusing"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusScanningInProgressStillFocusing"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKDocumentDataExtractionStatusScanningInProgressStillFocusing","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1scanningInProgressStillFocusing\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusScanningInProgressStillFocusing"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1scanningInProgressStillFocusing\/fragments"},{"op":"replace","value":"SBSDKDocumentDataExtractionStatus","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentDataExtractionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/navigatorTitle"}]}]}