{"metadata":{"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"textBackgroundHighlightedColor","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle(py)textBackgroundHighlightedColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textBackgroundHighlightedColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"title":"textBackgroundHighlightedColor","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewTextStyle"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"The background color of the barcode text when highlighted."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewTextStyle\/textBackgroundHighlightedColor"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewtextstyle\/textbackgroundhighlightedcolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewtextstyle\/textbackgroundhighlightedcolor"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textBackgroundHighlightedColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewTextStyle":{"type":"topic","title":"SBSDKBarcodeTrackedViewTextStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewTextStyle","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeTrackedViewTextStyle"}],"abstract":[{"type":"text","text":"A class that represents the style and kind of the text rendered below a barcode in "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","isActive":true},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeTrackedViewTextStyle"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewtextstyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewTextStyle/textBackgroundHighlightedColor":{"navigatorTitle":[{"text":"textBackgroundHighlightedColor","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The background color of the barcode text when highlighted.","type":"text"}],"title":"textBackgroundHighlightedColor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewTextStyle\/textBackgroundHighlightedColor","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewtextstyle\/textbackgroundhighlightedcolor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"textBackgroundHighlightedColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayController":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontroller","title":"SBSDKBarcodeTrackingOverlayController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"abstract":[{"text":"A class that represents an overlay used for visualizing scanned barcodes.","type":"text"},{"text":" ","type":"text"},{"text":"It provides a customizable user interface for displaying barcodes and supports interaction with them.","type":"text"},{"text":" ","type":"text"},{"text":"The overlay can be used to highlight and select barcodes based on user input.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"textBackgroundHighlightedColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"textBackgroundHighlightedColor"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"textBackgroundHighlightedColor"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewTextStyle\/title","value":"SBSDKBarcodeTrackedViewTextStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewTextStyle\/fragments","value":[{"text":"SBSDKBarcodeTrackedViewTextStyle","kind":"identifier"}]},{"value":[{"text":"SBSDKBarcodeTrackedViewTextStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewTextStyle\/navigatorTitle","op":"replace"},{"value":"textBackgroundHighlightedColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewTextStyle~1textBackgroundHighlightedColor\/title","op":"replace"},{"value":[{"kind":"identifier","text":"textBackgroundHighlightedColor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewTextStyle~1textBackgroundHighlightedColor\/fragments","op":"replace"},{"value":"SBSDKBarcodeTrackingOverlayController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/navigatorTitle","op":"replace"}]}]}