{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewMorePopupMenu"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2reviewmorepopupmenu\/reorderpages"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2reviewmorepopupmenu\/reorderpages"]}],"abstract":[{"type":"text","text":"Configuration of the ‘reorder pages’ button."}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewMorePopupMenu\/reorderPages"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reorderPages","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PopupMenuItem","text":"SBSDKUI2PopupMenuItem","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PopupMenuItem"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReviewMorePopupMenu(py)reorderPages","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reorderPages"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2PopupMenuItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PopupMenuItem"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"reorderPages"}],"roleHeading":"Instance Property","title":"reorderPages"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReviewMorePopupMenu":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewMorePopupMenu","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ReviewMorePopupMenu"}],"abstract":[{"text":"Configuration of the ‘more’ popup menu for the review screen.","type":"text"}],"title":"SBSDKUI2ReviewMorePopupMenu","url":"\/documentation\/scanbotsdk\/sbsdkui2reviewmorepopupmenu","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ReviewMorePopupMenu"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReviewMorePopupMenu/reorderPages":{"role":"symbol","navigatorTitle":[{"text":"reorderPages","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2reviewmorepopupmenu\/reorderpages","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewMorePopupMenu\/reorderPages","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reorderPages","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PopupMenuItem","text":"SBSDKUI2PopupMenuItem","kind":"typeIdentifier"}],"title":"reorderPages","abstract":[{"type":"text","text":"Configuration of the ‘reorder pages’ button."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PopupMenuItem":{"title":"SBSDKUI2PopupMenuItem","url":"\/documentation\/scanbotsdk\/sbsdkui2popupmenuitem","kind":"symbol","abstract":[{"text":"Configuration for the popup menu items.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PopupMenuItem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PopupMenuItem","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2PopupMenuItem","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"reorderPages","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"reorderPages","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PopupMenuItem","text":"SBSDKUI2PopupMenuItem","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PopupMenuItem","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"reorderPages","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2ReviewMorePopupMenu","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewMorePopupMenu\/title"},{"value":[{"text":"SBSDKUI2ReviewMorePopupMenu","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewMorePopupMenu\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewMorePopupMenu\/navigatorTitle","value":[{"text":"SBSDKUI2ReviewMorePopupMenu","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewMorePopupMenu~1reorderPages\/title","value":"reorderPages","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewMorePopupMenu~1reorderPages\/fragments","value":[{"kind":"identifier","text":"reorderPages"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PopupMenuItem\/title","value":"SBSDKUI2PopupMenuItem","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PopupMenuItem\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2PopupMenuItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PopupMenuItem\/navigatorTitle","value":[{"text":"SBSDKUI2PopupMenuItem","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}