{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgrayscalefilter\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGrayscaleFilter"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGrayscaleFilter\/copyWithZone:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"copyWithZone:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"_NSZone","preciseIdentifier":"c:@S@_NSZone"},{"kind":"text","text":" *) "},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGrayscaleFilter(im)copyWithZone:","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"title":"copyWithZone:","roleHeading":"Instance Method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGrayscaleFilter":{"role":"symbol","title":"SBSDKGrayscaleFilter","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGrayscaleFilter"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGrayscaleFilter","abstract":[{"text":"Converts color images to grayscale and applies autocontrast.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGrayscaleFilter"}],"url":"\/documentation\/scanbotsdk\/sbsdkgrayscalefilter","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGrayscaleFilter/copyWithZone:":{"abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGrayscaleFilter\/copyWithZone:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"title":"copyWithZone:","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgrayscalefilter\/copywithzone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGrayscaleFilter\/title","value":"SBSDKGrayscaleFilter"},{"value":[{"text":"SBSDKGrayscaleFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGrayscaleFilter\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGrayscaleFilter\/navigatorTitle","value":[{"text":"SBSDKGrayscaleFilter","kind":"identifier"}]}]}]}