{"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:checkAlertRetryButton:checkAlertCloseScannerButton:checkNoCheckDetectedAlertTitle:checkNoCheckDetectedAlertSubtitle:checkImageNotGoodAlertTitle:checkImageNotGoodAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:checkUserGuidanceNoCheckFound:checkUserGuidanceScanningProgress:checkUserGuidanceTooDark:checkUserGuidanceTooSmall:checkUserGuidanceBadPerspective:","kind":"identifier"}],"title":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:checkAlertRetryButton:checkAlertCloseScannerButton:checkNoCheckDetectedAlertTitle:checkNoCheckDetectedAlertSubtitle:checkImageNotGoodAlertTitle:checkImageNotGoodAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:checkUserGuidanceNoCheckFound:checkUserGuidanceScanningProgress:checkUserGuidanceTooDark:checkUserGuidanceTooSmall:checkUserGuidanceBadPerspective:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:checkAlertRetryButton:checkAlertCloseScannerButton:checkNoCheckDetectedAlertTitle:checkNoCheckDetectedAlertSubtitle:checkImageNotGoodAlertTitle:checkImageNotGoodAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:checkUserGuidanceNoCheckFound:checkUserGuidanceScanningProgress:checkUserGuidanceTooDark:checkUserGuidanceTooSmall:checkUserGuidanceBadPerspective:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerScreenTextLocalization(im)initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:checkAlertRetryButton:checkAlertCloseScannerButton:checkNoCheckDetectedAlertTitle:checkNoCheckDetectedAlertSubtitle:checkImageNotGoodAlertTitle:checkImageNotGoodAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:checkUserGuidanceNoCheckFound:checkUserGuidanceScanningProgress:checkUserGuidanceTooDark:checkUserGuidanceTooSmall:checkUserGuidanceBadPerspective:","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenTextLocalization"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenTextLocalization\/initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:checkAlertRetryButton:checkAlertCloseScannerButton:checkNoCheckDetectedAlertTitle:checkNoCheckDetectedAlertSubtitle:checkImageNotGoodAlertTitle:checkImageNotGoodAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:checkUserGuidanceNoCheckFound:checkUserGuidanceScanningProgress:checkUserGuidanceTooDark:checkUserGuidanceTooSmall:checkUserGuidanceBadPerspective:"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithTopBarTitle:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"topBarTitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarCancelButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"topBarCancelButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"topUserGuidance:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"topUserGuidance","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"finderViewUserGuidance:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"finderViewUserGuidance"},{"text":" ","kind":"text"},{"text":"introScreenTitle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"introScreenTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"introScreenDoneButton:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"introScreenDoneButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"introScreenText:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"introScreenText","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completionOverlaySuccessMessage:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"completionOverlaySuccessMessage"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionOpenIntroScreenButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionOpenIntroScreenButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionIntroScreenDoneButton:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionIntroScreenDoneButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionCancelButton:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionCancelButton"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionRetryButton:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionRetryButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCloseScannerButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionCloseScannerButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"checkAlertRetryButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"checkAlertRetryButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"checkAlertCloseScannerButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"checkAlertCloseScannerButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"checkNoCheckDetectedAlertTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"checkNoCheckDetectedAlertTitle","kind":"internalParam"},{"kind":"text","text":" "},{"text":"checkNoCheckDetectedAlertSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"checkNoCheckDetectedAlertSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"checkImageNotGoodAlertTitle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"checkImageNotGoodAlertTitle"},{"text":" ","kind":"text"},{"text":"checkImageNotGoodAlertSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"checkImageNotGoodAlertSubtitle"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionFlashButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionFlashButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionZoomButton:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionZoomButton"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionFlipCameraButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionFlipCameraButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraPermissionEnableCameraTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionEnableCameraExplanation:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraPermissionEnableCameraExplanation"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraPermissionEnableCameraButton"},{"kind":"text","text":" "},{"text":"cameraPermissionCloseButton:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraPermissionCloseButton"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkUserGuidanceNoCheckFound:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"checkUserGuidanceNoCheckFound"},{"text":" ","kind":"text"},{"text":"checkUserGuidanceScanningProgress:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"checkUserGuidanceScanningProgress","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkUserGuidanceTooDark:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"checkUserGuidanceTooDark","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"checkUserGuidanceTooSmall:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"checkUserGuidanceTooSmall","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkUserGuidanceBadPerspective:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"checkUserGuidanceBadPerspective"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreentextlocalization\/initwithtopbartitle:topbarcancelbutton:topuserguidance:finderviewuserguidance:introscreentitle:introscreendonebutton:introscreentext:completionoverlaysuccessmessage:accessibilitydescriptionopenintroscreenbutton:accessibilitydescriptionintro-9kxyk"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerScreenTextLocalization":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenTextLocalization","title":"SBSDKUI2CheckScannerScreenTextLocalization","abstract":[{"type":"text","text":"Configuration of the all strings for check scanner screen."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreentextlocalization","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2CheckScannerScreenTextLocalization","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CheckScannerScreenTextLocalization","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerScreenTextLocalization/initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:checkAlertRetryButton:checkAlertCloseScannerButton:checkNoCheckDetectedAlertTitle:checkNoCheckDetectedAlertSubtitle:checkImageNotGoodAlertTitle:checkImageNotGoodAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:checkUserGuidanceNoCheckFound:checkUserGuidanceScanningProgress:checkUserGuidanceTooDark:checkUserGuidanceTooSmall:checkUserGuidanceBadPerspective:":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreentextlocalization\/initwithtopbartitle:topbarcancelbutton:topuserguidance:finderviewuserguidance:introscreentitle:introscreendonebutton:introscreentext:completionoverlaysuccessmessage:accessibilitydescriptionopenintroscreenbutton:accessibilitydescriptionintro-9kxyk","title":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:checkAlertRetryButton:checkAlertCloseScannerButton:checkNoCheckDetectedAlertTitle:checkNoCheckDetectedAlertSubtitle:checkImageNotGoodAlertTitle:checkImageNotGoodAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:checkUserGuidanceNoCheckFound:checkUserGuidanceScanningProgress:checkUserGuidanceTooDark:checkUserGuidanceTooSmall:checkUserGuidanceBadPerspective:","abstract":[],"navigatorTitle":[{"text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:checkAlertRetryButton:checkAlertCloseScannerButton:checkNoCheckDetectedAlertTitle:checkNoCheckDetectedAlertSubtitle:checkImageNotGoodAlertTitle:checkImageNotGoodAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:checkUserGuidanceNoCheckFound:checkUserGuidanceScanningProgress:checkUserGuidanceTooDark:checkUserGuidanceTooSmall:checkUserGuidanceBadPerspective:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:checkAlertRetryButton:checkAlertCloseScannerButton:checkNoCheckDetectedAlertTitle:checkNoCheckDetectedAlertSubtitle:checkImageNotGoodAlertTitle:checkImageNotGoodAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:checkUserGuidanceNoCheckFound:checkUserGuidanceScanningProgress:checkUserGuidanceTooDark:checkUserGuidanceTooSmall:checkUserGuidanceBadPerspective:"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenTextLocalization\/initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:checkAlertRetryButton:checkAlertCloseScannerButton:checkNoCheckDetectedAlertTitle:checkNoCheckDetectedAlertSubtitle:checkImageNotGoodAlertTitle:checkImageNotGoodAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:checkUserGuidanceNoCheckFound:checkUserGuidanceScanningProgress:checkUserGuidanceTooDark:checkUserGuidanceTooSmall:checkUserGuidanceBadPerspective:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenTextLocalization\/title","value":"SBSDKUI2CheckScannerScreenTextLocalization","op":"replace"},{"value":[{"text":"SBSDKUI2CheckScannerScreenTextLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenTextLocalization\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenTextLocalization\/navigatorTitle","value":[{"text":"SBSDKUI2CheckScannerScreenTextLocalization","kind":"identifier"}]}]}]}