{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogFactory"]]},"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"confirmButtonTitle"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"image","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"didPressConfirmButton"},{"text":": (() -> ())?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogFactory(im)createWithTitle:message:confirmButtonTitle:image:didPressConfirmButton:","title":"create(with:message:confirmButtonTitle:image:didPressConfirmButton:)","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"createWithTitle:message:confirmButtonTitle:image:didPressConfirmButton:","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"text":"Creates and returns an instance of an alert for modal presentation.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(createWithTitle:message:confirmButtonTitle:image:didPressConfirmButton:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"confirmButtonTitle"},{"kind":"text","text":" "},{"text":"buttonTitle","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"image","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"didPressConfirmButton"},{"kind":"text","text":" "},{"text":"handler","kind":"internalParam"},{"kind":"text","text":": (() -> ())?) -> "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}]}]},{"kind":"parameters","parameters":[{"name":"title","content":[{"type":"paragraph","inlineContent":[{"text":"The title of the alert.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The message of the  alert."}]}],"name":"message"},{"name":"buttonTitle","content":[{"inlineContent":[{"type":"text","text":"The confirmation buttons title of the alert."}],"type":"paragraph"}]},{"name":"image","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image to be shown within the alert. Can be zoomed and scrolled."}]}]},{"name":"handler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion handler to be called when the confirm button is pressed."}]}]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The instance of the alert view controller.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuidialogfactory\/create(with:message:confirmbuttontitle:image:didpressconfirmbutton:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuidialogfactory\/create(with:message:confirmbuttontitle:image:didpressconfirmbutton:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogFactory\/create(with:message:confirmButtonTitle:image:didPressConfirmButton:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDialogFactory":{"type":"topic","kind":"symbol","title":"SBSDKUIDialogFactory","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDialogFactory"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDialogFactory"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidialogfactory","abstract":[{"text":"Factory class for creating instances of iOS system style alerts with extended functionality, e.g. displaying an image.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDialogFactory/create(with:message:confirmButtonTitle:image:didPressConfirmButton:)":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidialogfactory\/create(with:message:confirmbuttontitle:image:didpressconfirmbutton:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogFactory\/create(with:message:confirmButtonTitle:image:didPressConfirmButton:)","title":"create(with:message:confirmButtonTitle:image:didPressConfirmButton:)","abstract":[{"type":"text","text":"Creates and returns an instance of an alert for modal presentation."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"confirmButtonTitle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"image"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"didPressConfirmButton"},{"kind":"text","text":": (() -> ())?) -> "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"createWithTitle:message:confirmButtonTitle:image:didPressConfirmButton:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"createWithTitle:message:confirmButtonTitle:image:didPressConfirmButton:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"createWithTitle:message:confirmButtonTitle:image:didPressConfirmButton:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createWithTitle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"title"},{"kind":"text","text":" "},{"text":"message:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"message","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmButtonTitle:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"buttonTitle"},{"text":" ","kind":"text"},{"text":"image:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didPressConfirmButton:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")()) ","kind":"text"},{"text":"handler","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogFactory\/title","value":"SBSDKUIDialogFactory","op":"replace"},{"value":[{"text":"SBSDKUIDialogFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogFactory\/fragments"},{"value":"createWithTitle:message:confirmButtonTitle:image:didPressConfirmButton:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogFactory~1create(with:message:confirmButtonTitle:image:didPressConfirmButton:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogFactory~1create(with:message:confirmButtonTitle:image:didPressConfirmButton:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createWithTitle:message:confirmButtonTitle:image:didPressConfirmButton:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}