{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuidialogfactory\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogFactory\/init","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogFactory(im)init","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"init","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogFactory"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDialogFactory/init":{"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","url":"\/documentation\/scanbotsdk\/sbsdkuidialogfactory\/init","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogFactory\/init","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDialogFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIDialogFactory"}],"navigatorTitle":[{"text":"SBSDKUIDialogFactory","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidialogfactory","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Factory class for creating instances of iOS system style alerts with extended functionality, e.g. displaying an image."}],"title":"SBSDKUIDialogFactory","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogFactory"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogFactory\/title","value":"SBSDKUIDialogFactory"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDialogFactory"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogFactory\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIDialogFactory"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogFactory\/navigatorTitle"}]}]}