{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSimulatorDevice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]}],"abstract":[{"type":"text","text":"Returns "},{"code":"True","type":"codeVoice"},{"type":"text","text":" if the current device is a simulator, "},{"code":"False","type":"codeVoice"},{"type":"text","text":" otherwise."}],"metadata":{"roleHeading":"Type Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDeviceInformation(cpy)isSimulatorDevice","navigatorTitle":[{"text":"isSimulatorDevice","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"isSimulatorDevice","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"isSimulatorDevice","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/isSimulatorDevice"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdeviceinformation\/issimulatordevice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdeviceinformation\/issimulatordevice"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceInformation/isSimulatorDevice":{"role":"symbol","title":"isSimulatorDevice","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSimulatorDevice"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":" if the current device is a simulator, "},{"type":"codeVoice","code":"False"},{"text":" otherwise.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/isSimulatorDevice","url":"\/documentation\/scanbotsdk\/sbsdkdeviceinformation\/issimulatordevice","navigatorTitle":[{"kind":"identifier","text":"isSimulatorDevice"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceInformation":{"abstract":[{"type":"text","text":"Helper class that delivers information about the used iOS device."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDeviceInformation","kind":"identifier"}],"kind":"symbol","type":"topic","title":"SBSDKDeviceInformation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation","role":"symbol","navigatorTitle":[{"text":"SBSDKDeviceInformation","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdeviceinformation"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isSimulatorDevice","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"isSimulatorDevice","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSimulatorDevice"},{"kind":"text","text":";"}]}]}},{"value":"isSimulatorDevice","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1isSimulatorDevice\/title"},{"value":[{"text":"isSimulatorDevice","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1isSimulatorDevice\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation\/title","op":"replace","value":"SBSDKDeviceInformation"},{"value":[{"kind":"identifier","text":"SBSDKDeviceInformation"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDeviceInformation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation\/navigatorTitle"}]}]}