{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation"]]},"abstract":[{"text":"The amount of used disk space of the device in bytes.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"usedDiskSpaceInBytes"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDeviceInformation(cm)usedDiskSpaceInBytes","roleHeading":"Type Method","symbolKind":"method","title":"usedDiskSpaceInBytes()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"usedDiskSpaceInBytes","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"usedDiskSpaceInBytes"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The amount of used disk space of the device in bytes. In case of error the return value is -1."}]}],"kind":"content"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdeviceinformation\/useddiskspaceinbytes()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdeviceinformation\/useddiskspaceinbytes()"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/usedDiskSpaceInBytes()","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceInformation/usedDiskSpaceInBytes()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/usedDiskSpaceInBytes()","url":"\/documentation\/scanbotsdk\/sbsdkdeviceinformation\/useddiskspaceinbytes()","role":"symbol","navigatorTitle":[{"text":"usedDiskSpaceInBytes","kind":"identifier"}],"title":"usedDiskSpaceInBytes()","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"usedDiskSpaceInBytes"},{"text":"() -> ","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The amount of used disk space of the device in bytes."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceInformation":{"url":"\/documentation\/scanbotsdk\/sbsdkdeviceinformation","kind":"symbol","title":"SBSDKDeviceInformation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDeviceInformation"}],"abstract":[{"type":"text","text":"Helper class that delivers information about the used iOS device."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation","navigatorTitle":[{"kind":"identifier","text":"SBSDKDeviceInformation"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"usedDiskSpaceInBytes","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"usedDiskSpaceInBytes","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@T@int64_t","text":"int64_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"usedDiskSpaceInBytes","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"The amount of used disk space of the device in bytes. In case of error the return value is -1.","type":"text"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1usedDiskSpaceInBytes()\/title","value":"usedDiskSpaceInBytes","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1usedDiskSpaceInBytes()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"usedDiskSpaceInBytes","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation\/title","value":"SBSDKDeviceInformation"},{"op":"replace","value":[{"text":"SBSDKDeviceInformation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDeviceInformation"}],"op":"replace"}]}]}