{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession\/isScanningPaused","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession\/isscanningpaused"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession\/isscanningpaused"]}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCameraSession(py)isScanningPaused","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isScanningPaused"}],"title":"isScanningPaused","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isScanningPaused","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"True"},{"type":"text","text":", if the live scanning is paused, "},{"type":"codeVoice","code":"False"},{"type":"text","text":" otherwise. Readonly."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isScanningPaused"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraSession":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraSession","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession","kind":"symbol","role":"symbol","title":"SBSDKCameraSession","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession","abstract":[{"text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the","type":"text"},{"text":" ","type":"text"},{"text":"camera device and the preview layer. Provides functionality to capture still images.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"SBSDKCameraSession","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.0","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraSession/isScanningPaused":{"kind":"symbol","title":"isScanningPaused","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession\/isScanningPaused","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession\/isscanningpaused","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isScanningPaused","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isScanningPaused","kind":"identifier"}],"abstract":[{"text":"Returns ","type":"text"},{"code":"True","type":"codeVoice"},{"text":", if the live scanning is paused, ","type":"text"},{"code":"False","type":"codeVoice"},{"text":" otherwise. Readonly.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isScanningPaused","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"isScanningPaused","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isScanningPaused"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/title","value":"SBSDKCameraSession"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraSession"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/navigatorTitle","value":[{"text":"SBSDKCameraSession","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession~1isScanningPaused\/title","value":"isScanningPaused"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession~1isScanningPaused\/fragments","value":[{"kind":"identifier","text":"isScanningPaused"}],"op":"replace"}]}]}