{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration\/initWithFlashButton:zoomButton:flipCameraButton:"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithFlashButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2RoundButton","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton"},{"text":" *) ","kind":"text"},{"text":"flashButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"zoomButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2RoundButton","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton"},{"text":" *) ","kind":"text"},{"text":"zoomButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"flipCameraButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2RoundButton","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton"},{"text":" *) ","kind":"text"},{"text":"flipCameraButton","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2actionbarconfiguration\/initwithflashbutton:zoombutton:flipcamerabutton:"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithFlashButton:zoomButton:flipCameraButton:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ActionBarConfiguration(im)initWithFlashButton:zoomButton:flipCameraButton:","title":"initWithFlashButton:zoomButton:flipCameraButton:","navigatorTitle":[{"text":"initWithFlashButton:zoomButton:flipCameraButton:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ActionBarConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2actionbarconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ActionBarConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the buttons available in the action bar."}],"title":"SBSDKUI2ActionBarConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ActionBarConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2RoundButton":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2RoundButton","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2RoundButton","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2roundbutton","title":"SBSDKUI2RoundButton","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the round button."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ActionBarConfiguration/initWithFlashButton:zoomButton:flipCameraButton:":{"role":"symbol","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFlashButton:zoomButton:flipCameraButton:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFlashButton:zoomButton:flipCameraButton:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2actionbarconfiguration\/initwithflashbutton:zoombutton:flipcamerabutton:","kind":"symbol","abstract":[],"title":"initWithFlashButton:zoomButton:flipCameraButton:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration\/initWithFlashButton:zoomButton:flipCameraButton:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration\/title","value":"SBSDKUI2ActionBarConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ActionBarConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2ActionBarConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2RoundButton\/title","value":"SBSDKUI2RoundButton","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2RoundButton\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2RoundButton"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2RoundButton\/navigatorTitle","value":[{"text":"SBSDKUI2RoundButton","kind":"identifier"}],"op":"replace"}]}]}