{"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"copyWithZone:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerConfiguration(im)copyWithZone:","roleHeading":"Instance Method"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/copywithzone:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/copyWithZone:","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier","text":"_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration/copyWithZone:":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/copywithzone:","title":"copyWithZone:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/copyWithZone:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration","type":"topic","abstract":[{"text":"Configuration for the VIN scanner.","type":"text"}],"title":"SBSDKVINScannerConfiguration","navigatorTitle":[{"text":"SBSDKVINScannerConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINScannerConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration\/title","value":"SBSDKVINScannerConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKVINScannerConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration\/navigatorTitle","value":[{"text":"SBSDKVINScannerConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}