{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subtitleDeselected","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Configuration of the text displaying a barcode’s symbology in the info box when the barcode is yet to be"},{"type":"text","text":" "},{"type":"text","text":"selected."}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subtitleDeselected","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeItemConfiguration(py)subtitleDeselected","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"subtitleDeselected"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"subtitleDeselected"},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemConfiguration\/subtitleDeselected","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemConfiguration"]]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeitemconfiguration\/subtitledeselected"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeitemconfiguration\/subtitledeselected"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.3"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2StyledText":{"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","title":"SBSDKUI2StyledText","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2styledtext"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeItemConfiguration/subtitleDeselected":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subtitleDeselected","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemConfiguration\/subtitleDeselected","abstract":[{"text":"Configuration of the text displaying a barcode’s symbology in the info box when the barcode is yet to be","type":"text"},{"text":" ","type":"text"},{"text":"selected.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeitemconfiguration\/subtitledeselected","navigatorTitle":[{"text":"subtitleDeselected","kind":"identifier"}],"title":"subtitleDeselected"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeItemConfiguration":{"type":"topic","title":"SBSDKUI2BarcodeItemConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeitemconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the barcode info box displayed in the camera preview."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"subtitleDeselected","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"subtitleDeselected","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText"},{"text":" * ","kind":"text"},{"text":"subtitleDeselected","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUI2StyledText","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/title"},{"op":"replace","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/fragments"},{"value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/navigatorTitle","op":"replace"},{"value":"subtitleDeselected","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemConfiguration~1subtitleDeselected\/title","op":"replace"},{"value":[{"kind":"identifier","text":"subtitleDeselected"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemConfiguration~1subtitleDeselected\/fragments","op":"replace"},{"value":"SBSDKUI2BarcodeItemConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2BarcodeItemConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemConfiguration\/navigatorTitle","op":"replace"}]}]}