{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"overallConsistency","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKValueConsistency","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKValueConsistency"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"Overall status of the consistency verification. Corresponds to the most severe status of all fields."}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"overallConsistency","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKValueConsistency","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKValueConsistency"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKConsistencyVerificationReport(py)overallConsistency","symbolKind":"property","title":"overallConsistency","navigatorTitle":[{"kind":"identifier","text":"overallConsistency"}],"modules":[{"name":"ScanbotSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkconsistencyverificationreport\/overallconsistency"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkconsistencyverificationreport\/overallconsistency"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport\/overallConsistency","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConsistencyVerificationReport":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKConsistencyVerificationReport"}],"role":"symbol","abstract":[{"text":"Report of the document consistency verification. Shows whether information in the fields that correspond to the same logical field is consistent.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport","title":"SBSDKConsistencyVerificationReport","url":"\/documentation\/scanbotsdk\/sbsdkconsistencyverificationreport","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKConsistencyVerificationReport"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConsistencyVerificationReport/overallConsistency":{"navigatorTitle":[{"text":"overallConsistency","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConsistencyVerificationReport\/overallConsistency","url":"\/documentation\/scanbotsdk\/sbsdkconsistencyverificationreport\/overallconsistency","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"overallConsistency","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKValueConsistency","text":"SBSDKValueConsistency","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"Overall status of the consistency verification. Corresponds to the most severe status of all fields.","type":"text"}],"title":"overallConsistency","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency":{"abstract":[{"type":"text","text":"The status of the consistency verification."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKValueConsistency"}],"url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKValueConsistency"}],"type":"topic","title":"SBSDKValueConsistency","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"overallConsistency","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"overallConsistency"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKValueConsistency","text":"SBSDKValueConsistency"},{"kind":"text","text":" "},{"kind":"identifier","text":"overallConsistency"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKConsistencyVerificationReport","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport\/title"},{"value":[{"kind":"identifier","text":"SBSDKConsistencyVerificationReport"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport\/navigatorTitle","value":[{"text":"SBSDKConsistencyVerificationReport","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport~1overallConsistency\/title","value":"overallConsistency"},{"op":"replace","value":[{"kind":"identifier","text":"overallConsistency"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConsistencyVerificationReport~1overallConsistency\/fragments"},{"op":"replace","value":"SBSDKValueConsistency","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKValueConsistency"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKValueConsistency"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/navigatorTitle"}]}]}