{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization"]]},"abstract":[{"text":"The accessibility hint for the ‘rotate page’ button, located in the bottom bar of the cropping screen.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/accessibilitydescriptioncroppingrotatebutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/accessibilitydescriptioncroppingrotatebutton"]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingRotateButton","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"accessibilityDescriptionCroppingRotateButton","kind":"identifier"}],"title":"accessibilityDescriptionCroppingRotateButton","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingTextLocalization(py)accessibilityDescriptionCroppingRotateButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingRotateButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCroppingRotateButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is “Tap to rotate document”"}]}],"kind":"content"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization","title":"SBSDKUI2CroppingTextLocalization","abstract":[{"text":"Configuration of all the strings for the standalone cropping screen.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CroppingTextLocalization"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingTextLocalization"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/accessibilityDescriptionCroppingRotateButton":{"title":"accessibilityDescriptionCroppingRotateButton","role":"symbol","navigatorTitle":[{"text":"accessibilityDescriptionCroppingRotateButton","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCroppingRotateButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The accessibility hint for the ‘rotate page’ button, located in the bottom bar of the cropping screen."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingRotateButton","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/accessibilitydescriptioncroppingrotatebutton","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"accessibilityDescriptionCroppingRotateButton","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"accessibilityDescriptionCroppingRotateButton"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"accessibilityDescriptionCroppingRotateButton"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2CroppingTextLocalization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization\/title"},{"value":[{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CroppingTextLocalization"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization\/navigatorTitle"},{"op":"replace","value":"accessibilityDescriptionCroppingRotateButton","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1accessibilityDescriptionCroppingRotateButton\/title"},{"op":"replace","value":[{"kind":"identifier","text":"accessibilityDescriptionCroppingRotateButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1accessibilityDescriptionCroppingRotateButton\/fragments"}]}]}