{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerEnergyConfiguration"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"dynamic","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"energySaveDetectionRate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/energySaveDetectionRate"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerenergyconfiguration\/energysavedetectionrate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerenergyconfiguration\/energysavedetectionrate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"energySaveDetectionRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"symbolKind":"property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration(py)energySaveDetectionRate","navigatorTitle":[{"text":"energySaveDetectionRate","kind":"identifier"}],"roleHeading":"Instance Property","title":"energySaveDetectionRate"},"kind":"symbol","abstract":[{"text":"The rate of detections\/recognitions per second in energy save mode.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to 1, meaning that 1 frame per second is detected\/recognized.","type":"text"},{"text":" ","type":"text"},{"text":"When the video frame rate is 30, 29 frames will be skipped, 1 frame is detected\/recognized.","type":"text"},{"text":" ","type":"text"},{"text":"Note: if you set the detection rate greater to or equal to the video frame rate, no frames will be skipped,","type":"text"},{"text":" ","type":"text"},{"text":"the actual detection rate is limited by the video frame rate.","type":"text"},{"text":" ","type":"text"},{"text":"Note: Usually you set a much lower value here as for the detectionRate property to save energy.","type":"text"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerEnergyConfiguration/energySaveDetectionRate":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerenergyconfiguration\/energysavedetectionrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"energySaveDetectionRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/energySaveDetectionRate","navigatorTitle":[{"kind":"identifier","text":"energySaveDetectionRate"}],"role":"symbol","title":"energySaveDetectionRate","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The rate of detections\/recognitions per second in energy save mode."},{"type":"text","text":" "},{"type":"text","text":"Defaults to 1, meaning that 1 frame per second is detected\/recognized."},{"type":"text","text":" "},{"type":"text","text":"When the video frame rate is 30, 29 frames will be skipped, 1 frame is detected\/recognized."},{"type":"text","text":" "},{"type":"text","text":"Note: if you set the detection rate greater to or equal to the video frame rate, no frames will be skipped,"},{"type":"text","text":" "},{"type":"text","text":"the actual detection rate is limited by the video frame rate."},{"type":"text","text":" "},{"type":"text","text":"Note: Usually you set a much lower value here as for the detectionRate property to save energy."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerEnergyConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}],"abstract":[{"text":"The energy management configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"‘SBSDKBaseScannerViewController’ and subclasses sport a customizable energy management system."},{"type":"text","text":" "},{"type":"text","text":"Since scanners running on a live video feed can put a lot of load onto the CPU and\/or GPU"},{"type":"text","text":" "},{"type":"text","text":"of the device, causing the battery to drain quickly and running the device hot, you can customize the energy"},{"type":"text","text":" "},{"type":"text","text":"consumption using this class by configuring the rate of detections\/recognitions per second in performance mode as"},{"type":"text","text":" "},{"type":"text","text":"well as in energy saving mode."},{"type":"text","text":" "},{"type":"text","text":"In performance mode the scanners will be fed with a higher, configurable rate of"},{"type":"text","text":" "},{"type":"text","text":"video frames per second."},{"type":"text","text":" "},{"type":"text","text":"After a certain, configurable period of inactivity the energy save mode will be engaged and the rate"},{"type":"text","text":" "},{"type":"text","text":"of scans will be reduced to a lower (configurable) rate."},{"type":"text","text":" "},{"type":"text","text":"You can also configure the time of inactivity before the automatic mode switches from performance to energy save mode."},{"type":"text","text":" "},{"type":"text","text":"Inactivity here means that both of the following conditions are met:"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerEnergyConfiguration","role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerenergyconfiguration","title":"SBSDKBaseScannerEnergyConfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"energySaveDetectionRate","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"energySaveDetectionRate","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"energySaveDetectionRate"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"energySaveDetectionRate","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerEnergyConfiguration~1energySaveDetectionRate\/title"},{"op":"replace","value":[{"text":"energySaveDetectionRate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerEnergyConfiguration~1energySaveDetectionRate\/fragments"},{"op":"replace","value":"SBSDKBaseScannerEnergyConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}