{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/isEnergySavingEnabled","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"dynamic","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEnergySavingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerenergyconfiguration\/isenergysavingenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerenergyconfiguration\/isenergysavingenabled"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerEnergyConfiguration"]]},"abstract":[{"type":"text","text":"Set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":", if automatic energy saving should be enabled. With automatic energy saving enabled the"},{"type":"text","text":" "},{"type":"text","text":"base scanner view controller will, after a certain time of inactivity, enter the energy save mode by lowering the"},{"type":"text","text":" "},{"type":"text","text":"detection\/scanning rate."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration(py)isEnergySavingEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnergySavingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"isEnergySavingEnabled","kind":"identifier"}],"symbolKind":"property","title":"isEnergySavingEnabled"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerEnergyConfiguration/isEnergySavingEnabled":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/isEnergySavingEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnergySavingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isEnergySavingEnabled","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerenergyconfiguration\/isenergysavingenabled","abstract":[{"type":"text","text":"Set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":", if automatic energy saving should be enabled. With automatic energy saving enabled the"},{"type":"text","text":" "},{"type":"text","text":"base scanner view controller will, after a certain time of inactivity, enter the energy save mode by lowering the"},{"type":"text","text":" "},{"type":"text","text":"detection\/scanning rate."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEnergySavingEnabled"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerEnergyConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}],"abstract":[{"text":"The energy management configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"‘SBSDKBaseScannerViewController’ and subclasses sport a customizable energy management system."},{"type":"text","text":" "},{"type":"text","text":"Since scanners running on a live video feed can put a lot of load onto the CPU and\/or GPU"},{"type":"text","text":" "},{"type":"text","text":"of the device, causing the battery to drain quickly and running the device hot, you can customize the energy"},{"type":"text","text":" "},{"type":"text","text":"consumption using this class by configuring the rate of detections\/recognitions per second in performance mode as"},{"type":"text","text":" "},{"type":"text","text":"well as in energy saving mode."},{"type":"text","text":" "},{"type":"text","text":"In performance mode the scanners will be fed with a higher, configurable rate of"},{"type":"text","text":" "},{"type":"text","text":"video frames per second."},{"type":"text","text":" "},{"type":"text","text":"After a certain, configurable period of inactivity the energy save mode will be engaged and the rate"},{"type":"text","text":" "},{"type":"text","text":"of scans will be reduced to a lower (configurable) rate."},{"type":"text","text":" "},{"type":"text","text":"You can also configure the time of inactivity before the automatic mode switches from performance to energy save mode."},{"type":"text","text":" "},{"type":"text","text":"Inactivity here means that both of the following conditions are met:"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerEnergyConfiguration","role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerenergyconfiguration","title":"SBSDKBaseScannerEnergyConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"isEnergySavingEnabled","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"isEnergySavingEnabled","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnergySavingEnabled"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerEnergyConfiguration~1isEnergySavingEnabled\/title","value":"isEnergySavingEnabled","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerEnergyConfiguration~1isEnergySavingEnabled\/fragments","value":[{"kind":"identifier","text":"isEnergySavingEnabled"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/title","value":"SBSDKBaseScannerEnergyConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}],"op":"replace"}]}]}