{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2pagesnapfeedbackmode\/tojson()"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2pagesnapfeedbackmode\/tojson()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFeedbackMode"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFeedbackMode\/toJson()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"toJson","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PageSnapFeedbackMode(im)toJson","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"toJson()"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PageSnapFeedbackMode":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2pagesnapfeedbackmode","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackMode"}],"abstract":[{"text":"The type of animation to display after snapping a page.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","title":"SBSDKUI2PageSnapFeedbackMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFeedbackMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PageSnapFeedbackMode/toJson()":{"title":"toJson()","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2pagesnapfeedbackmode\/tojson()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFeedbackMode\/toJson()","navigatorTitle":[{"text":"toJson","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"toJson","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJson"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKUI2PageSnapFeedbackMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackMode\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackMode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackMode~1toJson()\/title","op":"replace","value":"toJson"},{"value":[{"kind":"text","text":"- "},{"text":"toJson","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackMode~1toJson()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}