{"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"metadata":{"title":"SBSDKTIFFGeneratorParameters","symbolKind":"class","navigatorTitle":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGeneratorParameters","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"TIFF generator parameters."}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/init()"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/binarizationFilter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/compression","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/dpi","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/jpegQuality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/userFields","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/zipCompressionLevel"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/binaryDocumentOptimizedCompression","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/defaultCompression","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/defaultParameters","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/defaultParametersForBinaryImages"],"generated":true,"anchor":"Type-Properties"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKTIFFGeneratorParameters) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/compression":{"title":"compression","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/compression","abstract":[{"text":"Compression.","type":"text"}],"navigatorTitle":[{"text":"compression","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"compression","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompressionMode","text":"SBSDKCompressionMode","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/compression"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/fromJsonWithJson:":{"url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/fromjsonwithjson:","title":"fromJsonWithJson:","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/defaultCompression":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Default compression."}],"url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/defaultcompression","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/defaultCompression","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultCompression"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCompressionMode","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompressionMode"}],"navigatorTitle":[{"kind":"identifier","text":"defaultCompression"}],"title":"defaultCompression"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/jpegQuality":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"JPEG quality (TIFFTAG_JPEGQUALITY). Values range from 0 to 100."}],"url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/jpegquality","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/jpegQuality","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpegQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"jpegQuality"}],"title":"jpegQuality"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/zipCompressionLevel":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"ZIP\/Deflate compression level (TIFFTAG_ZIPQUALITY). Values range from 1 to 9."}],"url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/zipcompressionlevel","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/zipCompressionLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zipCompressionLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"zipCompressionLevel"}],"title":"zipCompressionLevel"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/userFields":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/userFields","abstract":[{"text":"User-defined fields.","type":"text"}],"kind":"symbol","role":"symbol","title":"userFields","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/userfields","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKUserField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUserField","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"userFields","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/defaultParametersForBinaryImages":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultParametersForBinaryImages","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKTIFFGeneratorParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGeneratorParameters"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/defaultparametersforbinaryimages","kind":"symbol","abstract":[{"type":"text","text":"The default parameters for TIFF generating with binarization."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/defaultParametersForBinaryImages","type":"topic","title":"defaultParametersForBinaryImages"},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters","abstract":[{"text":"TIFF generator parameters.","type":"text"}],"title":"SBSDKTIFFGeneratorParameters","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/toJson(configuration:)":{"abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/tojson(configuration:)","title":"toJson(configuration:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/toJson(configuration:)","role":"symbol"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/binaryDocumentOptimizedCompression":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"binaryDocumentOptimizedCompression","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompressionMode","text":"SBSDKCompressionMode","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/binarydocumentoptimizedcompression","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/binaryDocumentOptimizedCompression","type":"topic","abstract":[{"text":"Compression mode typically producing the smallest file sizes for binary (1-bit) document images.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"binaryDocumentOptimizedCompression","kind":"identifier"}],"title":"binaryDocumentOptimizedCompression"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/isEqual:":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/isequal:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/initWithCompression:jpegQuality:zipCompressionLevel:dpi:userFields:binarizationFilter:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/initWithCompression:jpegQuality:zipCompressionLevel:dpi:userFields:binarizationFilter:","type":"topic","title":"initWithCompression:jpegQuality:zipCompressionLevel:dpi:userFields:binarizationFilter:","abstract":[],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCompression:jpegQuality:zipCompressionLevel:dpi:userFields:binarizationFilter:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/initwithcompression:jpegquality:zipcompressionlevel:dpi:userfields:binarizationfilter:","navigatorTitle":[{"text":"initWithCompression:jpegQuality:zipCompressionLevel:dpi:userFields:binarizationFilter:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/copyWithZone:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"role":"symbol","abstract":[],"title":"copyWithZone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/copywithzone:","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/hash":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/hash","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/hash","abstract":[],"title":"hash","kind":"symbol","fragments":[{"kind":"identifier","text":"hash"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/binarizationFilter":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"binarizationFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/binarizationfilter","title":"binarizationFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"binarizationFilter"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/binarizationFilter","abstract":[{"type":"text","text":"Filter to apply to the input image when adding pages with binarization."},{"type":"text","text":" "},{"type":"text","text":"If set, the filter is applied to the input image and the resulting image is stored as a 1-bit TIFF."},{"type":"text","text":" "},{"type":"text","text":"When storing documents it’s typically best to use the BINARY_DOCUMENT_OPTIMIZED_COMPRESSION compression mode"},{"type":"text","text":" "},{"type":"text","text":"(CCITT_T6)"},{"type":"text","text":" "},{"type":"text","text":"instead of the default, as it tends to produce the smallest file sizes."},{"type":"text","text":" "},{"type":"text","text":"If not set, simple thresholding is applied to the image, instead."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/init()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"type":"topic","title":"init()","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/init()","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/dpi":{"abstract":[{"text":"DPI value.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/dpi","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/dpi","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dpi","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"dpi","kind":"identifier"}],"title":"dpi","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/defaultParameters":{"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/defaultparameters","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/defaultParameters","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultParameters","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGeneratorParameters","text":"SBSDKTIFFGeneratorParameters","kind":"typeIdentifier"}],"title":"defaultParameters","type":"topic","abstract":[{"type":"text","text":"The default parameters for TIFF generating."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKTIFFGeneratorParameters","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/binarizationFilter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/compression","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/dpi","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/jpegQuality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/userFields","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/zipCompressionLevel"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/initWithCompression:jpegQuality:zipCompressionLevel:dpi:userFields:binarizationFilter:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/toJson(configuration:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/binaryDocumentOptimizedCompression","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/defaultCompression"],"generated":true,"title":"Type Properties","anchor":"Type-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/fromJsonWithJson:"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"type":"conformsTo"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1compression\/title","value":"compression","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1compression\/fragments","value":[{"text":"compression","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1defaultCompression\/title","value":"defaultCompression"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1defaultCompression\/fragments","value":[{"kind":"identifier","text":"defaultCompression"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1jpegQuality\/title","value":"jpegQuality"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1jpegQuality\/fragments","value":[{"kind":"identifier","text":"jpegQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1zipCompressionLevel\/title","value":"zipCompressionLevel"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1zipCompressionLevel\/fragments","value":[{"text":"zipCompressionLevel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1userFields\/title","value":"userFields"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1userFields\/fragments","value":[{"text":"userFields","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/title","value":"SBSDKTIFFGeneratorParameters"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/fragments","value":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/navigatorTitle","value":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1toJson(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1binaryDocumentOptimizedCompression\/title","value":"binaryDocumentOptimizedCompression"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1binaryDocumentOptimizedCompression\/fragments","value":[{"kind":"identifier","text":"binaryDocumentOptimizedCompression"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1binarizationFilter\/title","value":"binarizationFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1binarizationFilter\/fragments","value":[{"text":"binarizationFilter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1dpi\/title","value":"dpi"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1dpi\/fragments","value":[{"kind":"identifier","text":"dpi"}]}]}]}