{"abstract":[{"type":"text","text":"The sound selection type."}],"kind":"symbol","sections":[],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType\/classic","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType\/modern"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdksoundtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdksoundtype"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKSoundType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSoundType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKSoundType","kind":"identifier"}],"roleHeading":"Enumeration","externalID":"c:@M@ScanbotSDK@E@SBSDKSoundType","symbolKind":"enum","role":"symbol"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSoundType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundType/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdksoundtype\/rawrepresentable-implementations","type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundType/modern":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKSoundTypeModern","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType\/modern","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modern","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdksoundtype\/modern","abstract":[{"type":"text","text":"To choose the modern beep sound."}],"title":"SBSDKSoundType.modern","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundType/Equatable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdksoundtype\/equatable-implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType\/Equatable-Implementations","abstract":[],"kind":"article","title":"Equatable Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundType/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","title":"init(rawValue:)","url":"\/documentation\/scanbotsdk\/sbsdksoundtype\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType\/init(rawValue:)","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundType/classic":{"abstract":[{"type":"text","text":"To choose the old classic beep sound."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType\/classic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"classic","kind":"identifier"}],"title":"SBSDKSoundType.classic","navigatorTitle":[{"text":"SBSDKSoundTypeClassic","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdksoundtype\/classic","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundType":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSoundType"}],"abstract":[{"type":"text","text":"The sound selection type."}],"title":"SBSDKSoundType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKSoundType"}],"url":"\/documentation\/scanbotsdk\/sbsdksoundtype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKSoundType","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKSoundType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKSoundType","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType\/classic","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundType\/modern"],"generated":true,"title":"Enumeration Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSoundType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundType~1modern\/title","value":"SBSDKSoundTypeModern"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundType~1modern\/fragments","value":[{"kind":"identifier","text":"SBSDKSoundTypeModern"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundType~1classic\/title","value":"SBSDKSoundTypeClassic"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundType~1classic\/fragments","value":[{"text":"SBSDKSoundTypeClassic","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundType\/title","value":"SBSDKSoundType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundType\/fragments","value":[{"text":"SBSDKSoundType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKSoundType"}]}]}]}