{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageref"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageref"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/uniqueId"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/clear()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/clone()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/close()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/encodeImage(options:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/hibernate()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/info()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/saveImage(path:options:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/saveImage(url:options:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/serialize()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/toUIImage()"],"anchor":"Instance-Methods"},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/fromEncodedBuffer(encodedBuffer:options:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/fromPath(path:options:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/fromSampleBuffer(sampleBuffer:options:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/fromUIImage(image:options:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/releaseAllImages()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/setHibernationCacheDir(cacheDirPath:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/setHibernationJpegQuality(quality:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/setStorageCryptingProvider(provider:)"],"anchor":"Type-Methods"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships"}],"metadata":{"symbolKind":"class","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","roleHeading":"Class","navigatorTitle":[{"text":"SBSDKImageRef","kind":"identifier"}],"role":"symbol","title":"SBSDKImageRef","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRef","kind":"identifier"}]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRef"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"type":"text","text":"Image ref class."}],"references":{"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRef","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","type":"topic","kind":"symbol","abstract":[{"text":"Image ref class.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageref","role":"symbol","title":"SBSDKImageRef","navigatorTitle":[{"text":"SBSDKImageRef","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/initWithUniqueId:acquireStrongReference:":{"type":"topic","title":"initWithUniqueId:acquireStrongReference:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUniqueId:acquireStrongReference:"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/initwithuniqueid:acquirestrongreference:","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/initWithUniqueId:acquireStrongReference:","navigatorTitle":[{"kind":"identifier","text":"initWithUniqueId:acquireStrongReference:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/acquireSerializedReferenceWithUniqueId:":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/acquireserializedreferencewithuniqueid:","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"acquireSerializedReferenceWithUniqueId:"}],"title":"acquireSerializedReferenceWithUniqueId:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/acquireSerializedReferenceWithUniqueId:","kind":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"acquireSerializedReferenceWithUniqueId:"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/clear()":{"kind":"symbol","navigatorTitle":[{"text":"clear","kind":"identifier"}],"abstract":[{"type":"text","text":"Releases native resources stored by the ref."},{"type":"text","text":" "},{"type":"text","text":"If two different ImageRef objects have the same uniqueId both of them become cleared."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clear","kind":"identifier"},{"text":"()","kind":"text"}],"title":"clear()","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/clear()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/clear()","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/setStorageCryptingProvider(provider:)":{"url":"\/documentation\/scanbotsdk\/sbsdkimageref\/setstoragecryptingprovider(provider:)","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/setStorageCryptingProvider(provider:)","abstract":[{"text":"Sets crypting provider that is used when an image is read\/written from\/to disk.","type":"text"},{"text":" ","type":"text"},{"text":"The provider is used both when images are hibernated and when they are saved\/loaded from disk with saveImage\/fromPath.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setStorageCryptingProvider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"provider","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingProvider","text":"SBSDKStorageCryptingProvider","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"setStorageCryptingProvider(provider:)","navigatorTitle":[{"text":"setStorageCryptingProviderWithProvider:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/close()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"close"},{"kind":"text","text":"()"}],"title":"close()","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"close"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageref\/close()","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/close()","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/fromEncodedBuffer(encodedBuffer:options:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/fromEncodedBuffer(encodedBuffer:options:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromEncodedBufferWithEncodedBuffer:options:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromEncodedBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"encodedBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBufferImageLoadOptions","text":"SBSDKBufferImageLoadOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","title":"fromEncodedBuffer(encodedBuffer:options:)","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/fromencodedbuffer(encodedbuffer:options:)","abstract":[{"type":"text","text":"Creates ImageRef from encoded buffer, e.g. from jpeg."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/toUIImage()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/toUIImage()","role":"symbol","navigatorTitle":[{"text":"toUIImage","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toUIImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"kind":"symbol","title":"toUIImage()","type":"topic","abstract":[{"type":"text","text":"Returns stored image as a UIImage."}],"url":"\/documentation\/scanbotsdk\/sbsdkimageref\/touiimage()"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/fromSampleBuffer(sampleBuffer:options:)":{"type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkimageref\/fromsamplebuffer(samplebuffer:options:)","navigatorTitle":[{"text":"fromSampleBufferWithSampleBuffer:options:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromSampleBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sampleBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKRawImageLoadOptions","text":"SBSDKRawImageLoadOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/fromSampleBuffer(sampleBuffer:options:)","kind":"symbol","title":"fromSampleBuffer(sampleBuffer:options:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/setHibernationJpegQuality(quality:)":{"kind":"symbol","navigatorTitle":[{"text":"setHibernationJpegQualityWithQuality:","kind":"identifier"}],"abstract":[{"type":"text","text":"Sets the quality of JPEG compression used to encode images when hibernating. The default is 80."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setHibernationJpegQuality","kind":"identifier"},{"text":"(","kind":"text"},{"text":"quality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"setHibernationJpegQuality(quality:)","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/sethibernationjpegquality(quality:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/setHibernationJpegQuality(quality:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/encodeImage(options:)":{"url":"\/documentation\/scanbotsdk\/sbsdkimageref\/encodeimage(options:)","abstract":[{"type":"text","text":"Returns the stored image encoded with the given options"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/encodeImage(options:)","type":"topic","navigatorTitle":[{"text":"encodeImageWithOptions:","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"encodeImage(options:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encodeImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEncodeImageOptions","text":"SBSDKEncodeImageOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/info()":{"title":"info()","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/info()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKImageInfo","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageInfo","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"info","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Information about stored image."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/info()"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/clone()":{"title":"clone()","abstract":[{"type":"text","text":"Creates a deep copy of the image."}],"navigatorTitle":[{"kind":"identifier","text":"clone"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clone"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","kind":"typeIdentifier","text":"SBSDKImageRef"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/clone()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/clone()","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/fromUIImage(image:options:)":{"title":"fromUIImage(image:options:)","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/fromuiimage(image:options:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromUIImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBasicImageLoadOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBasicImageLoadOptions"},{"text":") -> ","kind":"text"},{"text":"SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"}],"navigatorTitle":[{"kind":"identifier","text":"fromUIImageWithImage:options:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/fromUIImage(image:options:)","abstract":[{"type":"text","text":"Creates ImageRef from an UIImage."}]},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/setHibernationCacheDir(cacheDirPath:)":{"navigatorTitle":[{"kind":"identifier","text":"setHibernationCacheDirWithCacheDirPath:"}],"title":"setHibernationCacheDir(cacheDirPath:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setHibernationCacheDir"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cacheDirPath"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/sethibernationcachedir(cachedirpath:)","abstract":[{"text":"Sets directory in which hibernated images are stored.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If null is passed, then hibernated images are stored in compressed format in memory."},{"type":"text","text":" "},{"type":"text","text":"Must be set once when application is initialized."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/setHibernationCacheDir(cacheDirPath:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/releaseStrongReferenceWithUniqueId:":{"title":"releaseStrongReferenceWithUniqueId:","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/releasestrongreferencewithuniqueid:","fragments":[{"text":"+ ","kind":"text"},{"text":"releaseStrongReferenceWithUniqueId:","kind":"identifier"}],"navigatorTitle":[{"text":"releaseStrongReferenceWithUniqueId:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/releaseStrongReferenceWithUniqueId:","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/hibernate()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/hibernate()","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/hibernate()","type":"topic","title":"hibernate()","navigatorTitle":[{"kind":"identifier","text":"hibernate"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hibernate"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Compresses ImageRef and stores it either on disk or in memory according to global settings."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/fromPath(path:options:)":{"abstract":[{"type":"text","text":"Creates ImageRef from the path to an image."}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"path","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPathImageLoadOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPathImageLoadOptions"},{"text":") -> ","kind":"text"},{"text":"SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/fromPath(path:options:)","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/frompath(path:options:)","type":"topic","title":"fromPath(path:options:)","navigatorTitle":[{"kind":"identifier","text":"fromPathWithPath:options:"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/saveImage(path:options:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/saveImage(path:options:)","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/saveimage(path:options:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Saves the stored image with the given options"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"saveImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"path"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKSaveImageOptions","kind":"typeIdentifier","text":"SBSDKSaveImageOptions"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"saveImageWithPath:options:"}],"kind":"symbol","title":"saveImage(path:options:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/saveImage(url:options:)":{"abstract":[{"text":"Saves the stored image at the provided URL with the given options.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"saveImageWithUrl:options:"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/saveImage(url:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"saveImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKSaveImageOptions","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKSaveImageOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"saveImage(url:options:)","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/saveimage(url:options:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/uniqueId":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"uniqueId"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uniqueId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageref\/uniqueid","abstract":[{"type":"text","text":"Unique id of the native resource the object points to."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/uniqueId","title":"uniqueId"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/releaseAllImages()":{"navigatorTitle":[{"text":"releaseAllImages","kind":"identifier"}],"abstract":[{"type":"text","text":"Releases all alive images despite any existing references."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/releaseAllImages()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"releaseAllImages","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","title":"releaseAllImages()","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/releaseallimages()","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/upgradeSerializedReferenceWithUniqueId:":{"role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"upgradeSerializedReferenceWithUniqueId:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"upgradeSerializedReferenceWithUniqueId:","navigatorTitle":[{"text":"upgradeSerializedReferenceWithUniqueId:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageref\/upgradeserializedreferencewithuniqueid:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/upgradeSerializedReferenceWithUniqueId:","abstract":[]},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef/serialize()":{"type":"topic","kind":"symbol","title":"serialize()","url":"\/documentation\/scanbotsdk\/sbsdkimageref\/serialize()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/serialize()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"serialize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Converts ImageRef to serialized string representation with acquiring serialized reference to the native resource."},{"type":"text","text":" "},{"type":"text","text":"You must eventually call deserialize, otherwise the reference will leak"}],"navigatorTitle":[{"kind":"identifier","text":"serialize"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKImageRef"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKImageRef"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageRef"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/uniqueId"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/clear()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/clone()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/close()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/encodeImage(options:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/hibernate()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/info()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/initWithUniqueId:acquireStrongReference:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/saveImage(path:options:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/saveImage(url:options:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/serialize()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/toUIImage()"],"generated":true},{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/acquireSerializedReferenceWithUniqueId:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/fromEncodedBuffer(encodedBuffer:options:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/fromPath(path:options:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/fromSampleBuffer(sampleBuffer:options:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/fromUIImage(image:options:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/releaseAllImages()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/releaseStrongReferenceWithUniqueId:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/setHibernationCacheDir(cacheDirPath:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/setHibernationJpegQuality(quality:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/setStorageCryptingProvider(provider:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef\/upgradeSerializedReferenceWithUniqueId:"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRef"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/title","value":"SBSDKImageRef"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/fragments","value":[{"text":"SBSDKImageRef","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/navigatorTitle","value":[{"text":"SBSDKImageRef","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1clear()\/title","value":"clear"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1clear()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"clear","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1setStorageCryptingProvider(provider:)\/title","value":"setStorageCryptingProviderWithProvider:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1setStorageCryptingProvider(provider:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setStorageCryptingProviderWithProvider:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1close()\/title","value":"close"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1close()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"close","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1fromEncodedBuffer(encodedBuffer:options:)\/title","value":"fromEncodedBufferWithEncodedBuffer:options:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1fromEncodedBuffer(encodedBuffer:options:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromEncodedBufferWithEncodedBuffer:options:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1toUIImage()\/title","value":"toUIImage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1toUIImage()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toUIImage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1fromSampleBuffer(sampleBuffer:options:)\/title","value":"fromSampleBufferWithSampleBuffer:options:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1fromSampleBuffer(sampleBuffer:options:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromSampleBufferWithSampleBuffer:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1setHibernationJpegQuality(quality:)\/title","value":"setHibernationJpegQualityWithQuality:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1setHibernationJpegQuality(quality:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setHibernationJpegQualityWithQuality:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1encodeImage(options:)\/title","value":"encodeImageWithOptions:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1encodeImage(options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"encodeImageWithOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1info()\/title","value":"info"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1info()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"info","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1clone()\/title","value":"clone"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1clone()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clone"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1fromUIImage(image:options:)\/title","value":"fromUIImageWithImage:options:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1fromUIImage(image:options:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromUIImageWithImage:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1setHibernationCacheDir(cacheDirPath:)\/title","value":"setHibernationCacheDirWithCacheDirPath:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1setHibernationCacheDir(cacheDirPath:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setHibernationCacheDirWithCacheDirPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1hibernate()\/title","value":"hibernate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1hibernate()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"hibernate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1fromPath(path:options:)\/title","value":"fromPathWithPath:options:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1fromPath(path:options:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromPathWithPath:options:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1saveImage(path:options:)\/title","value":"saveImageWithPath:options:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1saveImage(path:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"saveImageWithPath:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1saveImage(url:options:)\/title","value":"saveImageWithUrl:options:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1saveImage(url:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"saveImageWithUrl:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1uniqueId\/title","value":"uniqueId"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1uniqueId\/fragments","value":[{"text":"uniqueId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1releaseAllImages()\/title","value":"releaseAllImages"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1releaseAllImages()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"releaseAllImages","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1serialize()\/title","value":"serialize"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef~1serialize()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"serialize","kind":"identifier"}]}]}]}