{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScanGuidanceConfiguration"}],"roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScanGuidanceConfiguration","title":"SBSDKUI2CreditCardScanGuidanceConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScanGuidanceConfiguration"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"text":"Configuration of the hints guiding users through the credit card scanning process.","type":"text"}],"kind":"symbol","sections":[],"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/init()"],"generated":true},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/background","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/statesTitles","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/title","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/visibility"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/toJson(configuration:)"],"generated":true}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKUI2CreditCardScanGuidanceConfiguration) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScanGuidanceConfiguration"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanGuidanceConfiguration/hash":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/hash","title":"hash","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration\/hash","fragments":[{"kind":"identifier","text":"hash"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanGuidanceConfiguration/visibility":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visibility"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/visibility","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration\/visibility","title":"visibility","abstract":[{"type":"text","text":"Determines whether the user guidance hints should be visible (enabled)."}],"navigatorTitle":[{"kind":"identifier","text":"visibility"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanGuidanceConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScanGuidanceConfiguration"}],"type":"topic","title":"SBSDKUI2CreditCardScanGuidanceConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScanGuidanceConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration","abstract":[{"text":"Configuration of the hints guiding users through the credit card scanning process.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanGuidanceConfiguration/title":{"abstract":[{"type":"text","text":"Configure the text style for the user guidance hints."}],"title":"title","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration\/title","navigatorTitle":[{"kind":"identifier","text":"title"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/title"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanGuidanceConfiguration/fromJsonWithJson:":{"title":"fromJsonWithJson:","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration\/fromjsonwithjson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/fromJsonWithJson:"},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Node"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2node","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Node"}],"abstract":[{"type":"text","text":"Abstract class for all the configurations."}],"title":"SBSDKUI2Node","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","kind":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanGuidanceConfiguration/initWithVisibility:title:background:statesTitles:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/initWithVisibility:title:background:statesTitles:","kind":"symbol","title":"initWithVisibility:title:background:statesTitles:","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration\/initwithvisibility:title:background:statestitles:","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithVisibility:title:background:statesTitles:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithVisibility:title:background:statesTitles:","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanGuidanceConfiguration/toJson(configuration:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"toJson(configuration:)","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration\/tojson(configuration:)","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/toJson(configuration:)","abstract":[{"type":"text","text":"Returns a JSON string representation format."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanGuidanceConfiguration/statesTitles":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/statesTitles","abstract":[{"type":"text","text":"Configure the captions of the user guidance hints for different states."}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"statesTitles","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerGuidanceStates","text":"SBSDKUI2CreditCardScannerGuidanceStates"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration\/statestitles","navigatorTitle":[{"kind":"identifier","text":"statesTitles"}],"title":"statesTitles"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanGuidanceConfiguration/isEqual:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration\/isequal:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/isEqual:","title":"isEqual:","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanGuidanceConfiguration/background":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"background","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BackgroundStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BackgroundStyle","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/background","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration\/background","kind":"symbol","navigatorTitle":[{"text":"background","kind":"identifier"}],"title":"background","abstract":[{"type":"text","text":"Configure the background style for the user guidance hints."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanGuidanceConfiguration/copyWithZone:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration\/copywithzone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/copyWithZone:","abstract":[],"title":"copyWithZone:","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanGuidanceConfiguration/init()":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init()","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration\/init()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/init()","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKUI2CreditCardScanGuidanceConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKUI2CreditCardScanGuidanceConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKUI2CreditCardScanGuidanceConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/background","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/statesTitles","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/title","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/visibility"],"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/initWithVisibility:title:background:statesTitles:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/toJson(configuration:)"],"title":"Instance Methods"},{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/fromJsonWithJson:"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"title":"Conforms To","type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardScanGuidanceConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"SBSDKUI2Node","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"visibility","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration~1visibility\/title"},{"value":[{"kind":"identifier","text":"visibility"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration~1visibility\/fragments"},{"value":"SBSDKUI2CreditCardScanGuidanceConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration\/title"},{"value":[{"text":"SBSDKUI2CreditCardScanGuidanceConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2CreditCardScanGuidanceConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration\/navigatorTitle"},{"value":"title","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration~1title\/title"},{"value":[{"text":"title","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration~1title\/fragments"},{"value":"SBSDKUI2Node","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2Node"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments"},{"value":[{"text":"SBSDKUI2Node","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/navigatorTitle"},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration~1toJson(configuration:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration~1toJson(configuration:)\/fragments"},{"value":"statesTitles","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration~1statesTitles\/title"},{"value":[{"text":"statesTitles","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration~1statesTitles\/fragments"},{"value":"background","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration~1background\/title"},{"value":[{"text":"background","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration~1background\/fragments"},{"value":"init","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration~1init()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration~1init()\/fragments"}]}]}