{"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/init(fieldTypeName:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/fieldTypeName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/maxYear","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/minYear"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/toJson(configuration:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKGenericDocumentRecognizerDateValidationConfiguration) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Date validation configuration."},{"type":"text","text":" "},{"type":"text","text":"This configuration element does not enable the scanning of any document types by itself."},{"type":"text","text":" "},{"type":"text","text":"Add to recognizer configuration to require date validation checks for specific document types."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"}],"role":"symbol","roleHeading":"Class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerDateValidationConfiguration","symbolKind":"class","title":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"}]},"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerDateValidationConfiguration":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration","abstract":[{"type":"text","text":"Date validation configuration."},{"type":"text","text":" "},{"type":"text","text":"This configuration element does not enable the scanning of any document types by itself."},{"type":"text","text":" "},{"type":"text","text":"Add to recognizer configuration to require date validation checks for specific document types."}],"navigatorTitle":[{"text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration","title":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"Foundation.NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerDateValidationConfiguration/isEqual:":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration\/isequal:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/isEqual:","kind":"symbol","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerDateValidationConfiguration/init(fieldTypeName:)":{"type":"topic","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration\/init(fieldtypename:)","navigatorTitle":[{"kind":"identifier","text":"initWithFieldTypeName:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/init(fieldTypeName:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fieldTypeName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"title":"init(fieldTypeName:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerDateValidationConfiguration/fieldTypeName":{"navigatorTitle":[{"text":"fieldTypeName","kind":"identifier"}],"type":"topic","abstract":[{"text":"Name, FullName, or NormalizedName of field type for which the year bounds should be applied.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration\/fieldtypename","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fieldTypeName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/fieldTypeName","title":"fieldTypeName"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerDateValidationConfiguration/fromJsonWithJson:":{"title":"fromJsonWithJson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration\/fromjsonwithjson:","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerDateValidationConfiguration/maxYear":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/maxYear","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration\/maxyear","title":"maxYear","abstract":[{"type":"text","text":"Maximum year that is considered valid."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxYear"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"maxYear"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerDateValidationConfiguration/hash":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/hash","title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration\/hash","abstract":[],"fragments":[{"kind":"identifier","text":"hash"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationElement":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationelement","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement","abstract":[{"text":"Base class for all generic document configuration elements.","type":"text"}],"type":"topic","kind":"symbol","title":"SBSDKDocumentDataExtractorConfigurationElement","navigatorTitle":[{"text":"SBSDKDocumentDataExtractorConfigurationElement","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorConfigurationElement","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerDateValidationConfiguration/toJson(configuration:)":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/toJson(configuration:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"toJson(configuration:)","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration\/tojson(configuration:)","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerDateValidationConfiguration/minYear":{"abstract":[{"type":"text","text":"Minimum year that is considered valid."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"minYear"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration\/minyear","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minYear"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/minYear","title":"minYear"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerDateValidationConfiguration/copyWithZone:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration\/copywithzone:","role":"symbol","type":"topic","title":"copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerDateValidationConfiguration/initWithMinYear:maxYear:fieldTypeName:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/initWithMinYear:maxYear:fieldTypeName:","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration\/initwithminyear:maxyear:fieldtypename:","role":"symbol","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMinYear:maxYear:fieldTypeName:"}],"type":"topic","title":"initWithMinYear:maxYear:fieldTypeName:","navigatorTitle":[{"kind":"identifier","text":"initWithMinYear:maxYear:fieldTypeName:"}],"abstract":[]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/fieldTypeName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/maxYear","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/minYear"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/init(fieldTypeName:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/initWithMinYear:maxYear:fieldTypeName:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/toJson(configuration:)"]},{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration\/fromJsonWithJson:"]}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"SBSDKDocumentDataExtractorConfigurationElement","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfigurationElement"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration~1init(fieldTypeName:)\/title","op":"replace","value":"initWithFieldTypeName:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration~1init(fieldTypeName:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFieldTypeName:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration~1fieldTypeName\/title","op":"replace","value":"fieldTypeName"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration~1fieldTypeName\/fragments","op":"replace","value":[{"text":"fieldTypeName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration~1maxYear\/title","op":"replace","value":"maxYear"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration~1maxYear\/fragments","op":"replace","value":[{"kind":"identifier","text":"maxYear"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/title","op":"replace","value":"SBSDKDocumentDataExtractorConfigurationElement"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration~1toJson(configuration:)\/title","op":"replace","value":"toJsonWithConfiguration:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration~1toJson(configuration:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration~1minYear\/title","op":"replace","value":"minYear"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration~1minYear\/fragments","op":"replace","value":[{"text":"minYear","kind":"identifier"}]}]}]}