{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckDocumentModelAUSCheck"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"A check compatible with the Australian Paper Clearing System cheque standard","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelCheck"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/accountNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/auxDomestic","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/bsb","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/extraAuxDomestic","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/transactionCode"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelauscheck"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelauscheck"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentModelAUSCheck","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckDocumentModelAUSCheck","kind":"identifier"}],"title":"SBSDKCheckDocumentModelAUSCheck","roleHeading":"Class","navigatorTitle":[{"text":"SBSDKCheckDocumentModelAUSCheck","kind":"identifier"}],"symbolKind":"class"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelAUSCheck/transactionCode":{"type":"topic","title":"transactionCode","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"transactionCode"}],"abstract":[{"text":"Transaction code","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/transactionCode","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelauscheck\/transactioncode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelAUSCheck/accountNumber":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelauscheck\/accountnumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"accountNumber"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/accountNumber","title":"accountNumber","kind":"symbol","abstract":[{"type":"text","text":"Account number"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelAUSCheck/bsb":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelauscheck\/bsb","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/bsb","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bsb"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"title":"bsb","navigatorTitle":[{"kind":"identifier","text":"bsb"}],"role":"symbol","abstract":[{"type":"text","text":"BSB"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelAUSCheck/auxDomestic":{"kind":"symbol","title":"auxDomestic","abstract":[{"type":"text","text":"Auxiliary domestic"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/auxDomestic","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelauscheck\/auxdomestic","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"auxDomestic","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"auxDomestic","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelAUSCheck/initWithGenericDocument:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/initWithGenericDocument:","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelauscheck\/initwithgenericdocument:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"title":"initWithGenericDocument:","abstract":[],"kind":"symbol","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelAUSCheck/requiredDocumentType":{"title":"requiredDocumentType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/requiredDocumentType","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The name of the wrapped document type."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredDocumentType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"requiredDocumentType"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelauscheck\/requireddocumenttype"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelCheck":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelCheck","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelcheck","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckDocumentModelCheck","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCheckDocumentModelCheck","kind":"identifier"}],"kind":"symbol","title":"SBSDKCheckDocumentModelCheck","abstract":[{"text":"Check Document","type":"text"}]},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelAUSCheck":{"kind":"symbol","title":"SBSDKCheckDocumentModelAUSCheck","abstract":[{"type":"text","text":"A check compatible with the Australian Paper Clearing System cheque standard"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckDocumentModelAUSCheck"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelauscheck","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckDocumentModelAUSCheck"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelAUSCheck/extraAuxDomestic":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelauscheck\/extraauxdomestic","role":"symbol","type":"topic","abstract":[{"text":"Extra auxiliary domestic","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extraAuxDomestic","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"extraAuxDomestic","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/extraAuxDomestic","title":"extraAuxDomestic"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKCheckDocumentModelAUSCheck","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKCheckDocumentModelAUSCheck","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKCheckDocumentModelAUSCheck","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/accountNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/auxDomestic","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/bsb","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/extraAuxDomestic","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/transactionCode"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelAUSCheck\/initWithGenericDocument:"],"generated":true,"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelCheck"],"title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckDocumentModelAUSCheck","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentModelCheck","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelCheck","text":"SBSDKCheckDocumentModelCheck","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"transactionCode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelAUSCheck~1transactionCode\/title"},{"value":[{"kind":"identifier","text":"transactionCode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelAUSCheck~1transactionCode\/fragments"},{"value":"accountNumber","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelAUSCheck~1accountNumber\/title"},{"value":[{"text":"accountNumber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelAUSCheck~1accountNumber\/fragments"},{"value":"bsb","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelAUSCheck~1bsb\/title"},{"value":[{"kind":"identifier","text":"bsb"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelAUSCheck~1bsb\/fragments"},{"value":"auxDomestic","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelAUSCheck~1auxDomestic\/title"},{"value":[{"text":"auxDomestic","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelAUSCheck~1auxDomestic\/fragments"},{"value":"requiredDocumentType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelAUSCheck~1requiredDocumentType\/title"},{"value":[{"kind":"identifier","text":"requiredDocumentType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelAUSCheck~1requiredDocumentType\/fragments"},{"value":"SBSDKCheckDocumentModelCheck","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelCheck\/title"},{"value":[{"kind":"identifier","text":"SBSDKCheckDocumentModelCheck"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelCheck\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKCheckDocumentModelCheck"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelCheck\/navigatorTitle"},{"value":"SBSDKCheckDocumentModelAUSCheck","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelAUSCheck\/title"},{"value":[{"text":"SBSDKCheckDocumentModelAUSCheck","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelAUSCheck\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKCheckDocumentModelAUSCheck"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelAUSCheck\/navigatorTitle"},{"value":"extraAuxDomestic","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelAUSCheck~1extraAuxDomestic\/title"},{"value":[{"kind":"identifier","text":"extraAuxDomestic"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelAUSCheck~1extraAuxDomestic\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}