{"abstract":[{"text":"The delegate protocol for the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController","type":"reference"},{"text":".","type":"text"}],"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewControllerDelegate\/creditCardScannerViewController(_:didScanCreditCard:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewControllerDelegate\/creditCardScannerViewControllerShouldScanCreditCard(_:)"],"anchor":"Instance-Methods"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKCreditCardScannerViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKCreditCardScannerViewControllerDelegate"}],"role":"symbol","title":"SBSDKCreditCardScannerViewControllerDelegate","roleHeading":"Protocol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCreditCardScannerViewControllerDelegate"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCreditCardScannerViewControllerDelegate"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This is a beta feature that still may contain bugs or performance issues."}]}],"name":"Note"}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewControllerDelegate"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerViewControllerDelegate/creditCardScannerViewController(_:didScanCreditCard:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewControllerDelegate\/creditCardScannerViewController(_:didScanCreditCard:)","title":"creditCardScannerViewController(_:didScanCreditCard:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerViewController","text":"SBSDKCreditCardScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didScanCreditCard","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScanningResult","text":"SBSDKCreditCardScanningResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"creditCardScannerViewController:didScanCreditCard:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontrollerdelegate\/creditcardscannerviewcontroller(_:didscancreditcard:)","kind":"symbol","required":true,"abstract":[{"type":"text","text":"Informs the delegate that the scanner has scanned a credit card."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerViewControllerDelegate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKCreditCardScannerViewControllerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCreditCardScannerViewControllerDelegate"}],"kind":"symbol","title":"SBSDKCreditCardScannerViewControllerDelegate","abstract":[{"text":"The delegate protocol for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontrollerdelegate","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerViewController":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKCreditCardScannerViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontroller","title":"SBSDKCreditCardScannerViewController","type":"topic","abstract":[{"text":"Classic UI view controller that can be used to scan credit cards.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCreditCardScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerViewControllerDelegate/creditCardScannerViewControllerShouldScanCreditCard(_:)":{"kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"creditCardScannerViewControllerShouldScanCreditCard:"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewControllerDelegate\/creditCardScannerViewControllerShouldScanCreditCard(_:)","abstract":[{"text":"Asks the delegate if the scanner should scan credit cards on the next video frame.","type":"text"},{"text":" ","type":"text"},{"text":"Optional.","type":"text"}],"title":"creditCardScannerViewControllerShouldScanCreditCard(_:)","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontrollerdelegate\/creditcardscannerviewcontrollershouldscancreditcard(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"creditCardScannerViewControllerShouldScanCreditCard"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerViewController","kind":"typeIdentifier","text":"SBSDKCreditCardScannerViewController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKCreditCardScannerViewControllerDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKCreditCardScannerViewControllerDelegate"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCreditCardScannerViewControllerDelegate"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewControllerDelegate\/creditCardScannerViewController(_:didScanCreditCard:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewControllerDelegate\/creditCardScannerViewControllerShouldScanCreditCard(_:)"],"anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCreditCardScannerViewControllerDelegate"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"creditCardScannerViewController:didScanCreditCard:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewControllerDelegate~1creditCardScannerViewController(_:didScanCreditCard:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"creditCardScannerViewController:didScanCreditCard:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewControllerDelegate~1creditCardScannerViewController(_:didScanCreditCard:)\/fragments"},{"value":"SBSDKCreditCardScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewControllerDelegate\/title"},{"value":[{"text":"SBSDKCreditCardScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewControllerDelegate\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKCreditCardScannerViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewControllerDelegate\/navigatorTitle"},{"value":"SBSDKCreditCardScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController\/title"},{"value":[{"text":"SBSDKCreditCardScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController\/fragments"},{"value":[{"text":"SBSDKCreditCardScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewControllerDelegate~1creditCardScannerViewControllerShouldScanCreditCard(_:)\/title","op":"replace","value":"creditCardScannerViewControllerShouldScanCreditCard:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewControllerDelegate~1creditCardScannerViewControllerShouldScanCreditCard(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"creditCardScannerViewControllerShouldScanCreditCard:"}]}]}]}