{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"kind":"symbol","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the vehicle identification number scanner."}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewDelegate","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/s8SendableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring","doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller"]}],"metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKVINScannerViewController"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKVINScannerViewController","symbolKind":"class"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/init(configuration:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/init(parentViewController:parentView:configuration:delegate:)"],"generated":true},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/delegate"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/copyCurrentConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/setConfiguration(_:)"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVINScannerViewController"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"inlineContent":[{"type":"text","text":"A view finder like rectangle shows the area where vehicle identification numbers are detected."},{"type":"text","text":" "},{"type":"text","text":"The camera can be zoomed in and out using an action or a double-tap to make aiming at the desired area easier."},{"type":"text","text":" "},{"type":"text","text":"Once a vehicle identification number has been detected and validated within the view finder area,"},{"type":"text","text":" "},{"type":"text","text":"the result is delivered to the receivers delegate."}],"type":"paragraph"}]}],"references":{"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s8SendableP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderViewDelegate":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"abstract":[{"text":"The delegate protocol for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","type":"reference","isActive":true},{"text":" class.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewDelegate","title":"SBSDKFinderViewDelegate","url":"\/documentation\/scanbotsdk\/sbsdkfinderviewdelegate","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP"},"doc://net.doo.ScanbotSDK/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewController/initWithCoder:":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"title":"initWithCoder:","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller\/initwithcoder:","abstract":[],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/initWithCoder:","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSessionDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraSessionDelegate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKCameraSessionDelegate","kind":"identifier"}],"title":"SBSDKCameraSessionDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionDelegate","url":"\/documentation\/scanbotsdk\/sbsdkcamerasessiondelegate","kind":"symbol","abstract":[{"type":"text","text":"The  delegate protocol for "},{"type":"codeVoice","code":"SBSDKCameraSession"},{"type":"text","text":"."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewController":{"title":"SBSDKBaseScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller","abstract":[{"type":"text","text":"A highly customizable camera view controller that delivers a basic camera functionality along with video"},{"type":"text","text":" "},{"type":"text","text":"frame extraction and preprocessing, orientation correction and still image capturing."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"},"doc://net.doo.ScanbotSDK/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewController/setConfiguration(_:)":{"kind":"symbol","title":"setConfiguration(_:)","abstract":[{"text":"Sets the configuration of the receiver.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/setConfiguration(_:)","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller\/setconfiguration(_:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKVINScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setConfiguration:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSessionObserving":{"abstract":[{"text":"A multicast-observer protocol that informs its observers about state changes of a camera session.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSessionObserving"}],"role":"symbol","title":"SBSDKCameraSessionObserving","url":"\/documentation\/scanbotsdk\/sbsdkcamerasessionobserving","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSessionObserving"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewController":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","title":"SBSDKVINScannerViewController","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to show a camera screen with the vehicle identification number scanner.","type":"text"}],"navigatorTitle":[{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView":{"role":"symbol","kind":"symbol","title":"SBSDKFinderView","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIView"},{"text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderview","navigatorTitle":[{"kind":"identifier","text":"SBSDKFinderView"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFinderView"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewController/copyCurrentConfiguration()":{"abstract":[{"text":"Returns a copy of the receivers current configuration.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/copyCurrentConfiguration()","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller\/copycurrentconfiguration()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copyCurrentConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKVINScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerConfiguration"}],"title":"copyCurrentConfiguration()","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyCurrentConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewController/init(configuration:delegate:)":{"kind":"symbol","abstract":[{"text":"Creates a new instance of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","type":"reference","isActive":true},{"text":" with the given configuration and delegate.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/init(configuration:delegate:)","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller\/init(configuration:delegate:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKVINScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerConfiguration"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKVINScannerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKVINScannerViewControllerDelegate"},{"text":"?)","kind":"text"}],"role":"symbol","title":"init(configuration:delegate:)","navigatorTitle":[{"text":"initWithConfiguration:delegate:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewController/init(parentViewController:parentView:configuration:delegate:)":{"kind":"symbol","abstract":[{"text":"Creates a new instance of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","type":"reference","isActive":true},{"text":" and installs it as child view controller into the specified view using its entire bounds area.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/init(parentViewController:parentView:configuration:delegate:)","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller\/init(parentviewcontroller:parentview:configuration:delegate:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"parentViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"text":"parentView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKVINScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerConfiguration"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKVINScannerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKVINScannerViewControllerDelegate"},{"text":"?)","kind":"text"}],"role":"symbol","title":"init(parentViewController:parentView:configuration:delegate:)","navigatorTitle":[{"text":"initWithParentViewController:parentView:configuration:delegate:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding"},"doc://net.doo.ScanbotSDK/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer"},"doc://net.doo.ScanbotSDK/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment"},"doc://net.doo.ScanbotSDK/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewController/delegate":{"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller\/delegate","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKVINScannerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKVINScannerViewControllerDelegate"},{"text":"?","kind":"text"}],"abstract":[{"text":"Weak. The receivers delegate object.","type":"text"}],"title":"delegate","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/delegate","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewController/init()":{"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller\/init()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/init()","type":"topic","abstract":[{"text":"Initializes an instance of this class with the default configuration.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()"},"doc://net.doo.ScanbotSDK/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://net.doo.ScanbotSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKVINScannerViewController","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKVINScannerViewController"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/delegate"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/copyCurrentConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/init(configuration:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/init(parentViewController:parentView:configuration:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/initWithCoder:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/setConfiguration(_:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINScannerViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"SBSDKBaseScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKFinderViewDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate\/fragments","op":"replace","value":[{"text":"SBSDKFinderViewDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKFinderViewDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionDelegate\/title","op":"replace","value":"SBSDKCameraSessionDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionDelegate\/fragments","op":"replace","value":[{"text":"SBSDKCameraSessionDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionDelegate\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCameraSessionDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/title","op":"replace","value":"SBSDKBaseScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController~1setConfiguration(_:)\/title","op":"replace","value":"setConfiguration:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController~1setConfiguration(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setConfiguration:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving\/title","op":"replace","value":"SBSDKCameraSessionObserving"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraSessionObserving"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraSessionObserving"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/title","op":"replace","value":"SBSDKVINScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVINScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKVINScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/title","op":"replace","value":"SBSDKFinderView"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKFinderView"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKFinderView"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController~1copyCurrentConfiguration()\/title","op":"replace","value":"copyCurrentConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController~1copyCurrentConfiguration()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"copyCurrentConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController~1init(configuration:delegate:)\/title","op":"replace","value":"initWithConfiguration:delegate:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController~1init(configuration:delegate:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:delegate:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController~1init(parentViewController:parentView:configuration:delegate:)\/title","op":"replace","value":"initWithParentViewController:parentView:configuration:delegate:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController~1init(parentViewController:parentView:configuration:delegate:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithParentViewController:parentView:configuration:delegate:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController~1delegate\/title","op":"replace","value":"delegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController~1delegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"delegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController~1init()\/title","op":"replace","value":"init"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController~1init()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}