{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"title":"Conforms To","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKMedicalCertificateCheckBoxType) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateCheckBoxType","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Enumeration","symbolKind":"enum","title":"SBSDKMedicalCertificateCheckBoxType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxType"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateCheckBoxType","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxType"}]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"text":"Type of the checkbox.","type":"text"}],"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/accidentNo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/accidentYes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/assignedToAccidentInsuranceDoctor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/entitlementToContinuedPaymentNo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/entitlementToContinuedPaymentYes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/finalCertificate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/initialCertificate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/insuredPayCase","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/otherAccident","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/renewedCertificate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/requiresCareNo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/requiresCareYes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/sickPayWasClaimedNo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/sickPayWasClaimedYes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/singleParentNo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/singleParentYes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/unknown","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/workAccident"],"generated":true,"title":"Enumeration Cases"},{"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/init(rawValue:)"],"generated":true,"title":"Initializers"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"references":{"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","kind":"article","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/RawRepresentable-Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/requiresCareNo":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/requirescareno","title":"SBSDKMedicalCertificateCheckBoxType.requiresCareNo","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresCareNo"}],"abstract":[{"type":"text","text":"(Form 21a) Requires care no (Die Art der Erkrankung macht die Betreuung und Beaufsichtigung notwendig… nein)"},{"type":"text","text":" "},{"type":"text","text":"checkbox."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/requiresCareNo","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeRequiresCareNo"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/unknown":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/unknown","title":"SBSDKMedicalCertificateCheckBoxType.unknown","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"Unknown checkbox type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/unknown","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeUnknown"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/accidentYes":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/accidentyes","type":"topic","title":"SBSDKMedicalCertificateCheckBoxType.accidentYes","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeAccidentYes"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/accidentYes","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"accidentYes"}],"kind":"symbol","role":"symbol","abstract":[{"text":"(Form 21a) Accident yes (Unfall… ja) checkbox.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/finalCertificate":{"abstract":[{"type":"text","text":"(Form 1) Final certificate (Endbescheinigung) checkbox."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeFinalCertificate"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/finalCertificate","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/finalcertificate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalCertificate"}],"title":"SBSDKMedicalCertificateCheckBoxType.finalCertificate","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/Equatable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/equatable-implementations","title":"Equatable Implementations","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/Equatable-Implementations","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/accidentNo":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/accidentNo","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/accidentno","abstract":[{"type":"text","text":"(Form 21a) Accident no (Unfall… nein) checkbox."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"accidentNo"}],"title":"SBSDKMedicalCertificateCheckBoxType.accidentNo","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeAccidentNo"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/requiresCareYes":{"title":"SBSDKMedicalCertificateCheckBoxType.requiresCareYes","abstract":[{"type":"text","text":"(Form 21a) Requires care yes (Die Art der Erkrankung macht die Betreuung und Beaufsichtigung notwendig… ja)"},{"type":"text","text":" "},{"type":"text","text":"checkbox."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeRequiresCareYes"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/requirescareyes","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/requiresCareYes","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresCareYes"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/workAccident":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/workaccident","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"workAccident"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeWorkAccident"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/workAccident","title":"SBSDKMedicalCertificateCheckBoxType.workAccident","abstract":[{"text":"(Form 1) Work accident (Arbeitsunfall, Arbeitsunfall-folgen, Berufskrankheit) checkbox.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/singleParentYes":{"title":"SBSDKMedicalCertificateCheckBoxType.singleParentYes","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/singleParentYes","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"singleParentYes","kind":"identifier"}],"abstract":[{"text":"(Form 21a) Single parent yes (Ich bin Alleinerziehende(r)… ja) checkbox.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/singleparentyes","navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBoxTypeSingleParentYes","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/otherAccident":{"title":"SBSDKMedicalCertificateCheckBoxType.otherAccident","navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBoxTypeOtherAccident","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/otherAccident","kind":"symbol","abstract":[{"type":"text","text":"(Form 1) Other accident (Sonstiger Unfall, Unfallfolgen) checkbox."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/otheraccident","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"otherAccident","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/entitlementToContinuedPaymentNo":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/entitlementtocontinuedpaymentno","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/entitlementToContinuedPaymentNo","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entitlementToContinuedPaymentNo","kind":"identifier"}],"abstract":[{"type":"text","text":"(Form 21a) Entitlement to continued payment no (keinen Anspruch auf Entgeltfortzahlung) checkbox."}],"type":"topic","kind":"symbol","title":"SBSDKMedicalCertificateCheckBoxType.entitlementToContinuedPaymentNo","navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentNo","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/entitlementToContinuedPaymentYes":{"title":"SBSDKMedicalCertificateCheckBoxType.entitlementToContinuedPaymentYes","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/entitlementtocontinuedpaymentyes","kind":"symbol","abstract":[{"type":"text","text":"(Form 21a) Entitlement to continued payment yes (Anspruch auf Entgeltfortzahlung) checkbox."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entitlementToContinuedPaymentYes","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentYes","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/entitlementToContinuedPaymentYes"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/renewedCertificate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/renewedCertificate","kind":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBoxTypeRenewedCertificate","kind":"identifier"}],"type":"topic","title":"SBSDKMedicalCertificateCheckBoxType.renewedCertificate","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renewedCertificate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/renewedcertificate","abstract":[{"text":"(Form 1) Renewed certificate (Folgebescheinigung) checkbox.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/assignedToAccidentInsuranceDoctor":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/assignedToAccidentInsuranceDoctor","navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBoxTypeAssignedToAccidentInsuranceDoctor","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"assignedToAccidentInsuranceDoctor","kind":"identifier"}],"abstract":[{"text":"(Form 1) Assigned to accident insurance doctor (dem Durchgangsarzt zugewiesen) checkbox.","type":"text"}],"title":"SBSDKMedicalCertificateCheckBoxType.assignedToAccidentInsuranceDoctor","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/assignedtoaccidentinsurancedoctor","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/initialCertificate":{"abstract":[{"text":"(Form 1) Initial certificate (Erstbescheinigung) checkbox.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialCertificate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/initialcertificate","navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBoxTypeInitialCertificate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/initialCertificate","kind":"symbol","type":"topic","title":"SBSDKMedicalCertificateCheckBoxType.initialCertificate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/init(rawValue:)":{"title":"init(rawValue:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"role":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/init(rawvalue:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/init(rawValue:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/singleParentNo":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeSingleParentNo"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/singleparentno","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"singleParentNo"}],"abstract":[{"type":"text","text":"(Form 21a) Single parent no (Ich bin Alleinerziehende(r)… nein) checkbox."}],"title":"SBSDKMedicalCertificateCheckBoxType.singleParentNo","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/singleParentNo","role":"symbol"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/sickPayWasClaimedNo":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/sickPayWasClaimedNo","navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBoxTypeSickPayWasClaimedNo","kind":"identifier"}],"title":"SBSDKMedicalCertificateCheckBoxType.sickPayWasClaimedNo","type":"topic","abstract":[{"text":"(Form 21a) Sick pay was claimed no (Krankengeld aus Anlass einer früheren Erkrankung des umseitig genannten","type":"text"},{"text":" ","type":"text"},{"text":"Kindes wurde in diesem Kalenderjahr NICHT bezogen) checkbox.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/sickpaywasclaimedno","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sickPayWasClaimedNo","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType","title":"SBSDKMedicalCertificateCheckBoxType","abstract":[{"type":"text","text":"Type of the checkbox."}],"type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateCheckBoxType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBoxType","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/insuredPayCase":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/insuredPayCase","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeInsuredPayCase"}],"title":"SBSDKMedicalCertificateCheckBoxType.insuredPayCase","type":"topic","abstract":[{"type":"text","text":"(Form 1) Insured pay case (ab 7. AU-Woche oder sonstiger Krankengeldfall) checkbox."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/insuredpaycase","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"insuredPayCase"}]},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/sickPayWasClaimedYes":{"title":"SBSDKMedicalCertificateCheckBoxType.sickPayWasClaimedYes","kind":"symbol","abstract":[{"type":"text","text":"(Form 21a) Sick pay was claimed yes (Krankengeld aus Anlass einer früheren Erkrankung des umseitig genannten"},{"type":"text","text":" "},{"type":"text","text":"Kindes wurde in diesem Kalenderjahr bezogen) checkbox."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/sickPayWasClaimedYes","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeSickPayWasClaimedYes"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/sickpaywasclaimedyes","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sickPayWasClaimedYes"}]},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKMedicalCertificateCheckBoxType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxType"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKMedicalCertificateCheckBoxType","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/accidentNo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/accidentYes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/assignedToAccidentInsuranceDoctor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/entitlementToContinuedPaymentNo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/entitlementToContinuedPaymentYes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/finalCertificate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/initialCertificate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/insuredPayCase","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/otherAccident","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/renewedCertificate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/requiresCareNo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/requiresCareYes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/sickPayWasClaimedNo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/sickPayWasClaimedYes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/singleParentNo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/singleParentYes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/unknown","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/workAccident"]}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateCheckBoxType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1requiresCareNo\/title","op":"replace","value":"SBSDKMedicalCertificateCheckBoxTypeRequiresCareNo"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1requiresCareNo\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeRequiresCareNo"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1unknown\/title","op":"replace","value":"SBSDKMedicalCertificateCheckBoxTypeUnknown"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1unknown\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeUnknown"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1accidentYes\/title","op":"replace","value":"SBSDKMedicalCertificateCheckBoxTypeAccidentYes"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1accidentYes\/fragments","op":"replace","value":[{"text":"SBSDKMedicalCertificateCheckBoxTypeAccidentYes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1finalCertificate\/title","op":"replace","value":"SBSDKMedicalCertificateCheckBoxTypeFinalCertificate"},{"value":[{"text":"SBSDKMedicalCertificateCheckBoxTypeFinalCertificate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1finalCertificate\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateCheckBoxTypeAccidentNo","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1accidentNo\/title","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateCheckBoxTypeAccidentNo","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1accidentNo\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateCheckBoxTypeRequiresCareYes","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1requiresCareYes\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeRequiresCareYes"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1requiresCareYes\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateCheckBoxTypeWorkAccident","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1workAccident\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeWorkAccident"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1workAccident\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateCheckBoxTypeSingleParentYes","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1singleParentYes\/title","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateCheckBoxTypeSingleParentYes","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1singleParentYes\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateCheckBoxTypeOtherAccident","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1otherAccident\/title","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateCheckBoxTypeOtherAccident","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1otherAccident\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentNo","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1entitlementToContinuedPaymentNo\/title","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentNo","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1entitlementToContinuedPaymentNo\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentYes","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1entitlementToContinuedPaymentYes\/title","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentYes","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1entitlementToContinuedPaymentYes\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateCheckBoxTypeRenewedCertificate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1renewedCertificate\/title","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateCheckBoxTypeRenewedCertificate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1renewedCertificate\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateCheckBoxTypeAssignedToAccidentInsuranceDoctor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1assignedToAccidentInsuranceDoctor\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeAssignedToAccidentInsuranceDoctor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1assignedToAccidentInsuranceDoctor\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateCheckBoxTypeInitialCertificate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1initialCertificate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeInitialCertificate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1initialCertificate\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateCheckBoxTypeSingleParentNo","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1singleParentNo\/title","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateCheckBoxTypeSingleParentNo","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1singleParentNo\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateCheckBoxTypeSickPayWasClaimedNo","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1sickPayWasClaimedNo\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeSickPayWasClaimedNo"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1sickPayWasClaimedNo\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateCheckBoxType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType\/title","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateCheckBoxType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType\/navigatorTitle","op":"replace"},{"value":"SBSDKMedicalCertificateCheckBoxTypeInsuredPayCase","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1insuredPayCase\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeInsuredPayCase"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1insuredPayCase\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateCheckBoxTypeSickPayWasClaimedYes","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1sickPayWasClaimedYes\/title","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateCheckBoxTypeSickPayWasClaimedYes","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1sickPayWasClaimedYes\/fragments","op":"replace"}]}]}