{"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"type":"conformsTo","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus"]}],"abstract":[{"type":"text","text":"Status of the document detection."}],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Enumeration","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"symbolKind":"enum","externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectionStatus","title":"SBSDKDocumentDetectionStatus","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/errorNothingDetected","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/errorTooDark","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/errorTooNoisy","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/notAcquired","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/ok","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButBadAngles","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButBadAspectRatio","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButOffCenter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButOrientationMismatch","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButTooDark","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButTooSmall"],"anchor":"Enumeration-Cases","generated":true},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/isOK"],"anchor":"Instance-Properties","generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKDocumentDetectionStatus) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/isOK":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/isok","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/isOK","title":"isOK","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOK"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus","abstract":[{"type":"text","text":"Status of the document detection."}],"title":"SBSDKDocumentDetectionStatus","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/Equatable-Implementations","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/equatable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/notAcquired":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notAcquired"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/notAcquired","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusNotAcquired"}],"abstract":[{"type":"text","text":"Detection has not yet happened."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/notacquired","title":"SBSDKDocumentDetectionStatus.notAcquired"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/okButTooDark":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOkButTooDark"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"okButTooDark"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/okbuttoodark","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButTooDark","role":"symbol","title":"SBSDKDocumentDetectionStatus.okButTooDark","abstract":[{"text":"A document was detected, but it is too dark.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/errorTooNoisy":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/errorTooNoisy","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/errortoonoisy","abstract":[{"type":"text","text":"No document was detected, likely because the input image is too noisy or has a complex background."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusErrorTooNoisy"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorTooNoisy"}],"kind":"symbol","title":"SBSDKDocumentDetectionStatus.errorTooNoisy"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/okButTooSmall":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"okButTooSmall","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButTooSmall","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatusOkButTooSmall","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A document was detected, but it is too small."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/okbuttoosmall","title":"SBSDKDocumentDetectionStatus.okButTooSmall"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/RawRepresentable-Implementations":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/RawRepresentable-Implementations","role":"collectionGroup","abstract":[],"title":"RawRepresentable Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/init(rawValue:)":{"abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/init(rawvalue:)","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/init(rawValue:)","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/okButBadAspectRatio":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A document was detected, but its aspect ratio is not acceptable."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/okbutbadaspectratio","title":"SBSDKDocumentDetectionStatus.okButBadAspectRatio","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatusOkButBadAspectRatio","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"okButBadAspectRatio","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButBadAspectRatio"},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/okButOrientationMismatch":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"okButOrientationMismatch","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A document was detected, but its orientation does not match the input image orientation.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButOrientationMismatch","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatusOkButOrientationMismatch","kind":"identifier"}],"title":"SBSDKDocumentDetectionStatus.okButOrientationMismatch","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/okbutorientationmismatch"},"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/ok":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/ok","kind":"symbol","title":"SBSDKDocumentDetectionStatus.ok","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/ok","abstract":[{"type":"text","text":"An acceptable document was detected."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ok"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/okButOffCenter":{"abstract":[{"type":"text","text":"A document was detected, but its center is too far away from the input image center."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/okbutoffcenter","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOkButOffCenter"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"okButOffCenter"}],"title":"SBSDKDocumentDetectionStatus.okButOffCenter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButOffCenter","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/errorNothingDetected":{"role":"symbol","title":"SBSDKDocumentDetectionStatus.errorNothingDetected","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/errornothingdetected","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNothingDetected"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/errorNothingDetected","abstract":[{"type":"text","text":"No document was detected."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusErrorNothingDetected"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/okButBadAngles":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButBadAngles","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"okButBadAngles"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOkButBadAngles"}],"abstract":[{"text":"A document was detected, but it has too much perspective distortion.","type":"text"}],"title":"SBSDKDocumentDetectionStatus.okButBadAngles","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/okbutbadangles","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus/errorTooDark":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorTooDark","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentDetectionStatusErrorTooDark","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus\/errortoodark","role":"symbol","abstract":[{"type":"text","text":"No document was detected, likely because the input image is too dark."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/errorTooDark","title":"SBSDKDocumentDetectionStatus.errorTooDark"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKDocumentDetectionStatus","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/errorNothingDetected","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/errorTooDark","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/errorTooNoisy","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/notAcquired","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/ok","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButBadAngles","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButBadAspectRatio","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButOffCenter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButOrientationMismatch","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButTooDark","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus\/okButTooSmall"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKDocumentDetectionStatus","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/navigatorTitle"},{"op":"replace","value":"SBSDKDocumentDetectionStatusNotAcquired","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1notAcquired\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusNotAcquired"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1notAcquired\/fragments"},{"op":"replace","value":"SBSDKDocumentDetectionStatusOkButTooDark","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButTooDark\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOkButTooDark"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButTooDark\/fragments"},{"op":"replace","value":"SBSDKDocumentDetectionStatusErrorTooNoisy","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1errorTooNoisy\/title"},{"op":"replace","value":[{"text":"SBSDKDocumentDetectionStatusErrorTooNoisy","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1errorTooNoisy\/fragments"},{"op":"replace","value":"SBSDKDocumentDetectionStatusOkButTooSmall","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButTooSmall\/title"},{"op":"replace","value":[{"text":"SBSDKDocumentDetectionStatusOkButTooSmall","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButTooSmall\/fragments"},{"op":"replace","value":"SBSDKDocumentDetectionStatusOkButBadAspectRatio","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButBadAspectRatio\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOkButBadAspectRatio"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButBadAspectRatio\/fragments"},{"op":"replace","value":"SBSDKDocumentDetectionStatusOkButOrientationMismatch","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButOrientationMismatch\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOkButOrientationMismatch"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButOrientationMismatch\/fragments"},{"op":"replace","value":"SBSDKDocumentDetectionStatusOk","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1ok\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1ok\/fragments"},{"op":"replace","value":"SBSDKDocumentDetectionStatusOkButOffCenter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButOffCenter\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOkButOffCenter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButOffCenter\/fragments"},{"op":"replace","value":"SBSDKDocumentDetectionStatusErrorNothingDetected","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1errorNothingDetected\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusErrorNothingDetected"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1errorNothingDetected\/fragments"},{"op":"replace","value":"SBSDKDocumentDetectionStatusOkButBadAngles","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButBadAngles\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOkButBadAngles"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1okButBadAngles\/fragments"},{"op":"replace","value":"SBSDKDocumentDetectionStatusErrorTooDark","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1errorTooDark\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusErrorTooDark"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus~1errorTooDark\/fragments"}]}]}