{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(initWithUIConfiguration:textConfiguration:behaviorConfiguration:) ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"uiConfiguration"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenUIConfiguration","text":"SBSDKUICroppingScreenUIConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenUIConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textConfiguration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration","text":"SBSDKUICroppingScreenTextConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"behaviorConfiguration"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenBehaviorConfiguration","text":"SBSDKUICroppingScreenBehaviorConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenBehaviorConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A configuration for the user interface. Defines colors and sizes."}],"type":"paragraph"}],"name":"uiConfiguration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A configuration for text being displayed in the page review screen."}]}],"name":"textConfiguration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A configuration for defining the behavior of the cropping screen."}]}],"name":"behaviorConfiguration"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenConfiguration"]]},"abstract":[{"text":"Designated initializer. Creates a new instance of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenConfiguration","isActive":true,"type":"reference"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"uiConfiguration"},{"text":": ","kind":"text"},{"text":"SBSDKUICroppingScreenUIConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenUIConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenTextConfiguration","text":"SBSDKUICroppingScreenTextConfiguration"},{"kind":"text","text":", "},{"text":"behaviorConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenBehaviorConfiguration","text":"SBSDKUICroppingScreenBehaviorConfiguration"},{"kind":"text","text":")"}],"role":"symbol","symbolKind":"init","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenConfiguration(im)initWithUIConfiguration:textConfiguration:behaviorConfiguration:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithUIConfiguration:textConfiguration:behaviorConfiguration:"}],"title":"init(uiConfiguration:textConfiguration:behaviorConfiguration:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:)"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenUIConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICroppingScreenUIConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenUIConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenuiconfiguration","type":"topic","title":"SBSDKUICroppingScreenUIConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingScreenUIConfiguration"}],"abstract":[{"text":"Configuration for user interface of the page cropping screen.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenTextConfiguration":{"title":"SBSDKUICroppingScreenTextConfiguration","abstract":[{"type":"text","text":"Configuration for the textual content of the page cropping screen."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICroppingScreenTextConfiguration"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreentextconfiguration","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingScreenTextConfiguration"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenBehaviorConfiguration":{"navigatorTitle":[{"text":"SBSDKUICroppingScreenBehaviorConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICroppingScreenBehaviorConfiguration"}],"title":"SBSDKUICroppingScreenBehaviorConfiguration","abstract":[{"type":"text","text":"Configuration for the behavior of the cropping screen."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenBehaviorConfiguration","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenbehaviorconfiguration","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenConfiguration/init(uiConfiguration:textConfiguration:behaviorConfiguration:)":{"type":"topic","abstract":[{"type":"text","text":"Designated initializer. Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenConfiguration","isActive":true},{"text":".","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:)","title":"init(uiConfiguration:textConfiguration:behaviorConfiguration:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:)","role":"symbol","navigatorTitle":[{"text":"initWithUIConfiguration:textConfiguration:behaviorConfiguration:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"uiConfiguration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenUIConfiguration","kind":"typeIdentifier","text":"SBSDKUICroppingScreenUIConfiguration"},{"text":", ","kind":"text"},{"text":"textConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUICroppingScreenTextConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenTextConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"behaviorConfiguration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenBehaviorConfiguration","text":"SBSDKUICroppingScreenBehaviorConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 5.0.0"}],"title":"ScanbotDocumentScannerSDK","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenConfiguration":{"navigatorTitle":[{"text":"SBSDKUICroppingScreenConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUICroppingScreenConfiguration","kind":"identifier"}],"title":"SBSDKUICroppingScreenConfiguration","abstract":[{"type":"text","text":"This class describes the look and feel, as well as the textual contents of the page cropping screen."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenConfiguration","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenconfiguration","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithUIConfiguration:textConfiguration:behaviorConfiguration:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"initWithUIConfiguration:textConfiguration:behaviorConfiguration:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithUIConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUICroppingScreenUIConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenUIConfiguration"},{"kind":"text","text":" *) "},{"text":"uiConfiguration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"textConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenTextConfiguration","text":"SBSDKUICroppingScreenTextConfiguration"},{"kind":"text","text":" *) "},{"text":"textConfiguration","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"behaviorConfiguration:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenBehaviorConfiguration","kind":"typeIdentifier","text":"SBSDKUICroppingScreenBehaviorConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenBehaviorConfiguration"},{"kind":"text","text":" *) "},{"text":"behaviorConfiguration","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SBSDKUICroppingScreenUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenUIConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenUIConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUICroppingScreenUIConfiguration"}],"op":"replace"},{"op":"replace","value":"SBSDKUICroppingScreenTextConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUICroppingScreenTextConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenBehaviorConfiguration\/title","value":"SBSDKUICroppingScreenBehaviorConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenBehaviorConfiguration\/fragments","value":[{"text":"SBSDKUICroppingScreenBehaviorConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:)\/title","value":"initWithUIConfiguration:textConfiguration:behaviorConfiguration:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithUIConfiguration:textConfiguration:behaviorConfiguration:"}],"op":"replace"},{"value":"SBSDKUICroppingScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKUICroppingScreenConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenConfiguration\/fragments"}]}]}