{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration\/init(cameramodule:defaultzoomfactor:autocroponmanualsnap:flashenabled:minfocusdistancelock:pinchtozoomenabled:camerapreviewmode:capturequalityprioritization:acceptedanglescore:acceptedsizescore:autosnappingsensitivity:autosnappingdelay:acce-5nwl7"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration\/init(cameramodule:defaultzoomfactor:autocroponmanualsnap:flashenabled:minfocusdistancelock:pinchtozoomenabled:camerapreviewmode:capturequalityprioritization:acceptedanglescore:acceptedsizescore:autosnappingsensitivity:autosnappingdelay:acce-5nwl7"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"cameraModule","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2CameraModule","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule"},{"kind":"text","text":" = SBSDKUI2CameraModule.back, "},{"text":"defaultZoomFactor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = 1.0, "},{"kind":"externalParam","text":"autoCropOnManualSnap"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"text":"flashEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"text":"minFocusDistanceLock","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"pinchToZoomEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"cameraPreviewMode"},{"kind":"text","text":": "},{"text":"SBSDKUI2CameraPreviewMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode"},{"kind":"text","text":" = SBSDKUI2CameraPreviewMode.fillIn, "},{"kind":"externalParam","text":"captureQualityPrioritization"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CapturePhotoQualityPrioritization","text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2CapturePhotoQualityPrioritization.balanced, "},{"text":"acceptedAngleScore","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = 0.75, "},{"text":"acceptedSizeScore","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":" = 0.75, "},{"text":"autoSnappingSensitivity","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = 0.66, "},{"text":"autoSnappingDelay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" = 200, ","kind":"text"},{"kind":"externalParam","text":"acceptedBrightnessThreshold"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" = 50, ","kind":"text"},{"text":"autoSnappingEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = true, "},{"text":"requiredAspectRatios","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AspectRatio","text":"SBSDKUI2AspectRatio","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AspectRatio"},{"text":"] = [], ","kind":"text"},{"kind":"externalParam","text":"ignoreBadAspectRatio"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = true, ","kind":"text"},{"kind":"externalParam","text":"captureWithHardwareButtonsEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = true)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration\/init(cameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cameraModule"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2CameraModule","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"defaultZoomFactor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":", ","kind":"text"},{"text":"autoCropOnManualSnap","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"flashEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"minFocusDistanceLock","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"pinchToZoomEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraPreviewMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode"},{"text":", ","kind":"text"},{"text":"captureQualityPrioritization","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CapturePhotoQualityPrioritization","kind":"typeIdentifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"},{"text":", ","kind":"text"},{"text":"acceptedAngleScore","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"acceptedSizeScore"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"autoSnappingSensitivity","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"text":"autoSnappingDelay","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"acceptedBrightnessThreshold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"autoSnappingEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"requiredAspectRatios","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2AspectRatio","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AspectRatio"},{"text":"], ","kind":"text"},{"text":"ignoreBadAspectRatio","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"captureWithHardwareButtonsEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"role":"symbol","title":"init(cameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)","navigatorTitle":[{"kind":"identifier","text":"initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerCameraConfiguration(im)initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:","roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"symbolKind":"init"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerCameraConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration","title":"SBSDKUI2DocumentScannerCameraConfiguration","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the camera behavior."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AspectRatio":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2AspectRatio","kind":"identifier"}],"abstract":[{"text":"Configuration of the finder’s aspect ratio.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2AspectRatio","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aspectratio","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AspectRatio","title":"SBSDKUI2AspectRatio","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraModule":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule","role":"symbol","abstract":[{"text":"Determines which camera module to use on start-up.","type":"text"}],"kind":"symbol","type":"topic","title":"SBSDKUI2CameraModule","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2cameramodule"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerCameraConfiguration/init(cameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration\/init(cameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)","kind":"symbol","navigatorTitle":[{"text":"initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"cameraModule","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule","text":"SBSDKUI2CameraModule"},{"kind":"text","text":", "},{"kind":"externalParam","text":"defaultZoomFactor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"autoCropOnManualSnap","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"flashEnabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"minFocusDistanceLock","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pinchToZoomEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"cameraPreviewMode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode","text":"SBSDKUI2CameraPreviewMode"},{"text":", ","kind":"text"},{"text":"captureQualityPrioritization","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CapturePhotoQualityPrioritization","kind":"typeIdentifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"acceptedAngleScore"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"text":"acceptedSizeScore","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"autoSnappingSensitivity","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"autoSnappingDelay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"acceptedBrightnessThreshold","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"autoSnappingEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"requiredAspectRatios"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AspectRatio","text":"SBSDKUI2AspectRatio","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"ignoreBadAspectRatio"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"captureWithHardwareButtonsEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration\/init(cameramodule:defaultzoomfactor:autocroponmanualsnap:flashenabled:minfocusdistancelock:pinchtozoomenabled:camerapreviewmode:capturequalityprioritization:acceptedanglescore:acceptedsizescore:autosnappingsensitivity:autosnappingdelay:acce-5nwl7","title":"init(cameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)","type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPreviewMode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerapreviewmode","kind":"symbol","title":"SBSDKUI2CameraPreviewMode","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the camera preview mode."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization","title":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}],"abstract":[{"type":"text","text":"Determines the prioritization of still image quality and capturing speed."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCameraModule:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule","text":"SBSDKUI2CameraModule","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraModule"},{"kind":"text","text":" "},{"text":"defaultZoomFactor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"defaultZoomFactor"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoCropOnManualSnap:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"autoCropOnManualSnap"},{"text":" ","kind":"text"},{"text":"flashEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"flashEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"minFocusDistanceLock:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minFocusDistanceLock","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pinchToZoomEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"text":"pinchToZoomEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewMode:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode","text":"SBSDKUI2CameraPreviewMode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraPreviewMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureQualityPrioritization:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CapturePhotoQualityPrioritization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization"},{"kind":"text","text":") "},{"text":"captureQualityPrioritization","kind":"internalParam"},{"kind":"text","text":" "},{"text":"acceptedAngleScore:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"acceptedAngleScore"},{"text":" ","kind":"text"},{"text":"acceptedSizeScore:","kind":"identifier"},{"kind":"text","text":"("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"text":"acceptedSizeScore","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSnappingSensitivity:"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"autoSnappingSensitivity","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoSnappingDelay:"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"autoSnappingDelay","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedBrightnessThreshold:"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"acceptedBrightnessThreshold","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoSnappingEnabled:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"autoSnappingEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"requiredAspectRatios:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKUI2AspectRatio *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"requiredAspectRatios","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignoreBadAspectRatio:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"ignoreBadAspectRatio","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"captureWithHardwareButtonsEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"captureWithHardwareButtonsEnabled","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/title","value":"SBSDKUI2DocumentScannerCameraConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/fragments","value":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerCameraConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AspectRatio\/title","value":"SBSDKUI2AspectRatio"},{"value":[{"kind":"identifier","text":"SBSDKUI2AspectRatio"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AspectRatio\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2AspectRatio"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AspectRatio\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/title","value":"SBSDKUI2CameraModule","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/fragments","value":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/navigatorTitle"},{"op":"replace","value":"initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration~1init(cameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration~1init(cameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPreviewMode\/title","value":"SBSDKUI2CameraPreviewMode","op":"replace"},{"value":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPreviewMode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPreviewMode\/navigatorTitle","value":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/title","value":"SBSDKUI2CapturePhotoQualityPrioritization"},{"value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/navigatorTitle","value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}]}]}]}