{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","symbolKind":"case","role":"symbol","title":"SBSDKProcessingMode.auto","externalID":"c:@M@ScanbotSDK@E@SBSDKProcessingMode@SBSDKProcessingModeAuto","navigatorTitle":[{"text":"SBSDKProcessingModeAuto","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"auto","kind":"identifier"}]},"abstract":[{"text":"The scanner chooses live or single-shot mode based on the source of the image. An image constructed with RawImageLoadOptions.liveSource equal to true will be processed in live mode, otherwise it will be processed in single-shot mode.","type":"text"},{"text":" ","type":"text"},{"text":"On Android liveSource is automatically set to true if the ImageRef is created from Nv21 image data.","type":"text"},{"text":" ","type":"text"},{"text":"On iOS liveSource is automatically set to true if the ImageRef is created from a CMSampleBuffer.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode\/auto","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkprocessingmode\/auto"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkprocessingmode\/auto"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"auto"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessingMode":{"kind":"symbol","abstract":[{"type":"text","text":"Scanners typically can produce better results from a single image if they are allowed to spend a longer time analyzing it."},{"type":"text","text":" "},{"type":"text","text":"On the other hand, scanners can produce even better results if they can analyze multiple images of the same subject and cross-check and combine the results."},{"type":"text","text":" "},{"type":"text","text":"The processing mode tells the scanner whether to optimize for single or multiple images of a subject."}],"title":"SBSDKProcessingMode","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessingMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkprocessingmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProcessingMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessingMode/auto":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode\/auto","navigatorTitle":[{"text":"SBSDKProcessingModeAuto","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkprocessingmode\/auto","kind":"symbol","role":"symbol","title":"SBSDKProcessingMode.auto","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"auto","kind":"identifier"}],"type":"topic","abstract":[{"text":"The scanner chooses live or single-shot mode based on the source of the image. An image constructed with RawImageLoadOptions.liveSource equal to true will be processed in live mode, otherwise it will be processed in single-shot mode.","type":"text"},{"text":" ","type":"text"},{"text":"On Android liveSource is automatically set to true if the ImageRef is created from Nv21 image data.","type":"text"},{"text":" ","type":"text"},{"text":"On iOS liveSource is automatically set to true if the ImageRef is created from a CMSampleBuffer.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKProcessingModeAuto"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKProcessingModeAuto"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKProcessingModeAuto","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/title","value":"SBSDKProcessingMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/fragments","value":[{"kind":"identifier","text":"SBSDKProcessingMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/navigatorTitle","value":[{"text":"SBSDKProcessingMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode~1auto\/title","value":"SBSDKProcessingModeAuto"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode~1auto\/fragments","value":[{"kind":"identifier","text":"SBSDKProcessingModeAuto"}]}]}]}