{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"Equatable Implementations","modules":[{"name":"ScanbotSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagebinarization\/equatable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/Equatable-Implementations"},"kind":"article","topicSections":[{"title":"Operators","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/!=(_:_:)"],"generated":true,"anchor":"Operators"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageBinarization":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpagebinarization","abstract":[{"text":"Binarization behavior to apply when adding a page to a PDF\/TIFF.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPageBinarization"}],"title":"SBSDKPageBinarization","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageBinarization"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageBinarization/!=(_:_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkpagebinarization\/!=(_:_:)","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageBinarization\/!=(_:_:)","role":"symbol","title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization\/title","value":"SBSDKPageBinarization","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization\/fragments","value":[{"kind":"identifier","text":"SBSDKPageBinarization"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageBinarization\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPageBinarization"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}