{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(sizeWhenApplyingToImageOfSize:imageScale:focalLength:sensorWidth:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeWhenApplying"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"imageOfSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"focalLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sensorWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"imageOfSize","content":[{"type":"paragraph","inlineContent":[{"text":"The size of the original image the receiver should be applied to.","type":"text"}]}]},{"name":"imageScale","content":[{"inlineContent":[{"type":"text","text":"The scaling factor of the image."}],"type":"paragraph"}]},{"name":"focalLength","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The focal length of the lens the image was taken with in millimetres."}]}]},{"name":"sensorWidth","content":[{"inlineContent":[{"text":"The width of the sensor the image was taken with in millimetres.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The estimated size of the cropped and perspective-corrected image, when the receiver was applied.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpolygon\/sizewhenapplying(to:imagescale:focallength:sensorwidth:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpolygon\/sizewhenapplying(to:imagescale:focallength:sensorwidth:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon(im)sizeWhenApplyingToImageOfSize:imageScale:focalLength:sensorWidth:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"sizeWhenApplyingToImageOfSize:imageScale:focalLength:sensorWidth:"}],"title":"sizeWhenApplying(to:imageScale:focalLength:sensorWidth:)","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeWhenApplying"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageScale"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"focalLength"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sensorWidth"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}],"roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Calculates the estimated size of the perspective-corrected and cropped image when applying the receiver to an image with given size."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/sizeWhenApplying(to:imageScale:focalLength:sensorWidth:)"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/sizeWhenApplying(to:imageScale:focalLength:sensorWidth:)":{"role":"symbol","title":"sizeWhenApplying(to:imageScale:focalLength:sensorWidth:)","type":"topic","navigatorTitle":[{"text":"sizeWhenApplyingToImageOfSize:imageScale:focalLength:sensorWidth:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/sizeWhenApplying(to:imageScale:focalLength:sensorWidth:)","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/sizewhenapplying(to:imagescale:focallength:sensorwidth:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeWhenApplying","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"imageScale","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"focalLength","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sensorWidth","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"abstract":[{"text":"Calculates the estimated size of the perspective-corrected and cropped image when applying the receiver to an image with given size.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"url":"\/documentation\/scanbotsdk\/sbsdkpolygon","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","kind":"symbol","type":"topic","role":"symbol","title":"SBSDKPolygon","abstract":[{"text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPolygon"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"sizeWhenApplyingToImageOfSize:imageScale:focalLength:sensorWidth:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sizeWhenApplyingToImageOfSize:imageScale:focalLength:sensorWidth:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"kind":"identifier","text":"sizeWhenApplyingToImageOfSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"imageOfSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageScale:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"imageScale"},{"kind":"text","text":" "},{"kind":"identifier","text":"focalLength:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"focalLength"},{"kind":"text","text":" "},{"kind":"identifier","text":"sensorWidth:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sensorWidth"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The size of the original image the receiver should be applied to.","type":"text"}]}],"name":"imageOfSize"},{"content":[{"inlineContent":[{"type":"text","text":"The scaling factor of the image."}],"type":"paragraph"}],"name":"imageScale"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The focal length of the lens the image was taken with in millimetres."}]}],"name":"focalLength"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The width of the sensor the image was taken with in millimetres.","type":"text"}]}],"name":"sensorWidth"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"The estimated size of the cropped and perspective-corrected image, when the receiver was applied."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"value":"sizeWhenApplyingToImageOfSize:imageScale:focalLength:sensorWidth:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1sizeWhenApplying(to:imageScale:focalLength:sensorWidth:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"sizeWhenApplyingToImageOfSize:imageScale:focalLength:sensorWidth:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1sizeWhenApplying(to:imageScale:focalLength:sensorWidth:)\/fragments"},{"value":"SBSDKPolygon","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title"},{"value":[{"text":"SBSDKPolygon","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments"},{"value":[{"text":"SBSDKPolygon","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}