{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound\/init(successBeepEnabled:soundType:)"},"sections":[],"kind":"symbol","metadata":{"title":"init(successBeepEnabled:soundType:)","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"successBeepEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"soundType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2SoundType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2SoundType"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSuccessBeepEnabled:soundType:"}],"roleHeading":"Initializer","symbolKind":"init","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sound(im)initWithSuccessBeepEnabled:soundType:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"successBeepEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = true, "},{"text":"soundType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2SoundType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SoundType","kind":"typeIdentifier","text":"SBSDKUI2SoundType"},{"text":" = SBSDKUI2SoundType.modernBeep)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2sound\/init(successbeepenabled:soundtype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2sound\/init(successbeepenabled:soundtype:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sound/init(successBeepEnabled:soundType:)":{"title":"init(successBeepEnabled:soundType:)","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2sound\/init(successbeepenabled:soundtype:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"successBeepEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"soundType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2SoundType","text":"SBSDKUI2SoundType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSuccessBeepEnabled:soundType:"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound\/init(successBeepEnabled:soundType:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sound":{"abstract":[{"text":"Sound configuration.","type":"text"}],"type":"topic","kind":"symbol","title":"SBSDKUI2Sound","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Sound"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sound","navigatorTitle":[{"text":"SBSDKUI2Sound","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SoundType":{"title":"SBSDKUI2SoundType","navigatorTitle":[{"text":"SBSDKUI2SoundType","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2soundtype","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SoundType","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2SoundType"}],"abstract":[{"type":"text","text":"The sound selection type."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithSuccessBeepEnabled:soundType:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithSuccessBeepEnabled:soundType:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithSuccessBeepEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"successBeepEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"soundType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2SoundType","text":"SBSDKUI2SoundType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SoundType"},{"kind":"text","text":") "},{"text":"soundType","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound~1init(successBeepEnabled:soundType:)\/title","value":"initWithSuccessBeepEnabled:soundType:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithSuccessBeepEnabled:soundType:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound~1init(successBeepEnabled:soundType:)\/fragments"},{"op":"replace","value":"SBSDKUI2Sound","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2Sound"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/fragments"},{"value":[{"text":"SBSDKUI2Sound","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SoundType\/title","op":"replace","value":"SBSDKUI2SoundType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SoundType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2SoundType"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2SoundType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SoundType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}