{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredZoom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The actual zoom might be different from the preferred one to avoid clipping of finder area","type":"text"},{"text":" ","type":"text"},{"text":"and maintain its aspect ratio and height.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to 2.0."}]}]}],"sections":[],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"preferredZoom"}],"symbolKind":"property","title":"preferredZoom","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredZoom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextPatternScannerStep(py)preferredZoom","roleHeading":"Instance Property","platforms":[]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerstep\/preferredzoom"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerstep\/preferredzoom"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerStep\/preferredZoom"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"The cameras zoom level preferred for this step.","type":"text"}],"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2TextPatternScannerViewController instead.","type":"text"}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerStep"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerStep/preferredZoom":{"url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerstep\/preferredzoom","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredZoom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"type":"topic","abstract":[{"type":"text","text":"The cameras zoom level preferred for this step."}],"title":"preferredZoom","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerStep\/preferredZoom","kind":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"preferredZoom"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerStep":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUITextPatternScannerStep"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerStep","abstract":[{"type":"text","text":"Defines a single workflow step of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController","isActive":true,"type":"reference"},{"type":"text","text":" flow."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUITextPatternScannerStep"}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerstep","title":"SBSDKUITextPatternScannerStep","deprecated":true,"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerViewController":{"kind":"symbol","title":"SBSDKUITextPatternScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUITextPatternScannerViewController","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUITextPatternScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController","abstract":[{"text":"A highly customizable camera-based view controller to scan and validate a small rectangular text area in realtime.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"preferredZoom","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"preferredZoom","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"preferredZoom","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerStep~1preferredZoom\/title","value":"preferredZoom","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerStep~1preferredZoom\/fragments","value":[{"kind":"identifier","text":"preferredZoom"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerStep\/title","value":"SBSDKUITextPatternScannerStep","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerStep\/fragments","value":[{"kind":"identifier","text":"SBSDKUITextPatternScannerStep"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerStep\/navigatorTitle","value":[{"text":"SBSDKUITextPatternScannerStep","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController\/title","value":"SBSDKUITextPatternScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUITextPatternScannerViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController\/navigatorTitle","value":[{"text":"SBSDKUITextPatternScannerViewController","kind":"identifier"}],"op":"replace"}]}]}