{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentroottype\/wrap(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentroottype\/wrap(_:)"]}],"metadata":{"roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wrap"},{"text":"(","kind":"text"},{"text":"SBSDKGenericDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentWrapper","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentWrapper"},{"text":"?","kind":"text"}],"title":"wrap(_:)","symbolKind":"method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"wrap:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRootType(cm)wrap:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRootType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"wrap","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"document","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","text":"SBSDKGenericDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentWrapper","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","text":"SBSDKGenericDocumentWrapper"},{"text":"?","kind":"text"}]}]}],"abstract":[{"text":"Creates a strongly-typed wrapper of the given document.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Returns nil if the document type is not part of this document schema."}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRootType\/wrap(_:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentWrapper":{"abstract":[{"text":"Base class for strongly-typed ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","type":"reference","isActive":true},{"type":"text","text":" wrappers."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"title":"SBSDKGenericDocumentWrapper","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRootType":{"type":"topic","abstract":[{"text":"Root document type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRootType"}],"role":"symbol","title":"SBSDKGenericDocumentRootType","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentroottype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRootType","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentRootType"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRootType/wrap(_:)":{"type":"topic","kind":"symbol","role":"symbol","title":"wrap(_:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wrap","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","text":"SBSDKGenericDocument","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentWrapper","text":"SBSDKGenericDocumentWrapper"},{"kind":"text","text":"?"}],"abstract":[{"text":"Creates a strongly-typed wrapper of the given document.","type":"text"},{"type":"text","text":" "},{"text":"Returns nil if the document type is not part of this document schema.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentroottype\/wrap(_:)","navigatorTitle":[{"text":"wrap:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRootType\/wrap(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"abstract":[{"text":"Represents a generic document with fields and sub-documents used for document recognition.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocument","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"title":"SBSDKGenericDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"wrap:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"wrap:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","text":"SBSDKGenericDocumentWrapper","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentWrapper"},{"kind":"text","text":" *) "},{"text":"wrap:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","text":"SBSDKGenericDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"document"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/title","op":"replace","value":"SBSDKGenericDocumentWrapper"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRootType\/title","op":"replace","value":"SBSDKGenericDocumentRootType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRootType\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRootType"}]},{"value":"wrap:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRootType~1wrap(_:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRootType~1wrap(_:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"wrap:","kind":"identifier"}]},{"value":"SBSDKGenericDocument","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}]}]}]}