{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDeviceDeregistrationError\/initWithDeviceId:errorMessage:","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"navigatorTitle":[{"text":"initWithDeviceId:errorMessage:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"method","roleHeading":"Instance Method","title":"initWithDeviceId:errorMessage:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDeviceId:errorMessage:","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDeviceDeregistrationError(im)initWithDeviceId:errorMessage:"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdevicederegistrationerror\/initwithdeviceid:errormessage:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithDeviceId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"deviceId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"errorMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"errorMessage","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDeviceDeregistrationError"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDeviceDeregistrationError/initWithDeviceId:errorMessage:":{"navigatorTitle":[{"kind":"identifier","text":"initWithDeviceId:errorMessage:"}],"type":"topic","title":"initWithDeviceId:errorMessage:","kind":"symbol","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdevicederegistrationerror\/initwithdeviceid:errormessage:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDeviceDeregistrationError\/initWithDeviceId:errorMessage:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDeviceId:errorMessage:"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDeviceDeregistrationError":{"type":"topic","navigatorTitle":[{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDeviceDeregistrationError","abstract":[{"text":"Description of error that occurred during device deregistration.","type":"text"}],"title":"SBSDKDeviceDeregistrationError","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdevicederegistrationerror"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","abstract":[{"text":"Version: 8.0.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","role":"collection"}},"variantOverrides":[{"patch":[{"value":"SBSDKDeviceDeregistrationError","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDeviceDeregistrationError\/title"},{"value":[{"kind":"identifier","text":"SBSDKDeviceDeregistrationError"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDeviceDeregistrationError\/fragments"},{"value":[{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDeviceDeregistrationError\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}