{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus"]]},"metadata":{"symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus@SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusNotValidated","role":"symbol","title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus.notValidated","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notValidated","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusNotValidated"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/notValidated"},"kind":"symbol","abstract":[{"type":"text","text":"Field shouldn’t be validated."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notValidated"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/notvalidated"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/notvalidated"]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus"}],"abstract":[{"type":"text","text":"Health insurance card field validation status."}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus","title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus/notValidated":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"notValidated","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusNotValidated"}],"type":"topic","kind":"symbol","title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus.notValidated","abstract":[{"text":"Field shouldn’t be validated.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/notValidated","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/notvalidated"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusNotValidated"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusNotValidated"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusNotValidated"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/title","value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/fragments","op":"replace","value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/navigatorTitle","op":"replace","value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus~1notValidated\/title","value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusNotValidated"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus~1notValidated\/fragments","value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusNotValidated"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}