{"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithGenericDocument:"}],"symbolKind":"method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentModelDEMedicalPlanSubheading(im)initWithGenericDocument:","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGenericDocument:"}],"roleHeading":"Instance Method","title":"initWithGenericDocument:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelDEMedicalPlanSubheading"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelDEMedicalPlanSubheading\/initWithGenericDocument:"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodeldemedicalplansubheading\/initwithgenericdocument:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithGenericDocument:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocument","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocument","text":"SBSDKGenericDocument"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"document"},{"kind":"text","text":";"}]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelDEMedicalPlanSubheading/initWithGenericDocument:":{"navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelDEMedicalPlanSubheading\/initWithGenericDocument:","role":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodeldemedicalplansubheading\/initwithgenericdocument:","title":"initWithGenericDocument:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocument":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocument","kind":"symbol","title":"SBSDKGenericDocument","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocument","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"abstract":[{"type":"text","text":"Generic document."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocument","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelDEMedicalPlanSubheading":{"type":"topic","title":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheading","abstract":[{"type":"text","text":"Subheading"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheading"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheading"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodeldemedicalplansubheading","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelDEMedicalPlanSubheading"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/title","value":"SBSDKGenericDocument","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/fragments","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/navigatorTitle","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"op":"replace"},{"value":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheading","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelDEMedicalPlanSubheading\/title","op":"replace"},{"value":[{"text":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheading","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelDEMedicalPlanSubheading\/fragments","op":"replace"},{"value":[{"text":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheading","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelDEMedicalPlanSubheading\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}