{"abstract":[{"text":"Defines how to handle incomplete MRZ results (e.g. caused by failed validation).","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZParserConfiguration\/incompleteResultHandling","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incompleteResultHandling","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMRZIncompleteResultHandling","text":"SBSDKMRZIncompleteResultHandling","kind":"typeIdentifier"}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Default is ACCEPT"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzparserconfiguration\/incompleteresulthandling"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzparserconfiguration\/incompleteresulthandling"]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"incompleteResultHandling","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZParserConfiguration(py)incompleteResultHandling","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incompleteResultHandling","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKMRZIncompleteResultHandling","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMRZIncompleteResultHandling"}],"roleHeading":"Instance Property","role":"symbol","title":"incompleteResultHandling","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZParserConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZIncompleteResultHandling":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzincompleteresulthandling","abstract":[{"text":"Defines how to handle incomplete MRZ results (e.g. caused by failed validation).","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZIncompleteResultHandling"}],"title":"SBSDKMRZIncompleteResultHandling","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZIncompleteResultHandling"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZParserConfiguration":{"title":"SBSDKMRZParserConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkmrzparserconfiguration","abstract":[{"text":"Configuration for MRZ parser.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZParserConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZParserConfiguration","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZParserConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZParserConfiguration/incompleteResultHandling":{"abstract":[{"text":"Defines how to handle incomplete MRZ results (e.g. caused by failed validation).","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incompleteResultHandling","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKMRZIncompleteResultHandling","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMRZIncompleteResultHandling"}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzparserconfiguration\/incompleteresulthandling","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZParserConfiguration\/incompleteResultHandling","role":"symbol","type":"topic","kind":"symbol","title":"incompleteResultHandling","navigatorTitle":[{"text":"incompleteResultHandling","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"incompleteResultHandling","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"incompleteResultHandling"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMRZIncompleteResultHandling","text":"SBSDKMRZIncompleteResultHandling","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling"},{"text":" ","kind":"text"},{"text":"incompleteResultHandling","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/title","value":"SBSDKMRZIncompleteResultHandling","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/fragments","value":[{"text":"SBSDKMRZIncompleteResultHandling","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMRZIncompleteResultHandling"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZParserConfiguration\/title","value":"SBSDKMRZParserConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZParserConfiguration\/fragments","value":[{"text":"SBSDKMRZParserConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZParserConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMRZParserConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZParserConfiguration~1incompleteResultHandling\/title","value":"incompleteResultHandling","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZParserConfiguration~1incompleteResultHandling\/fragments","value":[{"text":"incompleteResultHandling","kind":"identifier"}],"op":"replace"}]}]}