{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRangeEncoding\/initWithStart:end:encoding:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRangeEncoding"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkrangeencoding\/initwithstart:end:encoding:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithStart:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"start","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"end:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"end","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"encoding:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding","text":"SBSDKCharacterEncoding","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"encoding","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"initWithStart:end:encoding:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKRangeEncoding(im)initWithStart:end:encoding:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStart:end:encoding:"}],"roleHeading":"Instance Method","title":"initWithStart:end:encoding:","modules":[{"name":"ScanbotSDK"}]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCharacterEncoding":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding","kind":"symbol","abstract":[{"text":"Enumerates character encodings.","type":"text"}],"title":"SBSDKCharacterEncoding","navigatorTitle":[{"text":"SBSDKCharacterEncoding","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcharacterencoding","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCharacterEncoding","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRangeEncoding":{"title":"SBSDKRangeEncoding","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKRangeEncoding","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkrangeencoding","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRangeEncoding","abstract":[{"type":"text","text":"A character encoding for a given range of bytes."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKRangeEncoding","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRangeEncoding/initWithStart:end:encoding:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithStart:end:encoding:","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithStart:end:encoding:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRangeEncoding\/initWithStart:end:encoding:","title":"initWithStart:end:encoding:","abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkrangeencoding\/initwithstart:end:encoding:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding\/title","value":"SBSDKCharacterEncoding","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding\/fragments","value":[{"kind":"identifier","text":"SBSDKCharacterEncoding"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding\/navigatorTitle","value":[{"text":"SBSDKCharacterEncoding","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRangeEncoding\/title","value":"SBSDKRangeEncoding","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRangeEncoding\/fragments","value":[{"kind":"identifier","text":"SBSDKRangeEncoding"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRangeEncoding\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKRangeEncoding"}],"op":"replace"}]}]}