{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresult\/string(fordateresulttype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresult\/string(fordateresulttype:)"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerResult(im)stringForDateResultType:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"stringForDateResultType:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"string"},{"kind":"text","text":"("},{"text":"forDateResultType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerDateResult","text":"SBSDKMedicalCertificateRecognizerDateResult","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","roleHeading":"Instance Method","title":"string(forDateResultType:)","modules":[{"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResult\/string(forDateResultType:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResult"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"string","kind":"identifier"},{"kind":"text","text":"("},{"text":"forDateResultType","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"date","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerDateResult","kind":"typeIdentifier","text":"SBSDKMedicalCertificateRecognizerDateResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResult"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A medical certificates date result."}],"type":"paragraph"}],"name":"date"}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A human readable english text for the given date’s type."}]}],"kind":"content"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResult":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResult"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResult"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresult","role":"symbol","kind":"symbol","abstract":[{"text":"Class contains date information retrieved by medical certificates recognizer.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResult","type":"topic","title":"SBSDKMedicalCertificateRecognizerDateResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResult/string(forDateResultType:)":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresult\/string(fordateresulttype:)","title":"string(forDateResultType:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"stringForDateResultType:"}],"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"string"},{"text":"(","kind":"text"},{"text":"forDateResultType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKMedicalCertificateRecognizerDateResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerDateResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResult\/string(forDateResultType:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResult":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResult"}],"title":"SBSDKMedicalCertificateRecognizerResult","role":"symbol","abstract":[{"type":"text","text":"This class describes the results of a medical certificate recognition."}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResult","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresult","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"stringForDateResultType:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stringForDateResultType:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"stringForDateResultType:"},{"kind":"text","text":"("},{"text":"SBSDKMedicalCertificateRecognizerDateResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerDateResult"},{"text":" *) ","kind":"text"},{"text":"date","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"date","content":[{"type":"paragraph","inlineContent":[{"text":"A medical certificates date result.","type":"text"}]}]}],"kind":"parameters"}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A human readable english text for the given date’s type."}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResult\/title","value":"SBSDKMedicalCertificateRecognizerDateResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResult"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResult\/navigatorTitle","op":"replace","value":[{"text":"SBSDKMedicalCertificateRecognizerDateResult","kind":"identifier"}]},{"value":"stringForDateResultType:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResult~1string(forDateResultType:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"stringForDateResultType:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResult~1string(forDateResultType:)\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateRecognizerResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResult\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResult\/fragments","value":[{"text":"SBSDKMedicalCertificateRecognizerResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResult\/navigatorTitle","op":"replace","value":[{"text":"SBSDKMedicalCertificateRecognizerResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}