{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"string"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forPatientFieldType"},{"text":" ","kind":"text"},{"text":"patientField","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerResultPatientField","kind":"typeIdentifier","text":"SBSDKMedicalCertificateRecognizerResultPatientField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientField"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"patientField","content":[{"inlineContent":[{"text":"A medical certificates patients field.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A human readable english text for the given patient fields type."}]}],"kind":"content"}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresult\/string(forpatientfieldtype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresult\/string(forpatientfieldtype:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResult\/string(forPatientFieldType:)"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"string","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forPatientFieldType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerResultPatientField","kind":"typeIdentifier","text":"SBSDKMedicalCertificateRecognizerResultPatientField"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"stringForPatientFieldType:","kind":"identifier"}],"title":"string(forPatientFieldType:)","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerResult(im)stringForPatientFieldType:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResult"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResult/string(forPatientFieldType:)":{"abstract":[],"title":"string(forPatientFieldType:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"string"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPatientFieldType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerResultPatientField","kind":"typeIdentifier","text":"SBSDKMedicalCertificateRecognizerResultPatientField"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","navigatorTitle":[{"text":"stringForPatientFieldType:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresult\/string(forpatientfieldtype:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResult\/string(forPatientFieldType:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResult":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresult","abstract":[{"type":"text","text":"This class describes the results of a medical certificate recognition."}],"title":"SBSDKMedicalCertificateRecognizerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKMedicalCertificateRecognizerResult","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResult"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResultPatientField":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientField","title":"SBSDKMedicalCertificateRecognizerResultPatientField","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerResultPatientField","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfield","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientField"}],"kind":"symbol","abstract":[{"type":"text","text":"This class represents one entry of patient information recognized by medical certificate recognition."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"stringForPatientFieldType:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"stringForPatientFieldType:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"stringForPatientFieldType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerResultPatientField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerResultPatientField"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"patientField"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResult~1string(forPatientFieldType:)\/title","value":"stringForPatientFieldType:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResult~1string(forPatientFieldType:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stringForPatientFieldType:"}],"op":"replace"},{"value":"SBSDKMedicalCertificateRecognizerResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResult\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResult\/fragments","value":[{"text":"SBSDKMedicalCertificateRecognizerResult","kind":"identifier"}]},{"op":"replace","value":"SBSDKMedicalCertificateRecognizerResultPatientField","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientField\/title"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientField"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientField\/fragments"}]}]}