{"kind":"symbol","abstract":[{"text":"Binarization filter primary inteded to use on low-contrast documents with heavy shadows.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"deprecationSummary":[{"inlineContent":[{"text":"Please consider using the new class-based SBSDKParametricFilters.","type":"text"}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/lowLightBinarization","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowLightBinarization"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Case","title":"SBSDKImageFilterType.lowLightBinarization","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFilterType@SBSDKImageFilterTypeLowLightBinarization","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowLightBinarization"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"platforms":[],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeLowLightBinarization"}]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/lowlightbinarization"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/lowlightbinarization"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/lowLightBinarization":{"abstract":[{"type":"text","text":"Binarization filter primary inteded to use on low-contrast documents with heavy shadows."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/lowLightBinarization","title":"SBSDKImageFilterType.lowLightBinarization","navigatorTitle":[{"text":"SBSDKImageFilterTypeLowLightBinarization","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lowLightBinarization","kind":"identifier"}],"kind":"symbol","deprecated":true,"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/lowlightbinarization"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType":{"abstract":[{"text":"The ScanbotSDK image filter types.","type":"text"}],"kind":"symbol","type":"topic","title":"SBSDKImageFilterType","navigatorTitle":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"deprecated":true,"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageFilterType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKImageFilterTypeLowLightBinarization","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKImageFilterTypeLowLightBinarization","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKImageFilterTypeLowLightBinarization","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1lowLightBinarization\/title","value":"SBSDKImageFilterTypeLowLightBinarization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1lowLightBinarization\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeLowLightBinarization"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/title","value":"SBSDKImageFilterType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/fragments","value":[{"text":"SBSDKImageFilterType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageFilterType"}]}]}]}