{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentWrapper(py)requiredDocumentType","navigatorTitle":[{"text":"requiredDocumentType","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"title":"requiredDocumentType"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper\/requiredDocumentType","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The required type of the wrapped document. "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if this wrapper can wrap more than one type of document."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper\/requireddocumenttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper\/requireddocumenttype"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentWrapper/requiredDocumentType":{"title":"requiredDocumentType","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper\/requiredDocumentType","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper\/requireddocumenttype","navigatorTitle":[{"text":"requiredDocumentType","kind":"identifier"}],"abstract":[{"type":"text","text":"The required type of the wrapped document. "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if this wrapper can wrap more than one type of document."}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentWrapper":{"type":"topic","abstract":[{"text":"Base class for strongly-typed ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"},{"text":" wrappers.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper","navigatorTitle":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"kind":"symbol","title":"SBSDKGenericDocumentWrapper"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"title":"SBSDKGenericDocument","abstract":[{"type":"text","text":"Generic document."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocument"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"requiredDocumentType","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"requiredDocumentType","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"requiredDocumentType"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"requiredDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper~1requiredDocumentType\/title","op":"replace"},{"value":[{"text":"requiredDocumentType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper~1requiredDocumentType\/fragments","op":"replace"},{"value":"SBSDKGenericDocumentWrapper","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/title","op":"replace"},{"value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/fragments","op":"replace"},{"value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","value":"SBSDKGenericDocument"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}]}]}]}