{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(availableDevicesForType:) ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableDevices","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType","text":"SBSDKCameraDeviceType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDeviceType"},{"text":") -> [","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice","text":"SBSDKCameraDevice","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice"},{"text":"]","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The type of the requested cameras: wide, ultra-wide, tele, etc.","type":"text"}]}],"name":"type"}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A list of the supported available cameras of the current device for the given type.","type":"text"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/availableDevices(for:)-16nqr","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableDevices"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDeviceType","text":"SBSDKCameraDeviceType"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice","text":"SBSDKCameraDevice"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"availableDevicesForType:"}],"roleHeading":"Type Method","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice(cm)availableDevicesForType:","title":"availableDevices(for:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Returns a list of all available and supported cameras of the device of the given type."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevice\/availabledevices(for:)-16nqr"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevice\/availabledevices(for:)-16nqr"]}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice/availableDevices(for:)-16nqr":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableDevices"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDeviceType","kind":"typeIdentifier","text":"SBSDKCameraDeviceType"},{"kind":"text","text":") -> ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice","kind":"typeIdentifier","text":"SBSDKCameraDevice"},{"kind":"text","text":"]"}],"title":"availableDevices(for:)","url":"\/documentation\/scanbotsdk\/sbsdkcameradevice\/availabledevices(for:)-16nqr","abstract":[{"text":"Returns a list of all available and supported cameras of the device of the given type.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/availableDevices(for:)-16nqr","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"availableDevicesForType:"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType","kind":"symbol","role":"symbol","title":"SBSDKCameraDeviceType","navigatorTitle":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"An enum to describe the different types of camera lenses\/devices."}],"url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraDeviceType","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraDevice","kind":"identifier"}],"title":"SBSDKCameraDevice","url":"\/documentation\/scanbotsdk\/sbsdkcameradevice","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKCameraDevice","kind":"identifier"}],"abstract":[{"type":"text","text":"The camera device to be used with a "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","type":"reference","isActive":true},{"type":"text","text":"."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","title":"SBSDKCameraSession","role":"symbol","navigatorTitle":[{"text":"SBSDKCameraSession","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraSession","kind":"identifier"}],"abstract":[{"text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the","type":"text"},{"text":" ","type":"text"},{"text":"camera device and the preview layer. Provides functionality to capture still images.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"availableDevicesForType:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"availableDevicesForType:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSArray<SBSDKCameraDevice *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"availableDevicesForType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType","text":"SBSDKCameraDeviceType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDeviceType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The type of the requested cameras: wide, ultra-wide, tele, etc.","type":"text"}]}],"name":"type"}],"kind":"parameters"},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A list of the supported available cameras of the current device for the given type."}]}]},"op":"replace"},{"value":"availableDevicesForType:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1availableDevices(for:)-16nqr\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"availableDevicesForType:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1availableDevices(for:)-16nqr\/fragments","op":"replace"},{"value":"SBSDKCameraDeviceType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCameraDeviceType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/fragments","op":"replace"},{"value":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/navigatorTitle","op":"replace"},{"value":"SBSDKCameraDevice","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCameraDevice"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCameraDevice"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice\/navigatorTitle","op":"replace"},{"value":"SBSDKCameraSession","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/title","op":"replace"},{"value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/fragments","op":"replace"},{"op":"replace","value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/navigatorTitle"}]}]}