{"abstract":[{"type":"text","text":"Creates a configuration object from a JSON file located at the specified URL."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration"]]},"kind":"symbol","metadata":{"roleHeading":"Type Method","navigatorTitle":[{"text":"configurationWithJSONFromURL:","kind":"identifier"}],"title":"configurationWithJSONFrom(URL:)","role":"symbol","symbolKind":"method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)ScanbotSDKConfiguration(cm)configurationWithJSONFromURL:","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configurationWithJSONFrom"},{"kind":"text","text":"("},{"text":"URL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)ScanbotSDKConfiguration","text":"ScanbotSDKConfiguration"},{"text":"?","kind":"text"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"configurationWithJSONFrom","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"URL"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)ScanbotSDKConfiguration","text":"ScanbotSDKConfiguration"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL of the JSON file containing configuration settings."}]}],"name":"URL"}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"A configured ","type":"text"},{"type":"codeVoice","code":"ScanbotSDKConfiguration"},{"text":" instance if the JSON file is successfully loaded and parsed,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the file is not found or there was an issue with parsing."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration\/configurationwithjsonfrom(url:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration\/configurationwithjsonfrom(url:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration\/configurationWithJSONFrom(URL:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/ScanbotSDKConfiguration":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration","title":"ScanbotSDKConfiguration","navigatorTitle":[{"kind":"identifier","text":"ScanbotSDKConfiguration"}],"kind":"symbol","abstract":[{"type":"codeVoice","code":"ScanbotSDKConfiguration"},{"text":" is a configuration class that allows you to customize various settings and behavior of the Scanbot SDK.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ScanbotSDKConfiguration"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/ScanbotSDKConfiguration/configurationWithJSONFrom(URL:)":{"abstract":[{"text":"Creates a configuration object from a JSON file located at the specified URL.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"configurationWithJSONFrom","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"URL"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)ScanbotSDKConfiguration","text":"ScanbotSDKConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"configurationWithJSONFrom(URL:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration\/configurationWithJSONFrom(URL:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"configurationWithJSONFromURL:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration\/configurationwithjsonfrom(url:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 6.1.0"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"configurationWithJSONFromURL:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configurationWithJSONFromURL:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration","text":"ScanbotSDKConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)ScanbotSDKConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"configurationWithJSONFromURL:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"URL","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"URL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL of the JSON file containing configuration settings."}]}]}]}},{"value":{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A configured ","type":"text"},{"type":"codeVoice","code":"ScanbotSDKConfiguration"},{"text":" instance if the JSON file is successfully loaded and parsed,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the file is not found or there was an issue with parsing."}]}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"ScanbotSDKConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration\/fragments","value":[{"kind":"identifier","text":"ScanbotSDKConfiguration"}]},{"value":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration~1configurationWithJSONFrom(URL:)\/title","value":"configurationWithJSONFromURL:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"configurationWithJSONFromURL:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration~1configurationWithJSONFrom(URL:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}