{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration\/sharedApplication","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration\/sharedapplication"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration\/sharedapplication"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"sharedApplication","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)ScanbotSDKConfiguration(py)sharedApplication","title":"sharedApplication","navigatorTitle":[{"text":"sharedApplication","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sharedApplication","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"The shared "},{"type":"codeVoice","code":"UIApplication"},{"type":"text","text":" instance. Automatically set to the shared application instance if available."}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/ScanbotSDKConfiguration/sharedApplication":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"sharedApplication","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"sharedApplication","kind":"identifier"}],"abstract":[{"type":"text","text":"The shared "},{"type":"codeVoice","code":"UIApplication"},{"type":"text","text":" instance. Automatically set to the shared application instance if available."}],"type":"topic","title":"sharedApplication","url":"\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration\/sharedapplication","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration\/sharedApplication"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/ScanbotSDKConfiguration":{"kind":"symbol","navigatorTitle":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ScanbotSDKConfiguration"}],"abstract":[{"code":"ScanbotSDKConfiguration","type":"codeVoice"},{"type":"text","text":" is a configuration class that allows you to customize various settings and behavior of the Scanbot SDK."}],"title":"ScanbotSDKConfiguration","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"sharedApplication","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"sharedApplication","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sharedApplication"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration~1sharedApplication\/title","value":"sharedApplication","op":"replace"},{"value":[{"kind":"identifier","text":"sharedApplication"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration~1sharedApplication\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration\/title","op":"replace","value":"ScanbotSDKConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration\/fragments","value":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration\/navigatorTitle","value":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}