{"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2TextPatternScannerViewController instead.","type":"text"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextPatternScannerUIConfiguration(py)topBarBackgroundColor","title":"topBarBackgroundColor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"topBarBackgroundColor"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"modules":[{"name":"ScanbotSDK"}],"platforms":[],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerUIConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerUIConfiguration\/topBarBackgroundColor","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Background color of the top bar."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscanneruiconfiguration\/topbarbackgroundcolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscanneruiconfiguration\/topbarbackgroundcolor"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerUIConfiguration":{"kind":"symbol","abstract":[{"text":"Configuration for the user interface of the RTU-UI text pattern scanner.","type":"text"}],"deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUITextPatternScannerUIConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerUIConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscanneruiconfiguration","role":"symbol","title":"SBSDKUITextPatternScannerUIConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUITextPatternScannerUIConfiguration"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerUIConfiguration/topBarBackgroundColor":{"abstract":[{"text":"Background color of the top bar.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"type":"topic","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerUIConfiguration\/topBarBackgroundColor","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscanneruiconfiguration\/topbarbackgroundcolor","title":"topBarBackgroundColor","navigatorTitle":[{"kind":"identifier","text":"topBarBackgroundColor"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"topBarBackgroundColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"topBarBackgroundColor","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"topBarBackgroundColor"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerUIConfiguration\/title","value":"SBSDKUITextPatternScannerUIConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerUIConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUITextPatternScannerUIConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerUIConfiguration\/navigatorTitle","value":[{"text":"SBSDKUITextPatternScannerUIConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerUIConfiguration~1topBarBackgroundColor\/title","value":"topBarBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerUIConfiguration~1topBarBackgroundColor\/fragments","value":[{"kind":"identifier","text":"topBarBackgroundColor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}