{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithVersion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"version"},{"text":" ","kind":"text"},{"text":"screen:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"screen","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"palette:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Palette","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Palette","kind":"typeIdentifier","text":"SBSDKUI2Palette"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"palette"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentUuid:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"documentUuid","kind":"internalParam"},{"kind":"text","text":" "},{"text":"pageUuid:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"pageUuid","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"localization:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingTextLocalization","text":"SBSDKUI2CroppingTextLocalization"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"localization"},{"text":" ","kind":"text"},{"text":"appearance:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUI2CroppingAppearanceConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingAppearanceConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingAppearanceConfiguration"},{"kind":"text","text":" *) "},{"text":"appearance","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cropping:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingScreenConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingScreenConfiguration","text":"SBSDKUI2CroppingScreenConfiguration"},{"text":" *) ","kind":"text"},{"text":"cropping","kind":"internalParam"},{"kind":"text","text":" "},{"text":"documentAnalysisMode:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentAnalysisMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2DocumentAnalysisMode","kind":"typeIdentifier","text":"SBSDKUI2DocumentAnalysisMode"},{"text":") ","kind":"text"},{"text":"documentAnalysisMode","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingConfiguration(im)initWithVersion:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:","navigatorTitle":[{"text":"initWithVersion:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"initWithVersion:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithVersion:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingConfiguration\/initWithVersion:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:","interfaceLanguage":"occ"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingconfiguration\/initwithversion:screen:palette:documentuuid:pageuuid:localization:appearance:cropping:documentanalysismode:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingConfiguration"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingConfiguration/initWithVersion:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:":{"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingconfiguration\/initwithversion:screen:palette:documentuuid:pageuuid:localization:appearance:cropping:documentanalysismode:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingConfiguration\/initWithVersion:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:","title":"initWithVersion:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:","fragments":[{"kind":"text","text":"- "},{"text":"initWithVersion:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithVersion:screen:palette:documentUuid:pageUuid:localization:appearance:cropping:documentAnalysisMode:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingConfiguration","title":"SBSDKUI2CroppingConfiguration","role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingconfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingConfiguration"}],"abstract":[{"text":"Configuration of the standalone cropping screen.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingAppearanceConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CroppingAppearanceConfiguration"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingAppearanceConfiguration","type":"topic","title":"SBSDKUI2CroppingAppearanceConfiguration","abstract":[{"type":"text","text":"Configuration of the general appearance for the cropping screen."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingappearanceconfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingAppearanceConfiguration"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingScreenConfiguration":{"kind":"symbol","abstract":[{"text":"Configuration of the screen for cropping the scanned pages.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingScreenConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CroppingScreenConfiguration"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingScreenConfiguration","title":"SBSDKUI2CroppingScreenConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingscreenconfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Palette":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2palette","title":"SBSDKUI2Palette","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Palette","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2Palette"}],"navigatorTitle":[{"text":"SBSDKUI2Palette","kind":"identifier"}],"abstract":[{"text":"Value palette describing the colors of the scanner screens.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization","title":"SBSDKUI2CroppingTextLocalization","navigatorTitle":[{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Configuration of all the strings for the standalone cropping screen."}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentAnalysisMode":{"navigatorTitle":[{"text":"SBSDKUI2DocumentAnalysisMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentAnalysisMode","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentanalysismode","role":"symbol","abstract":[{"type":"text","text":"Determines if the quality analysis for the acknowledgement mode will run on the filtered or the unfiltered image."}],"kind":"symbol","title":"SBSDKUI2DocumentAnalysisMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentAnalysisMode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingConfiguration\/title","value":"SBSDKUI2CroppingConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CroppingConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CroppingConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingAppearanceConfiguration\/title","value":"SBSDKUI2CroppingAppearanceConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingAppearanceConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CroppingAppearanceConfiguration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingAppearanceConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CroppingAppearanceConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingScreenConfiguration\/title","value":"SBSDKUI2CroppingScreenConfiguration","op":"replace"},{"value":[{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingScreenConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CroppingScreenConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingScreenConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2Palette","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Palette\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Palette\/fragments","op":"replace","value":[{"text":"SBSDKUI2Palette","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Palette"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Palette\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization\/title","value":"SBSDKUI2CroppingTextLocalization","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization\/fragments","value":[{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization\/navigatorTitle","value":[{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentAnalysisMode\/title","value":"SBSDKUI2DocumentAnalysisMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentAnalysisMode\/fragments","value":[{"text":"SBSDKUI2DocumentAnalysisMode","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentAnalysisMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentAnalysisMode\/navigatorTitle"}]}]}