{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode"]]},"abstract":[{"type":"text","text":"Main engine mode for high-power devices. Supports all barcodes types."}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/nextgen"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/nextgen"]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"nextGen","kind":"identifier"}],"title":"SBSDKBarcodeScannerEngineMode.nextGen","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineModeNextGen"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Case","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeScannerEngineMode@SBSDKBarcodeScannerEngineModeNextGen"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGen"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"nextGen","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode":{"type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode","title":"SBSDKBarcodeScannerEngineMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"abstract":[{"type":"text","text":"The engine mode for barcode scanning."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode/nextGen":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextGen","kind":"identifier"}],"title":"SBSDKBarcodeScannerEngineMode.nextGen","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineModeNextGen"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGen","abstract":[{"type":"text","text":"Main engine mode for high-power devices. Supports all barcodes types."}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/nextgen"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKBarcodeScannerEngineModeNextGen"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineModeNextGen"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKBarcodeScannerEngineModeNextGen","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode\/title","value":"SBSDKBarcodeScannerEngineMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineMode"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1nextGen\/title","value":"SBSDKBarcodeScannerEngineModeNextGen"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineModeNextGen"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1nextGen\/fragments"}]}]}