{"metadata":{"navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineModeNextGenFarDistance","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeScannerEngineMode@SBSDKBarcodeScannerEngineModeNextGenFarDistance","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextGenFarDistance","kind":"identifier"}],"role":"symbol","roleHeading":"Case","title":"SBSDKBarcodeScannerEngineMode.nextGenFarDistance","symbolKind":"case"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nextGenFarDistance"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGenFarDistance","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/nextgenfardistance"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/nextgenfardistance"]}],"abstract":[{"type":"text","text":"Similar to NEXT_GEN, but optimized for scanning from far distances."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode/nextGenFarDistance":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/nextgenfardistance","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGenFarDistance","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Similar to NEXT_GEN, but optimized for scanning from far distances."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextGenFarDistance","kind":"identifier"}],"title":"SBSDKBarcodeScannerEngineMode.nextGenFarDistance","navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineModeNextGenFarDistance","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode":{"type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode","title":"SBSDKBarcodeScannerEngineMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"abstract":[{"type":"text","text":"The engine mode for barcode scanning."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKBarcodeScannerEngineModeNextGenFarDistance","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeScannerEngineModeNextGenFarDistance","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKBarcodeScannerEngineModeNextGenFarDistance","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1nextGenFarDistance\/title","value":"SBSDKBarcodeScannerEngineModeNextGenFarDistance"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1nextGenFarDistance\/fragments","value":[{"text":"SBSDKBarcodeScannerEngineModeNextGenFarDistance","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode\/title","value":"SBSDKBarcodeScannerEngineMode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode\/navigatorTitle","value":[{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}