{"metadata":{"roleHeading":"Case","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2CameraModule@SBSDKUI2CameraModuleBackWidest","title":"SBSDKUI2CameraModule.backWidest","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"backWidest","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraModuleBackWidest"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraModule"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameramodule\/backwidest"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameramodule\/backwidest"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraModule\/backWidest"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backWidest"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Use the back camera with the widest available angle. iOS only."}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraModule/backWidest":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backWidest","kind":"identifier"}],"abstract":[{"type":"text","text":"Use the back camera with the widest available angle. iOS only."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraModule\/backWidest","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameramodule\/backwidest","title":"SBSDKUI2CameraModule.backWidest","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2CameraModuleBackWidest","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraModule":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameramodule","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"abstract":[{"text":"Determines which camera module to use on start-up.","type":"text"}],"kind":"symbol","title":"SBSDKUI2CameraModule","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraModule"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraModule"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKUI2CameraModuleBackWidest","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraModuleBackWidest"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKUI2CameraModuleBackWidest"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraModule~1backWidest\/title","op":"replace","value":"SBSDKUI2CameraModuleBackWidest"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraModuleBackWidest"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraModule~1backWidest\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraModule\/title","value":"SBSDKUI2CameraModule","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CameraModule"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraModule\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraModule\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}