{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfimageextractor\/extract(from:scaling:compression:encrypter:outputdirectory:)-7fdvi"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfimageextractor\/extract(from:scaling:compression:encrypter:outputdirectory:)-7fdvi"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFImageExtractor"]]},"metadata":{"title":"extract(from:scaling:compression:encrypter:outputDirectory:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extract","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"text":"scaling","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"text":"compression","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"text":"encrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"outputDirectory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"]"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"extractFromPDF:scaling:compression:encrypter:outputDirectory:"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKPDFImageExtractor(im)extractFromPDF:scaling:compression:encrypter:outputDirectory:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(extractFromPDF:scaling:compression:encrypter:outputDirectory:) "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extract"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"pdfURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"text":"scaling","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"compression","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"outputDirectory"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> ["},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"pdfURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL of the PDF file."}]}]},{"name":"scaling","content":[{"inlineContent":[{"type":"text","text":"Scaling applied to the PDF media box frame while extracting. Affects the output image quality. In most cases the recommended value is 2 and higher."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Compression of the output image file. The range is from 0 to 1, where 1 - lossless conversion, 0 - maximum compression is used.","type":"text"}]}],"name":"compression"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The encrypter used to encrypt output image files. If "},{"type":"codeVoice","code":"nil"},{"text":", no encryption is used.","type":"text"}]}],"name":"encrypter"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The output folder where images will be stored. If the folder does not exist, it will be created.","type":"text"}]}],"name":"outputDirectory"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"An array of URLs with extracted images as JPEG files. The array will be empty if something is wrong.","type":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFImageExtractor\/extract(from:scaling:compression:encrypter:outputDirectory:)-7fdvi"},"abstract":[{"type":"text","text":"Extracts images from a PDF, converts them to JPEGs and writes them to a specified URL. Runs in the same thread that it is called from."}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPDFImageExtractor":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFImageExtractor","abstract":[{"type":"text","text":"Class used to extract images from a PDF file and returns them in various ways."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPDFImageExtractor"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfimageextractor","title":"SBSDKPDFImageExtractor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFImageExtractor"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCrypting":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecrypting","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"abstract":[{"type":"text","text":"Protocol for implementing encryption and decryption of (streamed) data."}],"role":"symbol","title":"SBSDKStorageCrypting"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPDFImageExtractor/extract(from:scaling:compression:encrypter:outputDirectory:)-7fdvi":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFImageExtractor\/extract(from:scaling:compression:encrypter:outputDirectory:)-7fdvi","navigatorTitle":[{"text":"extractFromPDF:scaling:compression:encrypter:outputDirectory:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfimageextractor\/extract(from:scaling:compression:encrypter:outputdirectory:)-7fdvi","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"extract","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"text":"scaling","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"compression"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encrypter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"outputDirectory"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"]"}],"title":"extract(from:scaling:compression:encrypter:outputDirectory:)","abstract":[{"type":"text","text":"Extracts images from a PDF, converts them to JPEGs and writes them to a specified URL. Runs in the same thread that it is called from."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"extractFromPDF:scaling:compression:encrypter:outputDirectory:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"extractFromPDF:scaling:compression:encrypter:outputDirectory:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSURL *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"extractFromPDF:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"text":" *) ","kind":"text"},{"text":"pdfURL","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaling:"},{"text":"(","kind":"text"},{"text":"CGFloat","preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"scaling","kind":"internalParam"},{"kind":"text","text":" "},{"text":"compression:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"text":"compression","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"encrypter:"},{"text":"(","kind":"text"},{"text":"id<SBSDKStorageCrypting>","preciseIdentifier":"c:Qo@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"encrypter","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outputDirectory:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"outputDirectory","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The URL of the PDF file."}],"type":"paragraph"}],"name":"pdfURL"},{"name":"scaling","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Scaling applied to the PDF media box frame while extracting. Affects the output image quality. In most cases the recommended value is 2 and higher."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Compression of the output image file. The range is from 0 to 1, where 1 - lossless conversion, 0 - maximum compression is used."}]}],"name":"compression"},{"name":"encrypter","content":[{"type":"paragraph","inlineContent":[{"text":"The encrypter used to encrypt output image files. If ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":", no encryption is used."}]}]},{"name":"outputDirectory","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The output folder where images will be stored. If the folder does not exist, it will be created."}]}]}]}},{"value":{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"An array of URLs with extracted images as JPEG files. The array will be empty if something is wrong.","type":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFImageExtractor\/title","value":"SBSDKPDFImageExtractor","op":"replace"},{"op":"replace","value":[{"text":"SBSDKPDFImageExtractor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFImageExtractor\/fragments"},{"value":[{"text":"SBSDKPDFImageExtractor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFImageExtractor\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting\/title","op":"replace","value":"SBSDKStorageCrypting"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting\/fragments","value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"op":"replace"},{"value":"extractFromPDF:scaling:compression:encrypter:outputDirectory:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFImageExtractor~1extract(from:scaling:compression:encrypter:outputDirectory:)-7fdvi\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFImageExtractor~1extract(from:scaling:compression:encrypter:outputDirectory:)-7fdvi\/fragments","value":[{"kind":"text","text":"- "},{"text":"extractFromPDF:scaling:compression:encrypter:outputDirectory:","kind":"identifier"}],"op":"replace"}]}]}