{"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingResult(im)copyWithZone:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingResult"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingresult\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingResult\/copyWithZone:","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingResult":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingResult","kind":"identifier"}],"kind":"symbol","title":"SBSDKUI2CroppingResult","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingresult","type":"topic","abstract":[{"type":"text","text":"Configuration of the cropping result."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CroppingResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingResult/copyWithZone:":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingresult\/copywithzone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingResult\/copyWithZone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","type":"topic","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2CroppingResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingResult\/title"},{"op":"replace","value":[{"text":"SBSDKUI2CroppingResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingResult\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2CroppingResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingResult\/navigatorTitle"}]}]}