{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenTextConfiguration\/cancelButtonTitle","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenTextConfiguration(py)cancelButtonTitle","platforms":[],"title":"cancelButtonTitle","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"cancelButtonTitle","kind":"identifier"}],"symbolKind":"property"},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2CroppingViewController instead."}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreentextconfiguration\/cancelbuttontitle"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreentextconfiguration\/cancelbuttontitle"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"String being displayed on the cancel button."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cancelButtonTitle","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenTextConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenTextConfiguration":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenTextConfiguration","navigatorTitle":[{"text":"SBSDKUICroppingScreenTextConfiguration","kind":"identifier"}],"deprecated":true,"abstract":[{"text":"Configuration for the textual content of the page cropping screen.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreentextconfiguration","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICroppingScreenTextConfiguration"}],"title":"SBSDKUICroppingScreenTextConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenTextConfiguration/cancelButtonTitle":{"navigatorTitle":[{"kind":"identifier","text":"cancelButtonTitle"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenTextConfiguration\/cancelButtonTitle","type":"topic","abstract":[{"type":"text","text":"String being displayed on the cancel button."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cancelButtonTitle","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreentextconfiguration\/cancelbuttontitle","title":"cancelButtonTitle","deprecated":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"cancelButtonTitle","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"cancelButtonTitle"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"cancelButtonTitle","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"SBSDKUICroppingScreenTextConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenTextConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUICroppingScreenTextConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenTextConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUICroppingScreenTextConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenTextConfiguration\/navigatorTitle"},{"value":"cancelButtonTitle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenTextConfiguration~1cancelButtonTitle\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenTextConfiguration~1cancelButtonTitle\/fragments","value":[{"kind":"identifier","text":"cancelButtonTitle"}],"op":"replace"}]}]}