{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton\/layoutsubviews"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/layoutSubviews","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","title":"layoutSubviews","roleHeading":"Instance Method","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKShutterButton(im)layoutSubviews","fragments":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}]},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKShutterButton":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKShutterButton"}],"type":"topic","role":"symbol","title":"SBSDKShutterButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKShutterButton"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton","abstract":[{"text":"The button class used in the camera view controller to take a snapshot.","type":"text"},{"text":" ","type":"text"},{"text":"Animates itself depending on its status.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKShutterButton/layoutSubviews":{"title":"layoutSubviews","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/layoutSubviews","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton\/layoutsubviews","kind":"symbol","abstract":[],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKShutterButton","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton\/title"},{"op":"replace","value":[{"text":"SBSDKShutterButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton\/fragments"},{"op":"replace","value":[{"text":"SBSDKShutterButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}