{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/detectDocument"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectDocument"}],"platforms":["iOS"]}]}],"metadata":{"title":"SBSDKCheckDocumentDetectionMode.detectDocument","role":"symbol","roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKCheckDocumentDetectionMode@SBSDKCheckDocumentDetectionModeDetectDocument","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectDocument"}],"symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckDocumentDetectionModeDetectDocument"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode"]]},"kind":"symbol","abstract":[{"text":"Document scanner will be used to locate the complete check in the input image. The documentDetectionResult result field will contain the result of document detection.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode\/detectdocument"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode\/detectdocument"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentDetectionMode":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode","navigatorTitle":[{"text":"SBSDKCheckDocumentDetectionMode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckDocumentDetectionMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode","abstract":[{"type":"text","text":"Check document detection and extraction mode."}],"title":"SBSDKCheckDocumentDetectionMode","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentDetectionMode/detectDocument":{"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectDocument","kind":"identifier"}],"title":"SBSDKCheckDocumentDetectionMode.detectDocument","navigatorTitle":[{"text":"SBSDKCheckDocumentDetectionModeDetectDocument","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/detectDocument","kind":"symbol","abstract":[{"text":"Document scanner will be used to locate the complete check in the input image. The documentDetectionResult result field will contain the result of document detection.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode\/detectdocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKCheckDocumentDetectionModeDetectDocument","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKCheckDocumentDetectionModeDetectDocument","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKCheckDocumentDetectionModeDetectDocument","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode\/title","value":"SBSDKCheckDocumentDetectionMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckDocumentDetectionMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCheckDocumentDetectionMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode~1detectDocument\/title","value":"SBSDKCheckDocumentDetectionModeDetectDocument","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode~1detectDocument\/fragments","value":[{"text":"SBSDKCheckDocumentDetectionModeDetectDocument","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}