{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"visible"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"kind":"externalParam","text":"text"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" = \"\", ","kind":"text"},{"text":"background","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BackgroundStyle","text":"SBSDKUI2BackgroundStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BackgroundStyle","kind":"typeIdentifier"},{"text":" = SBSDKUI2BackgroundStyle(), ","kind":"text"},{"text":"foreground","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ForegroundStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ForegroundStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ForegroundStyle"},{"text":" = SBSDKUI2ForegroundStyle())","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"visible","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"text"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"background"},{"kind":"text","text":": "},{"text":"SBSDKUI2BackgroundStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BackgroundStyle"},{"text":", ","kind":"text"},{"text":"foreground","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ForegroundStyle","text":"SBSDKUI2ForegroundStyle"},{"kind":"text","text":")"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Initializer","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration(im)initWithVisible:text:background:foreground:","title":"init(visible:text:background:foreground:)","symbolKind":"init","navigatorTitle":[{"text":"initWithVisible:text:background:foreground:","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration\/init(visible:text:background:foreground:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2buttonconfiguration\/init(visible:text:background:foreground:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2buttonconfiguration\/init(visible:text:background:foreground:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ButtonConfiguration":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2buttonconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"title":"SBSDKUI2ButtonConfiguration","abstract":[{"text":"Button configuration.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ButtonConfiguration/init(visible:text:background:foreground:)":{"url":"\/documentation\/scanbotsdk\/sbsdkui2buttonconfiguration\/init(visible:text:background:foreground:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"visible"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"text","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"background"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BackgroundStyle","text":"SBSDKUI2BackgroundStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"foreground"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ForegroundStyle","text":"SBSDKUI2ForegroundStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration\/init(visible:text:background:foreground:)","kind":"symbol","role":"symbol","title":"init(visible:text:background:foreground:)","navigatorTitle":[{"text":"initWithVisible:text:background:foreground:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ForegroundStyle":{"type":"topic","navigatorTitle":[{"text":"SBSDKUI2ForegroundStyle","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ForegroundStyle"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ForegroundStyle","url":"\/documentation\/scanbotsdk\/sbsdkui2foregroundstyle","kind":"symbol","title":"SBSDKUI2ForegroundStyle","abstract":[{"type":"text","text":"Configuration of the appearance of foreground elements (e.g. text and\/or icons on buttons, etc)."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BackgroundStyle":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}],"type":"topic","title":"SBSDKUI2BackgroundStyle","url":"\/documentation\/scanbotsdk\/sbsdkui2backgroundstyle","role":"symbol","abstract":[{"text":"Appearance of the polygon used for buttons and hint backgrounds.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BackgroundStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BackgroundStyle"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithVisible:text:background:foreground:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithVisible:text:background:foreground:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithVisible:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"visible","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"text:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"text","kind":"internalParam"},{"kind":"text","text":" "},{"text":"background:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BackgroundStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BackgroundStyle","text":"SBSDKUI2BackgroundStyle"},{"text":" *) ","kind":"text"},{"text":"background","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"foreground:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ForegroundStyle","text":"SBSDKUI2ForegroundStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ForegroundStyle","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"foreground"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/title","value":"SBSDKUI2ButtonConfiguration","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/fragments"},{"value":"initWithVisible:text:background:foreground:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration~1init(visible:text:background:foreground:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"initWithVisible:text:background:foreground:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration~1init(visible:text:background:foreground:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ForegroundStyle\/title","op":"replace","value":"SBSDKUI2ForegroundStyle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ForegroundStyle\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ForegroundStyle"}],"op":"replace"},{"value":"SBSDKUI2BackgroundStyle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BackgroundStyle\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BackgroundStyle\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BackgroundStyle"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}