{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerIntroImage"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerintroimage\/vinintronoimage()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerintroimage\/vinintronoimage()"]}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"vinIntroNoImage","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"SBSDKUI2VINIntroNoImage","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINIntroNoImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINIntroNoImage"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerIntroImage\/vinIntroNoImage()","interfaceLanguage":"swift"},"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerIntroImage(cm)vinIntroNoImage","title":"vinIntroNoImage()","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"vinIntroNoImage","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINIntroNoImage","kind":"typeIdentifier","text":"SBSDKUI2VINIntroNoImage"}],"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"vinIntroNoImage","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINIntroNoImage":{"title":"SBSDKUI2VINIntroNoImage","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2VINIntroNoImage"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinintronoimage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINIntroNoImage","type":"topic","abstract":[{"text":"No image for the introduction screen.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2VINIntroNoImage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerIntroImage/vinIntroNoImage()":{"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerintroimage\/vinintronoimage()","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vinIntroNoImage"},{"kind":"text","text":"() -> "},{"text":"SBSDKUI2VINIntroNoImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINIntroNoImage","kind":"typeIdentifier"}],"abstract":[],"title":"vinIntroNoImage()","navigatorTitle":[{"text":"vinIntroNoImage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerIntroImage\/vinIntroNoImage()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerIntroImage":{"abstract":[{"text":"The image for the introduction screen of a VIN scanner screen.","type":"text"}],"title":"SBSDKUI2VINScannerIntroImage","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerintroimage","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2VINScannerIntroImage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerIntroImage","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2VINScannerIntroImage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"vinIntroNoImage"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"vinIntroNoImage","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2VINIntroNoImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINIntroNoImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINIntroNoImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"vinIntroNoImage","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINIntroNoImage\/title","value":"SBSDKUI2VINIntroNoImage"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2VINIntroNoImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINIntroNoImage\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2VINIntroNoImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINIntroNoImage\/navigatorTitle","op":"replace"},{"op":"replace","value":"vinIntroNoImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerIntroImage~1vinIntroNoImage()\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerIntroImage~1vinIntroNoImage()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"vinIntroNoImage"}],"op":"replace"},{"value":"SBSDKUI2VINScannerIntroImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerIntroImage\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerIntroImage\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2VINScannerIntroImage"}],"op":"replace"},{"value":[{"text":"SBSDKUI2VINScannerIntroImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerIntroImage\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}