{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldParsedData"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldparseddata\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldParsedData(py)hash","fragments":[{"text":"hash","kind":"identifier"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"hash","kind":"identifier"}],"title":"hash","role":"symbol","symbolKind":"property","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldParsedData\/hash"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldParsedData/hash":{"kind":"symbol","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"hash"}],"title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldparseddata\/hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldParsedData\/hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldParsedData":{"abstract":[{"text":"Parsed data.","type":"text"}],"title":"SBSDKGenericDocumentFieldParsedData","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfieldparseddata","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldParsedData","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentFieldParsedData","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentFieldParsedData","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldParsedData\/title","op":"replace","value":"SBSDKGenericDocumentFieldParsedData"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldParsedData\/fragments","op":"replace","value":[{"text":"SBSDKGenericDocumentFieldParsedData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldParsedData\/navigatorTitle","op":"replace","value":[{"text":"SBSDKGenericDocumentFieldParsedData","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}