{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessingQueueFactory"]]},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProcessingQueueFactory(im)init","symbolKind":"method","title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessingqueuefactory\/init"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessingQueueFactory\/init","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProcessingQueueFactory/init":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessingqueuefactory\/init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessingQueueFactory\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","title":"init","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProcessingQueueFactory":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKProcessingQueueFactory","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessingQueueFactory","kind":"symbol","navigatorTitle":[{"text":"SBSDKProcessingQueueFactory","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessingqueuefactory","type":"topic","abstract":[{"text":"Factory class providing different instances of","type":"text"},{"code":"NSOperationQueue","type":"codeVoice"},{"text":" to work on.","type":"text"},{"text":" ","type":"text"},{"text":"There are 2 main queues:","type":"text"}],"title":"SBSDKProcessingQueueFactory","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKProcessingQueueFactory","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessingQueueFactory\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKProcessingQueueFactory"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessingQueueFactory\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessingQueueFactory\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKProcessingQueueFactory"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}