{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/givenNames"},"abstract":[{"text":"Person given names field.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType"]]},"kind":"symbol","metadata":{"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKGenericDocumentCommonFieldType@SBSDKGenericDocumentCommonFieldTypeGivenNames","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenNames"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypeGivenNames","kind":"identifier"}],"role":"symbol","title":"SBSDKGenericDocumentCommonFieldType.givenNames","modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"givenNames","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/givennames"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/givennames"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/givenNames":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/givennames","abstract":[{"type":"text","text":"Person given names field."}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypeGivenNames","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/givenNames","title":"SBSDKGenericDocumentCommonFieldType.givenNames","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"givenNames"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType":{"kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype","role":"symbol","abstract":[{"text":"Common field types.","type":"text"}],"title":"SBSDKGenericDocumentCommonFieldType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKGenericDocumentCommonFieldTypeGivenNames"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentCommonFieldTypeGivenNames","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKGenericDocumentCommonFieldTypeGivenNames","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKGenericDocumentCommonFieldTypeGivenNames","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1givenNames\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentCommonFieldTypeGivenNames","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1givenNames\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType\/title","value":"SBSDKGenericDocumentCommonFieldType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldType"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType\/navigatorTitle"}]}]}