{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/height"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/height"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/height"},"abstract":[{"type":"text","text":"Person height field."}],"sections":[],"kind":"symbol","metadata":{"title":"SBSDKGenericDocumentCommonFieldType.height","externalID":"c:@M@ScanbotSDK@E@SBSDKGenericDocumentCommonFieldType@SBSDKGenericDocumentCommonFieldTypeHeight","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypeHeight","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"height"}],"symbolKind":"case","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType":{"kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype","role":"symbol","abstract":[{"text":"Common field types.","type":"text"}],"title":"SBSDKGenericDocumentCommonFieldType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/height":{"abstract":[{"type":"text","text":"Person height field."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/height","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"height","kind":"identifier"}],"kind":"symbol","title":"SBSDKGenericDocumentCommonFieldType.height","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/height","navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypeHeight","kind":"identifier"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"SBSDKGenericDocumentCommonFieldTypeHeight","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypeHeight","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKGenericDocumentCommonFieldTypeHeight","kind":"identifier"}]}],"kind":"declarations"}},{"value":"SBSDKGenericDocumentCommonFieldType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType\/fragments","value":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1height\/title","value":"SBSDKGenericDocumentCommonFieldTypeHeight","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1height\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeHeight"}]}]}]}