{"kind":"symbol","metadata":{"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKGenericDocumentCommonFieldType@SBSDKGenericDocumentCommonFieldTypeId","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeId"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"}],"title":"SBSDKGenericDocumentCommonFieldType.id","modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/id"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/id"]}],"abstract":[{"text":"Document ID.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/id"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType":{"abstract":[{"type":"text","text":"Common field types."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype","type":"topic","kind":"symbol","title":"SBSDKGenericDocumentCommonFieldType","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldType"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/id":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"}],"abstract":[{"text":"Document ID.","type":"text"}],"role":"symbol","title":"SBSDKGenericDocumentCommonFieldType.id","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/id","navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypeId","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/id","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKGenericDocumentCommonFieldTypeId","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKGenericDocumentCommonFieldTypeId","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKGenericDocumentCommonFieldTypeId","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType\/title","op":"replace","value":"SBSDKGenericDocumentCommonFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldType"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1id\/title","op":"replace","value":"SBSDKGenericDocumentCommonFieldTypeId"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeId"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1id\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}