{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issueDate","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/issueDate"},"abstract":[{"text":"Document issue date field.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/issuedate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/issuedate"]}],"metadata":{"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKGenericDocumentCommonFieldType@SBSDKGenericDocumentCommonFieldTypeIssueDate","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"issueDate","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypeIssueDate","kind":"identifier"}],"symbolKind":"case","role":"symbol","title":"SBSDKGenericDocumentCommonFieldType.issueDate","modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/issueDate":{"title":"SBSDKGenericDocumentCommonFieldType.issueDate","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/issuedate","type":"topic","abstract":[{"text":"Document issue date field.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"issueDate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/issueDate","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeIssueDate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType":{"navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldType"}],"abstract":[{"type":"text","text":"Common field types."}],"type":"topic","title":"SBSDKGenericDocumentCommonFieldType","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKGenericDocumentCommonFieldTypeIssueDate","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeIssueDate"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKGenericDocumentCommonFieldTypeIssueDate","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1issueDate\/title","value":"SBSDKGenericDocumentCommonFieldTypeIssueDate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1issueDate\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeIssueDate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType\/title","value":"SBSDKGenericDocumentCommonFieldType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType\/fragments","op":"replace","value":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}