{"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKGenericDocumentCommonFieldType@SBSDKGenericDocumentCommonFieldTypeSurname","title":"SBSDKGenericDocumentCommonFieldType.surname","modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeSurname"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"surname","kind":"identifier"}]},"abstract":[{"type":"text","text":"Person surname field."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/surname"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/surname"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/surname"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"surname","kind":"identifier"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType/surname":{"type":"topic","abstract":[{"type":"text","text":"Person surname field."}],"title":"SBSDKGenericDocumentCommonFieldType.surname","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType\/surname","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype\/surname","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeSurname"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"surname","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentCommonFieldType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentCommonFieldType","title":"SBSDKGenericDocumentCommonFieldType","abstract":[{"type":"text","text":"Common field types."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentcommonfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKGenericDocumentCommonFieldTypeSurname","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeSurname"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKGenericDocumentCommonFieldTypeSurname","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKGenericDocumentCommonFieldTypeSurname","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1surname\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType~1surname\/fragments","value":[{"text":"SBSDKGenericDocumentCommonFieldTypeSurname","kind":"identifier"}]},{"value":"SBSDKGenericDocumentCommonFieldType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType\/title"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentCommonFieldType\/fragments"}]}]}