{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"birthDateBeforeIssueDate","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKValueSemantics","text":"SBSDKValueSemantics"}],"languages":["swift"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"birthDateBeforeIssueDate"},{"kind":"text","text":": "},{"text":"SBSDKValueSemantics","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKValueSemantics"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSemanticsVerificationReport(py)birthDateBeforeIssueDate","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"birthDateBeforeIssueDate"}],"symbolKind":"property","title":"birthDateBeforeIssueDate","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport"]]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/birthdatebeforeissuedate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/birthdatebeforeissuedate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Result of verification whether the birth date is before the issue date."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/birthDateBeforeIssueDate","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueSemantics":{"abstract":[{"text":"The result of the value semantics verification.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkvaluesemantics","role":"symbol","kind":"symbol","title":"SBSDKValueSemantics","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKValueSemantics"}],"navigatorTitle":[{"text":"SBSDKValueSemantics","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport/birthDateBeforeIssueDate":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/birthdatebeforeissuedate","abstract":[{"type":"text","text":"Result of verification whether the birth date is before the issue date."}],"navigatorTitle":[{"kind":"identifier","text":"birthDateBeforeIssueDate"}],"kind":"symbol","title":"birthDateBeforeIssueDate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/birthDateBeforeIssueDate","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"birthDateBeforeIssueDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKValueSemantics","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKValueSemantics"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport":{"navigatorTitle":[{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKSemanticsVerificationReport"}],"type":"topic","title":"SBSDKSemanticsVerificationReport","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport","abstract":[{"type":"text","text":"Report of the document value semantics verification."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"birthDateBeforeIssueDate","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"birthDateBeforeIssueDate"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKValueSemantics","text":"SBSDKValueSemantics"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthDateBeforeIssueDate"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/title","value":"SBSDKValueSemantics"},{"value":[{"text":"SBSDKValueSemantics","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKValueSemantics"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1birthDateBeforeIssueDate\/title","value":"birthDateBeforeIssueDate"},{"value":[{"kind":"identifier","text":"birthDateBeforeIssueDate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1birthDateBeforeIssueDate\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/title","value":"SBSDKSemanticsVerificationReport","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKSemanticsVerificationReport"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/navigatorTitle","value":[{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}