{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle\/initWithStrokeColor:fillColor:strokeWidth:cornerRadius:","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle(im)initWithStrokeColor:fillColor:strokeWidth:cornerRadius:","title":"initWithStrokeColor:fillColor:strokeWidth:cornerRadius:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStrokeColor:fillColor:strokeWidth:cornerRadius:"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithStrokeColor:fillColor:strokeWidth:cornerRadius:"}],"roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithStrokeColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"strokeColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"fillColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fillColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"strokeWidth:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"strokeWidth"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cornerRadius"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2polygonstyle\/initwithstrokecolor:fillcolor:strokewidth:cornerradius:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PolygonStyle":{"role":"symbol","title":"SBSDKUI2PolygonStyle","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2polygonstyle","abstract":[{"text":"Configuration of the polygon appearance.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PolygonStyle/initWithStrokeColor:fillColor:strokeWidth:cornerRadius:":{"abstract":[],"navigatorTitle":[{"text":"initWithStrokeColor:fillColor:strokeWidth:cornerRadius:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2polygonstyle\/initwithstrokecolor:fillcolor:strokewidth:cornerradius:","title":"initWithStrokeColor:fillColor:strokeWidth:cornerRadius:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithStrokeColor:fillColor:strokeWidth:cornerRadius:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle\/initWithStrokeColor:fillColor:strokeWidth:cornerRadius:","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","url":"\/documentation\/scanbotsdk\/sbsdkui2color","title":"SBSDKUI2Color","abstract":[],"navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2PolygonStyle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PolygonStyle\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2PolygonStyle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PolygonStyle\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PolygonStyle\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2Color","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title"},{"op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle"}]}]}