{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkaesencryptermode\/!=(_:_:)"]}],"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"lhs","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"kind":"internalParam","text":"rhs"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode\/!=(_:_:)"},"metadata":{"modules":[{"name":"ScanbotSDK","relatedModules":["Swift"]}],"role":"symbol","symbolKind":"op","extendedModule":"Swift","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@ScanbotSDK@E@SBSDKAESEncrypterMode","title":"!=(_:_:)","roleHeading":"Operator"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode\/Equatable-Implementations"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESEncrypterMode/Equatable-Implementations":{"type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode\/Equatable-Implementations","kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkaesencryptermode\/equatable-implementations","role":"collectionGroup","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESEncrypterMode/!=(_:_:)":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkaesencryptermode\/!=(_:_:)","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode\/!=(_:_:)","abstract":[],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESEncrypter":{"navigatorTitle":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkaesencrypter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter","abstract":[{"type":"text","text":"ScanbotSDK’s default data encrypter. Provides AES128 and AES 256 encryption to your data."},{"type":"text","text":" "},{"text":"All data is encrypted and decrypted with the same key.","type":"text"},{"text":" ","type":"text"},{"text":"The context being passed to the encrypt\/decrypt methods is ignored.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKAESEncrypter","kind":"identifier"}],"title":"SBSDKAESEncrypter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESEncrypterMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode","title":"SBSDKAESEncrypterMode","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"An enum containing the available encryption modes for the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter","type":"reference","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKAESEncrypterMode"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKAESEncrypterMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkaesencryptermode"}},"variantOverrides":[{"patch":[{"value":"SBSDKAESEncrypter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/fragments","value":[{"kind":"identifier","text":"SBSDKAESEncrypter"}]},{"op":"replace","value":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/navigatorTitle"},{"op":"replace","value":"SBSDKAESEncrypterMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypterMode\/title"},{"value":[{"kind":"identifier","text":"SBSDKAESEncrypterMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypterMode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypterMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKAESEncrypterMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}