{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The serial text processing queue.","type":"text"},{"text":" ","type":"text"},{"text":"If you perform additonal tasks that consume a lot of CPU power you should consider using this queue.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Otherwise text processing operations can take a very long time."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingQueueFactory"]]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkprocessingqueuefactory\/serialtextprocessingqueue"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkprocessingqueuefactory\/serialtextprocessingqueue"]}],"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"serialTextProcessingQueue","kind":"identifier"},{"kind":"text","text":": "},{"text":"DispatchQueue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKProcessingQueueFactory(cpy)serialTextProcessingQueue","navigatorTitle":[{"kind":"identifier","text":"serialTextProcessingQueue"}],"role":"symbol","title":"serialTextProcessingQueue","roleHeading":"Type Property"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingQueueFactory\/serialTextProcessingQueue","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"serialTextProcessingQueue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessingQueueFactory":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingQueueFactory","role":"symbol","abstract":[{"text":"Factory class providing different instances of","type":"text"},{"type":"codeVoice","code":"NSOperationQueue"},{"type":"text","text":" to work on."},{"type":"text","text":" "},{"type":"text","text":"There are 2 main queues:"}],"title":"SBSDKProcessingQueueFactory","navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessingQueueFactory"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProcessingQueueFactory","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkprocessingqueuefactory"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessingQueueFactory/serialTextProcessingQueue":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingQueueFactory\/serialTextProcessingQueue","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"serialTextProcessingQueue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue","text":"DispatchQueue"}],"abstract":[{"text":"The serial text processing queue.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If you perform additonal tasks that consume a lot of CPU power you should consider using this queue."},{"text":" ","type":"text"},{"type":"text","text":"Otherwise text processing operations can take a very long time."}],"role":"symbol","kind":"symbol","title":"serialTextProcessingQueue","url":"\/documentation\/scanbotsdk\/sbsdkprocessingqueuefactory\/serialtextprocessingqueue","navigatorTitle":[{"text":"serialTextProcessingQueue","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"value":"serialTextProcessingQueue","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"serialTextProcessingQueue","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSObject<OS_dispatch_queue>","preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue"},{"kind":"text","text":" * "},{"kind":"identifier","text":"serialTextProcessingQueue"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingQueueFactory\/title","value":"SBSDKProcessingQueueFactory"},{"value":[{"text":"SBSDKProcessingQueueFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingQueueFactory\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingQueueFactory\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKProcessingQueueFactory"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingQueueFactory~1serialTextProcessingQueue\/title","value":"serialTextProcessingQueue","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingQueueFactory~1serialTextProcessingQueue\/fragments","value":[{"kind":"identifier","text":"serialTextProcessingQueue"}]}]}]}