{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shouldShowStatusBarOnScanningScreens","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotUI\/shouldShowStatusBarOnScanningScreens","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotUI"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)ScanbotUI(cpy)shouldShowStatusBarOnScanningScreens","role":"symbol","navigatorTitle":[{"text":"shouldShowStatusBarOnScanningScreens","kind":"identifier"}],"roleHeading":"Type Property","modules":[{"name":"ScanbotSDK"}],"title":"shouldShowStatusBarOnScanningScreens","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldShowStatusBarOnScanningScreens"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"abstract":[{"type":"text","text":"A Boolean value that determines whether the status bar is shown on scanning screens. Defaults to "},{"type":"codeVoice","code":"False"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/scanbotui\/shouldshowstatusbaronscanningscreens"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/scanbotui\/shouldshowstatusbaronscanningscreens"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/ScanbotUI/shouldShowStatusBarOnScanningScreens":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldShowStatusBarOnScanningScreens"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"shouldShowStatusBarOnScanningScreens","url":"\/documentation\/scanbotsdk\/scanbotui\/shouldshowstatusbaronscanningscreens","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotUI\/shouldShowStatusBarOnScanningScreens","navigatorTitle":[{"text":"shouldShowStatusBarOnScanningScreens","kind":"identifier"}],"type":"topic","abstract":[{"text":"A Boolean value that determines whether the status bar is shown on scanning screens. Defaults to ","type":"text"},{"code":"False","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/ScanbotUI":{"role":"symbol","url":"\/documentation\/scanbotsdk\/scanbotui","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanbotUI"}],"navigatorTitle":[{"text":"ScanbotUI","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Helper class to configure the properties of the ScanbotSDK RTU-UI (SBSDKUI) components."}],"kind":"symbol","title":"ScanbotUI","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotUI"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"shouldShowStatusBarOnScanningScreens"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"shouldShowStatusBarOnScanningScreens","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"shouldShowStatusBarOnScanningScreens","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotUI~1shouldShowStatusBarOnScanningScreens\/title","value":"shouldShowStatusBarOnScanningScreens","op":"replace"},{"value":[{"text":"shouldShowStatusBarOnScanningScreens","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotUI~1shouldShowStatusBarOnScanningScreens\/fragments"},{"value":"ScanbotUI","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotUI\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ScanbotUI"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotUI\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}