{"metadata":{"title":"hash","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"identifier","text":"hash"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDefaultContentValidator(py)hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdefaultcontentvalidator\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDefaultContentValidator"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDefaultContentValidator\/hash"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDefaultContentValidator":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDefaultContentValidator","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDefaultContentValidator","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDefaultContentValidator","title":"SBSDKDefaultContentValidator","abstract":[{"type":"text","text":"Default content validator. Accepts only non-empty strings."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdefaultcontentvalidator"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDefaultContentValidator/hash":{"fragments":[{"kind":"identifier","text":"hash"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDefaultContentValidator\/hash","title":"hash","type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkdefaultcontentvalidator\/hash","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDefaultContentValidator\/title","value":"SBSDKDefaultContentValidator"},{"value":[{"kind":"identifier","text":"SBSDKDefaultContentValidator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDefaultContentValidator\/fragments","op":"replace"},{"value":[{"text":"SBSDKDefaultContentValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDefaultContentValidator\/navigatorTitle","op":"replace"}]}]}