{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"valid"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2gs1systemelementvalidationstatus\/valid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2gs1systemelementvalidationstatus\/valid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2GS1SystemElementValidationStatus\/valid","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The GS1 field is valid."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"valid"}],"title":"SBSDKUI2GS1SystemElementValidationStatus.valid","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2GS1SystemElementValidationStatus@SBSDKUI2GS1SystemElementValidationStatusValid","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2GS1SystemElementValidationStatusValid"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2GS1SystemElementValidationStatus"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2GS1SystemElementValidationStatus":{"role":"symbol","title":"SBSDKUI2GS1SystemElementValidationStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2GS1SystemElementValidationStatus"}],"abstract":[{"type":"text","text":"GS1 Element Validation Status"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2GS1SystemElementValidationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2GS1SystemElementValidationStatus"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2gs1systemelementvalidationstatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2GS1SystemElementValidationStatus/valid":{"role":"symbol","title":"SBSDKUI2GS1SystemElementValidationStatus.valid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"valid"}],"abstract":[{"type":"text","text":"The GS1 field is valid."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2GS1SystemElementValidationStatus\/valid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2GS1SystemElementValidationStatusValid"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2gs1systemelementvalidationstatus\/valid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2GS1SystemElementValidationStatusValid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2GS1SystemElementValidationStatusValid"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2GS1SystemElementValidationStatusValid"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2GS1SystemElementValidationStatus\/title","value":"SBSDKUI2GS1SystemElementValidationStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2GS1SystemElementValidationStatus\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2GS1SystemElementValidationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2GS1SystemElementValidationStatus~1valid\/title","value":"SBSDKUI2GS1SystemElementValidationStatusValid"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2GS1SystemElementValidationStatus~1valid\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2GS1SystemElementValidationStatusValid"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}