{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textHintOrientationMismatch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerstatustextconfiguration\/texthintorientationmismatch"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerstatustextconfiguration\/texthintorientationmismatch"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerStatusTextConfiguration\/textHintOrientationMismatch","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textHintOrientationMismatch","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerStatusTextConfiguration(py)textHintOrientationMismatch","symbolKind":"property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","title":"textHintOrientationMismatch","roleHeading":"Instance Property","navigatorTitle":[{"text":"textHintOrientationMismatch","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerStatusTextConfiguration"]]},"sections":[],"abstract":[{"text":"The text being displayed on the user-guidance label, when a document was scanned, but the aspect ratio of the document is inverse to","type":"text"},{"text":" ","type":"text"},{"text":"the cameras aspect ratio.","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerStatusTextConfiguration":{"title":"SBSDKDocumentScannerStatusTextConfiguration","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerStatusTextConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentScannerStatusTextConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerStatusTextConfiguration","abstract":[{"type":"text","text":"Wraps the texts being displayed as the detection status."}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerstatustextconfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerStatusTextConfiguration/textHintOrientationMismatch":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textHintOrientationMismatch","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The text being displayed on the user-guidance label, when a document was scanned, but the aspect ratio of the document is inverse to"},{"type":"text","text":" "},{"type":"text","text":"the cameras aspect ratio."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerstatustextconfiguration\/texthintorientationmismatch","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerStatusTextConfiguration\/textHintOrientationMismatch","navigatorTitle":[{"text":"textHintOrientationMismatch","kind":"identifier"}],"title":"textHintOrientationMismatch"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"textHintOrientationMismatch","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"textHintOrientationMismatch","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"textHintOrientationMismatch"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKDocumentScannerStatusTextConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerStatusTextConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKDocumentScannerStatusTextConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerStatusTextConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentScannerStatusTextConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerStatusTextConfiguration\/navigatorTitle"},{"op":"replace","value":"textHintOrientationMismatch","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerStatusTextConfiguration~1textHintOrientationMismatch\/title"},{"op":"replace","value":[{"kind":"identifier","text":"textHintOrientationMismatch"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerStatusTextConfiguration~1textHintOrientationMismatch\/fragments"}]}]}