{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner"]]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner\/detectbarcodes(on:orientation:in:)-7ue2l"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner\/detectbarcodes(on:orientation:in:)-7ue2l"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner\/detectBarCodes(on:orientation:in:)-7ue2l","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","title":"detectBarCodes(on:orientation:in:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectBarCodes"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier","text":"CMSampleBuffer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"orientation"},{"kind":"text","text":": "},{"text":"AVCaptureVideoOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@AVCaptureVideoOrientation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerResult","text":"SBSDKBarcodeScannerResult"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"detectBarCodesOnSampleBuffer:orientation:inRect:"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScanner(im)detectBarCodesOnSampleBuffer:orientation:inRect:","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(detectBarCodesOnSampleBuffer:orientation:inRect:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectBarCodes"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":" ","kind":"text"},{"text":"sampleBuffer","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"orientation"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"videoOrientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureVideoOrientation","preciseIdentifier":"c:@E@AVCaptureVideoOrientation"},{"kind":"text","text":", "},{"text":"in","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"rect","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> ["},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerResult","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerResult","kind":"typeIdentifier","text":"SBSDKBarcodeScannerResult"},{"kind":"text","text":"]?"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The sample buffer reference."}]}],"name":"sampleBuffer"},{"name":"videoOrientation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Video frame orientation. Should be the orientation that the device currently has, not actual image orientation."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Rectangle in image coordinates in which to perform the search. Must be inside the image.","type":"text"}]}],"name":"rect"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"List of found barcodes."}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"This function is intended to be used with live detection."},{"type":"text","text":" "},{"type":"text","text":"Video stream from device returns a rotated image, so for example for portrait device orientation, every frame returned will be in landscape left orientation."},{"type":"text","text":" "},{"type":"text","text":"This function handles these orientation differences, so you shouldn’t fix or rotate the input buffer."},{"text":" ","type":"text"},{"text":"Keep in mind, that the buffer received from the video stream is handled by the system. So in some cases it might be cleaned or changed by the system","type":"text"},{"type":"text","text":" "},{"type":"text","text":"before recognition occurs. You may convert the buffer to UIImage upon receiving it and use "},{"type":"codeVoice","code":"detectBarCodesOnImage:orientation:inRect:"},{"type":"text","text":" "},{"type":"text","text":"function, if that is an issue."}],"type":"paragraph"}]}],"abstract":[{"text":"Search and decode specified types of barcodes from sample buffer reference.","type":"text"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanner":{"navigatorTitle":[{"text":"SBSDKBarcodeScanner","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Creates an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner"},{"text":" with no frame accumulator for detecting all supported barcode types.","type":"text"}],"role":"symbol","title":"SBSDKBarcodeScanner","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScanner","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.1"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanner/detectBarCodes(on:orientation:in:)-7ue2l":{"abstract":[{"type":"text","text":"Search and decode specified types of barcodes from sample buffer reference."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner\/detectBarCodes(on:orientation:in:)-7ue2l","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner\/detectbarcodes(on:orientation:in:)-7ue2l","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectBarCodes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AVCaptureVideoOrientation","text":"AVCaptureVideoOrientation"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerResult","text":"SBSDKBarcodeScannerResult","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"title":"detectBarCodes(on:orientation:in:)","kind":"symbol","navigatorTitle":[{"text":"detectBarCodesOnSampleBuffer:orientation:inRect:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerResult":{"abstract":[{"type":"text","text":"This class encapsulates the result of a barcode detection."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerResult","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerresult","title":"SBSDKBarcodeScannerResult","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"detectBarCodesOnSampleBuffer:orientation:inRect:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"detectBarCodesOnSampleBuffer:orientation:inRect:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"NSArray<SBSDKBarcodeScannerResult *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"detectBarCodesOnSampleBuffer:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@opaqueCMSampleBuffer","text":"opaqueCMSampleBuffer"},{"text":" *) ","kind":"text"},{"text":"sampleBuffer","kind":"internalParam"},{"kind":"text","text":" "},{"text":"orientation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVCaptureVideoOrientation","preciseIdentifier":"c:@E@AVCaptureVideoOrientation","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"videoOrientation","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inRect:"},{"kind":"text","text":"("},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"rect"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"sampleBuffer","content":[{"inlineContent":[{"type":"text","text":"The sample buffer reference."}],"type":"paragraph"}]},{"name":"videoOrientation","content":[{"type":"paragraph","inlineContent":[{"text":"Video frame orientation. Should be the orientation that the device currently has, not actual image orientation.","type":"text"}]}]},{"name":"rect","content":[{"inlineContent":[{"text":"Rectangle in image coordinates in which to perform the search. Must be inside the image.","type":"text"}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"List of found barcodes."}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner\/title","value":"SBSDKBarcodeScanner","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScanner"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScanner"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner~1detectBarCodes(on:orientation:in:)-7ue2l\/title","value":"detectBarCodesOnSampleBuffer:orientation:inRect:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner~1detectBarCodes(on:orientation:in:)-7ue2l\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"detectBarCodesOnSampleBuffer:orientation:inRect:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerResult\/title","value":"SBSDKBarcodeScannerResult"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerResult\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerResult\/navigatorTitle","value":[{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}