{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner\/extensionfilter"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner\/extensionfilter"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScanner(py)extensionFilter","title":"extensionFilter","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"extensionFilter","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extensionFilter"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodesExtensionFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodesExtensionFilter"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Filter for extended EAN and UPC barcodes.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner\/extensionFilter","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extensionFilter","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodesExtensionFilter","text":"SBSDKBarcodesExtensionFilter","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodesExtensionFilter","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"By default the filter is disabled ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodesExtensionFilter\/noFilter","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodesExtensionFilter":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodesExtensionFilter","kind":"symbol","role":"symbol","title":"SBSDKBarcodesExtensionFilter","abstract":[{"text":"Filter for extended EAN and UPC barcodes.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodesextensionfilter","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodesExtensionFilter","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilter"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodesExtensionFilter/noFilter":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodesExtensionFilter\/noFilter","abstract":[{"type":"text","text":"EAN and UPC barcoded with or without extensions will be returned."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"noFilter","kind":"identifier"}],"title":"SBSDKBarcodesExtensionFilter.noFilter","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodesextensionfilter\/nofilter","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilterNoFilter"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanner/extensionFilter":{"title":"extensionFilter","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner\/extensionFilter","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner\/extensionfilter","navigatorTitle":[{"kind":"identifier","text":"extensionFilter"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extensionFilter"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodesExtensionFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodesExtensionFilter"}],"abstract":[{"text":"Filter for extended EAN and UPC barcodes.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanner":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScanner","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Creates an "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner","isActive":true},{"type":"text","text":" with no frame accumulator for detecting all supported barcode types."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScanner"}],"title":"SBSDKBarcodeScanner","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 6.1.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"extensionFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"extensionFilter","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodesExtensionFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodesExtensionFilter","text":"SBSDKBarcodesExtensionFilter"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensionFilter"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodesExtensionFilter\/title","value":"SBSDKBarcodesExtensionFilter","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodesExtensionFilter\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodesExtensionFilter\/navigatorTitle"},{"value":"SBSDKBarcodesExtensionFilterNoFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodesExtensionFilter~1noFilter\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodesExtensionFilter~1noFilter\/fragments","value":[{"text":"SBSDKBarcodesExtensionFilterNoFilter","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"extensionFilter","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner~1extensionFilter\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner~1extensionFilter\/fragments","value":[{"kind":"identifier","text":"extensionFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner\/title","op":"replace","value":"SBSDKBarcodeScanner"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeScanner","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKBarcodeScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner\/navigatorTitle"}]}]}