{"abstract":[{"type":"text","text":"Creates an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner"},{"text":" that accumulates multiple frames before returning a detection result.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWithTypes:liveMode:) "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"types","kind":"externalParam"},{"kind":"text","text":" "},{"text":"barCodeTypes","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"SBSDKBarcodeType","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeType"},{"text":"], ","kind":"text"},{"text":"liveMode","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"useLiveMode","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Barcode types to limit detection results to.","type":"text"}],"type":"paragraph"}],"name":"barCodeTypes"},{"content":[{"inlineContent":[{"text":"Whether you want to recognize in live mode or not.","type":"text"}],"type":"paragraph"}],"name":"useLiveMode"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"inlineContent":[{"type":"text","text":"The barcode scanner’s detect methods will return empty results until they’ve been called the"},{"text":" ","type":"text"},{"type":"text","text":"given number of times. Then, they will perform detection on the frame with the least"},{"type":"text","text":" "},{"type":"text","text":"amount of blur. Intended for using with live detection."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner\/init(types:livemode:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner\/init(types:livemode:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner\/init(types:liveMode:)","interfaceLanguage":"swift"},"metadata":{"title":"init(types:liveMode:)","navigatorTitle":[{"kind":"identifier","text":"initWithTypes:liveMode:"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"types","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeType","text":"SBSDKBarcodeType"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"liveMode"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScanner(im)initWithTypes:liveMode:"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 6.1.0"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanner":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScanner","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Creates an "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner","isActive":true},{"type":"text","text":" with no frame accumulator for detecting all supported barcode types."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScanner"}],"title":"SBSDKBarcodeScanner","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeType":{"title":"SBSDKBarcodeType","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetype","kind":"symbol","type":"topic","abstract":[{"text":"Class that represents a barcode type.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeType"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeType"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanner/init(types:liveMode:)":{"navigatorTitle":[{"text":"initWithTypes:liveMode:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Creates an ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner","isActive":true,"type":"reference"},{"type":"text","text":" that accumulates multiple frames before returning a detection result."}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"types"},{"text":": [","kind":"text"},{"text":"SBSDKBarcodeType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeType","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"liveMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"init(types:liveMode:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner\/init(types:liveMode:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner\/init(types:livemode:)","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithTypes:liveMode:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithTypes:liveMode:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithTypes:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<SBSDKBarcodeType *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"barCodeTypes"},{"text":" ","kind":"text"},{"text":"liveMode:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"useLiveMode","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":{"kind":"parameters","parameters":[{"name":"barCodeTypes","content":[{"inlineContent":[{"type":"text","text":"Barcode types to limit detection results to."}],"type":"paragraph"}]},{"name":"useLiveMode","content":[{"type":"paragraph","inlineContent":[{"text":"Whether you want to recognize in live mode or not.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner\/title","value":"SBSDKBarcodeScanner","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeScanner","kind":"identifier"}]},{"value":[{"text":"SBSDKBarcodeScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner\/navigatorTitle","op":"replace"},{"value":"SBSDKBarcodeType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeType\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeType\/fragments","value":[{"text":"SBSDKBarcodeType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKBarcodeType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeType\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner~1init(types:liveMode:)\/title","op":"replace","value":"initWithTypes:liveMode:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTypes:liveMode:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner~1init(types:liveMode:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}