{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProfile","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageProfile","text":"SBSDKImageProfile"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofile\/imageinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofile\/imageinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfile\/imageInfo"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfile"]]},"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"imageInfo"}],"role":"symbol","title":"imageInfo","symbolKind":"property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefProfile(py)imageInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageProfile","kind":"typeIdentifier","text":"SBSDKImageProfile"}]},"abstract":[{"type":"text","text":"Image-specific information, e.g. memory consumption."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefProfile":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRefProfile"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRefProfile"}],"abstract":[{"text":"ImageRef profile which provides detailed information about stored object.","type":"text"}],"kind":"symbol","role":"symbol","title":"SBSDKImageRefProfile","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofile","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageProfile":{"navigatorTitle":[{"text":"SBSDKImageProfile","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageProfile","kind":"identifier"}],"title":"SBSDKImageProfile","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProfile","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageprofile","role":"symbol","abstract":[{"text":"ImageRef profile part specific to image information.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefProfile/imageInfo":{"navigatorTitle":[{"text":"imageInfo","kind":"identifier"}],"title":"imageInfo","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofile\/imageinfo","abstract":[{"text":"Image-specific information, e.g. memory consumption.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfile\/imageInfo","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageInfo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKImageProfile","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageProfile"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"imageInfo","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"imageInfo","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageProfile","text":"SBSDKImageProfile","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProfile"},{"kind":"text","text":" * "},{"kind":"identifier","text":"imageInfo"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKImageRefProfile","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfile\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRefProfile"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfile\/fragments"},{"value":[{"text":"SBSDKImageRefProfile","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfile\/navigatorTitle","op":"replace"},{"value":"SBSDKImageProfile","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProfile\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageProfile"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProfile\/fragments","op":"replace"},{"value":[{"text":"SBSDKImageProfile","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProfile\/navigatorTitle","op":"replace"},{"value":"imageInfo","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfile~1imageInfo\/title","op":"replace"},{"value":[{"text":"imageInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfile~1imageInfo\/fragments","op":"replace"}]}]}