{"abstract":[{"type":"text","text":"Creates a new user-defined TIFF field with a numeric-type value."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterUserDefinedField\/init(fieldName:fieldTag:numericValue:)"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriteruserdefinedfield\/init(fieldname:fieldtag:numericvalue:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriteruserdefinedfield\/init(fieldname:fieldtag:numericvalue:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriterUserDefinedField(im)initWithFieldName:fieldTag:numericValue:","modules":[{"name":"ScanbotSDK"}],"title":"init(fieldName:fieldTag:numericValue:)","navigatorTitle":[{"text":"initWithFieldName:fieldTag:numericValue:","kind":"identifier"}],"symbolKind":"init","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fieldName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"fieldTag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"numericValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"fieldName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"fieldTag","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"numericValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"fieldName","content":[{"type":"paragraph","inlineContent":[{"text":"The name of the field.","type":"text"}]}]},{"name":"fieldTag","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The tag of the field."}]}]},{"name":"numericValue","content":[{"inlineContent":[{"text":"The numeric value of the field.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterUserDefinedField"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterUserDefinedField":{"url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriteruserdefinedfield","role":"symbol","title":"SBSDKTIFFImageWriterUserDefinedField","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterUserDefinedField"}],"abstract":[{"type":"text","text":"A class used to describe a user-defined TIFF field."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFImageWriterUserDefinedField"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterUserDefinedField","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterUserDefinedField/init(fieldName:fieldTag:numericValue:)":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterUserDefinedField\/init(fieldName:fieldTag:numericValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fieldName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"fieldTag","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"numericValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriteruserdefinedfield\/init(fieldname:fieldtag:numericvalue:)","kind":"symbol","abstract":[{"type":"text","text":"Creates a new user-defined TIFF field with a numeric-type value."}],"title":"init(fieldName:fieldTag:numericValue:)","navigatorTitle":[{"text":"initWithFieldName:fieldTag:numericValue:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithFieldName:fieldTag:numericValue:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFieldName:fieldTag:numericValue:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithFieldName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"fieldName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fieldTag:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"fieldTag","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"numericValue:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" *) ","kind":"text"},{"text":"numericValue","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name of the field."}]}],"name":"fieldName"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The tag of the field.","type":"text"}]}],"name":"fieldTag"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The numeric value of the field.","type":"text"}]}],"name":"numericValue"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"SBSDKTIFFImageWriterUserDefinedField","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedField\/title","op":"replace"},{"value":[{"text":"SBSDKTIFFImageWriterUserDefinedField","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedField\/fragments","op":"replace"},{"value":[{"text":"SBSDKTIFFImageWriterUserDefinedField","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedField\/navigatorTitle","op":"replace"},{"value":"initWithFieldName:fieldTag:numericValue:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedField~1init(fieldName:fieldTag:numericValue:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFieldName:fieldTag:numericValue:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterUserDefinedField~1init(fieldName:fieldTag:numericValue:)\/fragments","op":"replace"}]}]}