{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/legal","interfaceLanguage":"swift"},"abstract":[{"text":"8.5 x 14 (inches)        612 x 1008 (pixels) at 72 DPI.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagesize\/legal"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagesize\/legal"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"legal"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"legal","kind":"identifier"}],"title":"SBSDKPageSize.legal","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"SBSDKPageSizeLegal","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKPageSize@SBSDKPageSizeLegal"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize","url":"\/documentation\/scanbotsdk\/sbsdkpagesize","kind":"symbol","title":"SBSDKPageSize","navigatorTitle":[{"text":"SBSDKPageSize","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPageSize","kind":"identifier"}],"abstract":[{"type":"text","text":"Page size."}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/legal":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"legal","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKPageSizeLegal","kind":"identifier"}],"abstract":[{"type":"text","text":"8.5 x 14 (inches)        612 x 1008 (pixels) at 72 DPI."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/legal","url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/legal","role":"symbol","title":"SBSDKPageSize.legal","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKPageSizeLegal","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKPageSizeLegal"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKPageSizeLegal","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/title","value":"SBSDKPageSize"},{"value":[{"kind":"identifier","text":"SBSDKPageSize"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/fragments","op":"replace"},{"value":[{"text":"SBSDKPageSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/navigatorTitle"},{"value":"SBSDKPageSizeLegal","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1legal\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1legal\/fragments","value":[{"text":"SBSDKPageSizeLegal","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}