{"abstract":[{"type":"text","text":"Initialize the MRZ scanner."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerConfiguration","text":"SBSDKMRZScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKMRZScannerConfiguration(  )) "},{"kind":"keyword","text":"throws"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The configuration to use for the scanner.","type":"text"}],"type":"paragraph"}],"name":"configuration"}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"name":"Throws","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKError"},{"type":"text","text":" in case of an error."}],"type":"paragraph"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscanner\/init(configuration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscanner\/init(configuration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/init(configuration:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScanner(im)initWithConfiguration:error:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerConfiguration","text":"SBSDKMRZScannerConfiguration","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"initWithConfiguration:error:","kind":"identifier"}],"title":"init(configuration:)","symbolKind":"init","roleHeading":"Initializer","role":"symbol","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScanner":{"title":"SBSDKMRZScanner","url":"\/documentation\/scanbotsdk\/sbsdkmrzscanner","kind":"symbol","type":"topic","abstract":[{"text":"API for machine readable zone scanning.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZScanner"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZScanner"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKError":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKError"}],"title":"SBSDKError","url":"\/documentation\/scanbotsdk\/sbsdkerror","abstract":[{"type":"text","text":"Represents errors that can occur within the Scanbot SDK."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKError","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKError"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerConfiguration","title":"SBSDKMRZScannerConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerconfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZScannerConfiguration"}],"abstract":[{"type":"text","text":"Configuration for MRZ scanner."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZScannerConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScanner/init(configuration:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerConfiguration","kind":"typeIdentifier","text":"SBSDKMRZScannerConfiguration"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"text":"Initialize the MRZ scanner.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScanner\/init(configuration:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:error:"}],"title":"init(configuration:)","url":"\/documentation\/scanbotsdk\/sbsdkmrzscanner\/init(configuration:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithConfiguration:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:error:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKMRZScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"configuration","content":[{"inlineContent":[{"text":"The configuration to use for the scanner.","type":"text"}],"type":"paragraph"}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" for this parameter."}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":"SBSDKMRZScanner","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner\/title"},{"op":"replace","value":[{"text":"SBSDKMRZScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner\/fragments"},{"op":"replace","value":[{"text":"SBSDKMRZScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner\/navigatorTitle"},{"op":"replace","value":"SBSDKMRZScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKMRZScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKMRZScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerConfiguration\/navigatorTitle"},{"op":"replace","value":"initWithConfiguration:error:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1init(configuration:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:error:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScanner~1init(configuration:)\/fragments"}]}]}