{"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"isReadyForNextFrame","kind":"identifier"}],"title":"isReadyForNextFrame()","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKFrameLimiter(im)isReadyForNextFrame","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isReadyForNextFrame","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkframelimiter\/isreadyfornextframe()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkframelimiter\/isreadyfornextframe()"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFrameLimiter"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isReadyForNextFrame"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"True"},{"type":"text","text":", if since the last call enough time passed by to process the next frame, "},{"type":"codeVoice","code":"False"},{"text":" otherwise.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFrameLimiter\/isReadyForNextFrame()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns wether the next frame should be processed or not. Call this method consecutively each frame and process the frame if the result was "},{"code":"True","type":"codeVoice"},{"type":"text","text":". Otherwise skip the frame processing."}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFrameLimiter":{"title":"SBSDKFrameLimiter","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKFrameLimiter","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKFrameLimiter"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkframelimiter","abstract":[{"text":"A frame limiter class. An object can use this class to limit the number of events fired per second.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFrameLimiter"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFrameLimiter/isReadyForNextFrame()":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkframelimiter\/isreadyfornextframe()","navigatorTitle":[{"text":"isReadyForNextFrame","kind":"identifier"}],"kind":"symbol","title":"isReadyForNextFrame()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isReadyForNextFrame","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns wether the next frame should be processed or not. Call this method consecutively each frame and process the frame if the result was "},{"type":"codeVoice","code":"True"},{"text":". Otherwise skip the frame processing.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFrameLimiter\/isReadyForNextFrame()"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"isReadyForNextFrame","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isReadyForNextFrame"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isReadyForNextFrame","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":""},{"code":"True","type":"codeVoice"},{"text":", if since the last call enough time passed by to process the next frame, ","type":"text"},{"type":"codeVoice","code":"False"},{"text":" otherwise.","type":"text"}],"type":"paragraph"}]},"op":"replace"},{"value":"SBSDKFrameLimiter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFrameLimiter\/title"},{"value":[{"text":"SBSDKFrameLimiter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFrameLimiter\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKFrameLimiter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFrameLimiter\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFrameLimiter~1isReadyForNextFrame()\/title","value":"isReadyForNextFrame"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFrameLimiter~1isReadyForNextFrame()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isReadyForNextFrame"}]}]}]}