{"abstract":[{"type":"text","text":"Barcode extraction is disabled in the configuration."}],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","title":"SBSDKVINBarcodeExtractionStatus.barcodeExtractionDisabled","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeExtractionDisabled"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatusBarcodeExtractionDisabled"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKVINBarcodeExtractionStatus@SBSDKVINBarcodeExtractionStatusBarcodeExtractionDisabled"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus\/barcodeextractiondisabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus\/barcodeextractiondisabled"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeExtractionDisabled","kind":"identifier"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/barcodeExtractionDisabled","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeExtractionStatus":{"abstract":[{"text":"Status of the barcode extraction.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus","navigatorTitle":[{"text":"SBSDKVINBarcodeExtractionStatus","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINBarcodeExtractionStatus","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus","title":"SBSDKVINBarcodeExtractionStatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeExtractionStatus/barcodeExtractionDisabled":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeExtractionDisabled"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/barcodeExtractionDisabled","url":"\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus\/barcodeextractiondisabled","type":"topic","abstract":[{"type":"text","text":"Barcode extraction is disabled in the configuration."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatusBarcodeExtractionDisabled"}],"title":"SBSDKVINBarcodeExtractionStatus.barcodeExtractionDisabled"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKVINBarcodeExtractionStatusBarcodeExtractionDisabled","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatusBarcodeExtractionDisabled"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKVINBarcodeExtractionStatusBarcodeExtractionDisabled","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKVINBarcodeExtractionStatus","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus~1barcodeExtractionDisabled\/title","value":"SBSDKVINBarcodeExtractionStatusBarcodeExtractionDisabled"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus~1barcodeExtractionDisabled\/fragments","value":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatusBarcodeExtractionDisabled"}]}]}]}