{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/observeValue(forKeyPath:of:change:context:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"observeValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forKeyPath","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"keyPath","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"of","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"change","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"NSKeyValueChangeKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSKeyValueChangeKey"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraSession(im)observeValueForKeyPath:ofObject:change:context:","roleHeading":"Instance Method","symbolKind":"method","title":"observeValue(forKeyPath:of:change:context:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"observeValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forKeyPath","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"change","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@T@NSKeyValueChangeKey","text":"NSKeyValueChangeKey","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"observeValueForKeyPath:ofObject:change:context:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcamerasession\/observevalue(forkeypath:of:change:context:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcamerasession\/observevalue(forkeypath:of:change:context:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession":{"title":"SBSDKCameraSession","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSession"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession","type":"topic","abstract":[{"type":"text","text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the"},{"type":"text","text":" "},{"type":"text","text":"camera device and the preview layer. Provides functionality to capture still images."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSession"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/observeValue(forKeyPath:of:change:context:)":{"url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/observevalue(forkeypath:of:change:context:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKeyPath"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"change"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@T@NSKeyValueChangeKey","kind":"typeIdentifier","text":"NSKeyValueChangeKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sv","kind":"typeIdentifier","text":"UnsafeMutableRawPointer"},{"kind":"text","text":"?)"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/observeValue(forKeyPath:of:change:context:)","type":"topic","title":"observeValue(forKeyPath:of:change:context:)","navigatorTitle":[{"kind":"identifier","text":"observeValueForKeyPath:ofObject:change:context:"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"observeValueForKeyPath:ofObject:change:context:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"observeValueForKeyPath:ofObject:change:context:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"observeValueForKeyPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"keyPath"},{"kind":"text","text":" "},{"kind":"identifier","text":"ofObject:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":" "},{"kind":"identifier","text":"change:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"change"},{"kind":"text","text":" "},{"kind":"identifier","text":"context:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"context"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/title","value":"SBSDKCameraSession","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/fragments","value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/navigatorTitle"},{"value":"observeValueForKeyPath:ofObject:change:context:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1observeValue(forKeyPath:of:change:context:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"observeValueForKeyPath:ofObject:change:context:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1observeValue(forKeyPath:of:change:context:)\/fragments"}]}]}