{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentCommonFieldType"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentCommonFieldType\/routingNumber","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"routingNumber","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeRoutingNumber"}],"title":"SBSDKGenericDocumentCommonFieldType.routingNumber","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGenericDocumentCommonFieldType@SBSDKGenericDocumentCommonFieldTypeRoutingNumber","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"routingNumber","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case"},"kind":"symbol","abstract":[{"text":"Check routing number.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentcommonfieldtype\/routingnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentcommonfieldtype\/routingnumber"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentCommonFieldType":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentCommonFieldType","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentcommonfieldtype","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldType"}],"kind":"symbol","abstract":[{"type":"text","text":"Common field types."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldType"}],"title":"SBSDKGenericDocumentCommonFieldType"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentCommonFieldType/routingNumber":{"kind":"symbol","title":"SBSDKGenericDocumentCommonFieldType.routingNumber","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentcommonfieldtype\/routingnumber","role":"symbol","abstract":[{"type":"text","text":"Check routing number."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentCommonFieldType\/routingNumber","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"routingNumber","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentCommonFieldTypeRoutingNumber","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKGenericDocumentCommonFieldTypeRoutingNumber"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentCommonFieldTypeRoutingNumber"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKGenericDocumentCommonFieldTypeRoutingNumber","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentCommonFieldType\/title","value":"SBSDKGenericDocumentCommonFieldType","op":"replace"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentCommonFieldType\/fragments"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentCommonFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentCommonFieldType\/navigatorTitle"},{"value":"SBSDKGenericDocumentCommonFieldTypeRoutingNumber","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentCommonFieldType~1routingNumber\/title"},{"value":[{"text":"SBSDKGenericDocumentCommonFieldTypeRoutingNumber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentCommonFieldType~1routingNumber\/fragments"}]}]}