{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/isequal:"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerScreenConfiguration(im)isEqual:"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/isEqual:","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/isEqual:":{"title":"isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/isEqual:","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/isequal:","role":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration":{"kind":"symbol","title":"SBSDKUI2CreditCardScannerScreenConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardScannerScreenConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CreditCardScannerScreenConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Configuration of the screen for detecting credit card data."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration\/title","op":"replace","value":"SBSDKUI2CreditCardScannerScreenConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CreditCardScannerScreenConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}