{"kind":"article","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountCaptureMode"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountCaptureMode\/!=(_:_:)"],"anchor":"Operators","title":"Operators"}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountCaptureMode\/Equatable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountcapturemode\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"Equatable Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountCaptureMode/!=(_:_:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountCaptureMode\/!=(_:_:)","kind":"symbol","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountcapturemode\/!=(_:_:)","role":"symbol","title":"!=(_:_:)","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.0","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountCaptureMode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScanAndCountCaptureMode"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountCaptureMode","title":"SBSDKBarcodeScanAndCountCaptureMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountCaptureMode"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountcapturemode","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The capture mode of the barcode scan and count."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKBarcodeScanAndCountCaptureMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountCaptureMode\/title"},{"value":[{"text":"SBSDKBarcodeScanAndCountCaptureMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountCaptureMode\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountCaptureMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountCaptureMode\/navigatorTitle"}]}]}