{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/captureStillImage(completion:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Captures a still image asynchronously and passes the image data or an error to the completion handler."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/capturestillimage(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/capturestillimage(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureStillImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerFrame","text":"SBSDKBaseScannerFrame"},{"kind":"text","text":"?, "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ())","kind":"text"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCameraSession(im)captureStillImageWithCompletionHandler:","title":"captureStillImage(completion:)","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"captureStillImageWithCompletionHandler:","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(captureStillImageWithCompletionHandler:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureStillImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerFrame","text":"SBSDKBaseScannerFrame","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ())","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The completion handler."}],"type":"paragraph"}]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/captureStillImage(completion:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/captureStillImage(completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureStillImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerFrame","kind":"typeIdentifier","text":"SBSDKBaseScannerFrame"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> ())"}],"navigatorTitle":[{"kind":"identifier","text":"captureStillImageWithCompletionHandler:"}],"title":"captureStillImage(completion:)","role":"symbol","abstract":[{"type":"text","text":"Captures a still image asynchronously and passes the image data or an error to the completion handler."}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/capturestillimage(completion:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerFrame":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerFrame","kind":"identifier"}],"abstract":[{"text":"A wrapper for a video frame. Can be used with ","type":"text"},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" and "},{"type":"codeVoice","code":"CMSampleBuffer"},{"type":"text","text":"."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKBaseScannerFrame","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerframe","kind":"symbol","title":"SBSDKBaseScannerFrame"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession","title":"SBSDKCameraSession","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSession"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession","abstract":[{"text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the","type":"text"},{"text":" ","type":"text"},{"text":"camera device and the preview layer. Provides functionality to capture still images.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSession"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"captureStillImageWithCompletionHandler:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"captureStillImageWithCompletionHandler:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"captureStillImageWithCompletionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame","text":"SBSDKBaseScannerFrame","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerFrame"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion handler."}]}],"name":"completion"}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1captureStillImage(completion:)\/title","value":"captureStillImageWithCompletionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1captureStillImage(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureStillImageWithCompletionHandler:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame\/title","value":"SBSDKBaseScannerFrame","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame\/fragments","value":[{"kind":"identifier","text":"SBSDKBaseScannerFrame"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame\/navigatorTitle","value":[{"text":"SBSDKBaseScannerFrame","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/title","value":"SBSDKCameraSession","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/fragments","value":[{"text":"SBSDKCameraSession","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKCameraSession"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}