{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}]}]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"hash","kind":"identifier"}],"title":"hash","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"hash","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerIntroScreenConfiguration(py)hash","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerIntroScreenConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerIntroScreenConfiguration\/hash"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerintroscreenconfiguration\/hash"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerIntroScreenConfiguration":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerIntroScreenConfiguration"}],"title":"SBSDKUI2CreditCardScannerIntroScreenConfiguration","abstract":[{"type":"text","text":"Configuration of the introduction screen for the credit card scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerintroscreenconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerIntroScreenConfiguration"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerIntroScreenConfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerIntroScreenConfiguration/hash":{"title":"hash","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerintroscreenconfiguration\/hash","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerIntroScreenConfiguration\/hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerIntroScreenConfiguration\/title","value":"SBSDKUI2CreditCardScannerIntroScreenConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerIntroScreenConfiguration\/fragments","value":[{"text":"SBSDKUI2CreditCardScannerIntroScreenConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerIntroScreenConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerIntroScreenConfiguration"}],"op":"replace"}]}]}