{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}],"type":"paragraph"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmationDialogTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannertextconfiguration\/confirmationdialogtitle"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannertextconfiguration\/confirmationdialogtitle"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerTextConfiguration"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"confirmationDialogTitle"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmationDialogTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"symbolKind":"property","roleHeading":"Instance Property","title":"confirmationDialogTitle","platforms":[],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerTextConfiguration(py)confirmationDialogTitle","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"kind":"symbol","abstract":[{"type":"text","text":"String being displayed as the confirmation dialogs title."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerTextConfiguration\/confirmationDialogTitle"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerTextConfiguration/confirmationDialogTitle":{"title":"confirmationDialogTitle","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerTextConfiguration\/confirmationDialogTitle","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannertextconfiguration\/confirmationdialogtitle","deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmationDialogTitle"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","abstract":[{"type":"text","text":"String being displayed as the confirmation dialogs title."}],"role":"symbol","navigatorTitle":[{"text":"confirmationDialogTitle","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerTextConfiguration":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerTextConfiguration","deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeScannerTextConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerTextConfiguration"}],"title":"SBSDKUIBarcodeScannerTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannertextconfiguration","abstract":[{"type":"text","text":"The configuration for the textual contents of the RTU-UI barcode scanner."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"confirmationDialogTitle","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"confirmationDialogTitle","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"confirmationDialogTitle"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerTextConfiguration~1confirmationDialogTitle\/title","value":"confirmationDialogTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerTextConfiguration~1confirmationDialogTitle\/fragments","op":"replace","value":[{"kind":"identifier","text":"confirmationDialogTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerTextConfiguration\/title","value":"SBSDKUIBarcodeScannerTextConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerTextConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUIBarcodeScannerTextConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerTextConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIBarcodeScannerTextConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}