{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isEqual:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcustombinarizationfilter\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter\/isEqual:"},"metadata":{"title":"isEqual:","symbolKind":"method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCustomBinarizationFilter(im)isEqual:","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCustomBinarizationFilter/isEqual:":{"type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkcustombinarizationfilter\/isequal:","role":"symbol","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter\/isEqual:","title":"isEqual:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCustomBinarizationFilter":{"title":"SBSDKCustomBinarizationFilter","navigatorTitle":[{"text":"SBSDKCustomBinarizationFilter","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcustombinarizationfilter","role":"symbol","abstract":[{"text":"Automatic binarization filter. This filter is a good starting point for most use cases.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCustomBinarizationFilter"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter\/title","value":"SBSDKCustomBinarizationFilter"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKCustomBinarizationFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCustomBinarizationFilter","kind":"identifier"}]}]}]}