{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter\/preset"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Preset of binarization filter parameters that are found to perform well on different types of documents."}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"preset"}],"modules":[{"name":"ScanbotSDK"}],"title":"preset","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"preset","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBinarizationFilterPreset","text":"SBSDKBinarizationFilterPreset","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCustomBinarizationFilter(py)preset"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcustombinarizationfilter\/preset"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcustombinarizationfilter\/preset"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preset"},{"kind":"text","text":": "},{"text":"SBSDKBinarizationFilterPreset","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarizationFilterPreset","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBinarizationFilterPreset"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is PRESET_4","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBinarizationFilterPreset":{"kind":"symbol","title":"SBSDKBinarizationFilterPreset","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarizationFilterPreset","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}],"abstract":[{"type":"text","text":"Preset of parameters for custom binarization filter."}],"url":"\/documentation\/scanbotsdk\/sbsdkbinarizationfilterpreset"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCustomBinarizationFilter":{"title":"SBSDKCustomBinarizationFilter","navigatorTitle":[{"text":"SBSDKCustomBinarizationFilter","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcustombinarizationfilter","role":"symbol","abstract":[{"text":"Automatic binarization filter. This filter is a good starting point for most use cases.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCustomBinarizationFilter"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCustomBinarizationFilter/preset":{"abstract":[{"text":"Preset of binarization filter parameters that are found to perform well on different types of documents.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter\/preset","navigatorTitle":[{"kind":"identifier","text":"preset"}],"title":"preset","url":"\/documentation\/scanbotsdk\/sbsdkcustombinarizationfilter\/preset","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preset"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBinarizationFilterPreset","text":"SBSDKBinarizationFilterPreset"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"preset"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"preset","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBinarizationFilterPreset","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarizationFilterPreset","text":"SBSDKBinarizationFilterPreset","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"preset","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarizationFilterPreset\/title","value":"SBSDKBinarizationFilterPreset"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarizationFilterPreset\/fragments","value":[{"kind":"identifier","text":"SBSDKBinarizationFilterPreset"}]},{"value":[{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarizationFilterPreset\/navigatorTitle","op":"replace"},{"value":"SBSDKCustomBinarizationFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKCustomBinarizationFilter"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter\/navigatorTitle","value":[{"text":"SBSDKCustomBinarizationFilter","kind":"identifier"}],"op":"replace"},{"value":"preset","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter~1preset\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"preset"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter~1preset\/fragments"}]}]}