{"metadata":{"symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"small","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKUI2CollapsedVisibleHeight.small","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeightSmall"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKUI2CollapsedVisibleHeight@SBSDKUI2CollapsedVisibleHeightSmall"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2collapsedvisibleheight\/small"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2collapsedvisibleheight\/small"]}],"abstract":[{"type":"text","text":"Result sheet is collapsed as much as possible, showing only the top part."}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CollapsedVisibleHeight"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"small","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CollapsedVisibleHeight\/small"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CollapsedVisibleHeight/small":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"small","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CollapsedVisibleHeight\/small","type":"topic","title":"SBSDKUI2CollapsedVisibleHeight.small","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeightSmall"}],"abstract":[{"text":"Result sheet is collapsed as much as possible, showing only the top part.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2collapsedvisibleheight\/small","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CollapsedVisibleHeight":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeight"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2collapsedvisibleheight","title":"SBSDKUI2CollapsedVisibleHeight","navigatorTitle":[{"text":"SBSDKUI2CollapsedVisibleHeight","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CollapsedVisibleHeight","kind":"symbol","abstract":[{"text":"Configuration of the barcodes result sheet’s height while collapsed.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2CollapsedVisibleHeightSmall"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeightSmall"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeightSmall"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CollapsedVisibleHeight~1small\/title","value":"SBSDKUI2CollapsedVisibleHeightSmall","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CollapsedVisibleHeight~1small\/fragments","op":"replace","value":[{"text":"SBSDKUI2CollapsedVisibleHeightSmall","kind":"identifier"}]},{"value":"SBSDKUI2CollapsedVisibleHeight","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CollapsedVisibleHeight\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CollapsedVisibleHeight\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeight"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CollapsedVisibleHeight\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CollapsedVisibleHeight","kind":"identifier"}]}]}]}