{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWhiteBlackPointFilter\/hash"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkwhiteblackpointfilter\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWhiteBlackPointFilter"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"hash","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"hash"}],"roleHeading":"Instance Property","role":"symbol","title":"hash","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKWhiteBlackPointFilter(py)hash","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWhiteBlackPointFilter":{"type":"topic","abstract":[{"text":"Maps image value channel so that all the pixels darker than the black point are set to 0,","type":"text"},{"text":" ","type":"text"},{"text":"all the pixels brighter than the white point are set to 255, and the pixels in between","type":"text"},{"text":" ","type":"text"},{"text":"are linearly scaled.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWhiteBlackPointFilter","title":"SBSDKWhiteBlackPointFilter","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkwhiteblackpointfilter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKWhiteBlackPointFilter","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKWhiteBlackPointFilter","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWhiteBlackPointFilter/hash":{"kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/scanbotsdk\/sbsdkwhiteblackpointfilter\/hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWhiteBlackPointFilter\/hash","role":"symbol","title":"hash"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWhiteBlackPointFilter\/title","value":"SBSDKWhiteBlackPointFilter","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWhiteBlackPointFilter\/fragments","value":[{"text":"SBSDKWhiteBlackPointFilter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWhiteBlackPointFilter\/navigatorTitle","value":[{"text":"SBSDKWhiteBlackPointFilter","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}