{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWhiteBlackPointFilter\/initWithBlackPoint:whitePoint:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWhiteBlackPointFilter"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkwhiteblackpointfilter\/initwithblackpoint:whitepoint:"]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKWhiteBlackPointFilter(im)initWithBlackPoint:whitePoint:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithBlackPoint:whitePoint:","kind":"identifier"}],"title":"initWithBlackPoint:whitePoint:","role":"symbol","navigatorTitle":[{"text":"initWithBlackPoint:whitePoint:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBlackPoint:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"blackPoint"},{"kind":"text","text":" "},{"kind":"identifier","text":"whitePoint:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"whitePoint"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWhiteBlackPointFilter/initWithBlackPoint:whitePoint:":{"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBlackPoint:whitePoint:"}],"title":"initWithBlackPoint:whitePoint:","url":"\/documentation\/scanbotsdk\/sbsdkwhiteblackpointfilter\/initwithblackpoint:whitepoint:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWhiteBlackPointFilter\/initWithBlackPoint:whitePoint:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBlackPoint:whitePoint:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWhiteBlackPointFilter":{"type":"topic","abstract":[{"text":"Maps image value channel so that all the pixels darker than the black point are set to 0,","type":"text"},{"text":" ","type":"text"},{"text":"all the pixels brighter than the white point are set to 255, and the pixels in between","type":"text"},{"text":" ","type":"text"},{"text":"are linearly scaled.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWhiteBlackPointFilter","title":"SBSDKWhiteBlackPointFilter","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkwhiteblackpointfilter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKWhiteBlackPointFilter","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKWhiteBlackPointFilter","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWhiteBlackPointFilter\/title","op":"replace","value":"SBSDKWhiteBlackPointFilter"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWhiteBlackPointFilter\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKWhiteBlackPointFilter"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWhiteBlackPointFilter\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKWhiteBlackPointFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}