{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscanneruiresult\/croppedimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscanneruiresult\/croppedimage"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerUIResult\/croppedImage","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Crop of the check if documentDetectionMode is set to DETECT_AND_CROP_DOCUMENT. Will be non-empty, only if check recognition succeeded.","type":"text"}],"sections":[],"kind":"symbol","metadata":{"title":"croppedImage","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"croppedImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"croppedImage","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerUIResult(py)croppedImage","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerUIResult"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"croppedImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerUIResult":{"url":"\/documentation\/scanbotsdk\/sbsdkui2checkscanneruiresult","abstract":[{"type":"text","text":"Configuration of the check scanner RTU UI result."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CheckScannerUIResult"}],"title":"SBSDKUI2CheckScannerUIResult","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CheckScannerUIResult"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerUIResult","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerUIResult/croppedImage":{"abstract":[{"text":"Crop of the check if documentDetectionMode is set to DETECT_AND_CROP_DOCUMENT. Will be non-empty, only if check recognition succeeded.","type":"text"}],"title":"croppedImage","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"croppedImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"croppedImage","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscanneruiresult\/croppedimage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerUIResult\/croppedImage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef":{"role":"symbol","abstract":[{"type":"text","text":"Image ref class."}],"navigatorTitle":[{"text":"SBSDKImageRef","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRef","kind":"identifier"}],"kind":"symbol","title":"SBSDKImageRef","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","url":"\/documentation\/scanbotsdk\/sbsdkimageref","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"croppedImage","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"croppedImage","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef"},{"kind":"text","text":" * "},{"kind":"identifier","text":"croppedImage"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerUIResult\/title","value":"SBSDKUI2CheckScannerUIResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerUIResult\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CheckScannerUIResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerUIResult\/navigatorTitle","value":[{"text":"SBSDKUI2CheckScannerUIResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerUIResult~1croppedImage\/title","value":"croppedImage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerUIResult~1croppedImage\/fragments","value":[{"text":"croppedImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/title","value":"SBSDKImageRef","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/fragments","value":[{"text":"SBSDKImageRef","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/navigatorTitle","value":[{"text":"SBSDKImageRef","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}