{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Barcode result of the VIN scanner."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerResult"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerResult(py)barcodeResult","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKVINBarcodeResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINBarcodeResult","kind":"typeIdentifier"}],"title":"barcodeResult","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"barcodeResult"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKVINBarcodeResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINBarcodeResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeResult"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerResult\/barcodeResult","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerresult\/barcoderesult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerresult\/barcoderesult"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerResult":{"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerresult","title":"SBSDKVINScannerResult","navigatorTitle":[{"text":"SBSDKVINScannerResult","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINScannerResult","kind":"identifier"}],"abstract":[{"text":"Result of the VIN scanner.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerResult","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeResult":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeResult","url":"\/documentation\/scanbotsdk\/sbsdkvinbarcoderesult","type":"topic","navigatorTitle":[{"text":"SBSDKVINBarcodeResult","kind":"identifier"}],"title":"SBSDKVINBarcodeResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVINBarcodeResult"}],"abstract":[{"type":"text","text":"Result of the barcode scanner."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerResult/barcodeResult":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKVINBarcodeResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINBarcodeResult"}],"navigatorTitle":[{"kind":"identifier","text":"barcodeResult"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerResult\/barcodeResult","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerresult\/barcoderesult","abstract":[{"type":"text","text":"Barcode result of the VIN scanner."}],"title":"barcodeResult"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"barcodeResult"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"barcodeResult"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKVINBarcodeResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINBarcodeResult"},{"text":" * ","kind":"text"},{"text":"barcodeResult","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerResult\/title","op":"replace","value":"SBSDKVINScannerResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerResult\/fragments","op":"replace","value":[{"text":"SBSDKVINScannerResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKVINScannerResult"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult\/title","op":"replace","value":"SBSDKVINBarcodeResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVINBarcodeResult"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult\/navigatorTitle","op":"replace","value":[{"text":"SBSDKVINBarcodeResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerResult~1barcodeResult\/title","op":"replace","value":"barcodeResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerResult~1barcodeResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"barcodeResult"}]}]}]}