{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedDocument"]]},"kind":"symbol","abstract":[{"type":"text","text":"The array of globally unique page identifiers the receiver manages."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pageUuids"},{"text":"() -> [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"An array of page identifiers."}],"type":"paragraph"}]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedDocument(im)pageUuids","title":"pageUuids()","navigatorTitle":[{"text":"pageUuids","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageUuids"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscanneddocument\/pageuuids()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscanneddocument\/pageuuids()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedDocument\/pageUuids()"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedDocument/pageUuids()":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanneddocument\/pageuuids()","type":"topic","title":"pageUuids()","navigatorTitle":[{"kind":"identifier","text":"pageUuids"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pageUuids"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"The array of globally unique page identifiers the receiver manages."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedDocument\/pageUuids()","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedDocument":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKScannedDocument"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanneddocument","title":"SBSDKScannedDocument","navigatorTitle":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedDocument","abstract":[{"type":"text","text":"An automatically persisted, thread-safe and observable document-page model for a document with multiple scanned pages."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"pageUuids","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pageUuids"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"text":"pageUuids","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"An array of page identifiers.","type":"text"}]}],"kind":"content"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedDocument~1pageUuids()\/title","value":"pageUuids","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pageUuids"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedDocument~1pageUuids()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedDocument\/title","value":"SBSDKScannedDocument"},{"value":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedDocument\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedDocument\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKScannedDocument"}],"op":"replace"}]}]}