{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegmentOrientation"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"text":"The edge is oriented horizontally.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"horizontal","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegmentorientation\/horizontal"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegmentorientation\/horizontal"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"SBSDKLineSegmentOrientation.horizontal","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKLineSegmentOrientation@SBSDKLineSegmentOrientationHorizontal","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontal"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLineSegmentOrientationHorizontal"}],"symbolKind":"case","roleHeading":"Case","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegmentOrientation\/horizontal"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegmentOrientation":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKLineSegmentOrientation"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegmentOrientation","title":"SBSDKLineSegmentOrientation","abstract":[{"type":"text","text":"An enum describing the orientation of a polygon edge."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLineSegmentOrientation"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegmentorientation"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegmentOrientation/horizontal":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegmentorientation\/horizontal","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKLineSegmentOrientationHorizontal"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegmentOrientation\/horizontal","title":"SBSDKLineSegmentOrientation.horizontal","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"horizontal"}],"abstract":[{"text":"The edge is oriented horizontally.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKLineSegmentOrientationHorizontal"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"SBSDKLineSegmentOrientationHorizontal","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKLineSegmentOrientationHorizontal","kind":"identifier"}]}]},"op":"replace"},{"value":"SBSDKLineSegmentOrientation","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentOrientation\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentOrientation\/fragments","value":[{"text":"SBSDKLineSegmentOrientation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentOrientation\/navigatorTitle","value":[{"text":"SBSDKLineSegmentOrientation","kind":"identifier"}]},{"op":"replace","value":"SBSDKLineSegmentOrientationHorizontal","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentOrientation~1horizontal\/title"},{"value":[{"kind":"identifier","text":"SBSDKLineSegmentOrientationHorizontal"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentOrientation~1horizontal\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}