{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator"]]},"abstract":[{"text":"Asynchronously converts the images at the given image URLs to a multipage-TIFF file and saves it to the specified URL.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator\/generate(from:to:)-4h3lx"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffgenerator\/generate(from:to:)-4h3lx"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"], ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"roleHeading":"Instance Method","title":"generate(from:to:)","externalID":"s:10ScanbotSDK18SBSDKTIFFGeneratorC8generate4from2to10Foundation3URLVSgSayAIG_AItYaKF","modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@nonobjc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"imageURLs","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"], ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"fileURL","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The array of image URLs to generate the multipage-TIFF from.","type":"text"}]}],"name":"imageURLs"},{"content":[{"inlineContent":[{"type":"text","text":"The file URL to save the TIFF file at."}],"type":"paragraph"}],"name":"fileURL"}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The URL the TIFF file has been written to or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" and an "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" if the operation failed."}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"In Swift language it is used with structured concurrency (async\/await).","type":"text"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/defaultCryptingProvider":{"navigatorTitle":[{"kind":"identifier","text":"defaultCryptingProvider"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultCryptingProvider","role":"symbol","abstract":[{"text":"The SDK-wide encryption provider for storing image data to disk. Defaults to ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":", no encryption used.","type":"text"}],"title":"defaultCryptingProvider","kind":"symbol","url":"\/documentation\/scanbotsdk\/scanbot\/defaultcryptingprovider","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultCryptingProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCryptingProvider","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingProvider"},{"kind":"text","text":"?"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGenerator/generate(from:to:)-4h3lx":{"abstract":[{"type":"text","text":"Asynchronously converts the images at the given image URLs to a multipage-TIFF file and saves it to the specified URL."}],"type":"topic","kind":"symbol","role":"symbol","title":"generate(from:to:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator\/generate(from:to:)-4h3lx","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"], ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffgenerator\/generate(from:to:)-4h3lx"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGenerator":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator","abstract":[{"text":"A class that converts images to (multipage) TIFF images.","type":"text"},{"text":" ","type":"text"},{"text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc.","type":"text"},{"text":" ","type":"text"},{"text":"If ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultCryptingProvider"},{"text":" is set, the generated TIFF files will be encrypted using the specified crypting provider.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffgenerator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"role":"symbol","type":"topic","title":"SBSDKTIFFGenerator","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1defaultCryptingProvider\/title","value":"defaultCryptingProvider","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1defaultCryptingProvider\/fragments","value":[{"kind":"identifier","text":"defaultCryptingProvider"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/title","value":"SBSDKTIFFGenerator","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/fragments","value":[{"text":"SBSDKTIFFGenerator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"op":"replace"}]}]}