{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@nonobjc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"images","kind":"internalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"fileURL","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The array of images to generate the multipage-TIFF from."}],"type":"paragraph"}],"name":"images"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The file URL to save the TIFF file at.","type":"text"}]}],"name":"fileURL"}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"The URL the TIFF file has been written to or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" and an "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" if the operation failed."}],"type":"paragraph"}],"kind":"content"},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"In Swift language it is used with structured concurrency (async\/await).","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktiffgenerator\/generate(from:to:)-4ippv"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Asynchronously converts the given images to a multipage-TIFF file and saves it to the specified URL.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator\/generate(from:to:)-4ippv","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"generate(from:to:)","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Method","externalID":"s:10ScanbotSDK18SBSDKTIFFGeneratorC8generate4from2to10Foundation3URLVSgSayAA13SBSDKImageRefCG_AItYaKF"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef":{"role":"symbol","abstract":[{"type":"text","text":"Image ref class."}],"navigatorTitle":[{"text":"SBSDKImageRef","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRef","kind":"identifier"}],"kind":"symbol","title":"SBSDKImageRef","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","url":"\/documentation\/scanbotsdk\/sbsdkimageref","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGenerator/generate(from:to:)-4ippv":{"type":"topic","title":"generate(from:to:)","url":"\/documentation\/scanbotsdk\/sbsdktiffgenerator\/generate(from:to:)-4ippv","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator\/generate(from:to:)-4ippv","role":"symbol","abstract":[{"type":"text","text":"Asynchronously converts the given images to a multipage-TIFF file and saves it to the specified URL."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGenerator":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKTIFFGenerator","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator","abstract":[{"type":"text","text":"A class that converts images to (multipage) TIFF images."},{"type":"text","text":" "},{"type":"text","text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc."},{"type":"text","text":" "},{"type":"text","text":"If "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultCryptingProvider"},{"type":"text","text":" is set, the generated TIFF files will be encrypted using the specified crypting provider."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffgenerator","title":"SBSDKTIFFGenerator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFGenerator","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/defaultCryptingProvider":{"title":"defaultCryptingProvider","kind":"symbol","navigatorTitle":[{"text":"defaultCryptingProvider","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultCryptingProvider","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultCryptingProvider","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingProvider"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"The SDK-wide encryption provider for storing image data to disk. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", no encryption used."}],"url":"\/documentation\/scanbotsdk\/scanbot\/defaultcryptingprovider","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKImageRef","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/title","op":"replace"},{"value":[{"text":"SBSDKImageRef","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/fragments","op":"replace"},{"value":[{"text":"SBSDKImageRef","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/navigatorTitle","op":"replace"},{"value":"SBSDKTIFFGenerator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/title","op":"replace"},{"value":[{"text":"SBSDKTIFFGenerator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/navigatorTitle"},{"value":"defaultCryptingProvider","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1defaultCryptingProvider\/title","op":"replace"},{"value":[{"kind":"identifier","text":"defaultCryptingProvider"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1defaultCryptingProvider\/fragments","op":"replace"}]}]}