{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageEditingViewControllerDidChangePolygon"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"editingViewController"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"editingViewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The calling "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/imageEditingViewControllerDidChangePolygon(_:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/SBSDKImageEditingViewControllerDelegate-Implementations"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Informs the delegate that the image editing view controllers polygon was changed by user interaction."}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller\/imageeditingviewcontrollerdidchangepolygon(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller\/imageeditingviewcontrollerdidchangepolygon(_:)"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerDidChangePolygon:"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"imageEditingViewControllerDidChangePolygon(_:)","externalID":"c:@CM@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingViewController(im)imageEditingViewControllerDidChangePolygon:","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageEditingViewControllerDidChangePolygon"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingViewController/imageEditingViewControllerDidChangePolygon(_:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/imageEditingViewControllerDidChangePolygon(_:)","title":"imageEditingViewControllerDidChangePolygon(_:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerDidChangePolygon:"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageEditingViewControllerDidChangePolygon"},{"kind":"text","text":"("},{"text":"SBSDKImageEditingViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller\/imageeditingviewcontrollerdidchangepolygon(_:)","abstract":[{"type":"text","text":"Informs the delegate that the image editing view controllers polygon was changed by user interaction."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingViewController":{"title":"SBSDKUI2CroppingViewController","abstract":[{"type":"text","text":"A highly customizable view controller to edit the page polygon or the page orientation."}],"navigatorTitle":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CroppingViewController"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController","type":"topic","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingViewController/SBSDKImageEditingViewControllerDelegate-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController\/SBSDKImageEditingViewControllerDelegate-Implementations","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller\/sbsdkimageeditingviewcontrollerdelegate-implementations","title":"SBSDKImageEditingViewControllerDelegate Implementations","abstract":[],"kind":"article","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewController":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to show and edit an image.","type":"text"}],"kind":"symbol","title":"SBSDKImageEditingViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","navigatorTitle":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"imageEditingViewControllerDidChangePolygon:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"imageEditingViewControllerDidChangePolygon:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"imageEditingViewControllerDidChangePolygon:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","kind":"typeIdentifier","text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"editingViewController"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"imageEditingViewControllerDidChangePolygon:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController~1imageEditingViewControllerDidChangePolygon(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerDidChangePolygon:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController~1imageEditingViewControllerDidChangePolygon(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController\/title","value":"SBSDKUI2CroppingViewController"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CroppingViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController\/fragments"},{"value":"SBSDKImageEditingViewController","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/title","op":"replace"},{"value":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/fragments","op":"replace"}]}]}