{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"oneDConfirmationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOneDConfirmationMode","text":"SBSDKOneDConfirmationMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOneDConfirmationMode"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"text":"Default is THOROUGH","type":"text"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonconfiguration\/onedconfirmationmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonconfiguration\/onedconfirmationmode"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonConfiguration\/oneDConfirmationMode","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonConfiguration"]]},"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCommonConfiguration(py)oneDConfirmationMode","navigatorTitle":[{"text":"oneDConfirmationMode","kind":"identifier"}],"title":"oneDConfirmationMode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"oneDConfirmationMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKOneDConfirmationMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOneDConfirmationMode","kind":"typeIdentifier"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol"},"abstract":[{"text":"Allows to select the balance between result accuracy (precision) and missed barcodes (recall) for linear barcodes.","type":"text"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonConfiguration/oneDConfirmationMode":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonconfiguration\/onedconfirmationmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonConfiguration\/oneDConfirmationMode","abstract":[{"type":"text","text":"Allows to select the balance between result accuracy (precision) and missed barcodes (recall) for linear barcodes."}],"role":"symbol","kind":"symbol","type":"topic","title":"oneDConfirmationMode","navigatorTitle":[{"text":"oneDConfirmationMode","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"oneDConfirmationMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOneDConfirmationMode","text":"SBSDKOneDConfirmationMode","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonConfiguration":{"abstract":[{"type":"text","text":"Convenience configuration for enabling the scanning of multiple barcode formats with a common configuration."},{"type":"text","text":" "},{"type":"text","text":"Add to scanner configuration to enable and configure the scanning of multiple barcodes."}],"title":"SBSDKBarcodeFormatCommonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCommonConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonconfiguration","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeFormatCommonConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOneDConfirmationMode":{"title":"SBSDKOneDConfirmationMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKOneDConfirmationMode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOneDConfirmationMode"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOneDConfirmationMode","type":"topic","abstract":[{"type":"text","text":"Allows to select the balance between result accuracy (precision) and missed barcodes (recall) for linear barcodes."},{"type":"text","text":" "},{"type":"text","text":"Some barcode types are naturally prone to false positives (e.g. MSI Plessey)."},{"type":"text","text":" "},{"type":"text","text":"For those barcode types false positives can be drastically reduced (precision can be increased) by requiring that multiple scan-lines in the input scan to the same result."},{"type":"text","text":" "},{"type":"text","text":"However, this stronger condition can lead to missed barcodes (lower recall)."},{"type":"text","text":" "},{"type":"text","text":"Confirmation is avoided for barcode types, which are by design resistant to false positives, (e.g. Code128) to maximize recall."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkonedconfirmationmode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"oneDConfirmationMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"oneDConfirmationMode","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOneDConfirmationMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOneDConfirmationMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOneDConfirmationMode","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"oneDConfirmationMode","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"oneDConfirmationMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonConfiguration~1oneDConfirmationMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"oneDConfirmationMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonConfiguration~1oneDConfirmationMode\/fragments"},{"op":"replace","value":"SBSDKBarcodeFormatCommonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKBarcodeFormatCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKOneDConfirmationMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOneDConfirmationMode\/title"},{"op":"replace","value":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOneDConfirmationMode\/fragments"},{"op":"replace","value":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOneDConfirmationMode\/navigatorTitle"}]}]}