{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScanningProgressConfiguration(im)isEqual:","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"title":"isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanningProgressConfiguration\/isEqual:","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanningProgressConfiguration"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscanningprogressconfiguration\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanningProgressConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanningProgressConfiguration","kind":"symbol","title":"SBSDKUI2CreditCardScanningProgressConfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CreditCardScanningProgressConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanningprogressconfiguration","abstract":[{"text":"Configuration of visualization of the scanning progress - indeterminate progress.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScanningProgressConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 7.1.0","type":"text"}],"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanningProgressConfiguration/isEqual:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanningprogressconfiguration\/isequal:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanningProgressConfiguration\/isEqual:","kind":"symbol","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2CreditCardScanningProgressConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanningProgressConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanningProgressConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScanningProgressConfiguration"}]},{"value":[{"text":"SBSDKUI2CreditCardScanningProgressConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanningProgressConfiguration\/navigatorTitle","op":"replace"}]}]}