{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration\/initwithallowpartiallyvisibledocuments:accumulationduration:retentiontime:minimumbrightness:"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration"]]},"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","navigatorTitle":[{"kind":"identifier","text":"initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPartiallyVisibleDocumentConfiguration(im)initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","roleHeading":"Instance Method","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithAllowPartiallyVisibleDocuments:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"allowPartiallyVisibleDocuments","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accumulationDuration:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"accumulationDuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"retentionTime:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"retentionTime","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumBrightness:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"minimumBrightness","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration","role":"symbol","title":"SBSDKPartiallyVisibleDocumentConfiguration","abstract":[{"text":"Configuration for handling partially visible documents.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration/initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:":{"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","kind":"identifier"}],"abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration\/initwithallowpartiallyvisibledocuments:accumulationduration:retentiontime:minimumbrightness:","title":"initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/title","value":"SBSDKPartiallyVisibleDocumentConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/fragments","value":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}],"op":"replace"}]}]}