{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentPreview","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPageImageTypeDocumentPreview"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKScannedPageImageType@SBSDKScannedPageImageTypeDocumentPreview","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKScannedPageImageType.documentPreview","roleHeading":"Case"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype\/documentpreview"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype\/documentpreview"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"A screen-sized preview of the fully processed, rotated, cropped and filtered image."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentPreview"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType\/documentPreview","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPageImageType":{"title":"SBSDKScannedPageImageType","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScannedPageImageType"}],"url":"\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType","type":"topic","abstract":[{"text":"An enum representing the different types of images a scanned page has.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPageImageType"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPageImageType/documentPreview":{"title":"SBSDKScannedPageImageType.documentPreview","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentPreview"}],"url":"\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype\/documentpreview","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType\/documentPreview","type":"topic","abstract":[{"text":"A screen-sized preview of the fully processed, rotated, cropped and filtered image.","type":"text"}],"navigatorTitle":[{"text":"SBSDKScannedPageImageTypeDocumentPreview","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKScannedPageImageTypeDocumentPreview"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKScannedPageImageTypeDocumentPreview","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKScannedPageImageTypeDocumentPreview"}],"languages":["occ"]}]}},{"op":"replace","value":"SBSDKScannedPageImageType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKScannedPageImageType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType\/fragments"},{"op":"replace","value":[{"text":"SBSDKScannedPageImageType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType\/navigatorTitle"},{"op":"replace","value":"SBSDKScannedPageImageTypeDocumentPreview","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType~1documentPreview\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType~1documentPreview\/fragments","value":[{"kind":"identifier","text":"SBSDKScannedPageImageTypeDocumentPreview"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}