{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"Equatable Implementations"},"kind":"article","sections":[],"topicSections":[{"anchor":"Operators","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/!=(_:_:)"],"generated":true,"title":"Operators"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoflipmode\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFlipMode":{"title":"SBSDKVideoFlipMode","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"An enum describing how images can be flipped."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFlipMode"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoflipmode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKVideoFlipMode"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFlipMode/!=(_:_:)":{"type":"topic","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoflipmode\/!=(_:_:)","title":"!=(_:_:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFlipMode\/!=(_:_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFlipMode\/title","value":"SBSDKVideoFlipMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFlipMode\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoFlipMode"}]},{"value":[{"kind":"identifier","text":"SBSDKVideoFlipMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFlipMode\/navigatorTitle"}]}]}