{"metadata":{"title":"resetSmoothingData()","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScanner(im)resetSmoothingData","roleHeading":"Instance Method","navigatorTitle":[{"text":"resetSmoothingData","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetSmoothingData"},{"kind":"text","text":"()"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanner"]]},"sections":[],"abstract":[{"text":"Resets the smoothingData. If smoothing is enabled the polygon scanner smoothes the result with results from","type":"text"},{"text":" ","type":"text"},{"text":"previous scans. You should call this method once per second or if the device has been moved.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resetSmoothingData"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscanner\/resetsmoothingdata()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscanner\/resetsmoothingdata()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanner\/resetSmoothingData()","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScanner/resetSmoothingData()":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanner\/resetSmoothingData()","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscanner\/resetsmoothingdata()","role":"symbol","abstract":[{"type":"text","text":"Resets the smoothingData. If smoothing is enabled the polygon scanner smoothes the result with results from"},{"type":"text","text":" "},{"type":"text","text":"previous scans. You should call this method once per second or if the device has been moved."}],"navigatorTitle":[{"kind":"identifier","text":"resetSmoothingData"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resetSmoothingData"},{"text":"()","kind":"text"}],"type":"topic","title":"resetSmoothingData()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScanner":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanner","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScanner"}],"type":"topic","abstract":[{"text":"A class to scan a document’s outline on various image sources.","type":"text"}],"title":"SBSDKDocumentScanner","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscanner","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentScanner","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"resetSmoothingData"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"resetSmoothingData"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"resetSmoothingData"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScanner~1resetSmoothingData()\/title","op":"replace","value":"resetSmoothingData"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"resetSmoothingData","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScanner~1resetSmoothingData()\/fragments"},{"op":"replace","value":"SBSDKDocumentScanner","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScanner\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScanner\/fragments","op":"replace","value":[{"text":"SBSDKDocumentScanner","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScanner\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentScanner"}]}]}]}