{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentType\/init(genericTypes:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentType(im)initWithGenericTypes:","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"genericTypes"},{"text":": [","kind":"text"},{"text":"SBSDKGenericDocumentRootType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRootType"},{"text":"])","kind":"text"}],"symbolKind":"init","role":"symbol","title":"init(genericTypes:)","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithGenericTypes:"}]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"A compound document type consisting of one or multiple generic document root types."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"genericTypes"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentRootType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRootType"},{"text":"])","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumenttype\/init(generictypes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumenttype\/init(generictypes:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentType/init(genericTypes:)":{"abstract":[{"type":"text","text":"A compound document type consisting of one or multiple generic document root types."}],"title":"init(genericTypes:)","navigatorTitle":[{"kind":"identifier","text":"initWithGenericTypes:"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentType\/init(genericTypes:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumenttype\/init(generictypes:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"genericTypes","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRootType","text":"SBSDKGenericDocumentRootType","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentType":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUIDocumentType","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumenttype","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentType","kind":"identifier"}],"abstract":[{"type":"text","text":"The type of the document that should be recognized with "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","type":"reference","isActive":true},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"It is a composition of the generic document types.","type":"text"}],"title":"SBSDKUIDocumentType","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRootType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRootType","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentRootType"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRootType"}],"role":"symbol","title":"SBSDKGenericDocumentRootType","type":"topic","abstract":[{"type":"text","text":"Root document type."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentroottype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to recognize generic documents."}],"title":"SBSDKUIGenericDocumentRecognizerViewController","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithGenericTypes:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGenericTypes:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithGenericTypes:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKGenericDocumentRootType *>"},{"kind":"text","text":" *) "},{"text":"genericTypes","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentType~1init(genericTypes:)\/title","value":"initWithGenericTypes:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentType~1init(genericTypes:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithGenericTypes:"}]},{"op":"replace","value":"SBSDKUIDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentType\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentType\/fragments","value":[{"text":"SBSDKUIDocumentType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentType\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIDocumentType","kind":"identifier"}]},{"value":"SBSDKGenericDocumentRootType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRootType\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRootType\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRootType"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRootType\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentRootType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/title","op":"replace","value":"SBSDKUIGenericDocumentRecognizerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewController"}]},{"value":[{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}