{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumenttype\/passportde"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumenttype\/passportde"]}],"kind":"symbol","abstract":[{"text":"The document type for a German passport. Front side only.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentType"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"passportDE","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentType","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentType","text":"SBSDKUIDocumentType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentType\/passportDE","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"passportDE"},{"kind":"text","text":": "},{"text":"SBSDKUIDocumentType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentType"}],"title":"passportDE","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentType(cpy)passportDE","navigatorTitle":[{"kind":"identifier","text":"passportDE"}],"modules":[{"name":"ScanbotSDK"}]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentType/passportDE":{"role":"symbol","abstract":[{"text":"The document type for a German passport. Front side only.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentType\/passportDE","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"passportDE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUIDocumentType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentType"}],"navigatorTitle":[{"kind":"identifier","text":"passportDE"}],"type":"topic","title":"passportDE","url":"\/documentation\/scanbotsdk\/sbsdkuidocumenttype\/passportde","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController":{"title":"SBSDKUIGenericDocumentRecognizerViewController","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewController"}],"navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to recognize generic documents."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentType":{"role":"symbol","abstract":[{"text":"The type of the document that should be recognized with ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"It is a composition of the generic document types."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentType","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentType"}],"type":"topic","title":"SBSDKUIDocumentType","url":"\/documentation\/scanbotsdk\/sbsdkuidocumenttype","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"passportDE","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"passportDE","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentType","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentType","text":"SBSDKUIDocumentType"},{"text":" * ","kind":"text"},{"text":"passportDE","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentType~1passportDE\/title","value":"passportDE"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentType~1passportDE\/fragments","value":[{"kind":"identifier","text":"passportDE"}]},{"op":"replace","value":"SBSDKUIGenericDocumentRecognizerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/fragments"},{"op":"replace","value":[{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentType\/title","value":"SBSDKUIDocumentType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentType\/fragments","op":"replace","value":[{"text":"SBSDKUIDocumentType","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKUIDocumentType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}