{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration\/new","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration(cm)new","navigatorTitle":[{"kind":"identifier","text":"new"}],"role":"symbol","roleHeading":"Type Method","title":"new","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"new"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"new"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatpharmacodetwotrackconfiguration\/new"]}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration/new":{"navigatorTitle":[{"text":"new","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"title":"new","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration\/new","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatpharmacodetwotrackconfiguration\/new","kind":"symbol","type":"topic","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatpharmacodetwotrackconfiguration","title":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","abstract":[{"type":"text","text":"PHARMA_CODE_TWO_TRACK barcode configuration. Add to scanner configuration to scan Laetus two-track PharmaCode"},{"type":"text","text":" "},{"type":"text","text":"barcodes. Linear (i.e. one-track) PharmaCode scanning is configured separately through the PharmaCodeConfig class."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration\/title","value":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}