{"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"buttonDetectedColor"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonDetectedColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol","title":"buttonDetectedColor","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKShutterButton(py)buttonDetectedColor"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton\/buttonDetectedColor","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The main color of the receiver while the scanner status is "},{"type":"codeVoice","code":"SBSDKScannerStatusDetected"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to white."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"dynamic","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"buttonDetectedColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkshutterbutton\/buttondetectedcolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkshutterbutton\/buttondetectedcolor"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKShutterButton":{"navigatorTitle":[{"text":"SBSDKShutterButton","kind":"identifier"}],"title":"SBSDKShutterButton","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkshutterbutton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton","kind":"symbol","role":"symbol","abstract":[{"text":"The button class used in the camera view controller to take a snapshot.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Animates itself depending on its status."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKShutterButton"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKShutterButton/buttonDetectedColor":{"kind":"symbol","abstract":[{"text":"The main color of the receiver while the scanner status is ","type":"text"},{"type":"codeVoice","code":"SBSDKScannerStatusDetected"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Defaults to white.","type":"text"}],"navigatorTitle":[{"text":"buttonDetectedColor","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"buttonDetectedColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"type":"topic","role":"symbol","title":"buttonDetectedColor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton\/buttonDetectedColor","url":"\/documentation\/scanbotsdk\/sbsdkshutterbutton\/buttondetectedcolor"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"buttonDetectedColor","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"buttonDetectedColor","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" * ","kind":"text"},{"text":"buttonDetectedColor","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","value":"SBSDKShutterButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton\/fragments","value":[{"text":"SBSDKShutterButton","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton~1buttonDetectedColor\/title","value":"buttonDetectedColor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton~1buttonDetectedColor\/fragments","value":[{"text":"buttonDetectedColor","kind":"identifier"}],"op":"replace"}]}]}