{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"didMoveToWindow"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkshutterbutton\/didmovetowindow"]}],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"didMoveToWindow"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","title":"didMoveToWindow","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKShutterButton(im)didMoveToWindow","roleHeading":"Instance Method","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton\/didMoveToWindow","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKShutterButton/didMoveToWindow":{"navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"didMoveToWindow","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton\/didMoveToWindow","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkshutterbutton\/didmovetowindow","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMoveToWindow"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKShutterButton":{"type":"topic","kind":"symbol","title":"SBSDKShutterButton","url":"\/documentation\/scanbotsdk\/sbsdkshutterbutton","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKShutterButton"}],"abstract":[{"type":"text","text":"The button class used in the camera view controller to take a snapshot."},{"type":"text","text":" "},{"type":"text","text":"Animates itself depending on its status."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKShutterButton"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKShutterButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton\/fragments","value":[{"text":"SBSDKShutterButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKShutterButton"}]}]}]}