{"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"text":"initWithFrame:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKShutterButton(im)initWithFrame:","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"roleHeading":"Instance Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") "},{"text":"frame","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkshutterbutton\/initwithframe:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton\/initWithFrame:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKShutterButton/initWithFrame:":{"fragments":[{"kind":"text","text":"- "},{"text":"initWithFrame:","kind":"identifier"}],"abstract":[],"title":"initWithFrame:","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkshutterbutton\/initwithframe:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton\/initWithFrame:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKShutterButton":{"title":"SBSDKShutterButton","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton","abstract":[{"text":"The button class used in the camera view controller to take a snapshot.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Animates itself depending on its status."}],"url":"\/documentation\/scanbotsdk\/sbsdkshutterbutton","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKShutterButton"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKShutterButton"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton\/title","value":"SBSDKShutterButton","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton\/fragments","value":[{"text":"SBSDKShutterButton","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKShutterButton"}]}]}]}