{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scannerStatus"},{"text":": ","kind":"text"},{"text":"SBSDKScannerStatus","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannerStatus","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKScannerStatus"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkshutterbutton\/scannerstatus"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkshutterbutton\/scannerstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton\/scannerStatus"},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"scannerStatus","navigatorTitle":[{"kind":"identifier","text":"scannerStatus"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scannerStatus","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKScannerStatus","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKScannerStatus"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKShutterButton(py)scannerStatus","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"abstract":[{"text":"The current status of the receiver. See ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannerStatus"},{"type":"text","text":"."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKShutterButton":{"navigatorTitle":[{"text":"SBSDKShutterButton","kind":"identifier"}],"title":"SBSDKShutterButton","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton","abstract":[{"type":"text","text":"The button class used in the camera view controller to take a snapshot."},{"type":"text","text":" "},{"text":"Animates itself depending on its status.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkshutterbutton","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKShutterButton","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannerStatus":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannerStatus","navigatorTitle":[{"text":"SBSDKScannerStatus","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkscannerstatus","title":"SBSDKScannerStatus","abstract":[{"type":"text","text":"This enum describes the possible scanning states of any scanner."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannerStatus","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKShutterButton/scannerStatus":{"navigatorTitle":[{"kind":"identifier","text":"scannerStatus"}],"title":"scannerStatus","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKShutterButton\/scannerStatus","abstract":[{"type":"text","text":"The current status of the receiver. See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannerStatus"},{"text":".","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkshutterbutton\/scannerstatus","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scannerStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKScannerStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKScannerStatus"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"scannerStatus"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"scannerStatus"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKScannerStatus","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannerStatus","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKScannerStatus"},{"kind":"text","text":" "},{"text":"scannerStatus","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKShutterButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKShutterButton"}]},{"value":"SBSDKScannerStatus","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannerStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKScannerStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannerStatus\/fragments"},{"value":"scannerStatus","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton~1scannerStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKShutterButton~1scannerStatus\/fragments","value":[{"text":"scannerStatus","kind":"identifier"}]}]}]}