{"abstract":[{"text":"Creates a new instance of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/create(configuration:delegate:)"},"metadata":{"title":"create(configuration:delegate:)","role":"symbol","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUIMRZScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerConfiguration"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUIMRZScannerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIMRZScannerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"text":"SBSDKUIMRZScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerViewController"}],"roleHeading":"Type Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerViewController(cm)createWithConfiguration:delegate:","navigatorTitle":[{"text":"createWithConfiguration:delegate:","kind":"identifier"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(createWithConfiguration:delegate:) "},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUIMRZScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIMRZScannerViewControllerDelegate","kind":"typeIdentifier","text":"SBSDKUIMRZScannerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SBSDKUIMRZScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController"}]}]},{"parameters":[{"name":"configuration","content":[{"inlineContent":[{"text":"The configuration to define look and feel of the new detection view controller.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The delegate of the new detection view controller.","type":"text"}],"type":"paragraph"}],"name":"delegate"}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new instance of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController"},{"type":"text","text":"."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller\/create(configuration:delegate:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller\/create(configuration:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewControllerDelegate":{"kind":"symbol","title":"SBSDKUIMRZScannerViewControllerDelegate","role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIMRZScannerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMRZScannerViewControllerDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol for "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","isActive":true},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontrollerdelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","title":"SBSDKUIMRZScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to detect machine readable zones."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIMRZScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerConfiguration","title":"SBSDKUIMRZScannerConfiguration","navigatorTitle":[{"text":"SBSDKUIMRZScannerConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerconfiguration","type":"topic","role":"symbol","abstract":[{"type":"text","text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI MRZ scanner."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIMRZScannerConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewController/create(configuration:delegate:)":{"url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller\/create(configuration:delegate:)","title":"create(configuration:delegate:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUIMRZScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"text":"SBSDKUIMRZScannerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIMRZScannerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerViewController","text":"SBSDKUIMRZScannerViewController","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/create(configuration:delegate:)","navigatorTitle":[{"text":"createWithConfiguration:delegate:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","value":"createWithConfiguration:delegate:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithConfiguration:delegate:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUIMRZScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController"},{"text":" *) ","kind":"text"},{"text":"createWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerConfiguration","text":"SBSDKUIMRZScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"text":"(","kind":"text"},{"text":"id<SBSDKUIMRZScannerViewControllerDelegate>","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKUIMRZScannerViewControllerDelegate","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"configuration","content":[{"inlineContent":[{"text":"The configuration to define look and feel of the new detection view controller.","type":"text"}],"type":"paragraph"}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate of the new detection view controller."}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A new instance of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","type":"reference","isActive":true},{"text":".","type":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewControllerDelegate\/title","value":"SBSDKUIMRZScannerViewControllerDelegate"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIMRZScannerViewControllerDelegate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewControllerDelegate\/fragments"},{"op":"replace","value":[{"text":"SBSDKUIMRZScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewControllerDelegate\/navigatorTitle"},{"value":"SBSDKUIMRZScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKUIMRZScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}]},{"value":"SBSDKUIMRZScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIMRZScannerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIMRZScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerConfiguration\/navigatorTitle"},{"value":"createWithConfiguration:delegate:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController~1create(configuration:delegate:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController~1create(configuration:delegate:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithConfiguration:delegate:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}