{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/SBSDKMRZScannerViewControllerDelegate-Implementations"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/mrzScannerController(_:didDetectMRZ:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzScannerController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController","text":"SBSDKMRZScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController"},{"text":", ","kind":"text"},{"text":"didDetectMRZ","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResult","text":"SBSDKMachineReadableZoneRecognizerResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"text":"The calling ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]},{"name":"result","content":[{"inlineContent":[{"text":"The detected machine-readable zone result.","type":"text"}],"type":"paragraph"}]}]}],"abstract":[{"type":"text","text":"Informs the delegate that the scanner has detected a machine-readable zone."}],"metadata":{"extendedModule":"ScanbotSDK","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzScannerController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController","kind":"typeIdentifier","text":"SBSDKMRZScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDetectMRZ"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResult","kind":"typeIdentifier","text":"SBSDKMachineReadableZoneRecognizerResult"},{"kind":"text","text":")"}],"title":"mrzScannerController(_:didDetectMRZ:)","navigatorTitle":[{"kind":"identifier","text":"mrzScannerController:didDetectMRZ:"}],"externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUIMRZScannerViewController(im)mrzScannerController:didDetectMRZ:","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller\/mrzscannercontroller(_:diddetectmrz:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller\/mrzscannercontroller(_:diddetectmrz:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZScannerViewController"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller","title":"SBSDKMRZScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZScannerViewController"}],"abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan machine-readable zones."}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewController/mrzScannerController(_:didDetectMRZ:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzScannerController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController","kind":"typeIdentifier","text":"SBSDKMRZScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDetectMRZ"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResult","kind":"typeIdentifier","text":"SBSDKMachineReadableZoneRecognizerResult"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"mrzScannerController:didDetectMRZ:"}],"title":"mrzScannerController(_:didDetectMRZ:)","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller\/mrzscannercontroller(_:diddetectmrz:)","kind":"symbol","abstract":[{"type":"text","text":"Informs the delegate that the scanner has detected a machine-readable zone."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/mrzScannerController(_:didDetectMRZ:)","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewController/SBSDKMRZScannerViewControllerDelegate-Implementations":{"kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/SBSDKMRZScannerViewControllerDelegate-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller\/sbsdkmrzscannerviewcontrollerdelegate-implementations","title":"SBSDKMRZScannerViewControllerDelegate Implementations","role":"collectionGroup","abstract":[],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResult":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresult","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult","abstract":[{"type":"text","text":"A class encapsulating a machine-readable-zone recognition result."}],"title":"SBSDKMachineReadableZoneRecognizerResult","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewController":{"kind":"symbol","type":"topic","title":"SBSDKUIMRZScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}],"abstract":[{"text":"A highly customizable camera-based view controller to detect machine readable zones.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"mrzScannerController:didDetectMRZ:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mrzScannerController:didDetectMRZ:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"mrzScannerController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMRZScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didDetectMRZ:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMachineReadableZoneRecognizerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResult"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/title","value":"SBSDKMRZScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKMRZScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKMRZScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController~1mrzScannerController(_:didDetectMRZ:)\/title","op":"replace","value":"mrzScannerController:didDetectMRZ:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController~1mrzScannerController(_:didDetectMRZ:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mrzScannerController:didDetectMRZ:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/title","op":"replace","value":"SBSDKMachineReadableZoneRecognizerResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/fragments","op":"replace","value":[{"text":"SBSDKMachineReadableZoneRecognizerResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResult"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/title","op":"replace","value":"SBSDKUIMRZScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKUIMRZScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}