{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/mrzScannerControllerShouldDetectMRZ(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/SBSDKMRZScannerViewControllerDelegate-Implementations"]]},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Method","role":"symbol","title":"mrzScannerControllerShouldDetectMRZ(_:)","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUIMRZScannerViewController(im)mrzScannerControllerShouldDetectMRZ:","symbolKind":"method","extendedModule":"ScanbotSDK","navigatorTitle":[{"text":"mrzScannerControllerShouldDetectMRZ:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mrzScannerControllerShouldDetectMRZ","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKMRZScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller\/mrzscannercontrollershoulddetectmrz(_:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller\/mrzscannercontrollershoulddetectmrz(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mrzScannerControllerShouldDetectMRZ","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"controller"},{"text":": ","kind":"text"},{"text":"SBSDKMRZScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}]},{"kind":"parameters","parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The calling "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController"},{"type":"text","text":"."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Return "},{"type":"codeVoice","code":"True"},{"text":" if you want to detect machine-readable zones on the next video frame, ","type":"text"},{"code":"False","type":"codeVoice"},{"type":"text","text":" otherwise."}]}]}],"abstract":[{"text":"Asks the delegate if the scanner should detect machine-readable zones on the next video frame.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Optional."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewController":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","title":"SBSDKMRZScannerViewController","abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan machine-readable zones."}],"navigatorTitle":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMRZScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewController/mrzScannerControllerShouldDetectMRZ(_:)":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Asks the delegate if the scanner should detect machine-readable zones on the next video frame.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Optional."}],"navigatorTitle":[{"text":"mrzScannerControllerShouldDetectMRZ:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mrzScannerControllerShouldDetectMRZ"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKMRZScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"mrzScannerControllerShouldDetectMRZ(_:)","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller\/mrzscannercontrollershoulddetectmrz(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/mrzScannerControllerShouldDetectMRZ(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewController/SBSDKMRZScannerViewControllerDelegate-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/SBSDKMRZScannerViewControllerDelegate-Implementations","title":"SBSDKMRZScannerViewControllerDelegate Implementations","kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller\/sbsdkmrzscannerviewcontrollerdelegate-implementations","type":"topic","role":"collectionGroup","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","title":"SBSDKUIMRZScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to detect machine readable zones."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIMRZScannerViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"mrzScannerControllerShouldDetectMRZ:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mrzScannerControllerShouldDetectMRZ:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"mrzScannerControllerShouldDetectMRZ:"},{"kind":"text","text":"("},{"text":"SBSDKMRZScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController"},{"kind":"text","text":" *) "},{"text":"controller","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKMRZScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/fragments","value":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/navigatorTitle"},{"value":"mrzScannerControllerShouldDetectMRZ:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController~1mrzScannerControllerShouldDetectMRZ(_:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController~1mrzScannerControllerShouldDetectMRZ(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"mrzScannerControllerShouldDetectMRZ:","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUIMRZScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}],"op":"replace"},{"value":[{"text":"SBSDKUIMRZScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/navigatorTitle","op":"replace"}]}]}