{"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2userguidancevisibility\/autocaptureonly"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2userguidancevisibility\/autocaptureonly"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceVisibility"]]},"sections":[],"abstract":[{"text":"Enabled only for the ‘auto snapping’ mode.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceVisibility\/autoCaptureOnly","interfaceLanguage":"swift"},"metadata":{"title":"SBSDKUI2UserGuidanceVisibility.autoCaptureOnly","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2UserGuidanceVisibility@SBSDKUI2UserGuidanceVisibilityAutoCaptureOnly","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCaptureOnly","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2UserGuidanceVisibilityAutoCaptureOnly","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCaptureOnly","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceVisibility":{"url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancevisibility","role":"symbol","abstract":[{"type":"text","text":"Determines the visibility mode for the document capturing user guidance labels."}],"navigatorTitle":[{"text":"SBSDKUI2UserGuidanceVisibility","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceVisibility","kind":"symbol","type":"topic","title":"SBSDKUI2UserGuidanceVisibility","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2UserGuidanceVisibility","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceVisibility/autoCaptureOnly":{"url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancevisibility\/autocaptureonly","title":"SBSDKUI2UserGuidanceVisibility.autoCaptureOnly","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceVisibility\/autoCaptureOnly","abstract":[{"type":"text","text":"Enabled only for the ‘auto snapping’ mode."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2UserGuidanceVisibilityAutoCaptureOnly","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCaptureOnly","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2UserGuidanceVisibilityAutoCaptureOnly"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2UserGuidanceVisibilityAutoCaptureOnly","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibilityAutoCaptureOnly"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceVisibility\/title","value":"SBSDKUI2UserGuidanceVisibility"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceVisibility\/fragments","value":[{"text":"SBSDKUI2UserGuidanceVisibility","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceVisibility\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibility"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceVisibility~1autoCaptureOnly\/title","op":"replace","value":"SBSDKUI2UserGuidanceVisibilityAutoCaptureOnly"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceVisibility~1autoCaptureOnly\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibilityAutoCaptureOnly"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}