{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"new"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2viewfinderconfiguration\/new"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","symbolKind":"method","roleHeading":"Type Method","title":"new","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ViewFinderConfiguration(cm)new","navigatorTitle":[{"text":"new","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ViewFinderConfiguration"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ViewFinderConfiguration\/new"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ViewFinderConfiguration":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the scanning interface’s viewfinder, allowing it to be shown or hidden as guidance to the user."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ViewFinderConfiguration","navigatorTitle":[{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2viewfinderconfiguration","title":"SBSDKUI2ViewFinderConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ViewFinderConfiguration/new":{"title":"new","fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2viewfinderconfiguration\/new","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ViewFinderConfiguration\/new","role":"symbol","navigatorTitle":[{"text":"new","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ViewFinderConfiguration\/title","value":"SBSDKUI2ViewFinderConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ViewFinderConfiguration\/fragments","value":[{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ViewFinderConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"op":"replace"}]}]}