{"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"willShowEnableCameraView","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/willShowEnableCameraView","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"willShowEnableCameraView"}],"title":"willShowEnableCameraView","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willShowEnableCameraView"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerViewController(im)willShowEnableCameraView"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/willshowenablecameraview"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewController":{"deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckScannerViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUICheckScannerViewController","kind":"identifier"}],"title":"SBSDKUICheckScannerViewController","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","role":"symbol","abstract":[{"text":"A Ready-To-Use viewController to scan checks using the camera.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewController/willShowEnableCameraView":{"url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/willshowenablecameraview","navigatorTitle":[{"kind":"identifier","text":"willShowEnableCameraView"}],"abstract":[],"title":"willShowEnableCameraView","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willShowEnableCameraView"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/willShowEnableCameraView"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"SBSDKUICheckScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}