{"metadata":{"roleHeading":"Initializer","role":"symbol","symbolKind":"init","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerConfiguration"},{"kind":"text","text":", "},{"text":"onSubmit","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerResult"},{"text":") -> (), ","kind":"text"},{"kind":"externalParam","text":"onCancel"},{"text":": () -> (), ","kind":"text"},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ())","kind":"text"}],"externalID":"s:10ScanbotSDK26SBSDKUI2BarcodeScannerViewV13configuration8onSubmit0H6Cancel0H5ErrorAcA0cdE13ConfigurationC_yAA0cdE6ResultCcyycys0K0_pSgctcfc","title":"init(configuration:onSubmit:onCancel:onError:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView"]]},"abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView","isActive":true},{"type":"text","text":"."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView\/init(configuration:onSubmit:onCancel:onError:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerConfiguration","kind":"typeIdentifier","text":"SBSDKUI2BarcodeScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onSubmit"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerResult","text":"SBSDKUI2BarcodeScannerResult","kind":"typeIdentifier"},{"kind":"text","text":") -> (), "},{"kind":"externalParam","text":"onCancel"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" () -> (), "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> ())"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"text":"The configuration to define look and feel of the new detection view controller.","type":"text"}]}]},{"name":"onSubmit","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A closure that is called when the Submit button was pressed. The scanning result is passed as a parameter."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A closure that is called when the Cancel button was pressed. Dismiss the scanner here."}]}],"name":"onCancel"},{"name":"onError","content":[{"type":"paragraph","inlineContent":[{"text":"A closure that is called if an error occured. The error may be passed as a parameter.","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerview\/init(configuration:onsubmit:oncancel:onerror:)"]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerView":{"role":"symbol","abstract":[{"text":"The SwifUI wrapper for ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerViewController","type":"reference"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeScannerView","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerview","title":"SBSDKUI2BarcodeScannerView","navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerView","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerView/init(configuration:onSubmit:onCancel:onError:)":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerview\/init(configuration:onsubmit:oncancel:onerror:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerConfiguration"},{"text":", ","kind":"text"},{"text":"onSubmit","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerResult","text":"SBSDKUI2BarcodeScannerResult"},{"kind":"text","text":") -> (), "},{"kind":"externalParam","text":"onCancel"},{"kind":"text","text":": () -> (), "},{"kind":"externalParam","text":"onError"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> ())"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView\/init(configuration:onSubmit:onCancel:onError:)","title":"init(configuration:onSubmit:onCancel:onError:)","type":"topic","abstract":[{"text":"Creates a new instance of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView","isActive":true,"type":"reference"},{"text":".","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerviewcontroller","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerViewController","abstract":[],"role":"symbol","title":"SBSDKUI2BarcodeScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerViewController"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerConfiguration":{"title":"SBSDKUI2BarcodeScannerConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Configuration of the barcode scanner screen."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeScannerConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerResult","title":"SBSDKUI2BarcodeScannerResult","abstract":[{"type":"text","text":"Results of the barcode scan."}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerResult","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeScannerResult"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerresult"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController\/title","value":"SBSDKUI2BarcodeScannerViewController"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration\/title","value":"SBSDKUI2BarcodeScannerConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}]},{"value":"SBSDKUI2BarcodeScannerResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerResult\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerResult\/fragments","value":[{"text":"SBSDKUI2BarcodeScannerResult","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}