{"abstract":[{"type":"text","text":"For binarized images only."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ccittrle","kind":"identifier"}],"roleHeading":"Case","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKTIFFImageWriterCompressionOptions@SBSDKTIFFImageWriterCompressionOptionsCcittrle","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsCcittrle"}],"title":"SBSDKTIFFImageWriterCompressionOptions.ccittrle"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/ccittrle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/ccittrle"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ccittrle","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittrle"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions/ccittrle":{"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsCcittrle"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/ccittrle","title":"SBSDKTIFFImageWriterCompressionOptions.ccittrle","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ccittrle","kind":"identifier"}],"abstract":[{"type":"text","text":"For binarized images only."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/ccittrle"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","url":"\/documentation\/scanbotdocumentscannersdk","abstract":[{"type":"text","text":"Version: 6.2.0"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions":{"navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions","type":"topic","abstract":[{"type":"text","text":"The TIFF compression algorithms."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"}],"title":"SBSDKTIFFImageWriterCompressionOptions","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKTIFFImageWriterCompressionOptionsCcittrle","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcittrle","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcittrle","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKTIFFImageWriterCompressionOptionsCcittrle","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccittrle\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1ccittrle\/fragments","op":"replace","value":[{"text":"SBSDKTIFFImageWriterCompressionOptionsCcittrle","kind":"identifier"}]},{"value":"SBSDKTIFFImageWriterCompressionOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions\/title"},{"value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions\/navigatorTitle","value":[{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}