{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzer"]]},"metadata":{"title":"init(configuration:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQualityAnalyzer(im)initWithConfiguration:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQualityAnalyzerConfiguration"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithConfiguration:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration","text":"SBSDKDocumentQualityAnalyzerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQualityAnalyzerConfiguration"},{"kind":"text","text":")"}]}]},{"parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration of the new analyzer."}]}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzer\/init(configuration:)"},"abstract":[{"text":"Initializes a new document quality analyzer with the given configuration.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzer\/init(configuration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzer\/init(configuration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzer":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentQualityAnalyzer","kind":"identifier"}],"title":"SBSDKDocumentQualityAnalyzer","abstract":[{"type":"text","text":"Analyzes the quality of a document on a still image."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzer","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzer","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQualityAnalyzer","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzerConfiguration":{"navigatorTitle":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"text":"Document Quality Analyzer configuration.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration","title":"SBSDKDocumentQualityAnalyzerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzer/init(configuration:)":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzer\/init(configuration:)","abstract":[{"text":"Initializes a new document quality analyzer with the given configuration.","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQualityAnalyzerConfiguration","kind":"typeIdentifier","text":"SBSDKDocumentQualityAnalyzerConfiguration"},{"kind":"text","text":")"}],"role":"symbol","title":"init(configuration:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzer\/init(configuration:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithConfiguration:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration","text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQualityAnalyzerConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"text":"The configuration of the new analyzer.","type":"text"}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzer\/title","value":"SBSDKDocumentQualityAnalyzer"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzer\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzer"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzer\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzer"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/title","value":"SBSDKDocumentQualityAnalyzerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzer~1init(configuration:)\/title","value":"initWithConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzer~1init(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"}]}]}]}