{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/dataIntelligence"},"abstract":[{"type":"text","text":"Data intelligence is enabled in the licence. Currently unused."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataIntelligence"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"SBSDKFeatureDataIntelligence","kind":"identifier"}],"symbolKind":"case","title":"SBSDKFeature.dataIntelligence","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataIntelligence","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKFeature@SBSDKFeatureDataIntelligence"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/dataintelligence"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/dataintelligence"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.2.1"}],"type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKFeature"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature","title":"SBSDKFeature","kind":"symbol","abstract":[{"text":"The features that are activated in the ScanbotSDK license.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKFeature","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/dataIntelligence":{"navigatorTitle":[{"text":"SBSDKFeatureDataIntelligence","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataIntelligence"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/dataintelligence","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/dataIntelligence","abstract":[{"type":"text","text":"Data intelligence is enabled in the licence. Currently unused."}],"title":"SBSDKFeature.dataIntelligence","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKFeatureDataIntelligence","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKFeatureDataIntelligence","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKFeatureDataIntelligence"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature\/title","value":"SBSDKFeature"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKFeature"}]},{"value":"SBSDKFeatureDataIntelligence","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1dataIntelligence\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKFeatureDataIntelligence"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1dataIntelligence\/fragments","op":"replace"}]}]}