{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPage"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPage\/initWithText:confidence:roi:blocks:","interfaceLanguage":"occ"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpage\/initwithtext:confidence:roi:blocks:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithText:confidence:roi:blocks:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","title":"initWithText:confidence:roi:blocks:","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPage(im)initWithText:confidence:roi:blocks:","navigatorTitle":[{"text":"initWithText:confidence:roi:blocks:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithText:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"text","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"confidence:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"confidence","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"roi:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSValue *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"roi","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"blocks:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKBlock *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"blocks","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPage":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKPage"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPage"}],"title":"SBSDKPage","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpage","abstract":[{"type":"text","text":"Represents result of performing OCR on an image. A page is made up of blocks."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPage/initWithText:confidence:roi:blocks:":{"abstract":[],"role":"symbol","title":"initWithText:confidence:roi:blocks:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithText:confidence:roi:blocks:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPage\/initWithText:confidence:roi:blocks:","navigatorTitle":[{"text":"initWithText:confidence:roi:blocks:","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpage\/initwithtext:confidence:roi:blocks:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPage\/title","value":"SBSDKPage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPage\/fragments","value":[{"kind":"identifier","text":"SBSDKPage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPage\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPage"}]}]}]}