{"metadata":{"navigatorTitle":[{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"}],"role":"symbol","title":"maximumNumberOfAccumulatedFrames","platforms":[],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextPatternScannerBehaviorConfiguration(py)maximumNumberOfAccumulatedFrames","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerBehaviorConfiguration\/maximumNumberOfAccumulatedFrames"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerBehaviorConfiguration"]]},"sections":[],"abstract":[{"text":"The maximum number of accumulated video frames before the current recognition result is returned.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerbehaviorconfiguration\/maximumnumberofaccumulatedframes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerbehaviorconfiguration\/maximumnumberofaccumulatedframes"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2TextPatternScannerViewController instead."}],"type":"paragraph"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerBehaviorConfiguration":{"abstract":[{"text":"Configuration for the behavior of RTU-UI text pattern scanner.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerbehaviorconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUITextPatternScannerBehaviorConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUITextPatternScannerBehaviorConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerBehaviorConfiguration","deprecated":true,"role":"symbol","title":"SBSDKUITextPatternScannerBehaviorConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerBehaviorConfiguration/maximumNumberOfAccumulatedFrames":{"deprecated":true,"abstract":[{"type":"text","text":"The maximum number of accumulated video frames before the current recognition result is returned."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerBehaviorConfiguration\/maximumNumberOfAccumulatedFrames","url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerbehaviorconfiguration\/maximumnumberofaccumulatedframes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"}],"kind":"symbol","role":"symbol","title":"maximumNumberOfAccumulatedFrames"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"maximumNumberOfAccumulatedFrames"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerBehaviorConfiguration\/title","op":"replace","value":"SBSDKUITextPatternScannerBehaviorConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerBehaviorConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUITextPatternScannerBehaviorConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerBehaviorConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUITextPatternScannerBehaviorConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerBehaviorConfiguration~1maximumNumberOfAccumulatedFrames\/title","op":"replace","value":"maximumNumberOfAccumulatedFrames"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerBehaviorConfiguration~1maximumNumberOfAccumulatedFrames\/fragments","op":"replace","value":[{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}