{"abstract":[{"text":"Minimum acceptable value of a result BarcodeItem’s sizeScore (between 0 and 1). Barcodes with a sizeScore less","type":"text"},{"text":" ","type":"text"},{"text":"than this value will not be scanned. When set to 0, barcodes are returned no matter what their size is.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerconfiguration\/minimumsizescore"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerconfiguration\/minimumsizescore"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration\/minimumSizeScore"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"title":"minimumSizeScore","navigatorTitle":[{"kind":"identifier","text":"minimumSizeScore"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerConfiguration(py)minimumSizeScore","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"minimumSizeScore","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"symbolKind":"property","roleHeading":"Instance Property"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumSizeScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is 0"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerConfiguration/minimumSizeScore":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration\/minimumSizeScore","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"minimumSizeScore"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerconfiguration\/minimumsizescore","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumSizeScore"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"title":"minimumSizeScore","abstract":[{"type":"text","text":"Minimum acceptable value of a result BarcodeItem’s sizeScore (between 0 and 1). Barcodes with a sizeScore less"},{"type":"text","text":" "},{"text":"than this value will not be scanned. When set to 0, barcodes are returned no matter what their size is.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration","type":"topic","title":"SBSDKUI2BarcodeScannerConfiguration","abstract":[{"text":"Configuration of the scanning behavior.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerconfiguration","navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"minimumSizeScore"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"minimumSizeScore"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimumSizeScore"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":"minimumSizeScore","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration~1minimumSizeScore\/title","op":"replace"},{"value":[{"kind":"identifier","text":"minimumSizeScore"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration~1minimumSizeScore\/fragments"},{"value":"SBSDKUI2BarcodeScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2BarcodeScannerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration\/navigatorTitle"}]}]}