{"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegment\/init(segmentInt:)"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegment(im)initWithSegmentInt:","symbolKind":"init","title":"init(segmentInt:)","navigatorTitle":[{"kind":"identifier","text":"initWithSegmentInt:"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"segmentInt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentInt","text":"SBSDKLineSegmentInt"},{"kind":"text","text":")"}],"roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegment"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"segmentInt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKLineSegmentInt","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentInt","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentInt"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklinesegment\/init(segmentint:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdklinesegment\/init(segmentint:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegment/init(segmentInt:)":{"navigatorTitle":[{"text":"initWithSegmentInt:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdklinesegment\/init(segmentint:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegment\/init(segmentInt:)","title":"init(segmentInt:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"segmentInt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKLineSegmentInt","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegment":{"title":"SBSDKLineSegment","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegment","url":"\/documentation\/scanbotsdk\/sbsdklinesegment","type":"topic","role":"symbol","abstract":[{"text":"Helper class that encapsulates a line segment and provides geometric helper methods.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLineSegment"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLineSegment"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegmentInt":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentInt","abstract":[{"text":"Represents a line segment in 2D space.","type":"text"}],"title":"SBSDKLineSegmentInt","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLineSegmentInt"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklinesegmentint","navigatorTitle":[{"kind":"identifier","text":"SBSDKLineSegmentInt"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithSegmentInt:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSegmentInt:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSegmentInt:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKLineSegmentInt","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentInt","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentInt"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"segmentInt"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegment~1init(segmentInt:)\/title","value":"initWithSegmentInt:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegment~1init(segmentInt:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSegmentInt:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegment\/title","op":"replace","value":"SBSDKLineSegment"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegment\/fragments","op":"replace","value":[{"text":"SBSDKLineSegment","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegment\/navigatorTitle","op":"replace","value":[{"text":"SBSDKLineSegment","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentInt\/title","op":"replace","value":"SBSDKLineSegmentInt"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentInt\/fragments","op":"replace","value":[{"text":"SBSDKLineSegmentInt","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentInt\/navigatorTitle","op":"replace","value":[{"text":"SBSDKLineSegmentInt","kind":"identifier"}]}]}]}