{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatTwoDConfigurationBase"]]},"metadata":{"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatTwoDConfigurationBase(cm)fromJsonWithJson:","role":"symbol","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"roleHeading":"Type Method","title":"fromJsonWithJson:"},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatTwoDConfigurationBase\/fromJsonWithJson:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformattwodconfigurationbase\/fromjsonwithjson:"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatTwoDConfigurationBase","text":"SBSDKBarcodeFormatTwoDConfigurationBase","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatTwoDConfigurationBase"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"json"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatTwoDConfigurationBase/fromJsonWithJson:":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformattwodconfigurationbase\/fromjsonwithjson:","role":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatTwoDConfigurationBase\/fromJsonWithJson:","kind":"symbol","abstract":[],"type":"topic","title":"fromJsonWithJson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatTwoDConfigurationBase":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatTwoDConfigurationBase","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformattwodconfigurationbase","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatTwoDConfigurationBase","navigatorTitle":[{"text":"SBSDKBarcodeFormatTwoDConfigurationBase","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Base class for all 2D barcode configurations."}],"kind":"symbol","title":"SBSDKBarcodeFormatTwoDConfigurationBase"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatTwoDConfigurationBase\/title","value":"SBSDKBarcodeFormatTwoDConfigurationBase","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatTwoDConfigurationBase\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeFormatTwoDConfigurationBase","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatTwoDConfigurationBase\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeFormatTwoDConfigurationBase","kind":"identifier"}]}]}]}