{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/init","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerenergyconfiguration\/init"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration(im)init","title":"init","role":"symbol"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerEnergyConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration","title":"SBSDKBaseScannerEnergyConfiguration","abstract":[{"type":"text","text":"The energy management configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"text":" ","type":"text"},{"text":"‘SBSDKBaseScannerViewController’ and subclasses sport a customizable energy management system.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Since scanners running on a live video feed can put a lot of load onto the CPU and\/or GPU"},{"text":" ","type":"text"},{"text":"of the device, causing the battery to drain quickly and running the device hot, you can customize the energy","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"consumption using this class by configuring the rate of detections\/recognitions per second in performance mode as"},{"type":"text","text":" "},{"text":"well as in energy saving mode.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"In performance mode the scanners will be fed with a higher, configurable rate of"},{"type":"text","text":" "},{"text":"video frames per second.","type":"text"},{"text":" ","type":"text"},{"text":"After a certain, configurable period of inactivity the energy save mode will be engaged and the rate","type":"text"},{"text":" ","type":"text"},{"text":"of scans will be reduced to a lower (configurable) rate.","type":"text"},{"text":" ","type":"text"},{"text":"You can also configure the time of inactivity before the automatic mode switches from performance to energy save mode.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Inactivity here means that both of the following conditions are met:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerenergyconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}],"type":"topic","navigatorTitle":[{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerEnergyConfiguration/init":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerenergyconfiguration\/init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"title":"init","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/init","abstract":[]}},"variantOverrides":[{"patch":[{"value":"SBSDKBaseScannerEnergyConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}