{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategories\/l"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategories\/l"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The child document of type “L”."}],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"l","navigatorTitle":[{"text":"l","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelEuropeanDriverLicenseBackCategories(py)l","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"l"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","kind":"typeIdentifier","text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL"},{"kind":"text","text":"?"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategories\/l"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategories"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelEuropeanDriverLicenseBackCategories/l":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategories\/l","navigatorTitle":[{"text":"l","kind":"identifier"}],"role":"symbol","title":"l","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategories\/l","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The child document of type “L”."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategoriesl","abstract":[{"text":"EuropeanDriverLicenseBack.Categories.L","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","navigatorTitle":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelEuropeanDriverLicenseBackCategories":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Categories table row container"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategories","title":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategories","navigatorTitle":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategories","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategories","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategories","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"l","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"l","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"l","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategories~1l\/title","value":"l","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategories~1l\/fragments","value":[{"kind":"identifier","text":"l"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL\/title","value":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategories\/title","value":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategories","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategories\/fragments","value":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategories","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategories\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategories"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}