{"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"dpi"},{"text":" parameter has two different meanings depending on the value of ","type":"text"},{"type":"codeVoice","code":"pageSize"},{"text":" and","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"pageFit"},{"text":". If pageSize is CUSTOM or pageFit is NONE, then ","type":"text"},{"type":"codeVoice","code":"dpi"},{"text":" is the conversion ratio used","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"to convert from units of pixels to physical inches when adding bitmap images (JPEG, PNG, or"},{"type":"text","text":" "},{"type":"text","text":"raw) to the PDF. Otherwise, if "},{"code":"resamplingMethod","type":"codeVoice"},{"type":"text","text":" is not NONE, then the image is downscaled"},{"type":"text","text":" "},{"type":"text","text":"if necessary (if the image after being fit to the page has a higher calculated DPI than"},{"type":"text","text":" "},{"code":"dpi","type":"codeVoice"},{"type":"text","text":") to match "},{"code":"dpi","type":"codeVoice"},{"type":"text","text":" before adding it to the PDF. Otherwise, the setting is ignored and the"},{"type":"text","text":" "},{"type":"text","text":"calculated image DPI is used instead."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/dpi","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"dpi","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration(py)dpi","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"dpi","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"dpi","role":"symbol"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dpi","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is 72","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/dpi"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/dpi"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration","title":"SBSDKPDFConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The parameters "},{"code":"pageSize","type":"codeVoice"},{"type":"text","text":", "},{"code":"pageFit","type":"codeVoice"},{"type":"text","text":", "},{"code":"dpi","type":"codeVoice"},{"type":"text","text":" and "},{"code":"resamplingMethod","type":"codeVoice"},{"type":"text","text":" interact in a complex way"},{"type":"text","text":" "},{"type":"text","text":"when adding bitmap images (JPEG, PNG, or raw) to the PDF."},{"type":"text","text":" "},{"type":"text","text":"There are three cases to consider:"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/dpi":{"title":"dpi","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/dpi","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/dpi","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dpi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"dpi"}],"abstract":[{"text":"The ","type":"text"},{"code":"dpi","type":"codeVoice"},{"text":" parameter has two different meanings depending on the value of ","type":"text"},{"code":"pageSize","type":"codeVoice"},{"text":" and","type":"text"},{"text":" ","type":"text"},{"code":"pageFit","type":"codeVoice"},{"text":". If pageSize is CUSTOM or pageFit is NONE, then ","type":"text"},{"code":"dpi","type":"codeVoice"},{"type":"text","text":" is the conversion ratio used"},{"type":"text","text":" "},{"type":"text","text":"to convert from units of pixels to physical inches when adding bitmap images (JPEG, PNG, or"},{"type":"text","text":" "},{"type":"text","text":"raw) to the PDF. Otherwise, if "},{"type":"codeVoice","code":"resamplingMethod"},{"type":"text","text":" is not NONE, then the image is downscaled"},{"type":"text","text":" "},{"type":"text","text":"if necessary (if the image after being fit to the page has a higher calculated DPI than"},{"type":"text","text":" "},{"type":"codeVoice","code":"dpi"},{"type":"text","text":") to match "},{"type":"codeVoice","code":"dpi"},{"type":"text","text":" before adding it to the PDF. Otherwise, the setting is ignored and the"},{"type":"text","text":" "},{"type":"text","text":"calculated image DPI is used instead."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"dpi"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"dpi","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"dpi","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/title","value":"SBSDKPDFConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/navigatorTitle","value":[{"text":"SBSDKPDFConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1dpi\/title","value":"dpi"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1dpi\/fragments","value":[{"kind":"identifier","text":"dpi"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}