{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/hash"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Property","title":"hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"fragments":[{"kind":"identifier","text":"hash"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration(py)hash","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration","title":"SBSDKPDFConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The parameters "},{"code":"pageSize","type":"codeVoice"},{"type":"text","text":", "},{"code":"pageFit","type":"codeVoice"},{"type":"text","text":", "},{"code":"dpi","type":"codeVoice"},{"type":"text","text":" and "},{"code":"resamplingMethod","type":"codeVoice"},{"type":"text","text":" interact in a complex way"},{"type":"text","text":" "},{"type":"text","text":"when adding bitmap images (JPEG, PNG, or raw) to the PDF."},{"type":"text","text":" "},{"type":"text","text":"There are three cases to consider:"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/hash":{"abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/hash","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/hash","fragments":[{"kind":"identifier","text":"hash"}],"title":"hash"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/title","value":"SBSDKPDFConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/fragments","value":[{"text":"SBSDKPDFConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/navigatorTitle","value":[{"text":"SBSDKPDFConfiguration","kind":"identifier"}]}]}]}