{"abstract":[{"text":"DeliveryAddress.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentVCard\/deliveryAddress","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","title":"deliveryAddress","navigatorTitle":[{"kind":"identifier","text":"deliveryAddress"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentVCard(py)deliveryAddress","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deliveryAddress"},{"kind":"text","text":": "},{"text":"SBSDKBarcodeDocumentVCardEntry","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentVCardEntry"},{"kind":"text","text":"?"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentVCard"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deliveryAddress","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentVCardEntry","text":"SBSDKBarcodeDocumentVCardEntry","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentVCardEntry"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentvcard\/deliveryaddress"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentvcard\/deliveryaddress"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentVCard/deliveryAddress":{"type":"topic","abstract":[{"text":"DeliveryAddress.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentvcard\/deliveryaddress","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deliveryAddress"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeDocumentVCardEntry","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentVCardEntry"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"deliveryAddress","kind":"identifier"}],"title":"deliveryAddress","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentVCard\/deliveryAddress","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentVCardEntry":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentvcardentry","kind":"symbol","type":"topic","abstract":[{"text":"VCard Entry.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentVCardEntry","title":"SBSDKBarcodeDocumentVCardEntry","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentVCardEntry"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentVCardEntry","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentVCard":{"abstract":[{"text":"VCard.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentVCard","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentVCard","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentVCard","title":"SBSDKBarcodeDocumentVCard","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentvcard"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"deliveryAddress"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"deliveryAddress","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentVCardEntry","text":"SBSDKBarcodeDocumentVCardEntry","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentVCardEntry"},{"kind":"text","text":" * "},{"text":"deliveryAddress","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentVCard~1deliveryAddress\/title","op":"replace","value":"deliveryAddress"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentVCard~1deliveryAddress\/fragments","op":"replace","value":[{"kind":"identifier","text":"deliveryAddress"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentVCardEntry\/title","value":"SBSDKBarcodeDocumentVCardEntry"},{"value":[{"text":"SBSDKBarcodeDocumentVCardEntry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentVCardEntry\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentVCardEntry"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentVCardEntry\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentVCard\/title","value":"SBSDKBarcodeDocumentVCard","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentVCard\/fragments","value":[{"text":"SBSDKBarcodeDocumentVCard","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentVCard\/navigatorTitle","value":[{"text":"SBSDKBarcodeDocumentVCard","kind":"identifier"}],"op":"replace"}]}]}