{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentVCard"]]},"abstract":[{"type":"text","text":"Languages."}],"metadata":{"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"languages"}],"title":"languages","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentVCard(py)languages","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"languages"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentVCardEntry","text":"SBSDKBarcodeDocumentVCardEntry","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentVCard\/languages"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentvcard\/languages"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentvcard\/languages"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"languages","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentVCardEntry","kind":"typeIdentifier","text":"SBSDKBarcodeDocumentVCardEntry","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentVCardEntry"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentVCard/languages":{"title":"languages","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentvcard\/languages","role":"symbol","abstract":[{"type":"text","text":"Languages."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentVCard\/languages","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"languages","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeDocumentVCardEntry","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentVCardEntry","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"languages"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentVCardEntry":{"navigatorTitle":[{"text":"SBSDKBarcodeDocumentVCardEntry","kind":"identifier"}],"title":"SBSDKBarcodeDocumentVCardEntry","kind":"symbol","abstract":[{"type":"text","text":"VCard Entry."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDocumentVCardEntry"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentVCardEntry","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentvcardentry","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentVCard":{"navigatorTitle":[{"text":"SBSDKBarcodeDocumentVCard","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"VCard."}],"title":"SBSDKBarcodeDocumentVCard","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentVCard","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentvcard","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentVCard","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"languages"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"languages","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentVCardEntry","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentVCardEntry","text":"SBSDKBarcodeDocumentVCardEntry"},{"kind":"text","text":" * "},{"kind":"identifier","text":"languages"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentVCard~1languages\/title","value":"languages","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentVCard~1languages\/fragments","value":[{"text":"languages","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentVCardEntry\/title","value":"SBSDKBarcodeDocumentVCardEntry","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentVCardEntry"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentVCardEntry\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentVCard\/title","op":"replace","value":"SBSDKBarcodeDocumentVCard"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentVCard\/fragments","value":[{"text":"SBSDKBarcodeDocumentVCard","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}