{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType\/original"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"original","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefiletype\/original"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefiletype\/original"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType"]]},"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType@SBSDKDocumentPageFileTypeOriginal","roleHeading":"Case","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageFileTypeOriginal"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"original","kind":"identifier"}],"title":"SBSDKDocumentPageFileType.original"},"abstract":[{"type":"text","text":"The image is the uncropped full image that was captured from the camera."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileType/original":{"kind":"symbol","abstract":[{"text":"The image is the uncropped full image that was captured from the camera.","type":"text"}],"type":"topic","role":"symbol","title":"SBSDKDocumentPageFileType.original","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"original"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefiletype\/original","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageFileTypeOriginal"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType\/original"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileType":{"title":"SBSDKDocumentPageFileType","abstract":[{"text":"Enumeration of image type classifiers.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefiletype","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageFileType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPageFileType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKDocumentPageFileTypeOriginal","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKDocumentPageFileTypeOriginal","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKDocumentPageFileTypeOriginal"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentPageFileTypeOriginal","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType~1original\/title"},{"value":[{"text":"SBSDKDocumentPageFileTypeOriginal","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType~1original\/fragments"},{"value":"SBSDKDocumentPageFileType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType\/title"},{"value":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentPageFileType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType\/navigatorTitle"}]}]}