{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"title":"hash","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sound(py)hash","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"hash"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound\/hash","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2sound\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sound":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration for the sound."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound","role":"symbol","type":"topic","title":"SBSDKUI2Sound","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Sound"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Sound"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sound"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sound/hash":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2sound\/hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound\/hash","title":"hash","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"hash","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2Sound","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/title"},{"op":"replace","value":[{"text":"SBSDKUI2Sound","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2Sound","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}