{"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfiguration\/initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithResultAccumulationConfig:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKResultAccumulationConfiguration","text":"SBSDKResultAccumulationConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"resultAccumulationConfig"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldExcludeList:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fieldExcludeList"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurations:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKDocumentDataExtractorConfigurationElement *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configurations"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnCrops:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"returnCrops"},{"kind":"text","text":";"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfiguration\/initwithresultaccumulationconfig:fieldexcludelist:configurations:returncrops:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfiguration"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfiguration(im)initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"method","title":"initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfiguration":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfiguration","type":"topic","navigatorTitle":[{"text":"SBSDKDocumentDataExtractorConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfiguration","title":"SBSDKDocumentDataExtractorConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorConfiguration","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Configuration for the document data extractor.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResultAccumulationConfiguration":{"kind":"symbol","title":"SBSDKResultAccumulationConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkresultaccumulationconfiguration","abstract":[{"type":"text","text":"Configuration for how to accumulate results."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfiguration/initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfiguration\/initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:","navigatorTitle":[{"text":"initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfiguration\/initwithresultaccumulationconfig:fieldexcludelist:configurations:returncrops:","title":"initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithResultAccumulationConfig:fieldExcludeList:configurations:returnCrops:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfiguration\/title","op":"replace","value":"SBSDKDocumentDataExtractorConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentDataExtractorConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/title","op":"replace","value":"SBSDKResultAccumulationConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKResultAccumulationConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}