{"metadata":{"externalID":"s:10ScanbotSDK25SBSDKGenericDocumentFieldC16ValidationStatusO","modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationStatus"}],"title":"SBSDKGenericDocumentField.ValidationStatus","navigatorTitle":[{"text":"ValidationStatus","kind":"identifier"}],"roleHeading":"Enumeration"},"abstract":[{"text":"The fields validation status. Applicable only to fields that support some kind of validation, e.g. using check digits.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/ValidationStatus-swift.enum","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/ValidationStatus-swift.enum\/confirmed","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/ValidationStatus-swift.enum\/invalid","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/ValidationStatus-swift.enum\/undefined","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/ValidationStatus-swift.enum\/valid"],"anchor":"Enumeration-Cases","generated":true},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/ValidationStatus-swift.enum\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/ValidationStatus-swift.enum\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/ValidationStatus-swift.enum\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield\/validationstatus-swift.enum"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKGenericDocumentFieldValidationStatus) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationStatus"}],"languages":["swift"]}],"kind":"declarations"}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"type":"conformsTo"}],"references":{"doc://net.doo.ScanbotSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField/ValidationStatus-swift.enum":{"role":"symbol","navigatorTitle":[{"text":"ValidationStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"The fields validation status. Applicable only to fields that support some kind of validation, e.g. using check digits."}],"kind":"symbol","title":"SBSDKGenericDocumentField.ValidationStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/ValidationStatus-swift.enum","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield\/validationstatus-swift.enum","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationStatus","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField/ValidationStatus-swift.enum/invalid":{"abstract":[{"text":"Field value failed validation","type":"text"}],"type":"topic","title":"SBSDKGenericDocumentField.ValidationStatus.invalid","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield\/validationstatus-swift.enum\/invalid","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalid","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/ValidationStatus-swift.enum\/invalid"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField/ValidationStatus-swift.enum/confirmed":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield\/validationstatus-swift.enum\/confirmed","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmed"}],"abstract":[{"text":"The same field value was recognized in multiple frames, thereby confirming the value. Occurs only for fields that have no validation rules otherwise.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/ValidationStatus-swift.enum\/confirmed","title":"SBSDKGenericDocumentField.ValidationStatus.confirmed"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"title":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","abstract":[{"type":"text","text":"A generic document field."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField/ValidationStatus-swift.enum/undefined":{"title":"SBSDKGenericDocumentField.ValidationStatus.undefined","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"undefined"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/ValidationStatus-swift.enum\/undefined","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield\/validationstatus-swift.enum\/undefined","abstract":[{"type":"text","text":"Field does not support validation"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField/ValidationStatus-swift.enum/init(rawValue:)":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield\/validationstatus-swift.enum\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/ValidationStatus-swift.enum\/init(rawValue:)","abstract":[],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField/ValidationStatus-swift.enum/valid":{"title":"SBSDKGenericDocumentField.ValidationStatus.valid","abstract":[{"text":"Field value passed validation","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield\/validationstatus-swift.enum\/valid","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"valid"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/ValidationStatus-swift.enum\/valid","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField/ValidationStatus-swift.enum/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield\/validationstatus-swift.enum\/rawrepresentable-implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/ValidationStatus-swift.enum\/RawRepresentable-Implementations","type":"topic"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField/ValidationStatus-swift.enum/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/ValidationStatus-swift.enum\/Equatable-Implementations","kind":"article","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield\/validationstatus-swift.enum\/equatable-implementations","type":"topic"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title","value":"SBSDKGenericDocumentField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]}]}]}