{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/configuration","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"The receivers configuration object."}],"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerViewController(py)configuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerConfiguration"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"configuration","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","title":"configuration"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration","text":"SBSDKVehicleIdentificationNumberScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller\/configuration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller\/configuration"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerconfiguration","navigatorTitle":[{"text":"SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"A descriptor-like class to configure "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScanner"},{"text":".","type":"text"}],"kind":"symbol","title":"SBSDKVehicleIdentificationNumberScannerConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewController/configuration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController\/configuration","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerConfiguration"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller\/configuration","navigatorTitle":[{"text":"configuration","kind":"identifier"}],"abstract":[{"text":"The receivers configuration object.","type":"text"}],"kind":"symbol","title":"configuration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScanner":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScanner","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVehicleIdentificationNumberScanner","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscanner","navigatorTitle":[{"text":"SBSDKVehicleIdentificationNumberScanner","kind":"identifier"}],"abstract":[{"text":"A class to scan video frames or still images for vehicle identification numbers and validate it.","type":"text"}],"kind":"symbol","title":"SBSDKVehicleIdentificationNumberScanner"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller","title":"SBSDKVINScannerViewController","role":"symbol","navigatorTitle":[{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show a camera screen with the vehicle identification number scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"configuration","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"configuration","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration","text":"SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKVehicleIdentificationNumberScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScannerConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController~1configuration\/title","value":"configuration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController~1configuration\/fragments","value":[{"text":"configuration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner\/title","op":"replace","value":"SBSDKVehicleIdentificationNumberScanner"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner\/fragments","value":[{"text":"SBSDKVehicleIdentificationNumberScanner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/title","value":"SBSDKVINScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/fragments","value":[{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"op":"replace"}]}]}