{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscanningresult\/hash"]}],"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"hash","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"identifier","text":"hash"}],"title":"hash","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanningResult(py)hash"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanningResult"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanningResult\/hash"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScanningResult/hash":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanningResult\/hash","url":"\/documentation\/scanbotsdk\/sbsdkcheckscanningresult\/hash","type":"topic","title":"hash","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"hash","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScanningResult":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckScanningResult","kind":"identifier"}],"title":"SBSDKCheckScanningResult","url":"\/documentation\/scanbotsdk\/sbsdkcheckscanningresult","kind":"symbol","abstract":[{"text":"The result of check scanning.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanningResult","navigatorTitle":[{"text":"SBSDKCheckScanningResult","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanningResult\/title","value":"SBSDKCheckScanningResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanningResult\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckScanningResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanningResult\/navigatorTitle","value":[{"text":"SBSDKCheckScanningResult","kind":"identifier"}],"op":"replace"}]}]}