{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerIntroScreenConfiguration\/copyWithZone:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerIntroScreenConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerintroscreenconfiguration\/copywithzone:"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","title":"copyWithZone:","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerIntroScreenConfiguration(im)copyWithZone:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerIntroScreenConfiguration/copyWithZone:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerintroscreenconfiguration\/copywithzone:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerIntroScreenConfiguration\/copyWithZone:","role":"symbol","title":"copyWithZone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerIntroScreenConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MRZScannerIntroScreenConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerintroscreenconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerIntroScreenConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MRZScannerIntroScreenConfiguration"}],"title":"SBSDKUI2MRZScannerIntroScreenConfiguration","abstract":[{"type":"text","text":"Configuration of the introduction screen for the MRZ scanner."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2MRZScannerIntroScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerIntroScreenConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerIntroScreenConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerIntroScreenConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerIntroScreenConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerIntroScreenConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}