{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/fromJsonWithJson:","interfaceLanguage":"occ"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode","text":"SBSDKUI2FindAndPickScanningMode","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FindAndPickScanningMode","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method","symbolKind":"method","title":"fromJsonWithJson:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FindAndPickScanningMode(cm)fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode":{"navigatorTitle":[{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode","title":"SBSDKUI2FindAndPickScanningMode","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the Find and Pick barcode scanning mode."}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/fromJsonWithJson:":{"title":"fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/fromJsonWithJson:","role":"symbol","type":"topic","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/fromjsonwithjson:"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode\/title","op":"replace","value":"SBSDKUI2FindAndPickScanningMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2FindAndPickScanningMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}