{"kind":"symbol","abstract":[{"type":"text","text":"Applies counter-clockwise 90 degree rotations, polygon warping and filtering to the receiver and returns JPEG image data of the given compression\/quality."}],"metadata":{"externalID":"c:@CM@ScanbotDocumentScannerSDK@@objc(cs)UIImage(im)sbsdk_imageDataByProcessingWithRotations:polygon:filters:compression:lensCameraProperties:imageScale:","title":"sbsdk_imageDataByProcessing(rotations:polygon:filters:compression:lensCameraProperties:imageScale:)","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","extendedModule":"UIKit","modules":[{"name":"ScanbotDocumentScannerSDK","relatedModules":["UIKit"]}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sbsdk_imageDataByProcessing"},{"kind":"text","text":"("},{"text":"rotations","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"filters"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"compression","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":", ","kind":"text"},{"text":"lensCameraProperties","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLensCameraProperties","text":"SBSDKLensCameraProperties","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"imageScale"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/UIKit","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/UIKit\/UIImage"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/uikit\/uiimage\/sbsdk_imagedatabyprocessing(rotations:polygon:filters:compression:lenscameraproperties:imagescale:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(sbsdk_imageDataByProcessingWithRotations:polygon:filters:compression:lensCameraProperties:imageScale:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sbsdk_imageDataByProcessing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rotations"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon"},{"text":"?, ","kind":"text"},{"text":"filters","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter"},{"text":"], ","kind":"text"},{"text":"compression","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"text":"lensCameraProperties","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLensCameraProperties","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLensCameraProperties","text":"SBSDKLensCameraProperties"},{"text":"?, ","kind":"text"},{"text":"imageScale","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"rotations","content":[{"type":"paragraph","inlineContent":[{"text":"Number of 90 degree rotations to apply. Can be negative. Uses modulo arithmetics.","type":"text"}]}]},{"name":"polygon","content":[{"type":"paragraph","inlineContent":[{"text":"The polygon used to crop and perspective correct the image.","type":"text"}]}]},{"name":"filters","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The types of the filters to be applied."}]}]},{"name":"compression","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The JPEG compression\/quality setting. The range is 0.0 (low quality, small file) to 1.0 (high quality, large file)."}]}]},{"content":[{"inlineContent":[{"text":"Properties of the camera which captured the image or ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"lensCameraProperties"},{"name":"imageScale","content":[{"inlineContent":[{"text":"If the image has been scaled, compared to how it was captured from the camera, you must set the scaling factor here for proper cropping. Otherwise the resulting aspect ratio will be wrong. Set to 1.0 if the image must retain its original size.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The JPEG data of the processed image or ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the operation failed."}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/UIKit\/UIImage\/sbsdk_imageDataByProcessing(rotations:polygon:filters:compression:lensCameraProperties:imageScale:)"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 5.0.0"}],"title":"ScanbotDocumentScannerSDK","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLensCameraProperties":{"title":"SBSDKLensCameraProperties","type":"topic","abstract":[{"type":"text","text":"Encapsulates lens and camera properties. Can be used with polygonal image cropping to achieve a very accurate aspect ratio of the resulting image."},{"type":"text","text":" "},{"text":"If created from image image metadata, uses a dictionary of some known devices to lookup the values.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKLensCameraProperties","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklenscameraproperties","navigatorTitle":[{"text":"SBSDKLensCameraProperties","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLensCameraProperties"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter","type":"topic","navigatorTitle":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","abstract":[{"text":"The abstract class of each parametric filter.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKParametricFilter","kind":"identifier"}],"title":"SBSDKParametricFilter","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/UIKit/UIImage/sbsdk_imageDataByProcessing(rotations:polygon:filters:compression:lensCameraProperties:imageScale:)":{"kind":"symbol","abstract":[{"type":"text","text":"Applies counter-clockwise 90 degree rotations, polygon warping and filtering to the receiver and returns JPEG image data of the given compression\/quality."}],"url":"\/documentation\/scanbotdocumentscannersdk\/uikit\/uiimage\/sbsdk_imagedatabyprocessing(rotations:polygon:filters:compression:lenscameraproperties:imagescale:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/UIKit\/UIImage\/sbsdk_imageDataByProcessing(rotations:polygon:filters:compression:lensCameraProperties:imageScale:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sbsdk_imageDataByProcessing","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rotations"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon"},{"text":"?, ","kind":"text"},{"text":"filters","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter"},{"text":"], ","kind":"text"},{"text":"compression","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"text":"lensCameraProperties","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLensCameraProperties","kind":"typeIdentifier","text":"SBSDKLensCameraProperties"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"imageScale"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?"}],"title":"sbsdk_imageDataByProcessing(rotations:polygon:filters:compression:lensCameraProperties:imageScale:)","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygon":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPolygon"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon","abstract":[{"text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon","role":"symbol","title":"SBSDKPolygon","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/UIKit/UIImage":{"url":"\/documentation\/scanbotdocumentscannersdk\/uikit\/uiimage","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIImage"}],"abstract":[{"type":"text","text":"An "},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" class extension to perform basic image processing operations."},{"text":" ","type":"text"},{"type":"text","text":"Direct usage is not recommended for large images."},{"text":" ","type":"text"},{"type":"text","text":"queues and proper memory management."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/UIKit\/UIImage","fragments":[{"text":"extension","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"role":"symbol","kind":"symbol","title":"UIImage"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/UIKit":{"type":"topic","abstract":[],"title":"UIKit","role":"collection","url":"\/documentation\/scanbotdocumentscannersdk\/uikit","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/UIKit","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLensCameraProperties\/title","op":"replace","value":"SBSDKLensCameraProperties"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLensCameraProperties\/fragments","value":[{"text":"SBSDKLensCameraProperties","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/title","op":"replace","value":"SBSDKParametricFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKParametricFilter"}]},{"op":"replace","value":"SBSDKPolygon","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/title"},{"value":[{"text":"SBSDKPolygon","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}