{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/UIKit","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/UIKit\/UIImage"]]},"metadata":{"externalID":"c:@CM@ScanbotDocumentScannerSDK@@objc(cs)UIImage(im)sbsdk_imageWarpedByPolygon:andFilteredBy:lensCameraProperties:imageScale:","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK","relatedModules":["UIKit"]}],"title":"sbsdk_imageWarped(by:filters:lensCameraProperties:imageScale:)","extendedModule":"UIKit","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sbsdk_imageWarped","kind":"identifier"},{"text":"(","kind":"text"},{"text":"by","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"filters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"lensCameraProperties"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLensCameraProperties","text":"SBSDKLensCameraProperties"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"imageScale"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/UIKit\/UIImage\/sbsdk_imageWarped(by:filters:lensCameraProperties:imageScale:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/uikit\/uiimage\/sbsdk_imagewarped(by:filters:lenscameraproperties:imagescale:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Applies a polygon and a filter to the receiver. Faster than two sequential operations."}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(sbsdk_imageWarpedByPolygon:andFilteredBy:lensCameraProperties:imageScale:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbsdk_imageWarped","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"by"},{"text":" ","kind":"text"},{"text":"polygon","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier","text":"SBSDKPolygon"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"filters"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter"},{"kind":"text","text":"], "},{"text":"lensCameraProperties","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKLensCameraProperties","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLensCameraProperties","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLensCameraProperties"},{"kind":"text","text":"?, "},{"text":"imageScale","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The polygon used to crop and perspective correct the image."}]}],"name":"polygon"},{"name":"filters","content":[{"type":"paragraph","inlineContent":[{"text":"The types of the filters to be applied.","type":"text"}]}]},{"name":"lensCameraProperties","content":[{"inlineContent":[{"type":"text","text":"Properties of the camera which captured the image or "},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"imageScale","content":[{"inlineContent":[{"type":"text","text":"If the image has been scaled, compared to how it was captured from the camera, you must set the scaling factor here for proper cropping. Otherwise the resulting aspect ratio will be wrong. Set to 1.0 if the image must retain its original size."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The cropped, perspective corrected and filtered "},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the operation failed."}]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygon":{"title":"SBSDKPolygon","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon","abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKPolygon","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPolygon","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 5.2.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter":{"role":"symbol","abstract":[{"type":"text","text":"Base class for all parametric filters."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKParametricFilter"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","kind":"symbol","title":"SBSDKParametricFilter","navigatorTitle":[{"text":"SBSDKParametricFilter","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/UIKit/UIImage":{"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"text":"UIImage","kind":"identifier","preciseIdentifier":"c:objc(cs)UIImage"}],"kind":"symbol","abstract":[{"text":"An ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" class extension to perform basic image processing operations."},{"text":" ","type":"text"},{"text":"Direct usage is not recommended for large images.","type":"text"},{"text":" ","type":"text"},{"text":"queues and proper memory management.","type":"text"}],"navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/uikit\/uiimage","role":"symbol","title":"UIImage","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/UIKit\/UIImage","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/UIKit":{"kind":"symbol","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/uikit","role":"collection","title":"UIKit","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/UIKit","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/UIKit/UIImage/sbsdk_imageWarped(by:filters:lensCameraProperties:imageScale:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/UIKit\/UIImage\/sbsdk_imageWarped(by:filters:lensCameraProperties:imageScale:)","role":"symbol","type":"topic","title":"sbsdk_imageWarped(by:filters:lensCameraProperties:imageScale:)","url":"\/documentation\/scanbotdocumentscannersdk\/uikit\/uiimage\/sbsdk_imagewarped(by:filters:lenscameraproperties:imagescale:)","abstract":[{"type":"text","text":"Applies a polygon and a filter to the receiver. Faster than two sequential operations."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sbsdk_imageWarped"},{"text":"(","kind":"text"},{"text":"by","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"filters"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"lensCameraProperties"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLensCameraProperties","text":"SBSDKLensCameraProperties"},{"kind":"text","text":"?, "},{"text":"imageScale","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLensCameraProperties":{"role":"symbol","abstract":[{"type":"text","text":"Encapsulates lens and camera properties. Can be used with polygonal image cropping to achieve a very accurate aspect ratio of the resulting image."},{"text":" ","type":"text"},{"type":"text","text":"If created from image image metadata, uses a dictionary of some known devices to lookup the values."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLensCameraProperties","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklenscameraproperties","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLensCameraProperties","kind":"symbol","title":"SBSDKLensCameraProperties","navigatorTitle":[{"text":"SBSDKLensCameraProperties","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKPolygon","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/title","op":"replace"},{"value":[{"text":"SBSDKPolygon","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/title","value":"SBSDKParametricFilter","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/fragments"},{"op":"replace","value":"SBSDKLensCameraProperties","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLensCameraProperties\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLensCameraProperties\/fragments","value":[{"text":"SBSDKLensCameraProperties","kind":"identifier"}],"op":"replace"}]}]}