{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonLayer\/actionForKey:"},"kind":"symbol","metadata":{"roleHeading":"Instance Method","title":"actionForKey:","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygonLayer(im)actionForKey:","navigatorTitle":[{"text":"actionForKey:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"text","text":"- "},{"text":"actionForKey:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonLayer"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpolygonlayer\/actionforkey:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:Qoobjc(pl)CAAction","kind":"typeIdentifier","text":"id<CAAction>"},{"text":") ","kind":"text"},{"kind":"identifier","text":"actionForKey:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"event"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygonLayer/actionForKey:":{"role":"symbol","abstract":[],"title":"actionForKey:","url":"\/documentation\/scanbotsdk\/sbsdkpolygonlayer\/actionforkey:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonLayer\/actionForKey:","fragments":[{"kind":"text","text":"- "},{"text":"actionForKey:","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"actionForKey:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygonLayer":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonLayer","title":"SBSDKPolygonLayer","abstract":[{"type":"text","text":"A "},{"code":"CAShapeLayer","type":"codeVoice"},{"type":"text","text":" subclass that is used to draw bezier paths with fluid animation."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygonLayer","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygonlayer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygonLayer"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"SBSDKPolygonLayer","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygonLayer\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygonLayer\/fragments","value":[{"kind":"identifier","text":"SBSDKPolygonLayer"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygonLayer\/navigatorTitle","value":[{"text":"SBSDKPolygonLayer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}