{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot\/setupDefaultLicenseFailureHandler()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupDefaultLicenseFailureHandler"},{"kind":"text","text":"()"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"setupDefaultLicenseFailureHandler()","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)Scanbot(cm)setupDefaultLicenseFailureHandler","roleHeading":"Type Method","symbolKind":"method","navigatorTitle":[{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot"]]},"abstract":[{"text":"Sets up the default license failure handler which is being called when the license is invalid or the trial time expired.","type":"text"},{"text":" ","type":"text"},{"text":"The default handler logs the license error to the console.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbot\/setupdefaultlicensefailurehandler()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbot\/setupdefaultlicensefailurehandler()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/Scanbot/setupDefaultLicenseFailureHandler()":{"url":"\/documentation\/scanbotdocumentscannersdk\/scanbot\/setupdefaultlicensefailurehandler()","navigatorTitle":[{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"}],"title":"setupDefaultLicenseFailureHandler()","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Sets up the default license failure handler which is being called when the license is invalid or the trial time expired."},{"type":"text","text":" "},{"type":"text","text":"The default handler logs the license error to the console."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot\/setupDefaultLicenseFailureHandler()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/Scanbot":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Scanbot","kind":"identifier"}],"abstract":[{"text":"Main class of Scanbot SDK. Lets you install the license and allows basic configuration.","type":"text"}],"title":"Scanbot","navigatorTitle":[{"text":"Scanbot","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/scanbot"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","abstract":[{"text":"Version: 8.0.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"setupDefaultLicenseFailureHandler"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setupDefaultLicenseFailureHandler"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"setupDefaultLicenseFailureHandler","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot~1setupDefaultLicenseFailureHandler()\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setupDefaultLicenseFailureHandler"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot~1setupDefaultLicenseFailureHandler()\/fragments"},{"op":"replace","value":"Scanbot","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot\/title"},{"op":"replace","value":[{"text":"Scanbot","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot\/fragments"},{"op":"replace","value":[{"text":"Scanbot","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}