{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling\/reject","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmrzincompleteresulthandling\/reject"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmrzincompleteresulthandling\/reject"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reject"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Reject incomplete results. If any fields are missing or fail validation, the result document will be empty. Typically used for live scanning."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"case","title":"SBSDKMRZIncompleteResultHandling.reject","externalID":"c:@M@ScanbotSDK@E@SBSDKMRZIncompleteResultHandling@SBSDKMRZIncompleteResultHandlingReject","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reject"}],"navigatorTitle":[{"text":"SBSDKMRZIncompleteResultHandlingReject","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZIncompleteResultHandling/reject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling\/reject","role":"symbol","abstract":[{"type":"text","text":"Reject incomplete results. If any fields are missing or fail validation, the result document will be empty. Typically used for live scanning."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmrzincompleteresulthandling\/reject","kind":"symbol","title":"SBSDKMRZIncompleteResultHandling.reject","navigatorTitle":[{"text":"SBSDKMRZIncompleteResultHandlingReject","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reject","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZIncompleteResultHandling":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZIncompleteResultHandling"}],"title":"SBSDKMRZIncompleteResultHandling","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZIncompleteResultHandling"}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzincompleteresulthandling","abstract":[{"type":"text","text":"Defines how to handle incomplete MRZ results (e.g. caused by failed validation)."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKMRZIncompleteResultHandlingReject","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMRZIncompleteResultHandlingReject"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKMRZIncompleteResultHandlingReject","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling~1reject\/title","value":"SBSDKMRZIncompleteResultHandlingReject","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling~1reject\/fragments","value":[{"text":"SBSDKMRZIncompleteResultHandlingReject","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/title","value":"SBSDKMRZIncompleteResultHandling","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/fragments","op":"replace","value":[{"text":"SBSDKMRZIncompleteResultHandling","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKMRZIncompleteResultHandling"}]}]}]}