{"metadata":{"navigatorTitle":[{"text":"SBSDKDocumentDataExtractionModeSingleShot","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKDocumentDataExtractionMode.singleShot","roleHeading":"Case","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"singleShot","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDataExtractionMode@SBSDKDocumentDataExtractionModeSingleShot"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionMode"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"singleShot","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionMode\/singleShot"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionmode\/singleshot"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionmode\/singleshot"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The extractor will only use the current frame and will spend additional time to ensure the best possible result.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionMode":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractionMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionMode","navigatorTitle":[{"text":"SBSDKDocumentDataExtractionMode","kind":"identifier"}],"title":"SBSDKDocumentDataExtractionMode","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionmode","abstract":[{"type":"text","text":"The extraction mode."}],"type":"topic","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionMode/singleShot":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"singleShot","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentDataExtractionModeSingleShot","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionMode\/singleShot","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionmode\/singleshot","abstract":[{"type":"text","text":"The extractor will only use the current frame and will spend additional time to ensure the best possible result."}],"title":"SBSDKDocumentDataExtractionMode.singleShot"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKDocumentDataExtractionModeSingleShot","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionModeSingleShot"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionModeSingleShot"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionMode\/title","value":"SBSDKDocumentDataExtractionMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionMode\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionMode~1singleShot\/title","value":"SBSDKDocumentDataExtractionModeSingleShot","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionMode~1singleShot\/fragments","value":[{"text":"SBSDKDocumentDataExtractionModeSingleShot","kind":"identifier"}],"op":"replace"}]}]}