{"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/addressString1","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/addressString2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/diagnose","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/doctorNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/firstName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/healthInsuranceNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/insuranceProvider","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/insuredPersonNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/lastName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/placeOfOperationNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/status","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/undefined"]},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/init(rawValue:)"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/RawRepresentable-Implementations"]}],"sections":[],"metadata":{"symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificatePatientInfoFieldType","kind":"identifier"}],"roleHeading":"Enumeration","navigatorTitle":[{"text":"SBSDKMedicalCertificatePatientInfoFieldType","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificatePatientInfoFieldType","title":"SBSDKMedicalCertificatePatientInfoFieldType"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKMedicalCertificatePatientInfoFieldType) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType","interfaceLanguage":"swift"},"abstract":[{"text":"Type of a field in the patient info box.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/insuranceProvider":{"title":"SBSDKMedicalCertificatePatientInfoFieldType.insuranceProvider","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeInsuranceProvider"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insuranceProvider","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/insuranceProvider","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/insuranceprovider","abstract":[{"text":"Insurance provider (Krankenkasse bzw. Kostenträger).","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/doctorNumber":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"doctorNumber"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/doctorNumber","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/doctornumber","abstract":[{"type":"text","text":"Number of the doctor (Arzt-Nr.)."}],"kind":"symbol","title":"SBSDKMedicalCertificatePatientInfoFieldType.doctorNumber","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeDoctorNumber"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/status":{"type":"topic","title":"SBSDKMedicalCertificatePatientInfoFieldType.status","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/status","abstract":[{"type":"text","text":"Status."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/status","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeStatus"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType":{"navigatorTitle":[{"text":"SBSDKMedicalCertificatePatientInfoFieldType","kind":"identifier"}],"abstract":[{"type":"text","text":"Type of a field in the patient info box."}],"type":"topic","title":"SBSDKMedicalCertificatePatientInfoFieldType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificatePatientInfoFieldType","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/firstName":{"title":"SBSDKMedicalCertificatePatientInfoFieldType.firstName","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeFirstName"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/firstname","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/firstName","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstName"}],"abstract":[{"type":"text","text":"First name (Vorname des Versicherten)."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/addressString1":{"abstract":[{"type":"text","text":"First line of address."}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/addressstring1","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/addressString1","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addressString1","kind":"identifier"}],"type":"topic","title":"SBSDKMedicalCertificatePatientInfoFieldType.addressString1","navigatorTitle":[{"text":"SBSDKMedicalCertificatePatientInfoFieldTypeAddressString1","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/healthInsuranceNumber":{"title":"SBSDKMedicalCertificatePatientInfoFieldType.healthInsuranceNumber","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeHealthInsuranceNumber"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/healthInsuranceNumber","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/healthinsurancenumber","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Number of the health insurance provider (Kostenträgerkennung)."}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"healthInsuranceNumber","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/s12CaseIterableP":{"title":"Swift.CaseIterable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/init(rawValue:)":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/init(rawValue:)","abstract":[],"title":"init(rawValue:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/diagnose":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/diagnose","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diagnose","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificatePatientInfoFieldTypeDiagnose","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/diagnose","abstract":[{"text":"Diagnose.","type":"text"}],"title":"SBSDKMedicalCertificatePatientInfoFieldType.diagnose"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/insuredPersonNumber":{"title":"SBSDKMedicalCertificatePatientInfoFieldType.insuredPersonNumber","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"insuredPersonNumber"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/insuredpersonnumber","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/insuredPersonNumber","abstract":[{"type":"text","text":"Personal number of the insured person (Versicherten-Nr.)."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeInsuredPersonNumber"}]},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/placeOfOperationNumber":{"navigatorTitle":[{"text":"SBSDKMedicalCertificatePatientInfoFieldTypePlaceOfOperationNumber","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/placeofoperationnumber","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeOfOperationNumber","kind":"identifier"}],"abstract":[{"text":"Number of the place of operation (Betriebsstätten-Nr.).","type":"text"}],"type":"topic","kind":"symbol","title":"SBSDKMedicalCertificatePatientInfoFieldType.placeOfOperationNumber","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/placeOfOperationNumber"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/undefined":{"type":"topic","title":"SBSDKMedicalCertificatePatientInfoFieldType.undefined","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeUndefined"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"undefined"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/undefined","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/undefined","abstract":[{"type":"text","text":"Undefined."}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/addressString2":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeAddressString2"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/addressstring2","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/addressString2","abstract":[{"type":"text","text":"Second line of address."}],"kind":"symbol","type":"topic","title":"SBSDKMedicalCertificatePatientInfoFieldType.addressString2","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressString2"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/Equatable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/equatable-implementations","abstract":[],"kind":"article"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/lastName":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/lastName","title":"SBSDKMedicalCertificatePatientInfoFieldType.lastName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastName"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/lastname","type":"topic","abstract":[{"type":"text","text":"Last name (Name des Versicherten)."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeLastName"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/rawrepresentable-implementations","type":"topic","abstract":[],"kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalCertificatePatientInfoFieldType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKMedicalCertificatePatientInfoFieldType","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/addressString1","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/addressString2","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/diagnose","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/doctorNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/firstName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/healthInsuranceNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/insuranceProvider","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/insuredPersonNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/lastName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/placeOfOperationNumber","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/status","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/undefined"],"anchor":"Enumeration-Cases","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificatePatientInfoFieldType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1insuranceProvider\/title","value":"SBSDKMedicalCertificatePatientInfoFieldTypeInsuranceProvider"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1insuranceProvider\/fragments","value":[{"text":"SBSDKMedicalCertificatePatientInfoFieldTypeInsuranceProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1doctorNumber\/title","value":"SBSDKMedicalCertificatePatientInfoFieldTypeDoctorNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1doctorNumber\/fragments","value":[{"text":"SBSDKMedicalCertificatePatientInfoFieldTypeDoctorNumber","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1status\/title","value":"SBSDKMedicalCertificatePatientInfoFieldTypeStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1status\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType\/title","value":"SBSDKMedicalCertificatePatientInfoFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1firstName\/title","value":"SBSDKMedicalCertificatePatientInfoFieldTypeFirstName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1firstName\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeFirstName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1addressString1\/title","value":"SBSDKMedicalCertificatePatientInfoFieldTypeAddressString1"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1addressString1\/fragments","value":[{"text":"SBSDKMedicalCertificatePatientInfoFieldTypeAddressString1","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1healthInsuranceNumber\/title","value":"SBSDKMedicalCertificatePatientInfoFieldTypeHealthInsuranceNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1healthInsuranceNumber\/fragments","value":[{"text":"SBSDKMedicalCertificatePatientInfoFieldTypeHealthInsuranceNumber","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1diagnose\/title","value":"SBSDKMedicalCertificatePatientInfoFieldTypeDiagnose"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1diagnose\/fragments","value":[{"text":"SBSDKMedicalCertificatePatientInfoFieldTypeDiagnose","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1insuredPersonNumber\/title","value":"SBSDKMedicalCertificatePatientInfoFieldTypeInsuredPersonNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1insuredPersonNumber\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeInsuredPersonNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1placeOfOperationNumber\/title","value":"SBSDKMedicalCertificatePatientInfoFieldTypePlaceOfOperationNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1placeOfOperationNumber\/fragments","value":[{"text":"SBSDKMedicalCertificatePatientInfoFieldTypePlaceOfOperationNumber","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1undefined\/title","value":"SBSDKMedicalCertificatePatientInfoFieldTypeUndefined"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1undefined\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeUndefined"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1addressString2\/title","value":"SBSDKMedicalCertificatePatientInfoFieldTypeAddressString2"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1addressString2\/fragments","value":[{"text":"SBSDKMedicalCertificatePatientInfoFieldTypeAddressString2","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1lastName\/title","value":"SBSDKMedicalCertificatePatientInfoFieldTypeLastName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1lastName\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeLastName"}]}]}]}