{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKUI2CroppingScreenConfiguration) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CroppingScreenConfiguration"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"text":"Configuration of the screen for cropping the scanned pages.","type":"text"}],"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/init()"],"title":"Initializers","generated":true},{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/backgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/bottomBar","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/croppingHandlerColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/croppingPolygonColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/croppingPolygonMagneticLineColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/topBarBackButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/topBarConfirmButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/topBarTitle"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/toJson(configuration:)"],"title":"Instance Methods","generated":true}],"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingScreenConfiguration","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}],"title":"SBSDKUI2CroppingScreenConfiguration","symbolKind":"class","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","title":"Conforms To"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration/croppingPolygonColor":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/croppingPolygonColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"croppingPolygonColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration\/croppingpolygoncolor","role":"symbol","title":"croppingPolygonColor","navigatorTitle":[{"text":"croppingPolygonColor","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"The color of the cropping polygon.","type":"text"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration/croppingPolygonMagneticLineColor":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/croppingPolygonMagneticLineColor","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration\/croppingpolygonmagneticlinecolor","abstract":[{"type":"text","text":"The color of the magnetic lines on the cropping polygon."}],"title":"croppingPolygonMagneticLineColor","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"croppingPolygonMagneticLineColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"}],"kind":"symbol","navigatorTitle":[{"text":"croppingPolygonMagneticLineColor","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration/initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:":{"navigatorTitle":[{"text":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:","kind":"identifier"}],"kind":"symbol","type":"topic","title":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration\/initwithtopbarbackbutton:topbartitle:topbarconfirmbutton:backgroundcolor:croppinghandlercolor:croppingpolygoncolor:croppingpolygonmagneticlinecolor:bottombar:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingScreenConfiguration"}],"abstract":[{"text":"Configuration of the screen for cropping the scanned pages.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration","kind":"symbol","type":"topic","title":"SBSDKUI2CroppingScreenConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CroppingScreenConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration/topBarBackButton":{"navigatorTitle":[{"text":"topBarBackButton","kind":"identifier"}],"kind":"symbol","type":"topic","title":"topBarBackButton","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration\/topbarbackbutton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/topBarBackButton","abstract":[{"text":"Configuration of the ‘cancel’ button, located in the top bar.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarBackButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration/topBarConfirmButton":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarConfirmButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"}],"role":"symbol","abstract":[{"text":"Configuration of the ‘confirm’ button, located in the top bar.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration\/topbarconfirmbutton","title":"topBarConfirmButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/topBarConfirmButton","navigatorTitle":[{"text":"topBarConfirmButton","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration/isEqual:":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration\/isequal:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/isEqual:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration/croppingHandlerColor":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingHandlerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"}],"title":"croppingHandlerColor","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration\/croppinghandlercolor","navigatorTitle":[{"kind":"identifier","text":"croppingHandlerColor"}],"type":"topic","abstract":[{"type":"text","text":"The color of the cropping handles."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/croppingHandlerColor"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration/init()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/init()","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration\/init()","type":"topic","role":"symbol","title":"init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration/fromJsonWithJson:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/fromJsonWithJson:","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration\/fromjsonwithjson:","title":"fromJsonWithJson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"kind":"symbol","title":"SBSDKUI2Node","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2node","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Node"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Node"}],"abstract":[{"type":"text","text":"Abstract class for all the configurations."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration/backgroundColor":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration\/backgroundcolor","abstract":[{"type":"text","text":"The background color of the cropping screen."}],"role":"symbol","title":"backgroundColor","navigatorTitle":[{"text":"backgroundColor","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/backgroundColor","kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration/toJson(configuration:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/toJson(configuration:)","title":"toJson(configuration:)","role":"symbol","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration\/tojson(configuration:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration/hash":{"abstract":[],"title":"hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/hash","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration\/hash","role":"symbol","fragments":[{"text":"hash","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration/bottomBar":{"abstract":[{"type":"text","text":"Configuration of the bottom bar for the cropping screen."}],"navigatorTitle":[{"kind":"identifier","text":"bottomBar"}],"title":"bottomBar","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/bottomBar","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration\/bottombar","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBar"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingBottomBar","kind":"typeIdentifier","text":"SBSDKUI2CroppingBottomBar"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration/copyWithZone:":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"type":"topic","title":"copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration\/copywithzone:","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration/topBarTitle":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/topBarTitle","navigatorTitle":[{"kind":"identifier","text":"topBarTitle"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration\/topbartitle","title":"topBarTitle","kind":"symbol","abstract":[{"text":"Configuration of the title, located in the top bar.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKUI2CroppingScreenConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKUI2CroppingScreenConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2CroppingScreenConfiguration"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/backgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/bottomBar","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/croppingHandlerColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/croppingPolygonColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/croppingPolygonMagneticLineColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/topBarBackButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/topBarConfirmButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/topBarTitle"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:croppingHandlerColor:croppingPolygonColor:croppingPolygonMagneticLineColor:bottomBar:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/toJson(configuration:)"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/fromJsonWithJson:"],"anchor":"Type-Methods","title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"type":"conformsTo","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","text":"SBSDKUI2Node","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"croppingPolygonColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1croppingPolygonColor\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1croppingPolygonColor\/fragments","value":[{"kind":"identifier","text":"croppingPolygonColor"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1croppingPolygonMagneticLineColor\/title","value":"croppingPolygonMagneticLineColor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1croppingPolygonMagneticLineColor\/fragments","value":[{"kind":"identifier","text":"croppingPolygonMagneticLineColor"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration\/title","value":"SBSDKUI2CroppingScreenConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration\/fragments","value":[{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1topBarBackButton\/title","value":"topBarBackButton"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1topBarBackButton\/fragments","value":[{"kind":"identifier","text":"topBarBackButton"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1topBarConfirmButton\/title","value":"topBarConfirmButton"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1topBarConfirmButton\/fragments","value":[{"kind":"identifier","text":"topBarConfirmButton"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1croppingHandlerColor\/title","value":"croppingHandlerColor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1croppingHandlerColor\/fragments","value":[{"text":"croppingHandlerColor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title","value":"SBSDKUI2Node"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments","value":[{"text":"SBSDKUI2Node","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Node"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1backgroundColor\/title","value":"backgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1backgroundColor\/fragments","value":[{"kind":"identifier","text":"backgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1toJson(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1bottomBar\/title","value":"bottomBar"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1bottomBar\/fragments","value":[{"kind":"identifier","text":"bottomBar"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1topBarTitle\/title","value":"topBarTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1topBarTitle\/fragments","value":[{"text":"topBarTitle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}