{"abstract":[{"text":"Report of the suspicious data field verification.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport"]}],"metadata":{"title":"SBSDKFieldSuspiciousDataVerificationReport","symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldSuspiciousDataVerificationReport","role":"symbol","roleHeading":"Class","navigatorTitle":[{"text":"SBSDKFieldSuspiciousDataVerificationReport","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFieldSuspiciousDataVerificationReport","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/fieldFullName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/isSuspicious"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/toJson(configuration:)"],"anchor":"Instance-Methods","generated":true}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKFieldSuspiciousDataVerificationReport) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFieldSuspiciousDataVerificationReport","kind":"identifier"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldSuspiciousDataVerificationReport/fromJsonWithJson:":{"title":"fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport\/fromjsonwithjson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"abstract":[],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/fromJsonWithJson:","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldSuspiciousDataVerificationReport/copyWithZone:":{"kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport\/copywithzone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/copyWithZone:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldSuspiciousDataVerificationReport/initWithFieldFullName:isSuspicious:":{"url":"\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport\/initwithfieldfullname:issuspicious:","role":"symbol","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFieldFullName:isSuspicious:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFieldFullName:isSuspicious:"}],"title":"initWithFieldFullName:isSuspicious:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/initWithFieldFullName:isSuspicious:","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldSuspiciousDataVerificationReport/fieldFullName":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/fieldFullName","url":"\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport\/fieldfullname","title":"fieldFullName","abstract":[{"text":"Full name of the field that was considered during the verification.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fieldFullName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"fieldFullName","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldSuspiciousDataVerificationReport/isSuspicious":{"navigatorTitle":[{"kind":"identifier","text":"isSuspicious"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSuspicious"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isSuspicious","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/isSuspicious","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Shows whether the data in the field is suspicious, e.g. contains word “Sample” in the name."}],"url":"\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport\/issuspicious"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldSuspiciousDataVerificationReport":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFieldSuspiciousDataVerificationReport"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport","title":"SBSDKFieldSuspiciousDataVerificationReport","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFieldSuspiciousDataVerificationReport"}],"kind":"symbol","abstract":[{"type":"text","text":"Report of the suspicious data field verification."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldSuspiciousDataVerificationReport/isEqual:":{"title":"isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/isEqual:","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport\/isequal:"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldSuspiciousDataVerificationReport/toJson(configuration:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","title":"toJson(configuration:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/toJson(configuration:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport\/tojson(configuration:)","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldSuspiciousDataVerificationReport/hash":{"type":"topic","role":"symbol","fragments":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/hash","title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport\/hash","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"SBSDKFieldSuspiciousDataVerificationReport","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKFieldSuspiciousDataVerificationReport"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKFieldSuspiciousDataVerificationReport"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/fieldFullName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/isSuspicious"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/initWithFieldFullName:isSuspicious:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/toJson(configuration:)"],"anchor":"Instance-Methods"},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/fromJsonWithJson:"],"anchor":"Type-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"title":"Conforms To"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFieldSuspiciousDataVerificationReport"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"fieldFullName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport~1fieldFullName\/title"},{"value":[{"text":"fieldFullName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport~1fieldFullName\/fragments"},{"value":"isSuspicious","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport~1isSuspicious\/title"},{"value":[{"kind":"identifier","text":"isSuspicious"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport~1isSuspicious\/fragments"},{"value":"SBSDKFieldSuspiciousDataVerificationReport","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport\/title"},{"value":[{"text":"SBSDKFieldSuspiciousDataVerificationReport","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKFieldSuspiciousDataVerificationReport"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport\/navigatorTitle"},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport~1toJson(configuration:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport~1toJson(configuration:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}