{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Configuration of the screen for detecting credit card data."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardScannerScreenConfiguration","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerScreenConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenConfiguration"}],"symbolKind":"class","role":"symbol","title":"SBSDKUI2CreditCardScannerScreenConfiguration","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/init()"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/actionBar","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/backgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/cameraConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/cameraPermission","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/exampleOverlayVisible","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/incompleteDataOverlay","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/introScreen","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/keepScreenOn","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/localization","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/palette","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/scanIncompleteDataTimeout","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/scanStatusUserGuidance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/scannerConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/scanningProgress","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/screen","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/sound","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/successOverlay","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/topBar","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/topBarOpenIntroScreenButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/topUserGuidance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/version","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/vibration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/viewFinder"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2CreditCardScannerScreenConfiguration) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenConfiguration"}],"platforms":["iOS"]}]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/screen":{"title":"screen","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"screen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"screen"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/screen","abstract":[{"text":"The configuration object should be applied for this screen.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/screen"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/copyWithZone:":{"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"role":"symbol","title":"copyWithZone:","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/copywithzone:","abstract":[],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/copyWithZone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:scanStatusUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:exampleOverlayVisible:scanningProgress:scanIncompleteDataTimeout:successOverlay:incompleteDataOverlay:sound:vibration:keepScreenOn:":{"kind":"symbol","title":"initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:scanStatusUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:exampleOverlayVisible:scanningProgress:scanIncompleteDataTimeout:successOverlay:incompleteDataOverlay:sound:vibration:keepScreenOn:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:scanStatusUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:exampleOverlayVisible:scanningProgress:scanIncompleteDataTimeout:successOverlay:incompleteDataOverlay:sound:vibration:keepScreenOn:","type":"topic","navigatorTitle":[{"text":"initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:scanStatusUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:exampleOverlayVisible:scanningProgress:scanIncompleteDataTimeout:successOverlay:incompleteDataOverlay:sound:vibration:keepScreenOn:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:scanStatusUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:exampleOverlayVisible:scanningProgress:scanIncompleteDataTimeout:successOverlay:incompleteDataOverlay:sound:vibration:keepScreenOn:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/initwithversion:screen:localization:palette:backgroundcolor:cameraconfiguration:camerapermission:topuserguidance:scanstatususerguidance:topbar:topbaropenintroscreenbutton:introscreen:actionbar:viewfinder:scannerconfiguration:exampleoverlayv-43sen"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/topUserGuidance":{"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"topUserGuidance"}],"title":"topUserGuidance","abstract":[{"type":"text","text":"Configuration of the top user guidance."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/topuserguidance","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/topUserGuidance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topUserGuidance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","text":"SBSDKUI2UserGuidanceConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/hash":{"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/hash","abstract":[],"fragments":[{"text":"hash","kind":"identifier"}],"title":"hash","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/hash","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/localization":{"abstract":[{"type":"text","text":"Configuration of the all strings for credit card scanner screen."}],"title":"localization","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localization"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"typeIdentifier","text":"SBSDKUI2CreditCardScannerScreenTextLocalization"}],"navigatorTitle":[{"kind":"identifier","text":"localization"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/localization","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/localization","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/scannerConfiguration":{"abstract":[{"text":"Configuration for the credit card recognizer.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/scannerConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/scannerconfiguration","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scannerConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCreditCardScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerConfiguration","kind":"typeIdentifier"}],"title":"scannerConfiguration","kind":"symbol","navigatorTitle":[{"text":"scannerConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/viewFinder":{"navigatorTitle":[{"kind":"identifier","text":"viewFinder"}],"title":"viewFinder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewFinder"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PermanentViewFinderConfiguration","kind":"typeIdentifier","text":"SBSDKUI2PermanentViewFinderConfiguration"}],"abstract":[{"text":"Configuration of the view finder.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/viewFinder","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/viewfinder","kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/fromJsonWithJson:":{"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/fromjsonwithjson:","kind":"symbol","title":"fromJsonWithJson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}]},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/incompleteDataOverlay":{"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/incompletedataoverlay","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/incompleteDataOverlay","title":"incompleteDataOverlay","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incompleteDataOverlay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ScanCompletionOverlay","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanCompletionOverlay"}],"abstract":[{"text":"Configuration of the success overlay.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"incompleteDataOverlay","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/topBar":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/topBar","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"topBar","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TopBarConfiguration","kind":"typeIdentifier","text":"SBSDKUI2TopBarConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/topbar","abstract":[{"type":"text","text":"Configuration of the top bar on the credit card scanner screen."}],"title":"topBar","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"topBar"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/palette":{"kind":"symbol","abstract":[{"type":"text","text":"Define the screen’s base color values from which other colors are derived."}],"navigatorTitle":[{"kind":"identifier","text":"palette"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"palette"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Palette","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Palette"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/palette","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/palette","title":"palette"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/toJson(configuration:)":{"type":"topic","title":"toJson(configuration:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/toJson(configuration:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/tojson(configuration:)","kind":"symbol","role":"symbol","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/vibration":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/vibration","abstract":[{"type":"text","text":"Configuration of the vibration feedback."}],"navigatorTitle":[{"kind":"identifier","text":"vibration"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vibration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Vibration","kind":"typeIdentifier","text":"SBSDKUI2Vibration"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/vibration","title":"vibration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/scanStatusUserGuidance":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/scanStatusUserGuidance","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/scanstatususerguidance","type":"topic","title":"scanStatusUserGuidance","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanStatusUserGuidance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CreditCardScanGuidanceConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScanGuidanceConfiguration"}],"navigatorTitle":[{"text":"scanStatusUserGuidance","kind":"identifier"}],"abstract":[{"text":"Configuration of the user guidance for the scanning status.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/successOverlay":{"navigatorTitle":[{"kind":"identifier","text":"successOverlay"}],"abstract":[{"type":"text","text":"Configuration of the success overlay."}],"title":"successOverlay","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/successOverlay","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/successoverlay","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"successOverlay"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanCompletionOverlay","kind":"typeIdentifier","text":"SBSDKUI2ScanCompletionOverlay"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/sound":{"navigatorTitle":[{"kind":"identifier","text":"sound"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Sound","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sound"}],"abstract":[{"type":"text","text":"Configuration of the scan confirmation sound."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/sound","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/sound","kind":"symbol","title":"sound","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/isEqual:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/isequal:","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/isEqual:","role":"symbol","title":"isEqual:"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenConfiguration"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration","role":"symbol","kind":"symbol","abstract":[{"text":"Configuration of the screen for detecting credit card data.","type":"text"}],"title":"SBSDKUI2CreditCardScannerScreenConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/init()":{"abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/init()","kind":"symbol","title":"init()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/scanIncompleteDataTimeout":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/scanIncompleteDataTimeout","title":"scanIncompleteDataTimeout","abstract":[{"text":"Timeout for the scan process. If the scan process takes longer than this value, the incomplete result will be returned.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/scanincompletedatatimeout","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"scanIncompleteDataTimeout","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanIncompleteDataTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/keepScreenOn":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keepScreenOn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/keepscreenon","type":"topic","title":"keepScreenOn","abstract":[{"type":"text","text":"If enabled, the screen will not turn off while the credit card scanner is active."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/keepScreenOn","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"keepScreenOn"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/introScreen":{"role":"symbol","abstract":[{"type":"text","text":"Configuration of the introduction screen for the credit card scanner."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"introScreen","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CreditCardScannerIntroScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerIntroScreenConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/introscreen","navigatorTitle":[{"text":"introScreen","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/introScreen","type":"topic","kind":"symbol","title":"introScreen"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/version":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"version","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"version","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Version number of the configuration object."}],"role":"symbol","title":"version","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/version","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/version"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/topBarOpenIntroScreenButton":{"abstract":[{"text":"Configuration of the button in the top bar that opens the introduction screen.","type":"text"}],"role":"symbol","title":"topBarOpenIntroScreenButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/topBarOpenIntroScreenButton","kind":"symbol","navigatorTitle":[{"text":"topBarOpenIntroScreenButton","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/topbaropenintroscreenbutton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarOpenIntroScreenButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","text":"SBSDKUI2IconButton","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/actionBar":{"role":"symbol","navigatorTitle":[{"text":"actionBar","kind":"identifier"}],"title":"actionBar","type":"topic","abstract":[{"text":"Configuration of the action bar.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/actionbar","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/actionBar","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionBar","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ActionBarConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ActionBarConfiguration","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/exampleOverlayVisible":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/exampleoverlayvisible","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/exampleOverlayVisible","title":"exampleOverlayVisible","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exampleOverlayVisible","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"text":"Flag to show or hide the preset button.","type":"text"}],"navigatorTitle":[{"text":"exampleOverlayVisible","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"abstract":[{"text":"Abstract class for all the configurations.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2node","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Node","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Node","kind":"identifier"}],"kind":"symbol","title":"SBSDKUI2Node","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/backgroundColor":{"navigatorTitle":[{"kind":"identifier","text":"backgroundColor"}],"title":"backgroundColor","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/backgroundcolor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/backgroundColor","abstract":[{"type":"text","text":"The background color of the credit card scanner screen."}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/cameraConfiguration":{"abstract":[{"type":"text","text":"Configuration of the camera behavior."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/cameraconfiguration","title":"cameraConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cameraConfiguration"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/cameraConfiguration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2CameraConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraConfiguration"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/scanningProgress":{"navigatorTitle":[{"text":"scanningProgress","kind":"identifier"}],"title":"scanningProgress","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/scanningProgress","abstract":[{"text":"Configuration of visualization of the scanning progress.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/scanningprogress","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanningProgress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CreditCardScanningProgressConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScanningProgressConfiguration"}]},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/cameraPermission":{"navigatorTitle":[{"kind":"identifier","text":"cameraPermission"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the dialog for requesting camera permissions."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/camerapermission","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/cameraPermission","title":"cameraPermission","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermission"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen","kind":"typeIdentifier","text":"SBSDKUI2CameraPermissionScreen"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKUI2CreditCardScannerScreenConfiguration","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenConfiguration"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenConfiguration"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/actionBar","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/backgroundColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/cameraConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/cameraPermission","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/exampleOverlayVisible","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/incompleteDataOverlay","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/introScreen","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/keepScreenOn","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/localization","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/palette","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/scanIncompleteDataTimeout","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/scanStatusUserGuidance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/scannerConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/scanningProgress","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/screen","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/sound","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/successOverlay","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/topBar","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/topBarOpenIntroScreenButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/topUserGuidance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/version","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/vibration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/viewFinder"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:scanStatusUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:exampleOverlayVisible:scanningProgress:scanIncompleteDataTimeout:successOverlay:incompleteDataOverlay:sound:vibration:keepScreenOn:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/fromJsonWithJson:"],"generated":true,"anchor":"Type-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"type":"conformsTo","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"SBSDKUI2Node","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1screen\/title","op":"replace","value":"screen"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1screen\/fragments","op":"replace","value":[{"kind":"identifier","text":"screen"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1topUserGuidance\/title","op":"replace","value":"topUserGuidance"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1topUserGuidance\/fragments","op":"replace","value":[{"kind":"identifier","text":"topUserGuidance"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1localization\/title","op":"replace","value":"localization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1localization\/fragments","op":"replace","value":[{"text":"localization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1scannerConfiguration\/title","op":"replace","value":"scannerConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1scannerConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"scannerConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1viewFinder\/title","op":"replace","value":"viewFinder"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1viewFinder\/fragments","op":"replace","value":[{"text":"viewFinder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1incompleteDataOverlay\/title","op":"replace","value":"incompleteDataOverlay"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1incompleteDataOverlay\/fragments","op":"replace","value":[{"kind":"identifier","text":"incompleteDataOverlay"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1topBar\/title","op":"replace","value":"topBar"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1topBar\/fragments","op":"replace","value":[{"kind":"identifier","text":"topBar"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1palette\/title","op":"replace","value":"palette"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1palette\/fragments","op":"replace","value":[{"text":"palette","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1toJson(configuration:)\/title","op":"replace","value":"toJsonWithConfiguration:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1toJson(configuration:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1vibration\/title","op":"replace","value":"vibration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1vibration\/fragments","op":"replace","value":[{"kind":"identifier","text":"vibration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1scanStatusUserGuidance\/title","op":"replace","value":"scanStatusUserGuidance"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1scanStatusUserGuidance\/fragments","op":"replace","value":[{"text":"scanStatusUserGuidance","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1successOverlay\/title","op":"replace","value":"successOverlay"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1successOverlay\/fragments","op":"replace","value":[{"text":"successOverlay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1sound\/title","op":"replace","value":"sound"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1sound\/fragments","op":"replace","value":[{"text":"sound","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration\/title","op":"replace","value":"SBSDKUI2CreditCardScannerScreenConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2CreditCardScannerScreenConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CreditCardScannerScreenConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1init()\/title","op":"replace","value":"init"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1init()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1scanIncompleteDataTimeout\/title","op":"replace","value":"scanIncompleteDataTimeout"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1scanIncompleteDataTimeout\/fragments","op":"replace","value":[{"text":"scanIncompleteDataTimeout","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1keepScreenOn\/title","op":"replace","value":"keepScreenOn"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1keepScreenOn\/fragments","op":"replace","value":[{"text":"keepScreenOn","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1introScreen\/title","op":"replace","value":"introScreen"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1introScreen\/fragments","op":"replace","value":[{"text":"introScreen","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1version\/title","op":"replace","value":"version"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1version\/fragments","op":"replace","value":[{"kind":"identifier","text":"version"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1topBarOpenIntroScreenButton\/title","op":"replace","value":"topBarOpenIntroScreenButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1topBarOpenIntroScreenButton\/fragments","op":"replace","value":[{"kind":"identifier","text":"topBarOpenIntroScreenButton"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1actionBar\/title","op":"replace","value":"actionBar"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1actionBar\/fragments","op":"replace","value":[{"kind":"identifier","text":"actionBar"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1exampleOverlayVisible\/title","op":"replace","value":"exampleOverlayVisible"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1exampleOverlayVisible\/fragments","op":"replace","value":[{"kind":"identifier","text":"exampleOverlayVisible"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title","op":"replace","value":"SBSDKUI2Node"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Node"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2Node","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1backgroundColor\/title","op":"replace","value":"backgroundColor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1backgroundColor\/fragments","op":"replace","value":[{"text":"backgroundColor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1cameraConfiguration\/title","op":"replace","value":"cameraConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1cameraConfiguration\/fragments","op":"replace","value":[{"text":"cameraConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1scanningProgress\/title","op":"replace","value":"scanningProgress"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1scanningProgress\/fragments","op":"replace","value":[{"kind":"identifier","text":"scanningProgress"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1cameraPermission\/title","op":"replace","value":"cameraPermission"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1cameraPermission\/fragments","op":"replace","value":[{"kind":"identifier","text":"cameraPermission"}]}]}]}