{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorType"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKErrorType","kind":"identifier"}],"title":"SBSDKErrorType","externalID":"c:@M@ScanbotSDK@E@SBSDKErrorType","roleHeading":"Enumeration","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"enum"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrortype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrortype"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"An Objective-C compatible enum representing the types of errors that can occur within the Scanbot SDK."},{"type":"text","text":" "},{"type":"text","text":"Each case corresponds to a specific error code."}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/componentUnavailable","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/illegalState","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/invalidArgument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/invalidData","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/invalidImageRef","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/invalidLicense","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/ioError","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/nullPointer","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/operationCanceled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/outOfMemory","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/timeout","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/unknownError"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKErrorType"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/Equatable-Implementations":{"role":"collectionGroup","type":"topic","title":"Equatable Implementations","url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/equatable-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/Equatable-Implementations","kind":"article","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/invalidLicense":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidLicense"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/invalidLicense","url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/invalidlicense","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeInvalidLicense"}],"abstract":[{"type":"text","text":"The SDK license is invalid or license requirements are not satisfied."}],"title":"SBSDKErrorType.invalidLicense","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/invalidImageRef":{"abstract":[{"type":"text","text":"An invalid image reference was provided or the image data is corrupted."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/invalidImageRef","role":"symbol","title":"SBSDKErrorType.invalidImageRef","url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/invalidimageref","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidImageRef","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKErrorTypeInvalidImageRef","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType","abstract":[{"type":"text","text":"An Objective-C compatible enum representing the types of errors that can occur within the Scanbot SDK."},{"type":"text","text":" "},{"type":"text","text":"Each case corresponds to a specific error code."}],"url":"\/documentation\/scanbotsdk\/sbsdkerrortype","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKErrorType"}],"type":"topic","title":"SBSDKErrorType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorType"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/invalidData":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidData"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The provided data is invalid, corrupted, or in an unexpected format."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/invaliddata","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeInvalidData"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/invalidData","title":"SBSDKErrorType.invalidData"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/nullPointer":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nullPointer","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/nullpointer","kind":"symbol","abstract":[{"type":"text","text":"A null pointer was encountered where a valid reference was expected."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/nullPointer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeNullPointer"}],"title":"SBSDKErrorType.nullPointer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/illegalState":{"title":"SBSDKErrorType.illegalState","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"illegalState"}],"abstract":[{"type":"text","text":"The SDK is in an illegal or inconsistent state for the requested operation."}],"url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/illegalstate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/illegalState","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeIllegalState"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/invalidArgument":{"url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/invalidargument","title":"SBSDKErrorType.invalidArgument","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/invalidArgument","type":"topic","abstract":[{"type":"text","text":"An invalid argument was passed to an SDK function or method."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidArgument"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeInvalidArgument"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/componentUnavailable":{"title":"SBSDKErrorType.componentUnavailable","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/componentUnavailable","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeComponentUnavailable"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"componentUnavailable"}],"abstract":[{"type":"text","text":"A required SDK component is unavailable or not properly initialized."}],"url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/componentunavailable"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/RawRepresentable-Implementations","abstract":[],"kind":"article","role":"collectionGroup","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/rawrepresentable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/timeout":{"kind":"symbol","type":"topic","role":"symbol","title":"SBSDKErrorType.timeout","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/timeout","url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/timeout","abstract":[{"type":"text","text":"The operation timed out before completion."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeout"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeTimeout"}]},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/operationCanceled":{"title":"SBSDKErrorType.operationCanceled","navigatorTitle":[{"text":"SBSDKErrorTypeOperationCanceled","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/operationCanceled","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"operationCanceled","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/operationcanceled","type":"topic","abstract":[{"type":"text","text":"The operation was canceled before completion or by user."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/init(rawValue:)":{"url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/init(rawvalue:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/init(rawValue:)","abstract":[],"title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/outOfMemory":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/outofmemory","role":"symbol","kind":"symbol","title":"SBSDKErrorType.outOfMemory","abstract":[{"type":"text","text":"The system ran out of memory during the operation."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"outOfMemory","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKErrorTypeOutOfMemory","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/outOfMemory"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/ioError":{"title":"SBSDKErrorType.ioError","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/ioError","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeIoError"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ioError"}],"abstract":[{"type":"text","text":"An input\/output error occurred during file or data operations."}],"url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/ioerror"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/unknownError":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/unknownError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKErrorTypeUnknownError","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"An unknown or unexpected error occurred.","type":"text"}],"title":"SBSDKErrorType.unknownError","url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/unknownerror"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKErrorType","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKErrorType"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKErrorType"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/componentUnavailable","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/illegalState","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/invalidArgument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/invalidData","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/invalidImageRef","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/invalidLicense","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/ioError","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/nullPointer","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/operationCanceled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/outOfMemory","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/timeout","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/unknownError"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKErrorType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKErrorTypeInvalidLicense","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1invalidLicense\/title"},{"value":[{"text":"SBSDKErrorTypeInvalidLicense","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1invalidLicense\/fragments"},{"value":"SBSDKErrorTypeInvalidImageRef","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1invalidImageRef\/title"},{"value":[{"kind":"identifier","text":"SBSDKErrorTypeInvalidImageRef"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1invalidImageRef\/fragments"},{"value":"SBSDKErrorType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType\/title"},{"value":[{"text":"SBSDKErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKErrorType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType\/navigatorTitle"},{"value":"SBSDKErrorTypeInvalidData","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1invalidData\/title"},{"value":[{"text":"SBSDKErrorTypeInvalidData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1invalidData\/fragments"},{"value":"SBSDKErrorTypeNullPointer","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1nullPointer\/title"},{"value":[{"text":"SBSDKErrorTypeNullPointer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1nullPointer\/fragments"},{"value":"SBSDKErrorTypeIllegalState","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1illegalState\/title"},{"value":[{"text":"SBSDKErrorTypeIllegalState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1illegalState\/fragments"},{"value":"SBSDKErrorTypeInvalidArgument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1invalidArgument\/title"},{"value":[{"kind":"identifier","text":"SBSDKErrorTypeInvalidArgument"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1invalidArgument\/fragments"},{"value":"SBSDKErrorTypeComponentUnavailable","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1componentUnavailable\/title"},{"value":[{"kind":"identifier","text":"SBSDKErrorTypeComponentUnavailable"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1componentUnavailable\/fragments"},{"value":"SBSDKErrorTypeTimeout","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1timeout\/title"},{"value":[{"text":"SBSDKErrorTypeTimeout","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1timeout\/fragments"},{"value":"SBSDKErrorTypeOperationCanceled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1operationCanceled\/title"},{"value":[{"text":"SBSDKErrorTypeOperationCanceled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1operationCanceled\/fragments"},{"value":"SBSDKErrorTypeOutOfMemory","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1outOfMemory\/title"},{"value":[{"kind":"identifier","text":"SBSDKErrorTypeOutOfMemory"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1outOfMemory\/fragments"},{"value":"SBSDKErrorTypeIoError","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1ioError\/title"},{"value":[{"text":"SBSDKErrorTypeIoError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1ioError\/fragments"},{"value":"SBSDKErrorTypeUnknownError","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1unknownError\/title"},{"value":[{"text":"SBSDKErrorTypeUnknownError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1unknownError\/fragments"}]}]}