{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKImageManipulator) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageManipulator","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Class","navigatorTitle":[{"text":"SBSDKImageManipulator","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageManipulator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageManipulator"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKImageManipulator","symbolKind":"class","role":"symbol"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageManipulator","interfaceLanguage":"swift"},"abstract":[{"text":"API for image processing. If applicable on the platform, all the methods return images with the same liveness flag as the input image.","type":"text"}],"sections":[],"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageManipulator\/init()"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageManipulator\/cropRect(image:rect:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageManipulator\/flip(image:origin:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageManipulator\/resize(image:size:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageManipulator\/rotate(image:rotation:)"],"generated":true}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagemanipulator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagemanipulator"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageManipulator/cropRect(image:rect:)":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Crops out the given rectangle from the image."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cropRectWithImage:rect:error:"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagemanipulator\/croprect(image:rect:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageManipulator\/cropRect(image:rect:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cropRect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef"}],"title":"cropRect(image:rect:)"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageManipulator/init()":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Initialize the image processor."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagemanipulator\/init()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageManipulator\/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageManipulator/rotate(image:rotation:)":{"role":"symbol","type":"topic","abstract":[{"text":"Rotates the given image by the given angle.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"rotateWithImage:rotation:error:"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagemanipulator\/rotate(image:rotation:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageManipulator\/rotate(image:rotation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rotate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRotation","text":"SBSDKImageRotation"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"}],"title":"rotate(image:rotation:)"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageManipulator/flip(image:origin:)":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagemanipulator\/flip(image:origin:)","navigatorTitle":[{"text":"flipWithImage:origin:error:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageManipulator\/flip(image:origin:)","role":"symbol","abstract":[{"text":"Flips the given image horizontally or vertically.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"flip"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageOrigin","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageOrigin"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"}],"title":"flip(image:origin:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageManipulator/resize(image:size:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"},{"text":", ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagemanipulator\/resize(image:size:)","role":"symbol","title":"resize(image:size:)","navigatorTitle":[{"text":"resizeWithImage:size:error:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageManipulator\/resize(image:size:)","abstract":[{"type":"text","text":"Resizes the given image to the given size."}],"type":"topic"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageManipulator":{"abstract":[{"text":"API for image processing. If applicable on the platform, all the methods return images with the same liveness flag as the input image.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageManipulator","title":"SBSDKImageManipulator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageManipulator","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKImageManipulator","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagemanipulator","kind":"symbol"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKImageManipulator","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageManipulator"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SBSDKImageManipulator","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageManipulator\/cropRect(image:rect:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageManipulator\/flip(image:origin:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageManipulator\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageManipulator\/resize(image:size:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageManipulator\/rotate(image:rotation:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageManipulator","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"cropRectWithImage:rect:error:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageManipulator~1cropRect(image:rect:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cropRectWithImage:rect:error:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageManipulator~1cropRect(image:rect:)\/fragments","op":"replace"},{"value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageManipulator~1init()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageManipulator~1init()\/fragments","op":"replace"},{"value":"rotateWithImage:rotation:error:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageManipulator~1rotate(image:rotation:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"rotateWithImage:rotation:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageManipulator~1rotate(image:rotation:)\/fragments","op":"replace"},{"value":"flipWithImage:origin:error:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageManipulator~1flip(image:origin:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"flipWithImage:origin:error:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageManipulator~1flip(image:origin:)\/fragments","op":"replace"},{"value":"resizeWithImage:size:error:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageManipulator~1resize(image:size:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"resizeWithImage:size:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageManipulator~1resize(image:size:)\/fragments","op":"replace"},{"value":"SBSDKImageManipulator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageManipulator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageManipulator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageManipulator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageManipulator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageManipulator\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}