{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode"},"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/init()"],"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/accessibilityDescription","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/pageCounter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/text"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/toJson(configuration:)"],"anchor":"Instance-Methods"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2textwithbadgebuttonmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2textwithbadgebuttonmode"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2TextWithBadgeButtonMode) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TextWithBadgeButtonMode","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextWithBadgeButtonMode"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextWithBadgeButtonMode","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Class","symbolKind":"class","title":"SBSDKUI2TextWithBadgeButtonMode","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextWithBadgeButtonMode"}]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the ‘preview’ button in ‘text with badge button mode’."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextWithBadgeButtonMode/isEqual:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2textwithbadgebuttonmode\/isequal:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/isEqual:","title":"isEqual:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextWithBadgeButtonMode":{"abstract":[{"type":"text","text":"Configuration of the ‘preview’ button in ‘text with badge button mode’."}],"title":"SBSDKUI2TextWithBadgeButtonMode","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2textwithbadgebuttonmode","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextWithBadgeButtonMode"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextWithBadgeButtonMode"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextWithBadgeButtonMode/toJson(configuration:)":{"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textwithbadgebuttonmode\/tojson(configuration:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/toJson(configuration:)","type":"topic","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"title":"toJson(configuration:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextWithBadgeButtonMode/fromJsonWithJson:":{"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/fromJsonWithJson:","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2textwithbadgebuttonmode\/fromjsonwithjson:","title":"fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextWithBadgeButtonMode/hash":{"abstract":[],"title":"hash","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2textwithbadgebuttonmode\/hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/hash","fragments":[{"kind":"identifier","text":"hash"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextWithBadgeButtonMode/copyWithZone:":{"abstract":[],"title":"copyWithZone:","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2textwithbadgebuttonmode\/copywithzone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/copyWithZone:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextWithBadgeButtonMode/init()":{"title":"init()","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2textwithbadgebuttonmode\/init()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextWithBadgeButtonMode/text":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"}],"title":"text","url":"\/documentation\/scanbotsdk\/sbsdkui2textwithbadgebuttonmode\/text","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/text","type":"topic","role":"symbol","navigatorTitle":[{"text":"text","kind":"identifier"}],"abstract":[{"text":"Configuration of the text style for the ‘preview’ button.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"title":"Foundation.NSCopying","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextWithBadgeButtonMode/accessibilityDescription":{"url":"\/documentation\/scanbotsdk\/sbsdkui2textwithbadgebuttonmode\/accessibilitydescription","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/accessibilityDescription","abstract":[{"text":"The text to be read when the ‘preview’ button is selected via the accessibility mode.","type":"text"}],"title":"accessibilityDescription","navigatorTitle":[{"text":"accessibilityDescription","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PreviewButton":{"url":"\/documentation\/scanbotsdk\/sbsdkui2previewbutton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton","abstract":[{"text":"Configuration of the ‘preview’ button.","type":"text"}],"title":"SBSDKUI2PreviewButton","navigatorTitle":[{"text":"SBSDKUI2PreviewButton","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PreviewButton","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextWithBadgeButtonMode/pageCounter":{"url":"\/documentation\/scanbotsdk\/sbsdkui2textwithbadgebuttonmode\/pagecounter","title":"pageCounter","navigatorTitle":[{"kind":"identifier","text":"pageCounter"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/pageCounter","role":"symbol","abstract":[{"type":"text","text":"Configuration of the badge icon."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageCounter"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgeStyle","kind":"typeIdentifier","text":"SBSDKUI2BadgeStyle"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextWithBadgeButtonMode/initWithAccessibilityDescription:text:pageCounter:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2textwithbadgebuttonmode\/initwithaccessibilitydescription:text:pagecounter:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAccessibilityDescription:text:pageCounter:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAccessibilityDescription:text:pageCounter:"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/initWithAccessibilityDescription:text:pageCounter:","abstract":[],"title":"initWithAccessibilityDescription:text:pageCounter:"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKUI2TextWithBadgeButtonMode","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2TextWithBadgeButtonMode"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2TextWithBadgeButtonMode","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/accessibilityDescription","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/pageCounter","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/text"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/initWithAccessibilityDescription:text:pageCounter:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/toJson(configuration:)"],"generated":true,"title":"Instance Methods"},{"anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextWithBadgeButtonMode\/fromJsonWithJson:"],"generated":true,"title":"Type Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TextWithBadgeButtonMode","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PreviewButton","text":"SBSDKUI2PreviewButton","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUI2TextWithBadgeButtonMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextWithBadgeButtonMode\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2TextWithBadgeButtonMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextWithBadgeButtonMode\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2TextWithBadgeButtonMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextWithBadgeButtonMode\/navigatorTitle"},{"op":"replace","value":"toJsonWithConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextWithBadgeButtonMode~1toJson(configuration:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextWithBadgeButtonMode~1toJson(configuration:)\/fragments"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextWithBadgeButtonMode~1init()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextWithBadgeButtonMode~1init()\/fragments"},{"op":"replace","value":"text","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextWithBadgeButtonMode~1text\/title"},{"op":"replace","value":[{"text":"text","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextWithBadgeButtonMode~1text\/fragments"},{"op":"replace","value":"accessibilityDescription","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextWithBadgeButtonMode~1accessibilityDescription\/title"},{"op":"replace","value":[{"text":"accessibilityDescription","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextWithBadgeButtonMode~1accessibilityDescription\/fragments"},{"op":"replace","value":"SBSDKUI2PreviewButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton\/title"},{"op":"replace","value":[{"text":"SBSDKUI2PreviewButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2PreviewButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton\/navigatorTitle"},{"op":"replace","value":"pageCounter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextWithBadgeButtonMode~1pageCounter\/title"},{"op":"replace","value":[{"text":"pageCounter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextWithBadgeButtonMode~1pageCounter\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}