{"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"title":"SBSDKVINBarcodeExtractionStatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINBarcodeExtractionStatus","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKVINBarcodeExtractionStatus","symbolKind":"enum","roleHeading":"Enumeration","navigatorTitle":[{"text":"SBSDKVINBarcodeExtractionStatus","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/barcodeExtractionDisabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/barcodeWithoutVin","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/noBarcodeFound","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/success"],"generated":true,"title":"Enumeration Cases"},{"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/init(rawValue:)"],"generated":true,"title":"Initializers"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"sections":[],"abstract":[{"text":"Status of the barcode extraction.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKVINBarcodeExtractionStatus) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINBarcodeExtractionStatus","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeExtractionStatus":{"url":"\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus","kind":"symbol","title":"SBSDKVINBarcodeExtractionStatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINBarcodeExtractionStatus","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKVINBarcodeExtractionStatus","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus","type":"topic","abstract":[{"type":"text","text":"Status of the barcode extraction."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeExtractionStatus/noBarcodeFound":{"abstract":[{"text":"No barcode was found in the image.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/noBarcodeFound","title":"SBSDKVINBarcodeExtractionStatus.noBarcodeFound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noBarcodeFound"}],"url":"\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus\/nobarcodefound","navigatorTitle":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatusNoBarcodeFound"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeExtractionStatus/init(rawValue:)":{"abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/init(rawValue:)","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus\/init(rawvalue:)","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeExtractionStatus/success":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"success","kind":"identifier"}],"title":"SBSDKVINBarcodeExtractionStatus.success","navigatorTitle":[{"text":"SBSDKVINBarcodeExtractionStatusSuccess","kind":"identifier"}],"abstract":[{"type":"text","text":"Barcode containing a VIN was successfully extracted."}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/success","url":"\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus\/success"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeExtractionStatus/barcodeExtractionDisabled":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeExtractionDisabled"}],"url":"\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus\/barcodeextractiondisabled","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/barcodeExtractionDisabled","abstract":[{"type":"text","text":"Barcode extraction is disabled in the configuration."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatusBarcodeExtractionDisabled"}],"title":"SBSDKVINBarcodeExtractionStatus.barcodeExtractionDisabled"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeExtractionStatus/barcodeWithoutVin":{"kind":"symbol","title":"SBSDKVINBarcodeExtractionStatus.barcodeWithoutVin","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/barcodeWithoutVin","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatusBarcodeWithoutVin"}],"url":"\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus\/barcodewithoutvin","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeWithoutVin"}],"abstract":[{"type":"text","text":"Barcode was found but it does not contain a VIN."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeExtractionStatus/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/RawRepresentable-Implementations","role":"collectionGroup","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus\/rawrepresentable-implementations","type":"topic","kind":"article","title":"RawRepresentable Implementations"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeExtractionStatus/Equatable-Implementations":{"role":"collectionGroup","kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus\/equatable-implementations","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/Equatable-Implementations","abstract":[],"title":"Equatable Implementations"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/s12CaseIterableP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","title":"Swift.CaseIterable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKVINBarcodeExtractionStatus","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatus"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKVINBarcodeExtractionStatus","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/barcodeExtractionDisabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/barcodeWithoutVin","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/noBarcodeFound","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/success"],"title":"Enumeration Cases","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINBarcodeExtractionStatus","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus\/title","value":"SBSDKVINBarcodeExtractionStatus","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus\/fragments","value":[{"text":"SBSDKVINBarcodeExtractionStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus~1noBarcodeFound\/title","value":"SBSDKVINBarcodeExtractionStatusNoBarcodeFound","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus~1noBarcodeFound\/fragments","value":[{"text":"SBSDKVINBarcodeExtractionStatusNoBarcodeFound","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus~1success\/title","value":"SBSDKVINBarcodeExtractionStatusSuccess","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus~1success\/fragments","value":[{"text":"SBSDKVINBarcodeExtractionStatusSuccess","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus~1barcodeExtractionDisabled\/title","value":"SBSDKVINBarcodeExtractionStatusBarcodeExtractionDisabled","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus~1barcodeExtractionDisabled\/fragments","value":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatusBarcodeExtractionDisabled"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus~1barcodeWithoutVin\/title","value":"SBSDKVINBarcodeExtractionStatusBarcodeWithoutVin","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus~1barcodeWithoutVin\/fragments","value":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatusBarcodeWithoutVin"}],"op":"replace"}]}]}