{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorAutoFocusConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorAutoFocusConfiguration"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKDocumentDataExtractorAutoFocusConfiguration","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorAutoFocusConfiguration"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKDocumentDataExtractorAutoFocusConfiguration) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorAutoFocusConfiguration","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/init()"],"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/sensitivityThreshold"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/toJson(configuration:)"],"anchor":"Instance-Methods"}],"abstract":[{"text":"Auto-focus configuration.","type":"text"},{"text":" ","type":"text"},{"text":"The recognizer will ignore frames that are not focused. This option is enabled by default.","type":"text"},{"text":" ","type":"text"},{"text":"This configuration has no effect in SINGLE_SHOT mode.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationElement":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement","type":"topic","title":"SBSDKDocumentDataExtractorConfigurationElement","abstract":[{"text":"Base class for all document data extraction configuration elements.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationelement","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorAutoFocusConfiguration/hash":{"title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration\/hash","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/hash","role":"symbol","abstract":[],"fragments":[{"text":"hash","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"Foundation.NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorAutoFocusConfiguration/init()":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/init()","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration\/init()","title":"init()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorAutoFocusConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorAutoFocusConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Auto-focus configuration.","type":"text"},{"text":" ","type":"text"},{"text":"The recognizer will ignore frames that are not focused. This option is enabled by default.","type":"text"},{"text":" ","type":"text"},{"text":"This configuration has no effect in SINGLE_SHOT mode.","type":"text"}],"navigatorTitle":[{"text":"SBSDKDocumentDataExtractorAutoFocusConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration","title":"SBSDKDocumentDataExtractorAutoFocusConfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorAutoFocusConfiguration/fromJsonWithJson:":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration\/fromjsonwithjson:","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/fromJsonWithJson:","title":"fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"type":"topic"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorAutoFocusConfiguration/sensitivityThreshold":{"navigatorTitle":[{"text":"sensitivityThreshold","kind":"identifier"}],"role":"symbol","type":"topic","title":"sensitivityThreshold","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sensitivityThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration\/sensitivitythreshold","abstract":[{"type":"text","text":"Sensitivity threshold for detecting that autofocus is in progress."},{"type":"text","text":" "},{"type":"text","text":"The value should be in the range [0.0, 1.0]."},{"type":"text","text":" "},{"type":"text","text":"The lower the value, the more frames might be discarded as not focused."},{"type":"text","text":" "},{"type":"text","text":"The higher the value, the earlier the focus might be considered as focused."},{"type":"text","text":" "},{"type":"text","text":"If set to 0.0, the feature is disabled."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/sensitivityThreshold","kind":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorAutoFocusConfiguration/isEqual:":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration\/isequal:","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","abstract":[],"title":"isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/isEqual:","type":"topic"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorAutoFocusConfiguration/copyWithZone:":{"kind":"symbol","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"abstract":[],"title":"copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration\/copywithzone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/copyWithZone:","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorAutoFocusConfiguration/toJson(configuration:)":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration\/tojson(configuration:)","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"role":"symbol","title":"toJson(configuration:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/toJson(configuration:)","navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorAutoFocusConfiguration/initWithSensitivityThreshold:":{"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSensitivityThreshold:","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"initWithSensitivityThreshold:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration\/initwithsensitivitythreshold:","title":"initWithSensitivityThreshold:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/initWithSensitivityThreshold:","role":"symbol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKDocumentDataExtractorAutoFocusConfiguration","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorAutoFocusConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorAutoFocusConfiguration"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/sensitivityThreshold"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/initWithSensitivityThreshold:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/toJson(configuration:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/fromJsonWithJson:"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorAutoFocusConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"SBSDKDocumentDataExtractorConfigurationElement","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfigurationElement","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/title","value":"SBSDKDocumentDataExtractorConfigurationElement"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}]},{"value":[{"text":"SBSDKDocumentDataExtractorConfigurationElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/navigatorTitle"},{"value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration~1init()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration~1init()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration\/title","op":"replace","value":"SBSDKDocumentDataExtractorAutoFocusConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKDocumentDataExtractorAutoFocusConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentDataExtractorAutoFocusConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration~1sensitivityThreshold\/title","op":"replace","value":"sensitivityThreshold"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration~1sensitivityThreshold\/fragments","op":"replace","value":[{"text":"sensitivityThreshold","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration~1toJson(configuration:)\/title","op":"replace","value":"toJsonWithConfiguration:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration~1toJson(configuration:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}