{"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod\/exact","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod\/interpolate"]},{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod\/init(rawValue:)"]},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod\/RawRepresentable-Implementations"]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"SBSDKConfirmationMethod","kind":"identifier"}],"title":"SBSDKConfirmationMethod","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKConfirmationMethod","kind":"identifier"}],"roleHeading":"Enumeration","externalID":"c:@M@ScanbotSDK@E@SBSDKConfirmationMethod","symbolKind":"enum"},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"type":"conformsTo","kind":"relationships"}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKConfirmationMethod) "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKConfirmationMethod","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkconfirmationmethod"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkconfirmationmethod"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Method used to confirm a result.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConfirmationMethod/interpolate":{"abstract":[{"type":"text","text":"Interpolate between seen values to generate the most likely true value."},{"type":"text","text":" "},{"type":"text","text":"E.g. if the seen values are “John X. Doe”, “John B.”, “B. Doe” then the most likely true value"},{"type":"text","text":" "},{"type":"text","text":"can be interpolated to be “John B. Doe”."},{"type":"text","text":" "},{"type":"text","text":"The interpolated value is considered CONFIRMED if each character"},{"type":"text","text":" "},{"type":"text","text":"in it has been seen at least minConfirmations times."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interpolate","kind":"identifier"}],"kind":"symbol","title":"SBSDKConfirmationMethod.interpolate","navigatorTitle":[{"text":"SBSDKConfirmationMethodInterpolate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod\/interpolate","url":"\/documentation\/scanbotsdk\/sbsdkconfirmationmethod\/interpolate","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConfirmationMethod/exact":{"url":"\/documentation\/scanbotsdk\/sbsdkconfirmationmethod\/exact","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exact","kind":"identifier"}],"title":"SBSDKConfirmationMethod.exact","role":"symbol","abstract":[{"type":"text","text":"Require seeing the same result multiple times to confirm it."},{"type":"text","text":" "},{"type":"text","text":"E.g. if the seen values are “John B. Doe”, “John B.”, “B. Doe”, “John B. Doe” then the confirmation count for"},{"type":"text","text":" "},{"type":"text","text":"the value “John B. Doe” is 2 and for the rest it’s 1."},{"type":"text","text":" "},{"type":"text","text":"A field’s value is considered CONFIRMED if its confirmation count is greater or equal to minConfirmations."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod\/exact","navigatorTitle":[{"text":"SBSDKConfirmationMethodExact","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConfirmationMethod/init(rawValue:)":{"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkconfirmationmethod\/init(rawvalue:)","title":"init(rawValue:)","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConfirmationMethod":{"navigatorTitle":[{"text":"SBSDKConfirmationMethod","kind":"identifier"}],"abstract":[{"text":"Method used to confirm a result.","type":"text"}],"title":"SBSDKConfirmationMethod","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKConfirmationMethod","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkconfirmationmethod"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConfirmationMethod/Equatable-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod\/Equatable-Implementations","title":"Equatable Implementations","kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkconfirmationmethod\/equatable-implementations","role":"collectionGroup"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConfirmationMethod/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod\/RawRepresentable-Implementations","abstract":[],"type":"topic","kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkconfirmationmethod\/rawrepresentable-implementations"},"doc://net.doo.ScanbotSDK/s12CaseIterableP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","title":"Swift.CaseIterable"},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKConfirmationMethod","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKConfirmationMethod","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKConfirmationMethod"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod\/exact","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod\/interpolate"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKConfirmationMethod","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod~1interpolate\/title","value":"SBSDKConfirmationMethodInterpolate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod~1interpolate\/fragments","value":[{"kind":"identifier","text":"SBSDKConfirmationMethodInterpolate"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod~1exact\/title","value":"SBSDKConfirmationMethodExact","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod~1exact\/fragments","value":[{"text":"SBSDKConfirmationMethodExact","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod\/title","value":"SBSDKConfirmationMethod","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod\/fragments","value":[{"kind":"identifier","text":"SBSDKConfirmationMethod"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKConfirmationMethod"}],"op":"replace"}]}]}