{"sections":[],"abstract":[{"type":"text","text":"Information about the SDK license."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKLicenseInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseInfo"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseInfo"}],"roleHeading":"Class","role":"symbol","title":"SBSDKLicenseInfo"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKLicenseInfo) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseInfo"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklicenseinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdklicenseinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/deviceDeregistationErrors","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/devices","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/errorMessage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/expirationDateString","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/expirationTimestamp","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/isValid","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/license","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/licenseStatusMessage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/nextOnlineLicenseCheckInMs","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/onlineLicenseCheckInProgress","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/status"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/toJson(configuration:)"],"generated":true}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/copyWithZone:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/copyWithZone:","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/copywithzone:","kind":"symbol","title":"copyWithZone:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/expirationDateString":{"title":"expirationDateString","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/expirationdatestring","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expirationDateString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"expirationDateString"}],"type":"topic","abstract":[{"type":"text","text":"Expiration date of the license or trial period in ISO 8601 date-time format."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/expirationDateString","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/licenseStatusMessage":{"abstract":[{"type":"text","text":"Message describing the license status."}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/licensestatusmessage","title":"licenseStatusMessage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/licenseStatusMessage","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licenseStatusMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"licenseStatusMessage","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/nextOnlineLicenseCheckInMs":{"url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/nextonlinelicensecheckinms","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Time in milliseconds until the next online license check will be performed. -1 if no online license check is scheduled."}],"kind":"symbol","title":"nextOnlineLicenseCheckInMs","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/nextOnlineLicenseCheckInMs","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextOnlineLicenseCheckInMs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"nextOnlineLicenseCheckInMs"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/license":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/license","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"license"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"text":"The currently active license. May be different from the license used to initialize","type":"text"},{"text":" ","type":"text"},{"text":"the SDK if the online license check has completed and the server has sent","type":"text"},{"text":" ","type":"text"},{"text":"an updated license.","type":"text"}],"title":"license","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"license"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/license"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/isEqual:":{"title":"isEqual:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/isEqual:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/isequal:","abstract":[],"role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:":{"navigatorTitle":[{"text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","title":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/initwithstatus:isvalid:licensestatusmessage:expirationtimestamp:expirationdatestring:errormessage:onlinelicensecheckinprogress:license:devices:nextonlinelicensecheckinms:devicederegistationerrors:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/devices":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"devices","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/devices","kind":"symbol","navigatorTitle":[{"text":"devices","kind":"identifier"}],"abstract":[{"text":"Number of devices the license is valid for, if the license is floating.","type":"text"}],"title":"devices","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/devices","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/deviceDeregistationErrors":{"navigatorTitle":[{"kind":"identifier","text":"deviceDeregistationErrors"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceDeregistationErrors"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDeviceDeregistrationError","text":"SBSDKDeviceDeregistrationError"},{"kind":"text","text":">"}],"title":"deviceDeregistationErrors","abstract":[{"text":"List of errors that occurred during device deregistration. If for some device deregistration completed successfully, it will not be listed here. For each device at most one entry will be present.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/devicederegistationerrors","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/deviceDeregistationErrors"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/onlineLicenseCheckInProgress":{"url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/onlinelicensecheckinprogress","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlineLicenseCheckInProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/onlineLicenseCheckInProgress","kind":"symbol","title":"onlineLicenseCheckInProgress","abstract":[{"text":"True if an online license check is in progress.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onlineLicenseCheckInProgress"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/expirationTimestamp":{"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expirationTimestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/expirationTimestamp","kind":"symbol","navigatorTitle":[{"text":"expirationTimestamp","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/expirationtimestamp","role":"symbol","abstract":[{"type":"text","text":"Expiration timestamp of the license or trial period in seconds since the UNIX epoch."}],"title":"expirationTimestamp"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:"}],"title":"init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/init(status:isvalid:licensestatusmessage:expirationtimestamp:expirationdatestring:errormessage:onlinelicensecheckinprogress:license:nextonlinelicensecheckinms:devicederegistationerrors:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKLicenseStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKLicenseStatus"},{"text":", ","kind":"text"},{"text":"isValid","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"licenseStatusMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expirationTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expirationDateString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onlineLicenseCheckInProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nextOnlineLicenseCheckInMs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deviceDeregistationErrors"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"SBSDKDeviceDeregistrationError","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDeviceDeregistrationError"},{"kind":"text","text":">)"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/isValid":{"navigatorTitle":[{"kind":"identifier","text":"isValid"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isValid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"True if the license status corresponds to a valid license.","type":"text"}],"title":"isValid","url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/isvalid","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/isValid"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/hash":{"url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/hash","kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"hash","kind":"identifier"}],"title":"hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/errorMessage":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/errorMessage","abstract":[{"text":"Additional error message in case of a license error.","type":"text"}],"kind":"symbol","title":"errorMessage","navigatorTitle":[{"text":"errorMessage","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/errormessage","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/fromJsonWithJson:":{"kind":"symbol","title":"fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/fromjsonwithjson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/fromJsonWithJson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo","title":"SBSDKLicenseInfo","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseInfo"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseInfo"}],"kind":"symbol","abstract":[{"type":"text","text":"Information about the SDK license."}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/toJson(configuration:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/tojson(configuration:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/toJson(configuration:)","role":"symbol","title":"toJson(configuration:)","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/status":{"kind":"symbol","abstract":[{"text":"License status.","type":"text"}],"navigatorTitle":[{"text":"status","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/status","title":"status","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKLicenseStatus","text":"SBSDKLicenseStatus","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/status","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKLicenseInfo","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseInfo"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKLicenseInfo","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/deviceDeregistationErrors","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/devices","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/errorMessage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/expirationDateString","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/expirationTimestamp","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/isValid","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/license","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/licenseStatusMessage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/nextOnlineLicenseCheckInMs","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/onlineLicenseCheckInProgress","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/status"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/toJson(configuration:)"],"anchor":"Instance-Methods"},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/fromJsonWithJson:"],"anchor":"Type-Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"expirationDateString","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1expirationDateString\/title"},{"op":"replace","value":[{"text":"expirationDateString","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1expirationDateString\/fragments"},{"op":"replace","value":"licenseStatusMessage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1licenseStatusMessage\/title"},{"op":"replace","value":[{"text":"licenseStatusMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1licenseStatusMessage\/fragments"},{"op":"replace","value":"nextOnlineLicenseCheckInMs","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1nextOnlineLicenseCheckInMs\/title"},{"op":"replace","value":[{"kind":"identifier","text":"nextOnlineLicenseCheckInMs"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1nextOnlineLicenseCheckInMs\/fragments"},{"op":"replace","value":"license","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1license\/title"},{"op":"replace","value":[{"text":"license","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1license\/fragments"},{"op":"replace","value":"devices","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1devices\/title"},{"op":"replace","value":[{"kind":"identifier","text":"devices"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1devices\/fragments"},{"op":"replace","value":"deviceDeregistationErrors","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1deviceDeregistationErrors\/title"},{"op":"replace","value":[{"kind":"identifier","text":"deviceDeregistationErrors"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1deviceDeregistationErrors\/fragments"},{"op":"replace","value":"onlineLicenseCheckInProgress","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1onlineLicenseCheckInProgress\/title"},{"op":"replace","value":[{"text":"onlineLicenseCheckInProgress","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1onlineLicenseCheckInProgress\/fragments"},{"op":"replace","value":"expirationTimestamp","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1expirationTimestamp\/title"},{"op":"replace","value":[{"kind":"identifier","text":"expirationTimestamp"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1expirationTimestamp\/fragments"},{"op":"replace","value":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)\/fragments"},{"op":"replace","value":"isValid","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1isValid\/title"},{"op":"replace","value":[{"text":"isValid","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1isValid\/fragments"},{"op":"replace","value":"errorMessage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1errorMessage\/title"},{"op":"replace","value":[{"text":"errorMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1errorMessage\/fragments"},{"op":"replace","value":"SBSDKLicenseInfo","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseInfo"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseInfo"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1toJson(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1status\/title","value":"status"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1status\/fragments","value":[{"kind":"identifier","text":"status"}]}]}]}