{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/decodeFull","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/decodeStructure","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/parse","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/validateFull","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/validateStructure"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKGS1Handling) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGS1Handling"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"inlineContent":[{"type":"text","text":"GS1 messages have two representations or formats: a human-readable format and a"},{"type":"text","text":" "},{"type":"text","text":"machine-readable format. The human-readable format uses parentheses to wrap the keys in each"},{"type":"text","text":" "},{"type":"text","text":"pair. For example, the string “(01)012345678901(37)02(3922)00278” contains three AI keys:"},{"type":"text","text":" "},{"type":"text","text":"01, 37, and 3922. The corresponding values are 012345678901, 02, and 00278."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The machine-readable format uses the special ASCII \\x1D character to terminate key-value"},{"type":"text","text":" "},{"type":"text","text":"pairs in the string in cases where the given key implies that the value is variable-length."},{"type":"text","text":" "},{"type":"text","text":"The equivalent machine-readable string for the above example is"},{"type":"text","text":" "},{"type":"text","text":"“010123456789013702\\x1D392200278”."},{"type":"text","text":" "},{"type":"text","text":"In the above example, the 01 AI key is fixed-length, so the \\x1D character is not necessary."},{"type":"text","text":" "},{"type":"text","text":"The 37 AI keys is variable-length, so the \\x1D character is necessary after the value in the"},{"type":"text","text":" "},{"type":"text","text":"pair. The 3922 AI key is also variable-length, but it is the last pair in the message, so"},{"type":"text","text":" "},{"type":"text","text":"the \\x1D character is not necessary at the end."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The character \\x1D is UNPRINTABLE - this means that if you try to print or otherwise"},{"type":"text","text":" "},{"type":"text","text":"visualize a GS1 message containing the \\x1D character, you may see a number of different"},{"type":"text","text":" "},{"type":"text","text":"results, depending on how the system handles unprintable characters. You may see a question"},{"type":"text","text":" "},{"type":"text","text":"mark, a box, an escape sequence, a space or nothing at all."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"symbolKind":"enum","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGS1Handling","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"title":"SBSDKGS1Handling","roleHeading":"Enumeration","externalID":"c:@M@ScanbotSDK@E@SBSDKGS1Handling"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgs1handling"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgs1handling"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"GS1 message handling options."},{"type":"text","text":" "},{"type":"text","text":"The GS1 standard defines a key-value format for business-centric data that can be encoded into many 1D and 2D barcode types."},{"type":"text","text":" "},{"type":"text","text":"https:\/\/ref.gs1.org\/standards\/genspecs\/"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling/Equatable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkgs1handling\/equatable-implementations","type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/Equatable-Implementations","kind":"article","role":"collectionGroup","title":"Equatable Implementations"},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling/parse":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1HandlingParse"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/parse","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"parse"}],"url":"\/documentation\/scanbotsdk\/sbsdkgs1handling\/parse","title":"SBSDKGS1Handling.parse","kind":"symbol","abstract":[{"text":"This is the default. GS1 messages are converted to the machine-readable format per","type":"text"},{"text":" ","type":"text"},{"text":"the GS1 spec (the special FNC1 character is converted to ASCII \\x1D).","type":"text"},{"text":" ","type":"text"},{"text":"The implied 01 AI key is prepended to DataBar results.","type":"text"},{"text":" ","type":"text"},{"text":"No validation is performed.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s12CaseIterableP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","type":"unresolvable","title":"Swift.CaseIterable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGS1Handling","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling","role":"symbol","title":"SBSDKGS1Handling","url":"\/documentation\/scanbotsdk\/sbsdkgs1handling","abstract":[{"type":"text","text":"GS1 message handling options."},{"type":"text","text":" "},{"type":"text","text":"The GS1 standard defines a key-value format for business-centric data that can be encoded into many 1D and 2D barcode types."},{"type":"text","text":" "},{"type":"text","text":"https:\/\/ref.gs1.org\/standards\/genspecs\/"}],"navigatorTitle":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling/decodeFull":{"abstract":[{"type":"text","text":"Combines the validations of VALIDATE_FULL and the human-readable output format of DECODE_STRUCTURE."}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgs1handling\/decodefull","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeFull"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1HandlingDecodeFull"}],"type":"topic","title":"SBSDKGS1Handling.decodeFull","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/decodeFull"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/init(rawValue:)","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkgs1handling\/init(rawvalue:)","title":"init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling/decodeStructure":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/decodeStructure","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeStructure"}],"abstract":[{"text":"Same as VALIDATE_STRUCTURE. Additionally, GS1 strings are converted to the human-readable format,","type":"text"},{"text":" ","type":"text"},{"text":"instead (with parentheses used to wrap AI keys, e.g. “(01)123456789”). The \\x1D character is","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"never used in this representation."}],"url":"\/documentation\/scanbotsdk\/sbsdkgs1handling\/decodestructure","type":"topic","navigatorTitle":[{"text":"SBSDKGS1HandlingDecodeStructure","kind":"identifier"}],"title":"SBSDKGS1Handling.decodeStructure","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling/validateStructure":{"abstract":[{"text":"Same as PARSE. Additionally, messages containing unknown AI keys, or containing values","type":"text"},{"text":" ","type":"text"},{"text":"that don’t fulfill the length, character set or regex requirements for known keys, are rejected.","type":"text"}],"title":"SBSDKGS1Handling.validateStructure","url":"\/documentation\/scanbotsdk\/sbsdkgs1handling\/validatestructure","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/validateStructure","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"validateStructure"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1HandlingValidateStructure"}]},"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling/validateFull":{"abstract":[{"type":"text","text":"Includes all validations from VALIDATE_STRUCTURE. Additionally, GS1 messages which have missing or incompatible combinations of AI keys are rejected. Additionally, values are checked against a list of known linting rules, e.g. checksums are calculated and verified, dates are checked for validity, etc. Results that fail any of the linter rules are rejected. The complete set of linter rules from the GS1 Syntax Dictionary are implemented."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1HandlingValidateFull"}],"url":"\/documentation\/scanbotsdk\/sbsdkgs1handling\/validatefull","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/validateFull","type":"topic","title":"SBSDKGS1Handling.validateFull","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"validateFull"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling/RawRepresentable-Implementations":{"kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/RawRepresentable-Implementations","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkgs1handling\/rawrepresentable-implementations","type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKGS1Handling","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/decodeFull","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/decodeStructure","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/parse","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/validateFull","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/validateStructure"],"title":"Enumeration Cases","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGS1Handling","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling~1parse\/title","value":"SBSDKGS1HandlingParse","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling~1parse\/fragments","value":[{"text":"SBSDKGS1HandlingParse","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/title","value":"SBSDKGS1Handling","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/fragments","value":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/navigatorTitle","value":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling~1decodeFull\/title","value":"SBSDKGS1HandlingDecodeFull","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling~1decodeFull\/fragments","value":[{"kind":"identifier","text":"SBSDKGS1HandlingDecodeFull"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling~1decodeStructure\/title","value":"SBSDKGS1HandlingDecodeStructure","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling~1decodeStructure\/fragments","value":[{"text":"SBSDKGS1HandlingDecodeStructure","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling~1validateStructure\/title","value":"SBSDKGS1HandlingValidateStructure","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling~1validateStructure\/fragments","value":[{"kind":"identifier","text":"SBSDKGS1HandlingValidateStructure"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling~1validateFull\/title","value":"SBSDKGS1HandlingValidateFull","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling~1validateFull\/fragments","value":[{"kind":"identifier","text":"SBSDKGS1HandlingValidateFull"}],"op":"replace"}]}]}