{"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoOrientation"}],"roleHeading":"Enumeration","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoOrientation"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKVideoOrientation","title":"SBSDKVideoOrientation","modules":[{"name":"ScanbotSDK"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoOrientation","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"kind":"symbol","abstract":[{"type":"text","text":"An enum describing the orientation of a video frame."}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/landscapeLeft","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/landscapeRight","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/portrait","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/portraitUpsideDown"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/angle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/isLandscape","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/isPortrait"],"generated":true,"anchor":"Instance-Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvideoorientation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvideoorientation"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation/landscapeLeft":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscapeLeft"}],"title":"SBSDKVideoOrientation.landscapeLeft","url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation\/landscapeleft","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/landscapeLeft","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoOrientationLandscapeLeft"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Landscape left orientation."}]},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation/angle":{"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"angle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation\/angle","title":"angle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/angle","role":"symbol","abstract":[{"type":"text","text":"Returns the counter-clockwise angle of the orientation in degrees, with portrait equaling 90 degrees."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","abstract":[],"kind":"article","role":"collectionGroup","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation\/rawrepresentable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation/portrait":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKVideoOrientationPortrait","kind":"identifier"}],"title":"SBSDKVideoOrientation.portrait","url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation\/portrait","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"portrait","kind":"identifier"}],"abstract":[{"text":"Portrait orientation.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/portrait"},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation":{"url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation","role":"symbol","title":"SBSDKVideoOrientation","type":"topic","abstract":[{"type":"text","text":"An enum describing the orientation of a video frame."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoOrientation"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoOrientation"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation/isLandscape":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/isLandscape","title":"isLandscape","url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation\/islandscape","abstract":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" if the receiver is either landscape left or landscape right, ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" otherwise.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isLandscape","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"type":"topic","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/Equatable-Implementations","kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation\/equatable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation/landscapeRight":{"url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation\/landscaperight","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscapeRight"}],"abstract":[{"type":"text","text":"Landscape right orientation."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoOrientationLandscapeRight"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/landscapeRight","kind":"symbol","type":"topic","title":"SBSDKVideoOrientation.landscapeRight"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"abstract":[],"title":"init(rawValue:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/init(rawValue:)","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation\/init(rawvalue:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation/isPortrait":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation\/isportrait","title":"isPortrait","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/isPortrait","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPortrait","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Returns "},{"code":"true","type":"codeVoice"},{"text":" if the receiver is either portrait or portrait upside down, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" otherwise.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation/portraitUpsideDown":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Portrait upside down orientation."}],"title":"SBSDKVideoOrientation.portraitUpsideDown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"portraitUpsideDown","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/portraitUpsideDown","navigatorTitle":[{"text":"SBSDKVideoOrientationPortraitUpsideDown","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation\/portraitupsidedown","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKVideoOrientation","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoOrientation"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoOrientation"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/landscapeLeft","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/landscapeRight","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/portrait","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/portraitUpsideDown"],"title":"Enumeration Cases","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoOrientation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation~1landscapeLeft\/title","op":"replace","value":"SBSDKVideoOrientationLandscapeLeft"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation~1landscapeLeft\/fragments","op":"replace","value":[{"text":"SBSDKVideoOrientationLandscapeLeft","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation~1portrait\/title","op":"replace","value":"SBSDKVideoOrientationPortrait"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation~1portrait\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoOrientationPortrait"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/title","op":"replace","value":"SBSDKVideoOrientation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoOrientation"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/navigatorTitle","op":"replace","value":[{"text":"SBSDKVideoOrientation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation~1landscapeRight\/title","op":"replace","value":"SBSDKVideoOrientationLandscapeRight"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation~1landscapeRight\/fragments","op":"replace","value":[{"text":"SBSDKVideoOrientationLandscapeRight","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation~1portraitUpsideDown\/title","op":"replace","value":"SBSDKVideoOrientationPortraitUpsideDown"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation~1portraitUpsideDown\/fragments","op":"replace","value":[{"text":"SBSDKVideoOrientationPortraitUpsideDown","kind":"identifier"}]}]}]}