{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcamerasessionobserving"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcamerasessionobserving"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"SBSDKCameraSessionObserving","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraSessionObserving","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKCameraSessionObserving","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKCameraSessionObserving","roleHeading":"Protocol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSessionObserving"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"A multicast-observer protocol that informs its observers about state changes of a camera session.","type":"text"}],"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving\/cameraSession(_:didChangeDevice:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving\/cameraSession(_:didChangeZoom:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving\/cameraSession(_:didToggleTorchlight:)"],"anchor":"Instance-Methods"}],"relationshipsSections":[{"title":"Conforming Types","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController"],"kind":"relationships","type":"conformingTypes"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewController":{"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the vehicle identification number scanner."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKVINScannerViewController"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","kind":"symbol","title":"SBSDKVINScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVINScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"type":"topic","title":"SBSDKDocumentScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"abstract":[{"text":"A UIViewController subclass to show a camera screen and run a user guiding document scanner.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}],"abstract":[{"text":"The classic UI view controller that can be used to detect and scan medical certificates. Can be configured to scan on video frames or,","type":"text"},{"text":" ","type":"text"},{"text":"for better accuracy, on high-res photos that are automatically captured.","type":"text"}],"title":"SBSDKMedicalCertificateScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSessionObserving/cameraSession(_:didToggleTorchlight:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKCameraSession","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didToggleTorchlight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"role":"symbol","title":"cameraSession(_:didToggleTorchlight:)","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcamerasessionobserving\/camerasession(_:didtoggletorchlight:)","abstract":[{"type":"text","text":"Informs the observer that the torch light has been toggled on or off."}],"navigatorTitle":[{"kind":"identifier","text":"cameraSession:didToggleTorchlight:"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving\/cameraSession(_:didToggleTorchlight:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController","type":"topic","navigatorTitle":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller","role":"symbol","title":"SBSDKBaseScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A highly customizable camera view controller that delivers a basic camera functionality along with video"},{"type":"text","text":" "},{"type":"text","text":"frame extraction and preprocessing, orientation correction and still image capturing."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode scanner."}],"kind":"symbol","title":"SBSDKBarcodeScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewController":{"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode scanner."},{"type":"text","text":" "},{"type":"text","text":"Screen also shows snap, scan more and reset buttons."},{"type":"text","text":" "},{"type":"text","text":"The snap button starts the scanning when tapped."},{"type":"text","text":" "},{"type":"text","text":"The snap button resets the scanning when tapped again."},{"type":"text","text":" "},{"type":"text","text":"Instead it is installing itself as a child view controller onto a given parent view controller."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}],"title":"SBSDKBarcodeScanAndCountViewController","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSessionObserving/cameraSession(_:didChangeDevice:)":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcamerasessionobserving\/camerasession(_:didchangedevice:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cameraSession:didChangeDevice:"}],"abstract":[{"text":"Informs the observer that the camera device has been changed.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving\/cameraSession(_:didChangeDevice:)","title":"cameraSession(_:didChangeDevice:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKCameraSession","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeDevice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCameraDevice","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerViewController":{"title":"SBSDKCreditCardScannerViewController","role":"symbol","navigatorTitle":[{"text":"SBSDKCreditCardScannerViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCreditCardScannerViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontroller","abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan credit cards."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerViewController":{"abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show a camera screen with the text pattern scanner."}],"title":"SBSDKTextPatternScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","navigatorTitle":[{"text":"SBSDKTextPatternScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontroller","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextPatternScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSessionObserving/cameraSession(_:didChangeZoom:)":{"url":"\/documentation\/scanbotsdk\/sbsdkcamerasessionobserving\/camerasession(_:didchangezoom:)","role":"symbol","abstract":[{"text":"Informs the observer that the zoom value has changed.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving\/cameraSession(_:didChangeZoom:)","kind":"symbol","title":"cameraSession(_:didChangeZoom:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraSession","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraSession","text":"SBSDKCameraSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didChangeZoom","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"cameraSession:didChangeZoom:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorViewController":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorviewcontroller","title":"SBSDKDocumentDataExtractorViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorViewController","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDataExtractorViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to extract documents data, e.g. German passports, ID cards and driver’s licenses on video frames."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewController":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"kind":"symbol","title":"SBSDKCheckScannerViewController","navigatorTitle":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan bank checks."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","title":"SBSDKMRZScannerViewController","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller","abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan machine-readable zones."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZScannerViewController"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSessionObserving":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSessionObserving"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving","title":"SBSDKCameraSessionObserving","url":"\/documentation\/scanbotsdk\/sbsdkcamerasessionobserving","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSessionObserving"}],"abstract":[{"type":"text","text":"A multicast-observer protocol that informs its observers about state changes of a camera session."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKCameraSessionObserving"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKCameraSessionObserving","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCameraSessionObserving","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving\/cameraSession(_:didChangeDevice:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving\/cameraSession(_:didChangeZoom:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving\/cameraSession(_:didToggleTorchlight:)"],"generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Conforming Types","kind":"relationships","type":"conformingTypes","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraSessionObserving","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/title","op":"replace","value":"SBSDKVINScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKVINScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKVINScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/title","op":"replace","value":"SBSDKDocumentScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/title","op":"replace","value":"SBSDKMedicalCertificateScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving~1cameraSession(_:didToggleTorchlight:)\/title","op":"replace","value":"cameraSession:didToggleTorchlight:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving~1cameraSession(_:didToggleTorchlight:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cameraSession:didToggleTorchlight:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/title","op":"replace","value":"SBSDKBaseScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/title","op":"replace","value":"SBSDKBarcodeScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/title","op":"replace","value":"SBSDKBarcodeScanAndCountViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving~1cameraSession(_:didChangeDevice:)\/title","op":"replace","value":"cameraSession:didChangeDevice:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving~1cameraSession(_:didChangeDevice:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"cameraSession:didChangeDevice:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController\/title","op":"replace","value":"SBSDKCreditCardScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKCreditCardScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKCreditCardScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/title","op":"replace","value":"SBSDKTextPatternScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKTextPatternScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving~1cameraSession(_:didChangeZoom:)\/title","op":"replace","value":"cameraSession:didChangeZoom:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving~1cameraSession(_:didChangeZoom:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cameraSession:didChangeZoom:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewController\/title","op":"replace","value":"SBSDKDocumentDataExtractorViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewController\/fragments","op":"replace","value":[{"text":"SBSDKDocumentDataExtractorViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentDataExtractorViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/title","op":"replace","value":"SBSDKCheckScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/title","op":"replace","value":"SBSDKMRZScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKMRZScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving\/title","op":"replace","value":"SBSDKCameraSessionObserving"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving\/fragments","op":"replace","value":[{"text":"SBSDKCameraSessionObserving","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraSessionObserving"}]}]}]}