{"metadata":{"symbolKind":"class","roleHeading":"Class","title":"SBSDKDocumentScanningResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScanningResult","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScanningResult","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentScanningResult","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKDocumentScanningResult) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScanningResult","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/init(detectionResult:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/croppedImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/detectionResult"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/close()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods"}],"kind":"symbol","abstract":[{"text":"Result of the document detection followed by cropping of the found document.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscanningresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscanningresult"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScanningResult/toJson(configuration:)":{"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/toJson(configuration:)","title":"toJson(configuration:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscanningresult\/tojson(configuration:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScanningResult/croppedImage":{"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"croppedImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"croppedImage","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscanningresult\/croppedimage","kind":"symbol","role":"symbol","title":"croppedImage","abstract":[{"type":"text","text":"Cropped document image."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/croppedImage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScanningResult/isEqual:":{"type":"topic","title":"isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/isEqual:","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscanningresult\/isequal:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScanningResult/init(detectionResult:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/init(detectionResult:)","role":"symbol","kind":"symbol","title":"init(detectionResult:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscanningresult\/init(detectionresult:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithDetectionResult:"}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detectionResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","text":"SBSDKDocumentDetectionResult"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScanningResult/copyWithZone:":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscanningresult\/copywithzone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/copyWithZone:","type":"topic","role":"symbol","title":"copyWithZone:","abstract":[],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScanningResult/close()":{"kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"close","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/close()","title":"close()","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscanningresult\/close()","navigatorTitle":[{"text":"close","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScanningResult/fromJsonWithJson:":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscanningresult\/fromjsonwithjson:","abstract":[],"kind":"symbol","title":"fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScanningResult/initWithDetectionResult:croppedImage:":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithDetectionResult:croppedImage:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetectionResult:croppedImage:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/initWithDetectionResult:croppedImage:","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscanningresult\/initwithdetectionresult:croppedimage:","kind":"symbol","type":"topic","title":"initWithDetectionResult:croppedImage:","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScanningResult/detectionResult":{"abstract":[{"type":"text","text":"Result of the document contour detection."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/detectionResult","kind":"symbol","title":"detectionResult","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscanningresult\/detectionresult","navigatorTitle":[{"text":"detectionResult","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScanningResult/hash":{"type":"topic","abstract":[],"fragments":[{"text":"hash","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/hash","kind":"symbol","title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscanningresult\/hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScanningResult":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScanningResult"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscanningresult","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScanningResult"}],"abstract":[{"text":"Result of the document detection followed by cropping of the found document.","type":"text"}],"title":"SBSDKDocumentScanningResult","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKDocumentScanningResult"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKDocumentScanningResult","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentScanningResult"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/croppedImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/detectionResult","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/hash"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/close()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/init(detectionResult:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/initWithDetectionResult:croppedImage:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/toJson(configuration:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScanningResult\/fromJsonWithJson:"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"type":"conformsTo","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScanningResult","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScanningResult~1toJson(configuration:)\/title","op":"replace","value":"toJsonWithConfiguration:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScanningResult~1toJson(configuration:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScanningResult~1croppedImage\/title","value":"croppedImage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScanningResult~1croppedImage\/fragments","value":[{"text":"croppedImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScanningResult~1init(detectionResult:)\/title","value":"initWithDetectionResult:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScanningResult~1init(detectionResult:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetectionResult:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScanningResult~1close()\/title","value":"close"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScanningResult~1close()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"close"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScanningResult~1detectionResult\/title","value":"detectionResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScanningResult~1detectionResult\/fragments","value":[{"text":"detectionResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScanningResult\/title","value":"SBSDKDocumentScanningResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScanningResult\/fragments","value":[{"text":"SBSDKDocumentScanningResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScanningResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentScanningResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}