{"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/init(parentViewController:parentView:scannerParameters:delegate:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/captureHighResolutionImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/delegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/scannerParameters","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/state"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/viewDidAppear(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController"},"kind":"symbol","abstract":[{"type":"text","text":"The classic UI view controller that can be used to detect and scan medical certificates. Can be configured to scan on video frames or,"},{"type":"text","text":" "},{"type":"text","text":"for better accuracy, on high-res photos that are automatically captured."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"class","title":"SBSDKMedicalCertificateScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}]},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionDelegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewDelegate","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/s8SendableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring","doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"references":{"doc://net.doo.ScanbotSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCoding","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIContentContainer","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController/scannerParameters":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scannerParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningParameters","text":"SBSDKMedicalCertificateScanningParameters"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/scannerParameters","title":"scannerParameters","type":"topic","abstract":[{"type":"text","text":"The scanner parameters."}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller\/scannerparameters","navigatorTitle":[{"kind":"identifier","text":"scannerParameters"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://net.doo.ScanbotSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/net.doo.ScanbotSDK\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","title":"SBSDKFinderView","abstract":[{"text":"A ","type":"text"},{"code":"UIView","type":"codeVoice"},{"text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKFinderView","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkfinderview"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController/captureHighResolutionImage":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/captureHighResolutionImage","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller\/capturehighresolutionimage","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureHighResolutionImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"captureHighResolutionImage","kind":"identifier"}],"abstract":[{"type":"text","text":"If set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":" a high-resolution photo of the medical certificate is captured to run the scan on."}],"title":"captureHighResolutionImage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSessionObserving":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSessionObserving"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionObserving","title":"SBSDKCameraSessionObserving","url":"\/documentation\/scanbotsdk\/sbsdkcamerasessionobserving","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSessionObserving"}],"abstract":[{"type":"text","text":"A multicast-observer protocol that informs its observers about state changes of a camera session."}]},"doc://net.doo.ScanbotSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController/init()":{"type":"topic","kind":"symbol","abstract":[{"text":"Initializes an instance of this class with the default configuration.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller\/init()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/init()","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController","type":"topic","navigatorTitle":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller","role":"symbol","title":"SBSDKBaseScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A highly customizable camera view controller that delivers a basic camera functionality along with video"},{"type":"text","text":" "},{"type":"text","text":"frame extraction and preprocessing, orientation correction and still image capturing."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderViewDelegate":{"title":"SBSDKFinderViewDelegate","url":"\/documentation\/scanbotsdk\/sbsdkfinderviewdelegate","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"abstract":[{"type":"text","text":"The delegate protocol for the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView"},{"type":"text","text":" class."}]},"doc://net.doo.ScanbotSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController/viewDidAppear(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/viewDidAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"title":"viewDidAppear(_:)","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller\/viewdidappear(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController/state":{"navigatorTitle":[{"text":"state","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The current state of the medical certificate scanner.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKMedicalCertificateScannerState","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateScannerState","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/state","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller\/state","role":"symbol","title":"state"},"doc://net.doo.ScanbotSDK/s8SendableP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://net.doo.ScanbotSDK/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSessionDelegate":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSessionDelegate"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionDelegate","kind":"symbol","title":"SBSDKCameraSessionDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSessionDelegate"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasessiondelegate","abstract":[{"type":"text","text":"The  delegate protocol for "},{"type":"codeVoice","code":"SBSDKCameraSession"},{"type":"text","text":"."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController/init(parentViewController:parentView:scannerParameters:delegate:)":{"type":"topic","title":"init(parentViewController:parentView:scannerParameters:delegate:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/init(parentViewController:parentView:scannerParameters:delegate:)","role":"symbol","abstract":[{"text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area.","type":"text"}],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"parentViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"parentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scannerParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKMedicalCertificateScanningParameters","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningParameters"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKMedicalCertificateScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKMedicalCertificateScannerViewControllerDelegate"},{"kind":"text","text":"?)"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller\/init(parentviewcontroller:parentview:scannerparameters:delegate:)","navigatorTitle":[{"kind":"identifier","text":"initWithParentViewController:parentView:scannerParameters:delegate:"}]},"doc://net.doo.ScanbotSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}],"abstract":[{"text":"The classic UI view controller that can be used to detect and scan medical certificates. Can be configured to scan on video frames or,","type":"text"},{"text":" ","type":"text"},{"text":"for better accuracy, on high-res photos that are automatically captured.","type":"text"}],"title":"SBSDKMedicalCertificateScannerViewController"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController/delegate":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKMedicalCertificateScannerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKMedicalCertificateScannerViewControllerDelegate"},{"text":"?","kind":"text"}],"title":"delegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/delegate","abstract":[{"text":"The delegate of the receiver.","type":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller\/delegate"},"doc://net.doo.ScanbotSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKMedicalCertificateScannerViewController","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/captureHighResolutionImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/delegate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/scannerParameters","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/state"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/init(parentViewController:parentView:scannerParameters:delegate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController\/viewDidAppear(_:)"],"generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"SBSDKBaseScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"scannerParameters","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController~1scannerParameters\/title"},{"op":"replace","value":[{"kind":"identifier","text":"scannerParameters"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController~1scannerParameters\/fragments"},{"op":"replace","value":"SBSDKFinderView","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/title"},{"op":"replace","value":[{"text":"SBSDKFinderView","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKFinderView"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/navigatorTitle"},{"op":"replace","value":"captureHighResolutionImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController~1captureHighResolutionImage\/title"},{"op":"replace","value":[{"text":"captureHighResolutionImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController~1captureHighResolutionImage\/fragments"},{"op":"replace","value":"SBSDKCameraSessionObserving","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving\/title"},{"op":"replace","value":[{"text":"SBSDKCameraSessionObserving","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraSessionObserving"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionObserving\/navigatorTitle"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController~1init()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController~1init()\/fragments"},{"op":"replace","value":"SBSDKBaseScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/navigatorTitle"},{"op":"replace","value":"SBSDKFinderViewDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate\/title"},{"op":"replace","value":[{"text":"SBSDKFinderViewDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate\/fragments"},{"op":"replace","value":[{"text":"SBSDKFinderViewDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate\/navigatorTitle"},{"op":"replace","value":"viewDidAppear:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController~1viewDidAppear(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewDidAppear:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController~1viewDidAppear(_:)\/fragments"},{"op":"replace","value":"state","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController~1state\/title"},{"op":"replace","value":[{"kind":"identifier","text":"state"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController~1state\/fragments"},{"op":"replace","value":"SBSDKCameraSessionDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionDelegate\/title"},{"op":"replace","value":[{"text":"SBSDKCameraSessionDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraSessionDelegate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionDelegate\/navigatorTitle"},{"op":"replace","value":"initWithParentViewController:parentView:scannerParameters:delegate:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController~1init(parentViewController:parentView:scannerParameters:delegate:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParentViewController:parentView:scannerParameters:delegate:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController~1init(parentViewController:parentView:scannerParameters:delegate:)\/fragments"},{"op":"replace","value":"SBSDKMedicalCertificateScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/fragments"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/navigatorTitle"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController~1delegate\/title"},{"op":"replace","value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController~1delegate\/fragments"}]}]}