{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"A class to perform optical character recognition (text) on an image (OCR).","type":"text"}],"metadata":{"role":"symbol","roleHeading":"Class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineManager","symbolKind":"class","title":"SBSDKOCREngineManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCREngineManager","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKOCREngineManager","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/init(configuration:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:)-26gmc","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:)-3hjxh","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:)-49pep","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:)-54e9j","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:)-6soss","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:completion:)-2z5yh","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:completion:)-49gj4","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:completion:)-6woxr","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:completion:)-9pkqo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:cryptingProvider:completion:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCREngineManager"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Since this is a CPU-intensive task, the recognition methods are asynchronous and run on a dedicated concurrent queue."}],"type":"paragraph"},{"style":"note","type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion handlers are dispatched to the main thread."}]}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkocrenginemanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkocrenginemanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineManager/recognize(from:completion:)-6woxr":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"SBSDKOCRResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ()) -> ","kind":"text"},{"text":"SBSDKProgress","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrenginemanager\/recognize(from:completion:)-6woxr","title":"recognize(from:completion:)","navigatorTitle":[{"text":"recognizeFromScannedDocument:completion:","kind":"identifier"}],"abstract":[{"text":"Recognizes characters on all pages of the scanned document and passes the result, or the error, to the completion handler.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:completion:)-6woxr","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineManager/init(configuration:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/init(configuration:)","url":"\/documentation\/scanbotsdk\/sbsdkocrenginemanager\/init(configuration:)","role":"symbol","title":"init(configuration:)","abstract":[{"type":"text","text":"Designated initializer."}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration","text":"SBSDKOCREngineConfiguration"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineManager/recognize(from:completion:)-9pkqo":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"recognizeFromImageStorage:completion:"}],"title":"recognize(from:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageStoring","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"SBSDKOCRResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ()) -> ","kind":"text"},{"text":"SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:completion:)-9pkqo","url":"\/documentation\/scanbotsdk\/sbsdkocrenginemanager\/recognize(from:completion:)-9pkqo","abstract":[{"type":"text","text":"Recognizes characters on all images of an image storage and passes the result, or the error, to the completion handler."}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineManager/recognize(from:completion:)-49gj4":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:completion:)-49gj4","role":"symbol","abstract":[{"type":"text","text":"Recognizes characters on the given image and passes the result, or the error, to the completion handler."}],"kind":"symbol","title":"recognize(from:completion:)","url":"\/documentation\/scanbotsdk\/sbsdkocrenginemanager\/recognize(from:completion:)-49gj4","navigatorTitle":[{"kind":"identifier","text":"recognizeFromImage:completion:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"SBSDKOCRResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ())","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineManager/recognize(from:completion:)-2z5yh":{"abstract":[{"type":"text","text":"Recognizes characters on all pages of the document and passes the result, or the error, to the completion handler."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:completion:)-2z5yh","title":"recognize(from:completion:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"SBSDKOCRResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ()) -> ","kind":"text"},{"text":"SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"recognizeFromDocument:completion:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkocrenginemanager\/recognize(from:completion:)-2z5yh"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineManager":{"title":"SBSDKOCREngineManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCREngineManager"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrenginemanager","navigatorTitle":[{"kind":"identifier","text":"SBSDKOCREngineManager"}],"abstract":[{"type":"text","text":"A class to perform optical character recognition (text) on an image (OCR)."}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineManager/recognize(from:cryptingProvider:completion:)":{"url":"\/documentation\/scanbotsdk\/sbsdkocrenginemanager\/recognize(from:cryptingprovider:completion:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:cryptingProvider:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"cryptingProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingProvider"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"SBSDKOCRResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ())","kind":"text"}],"title":"recognize(from:cryptingProvider:completion:)","type":"topic","abstract":[{"type":"text","text":"Recognizes characters on the image given by a file URL and passes the result, or the error, to the completion handler."}],"navigatorTitle":[{"text":"recognizeFromImageURL:encrypter:completion:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineManager/recognize(from:)-54e9j":{"title":"recognize(from:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:)-54e9j","abstract":[{"type":"text","text":"Asynchronously recognizes characters on the image given by a file URL and returns the result, or throws an error otherwise."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"SBSDKOCRResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrenginemanager\/recognize(from:)-54e9j","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineManager/recognize(from:)-26gmc":{"url":"\/documentation\/scanbotsdk\/sbsdkocrenginemanager\/recognize(from:)-26gmc","title":"recognize(from:)","kind":"symbol","type":"topic","abstract":[{"text":"Asynchronously recognizes characters on the given image and returns the result, or throws an error otherwise.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"SBSDKOCRResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:)-26gmc"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineManager/recognize(from:)-49pep":{"title":"recognize(from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","text":"SBSDKImageStoring"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult","text":"SBSDKOCRResult"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrenginemanager\/recognize(from:)-49pep","abstract":[{"type":"text","text":"Asynchronously recognizes characters on all images of an image storage and returns the result, or throws an error otherwise."}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:)-49pep"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineManager/recognize(from:)-6soss":{"abstract":[{"type":"text","text":"Asynchronously recognizes characters on all pages of the scanned document and returns the result, or throws an error otherwise."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkocrenginemanager\/recognize(from:)-6soss","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult","text":"SBSDKOCRResult"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:)-6soss","type":"topic","title":"recognize(from:)"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineManager/recognize(from:)-3hjxh":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"SBSDKOCRResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:)-3hjxh","url":"\/documentation\/scanbotsdk\/sbsdkocrenginemanager\/recognize(from:)-3hjxh","type":"topic","title":"recognize(from:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Asynchronously recognizes characters on all pages of the document and returns the result, or throws an error otherwise."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKOCREngineManager","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKOCREngineManager","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKOCREngineManager"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/init(configuration:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:completion:)-2z5yh","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:completion:)-49gj4","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:completion:)-6woxr","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:completion:)-9pkqo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineManager\/recognize(from:cryptingProvider:completion:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCREngineManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"recognizeFromScannedDocument:completion:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager~1recognize(from:completion:)-6woxr\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"recognizeFromScannedDocument:completion:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager~1recognize(from:completion:)-6woxr\/fragments"},{"value":"initWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager~1init(configuration:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager~1init(configuration:)\/fragments"},{"value":"recognizeFromImageStorage:completion:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager~1recognize(from:completion:)-9pkqo\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"recognizeFromImageStorage:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager~1recognize(from:completion:)-9pkqo\/fragments"},{"value":"recognizeFromImage:completion:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager~1recognize(from:completion:)-49gj4\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"recognizeFromImage:completion:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager~1recognize(from:completion:)-49gj4\/fragments"},{"value":"recognizeFromDocument:completion:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager~1recognize(from:completion:)-2z5yh\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"recognizeFromDocument:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager~1recognize(from:completion:)-2z5yh\/fragments"},{"value":"SBSDKOCREngineManager","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager\/title"},{"value":[{"text":"SBSDKOCREngineManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKOCREngineManager"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager\/navigatorTitle"},{"value":"recognizeFromImageURL:encrypter:completion:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager~1recognize(from:cryptingProvider:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"recognizeFromImageURL:encrypter:completion:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineManager~1recognize(from:cryptingProvider:completion:)\/fragments"}]}]}