{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkapplicationstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkapplicationstate"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKApplicationState","kind":"identifier"}]}]}],"abstract":[{"type":"text","text":"An enum describing the current state of the app."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKApplicationState"}],"symbolKind":"enum","title":"SBSDKApplicationState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKApplicationState"}],"roleHeading":"Enumeration","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKApplicationState"},"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/active","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/background","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/inactive"],"title":"Enumeration Cases"},{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/init(rawValue:)"],"title":"Initializers"},{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKApplicationState/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"abstract":[],"title":"init(rawValue:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/init(rawValue:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkapplicationstate\/init(rawvalue:)","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKApplicationState/background":{"title":"SBSDKApplicationState.background","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkapplicationstate\/background","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/background","navigatorTitle":[{"kind":"identifier","text":"SBSDKApplicationStateBackground"}],"abstract":[{"text":"The app is in background.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"background"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKApplicationState/inactive":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inactive"}],"abstract":[{"type":"text","text":"The app is inactive and in background."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKApplicationStateInactive"}],"title":"SBSDKApplicationState.inactive","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/inactive","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkapplicationstate\/inactive","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKApplicationState/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkapplicationstate\/equatable-implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/Equatable-Implementations","kind":"article","title":"Equatable Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKApplicationState":{"title":"SBSDKApplicationState","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An enum describing the current state of the app."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState","navigatorTitle":[{"kind":"identifier","text":"SBSDKApplicationState"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKApplicationState"}],"url":"\/documentation\/scanbotsdk\/sbsdkapplicationstate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKApplicationState/active":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKApplicationStateActive"}],"abstract":[{"type":"text","text":"The app is active and in foreground."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkapplicationstate\/active","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/active","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"active"}],"title":"SBSDKApplicationState.active"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKApplicationState/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","url":"\/documentation\/scanbotsdk\/sbsdkapplicationstate\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/RawRepresentable-Implementations","kind":"article","abstract":[],"role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKApplicationState","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKApplicationState","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKApplicationState","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/active","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/background","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/inactive"],"anchor":"Enumeration-Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKApplicationState"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKApplicationStateBackground","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState~1background\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKApplicationStateBackground"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState~1background\/fragments"},{"op":"replace","value":"SBSDKApplicationStateInactive","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState~1inactive\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKApplicationStateInactive"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState~1inactive\/fragments"},{"op":"replace","value":"SBSDKApplicationState","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKApplicationState"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState\/fragments"},{"op":"replace","value":[{"text":"SBSDKApplicationState","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState\/navigatorTitle"},{"op":"replace","value":"SBSDKApplicationStateActive","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState~1active\/title"},{"op":"replace","value":[{"text":"SBSDKApplicationStateActive","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState~1active\/fragments"}]}]}