{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Timeouts\/initWithAutoCancelTimeout:initialScanDelay:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Timeouts"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAutoCancelTimeout:initialScanDelay:"}],"title":"initWithAutoCancelTimeout:initialScanDelay:","navigatorTitle":[{"kind":"identifier","text":"initWithAutoCancelTimeout:initialScanDelay:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Timeouts(im)initWithAutoCancelTimeout:initialScanDelay:"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2timeouts\/initwithautocanceltimeout:initialscandelay:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithAutoCancelTimeout:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"autoCancelTimeout","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"initialScanDelay:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initialScanDelay","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Timeouts/initWithAutoCancelTimeout:initialScanDelay:":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Timeouts\/initWithAutoCancelTimeout:initialScanDelay:","navigatorTitle":[{"kind":"identifier","text":"initWithAutoCancelTimeout:initialScanDelay:"}],"abstract":[],"title":"initWithAutoCancelTimeout:initialScanDelay:","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAutoCancelTimeout:initialScanDelay:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2timeouts\/initwithautocanceltimeout:initialscandelay:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Timeouts":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Timeouts","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Timeouts"}],"title":"SBSDKUI2Timeouts","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Timeouts"}],"abstract":[{"type":"text","text":"Configuration of timeouts."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2timeouts","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Timeouts\/title","value":"SBSDKUI2Timeouts"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Timeouts\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Timeouts"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Timeouts\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Timeouts"}]}]}]}