{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationBuilder"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationBuilder"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKDocumentDataExtractorConfigurationBuilder","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfigurationBuilder","roleHeading":"Class","symbolKind":"class","role":"symbol"},"abstract":[{"text":"A builder class to help with assembling the configuration for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor"},{"text":".","type":"text"}],"kind":"symbol","sections":[],"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/addDateValidatorConfiguration(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/addExcludedField(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/buildConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setAcceptedDocumentTypes(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setAddressDatabaseURL(_:forDocumentTypes:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setAutoFocusConfig(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setEuropeanHealthInsuranceCardConfiguration(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setGlareDetectionConfiguration(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setMachineReadableZoneConfiguration(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setResultAccumulationConfiguration(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setReturnCrops(_:)"],"anchor":"Instance-Methods"},{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/defaultConfiguration"],"anchor":"Type-Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractor":{"title":"SBSDKDocumentDataExtractor","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A class to extract generic documents data on various image sources."},{"type":"text","text":" "},{"type":"text","text":"Extracts the sub-documents, field names and field values from many types of documents e.g. German passports, ID cards, driver’s licenses."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder","navigatorTitle":[{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"}],"type":"topic","title":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"symbol","abstract":[{"text":"A builder class to help with assembling the configuration for ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor","isActive":true,"type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder/setAutoFocusConfig(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAutoFocusConfig"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKDocumentDataExtractorAutoFocusConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorAutoFocusConfiguration"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"setAutoFocusConfig:"}],"type":"topic","title":"setAutoFocusConfig(_:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setAutoFocusConfig(_:)","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/setautofocusconfig(_:)","abstract":[{"text":"Lets you precisely control the exclusion of frames that lack focus.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder/init":{"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/init","abstract":[],"role":"symbol","title":"init","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/init"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder/setGlareDetectionConfiguration(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/setglaredetectionconfiguration(_:)","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setGlareDetectionConfiguration(_:)","abstract":[{"text":"Lets you fine-tune the detection of glare over the fields.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setGlareDetectionConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorGlareDetectionConfiguration","text":"SBSDKDocumentDataExtractorGlareDetectionConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"setGlareDetectionConfiguration(_:)","kind":"symbol","navigatorTitle":[{"text":"setGlareDetectionConfiguration:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelRootType/mrz":{"title":"mrz","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType\/mrz","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelroottype\/mrz","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrz"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelRootType","kind":"typeIdentifier","text":"SBSDKDocumentsModelRootType"}],"abstract":[{"type":"text","text":"MRZ document type."}],"navigatorTitle":[{"kind":"identifier","text":"mrz"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder/setReturnCrops(_:)":{"title":"setReturnCrops(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setReturnCrops"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setReturnCrops(_:)","abstract":[{"text":"Lets you specify if the extractor, should return crops of the detected documents and fields.","type":"text"}],"navigatorTitle":[{"text":"setReturnCrops:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/setreturncrops(_:)","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder/defaultConfiguration":{"abstract":[{"type":"text","text":"Builds the default generic document recognizer configuration, accepting all allowed document types, including machine-readable-zone-based documents,"},{"type":"text","text":" "},{"type":"text","text":"no date validation and no excluded fields."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultConfiguration"}],"title":"defaultConfiguration","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/defaultconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/defaultConfiguration","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfiguration","text":"SBSDKDocumentDataExtractorConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder/addExcludedField(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/addexcludedfield(_:)","role":"symbol","title":"addExcludedField(_:)","abstract":[{"text":"Excludes fields with the specified field name from the result.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/addExcludedField(_:)","navigatorTitle":[{"text":"addExcludedField:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addExcludedField","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder/addDateValidatorConfiguration(_:)":{"abstract":[{"text":"Adds a date validation config for a single field. Existing date validators for the specified field will be overwritten.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/adddatevalidatorconfiguration(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addDateValidatorConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerDateValidationConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"addDateValidatorConfiguration:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/addDateValidatorConfiguration(_:)","title":"addDateValidatorConfiguration(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder/setEuropeanHealthInsuranceCardConfiguration(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setEuropeanHealthInsuranceCardConfiguration(_:)","abstract":[{"text":"Lets you fine-tune the recognition of EU health insurance cards. Setting this property will automatically add the document type ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType\/europeanHealthInsuranceCard"},{"text":" to the accepted document types.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setEuropeanHealthInsuranceCardConfiguration:"}],"type":"topic","title":"setEuropeanHealthInsuranceCardConfiguration(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEuropeanHealthInsuranceCardConfiguration"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardConfiguration","kind":"typeIdentifier","text":"SBSDKEuropeanHealthInsuranceCardConfiguration"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/seteuropeanhealthinsurancecardconfiguration(_:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder/setAcceptedDocumentTypes(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setAcceptedDocumentTypes(_:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/setaccepteddocumenttypes(_:)","navigatorTitle":[{"text":"setAcceptedDocumentTypes:","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"Sets the accepted generic document types. The recognizer will only recognize documents of these types.","type":"text"}],"title":"setAcceptedDocumentTypes(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAcceptedDocumentTypes","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelRootType","text":"SBSDKDocumentsModelRootType","kind":"typeIdentifier"},{"text":"])","kind":"text"}]},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder/setResultAccumulationConfiguration(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setResultAccumulationConfiguration(_:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/setresultaccumulationconfiguration(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setResultAccumulationConfiguration"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKResultAccumulationConfiguration","kind":"typeIdentifier","text":"SBSDKResultAccumulationConfiguration"},{"kind":"text","text":")"}],"type":"topic","title":"setResultAccumulationConfiguration(_:)","abstract":[{"text":"Lets you fine-tune the accumulation of live recognition results.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setResultAccumulationConfiguration:"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder/setAddressDatabaseURL(_:forDocumentTypes:)":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/setaddressdatabaseurl(_:fordocumenttypes:)","kind":"symbol","title":"setAddressDatabaseURL(_:forDocumentTypes:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAddressDatabaseURL","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"forDocumentTypes","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelRootType","text":"SBSDKDocumentsModelRootType","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}],"navigatorTitle":[{"text":"setAddressDatabaseURL:forDocumentTypes:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setAddressDatabaseURL(_:forDocumentTypes:)","abstract":[{"type":"text","text":"Lets you specify the address database URL for the address parser. The address parser uses a database to extract accurate address information from documents."},{"type":"text","text":" "},{"type":"text","text":"Currently the address database only supports german addresses."}]},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder/setMachineReadableZoneConfiguration(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setMachineReadableZoneConfiguration(_:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/setmachinereadablezoneconfiguration(_:)","abstract":[{"type":"text","text":"Lets you fine-tune the recognition of machine-readable-zone-based documents. Setting this property will automatically add the document type "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType\/mrz","isActive":true,"type":"reference"},{"type":"text","text":" to the accepted document types."}],"role":"symbol","title":"setMachineReadableZoneConfiguration(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMachineReadableZoneConfiguration"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorMRZFallbackConfiguration","text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"setMachineReadableZoneConfiguration:"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder/buildConfiguration()":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/buildConfiguration()","title":"buildConfiguration()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKDocumentDataExtractorConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfiguration","kind":"typeIdentifier"}],"abstract":[{"text":"Builds the final configuration that can be passed to the generic document recognizer.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/buildconfiguration()","role":"symbol","navigatorTitle":[{"text":"buildConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelRootType/europeanHealthInsuranceCard":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"europeanHealthInsuranceCard"}],"role":"symbol","abstract":[{"text":"EuropeanHealthInsuranceCard document type.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType\/europeanHealthInsuranceCard","title":"europeanHealthInsuranceCard","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelroottype\/europeanhealthinsurancecard","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"europeanHealthInsuranceCard"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelRootType","kind":"typeIdentifier","text":"SBSDKDocumentsModelRootType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKDocumentDataExtractorConfigurationBuilder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/addDateValidatorConfiguration(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/addExcludedField(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/buildConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/init","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setAcceptedDocumentTypes(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setAddressDatabaseURL(_:forDocumentTypes:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setAutoFocusConfig(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setEuropeanHealthInsuranceCardConfiguration(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setGlareDetectionConfiguration(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setMachineReadableZoneConfiguration(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setResultAccumulationConfiguration(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setReturnCrops(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/defaultConfiguration"],"generated":true,"anchor":"Type-Properties","title":"Type Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/title","value":"SBSDKDocumentDataExtractor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/fragments","value":[{"text":"SBSDKDocumentDataExtractor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/navigatorTitle","value":[{"text":"SBSDKDocumentDataExtractor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder\/title","value":"SBSDKDocumentDataExtractorConfigurationBuilder"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder\/navigatorTitle","value":[{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setAutoFocusConfig(_:)\/title","value":"setAutoFocusConfig:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setAutoFocusConfig(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAutoFocusConfig:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setGlareDetectionConfiguration(_:)\/title","value":"setGlareDetectionConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setGlareDetectionConfiguration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setGlareDetectionConfiguration:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType~1mrz\/title","value":"mrz"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType~1mrz\/fragments","value":[{"kind":"identifier","text":"mrz"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setReturnCrops(_:)\/title","value":"setReturnCrops:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setReturnCrops(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setReturnCrops:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1defaultConfiguration\/title","value":"defaultConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1defaultConfiguration\/fragments","value":[{"text":"defaultConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1addExcludedField(_:)\/title","value":"addExcludedField:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1addExcludedField(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addExcludedField:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1addDateValidatorConfiguration(_:)\/title","value":"addDateValidatorConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1addDateValidatorConfiguration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addDateValidatorConfiguration:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setEuropeanHealthInsuranceCardConfiguration(_:)\/title","value":"setEuropeanHealthInsuranceCardConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setEuropeanHealthInsuranceCardConfiguration(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setEuropeanHealthInsuranceCardConfiguration:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setAcceptedDocumentTypes(_:)\/title","value":"setAcceptedDocumentTypes:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setAcceptedDocumentTypes(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setAcceptedDocumentTypes:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setResultAccumulationConfiguration(_:)\/title","value":"setResultAccumulationConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setResultAccumulationConfiguration(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setResultAccumulationConfiguration:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setAddressDatabaseURL(_:forDocumentTypes:)\/title","value":"setAddressDatabaseURL:forDocumentTypes:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setAddressDatabaseURL(_:forDocumentTypes:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setAddressDatabaseURL:forDocumentTypes:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setMachineReadableZoneConfiguration(_:)\/title","value":"setMachineReadableZoneConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setMachineReadableZoneConfiguration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMachineReadableZoneConfiguration:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1buildConfiguration()\/title","value":"buildConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1buildConfiguration()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"buildConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType~1europeanHealthInsuranceCard\/title","value":"europeanHealthInsuranceCard"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType~1europeanHealthInsuranceCard\/fragments","value":[{"text":"europeanHealthInsuranceCard","kind":"identifier"}]}]}]}