{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Enumeration","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKResamplingMethod","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"enum","externalID":"c:@M@ScanbotSDK@E@SBSDKResamplingMethod","navigatorTitle":[{"text":"SBSDKResamplingMethod","kind":"identifier"}],"title":"SBSDKResamplingMethod"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKResamplingMethod) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKResamplingMethod"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkresamplingmethod"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkresamplingmethod"]}],"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/area","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/cubic","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/lanczos4","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/linear","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/nearest","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/none"],"title":"Enumeration Cases","generated":true},{"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/init(rawValue:)"],"title":"Initializers","generated":true},{"anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"text":"Resampling method.","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod/nearest":{"abstract":[{"text":"Nearest-neighbor interpolation. Lowest quality. Produces blocky images, especially when","type":"text"},{"text":" ","type":"text"},{"text":"upsampling.","type":"text"}],"title":"SBSDKResamplingMethod.nearest","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nearest"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKResamplingMethodNearest"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/nearest","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/nearest"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod/lanczos4":{"abstract":[{"text":"Lanczos (Sinc) interpolation over 8x8 neighborhood. Produces very high quality results,","type":"text"},{"text":" ","type":"text"},{"text":"but slower than bi-cubic. Retains sharp edges like those of text when downsampling.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKResamplingMethodLanczos4","kind":"identifier"}],"title":"SBSDKResamplingMethod.lanczos4","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/lanczos4","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/lanczos4","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"lanczos4","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod/none":{"role":"symbol","navigatorTitle":[{"text":"SBSDKResamplingMethodNone","kind":"identifier"}],"abstract":[{"type":"text","text":"Always geometrically rescale the image to fit the page if necessary. Fast."}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/none","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/none","title":"SBSDKResamplingMethod.none","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod/cubic":{"role":"symbol","navigatorTitle":[{"text":"SBSDKResamplingMethodCubic","kind":"identifier"}],"abstract":[{"text":"Bi-cubic interpolation. Better quality than bi-linear, slower. Produces high-quality","type":"text"},{"text":" ","type":"text"},{"text":"results in a larger range than that of bi-linear.","type":"text"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cubic","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/cubic","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/cubic","title":"SBSDKResamplingMethod.cubic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod/RawRepresentable-Implementations":{"role":"collectionGroup","abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/RawRepresentable-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/rawrepresentable-implementations","title":"RawRepresentable Implementations","kind":"article"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod/linear":{"abstract":[{"type":"text","text":"Bi-linear interpolation. Better quality than nearest-neighbor, slower. Okay when the"},{"type":"text","text":" "},{"type":"text","text":"target size is not too different from the source size."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKResamplingMethodLinear","kind":"identifier"}],"kind":"symbol","type":"topic","title":"SBSDKResamplingMethod.linear","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/linear","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/linear","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"linear","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod":{"type":"topic","role":"symbol","abstract":[{"text":"Resampling method.","type":"text"}],"navigatorTitle":[{"text":"SBSDKResamplingMethod","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKResamplingMethod","kind":"identifier"}],"title":"SBSDKResamplingMethod","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod/init(rawValue:)":{"role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/init(rawValue:)","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/init(rawvalue:)","title":"init(rawValue:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod/area":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"area"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKResamplingMethodArea"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/area","abstract":[{"text":"Accurate, produces moire-free results, but tends to produce blurrier images. When","type":"text"},{"text":" ","type":"text"},{"text":"upsampling, it is similar to nearest-neighbor.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/area","title":"SBSDKResamplingMethod.area","role":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/Equatable-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/equatable-implementations","title":"Equatable Implementations","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKResamplingMethod","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKResamplingMethod","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKResamplingMethod"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/area","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/cubic","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/lanczos4","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/linear","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/nearest","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/none"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKResamplingMethod","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKResamplingMethodNearest","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1nearest\/title"},{"value":[{"text":"SBSDKResamplingMethodNearest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1nearest\/fragments"},{"value":"SBSDKResamplingMethodLanczos4","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1lanczos4\/title"},{"value":[{"kind":"identifier","text":"SBSDKResamplingMethodLanczos4"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1lanczos4\/fragments"},{"value":"SBSDKResamplingMethodNone","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1none\/title"},{"value":[{"kind":"identifier","text":"SBSDKResamplingMethodNone"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1none\/fragments"},{"value":"SBSDKResamplingMethodCubic","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1cubic\/title"},{"value":[{"text":"SBSDKResamplingMethodCubic","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1cubic\/fragments"},{"value":"SBSDKResamplingMethodLinear","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1linear\/title"},{"value":[{"kind":"identifier","text":"SBSDKResamplingMethodLinear"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1linear\/fragments"},{"value":"SBSDKResamplingMethod","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/title"},{"value":[{"kind":"identifier","text":"SBSDKResamplingMethod"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKResamplingMethod"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/navigatorTitle"},{"value":"SBSDKResamplingMethodArea","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1area\/title"},{"value":[{"kind":"identifier","text":"SBSDKResamplingMethodArea"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1area\/fragments"}]}]}