{"topicSections":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAdditionalFrameProcessing\/process(frame:)"]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkadditionalframeprocessing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkadditionalframeprocessing"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAdditionalFrameProcessing","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAdditionalFrameProcessing"}],"role":"symbol","title":"SBSDKAdditionalFrameProcessing","symbolKind":"protocol","roleHeading":"Protocol","navigatorTitle":[{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKAdditionalFrameProcessing","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","abstract":[{"text":"A protocol that allows to perform additional processing of frames before they are passed to the main scanner.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAdditionalFrameProcessing":{"kind":"symbol","type":"topic","role":"symbol","title":"SBSDKAdditionalFrameProcessing","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAdditionalFrameProcessing"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKAdditionalFrameProcessing"}],"url":"\/documentation\/scanbotsdk\/sbsdkadditionalframeprocessing","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAdditionalFrameProcessing","abstract":[{"type":"text","text":"A protocol that allows to perform additional processing of frames before they are passed to the main scanner."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAdditionalFrameProcessing/process(frame:)":{"url":"\/documentation\/scanbotsdk\/sbsdkadditionalframeprocessing\/process(frame:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"process","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBaseScannerFrame","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerFrame"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","navigatorTitle":[{"text":"processWithFrame:","kind":"identifier"}],"kind":"symbol","required":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAdditionalFrameProcessing\/process(frame:)","title":"process(frame:)","abstract":[{"type":"text","text":"Performs additional processing of the frame, e.g. running other scanners on the frame."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKAdditionalFrameProcessing"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAdditionalFrameProcessing\/process(frame:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAdditionalFrameProcessing\/title","value":"SBSDKAdditionalFrameProcessing"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAdditionalFrameProcessing\/fragments","value":[{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAdditionalFrameProcessing\/navigatorTitle","value":[{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAdditionalFrameProcessing~1process(frame:)\/title","value":"processWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAdditionalFrameProcessing~1process(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processWithFrame:"}]}]}]}