{"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/always","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/badQuality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/none"],"anchor":"Enumeration-Cases"},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKUI2AcknowledgementMode) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AcknowledgementMode"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKUI2AcknowledgementMode","symbolKind":"enum","roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementMode"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKUI2AcknowledgementMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2AcknowledgementMode","kind":"identifier"}]},"sections":[],"abstract":[{"type":"text","text":"Determines, after each page is snapped, whether the acknowledgment screen should be displayed or not."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementMode/none":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/none","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2AcknowledgementModeNone","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode\/none","abstract":[{"type":"text","text":"The acknowledgement screen will be disabled, in effect never shown."}],"title":"SBSDKUI2AcknowledgementMode.none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementMode/init(rawValue:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/init(rawValue:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode\/init(rawvalue:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementMode/always":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/always","type":"topic","title":"SBSDKUI2AcknowledgementMode.always","abstract":[{"text":"The acknowledgement screen will always be shown after each snap, regardless of the scanned page’s quality.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode\/always","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"always"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementModeAlways"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementMode/RawRepresentable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode\/rawrepresentable-implementations","abstract":[],"kind":"article","title":"RawRepresentable Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/RawRepresentable-Implementations","type":"topic","role":"collectionGroup"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementMode/badQuality":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badQuality","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode\/badquality","abstract":[{"text":"The acknowledgement screen will only be shown when the quality of a scanned page is unacceptable. The quality","type":"text"},{"type":"text","text":" "},{"type":"text","text":"threshold is determined by the "},{"type":"codeVoice","code":"minimumQuality"},{"type":"text","text":" parameter."}],"navigatorTitle":[{"text":"SBSDKUI2AcknowledgementModeBadQuality","kind":"identifier"}],"title":"SBSDKUI2AcknowledgementMode.badQuality","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/badQuality","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementMode":{"type":"topic","abstract":[{"text":"Determines, after each page is snapped, whether the acknowledgment screen should be displayed or not.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode","title":"SBSDKUI2AcknowledgementMode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementMode"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AcknowledgementMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementMode/Equatable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode\/equatable-implementations","abstract":[],"type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/Equatable-Implementations","role":"collectionGroup","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKUI2AcknowledgementMode","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKUI2AcknowledgementMode","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementMode"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/always","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/badQuality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/none"],"title":"Enumeration Cases","generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AcknowledgementMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUI2AcknowledgementModeNone","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode~1none\/title","op":"replace"},{"value":[{"text":"SBSDKUI2AcknowledgementModeNone","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode~1none\/fragments","op":"replace"},{"value":"SBSDKUI2AcknowledgementModeAlways","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode~1always\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementModeAlways"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode~1always\/fragments","op":"replace"},{"value":"SBSDKUI2AcknowledgementModeBadQuality","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode~1badQuality\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementModeBadQuality"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode~1badQuality\/fragments","op":"replace"},{"value":"SBSDKUI2AcknowledgementMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode\/title","op":"replace"},{"value":[{"text":"SBSDKUI2AcknowledgementMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode\/navigatorTitle","op":"replace"}]}]}