{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKUI2VINScannerScreenTextLocalization) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2VINScannerScreenTextLocalization"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization"},"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerScreenTextLocalization","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2VINScannerScreenTextLocalization","kind":"identifier"}],"title":"SBSDKUI2VINScannerScreenTextLocalization","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2VINScannerScreenTextLocalization"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"abstract":[{"text":"Configuration of the all strings for generic text scanner screen.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/init()"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionCameraPermissionCloseButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionCameraPermissionEnableCameraButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionConfirmationCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionConfirmationSubmitButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionFlashButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionFlipCameraButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionIntroScreenDoneButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionOpenIntroScreenButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionZoomButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/cameraPermissionCloseButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/cameraPermissionEnableCameraButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/cameraPermissionEnableCameraExplanation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/cameraPermissionEnableCameraTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/completionOverlaySuccessMessage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/finderViewUserGuidance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/introScreenDoneButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/introScreenText","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/introScreenTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/topBarCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/topBarTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/topUserGuidance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/vinConfirmationAlertCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/vinConfirmationAlertSubmitButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/vinConfirmationAlertTitle"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/toJson(configuration:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/introScreenTitle":{"navigatorTitle":[{"kind":"identifier","text":"introScreenTitle"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Title for the introduction screen.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"introScreenTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/introScreenTitle","title":"introScreenTitle","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/introscreentitle","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/accessibilityDescriptionOpenIntroScreenButton":{"title":"accessibilityDescriptionOpenIntroScreenButton","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionOpenIntroScreenButton","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptionopenintroscreenbutton","abstract":[{"text":"Accessibility description for the ‘open introduction screen’ button in top bar.","type":"text"}],"navigatorTitle":[{"text":"accessibilityDescriptionOpenIntroScreenButton","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionOpenIntroScreenButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/cameraPermissionEnableCameraTitle":{"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/camerapermissionenablecameratitle","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"cameraPermissionEnableCameraTitle","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The title of the camera permission dialog."}],"title":"cameraPermissionEnableCameraTitle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/cameraPermissionEnableCameraTitle","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/accessibilityDescriptionIntroScreenDoneButton":{"abstract":[{"text":"Accessibility description for the ‘done’\/‘start scanning’ button in the introduction screen.","type":"text"}],"navigatorTitle":[{"text":"accessibilityDescriptionIntroScreenDoneButton","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionIntroScreenDoneButton","type":"topic","kind":"symbol","title":"accessibilityDescriptionIntroScreenDoneButton","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptionintroscreendonebutton","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionIntroScreenDoneButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/topBarTitle":{"kind":"symbol","navigatorTitle":[{"text":"topBarTitle","kind":"identifier"}],"title":"topBarTitle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/topBarTitle","abstract":[{"type":"text","text":"Title for the top bar."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/topbartitle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/topUserGuidance":{"title":"topUserGuidance","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/topuserguidance","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topUserGuidance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/topUserGuidance","role":"symbol","type":"topic","navigatorTitle":[{"text":"topUserGuidance","kind":"identifier"}],"abstract":[{"text":"Text for the top user guidance caption.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/accessibilityDescriptionConfirmationCancelButton":{"kind":"symbol","abstract":[{"type":"text","text":"Accessibility description for the cancel button in the text pattern confirmation alert."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionConfirmationCancelButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionConfirmationCancelButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","navigatorTitle":[{"text":"accessibilityDescriptionConfirmationCancelButton","kind":"identifier"}],"type":"topic","title":"accessibilityDescriptionConfirmationCancelButton","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptionconfirmationcancelbutton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/accessibilityDescriptionFlipCameraButton":{"kind":"symbol","navigatorTitle":[{"text":"accessibilityDescriptionFlipCameraButton","kind":"identifier"}],"type":"topic","role":"symbol","title":"accessibilityDescriptionFlipCameraButton","abstract":[{"text":"Accessibility description for the flip camera button.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionFlipCameraButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptionflipcamerabutton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionFlipCameraButton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/accessibilityDescriptionCancelButton":{"kind":"symbol","title":"accessibilityDescriptionCancelButton","abstract":[{"type":"text","text":"Accessibility description for the ‘cancel’ button in the top bar."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionCancelButton","type":"topic","navigatorTitle":[{"text":"accessibilityDescriptionCancelButton","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCancelButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptioncancelbutton"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2VINScannerScreenTextLocalization","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2VINScannerScreenTextLocalization","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the all strings for generic text scanner screen."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization","title":"SBSDKUI2VINScannerScreenTextLocalization","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:vinConfirmationAlertTitle:vinConfirmationAlertCancelButton:vinConfirmationAlertSubmitButton:accessibilityDescriptionConfirmationCancelButton:accessibilityDescriptionConfirmationSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:":{"abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:vinConfirmationAlertTitle:vinConfirmationAlertCancelButton:vinConfirmationAlertSubmitButton:accessibilityDescriptionConfirmationCancelButton:accessibilityDescriptionConfirmationSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:vinConfirmationAlertTitle:vinConfirmationAlertCancelButton:vinConfirmationAlertSubmitButton:accessibilityDescriptionConfirmationCancelButton:accessibilityDescriptionConfirmationSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","type":"topic","kind":"symbol","navigatorTitle":[{"text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:vinConfirmationAlertTitle:vinConfirmationAlertCancelButton:vinConfirmationAlertSubmitButton:accessibilityDescriptionConfirmationCancelButton:accessibilityDescriptionConfirmationSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"title":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:vinConfirmationAlertTitle:vinConfirmationAlertCancelButton:vinConfirmationAlertSubmitButton:accessibilityDescriptionConfirmationCancelButton:accessibilityDescriptionConfirmationSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/initwithtopbartitle:topbarcancelbutton:topuserguidance:finderviewuserguidance:introscreentitle:introscreendonebutton:introscreentext:completionoverlaysuccessmessage:accessibilitydescriptionopenintroscreenbutton:accessibilitydescriptionintro-82ctw"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/finderViewUserGuidance":{"abstract":[{"type":"text","text":"Text for the user guidance caption below the finder view."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderViewUserGuidance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/finderViewUserGuidance","type":"topic","kind":"symbol","navigatorTitle":[{"text":"finderViewUserGuidance","kind":"identifier"}],"title":"finderViewUserGuidance","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/finderviewuserguidance"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/vinConfirmationAlertSubmitButton":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/vinConfirmationAlertSubmitButton","abstract":[{"text":"Submit button text for the text pattern confirmation alert.","type":"text"}],"title":"vinConfirmationAlertSubmitButton","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vinConfirmationAlertSubmitButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"vinConfirmationAlertSubmitButton","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/vinconfirmationalertsubmitbutton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/completionOverlaySuccessMessage":{"navigatorTitle":[{"text":"completionOverlaySuccessMessage","kind":"identifier"}],"title":"completionOverlaySuccessMessage","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/completionOverlaySuccessMessage","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"completionOverlaySuccessMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/completionoverlaysuccessmessage","abstract":[{"type":"text","text":"Caption for the success overlay."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/accessibilityDescriptionCameraPermissionCloseButton":{"title":"accessibilityDescriptionCameraPermissionCloseButton","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionCameraPermissionCloseButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptioncamerapermissionclosebutton","navigatorTitle":[{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"}],"abstract":[{"text":"The accessibility hint for the ‘close’ button of the camera permission dialog.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/accessibilityDescriptionConfirmationSubmitButton":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"accessibilityDescriptionConfirmationSubmitButton","kind":"identifier"}],"title":"accessibilityDescriptionConfirmationSubmitButton","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptionconfirmationsubmitbutton","type":"topic","abstract":[{"type":"text","text":"Accessibility description for the submit button in the text pattern confirmation alert."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionConfirmationSubmitButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionConfirmationSubmitButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/topBarCancelButton":{"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/topbarcancelbutton","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/topBarCancelButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarCancelButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"topBarCancelButton","kind":"identifier"}],"abstract":[{"text":"Cancel button text for the top bar.","type":"text"}],"title":"topBarCancelButton","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/vinConfirmationAlertCancelButton":{"navigatorTitle":[{"text":"vinConfirmationAlertCancelButton","kind":"identifier"}],"title":"vinConfirmationAlertCancelButton","abstract":[{"type":"text","text":"Cancel button text for the text pattern confirmation alert."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/vinConfirmationAlertCancelButton","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/vinconfirmationalertcancelbutton","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vinConfirmationAlertCancelButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/introScreenDoneButton":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/introScreenDoneButton","type":"topic","title":"introScreenDoneButton","abstract":[{"text":"Start scanning button text for the introduction screen.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"introScreenDoneButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"introScreenDoneButton","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/introscreendonebutton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/cameraPermissionCloseButton":{"abstract":[{"type":"text","text":"The ‘close’ button title of the camera permission dialog."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPermissionCloseButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/camerapermissionclosebutton","navigatorTitle":[{"text":"cameraPermissionCloseButton","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/cameraPermissionCloseButton","kind":"symbol","title":"cameraPermissionCloseButton","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/accessibilityDescriptionFlashButton":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptionflashbutton","abstract":[{"text":"Accessibility description for the flash button.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionFlashButton","type":"topic","navigatorTitle":[{"text":"accessibilityDescriptionFlashButton","kind":"identifier"}],"title":"accessibilityDescriptionFlashButton","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionFlashButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/hash":{"fragments":[{"text":"hash","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/hash","role":"symbol","title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/hash","type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/vinConfirmationAlertTitle":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/vinConfirmationAlertTitle","navigatorTitle":[{"text":"vinConfirmationAlertTitle","kind":"identifier"}],"abstract":[{"text":"Title for the text pattern confirmation alert.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vinConfirmationAlertTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","title":"vinConfirmationAlertTitle","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/vinconfirmationalerttitle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/accessibilityDescriptionZoomButton":{"type":"topic","navigatorTitle":[{"text":"accessibilityDescriptionZoomButton","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionZoomButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionZoomButton","kind":"symbol","abstract":[{"type":"text","text":"Accessibility description for the zoom button."}],"title":"accessibilityDescriptionZoomButton","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptionzoombutton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/fromJsonWithJson:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/fromjsonwithjson:","title":"fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/fromJsonWithJson:","abstract":[],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/copyWithZone:":{"abstract":[],"title":"copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/copywithzone:","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/copyWithZone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/cameraPermissionEnableCameraButton":{"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/camerapermissionenablecamerabutton","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"The ‘enable’ button title of the camera permission dialog.","type":"text"}],"title":"cameraPermissionEnableCameraButton","navigatorTitle":[{"text":"cameraPermissionEnableCameraButton","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/cameraPermissionEnableCameraButton"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/isEqual:":{"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/isequal:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/isEqual:","title":"isEqual:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/accessibilityDescriptionCameraPermissionEnableCameraButton":{"kind":"symbol","title":"accessibilityDescriptionCameraPermissionEnableCameraButton","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptioncamerapermissionenablecamerabutton","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionCameraPermissionEnableCameraButton","abstract":[{"text":"The accessibility hint for the ‘enable’ button of the camera permission dialog.","type":"text"}],"navigatorTitle":[{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/introScreenText":{"title":"introScreenText","navigatorTitle":[{"text":"introScreenText","kind":"identifier"}],"abstract":[{"text":"The text explanation for the introduction screen.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/introscreentext","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/introScreenText","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"introScreenText","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/cameraPermissionEnableCameraExplanation":{"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/camerapermissionenablecameraexplanation","navigatorTitle":[{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/cameraPermissionEnableCameraExplanation","type":"topic","abstract":[{"text":"The explanation text of the camera permission dialog.","type":"text"}],"title":"cameraPermissionEnableCameraExplanation","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/init()":{"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/init()","type":"topic","abstract":[],"title":"init()","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Abstract class for all the configurations."}],"navigatorTitle":[{"text":"SBSDKUI2Node","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2node","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Node","kind":"identifier"}],"title":"SBSDKUI2Node","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","role":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/toJson(configuration:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"title":"toJson(configuration:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/toJson(configuration:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/tojson(configuration:)","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUI2VINScannerScreenTextLocalization"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2VINScannerScreenTextLocalization"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2VINScannerScreenTextLocalization"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionCameraPermissionCloseButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionCameraPermissionEnableCameraButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionConfirmationCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionConfirmationSubmitButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionFlashButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionFlipCameraButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionIntroScreenDoneButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionOpenIntroScreenButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionZoomButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/cameraPermissionCloseButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/cameraPermissionEnableCameraButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/cameraPermissionEnableCameraExplanation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/cameraPermissionEnableCameraTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/completionOverlaySuccessMessage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/finderViewUserGuidance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/introScreenDoneButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/introScreenText","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/introScreenTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/topBarCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/topBarTitle","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/topUserGuidance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/vinConfirmationAlertCancelButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/vinConfirmationAlertSubmitButton","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/vinConfirmationAlertTitle"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:vinConfirmationAlertTitle:vinConfirmationAlertCancelButton:vinConfirmationAlertSubmitButton:accessibilityDescriptionConfirmationCancelButton:accessibilityDescriptionConfirmationSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/fromJsonWithJson:"],"generated":true,"anchor":"Type-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2VINScannerScreenTextLocalization"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node","text":"SBSDKUI2Node"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1introScreenTitle\/title","op":"replace","value":"introScreenTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1introScreenTitle\/fragments","op":"replace","value":[{"text":"introScreenTitle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionOpenIntroScreenButton\/title","op":"replace","value":"accessibilityDescriptionOpenIntroScreenButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionOpenIntroScreenButton\/fragments","op":"replace","value":[{"text":"accessibilityDescriptionOpenIntroScreenButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1cameraPermissionEnableCameraTitle\/title","op":"replace","value":"cameraPermissionEnableCameraTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1cameraPermissionEnableCameraTitle\/fragments","op":"replace","value":[{"kind":"identifier","text":"cameraPermissionEnableCameraTitle"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionIntroScreenDoneButton\/title","op":"replace","value":"accessibilityDescriptionIntroScreenDoneButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionIntroScreenDoneButton\/fragments","op":"replace","value":[{"text":"accessibilityDescriptionIntroScreenDoneButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1topBarTitle\/title","op":"replace","value":"topBarTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1topBarTitle\/fragments","op":"replace","value":[{"text":"topBarTitle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1topUserGuidance\/title","op":"replace","value":"topUserGuidance"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1topUserGuidance\/fragments","op":"replace","value":[{"kind":"identifier","text":"topUserGuidance"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionConfirmationCancelButton\/title","op":"replace","value":"accessibilityDescriptionConfirmationCancelButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionConfirmationCancelButton\/fragments","op":"replace","value":[{"text":"accessibilityDescriptionConfirmationCancelButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionFlipCameraButton\/title","op":"replace","value":"accessibilityDescriptionFlipCameraButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionFlipCameraButton\/fragments","op":"replace","value":[{"kind":"identifier","text":"accessibilityDescriptionFlipCameraButton"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionCancelButton\/title","op":"replace","value":"accessibilityDescriptionCancelButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionCancelButton\/fragments","op":"replace","value":[{"text":"accessibilityDescriptionCancelButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization\/title","op":"replace","value":"SBSDKUI2VINScannerScreenTextLocalization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization\/fragments","op":"replace","value":[{"text":"SBSDKUI2VINScannerScreenTextLocalization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2VINScannerScreenTextLocalization"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1finderViewUserGuidance\/title","op":"replace","value":"finderViewUserGuidance"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1finderViewUserGuidance\/fragments","op":"replace","value":[{"text":"finderViewUserGuidance","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1vinConfirmationAlertSubmitButton\/title","op":"replace","value":"vinConfirmationAlertSubmitButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1vinConfirmationAlertSubmitButton\/fragments","op":"replace","value":[{"text":"vinConfirmationAlertSubmitButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1completionOverlaySuccessMessage\/title","op":"replace","value":"completionOverlaySuccessMessage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1completionOverlaySuccessMessage\/fragments","op":"replace","value":[{"text":"completionOverlaySuccessMessage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionCameraPermissionCloseButton\/title","op":"replace","value":"accessibilityDescriptionCameraPermissionCloseButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionCameraPermissionCloseButton\/fragments","op":"replace","value":[{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionConfirmationSubmitButton\/title","op":"replace","value":"accessibilityDescriptionConfirmationSubmitButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionConfirmationSubmitButton\/fragments","op":"replace","value":[{"kind":"identifier","text":"accessibilityDescriptionConfirmationSubmitButton"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1topBarCancelButton\/title","op":"replace","value":"topBarCancelButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1topBarCancelButton\/fragments","op":"replace","value":[{"kind":"identifier","text":"topBarCancelButton"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1vinConfirmationAlertCancelButton\/title","op":"replace","value":"vinConfirmationAlertCancelButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1vinConfirmationAlertCancelButton\/fragments","op":"replace","value":[{"text":"vinConfirmationAlertCancelButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1introScreenDoneButton\/title","op":"replace","value":"introScreenDoneButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1introScreenDoneButton\/fragments","op":"replace","value":[{"text":"introScreenDoneButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1cameraPermissionCloseButton\/title","op":"replace","value":"cameraPermissionCloseButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1cameraPermissionCloseButton\/fragments","op":"replace","value":[{"text":"cameraPermissionCloseButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionFlashButton\/title","op":"replace","value":"accessibilityDescriptionFlashButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionFlashButton\/fragments","op":"replace","value":[{"kind":"identifier","text":"accessibilityDescriptionFlashButton"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1vinConfirmationAlertTitle\/title","op":"replace","value":"vinConfirmationAlertTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1vinConfirmationAlertTitle\/fragments","op":"replace","value":[{"text":"vinConfirmationAlertTitle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionZoomButton\/title","op":"replace","value":"accessibilityDescriptionZoomButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionZoomButton\/fragments","op":"replace","value":[{"text":"accessibilityDescriptionZoomButton","kind":"identifier"}]},{"value":"cameraPermissionEnableCameraButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1cameraPermissionEnableCameraButton\/title","op":"replace"},{"value":[{"text":"cameraPermissionEnableCameraButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1cameraPermissionEnableCameraButton\/fragments","op":"replace"},{"value":"accessibilityDescriptionCameraPermissionEnableCameraButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionCameraPermissionEnableCameraButton\/title","op":"replace"},{"value":[{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionCameraPermissionEnableCameraButton\/fragments","op":"replace"},{"value":"introScreenText","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1introScreenText\/title","op":"replace"},{"value":[{"kind":"identifier","text":"introScreenText"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1introScreenText\/fragments","op":"replace"},{"value":"cameraPermissionEnableCameraExplanation","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1cameraPermissionEnableCameraExplanation\/title","op":"replace"},{"value":[{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1cameraPermissionEnableCameraExplanation\/fragments","op":"replace"},{"value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1init()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1init()\/fragments","op":"replace"},{"value":"SBSDKUI2Node","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title","op":"replace"},{"value":[{"text":"SBSDKUI2Node","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Node"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/navigatorTitle","op":"replace"},{"value":"toJsonWithConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1toJson(configuration:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1toJson(configuration:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}