{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation"},"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/horizontal","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/undefined","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/vertical"]},{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/init(rawValue:)"]},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLineSegmentOrientation","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"SBSDKLineSegmentOrientation","externalID":"c:@M@ScanbotSDK@E@SBSDKLineSegmentOrientation","symbolKind":"enum","navigatorTitle":[{"text":"SBSDKLineSegmentOrientation","kind":"identifier"}],"roleHeading":"Enumeration","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLineSegmentOrientation","kind":"identifier"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklinesegmentorientation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdklinesegmentorientation"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"An enum describing the orientation of a polygon edge.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegmentOrientation/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/RawRepresentable-Implementations","kind":"article","abstract":[],"type":"topic","role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/scanbotsdk\/sbsdklinesegmentorientation\/rawrepresentable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegmentOrientation/horizontal":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontal"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/horizontal","url":"\/documentation\/scanbotsdk\/sbsdklinesegmentorientation\/horizontal","navigatorTitle":[{"kind":"identifier","text":"SBSDKLineSegmentOrientationHorizontal"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The edge is oriented horizontally."}],"title":"SBSDKLineSegmentOrientation.horizontal"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegmentOrientation/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/init(rawValue:)","url":"\/documentation\/scanbotsdk\/sbsdklinesegmentorientation\/init(rawvalue:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegmentOrientation":{"url":"\/documentation\/scanbotsdk\/sbsdklinesegmentorientation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLineSegmentOrientation","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKLineSegmentOrientation","kind":"identifier"}],"abstract":[{"text":"An enum describing the orientation of a polygon edge.","type":"text"}],"title":"SBSDKLineSegmentOrientation","role":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegmentOrientation/undefined":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"undefined","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKLineSegmentOrientationUndefined","kind":"identifier"}],"abstract":[{"text":"The edge is oriented 45° from x- and y-axis.","type":"text"}],"kind":"symbol","title":"SBSDKLineSegmentOrientation.undefined","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/undefined","url":"\/documentation\/scanbotsdk\/sbsdklinesegmentorientation\/undefined","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegmentOrientation/vertical":{"url":"\/documentation\/scanbotsdk\/sbsdklinesegmentorientation\/vertical","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKLineSegmentOrientationVertical"}],"title":"SBSDKLineSegmentOrientation.vertical","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"vertical"}],"abstract":[{"text":"The edge is oriented vertically.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/vertical"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegmentOrientation/Equatable-Implementations":{"type":"topic","kind":"article","role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdklinesegmentorientation\/equatable-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/Equatable-Implementations","abstract":[],"title":"Equatable Implementations"},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKLineSegmentOrientation","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKLineSegmentOrientation","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKLineSegmentOrientation","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/horizontal","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/undefined","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentOrientation\/vertical"],"generated":true,"anchor":"Enumeration-Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLineSegmentOrientation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKLineSegmentOrientationHorizontal","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation~1horizontal\/title"},{"value":[{"text":"SBSDKLineSegmentOrientationHorizontal","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation~1horizontal\/fragments"},{"value":"SBSDKLineSegmentOrientation","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation\/title"},{"value":[{"text":"SBSDKLineSegmentOrientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKLineSegmentOrientation"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation\/navigatorTitle"},{"value":"SBSDKLineSegmentOrientationUndefined","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation~1undefined\/title"},{"value":[{"kind":"identifier","text":"SBSDKLineSegmentOrientationUndefined"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation~1undefined\/fragments"},{"value":"SBSDKLineSegmentOrientationVertical","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation~1vertical\/title"},{"value":[{"text":"SBSDKLineSegmentOrientationVertical","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentOrientation~1vertical\/fragments"}]}]}