{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentTrustMode"}],"symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentTrustMode"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentTrustMode","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKDocumentTrustMode","roleHeading":"Enumeration"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKDocumentTrustMode) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentTrustMode","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumenttrustmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumenttrustmode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode","interfaceLanguage":"swift"},"abstract":[{"text":"Level of trust in the authenticity of the extracted document.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode\/trusted","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode\/untrusted"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentTrustMode/init(rawValue:)":{"kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumenttrustmode\/init(rawvalue:)","type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentTrustMode/untrusted":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"untrusted"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentTrustModeUntrusted"}],"type":"topic","role":"symbol","abstract":[{"text":"The extracted document is not trusted, i.e. its authenticity cannot be assumed. All fields will be read out","type":"text"},{"text":" ","type":"text"},{"text":"independently and can be further verified. Extracting untrusted documents takes slightly longer, as the","type":"text"},{"text":" ","type":"text"},{"text":"extractor is not allowed to employ certain time-saving optimizations.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumenttrustmode\/untrusted","title":"SBSDKDocumentTrustMode.untrusted","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode\/untrusted"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentTrustMode/Equatable-Implementations":{"abstract":[],"type":"topic","role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode\/Equatable-Implementations","kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkdocumenttrustmode\/equatable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentTrustMode/trusted":{"abstract":[{"text":"The extracted document is trusted, i.e. the scanner may assume that it’s authentic. This allows certain","type":"text"},{"text":" ","type":"text"},{"text":"optimizations that make extraction faster.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trusted"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode\/trusted","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentTrustModeTrusted"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumenttrustmode\/trusted","title":"SBSDKDocumentTrustMode.trusted","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentTrustMode":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Level of trust in the authenticity of the extracted document."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentTrustMode","kind":"identifier"}],"title":"SBSDKDocumentTrustMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumenttrustmode","navigatorTitle":[{"text":"SBSDKDocumentTrustMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentTrustMode/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","kind":"article","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkdocumenttrustmode\/rawrepresentable-implementations","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKDocumentTrustMode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKDocumentTrustMode","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKDocumentTrustMode","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode\/trusted","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentTrustMode\/untrusted"],"generated":true,"anchor":"Enumeration-Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentTrustMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentTrustMode~1untrusted\/title","value":"SBSDKDocumentTrustModeUntrusted","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentTrustMode~1untrusted\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentTrustModeUntrusted"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentTrustMode~1trusted\/title","value":"SBSDKDocumentTrustModeTrusted","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentTrustMode~1trusted\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentTrustModeTrusted"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentTrustMode\/title","value":"SBSDKDocumentTrustMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentTrustMode\/fragments","value":[{"text":"SBSDKDocumentTrustMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentTrustMode\/navigatorTitle","value":[{"text":"SBSDKDocumentTrustMode","kind":"identifier"}],"op":"replace"}]}]}