{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor"},"sections":[],"abstract":[{"text":"A class to process images.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"SBSDKImageProcessor","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKImageProcessor","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageProcessor","symbolKind":"class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageProcessor","kind":"identifier"}]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/init(imageRef:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/init(imageURL:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/init(uiImage:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/imageRef","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/processedImage"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyCrop(points:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyCrop(polygon:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyFilter(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyFilters(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyResize(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyRotation(_:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyCrop(points:on:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyCrop(polygon:on:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyFilter(_:on:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyFilters(_:on:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyResize(_:on:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyRotation(_:on:)"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageProcessor","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageprocessor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageprocessor"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/init(uiImage:)":{"title":"init(uiImage:)","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/init(uiimage:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/init(uiImage:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uiImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithUiImage:","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Initializes an image processor with an input image."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/applyFilters(_:on:)":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyFilters","kind":"identifier"},{"text":"([","kind":"text"},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"text":"], ","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyFilters(_:on:)","abstract":[{"text":"Applies multiple filters to an image.","type":"text"}],"type":"topic","title":"applyFilters(_:on:)","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applyfilters(_:on:)","role":"symbol","navigatorTitle":[{"text":"applyFilters:on:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/applyResize(_:)":{"kind":"symbol","abstract":[{"text":"Uniformly resizes the input image to the given size, so that its larger dimension matches the given size.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyResize(_:)","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applyresize(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applyResize"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":")"}],"title":"applyResize(_:)","navigatorTitle":[{"kind":"identifier","text":"applyResize:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/applyCrop(points:)":{"abstract":[{"type":"text","text":"Crops the input image by the given polygon and performs perspective correction."}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applyCropWithPoints:"}],"title":"applyCrop(points:)","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applycrop(points:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applyCrop"},{"kind":"text","text":"("},{"kind":"externalParam","text":"points"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyCrop(points:)"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/imageRef":{"navigatorTitle":[{"kind":"identifier","text":"imageRef"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/imageRef","role":"symbol","title":"imageRef","abstract":[{"text":"The input image.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageRef"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/imageref"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/applyFilter(_:on:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyFilter(_:on:)","abstract":[{"text":"Applies a filter to an image.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applyfilter(_:on:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyFilter","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"applyFilter:on:","kind":"identifier"}],"type":"topic","role":"symbol","title":"applyFilter(_:on:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/applyCrop(polygon:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyCrop","kind":"identifier"},{"text":"(","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"text":"?)","kind":"text"}],"role":"symbol","title":"applyCrop(polygon:)","abstract":[{"text":"Crops the input image by the given polygon and performs perspective correction.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyCrop(polygon:)","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applycrop(polygon:)","navigatorTitle":[{"text":"applyCropWithPolygon:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageProcessor"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor","type":"topic","abstract":[{"text":"A class to process images.","type":"text"}],"title":"SBSDKImageProcessor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageProcessor"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/init(imageURL:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithImageURL:"}],"type":"topic","abstract":[{"type":"text","text":"Initializes and image processor with an input image at the given URL. If there is no valid image on the URL, "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" is returned."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/init(imageURL:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"imageURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"title":"init(imageURL:)","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/init(imageurl:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/applyRotation(_:on:)":{"abstract":[{"text":"Rotates an image in the given direction.","type":"text"}],"title":"applyRotation(_:on:)","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applyrotation(_:on:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyRotation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKImageRotation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageRotation"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyRotation(_:on:)","navigatorTitle":[{"text":"applyRotation:on:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/applyResize(_:on:)":{"abstract":[{"type":"text","text":"Uniformly resizes an image to the given size, so that its larger dimension matches the given size."}],"url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applyresize(_:on:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applyResize:on:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyResize(_:on:)","title":"applyResize(_:on:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyResize","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/applyCrop(points:on:)":{"role":"symbol","navigatorTitle":[{"text":"applyCropWithPoints:on:","kind":"identifier"}],"title":"applyCrop(points:on:)","abstract":[{"text":"Crops an image by the given polygon and performs perspective correction.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applycrop(points:on:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyCrop","kind":"identifier"},{"text":"(","kind":"text"},{"text":"points","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":"], ","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyCrop(points:on:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/applyRotation(_:)":{"role":"symbol","navigatorTitle":[{"text":"applyRotation:","kind":"identifier"}],"abstract":[{"text":"Rotates the input image in the given direction.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyRotation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKImageRotation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageRotation"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyRotation(_:)","title":"applyRotation(_:)","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applyrotation(_:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/init(imageRef:)":{"navigatorTitle":[{"text":"initWithImageRef:","kind":"identifier"}],"title":"init(imageRef:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/init(imageRef:)","abstract":[{"type":"text","text":"Initializes an image processor with an input image."}],"url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/init(imageref:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"imageRef","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/applyFilter(_:)":{"navigatorTitle":[{"text":"applyFilter:","kind":"identifier"}],"title":"applyFilter(_:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyFilter(_:)","abstract":[{"text":"Applies a filter to the input image.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applyfilter(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyFilter","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/processedImage":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/processedImage","abstract":[{"text":"The current ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" representation of the processed image."}],"title":"processedImage","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/processedimage","navigatorTitle":[{"kind":"identifier","text":"processedImage"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"processedImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/applyFilters(_:)":{"title":"applyFilters(_:)","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applyfilters(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applyFilters"},{"kind":"text","text":"(["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier","text":"SBSDKParametricFilter"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"applyFilters:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyFilters(_:)","abstract":[{"type":"text","text":"Applies multiple filters to the input image."}],"type":"topic","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/applyCrop(polygon:on:)":{"title":"applyCrop(polygon:on:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyCrop","kind":"identifier"},{"text":"(","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"applyCropWithPolygon:on:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyCrop(polygon:on:)","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applycrop(polygon:on:)","abstract":[{"text":"Crops an image by the given polygon and performs perspective correction.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKImageProcessor"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKImageProcessor","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageProcessor","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/imageRef","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/processedImage"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyCrop(points:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyCrop(polygon:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyFilter(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyFilters(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyResize(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyRotation(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/init(imageRef:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/init(imageURL:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/init(uiImage:)"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyCrop(points:on:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyCrop(polygon:on:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyFilter(_:on:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyFilters(_:on:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyResize(_:on:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyRotation(_:on:)"],"anchor":"Type-Methods","title":"Type Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageProcessor","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1init(uiImage:)\/title","op":"replace","value":"initWithUiImage:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1init(uiImage:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithUiImage:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyFilters(_:on:)\/title","value":"applyFilters:on:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyFilters(_:on:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"applyFilters:on:"}]},{"value":"applyResize:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyResize(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applyResize:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyResize(_:)\/fragments","op":"replace"},{"value":"applyCropWithPoints:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyCrop(points:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"applyCropWithPoints:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyCrop(points:)\/fragments","op":"replace"},{"value":"imageRef","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1imageRef\/title","op":"replace"},{"value":[{"text":"imageRef","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1imageRef\/fragments","op":"replace"},{"value":"applyFilter:on:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyFilter(_:on:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"applyFilter:on:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyFilter(_:on:)\/fragments","op":"replace"},{"value":"applyCropWithPolygon:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyCrop(polygon:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applyCropWithPolygon:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyCrop(polygon:)\/fragments","op":"replace"},{"value":"SBSDKImageProcessor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageProcessor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/fragments","op":"replace"},{"value":[{"text":"SBSDKImageProcessor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/navigatorTitle","op":"replace"},{"value":"initWithImageURL:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1init(imageURL:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageURL:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1init(imageURL:)\/fragments","op":"replace"},{"value":"applyRotation:on:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyRotation(_:on:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"applyRotation:on:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyRotation(_:on:)\/fragments","op":"replace"},{"value":"applyResize:on:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyResize(_:on:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"applyResize:on:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyResize(_:on:)\/fragments","op":"replace"},{"value":"applyCropWithPoints:on:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyCrop(points:on:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"applyCropWithPoints:on:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyCrop(points:on:)\/fragments","op":"replace"},{"value":"applyRotation:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyRotation(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"applyRotation:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyRotation(_:)\/fragments","op":"replace"},{"value":"initWithImageRef:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1init(imageRef:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageRef:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1init(imageRef:)\/fragments","op":"replace"},{"value":"applyFilter:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyFilter(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"applyFilter:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyFilter(_:)\/fragments","op":"replace"},{"value":"processedImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1processedImage\/title","op":"replace"},{"value":[{"text":"processedImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1processedImage\/fragments","op":"replace"},{"value":"applyFilters:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyFilters(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applyFilters:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyFilters(_:)\/fragments","op":"replace"},{"value":"applyCropWithPolygon:on:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyCrop(polygon:on:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"applyCropWithPolygon:on:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyCrop(polygon:on:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}