{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration\/initwithstatusbarmode:topbarbackgroundcolor:bottombarbackgroundcolor:orientationlockmode:"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentFlowAppearanceConfiguration(im)initWithStatusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:","navigatorTitle":[{"text":"initWithStatusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithStatusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:","kind":"identifier"}],"title":"initWithStatusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:","symbolKind":"method"},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/initWithStatusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithStatusBarMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StatusBarMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2StatusBarMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StatusBarMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"statusBarMode"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topBarBackgroundColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"topBarBackgroundColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBarBackgroundColor:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bottomBarBackgroundColor"},{"text":" ","kind":"text"},{"text":"orientationLockMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2OrientationLockMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode","text":"SBSDKUI2OrientationLockMode"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"orientationLockMode"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StatusBarMode":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2StatusBarMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2statusbarmode","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2StatusBarMode","kind":"identifier"}],"title":"SBSDKUI2StatusBarMode","abstract":[{"type":"text","text":"The visual mode used for the status bar icons."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StatusBarMode","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","title":"SBSDKUI2Color","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2Color","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2color","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentFlowAppearanceConfiguration/initWithStatusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:":{"kind":"symbol","title":"initWithStatusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/initWithStatusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"text":"initWithStatusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration\/initwithstatusbarmode:topbarbackgroundcolor:bottombarbackgroundcolor:orientationlockmode:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStatusBarMode:topBarBackgroundColor:bottomBarBackgroundColor:orientationLockMode:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentFlowAppearanceConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration","title":"SBSDKUI2DocumentFlowAppearanceConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentFlowAppearanceConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Configuration of the general appearance."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentFlowAppearanceConfiguration"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2OrientationLockMode":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2OrientationLockMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Configure the orientation of the interface."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode","title":"SBSDKUI2OrientationLockMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StatusBarMode\/title","value":"SBSDKUI2StatusBarMode"},{"value":[{"text":"SBSDKUI2StatusBarMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StatusBarMode\/fragments"},{"value":[{"text":"SBSDKUI2StatusBarMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StatusBarMode\/navigatorTitle"},{"value":"SBSDKUI2Color","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments","value":[{"text":"SBSDKUI2Color","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2DocumentFlowAppearanceConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKUI2DocumentFlowAppearanceConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentFlowAppearanceConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2OrientationLockMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode\/title"},{"value":[{"text":"SBSDKUI2OrientationLockMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode\/navigatorTitle","value":[{"text":"SBSDKUI2OrientationLockMode","kind":"identifier"}]}]}]}