{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset\/preset4"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preset4","kind":"identifier"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarizationfilterpreset\/preset4"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarizationfilterpreset\/preset4"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset4"}],"title":"SBSDKBinarizationFilterPreset.preset4","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKBinarizationFilterPreset@SBSDKBinarizationFilterPresetPreset4","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preset4","kind":"identifier"}],"role":"symbol"},"abstract":[{"text":"Performs well even if there are shadows. Recommended for most use cases involving text documents.","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBinarizationFilterPreset/preset4":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset4"}],"title":"SBSDKBinarizationFilterPreset.preset4","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarizationfilterpreset\/preset4","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset\/preset4","abstract":[{"text":"Performs well even if there are shadows. Recommended for most use cases involving text documents.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preset4"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBinarizationFilterPreset":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarizationfilterpreset","abstract":[{"type":"text","text":"Preset of parameters for custom binarization filter."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarizationFilterPreset"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBinarizationFilterPreset"}],"kind":"symbol","role":"symbol","title":"SBSDKBinarizationFilterPreset"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKBinarizationFilterPresetPreset4","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset4"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset4"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset~1preset4\/title","value":"SBSDKBinarizationFilterPresetPreset4","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset~1preset4\/fragments","value":[{"text":"SBSDKBinarizationFilterPresetPreset4","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset\/title","op":"replace","value":"SBSDKBinarizationFilterPreset"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset\/fragments","op":"replace","value":[{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}