{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"orientation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKImageRotation","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRotation","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRotation"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Default is NONE"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKRawImageLoadOptions\/orientation","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKRawImageLoadOptions"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkrawimageloadoptions\/orientation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkrawimageloadoptions\/orientation"]}],"metadata":{"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKRawImageLoadOptions(py)orientation","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"orientation"}],"title":"orientation","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"orientation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRotation","text":"SBSDKImageRotation","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"kind":"symbol","abstract":[{"type":"text","text":"Rotation that should be applied to the image to recover correct orientation. Is applied before cropping."}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRotation":{"role":"symbol","kind":"symbol","title":"SBSDKImageRotation","type":"topic","navigatorTitle":[{"text":"SBSDKImageRotation","kind":"identifier"}],"abstract":[{"type":"text","text":"Image rotation."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerotation","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRotation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRotation","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKRawImageLoadOptions":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKRawImageLoadOptions"}],"title":"SBSDKRawImageLoadOptions","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkrawimageloadoptions","navigatorTitle":[{"kind":"identifier","text":"SBSDKRawImageLoadOptions"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKRawImageLoadOptions","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Options for loading images that come from sensor."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKRawImageLoadOptions/orientation":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkrawimageloadoptions\/orientation","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRotation","kind":"typeIdentifier","text":"SBSDKImageRotation"}],"title":"orientation","abstract":[{"type":"text","text":"Rotation that should be applied to the image to recover correct orientation. Is applied before cropping."}],"navigatorTitle":[{"text":"orientation","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKRawImageLoadOptions\/orientation","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"orientation","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"orientation"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKImageRotation","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRotation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRotation"},{"text":" * ","kind":"text"},{"text":"orientation","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKImageRotation","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRotation\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageRotation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRotation\/fragments","op":"replace"},{"value":[{"text":"SBSDKImageRotation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRotation\/navigatorTitle","op":"replace"},{"value":"SBSDKRawImageLoadOptions","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRawImageLoadOptions\/title","op":"replace"},{"value":[{"text":"SBSDKRawImageLoadOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRawImageLoadOptions\/fragments","op":"replace"},{"value":[{"text":"SBSDKRawImageLoadOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRawImageLoadOptions\/navigatorTitle","op":"replace"},{"value":"orientation","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRawImageLoadOptions~1orientation\/title","op":"replace"},{"value":[{"kind":"identifier","text":"orientation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRawImageLoadOptions~1orientation\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}