{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkrawimageloadoptions\/origin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkrawimageloadoptions\/origin"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"origin","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKImageOrigin","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageOrigin","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageOrigin"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The origin is interpreted net of the image orientation. The origin rotates together with the image. The origin value is interpreted and the resulting flip executed AFTER the image matrix has been reoriented to have a neutral orientation."}]},{"type":"paragraph","inlineContent":[{"text":"Default is TOP_LEFT","type":"text"}]}]}],"metadata":{"symbolKind":"property","title":"origin","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKRawImageLoadOptions(py)origin","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageOrigin","text":"SBSDKImageOrigin"}],"navigatorTitle":[{"kind":"identifier","text":"origin"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKRawImageLoadOptions\/origin"},"abstract":[{"type":"text","text":"Location of the image origin in the image coordinate system."},{"type":"text","text":" "},{"type":"text","text":"During loading images are flipped such that after the flip their new origin is in their top-left corner."},{"type":"text","text":" "},{"type":"text","text":"For example, an image coming from the front camera might have its origin set to the top-right, which will flip it along its vertical axis to create a mirror effect."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKRawImageLoadOptions"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKRawImageLoadOptions":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKRawImageLoadOptions"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKRawImageLoadOptions","role":"symbol","title":"SBSDKRawImageLoadOptions","abstract":[{"text":"Options for loading images that come from sensor.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKRawImageLoadOptions"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkrawimageloadoptions"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageOrigin":{"title":"SBSDKImageOrigin","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimageorigin","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageOrigin","abstract":[{"type":"text","text":"Location of the image origin in the image coordinate system."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageOrigin"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageOrigin"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKRawImageLoadOptions/origin":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageOrigin","text":"SBSDKImageOrigin"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkrawimageloadoptions\/origin","title":"origin","navigatorTitle":[{"kind":"identifier","text":"origin"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKRawImageLoadOptions\/origin","role":"symbol","type":"topic","abstract":[{"text":"Location of the image origin in the image coordinate system.","type":"text"},{"text":" ","type":"text"},{"text":"During loading images are flipped such that after the flip their new origin is in their top-left corner.","type":"text"},{"text":" ","type":"text"},{"text":"For example, an image coming from the front camera might have its origin set to the top-right, which will flip it along its vertical axis to create a mirror effect.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"origin"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"origin","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageOrigin","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageOrigin","kind":"typeIdentifier","text":"SBSDKImageOrigin"},{"kind":"text","text":" * "},{"kind":"identifier","text":"origin"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRawImageLoadOptions\/title","value":"SBSDKRawImageLoadOptions"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRawImageLoadOptions\/fragments","value":[{"text":"SBSDKRawImageLoadOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRawImageLoadOptions\/navigatorTitle","value":[{"text":"SBSDKRawImageLoadOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageOrigin\/title","value":"SBSDKImageOrigin"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageOrigin\/fragments","value":[{"kind":"identifier","text":"SBSDKImageOrigin"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageOrigin\/navigatorTitle","value":[{"text":"SBSDKImageOrigin","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRawImageLoadOptions~1origin\/title","value":"origin"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRawImageLoadOptions~1origin\/fragments","value":[{"text":"origin","kind":"identifier"}]}]}]}