{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/expirydatesemantics"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/expirydatesemantics"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/expiryDateSemantics","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport"]]},"metadata":{"symbolKind":"property","title":"expiryDateSemantics","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"expiryDateSemantics"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSemanticsVerificationReport(py)expiryDateSemantics","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiryDateSemantics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompositeFieldValueSemantics","text":"SBSDKCompositeFieldValueSemantics"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiryDateSemantics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompositeFieldValueSemantics","text":"SBSDKCompositeFieldValueSemantics","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompositeFieldValueSemantics"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Status of the expiry date semantics verification. Shows whether the expiry date in the document is in the"},{"type":"text","text":" "},{"type":"text","text":"future."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport/expiryDateSemantics":{"type":"topic","abstract":[{"type":"text","text":"Status of the expiry date semantics verification. Shows whether the expiry date in the document is in the"},{"type":"text","text":" "},{"type":"text","text":"future."}],"url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/expirydatesemantics","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/expiryDateSemantics","title":"expiryDateSemantics","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"expiryDateSemantics","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expiryDateSemantics","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCompositeFieldValueSemantics","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompositeFieldValueSemantics"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport","title":"SBSDKSemanticsVerificationReport","abstract":[{"type":"text","text":"Report of the document value semantics verification."}],"navigatorTitle":[{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCompositeFieldValueSemantics":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompositeFieldValueSemantics","type":"topic","abstract":[{"text":"Report of a logical field value semantics verification. If some logical field, e.g. expiry date is present in","type":"text"},{"text":" ","type":"text"},{"text":"multiple places in the document, it can occur that some entries are semantically correct and some are semantically","type":"text"},{"text":" ","type":"text"},{"text":"incorrect. This report shows the overall status of the logical field value semantics verification and details for","type":"text"},{"text":" ","type":"text"},{"text":"each field that was verified.","type":"text"}],"title":"SBSDKCompositeFieldValueSemantics","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCompositeFieldValueSemantics"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcompositefieldvaluesemantics","navigatorTitle":[{"kind":"identifier","text":"SBSDKCompositeFieldValueSemantics"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"expiryDateSemantics","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"expiryDateSemantics","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompositeFieldValueSemantics","text":"SBSDKCompositeFieldValueSemantics","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompositeFieldValueSemantics","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"expiryDateSemantics","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"expiryDateSemantics","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1expiryDateSemantics\/title"},{"op":"replace","value":[{"text":"expiryDateSemantics","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1expiryDateSemantics\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/title","value":"SBSDKSemanticsVerificationReport","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/fragments","value":[{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/navigatorTitle","value":[{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompositeFieldValueSemantics\/title","value":"SBSDKCompositeFieldValueSemantics","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompositeFieldValueSemantics\/fragments","value":[{"text":"SBSDKCompositeFieldValueSemantics","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompositeFieldValueSemantics\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCompositeFieldValueSemantics"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}