{"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardnoimage\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardNoImage"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardNoImage(im)init","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardNoImage\/init","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardNoImage":{"title":"SBSDKUI2CreditCardNoImage","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardnoimage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardNoImage","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardNoImage","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2CreditCardNoImage","kind":"identifier"}],"abstract":[{"type":"text","text":"No image for the introduction screen."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardNoImage/init":{"type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardnoimage\/init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardNoImage\/init"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2CreditCardNoImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardNoImage\/title"},{"value":[{"text":"SBSDKUI2CreditCardNoImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardNoImage\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2CreditCardNoImage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardNoImage\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}