{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItem(py)count","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"count","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"count"}],"roleHeading":"Instance Property","symbolKind":"property","title":"count"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Number of recognized barcodes of this symbology and value."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"count","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItem\/count"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeitem\/count"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeitem\/count"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItem"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItem/count":{"title":"count","abstract":[{"type":"text","text":"Number of recognized barcodes of this symbology and value."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitem\/count","navigatorTitle":[{"text":"count","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItem\/count","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"count","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItem":{"abstract":[{"text":"Data about the scanned barcode.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeItem","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItem"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItem","title":"SBSDKUI2BarcodeItem","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitem","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"count"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"count","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"count","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItem~1count\/title","value":"count"},{"op":"replace","value":[{"text":"count","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItem~1count\/fragments"},{"value":"SBSDKUI2BarcodeItem","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItem\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItem\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItem"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}