{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formattedResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseDocumentFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BaseDocumentFormat","text":"SBSDKUI2BaseDocumentFormat"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeitem\/formattedresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeitem\/formattedresult"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItem\/formattedResult","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Formatted barcode document (if parsed successfully)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formattedResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BaseDocumentFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BaseDocumentFormat"},{"kind":"text","text":"?"}],"title":"formattedResult","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItem(py)formattedResult","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"formattedResult"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItem"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItem/formattedResult":{"role":"symbol","title":"formattedResult","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formattedResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BaseDocumentFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BaseDocumentFormat"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Formatted barcode document (if parsed successfully)."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItem\/formattedResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"formattedResult"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitem\/formattedresult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseDocumentFormat":{"role":"symbol","title":"SBSDKUI2BaseDocumentFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BaseDocumentFormat"}],"abstract":[{"type":"text","text":"Base Document Format"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseDocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BaseDocumentFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2basedocumentformat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItem":{"role":"symbol","title":"SBSDKUI2BarcodeItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeItem"}],"abstract":[{"type":"text","text":"Data about the scanned barcode."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItem"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"formattedResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"formattedResult"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseDocumentFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BaseDocumentFormat","text":"SBSDKUI2BaseDocumentFormat"},{"kind":"text","text":" * "},{"kind":"identifier","text":"formattedResult"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItem~1formattedResult\/title","value":"formattedResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItem~1formattedResult\/fragments","value":[{"kind":"identifier","text":"formattedResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseDocumentFormat\/title","value":"SBSDKUI2BaseDocumentFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseDocumentFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BaseDocumentFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItem\/title","value":"SBSDKUI2BarcodeItem"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItem\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}