{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/childneedscareuntil"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/childneedscareuntil"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"childNeedsCareUntil"}]}]}],"abstract":[{"type":"text","text":"The date until the child needs care."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/childNeedsCareUntil","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultTypeChildNeedsCareUntil"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerDateResultType@SBSDKMedicalCertificateRecognizerDateResultTypeChildNeedsCareUntil","symbolKind":"case","title":"SBSDKMedicalCertificateRecognizerDateResultType.childNeedsCareUntil","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"childNeedsCareUntil"}],"roleHeading":"Case","role":"symbol"},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType/childNeedsCareUntil":{"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"childNeedsCareUntil"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/childNeedsCareUntil","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeChildNeedsCareUntil","kind":"identifier"}],"abstract":[{"type":"text","text":"The date until the child needs care."}],"title":"SBSDKMedicalCertificateRecognizerDateResultType.childNeedsCareUntil","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/childneedscareuntil"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType":{"type":"topic","kind":"symbol","title":"SBSDKMedicalCertificateRecognizerDateResultType","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype","role":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerDateResultType","kind":"identifier"}],"abstract":[{"type":"text","text":"Type classifiers for dates recognized on medical certificates."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerDateResultType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalCertificateRecognizerDateResultTypeChildNeedsCareUntil"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeChildNeedsCareUntil","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeChildNeedsCareUntil","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1childNeedsCareUntil\/title","value":"SBSDKMedicalCertificateRecognizerDateResultTypeChildNeedsCareUntil","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1childNeedsCareUntil\/fragments","op":"replace","value":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeChildNeedsCareUntil","kind":"identifier"}]},{"value":"SBSDKMedicalCertificateRecognizerDateResultType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType\/fragments"},{"value":[{"text":"SBSDKMedicalCertificateRecognizerDateResultType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}