{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"The date describes the day of diagnosis.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diagnosedOn","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/diagnosedOn","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/diagnosedon"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/diagnosedon"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diagnosedOn","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerDateResultType@SBSDKMedicalCertificateRecognizerDateResultTypeDiagnosedOn","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeDiagnosedOn","kind":"identifier"}],"symbolKind":"case","title":"SBSDKMedicalCertificateRecognizerDateResultType.diagnosedOn"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType":{"abstract":[{"type":"text","text":"Type classifiers for dates recognized on medical certificates."}],"title":"SBSDKMedicalCertificateRecognizerDateResultType","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerDateResultType","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultType"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType/diagnosedOn":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/diagnosedOn","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diagnosedOn","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultTypeDiagnosedOn"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/diagnosedon","abstract":[{"type":"text","text":"The date describes the day of diagnosis."}],"title":"SBSDKMedicalCertificateRecognizerDateResultType.diagnosedOn","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKMedicalCertificateRecognizerDateResultTypeDiagnosedOn"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultTypeDiagnosedOn"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeDiagnosedOn","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType\/title","value":"SBSDKMedicalCertificateRecognizerDateResultType"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateRecognizerDateResultType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultType"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1diagnosedOn\/title","value":"SBSDKMedicalCertificateRecognizerDateResultTypeDiagnosedOn","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1diagnosedOn\/fragments","value":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeDiagnosedOn","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}