{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle\/polygonbackgroundcolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle\/polygonbackgroundcolor"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonBackgroundColor"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle(py)polygonBackgroundColor","title":"polygonBackgroundColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygonBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"polygonBackgroundColor","kind":"identifier"}]},"abstract":[{"text":"The color of the barcode polygon’s background when not selected.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewPolygonStyle/polygonBackgroundColor":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle\/polygonbackgroundcolor","type":"topic","kind":"symbol","title":"polygonBackgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle\/polygonBackgroundColor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"polygonBackgroundColor"}],"abstract":[{"text":"The color of the barcode polygon’s background when not selected.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayController":{"title":"SBSDKBarcodeTrackingOverlayController","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontroller","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"abstract":[{"type":"text","text":"A class that represents an overlay used for visualizing detected barcodes."},{"type":"text","text":" "},{"type":"text","text":"It provides a customizable user interface for displaying barcodes and supports interaction with them."},{"type":"text","text":" "},{"type":"text","text":"The overlay can be used to highlight and select barcodes based on user input."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewPolygonStyle":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewPolygonStyle","title":"SBSDKBarcodeTrackedViewPolygonStyle","abstract":[{"type":"text","text":"A class that represents the style of the polygon rendered around a barcode in "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","type":"reference"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewpolygonstyle","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"polygonBackgroundColor","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"polygonBackgroundColor","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"polygonBackgroundColor"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"polygonBackgroundColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle~1polygonBackgroundColor\/title","op":"replace"},{"value":[{"kind":"identifier","text":"polygonBackgroundColor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle~1polygonBackgroundColor\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/title","value":"SBSDKBarcodeTrackingOverlayController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle\/title","value":"SBSDKBarcodeTrackedViewPolygonStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackedViewPolygonStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewPolygonStyle\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackedViewPolygonStyle"}]}]}]}