{"abstract":[{"text":"Asks the delegate for a `UIBarButtonItem to apply the actual editing.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerApplyButtonItem(_:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageEditingViewControllerApplyButtonItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"editingViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"text":") -> ","kind":"text"},{"text":"UIBarButtonItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"text":"?","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The calling ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"editingViewController"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"UIBarButtonItem"},{"text":" for applying the editing.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerapplybuttonitem(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerapplybuttonitem(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","required":true,"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKImageEditingViewControllerDelegate(im)imageEditingViewControllerApplyButtonItem:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerApplyButtonItem:"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"imageEditingViewControllerApplyButtonItem(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerApplyButtonItem"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController"},{"text":") -> ","kind":"text"},{"text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Method"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewController":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontroller","type":"topic","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show and edit an image."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","title":"SBSDKImageEditingViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageEditingViewController"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerApplyButtonItem(_:)":{"title":"imageEditingViewControllerApplyButtonItem(_:)","abstract":[{"text":"Asks the delegate for a `UIBarButtonItem to apply the actual editing.","type":"text"}],"navigatorTitle":[{"text":"imageEditingViewControllerApplyButtonItem:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerApplyButtonItem(_:)","type":"topic","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageEditingViewControllerApplyButtonItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollerapplybuttonitem(_:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate":{"title":"SBSDKImageEditingViewControllerDelegate","kind":"symbol","abstract":[{"text":"A delegate protocol to inform an object about changes in ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"imageEditingViewControllerApplyButtonItem:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerApplyButtonItem:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"imageEditingViewControllerApplyButtonItem:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"editingViewController"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"editingViewController","content":[{"inlineContent":[{"type":"text","text":"The calling "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"code":"UIBarButtonItem","type":"codeVoice"},{"text":" for applying the editing.","type":"text"}]}]},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"SBSDKImageEditingViewController","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/title"},{"op":"replace","value":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/fragments"},{"op":"replace","value":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/navigatorTitle"},{"op":"replace","value":"imageEditingViewControllerApplyButtonItem:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerApplyButtonItem(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imageEditingViewControllerApplyButtonItem:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerApplyButtonItem(_:)\/fragments"},{"op":"replace","value":"SBSDKImageEditingViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate\/fragments"},{"op":"replace","value":[{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}