{"metadata":{"navigatorTitle":[{"text":"callback","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callback"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKContentValidationCallback","kind":"typeIdentifier","text":"SBSDKContentValidationCallback"},{"kind":"text","text":"?"}],"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"title":"callback","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCustomContentValidator(py)callback","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomContentValidator"]]},"sections":[],"abstract":[{"text":"Custom validation callback.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomContentValidator\/callback"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callback","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidationCallback","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKContentValidationCallback","text":"SBSDKContentValidationCallback","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcustomcontentvalidator\/callback"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcustomcontentvalidator\/callback"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCustomContentValidator/callback":{"title":"callback","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"callback","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomContentValidator\/callback","url":"\/documentation\/scanbotsdk\/sbsdkcustomcontentvalidator\/callback","type":"topic","abstract":[{"type":"text","text":"Custom validation callback."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callback","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKContentValidationCallback","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKContentValidationCallback","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidationCallback":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKContentValidationCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"Content validation callback."}],"title":"SBSDKContentValidationCallback","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidationcallback","navigatorTitle":[{"text":"SBSDKContentValidationCallback","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidationCallback","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCustomContentValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCustomContentValidator","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Custom content validator."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomContentValidator","role":"symbol","navigatorTitle":[{"text":"SBSDKCustomContentValidator","kind":"identifier"}],"kind":"symbol","title":"SBSDKCustomContentValidator","url":"\/documentation\/scanbotsdk\/sbsdkcustomcontentvalidator"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"callback","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"callback","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<SBSDKContentValidationCallback>","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKContentValidationCallback"},{"kind":"text","text":" "},{"kind":"identifier","text":"callback"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"callback","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomContentValidator~1callback\/title"},{"value":[{"text":"callback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomContentValidator~1callback\/fragments"},{"value":"SBSDKContentValidationCallback","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidationCallback\/title"},{"value":[{"text":"SBSDKContentValidationCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidationCallback\/fragments"},{"value":[{"text":"SBSDKContentValidationCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidationCallback\/navigatorTitle"},{"value":"SBSDKCustomContentValidator","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomContentValidator\/title"},{"value":[{"text":"SBSDKCustomContentValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomContentValidator\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKCustomContentValidator"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomContentValidator\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}