{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerScreenConfiguration","text":"SBSDKUI2CheckScannerScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerViewController","text":"SBSDKUI2CheckScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController"},{"kind":"text","text":", "},{"text":"SBSDKUI2CheckScannerUIResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerUIResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerUIResult"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> (), ","kind":"text"},{"text":"performDismiss","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"SBSDKUI2CheckScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerViewController"},{"text":", ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" () -> ()) -> ())? = nil) -> ","kind":"text"},{"text":"SBSDKUI2CheckScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerViewController"}]}]},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"inlineContent":[{"text":"The configuration object for the Check scanner screen.","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"The completion closure that is called when the Check scanner has finished.","type":"text"}]}]},{"name":"performDismiss","content":[{"inlineContent":[{"type":"text","text":"An optional custom dismiss handler. If not provided, the dismissal will be handled automatically."}],"type":"paragraph"}]}]}],"sections":[],"abstract":[{"text":"Creates a new instance of the Check scanner and returns it.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController\/create(with:completion:performDismiss:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerviewcontroller\/create(with:completion:performdismiss:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerviewcontroller\/create(with:completion:performdismiss:)"]}],"metadata":{"title":"create(with:completion:performDismiss:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CheckScannerScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerScreenConfiguration"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"SBSDKUI2CheckScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerViewController"},{"text":", ","kind":"text"},{"text":"SBSDKUI2CheckScannerUIResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerUIResult"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> (), ","kind":"text"},{"text":"performDismiss","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"SBSDKUI2CheckScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerViewController"},{"text":", () -> ()) -> ())?) -> ","kind":"text"},{"text":"SBSDKUI2CheckScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerViewController"}],"symbolKind":"method","navigatorTitle":[{"text":"createWith:completion:performDismiss:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerViewController(cm)createWith:completion:performDismiss:","roleHeading":"Type Method","modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerScreenConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CheckScannerScreenConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CheckScannerScreenConfiguration","kind":"identifier"}],"title":"SBSDKUI2CheckScannerScreenConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreenconfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration of the screen for detecting check data."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerUIResult":{"url":"\/documentation\/scanbotsdk\/sbsdkui2checkscanneruiresult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerUIResult","title":"SBSDKUI2CheckScannerUIResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CheckScannerUIResult"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the check scanner RTU UI result."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CheckScannerUIResult"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerViewController/create(with:completion:performDismiss:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2CheckScannerScreenConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerScreenConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"SBSDKUI2CheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerViewController"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"SBSDKUI2CheckScannerUIResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerUIResult"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> (), "},{"kind":"externalParam","text":"performDismiss"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"SBSDKUI2CheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerViewController"},{"kind":"text","text":", () -> ()) -> ())?) -> "},{"kind":"typeIdentifier","text":"SBSDKUI2CheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController\/create(with:completion:performDismiss:)","navigatorTitle":[{"kind":"identifier","text":"createWith:completion:performDismiss:"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerviewcontroller\/create(with:completion:performdismiss:)","abstract":[{"type":"text","text":"Creates a new instance of the Check scanner and returns it."}],"kind":"symbol","title":"create(with:completion:performDismiss:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CheckScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CheckScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerviewcontroller","role":"symbol","type":"topic","title":"SBSDKUI2CheckScannerViewController","kind":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to scan check data."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"createWith:completion:performDismiss:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWith:completion:performDismiss:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2CheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController"},{"text":" *) ","kind":"text"},{"text":"createWith:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2CheckScannerScreenConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerScreenConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"SBSDKUI2CheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"SBSDKUI2CheckScannerUIResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerUIResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerUIResult"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"performDismiss:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"SBSDKUI2CheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":"","kind":"internalParam"},{"text":")())) ","kind":"text"},{"text":"performDismiss","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The configuration object for the Check scanner screen."}],"type":"paragraph"}],"name":"configuration"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The completion closure that is called when the Check scanner has finished.","type":"text"}]}],"name":"completion"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional custom dismiss handler. If not provided, the dismissal will be handled automatically."}]}],"name":"performDismiss"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenConfiguration\/title","op":"replace","value":"SBSDKUI2CheckScannerScreenConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2CheckScannerScreenConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CheckScannerScreenConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerUIResult\/title","op":"replace","value":"SBSDKUI2CheckScannerUIResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerUIResult\/fragments","op":"replace","value":[{"text":"SBSDKUI2CheckScannerUIResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerUIResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CheckScannerUIResult"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController~1create(with:completion:performDismiss:)\/title","op":"replace","value":"createWith:completion:performDismiss:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController~1create(with:completion:performDismiss:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWith:completion:performDismiss:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController\/title","op":"replace","value":"SBSDKUI2CheckScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKUI2CheckScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CheckScannerViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}