{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"imageName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"capturedImageName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"refreshOnEachFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKSimulatedCameraMockData(im)initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","roleHeading":"Initializer","role":"symbol","symbolKind":"init","title":"init(label:imageName:capturedImageName:refreshOnEachFrame:)","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithLabel:imageName:capturedImageName:refreshOnEachFrame:) ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"imageName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"capturedImageName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"refreshOnEachFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The label to describe the mock data."}]}],"name":"label"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The case-sensitive name of the image resource in the application bundle that provides the simulated frames."}]}],"name":"imageName"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The case-sensitive name of the  image resource in the application bundle that is used when capturing still images. If ‘nil’ the current frame of the "},{"code":"imageName","type":"codeVoice"},{"type":"text","text":" is returned when capturing a still image."}]}],"name":"capturedImageName"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" the image is reloaded\/downloaded after each frame. Otherwise the image is loaded only once and reused per frame."}]}],"name":"refreshOnEachFrame"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageName:capturedImageName:refreshOnEachFrame:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData"]]},"kind":"symbol","abstract":[{"type":"text","text":"Initializes mock data for a simulated camera device from ressource names of the application bundle."}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdksimulatedcameramockdata\/init(label:imagename:capturedimagename:refreshoneachframe:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdksimulatedcameramockdata\/init(label:imagename:capturedimagename:refreshoneachframe:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.1.4","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSimulatedCameraMockData/init(label:imageName:capturedImageName:refreshOnEachFrame:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"imageName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"capturedImageName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"refreshOnEachFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Initializes mock data for a simulated camera device from ressource names of the application bundle."}],"kind":"symbol","title":"init(label:imageName:capturedImageName:refreshOnEachFrame:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksimulatedcameramockdata\/init(label:imagename:capturedimagename:refreshoneachframe:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageName:capturedImageName:refreshOnEachFrame:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSimulatedCameraMockData":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksimulatedcameramockdata","navigatorTitle":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData","kind":"symbol","role":"symbol","abstract":[{"text":"A class to describe the mocking data that is fed to a simulated camera device.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"title":"SBSDKSimulatedCameraMockData"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithLabel:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"label","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"imageName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"imageName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"capturedImageName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"capturedImageName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"refreshOnEachFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"refreshOnEachFrame","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The label to describe the mock data."}]}],"name":"label"},{"content":[{"inlineContent":[{"type":"text","text":"The case-sensitive name of the image resource in the application bundle that provides the simulated frames."}],"type":"paragraph"}],"name":"imageName"},{"content":[{"inlineContent":[{"text":"The case-sensitive name of the  image resource in the application bundle that is used when capturing still images. If ‘nil’ the current frame of the ","type":"text"},{"code":"imageName","type":"codeVoice"},{"text":" is returned when capturing a still image.","type":"text"}],"type":"paragraph"}],"name":"capturedImageName"},{"content":[{"type":"paragraph","inlineContent":[{"text":"If set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" the image is reloaded\/downloaded after each frame. Otherwise the image is loaded only once and reused per frame.","type":"text"}]}],"name":"refreshOnEachFrame"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData~1init(label:imageName:capturedImageName:refreshOnEachFrame:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData~1init(label:imageName:capturedImageName:refreshOnEachFrame:)\/fragments","op":"replace"},{"value":"SBSDKSimulatedCameraMockData","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData\/title","op":"replace"},{"value":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData\/fragments","op":"replace"},{"value":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData\/navigatorTitle","op":"replace"}]}]}