{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult\/initwithstatus:detectionscores:points:horizontallines:verticallines:pointsnormalized:horizontallinesnormalized:verticallinesnormalized:aspectratio:averagebrightness:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult\/initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:"},"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:"}],"symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionResult(im)initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:"}],"role":"symbol"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithStatus:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentDetectionStatus","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus","text":"SBSDKDocumentDetectionStatus"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"status"},{"kind":"text","text":" "},{"text":"detectionScores:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionScores","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionScores","kind":"typeIdentifier","text":"SBSDKDocumentDetectionScores"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detectionScores"},{"text":" ","kind":"text"},{"kind":"identifier","text":"points:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSValue *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"points"},{"text":" ","kind":"text"},{"text":"horizontalLines:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<SBSDKLineSegmentInt *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"horizontalLines"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verticalLines:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKLineSegmentInt *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"verticalLines"},{"text":" ","kind":"text"},{"text":"pointsNormalized:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSValue *>"},{"text":" *) ","kind":"text"},{"text":"pointsNormalized","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontalLinesNormalized:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKLineSegmentFloat *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"horizontalLinesNormalized","kind":"internalParam"},{"kind":"text","text":" "},{"text":"verticalLinesNormalized:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<SBSDKLineSegmentFloat *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"verticalLinesNormalized","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"aspectRatio:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"aspectRatio","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"averageBrightness:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"averageBrightness"},{"text":";","kind":"text"}]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionResult":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"abstract":[{"type":"text","text":"Result of the document contour detection."}],"title":"SBSDKDocumentDetectionResult","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult","role":"symbol","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionStatus":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus","kind":"symbol","title":"SBSDKDocumentDetectionStatus","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Status of the document detection."}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionResult/initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:":{"navigatorTitle":[{"text":"initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult\/initwithstatus:detectionscores:points:horizontallines:verticallines:pointsnormalized:horizontallinesnormalized:verticallinesnormalized:aspectratio:averagebrightness:","title":"initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult\/initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionScores":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionScores","abstract":[{"text":"The total and partial scores for the detected document contour.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionScores"}],"role":"symbol","title":"SBSDKDocumentDetectionScores","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionScores","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionscores"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKDocumentDetectionResult","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus\/title","value":"SBSDKDocumentDetectionStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionScores\/title","value":"SBSDKDocumentDetectionScores","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionScores\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionScores"}]},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionScores"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionScores\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}