{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/finderaspectratio"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/finderaspectratio"]}],"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKAspectRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAspectRatio"}],"roleHeading":"Instance Property","symbolKind":"property","platforms":[],"title":"finderAspectRatio","navigatorTitle":[{"text":"finderAspectRatio","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodesBatchScannerUIConfiguration(py)finderAspectRatio"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/finderAspectRatio","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Aspect ratio of finder frame (width \\ height), which is used to build actual finder frame."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAspectRatio","text":"SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAspectRatio","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/finderAspectRatio":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/finderAspectRatio","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/finderaspectratio","kind":"symbol","role":"symbol","title":"finderAspectRatio","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAspectRatio","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"finderAspectRatio","kind":"identifier"}],"deprecated":true,"abstract":[{"type":"text","text":"Aspect ratio of finder frame (width \\ height), which is used to build actual finder frame."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration":{"navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration","role":"symbol","title":"SBSDKUIBarcodesBatchScannerUIConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"}],"abstract":[{"text":"The configuration for user interface of the RTU-UI batch barcode scanner.","type":"text"}],"kind":"symbol","type":"topic","deprecated":true},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.0","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAspectRatio":{"type":"topic","abstract":[{"type":"text","text":"Aspect ratio is the ratio of the width to the height of an image or screen."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAspectRatio","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKAspectRatio","kind":"identifier"}],"title":"SBSDKAspectRatio","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaspectratio","navigatorTitle":[{"text":"SBSDKAspectRatio","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"finderAspectRatio"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"finderAspectRatio","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAspectRatio","text":"SBSDKAspectRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAspectRatio"},{"text":" * ","kind":"text"},{"text":"finderAspectRatio","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1finderAspectRatio\/title","op":"replace","value":"finderAspectRatio"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1finderAspectRatio\/fragments","op":"replace","value":[{"text":"finderAspectRatio","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration\/title","op":"replace","value":"SBSDKUIBarcodesBatchScannerUIConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAspectRatio\/title","op":"replace","value":"SBSDKAspectRatio"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAspectRatio\/fragments","value":[{"text":"SBSDKAspectRatio","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAspectRatio\/navigatorTitle","value":[{"text":"SBSDKAspectRatio","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}