{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeTrackingOverlay:textStyleFor:proposedStyle:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle","text":"SBSDKBarcodeTrackedViewTextStyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackedViewTextStyle"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"barcodeTrackingOverlay:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController","text":"SBSDKBarcodeTrackingOverlayController","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackingOverlayController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textStyleFor:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeItem","text":"SBSDKBarcodeItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"barcode"},{"kind":"text","text":" "},{"text":"proposedStyle:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackedViewTextStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle","kind":"typeIdentifier","text":"SBSDKBarcodeTrackedViewTextStyle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"proposedStyle"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/barcodetrackingoverlay:textstylefor:proposedstyle:"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"barcodeTrackingOverlay:textStyleFor:proposedStyle:"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Method","symbolKind":"method","title":"barcodeTrackingOverlay:textStyleFor:proposedStyle:","role":"symbol","externalID":"c:@CM@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController(im)barcodeTrackingOverlay:textStyleFor:proposedStyle:","fragments":[{"kind":"text","text":"- "},{"text":"barcodeTrackingOverlay:textStyleFor:proposedStyle:","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/barcodeTrackingOverlay:textStyleFor:proposedStyle:":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/barcodetrackingoverlay:textstylefor:proposedstyle:","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"barcodeTrackingOverlay:textStyleFor:proposedStyle:","kind":"identifier"}],"role":"symbol","title":"barcodeTrackingOverlay:textStyleFor:proposedStyle:","fragments":[{"text":"- ","kind":"text"},{"text":"barcodeTrackingOverlay:textStyleFor:proposedStyle:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeTrackingOverlay:textStyleFor:proposedStyle:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController":{"deprecated":true,"type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller","title":"SBSDKUIBarcodesBatchScannerViewController","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan barcodes batches."}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackingOverlayController":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlaycontroller","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"abstract":[{"type":"text","text":"A class that represents an overlay used for visualizing scanned barcodes."},{"text":" ","type":"text"},{"text":"It provides a customizable user interface for displaying barcodes and supports interaction with them.","type":"text"},{"text":" ","type":"text"},{"text":"The overlay can be used to highlight and select barcodes based on user input.","type":"text"}],"type":"topic","title":"SBSDKBarcodeTrackingOverlayController"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackedViewTextStyle":{"navigatorTitle":[{"text":"SBSDKBarcodeTrackedViewTextStyle","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackedViewTextStyle","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackedviewtextstyle","role":"symbol","title":"SBSDKBarcodeTrackedViewTextStyle","kind":"symbol","abstract":[{"type":"text","text":"A class that represents the style and kind of the text rendered below a barcode in "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController","isActive":true},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeTrackedViewTextStyle","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeItem":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeItem"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeItem"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"A single barcode found in the input image. Barcodes with the same content but different locations in the image are","type":"text"},{"type":"text","text":" "},{"type":"text","text":"considered separate barcodes."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeitem","title":"SBSDKBarcodeItem","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeItem"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController\/title","op":"replace","value":"SBSDKUIBarcodesBatchScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/title","value":"SBSDKBarcodeTrackingOverlayController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/fragments","value":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}],"op":"replace"},{"op":"replace","value":"SBSDKBarcodeTrackedViewTextStyle","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackedViewTextStyle\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackedViewTextStyle\/fragments","value":[{"text":"SBSDKBarcodeTrackedViewTextStyle","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKBarcodeTrackedViewTextStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackedViewTextStyle\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeItem\/title","value":"SBSDKBarcodeItem"},{"value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeItem\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeItem\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}