{"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"API Collection","role":"collectionGroup","title":"AVCaptureVideoDataOutputSampleBufferDelegate Implementations"},"kind":"article","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/avcapturevideodataoutputsamplebufferdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/avcapturevideodataoutputsamplebufferdelegate-implementations"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/captureOutput(_:didOutput:from:)"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession","title":"SBSDKCameraSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSession"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSession"}],"kind":"symbol","abstract":[{"type":"text","text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the"},{"type":"text","text":" "},{"type":"text","text":"camera device and the preview layer. Provides functionality to capture still images."}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/captureOutput(_:didOutput:from:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/captureoutput(_:didoutput:from:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"captureOutput:didOutputSampleBuffer:fromConnection:"}],"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureOutput"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVCaptureOutput","kind":"typeIdentifier","text":"AVCaptureOutput"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didOutput"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier","text":"CMSampleBuffer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCaptureConnection","kind":"typeIdentifier","text":"AVCaptureConnection"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/captureOutput(_:didOutput:from:)","type":"topic","title":"captureOutput(_:didOutput:from:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/captureOutput(_:didOutput:from:)"],"title":"Instance Methods"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/title","value":"SBSDKCameraSession"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/fragments","value":[{"text":"SBSDKCameraSession","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/navigatorTitle","value":[{"text":"SBSDKCameraSession","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1captureOutput(_:didOutput:from:)\/title","value":"captureOutput:didOutputSampleBuffer:fromConnection:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1captureOutput(_:didOutput:from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureOutput:didOutputSampleBuffer:fromConnection:"}]}]}]}