{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerTextConfiguration"]]},"kind":"symbol","metadata":{"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextPatternScannerTextConfiguration(im)init","modules":[{"name":"ScanbotSDK"}],"title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerTextConfiguration\/init"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannertextconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerTextConfiguration/init":{"url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannertextconfiguration\/init","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerTextConfiguration\/init","abstract":[],"kind":"symbol","role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerTextConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannertextconfiguration","deprecated":true,"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Configuration for the textual contents of the RTU-UI text pattern scanner.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUITextPatternScannerTextConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUITextPatternScannerTextConfiguration"}],"title":"SBSDKUITextPatternScannerTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerTextConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerTextConfiguration\/title","value":"SBSDKUITextPatternScannerTextConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUITextPatternScannerTextConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerTextConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUITextPatternScannerTextConfiguration"}]}]}]}