{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController"]]},"metadata":{"roleHeading":"Instance Property","title":"shouldShowWordBoxes","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldShowWordBoxes","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"shouldShowWordBoxes"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerViewController(py)shouldShowWordBoxes"},"abstract":[{"type":"text","text":"Whether word boxes should be displayed or not."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController\/shouldShowWordBoxes"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldShowWordBoxes","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"inlineContent":[{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"True"},{"text":".","type":"text"}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontroller\/shouldshowwordboxes"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontroller\/shouldshowwordboxes"]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerViewController/shouldShowWordBoxes":{"title":"shouldShowWordBoxes","navigatorTitle":[{"text":"shouldShowWordBoxes","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController\/shouldShowWordBoxes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldShowWordBoxes","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontroller\/shouldshowwordboxes","type":"topic","kind":"symbol","abstract":[{"text":"Whether word boxes should be displayed or not.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerViewController":{"type":"topic","title":"SBSDKGenericTextLineRecognizerViewController","navigatorTitle":[{"text":"SBSDKGenericTextLineRecognizerViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontroller","kind":"symbol","abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to show a camera screen with the text line recognizer.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"shouldShowWordBoxes","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"shouldShowWordBoxes","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"text":"shouldShowWordBoxes","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController~1shouldShowWordBoxes\/title","value":"shouldShowWordBoxes","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController~1shouldShowWordBoxes\/fragments","value":[{"kind":"identifier","text":"shouldShowWordBoxes"}]},{"value":"SBSDKGenericTextLineRecognizerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController\/title","op":"replace"},{"value":[{"text":"SBSDKGenericTextLineRecognizerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController\/fragments","op":"replace"}]}]}