{"abstract":[{"type":"text","text":"No license active. The set license does not cover the current SDK version."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureVersion","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseStatus\/failureVersion"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseStatus"]]},"metadata":{"role":"symbol","title":"SBSDKLicenseStatus.failureVersion","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKLicenseStatus@SBSDKLicenseStatusFailureVersion","symbolKind":"case","roleHeading":"Case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"SBSDKLicenseStatusFailureVersion","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureVersion","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdklicensestatus\/failureversion"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdklicensestatus\/failureversion"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKLicenseStatus":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseStatus"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdklicensestatus","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseStatus","title":"SBSDKLicenseStatus","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Status of the license plate scanner."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatus"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKLicenseStatus/failureVersion":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdklicensestatus\/failureversion","kind":"symbol","abstract":[{"text":"No license active. The set license does not cover the current SDK version.","type":"text"}],"title":"SBSDKLicenseStatus.failureVersion","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureVersion","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKLicenseStatusFailureVersion","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseStatus\/failureVersion"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKLicenseStatusFailureVersion","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureVersion"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureVersion"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKLicenseStatus","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus\/title"},{"value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus\/fragments"},{"value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus\/navigatorTitle"},{"value":"SBSDKLicenseStatusFailureVersion","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus~1failureVersion\/title"},{"value":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureVersion"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus~1failureVersion\/fragments"}]}]}