{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio\/initWithWidth:height:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio"]]},"metadata":{"title":"initWithWidth:height:","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"initWithWidth:height:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithWidth:height:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio(im)initWithWidth:height:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithWidth:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"width","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"height:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"height"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkaspectratio\/initwithwidth:height:"]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAspectRatio/initWithWidth:height:":{"url":"\/documentation\/scanbotsdk\/sbsdkaspectratio\/initwithwidth:height:","title":"initWithWidth:height:","navigatorTitle":[{"kind":"identifier","text":"initWithWidth:height:"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithWidth:height:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio\/initWithWidth:height:","abstract":[],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAspectRatio":{"navigatorTitle":[{"text":"SBSDKAspectRatio","kind":"identifier"}],"title":"SBSDKAspectRatio","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkaspectratio","abstract":[{"type":"text","text":"Aspect ratio is the ratio of the width to the height of an image or screen."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAspectRatio","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKAspectRatio","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatio\/title"},{"value":[{"kind":"identifier","text":"SBSDKAspectRatio"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatio\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKAspectRatio"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatio\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}