{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"down","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDisplacement"]]},"abstract":[{"type":"text","text":"The document is partially visible. Move the camera down to capture the full document."}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDisplacement\/down","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdisplacement\/down"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdisplacement\/down"]}],"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"down","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentDisplacement@SBSDKDocumentDisplacementDown","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"case","title":"SBSDKDocumentDisplacement.down","navigatorTitle":[{"text":"SBSDKDocumentDisplacementDown","kind":"identifier"}],"roleHeading":"Case"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDisplacement/down":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDisplacement\/down","abstract":[{"type":"text","text":"The document is partially visible. Move the camera down to capture the full document."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDisplacementDown"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdisplacement\/down","role":"symbol","title":"SBSDKDocumentDisplacement.down","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"down"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDisplacement":{"kind":"symbol","title":"SBSDKDocumentDisplacement","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdisplacement","abstract":[{"type":"text","text":"The direction towards the center of the document if the document is partially visible."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDisplacement"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDisplacement"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDisplacement","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKDocumentDisplacementDown"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDisplacementDown"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKDocumentDisplacementDown","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDisplacement~1down\/title","op":"replace","value":"SBSDKDocumentDisplacementDown"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDisplacement~1down\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDisplacementDown"}]},{"value":"SBSDKDocumentDisplacement","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDisplacement\/title"},{"value":[{"text":"SBSDKDocumentDisplacement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDisplacement\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDisplacement"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDisplacement\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}