{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"imageHeight","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageHeight"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"imageHeight"}],"symbolKind":"property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageMetadata(py)imageHeight","role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageHeight"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/imageheight"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/imageheight"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/imageHeight"},"sections":[],"abstract":[{"type":"text","text":"The height of the image in pixels."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadataProcessor":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageMetadataProcessor"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadataProcessor","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}],"title":"SBSDKImageMetadataProcessor","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadataprocessor","kind":"symbol","abstract":[{"text":"Helper class to extract or inject image metadata, e.g. EXIF, TIFF, JFIF from  image data.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.2.1"}],"type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata":{"role":"symbol","title":"SBSDKImageMetadata","abstract":[{"text":"Encapsulates image metadata, e.g. EXIF, TIFF, JFIF in a convenient way.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Use "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadataProcessor"},{"type":"text","text":" to extract metadata from and inject changed metadata into image data."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKImageMetadata","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKImageMetadata","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/imageHeight":{"title":"imageHeight","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageHeight"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"imageHeight"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The height of the image in pixels."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/imageHeight","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/imageheight"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"imageHeight"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"imageHeight","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageHeight"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadataProcessor\/title","op":"replace","value":"SBSDKImageMetadataProcessor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadataProcessor\/fragments","value":[{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}]},{"value":"SBSDKImageMetadata","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageMetadata"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1imageHeight\/title","value":"imageHeight","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1imageHeight\/fragments","op":"replace","value":[{"text":"imageHeight","kind":"identifier"}]}]}]}