{"abstract":[{"type":"text","text":"The number of iterations used to derive the encryption key from the salt data and the password."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkaesencrypter\/iterations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkaesencrypter\/iterations"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESEncrypter\/iterations","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"iterations","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"A fixed value that may be needed for manual decryption key derivation on the backend side."},{"text":" ","type":"text"},{"type":"text","text":"Readonly."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAESEncrypter(py)iterations","navigatorTitle":[{"kind":"identifier","text":"iterations"}],"title":"iterations","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iterations"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESEncrypter"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAESEncrypter":{"title":"SBSDKAESEncrypter","type":"topic","navigatorTitle":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"abstract":[{"type":"text","text":"ScanbotSDK’s default data encrypter. Provides AES128 and AES 256 encryption to your data."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaesencrypter","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESEncrypter","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKAESEncrypter","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAESEncrypter/iterations":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESEncrypter\/iterations","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"iterations"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaesencrypter\/iterations","abstract":[{"text":"The number of iterations used to derive the encryption key from the salt data and the password.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"iterations"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"kind":"symbol","title":"iterations"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"iterations","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"iterations"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"iterations"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESEncrypter\/title","value":"SBSDKAESEncrypter","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESEncrypter\/fragments","value":[{"text":"SBSDKAESEncrypter","kind":"identifier"}]},{"value":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESEncrypter\/navigatorTitle"},{"value":"iterations","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESEncrypter~1iterations\/title","op":"replace"},{"op":"replace","value":[{"text":"iterations","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESEncrypter~1iterations\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}