{"sections":[],"abstract":[{"type":"text","text":"Designated initializer."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(initWithWidth:andHeight:) ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"width","content":[{"inlineContent":[{"text":"The width of the document page.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The height of the document page."}]}],"name":"height"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatio"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkaspectratio\/init(width:height:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkaspectratio\/init(width:height:)"]}],"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithWidth:andHeight:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"init","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatio(im)initWithWidth:andHeight:","roleHeading":"Initializer","title":"init(width:height:)"},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatio\/init(width:height:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAspectRatio":{"navigatorTitle":[{"text":"SBSDKAspectRatio","kind":"identifier"}],"abstract":[{"text":"A class that describes an aspect ratio for a document page.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKAspectRatio","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatio","title":"SBSDKAspectRatio","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaspectratio"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAspectRatio/init(width:height:)":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaspectratio\/init(width:height:)","abstract":[{"type":"text","text":"Designated initializer."}],"navigatorTitle":[{"kind":"identifier","text":"initWithWidth:andHeight:"}],"title":"init(width:height:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatio\/init(width:height:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithWidth:andHeight:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithWidth:andHeight:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithWidth:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"text":") ","kind":"text"},{"text":"width","kind":"internalParam"},{"kind":"text","text":" "},{"text":"andHeight:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"text":") ","kind":"text"},{"text":"height","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"width","content":[{"inlineContent":[{"text":"The width of the document page.","type":"text"}],"type":"paragraph"}]},{"name":"height","content":[{"type":"paragraph","inlineContent":[{"text":"The height of the document page.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio\/title","value":"SBSDKAspectRatio"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio\/fragments","value":[{"kind":"identifier","text":"SBSDKAspectRatio"}]},{"value":[{"text":"SBSDKAspectRatio","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio~1init(width:height:)\/title","value":"initWithWidth:andHeight:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithWidth:andHeight:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio~1init(width:height:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}