{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithBorderWidthFraction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"borderWidthFraction","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"blackOutliersFraction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"blackOutliersFraction","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"whiteOutliersFraction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"whiteOutliersFraction","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGrayscaleFilter"]]},"sections":[],"metadata":{"title":"initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:","roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGrayscaleFilter(im)initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGrayscaleFilter\/initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgrayscalefilter\/initwithborderwidthfraction:blackoutliersfraction:whiteoutliersfraction:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGrayscaleFilter":{"url":"\/documentation\/scanbotsdk\/sbsdkgrayscalefilter","navigatorTitle":[{"text":"SBSDKGrayscaleFilter","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGrayscaleFilter","kind":"identifier"}],"kind":"symbol","title":"SBSDKGrayscaleFilter","abstract":[{"type":"text","text":"Converts color images to grayscale and applies autocontrast."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGrayscaleFilter","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGrayscaleFilter/initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:":{"title":"initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgrayscalefilter\/initwithborderwidthfraction:blackoutliersfraction:whiteoutliersfraction:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGrayscaleFilter\/initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGrayscaleFilter\/title","value":"SBSDKGrayscaleFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGrayscaleFilter\/fragments","value":[{"text":"SBSDKGrayscaleFilter","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKGrayscaleFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGrayscaleFilter\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}