{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Applies one or more editing operations on the page at once and waits for the completion.","type":"text"}],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedPage(im)applyWithRotation:polygon:filters:error:","symbolKind":"method","role":"symbol","title":"apply(rotation:polygon:filters:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apply","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rotation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRotation","text":"SBSDKImageRotation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"filters","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter","kind":"typeIdentifier"},{"text":"]?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"applyWithRotation:polygon:filters:error:","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apply","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rotation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRotation","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRotation","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRotation"},{"text":" = .none, ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon"},{"text":"? = nil, ","kind":"text"},{"text":"filters","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter"},{"text":"]? = nil) ","kind":"text"},{"text":"throws","kind":"keyword"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The rotation of the receiver."}]}],"name":"rotation"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The cropping polygon of the receiver. Pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if you do not wish to crop the receiver.","type":"text"}]}],"name":"polygon"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The filters to apply on the receiver. Pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if you do not wish to filter the receiver."}]}],"name":"filters"}],"kind":"parameters"}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPage\/apply(rotation:polygon:filters:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpage\/apply(rotation:polygon:filters:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpage\/apply(rotation:polygon:filters:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPage"]]},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRotation":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerotation","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRotation"}],"kind":"symbol","abstract":[{"text":"Image rotation.","type":"text"}],"title":"SBSDKImageRotation","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRotation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRotation"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedPage":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpage","kind":"symbol","abstract":[{"type":"text","text":"A scanned page ("},{"code":"SBSDKScannedPage","type":"codeVoice"},{"type":"text","text":") is a representation of a scanned documents page in digital form."},{"type":"text","text":" "},{"type":"text","text":"Each page consists of an original image of the scan, various editing properties like cropping polygon, rotation and filters, some metadata properties like the document detection status and the document quality analyzer result and a number of processed images in different stages."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPage","title":"SBSDKScannedPage","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScannedPage"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPage"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKParametricFilter","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter","abstract":[{"text":"Base class for all parametric filters.","type":"text"}],"title":"SBSDKParametricFilter"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygon":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon","role":"symbol","navigatorTitle":[{"text":"SBSDKPolygon","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygon","kind":"identifier"}],"title":"SBSDKPolygon","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon","abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedPage/apply(rotation:polygon:filters:)":{"title":"apply(rotation:polygon:filters:)","type":"topic","abstract":[{"type":"text","text":"Applies one or more editing operations on the page at once and waits for the completion."}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpage\/apply(rotation:polygon:filters:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPage\/apply(rotation:polygon:filters:)","navigatorTitle":[{"text":"applyWithRotation:polygon:filters:error:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apply","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rotation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRotation","text":"SBSDKImageRotation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"filters","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter","kind":"typeIdentifier"},{"text":"]?) ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"applyWithRotation:polygon:filters:error:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applyWithRotation:polygon:filters:error:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"applyWithRotation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKImageRotation","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRotation","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRotation"},{"text":" *) ","kind":"text"},{"text":"rotation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"polygon:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKPolygon","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon"},{"text":" *) ","kind":"text"},{"text":"polygon","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"filters:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKParametricFilter *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"filters","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"rotation","content":[{"inlineContent":[{"text":"The rotation of the receiver.","type":"text"}],"type":"paragraph"}]},{"name":"polygon","content":[{"type":"paragraph","inlineContent":[{"text":"The cropping polygon of the receiver. Pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if you do not wish to crop the receiver.","type":"text"}]}]},{"name":"filters","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The filters to apply on the receiver. Pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if you do not wish to filter the receiver."}]}]},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"YES"},{"type":"text","text":" if the method succeeded, otherwise "},{"type":"codeVoice","code":"NO"},{"type":"text","text":"."}]}]},"path":"\/primaryContentSections\/2","op":"add"},{"value":"SBSDKImageRotation","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRotation\/title","op":"replace"},{"value":[{"text":"SBSDKImageRotation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRotation\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageRotation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRotation\/navigatorTitle","op":"replace"},{"value":"SBSDKScannedPage","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPage\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKScannedPage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPage\/fragments","op":"replace"},{"value":[{"text":"SBSDKScannedPage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPage\/navigatorTitle","op":"replace"},{"value":"SBSDKParametricFilter","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/fragments","op":"replace"},{"value":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/navigatorTitle","op":"replace"},{"value":"SBSDKPolygon","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPolygon"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/fragments","op":"replace"},{"value":[{"text":"SBSDKPolygon","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/navigatorTitle","op":"replace"},{"value":"applyWithRotation:polygon:filters:error:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPage~1apply(rotation:polygon:filters:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applyWithRotation:polygon:filters:error:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPage~1apply(rotation:polygon:filters:)\/fragments","op":"replace"}]}]}