{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ThreeLineMRZFinderLayoutPreset\/adjustedFinderAspectRatio","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Aspect ratio of the finder adjusted to the 3-line MRZ text. Not editable. To override, please use ‘aspectRatio’","type":"text"},{"text":" ","type":"text"},{"text":"parameter in ‘viewFinder’ field in MRZ screen configuration.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustedFinderAspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Default is 4.3125","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ThreeLineMRZFinderLayoutPreset"]]},"metadata":{"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adjustedFinderAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"roleHeading":"Instance Property","title":"adjustedFinderAspectRatio","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ThreeLineMRZFinderLayoutPreset(py)adjustedFinderAspectRatio","navigatorTitle":[{"text":"adjustedFinderAspectRatio","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2threelinemrzfinderlayoutpreset\/adjustedfinderaspectratio"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2threelinemrzfinderlayoutpreset\/adjustedfinderaspectratio"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ThreeLineMRZFinderLayoutPreset":{"kind":"symbol","abstract":[{"text":"A ready-to-use preset 3-line text to be displayed.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2threelinemrzfinderlayoutpreset","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ThreeLineMRZFinderLayoutPreset","title":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ThreeLineMRZFinderLayoutPreset/adjustedFinderAspectRatio":{"abstract":[{"type":"text","text":"Aspect ratio of the finder adjusted to the 3-line MRZ text. Not editable. To override, please use ‘aspectRatio’"},{"type":"text","text":" "},{"type":"text","text":"parameter in ‘viewFinder’ field in MRZ screen configuration."}],"title":"adjustedFinderAspectRatio","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ThreeLineMRZFinderLayoutPreset\/adjustedFinderAspectRatio","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustedFinderAspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2threelinemrzfinderlayoutpreset\/adjustedfinderaspectratio","navigatorTitle":[{"kind":"identifier","text":"adjustedFinderAspectRatio"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"adjustedFinderAspectRatio","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"adjustedFinderAspectRatio","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"adjustedFinderAspectRatio","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset\/title"},{"op":"replace","value":[{"text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset\/fragments"},{"value":[{"text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset\/navigatorTitle"},{"value":"adjustedFinderAspectRatio","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset~1adjustedFinderAspectRatio\/title"},{"value":[{"text":"adjustedFinderAspectRatio","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset~1adjustedFinderAspectRatio\/fragments"}]}]}