{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration\/noDocumentDetectedAlertDialog","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration"]]},"abstract":[{"type":"text","text":"Configuration of the alert dialog that will be presented when no document is detected."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noDocumentDetectedAlertDialog","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"noDocumentDetectedAlertDialog"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","text":"SBSDKUI2ScanbotAlertDialog"}],"navigatorTitle":[{"kind":"identifier","text":"noDocumentDetectedAlertDialog"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"noDocumentDetectedAlertDialog","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorScreenConfiguration(py)noDocumentDetectedAlertDialog"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration\/nodocumentdetectedalertdialog"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration\/nodocumentdetectedalertdialog"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentDataExtractorScreenConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the screen for extracting data from ID documents."}],"navigatorTitle":[{"text":"SBSDKUI2DocumentDataExtractorScreenConfiguration","kind":"identifier"}],"title":"SBSDKUI2DocumentDataExtractorScreenConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ScanbotAlertDialog":{"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2scanbotalertdialog","title":"SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","abstract":[{"text":"Configuration of the standard alert dialog.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenConfiguration/noDocumentDetectedAlertDialog":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration\/nodocumentdetectedalertdialog","abstract":[{"text":"Configuration of the alert dialog that will be presented when no document is detected.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noDocumentDetectedAlertDialog","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","title":"noDocumentDetectedAlertDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration\/noDocumentDetectedAlertDialog","navigatorTitle":[{"text":"noDocumentDetectedAlertDialog","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"noDocumentDetectedAlertDialog"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"noDocumentDetectedAlertDialog","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog"},{"text":" * ","kind":"text"},{"text":"noDocumentDetectedAlertDialog","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"SBSDKUI2DocumentDataExtractorScreenConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration\/title"},{"value":[{"text":"SBSDKUI2DocumentDataExtractorScreenConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration\/navigatorTitle"},{"value":"SBSDKUI2ScanbotAlertDialog","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/fragments"},{"value":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/navigatorTitle"},{"value":"noDocumentDetectedAlertDialog","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration~1noDocumentDetectedAlertDialog\/title"},{"value":[{"kind":"identifier","text":"noDocumentDetectedAlertDialog"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration~1noDocumentDetectedAlertDialog\/fragments"}]}]}