{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeMetadataIsGS1MessageKey"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeMetadataIsGS1MessageKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Property","title":"SBSDKBarcodeMetadataIsGS1MessageKey","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult(cpy)SBSDKBarcodeMetadataIsGS1MessageKey"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/sbsdkbarcodemetadataisgs1messagekey"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/sbsdkbarcodemetadataisgs1messagekey"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/SBSDKBarcodeMetadataIsGS1MessageKey","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeMetadataIsGS1MessageKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult"]]},"abstract":[{"type":"text","text":"The barcode metadata key for the GS1 messages."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult/SBSDKBarcodeMetadataIsGS1MessageKey":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeMetadataIsGS1MessageKey","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"type":"text","text":"The barcode metadata key for the GS1 messages."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult\/sbsdkbarcodemetadataisgs1messagekey","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult\/SBSDKBarcodeMetadataIsGS1MessageKey","type":"topic","title":"SBSDKBarcodeMetadataIsGS1MessageKey","navigatorTitle":[{"text":"SBSDKBarcodeMetadataIsGS1MessageKey","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"abstract":[{"type":"text","text":"This class encapsulates the result of a barcode detection."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}],"kind":"symbol","title":"SBSDKBarcodeScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","value":"SBSDKBarcodeMetadataIsGS1MessageKey","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKBarcodeMetadataIsGS1MessageKey","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SBSDKBarcodeMetadataIsGS1MessageKey"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1SBSDKBarcodeMetadataIsGS1MessageKey\/title","op":"replace","value":"SBSDKBarcodeMetadataIsGS1MessageKey"},{"op":"replace","value":[{"text":"SBSDKBarcodeMetadataIsGS1MessageKey","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult~1SBSDKBarcodeMetadataIsGS1MessageKey\/fragments"},{"op":"replace","value":"SBSDKBarcodeScannerResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}