{"sections":[],"abstract":[{"text":"Extracts images from a PDF, converts them to JPEGs and writes them to a specified URL. Runs in the same thread that it is called from.","type":"text"},{"text":" ","type":"text"},{"text":"No encryption is used here. The compression is set to 1.0. Media box scale value is 2.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfimageextractor\/extract(from:outputdirectory:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfimageextractor\/extract(from:outputdirectory:)"]}],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"extract"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputDirectory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"]"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","title":"extract(from:outputDirectory:)","navigatorTitle":[{"kind":"identifier","text":"extractFromPDF:outputDirectory:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFImageExtractor(im)extractFromPDF:outputDirectory:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(extractFromPDF:outputDirectory:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"extract"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pdfURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputDirectory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"]"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL of the PDF file."}]}],"name":"pdfURL"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The output folder where images will be stored. If the folder does not exist, it will be created."}]}],"name":"outputDirectory"}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"An array of URLs with extracted images as JPEG files. The array will be empty if something is wrong.","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFImageExtractor\/extract(from:outputDirectory:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFImageExtractor"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFImageExtractor/extract(from:outputDirectory:)":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfimageextractor\/extract(from:outputdirectory:)","abstract":[{"type":"text","text":"Extracts images from a PDF, converts them to JPEGs and writes them to a specified URL. Runs in the same thread that it is called from."},{"type":"text","text":" "},{"type":"text","text":"No encryption is used here. The compression is set to 1.0. Media box scale value is 2."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extract","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"outputDirectory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFImageExtractor\/extract(from:outputDirectory:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"extractFromPDF:outputDirectory:","kind":"identifier"}],"title":"extract(from:outputDirectory:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFImageExtractor":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfimageextractor","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFImageExtractor","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFImageExtractor","kind":"symbol","navigatorTitle":[{"text":"SBSDKPDFImageExtractor","kind":"identifier"}],"type":"topic","title":"SBSDKPDFImageExtractor","abstract":[{"text":"Class used to extract images from a PDF file and returns them in various ways.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"extractFromPDF:outputDirectory:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"extractFromPDF:outputDirectory:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSArray<NSURL *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"extractFromPDF:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"pdfURL","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"outputDirectory:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"outputDirectory","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The URL of the PDF file.","type":"text"}]}],"name":"pdfURL"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The output folder where images will be stored. If the folder does not exist, it will be created.","type":"text"}]}],"name":"outputDirectory"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"text":"An array of URLs with extracted images as JPEG files. The array will be empty if something is wrong.","type":"text"}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"extractFromPDF:outputDirectory:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFImageExtractor~1extract(from:outputDirectory:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"extractFromPDF:outputDirectory:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFImageExtractor~1extract(from:outputDirectory:)\/fragments"},{"op":"replace","value":"SBSDKPDFImageExtractor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFImageExtractor\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFImageExtractor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFImageExtractor\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFImageExtractor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFImageExtractor\/navigatorTitle"}]}]}