{"sections":[],"abstract":[{"type":"text","text":"AlphaNumeric."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkaustraliapostcustomerformat\/alphanumeric"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkaustraliapostcustomerformat\/alphanumeric"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alphaNumeric","kind":"identifier"}]}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKAustraliaPostCustomerFormat@SBSDKAustraliaPostCustomerFormatAlphaNumeric","symbolKind":"case","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKAustraliaPostCustomerFormat.alphaNumeric","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alphaNumeric","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormatAlphaNumeric"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat\/alphaNumeric"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAustraliaPostCustomerFormat/alphaNumeric":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat\/alphaNumeric","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alphaNumeric","kind":"identifier"}],"title":"SBSDKAustraliaPostCustomerFormat.alphaNumeric","kind":"symbol","navigatorTitle":[{"text":"SBSDKAustraliaPostCustomerFormatAlphaNumeric","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkaustraliapostcustomerformat\/alphanumeric","abstract":[{"type":"text","text":"AlphaNumeric."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAustraliaPostCustomerFormat":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormat"}],"title":"SBSDKAustraliaPostCustomerFormat","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormat"}],"role":"symbol","abstract":[{"text":"Can be either numeric or alphanumeric and is only relevant for Format Codes 59 and 62.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkaustraliapostcustomerformat"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKAustraliaPostCustomerFormatAlphaNumeric","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormatAlphaNumeric"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormatAlphaNumeric"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKAustraliaPostCustomerFormatAlphaNumeric","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat~1alphaNumeric\/title","op":"replace"},{"value":[{"text":"SBSDKAustraliaPostCustomerFormatAlphaNumeric","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat~1alphaNumeric\/fragments","op":"replace"},{"value":"SBSDKAustraliaPostCustomerFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat\/title"},{"value":[{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormat"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat\/navigatorTitle"}]}]}