{"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"canvasColor","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBasicImageLoadOptions(py)canvasColor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"canvasColor"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canvasColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCanvasColor","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCanvasColor"}],"roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"CanvasColor color to use when converting images with alpha channel to images without alpha channel."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions\/canvascolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions\/canvascolor"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canvasColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCanvasColor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCanvasColor","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCanvasColor","kind":"typeIdentifier"}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is WHITE","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/canvasColor"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCanvasColor":{"url":"\/documentation\/scanbotsdk\/sbsdkcanvascolor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCanvasColor"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCanvasColor","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCanvasColor"}],"title":"SBSDKCanvasColor","abstract":[{"type":"text","text":"Canvas color to use when converting images with alpha channel to images without alpha channel."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBasicImageLoadOptions/canvasColor":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canvasColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCanvasColor","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCanvasColor"}],"type":"topic","title":"canvasColor","abstract":[{"type":"text","text":"CanvasColor color to use when converting images with alpha channel to images without alpha channel."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/canvasColor","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions\/canvascolor","navigatorTitle":[{"kind":"identifier","text":"canvasColor"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBasicImageLoadOptions":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions","navigatorTitle":[{"kind":"identifier","text":"SBSDKBasicImageLoadOptions"}],"title":"SBSDKBasicImageLoadOptions","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions","abstract":[{"type":"text","text":"Basic options for loading image."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBasicImageLoadOptions"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"canvasColor","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"canvasColor","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCanvasColor","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCanvasColor","text":"SBSDKCanvasColor"},{"kind":"text","text":" "},{"text":"canvasColor","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKCanvasColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCanvasColor\/title"},{"value":[{"kind":"identifier","text":"SBSDKCanvasColor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCanvasColor\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKCanvasColor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCanvasColor\/navigatorTitle"},{"value":"canvasColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions~1canvasColor\/title"},{"value":[{"kind":"identifier","text":"canvasColor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions~1canvasColor\/fragments"},{"value":"SBSDKBasicImageLoadOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions\/title"},{"value":[{"text":"SBSDKBasicImageLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBasicImageLoadOptions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions\/navigatorTitle"}]}]}