{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer\/init(configurationOptions:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"configurationOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerConfigurationOptions","text":"SBSDKMedicalCertificateRecognizerConfigurationOptions"},{"kind":"text","text":")"}],"symbolKind":"init","roleHeading":"Initializer","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizer(im)initWithConfigurationOptions:","navigatorTitle":[{"text":"initWithConfigurationOptions:","kind":"identifier"}],"title":"init(configurationOptions:)","modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"The designated initializer.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWithConfigurationOptions:) "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"configurationOptions","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"options","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerConfigurationOptions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerConfigurationOptions","text":"SBSDKMedicalCertificateRecognizerConfigurationOptions","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]},{"parameters":[{"name":"options","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The options used to create a new medical certificates recognizer."}]}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizer\/init(configurationoptions:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizer\/init(configurationoptions:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerConfigurationOptions":{"abstract":[{"type":"text","text":"A class intended to store the configuration options for a medical certificate recognizer."}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerconfigurationoptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerConfigurationOptions"}],"type":"topic","title":"SBSDKMedicalCertificateRecognizerConfigurationOptions","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerConfigurationOptions","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerConfigurationOptions","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizer/init(configurationOptions:)":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizer\/init(configurationoptions:)","role":"symbol","abstract":[{"text":"The designated initializer.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"configurationOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerConfigurationOptions","text":"SBSDKMedicalCertificateRecognizerConfigurationOptions"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer\/init(configurationOptions:)","navigatorTitle":[{"kind":"identifier","text":"initWithConfigurationOptions:"}],"title":"init(configurationOptions:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizer":{"type":"topic","kind":"symbol","title":"SBSDKMedicalCertificateRecognizer","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizer"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizer","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizer","abstract":[{"text":"A class to recognize medical certificates in a ","type":"text"},{"type":"codeVoice","code":"UIImage"},{"text":" or ","type":"text"},{"code":"CMSampleBuffer","type":"codeVoice"},{"type":"text","text":"."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithConfigurationOptions:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithConfigurationOptions:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithConfigurationOptions:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKMedicalCertificateRecognizerConfigurationOptions","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerConfigurationOptions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerConfigurationOptions","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"options","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerConfigurationOptions\/title","value":"SBSDKMedicalCertificateRecognizerConfigurationOptions"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerConfigurationOptions"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerConfigurationOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer~1init(configurationOptions:)\/title","value":"initWithConfigurationOptions:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer~1init(configurationOptions:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConfigurationOptions:"}]},{"value":"SBSDKMedicalCertificateRecognizer","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer\/title"},{"value":[{"text":"SBSDKMedicalCertificateRecognizer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer\/fragments"}]}]}