{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognitionOptions"},{"kind":"text","text":": "},{"text":"SBSDKMedicalCertificateRecognizerConfigurationOptions","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerConfigurationOptions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerConfigurationOptions","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"recognitionOptions","symbolKind":"property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizer(py)recognitionOptions","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"recognitionOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerConfigurationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerConfigurationOptions"}],"navigatorTitle":[{"text":"recognitionOptions","kind":"identifier"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizer\/recognitionoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizer\/recognitionoptions"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The options to be used with the medical certificates recognizer."}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer\/recognitionOptions"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizer/recognitionOptions":{"kind":"symbol","abstract":[{"type":"text","text":"The options to be used with the medical certificates recognizer."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognitionOptions"},{"text":": ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerConfigurationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerConfigurationOptions"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizer\/recognitionoptions","title":"recognitionOptions","type":"topic","navigatorTitle":[{"text":"recognitionOptions","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer\/recognitionOptions"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizer":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizer","abstract":[{"text":"A class to recognize medical certificates in a ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" or "},{"code":"CMSampleBuffer","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKMedicalCertificateRecognizer","kind":"identifier"}],"role":"symbol","title":"SBSDKMedicalCertificateRecognizer","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizer","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizer"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerConfigurationOptions":{"role":"symbol","title":"SBSDKMedicalCertificateRecognizerConfigurationOptions","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerConfigurationOptions"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerConfigurationOptions"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerconfigurationoptions","kind":"symbol","abstract":[{"text":"A class intended to store the configuration options for a medical certificate recognizer.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerConfigurationOptions"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"recognitionOptions","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"recognitionOptions"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerConfigurationOptions","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerConfigurationOptions","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerConfigurationOptions"},{"kind":"text","text":" * "},{"text":"recognitionOptions","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer~1recognitionOptions\/title","value":"recognitionOptions","op":"replace"},{"value":[{"kind":"identifier","text":"recognitionOptions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer~1recognitionOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer\/title","value":"SBSDKMedicalCertificateRecognizer"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer\/fragments","value":[{"text":"SBSDKMedicalCertificateRecognizer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizer\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizer"}],"op":"replace"},{"value":"SBSDKMedicalCertificateRecognizerConfigurationOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerConfigurationOptions\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerConfigurationOptions\/fragments","op":"replace","value":[{"text":"SBSDKMedicalCertificateRecognizerConfigurationOptions","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerConfigurationOptions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerConfigurationOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}