{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verticalLines"},{"text":": [","kind":"text"},{"text":"SBSDKLineSegmentInt","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentInt","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentInt"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult\/verticalLines"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"All detected vertical lines in image space.","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"verticalLines"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"verticalLines"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKLineSegmentInt","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentInt"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult(py)verticalLines","modules":[{"name":"ScanbotSDK"}],"title":"verticalLines","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult\/verticallines"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult\/verticallines"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionResult/verticalLines":{"title":"verticalLines","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult\/verticalLines","abstract":[{"text":"All detected vertical lines in image space.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"verticalLines"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verticalLines"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegmentInt","text":"SBSDKLineSegmentInt","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult\/verticallines","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult","title":"SBSDKDocumentDetectionResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult","abstract":[{"text":"Result of the document contour detection.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLineSegmentInt":{"title":"SBSDKLineSegmentInt","url":"\/documentation\/scanbotsdk\/sbsdklinesegmentint","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKLineSegmentInt","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLineSegmentInt","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKLineSegmentInt","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Represents a line segment in 2D space."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"verticalLines","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"verticalLines"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKLineSegmentInt *>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"verticalLines","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"verticalLines","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult~1verticalLines\/title","op":"replace"},{"value":[{"kind":"identifier","text":"verticalLines"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult~1verticalLines\/fragments"},{"value":"SBSDKDocumentDetectionResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/fragments","value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/navigatorTitle","value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentInt\/title","op":"replace","value":"SBSDKLineSegmentInt"},{"value":[{"text":"SBSDKLineSegmentInt","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentInt\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLineSegmentInt\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKLineSegmentInt"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}