{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognizerConfiguration"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","kind":"typeIdentifier","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerBehaviorConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerbehaviorconfiguration\/recognizerconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerbehaviorconfiguration\/recognizerconfiguration"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The live detection configuration parameters.","type":"text"}],"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"recognizerConfiguration","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardRecognizerBehaviorConfiguration(py)recognizerConfiguration","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognizerConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","kind":"typeIdentifier","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"recognizerConfiguration"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerBehaviorConfiguration\/recognizerConfiguration","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerBehaviorConfiguration/recognizerConfiguration":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognizerConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerbehaviorconfiguration\/recognizerconfiguration","abstract":[{"text":"The live detection configuration parameters.","type":"text"}],"type":"topic","title":"recognizerConfiguration","navigatorTitle":[{"text":"recognizerConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerBehaviorConfiguration\/recognizerConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerBehaviorConfiguration":{"navigatorTitle":[{"text":"SBSDKUIHealthInsuranceCardRecognizerBehaviorConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Configuration for the behavior of RTU-UI health Insurance Card scanner screen."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerBehaviorConfiguration","title":"SBSDKUIHealthInsuranceCardRecognizerBehaviorConfiguration","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerbehaviorconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIHealthInsuranceCardRecognizerBehaviorConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognizerconfiguration","type":"topic","abstract":[{"text":"Configuration for the European health insurance card (EHIC) recognizer.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","title":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"recognizerConfiguration","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"recognizerConfiguration"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"},{"text":" * ","kind":"text"},{"text":"recognizerConfiguration","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"recognizerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerBehaviorConfiguration~1recognizerConfiguration\/title","op":"replace"},{"value":[{"text":"recognizerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerBehaviorConfiguration~1recognizerConfiguration\/fragments","op":"replace"},{"value":"SBSDKUIHealthInsuranceCardRecognizerBehaviorConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerBehaviorConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKUIHealthInsuranceCardRecognizerBehaviorConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerBehaviorConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKUIHealthInsuranceCardRecognizerBehaviorConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerBehaviorConfiguration\/navigatorTitle","op":"replace"},{"value":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/navigatorTitle","op":"replace"}]}]}