{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"totalMemoryConsumptionDiff","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"}]}]},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Default is 0"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshotsDiff\/totalMemoryConsumptionDiff"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshotsDiff"]]},"abstract":[{"type":"text","text":"Difference between total memory consumption in two snapshots."}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefpoolsnapshotsdiff\/totalmemoryconsumptiondiff"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefpoolsnapshotsdiff\/totalmemoryconsumptiondiff"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"totalMemoryConsumptionDiff"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalMemoryConsumptionDiff"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"}],"role":"symbol","title":"totalMemoryConsumptionDiff","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshotsDiff(py)totalMemoryConsumptionDiff","symbolKind":"property","roleHeading":"Instance Property"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 8.0.4","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefPoolSnapshotsDiff":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshotsDiff","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefpoolsnapshotsdiff","type":"topic","title":"SBSDKImageRefPoolSnapshotsDiff","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshotsDiff","abstract":[{"type":"text","text":"difference between two snapshots."}],"navigatorTitle":[{"text":"SBSDKImageRefPoolSnapshotsDiff","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefPoolSnapshotsDiff/totalMemoryConsumptionDiff":{"navigatorTitle":[{"kind":"identifier","text":"totalMemoryConsumptionDiff"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshotsDiff\/totalMemoryConsumptionDiff","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalMemoryConsumptionDiff"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"text":"Difference between total memory consumption in two snapshots.","type":"text"}],"title":"totalMemoryConsumptionDiff","type":"topic","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefpoolsnapshotsdiff\/totalmemoryconsumptiondiff"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"totalMemoryConsumptionDiff","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"totalMemoryConsumptionDiff"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"int64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@int64_t"},{"text":" ","kind":"text"},{"text":"totalMemoryConsumptionDiff","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefPoolSnapshotsDiff\/title","value":"SBSDKImageRefPoolSnapshotsDiff","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefPoolSnapshotsDiff\/fragments","value":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshotsDiff"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefPoolSnapshotsDiff\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshotsDiff"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefPoolSnapshotsDiff~1totalMemoryConsumptionDiff\/title","value":"totalMemoryConsumptionDiff","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefPoolSnapshotsDiff~1totalMemoryConsumptionDiff\/fragments","value":[{"text":"totalMemoryConsumptionDiff","kind":"identifier"}],"op":"replace"}]}]}