{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"creditCardCardholderNameFieldNormalizedName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardCardholderNameFieldNormalizedName","interfaceLanguage":"swift"},"abstract":[{"text":"Normalized full name of the “CardholderName” field type in document type “CreditCard”.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants\/creditcardcardholdernamefieldnormalizedname"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants\/creditcardcardholdernamefieldnormalizedname"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardDocumentModelConstants(cpy)creditCardCardholderNameFieldNormalizedName","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"creditCardCardholderNameFieldNormalizedName"}],"symbolKind":"property","title":"creditCardCardholderNameFieldNormalizedName","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardCardholderNameFieldNormalizedName","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardDocumentModelConstants/creditCardCardholderNameFieldNormalizedName":{"title":"creditCardCardholderNameFieldNormalizedName","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"creditCardCardholderNameFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardCardholderNameFieldNormalizedName","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Normalized full name of the “CardholderName” field type in document type “CreditCard”."}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants\/creditcardcardholdernamefieldnormalizedname","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"creditCardCardholderNameFieldNormalizedName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardDocumentModelConstants":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCreditCardDocumentModelConstants","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants","title":"SBSDKCreditCardDocumentModelConstants","navigatorTitle":[{"text":"SBSDKCreditCardDocumentModelConstants","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"creditCardCardholderNameFieldNormalizedName","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"creditCardCardholderNameFieldNormalizedName"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"creditCardCardholderNameFieldNormalizedName"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants~1creditCardCardholderNameFieldNormalizedName\/title","value":"creditCardCardholderNameFieldNormalizedName"},{"value":[{"kind":"identifier","text":"creditCardCardholderNameFieldNormalizedName"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants~1creditCardCardholderNameFieldNormalizedName\/fragments","op":"replace"},{"value":"SBSDKCreditCardDocumentModelConstants","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants\/title","op":"replace"},{"value":[{"text":"SBSDKCreditCardDocumentModelConstants","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants\/navigatorTitle","value":[{"text":"SBSDKCreditCardDocumentModelConstants","kind":"identifier"}]}]}]}