{"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"width"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatio(py)width","title":"width","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatio\/width"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is 1.0"}]}],"kind":"content"}],"abstract":[{"text":"Width component of the aspect ratio.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatio"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkaspectratio\/width"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkaspectratio\/width"]}],"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAspectRatio/width":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatio\/width","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"type":"topic","title":"width","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaspectratio\/width","abstract":[{"type":"text","text":"Width component of the aspect ratio."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"width"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAspectRatio":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaspectratio","role":"symbol","navigatorTitle":[{"text":"SBSDKAspectRatio","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatio","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKAspectRatio"}],"title":"SBSDKAspectRatio","abstract":[{"type":"text","text":"Aspect ratio is the ratio of the width to the height of an image or screen."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"width"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"width"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":" ","kind":"text"},{"kind":"identifier","text":"width"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio~1width\/title","value":"width"},{"value":[{"text":"width","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio~1width\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio\/title","op":"replace","value":"SBSDKAspectRatio"},{"value":[{"text":"SBSDKAspectRatio","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKAspectRatio"}],"op":"replace"}]}]}