{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter\/paperwhitening"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter\/paperwhitening"]}],"sections":[],"kind":"symbol","abstract":[{"text":"Paper whitening strength balances color enhancement and paper color improvement.","type":"text"},{"text":" ","type":"text"},{"text":"Only relevant if colorEnhancement is above 0. Typical values are between 0 and 2.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paperWhitening"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]}]},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Default is 1"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/paperWhitening"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter"]]},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paperWhitening","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKColorDocumentFilter(py)paperWhitening","navigatorTitle":[{"text":"paperWhitening","kind":"identifier"}],"title":"paperWhitening","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorDocumentFilter/paperWhitening":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/paperWhitening","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"paperWhitening","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter\/paperwhitening","title":"paperWhitening","abstract":[{"text":"Paper whitening strength balances color enhancement and paper color improvement.","type":"text"},{"text":" ","type":"text"},{"text":"Only relevant if colorEnhancement is above 0. Typical values are between 0 and 2.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paperWhitening","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorDocumentFilter":{"title":"SBSDKColorDocumentFilter","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter","role":"symbol","navigatorTitle":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter","abstract":[{"text":"Color document filter. This filter is a good starting point for most use cases.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"paperWhitening","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"paperWhitening"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"paperWhitening","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"paperWhitening","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter~1paperWhitening\/title"},{"op":"replace","value":[{"text":"paperWhitening","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter~1paperWhitening\/fragments"},{"op":"replace","value":"SBSDKColorDocumentFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter\/title"},{"op":"replace","value":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter\/navigatorTitle","value":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}