{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypter\/decryptDataFromURL:error:"},"metadata":{"fragments":[{"kind":"text","text":"- "},{"text":"decryptDataFromURL:error:","kind":"identifier"}],"navigatorTitle":[{"text":"decryptDataFromURL:error:","kind":"identifier"}],"role":"symbol","symbolKind":"method","title":"decryptDataFromURL:error:","roleHeading":"Instance Method","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAESEncrypter(im)decryptDataFromURL:error:"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypter"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"text":" *) ","kind":"text"},{"text":"decryptDataFromURL:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"url"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkaesencrypter\/decryptdatafromurl:error:"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAESEncrypter/decryptDataFromURL:error:":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypter\/decryptDataFromURL:error:","abstract":[],"kind":"symbol","title":"decryptDataFromURL:error:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"decryptDataFromURL:error:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaesencrypter\/decryptdatafromurl:error:","navigatorTitle":[{"kind":"identifier","text":"decryptDataFromURL:error:"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAESEncrypter":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKAESEncrypter"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKAESEncrypter"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaesencrypter","abstract":[{"text":"ScanbotSDK’s default data encrypter. Provides AES128 and AES 256 encryption to your data.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"All data is encrypted and decrypted with the same key."},{"type":"text","text":" "},{"text":"The context being passed to the encrypt\/decrypt methods is ignored.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypter","title":"SBSDKAESEncrypter"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKAESEncrypter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypter\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypter\/fragments","value":[{"kind":"identifier","text":"SBSDKAESEncrypter"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypter\/navigatorTitle","value":[{"text":"SBSDKAESEncrypter","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}