{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"a1","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeDriverLicenseBackCategory","kind":"typeIdentifier","text":"SBSDKGenericDocumentDeDriverLicenseBackCategory","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentDeDriverLicenseBackCategory"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentdedriverlicensebackcategories\/a1"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentdedriverlicensebackcategories\/a1"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeDriverLicenseBackCategories"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"a1","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"a1"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentDeDriverLicenseBackCategory","kind":"typeIdentifier","text":"SBSDKGenericDocumentDeDriverLicenseBackCategory"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"a1"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentDeDriverLicenseBackCategories(py)a1","role":"symbol","roleHeading":"Instance Property","symbolKind":"property"},"sections":[],"abstract":[{"type":"text","text":"A1."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeDriverLicenseBackCategories\/a1"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentDeDriverLicenseBackCategories":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentDeDriverLicenseBackCategories"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeDriverLicenseBackCategories","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentdedriverlicensebackcategories","kind":"symbol","title":"SBSDKGenericDocumentDeDriverLicenseBackCategories","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentDeDriverLicenseBackCategories"}],"abstract":[{"type":"text","text":"Categories table row container."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentDeDriverLicenseBackCategories/a1":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeDriverLicenseBackCategories\/a1","navigatorTitle":[{"text":"a1","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"a1","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentDeDriverLicenseBackCategory","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentDeDriverLicenseBackCategory"},{"text":"?","kind":"text"}],"title":"a1","abstract":[{"text":"A1.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentdedriverlicensebackcategories\/a1","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentDeDriverLicenseBackCategory":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentDeDriverLicenseBackCategory"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeDriverLicenseBackCategory","kind":"symbol","title":"SBSDKGenericDocumentDeDriverLicenseBackCategory","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentdedriverlicensebackcategory","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentDeDriverLicenseBackCategory","kind":"identifier"}],"abstract":[{"type":"text","text":"A category row from the categories table."}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"a1","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"a1"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeDriverLicenseBackCategory","kind":"typeIdentifier","text":"SBSDKGenericDocumentDeDriverLicenseBackCategory","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentDeDriverLicenseBackCategory"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"a1"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKGenericDocumentDeDriverLicenseBackCategories","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeDriverLicenseBackCategories\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeDriverLicenseBackCategories\/fragments","value":[{"text":"SBSDKGenericDocumentDeDriverLicenseBackCategories","kind":"identifier"}],"op":"replace"},{"value":"a1","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeDriverLicenseBackCategories~1a1\/title"},{"op":"replace","value":[{"text":"a1","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeDriverLicenseBackCategories~1a1\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeDriverLicenseBackCategory\/title","value":"SBSDKGenericDocumentDeDriverLicenseBackCategory","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeDriverLicenseBackCategory\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentDeDriverLicenseBackCategory"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}