{"abstract":[{"type":"text","text":"For both colored and binarized images."}],"sections":[],"metadata":{"title":"SBSDKTIFFImageWriterCompressionOptions.none","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKTIFFImageWriterCompressionOptions@SBSDKTIFFImageWriterCompressionOptionsNone","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsNone"}],"symbolKind":"case","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/none"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/none"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/none","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions/none":{"title":"SBSDKTIFFImageWriterCompressionOptions.none","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsNone"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/none","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/none","kind":"symbol","abstract":[{"text":"For both colored and binarized images.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.2.0","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions":{"kind":"symbol","type":"topic","title":"SBSDKTIFFImageWriterCompressionOptions","role":"symbol","abstract":[{"type":"text","text":"The TIFF compression algorithms."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"}],"navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKTIFFImageWriterCompressionOptionsNone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKTIFFImageWriterCompressionOptionsNone","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKTIFFImageWriterCompressionOptionsNone","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1none\/title","value":"SBSDKTIFFImageWriterCompressionOptionsNone"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1none\/fragments","value":[{"text":"SBSDKTIFFImageWriterCompressionOptionsNone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions\/title","value":"SBSDKTIFFImageWriterCompressionOptions"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions\/fragments","value":[{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions\/navigatorTitle","value":[{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}