{"metadata":{"title":"pageCounter","symbolKind":"property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2TextWithBadgeButtonMode(py)pageCounter","navigatorTitle":[{"kind":"identifier","text":"pageCounter"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageCounter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BadgeStyle","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BadgeStyle"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2textwithbadgebuttonmode\/pagecounter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2textwithbadgebuttonmode\/pagecounter"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageCounter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BadgeStyle","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BadgeStyle","text":"SBSDKUI2BadgeStyle"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Configuration of the badge icon."}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TextWithBadgeButtonMode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TextWithBadgeButtonMode\/pageCounter"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2TextWithBadgeButtonMode/pageCounter":{"navigatorTitle":[{"text":"pageCounter","kind":"identifier"}],"type":"topic","title":"pageCounter","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageCounter","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BadgeStyle","text":"SBSDKUI2BadgeStyle","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TextWithBadgeButtonMode\/pageCounter","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2textwithbadgebuttonmode\/pagecounter","abstract":[{"type":"text","text":"Configuration of the badge icon."}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2TextWithBadgeButtonMode":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextWithBadgeButtonMode"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2textwithbadgebuttonmode","abstract":[{"text":"Configuration of the ‘preview’ button in ‘text with badge button mode’.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TextWithBadgeButtonMode","title":"SBSDKUI2TextWithBadgeButtonMode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextWithBadgeButtonMode"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2BadgeStyle":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BadgeStyle","kind":"symbol","title":"SBSDKUI2BadgeStyle","abstract":[{"type":"text","text":"Configuration of the badge."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2badgestyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BadgeStyle"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BadgeStyle"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","abstract":[{"text":"Version: 8.0.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"pageCounter"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"pageCounter","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BadgeStyle","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BadgeStyle","text":"SBSDKUI2BadgeStyle","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"pageCounter","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TextWithBadgeButtonMode~1pageCounter\/title","op":"replace","value":"pageCounter"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TextWithBadgeButtonMode~1pageCounter\/fragments","op":"replace","value":[{"kind":"identifier","text":"pageCounter"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TextWithBadgeButtonMode\/title","op":"replace","value":"SBSDKUI2TextWithBadgeButtonMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TextWithBadgeButtonMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2TextWithBadgeButtonMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TextWithBadgeButtonMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2TextWithBadgeButtonMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BadgeStyle\/title","op":"replace","value":"SBSDKUI2BadgeStyle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BadgeStyle\/fragments","op":"replace","value":[{"text":"SBSDKUI2BadgeStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BadgeStyle\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2BadgeStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}