{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"binarized"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/binarized"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/binarized"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/binarized","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Standard binarization filter with contrast optimization. Creates a grayscaled 8-bit image with mostly black or white pixels."},{"type":"text","text":" "},{"type":"text","text":"Usecase: Preparation for optical character recognition."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeBinarized"}],"role":"symbol","title":"SBSDKImageFilterType.binarized","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"binarized"}],"symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKImageFilterType@SBSDKImageFilterTypeBinarized","modules":[{"name":"ScanbotSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please consider using the new class-based SBSDKParametricFilters."}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/binarized":{"deprecated":true,"role":"symbol","title":"SBSDKImageFilterType.binarized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"binarized"}],"abstract":[{"type":"text","text":"Standard binarization filter with contrast optimization. Creates a grayscaled 8-bit image with mostly black or white pixels."},{"type":"text","text":" "},{"type":"text","text":"Usecase: Preparation for optical character recognition."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/binarized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeBinarized"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/binarized"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType":{"deprecated":true,"role":"symbol","title":"SBSDKImageFilterType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFilterType"}],"abstract":[{"type":"text","text":"The ScanbotSDK image filter types."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKImageFilterTypeBinarized"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeBinarized"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKImageFilterTypeBinarized"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1binarized\/title","value":"SBSDKImageFilterTypeBinarized"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1binarized\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeBinarized"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/title","value":"SBSDKImageFilterType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}