{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/colordocument"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/colordocument"]}],"sections":[],"abstract":[{"text":"Fixes white-balance and cleans up the background.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Usecase: images of paper documents."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/colorDocument"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"colorDocument","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKImageFilterType@SBSDKImageFilterTypeColorDocument","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeColorDocument"}],"roleHeading":"Case","role":"symbol","platforms":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"colorDocument"}],"title":"SBSDKImageFilterType.colorDocument","modules":[{"name":"ScanbotSDK"}]},"deprecationSummary":[{"inlineContent":[{"text":"Please consider using the new class-based SBSDKParametricFilters.","type":"text"}],"type":"paragraph"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/colorDocument":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"colorDocument","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/colordocument","title":"SBSDKImageFilterType.colorDocument","role":"symbol","navigatorTitle":[{"text":"SBSDKImageFilterTypeColorDocument","kind":"identifier"}],"deprecated":true,"abstract":[{"type":"text","text":"Fixes white-balance and cleans up the background."},{"type":"text","text":" "},{"type":"text","text":"Usecase: images of paper documents."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/colorDocument","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","title":"SBSDKImageFilterType","url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFilterType"}],"kind":"symbol","deprecated":true,"navigatorTitle":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"abstract":[{"text":"The ScanbotSDK image filter types.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKImageFilterTypeColorDocument","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKImageFilterTypeColorDocument"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKImageFilterTypeColorDocument"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKImageFilterTypeColorDocument","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1colorDocument\/title","op":"replace"},{"value":[{"text":"SBSDKImageFilterTypeColorDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1colorDocument\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/title","value":"SBSDKImageFilterType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}