{"abstract":[{"type":"text","text":"A filter that enhances edges in low-contrast documents."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/edgehighlight"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/edgehighlight"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"platforms":[],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKImageFilterType@SBSDKImageFilterTypeEdgeHighlight","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"edgeHighlight","kind":"identifier"}],"title":"SBSDKImageFilterType.edgeHighlight","roleHeading":"Case","role":"symbol","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeEdgeHighlight"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"edgeHighlight"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType"]]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/edgeHighlight","interfaceLanguage":"swift"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Please consider using the new class-based SBSDKParametricFilters.","type":"text"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/edgeHighlight":{"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/edgehighlight","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/edgeHighlight","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"edgeHighlight"}],"title":"SBSDKImageFilterType.edgeHighlight","abstract":[{"text":"A filter that enhances edges in low-contrast documents.","type":"text"}],"kind":"symbol","role":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeEdgeHighlight"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType":{"abstract":[{"type":"text","text":"The ScanbotSDK image filter types."}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype","title":"SBSDKImageFilterType","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","deprecated":true,"navigatorTitle":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKImageFilterType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKImageFilterTypeEdgeHighlight","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKImageFilterTypeEdgeHighlight","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKImageFilterTypeEdgeHighlight"}]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKImageFilterTypeEdgeHighlight","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1edgeHighlight\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1edgeHighlight\/fragments","op":"replace","value":[{"text":"SBSDKImageFilterTypeEdgeHighlight","kind":"identifier"}]},{"value":"SBSDKImageFilterType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/title"},{"value":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/fragments"}]}]}