{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/lowlightbinarization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/lowlightbinarization"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"lowLightBinarization","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Binarization filter primary inteded to use on low-contrast documents with heavy shadows."}],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKImageFilterType@SBSDKImageFilterTypeLowLightBinarization","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeLowLightBinarization"}],"role":"symbol","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKImageFilterType.lowLightBinarization","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"lowLightBinarization","kind":"identifier"}],"roleHeading":"Case","platforms":[]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/lowLightBinarization","interfaceLanguage":"swift"},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Please consider using the new class-based SBSDKParametricFilters."}],"type":"paragraph"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/lowLightBinarization":{"role":"symbol","abstract":[{"type":"text","text":"Binarization filter primary inteded to use on low-contrast documents with heavy shadows."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/lowLightBinarization","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lowLightBinarization","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/lowlightbinarization","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeLowLightBinarization"}],"deprecated":true,"title":"SBSDKImageFilterType.lowLightBinarization","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType":{"deprecated":true,"title":"SBSDKImageFilterType","abstract":[{"type":"text","text":"The ScanbotSDK image filter types."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageFilterType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","navigatorTitle":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"SBSDKImageFilterTypeLowLightBinarization","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeLowLightBinarization"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKImageFilterTypeLowLightBinarization"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1lowLightBinarization\/title","op":"replace","value":"SBSDKImageFilterTypeLowLightBinarization"},{"value":[{"text":"SBSDKImageFilterTypeLowLightBinarization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1lowLightBinarization\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/title","value":"SBSDKImageFilterType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}