{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/none"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/none"},"kind":"symbol","abstract":[{"text":"Passthrough filter. Does not alter the image.","type":"text"}],"deprecationSummary":[{"inlineContent":[{"text":"Please consider using the new class-based SBSDKParametricFilters.","type":"text"}],"type":"paragraph"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType"]]},"metadata":{"title":"SBSDKImageFilterType.none","externalID":"c:@M@ScanbotSDK@E@SBSDKImageFilterType@SBSDKImageFilterTypeNone","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeNone"}],"symbolKind":"case","role":"symbol","platforms":[],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"roleHeading":"Case"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType":{"navigatorTitle":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"abstract":[{"type":"text","text":"The ScanbotSDK image filter types."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFilterType"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","role":"symbol","deprecated":true,"title":"SBSDKImageFilterType","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/none":{"title":"SBSDKImageFilterType.none","deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/none","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeNone"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/none","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"kind":"symbol","abstract":[{"text":"Passthrough filter. Does not alter the image.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKImageFilterTypeNone"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKImageFilterTypeNone","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKImageFilterTypeNone","kind":"identifier"}],"languages":["occ"]}]}},{"value":"SBSDKImageFilterType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1none\/title","value":"SBSDKImageFilterTypeNone"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1none\/fragments","op":"replace","value":[{"text":"SBSDKImageFilterTypeNone","kind":"identifier"}]}]}]}