{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvavehiclesafetyinspectiondatainspectionaddressfieldnormalizedname"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvavehiclesafetyinspectiondatainspectionaddressfieldnormalizedname"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/aamvaVehicleSafetyInspectionDataInspectionAddressFieldNormalizedName"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"aamvaVehicleSafetyInspectionDataInspectionAddressFieldNormalizedName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelConstants(cpy)aamvaVehicleSafetyInspectionDataInspectionAddressFieldNormalizedName","navigatorTitle":[{"text":"aamvaVehicleSafetyInspectionDataInspectionAddressFieldNormalizedName","kind":"identifier"}],"symbolKind":"property","title":"aamvaVehicleSafetyInspectionDataInspectionAddressFieldNormalizedName","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aamvaVehicleSafetyInspectionDataInspectionAddressFieldNormalizedName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}]},"sections":[],"abstract":[{"text":"Normalized full name of the “InspectionAddress” field type in document type “AAMVA.VehicleSafetyInspectionData”.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants/aamvaVehicleSafetyInspectionDataInspectionAddressFieldNormalizedName":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/aamvaVehicleSafetyInspectionDataInspectionAddressFieldNormalizedName","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvavehiclesafetyinspectiondatainspectionaddressfieldnormalizedname","abstract":[{"text":"Normalized full name of the “InspectionAddress” field type in document type “AAMVA.VehicleSafetyInspectionData”.","type":"text"}],"navigatorTitle":[{"text":"aamvaVehicleSafetyInspectionDataInspectionAddressFieldNormalizedName","kind":"identifier"}],"title":"aamvaVehicleSafetyInspectionDataInspectionAddressFieldNormalizedName","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aamvaVehicleSafetyInspectionDataInspectionAddressFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants","kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants","type":"topic","title":"SBSDKBarcodeDocumentModelConstants","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"aamvaVehicleSafetyInspectionDataInspectionAddressFieldNormalizedName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"aamvaVehicleSafetyInspectionDataInspectionAddressFieldNormalizedName","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"aamvaVehicleSafetyInspectionDataInspectionAddressFieldNormalizedName"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"aamvaVehicleSafetyInspectionDataInspectionAddressFieldNormalizedName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1aamvaVehicleSafetyInspectionDataInspectionAddressFieldNormalizedName\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1aamvaVehicleSafetyInspectionDataInspectionAddressFieldNormalizedName\/fragments","value":[{"text":"aamvaVehicleSafetyInspectionDataInspectionAddressFieldNormalizedName","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/title","value":"SBSDKBarcodeDocumentModelConstants"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/navigatorTitle","value":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}