{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"String being displayed when health insurance card was not found."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizertextconfiguration\/detectionstatusfaileddetectiontext"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizertextconfiguration\/detectionstatusfaileddetectiontext"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerTextConfiguration"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"detectionStatusFailedDetectionText"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionStatusFailedDetectionText","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardRecognizerTextConfiguration(py)detectionStatusFailedDetectionText","roleHeading":"Instance Property","title":"detectionStatusFailedDetectionText","symbolKind":"property"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerTextConfiguration\/detectionStatusFailedDetectionText"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionStatusFailedDetectionText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerTextConfiguration":{"abstract":[{"type":"text","text":"Configuration for the textual contents of the detector RTU-UI screen for Health Insurance Card scanner."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizertextconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIHealthInsuranceCardRecognizerTextConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIHealthInsuranceCardRecognizerTextConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerTextConfiguration","title":"SBSDKUIHealthInsuranceCardRecognizerTextConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerTextConfiguration/detectionStatusFailedDetectionText":{"title":"detectionStatusFailedDetectionText","abstract":[{"text":"String being displayed when health insurance card was not found.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerTextConfiguration\/detectionStatusFailedDetectionText","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"detectionStatusFailedDetectionText"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionStatusFailedDetectionText"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizertextconfiguration\/detectionstatusfaileddetectiontext"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"detectionStatusFailedDetectionText","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"detectionStatusFailedDetectionText","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"detectionStatusFailedDetectionText"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUIHealthInsuranceCardRecognizerTextConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerTextConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKUIHealthInsuranceCardRecognizerTextConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerTextConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerTextConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerTextConfiguration\/navigatorTitle"},{"op":"replace","value":"detectionStatusFailedDetectionText","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerTextConfiguration~1detectionStatusFailedDetectionText\/title"},{"op":"replace","value":[{"text":"detectionStatusFailedDetectionText","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerTextConfiguration~1detectionStatusFailedDetectionText\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}