{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensefront\/initwithgenericdocument:"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseFront"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithGenericDocument:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","text":"SBSDKGenericDocument"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"document"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseFront\/initWithGenericDocument:"},"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"title":"initWithGenericDocument:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelEuropeanDriverLicenseFront(im)initWithGenericDocument:"},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocument"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","type":"topic","abstract":[{"type":"text","text":"Generic document."}],"title":"SBSDKGenericDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelEuropeanDriverLicenseFront/initWithGenericDocument:":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensefront\/initwithgenericdocument:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseFront\/initWithGenericDocument:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"title":"initWithGenericDocument:","role":"symbol","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelEuropeanDriverLicenseFront":{"title":"SBSDKDocumentsModelEuropeanDriverLicenseFront","abstract":[{"text":"European driver license, front side","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelEuropeanDriverLicenseFront","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseFront","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensefront","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseFront"}},"variantOverrides":[{"patch":[{"value":"SBSDKGenericDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title"},{"value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments"},{"value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle"},{"value":"SBSDKDocumentsModelEuropeanDriverLicenseFront","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseFront\/title"},{"value":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseFront","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseFront\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentsModelEuropeanDriverLicenseFront"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseFront\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}