{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckbox\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBox\/hash"},"metadata":{"title":"hash","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"hash"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"hash","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateCheckBox(py)hash"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBox"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBox":{"abstract":[{"type":"text","text":"Structure to contain full information about found box."}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBox","kind":"identifier"}],"title":"SBSDKMedicalCertificateCheckBox","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckbox","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBox","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateCheckBox","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBox/hash":{"type":"topic","title":"hash","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBox\/hash","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckbox\/hash","role":"symbol","kind":"symbol","fragments":[{"text":"hash","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBox\/title","op":"replace","value":"SBSDKMedicalCertificateCheckBox"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBox\/fragments","op":"replace","value":[{"text":"SBSDKMedicalCertificateCheckBox","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBox\/navigatorTitle","op":"replace","value":[{"text":"SBSDKMedicalCertificateCheckBox","kind":"identifier"}]}]}]}