{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration\/energySaveDetectionRate"},"metadata":{"navigatorTitle":[{"text":"energySaveDetectionRate","kind":"identifier"}],"roleHeading":"Instance Property","title":"energySaveDetectionRate","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration(py)energySaveDetectionRate","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"energySaveDetectionRate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"energySaveDetectionRate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration\/energysavedetectionrate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration\/energysavedetectionrate"]}],"abstract":[{"type":"text","text":"The rate of detections\/recognitions per second in energy save mode."},{"type":"text","text":" "},{"type":"text","text":"Defaults to 1, meaning that 1 frame per second is detected\/recognized."},{"type":"text","text":" "},{"type":"text","text":"When the video frame rate is 30, 29 frames will be skipped, 1 frame is detected\/recognized."},{"type":"text","text":" "},{"type":"text","text":"Note: if you set the detection rate greater to or equal to the video frame rate, no frames will be skipped,"},{"type":"text","text":" "},{"type":"text","text":"the actual detection rate is limited by the video frame rate."},{"type":"text","text":" "},{"type":"text","text":"Note: Usually you set a much lower value here as for the detectionRate property to save energy."}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerEnergyConfiguration/energySaveDetectionRate":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"energySaveDetectionRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration\/energysavedetectionrate","title":"energySaveDetectionRate","abstract":[{"type":"text","text":"The rate of detections\/recognitions per second in energy save mode."},{"type":"text","text":" "},{"type":"text","text":"Defaults to 1, meaning that 1 frame per second is detected\/recognized."},{"type":"text","text":" "},{"type":"text","text":"When the video frame rate is 30, 29 frames will be skipped, 1 frame is detected\/recognized."},{"type":"text","text":" "},{"type":"text","text":"Note: if you set the detection rate greater to or equal to the video frame rate, no frames will be skipped,"},{"type":"text","text":" "},{"type":"text","text":"the actual detection rate is limited by the video frame rate."},{"text":" ","type":"text"},{"text":"Note: Usually you set a much lower value here as for the detectionRate property to save energy.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration\/energySaveDetectionRate","navigatorTitle":[{"kind":"identifier","text":"energySaveDetectionRate"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerEnergyConfiguration":{"title":"SBSDKBaseScannerEnergyConfiguration","abstract":[{"text":"The energy management configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"},{"text":" ","type":"text"},{"text":"‘SBSDKBaseScannerViewController’ and subclasses sport a customizable energy management system.","type":"text"},{"text":" ","type":"text"},{"text":"Since scanners running on a live video feed can put a lot of load onto the CPU and\/or GPU","type":"text"},{"text":" ","type":"text"},{"text":"of the device, causing the battery to drain quickly and running the device hot, you can customize the energy","type":"text"},{"text":" ","type":"text"},{"text":"consumption using this class by configuring the rate of detections\/recognitions per second in performance mode as","type":"text"},{"text":" ","type":"text"},{"text":"well as in energy saving mode.","type":"text"},{"text":" ","type":"text"},{"text":"In performance mode the scanners will be fed with a higher, configurable rate of","type":"text"},{"text":" ","type":"text"},{"text":"video frames per second.","type":"text"},{"text":" ","type":"text"},{"text":"After a certain, configurable period of inactivity the energy save mode will be engaged and the rate","type":"text"},{"text":" ","type":"text"},{"text":"of scans will be reduced to a lower (configurable) rate.","type":"text"},{"text":" ","type":"text"},{"text":"You can also configure the time of inactivity before the automatic mode switches from performance to energy save mode.","type":"text"},{"text":" ","type":"text"},{"text":"Inactivity here means that both of the following conditions are met:","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"energySaveDetectionRate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"energySaveDetectionRate"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"energySaveDetectionRate"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration~1energySaveDetectionRate\/title","op":"replace","value":"energySaveDetectionRate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration~1energySaveDetectionRate\/fragments","op":"replace","value":[{"text":"energySaveDetectionRate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration\/title","op":"replace","value":"SBSDKBaseScannerEnergyConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}]}]}]}