{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController\/init(parentViewController:parentView:configuration:delegate:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController"]]},"kind":"symbol","abstract":[{"text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontroller\/init(parentviewcontroller:parentview:configuration:delegate:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontroller\/init(parentviewcontroller:parentview:configuration:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(initWithParentViewController:parentView:delegate:configuration:) "},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"text":"parentViewController","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":", ","kind":"text"},{"text":"parentView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration","text":"SBSDKBarcodeScannerConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKBarcodeScanAndCountViewControllerDelegate","text":"SBSDKBarcodeScanAndCountViewControllerDelegate"},{"text":"?)","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The view controller the newly created instance is embedded into."}],"type":"paragraph"}],"name":"parentViewController"},{"name":"parentView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view the newly created instance is embedded into."}]}]},{"name":"configuration","content":[{"inlineContent":[{"type":"text","text":"The receivers configuration."}],"type":"paragraph"}]},{"name":"delegate","content":[{"inlineContent":[{"text":"The delegate for the receiver.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"code":"parentViewController","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate"},{"text":" and if the delegate is ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":", it is"},{"text":" ","type":"text"},{"text":"automatically set as delegate.","type":"text"}]}]}],"metadata":{"roleHeading":"Initializer","title":"init(parentViewController:parentView:configuration:delegate:)","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"parentViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"text":"parentView","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerConfiguration","text":"SBSDKBarcodeScannerConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKBarcodeScanAndCountViewControllerDelegate","text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScanAndCountViewController(im)initWithParentViewController:parentView:delegate:configuration:","modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithParentViewController:parentView:delegate:configuration:"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewControllerDelegate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}],"title":"SBSDKBarcodeScanAndCountViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontrollerdelegate","abstract":[{"text":"A delegate protocol to handle the barcode results from ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController","isActive":true},{"type":"text","text":"."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewController":{"title":"SBSDKBarcodeScanAndCountViewController","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontroller","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to show a camera screen with the barcode scanner.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Screen also shows snap, scan more and reset buttons."},{"type":"text","text":" "},{"text":"The snap button starts the scanning when tapped.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The snap button resets the scanning when tapped again."},{"type":"text","text":" "},{"text":"Instead it is installing itself as a child view controller onto a given parent view controller.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewController/init(parentViewController:parentView:configuration:delegate:)":{"title":"init(parentViewController:parentView:configuration:delegate:)","navigatorTitle":[{"text":"initWithParentViewController:parentView:delegate:configuration:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"parentViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"parentView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerConfiguration","text":"SBSDKBarcodeScannerConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKBarcodeScanAndCountViewControllerDelegate","text":"SBSDKBarcodeScanAndCountViewControllerDelegate"},{"kind":"text","text":"?)"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontroller\/init(parentviewcontroller:parentview:configuration:delegate:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController\/init(parentViewController:parentView:configuration:delegate:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for the barcode scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration","navigatorTitle":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration","title":"SBSDKBarcodeScannerConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithParentViewController:parentView:delegate:configuration:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithParentViewController:parentView:delegate:configuration:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithParentViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"parentViewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"parentView:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"parentView"},{"kind":"text","text":" "},{"text":"delegate:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKBarcodeScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKBarcodeScanAndCountViewControllerDelegate","text":"id<SBSDKBarcodeScanAndCountViewControllerDelegate>"},{"kind":"text","text":") "},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"parentViewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller the newly created instance is embedded into."}]}]},{"name":"parentView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view the newly created instance is embedded into."}]}]},{"name":"configuration","content":[{"inlineContent":[{"text":"The receivers configuration.","type":"text"}],"type":"paragraph"}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate for the receiver."}]}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate\/title","value":"SBSDKBarcodeScanAndCountViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/title","op":"replace","value":"SBSDKBarcodeScanAndCountViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/fragments","value":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}]},{"value":"initWithParentViewController:parentView:delegate:configuration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController~1init(parentViewController:parentView:configuration:delegate:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController~1init(parentViewController:parentView:configuration:delegate:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithParentViewController:parentView:delegate:configuration:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/title","value":"SBSDKBarcodeScannerConfiguration"},{"op":"replace","value":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}