{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/fromJsonWithJson:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/fromjsonwithjson:"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates","text":"SBSDKUI2CreditCardScannerGuidanceStates","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerGuidanceStates","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"metadata":{"role":"symbol","roleHeading":"Type Method","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"title":"fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerGuidanceStates(cm)fromJsonWithJson:"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates/fromJsonWithJson:":{"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/fromjsonwithjson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/fromJsonWithJson:","title":"fromJsonWithJson:","role":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerGuidanceStates"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates","abstract":[{"type":"text","text":"Configure the captions of the user guidance hints for different scanning states."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerGuidanceStates"}],"title":"SBSDKUI2CreditCardScannerGuidanceStates","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates\/title","value":"SBSDKUI2CreditCardScannerGuidanceStates","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates\/fragments","value":[{"text":"SBSDKUI2CreditCardScannerGuidanceStates","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerGuidanceStates"}],"op":"replace"}]}]}