{"schemaVersion":{"patch":0,"minor":3,"major":0},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2CroppingViewController instead."}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"cancelButtonAccessibilityLabel","navigatorTitle":[{"kind":"identifier","text":"cancelButtonAccessibilityLabel"}],"platforms":[],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenAccessibilityConfiguration(py)cancelButtonAccessibilityLabel","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelButtonAccessibilityLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/cancelButtonAccessibilityLabel","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelButtonAccessibilityLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to “Cancel”."}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/cancelbuttonaccessibilitylabel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/cancelbuttonaccessibilitylabel"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Text, that is used as an accessibility label for the cancel button."}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenAccessibilityConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingScreenAccessibilityConfiguration"}],"title":"SBSDKUICroppingScreenAccessibilityConfiguration","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration for the accessibility labels and hints."}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICroppingScreenAccessibilityConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenAccessibilityConfiguration/cancelButtonAccessibilityLabel":{"abstract":[{"type":"text","text":"Text, that is used as an accessibility label for the cancel button."}],"kind":"symbol","title":"cancelButtonAccessibilityLabel","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelButtonAccessibilityLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"deprecated":true,"type":"topic","navigatorTitle":[{"text":"cancelButtonAccessibilityLabel","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/cancelButtonAccessibilityLabel","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/cancelbuttonaccessibilitylabel"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"cancelButtonAccessibilityLabel","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"cancelButtonAccessibilityLabel","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cancelButtonAccessibilityLabel"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUICroppingScreenAccessibilityConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUICroppingScreenAccessibilityConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUICroppingScreenAccessibilityConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration\/navigatorTitle","op":"replace"},{"value":"cancelButtonAccessibilityLabel","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1cancelButtonAccessibilityLabel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"cancelButtonAccessibilityLabel"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1cancelButtonAccessibilityLabel\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}