{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatAztecConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformataztecconfiguration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatAztecConfiguration\/hash"},"metadata":{"title":"hash","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatAztecConfiguration(py)hash","fragments":[{"text":"hash","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatAztecConfiguration/hash":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatAztecConfiguration\/hash","title":"hash","fragments":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformataztecconfiguration\/hash","type":"topic","abstract":[],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatAztecConfiguration":{"abstract":[{"type":"text","text":"Aztec configuration. Add to scanner configuration to scan Aztec codes."}],"type":"topic","title":"SBSDKBarcodeFormatAztecConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformataztecconfiguration","navigatorTitle":[{"text":"SBSDKBarcodeFormatAztecConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatAztecConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeFormatAztecConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatAztecConfiguration\/title","value":"SBSDKBarcodeFormatAztecConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatAztecConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatAztecConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatAztecConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatAztecConfiguration\/navigatorTitle","op":"replace"}]}]}