{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2acknowledgementbottombar\/fromjsonwithjson:"]}],"metadata":{"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"symbolKind":"method","title":"fromJsonWithJson:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar(cm)fromJsonWithJson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2AcknowledgementBottomBar","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar\/fromJsonWithJson:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementBottomBar":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"identifier"}],"title":"SBSDKUI2AcknowledgementBottomBar","navigatorTitle":[{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementbottombar","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the bottom bar for the acknowledgement screen."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementBottomBar/fromJsonWithJson:":{"type":"topic","title":"fromJsonWithJson:","abstract":[],"role":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementbottombar\/fromjsonwithjson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar\/fromJsonWithJson:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementBottomBar\/title","value":"SBSDKUI2AcknowledgementBottomBar"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementBottomBar\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementBottomBar"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementBottomBar\/navigatorTitle","value":[{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"identifier"}]}]}]}