{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingView","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingView\/View-Implementations"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.disableAutocorrection(_:)"},{"type":"text","text":"."}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingView\/disableAutocorrection(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disableAutocorrection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"disable","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"},{"text":"\n","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingview\/disableautocorrection(_:)"]}],"metadata":{"platforms":[{"renamed":"autocorrectionDisabled(_:)","name":"iOS","beta":false,"deprecatedAt":"100000.0","unavailable":false,"deprecated":false,"introducedAt":"13.0"},{"renamed":"autocorrectionDisabled(_:)","name":"iPadOS","beta":false,"deprecatedAt":"100000.0","unavailable":false,"deprecated":false,"introducedAt":"13.0"},{"renamed":"autocorrectionDisabled(_:)","name":"Mac Catalyst","beta":false,"deprecatedAt":"100000.0","unavailable":false,"deprecated":false,"introducedAt":"13.0"},{"renamed":"autocorrectionDisabled(_:)","name":"macOS","beta":false,"deprecatedAt":"100000.0","unavailable":false,"deprecated":false,"introducedAt":"10.15"},{"renamed":"autocorrectionDisabled(_:)","name":"tvOS","beta":false,"deprecatedAt":"100000.0","unavailable":false,"deprecated":false,"introducedAt":"13.0"},{"renamed":"autocorrectionDisabled(_:)","name":"visionOS","beta":false,"deprecatedAt":"100000.0","unavailable":false,"deprecated":false,"introducedAt":"1.0"},{"renamed":"autocorrectionDisabled(_:)","name":"watchOS","beta":false,"deprecatedAt":"100000.0","unavailable":false,"deprecated":false,"introducedAt":"8.0"}],"extendedModule":"SwiftUICore","title":"disableAutocorrection(_:)","roleHeading":"Instance Method","role":"symbol","modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"method","externalID":"s:7SwiftUI4ViewPAAE21disableAutocorrectionyQrSbSgF::SYNTHESIZED::s:25ScanbotDocumentScannerSDK20SBSDKUI2CroppingViewV","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableAutocorrection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingView/View-Implementations":{"title":"View Implementations","abstract":[],"role":"collectionGroup","kind":"article","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingview\/view-implementations","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingView\/View-Implementations","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingViewController":{"title":"SBSDKUI2CroppingViewController","abstract":[{"type":"text","text":"A highly customizable view controller to edit the page polygon or the page orientation."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingviewcontroller","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CroppingViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingViewController"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingView":{"title":"SBSDKUI2CroppingView","abstract":[{"type":"text","text":"The SwiftUI wrapper for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingViewController"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingview","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingView","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CroppingView"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingView"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingView/disableAutocorrection(_:)":{"deprecated":true,"title":"disableAutocorrection(_:)","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingview\/disableautocorrection(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableAutocorrection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingView\/disableAutocorrection(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController\/title","value":"SBSDKUI2CroppingViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController\/fragments","value":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CroppingViewController"}]}]}]}