{"sections":[],"abstract":[{"text":"Configuration of timeouts.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerScreenConfiguration\/timeouts"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerScreenConfiguration(py)timeouts","title":"timeouts","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeouts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Timeouts","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Timeouts"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"timeouts"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerscreenconfiguration\/timeouts"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerscreenconfiguration\/timeouts"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeouts","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Timeouts","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Timeouts","kind":"typeIdentifier","text":"SBSDKUI2Timeouts"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerScreenConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerScreenConfiguration":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerScreenConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeScannerScreenConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerScreenConfiguration","kind":"identifier"}],"role":"symbol","title":"SBSDKUI2BarcodeScannerScreenConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerscreenconfiguration","abstract":[{"type":"text","text":"Configuration of the barcode scanner screen."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Timeouts":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2timeouts","navigatorTitle":[{"text":"SBSDKUI2Timeouts","kind":"identifier"}],"title":"SBSDKUI2Timeouts","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2Timeouts"}],"abstract":[{"type":"text","text":"Configuration of timeouts."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Timeouts"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerScreenConfiguration/timeouts":{"title":"timeouts","role":"symbol","navigatorTitle":[{"text":"timeouts","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerScreenConfiguration\/timeouts","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"timeouts","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Timeouts","kind":"typeIdentifier","text":"SBSDKUI2Timeouts"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration of timeouts."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerscreenconfiguration\/timeouts","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"timeouts","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"timeouts","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Timeouts","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Timeouts","kind":"typeIdentifier","text":"SBSDKUI2Timeouts"},{"text":" * ","kind":"text"},{"text":"timeouts","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"SBSDKUI2BarcodeScannerScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerScreenConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerScreenConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerScreenConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerScreenConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2BarcodeScannerScreenConfiguration","kind":"identifier"}]},{"value":"SBSDKUI2Timeouts","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Timeouts\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Timeouts\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Timeouts"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Timeouts\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Timeouts"}],"op":"replace"},{"value":"timeouts","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerScreenConfiguration~1timeouts\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerScreenConfiguration~1timeouts\/fragments","value":[{"kind":"identifier","text":"timeouts"}],"op":"replace"}]}]}