{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSessionObserving"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession","text":"SBSDKCameraSession","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCameraSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didToggleTorchlight","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"enabled","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The camera session that toggled the torch light.","type":"text"}]}],"name":"session"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Whether the light was turned on or off.","type":"text"}]}],"name":"enabled"}]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Informs the observer that the torch light has been toggled on or off."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasessionobserving\/camerasession(_:didtoggletorchlight:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasessionobserving\/camerasession(_:didtoggletorchlight:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSessionObserving\/cameraSession(_:didToggleTorchlight:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraSession","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCameraSession","text":"SBSDKCameraSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didToggleTorchlight","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"cameraSession:didToggleTorchlight:","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"cameraSession(_:didToggleTorchlight:)","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKCameraSessionObserving(im)cameraSession:didToggleTorchlight:","symbolKind":"method","roleHeading":"Instance Method"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession","abstract":[{"text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the","type":"text"},{"text":" ","type":"text"},{"text":"camera device and the preview layer. Provides functionality to capture still images.","type":"text"}],"title":"SBSDKCameraSession","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSession"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSession"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSessionObserving":{"role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraSessionObserving","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCameraSessionObserving","kind":"identifier"}],"kind":"symbol","title":"SBSDKCameraSessionObserving","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSessionObserving","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasessionobserving","abstract":[{"type":"text","text":"A multicast-observer protocol that informs its observers about state changes of a camera session."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSessionObserving/cameraSession(_:didToggleTorchlight:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cameraSession:didToggleTorchlight:"}],"title":"cameraSession(_:didToggleTorchlight:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasessionobserving\/camerasession(_:didtoggletorchlight:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKCameraSession","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCameraSession"},{"text":", ","kind":"text"},{"text":"didToggleTorchlight","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSessionObserving\/cameraSession(_:didToggleTorchlight:)","abstract":[{"type":"text","text":"Informs the observer that the torch light has been toggled on or off."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"cameraSession:didToggleTorchlight:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"cameraSession:didToggleTorchlight:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"cameraSession:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKCameraSession","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCameraSession"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"session"},{"kind":"text","text":" "},{"kind":"identifier","text":"didToggleTorchlight:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"session","content":[{"inlineContent":[{"type":"text","text":"The camera session that toggled the torch light."}],"type":"paragraph"}]},{"name":"enabled","content":[{"inlineContent":[{"type":"text","text":"Whether the light was turned on or off."}],"type":"paragraph"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/title","op":"replace","value":"SBSDKCameraSession"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/fragments","op":"replace","value":[{"text":"SBSDKCameraSession","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraSession"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSessionObserving\/title","op":"replace","value":"SBSDKCameraSessionObserving"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSessionObserving\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraSessionObserving"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSessionObserving\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCameraSessionObserving","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSessionObserving~1cameraSession(_:didToggleTorchlight:)\/title","op":"replace","value":"cameraSession:didToggleTorchlight:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSessionObserving~1cameraSession(_:didToggleTorchlight:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"cameraSession:didToggleTorchlight:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}