{"abstract":[{"text":"Enables or disables crop functionality.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCropEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Defaults to "},{"code":"True","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreenbehaviorconfiguration\/iscropenabled"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreenbehaviorconfiguration\/iscropenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenBehaviorConfiguration\/isCropEnabled"},"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2CroppingViewController instead.","type":"text"}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenBehaviorConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"platforms":[],"role":"symbol","roleHeading":"Instance Property","title":"isCropEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isCropEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isCropEnabled","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenBehaviorConfiguration(py)isCropEnabled"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenBehaviorConfiguration":{"title":"SBSDKUICroppingScreenBehaviorConfiguration","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenbehaviorconfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUICroppingScreenBehaviorConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for the behavior of the cropping screen."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingScreenBehaviorConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenBehaviorConfiguration","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenBehaviorConfiguration/isCropEnabled":{"navigatorTitle":[{"kind":"identifier","text":"isCropEnabled"}],"deprecated":true,"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenbehaviorconfiguration\/iscropenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isCropEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenBehaviorConfiguration\/isCropEnabled","title":"isCropEnabled","type":"topic","abstract":[{"type":"text","text":"Enables or disables crop functionality."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"isCropEnabled","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"isCropEnabled","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isCropEnabled"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"SBSDKUICroppingScreenBehaviorConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenBehaviorConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenBehaviorConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUICroppingScreenBehaviorConfiguration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenBehaviorConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUICroppingScreenBehaviorConfiguration"}]},{"value":"isCropEnabled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenBehaviorConfiguration~1isCropEnabled\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenBehaviorConfiguration~1isCropEnabled\/fragments","value":[{"text":"isCropEnabled","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}