{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPermissionScreen\/closeButton","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"closeButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"}]}]}],"metadata":{"symbolKind":"property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CameraPermissionScreen(py)closeButton","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"closeButton"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"closeButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"}],"title":"closeButton","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol"},"abstract":[{"text":"Configuration of the camera permission request’s close button.","type":"text"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPermissionScreen"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerapermissionscreen\/closebutton"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerapermissionscreen\/closebutton"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraPermissionScreen":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerapermissionscreen","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the camera permission request view."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPermissionScreen","role":"symbol","title":"SBSDKUI2CameraPermissionScreen"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraPermissionScreen/closeButton":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerapermissionscreen\/closebutton","type":"topic","navigatorTitle":[{"kind":"identifier","text":"closeButton"}],"abstract":[{"type":"text","text":"Configuration of the camera permission request’s close button."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeButton"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration"}],"kind":"symbol","title":"closeButton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPermissionScreen\/closeButton"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ButtonConfiguration":{"type":"topic","title":"SBSDKUI2ButtonConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2buttonconfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","navigatorTitle":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the button."}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","abstract":[{"text":"Version: 8.0.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"closeButton","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"closeButton"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"closeButton"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUI2CameraPermissionScreen","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPermissionScreen\/title"},{"op":"replace","value":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPermissionScreen\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPermissionScreen\/navigatorTitle"},{"op":"replace","value":"closeButton","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPermissionScreen~1closeButton\/title"},{"op":"replace","value":[{"text":"closeButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPermissionScreen~1closeButton\/fragments"},{"op":"replace","value":"SBSDKUI2ButtonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ButtonConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ButtonConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle"}]}]}