{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiffasync(from:imagedecrypter:tofile:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiffasync(from:imagedecrypter:tofile:)"]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(from:imageDecrypter:toFile:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Asynchronously converts the images at the given image URLs to a multipage-TIFF file and writes it to the specified URL."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"writeTIFFAsync"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"imageURLs"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"imageDecrypter"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCrypting","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"toFile","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"fileURL","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"imageURLs","content":[{"inlineContent":[{"type":"text","text":"The array of image URLs to write into the multipage-TIFF."}],"type":"paragraph"}]},{"name":"imageDecrypter","content":[{"type":"paragraph","inlineContent":[{"text":"The decrypter used to decrypt the image data.","type":"text"}]}]},{"name":"fileURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The file URL to save the TIFF file at."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The URL the TIFF file has been written to or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the operation failed.","type":"text"}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"In Swift language it is used with structured concurrency (async\/await).","type":"text"}]}]}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"writeTIFFAsyncFrom:imageDecrypter:toFile:completionHandler:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"writeTIFFAsync"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"imageDecrypter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"toFile"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"writeTIFFAsync(from:imageDecrypter:toFile:)","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFImageWriter(im)writeTIFFAsyncFrom:imageDecrypter:toFile:completionHandler:","role":"symbol","symbolKind":"method"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.2.0","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCrypting":{"navigatorTitle":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Protocol for implementing encryption and decryption of (streamed) data.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecrypting","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCrypting","title":"SBSDKStorageCrypting","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"abstract":[{"text":"A class that converts images to (multipage) TIFF images.","type":"text"},{"text":" ","type":"text"},{"text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc.","type":"text"},{"text":" ","type":"text"},{"text":"When passing an encrypter the generated TIFF images will be encrypted.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter","navigatorTitle":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"type":"topic","title":"SBSDKTIFFImageWriter","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/writeTIFFAsync(from:imageDecrypter:toFile:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiffasync(from:imagedecrypter:tofile:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(from:imageDecrypter:toFile:)","kind":"symbol","title":"writeTIFFAsync(from:imageDecrypter:toFile:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"writeTIFFAsyncFrom:imageDecrypter:toFile:completionHandler:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"writeTIFFAsync"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"imageDecrypter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"toFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Asynchronously converts the images at the given image URLs to a multipage-TIFF file and writes it to the specified URL."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"writeTIFFAsyncFrom:imageDecrypter:toFile:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"writeTIFFAsyncFrom:imageDecrypter:toFile:completionHandler:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"writeTIFFAsyncFrom:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSURL *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"imageURLs"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageDecrypter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","text":"id<SBSDKStorageCrypting>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"imageDecrypter"},{"kind":"text","text":" "},{"kind":"identifier","text":"toFile:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fileURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"imageURLs","content":[{"type":"paragraph","inlineContent":[{"text":"The array of image URLs to write into the multipage-TIFF.","type":"text"}]}]},{"name":"imageDecrypter","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The decrypter used to decrypt the image data."}]}]},{"name":"fileURL","content":[{"type":"paragraph","inlineContent":[{"text":"The file URL to save the TIFF file at.","type":"text"}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/primaryContentSections\/2","value":null},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/title","value":"SBSDKStorageCrypting"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/fragments","value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/navigatorTitle","value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/title","value":"SBSDKTIFFImageWriter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/fragments","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriter"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriter"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(from:imageDecrypter:toFile:)\/title","value":"writeTIFFAsyncFrom:imageDecrypter:toFile:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(from:imageDecrypter:toFile:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"writeTIFFAsyncFrom:imageDecrypter:toFile:completionHandler:","kind":"identifier"}]}]}]}