{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiffasync(scanneddocument:tofile:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiffasync(scanneddocument:tofile:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"writeTIFFAsync","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"scannedDocument"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedDocument","text":"SBSDKScannedDocument","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"toFile"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fileURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"? = nil) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"scannedDocument","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The scanned document to convert to a TIFF file."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The file URL to save the TIFF file at. If ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":"the default TIFF location of the scanned document will be used."}]}],"name":"fileURL"}]},{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"The URL the TIFF file has been written to or "},{"code":"nil","type":"codeVoice"},{"text":" if the operation failed.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In Swift language it is used with structured concurrency (async\/await)."}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter"]]},"abstract":[{"text":"Asynchronously converts the scanned document to a multipage-TIFF file and writes it to the specified URL.","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"writeTIFFAsyncWithScannedDocument:toFile:completionHandler:"}],"roleHeading":"Instance Method","title":"writeTIFFAsync(scannedDocument:toFile:)","symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"writeTIFFAsync"},{"kind":"text","text":"("},{"text":"scannedDocument","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedDocument","text":"SBSDKScannedDocument"},{"kind":"text","text":", "},{"text":"toFile","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFImageWriter(im)writeTIFFAsyncWithScannedDocument:toFile:completionHandler:"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(scannedDocument:toFile:)"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","url":"\/documentation\/scanbotdocumentscannersdk","abstract":[{"type":"text","text":"Version: 6.2.0"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter/writeTIFFAsync(scannedDocument:toFile:)":{"navigatorTitle":[{"text":"writeTIFFAsyncWithScannedDocument:toFile:completionHandler:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter\/writeTIFFAsync(scannedDocument:toFile:)","role":"symbol","kind":"symbol","title":"writeTIFFAsync(scannedDocument:toFile:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"writeTIFFAsync","kind":"identifier"},{"kind":"text","text":"("},{"text":"scannedDocument","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedDocument","text":"SBSDKScannedDocument","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"toFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter\/writetiffasync(scanneddocument:tofile:)","abstract":[{"text":"Asynchronously converts the scanned document to a multipage-TIFF file and writes it to the specified URL.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriter":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriter","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriter","title":"SBSDKTIFFImageWriter","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A class that converts images to (multipage) TIFF images."},{"type":"text","text":" "},{"type":"text","text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc."},{"type":"text","text":" "},{"type":"text","text":"When passing an encrypter the generated TIFF images will be encrypted."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedDocument":{"abstract":[{"type":"text","text":"An automatically persisted, thread-safe and observable document-page model for a document with multiple scanned pages."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKScannedDocument"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedDocument","title":"SBSDKScannedDocument","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanneddocument","navigatorTitle":[{"text":"SBSDKScannedDocument","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"writeTIFFAsyncWithScannedDocument:toFile:completionHandler:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"writeTIFFAsyncWithScannedDocument:toFile:completionHandler:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"writeTIFFAsyncWithScannedDocument:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedDocument","text":"SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedDocument","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"scannedDocument","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toFile:"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fileURL"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"scannedDocument","content":[{"type":"paragraph","inlineContent":[{"text":"The scanned document to convert to a TIFF file.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"The file URL to save the TIFF file at. If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":"the default TIFF location of the scanned document will be used.","type":"text"}],"type":"paragraph"}],"name":"fileURL"}]}},{"value":null,"path":"\/primaryContentSections\/2","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(scannedDocument:toFile:)\/title","value":"writeTIFFAsyncWithScannedDocument:toFile:completionHandler:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter~1writeTIFFAsync(scannedDocument:toFile:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"writeTIFFAsyncWithScannedDocument:toFile:completionHandler:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/title","value":"SBSDKTIFFImageWriter","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/fragments","value":[{"text":"SBSDKTIFFImageWriter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriter"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedDocument\/title","value":"SBSDKScannedDocument"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedDocument\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKScannedDocument"}]},{"value":[{"kind":"identifier","text":"SBSDKScannedDocument"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedDocument\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}