{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationConfiguration\/removeUnconnectedResults"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationConfiguration"]]},"kind":"symbol","abstract":[{"text":"If true, the results from previous frames that are not connected to results on the current frame will be removed.","type":"text"},{"text":" ","type":"text"},{"text":"This is should be enabled when large camera movements are expected.","type":"text"},{"text":" ","type":"text"},{"text":"For small camera movements, the option can be disabled.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationconfiguration\/removeunconnectedresults"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationconfiguration\/removeunconnectedresults"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeUnconnectedResults","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is true"}]}]}],"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"removeUnconnectedResults"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeUnconnectedResults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeAccumulationConfiguration(py)removeUnconnectedResults","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"removeUnconnectedResults"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAccumulationConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationConfiguration","title":"SBSDKBarcodeAccumulationConfiguration","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationconfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration for how to accumulate results."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeAccumulationConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAccumulationConfiguration/removeUnconnectedResults":{"type":"topic","navigatorTitle":[{"text":"removeUnconnectedResults","kind":"identifier"}],"title":"removeUnconnectedResults","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationConfiguration\/removeUnconnectedResults","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationconfiguration\/removeunconnectedresults","kind":"symbol","abstract":[{"text":"If true, the results from previous frames that are not connected to results on the current frame will be removed.","type":"text"},{"text":" ","type":"text"},{"text":"This is should be enabled when large camera movements are expected.","type":"text"},{"text":" ","type":"text"},{"text":"For small camera movements, the option can be disabled.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeUnconnectedResults","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"removeUnconnectedResults","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"removeUnconnectedResults","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeUnconnectedResults"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKBarcodeAccumulationConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationConfiguration\/navigatorTitle"},{"op":"replace","value":"removeUnconnectedResults","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationConfiguration~1removeUnconnectedResults\/title"},{"op":"replace","value":[{"text":"removeUnconnectedResults","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationConfiguration~1removeUnconnectedResults\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}