{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidanceconfiguration\/tojson()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidanceconfiguration\/tojson()"]}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"toJson"}],"role":"symbol","symbolKind":"method","title":"toJson()","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration(im)toJson"},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceConfiguration\/toJson()","interfaceLanguage":"swift"},"abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2UserGuidanceConfiguration/toJson()":{"title":"toJson()","kind":"symbol","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceConfiguration\/toJson()","navigatorTitle":[{"text":"toJson","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidanceconfiguration\/tojson()","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2UserGuidanceConfiguration":{"title":"SBSDKUI2UserGuidanceConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the hint guiding users through the scanning process."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidanceconfiguration","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"toJson"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJson"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"toJson","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceConfiguration~1toJson()\/title","value":"toJson"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceConfiguration~1toJson()\/fragments","value":[{"kind":"text","text":"- "},{"text":"toJson","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceConfiguration\/title","value":"SBSDKUI2UserGuidanceConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceConfiguration\/fragments","value":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}