{"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerViewController(im)viewDidLoad","title":"viewDidLoad","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontroller\/viewdidload"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/viewDidLoad"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewController/viewDidLoad":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController\/viewDidLoad","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}],"title":"viewDidLoad","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontroller\/viewdidload"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewController":{"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to scan for license plates with the camera."}],"title":"SBSDKLicensePlateScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontroller","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","role":"symbol","navigatorTitle":[{"text":"SBSDKLicensePlateScannerViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKLicensePlateScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController\/title","op":"replace","value":"SBSDKLicensePlateScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController\/navigatorTitle","value":[{"text":"SBSDKLicensePlateScannerViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}