{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPageBinarization\/enabledIfBinarizationFilterSet","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPageBinarization"]]},"sections":[],"metadata":{"role":"symbol","title":"SBSDKPageBinarization.enabledIfBinarizationFilterSet","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageBinarizationEnabledIfBinarizationFilterSet"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabledIfBinarizationFilterSet"}],"roleHeading":"Case","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKPageBinarization@SBSDKPageBinarizationEnabledIfBinarizationFilterSet"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpagebinarization\/enabledifbinarizationfilterset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpagebinarization\/enabledifbinarizationfilterset"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabledIfBinarizationFilterSet","kind":"identifier"}]}]}],"abstract":[{"text":"Same behavior as ENABLED if a binarizationFilter is set,","type":"text"},{"text":" ","type":"text"},{"text":"otherwise same behavior as DISABLED. This is the default.","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPageBinarization/enabledIfBinarizationFilterSet":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPageBinarization\/enabledIfBinarizationFilterSet","title":"SBSDKPageBinarization.enabledIfBinarizationFilterSet","abstract":[{"type":"text","text":"Same behavior as ENABLED if a binarizationFilter is set,"},{"text":" ","type":"text"},{"text":"otherwise same behavior as DISABLED. This is the default.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabledIfBinarizationFilterSet","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPageBinarizationEnabledIfBinarizationFilterSet","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpagebinarization\/enabledifbinarizationfilterset"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPageBinarization":{"kind":"symbol","abstract":[{"type":"text","text":"Binarization behavior to apply when adding a page to a PDF\/TIFF."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKPageBinarization","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpagebinarization","type":"topic","title":"SBSDKPageBinarization","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageBinarization","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPageBinarization"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKPageBinarizationEnabledIfBinarizationFilterSet","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKPageBinarizationEnabledIfBinarizationFilterSet"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKPageBinarizationEnabledIfBinarizationFilterSet","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPageBinarization~1enabledIfBinarizationFilterSet\/title","value":"SBSDKPageBinarizationEnabledIfBinarizationFilterSet","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPageBinarization~1enabledIfBinarizationFilterSet\/fragments","value":[{"text":"SBSDKPageBinarizationEnabledIfBinarizationFilterSet","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPageBinarization\/title","value":"SBSDKPageBinarization","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPageBinarization\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPageBinarization"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPageBinarization\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPageBinarization"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}