{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfiler\/diff(firstSnapshot:secondSnapshot:)"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diff","kind":"identifier"},{"text":"(","kind":"text"},{"text":"firstSnapshot","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot","text":"SBSDKImageRefPoolSnapshot","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshot","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"secondSnapshot","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshot","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshot","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshotsDiff","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshotsDiff","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshotsDiff","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"firstSnapshot","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Snapshot that was taken earlier"}]}]},{"name":"secondSnapshot","content":[{"inlineContent":[{"text":"Snapshot that was taken later","type":"text"}],"type":"paragraph"}]}]},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Difference between two snapshots"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfiler"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Computes difference between two snapshots. To confirm that a particular operation doesn’t leak, take a snapshot"},{"type":"text","text":" "},{"type":"text","text":"before and after the operation, and check that the diff doesn’t contain any unexpected new ImageRefs."}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofiler\/diff(firstsnapshot:secondsnapshot:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofiler\/diff(firstsnapshot:secondsnapshot:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Type Method","title":"diff(firstSnapshot:secondSnapshot:)","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefProfiler(cm)diffWithFirstSnapshot:secondSnapshot:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diff","kind":"identifier"},{"text":"(","kind":"text"},{"text":"firstSnapshot","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshot","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot"},{"text":", ","kind":"text"},{"text":"secondSnapshot","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshot","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot"},{"text":") -> ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshotsDiff","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshotsDiff"}],"navigatorTitle":[{"kind":"identifier","text":"diffWithFirstSnapshot:secondSnapshot:"}],"symbolKind":"method","role":"symbol"},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefPoolSnapshot":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshot","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefpoolsnapshot","abstract":[{"type":"text","text":"Snapshot of all alive ImageRefs."}],"kind":"symbol","title":"SBSDKImageRefPoolSnapshot","role":"symbol","navigatorTitle":[{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefPoolSnapshotsDiff":{"abstract":[{"text":"difference between two snapshots.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefpoolsnapshotsdiff","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshotsDiff","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshotsDiff","navigatorTitle":[{"text":"SBSDKImageRefPoolSnapshotsDiff","kind":"identifier"}],"title":"SBSDKImageRefPoolSnapshotsDiff"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefProfiler":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofiler","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfiler","abstract":[{"type":"text","text":"ImageRef memory profiler."}],"navigatorTitle":[{"text":"SBSDKImageRefProfiler","kind":"identifier"}],"title":"SBSDKImageRefProfiler","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRefProfiler","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefProfiler/diff(firstSnapshot:secondSnapshot:)":{"abstract":[{"text":"Computes difference between two snapshots. To confirm that a particular operation doesn’t leak, take a snapshot","type":"text"},{"text":" ","type":"text"},{"text":"before and after the operation, and check that the diff doesn’t contain any unexpected new ImageRefs.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofiler\/diff(firstsnapshot:secondsnapshot:)","type":"topic","title":"diff(firstSnapshot:secondSnapshot:)","kind":"symbol","navigatorTitle":[{"text":"diffWithFirstSnapshot:secondSnapshot:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfiler\/diff(firstSnapshot:secondSnapshot:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diff","kind":"identifier"},{"text":"(","kind":"text"},{"text":"firstSnapshot","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshot","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"secondSnapshot","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshot","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshotsDiff","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshotsDiff","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"diffWithFirstSnapshot:secondSnapshot:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"diffWithFirstSnapshot:secondSnapshot:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshotsDiff","text":"SBSDKImageRefPoolSnapshotsDiff","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshotsDiff"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"diffWithFirstSnapshot:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot","text":"SBSDKImageRefPoolSnapshot","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshot"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"firstSnapshot"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondSnapshot:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshot","kind":"typeIdentifier","text":"SBSDKImageRefPoolSnapshot"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"secondSnapshot"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"firstSnapshot","content":[{"inlineContent":[{"type":"text","text":"Snapshot that was taken earlier"}],"type":"paragraph"}]},{"name":"secondSnapshot","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Snapshot that was taken later"}]}]}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"Difference between two snapshots"}],"type":"paragraph"}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefPoolSnapshot\/title","op":"replace","value":"SBSDKImageRefPoolSnapshot"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefPoolSnapshot\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefPoolSnapshot\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefPoolSnapshotsDiff\/title","op":"replace","value":"SBSDKImageRefPoolSnapshotsDiff"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefPoolSnapshotsDiff\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshotsDiff"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefPoolSnapshotsDiff\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageRefPoolSnapshotsDiff","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfiler\/title","op":"replace","value":"SBSDKImageRefProfiler"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfiler\/fragments","op":"replace","value":[{"text":"SBSDKImageRefProfiler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfiler\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRefProfiler"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfiler~1diff(firstSnapshot:secondSnapshot:)\/title","op":"replace","value":"diffWithFirstSnapshot:secondSnapshot:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfiler~1diff(firstSnapshot:secondSnapshot:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"diffWithFirstSnapshot:secondSnapshot:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}