{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithLabel:imageName:capturedImageName:refreshOnEachFrame:) ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"label","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"imageName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"capturedImageName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"refreshOnEachFrame","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"label","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The label to describe the mock data."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The case-sensitive name of the image resource in the application bundle that provides the simulated frames.","type":"text"}]}],"name":"imageName"},{"name":"capturedImageName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The case-sensitive name of the  image resource in the application bundle that is used when capturing still images. If ‘nil’ the current frame of the "},{"type":"codeVoice","code":"imageName"},{"text":" is returned when capturing a still image.","type":"text"}]}]},{"name":"refreshOnEachFrame","content":[{"type":"paragraph","inlineContent":[{"text":"If set to ","type":"text"},{"code":"True","type":"codeVoice"},{"text":" the image is reloaded\/downloaded after each frame. Otherwise the image is loaded only once and reused per frame.","type":"text"}]}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageName:capturedImageName:refreshOnEachFrame:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes mock data for a simulated camera device from ressource names of the application bundle."}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata\/init(label:imagename:capturedimagename:refreshoneachframe:)"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata\/init(label:imagename:capturedimagename:refreshoneachframe:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData"]]},"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","kind":"identifier"}],"roleHeading":"Initializer","role":"symbol","title":"init(label:imageName:capturedImageName:refreshOnEachFrame:)","symbolKind":"init","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKSimulatedCameraMockData(im)initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"label"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"capturedImageName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"refreshOnEachFrame"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSimulatedCameraMockData/init(label:imageName:capturedImageName:refreshOnEachFrame:)":{"title":"init(label:imageName:capturedImageName:refreshOnEachFrame:)","navigatorTitle":[{"text":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata\/init(label:imagename:capturedimagename:refreshoneachframe:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageName:capturedImageName:refreshOnEachFrame:)","role":"symbol","type":"topic","abstract":[{"text":"Initializes mock data for a simulated camera device from ressource names of the application bundle.","type":"text"}],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"label"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"imageName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"capturedImageName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"refreshOnEachFrame","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","kind":"symbol","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSimulatedCameraMockData":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData","navigatorTitle":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"abstract":[{"text":"A class to describe the mocking data that is fed to a simulated camera device.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata","type":"topic","title":"SBSDKSimulatedCameraMockData","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithLabel:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"label","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageName:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"imageName","kind":"internalParam"},{"kind":"text","text":" "},{"text":"capturedImageName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"capturedImageName","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshOnEachFrame:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"refreshOnEachFrame","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The label to describe the mock data."}],"type":"paragraph"}],"name":"label"},{"name":"imageName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The case-sensitive name of the image resource in the application bundle that provides the simulated frames."}]}]},{"name":"capturedImageName","content":[{"inlineContent":[{"text":"The case-sensitive name of the  image resource in the application bundle that is used when capturing still images. If ‘nil’ the current frame of the ","type":"text"},{"type":"codeVoice","code":"imageName"},{"type":"text","text":" is returned when capturing a still image."}],"type":"paragraph"}]},{"name":"refreshOnEachFrame","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"True"},{"text":" the image is reloaded\/downloaded after each frame. Otherwise the image is loaded only once and reused per frame.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData~1init(label:imageName:capturedImageName:refreshOnEachFrame:)\/title","op":"replace","value":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithLabel:imageName:capturedImageName:refreshOnEachFrame:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData~1init(label:imageName:capturedImageName:refreshOnEachFrame:)\/fragments","op":"replace"},{"op":"replace","value":"SBSDKSimulatedCameraMockData","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData\/fragments","value":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData\/navigatorTitle","op":"replace"}]}]}