{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration\/notifyPropertiesChange()","interfaceLanguage":"swift"},"abstract":[{"text":"Notifies that properties have changed by incrementing the update counter.","type":"text"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration(im)notifyPropertiesChange","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyPropertiesChange"},{"kind":"text","text":"()"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","title":"notifyPropertiesChange()","navigatorTitle":[{"kind":"identifier","text":"notifyPropertiesChange"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notifyPropertiesChange","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration\/notifypropertieschange()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration\/notifypropertieschange()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerEnergyConfiguration/notifyPropertiesChange()":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"notifyPropertiesChange","kind":"identifier"}],"abstract":[{"text":"Notifies that properties have changed by incrementing the update counter.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration\/notifyPropertiesChange()","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration\/notifypropertieschange()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notifyPropertiesChange","kind":"identifier"},{"text":"()","kind":"text"}],"title":"notifyPropertiesChange()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerEnergyConfiguration":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The energy management configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"type":"text","text":" "},{"type":"text","text":"‘SBSDKBaseScannerViewController’ and subclasses sport a customizable energy management system."},{"type":"text","text":" "},{"type":"text","text":"Since scanners running on a live video feed can put a lot of load onto the CPU and\/or GPU"},{"type":"text","text":" "},{"type":"text","text":"of the device, causing the battery to drain quickly and running the device hot, you can customize the energy"},{"type":"text","text":" "},{"type":"text","text":"consumption using this class by configuring the rate of detections\/recognitions per second in performance mode as"},{"type":"text","text":" "},{"type":"text","text":"well as in energy saving mode."},{"text":" ","type":"text"},{"text":"In performance mode the scanners will be fed with a higher, configurable rate of","type":"text"},{"text":" ","type":"text"},{"text":"video frames per second.","type":"text"},{"text":" ","type":"text"},{"text":"After a certain, configurable period of inactivity the energy save mode will be engaged and the rate","type":"text"},{"text":" ","type":"text"},{"text":"of scans will be reduced to a lower (configurable) rate.","type":"text"},{"text":" ","type":"text"},{"text":"You can also configure the time of inactivity before the automatic mode switches from performance to energy save mode.","type":"text"},{"text":" ","type":"text"},{"text":"Inactivity here means that both of the following conditions are met:","type":"text"}],"title":"SBSDKBaseScannerEnergyConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"notifyPropertiesChange"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"notifyPropertiesChange","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"notifyPropertiesChange","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration~1notifyPropertiesChange()\/title","op":"replace","value":"notifyPropertiesChange"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration~1notifyPropertiesChange()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"notifyPropertiesChange"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration\/title","op":"replace","value":"SBSDKBaseScannerEnergyConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}]}]}]}