{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"blackOutliersFraction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"Default is 0.0","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgrayscalefilter\/blackoutliersfraction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgrayscalefilter\/blackoutliersfraction"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGrayscaleFilter"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGrayscaleFilter(py)blackOutliersFraction","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"blackOutliersFraction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"blackOutliersFraction","kind":"identifier"}],"title":"blackOutliersFraction"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGrayscaleFilter\/blackOutliersFraction"},"abstract":[{"type":"text","text":"Clip this fraction of the darkest pixels in operations such as autocontrast."},{"type":"text","text":" "},{"type":"text","text":"Increasing the range of middle gray levels at the expense of the brightest and darkest levels"},{"type":"text","text":" "},{"type":"text","text":"may improve the overall contrast and quality of the result."},{"type":"text","text":" "},{"type":"text","text":"Sum of blackOutliersFraction and whiteOutliersFraction must be less than 1 but usually"},{"type":"text","text":" "},{"type":"text","text":"good values for the parameters do not exceed 0.05;."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGrayscaleFilter":{"url":"\/documentation\/scanbotsdk\/sbsdkgrayscalefilter","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGrayscaleFilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGrayscaleFilter"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGrayscaleFilter"}],"kind":"symbol","abstract":[{"type":"text","text":"Converts color images to grayscale and applies autocontrast."}],"type":"topic","title":"SBSDKGrayscaleFilter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGrayscaleFilter/blackOutliersFraction":{"title":"blackOutliersFraction","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"blackOutliersFraction","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgrayscalefilter\/blackoutliersfraction","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGrayscaleFilter\/blackOutliersFraction","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"blackOutliersFraction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Clip this fraction of the darkest pixels in operations such as autocontrast."},{"type":"text","text":" "},{"type":"text","text":"Increasing the range of middle gray levels at the expense of the brightest and darkest levels"},{"type":"text","text":" "},{"type":"text","text":"may improve the overall contrast and quality of the result."},{"type":"text","text":" "},{"type":"text","text":"Sum of blackOutliersFraction and whiteOutliersFraction must be less than 1 but usually"},{"type":"text","text":" "},{"type":"text","text":"good values for the parameters do not exceed 0.05;."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"blackOutliersFraction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"blackOutliersFraction"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"blackOutliersFraction"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGrayscaleFilter\/title","value":"SBSDKGrayscaleFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGrayscaleFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKGrayscaleFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGrayscaleFilter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGrayscaleFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGrayscaleFilter~1blackOutliersFraction\/title","value":"blackOutliersFraction"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGrayscaleFilter~1blackOutliersFraction\/fragments","value":[{"kind":"identifier","text":"blackOutliersFraction"}]}]}]}