{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod11NCR","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mod11NCR","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeMSIPlesseyChecksumAlgorithm@SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11NCR","roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11NCR","kind":"identifier"}],"title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod11NCR"},"sections":[],"abstract":[{"type":"text","text":"Mod11NCR."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mod11NCR"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod11ncr"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod11ncr"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"type":"topic","abstract":[{"text":"The checksum algorithm for MSI-Plessey type barcodes.","type":"text"}],"navigatorTitle":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/mod11NCR":{"title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod11NCR","url":"\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod11ncr","role":"symbol","abstract":[{"type":"text","text":"Mod11NCR."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11NCR"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mod11NCR","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod11NCR"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11NCR"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11NCR","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11NCR"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/title","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod11NCR\/title","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11NCR"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod11NCR\/fragments","value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11NCR","kind":"identifier"}]}]}]}