{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcompositefieldvaluesemantics\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"title":"isEqual:","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCompositeFieldValueSemantics(im)isEqual:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"object","kind":"internalParam"},{"kind":"text","text":";"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompositeFieldValueSemantics\/isEqual:","interfaceLanguage":"occ"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompositeFieldValueSemantics"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCompositeFieldValueSemantics/isEqual:":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompositeFieldValueSemantics\/isEqual:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"abstract":[],"type":"topic","title":"isEqual:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/scanbotsdk\/sbsdkcompositefieldvaluesemantics\/isequal:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCompositeFieldValueSemantics":{"title":"SBSDKCompositeFieldValueSemantics","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCompositeFieldValueSemantics"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Report of a logical field value semantics verification. If some logical field, e.g. expiry date is present in"},{"type":"text","text":" "},{"text":"multiple places in the document, it can occur that some entries are semantically correct and some are semantically","type":"text"},{"type":"text","text":" "},{"text":"incorrect. This report shows the overall status of the logical field value semantics verification and details for","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"each field that was verified."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCompositeFieldValueSemantics","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompositeFieldValueSemantics","url":"\/documentation\/scanbotsdk\/sbsdkcompositefieldvaluesemantics"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"SBSDKCompositeFieldValueSemantics","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompositeFieldValueSemantics\/title"},{"value":[{"text":"SBSDKCompositeFieldValueSemantics","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompositeFieldValueSemantics\/fragments"},{"op":"replace","value":[{"text":"SBSDKCompositeFieldValueSemantics","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompositeFieldValueSemantics\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}