{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incompleteValidation","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKCheckMagneticInkStripScanningStatus.incompleteValidation","externalID":"c:@M@ScanbotSDK@E@SBSDKCheckMagneticInkStripScanningStatus@SBSDKCheckMagneticInkStripScanningStatusIncompleteValidation","navigatorTitle":[{"text":"SBSDKCheckMagneticInkStripScanningStatusIncompleteValidation","kind":"identifier"}],"role":"symbol","roleHeading":"Case"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incompleteValidation","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Magnetic ink strip was found, but validation failed, because of a format violation, an unsupported format, or an"},{"type":"text","text":" "},{"type":"text","text":"OCR error."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckMagneticInkStripScanningStatus"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckMagneticInkStripScanningStatus\/incompleteValidation","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckmagneticinkstripscanningstatus\/incompletevalidation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckmagneticinkstripscanningstatus\/incompletevalidation"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckMagneticInkStripScanningStatus/incompleteValidation":{"title":"SBSDKCheckMagneticInkStripScanningStatus.incompleteValidation","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckmagneticinkstripscanningstatus\/incompletevalidation","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incompleteValidation","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckMagneticInkStripScanningStatus\/incompleteValidation","abstract":[{"type":"text","text":"Magnetic ink strip was found, but validation failed, because of a format violation, an unsupported format, or an"},{"type":"text","text":" "},{"type":"text","text":"OCR error."}],"navigatorTitle":[{"text":"SBSDKCheckMagneticInkStripScanningStatusIncompleteValidation","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckMagneticInkStripScanningStatus":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckmagneticinkstripscanningstatus","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckMagneticInkStripScanningStatus","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCheckMagneticInkStripScanningStatus","kind":"identifier"}],"abstract":[{"text":"Check magnetic ink (MICR) strip scanning status.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckMagneticInkStripScanningStatus","type":"topic","title":"SBSDKCheckMagneticInkStripScanningStatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKCheckMagneticInkStripScanningStatusIncompleteValidation"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKCheckMagneticInkStripScanningStatusIncompleteValidation","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKCheckMagneticInkStripScanningStatusIncompleteValidation","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckMagneticInkStripScanningStatus~1incompleteValidation\/title","op":"replace","value":"SBSDKCheckMagneticInkStripScanningStatusIncompleteValidation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckMagneticInkStripScanningStatus~1incompleteValidation\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckMagneticInkStripScanningStatusIncompleteValidation"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckMagneticInkStripScanningStatus\/title","op":"replace","value":"SBSDKCheckMagneticInkStripScanningStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckMagneticInkStripScanningStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckMagneticInkStripScanningStatus"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckMagneticInkStripScanningStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckMagneticInkStripScanningStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}