{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"nonisolated"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"speechAlwaysIncludesPunctuation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true) -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"},{"kind":"text","text":"\n"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"extendedModule":"SwiftUICore","title":"speechAlwaysIncludesPunctuation(_:)","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK","relatedModules":["SwiftUICore"]}],"externalID":"s:7SwiftUI4ViewPAAE31speechAlwaysIncludesPunctuationyQrSbF::SYNTHESIZED::s:10ScanbotSDK33SBSDKUI2DocumentDataExtractorViewV","role":"symbol","platforms":[{"deprecated":false,"beta":false,"name":"iOS","introducedAt":"15.0","unavailable":false},{"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"15.0","unavailable":false},{"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"15.0","unavailable":false},{"deprecated":false,"beta":false,"name":"macOS","introducedAt":"12.0","unavailable":false},{"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"15.0","unavailable":false},{"deprecated":false,"beta":false,"name":"watchOS","introducedAt":"8.0","unavailable":false}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"speechAlwaysIncludesPunctuation","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorView\/View-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorview\/speechalwaysincludespunctuation(_:)"]}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorView\/speechAlwaysIncludesPunctuation(_:)"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"View.speechAlwaysIncludesPunctuation(_:)","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorView/speechAlwaysIncludesPunctuation(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorView\/speechAlwaysIncludesPunctuation(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"speechAlwaysIncludesPunctuation","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorview\/speechalwaysincludespunctuation(_:)","kind":"symbol","title":"speechAlwaysIncludesPunctuation(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorViewController":{"title":"SBSDKUI2DocumentDataExtractorViewController","abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to extract data from various documents."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorViewController"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorviewcontroller","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorView":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorView"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorview","title":"SBSDKUI2DocumentDataExtractorView","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorView","abstract":[{"type":"text","text":"The SwiftUI wrapper for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorViewController"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorView"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorView/View-Implementations":{"abstract":[],"type":"topic","title":"View Implementations","kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorview\/view-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorView\/View-Implementations","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2DocumentDataExtractorViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorViewController\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentDataExtractorViewController","kind":"identifier"}],"op":"replace"}]}]}