{"abstract":[{"type":"text","text":"Data element ID “DBD”. Date on which the document was issued. The format is ISO8601 with delimiters."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"documentIssueDate","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVADLID(py)documentIssueDate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentIssueDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"documentIssueDate"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"documentIssueDate","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVADLID"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvadlid\/documentissuedate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvadlid\/documentissuedate"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVADLID\/documentIssueDate","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVADLID/documentIssueDate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVADLID\/documentIssueDate","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvadlid\/documentissuedate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentIssueDate"}],"title":"documentIssueDate","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentIssueDate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"abstract":[{"text":"Data element ID “DBD”. Date on which the document was issued. The format is ISO8601 with delimiters.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"title":"SBSDKGenericDocumentField","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","navigatorTitle":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"abstract":[{"text":"A generic document field.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVADLID":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVADLID"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVADLID"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVADLID","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvadlid","role":"symbol","abstract":[{"type":"text","text":"Driver License Or ID Document."}],"title":"SBSDKBarcodeDocumentAAMVADLID"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"documentIssueDate"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"documentIssueDate","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":" * "},{"kind":"identifier","text":"documentIssueDate"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"documentIssueDate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVADLID~1documentIssueDate\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVADLID~1documentIssueDate\/fragments","value":[{"kind":"identifier","text":"documentIssueDate"}],"op":"replace"},{"value":"SBSDKGenericDocumentField","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVADLID\/title","op":"replace","value":"SBSDKBarcodeDocumentAAMVADLID"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVADLID\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVADLID"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVADLID\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVADLID"}],"op":"replace"}]}]}