{"metadata":{"modules":[{"name":"ScanbotSDK"}],"platforms":[],"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"copyCurrentConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}],"navigatorTitle":[{"text":"copyCurrentConfiguration","kind":"identifier"}],"title":"copyCurrentConfiguration()","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognizerViewController(im)copyCurrentConfiguration","roleHeading":"Instance Method"},"abstract":[{"text":"Returns a copy of the receivers current configuration.","type":"text"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Please consider using SBSDKDocumentDataExtractorViewController."}],"type":"paragraph"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"copyCurrentConfiguration"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}],"languages":["swift"]}]},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The current configuration."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerviewcontroller\/copycurrentconfiguration()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerviewcontroller\/copycurrentconfiguration()"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewController\/copyCurrentConfiguration()","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerViewController/copyCurrentConfiguration()":{"deprecated":true,"title":"copyCurrentConfiguration()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"copyCurrentConfiguration"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"copyCurrentConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewController\/copyCurrentConfiguration()","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerviewcontroller\/copycurrentconfiguration()","abstract":[{"type":"text","text":"Returns a copy of the receivers current configuration."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerViewController":{"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewController","type":"topic","title":"SBSDKHealthInsuranceCardRecognizerViewController","abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to scan health insurance cards with the camera."}],"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardRecognizerViewController","kind":"identifier"}],"deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognizerconfiguration","role":"symbol","kind":"symbol","abstract":[{"text":"Configuration for the European health insurance card (EHIC) recognizer.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}],"title":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","navigatorTitle":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"copyCurrentConfiguration","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"copyCurrentConfiguration","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"copyCurrentConfiguration"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The current configuration.","type":"text"}]}],"kind":"content"}},{"value":"copyCurrentConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewController~1copyCurrentConfiguration()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyCurrentConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewController~1copyCurrentConfiguration()\/fragments"},{"op":"replace","value":"SBSDKHealthInsuranceCardRecognizerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewController\/fragments","op":"replace","value":[{"text":"SBSDKHealthInsuranceCardRecognizerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/title","value":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}]},{"op":"replace","value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/navigatorTitle"}]}]}