{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeAccumulationConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeAccumulationConfiguration\/initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:"},"sections":[],"metadata":{"role":"symbol","title":"initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:","navigatorTitle":[{"text":"initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeAccumulationConfiguration(im)initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:","kind":"identifier"}],"symbolKind":"method"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithMinConfirmationsStandaloneEAN:"},{"kind":"text","text":"("},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minConfirmationsStandaloneEAN","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accumulationTime:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"accumulationTime","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeUnconnectedResults:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"removeUnconnectedResults","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"method:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKBarcodeAccumulationMethod","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodeAccumulationMethod","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeAccumulationMethod"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"method"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeaccumulationconfiguration\/initwithminconfirmationsstandaloneean:accumulationtime:removeunconnectedresults:method:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeAccumulationConfiguration":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeAccumulationConfiguration","title":"SBSDKBarcodeAccumulationConfiguration","type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeAccumulationConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeAccumulationConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for how to accumulate results."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeaccumulationconfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeAccumulationConfiguration/initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeAccumulationConfiguration\/initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeaccumulationconfiguration\/initwithminconfirmationsstandaloneean:accumulationtime:removeunconnectedresults:method:","abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:","kind":"identifier"}],"title":"initWithMinConfirmationsStandaloneEAN:accumulationTime:removeUnconnectedResults:method:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeAccumulationMethod":{"abstract":[{"type":"text","text":"The method how to display barcodes from previous frames."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeAccumulationMethod","kind":"identifier"}],"role":"symbol","title":"SBSDKBarcodeAccumulationMethod","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethod"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeaccumulationmethod","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeAccumulationMethod","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKBarcodeAccumulationConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAccumulationConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAccumulationConfiguration\/fragments","value":[{"text":"SBSDKBarcodeAccumulationConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAccumulationConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeAccumulationConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAccumulationMethod\/title","value":"SBSDKBarcodeAccumulationMethod","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAccumulationMethod\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeAccumulationMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAccumulationMethod\/navigatorTitle","value":[{"text":"SBSDKBarcodeAccumulationMethod","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}