{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incapableOfWorkUntil","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateDateRecordType@SBSDKMedicalCertificateDateRecordTypeIncapableOfWorkUntil","title":"SBSDKMedicalCertificateDateRecordType.incapableOfWorkUntil","role":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateDateRecordTypeIncapableOfWorkUntil","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"(Form 1) Incapable of work until (voraussichtlich arbeitsunfähig bis einschließlich oder letzter Tag der Arbeitsunfähigkeit) date.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incapableOfWorkUntil","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType\/incapableOfWorkUntil","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype\/incapableofworkuntil"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype\/incapableofworkuntil"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecordType":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordType"}],"abstract":[{"text":"Type of a date record.","type":"text"}],"title":"SBSDKMedicalCertificateDateRecordType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordType"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecordType/incapableOfWorkUntil":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype\/incapableofworkuntil","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incapableOfWorkUntil","kind":"identifier"}],"kind":"symbol","title":"SBSDKMedicalCertificateDateRecordType.incapableOfWorkUntil","role":"symbol","abstract":[{"text":"(Form 1) Incapable of work until (voraussichtlich arbeitsunfähig bis einschließlich oder letzter Tag der Arbeitsunfähigkeit) date.","type":"text"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateDateRecordTypeIncapableOfWorkUntil","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType\/incapableOfWorkUntil"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKMedicalCertificateDateRecordTypeIncapableOfWorkUntil"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordTypeIncapableOfWorkUntil"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordTypeIncapableOfWorkUntil"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType\/title","op":"replace","value":"SBSDKMedicalCertificateDateRecordType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType\/fragments","op":"replace","value":[{"text":"SBSDKMedicalCertificateDateRecordType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType~1incapableOfWorkUntil\/title","value":"SBSDKMedicalCertificateDateRecordTypeIncapableOfWorkUntil"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType~1incapableOfWorkUntil\/fragments","value":[{"text":"SBSDKMedicalCertificateDateRecordTypeIncapableOfWorkUntil","kind":"identifier"}]}]}]}