{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding\/ascii"},"abstract":[{"text":"ASCII (ISO 646).","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ascii","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCharacterEncoding","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding"}]}],"kind":"declarations"}],"metadata":{"title":"ascii","roleHeading":"Type Property","symbolKind":"property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding(cpy)ascii","navigatorTitle":[{"text":"ascii","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ascii","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCharacterEncoding","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding"}],"modules":[{"name":"ScanbotSDK"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcharacterencoding\/ascii"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcharacterencoding\/ascii"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCharacterEncoding/ascii":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ascii","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCharacterEncoding","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"ASCII (ISO 646).","type":"text"}],"type":"topic","title":"ascii","url":"\/documentation\/scanbotsdk\/sbsdkcharacterencoding\/ascii","navigatorTitle":[{"text":"ascii","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding\/ascii"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCharacterEncoding":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKCharacterEncoding"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcharacterencoding","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCharacterEncoding"}],"title":"SBSDKCharacterEncoding","abstract":[{"text":"Enumerates character encodings.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ascii","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ascii","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKCharacterEncoding","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding"},{"text":" * ","kind":"text"},{"text":"ascii","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding~1ascii\/title","value":"ascii","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding~1ascii\/fragments","value":[{"text":"ascii","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding\/title","value":"SBSDKCharacterEncoding","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding\/fragments","value":[{"text":"SBSDKCharacterEncoding","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCharacterEncoding"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}