{"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cp1251"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding","text":"SBSDKCharacterEncoding"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cp1251"}],"symbolKind":"property","title":"cp1251","roleHeading":"Type Property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding(cpy)cp1251"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cp1251","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCharacterEncoding","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcharacterencoding\/cp1251"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcharacterencoding\/cp1251"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding\/cp1251","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding"]]},"abstract":[{"text":"Windows-1251 (Cyrillic).","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCharacterEncoding":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKCharacterEncoding"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcharacterencoding","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCharacterEncoding"}],"title":"SBSDKCharacterEncoding","abstract":[{"text":"Enumerates character encodings.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCharacterEncoding/cp1251":{"title":"cp1251","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cp1251","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCharacterEncoding","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding\/cp1251","role":"symbol","navigatorTitle":[{"text":"cp1251","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcharacterencoding\/cp1251","abstract":[{"type":"text","text":"Windows-1251 (Cyrillic)."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"cp1251","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cp1251"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKCharacterEncoding","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding"},{"text":" * ","kind":"text"},{"text":"cp1251","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding\/title","value":"SBSDKCharacterEncoding","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding\/fragments","value":[{"text":"SBSDKCharacterEncoding","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKCharacterEncoding","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding\/navigatorTitle"},{"value":"cp1251","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding~1cp1251\/title"},{"value":[{"text":"cp1251","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding~1cp1251\/fragments"}]}]}