{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathImageLoadOptions"]]},"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCropRect:colorConversion:canvasColor:loadMode:encryptionMode:decrypter:","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKPathImageLoadOptions(im)initWithCropRect:colorConversion:canvasColor:loadMode:encryptionMode:decrypter:","navigatorTitle":[{"kind":"identifier","text":"initWithCropRect:colorConversion:canvasColor:loadMode:encryptionMode:decrypter:"}],"roleHeading":"Instance Method","title":"initWithCropRect:colorConversion:canvasColor:loadMode:encryptionMode:decrypter:","role":"symbol","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithCropRect:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cropRect","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"colorConversion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKColorConversion","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKColorConversion","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKColorConversion","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"colorConversion","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"canvasColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCanvasColor","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCanvasColor","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKCanvasColor","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"canvasColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"loadMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPathLoadMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKPathLoadMode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"loadMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"encryptionMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEncryptionMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncryptionMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKEncryptionMode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"encryptionMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"decrypter:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SBSDKStorageCryptingProvider>","preciseIdentifier":"c:Qo@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCryptingProvider","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"decrypter","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathImageLoadOptions\/initWithCropRect:colorConversion:canvasColor:loadMode:encryptionMode:decrypter:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpathimageloadoptions\/initwithcroprect:colorconversion:canvascolor:loadmode:encryptionmode:decrypter:"]}],"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKEncryptionMode":{"title":"SBSDKEncryptionMode","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEncryptionMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKEncryptionMode","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkencryptionmode","role":"symbol","abstract":[{"text":"Encryption\/Decryption mode to be used when an image is loaded\/saved.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncryptionMode"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPathImageLoadOptions/initWithCropRect:colorConversion:canvasColor:loadMode:encryptionMode:decrypter:":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpathimageloadoptions\/initwithcroprect:colorconversion:canvascolor:loadmode:encryptionmode:decrypter:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathImageLoadOptions\/initWithCropRect:colorConversion:canvasColor:loadMode:encryptionMode:decrypter:","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCropRect:colorConversion:canvasColor:loadMode:encryptionMode:decrypter:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCropRect:colorConversion:canvasColor:loadMode:encryptionMode:decrypter:"}],"title":"initWithCropRect:colorConversion:canvasColor:loadMode:encryptionMode:decrypter:","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPathLoadMode":{"abstract":[{"text":"Image Ref Path Load Mode.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpathloadmode","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPathLoadMode","kind":"identifier"}],"title":"SBSDKPathLoadMode","navigatorTitle":[{"text":"SBSDKPathLoadMode","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKColorConversion":{"title":"SBSDKColorConversion","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcolorconversion","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKColorConversion","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKColorConversion"}],"abstract":[{"type":"text","text":"Color conversion to apply during image loading."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKColorConversion"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCanvasColor":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKCanvasColor"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcanvascolor","title":"SBSDKCanvasColor","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCanvasColor"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCanvasColor","abstract":[{"text":"Canvas color to use when converting images with alpha channel to images without alpha channel.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPathImageLoadOptions":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathImageLoadOptions","type":"topic","abstract":[{"type":"text","text":"Options for loading image from path."}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}],"role":"symbol","title":"SBSDKPathImageLoadOptions","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpathimageloadoptions"}},"variantOverrides":[{"patch":[{"value":"SBSDKEncryptionMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode\/title"},{"value":[{"text":"SBSDKEncryptionMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode\/fragments"},{"value":[{"text":"SBSDKEncryptionMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode\/navigatorTitle"},{"value":"SBSDKPathLoadMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathLoadMode\/title"},{"value":[{"text":"SBSDKPathLoadMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathLoadMode\/fragments"},{"value":[{"text":"SBSDKPathLoadMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathLoadMode\/navigatorTitle"},{"value":"SBSDKColorConversion","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKColorConversion\/title"},{"value":[{"text":"SBSDKColorConversion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKColorConversion\/fragments"},{"value":[{"text":"SBSDKColorConversion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKColorConversion\/navigatorTitle"},{"value":"SBSDKCanvasColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCanvasColor\/title"},{"value":[{"text":"SBSDKCanvasColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCanvasColor\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKCanvasColor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCanvasColor\/navigatorTitle"},{"value":"SBSDKPathImageLoadOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathImageLoadOptions\/title"},{"value":[{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathImageLoadOptions\/fragments"},{"value":[{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathImageLoadOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}