{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"motionSensitivity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration(py)motionSensitivity","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"motionSensitivity","kind":"identifier"}],"title":"motionSensitivity","symbolKind":"property","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"type":"text","text":"The sensitivity to device motion. The lower the value the less motion of the device is required to prevent the scanner from entering energy save mode."},{"type":"text","text":" "},{"text":"Defaults to 4.0","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration\/motionsensitivity"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration\/motionsensitivity"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"motionSensitivity"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration\/motionSensitivity","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerEnergyConfiguration/motionSensitivity":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"motionSensitivity","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration\/motionsensitivity","role":"symbol","type":"topic","abstract":[{"text":"The sensitivity to device motion. The lower the value the less motion of the device is required to prevent the scanner from entering energy save mode.","type":"text"},{"type":"text","text":" "},{"text":"Defaults to 4.0","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"motionSensitivity","kind":"identifier"}],"title":"motionSensitivity","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration\/motionSensitivity"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerEnergyConfiguration":{"abstract":[{"type":"text","text":"The energy management configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"type":"text","text":" "},{"text":"‘SBSDKBaseScannerViewController’ and subclasses sport a customizable energy management system.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Since detectors and recognizers running on a live video feed can put a lot of load onto the CPU and\/or GPU"},{"text":" ","type":"text"},{"type":"text","text":"of the device, causing the battery to drain quickly and running the device hot, you can customize the energy"},{"type":"text","text":" "},{"type":"text","text":"consumption using this class by configuring the rate of detections\/recognitions per second in performance mode as"},{"type":"text","text":" "},{"text":"well as in energy saving mode.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"In performance mode the detectors\/recognizers will be fed with a higher, configurable rate of"},{"text":" ","type":"text"},{"text":"video frames per second.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"After a certain, configurable period of inactivity the energy save mode will be engaged and the rate"},{"text":" ","type":"text"},{"type":"text","text":"of detections\/recognitions will be reduced to a lower (configurable) rate."},{"text":" ","type":"text"},{"type":"text","text":"You can also configure the time of inactivity before the automatic mode switches from performance to energy save mode."},{"type":"text","text":" "},{"type":"text","text":"Inactivity here means that both of the following conditions are met:"}],"title":"SBSDKBaseScannerEnergyConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"motionSensitivity","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"motionSensitivity"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"motionSensitivity"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration~1motionSensitivity\/title","value":"motionSensitivity","op":"replace"},{"value":[{"kind":"identifier","text":"motionSensitivity"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration~1motionSensitivity\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration\/title","op":"replace","value":"SBSDKBaseScannerEnergyConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration\/navigatorTitle","value":[{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}