{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The minimum insets of the viewfinder."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumInsets"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2EdgeInsets","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2EdgeInsets","kind":"typeIdentifier","text":"SBSDKUI2EdgeInsets"}],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BaseViewFinderConfiguration\/minimumInsets","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2baseviewfinderconfiguration\/minimuminsets"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2baseviewfinderconfiguration\/minimuminsets"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BaseViewFinderConfiguration"]]},"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"minimumInsets"}],"title":"minimumInsets","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BaseViewFinderConfiguration(py)minimumInsets","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumInsets","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2EdgeInsets","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2EdgeInsets","kind":"typeIdentifier"}]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BaseViewFinderConfiguration":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2baseviewfinderconfiguration","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Base configuration of the scanning interface’s viewfinder, serving as guidance to the user."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BaseViewFinderConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BaseViewFinderConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BaseViewFinderConfiguration"}],"title":"SBSDKUI2BaseViewFinderConfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BaseViewFinderConfiguration/minimumInsets":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BaseViewFinderConfiguration\/minimumInsets","navigatorTitle":[{"text":"minimumInsets","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The minimum insets of the viewfinder."}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2baseviewfinderconfiguration\/minimuminsets","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumInsets","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2EdgeInsets","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2EdgeInsets","kind":"typeIdentifier"}],"title":"minimumInsets"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2EdgeInsets":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2EdgeInsets","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2EdgeInsets"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2edgeinsets","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2EdgeInsets","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Represents the insets of a rectangle."}],"title":"SBSDKUI2EdgeInsets"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"minimumInsets","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"minimumInsets"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKUI2EdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2EdgeInsets","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2EdgeInsets"},{"text":" * ","kind":"text"},{"text":"minimumInsets","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BaseViewFinderConfiguration\/title","value":"SBSDKUI2BaseViewFinderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BaseViewFinderConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BaseViewFinderConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BaseViewFinderConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2BaseViewFinderConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BaseViewFinderConfiguration~1minimumInsets\/title","value":"minimumInsets"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BaseViewFinderConfiguration~1minimumInsets\/fragments","value":[{"kind":"identifier","text":"minimumInsets"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2EdgeInsets\/title","value":"SBSDKUI2EdgeInsets"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2EdgeInsets\/fragments","value":[{"text":"SBSDKUI2EdgeInsets","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2EdgeInsets\/navigatorTitle","value":[{"text":"SBSDKUI2EdgeInsets","kind":"identifier"}]}]}]}