{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Vibration\/initWithEnabled:","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vibration\/initwithenabled:"]}],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithEnabled:","kind":"identifier"}],"symbolKind":"method","title":"initWithEnabled:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Vibration(im)initWithEnabled:","navigatorTitle":[{"text":"initWithEnabled:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Vibration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithEnabled:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":";"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Vibration":{"role":"symbol","abstract":[{"type":"text","text":"Configure the vibration."}],"kind":"symbol","type":"topic","title":"SBSDKUI2Vibration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Vibration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2Vibration"}],"navigatorTitle":[{"text":"SBSDKUI2Vibration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vibration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Vibration/initWithEnabled:":{"role":"symbol","abstract":[],"kind":"symbol","type":"topic","title":"initWithEnabled:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Vibration\/initWithEnabled:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithEnabled:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithEnabled:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vibration\/initwithenabled:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2Vibration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Vibration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Vibration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Vibration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Vibration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Vibration"}]}]}]}