{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatGs1CompositeConfiguration"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatGS1CompositeConfiguration","kind":"typeIdentifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatgs1compositeconfiguration()"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"barcodeFormatGs1CompositeConfiguration()","roleHeading":"Type Method","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatGs1CompositeConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatGS1CompositeConfiguration"}],"symbolKind":"method","externalID":"s:10ScanbotSDK35SBSDKBarcodeFormatConfigurationBaseC07barcoded12Gs1CompositeE0AA0cd3GS1iE0CyFZ"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatGs1CompositeConfiguration()","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatGs1CompositeConfiguration()":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatgs1compositeconfiguration()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatGs1CompositeConfiguration()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatGs1CompositeConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatGS1CompositeConfiguration","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"}],"type":"topic","title":"barcodeFormatGs1CompositeConfiguration()","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase":{"navigatorTitle":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase","type":"topic","abstract":[{"text":"Base class for all barcode configurations.","type":"text"}],"title":"SBSDKBarcodeFormatConfigurationBase","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatGS1CompositeConfiguration":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatgs1compositeconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"}],"abstract":[{"type":"text","text":"GS1 Composite configuration. Add to scanner configuration to scan GS1 Composite barcodes."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration","title":"SBSDKBarcodeFormatGS1CompositeConfiguration","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKBarcodeFormatConfigurationBase","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase\/title","op":"replace"},{"value":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase\/fragments","op":"replace"},{"value":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase\/navigatorTitle","op":"replace"},{"value":"SBSDKBarcodeFormatGS1CompositeConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}