{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLineSegmentFloat"]]},"metadata":{"title":"initWithStart:end:","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithStart:end:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithStart:end:"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKLineSegmentFloat(im)initWithStart:end:","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLineSegmentFloat\/initWithStart:end:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdklinesegmentfloat\/initwithstart:end:"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithStart:"},{"text":"(","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") "},{"text":"start","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"end:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"end"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKLineSegmentFloat":{"kind":"symbol","abstract":[{"text":"Represents a line segment in 2D space.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLineSegmentFloat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLineSegmentFloat"}],"title":"SBSDKLineSegmentFloat","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKLineSegmentFloat"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdklinesegmentfloat"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKLineSegmentFloat/initWithStart:end:":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdklinesegmentfloat\/initwithstart:end:","title":"initWithStart:end:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithStart:end:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithStart:end:","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLineSegmentFloat\/initWithStart:end:","abstract":[]}},"variantOverrides":[{"patch":[{"value":"SBSDKLineSegmentFloat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLineSegmentFloat\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLineSegmentFloat\/fragments","value":[{"kind":"identifier","text":"SBSDKLineSegmentFloat"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLineSegmentFloat\/navigatorTitle","op":"replace","value":[{"text":"SBSDKLineSegmentFloat","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}