{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The button class used in the camera view controller to take a snapshot."},{"type":"text","text":" "},{"type":"text","text":"Animates itself depending on its status."}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)UIButton"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)CALayerDelegate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s8SendableP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIAppearance","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIContextMenuInteractionDelegate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UICoordinateSpace","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIDynamicItem","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIFocusItem","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIFocusItemContainer","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UISpringLoadedInteractionSupporting","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKShutterButton"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton"]}],"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKShutterButton","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKShutterButton","kind":"identifier"}],"role":"symbol","roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"SBSDKShutterButton","kind":"identifier"}],"title":"SBSDKShutterButton","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/buttonScannedBackgroundColor","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/buttonScannedColor","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/buttonSearchingBackgroundColor","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/buttonSearchingColor","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/indicatorColor","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/isTakingPhoto","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/scannerStatus"],"anchor":"Instance-Properties"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKShutterButton/initWithCoder:":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/initWithCoder:","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton\/initwithcoder:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"title":"initWithCoder:","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKShutterButton/scannerStatus":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/scannerStatus","abstract":[{"text":"The current status of the receiver. See ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus","type":"reference","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton\/scannerstatus","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scannerStatus"},{"kind":"text","text":": "},{"text":"SBSDKScannerStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKScannerStatus"}],"title":"scannerStatus","navigatorTitle":[{"kind":"identifier","text":"scannerStatus"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)UIButton":{"type":"unresolvable","title":"UIButton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)UIButton"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UITraitEnvironment"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannerStatus/scanned":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/scanned","abstract":[{"type":"text","text":"The scanner has scanned something."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannerstatus\/scanned","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scanned"}],"title":"SBSDKScannerStatus.scanned","navigatorTitle":[{"text":"SBSDKScannerStatusScanned","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)CALayerDelegate"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKShutterButton/buttonScannedColor":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/buttonScannedColor","abstract":[{"text":"The main color of the receiver while the scanner status is ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/scanned"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Defaults to white.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton\/buttonscannedcolor","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"buttonScannedColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"buttonScannedColor","navigatorTitle":[{"text":"buttonScannedColor","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKShutterButton/layoutSubviews":{"title":"layoutSubviews","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/layoutSubviews","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton\/layoutsubviews"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKShutterButton/beginTrackingWithTouch:withEvent:":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/beginTrackingWithTouch:withEvent:","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton\/begintrackingwithtouch:withevent:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"beginTrackingWithTouch:withEvent:","kind":"identifier"}],"title":"beginTrackingWithTouch:withEvent:","navigatorTitle":[{"text":"beginTrackingWithTouch:withEvent:","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKShutterButton/indicatorColor":{"abstract":[{"text":"The color of the indicator shown, when ","type":"text"},{"type":"codeVoice","code":"isTakingPhoto"},{"type":"text","text":" is set to "},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/indicatorColor","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indicatorColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton\/indicatorcolor","navigatorTitle":[{"kind":"identifier","text":"indicatorColor"}],"title":"indicatorColor","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIFocusItem"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIAccessibilityIdentification"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIContextMenuInteractionDelegate":{"title":"UIKit.UIContextMenuInteractionDelegate","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIContextMenuInteractionDelegate"},"doc://net.doo.ScanbotDocumentScannerSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/5UIKit23UITraitChangeObservableP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKShutterButton/highlighted":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/highlighted","role":"symbol","fragments":[{"text":"highlighted","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton\/highlighted","title":"highlighted","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKShutterButton/isTakingPhoto":{"abstract":[{"text":"Indicates, whether a still image is currently being taken or not.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If set to "},{"type":"codeVoice","code":"true"},{"text":" a ","type":"text"},{"type":"codeVoice","code":"UIActivityIndicator"},{"text":" is shown in the center.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/isTakingPhoto","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTakingPhoto","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton\/istakingphoto","navigatorTitle":[{"text":"isTakingPhoto","kind":"identifier"}],"title":"isTakingPhoto","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannerStatus":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKScannerStatus"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannerstatus","title":"SBSDKScannerStatus","abstract":[{"type":"text","text":"This enum describes the possible scanning states of any scanner."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannerStatus","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKShutterButton/buttonSearchingColor":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/buttonSearchingColor","abstract":[{"type":"text","text":"The main color of the receiver while the scanner status is "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/scanned"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Defaults to white."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton\/buttonsearchingcolor","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"buttonSearchingColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"title":"buttonSearchingColor","navigatorTitle":[{"text":"buttonSearchingColor","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKShutterButton/buttonSearchingBackgroundColor":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/buttonSearchingBackgroundColor","abstract":[{"type":"text","text":"The background color of the receiver while the scanner status is "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/scanning","isActive":true},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to clear.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton\/buttonsearchingbackgroundcolor","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buttonSearchingBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"title":"buttonSearchingBackgroundColor","navigatorTitle":[{"text":"buttonSearchingBackgroundColor","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCoding"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKShutterButton/initWithFrame:":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/initWithFrame:","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton\/initwithframe:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"title":"initWithFrame:","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKShutterButton":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKShutterButton"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKShutterButton","kind":"identifier"}],"abstract":[{"text":"The button class used in the camera view controller to take a snapshot.","type":"text"},{"text":" ","type":"text"},{"text":"Animates itself depending on its status.","type":"text"}],"title":"SBSDKShutterButton"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKShutterButton/didMoveToWindow":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/didMoveToWindow","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton\/didmovetowindow","navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}],"title":"didMoveToWindow","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIAppearanceContainer"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIResponderStandardEditActions"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKShutterButton/buttonScannedBackgroundColor":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/buttonScannedBackgroundColor","abstract":[{"type":"text","text":"The background color of the receiver while the scanner status is "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/scanned"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Defaults to clear."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkshutterbutton\/buttonscannedbackgroundcolor","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"buttonScannedBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"title":"buttonScannedBackgroundColor","navigatorTitle":[{"text":"buttonScannedBackgroundColor","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannerStatus/scanning":{"abstract":[{"text":"The scanner is active.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/scanning","title":"SBSDKScannerStatus.scanning","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanning","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannerstatus\/scanning","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannerStatusScanning"}]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://net.doo.ScanbotDocumentScannerSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s8SendableP","title":"Swift.Sendable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UISpringLoadedInteractionSupporting":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UISpringLoadedInteractionSupporting","title":"UIKit.UISpringLoadedInteractionSupporting"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting","title":"UIKit.UIAccessibilityContentSizeCategoryImageAdjusting"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKShutterButton","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKShutterButton","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKShutterButton","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/buttonScannedBackgroundColor","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/buttonScannedColor","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/buttonSearchingBackgroundColor","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/buttonSearchingColor","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/highlighted","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/indicatorColor","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/isTakingPhoto","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/scannerStatus"],"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/beginTrackingWithTouch:withEvent:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/didMoveToWindow","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/initWithCoder:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/initWithFrame:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKShutterButton\/layoutSubviews"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)UIButton"],"type":"inheritsFrom","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKShutterButton","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)UIButton","kind":"typeIdentifier","text":"UIButton"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"scannerStatus","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton~1scannerStatus\/title"},{"value":[{"text":"scannerStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton~1scannerStatus\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannerStatus~1scanned\/title","value":"SBSDKScannerStatusScanned","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKScannerStatusScanned"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannerStatus~1scanned\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton~1buttonScannedColor\/title","op":"replace","value":"buttonScannedColor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton~1buttonScannedColor\/fragments","value":[{"kind":"identifier","text":"buttonScannedColor"}]},{"value":"indicatorColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton~1indicatorColor\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton~1indicatorColor\/fragments","value":[{"text":"indicatorColor","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton~1isTakingPhoto\/title","value":"isTakingPhoto"},{"value":[{"text":"isTakingPhoto","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton~1isTakingPhoto\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannerStatus\/title","op":"replace","value":"SBSDKScannerStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannerStatus\/fragments","value":[{"text":"SBSDKScannerStatus","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKScannerStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannerStatus\/navigatorTitle","op":"replace"},{"value":"buttonSearchingColor","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton~1buttonSearchingColor\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton~1buttonSearchingColor\/fragments","value":[{"text":"buttonSearchingColor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton~1buttonSearchingBackgroundColor\/title","value":"buttonSearchingBackgroundColor"},{"value":[{"text":"buttonSearchingBackgroundColor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton~1buttonSearchingBackgroundColor\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton\/title","op":"replace","value":"SBSDKShutterButton"},{"value":[{"text":"SBSDKShutterButton","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton\/navigatorTitle","value":[{"text":"SBSDKShutterButton","kind":"identifier"}]},{"value":"buttonScannedBackgroundColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton~1buttonScannedBackgroundColor\/title"},{"value":[{"text":"buttonScannedBackgroundColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKShutterButton~1buttonScannedBackgroundColor\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannerStatus~1scanning\/title","op":"replace","value":"SBSDKScannerStatusScanning"},{"op":"replace","value":[{"text":"SBSDKScannerStatusScanning","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannerStatus~1scanning\/fragments"}]}]}