{"abstract":[{"text":"The subscriber that is being tracked.","type":"text"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsSubscriber\/logEvent(event:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkanalyticssubscriber"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkanalyticssubscriber"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsSubscriber","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKAnalyticsSubscriber) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"title":"SBSDKAnalyticsSubscriber","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}],"symbolKind":"protocol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKAnalyticsSubscriber","role":"symbol","roleHeading":"Protocol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAnalyticsSubscriber/logEvent(event:)":{"title":"logEvent(event:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"logEventWithEvent:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkanalyticssubscriber\/logevent(event:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logEvent"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKAnalyticsEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAnalyticsEvent"},{"text":")","kind":"text"}],"abstract":[{"text":"Log an event.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsSubscriber\/logEvent(event:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAnalyticsSubscriber":{"abstract":[{"text":"The subscriber that is being tracked.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsSubscriber","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkanalyticssubscriber","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}],"navigatorTitle":[{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"role":"symbol","title":"SBSDKAnalyticsSubscriber","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"value":"SBSDKAnalyticsSubscriber","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsSubscriber\/logEvent(event:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}]},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"logEventWithEvent:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsSubscriber~1logEvent(event:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsSubscriber~1logEvent(event:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"logEventWithEvent:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsSubscriber\/title","op":"replace","value":"SBSDKAnalyticsSubscriber"},{"value":[{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsSubscriber\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsSubscriber\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}