{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/init()"]},{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/detectOrientation","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/earlyStopIfNSymbolsFound","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/inspectSmallText","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/maxImageSize","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/maxProcessedFraction","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/minEstimatedNumberOfSymbolsForDocument","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/minProcessedFraction","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/qualityIndices","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/qualityThresholds","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/returnQualityHeatmap","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/tileSize"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/toJson(configuration:)"],"title":"Instance Methods","generated":true}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKDocumentQualityAnalyzerConfiguration) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Document Quality Analyzer configuration."}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration"]}],"metadata":{"symbolKind":"class","roleHeading":"Class","title":"SBSDKDocumentQualityAnalyzerConfiguration","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentQualityAnalyzerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying","title":"NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/copyWithZone:":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/copyWithZone:","role":"symbol","kind":"symbol","title":"copyWithZone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/copywithzone:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/hash":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/hash","title":"hash","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/hash","kind":"symbol","fragments":[{"kind":"identifier","text":"hash"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/minProcessedFraction":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/minprocessedfraction","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/minProcessedFraction","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"minProcessedFraction"}],"title":"minProcessedFraction","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minProcessedFraction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"abstract":[{"text":"At least this fraction of the image will be processed, range is from 0 to 1.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/isEqual:":{"role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/isEqual:","type":"topic","title":"isEqual:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/isequal:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/returnQualityHeatmap":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/returnQualityHeatmap","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/returnqualityheatmap","navigatorTitle":[{"kind":"identifier","text":"returnQualityHeatmap"}],"kind":"symbol","abstract":[{"type":"text","text":"If true, will return the quality heatmap as a part of the result."},{"type":"text","text":" "},{"text":"In this case, the entire image will be processed and the minProcessedFraction will be ignored.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Useful for debugging situations where the returned quality doesn’t appear to match the perceived quality."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"returnQualityHeatmap","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"returnQualityHeatmap"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/inspectSmallText":{"type":"topic","abstract":[{"text":"Inspect small text (typically less than 12 pixels height) when analyzing the document quality.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If true, processing will be slower, but when the quality issue with a document is the low resolution of the"},{"type":"text","text":" "},{"type":"text","text":"text,"},{"type":"text","text":" "},{"text":"then the issue will be caught.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/inspectsmalltext","navigatorTitle":[{"kind":"identifier","text":"inspectSmallText"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inspectSmallText"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/inspectSmallText","title":"inspectSmallText","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration":{"abstract":[{"text":"Document Quality Analyzer configuration.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration","title":"SBSDKDocumentQualityAnalyzerConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerConfiguration"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/maxProcessedFraction":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/maxProcessedFraction","type":"topic","title":"maxProcessedFraction","abstract":[{"type":"text","text":"At most this fraction of the image will be processed, range is from 0 to 1."}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/maxprocessedfraction","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"maxProcessedFraction","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"maxProcessedFraction"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/tileSize":{"type":"topic","abstract":[{"text":"Image will be processed in tiles of this size; will be ignored if image is small.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/tilesize","navigatorTitle":[{"text":"tileSize","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"tileSize","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/tileSize","title":"tileSize","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:":{"navigatorTitle":[{"text":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/initwithqualitythresholds:qualityindices:detectorientation:inspectsmalltext:maximagesize:minestimatednumberofsymbolsfordocument:minprocessedfraction:maxprocessedfraction:earlystopifnsymbolsfound:tilesize:returnqualityheatmap:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","kind":"identifier"}],"title":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","role":"symbol","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/maxImageSize":{"abstract":[{"type":"text","text":"Maximum image size in pixels, if image is bigger, it will be resized."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"maxImageSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/maximagesize","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/maxImageSize","title":"maxImageSize","navigatorTitle":[{"text":"maxImageSize","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/qualityThresholds":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/qualityThresholds","type":"topic","title":"qualityThresholds","abstract":[{"type":"text","text":"Quality thresholds to separate quality levels."}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/qualitythresholds","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"qualityThresholds"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentQualityThreshold","text":"SBSDKDocumentQualityThreshold"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"qualityThresholds","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/qualityIndices":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/qualityIndices","title":"qualityIndices","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"qualityIndices"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/qualityindices","abstract":[{"type":"text","text":"quality levels."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"qualityIndices"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentQuality","kind":"typeIdentifier","text":"SBSDKDocumentQuality"},{"text":"]","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/minEstimatedNumberOfSymbolsForDocument":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minEstimatedNumberOfSymbolsForDocument"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"minEstimatedNumberOfSymbolsForDocument"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/minEstimatedNumberOfSymbolsForDocument","title":"minEstimatedNumberOfSymbolsForDocument","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/minestimatednumberofsymbolsfordocument","abstract":[{"text":"If estimated number of symbols is less than this value, return that document is not found.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/earlyStopIfNSymbolsFound":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/earlyStopIfNSymbolsFound","abstract":[{"type":"text","text":"If this number of symbols is found and minProcessedFraction of the image is processed, the processing stops."}],"kind":"symbol","title":"earlyStopIfNSymbolsFound","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/earlystopifnsymbolsfound","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"earlyStopIfNSymbolsFound","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"earlyStopIfNSymbolsFound","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/init()":{"role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/init()","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/init()","title":"init()","abstract":[],"type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/toJson(configuration:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/toJson(configuration:)","title":"toJson(configuration:)","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/tojson(configuration:)","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/detectOrientation":{"navigatorTitle":[{"text":"detectOrientation","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/detectOrientation","title":"detectOrientation","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/detectorientation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"detectOrientation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Enable orientation detection. Document orientation will be returned in"},{"text":" ","type":"text"},{"code":"DocumentQualityAnalyzerResult.orientation","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/fromJsonWithJson:":{"title":"fromJsonWithJson:","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/fromjsonwithjson:","fragments":[{"kind":"text","text":"+ "},{"text":"fromJsonWithJson:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/fromJsonWithJson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"},"doc://net.doo.ScanbotDocumentScannerSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKDocumentQualityAnalyzerConfiguration","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/detectOrientation","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/earlyStopIfNSymbolsFound","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/hash","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/inspectSmallText","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/maxImageSize","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/maxProcessedFraction","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/minEstimatedNumberOfSymbolsForDocument","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/minProcessedFraction","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/qualityIndices","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/qualityThresholds","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/returnQualityHeatmap","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/tileSize"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/init()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/toJson(configuration:)"],"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/fromJsonWithJson:"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying"],"type":"conformsTo","title":"Conforms To"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerConfiguration"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1minProcessedFraction\/title","value":"minProcessedFraction","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1minProcessedFraction\/fragments","value":[{"text":"minProcessedFraction","kind":"identifier"}]},{"value":"returnQualityHeatmap","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1returnQualityHeatmap\/title"},{"op":"replace","value":[{"kind":"identifier","text":"returnQualityHeatmap"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1returnQualityHeatmap\/fragments"},{"value":"inspectSmallText","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1inspectSmallText\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"inspectSmallText"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1inspectSmallText\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/title","value":"SBSDKDocumentQualityAnalyzerConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/fragments","value":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/navigatorTitle","value":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"maxProcessedFraction","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1maxProcessedFraction\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1maxProcessedFraction\/fragments","value":[{"kind":"identifier","text":"maxProcessedFraction"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1tileSize\/title","value":"tileSize","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1tileSize\/fragments","op":"replace","value":[{"text":"tileSize","kind":"identifier"}]},{"value":"maxImageSize","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1maxImageSize\/title","op":"replace"},{"value":[{"kind":"identifier","text":"maxImageSize"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1maxImageSize\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1qualityThresholds\/title","value":"qualityThresholds"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1qualityThresholds\/fragments","value":[{"kind":"identifier","text":"qualityThresholds"}]},{"op":"replace","value":"qualityIndices","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1qualityIndices\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1qualityIndices\/fragments","value":[{"kind":"identifier","text":"qualityIndices"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1minEstimatedNumberOfSymbolsForDocument\/title","value":"minEstimatedNumberOfSymbolsForDocument"},{"value":[{"text":"minEstimatedNumberOfSymbolsForDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1minEstimatedNumberOfSymbolsForDocument\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1earlyStopIfNSymbolsFound\/title","value":"earlyStopIfNSymbolsFound"},{"op":"replace","value":[{"text":"earlyStopIfNSymbolsFound","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1earlyStopIfNSymbolsFound\/fragments"},{"value":"init","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1init()\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1toJson(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJsonWithConfiguration:"}]},{"value":"detectOrientation","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1detectOrientation\/title"},{"value":[{"text":"detectOrientation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1detectOrientation\/fragments","op":"replace"}]}]}