{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController\/enableCameraUIConfiguration","interfaceLanguage":"occ"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller\/enablecamerauiconfiguration"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIEnableCameraUIConfiguration","kind":"typeIdentifier","text":"SBSDKUIEnableCameraUIConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"enableCameraUIConfiguration"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"enableCameraUIConfiguration","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorViewController(py)enableCameraUIConfiguration","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"enableCameraUIConfiguration","kind":"identifier"}],"symbolKind":"property","navigatorTitle":[{"text":"enableCameraUIConfiguration","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewController/enableCameraUIConfiguration":{"title":"enableCameraUIConfiguration","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller\/enablecamerauiconfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController\/enableCameraUIConfiguration","kind":"symbol","fragments":[{"text":"enableCameraUIConfiguration","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIEnableCameraUIConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuienablecamerauiconfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration for the user interface of camera based view controllers.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraUIConfiguration","title":"SBSDKUIEnableCameraUIConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewController":{"title":"SBSDKUIDocumentDataExtractorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to extract generic documents data."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUIEnableCameraUIConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraUIConfiguration\/title"},{"value":[{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraUIConfiguration\/fragments"},{"value":[{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraUIConfiguration\/navigatorTitle"},{"value":"SBSDKUIDocumentDataExtractorViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/title"},{"value":[{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/navigatorTitle"}]}]}