{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"gender"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCommonFieldType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCommonFieldType","text":"SBSDKCommonFieldType","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Gender field."}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcommonfieldtype\/gender"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcommonfieldtype\/gender"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCommonFieldType\/gender","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"property","title":"gender","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"gender"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCommonFieldType","text":"SBSDKCommonFieldType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"gender","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCommonFieldType(cpy)gender"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCommonFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCommonFieldType/gender":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"gender","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCommonFieldType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCommonFieldType"}],"title":"gender","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcommonfieldtype\/gender","abstract":[{"type":"text","text":"Gender field."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCommonFieldType\/gender","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"gender","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCommonFieldType":{"title":"SBSDKCommonFieldType","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcommonfieldtype","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKCommonFieldType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCommonFieldType"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCommonFieldType","abstract":[{"type":"text","text":"Common field types."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"value":"gender","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"gender"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCommonFieldType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCommonFieldType","text":"SBSDKCommonFieldType","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"gender","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCommonFieldType~1gender\/title","op":"replace","value":"gender"},{"value":[{"text":"gender","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCommonFieldType~1gender\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCommonFieldType\/title","value":"SBSDKCommonFieldType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCommonFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKCommonFieldType"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCommonFieldType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCommonFieldType"}],"op":"replace"}]}]}