{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debtorPostalCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/debtorpostalcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/debtorpostalcode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorPostalCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Debtor Postal Code"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debtorPostalCode"}],"title":"SBSDKUI2SwissQRCodeDocumentFieldType.debtorPostalCode","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2SwissQRCodeDocumentFieldType@SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPostalCode","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPostalCode"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldType"}],"abstract":[{"type":"text","text":"Swiss QR Code Document Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwissQRCodeDocumentFieldType/debtorPostalCode":{"role":"symbol","title":"SBSDKUI2SwissQRCodeDocumentFieldType.debtorPostalCode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debtorPostalCode"}],"abstract":[{"type":"text","text":"Debtor Postal Code"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwissQRCodeDocumentFieldType\/debtorPostalCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPostalCode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swissqrcodedocumentfieldtype\/debtorpostalcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPostalCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPostalCode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPostalCode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1debtorPostalCode\/title","value":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPostalCode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwissQRCodeDocumentFieldType~1debtorPostalCode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SwissQRCodeDocumentFieldTypeDebtorPostalCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}