{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerStatusTextConfiguration"]]},"abstract":[{"text":"The text being displayed on the user-guidance label, when a document was scanned, but its center is too far away from the image center.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textHintOffCenter"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerStatusTextConfiguration\/textHintOffCenter","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerstatustextconfiguration\/texthintoffcenter"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerstatustextconfiguration\/texthintoffcenter"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textHintOffCenter","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerStatusTextConfiguration(py)textHintOffCenter","roleHeading":"Instance Property","symbolKind":"property","title":"textHintOffCenter","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"textHintOffCenter","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerStatusTextConfiguration":{"title":"SBSDKDocumentScannerStatusTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerStatusTextConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerStatusTextConfiguration"}],"role":"symbol","abstract":[{"text":"Wraps the texts being displayed as the detection status.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerStatusTextConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerstatustextconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerStatusTextConfiguration/textHintOffCenter":{"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textHintOffCenter","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerstatustextconfiguration\/texthintoffcenter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerStatusTextConfiguration\/textHintOffCenter","title":"textHintOffCenter","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"textHintOffCenter"}],"abstract":[{"type":"text","text":"The text being displayed on the user-guidance label, when a document was scanned, but its center is too far away from the image center."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"textHintOffCenter","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"textHintOffCenter"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"textHintOffCenter"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration\/title","op":"replace","value":"SBSDKDocumentScannerStatusTextConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentScannerStatusTextConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration\/navigatorTitle","value":[{"text":"SBSDKDocumentScannerStatusTextConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"textHintOffCenter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration~1textHintOffCenter\/title"},{"value":[{"text":"textHintOffCenter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration~1textHintOffCenter\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}