{"sections":[],"metadata":{"role":"symbol","symbolKind":"method","roleHeading":"Type Method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ReorderPagesScreenConfiguration(cm)fromJsonWithJson:","title":"fromJsonWithJson:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReorderPagesScreenConfiguration\/fromJsonWithJson:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReorderPagesScreenConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reorderpagesscreenconfiguration\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ReorderPagesScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReorderPagesScreenConfiguration","text":"SBSDKUI2ReorderPagesScreenConfiguration"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromJsonWithJson:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"json"},{"kind":"text","text":";"}]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReorderPagesScreenConfiguration":{"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReorderPagesScreenConfiguration","abstract":[{"type":"text","text":"Configuration of the screen for reordering the scanned pages."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reorderpagesscreenconfiguration","title":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReorderPagesScreenConfiguration/fromJsonWithJson:":{"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reorderpagesscreenconfiguration\/fromjsonwithjson:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReorderPagesScreenConfiguration\/fromJsonWithJson:","role":"symbol","kind":"symbol","title":"fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2ReorderPagesScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReorderPagesScreenConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReorderPagesScreenConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2ReorderPagesScreenConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReorderPagesScreenConfiguration\/navigatorTitle","op":"replace"}]}]}