{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality\/noDocument"},"metadata":{"title":"SBSDKDocumentQuality.noDocument","externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentQuality@SBSDKDocumentQualityNoDocument","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentQualityNoDocument"}],"symbolKind":"case","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noDocument"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality"]]},"abstract":[{"text":"No document was found.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noDocument"}],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentquality\/nodocument"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentquality\/nodocument"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQuality":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQuality","kind":"identifier"}],"abstract":[{"type":"text","text":"The quality of a document in a digital image."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentQuality"}],"title":"SBSDKDocumentQuality","url":"\/documentation\/scanbotsdk\/sbsdkdocumentquality","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQuality/noDocument":{"navigatorTitle":[{"text":"SBSDKDocumentQualityNoDocument","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"No document was found."}],"title":"SBSDKDocumentQuality.noDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality\/noDocument","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"noDocument","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentquality\/nodocument","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"SBSDKDocumentQualityNoDocument","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentQualityNoDocument"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKDocumentQualityNoDocument"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKDocumentQuality","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality\/title"},{"value":[{"text":"SBSDKDocumentQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality\/fragments"},{"value":"SBSDKDocumentQualityNoDocument","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality~1noDocument\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality~1noDocument\/fragments","op":"replace","value":[{"text":"SBSDKDocumentQualityNoDocument","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}