{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"secondOwnerLegalStatus","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleOwnerData"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleOwnerData\/secondOwnerLegalStatus"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehicleownerdata\/secondownerlegalstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehicleownerdata\/secondownerlegalstatus"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Data element ID “NBB”. The legal status of the second vehicle owner. This is only used when a vehicle has multiple owners. A legal status may be (“AND”, “OR”).","type":"text"}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVAVehicleOwnerData(py)secondOwnerLegalStatus","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"secondOwnerLegalStatus","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"secondOwnerLegalStatus","kind":"identifier"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","title":"secondOwnerLegalStatus"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","title":"SBSDKGenericDocumentField","abstract":[{"text":"A generic document field.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleOwnerData":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleOwnerData","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVAVehicleOwnerData"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentAAMVAVehicleOwnerData","kind":"identifier"}],"abstract":[{"text":"Vehicle Owner Data. File type “OW”.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehicleownerdata","role":"symbol","title":"SBSDKBarcodeDocumentAAMVAVehicleOwnerData","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAVehicleOwnerData/secondOwnerLegalStatus":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvavehicleownerdata\/secondownerlegalstatus","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"secondOwnerLegalStatus","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"secondOwnerLegalStatus","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAVehicleOwnerData\/secondOwnerLegalStatus","abstract":[{"type":"text","text":"Data element ID “NBB”. The legal status of the second vehicle owner. This is only used when a vehicle has multiple owners. A legal status may be (“AND”, “OR”)."}],"title":"secondOwnerLegalStatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"secondOwnerLegalStatus"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"secondOwnerLegalStatus","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField"},{"kind":"text","text":" * "},{"kind":"identifier","text":"secondOwnerLegalStatus"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"SBSDKGenericDocumentField","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}]},{"op":"replace","value":"SBSDKBarcodeDocumentAAMVAVehicleOwnerData","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleOwnerData\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleOwnerData\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeDocumentAAMVAVehicleOwnerData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleOwnerData\/navigatorTitle","value":[{"text":"SBSDKBarcodeDocumentAAMVAVehicleOwnerData","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleOwnerData~1secondOwnerLegalStatus\/title","value":"secondOwnerLegalStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAVehicleOwnerData~1secondOwnerLegalStatus\/fragments","value":[{"text":"secondOwnerLegalStatus","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}