{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport\/isEqual:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkfieldconsistencyverificationreport\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"symbolKind":"method","title":"isEqual:","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldConsistencyVerificationReport(im)isEqual:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldConsistencyVerificationReport/isEqual:":{"url":"\/documentation\/scanbotsdk\/sbsdkfieldconsistencyverificationreport\/isequal:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport\/isEqual:","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"title":"isEqual:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldConsistencyVerificationReport":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFieldConsistencyVerificationReport"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport","title":"SBSDKFieldConsistencyVerificationReport","abstract":[{"text":"Report of the field consistency verification.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkfieldconsistencyverificationreport","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKFieldConsistencyVerificationReport"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKFieldConsistencyVerificationReport","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldConsistencyVerificationReport\/title","op":"replace"},{"value":[{"text":"SBSDKFieldConsistencyVerificationReport","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldConsistencyVerificationReport\/fragments","op":"replace"},{"value":[{"text":"SBSDKFieldConsistencyVerificationReport","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldConsistencyVerificationReport\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}