{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2IntroImage","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IntroImage","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IntroImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"kind":"text","text":" "},{"kind":"identifier","text":"text:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"text"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IntroListEntry"]]},"kind":"symbol","metadata":{"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","title":"initWithImage:text:","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IntroListEntry(im)initWithImage:text:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:text:"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImage:text:"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2introlistentry\/initwithimage:text:"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IntroListEntry\/initWithImage:text:"},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2IntroListEntry":{"abstract":[{"text":"An entry in the list of scanning steps of the introduction screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IntroListEntry","type":"topic","title":"SBSDKUI2IntroListEntry","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2introlistentry","navigatorTitle":[{"text":"SBSDKUI2IntroListEntry","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2IntroListEntry","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2IntroListEntry/initWithImage:text:":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IntroListEntry\/initWithImage:text:","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2introlistentry\/initwithimage:text:","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithImage:text:"}],"abstract":[],"role":"symbol","title":"initWithImage:text:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:text:"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2IntroImage":{"abstract":[{"text":"Determines the image for the introduction screen.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2IntroImage","kind":"identifier"}],"title":"SBSDKUI2IntroImage","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2introimage","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IntroImage","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2IntroImage","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2StyledText":{"kind":"symbol","type":"topic","title":"SBSDKUI2StyledText","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2styledtext","navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 8.0.4","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2IntroListEntry","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IntroListEntry\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2IntroListEntry"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IntroListEntry\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2IntroListEntry"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IntroListEntry\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2IntroImage","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IntroImage\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2IntroImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IntroImage\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2IntroImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IntroImage\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2StyledText","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/navigatorTitle","op":"replace"}]}]}