{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconButton\/isEqual:","interfaceLanguage":"occ"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"roleHeading":"Instance Method","title":"isEqual:","role":"symbol","symbolKind":"method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2IconButton(im)isEqual:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2iconbutton\/isequal:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconButton"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IconButton/isEqual:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2iconbutton\/isequal:","abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconButton\/isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","title":"isEqual:","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IconButton":{"title":"SBSDKUI2IconButton","role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2iconbutton","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconButton","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2IconButton"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IconButton"}],"abstract":[{"type":"text","text":"Configuration of the icon appearance on a button."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2IconButton","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconButton\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2IconButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconButton\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconButton\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2IconButton"}]}]}]}