{"sections":[],"abstract":[{"type":"text","text":"Removes an observer from the receiver."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument"]]},"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument(im)removeObserver:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeObserver","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKScannedDocumentObserver","text":"SBSDKScannedDocumentObserver"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"removeObserver(_:)","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"removeObserver:"}],"role":"symbol","symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument\/removeObserver(_:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeObserver","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"observer","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKScannedDocumentObserver","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKScannedDocumentObserver","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocumentObserver"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"observer","content":[{"inlineContent":[{"type":"text","text":"The observer that wants to stop receiving delegate calls."}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscanneddocument\/removeobserver(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscanneddocument\/removeobserver(_:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedDocument","kind":"identifier"}],"abstract":[{"type":"text","text":"An automatically persisted, thread-safe and observable document-page model for a document with multiple scanned pages."}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","title":"SBSDKScannedDocument","url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument/removeObserver(_:)":{"abstract":[{"text":"Removes an observer from the receiver.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeObserver"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKScannedDocumentObserver","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKScannedDocumentObserver"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"removeObserver:"}],"title":"removeObserver(_:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument\/removeObserver(_:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument\/removeobserver(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocumentObserver":{"title":"SBSDKScannedDocumentObserver","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedDocumentObserver"}],"role":"symbol","type":"topic","abstract":[{"text":"A delegation-like protocol for observing changes on an instance of ","type":"text"},{"type":"codeVoice","code":"SBSDKScannedDocument"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKScannedDocumentObserver","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocumentObserver","url":"\/documentation\/scanbotsdk\/sbsdkscanneddocumentobserver"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"removeObserver:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeObserver:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"removeObserver:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SBSDKScannedDocumentObserver>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKScannedDocumentObserver"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"observer"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"observer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The observer that wants to stop receiving delegate calls."}]}]}],"kind":"parameters"}},{"value":"SBSDKScannedDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKScannedDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKScannedDocument"}]},{"value":"removeObserver:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument~1removeObserver(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument~1removeObserver(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeObserver:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocumentObserver\/title","value":"SBSDKScannedDocumentObserver"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocumentObserver\/fragments","value":[{"text":"SBSDKScannedDocumentObserver","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocumentObserver\/navigatorTitle","value":[{"text":"SBSDKScannedDocumentObserver","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}