{"sections":[],"abstract":[{"type":"text","text":"A check format commonly used in Israel."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard\/isr","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isr","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCheckStandard","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckStandard"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"property","title":"isr","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckStandard(cpy)isr","navigatorTitle":[{"kind":"identifier","text":"isr"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isr"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckStandard","kind":"typeIdentifier","text":"SBSDKCheckStandard"}],"roleHeading":"Type Property","role":"symbol","modules":[{"name":"ScanbotSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckstandard\/isr"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckstandard\/isr"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckStandard/isr":{"abstract":[{"text":"A check format commonly used in Israel.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isr"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCheckStandard","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckStandard"}],"navigatorTitle":[{"kind":"identifier","text":"isr"}],"title":"isr","url":"\/documentation\/scanbotsdk\/sbsdkcheckstandard\/isr","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard\/isr"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckStandard":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Supported check standards."}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckstandard","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard","navigatorTitle":[{"text":"SBSDKCheckStandard","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckStandard","kind":"identifier"}],"title":"SBSDKCheckStandard"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"isr","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isr"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckStandard","text":"SBSDKCheckStandard"},{"kind":"text","text":" * "},{"kind":"identifier","text":"isr"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckStandard~1isr\/title","value":"isr","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckStandard~1isr\/fragments","value":[{"kind":"identifier","text":"isr"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckStandard\/title","value":"SBSDKCheckStandard","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckStandard\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckStandard"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckStandard\/navigatorTitle","value":[{"text":"SBSDKCheckStandard","kind":"identifier"}],"op":"replace"}]}]}