{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType\/childNeedsCareUntil"},"abstract":[{"type":"text","text":"(Form 21a) Child needs care until (Das genannte Kind bedarf\/bedurfte bis einschließlich) date."}],"metadata":{"role":"symbol","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"childNeedsCareUntil"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordTypeChildNeedsCareUntil"}],"symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateDateRecordType@SBSDKMedicalCertificateDateRecordTypeChildNeedsCareUntil","title":"SBSDKMedicalCertificateDateRecordType.childNeedsCareUntil"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype\/childneedscareuntil"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype\/childneedscareuntil"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"childNeedsCareUntil","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecordType/childNeedsCareUntil":{"abstract":[{"type":"text","text":"(Form 21a) Child needs care until (Das genannte Kind bedarf\/bedurfte bis einschließlich) date."}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateDateRecordTypeChildNeedsCareUntil","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype\/childneedscareuntil","title":"SBSDKMedicalCertificateDateRecordType.childNeedsCareUntil","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType\/childNeedsCareUntil","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"childNeedsCareUntil","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecordType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateDateRecordType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateDateRecordType","kind":"identifier"}],"kind":"symbol","title":"SBSDKMedicalCertificateDateRecordType","abstract":[{"text":"Type of a date record.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKMedicalCertificateDateRecordTypeChildNeedsCareUntil","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateDateRecordTypeChildNeedsCareUntil","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordTypeChildNeedsCareUntil"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKMedicalCertificateDateRecordTypeChildNeedsCareUntil","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType~1childNeedsCareUntil\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordTypeChildNeedsCareUntil"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType~1childNeedsCareUntil\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateDateRecordType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType\/fragments","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateDateRecordType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}