{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"photoQualityPrioritization"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKCapturePhotoQualityPrioritization","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCapturePhotoQualityPrioritization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/photoQualityPrioritization"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraSession(py)photoQualityPrioritization","symbolKind":"property","roleHeading":"Instance Property","title":"photoQualityPrioritization","navigatorTitle":[{"text":"photoQualityPrioritization","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"photoQualityPrioritization","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCapturePhotoQualityPrioritization","kind":"typeIdentifier","text":"SBSDKCapturePhotoQualityPrioritization"}]},"abstract":[{"text":"The prioritization of still image quality and capturing speed.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced","type":"reference"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcamerasession\/photoqualityprioritization"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcamerasession\/photoqualityprioritization"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCapturePhotoQualityPrioritization":{"type":"topic","title":"SBSDKCapturePhotoQualityPrioritization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization","url":"\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}],"abstract":[{"text":"The prioritization of still image quality and capturing speed.","type":"text"}],"navigatorTitle":[{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","role":"symbol","abstract":[{"type":"text","text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the"},{"text":" ","type":"text"},{"type":"text","text":"camera device and the preview layer. Provides functionality to capture still images."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSession"}],"title":"SBSDKCameraSession","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraSession","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/photoQualityPrioritization":{"role":"symbol","navigatorTitle":[{"text":"photoQualityPrioritization","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/photoqualityprioritization","kind":"symbol","abstract":[{"type":"text","text":"The prioritization of still image quality and capturing speed."},{"text":" ","type":"text"},{"type":"text","text":"Defaults to "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced","isActive":true},{"type":"text","text":"."}],"title":"photoQualityPrioritization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/photoQualityPrioritization","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"photoQualityPrioritization","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCapturePhotoQualityPrioritization","text":"SBSDKCapturePhotoQualityPrioritization"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCapturePhotoQualityPrioritization/balanced":{"role":"symbol","navigatorTitle":[{"text":"SBSDKCapturePhotoQualityPrioritizationBalanced","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization\/balanced","kind":"symbol","abstract":[{"type":"text","text":"Balances capturing speed and image quality equally. This is the default value."}],"title":"SBSDKCapturePhotoQualityPrioritization.balanced","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"balanced","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"photoQualityPrioritization","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"photoQualityPrioritization"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCapturePhotoQualityPrioritization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization"},{"text":" ","kind":"text"},{"text":"photoQualityPrioritization","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKCapturePhotoQualityPrioritization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization\/fragments","value":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritization"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/title","value":"SBSDKCameraSession"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/fragments","value":[{"text":"SBSDKCameraSession","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1photoQualityPrioritization\/title","value":"photoQualityPrioritization","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1photoQualityPrioritization\/fragments","op":"replace","value":[{"text":"photoQualityPrioritization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization~1balanced\/title","value":"SBSDKCapturePhotoQualityPrioritizationBalanced","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritizationBalanced"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization~1balanced\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}