{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcamerasession\/resumedetection()"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcamerasession\/resumedetection()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Resumes the delivery of frames to the delegate.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/resumeDetection()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resumeDetection"},{"kind":"text","text":"()"}]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraSession(im)resumeDetection","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"resumeDetection"}],"title":"resumeDetection()","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"resumeDetection","kind":"identifier"},{"text":"()","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession":{"navigatorTitle":[{"text":"SBSDKCameraSession","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the"},{"text":" ","type":"text"},{"type":"text","text":"camera device and the preview layer. Provides functionality to capture still images."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKCameraSession","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession","title":"SBSDKCameraSession"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/resumeDetection()":{"abstract":[{"text":"Resumes the delivery of frames to the delegate.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"resumeDetection"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/resumeDetection()","title":"resumeDetection()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resumeDetection"},{"kind":"text","text":"()"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/resumedetection()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"resumeDetection","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"resumeDetection","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"resumeDetection","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/title","value":"SBSDKCameraSession"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/fragments","value":[{"text":"SBSDKCameraSession","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1resumeDetection()\/title","value":"resumeDetection","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1resumeDetection()\/fragments","value":[{"kind":"text","text":"- "},{"text":"resumeDetection","kind":"identifier"}],"op":"replace"}]}]}