{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession"]]},"abstract":[{"type":"text","text":"Sets or gets the current video frame resolution."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcamerasession\/videoframeresolution"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcamerasession\/videoframeresolution"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoFrameResolution"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution","text":"SBSDKVideoFrameResolution","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoFrameResolution"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"title":"videoFrameResolution","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraSession(py)videoFrameResolution","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoFrameResolution","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKVideoFrameResolution","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoFrameResolution"}],"navigatorTitle":[{"text":"videoFrameResolution","kind":"identifier"}],"role":"symbol"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/videoFrameResolution"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession/videoFrameResolution":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession\/videoFrameResolution","navigatorTitle":[{"text":"videoFrameResolution","kind":"identifier"}],"title":"videoFrameResolution","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession\/videoframeresolution","abstract":[{"type":"text","text":"Sets or gets the current video frame resolution."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"videoFrameResolution","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKVideoFrameResolution","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoFrameResolution"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession":{"navigatorTitle":[{"text":"SBSDKCameraSession","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession","kind":"symbol","title":"SBSDKCameraSession","role":"symbol","abstract":[{"type":"text","text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the"},{"type":"text","text":" "},{"text":"camera device and the preview layer. Provides functionality to capture still images.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCameraSession"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFrameResolution":{"url":"\/documentation\/scanbotsdk\/sbsdkvideoframeresolution","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution","type":"topic","abstract":[{"type":"text","text":"An enum describing the resolution of a video or camera stream."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"role":"symbol","title":"SBSDKVideoFrameResolution"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"videoFrameResolution","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"videoFrameResolution","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoFrameResolution","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution","kind":"typeIdentifier","text":"SBSDKVideoFrameResolution"},{"kind":"text","text":" "},{"text":"videoFrameResolution","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"videoFrameResolution","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1videoFrameResolution\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession~1videoFrameResolution\/fragments","value":[{"kind":"identifier","text":"videoFrameResolution"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/title","value":"SBSDKCameraSession"},{"op":"replace","value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraSession"}]},{"value":"SBSDKVideoFrameResolution","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution\/fragments","op":"replace","value":[{"text":"SBSDKVideoFrameResolution","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution\/navigatorTitle","value":[{"text":"SBSDKVideoFrameResolution","kind":"identifier"}]}]}]}