{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerConfiguration\/behaviorConfiguration","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"The configuration for behavior."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerconfiguration\/behaviorconfiguration"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerconfiguration\/behaviorconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerConfiguration(py)behaviorConfiguration","role":"symbol","title":"behaviorConfiguration","navigatorTitle":[{"text":"behaviorConfiguration","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"behaviorConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerBehaviorConfiguration","kind":"typeIdentifier","text":"SBSDKUITextDataScannerBehaviorConfiguration"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"behaviorConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerBehaviorConfiguration","text":"SBSDKUITextDataScannerBehaviorConfiguration"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerConfiguration/behaviorConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerconfiguration\/behaviorconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerConfiguration\/behaviorConfiguration","abstract":[{"type":"text","text":"The configuration for behavior."}],"role":"symbol","title":"behaviorConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"behaviorConfiguration"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"behaviorConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUITextDataScannerBehaviorConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerBehaviorConfiguration"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerConfiguration":{"abstract":[{"type":"text","text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI text data scanner."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUITextDataScannerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerconfiguration","kind":"symbol","title":"SBSDKUITextDataScannerConfiguration","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUITextDataScannerConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerBehaviorConfiguration":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUITextDataScannerBehaviorConfiguration"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUITextDataScannerBehaviorConfiguration"}],"title":"SBSDKUITextDataScannerBehaviorConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerbehaviorconfiguration","abstract":[{"type":"text","text":"Configuration for the behavior of RTU-UI text data scanner."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"behaviorConfiguration"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"behaviorConfiguration"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"text":"SBSDKUITextDataScannerBehaviorConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerBehaviorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"behaviorConfiguration","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerConfiguration~1behaviorConfiguration\/title","op":"replace","value":"behaviorConfiguration"},{"value":[{"kind":"identifier","text":"behaviorConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerConfiguration~1behaviorConfiguration\/fragments","op":"replace"},{"value":"SBSDKUITextDataScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUITextDataScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerConfiguration\/navigatorTitle","value":[{"text":"SBSDKUITextDataScannerConfiguration","kind":"identifier"}]},{"value":"SBSDKUITextDataScannerBehaviorConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration\/fragments","value":[{"text":"SBSDKUITextDataScannerBehaviorConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUITextDataScannerBehaviorConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}