{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"issueTimeStamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"issueTimeStamp","kind":"identifier"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVADLID(py)issueTimeStamp","roleHeading":"Instance Property","title":"issueTimeStamp"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvadlid\/issuetimestamp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvadlid\/issuetimestamp"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","abstract":[{"text":"Data element ID “DBE”. A string used by some jurisdictions to validate the document against their data base.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"issueTimeStamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVADLID\/issueTimeStamp","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVADLID"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVADLID/issueTimeStamp":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"issueTimeStamp"}],"role":"symbol","title":"issueTimeStamp","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVADLID\/issueTimeStamp","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvadlid\/issuetimestamp","abstract":[{"text":"Data element ID “DBE”. A string used by some jurisdictions to validate the document against their data base.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"issueTimeStamp"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"title":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","abstract":[{"type":"text","text":"A generic document field."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVADLID":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVADLID","abstract":[{"type":"text","text":"Driver License Or ID Document."}],"title":"SBSDKBarcodeDocumentAAMVADLID","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVADLID"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVADLID"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvadlid"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"issueTimeStamp","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"issueTimeStamp"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"issueTimeStamp","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"issueTimeStamp","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVADLID~1issueTimeStamp\/title","op":"replace"},{"value":[{"kind":"identifier","text":"issueTimeStamp"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVADLID~1issueTimeStamp\/fragments","op":"replace"},{"value":"SBSDKGenericDocumentField","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments","op":"replace"},{"value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle","op":"replace"},{"value":"SBSDKBarcodeDocumentAAMVADLID","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVADLID\/title","op":"replace"},{"value":[{"text":"SBSDKBarcodeDocumentAAMVADLID","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVADLID\/fragments","op":"replace"},{"value":[{"text":"SBSDKBarcodeDocumentAAMVADLID","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVADLID\/navigatorTitle","op":"replace"}]}]}