{"metadata":{"navigatorTitle":[{"text":"SBSDKMedicalCertificateDateRecordTypeDocumentDate","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateDateRecordType@SBSDKMedicalCertificateDateRecordTypeDocumentDate","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDate"}],"title":"SBSDKMedicalCertificateDateRecordType.documentDate","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype\/documentdate"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype\/documentdate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType"]]},"abstract":[{"type":"text","text":"Document date."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType\/documentDate","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDate","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecordType/documentDate":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDate"}],"abstract":[{"text":"Document date.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype\/documentdate","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType\/documentDate","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordTypeDocumentDate"}],"title":"SBSDKMedicalCertificateDateRecordType.documentDate","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecordType":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordType"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordType"}],"type":"topic","title":"SBSDKMedicalCertificateDateRecordType","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType","abstract":[{"type":"text","text":"Type of a date record."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalCertificateDateRecordTypeDocumentDate"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKMedicalCertificateDateRecordTypeDocumentDate","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKMedicalCertificateDateRecordTypeDocumentDate","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"SBSDKMedicalCertificateDateRecordTypeDocumentDate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType~1documentDate\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType~1documentDate\/fragments","value":[{"text":"SBSDKMedicalCertificateDateRecordTypeDocumentDate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType\/title","value":"SBSDKMedicalCertificateDateRecordType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType\/fragments","value":[{"text":"SBSDKMedicalCertificateDateRecordType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}