{"sections":[],"abstract":[{"type":"text","text":"If true, the barcode scanner will only return barcodes that pass the strict validation checks according to"},{"text":" ","type":"text"},{"text":"standards to avoid false positives.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatgs1compositeconfiguration\/strictmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatgs1compositeconfiguration\/strictmode"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"strictMode","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"strictMode","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"strictMode","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatGS1CompositeConfiguration(py)strictMode","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration\/strictMode"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"strictMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Default is true","type":"text"}]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatGS1CompositeConfiguration":{"abstract":[{"type":"text","text":"GS1 Composite configuration. Add to scanner configuration to scan GS1 Composite barcodes."}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatGS1CompositeConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatgs1compositeconfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatGS1CompositeConfiguration","kind":"identifier"}],"role":"symbol","title":"SBSDKBarcodeFormatGS1CompositeConfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatGS1CompositeConfiguration/strictMode":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"strictMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"If true, the barcode scanner will only return barcodes that pass the strict validation checks according to"},{"type":"text","text":" "},{"type":"text","text":"standards to avoid false positives."}],"navigatorTitle":[{"text":"strictMode","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration\/strictMode","title":"strictMode","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatgs1compositeconfiguration\/strictmode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"strictMode","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"strictMode"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"strictMode","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/title","value":"SBSDKBarcodeFormatGS1CompositeConfiguration","op":"replace"},{"op":"replace","value":[{"text":"SBSDKBarcodeFormatGS1CompositeConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"}],"op":"replace"},{"value":"strictMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration~1strictMode\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration~1strictMode\/fragments","value":[{"text":"strictMode","kind":"identifier"}],"op":"replace"}]}]}