{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/Equatable-Implementations"},"metadata":{"title":"Equatable Implementations","role":"collectionGroup","modules":[{"name":"ScanbotSDK"}],"roleHeading":"API Collection"},"topicSections":[{"title":"Operators","generated":true,"anchor":"Operators","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/!=(_:_:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/equatable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType"]]},"kind":"article","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/!=(_:_:)":{"type":"topic","role":"symbol","abstract":[],"title":"!=(_:_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/!=(_:_:)","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/!=(_:_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType":{"abstract":[{"type":"text","text":"Type of a field in the patient info box."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype","kind":"symbol","title":"SBSDKMedicalCertificatePatientInfoFieldType","navigatorTitle":[{"text":"SBSDKMedicalCertificatePatientInfoFieldType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKMedicalCertificatePatientInfoFieldType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType\/title","value":"SBSDKMedicalCertificatePatientInfoFieldType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificatePatientInfoFieldType","kind":"identifier"}]}]}]}