{"metadata":{"title":"maxCountryDetectionAttempts","navigatorTitle":[{"kind":"identifier","text":"maxCountryDetectionAttempts"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognizerParameters(py)maxCountryDetectionAttempts","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxCountryDetectionAttempts"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxCountryDetectionAttempts","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}]}]},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"Defaults to 5."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters\/maxCountryDetectionAttempts"},"abstract":[{"type":"text","text":"Maximum number of attempts before giving up on country detection."},{"type":"text","text":" "},{"type":"text","text":"After the specified number of attempts, the country field is considered to be unknown and validation is skipped. This option is neglected if "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters\/acceptedCountries"},{"type":"text","text":" contains only a single country, which will be used for field validations."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters\/maxcountrydetectionattempts"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters\/maxcountrydetectionattempts"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerParameters":{"abstract":[{"type":"text","text":"The health insurance card recognizer configuration."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerParameters"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerParameters"}],"title":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerParameters/acceptedCountries":{"title":"acceptedCountries","navigatorTitle":[{"text":"acceptedCountries","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters\/acceptedcountries","kind":"symbol","abstract":[{"text":"List of allowed countries for the health insurance card recognizer.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters\/acceptedCountries","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"acceptedCountries","kind":"identifier"},{"kind":"text","text":": ["},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"},{"text":"]","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerParameters/maxCountryDetectionAttempts":{"title":"maxCountryDetectionAttempts","navigatorTitle":[{"kind":"identifier","text":"maxCountryDetectionAttempts"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters\/maxcountrydetectionattempts","kind":"symbol","abstract":[{"type":"text","text":"Maximum number of attempts before giving up on country detection."},{"text":" ","type":"text"},{"type":"text","text":"After the specified number of attempts, the country field is considered to be unknown and validation is skipped. This option is neglected if "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters\/acceptedCountries","type":"reference"},{"type":"text","text":" contains only a single country, which will be used for field validations."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters\/maxCountryDetectionAttempts","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxCountryDetectionAttempts","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"maxCountryDetectionAttempts"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"maxCountryDetectionAttempts"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"maxCountryDetectionAttempts","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKHealthInsuranceCardRecognizerParameters","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/fragments","value":[{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters~1acceptedCountries\/title","value":"acceptedCountries","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"acceptedCountries"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters~1acceptedCountries\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters~1maxCountryDetectionAttempts\/title","value":"maxCountryDetectionAttempts"},{"op":"replace","value":[{"kind":"identifier","text":"maxCountryDetectionAttempts"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters~1maxCountryDetectionAttempts\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}