{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters\/maxExpirationYear"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxExpirationYear"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"text":"Defaults to 2999.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"title":"maxExpirationYear","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognizerParameters(py)maxExpirationYear","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"maxExpirationYear","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"maxExpirationYear"}],"role":"symbol","roleHeading":"Instance Property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"Maximum ranges of card-expiration-year."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters\/maxexpirationyear"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters\/maxexpirationyear"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerParameters":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerParameters"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters","title":"SBSDKHealthInsuranceCardRecognizerParameters","type":"topic","abstract":[{"text":"The health insurance card recognizer configuration.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerParameters/maxExpirationYear":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters\/maxExpirationYear","type":"topic","kind":"symbol","abstract":[{"text":"Maximum ranges of card-expiration-year.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters\/maxexpirationyear","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxExpirationYear","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"maxExpirationYear"}],"title":"maxExpirationYear","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"maxExpirationYear","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"maxExpirationYear","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxExpirationYear"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/title","value":"SBSDKHealthInsuranceCardRecognizerParameters","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/fragments","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters~1maxExpirationYear\/title","value":"maxExpirationYear"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters~1maxExpirationYear\/fragments","value":[{"text":"maxExpirationYear","kind":"identifier"}]}]}]}