{"kind":"symbol","metadata":{"title":"minEqualFrameCount","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minEqualFrameCount","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognizerParameters(py)minEqualFrameCount","navigatorTitle":[{"kind":"identifier","text":"minEqualFrameCount"}],"roleHeading":"Instance Property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minEqualFrameCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Defaults to 4.","type":"text"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Minimum number of accumulated frames that should have equal result for a field."},{"type":"text","text":" "},{"text":"Once satisfied, the corresponding field is considered to be successfully-recognized and won’t be considered in the subsequent frames.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters\/minEqualFrameCount","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters\/minequalframecount"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters\/minequalframecount"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerParameters/minEqualFrameCount":{"role":"symbol","type":"topic","abstract":[{"text":"Minimum number of accumulated frames that should have equal result for a field.","type":"text"},{"text":" ","type":"text"},{"text":"Once satisfied, the corresponding field is considered to be successfully-recognized and won’t be considered in the subsequent frames.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minEqualFrameCount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters\/minequalframecount","navigatorTitle":[{"kind":"identifier","text":"minEqualFrameCount"}],"title":"minEqualFrameCount","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters\/minEqualFrameCount","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerParameters":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The health insurance card recognizer configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerParameters"}],"title":"SBSDKHealthInsuranceCardRecognizerParameters","navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerParameters"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"minEqualFrameCount"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"minEqualFrameCount","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"text":" ","kind":"text"},{"text":"minEqualFrameCount","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters~1minEqualFrameCount\/title","value":"minEqualFrameCount"},{"value":[{"text":"minEqualFrameCount","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters~1minEqualFrameCount\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/title","value":"SBSDKHealthInsuranceCardRecognizerParameters","op":"replace"},{"value":[{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizerParameters"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}