{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanCompletionOverlay"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2scancompletionoverlay\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Type Method","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"fromJsonWithJson:","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ScanCompletionOverlay(cm)fromJsonWithJson:","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ScanCompletionOverlay","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanCompletionOverlay","text":"SBSDKUI2ScanCompletionOverlay"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromJsonWithJson:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"json"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanCompletionOverlay\/fromJsonWithJson:"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ScanCompletionOverlay":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ScanCompletionOverlay","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanCompletionOverlay","abstract":[{"text":"Configuration of the overlay to be shown after the successful scan.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2scancompletionoverlay","title":"SBSDKUI2ScanCompletionOverlay","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2ScanCompletionOverlay","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 8.0.4","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ScanCompletionOverlay/fromJsonWithJson:":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanCompletionOverlay\/fromJsonWithJson:","abstract":[],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"title":"fromJsonWithJson:","role":"symbol","type":"topic","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2scancompletionoverlay\/fromjsonwithjson:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanCompletionOverlay\/title","op":"replace","value":"SBSDKUI2ScanCompletionOverlay"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanCompletionOverlay\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ScanCompletionOverlay"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanCompletionOverlay\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2ScanCompletionOverlay","kind":"identifier"}]}]}]}