{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentAnimationConfiguration(im)initWithAppearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Initializer","role":"symbol","title":"init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appearanceDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"displayDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"disappearanceDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"overlayColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"imageContentMode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIViewContentMode","text":"ContentMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"finalFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithAppearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentAnimationConfiguration\/init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"appearanceDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" = 0.2, ","kind":"text"},{"text":"displayDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" = 0.4, ","kind":"text"},{"text":"disappearanceDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" = 0.2, ","kind":"text"},{"text":"overlayColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":" = .black.withAlphaComponent(0.3), "},{"kind":"externalParam","text":"imageContentMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIViewContentMode","text":"ContentMode"},{"kind":"text","text":" = .scaleAspectFit, "},{"kind":"externalParam","text":"finalFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":" = .zero)"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The amount of time the document takes to appear."}],"type":"paragraph"}],"name":"appearanceDuration"},{"content":[{"inlineContent":[{"type":"text","text":"The display time for the document, before it animates to the provided valid final frame or disappear otherwise."}],"type":"paragraph"}],"name":"displayDuration"},{"content":[{"inlineContent":[{"text":"The amount of time the document takes to disappear or animate to the final frame.","type":"text"}],"type":"paragraph"}],"name":"disappearanceDuration"},{"content":[{"inlineContent":[{"type":"text","text":"The color used to overlay the camera screen during the animation."}],"type":"paragraph"}],"name":"overlayColor"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The content mode for the document’s image view being animated."}]}],"name":"imageContentMode"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The final frame where the animated document should animate to."}]}],"name":"finalFrame"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentanimationconfiguration\/init(appearanceduration:displayduration:disappearanceduration:overlaycolor:imagecontentmode:finalframe:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentanimationconfiguration\/init(appearanceduration:displayduration:disappearanceduration:overlaycolor:imagecontentmode:finalframe:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentAnimationConfiguration"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Creates a new instance of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentAnimationConfiguration","type":"reference","isActive":true},{"text":".","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentAnimationConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentAnimationConfiguration"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentanimationconfiguration","title":"SBSDKDocumentAnimationConfiguration","abstract":[{"type":"text","text":"A class to configure the document animation properties."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentAnimationConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentAnimationConfiguration"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentAnimationConfiguration/init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentanimationconfiguration\/init(appearanceduration:displayduration:disappearanceduration:overlaycolor:imagecontentmode:finalframe:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"appearanceDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"displayDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"disappearanceDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"overlayColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"imageContentMode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIViewContentMode","text":"ContentMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"finalFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentAnimationConfiguration\/init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)","title":"init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)","navigatorTitle":[{"text":"initWithAppearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:","kind":"identifier"}],"abstract":[{"text":"Creates a new instance of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentAnimationConfiguration","isActive":true,"type":"reference"},{"text":".","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithAppearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithAppearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAppearanceDuration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"appearanceDuration"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayDuration:"},{"kind":"text","text":"("},{"text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"displayDuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"disappearanceDuration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"disappearanceDuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"overlayColor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"overlayColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"imageContentMode:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@UIViewContentMode","text":"UIViewContentMode","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"imageContentMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":") ","kind":"text"},{"text":"finalFrame","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The amount of time the document takes to appear."}]}],"name":"appearanceDuration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The display time for the document, before it animates to the provided valid final frame or disappear otherwise."}]}],"name":"displayDuration"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The amount of time the document takes to disappear or animate to the final frame.","type":"text"}]}],"name":"disappearanceDuration"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The color used to overlay the camera screen during the animation.","type":"text"}]}],"name":"overlayColor"},{"content":[{"inlineContent":[{"type":"text","text":"The content mode for the document’s image view being animated."}],"type":"paragraph"}],"name":"imageContentMode"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The final frame where the animated document should animate to.","type":"text"}]}],"name":"finalFrame"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SBSDKDocumentAnimationConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentAnimationConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentAnimationConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentAnimationConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentAnimationConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentAnimationConfiguration\/navigatorTitle"},{"op":"replace","value":"initWithAppearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentAnimationConfiguration~1init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithAppearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentAnimationConfiguration~1init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}