{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2nointroimage\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2nointroimage\/init()"]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoIntroImage\/init()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoIntroImage"]]},"metadata":{"title":"init()","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2NoIntroImage(im)init","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","symbolKind":"init","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2NoIntroImage":{"type":"topic","title":"SBSDKUI2NoIntroImage","navigatorTitle":[{"text":"SBSDKUI2NoIntroImage","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2nointroimage","abstract":[{"text":"No image for the introduction screen.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2NoIntroImage","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoIntroImage","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2NoIntroImage/init()":{"abstract":[],"title":"init()","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoIntroImage\/init()","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2nointroimage\/init()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoIntroImage\/title","value":"SBSDKUI2NoIntroImage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoIntroImage\/fragments","value":[{"text":"SBSDKUI2NoIntroImage","kind":"identifier"}]},{"op":"replace","value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoIntroImage~1init()\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoIntroImage~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"op":"replace"}]}]}