{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/permission"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"cancel","externalID":"s:10ScanbotSDK32SBSDKUI2DataCaptureAccessibilityC10permissionC6cancelSSvpZ","symbolKind":"property","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"roleHeading":"Type Property"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/permission\/cancel"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/permission\/cancel"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility/permission/cancel":{"role":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/permission\/cancel","type":"topic","title":"cancel","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/permission\/cancel","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility/permission":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/permission","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/permission","title":"SBSDKUI2DataCaptureAccessibility.permission","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"permission","kind":"identifier"}],"navigatorTitle":[{"text":"permission","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility","navigatorTitle":[{"text":"SBSDKUI2DataCaptureAccessibility","kind":"identifier"}],"title":"SBSDKUI2DataCaptureAccessibility","abstract":[{"type":"text","text":"Accessibility identifiers to be used in UI tests for the data capture scanner RTU-UI V2 (MRZ, credit card, text pattern).."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DataCaptureAccessibility","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2DataCaptureAccessibility","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DataCaptureAccessibility\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2DataCaptureAccessibility"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DataCaptureAccessibility\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2DataCaptureAccessibility"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DataCaptureAccessibility\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}