{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/permission\/settings"},"metadata":{"roleHeading":"Type Property","symbolKind":"property","title":"settings","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"settings","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"s:10ScanbotSDK32SBSDKUI2DataCaptureAccessibilityC10permissionC8settingsSSvpZ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/permission"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/permission\/settings"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility/permission/settings":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/permission\/settings","title":"settings","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"settings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/permission\/settings"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility/permission":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/permission","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/permission","title":"SBSDKUI2DataCaptureAccessibility.permission","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"permission","kind":"identifier"}],"navigatorTitle":[{"text":"permission","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility","navigatorTitle":[{"text":"SBSDKUI2DataCaptureAccessibility","kind":"identifier"}],"title":"SBSDKUI2DataCaptureAccessibility","abstract":[{"type":"text","text":"Accessibility identifiers to be used in UI tests for the data capture scanner RTU-UI V2 (MRZ, credit card, text pattern).."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DataCaptureAccessibility","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2DataCaptureAccessibility","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DataCaptureAccessibility\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DataCaptureAccessibility"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DataCaptureAccessibility\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DataCaptureAccessibility"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DataCaptureAccessibility\/navigatorTitle"}]}]}