{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"vibrate","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"vibrate","kind":"identifier"}],"title":"vibrate()","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSoundController(im)vibrate","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"vibrate","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/vibrate()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initiates a short vibration of the device. Can be used to give a haptic feedback."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdksoundcontroller\/vibrate()"]},{"paths":["\/documentation\/scanbotsdk\/sbsdksoundcontroller\/vibrate()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundController":{"url":"\/documentation\/scanbotsdk\/sbsdksoundcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController","kind":"symbol","navigatorTitle":[{"text":"SBSDKSoundController","kind":"identifier"}],"abstract":[{"type":"text","text":"A class to manage playback of sounds and vibration."}],"type":"topic","role":"symbol","title":"SBSDKSoundController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKSoundController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSoundController/vibrate()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSoundController\/vibrate()","title":"vibrate()","url":"\/documentation\/scanbotsdk\/sbsdksoundcontroller\/vibrate()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vibrate"},{"text":"()","kind":"text"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Initiates a short vibration of the device. Can be used to give a haptic feedback."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"vibrate"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"vibrate","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"vibrate"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"vibrate","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController\/title","value":"SBSDKSoundController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController\/fragments","value":[{"text":"SBSDKSoundController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKSoundController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController~1vibrate()\/title","value":"vibrate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSoundController~1vibrate()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"vibrate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}