{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2twolinemrzfinderlayoutpreset\/isequal:"]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset\/isEqual:","interfaceLanguage":"occ"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"role":"symbol","title":"isEqual:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TwoLineMRZFinderLayoutPreset(im)isEqual:","roleHeading":"Instance Method","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TwoLineMRZFinderLayoutPreset/isEqual:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset\/isEqual:","url":"\/documentation\/scanbotsdk\/sbsdkui2twolinemrzfinderlayoutpreset\/isequal:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"abstract":[],"role":"symbol","title":"isEqual:","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TwoLineMRZFinderLayoutPreset":{"kind":"symbol","type":"topic","role":"symbol","title":"SBSDKUI2TwoLineMRZFinderLayoutPreset","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"identifier"}],"abstract":[{"type":"text","text":"A ready-to-use preset 2-line text to be displayed."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2twolinemrzfinderlayoutpreset","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset","navigatorTitle":[{"text":"SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2TwoLineMRZFinderLayoutPreset","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TwoLineMRZFinderLayoutPreset\/title","op":"replace"},{"value":[{"text":"SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TwoLineMRZFinderLayoutPreset\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TwoLineMRZFinderLayoutPreset\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}