{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Modulo 1010."}],"metadata":{"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Type Property","title":"mod1010","navigatorTitle":[{"text":"mod1010","kind":"identifier"}],"symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mod1010","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm(cpy)mod1010"},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMSIPlesseyChecksumAlgorithm\/mod1010","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mod1010"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm","text":"SBSDKMSIPlesseyChecksumAlgorithm","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMSIPlesseyChecksumAlgorithm"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMSIPlesseyChecksumAlgorithm"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkmsiplesseychecksumalgorithm\/mod1010"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkmsiplesseychecksumalgorithm\/mod1010"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMSIPlesseyChecksumAlgorithm/mod1010":{"abstract":[{"type":"text","text":"Modulo 1010."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mod1010"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKMSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm"}],"navigatorTitle":[{"kind":"identifier","text":"mod1010"}],"title":"mod1010","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMSIPlesseyChecksumAlgorithm\/mod1010","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmsiplesseychecksumalgorithm\/mod1010","type":"topic","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.0","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMSIPlesseyChecksumAlgorithm":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmsiplesseychecksumalgorithm","navigatorTitle":[{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMSIPlesseyChecksumAlgorithm","type":"topic","title":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"symbol","abstract":[{"type":"text","text":"Checksum algorithm for MSI_PLESSEY."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"mod1010"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"mod1010"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm","text":"SBSDKMSIPlesseyChecksumAlgorithm","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMSIPlesseyChecksumAlgorithm","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"mod1010","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMSIPlesseyChecksumAlgorithm~1mod1010\/title","op":"replace","value":"mod1010"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMSIPlesseyChecksumAlgorithm~1mod1010\/fragments","op":"replace","value":[{"kind":"identifier","text":"mod1010"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/title","op":"replace","value":"SBSDKMSIPlesseyChecksumAlgorithm"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMSIPlesseyChecksumAlgorithm"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/navigatorTitle","op":"replace","value":[{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}