{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Method","title":"extract(from:)","role":"symbol","navigatorTitle":[{"text":"extractFromPDF:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKPDFImageExtractor(im)extractFromPDF:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"extract","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"]"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFImageExtractor\/extract(from:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFImageExtractor"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfimageextractor\/extract(from:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfimageextractor\/extract(from:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Extracts images from PDF and converts them to an array of "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":". Nothing is written to disk during this operation. Runs in the same thread, as it is called from."},{"type":"text","text":" "},{"text":"The scaling of the media box is set to 2.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(extractFromPDF:) ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"extract"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":" "},{"text":"pdfURL","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"pdfURL","content":[{"inlineContent":[{"text":"The URL of the PDF file.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of "},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" with extracted images. The array will be empty if something is wrong."}]}],"kind":"content"}],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPDFImageExtractor":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfimageextractor","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFImageExtractor","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Class used to extract images from a PDF file and returns them in various ways."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFImageExtractor"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFImageExtractor","title":"SBSDKPDFImageExtractor"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPDFImageExtractor/extract(from:)":{"abstract":[{"text":"Extracts images from PDF and converts them to an array of ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":". Nothing is written to disk during this operation. Runs in the same thread, as it is called from."},{"type":"text","text":" "},{"text":"The scaling of the media box is set to 2.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFImageExtractor\/extract(from:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"extract","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":") -> ["},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"extractFromPDF:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfimageextractor\/extract(from:)","title":"extract(from:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"extractFromPDF:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"extractFromPDF:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSArray<UIImage *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"extractFromPDF:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"text":" *) ","kind":"text"},{"text":"pdfURL","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"pdfURL","content":[{"inlineContent":[{"type":"text","text":"The URL of the PDF file."}],"type":"paragraph"}]}],"kind":"parameters"}},{"value":{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"An array of ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"text":" with extracted images. The array will be empty if something is wrong.","type":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"SBSDKPDFImageExtractor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFImageExtractor\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFImageExtractor\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFImageExtractor"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFImageExtractor\/navigatorTitle","op":"replace","value":[{"text":"SBSDKPDFImageExtractor","kind":"identifier"}]},{"op":"replace","value":"extractFromPDF:","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFImageExtractor~1extract(from:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFImageExtractor~1extract(from:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"extractFromPDF:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}