{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"code93"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat","kind":"typeIdentifier"}],"title":"code93","navigatorTitle":[{"kind":"identifier","text":"code93"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat(cpy)code93","roleHeading":"Type Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"code93"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat","text":"SBSDKUI2BarcodeFormat"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Code 93 barcode type"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat\/code93","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeformat\/code93"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeformat\/code93"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeFormat":{"kind":"symbol","title":"SBSDKUI2BarcodeFormat","abstract":[{"text":"Barcode symbology used.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeformat","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeFormat"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeFormat","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeFormat/code93":{"kind":"symbol","navigatorTitle":[{"text":"code93","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeformat\/code93","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"code93"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat","text":"SBSDKUI2BarcodeFormat"}],"abstract":[{"type":"text","text":"Code 93 barcode type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat\/code93","role":"symbol","type":"topic","title":"code93"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"code93","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"code93"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"SBSDKUI2BarcodeFormat","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat"},{"kind":"text","text":" * "},{"kind":"identifier","text":"code93"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat\/title","value":"SBSDKUI2BarcodeFormat","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat~1code93\/title","op":"replace","value":"code93"},{"value":[{"text":"code93","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat~1code93\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}