{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat\/dataMatrix","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeformat\/datamatrix"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeformat\/datamatrix"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Data Matrix barcode type"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"dataMatrix"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","roleHeading":"Type Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat(cpy)dataMatrix","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataMatrix"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat","kind":"typeIdentifier"}],"role":"symbol","title":"dataMatrix"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"dataMatrix","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat","text":"SBSDKUI2BarcodeFormat"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeFormat":{"type":"topic","title":"SBSDKUI2BarcodeFormat","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeformat","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeFormat"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat","abstract":[{"type":"text","text":"Barcode symbology used."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeFormat","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeFormat/dataMatrix":{"abstract":[{"type":"text","text":"Data Matrix barcode type"}],"type":"topic","title":"dataMatrix","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"dataMatrix","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat\/dataMatrix","navigatorTitle":[{"text":"dataMatrix","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeformat\/datamatrix","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","value":"dataMatrix","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dataMatrix"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat","text":"SBSDKUI2BarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"dataMatrix","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUI2BarcodeFormat","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat\/fragments","value":[{"text":"SBSDKUI2BarcodeFormat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2BarcodeFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat~1dataMatrix\/title","value":"dataMatrix"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat~1dataMatrix\/fragments","op":"replace","value":[{"kind":"identifier","text":"dataMatrix"}]}]}]}