{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat\/ean8"},"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","navigatorTitle":[{"text":"ean8","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ean8"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat"}],"title":"ean8","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat(cpy)ean8","roleHeading":"Type Property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ean8"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat","text":"SBSDKUI2BarcodeFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeformat\/ean8"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeformat\/ean8"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"EAN-8 barcode type"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeFormat/ean8":{"navigatorTitle":[{"text":"ean8","kind":"identifier"}],"abstract":[{"text":"EAN-8 barcode type","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"ean8","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat\/ean8","type":"topic","title":"ean8","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeformat\/ean8","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeFormat":{"type":"topic","title":"SBSDKUI2BarcodeFormat","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeformat","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeFormat"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat","abstract":[{"type":"text","text":"Barcode symbology used."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeFormat","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"op":"replace","value":"ean8","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ean8"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat","text":"SBSDKUI2BarcodeFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"ean8"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat~1ean8\/title","value":"ean8","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat~1ean8\/fragments","value":[{"kind":"identifier","text":"ean8"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat\/title","value":"SBSDKUI2BarcodeFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeFormat"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeFormat"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}