{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/initwithcameratopbarcancelbuttontitle:cameratopbartitle:cameratopguidance:camerauserguidancestart:camerauserguidancenodocumentfound:camerauserguidancebadaspectratio:camerauserguidanceorientationmismatch:camerauserguidancebadangles:camerause-3zazc"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCameraTopBarCancelButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraTopBarCancelButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraTopBarTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraTopBarTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraTopGuidance:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraTopGuidance"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraUserGuidanceStart:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraUserGuidanceStart"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraUserGuidanceNoDocumentFound:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraUserGuidanceNoDocumentFound"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraUserGuidanceBadAspectRatio:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraUserGuidanceBadAspectRatio"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraUserGuidanceOrientationMismatch:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraUserGuidanceOrientationMismatch"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraUserGuidanceBadAngles:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraUserGuidanceBadAngles"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraUserGuidanceTooNoisy:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraUserGuidanceTooNoisy"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraUserGuidanceTextHintOffCenter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraUserGuidanceTextHintOffCenter"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraUserGuidanceTooSmall:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"cameraUserGuidanceTooSmall","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceTooDark:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceTooDark","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceEnergySaveMode:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceEnergySaveMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceReadyToCapture:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceReadyToCapture","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceReadyToCaptureManual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceReadyToCaptureManual","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraImportButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraImportButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraTorchOnButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraTorchOnButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraTorchOffButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraTorchOffButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraAutoSnapButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraAutoSnapButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraManualSnapButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraManualSnapButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPreviewButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraPreviewButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraBadgedPreviewButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraBadgedPreviewButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraIntroDoneButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraIntroDoneButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraIntroTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraIntroTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraIntroSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraIntroSubtitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraIntroItem1:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraIntroItem1"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraIntroItem2:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraIntroItem2"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraIntroItem3:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraIntroItem3"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraIntroItem4:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraIntroItem4"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraProgressOverlayTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraProgressOverlayTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraCancelAlertTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraCancelAlertTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraCancelAlertSubtitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraCancelAlertSubtitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraCancelNoButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraCancelNoButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraCancelYesButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraCancelYesButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraLimitReachedAlertTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraLimitReachedAlertTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraLimitReachedAlertSubtitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraLimitReachedAlertSubtitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraLimitReachedOkButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraLimitReachedOkButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"acknowledgementScreenBadDocumentHint:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"acknowledgementScreenBadDocumentHint"},{"kind":"text","text":" "},{"kind":"identifier","text":"acknowledgementRetakeButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"acknowledgementRetakeButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"acknowledgementAcceptButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"acknowledgementAcceptButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewScreenTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewScreenTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewTopBarBackButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewTopBarBackButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewScreenPageCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewScreenPageCount"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewScreenAddButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewScreenAddButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewScreenRetakeButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewScreenRetakeButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewScreenCropButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewScreenCropButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewScreenRotateButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewScreenRotateButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewScreenDeleteButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewScreenDeleteButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewScreenSubmitButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewScreenSubmitButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewScreenDeleteAllButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewScreenDeleteAllButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewScreenReorderPagesButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewScreenReorderPagesButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomOverlayCancelButtonText:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zoomOverlayCancelButtonText"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewDeletePageAlertTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewDeletePageAlertTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewDeleteAllPagesAlertTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewDeleteAllPagesAlertTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewDeletePageAlertSubTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewDeletePageAlertSubTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewDeleteAllPagesAlertSubtitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewDeleteAllPagesAlertSubtitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewDeletePageAlertConfirmButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewDeletePageAlertConfirmButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewDeleteAllPagesAlertDeleteButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewDeleteAllPagesAlertDeleteButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewDeletePageAlertDeleteRetakeButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewDeletePageAlertDeleteRetakeButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewDeletePageAlertCancelButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewDeletePageAlertCancelButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewDeleteAllPagesAlertCancelButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewDeleteAllPagesAlertCancelButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"acknowledgementTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"acknowledgementTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reorderPageTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reorderPageTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reorderPageGuidanceTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reorderPageGuidanceTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reorderPageText:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reorderPageText"},{"kind":"text","text":" "},{"kind":"identifier","text":"reorderTopBarConfirmButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reorderTopBarConfirmButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reorderTopBarCancelButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reorderTopBarCancelButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingTopBarConfirmButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"croppingTopBarConfirmButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingTopBarCancelButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"croppingTopBarCancelButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingDetectButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"croppingDetectButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingRotateButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"croppingRotateButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingResetButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"croppingResetButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingScreenTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"croppingScreenTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraTopBarIntroButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraTopBarIntroButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraTopBarCancelButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraTopBarCancelButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraImportButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraImportButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraTorchOnButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraTorchOnButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraTorchOffButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraTorchOffButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraShutterButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraShutterButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraAutoSnapButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraAutoSnapButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraManualSnapButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraManualSnapButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraPreviewButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraPreviewButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraIntroDoneButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraIntroDoneButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionAcknowledgementRetakeButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionAcknowledgementRetakeButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionAcknowledgementAcceptButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionAcknowledgementAcceptButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingTopBarConfirmButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCroppingTopBarConfirmButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingTopBarCancelButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCroppingTopBarCancelButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingDetectButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCroppingDetectButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingRotateButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCroppingRotateButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingResetButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCroppingResetButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReorderTopBarConfirmButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReorderTopBarConfirmButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReorderTopBarCancelButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReorderTopBarCancelButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewNextPageButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewNextPageButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewPreviousPageButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewPreviousPageButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewAddButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewAddButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewRetakeButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewRetakeButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewCropButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewCropButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewRotateButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewRotateButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewDeleteButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewDeleteButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewSubmitButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewSubmitButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewMoreButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewMoreButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewDeleteAllButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewDeleteAllButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewReorderPagesButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewReorderPagesButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionZoomOverlayCancelButton:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionZoomOverlayCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewZoomButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewZoomButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewTopBarBackButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewTopBarBackButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewDeletePageAlertConfirmButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewDeletePageAlertConfirmButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewDeletePageAlertCancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewDeletePageAlertCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraLimitReachedOkButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraLimitReachedOkButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraCancelYesButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraCancelYesButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraCancelNoButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraCancelNoButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionEnableCameraTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionEnableCameraButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermissionCloseButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionCloseButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"role":"symbol","title":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization(im)initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","symbolKind":"method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization":{"title":"SBSDKUI2DocumentScannerTextLocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Configuration of all the strings for the standalone cropping screen.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization/initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/initwithcameratopbarcancelbuttontitle:cameratopbartitle:cameratopguidance:camerauserguidancestart:camerauserguidancenodocumentfound:camerauserguidancebadaspectratio:camerauserguidanceorientationmismatch:camerauserguidancebadangles:camerause-3zazc","title":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","abstract":[],"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","navigatorTitle":[{"text":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/title","op":"replace","value":"SBSDKUI2DocumentScannerTextLocalization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}