{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/cameraConfiguration"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration"]]},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraConfiguration","text":"SBSDKUI2CameraConfiguration","kind":"typeIdentifier"}],"roleHeading":"Instance Property","title":"cameraConfiguration","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerScreenConfiguration(py)cameraConfiguration","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"cameraConfiguration"}]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Configuration of the camera behavior."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2CameraConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/cameraconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/cameraconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration":{"title":"SBSDKUI2CreditCardScannerScreenConfiguration","abstract":[{"type":"text","text":"Configuration of the screen for detecting credit card data."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardScannerScreenConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2CreditCardScannerScreenConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenConfiguration/cameraConfiguration":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraConfiguration"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenConfiguration\/cameraConfiguration","title":"cameraConfiguration","navigatorTitle":[{"text":"cameraConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreenconfiguration\/cameraconfiguration","abstract":[{"type":"text","text":"Configuration of the camera behavior."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraConfiguration":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration","type":"topic","title":"SBSDKUI2CameraConfiguration","abstract":[{"type":"text","text":"Configuration of the camera settings to be used while scanning."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2cameraconfiguration"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"cameraConfiguration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"cameraConfiguration"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraConfiguration","kind":"typeIdentifier","text":"SBSDKUI2CameraConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cameraConfiguration"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration\/title","op":"replace","value":"SBSDKUI2CreditCardScannerScreenConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2CreditCardScannerScreenConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CreditCardScannerScreenConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1cameraConfiguration\/title","op":"replace","value":"cameraConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenConfiguration~1cameraConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"cameraConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration\/title","op":"replace","value":"SBSDKUI2CameraConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}