{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/Equatable-Implementations","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/equatable-implementations"]}],"topicSections":[{"title":"Operators","generated":true,"anchor":"Operators","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/!=(_:_:)"]}],"kind":"article","metadata":{"title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"ScanbotSDK"}],"role":"collectionGroup"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod":{"title":"SBSDKResamplingMethod","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod","abstract":[{"text":"Resampling method.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKResamplingMethod","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKResamplingMethod","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod/!=(_:_:)":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/!=(_:_:)","abstract":[],"title":"!=(_:_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/!=(_:_:)"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/title","op":"replace","value":"SBSDKResamplingMethod"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/fragments","op":"replace","value":[{"text":"SBSDKResamplingMethod","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/navigatorTitle","op":"replace","value":[{"text":"SBSDKResamplingMethod","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}