{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKBarcodeScannerViewControllerDelegate","text":"SBSDKBarcodeScannerViewControllerDelegate"},{"kind":"text","text":"?"}],"title":"delegate","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController(py)delegate","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/delegate"},"abstract":[{"type":"text","text":"The weak delegate. See "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate","type":"reference","isActive":true},{"type":"text","text":" protocol."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKBarcodeScannerViewControllerDelegate","text":"SBSDKBarcodeScannerViewControllerDelegate"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController/delegate":{"abstract":[{"type":"text","text":"The weak delegate. See "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate"},{"type":"text","text":" protocol."}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController\/delegate","kind":"symbol","title":"delegate","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller\/delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKBarcodeScannerViewControllerDelegate","kind":"typeIdentifier","text":"SBSDKBarcodeScannerViewControllerDelegate"},{"kind":"text","text":"?"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewControllerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"type":"topic","role":"symbol","title":"SBSDKBarcodeScannerViewControllerDelegate","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate","abstract":[{"text":"The delegate protocol of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","type":"reference"},{"text":" that provides methods for","type":"text"},{"text":" ","type":"text"},{"text":"enabling\/disabling scanning and managing scanned barcodes.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show a camera screen with the barcode scanner."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","title":"SBSDKBarcodeScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"delegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<SBSDKBarcodeScannerViewControllerDelegate>","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKBarcodeScannerViewControllerDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1delegate\/title","op":"replace","value":"delegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController~1delegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate\/title","value":"SBSDKBarcodeScannerViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate\/fragments","value":[{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/title","value":"SBSDKBarcodeScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/fragments","value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}