{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickCompleteAlertSubtitle"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Subtitle for the find and pick complete alert."},{"type":"text","text":" "},{"type":"text","text":"Default is “You have successfully scanned all codes. Proceed with submission?”"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"findAndPickCompleteAlertSubtitle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/findandpickcompletealertsubtitle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/findandpickcompletealertsubtitle"]}],"sections":[],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"findAndPickCompleteAlertSubtitle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeTextLocalization(py)findAndPickCompleteAlertSubtitle","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"findAndPickCompleteAlertSubtitle"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"findAndPickCompleteAlertSubtitle","symbolKind":"property"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/findAndPickCompleteAlertSubtitle":{"role":"symbol","navigatorTitle":[{"text":"findAndPickCompleteAlertSubtitle","kind":"identifier"}],"title":"findAndPickCompleteAlertSubtitle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickCompleteAlertSubtitle","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/findandpickcompletealertsubtitle","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"findAndPickCompleteAlertSubtitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Subtitle for the find and pick complete alert."},{"type":"text","text":" "},{"type":"text","text":"Default is “You have successfully scanned all codes. Proceed with submission?”"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization","role":"symbol","abstract":[{"type":"text","text":"Configuration of the all strings for barcode scanner."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization","title":"SBSDKUI2BarcodeTextLocalization","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"findAndPickCompleteAlertSubtitle","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"findAndPickCompleteAlertSubtitle","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"findAndPickCompleteAlertSubtitle"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"findAndPickCompleteAlertSubtitle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickCompleteAlertSubtitle\/title"},{"value":[{"kind":"identifier","text":"findAndPickCompleteAlertSubtitle"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickCompleteAlertSubtitle\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/title","value":"SBSDKUI2BarcodeTextLocalization","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/fragments","value":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}]}]}]}