{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"findAndPickPartialAlertSubtitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"findAndPickPartialAlertSubtitle","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","title":"findAndPickPartialAlertSubtitle","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeTextLocalization(py)findAndPickPartialAlertSubtitle","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"findAndPickPartialAlertSubtitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"kind":"symbol","abstract":[{"type":"text","text":"Subtitle for the find and pick partial alert."},{"type":"text","text":" "},{"text":"Default is “Some codes are yet to be scanned. Proceed with submission anyway?”","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickPartialAlertSubtitle"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/findandpickpartialalertsubtitle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/findandpickpartialalertsubtitle"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/findAndPickPartialAlertSubtitle":{"type":"topic","kind":"symbol","abstract":[{"text":"Subtitle for the find and pick partial alert.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is “Some codes are yet to be scanned. Proceed with submission anyway?”"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/findAndPickPartialAlertSubtitle","title":"findAndPickPartialAlertSubtitle","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/findandpickpartialalertsubtitle","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"findAndPickPartialAlertSubtitle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"findAndPickPartialAlertSubtitle"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization","abstract":[{"type":"text","text":"Configuration of the all strings for barcode scanner."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}],"kind":"symbol","title":"SBSDKUI2BarcodeTextLocalization"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"findAndPickPartialAlertSubtitle","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"findAndPickPartialAlertSubtitle","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"findAndPickPartialAlertSubtitle","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickPartialAlertSubtitle\/title","value":"findAndPickPartialAlertSubtitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1findAndPickPartialAlertSubtitle\/fragments","value":[{"kind":"identifier","text":"findAndPickPartialAlertSubtitle"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/title","value":"SBSDKUI2BarcodeTextLocalization"},{"value":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}