{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetPlaceholderTitle"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sheetPlaceholderTitle"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Title for the barcode sheet placeholder."},{"type":"text","text":" "},{"type":"text","text":"Default is “No barcodes here!”"}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sheetPlaceholderTitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeTextLocalization(py)sheetPlaceholderTitle","symbolKind":"property","title":"sheetPlaceholderTitle","navigatorTitle":[{"kind":"identifier","text":"sheetPlaceholderTitle"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/sheetplaceholdertitle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/sheetplaceholdertitle"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization","abstract":[{"text":"Configuration of the all strings for barcode scanner.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization","role":"symbol","kind":"symbol","title":"SBSDKUI2BarcodeTextLocalization","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization/sheetPlaceholderTitle":{"navigatorTitle":[{"text":"sheetPlaceholderTitle","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sheetPlaceholderTitle"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization\/sheetPlaceholderTitle","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization\/sheetplaceholdertitle","title":"sheetPlaceholderTitle","abstract":[{"type":"text","text":"Title for the barcode sheet placeholder."},{"type":"text","text":" "},{"type":"text","text":"Default is “No barcodes here!”"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"sheetPlaceholderTitle","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"sheetPlaceholderTitle"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"sheetPlaceholderTitle"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"SBSDKUI2BarcodeTextLocalization","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1sheetPlaceholderTitle\/title","value":"sheetPlaceholderTitle","op":"replace"},{"op":"replace","value":[{"text":"sheetPlaceholderTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization~1sheetPlaceholderTitle\/fragments"}]}]}