{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodesextensionfilter\/equatable-implementations"]}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter\/!=(_:_:)"],"title":"Operators","generated":true,"anchor":"Operators"}],"kind":"article","sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter\/Equatable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodesExtensionFilter/!=(_:_:)":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter\/!=(_:_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"!=(_:_:)","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodesextensionfilter\/!=(_:_:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodesExtensionFilter":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodesextensionfilter","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2BarcodesExtensionFilter","kind":"identifier"}],"kind":"symbol","title":"SBSDKUI2BarcodesExtensionFilter","abstract":[{"type":"text","text":"Filter for extended EAN and UPC barcodes."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilter"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2BarcodesExtensionFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodesExtensionFilter\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodesExtensionFilter\/fragments","value":[{"text":"SBSDKUI2BarcodesExtensionFilter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodesExtensionFilter\/navigatorTitle","value":[{"text":"SBSDKUI2BarcodesExtensionFilter","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}