{"abstract":[{"text":"This is the default configuration with the properties initialized as mentioned in their description.","type":"text"}],"kind":"symbol","metadata":{"roleHeading":"Type Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerGeneralConfiguration(cpy)defaultConfiguration","title":"defaultConfiguration","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerGeneralConfiguration"}],"symbolKind":"property","navigatorTitle":[{"text":"defaultConfiguration","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/defaultconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/defaultconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/defaultConfiguration","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerGeneralConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration","text":"SBSDKBaseScannerGeneralConfiguration"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/defaultConfiguration":{"type":"topic","title":"defaultConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/defaultConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/defaultconfiguration","navigatorTitle":[{"kind":"identifier","text":"defaultConfiguration"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerGeneralConfiguration","kind":"typeIdentifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"abstract":[{"type":"text","text":"This is the default configuration with the properties initialized as mentioned in their description."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration":{"abstract":[{"text":"The general configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration","title":"SBSDKBaseScannerGeneralConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"defaultConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"defaultConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration","text":"SBSDKBaseScannerGeneralConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerGeneralConfiguration"},{"text":" * ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"defaultConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1defaultConfiguration\/title"},{"value":[{"text":"defaultConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1defaultConfiguration\/fragments"},{"value":"SBSDKBaseScannerGeneralConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/title"},{"value":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/fragments"},{"value":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/navigatorTitle"}]}]}