{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling\/accept"},"metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accept","kind":"identifier"}],"roleHeading":"Case","title":"SBSDKMRZIncompleteResultHandling.accept","externalID":"c:@M@ScanbotSDK@E@SBSDKMRZIncompleteResultHandling@SBSDKMRZIncompleteResultHandlingAccept","symbolKind":"case","navigatorTitle":[{"text":"SBSDKMRZIncompleteResultHandlingAccept","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Accept incomplete results. Fields failing validation will have a validation status of INVALID. Typically used","type":"text"},{"text":" ","type":"text"},{"text":"for single-shot scanning.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accept"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmrzincompleteresulthandling\/accept"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmrzincompleteresulthandling\/accept"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZIncompleteResultHandling/accept":{"type":"topic","title":"SBSDKMRZIncompleteResultHandling.accept","navigatorTitle":[{"text":"SBSDKMRZIncompleteResultHandlingAccept","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling\/accept","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzincompleteresulthandling\/accept","role":"symbol","abstract":[{"type":"text","text":"Accept incomplete results. Fields failing validation will have a validation status of INVALID. Typically used"},{"type":"text","text":" "},{"text":"for single-shot scanning.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"accept","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZIncompleteResultHandling":{"abstract":[{"text":"Defines how to handle incomplete MRZ results (e.g. caused by failed validation).","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZIncompleteResultHandling","type":"topic","navigatorTitle":[{"text":"SBSDKMRZIncompleteResultHandling","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMRZIncompleteResultHandling"}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzincompleteresulthandling","title":"SBSDKMRZIncompleteResultHandling"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMRZIncompleteResultHandlingAccept"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"SBSDKMRZIncompleteResultHandlingAccept","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"SBSDKMRZIncompleteResultHandlingAccept","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling~1accept\/title","op":"replace","value":"SBSDKMRZIncompleteResultHandlingAccept"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling~1accept\/fragments","op":"replace","value":[{"text":"SBSDKMRZIncompleteResultHandlingAccept","kind":"identifier"}]},{"op":"replace","value":"SBSDKMRZIncompleteResultHandling","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMRZIncompleteResultHandling"}]},{"value":[{"kind":"identifier","text":"SBSDKMRZIncompleteResultHandling"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZIncompleteResultHandling\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}