{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration\/patternMatching(_:allowedCharacters:matchSubstring:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"patternMatching(_:allowedCharacters:matchSubstring:)","role":"symbol","symbolKind":"method","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKTextPatternScannerConfiguration(cm)patternMatching:allowedCharacters:matchSubstring:","modules":[{"name":"ScanbotSDK"}],"extendedModule":"ScanbotSDK","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"patternMatching","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowedCharacters"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"matchSubstring"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKTextPatternScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerConfiguration"}],"navigatorTitle":[{"text":"patternMatching:allowedCharacters:matchSubstring:","kind":"identifier"}],"roleHeading":"Type Method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration\/patternmatching(_:allowedcharacters:matchsubstring:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration\/patternmatching(_:allowedcharacters:matchsubstring:)"]}],"abstract":[{"type":"text","text":"Creates a configuration for scanning string patterns using "},{"code":"SBSDKGenericTextLineScanner","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"patternMatching"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"pattern","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"allowedCharacters","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" = \"\", "},{"text":"matchSubstring","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = false) -> ","kind":"text"},{"text":"SBSDKTextPatternScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerConfiguration","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"pattern","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Wildcard validation pattern."},{"text":" ","type":"text"},{"type":"text","text":"? - any character"}]}]},{"name":"allowedCharacters","content":[{"inlineContent":[{"text":"A string with all allowed characters. If empty, all characters are allowed.","type":"text"}],"type":"paragraph"}]},{"name":"matchSubstring","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether the pattern should match the whole string or just a substring."}]}]}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The pattern matching configuration.","type":"text"}]}],"kind":"content"}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerConfiguration/patternMatching(_:allowedCharacters:matchSubstring:)":{"abstract":[{"type":"text","text":"Creates a configuration for scanning string patterns using "},{"type":"codeVoice","code":"SBSDKGenericTextLineScanner"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"patternMatching:allowedCharacters:matchSubstring:","kind":"identifier"}],"title":"patternMatching(_:allowedCharacters:matchSubstring:)","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration\/patternmatching(_:allowedcharacters:matchsubstring:)","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"patternMatching","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowedCharacters"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"matchSubstring","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"text":"SBSDKTextPatternScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerConfiguration","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration\/patternMatching(_:allowedCharacters:matchSubstring:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerConfiguration":{"role":"symbol","title":"SBSDKTextPatternScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration","abstract":[{"text":"Configuration for the text pattern scanner.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKTextPatternScannerConfiguration","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerConfiguration"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","value":"patternMatching:allowedCharacters:matchSubstring:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"patternMatching:allowedCharacters:matchSubstring:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKTextPatternScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"patternMatching:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"pattern","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"allowedCharacters:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"allowedCharacters"},{"text":" ","kind":"text"},{"kind":"identifier","text":"matchSubstring:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"matchSubstring","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"pattern","content":[{"inlineContent":[{"type":"text","text":"Wildcard validation pattern."},{"type":"text","text":" "},{"text":"? - any character","type":"text"}],"type":"paragraph"}]},{"name":"allowedCharacters","content":[{"inlineContent":[{"type":"text","text":"A string with all allowed characters. If empty, all characters are allowed."}],"type":"paragraph"}]},{"name":"matchSubstring","content":[{"type":"paragraph","inlineContent":[{"text":"Whether the pattern should match the whole string or just a substring.","type":"text"}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The pattern matching configuration."}],"type":"paragraph"}]},"op":"replace","path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration~1patternMatching(_:allowedCharacters:matchSubstring:)\/title","op":"replace","value":"patternMatching:allowedCharacters:matchSubstring:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"patternMatching:allowedCharacters:matchSubstring:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration~1patternMatching(_:allowedCharacters:matchSubstring:)\/fragments"},{"value":"SBSDKTextPatternScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerConfiguration"}]},{"value":[{"text":"SBSDKTextPatternScannerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/navigatorTitle"}]}]}