{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerConfiguration(im)initWithVersion:screen:palette:localization:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"version"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"screen","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"palette"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Palette","kind":"typeIdentifier","text":"SBSDKUI2Palette"},{"kind":"text","text":", "},{"text":"localization","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeTextLocalization","text":"SBSDKUI2BarcodeTextLocalization","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backgroundColor"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"topBar","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TopBarConfiguration","text":"SBSDKUI2TopBarConfiguration"},{"kind":"text","text":", "},{"text":"actionBar","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ActionBarConfiguration","text":"SBSDKUI2ActionBarConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewFinder"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ViewFinderConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userGuidance","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier","text":"SBSDKUI2UserGuidanceConfiguration"},{"text":", ","kind":"text"},{"text":"cameraPermission","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraPermissionScreen","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cameraConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraConfiguration"},{"text":", ","kind":"text"},{"text":"recognizerConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeRecognizerConfiguration"},{"text":", ","kind":"text"},{"text":"useCase","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeUseCase","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeUseCase","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sound"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sound","text":"SBSDKUI2Sound","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"vibration"},{"kind":"text","text":": "},{"text":"SBSDKUI2Vibration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Vibration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"timeouts"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2Timeouts","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Timeouts"},{"text":")","kind":"text"}],"symbolKind":"init","title":"init(version:screen:palette:localization:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithVersion:screen:palette:localization:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:"}],"modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration\/init(version:screen:palette:localization:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerconfiguration\/init(version:screen:palette:localization:backgroundcolor:topbar:actionbar:viewfinder:userguidance:camerapermission:cameraconfiguration:recognizerconfiguration:usecase:sound:vibration:timeouts:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerconfiguration\/init(version:screen:palette:localization:backgroundcolor:topbar:actionbar:viewfinder:userguidance:camerapermission:cameraconfiguration:recognizerconfiguration:usecase:sound:vibration:timeouts:)"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"version","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"1.0\", "},{"kind":"externalParam","text":"screen"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" = \"BarcodeScanner\", ","kind":"text"},{"text":"palette","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Palette","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Palette","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Palette","kind":"typeIdentifier"},{"text":" = SBSDKUI2Palette(sbColorPrimary: SBSDKUI2Color(colorString: \"#C8193C\", isArgb: false),\n                                    sbColorPrimaryDisabled: SBSDKUI2Color(colorString: \"#F5F5F5\",\n                                                                          isArgb: false),\n                                    sbColorNegative: SBSDKUI2Color(colorString: \"#FF3737\",\n                                                                   isArgb: false),\n                                    sbColorPositive: SBSDKUI2Color(colorString: \"#4EFFB4\",\n                                                                   isArgb: false),\n                                    sbColorWarning: SBSDKUI2Color(colorString: \"#FFCE5C\",\n                                                                  isArgb: false),\n                                    sbColorSecondary: SBSDKUI2Color(colorString: \"#FFEDEE\",\n                                                                    isArgb: false),\n                                    sbColorSecondaryDisabled: SBSDKUI2Color(colorString: \"#F5F5F5\",\n                                                                            isArgb: false),\n                                    sbColorOnPrimary: SBSDKUI2Color(colorString: \"#FFFFFF\",\n                                                                    isArgb: false),\n                                    sbColorOnSecondary: SBSDKUI2Color(colorString: \"#C8193C\",\n                                                                      isArgb: false),\n                                    sbColorSurface: SBSDKUI2Color(colorString: \"#FFFFFF\",\n                                                                  isArgb: false),\n                                    sbColorOutline: SBSDKUI2Color(colorString: \"#EFEFEF\",\n                                                                  isArgb: false),\n                                    sbColorOnSurfaceVariant: SBSDKUI2Color(colorString: \"#707070\",\n                                                                           isArgb: false),\n                                    sbColorOnSurface: SBSDKUI2Color(colorString: \"#000000\",\n                                                                    isArgb: false),\n                                    sbColorSurfaceLow: SBSDKUI2Color(colorString: \"#00000026\",\n                                                                     isArgb: false),\n                                    sbColorSurfaceHigh: SBSDKUI2Color(colorString: \"#0000007A\",\n                                                                      isArgb: false),\n                                    sbColorModalOverlay: SBSDKUI2Color(colorString: \"#000000A3\",\n                                                                       isArgb: false)), ","kind":"text"},{"text":"localization","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeTextLocalization","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization","text":"SBSDKUI2BarcodeTextLocalization"},{"kind":"text","text":" = SBSDKUI2BarcodeTextLocalization(), "},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":" = SBSDKUI2Color(colorString: \"?sbColorSurfaceLow\", isArgb: false), ","kind":"text"},{"kind":"externalParam","text":"topBar"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TopBarConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarConfiguration","text":"SBSDKUI2TopBarConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2TopBarConfiguration(title: SBSDKUI2StyledText(text: \"?topBarTitle\",\n                                                                          color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                               isArgb: false)),\n                                                mode: SBSDKUI2TopBarMode.solid,\n                                                statusBarMode: SBSDKUI2StatusBarMode\n                                                    .light,\n                                                backgroundColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                               isArgb: false),\n                                                cancelButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                          text: \"?topBarCancelButton\",\n                                                                                          background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                              fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                       isArgb: false),\n                                                                                                                              strokeWidth: 0.0),\n                                                                                          foreground: SBSDKUI2ForegroundStyle(iconVisible: true,\n                                                                                                                              color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                   isArgb: false),\n                                                                                                                              useShadow: false))), "},{"kind":"externalParam","text":"actionBar"},{"kind":"text","text":": "},{"text":"SBSDKUI2ActionBarConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ActionBarConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration"},{"kind":"text","text":" = SBSDKUI2ActionBarConfiguration(flashButton: SBSDKUI2RoundButton(visible: true,\n                                                                                    backgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                                   isArgb: false),\n                                                                                    foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                   isArgb: false),\n                                                                                    activeBackgroundColor: SBSDKUI2Color(colorString: \"?sbColorWarning\",\n                                                                                                                         isArgb: false),\n                                                                                    activeForegroundColor: SBSDKUI2Color(colorString: \"#1C1B1F\",\n                                                                                                                         isArgb: false)),\n                                                   zoomButton: SBSDKUI2RoundButton(visible: true,\n                                                                                   backgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                                  isArgb: false),\n                                                                                   foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                  isArgb: false),\n                                                                                   activeBackgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                                        isArgb: false),\n                                                                                   activeForegroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                        isArgb: false)),\n                                                   flipCameraButton: SBSDKUI2RoundButton(visible: true,\n                                                                                         backgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                                        isArgb: false),\n                                                                                         foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                        isArgb: false),\n                                                                                         activeBackgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                                              isArgb: false),\n                                                                                         activeForegroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                              isArgb: false))), "},{"text":"viewFinder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2ViewFinderConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ViewFinderConfiguration"},{"kind":"text","text":" = SBSDKUI2ViewFinderConfiguration(visible: true,\n                                                                                              style: SBSDKUI2FinderCorneredStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                                                            isArgb: false),\n                                                                                                                                 strokeWidth: 2.0,\n                                                                                                                                 cornerRadius: 10.0),\n                                                                                              overlayColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceLow\",\n                                                                                                                          isArgb: false),\n                                                                                              aspectRatio: SBSDKUI2AspectRatio(width: 1.0,\n                                                                                                                               height: 1.0)), "},{"text":"userGuidance","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration","text":"SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration"},{"text":" = SBSDKUI2UserGuidanceConfiguration(visible: true,\n                                                                                                    title: SBSDKUI2StyledText(text: \"?userGuidance\",\n                                                                                                                              color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                   isArgb: false)),\n                                                                                                    background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                   isArgb: false),\n                                                                                                                                        fillColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceLow\",\n                                                                                                                                                                 isArgb: false),\n                                                                                                                                        strokeWidth: 0.0)), ","kind":"text"},{"text":"cameraPermission","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2CameraPermissionScreen","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen"},{"kind":"text","text":" = SBSDKUI2CameraPermissionScreen(statusBarMode: SBSDKUI2StatusBarMode.dark,\n                                                   background: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                             isArgb: false),\n                                                   iconBackground: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                                 isArgb: false),\n                                                   icon: SBSDKUI2IconStyle(visible: true,\n                                                                           color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                isArgb: false)),\n                                                   enableCameraButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                                   text: \"?cameraPermissionEnableCameraButton\",\n                                                                                                   background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                                  isArgb: false),\n                                                                                                                                       fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                                isArgb: false),\n                                                                                                                                       strokeWidth: 0.0),\n                                                                                                   foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                                       color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                            isArgb: false),\n                                                                                                                                       useShadow: false)),\n                                                   closeButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                            text: \"?cameraPermissionCloseButton\",\n                                                                                            background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                           isArgb: false),\n                                                                                                                                fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                                strokeWidth: 0.0),\n                                                                                            foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                                color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                     isArgb: false),\n                                                                                                                                useShadow: false)),\n                                                   enableCameraTitle: SBSDKUI2StyledText(text: \"?cameraPermissionEnableCameraTitle\",\n                                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                              isArgb: false)),\n                                                   enableCameraExplanation: SBSDKUI2StyledText(text: \"?cameraPermissionEnableCameraExplanation\",\n                                                                                               color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                                    isArgb: false))), "},{"text":"cameraConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraConfiguration","text":"SBSDKUI2CameraConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration"},{"kind":"text","text":" = SBSDKUI2CameraConfiguration(), "},{"kind":"externalParam","text":"recognizerConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeRecognizerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeRecognizerConfiguration"},{"text":" = SBSDKUI2BarcodeRecognizerConfiguration(), ","kind":"text"},{"text":"useCase","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeUseCase","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeUseCase","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeUseCase"},{"text":" = SBSDKUI2SingleScanningMode(), ","kind":"text"},{"kind":"externalParam","text":"sound"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sound","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound","text":"SBSDKUI2Sound"},{"text":" = SBSDKUI2Sound(successBeepEnabled: true,\n                                                     soundType: SBSDKUI2SoundType.modernBeep), ","kind":"text"},{"text":"vibration","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Vibration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Vibration","text":"SBSDKUI2Vibration","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2Vibration(enabled: true), "},{"kind":"externalParam","text":"timeouts"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Timeouts","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Timeouts","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Timeouts","kind":"typeIdentifier"},{"text":" = SBSDKUI2Timeouts(autoCancelTimeout: 0, initialScanDelay: 0))","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TopBarConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarConfiguration","type":"topic","role":"symbol","title":"SBSDKUI2TopBarConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the top screen bar’s appearance."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2topbarconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeUseCase":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeUseCase"}],"type":"topic","abstract":[{"text":"Configuration of the barcode scanner screen’s behavior.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeUseCase","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeusecase","title":"SBSDKUI2BarcodeUseCase","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeUseCase"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceConfiguration":{"type":"topic","abstract":[{"type":"text","text":"Configuration of the hint guiding users through the scanning process."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"role":"symbol","title":"SBSDKUI2UserGuidanceConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidanceconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Palette":{"url":"\/documentation\/scanbotsdk\/sbsdkui2palette","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2Palette","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Palette","abstract":[{"type":"text","text":"Value palette describing the colors of the scanner screens."}],"navigatorTitle":[{"text":"SBSDKUI2Palette","kind":"identifier"}],"title":"SBSDKUI2Palette","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPermissionScreen":{"navigatorTitle":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the camera permission request view."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen","title":"SBSDKUI2CameraPermissionScreen","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerconfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the barcode scanner screen."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration","title":"SBSDKUI2BarcodeScannerConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeScannerConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Vibration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2vibration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Vibration","kind":"identifier"}],"abstract":[{"text":"Vibration configuration.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Vibration","title":"SBSDKUI2Vibration","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2Vibration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ActionBarConfiguration":{"title":"SBSDKUI2ActionBarConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ActionBarConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2actionbarconfiguration","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the buttons available in the action bar."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2ActionBarConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"title":"SBSDKUI2Color","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Timeouts":{"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2Timeouts","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of timeouts."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Timeouts","title":"SBSDKUI2Timeouts","url":"\/documentation\/scanbotsdk\/sbsdkui2timeouts","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Timeouts"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerConfiguration/init(version:screen:palette:localization:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:)":{"role":"symbol","title":"init(version:screen:palette:localization:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration\/init(version:screen:palette:localization:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"version"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"screen","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"palette","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Palette","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Palette"},{"kind":"text","text":", "},{"text":"localization","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeTextLocalization","text":"SBSDKUI2BarcodeTextLocalization"},{"kind":"text","text":", "},{"text":"backgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"topBar","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TopBarConfiguration","kind":"typeIdentifier","text":"SBSDKUI2TopBarConfiguration"},{"kind":"text","text":", "},{"text":"actionBar","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ActionBarConfiguration","kind":"typeIdentifier","text":"SBSDKUI2ActionBarConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewFinder"},{"kind":"text","text":": "},{"text":"SBSDKUI2ViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ViewFinderConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userGuidance","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraPermission"},{"kind":"text","text":": "},{"text":"SBSDKUI2CameraPermissionScreen","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen"},{"kind":"text","text":", "},{"text":"cameraConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recognizerConfiguration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeRecognizerConfiguration","text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"useCase","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeUseCase","kind":"typeIdentifier","text":"SBSDKUI2BarcodeUseCase"},{"kind":"text","text":", "},{"text":"sound","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sound","text":"SBSDKUI2Sound"},{"kind":"text","text":", "},{"kind":"externalParam","text":"vibration"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Vibration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Vibration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timeouts"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Timeouts","kind":"typeIdentifier","text":"SBSDKUI2Timeouts"},{"kind":"text","text":")"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerconfiguration\/init(version:screen:palette:localization:backgroundcolor:topbar:actionbar:viewfinder:userguidance:camerapermission:cameraconfiguration:recognizerconfiguration:usecase:sound:vibration:timeouts:)","navigatorTitle":[{"kind":"identifier","text":"initWithVersion:screen:palette:localization:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration","abstract":[{"type":"text","text":"Configuration of the scanning behavior."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}],"title":"SBSDKUI2BarcodeRecognizerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ViewFinderConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"title":"SBSDKUI2ViewFinderConfiguration","abstract":[{"text":"Configuration of the scanning interface’s viewfinder, serving as guidance to the user.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2viewfinderconfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}],"role":"symbol","title":"SBSDKUI2BarcodeTextLocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization","abstract":[{"text":"Configuration of the all strings for barcode scanner.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2cameraconfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the camera settings to be used while scanning."}],"title":"SBSDKUI2CameraConfiguration","navigatorTitle":[{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sound":{"url":"\/documentation\/scanbotsdk\/sbsdkui2sound","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound","type":"topic","title":"SBSDKUI2Sound","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Sound"}],"abstract":[{"text":"Sound configuration.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Sound"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithVersion:screen:palette:localization:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithVersion:screen:palette:localization:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithVersion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"version"},{"text":" ","kind":"text"},{"kind":"identifier","text":"screen:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"screen"},{"text":" ","kind":"text"},{"kind":"identifier","text":"palette:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Palette","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Palette","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Palette","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"palette"},{"kind":"text","text":" "},{"text":"localization:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeTextLocalization","text":"SBSDKUI2BarcodeTextLocalization","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"localization","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"backgroundColor:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backgroundColor"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topBar:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2TopBarConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TopBarConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarConfiguration"},{"kind":"text","text":" *) "},{"text":"topBar","kind":"internalParam"},{"kind":"text","text":" "},{"text":"actionBar:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2ActionBarConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ActionBarConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"actionBar"},{"text":" ","kind":"text"},{"text":"viewFinder:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ViewFinderConfiguration","text":"SBSDKUI2ViewFinderConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration"},{"kind":"text","text":" *) "},{"text":"viewFinder","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userGuidance:"},{"kind":"text","text":"("},{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration"},{"kind":"text","text":" *) "},{"text":"userGuidance","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermission:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen","text":"SBSDKUI2CameraPermissionScreen","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraPermission"},{"text":" ","kind":"text"},{"text":"cameraConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2CameraConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraConfiguration"},{"kind":"text","text":" *) "},{"text":"cameraConfiguration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"recognizerConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeRecognizerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration"},{"text":" *) ","kind":"text"},{"text":"recognizerConfiguration","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"useCase:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeUseCase","text":"SBSDKUI2BarcodeUseCase","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeUseCase","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"useCase","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sound:"},{"kind":"text","text":"("},{"text":"SBSDKUI2Sound","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sound"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sound"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vibration:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Vibration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Vibration","text":"SBSDKUI2Vibration"},{"text":" *) ","kind":"text"},{"text":"vibration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"timeouts:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Timeouts","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Timeouts","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Timeouts","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"timeouts"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2TopBarConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKUI2TopBarConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration\/fragments"},{"op":"replace","value":"SBSDKUI2BarcodeUseCase","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeUseCase\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeUseCase\/fragments","value":[{"text":"SBSDKUI2BarcodeUseCase","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2UserGuidanceConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/fragments","value":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Palette\/title","value":"SBSDKUI2Palette"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Palette"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Palette\/fragments"},{"value":"SBSDKUI2CameraPermissionScreen","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration\/title","value":"SBSDKUI2BarcodeScannerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Vibration\/title","op":"replace","value":"SBSDKUI2Vibration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Vibration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Vibration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration\/title","value":"SBSDKUI2ActionBarConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2ActionBarConfiguration","kind":"identifier"}]},{"value":"SBSDKUI2Color","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Timeouts\/title","value":"SBSDKUI2Timeouts"},{"value":[{"kind":"identifier","text":"SBSDKUI2Timeouts"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Timeouts\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration~1init(version:screen:palette:localization:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:)\/title","value":"initWithVersion:screen:palette:localization:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration~1init(version:screen:palette:localization:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithVersion:screen:palette:localization:backgroundColor:topBar:actionBar:viewFinder:userGuidance:cameraPermission:cameraConfiguration:recognizerConfiguration:useCase:sound:vibration:timeouts:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/title","value":"SBSDKUI2BarcodeRecognizerConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/fragments","value":[{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration\/title","value":"SBSDKUI2ViewFinderConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ViewFinderConfiguration"}]},{"op":"replace","value":"SBSDKUI2BarcodeTextLocalization","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/fragments","value":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2CameraConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}]},{"value":"SBSDKUI2Sound","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/fragments","value":[{"text":"SBSDKUI2Sound","kind":"identifier"}]}]}]}