{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithExtractedDocumentFormats:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKBarcodeDocumentFormat *>"},{"text":" *) ","kind":"text"},{"text":"extractedDocumentFormats","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onlyAcceptDocuments:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"text":"onlyAcceptDocuments","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"extensions:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior","text":"SBSDKUpcEanExtensionBehavior","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUpcEanExtensionBehavior"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"extensions"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodesRegexFilter:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"barcodesRegexFilter","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumSizeScore:"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"minimumSizeScore","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumTextLength:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"minimumTextLength"},{"text":" ","kind":"text"},{"text":"maximumTextLength:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"maximumTextLength"},{"kind":"text","text":" "},{"text":"minimum1DBarcodesQuietZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimum1DBarcodesQuietZone","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"stripCheckDigits:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"stripCheckDigits"},{"kind":"text","text":" "},{"text":"useIATA2OF5Checksum:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"useIATA2OF5Checksum"},{"text":" ","kind":"text"},{"text":"useCode11Checksum:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"useCode11Checksum"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormats:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKBarcodeFormat *>"},{"kind":"text","text":" *) "},{"text":"barcodeFormats","kind":"internalParam"},{"kind":"text","text":" "},{"text":"msiPlesseyChecksumAlgorithm:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm","text":"SBSDKMSIPlesseyChecksumAlgorithm"},{"kind":"text","text":" *) "},{"text":"msiPlesseyChecksumAlgorithm","kind":"internalParam"},{"kind":"text","text":" "},{"text":"australiaPostCustomerFormat:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAustraliaPostCustomerFormat","text":"SBSDKAustraliaPostCustomerFormat","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"australiaPostCustomerFormat"},{"kind":"text","text":" "},{"kind":"identifier","text":"gs1Handling:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKGS1Handling","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKGS1Handling","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"gs1Handling","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"returnBarcodeImage:"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"returnBarcodeImage"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration\/initWithExtractedDocumentFormats:onlyAcceptDocuments:extensions:barcodesRegexFilter:minimumSizeScore:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:returnBarcodeImage:","interfaceLanguage":"occ"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerconfiguration\/initwithextracteddocumentformats:onlyacceptdocuments:extensions:barcodesregexfilter:minimumsizescore:minimumtextlength:maximumtextlength:minimum1dbarcodesquietzone:stripcheckdigits:useiata2of5checksum:usecode11checksum:barcodeformats:msiple-1ovfl"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithExtractedDocumentFormats:onlyAcceptDocuments:extensions:barcodesRegexFilter:minimumSizeScore:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:returnBarcodeImage:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerConfiguration(im)initWithExtractedDocumentFormats:onlyAcceptDocuments:extensions:barcodesRegexFilter:minimumSizeScore:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:returnBarcodeImage:","modules":[{"name":"ScanbotSDK"}],"title":"initWithExtractedDocumentFormats:onlyAcceptDocuments:extensions:barcodesRegexFilter:minimumSizeScore:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:returnBarcodeImage:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithExtractedDocumentFormats:onlyAcceptDocuments:extensions:barcodesRegexFilter:minimumSizeScore:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:returnBarcodeImage:"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUpcEanExtensionBehavior":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkupceanextensionbehavior","title":"SBSDKUpcEanExtensionBehavior","abstract":[{"type":"text","text":"Behavior when scanning UPC\/EAN barcodes with EAN-2 or EAN-5 extensions."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerConfiguration":{"abstract":[{"text":"Configuration of the scanning behavior.","type":"text"}],"title":"SBSDKUI2BarcodeScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerconfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeScannerConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAustraliaPostCustomerFormat":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormat"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}],"title":"SBSDKAustraliaPostCustomerFormat","url":"\/documentation\/scanbotsdk\/sbsdkaustraliapostcustomerformat","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat","abstract":[{"text":"Can be either numeric or alphanumeric and is only relevant for Format Codes 59 and 62.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling","type":"topic","role":"symbol","abstract":[{"type":"text","text":"GS1 message handling options."},{"type":"text","text":" "},{"text":"The GS1 standard defines a key-value format for business-centric data that can be encoded into many 1D and 2D","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"barcode types."},{"type":"text","text":" "},{"type":"text","text":"https:\/\/ref.gs1.org\/standards\/genspecs\/"}],"kind":"symbol","title":"SBSDKGS1Handling","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGS1Handling"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"url":"\/documentation\/scanbotsdk\/sbsdkgs1handling"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMSIPlesseyChecksumAlgorithm":{"abstract":[{"type":"text","text":"Checksum algorithm for MSI_PLESSEY."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmsiplesseychecksumalgorithm","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMSIPlesseyChecksumAlgorithm"}],"title":"SBSDKMSIPlesseyChecksumAlgorithm"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerConfiguration/initWithExtractedDocumentFormats:onlyAcceptDocuments:extensions:barcodesRegexFilter:minimumSizeScore:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:returnBarcodeImage:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration\/initWithExtractedDocumentFormats:onlyAcceptDocuments:extensions:barcodesRegexFilter:minimumSizeScore:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:returnBarcodeImage:","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithExtractedDocumentFormats:onlyAcceptDocuments:extensions:barcodesRegexFilter:minimumSizeScore:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:returnBarcodeImage:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerconfiguration\/initwithextracteddocumentformats:onlyacceptdocuments:extensions:barcodesregexfilter:minimumsizescore:minimumtextlength:maximumtextlength:minimum1dbarcodesquietzone:stripcheckdigits:useiata2of5checksum:usecode11checksum:barcodeformats:msiple-1ovfl","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithExtractedDocumentFormats:onlyAcceptDocuments:extensions:barcodesRegexFilter:minimumSizeScore:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:returnBarcodeImage:"}],"title":"initWithExtractedDocumentFormats:onlyAcceptDocuments:extensions:barcodesRegexFilter:minimumSizeScore:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:returnBarcodeImage:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior\/title","value":"SBSDKUpcEanExtensionBehavior"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior\/fragments","value":[{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}]},{"value":"SBSDKUI2BarcodeScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2BarcodeScannerConfiguration","kind":"identifier"}]},{"value":"SBSDKAustraliaPostCustomerFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat\/fragments","value":[{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat\/navigatorTitle","value":[{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}]},{"value":"SBSDKGS1Handling","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGS1Handling"}]},{"value":"SBSDKMSIPlesseyChecksumAlgorithm","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/fragments","value":[{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}]},{"value":[{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/navigatorTitle","op":"replace"}]}]}