{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/set(_:forExistingPageFileID:pageFileType:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"set"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forExistingPageFileID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pageFileType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentPageFileType","text":"SBSDKDocumentPageFileType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"set:forExistingPageFileID:pageFileType:"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentPageFileStorage(im)set:forExistingPageFileID:pageFileType:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Method","symbolKind":"method","title":"set(_:forExistingPageFileID:pageFileType:)","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/set(_:forexistingpagefileid:pagefiletype:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/set(_:forexistingpagefileid:pagefiletype:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"set","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"image","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forExistingPageFileID"},{"text":" ","kind":"text"},{"text":"pageFileID","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":", ","kind":"text"},{"text":"pageFileType","kind":"externalParam"},{"kind":"text","text":" "},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentPageFileType","kind":"typeIdentifier","text":"SBSDKDocumentPageFileType"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"image","content":[{"inlineContent":[{"text":"The UIImage instance to add.","type":"text"}],"type":"paragraph"}]},{"name":"pageFileID","content":[{"inlineContent":[{"type":"text","text":"An existing page file identifier."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The page file type of the image to be added."}]}],"name":"type"}],"kind":"parameters"},{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"true","type":"codeVoice"},{"text":" if the image was successfully added, ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise."}]}],"kind":"content"}],"kind":"symbol","abstract":[{"type":"text","text":"Sets the image of the given page file type and page file type to the receiver."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileType":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefiletype","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentPageFileType"}],"title":"SBSDKDocumentPageFileType","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType","navigatorTitle":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Enumeration of image type classifiers."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/set(_:forExistingPageFileID:pageFileType:)":{"title":"set(_:forExistingPageFileID:pageFileType:)","type":"topic","role":"symbol","abstract":[{"text":"Sets the image of the given page file type and page file type to the receiver.","type":"text"}],"navigatorTitle":[{"text":"set:forExistingPageFileID:pageFileType:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forExistingPageFileID"},{"kind":"text","text":": "},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pageFileType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentPageFileType","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentPageFileType"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/set(_:forExistingPageFileID:pageFileType:)","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/set(_:forexistingpagefileid:pagefiletype:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage","title":"SBSDKDocumentPageFileStorage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}],"navigatorTitle":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage","abstract":[{"text":"A class to store and restore images of different types in a memory-efficient way.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"set:forExistingPageFileID:pageFileType:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"set:forExistingPageFileID:pageFileType:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"text":"set:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"forExistingPageFileID:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSUUID","text":"NSUUID","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"pageFileID"},{"text":" ","kind":"text"},{"text":"pageFileType:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentPageFileType","text":"SBSDKDocumentPageFileType","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The UIImage instance to add."}],"type":"paragraph"}],"name":"image"},{"name":"pageFileID","content":[{"inlineContent":[{"text":"An existing page file identifier.","type":"text"}],"type":"paragraph"}]},{"name":"type","content":[{"inlineContent":[{"text":"The page file type of the image to be added.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"true"},{"text":" if the image was successfully added, ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" otherwise."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileType\/title","value":"SBSDKDocumentPageFileType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileType\/fragments","value":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentPageFileType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileType\/navigatorTitle"},{"value":"set:forExistingPageFileID:pageFileType:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1set(_:forExistingPageFileID:pageFileType:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1set(_:forExistingPageFileID:pageFileType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"set:forExistingPageFileID:pageFileType:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage\/title","op":"replace","value":"SBSDKDocumentPageFileStorage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}]}]}]}