{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKColorDocumentFilter\/initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:","interfaceLanguage":"occ"},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKColorDocumentFilter(im)initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:","kind":"identifier"}],"roleHeading":"Instance Method","title":"initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:","symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcolordocumentfilter\/initwithcontrastenhancement:colorenhancement:paperwhitening:paperwhiteningbias:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithContrastEnhancement:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"contrastEnhancement"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorEnhancement:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"colorEnhancement"},{"kind":"text","text":" "},{"kind":"identifier","text":"paperWhitening:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"paperWhitening"},{"kind":"text","text":" "},{"kind":"identifier","text":"paperWhiteningBias:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"paperWhiteningBias"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKColorDocumentFilter"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKColorDocumentFilter":{"abstract":[{"text":"Color document filter. This filter is a good starting point for most use cases.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcolordocumentfilter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"title":"SBSDKColorDocumentFilter","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKColorDocumentFilter","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKColorDocumentFilter/initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcolordocumentfilter\/initwithcontrastenhancement:colorenhancement:paperwhitening:paperwhiteningbias:","title":"initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:","abstract":[],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKColorDocumentFilter\/initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKColorDocumentFilter\/title","value":"SBSDKColorDocumentFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKColorDocumentFilter\/fragments","value":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKColorDocumentFilter\/navigatorTitle","value":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}