{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration"]]},"abstract":[{"type":"text","text":"Physical size of the page. If CUSTOM, the page size will be set as the image size at given dpi."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/pagesize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/pagesize"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"pageSize"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"pageSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKPageSize","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageSize"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration(py)pageSize","symbolKind":"property"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKPageSize","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageSize"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"text":"Default is A4","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/pageSize"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/pageSize":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/pagesize","role":"symbol","navigatorTitle":[{"text":"pageSize","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/pageSize","kind":"symbol","title":"pageSize","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKPageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageSize"}],"abstract":[{"type":"text","text":"Physical size of the page. If CUSTOM, the page size will be set as the image size at given dpi."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize":{"url":"\/documentation\/scanbotsdk\/sbsdkpagesize","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSize"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize","abstract":[{"text":"Page size.","type":"text"}],"role":"symbol","title":"SBSDKPageSize","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPageSize"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKPDFConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"abstract":[{"type":"text","text":"The parameters "},{"type":"codeVoice","code":"pageSize"},{"type":"text","text":", "},{"type":"codeVoice","code":"pageFit"},{"type":"text","text":", "},{"code":"dpi","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"resamplingMethod","type":"codeVoice"},{"text":" interact in a complex way","type":"text"},{"text":" ","type":"text"},{"text":"when adding bitmap images (JPEG, PNG, or raw) to the PDF.","type":"text"},{"text":" ","type":"text"},{"text":"There are three cases to consider:","type":"text"}],"title":"SBSDKPDFConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"pageSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"pageSize"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageSize","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageSize"},{"text":" ","kind":"text"},{"text":"pageSize","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1pageSize\/title","value":"pageSize"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration~1pageSize\/fragments","value":[{"kind":"identifier","text":"pageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/title","value":"SBSDKPageSize"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/fragments","value":[{"kind":"identifier","text":"SBSDKPageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/title","value":"SBSDKPDFConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/navigatorTitle","value":[{"text":"SBSDKPDFConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}