{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:textStyleFor:proposedStyle:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:textstylefor:proposedstyle:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:textstylefor:proposedstyle:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKBarcodeTrackingOverlayControllerDelegate(im)barcodeTrackingOverlay:textStyleFor:proposedStyle:","symbolKind":"method","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeTrackingOverlay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController"},{"text":", ","kind":"text"},{"text":"textStyleFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem"},{"text":", ","kind":"text"},{"text":"proposedStyle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle","kind":"typeIdentifier","text":"SBSDKBarcodeTrackedViewTextStyle"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle","kind":"typeIdentifier","text":"SBSDKBarcodeTrackedViewTextStyle"}],"roleHeading":"Instance Method","title":"barcodeTrackingOverlay(_:textStyleFor:proposedStyle:)","navigatorTitle":[{"kind":"identifier","text":"barcodeTrackingOverlay:textStyleFor:proposedStyle:"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate"]]},"abstract":[{"type":"text","text":"Asks the delegate to provide a custom style for a tracked barcodes info view. Is called when drawing the"},{"type":"text","text":" "},{"type":"text","text":"info view for the tracked barcode."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeTrackingOverlay"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeTrackingOverlayController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textStyleFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"barcode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"proposedStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeTrackedViewTextStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewTextStyle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeTrackedViewTextStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewTextStyle"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"controller","content":[{"inlineContent":[{"type":"text","text":"The barcode tracking overlay controller that the tracked barcode view belongs to."}],"type":"paragraph"}]},{"name":"barcode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The barcode that should be drawn on the overlay."}]}]},{"name":"proposedStyle","content":[{"type":"paragraph","inlineContent":[{"text":"The proposed text style that will be used by default.","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"The text style to be used when drawing the polygon for the tracked barcode."}],"type":"paragraph"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayController":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontroller","title":"SBSDKBarcodeTrackingOverlayController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"abstract":[{"text":"A class that represents an overlay used for visualizing scanned barcodes.","type":"text"},{"text":" ","type":"text"},{"text":"It provides a customizable user interface for displaying barcodes and supports interaction with them.","type":"text"},{"text":" ","type":"text"},{"text":"The overlay can be used to highlight and select barcodes based on user input.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewTextStyle":{"type":"topic","title":"SBSDKBarcodeTrackedViewTextStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewTextStyle","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeTrackedViewTextStyle"}],"abstract":[{"type":"text","text":"A class that represents the style and kind of the text rendered below a barcode in "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","isActive":true},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeTrackedViewTextStyle"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewtextstyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeItem":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeItem"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeitem","abstract":[{"type":"text","text":"A single barcode found in the input image. Barcodes with the same content but different locations in the image are considered separate barcodes."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeItem"}],"title":"SBSDKBarcodeItem"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayControllerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}],"title":"SBSDKBarcodeTrackingOverlayControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate","type":"topic","role":"symbol","abstract":[{"text":"The delegation protocol for the barcode tracking overlay controller.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayControllerDelegate/barcodeTrackingOverlay(_:textStyleFor:proposedStyle:)":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:textstylefor:proposedstyle:)","navigatorTitle":[{"text":"barcodeTrackingOverlay:textStyleFor:proposedStyle:","kind":"identifier"}],"abstract":[{"text":"Asks the delegate to provide a custom style for a tracked barcodes info view. Is called when drawing the","type":"text"},{"text":" ","type":"text"},{"text":"info view for the tracked barcode.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeTrackingOverlay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"textStyleFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"proposedStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewTextStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewTextStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle","kind":"typeIdentifier"}],"title":"barcodeTrackingOverlay(_:textStyleFor:proposedStyle:)","kind":"symbol","required":true,"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:textStyleFor:proposedStyle:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"barcodeTrackingOverlay:textStyleFor:proposedStyle:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodeTrackingOverlay:textStyleFor:proposedStyle:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewTextStyle","text":"SBSDKBarcodeTrackedViewTextStyle"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"barcodeTrackingOverlay:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","text":"SBSDKBarcodeTrackingOverlayController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"textStyleFor:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem","text":"SBSDKBarcodeItem"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcode"},{"kind":"text","text":" "},{"kind":"identifier","text":"proposedStyle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewTextStyle","text":"SBSDKBarcodeTrackedViewTextStyle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"proposedStyle"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The barcode tracking overlay controller that the tracked barcode view belongs to.","type":"text"}]}],"name":"controller"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The barcode that should be drawn on the overlay.","type":"text"}]}],"name":"barcode"},{"content":[{"inlineContent":[{"text":"The proposed text style that will be used by default.","type":"text"}],"type":"paragraph"}],"name":"proposedStyle"}],"kind":"parameters"}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The text style to be used when drawing the polygon for the tracked barcode."}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/title","value":"SBSDKBarcodeTrackingOverlayController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewTextStyle\/title","value":"SBSDKBarcodeTrackedViewTextStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewTextStyle\/fragments","value":[{"text":"SBSDKBarcodeTrackedViewTextStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewTextStyle\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackedViewTextStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/title","value":"SBSDKBarcodeItem"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/fragments","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/navigatorTitle","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/title","value":"SBSDKBarcodeTrackingOverlayControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:textStyleFor:proposedStyle:)\/title","value":"barcodeTrackingOverlay:textStyleFor:proposedStyle:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:textStyleFor:proposedStyle:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodeTrackingOverlay:textStyleFor:proposedStyle:"}]}]}]}