{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/potentialviewfinderrectwithbounds(_:findersafearea:aspectratio:minimuminsets:offset:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/potentialviewfinderrectwithbounds(_:findersafearea:aspectratio:minimuminsets:offset:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"A function, that returns a rect of a finder, if it will be placed in view with certain bounds, with given aspect ratio and insets. Useful for pre-calculations in some animation cases"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"potentialViewFinderRectWithBounds","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"bounds","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"finderSafeArea","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"aspectRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"minimumInsets","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"},{"text":", ","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":") -> ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The bounds of the view, where potential view will be placed.","type":"text"}],"type":"paragraph"}],"name":"bounds"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The safe area of the view finder.","type":"text"}]}],"name":"finderSafeArea"},{"content":[{"inlineContent":[{"type":"text","text":"An expected aspect ratio."}],"type":"paragraph"}],"name":"aspectRatio"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Minimal insets of the view finder."}]}],"name":"minimumInsets"},{"content":[{"inlineContent":[{"text":"The offset of the view finder.","type":"text"}],"type":"paragraph"}],"name":"offset"}],"kind":"parameters"},{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"A calculated rectangle of a potential view finder.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)"},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKFinderView(cm)potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:offset:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"potentialViewFinderRectWithBounds"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"finderSafeArea"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"aspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minimumInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"},{"kind":"text","text":", "},{"kind":"externalParam","text":"offset"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"}],"navigatorTitle":[{"kind":"identifier","text":"potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:offset:"}],"role":"symbol","title":"potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)","roleHeading":"Type Method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView/potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView\/potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)","role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview\/potentialviewfinderrectwithbounds(_:findersafearea:aspectratio:minimuminsets:offset:)","abstract":[{"type":"text","text":"A function, that returns a rect of a finder, if it will be placed in view with certain bounds, with given aspect ratio and insets. Useful for pre-calculations in some animation cases"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"potentialViewFinderRectWithBounds","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"finderSafeArea","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"aspectRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minimumInsets","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"title":"potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)","kind":"symbol","navigatorTitle":[{"text":"potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:offset:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView":{"abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIView"},{"text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview","title":"SBSDKFinderView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKFinderView","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:offset:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:offset:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"potentialViewFinderRectWithBounds:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"bounds","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"finderSafeArea:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"finderSafeArea","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"aspectRatio:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"aspectRatio","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumInsets:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimumInsets","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"offset:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"offset","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"bounds","content":[{"type":"paragraph","inlineContent":[{"text":"The bounds of the view, where potential view will be placed.","type":"text"}]}]},{"name":"finderSafeArea","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The safe area of the view finder."}]}]},{"name":"aspectRatio","content":[{"inlineContent":[{"type":"text","text":"An expected aspect ratio."}],"type":"paragraph"}]},{"name":"minimumInsets","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Minimal insets of the view finder."}]}]},{"name":"offset","content":[{"inlineContent":[{"type":"text","text":"The offset of the view finder."}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"A calculated rectangle of a potential view finder.","type":"text"}],"type":"paragraph"}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)\/title","op":"replace","value":"potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:offset:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView~1potentialViewFinderRectWithBounds(_:finderSafeArea:aspectRatio:minimumInsets:offset:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"potentialViewFinderRectWithBounds:finderSafeArea:aspectRatio:minimumInsets:offset:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView\/title","op":"replace","value":"SBSDKFinderView"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView\/fragments","op":"replace","value":[{"text":"SBSDKFinderView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKFinderView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}