{"kind":"symbol","abstract":[{"text":"The area where the finder should be placed in the coordinate system of the receiver.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Is ignored if finder safe area is empty (zero height or width)."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/finderSafeArea","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finderSafeArea"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"navigatorTitle":[{"text":"finderSafeArea","kind":"identifier"}],"title":"finderSafeArea","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration(py)finderSafeArea"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finderSafeArea"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Defaults to the zero rectangle.","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration\/findersafearea"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration\/findersafearea"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewFinderConfiguration":{"abstract":[{"type":"text","text":"The view finder configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"type":"text","text":" "},{"type":"text","text":"Sometimes it is necessary to limit a live video frame detection or recognition to a certain rectangular area with"},{"type":"text","text":" "},{"type":"text","text":"a specific aspect ratio: the region or rectangle of interest. This is where a view finder comes in."},{"text":" ","type":"text"},{"text":"It crops the video frame to that region of interest before passing it to any scanner. Usually","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the performance of scanners gain a benefit from it because less pixels must be processed."},{"type":"text","text":" "},{"text":"Additionally, to guide the user, the view finder visualizes the region of interest by drawing a rectangle around","type":"text"},{"type":"text","text":" "},{"type":"text","text":"on the user interface."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration","title":"SBSDKBaseScannerViewFinderConfiguration","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewFinderConfiguration/finderSafeArea":{"kind":"symbol","navigatorTitle":[{"text":"finderSafeArea","kind":"identifier"}],"abstract":[{"text":"The area where the finder should be placed in the coordinate system of the receiver.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Is ignored if finder safe area is empty (zero height or width)."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/finderSafeArea","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration\/findersafearea","type":"topic","role":"symbol","title":"finderSafeArea","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"finderSafeArea","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"finderSafeArea"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"finderSafeArea","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":" ","kind":"text"},{"text":"finderSafeArea","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"SBSDKBaseScannerViewFinderConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/navigatorTitle","op":"replace"},{"op":"replace","value":"finderSafeArea","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1finderSafeArea\/title"},{"value":[{"text":"finderSafeArea","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1finderSafeArea\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}