{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hazMatEndorsementExpiryDate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkaamvarecordfieldtype\/hazmatendorsementexpirydate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkaamvarecordfieldtype\/hazmatendorsementexpirydate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVARecordFieldType\/hazMatEndorsementExpiryDate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The HazMat endorsement expiry date."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hazMatEndorsementExpiryDate"}],"title":"SBSDKAAMVARecordFieldType.hazMatEndorsementExpiryDate","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKAAMVARecordFieldType@SBSDKAAMVARecordFieldTypeHazMatEndorsementExpiryDate","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeHazMatEndorsementExpiryDate"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVARecordFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAAMVARecordFieldType":{"role":"symbol","title":"SBSDKAAMVARecordFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAAMVARecordFieldType"}],"abstract":[{"type":"text","text":"The known values for AAMVA fields."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVARecordFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkaamvarecordfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAAMVARecordFieldType/hazMatEndorsementExpiryDate":{"role":"symbol","title":"SBSDKAAMVARecordFieldType.hazMatEndorsementExpiryDate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hazMatEndorsementExpiryDate"}],"abstract":[{"type":"text","text":"The HazMat endorsement expiry date."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVARecordFieldType\/hazMatEndorsementExpiryDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeHazMatEndorsementExpiryDate"}],"url":"\/documentation\/scanbotsdk\/sbsdkaamvarecordfieldtype\/hazmatendorsementexpirydate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKAAMVARecordFieldTypeHazMatEndorsementExpiryDate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeHazMatEndorsementExpiryDate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeHazMatEndorsementExpiryDate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVARecordFieldType\/title","value":"SBSDKAAMVARecordFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVARecordFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVARecordFieldType~1hazMatEndorsementExpiryDate\/title","value":"SBSDKAAMVARecordFieldTypeHazMatEndorsementExpiryDate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVARecordFieldType~1hazMatEndorsementExpiryDate\/fragments","value":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeHazMatEndorsementExpiryDate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}