{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"limitedDurationDocumentIndicator"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkaamvarecordfieldtype\/limiteddurationdocumentindicator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkaamvarecordfieldtype\/limiteddurationdocumentindicator"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVARecordFieldType\/limitedDurationDocumentIndicator","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The llimited duration document indicator."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"limitedDurationDocumentIndicator"}],"title":"SBSDKAAMVARecordFieldType.limitedDurationDocumentIndicator","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKAAMVARecordFieldType@SBSDKAAMVARecordFieldTypeLimitedDurationDocumentIndicator","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeLimitedDurationDocumentIndicator"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVARecordFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAAMVARecordFieldType":{"role":"symbol","title":"SBSDKAAMVARecordFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAAMVARecordFieldType"}],"abstract":[{"type":"text","text":"The known values for AAMVA fields."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVARecordFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkaamvarecordfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.2"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAAMVARecordFieldType/limitedDurationDocumentIndicator":{"role":"symbol","title":"SBSDKAAMVARecordFieldType.limitedDurationDocumentIndicator","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"limitedDurationDocumentIndicator"}],"abstract":[{"type":"text","text":"The llimited duration document indicator."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVARecordFieldType\/limitedDurationDocumentIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeLimitedDurationDocumentIndicator"}],"url":"\/documentation\/scanbotsdk\/sbsdkaamvarecordfieldtype\/limiteddurationdocumentindicator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKAAMVARecordFieldTypeLimitedDurationDocumentIndicator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeLimitedDurationDocumentIndicator"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeLimitedDurationDocumentIndicator"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVARecordFieldType\/title","value":"SBSDKAAMVARecordFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVARecordFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVARecordFieldType~1limitedDurationDocumentIndicator\/title","value":"SBSDKAAMVARecordFieldTypeLimitedDurationDocumentIndicator"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVARecordFieldType~1limitedDurationDocumentIndicator\/fragments","value":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeLimitedDurationDocumentIndicator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}