{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"standardEndorsementCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkaamvarecordfieldtype\/standardendorsementcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkaamvarecordfieldtype\/standardendorsementcode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVARecordFieldType\/standardEndorsementCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The standard endorsement code."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"standardEndorsementCode"}],"title":"SBSDKAAMVARecordFieldType.standardEndorsementCode","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKAAMVARecordFieldType@SBSDKAAMVARecordFieldTypeStandardEndorsementCode","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeStandardEndorsementCode"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVARecordFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAAMVARecordFieldType/standardEndorsementCode":{"role":"symbol","title":"SBSDKAAMVARecordFieldType.standardEndorsementCode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"standardEndorsementCode"}],"abstract":[{"type":"text","text":"The standard endorsement code."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVARecordFieldType\/standardEndorsementCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeStandardEndorsementCode"}],"url":"\/documentation\/scanbotsdk\/sbsdkaamvarecordfieldtype\/standardendorsementcode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAAMVARecordFieldType":{"role":"symbol","title":"SBSDKAAMVARecordFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAAMVARecordFieldType"}],"abstract":[{"type":"text","text":"The known values for AAMVA fields."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVARecordFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkaamvarecordfieldtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKAAMVARecordFieldTypeStandardEndorsementCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeStandardEndorsementCode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeStandardEndorsementCode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVARecordFieldType~1standardEndorsementCode\/title","value":"SBSDKAAMVARecordFieldTypeStandardEndorsementCode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVARecordFieldType~1standardEndorsementCode\/fragments","value":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldTypeStandardEndorsementCode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVARecordFieldType\/title","value":"SBSDKAAMVARecordFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVARecordFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKAAMVARecordFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}