{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerview\/ondrag(_:preview:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"nonisolated"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDrag"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"V"},{"kind":"text","text":">("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" () -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSItemProvider","text":"NSItemProvider"},{"kind":"text","text":", "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:7SwiftUI11ViewBuilderV","text":"ViewBuilder"},{"kind":"text","text":" "},{"kind":"externalParam","text":"preview"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"V"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"},{"kind":"text","text":" "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"V"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"},{"kind":"text","text":"\n"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView\/onDrag(_:preview:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onDrag","kind":"identifier"},{"text":"<","kind":"text"},{"text":"V","kind":"genericParameter"},{"text":">(() -> ","kind":"text"},{"text":"NSItemProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSItemProvider"},{"text":", ","kind":"text"},{"text":"preview","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"V","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"modules":[{"name":"ScanbotSDK","relatedModules":["SwiftUICore"]}],"title":"onDrag(_:preview:)","externalID":"s:7SwiftUI4ViewPAAE6onDrag_7previewQrSo14NSItemProviderCyc_qd__yXEtAaBRd__lF::SYNTHESIZED::s:10ScanbotSDK24SBSDKUI2CheckScannerViewV","roleHeading":"Instance Method","extendedModule":"SwiftUICore","platforms":[{"beta":false,"name":"iOS","deprecated":false,"introducedAt":"15.0","unavailable":false},{"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"15.0","unavailable":false},{"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"15.0","unavailable":false},{"beta":false,"name":"macOS","deprecated":false,"introducedAt":"12.0","unavailable":false}]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"View.onDrag(_:preview:)","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView\/View-Implementations"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerView/onDrag(_:preview:)":{"title":"onDrag(_:preview:)","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView\/onDrag(_:preview:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDrag"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"V"},{"kind":"text","text":">(() -> "},{"kind":"typeIdentifier","text":"NSItemProvider","preciseIdentifier":"c:objc(cs)NSItemProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"preview"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"V"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerview\/ondrag(_:preview:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CheckScannerViewController"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CheckScannerViewController"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerviewcontroller","role":"symbol","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan check data.","type":"text"}],"title":"SBSDKUI2CheckScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerView":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerview","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CheckScannerView","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CheckScannerView","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView","role":"symbol","title":"SBSDKUI2CheckScannerView","abstract":[{"text":"The SwiftUI wrapper for ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerView/View-Implementations":{"type":"topic","title":"View Implementations","kind":"article","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView\/View-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerview\/view-implementations","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2CheckScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CheckScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CheckScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController\/navigatorTitle","op":"replace"}]}]}