{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelHIBC\/initWithGenericDocument:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelHIBC"]]},"metadata":{"title":"initWithGenericDocument:","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelHIBC(im)initWithGenericDocument:","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelhibc\/initwithgenericdocument:"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"initWithGenericDocument:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKGenericDocument","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"document"},{"text":";","kind":"text"}]}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelHIBC":{"kind":"symbol","type":"topic","abstract":[{"text":"HIBC","type":"text"}],"title":"SBSDKBarcodeDocumentModelHIBC","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelhibc","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelHIBC"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelHIBC","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelHIBC","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocument","kind":"identifier"}],"title":"SBSDKGenericDocument","type":"topic","abstract":[{"type":"text","text":"Generic document."}],"navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelHIBC/initWithGenericDocument:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelHIBC\/initWithGenericDocument:","title":"initWithGenericDocument:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelhibc\/initwithgenericdocument:","type":"topic","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGenericDocument:"}],"kind":"symbol","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKBarcodeDocumentModelHIBC","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelHIBC\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelHIBC"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelHIBC\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelHIBC\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelHIBC"}],"op":"replace"},{"value":"SBSDKGenericDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}