{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration\/init(visible:counterBadge:automaticSelectionEnabled:barcodeItemInfoPosition:polygon:barcodeItemConfiguration:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration\/init(visible:counterbadge:automaticselectionenabled:barcodeiteminfoposition:polygon:barcodeitemconfiguration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration\/init(visible:counterbadge:automaticselectionenabled:barcodeiteminfoposition:polygon:barcodeitemconfiguration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration(im)initWithVisible:counterBadge:automaticSelectionEnabled:barcodeItemInfoPosition:polygon:barcodeItemConfiguration:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"visible"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"counterBadge","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BadgeStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgeStyle"},{"kind":"text","text":", "},{"text":"automaticSelectionEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"barcodeItemInfoPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeItemInfoPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodeItemInfoPosition"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ArOverlayPolygonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayPolygonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"barcodeItemConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeItemConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItemConfiguration"},{"text":")","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"init","role":"symbol","title":"init(visible:counterBadge:automaticSelectionEnabled:barcodeItemInfoPosition:polygon:barcodeItemConfiguration:)","navigatorTitle":[{"kind":"identifier","text":"initWithVisible:counterBadge:automaticSelectionEnabled:barcodeItemInfoPosition:polygon:barcodeItemConfiguration:"}],"roleHeading":"Initializer"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"visible","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"counterBadge"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgeStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgeStyle","text":"SBSDKUI2BadgeStyle","kind":"typeIdentifier"},{"text":" = SBSDKUI2BadgeStyle(background: SBSDKUI2BackgroundStyle(),\n                                                                      foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                     isArgb: false)), ","kind":"text"},{"text":"automaticSelectionEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = false, ","kind":"text"},{"text":"barcodeItemInfoPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemInfoPosition","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodeItemInfoPosition","text":"SBSDKUI2BarcodeItemInfoPosition"},{"text":" = SBSDKUI2BarcodeItemInfoPosition.below, ","kind":"text"},{"kind":"externalParam","text":"polygon"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayPolygonConfiguration","text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration"},{"text":" = SBSDKUI2ArOverlayPolygonConfiguration(visible: true,\n                                                                                                       deselected: SBSDKUI2PolygonStyle(),\n                                                                                                       selected: SBSDKUI2PolygonStyle()), ","kind":"text"},{"kind":"externalParam","text":"barcodeItemConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeItemConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItemConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemConfiguration"},{"kind":"text","text":" = SBSDKUI2BarcodeItemConfiguration(imageVisible: true,\n                                                     titleSelected: SBSDKUI2StyledText(text: \"BARCODE_TITLE\",\n                                                                                       color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                            isArgb: false)),\n                                                     subtitleSelected: SBSDKUI2StyledText(text: \"BARCODE_SUBTITLE\",\n                                                                                          color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                               isArgb: false)),\n                                                     titleDeselected: SBSDKUI2StyledText(text: \"BARCODE_TITLE\",\n                                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                              isArgb: false)),\n                                                     subtitleDeselected: SBSDKUI2StyledText(text: \"BARCODE_SUBTITLE\",\n                                                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                                 isArgb: false)),\n                                                     backgroundSelected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                         isArgb: false),\n                                                                                              fillColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                       isArgb: false),\n                                                                                              strokeWidth: 1.0,\n                                                                                              cornerRadius: 5.0),\n                                                     backgroundDeselected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                           isArgb: false),\n                                                                                                fillColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                         isArgb: false),\n                                                                                                strokeWidth: 1.0,\n                                                                                                cornerRadius: 5.0)))"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayGeneralConfiguration":{"kind":"symbol","title":"SBSDKUI2ArOverlayGeneralConfiguration","navigatorTitle":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the AR overlay displayed on top of barcodes in the camera preview."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemInfoPosition":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeiteminfoposition","abstract":[{"text":"Where to display the barcode info box in the camera preview.","type":"text"}],"role":"symbol","kind":"symbol","title":"SBSDKUI2BarcodeItemInfoPosition","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemInfoPosition","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemInfoPosition"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeItemInfoPosition"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BadgeStyle":{"type":"topic","abstract":[{"type":"text","text":"Configuration of the badge."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BadgeStyle"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgeStyle","title":"SBSDKUI2BadgeStyle","url":"\/documentation\/scanbotsdk\/sbsdkui2badgestyle","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BadgeStyle"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}],"abstract":[{"text":"Configuration of the barcode info box displayed in the camera preview.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitemconfiguration","title":"SBSDKUI2BarcodeItemConfiguration","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeItemConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayGeneralConfiguration/init(visible:counterBadge:automaticSelectionEnabled:barcodeItemInfoPosition:polygon:barcodeItemConfiguration:)":{"kind":"symbol","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithVisible:counterBadge:automaticSelectionEnabled:barcodeItemInfoPosition:polygon:barcodeItemConfiguration:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"visible"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"counterBadge"},{"kind":"text","text":": "},{"text":"SBSDKUI2BadgeStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgeStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"automaticSelectionEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"barcodeItemInfoPosition","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeItemInfoPosition","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodeItemInfoPosition"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2ArOverlayPolygonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayPolygonConfiguration"},{"text":", ","kind":"text"},{"text":"barcodeItemConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeItemConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItemConfiguration"},{"kind":"text","text":")"}],"title":"init(visible:counterBadge:automaticSelectionEnabled:barcodeItemInfoPosition:polygon:barcodeItemConfiguration:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration\/init(visible:counterBadge:automaticSelectionEnabled:barcodeItemInfoPosition:polygon:barcodeItemConfiguration:)","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration\/init(visible:counterbadge:automaticselectionenabled:barcodeiteminfoposition:polygon:barcodeitemconfiguration:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayPolygonConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ArOverlayPolygonConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration","abstract":[{"type":"text","text":"Configuration of the overlay polygon displayed on top of a barcode in the camera preview."}],"role":"symbol","kind":"symbol","title":"SBSDKUI2ArOverlayPolygonConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ArOverlayPolygonConfiguration"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"initWithVisible:counterBadge:automaticSelectionEnabled:barcodeItemInfoPosition:polygon:barcodeItemConfiguration:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVisible:counterBadge:automaticSelectionEnabled:barcodeItemInfoPosition:polygon:barcodeItemConfiguration:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"visible"},{"text":" ","kind":"text"},{"kind":"identifier","text":"counterBadge:"},{"kind":"text","text":"("},{"text":"SBSDKUI2BadgeStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgeStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgeStyle"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"counterBadge"},{"text":" ","kind":"text"},{"text":"automaticSelectionEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"automaticSelectionEnabled"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeItemInfoPosition:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeItemInfoPosition","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemInfoPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodeItemInfoPosition"},{"kind":"text","text":") "},{"kind":"internalParam","text":"barcodeItemInfoPosition"},{"text":" ","kind":"text"},{"text":"polygon:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ArOverlayPolygonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayPolygonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"polygon","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeItemConfiguration:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItemConfiguration","text":"SBSDKUI2BarcodeItemConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"barcodeItemConfiguration","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2ArOverlayGeneralConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/fragments","value":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2BarcodeItemInfoPosition","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemInfoPosition\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemInfoPosition\/fragments","value":[{"text":"SBSDKUI2BarcodeItemInfoPosition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemInfoPosition\/navigatorTitle","value":[{"text":"SBSDKUI2BarcodeItemInfoPosition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgeStyle\/title","value":"SBSDKUI2BadgeStyle","op":"replace"},{"value":[{"text":"SBSDKUI2BadgeStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgeStyle\/fragments","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2BadgeStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgeStyle\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemConfiguration\/title","value":"SBSDKUI2BarcodeItemConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration~1init(visible:counterBadge:automaticSelectionEnabled:barcodeItemInfoPosition:polygon:barcodeItemConfiguration:)\/title","value":"initWithVisible:counterBadge:automaticSelectionEnabled:barcodeItemInfoPosition:polygon:barcodeItemConfiguration:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithVisible:counterBadge:automaticSelectionEnabled:barcodeItemInfoPosition:polygon:barcodeItemConfiguration:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration~1init(visible:counterBadge:automaticSelectionEnabled:barcodeItemInfoPosition:polygon:barcodeItemConfiguration:)\/fragments"},{"value":"SBSDKUI2ArOverlayPolygonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayPolygonConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}