{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarOpenIntroScreenButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","text":"SBSDKUI2IconButton"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration\/topbaropenintroscreenbutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration\/topbaropenintroscreenbutton"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorScreenConfiguration(py)topBarOpenIntroScreenButton","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"topBarOpenIntroScreenButton"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarOpenIntroScreenButton"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","kind":"typeIdentifier","text":"SBSDKUI2IconButton"}],"title":"topBarOpenIntroScreenButton"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration\/topBarOpenIntroScreenButton","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Configuration of the button in the top bar that opens the introduction screen."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IconButton":{"title":"SBSDKUI2IconButton","abstract":[{"text":"Configuration of the icon appearance on a button.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2iconbutton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2IconButton","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2IconButton","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration","kind":"symbol","type":"topic","title":"SBSDKUI2DocumentDataExtractorScreenConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenConfiguration"}],"abstract":[{"text":"Configuration of the screen for extracting data from ID documents.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenConfiguration/topBarOpenIntroScreenButton":{"kind":"symbol","title":"topBarOpenIntroScreenButton","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration\/topbaropenintroscreenbutton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration\/topBarOpenIntroScreenButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarOpenIntroScreenButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","text":"SBSDKUI2IconButton","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Configuration of the button in the top bar that opens the introduction screen.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"topBarOpenIntroScreenButton","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"topBarOpenIntroScreenButton","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"topBarOpenIntroScreenButton"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton","text":"SBSDKUI2IconButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton"},{"text":" * ","kind":"text"},{"text":"topBarOpenIntroScreenButton","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/title","value":"SBSDKUI2IconButton","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IconButton"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2IconButton"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration\/title","value":"SBSDKUI2DocumentDataExtractorScreenConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration\/fragments","value":[{"text":"SBSDKUI2DocumentDataExtractorScreenConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentDataExtractorScreenConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration~1topBarOpenIntroScreenButton\/title","value":"topBarOpenIntroScreenButton","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration~1topBarOpenIntroScreenButton\/fragments","value":[{"text":"topBarOpenIntroScreenButton","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}