{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/dualwide"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/dualwide"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/dualWide","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeDualWide"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dualWide","kind":"identifier"}],"symbolKind":"case","role":"symbol","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKCameraDeviceType@SBSDKCameraDeviceTypeDualWide","title":"SBSDKCameraDeviceType.dualWide"},"sections":[],"abstract":[{"type":"text","text":"The dual-wide lens\/device (wide + ultra-wide)."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dualWide"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType/dualWide":{"abstract":[{"text":"The dual-wide lens\/device (wide + ultra-wide).","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/dualWide","type":"topic","navigatorTitle":[{"text":"SBSDKCameraDeviceTypeDualWide","kind":"identifier"}],"title":"SBSDKCameraDeviceType.dualWide","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dualWide","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/dualwide","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType":{"role":"symbol","navigatorTitle":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"abstract":[{"text":"An enum to describe the different types of camera lenses\/devices.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"type":"topic","title":"SBSDKCameraDeviceType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKCameraDeviceTypeDualWide","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeDualWide"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKCameraDeviceTypeDualWide","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1dualWide\/title","value":"SBSDKCameraDeviceTypeDualWide"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1dualWide\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeDualWide"}]},{"value":"SBSDKCameraDeviceType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraDeviceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}