{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ultraWide"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/ultrawide"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/ultrawide"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType"]]},"sections":[],"abstract":[{"text":"The ultra-wide lens\/device.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/ultraWide","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKCameraDeviceType@SBSDKCameraDeviceTypeUltraWide","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"ultraWide","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","title":"SBSDKCameraDeviceType.ultraWide","navigatorTitle":[{"text":"SBSDKCameraDeviceTypeUltraWide","kind":"identifier"}],"roleHeading":"Case"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType/ultraWide":{"title":"SBSDKCameraDeviceType.ultraWide","url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/ultrawide","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"ultraWide","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/ultraWide","navigatorTitle":[{"text":"SBSDKCameraDeviceTypeUltraWide","kind":"identifier"}],"abstract":[{"type":"text","text":"The ultra-wide lens\/device."}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype","role":"symbol","abstract":[{"type":"text","text":"An enum to describe the different types of camera lenses\/devices."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraDeviceType"}],"navigatorTitle":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"title":"SBSDKCameraDeviceType","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"SBSDKCameraDeviceTypeUltraWide","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeUltraWide"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKCameraDeviceTypeUltraWide","kind":"identifier"}]}]},"op":"replace"},{"value":"SBSDKCameraDeviceTypeUltraWide","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1ultraWide\/title"},{"value":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeUltraWide"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1ultraWide\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/title","value":"SBSDKCameraDeviceType","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCameraDeviceType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}