{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/wide","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wide"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The wide angle lens\/device."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/wide"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/wide"]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"wide","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKCameraDeviceType@SBSDKCameraDeviceTypeWide","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeWide"}],"symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","title":"SBSDKCameraDeviceType.wide"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType/wide":{"url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/wide","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/wide","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeWide"}],"kind":"symbol","type":"topic","abstract":[{"text":"The wide angle lens\/device.","type":"text"}],"title":"SBSDKCameraDeviceType.wide","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"wide"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType","title":"SBSDKCameraDeviceType","abstract":[{"type":"text","text":"An enum to describe the different types of camera lenses\/devices."}],"url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCameraDeviceType"}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDeviceType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKCameraDeviceTypeWide","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKCameraDeviceTypeWide","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeWide"}]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKCameraDeviceTypeWide","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1wide\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1wide\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeWide"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/title","value":"SBSDKCameraDeviceType"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraDeviceType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/fragments"}]}]}