{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetContent"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetContent\/isEqual:","interfaceLanguage":"occ"},"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2SheetContent(im)isEqual:","title":"isEqual:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"symbolKind":"method","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheetcontent\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SheetContent/isEqual:":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetContent\/isEqual:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheetcontent\/isequal:","kind":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SheetContent":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetContent","title":"SBSDKUI2SheetContent","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2SheetContent","kind":"identifier"}],"abstract":[{"text":"Configuration of the list containing the barcodes that have already been scanned.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheetcontent","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2SheetContent","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetContent\/title","value":"SBSDKUI2SheetContent","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2SheetContent","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetContent\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetContent\/navigatorTitle","value":[{"text":"SBSDKUI2SheetContent","kind":"identifier"}],"op":"replace"}]}]}