{"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMoIdentityCardBack(py)mrz","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mrz"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentsModelMRZ","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMRZ","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"mrz","navigatorTitle":[{"kind":"identifier","text":"mrz"}],"roleHeading":"Instance Property","role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMoIdentityCardBack\/mrz","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"The child document of type “MRZ”."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMoIdentityCardBack"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrz"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentsModelMRZ","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMRZ","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMRZ"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmoidentitycardback\/mrz"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmoidentitycardback\/mrz"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelMoIdentityCardBack":{"abstract":[{"text":"MoIdentityCardBack","type":"text"}],"navigatorTitle":[{"text":"SBSDKDocumentsModelMoIdentityCardBack","kind":"identifier"}],"title":"SBSDKDocumentsModelMoIdentityCardBack","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmoidentitycardback","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelMoIdentityCardBack"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMoIdentityCardBack"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelMRZ":{"title":"SBSDKDocumentsModelMRZ","role":"symbol","type":"topic","abstract":[{"text":"MRZ part of the document","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelMRZ","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMRZ","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelMRZ"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmrz"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelMoIdentityCardBack/mrz":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrz"},{"kind":"text","text":": "},{"text":"SBSDKDocumentsModelMRZ","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMRZ"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The child document of type “MRZ”."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMoIdentityCardBack\/mrz","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmoidentitycardback\/mrz","kind":"symbol","type":"topic","title":"mrz","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mrz"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"mrz","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mrz"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMRZ","text":"SBSDKDocumentsModelMRZ","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMRZ","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"mrz","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","value":"SBSDKDocumentsModelMoIdentityCardBack","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMoIdentityCardBack\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMoIdentityCardBack\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentsModelMoIdentityCardBack"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMoIdentityCardBack\/navigatorTitle","value":[{"text":"SBSDKDocumentsModelMoIdentityCardBack","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMRZ\/title","value":"SBSDKDocumentsModelMRZ","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMRZ\/fragments","op":"replace","value":[{"text":"SBSDKDocumentsModelMRZ","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKDocumentsModelMRZ"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMRZ\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMoIdentityCardBack~1mrz\/title","value":"mrz","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMoIdentityCardBack~1mrz\/fragments","value":[{"text":"mrz","kind":"identifier"}],"op":"replace"}]}]}