{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionMetrics\/matches(aspectRatio:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionMetrics"]]},"abstract":[{"text":"Checks if the passed aspect ratio matches the ","type":"text"},{"type":"codeVoice","code":"unwarpedAspectRatio"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"matches"},{"text":"(","kind":"text"},{"text":"aspectRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio","text":"SBSDKAspectRatio"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio","isActive":true},{"text":" to compare.","type":"text"}]}],"name":"aspectRatio"}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"True"},{"text":", if the given aspect ratio matches the receivers ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionMetrics\/unwarpedAspectRatio"},{"type":"text","text":" in a fuzzy way."}]}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionMetrics(im)matchesWithAspectRatio:","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"matches"},{"kind":"text","text":"("},{"text":"aspectRatio","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio","text":"SBSDKAspectRatio"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"matches(aspectRatio:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"matchesWithAspectRatio:"}],"roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionmetrics\/matches(aspectratio:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionmetrics\/matches(aspectratio:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAspectRatio":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAspectRatio"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKAspectRatio"}],"title":"SBSDKAspectRatio","url":"\/documentation\/scanbotsdk\/sbsdkaspectratio","abstract":[{"text":"A class that describes an aspect ratio for a document page.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionMetrics":{"kind":"symbol","title":"SBSDKDocumentDetectionMetrics","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionMetrics","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionMetrics"}],"abstract":[{"text":"The metrics and additional properties returned by ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector","isActive":true},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Can be used to make decisions on polygon acceptance, automatic capturing and user guidance.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDetectionMetrics","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionmetrics"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionMetrics/matches(aspectRatio:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"matches","kind":"identifier"},{"text":"(","kind":"text"},{"text":"aspectRatio","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio","kind":"typeIdentifier","text":"SBSDKAspectRatio"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Checks if the passed aspect ratio matches the "},{"type":"codeVoice","code":"unwarpedAspectRatio"},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionMetrics\/matches(aspectRatio:)","navigatorTitle":[{"kind":"identifier","text":"matchesWithAspectRatio:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionmetrics\/matches(aspectratio:)","title":"matches(aspectRatio:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector":{"kind":"symbol","title":"SBSDKDocumentDetector","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetector"}],"abstract":[{"type":"text","text":"A class to detect a document’s outline polygon in a UIImage or CMSampleBufferRef."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetector"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionMetrics/unwarpedAspectRatio":{"role":"symbol","title":"unwarpedAspectRatio","navigatorTitle":[{"kind":"identifier","text":"unwarpedAspectRatio"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unwarpedAspectRatio","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionmetrics\/unwarpedaspectratio","kind":"symbol","abstract":[{"text":"The unwarped aspect ratio of the detected polygon or -1, if no polygon was detected.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionMetrics\/unwarpedAspectRatio"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"matchesWithAspectRatio:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"matchesWithAspectRatio:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"matchesWithAspectRatio:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio","text":"SBSDKAspectRatio","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aspectRatio"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"aspectRatio","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio","isActive":true},{"type":"text","text":" to compare."}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"True"},{"text":", if the given aspect ratio matches the receivers ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionMetrics\/unwarpedAspectRatio","isActive":true,"type":"reference"},{"type":"text","text":" in a fuzzy way."}],"type":"paragraph"}],"kind":"content"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatio\/title","op":"replace","value":"SBSDKAspectRatio"},{"value":[{"kind":"identifier","text":"SBSDKAspectRatio"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatio\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatio\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKAspectRatio"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionMetrics\/title","value":"SBSDKDocumentDetectionMetrics"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionMetrics"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionMetrics\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionMetrics"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionMetrics\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionMetrics~1matches(aspectRatio:)\/title","value":"matchesWithAspectRatio:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionMetrics~1matches(aspectRatio:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"matchesWithAspectRatio:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/title","value":"SBSDKDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetector"}]},{"value":[{"text":"SBSDKDocumentDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/navigatorTitle"},{"value":"unwarpedAspectRatio","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionMetrics~1unwarpedAspectRatio\/title","op":"replace"},{"value":[{"kind":"identifier","text":"unwarpedAspectRatio"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionMetrics~1unwarpedAspectRatio\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}