{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller\/barcodescannercontrollershouldscanbarcodes:"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeScannerControllerShouldScanBarcodes:"},"kind":"symbol","metadata":{"externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController(im)barcodeScannerControllerShouldScanBarcodes:","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"barcodeScannerControllerShouldScanBarcodes:"}],"navigatorTitle":[{"text":"barcodeScannerControllerShouldScanBarcodes:","kind":"identifier"}],"role":"symbol","title":"barcodeScannerControllerShouldScanBarcodes:","symbolKind":"method","roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"barcodeScannerControllerShouldScanBarcodes:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController","kind":"typeIdentifier","text":"SBSDKBarcodeScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController"},{"kind":"text","text":" *) "},{"text":"controller","kind":"internalParam"},{"kind":"text","text":";"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewController/barcodeScannerControllerShouldScanBarcodes:":{"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller\/barcodescannercontrollershouldscanbarcodes:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"barcodeScannerControllerShouldScanBarcodes:"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeScannerControllerShouldScanBarcodes:","type":"topic","kind":"symbol","title":"barcodeScannerControllerShouldScanBarcodes:","navigatorTitle":[{"kind":"identifier","text":"barcodeScannerControllerShouldScanBarcodes:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"title":"SBSDKBarcodeScannerViewController","kind":"symbol","abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show a camera screen with the barcode scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller","navigatorTitle":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller","deprecated":true,"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"title":"SBSDKUIBarcodesBatchScannerViewController","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan barcodes batches."}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKBarcodeScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/title","value":"SBSDKUIBarcodesBatchScannerViewController"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/navigatorTitle","value":[{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}