{"abstract":[{"text":"The app is inactive and in background.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/inactive"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkapplicationstate\/inactive"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkapplicationstate\/inactive"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"title":"SBSDKApplicationState.inactive","navigatorTitle":[{"kind":"identifier","text":"SBSDKApplicationStateInactive"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKApplicationState@SBSDKApplicationStateInactive","symbolKind":"case","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inactive"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inactive","kind":"identifier"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKApplicationState/inactive":{"abstract":[{"type":"text","text":"The app is inactive and in background."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inactive"}],"url":"\/documentation\/scanbotsdk\/sbsdkapplicationstate\/inactive","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/inactive","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKApplicationStateInactive"}],"type":"topic","title":"SBSDKApplicationState.inactive"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKApplicationState":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKApplicationState"}],"url":"\/documentation\/scanbotsdk\/sbsdkapplicationstate","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An enum describing the current state of the app."}],"title":"SBSDKApplicationState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKApplicationState"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKApplicationStateInactive","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKApplicationStateInactive","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"SBSDKApplicationStateInactive","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKApplicationStateInactive","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState~1inactive\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState~1inactive\/fragments","value":[{"kind":"identifier","text":"SBSDKApplicationStateInactive"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState\/title","value":"SBSDKApplicationState","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState\/fragments","value":[{"kind":"identifier","text":"SBSDKApplicationState"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState\/navigatorTitle","value":[{"text":"SBSDKApplicationState","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}