{"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"unsubscribe(_:)","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"unsubscribe:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAnalyticsManager(im)unsubscribe:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unsubscribe"},{"text":"(","kind":"text"},{"text":"SBSDKAnalyticsSubscriber","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKAnalyticsSubscriber"},{"text":")","kind":"text"}],"symbolKind":"method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsManager\/unsubscribe(_:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unsubscribe"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"subscriber","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsSubscriber","kind":"typeIdentifier","text":"SBSDKAnalyticsSubscriber","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKAnalyticsSubscriber"},{"kind":"text","text":")"}]}]}],"abstract":[{"type":"text","text":"Unsubscribes a subscriber from receiving analytics events."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkanalyticsmanager\/unsubscribe(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkanalyticsmanager\/unsubscribe(_:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsManager"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAnalyticsManager/unsubscribe(_:)":{"kind":"symbol","title":"unsubscribe(_:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkanalyticsmanager\/unsubscribe(_:)","role":"symbol","navigatorTitle":[{"text":"unsubscribe:","kind":"identifier"}],"abstract":[{"text":"Unsubscribes a subscriber from receiving analytics events.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsManager\/unsubscribe(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"unsubscribe","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKAnalyticsSubscriber","text":"SBSDKAnalyticsSubscriber"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAnalyticsManager":{"navigatorTitle":[{"text":"SBSDKAnalyticsManager","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkanalyticsmanager","title":"SBSDKAnalyticsManager","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsManager","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAnalyticsManager","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"codeVoice","code":"SBSDKAnalyticsManager"},{"type":"text","text":" is a singleton class that manages analytics events within the Scanbot SDK."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAnalyticsSubscriber":{"navigatorTitle":[{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkanalyticssubscriber","title":"SBSDKAnalyticsSubscriber","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsSubscriber","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"The subscriber that is being tracked.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"unsubscribe:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unsubscribe:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"unsubscribe:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKAnalyticsSubscriber","text":"id<SBSDKAnalyticsSubscriber>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"subscriber","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"unsubscribe:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsManager~1unsubscribe(_:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsManager~1unsubscribe(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unsubscribe:"}]},{"value":"SBSDKAnalyticsManager","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsManager\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsManager\/fragments","value":[{"kind":"identifier","text":"SBSDKAnalyticsManager"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAnalyticsManager"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsManager\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsSubscriber\/title","value":"SBSDKAnalyticsSubscriber"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsSubscriber\/fragments","value":[{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsSubscriber\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}]}]}]}