{"abstract":[{"text":"An unknown or unexpected error occurred.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrortype\/unknownerror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrortype\/unknownerror"]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKErrorType@SBSDKErrorTypeUnknownError","symbolKind":"case","title":"SBSDKErrorType.unknownError","role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeUnknownError"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/unknownError"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/unknownError":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"kind":"symbol","abstract":[{"type":"text","text":"An unknown or unexpected error occurred."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeUnknownError"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/unknownError","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/unknownerror","title":"SBSDKErrorType.unknownError"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorType"}],"url":"\/documentation\/scanbotsdk\/sbsdkerrortype","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKErrorType"}],"abstract":[{"type":"text","text":"An Objective-C compatible enum representing the types of errors that can occur within the Scanbot SDK."},{"type":"text","text":" "},{"type":"text","text":"Each case corresponds to a specific error code."}],"kind":"symbol","title":"SBSDKErrorType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKErrorTypeUnknownError","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKErrorTypeUnknownError","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKErrorTypeUnknownError"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKErrorTypeUnknownError","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1unknownError\/title"},{"op":"replace","value":[{"text":"SBSDKErrorTypeUnknownError","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1unknownError\/fragments"},{"op":"replace","value":"SBSDKErrorType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType\/fragments"},{"op":"replace","value":[{"text":"SBSDKErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}