{"abstract":[{"type":"text","text":"7.25 x 10.5 (inches)     522 x 756 (pixels) at 72 DPI."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/executive","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"SBSDKPageSize.executive","externalID":"c:@M@ScanbotSDK@E@SBSDKPageSize@SBSDKPageSizeExecutive","symbolKind":"case","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"executive"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSizeExecutive"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"executive"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagesize\/executive"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagesize\/executive"]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/executive":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/executive","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"executive","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/executive","abstract":[{"type":"text","text":"7.25 x 10.5 (inches)     522 x 756 (pixels) at 72 DPI."}],"type":"topic","navigatorTitle":[{"text":"SBSDKPageSizeExecutive","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"SBSDKPageSize.executive"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize":{"url":"\/documentation\/scanbotsdk\/sbsdkpagesize","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSize"}],"kind":"symbol","title":"SBSDKPageSize","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPageSize"}],"abstract":[{"text":"Page size.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKPageSizeExecutive"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPageSizeExecutive"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKPageSizeExecutive"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1executive\/title","op":"replace","value":"SBSDKPageSizeExecutive"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1executive\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPageSizeExecutive"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/title","op":"replace","value":"SBSDKPageSize"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPageSize"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPageSize"}]}]}]}