{"abstract":[{"text":"The ‘submit’ button title, located in the bottom bar of the review screen.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/reviewscreensubmitbuttontitle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/reviewscreensubmitbuttontitle"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/reviewScreenSubmitButtonTitle"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"reviewScreenSubmitButtonTitle","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is “Submit”","type":"text"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization(py)reviewScreenSubmitButtonTitle","role":"symbol","title":"reviewScreenSubmitButtonTitle","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"reviewScreenSubmitButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"reviewScreenSubmitButtonTitle"}],"roleHeading":"Instance Property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization/reviewScreenSubmitButtonTitle":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewScreenSubmitButtonTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"reviewScreenSubmitButtonTitle","abstract":[{"type":"text","text":"The ‘submit’ button title, located in the bottom bar of the review screen."}],"navigatorTitle":[{"text":"reviewScreenSubmitButtonTitle","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization\/reviewScreenSubmitButtonTitle","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization\/reviewscreensubmitbuttontitle","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerTextLocalization":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannertextlocalization","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"kind":"symbol","title":"SBSDKUI2DocumentScannerTextLocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerTextLocalization","abstract":[{"text":"Configuration of all the strings for the standalone cropping screen.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"reviewScreenSubmitButtonTitle","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"reviewScreenSubmitButtonTitle"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"reviewScreenSubmitButtonTitle","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization~1reviewScreenSubmitButtonTitle\/title","value":"reviewScreenSubmitButtonTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization~1reviewScreenSubmitButtonTitle\/fragments","value":[{"kind":"identifier","text":"reviewScreenSubmitButtonTitle"}],"op":"replace"},{"value":"SBSDKUI2DocumentScannerTextLocalization","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerTextLocalization\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"op":"replace"}]}]}