{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickscanningmode\/countingrepeatdelay"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickscanningmode\/countingrepeatdelay"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"countingRepeatDelay"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FindAndPickScanningMode(py)countingRepeatDelay","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"countingRepeatDelay"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","title":"countingRepeatDelay","symbolKind":"property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickScanningMode"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"countingRepeatDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Time interval in milliseconds before a barcode is counted again. 0 = no delay. The default value is 1000."},{"type":"text","text":" "},{"type":"text","text":"Default is 1000"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickScanningMode\/countingRepeatDelay","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickScanningMode/countingRepeatDelay":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"countingRepeatDelay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickScanningMode\/countingRepeatDelay","navigatorTitle":[{"text":"countingRepeatDelay","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickscanningmode\/countingrepeatdelay","abstract":[{"text":"Time interval in milliseconds before a barcode is counted again. 0 = no delay. The default value is 1000.","type":"text"},{"text":" ","type":"text"},{"text":"Default is 1000","type":"text"}],"role":"symbol","title":"countingRepeatDelay"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickScanningMode":{"abstract":[{"text":"Configuration of the Find and Pick barcode scanning mode.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickscanningmode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}],"kind":"symbol","type":"topic","title":"SBSDKUI2FindAndPickScanningMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickScanningMode","navigatorTitle":[{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"countingRepeatDelay","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"countingRepeatDelay","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"countingRepeatDelay","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickScanningMode~1countingRepeatDelay\/title","value":"countingRepeatDelay","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickScanningMode~1countingRepeatDelay\/fragments","value":[{"text":"countingRepeatDelay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickScanningMode\/title","value":"SBSDKUI2FindAndPickScanningMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickScanningMode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2FindAndPickScanningMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickScanningMode\/navigatorTitle","value":[{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}],"op":"replace"}]}]}