{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBitmapMemoryConsumption:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"bitmapMemoryConsumption"},{"kind":"text","text":" "},{"kind":"identifier","text":"hibernationMemoryConsumption:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"hibernationMemoryConsumption"},{"kind":"text","text":";"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProfile\/initWithBitmapMemoryConsumption:hibernationMemoryConsumption:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProfile"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"initWithBitmapMemoryConsumption:hibernationMemoryConsumption:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageProfile(im)initWithBitmapMemoryConsumption:hibernationMemoryConsumption:","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithBitmapMemoryConsumption:hibernationMemoryConsumption:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBitmapMemoryConsumption:hibernationMemoryConsumption:"}],"symbolKind":"method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimageprofile\/initwithbitmapmemoryconsumption:hibernationmemoryconsumption:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProfile/initWithBitmapMemoryConsumption:hibernationMemoryConsumption:":{"role":"symbol","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProfile\/initWithBitmapMemoryConsumption:hibernationMemoryConsumption:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBitmapMemoryConsumption:hibernationMemoryConsumption:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBitmapMemoryConsumption:hibernationMemoryConsumption:"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageprofile\/initwithbitmapmemoryconsumption:hibernationmemoryconsumption:","title":"initWithBitmapMemoryConsumption:hibernationMemoryConsumption:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProfile":{"navigatorTitle":[{"text":"SBSDKImageProfile","kind":"identifier"}],"abstract":[{"text":"ImageRef profile part specific to image information.","type":"text"}],"title":"SBSDKImageProfile","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProfile","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageProfile","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageprofile","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProfile\/title","value":"SBSDKImageProfile"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProfile\/fragments","value":[{"text":"SBSDKImageProfile","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProfile\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageProfile"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}