{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferImageLoadOptions"]]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbufferimageloadoptions\/initwithcroprect:colorconversion:canvascolor:loadmode:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferImageLoadOptions\/initWithCropRect:colorConversion:canvasColor:loadMode:"},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"initWithCropRect:colorConversion:canvasColor:loadMode:","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBufferImageLoadOptions(im)initWithCropRect:colorConversion:canvasColor:loadMode:","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCropRect:colorConversion:canvasColor:loadMode:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithCropRect:colorConversion:canvasColor:loadMode:","kind":"identifier"}],"role":"symbol","symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCropRect:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cropRect"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorConversion:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKColorConversion","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKColorConversion","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKColorConversion"},{"kind":"text","text":") "},{"kind":"internalParam","text":"colorConversion"},{"kind":"text","text":" "},{"kind":"identifier","text":"canvasColor:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKCanvasColor","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCanvasColor","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCanvasColor"},{"kind":"text","text":") "},{"kind":"internalParam","text":"canvasColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKBufferLoadMode","text":"SBSDKBufferLoadMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferLoadMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"loadMode"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKColorConversion":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcolorconversion","title":"SBSDKColorConversion","role":"symbol","abstract":[{"text":"Color conversion to apply during image loading.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKColorConversion","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKColorConversion","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKColorConversion","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBufferImageLoadOptions":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferImageLoadOptions","navigatorTitle":[{"text":"SBSDKBufferImageLoadOptions","kind":"identifier"}],"kind":"symbol","title":"SBSDKBufferImageLoadOptions","role":"symbol","abstract":[{"type":"text","text":"Options for loading image from buffer."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbufferimageloadoptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBufferImageLoadOptions","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBufferImageLoadOptions/initWithCropRect:colorConversion:canvasColor:loadMode:":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbufferimageloadoptions\/initwithcroprect:colorconversion:canvascolor:loadmode:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferImageLoadOptions\/initWithCropRect:colorConversion:canvasColor:loadMode:","kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCropRect:colorConversion:canvasColor:loadMode:","kind":"identifier"}],"title":"initWithCropRect:colorConversion:canvasColor:loadMode:","navigatorTitle":[{"text":"initWithCropRect:colorConversion:canvasColor:loadMode:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCanvasColor":{"role":"symbol","navigatorTitle":[{"text":"SBSDKCanvasColor","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Canvas color to use when converting images with alpha channel to images without alpha channel."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcanvascolor","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCanvasColor","title":"SBSDKCanvasColor","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCanvasColor","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBufferLoadMode":{"type":"topic","abstract":[{"text":"Image Ref Buffer Load Mode.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferLoadMode","title":"SBSDKBufferLoadMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKBufferLoadMode"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbufferloadmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBufferLoadMode"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKColorConversion","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKColorConversion\/title"},{"value":[{"kind":"identifier","text":"SBSDKColorConversion"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKColorConversion\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKColorConversion"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKColorConversion\/navigatorTitle"},{"value":"SBSDKBufferImageLoadOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferImageLoadOptions\/title"},{"value":[{"text":"SBSDKBufferImageLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferImageLoadOptions\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBufferImageLoadOptions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferImageLoadOptions\/navigatorTitle"},{"value":"SBSDKCanvasColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCanvasColor\/title"},{"value":[{"text":"SBSDKCanvasColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCanvasColor\/fragments"},{"value":[{"text":"SBSDKCanvasColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCanvasColor\/navigatorTitle"},{"value":"SBSDKBufferLoadMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferLoadMode\/title"},{"value":[{"text":"SBSDKBufferLoadMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferLoadMode\/fragments"},{"value":[{"text":"SBSDKBufferLoadMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferLoadMode\/navigatorTitle"}]}]}