{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/landscape","interfaceLanguage":"swift"},"abstract":[{"text":"Lock the orientation to landscape.","type":"text"}],"metadata":{"symbolKind":"case","roleHeading":"Case","title":"SBSDKUI2OrientationLockMode.landscape","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2OrientationLockMode@SBSDKUI2OrientationLockModeLandscape","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2OrientationLockModeLandscape"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode\/landscape"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode\/landscape"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"landscape","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2OrientationLockMode/landscape":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode\/landscape","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2OrientationLockModeLandscape"}],"title":"SBSDKUI2OrientationLockMode.landscape","kind":"symbol","role":"symbol","abstract":[{"text":"Lock the orientation to landscape.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode\/landscape"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2OrientationLockMode":{"title":"SBSDKUI2OrientationLockMode","navigatorTitle":[{"text":"SBSDKUI2OrientationLockMode","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2OrientationLockMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode","type":"topic","abstract":[{"text":"Configure the orientation of the interface.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKUI2OrientationLockModeLandscape","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKUI2OrientationLockModeLandscape","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKUI2OrientationLockModeLandscape","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUI2OrientationLockModeLandscape","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode~1landscape\/title","op":"replace"},{"value":[{"text":"SBSDKUI2OrientationLockModeLandscape","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode~1landscape\/fragments","op":"replace"},{"value":"SBSDKUI2OrientationLockMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2OrientationLockMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode\/navigatorTitle","op":"replace"}]}]}