{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfile\/hash","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfile"]]},"metadata":{"roleHeading":"Instance Property","title":"hash","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"hash","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefProfile(py)hash","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagerefprofile\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfile":{"type":"topic","navigatorTitle":[{"text":"SBSDKImageRefProfile","kind":"identifier"}],"title":"SBSDKImageRefProfile","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfile","url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofile","abstract":[{"text":"ImageRef profile which provides detailed information about stored object.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRefProfile","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfile/hash":{"kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofile\/hash","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfile\/hash","role":"symbol","title":"hash"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKImageRefProfile","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfile\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRefProfile"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfile\/fragments"},{"op":"replace","value":[{"text":"SBSDKImageRefProfile","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfile\/navigatorTitle"}]}]}