{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar\/initWithBottomBarMode:importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","interfaceLanguage":"occ"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithBottomBarMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BottomBarMode","text":"SBSDKUI2BottomBarMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BottomBarMode"},{"text":") ","kind":"text"},{"text":"bottomBarMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"importButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"importButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"autoSnappingModeButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"autoSnappingModeButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"manualSnappingModeButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"manualSnappingModeButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"shutterButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ShutterButton","text":"SBSDKUI2ShutterButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ShutterButton"},{"text":" *) ","kind":"text"},{"text":"shutterButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"torchOnButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"torchOnButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"torchOffButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"torchOffButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"previewButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton","text":"SBSDKUI2PreviewButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PreviewButton"},{"text":" *) ","kind":"text"},{"text":"previewButton","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerabottombar\/initwithbottombarmode:importbutton:autosnappingmodebutton:manualsnappingmodebutton:shutterbutton:torchonbutton:torchoffbutton:previewbutton:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithBottomBarMode:importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","kind":"identifier"}],"title":"initWithBottomBarMode:importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraBottomBar(im)initWithBottomBarMode:importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","symbolKind":"method","navigatorTitle":[{"text":"initWithBottomBarMode:importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PreviewButton":{"abstract":[{"type":"text","text":"Configuration of the ‘preview’ button."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton","url":"\/documentation\/scanbotsdk\/sbsdkui2previewbutton","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PreviewButton","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2PreviewButton","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"SBSDKUI2PreviewButton","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BottomBarMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BottomBarMode","type":"topic","title":"SBSDKUI2BottomBarMode","role":"symbol","abstract":[{"text":"The visual mode used for the bottom bar.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2BottomBarMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2bottombarmode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BottomBarMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraBottomBar":{"url":"\/documentation\/scanbotsdk\/sbsdkui2camerabottombar","abstract":[{"type":"text","text":"Configuration of the bottom bar for the camera screen."}],"title":"SBSDKUI2CameraBottomBar","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraBottomBar/initWithBottomBarMode:importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:":{"title":"initWithBottomBarMode:importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerabottombar\/initwithbottombarmode:importbutton:autosnappingmodebutton:manualsnappingmodebutton:shutterbutton:torchonbutton:torchoffbutton:previewbutton:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar\/initWithBottomBarMode:importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithBottomBarMode:importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithBottomBarMode:importButton:autoSnappingModeButton:manualSnappingModeButton:shutterButton:torchOnButton:torchOffButton:previewButton:","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarButtonConfiguration":{"abstract":[{"text":"Configuration of the button located on a bar.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2barbuttonconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"title":"SBSDKUI2BarButtonConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ShutterButton":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2ShutterButton","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2shutterbutton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ShutterButton","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ShutterButton","kind":"identifier"}],"title":"SBSDKUI2ShutterButton","abstract":[{"text":"Configuration of the ‘shutter’ button.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton\/title","op":"replace","value":"SBSDKUI2PreviewButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2PreviewButton"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2PreviewButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BottomBarMode\/title","op":"replace","value":"SBSDKUI2BottomBarMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BottomBarMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BottomBarMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BottomBarMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BottomBarMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar\/title","op":"replace","value":"SBSDKUI2CameraBottomBar"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar\/fragments","op":"replace","value":[{"text":"SBSDKUI2CameraBottomBar","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/title","op":"replace","value":"SBSDKUI2BarButtonConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ShutterButton\/title","op":"replace","value":"SBSDKUI2ShutterButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ShutterButton\/fragments","op":"replace","value":[{"text":"SBSDKUI2ShutterButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ShutterButton\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2ShutterButton","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}