{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResultWordBox\/boundingRect"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerresultwordbox\/boundingrect"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerresultwordbox\/boundingrect"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResultWordBox"]]},"abstract":[{"text":"The recognized words bounding rect.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"boundingRect"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"title":"boundingRect","role":"symbol","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"boundingRect","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResultWordBox(py)boundingRect","navigatorTitle":[{"text":"boundingRect","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerResultWordBox":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerResultWordBox"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerResultWordBox"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResultWordBox","title":"SBSDKGenericTextLineRecognizerResultWordBox","abstract":[{"type":"text","text":"A class describing a recognized word, its bounding box and its text recognition confidence."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerresultwordbox"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerResultWordBox/boundingRect":{"title":"boundingRect","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"boundingRect","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResultWordBox\/boundingRect","abstract":[{"type":"text","text":"The recognized words bounding rect."}],"navigatorTitle":[{"kind":"identifier","text":"boundingRect"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerresultwordbox\/boundingrect"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"boundingRect"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"boundingRect","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"boundingRect","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKGenericTextLineRecognizerResultWordBox","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerResultWordBox\/title"},{"value":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerResultWordBox"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerResultWordBox\/fragments"},{"op":"replace","value":[{"text":"SBSDKGenericTextLineRecognizerResultWordBox","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerResultWordBox\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerResultWordBox~1boundingRect\/title","value":"boundingRect","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerResultWordBox~1boundingRect\/fragments","value":[{"kind":"identifier","text":"boundingRect"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}