{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpathloadmode\/eager"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpathloadmode\/eager"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode\/eager"},"kind":"symbol","abstract":[{"type":"text","text":"Image is immediately loaded into memory."}],"metadata":{"navigatorTitle":[{"text":"SBSDKPathLoadModeEager","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"eager","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKPathLoadMode@SBSDKPathLoadModeEager","title":"SBSDKPathLoadMode.eager"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eager","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPathLoadMode":{"title":"SBSDKPathLoadMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKPathLoadMode","kind":"identifier"}],"type":"topic","abstract":[{"text":"Image Ref Path Load Mode.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpathloadmode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPathLoadMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPathLoadMode/eager":{"url":"\/documentation\/scanbotsdk\/sbsdkpathloadmode\/eager","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"eager","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Image is immediately loaded into memory."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKPathLoadModeEager","kind":"identifier"}],"title":"SBSDKPathLoadMode.eager","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode\/eager"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKPathLoadModeEager"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKPathLoadModeEager"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKPathLoadModeEager","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"SBSDKPathLoadMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathLoadMode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathLoadMode\/fragments","op":"replace","value":[{"text":"SBSDKPathLoadMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathLoadMode\/navigatorTitle","value":[{"text":"SBSDKPathLoadMode","kind":"identifier"}]},{"value":"SBSDKPathLoadModeEager","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathLoadMode~1eager\/title"},{"value":[{"kind":"identifier","text":"SBSDKPathLoadModeEager"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathLoadMode~1eager\/fragments"}]}]}