{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewControllerDelegate\/licensePlateScanner(_:didRecognizeLicensePlate:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Informs the delegate that a license plate has been recognized."}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewControllerDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"licensePlateScanner"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"controller","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUILicensePlateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didRecognizeLicensePlate"},{"text":" ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKLicensePlateScannerResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"text":"The license plate scanner view controller instance.","type":"text"}]}]},{"name":"result","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the license plate scan."}]}]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontrollerdelegate\/licenseplatescanner(_:didrecognizelicenseplate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontrollerdelegate\/licenseplatescanner(_:didrecognizelicenseplate:)"]}],"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"licensePlateScanner"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUILicensePlateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didRecognizeLicensePlate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult","kind":"typeIdentifier","text":"SBSDKLicensePlateScannerResult"},{"kind":"text","text":")"}],"role":"symbol","title":"licensePlateScanner(_:didRecognizeLicensePlate:)","navigatorTitle":[{"text":"licensePlateScanner:didRecognizeLicensePlate:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"required":true,"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUILicensePlateScannerViewControllerDelegate(im)licensePlateScanner:didRecognizeLicensePlate:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController":{"kind":"symbol","abstract":[{"text":"A highly customizable camera-based view controller to scan vehicle license plates in realtime.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller","title":"SBSDKUILicensePlateScannerViewController","navigatorTitle":[{"text":"SBSDKUILicensePlateScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewControllerDelegate/licensePlateScanner(_:didRecognizeLicensePlate:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"licensePlateScanner","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerViewController","text":"SBSDKUILicensePlateScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didRecognizeLicensePlate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult","text":"SBSDKLicensePlateScannerResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontrollerdelegate\/licenseplatescanner(_:didrecognizelicenseplate:)","title":"licensePlateScanner(_:didRecognizeLicensePlate:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewControllerDelegate\/licensePlateScanner(_:didRecognizeLicensePlate:)","navigatorTitle":[{"kind":"identifier","text":"licensePlateScanner:didRecognizeLicensePlate:"}],"abstract":[{"text":"Informs the delegate that a license plate has been recognized.","type":"text"}],"required":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewControllerDelegate":{"abstract":[{"text":"Delegate protocol for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController"},{"text":".","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontrollerdelegate","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewControllerDelegate"}],"title":"SBSDKUILicensePlateScannerViewControllerDelegate","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewControllerDelegate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerResult":{"title":"SBSDKLicensePlateScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerresult","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLicensePlateScannerResult"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicensePlateScannerResult"}],"type":"topic","abstract":[{"type":"text","text":"A class describing the result of a license plate scan."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"licensePlateScanner:didRecognizeLicensePlate:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"licensePlateScanner:didRecognizeLicensePlate:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"licensePlateScanner:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerViewController","kind":"typeIdentifier","text":"SBSDKUILicensePlateScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRecognizeLicensePlate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKLicensePlateScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"result"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/title","value":"SBSDKUILicensePlateScannerViewController","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/fragments"},{"value":"licensePlateScanner:didRecognizeLicensePlate:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewControllerDelegate~1licensePlateScanner(_:didRecognizeLicensePlate:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewControllerDelegate~1licensePlateScanner(_:didRecognizeLicensePlate:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"licensePlateScanner:didRecognizeLicensePlate:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewControllerDelegate\/title","op":"replace","value":"SBSDKUILicensePlateScannerViewControllerDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewControllerDelegate\/fragments","value":[{"text":"SBSDKUILicensePlateScannerViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"value":"SBSDKLicensePlateScannerResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult\/fragments","op":"replace","value":[{"text":"SBSDKLicensePlateScannerResult","kind":"identifier"}]}]}]}