{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"licenseInfo"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"licenseInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKLicenseInfo","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLicenseInfo"}],"symbolKind":"property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Type Property","role":"symbol","title":"licenseInfo","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)Scanbot(cpy)licenseInfo"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"licenseInfo"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseInfo","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLicenseInfo","kind":"typeIdentifier","text":"SBSDKLicenseInfo"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Returns information about the currently set license."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbot\/licenseinfo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbot\/licenseinfo"]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot\/licenseInfo","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseInfo":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseInfo"}],"abstract":[{"text":"Information about the SDK license.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseInfo","title":"SBSDKLicenseInfo","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicenseinfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseInfo"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 8.0.4","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/Scanbot/licenseInfo":{"abstract":[{"text":"Returns information about the currently set license.","type":"text"}],"type":"topic","title":"licenseInfo","navigatorTitle":[{"text":"licenseInfo","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot\/licenseInfo","url":"\/documentation\/scanbotdocumentscannersdk\/scanbot\/licenseinfo","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licenseInfo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKLicenseInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLicenseInfo"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/Scanbot":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot","url":"\/documentation\/scanbotdocumentscannersdk\/scanbot","role":"symbol","abstract":[{"text":"Main class of Scanbot SDK. Lets you install the license and allows basic configuration.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Scanbot"}],"navigatorTitle":[{"kind":"identifier","text":"Scanbot"}],"title":"Scanbot"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"licenseInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"licenseInfo"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKLicenseInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLicenseInfo","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseInfo"},{"text":" * ","kind":"text"},{"text":"licenseInfo","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseInfo\/title","value":"SBSDKLicenseInfo"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseInfo\/fragments","value":[{"text":"SBSDKLicenseInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseInfo\/navigatorTitle","value":[{"text":"SBSDKLicenseInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot~1licenseInfo\/title","value":"licenseInfo"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot~1licenseInfo\/fragments","value":[{"text":"licenseInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot\/title","value":"Scanbot"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot\/fragments","value":[{"kind":"identifier","text":"Scanbot"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot\/navigatorTitle","value":[{"text":"Scanbot","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}