{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/enablecamerauiconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/enableCameraUIConfiguration","interfaceLanguage":"occ"},"sections":[],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerViewController(py)enableCameraUIConfiguration","symbolKind":"property","title":"enableCameraUIConfiguration","roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"enableCameraUIConfiguration"}],"navigatorTitle":[{"text":"enableCameraUIConfiguration","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIEnableCameraUIConfiguration"},{"text":" * ","kind":"text"},{"text":"enableCameraUIConfiguration","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/enableCameraUIConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/enableCameraUIConfiguration","fragments":[{"kind":"identifier","text":"enableCameraUIConfiguration"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/enablecamerauiconfiguration","kind":"symbol","type":"topic","role":"symbol","title":"enableCameraUIConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewController"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller","title":"SBSDKUIMedicalCertificateScannerViewController","abstract":[{"text":"A Ready-To-Use viewController to scan medical certificates.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIEnableCameraUIConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraUIConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuienablecamerauiconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIEnableCameraUIConfiguration"}],"kind":"symbol","title":"SBSDKUIEnableCameraUIConfiguration","abstract":[{"type":"text","text":"Configuration for the user interface of camera based view controllers."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUIMedicalCertificateScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/title","op":"replace"},{"value":[{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraUIConfiguration\/title","value":"SBSDKUIEnableCameraUIConfiguration","op":"replace"},{"value":[{"text":"SBSDKUIEnableCameraUIConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraUIConfiguration\/fragments"}]}]}