{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/SBSDKMedicalCertificateScannerViewControllerDelegate-Implementations"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/medicalCertificateScannerViewController(_:didRecognizeMedicalCertificate:)","interfaceLanguage":"swift"},"abstract":[{"text":"Informs the delegate, that the medical certificate scanner has successfully detected and recognized a medical certificate.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"medicalCertificateScannerViewController"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController","kind":"typeIdentifier","text":"SBSDKMedicalCertificateScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController"},{"text":", ","kind":"text"},{"text":"didRecognizeMedicalCertificate","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerResult","text":"SBSDKMedicalCertificateRecognizerResult"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The medical scanner view controller which recognized the medical certificate.","type":"text"}]}],"name":"controller"},{"name":"result","content":[{"type":"paragraph","inlineContent":[{"text":"The medical scanner result that have been recognized.","type":"text"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/medicalcertificatescannerviewcontroller(_:didrecognizemedicalcertificate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/medicalcertificatescannerviewcontroller(_:didrecognizemedicalcertificate:)"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"medicalCertificateScannerViewController:didRecognizeMedicalCertificate:"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerViewController(im)medicalCertificateScannerViewController:didRecognizeMedicalCertificate:","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"medicalCertificateScannerViewController"},{"kind":"text","text":"("},{"text":"SBSDKMedicalCertificateScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController"},{"kind":"text","text":", "},{"text":"didRecognizeMedicalCertificate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKMedicalCertificateRecognizerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerResult"},{"kind":"text","text":")"}],"title":"medicalCertificateScannerViewController(_:didRecognizeMedicalCertificate:)","extendedModule":"ScanbotSDK","role":"symbol"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/SBSDKMedicalCertificateScannerViewControllerDelegate-Implementations":{"title":"SBSDKMedicalCertificateScannerViewControllerDelegate Implementations","role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/SBSDKMedicalCertificateScannerViewControllerDelegate-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/sbsdkmedicalcertificatescannerviewcontrollerdelegate-implementations","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController":{"kind":"symbol","title":"SBSDKUIMedicalCertificateScannerViewController","type":"topic","navigatorTitle":[{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A Ready-To-Use viewController to scan medical certificates."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController","abstract":[{"type":"text","text":"The classic UI view controller that can be used to detect and recognize medical certificates. Can be configured to recognize on video frames or,"},{"type":"text","text":" "},{"type":"text","text":"for better accuracy, on high-res photos that are automatically captured."}],"title":"SBSDKMedicalCertificateScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/medicalCertificateScannerViewController(_:didRecognizeMedicalCertificate:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/medicalCertificateScannerViewController(_:didRecognizeMedicalCertificate:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Informs the delegate, that the medical certificate scanner has successfully detected and recognized a medical certificate."}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/medicalcertificatescannerviewcontroller(_:didrecognizemedicalcertificate:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"medicalCertificateScannerViewController"},{"kind":"text","text":"("},{"text":"SBSDKMedicalCertificateScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRecognizeMedicalCertificate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerResult","text":"SBSDKMedicalCertificateRecognizerResult"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"medicalCertificateScannerViewController:didRecognizeMedicalCertificate:","kind":"identifier"}],"title":"medicalCertificateScannerViewController(_:didRecognizeMedicalCertificate:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResult":{"title":"SBSDKMedicalCertificateRecognizerResult","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerResult","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerResult","kind":"identifier"}],"abstract":[{"type":"text","text":"This class describes the results of a medical certificate recognition."}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresult","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"medicalCertificateScannerViewController:didRecognizeMedicalCertificate:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"medicalCertificateScannerViewController:didRecognizeMedicalCertificate:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"medicalCertificateScannerViewController:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKMedicalCertificateScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"text":" ","kind":"text"},{"text":"didRecognizeMedicalCertificate:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerResult","kind":"typeIdentifier","text":"SBSDKMedicalCertificateRecognizerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResult"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/title","op":"replace","value":"SBSDKUIMedicalCertificateScannerViewController"},{"value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/title","value":"SBSDKMedicalCertificateScannerViewController","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/fragments"},{"op":"replace","value":"medicalCertificateScannerViewController:didRecognizeMedicalCertificate:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController~1medicalCertificateScannerViewController(_:didRecognizeMedicalCertificate:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"medicalCertificateScannerViewController:didRecognizeMedicalCertificate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController~1medicalCertificateScannerViewController(_:didRecognizeMedicalCertificate:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResult\/title","value":"SBSDKMedicalCertificateRecognizerResult"},{"value":[{"text":"SBSDKMedicalCertificateRecognizerResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResult\/fragments"}]}]}