{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"text":"(presentOn:configuration:delegate:) ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"presenter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerConfiguration","text":"SBSDKUIMedicalCertificateScannerConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIMedicalCertificateScannerViewControllerDelegate","text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewControllerDelegate","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","text":"SBSDKUIMedicalCertificateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerViewController"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller the new instance that should be presented on."}]}],"name":"presenter"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration to define the look and feel of the new detection view controller."}]}],"name":"configuration"},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate of the new detection view controller.","type":"text"}]}]}]},{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"A new instance of ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","isActive":true},{"type":"text","text":"."}]}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/present(on:configuration:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/present(on:configuration:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController"]]},"metadata":{"role":"symbol","symbolKind":"method","title":"present(on:configuration:delegate:)","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerViewController(cm)presentOn:configuration:delegate:","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"SBSDKUIMedicalCertificateScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIMedicalCertificateScannerViewControllerDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SBSDKUIMedicalCertificateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"presentOn:configuration:delegate:"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/present(on:configuration:delegate:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","isActive":true},{"text":" and presents it modally.","type":"text"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIMedicalCertificateScannerConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerconfiguration","title":"SBSDKUIMedicalCertificateScannerConfiguration","abstract":[{"type":"text","text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI medical certificate scanner."}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/present(on:configuration:delegate:)":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/present(on:configuration:delegate:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/present(on:configuration:delegate:)","title":"present(on:configuration:delegate:)","abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","isActive":true},{"type":"text","text":" and presents it modally."}],"type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUIMedicalCertificateScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerConfiguration"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUIMedicalCertificateScannerViewControllerDelegate"},{"text":"?) -> ","kind":"text"},{"text":"SBSDKUIMedicalCertificateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerViewController","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"presentOn:configuration:delegate:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewControllerDelegate":{"title":"SBSDKUIMedicalCertificateScannerViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontrollerdelegate","abstract":[{"type":"text","text":"The delegation protocol for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewControllerDelegate","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController":{"title":"SBSDKUIMedicalCertificateScannerViewController","navigatorTitle":[{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","abstract":[{"type":"text","text":"A Ready-To-Use viewController to scan medical certificates."}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"presentOn:configuration:delegate:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"presentOn:configuration:delegate:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUIMedicalCertificateScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerViewController"},{"text":" *) ","kind":"text"},{"text":"presentOn:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"presenter"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerConfiguration","text":"SBSDKUIMedicalCertificateScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":" "},{"text":"delegate:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKUIMedicalCertificateScannerViewControllerDelegate","text":"id<SBSDKUIMedicalCertificateScannerViewControllerDelegate>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerConfiguration\/title","value":"SBSDKUIMedicalCertificateScannerConfiguration","op":"replace"},{"value":[{"text":"SBSDKUIMedicalCertificateScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController~1present(on:configuration:delegate:)\/title","value":"presentOn:configuration:delegate:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController~1present(on:configuration:delegate:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"presentOn:configuration:delegate:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewControllerDelegate\/title","value":"SBSDKUIMedicalCertificateScannerViewControllerDelegate","op":"replace"},{"value":[{"text":"SBSDKUIMedicalCertificateScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewControllerDelegate\/fragments"},{"value":"SBSDKUIMedicalCertificateScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}