{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/SBSDKMedicalCertificateScannerViewControllerDelegate-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/sbsdkmedicalcertificatescannerviewcontrollerdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/sbsdkmedicalcertificatescannerviewcontrollerdelegate-implementations"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController"]]},"kind":"article","metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"collectionGroup","title":"SBSDKMedicalCertificateScannerViewControllerDelegate Implementations","roleHeading":"API Collection"},"sections":[],"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/medicalCertificateScannerViewController(_:didChangeState:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/medicalCertificateScannerViewController(_:didRecognizeMedicalCertificate:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/medicalCertificateScannerViewController(_:didRecognizeMedicalCertificate:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/medicalCertificateScannerViewController(_:didRecognizeMedicalCertificate:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Informs the delegate, that the medical certificate scanner has successfully detected and recognized a medical certificate."}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/medicalcertificatescannerviewcontroller(_:didrecognizemedicalcertificate:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"medicalCertificateScannerViewController"},{"kind":"text","text":"("},{"text":"SBSDKMedicalCertificateScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRecognizeMedicalCertificate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerResult","text":"SBSDKMedicalCertificateRecognizerResult"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"medicalCertificateScannerViewController:didRecognizeMedicalCertificate:","kind":"identifier"}],"title":"medicalCertificateScannerViewController(_:didRecognizeMedicalCertificate:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/medicalCertificateScannerViewController(_:didChangeState:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/medicalCertificateScannerViewController(_:didChangeState:)","type":"topic","kind":"symbol","abstract":[{"text":"Informs the delegate, that the medical certificate scanner has changed its detection\/recognition state.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/medicalcertificatescannerviewcontroller(_:didchangestate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"medicalCertificateScannerViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKMedicalCertificateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didChangeState"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateScannerState","text":"SBSDKMedicalCertificateScannerState","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"medicalCertificateScannerViewController:didChangeState:","kind":"identifier"}],"title":"medicalCertificateScannerViewController(_:didChangeState:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController":{"kind":"symbol","title":"SBSDKUIMedicalCertificateScannerViewController","type":"topic","navigatorTitle":[{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A Ready-To-Use viewController to scan medical certificates."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/medicalCertificateScannerViewController(_:didChangeState:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/medicalCertificateScannerViewController(_:didRecognizeMedicalCertificate:)"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":"medicalCertificateScannerViewController:didRecognizeMedicalCertificate:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController~1medicalCertificateScannerViewController(_:didRecognizeMedicalCertificate:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController~1medicalCertificateScannerViewController(_:didRecognizeMedicalCertificate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"medicalCertificateScannerViewController:didRecognizeMedicalCertificate:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController~1medicalCertificateScannerViewController(_:didChangeState:)\/title","value":"medicalCertificateScannerViewController:didChangeState:"},{"value":[{"kind":"text","text":"- "},{"text":"medicalCertificateScannerViewController:didChangeState:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController~1medicalCertificateScannerViewController(_:didChangeState:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/title","value":"SBSDKUIMedicalCertificateScannerViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}