{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/viewDidLoad","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"viewDidLoad","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerViewController(im)viewDidLoad","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":";"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/viewdidload"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController/viewDidLoad":{"abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController\/viewDidLoad","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller\/viewdidload","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"kind":"symbol","title":"viewDidLoad"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerViewController","title":"SBSDKUIMedicalCertificateScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerviewcontroller","abstract":[{"text":"A Ready-To-Use viewController to scan medical certificates.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerViewController"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/title","value":"SBSDKUIMedicalCertificateScannerViewController"},{"op":"replace","value":[{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/fragments"},{"value":[{"text":"SBSDKUIMedicalCertificateScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}