{"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"bottomBar"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingScreenConfiguration(py)bottomBar","role":"symbol","title":"bottomBar","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bottomBar","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2CroppingBottomBar","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingBottomBar"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/bottomBar"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration"]]},"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the bottom bar for the cropping screen."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bottomBar","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CroppingBottomBar","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingBottomBar","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingBottomBar","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration\/bottombar"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration\/bottombar"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration/bottomBar":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bottomBar","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CroppingBottomBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingBottomBar"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration\/bottomBar","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration\/bottombar","kind":"symbol","title":"bottomBar","role":"symbol","abstract":[{"text":"Configuration of the bottom bar for the cropping screen.","type":"text"}],"navigatorTitle":[{"text":"bottomBar","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}],"title":"SBSDKUI2CroppingScreenConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingScreenConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Configuration of the screen for cropping the scanned pages.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingBottomBar":{"title":"SBSDKUI2CroppingBottomBar","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingBottomBar","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingBottomBar"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingbottombar","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingBottomBar","abstract":[{"text":"Configuration of the bottom bar for the cropping screen.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"bottomBar"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"bottomBar","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKUI2CroppingBottomBar","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingBottomBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingBottomBar"},{"kind":"text","text":" * "},{"text":"bottomBar","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"bottomBar","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1bottomBar\/title"},{"op":"replace","value":[{"kind":"identifier","text":"bottomBar"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration~1bottomBar\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration\/title","value":"SBSDKUI2CroppingScreenConfiguration","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingBottomBar\/title","value":"SBSDKUI2CroppingBottomBar","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingBottomBar\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CroppingBottomBar"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingBottomBar\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CroppingBottomBar"}]}]}]}