{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewController"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"editingViewController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKImageEditingViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController"},{"text":", ","kind":"text"},{"text":"didDetectPolygon","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"polygon"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"editingViewController","content":[{"type":"paragraph","inlineContent":[{"text":"The calling ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController"},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"text":"The detected instance of the ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"name":"polygon"}],"kind":"parameters"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/SBSDKImageEditingViewControllerDelegate-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/imageEditingViewController(_:didDetectPolygon:)"},"abstract":[{"type":"text","text":"Informs the delegate that the image editing view controller detected a polygon."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller\/imageeditingviewcontroller(_:diddetectpolygon:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller\/imageeditingviewcontroller(_:diddetectpolygon:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didDetectPolygon","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"kind":"text","text":")"}],"modules":[{"name":"ScanbotSDK"}],"title":"imageEditingViewController(_:didDetectPolygon:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewController:didDetectPolygon:"}],"role":"symbol","symbolKind":"method","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUI2CroppingViewController(im)imageEditingViewController:didDetectPolygon:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"type":"topic","abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show and edit an image."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller","role":"symbol","title":"SBSDKImageEditingViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingViewController":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController","abstract":[{"type":"text","text":"A highly customizable view controller to edit the page polygon or the page orientation."}],"role":"symbol","title":"SBSDKUI2CroppingViewController","navigatorTitle":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingViewController/SBSDKImageEditingViewControllerDelegate-Implementations":{"abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/SBSDKImageEditingViewControllerDelegate-Implementations","title":"SBSDKImageEditingViewControllerDelegate Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller\/sbsdkimageeditingviewcontrollerdelegate-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"title":"SBSDKPolygon","abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKPolygon","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon","navigatorTitle":[{"text":"SBSDKPolygon","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingViewController/imageEditingViewController(_:didDetectPolygon:)":{"type":"topic","role":"symbol","abstract":[{"text":"Informs the delegate that the image editing view controller detected a polygon.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"imageEditingViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didDetectPolygon","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"kind":"text","text":")"}],"title":"imageEditingViewController(_:didDetectPolygon:)","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller\/imageeditingviewcontroller(_:diddetectpolygon:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/imageEditingViewController(_:didDetectPolygon:)","kind":"symbol","navigatorTitle":[{"text":"imageEditingViewController:didDetectPolygon:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"imageEditingViewController:didDetectPolygon:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"imageEditingViewController:didDetectPolygon:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"imageEditingViewController:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController"},{"kind":"text","text":" *) "},{"text":"editingViewController","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didDetectPolygon:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"text":" *) ","kind":"text"},{"text":"polygon","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/title","value":"SBSDKImageEditingViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKImageEditingViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController\/title","op":"replace","value":"SBSDKUI2CroppingViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CroppingViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title","value":"SBSDKPolygon","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments","value":[{"text":"SBSDKPolygon","kind":"identifier"}]},{"value":"imageEditingViewController:didDetectPolygon:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController~1imageEditingViewController(_:didDetectPolygon:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"imageEditingViewController:didDetectPolygon:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController~1imageEditingViewController(_:didDetectPolygon:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}