{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"baggageTagLicensePlateNumbers"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkboardingpassdocumentfieldtype\/baggagetaglicenseplatenumbers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkboardingpassdocumentfieldtype\/baggagetaglicenseplatenumbers"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBoardingPassDocumentFieldType\/baggageTagLicensePlateNumbers","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The baggage tag license plate numbers."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"baggageTagLicensePlateNumbers"}],"title":"SBSDKBoardingPassDocumentFieldType.baggageTagLicensePlateNumbers","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKBoardingPassDocumentFieldType@SBSDKBoardingPassDocumentFieldTypeBaggageTagLicensePlateNumbers","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeBaggageTagLicensePlateNumbers"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBoardingPassDocumentFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBoardingPassDocumentFieldType":{"role":"symbol","title":"SBSDKBoardingPassDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldType"}],"abstract":[{"type":"text","text":"The boarding pass field types."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBoardingPassDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkboardingpassdocumentfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBoardingPassDocumentFieldType/baggageTagLicensePlateNumbers":{"role":"symbol","title":"SBSDKBoardingPassDocumentFieldType.baggageTagLicensePlateNumbers","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"baggageTagLicensePlateNumbers"}],"abstract":[{"type":"text","text":"The baggage tag license plate numbers."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBoardingPassDocumentFieldType\/baggageTagLicensePlateNumbers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeBaggageTagLicensePlateNumbers"}],"url":"\/documentation\/scanbotsdk\/sbsdkboardingpassdocumentfieldtype\/baggagetaglicenseplatenumbers"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBoardingPassDocumentFieldTypeBaggageTagLicensePlateNumbers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeBaggageTagLicensePlateNumbers"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeBaggageTagLicensePlateNumbers"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBoardingPassDocumentFieldType\/title","value":"SBSDKBoardingPassDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBoardingPassDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBoardingPassDocumentFieldType~1baggageTagLicensePlateNumbers\/title","value":"SBSDKBoardingPassDocumentFieldTypeBaggageTagLicensePlateNumbers"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBoardingPassDocumentFieldType~1baggageTagLicensePlateNumbers\/fragments","value":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeBaggageTagLicensePlateNumbers"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}