{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkInSequenceNumber"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkboardingpassdocumentfieldtype\/checkinsequencenumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkboardingpassdocumentfieldtype\/checkinsequencenumber"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBoardingPassDocumentFieldType\/checkInSequenceNumber","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The check-in sequence number."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkInSequenceNumber"}],"title":"SBSDKBoardingPassDocumentFieldType.checkInSequenceNumber","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKBoardingPassDocumentFieldType@SBSDKBoardingPassDocumentFieldTypeCheckInSequenceNumber","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeCheckInSequenceNumber"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBoardingPassDocumentFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBoardingPassDocumentFieldType":{"role":"symbol","title":"SBSDKBoardingPassDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldType"}],"abstract":[{"type":"text","text":"The boarding pass field types."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBoardingPassDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkboardingpassdocumentfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBoardingPassDocumentFieldType/checkInSequenceNumber":{"role":"symbol","title":"SBSDKBoardingPassDocumentFieldType.checkInSequenceNumber","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkInSequenceNumber"}],"abstract":[{"type":"text","text":"The check-in sequence number."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBoardingPassDocumentFieldType\/checkInSequenceNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeCheckInSequenceNumber"}],"url":"\/documentation\/scanbotsdk\/sbsdkboardingpassdocumentfieldtype\/checkinsequencenumber"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBoardingPassDocumentFieldTypeCheckInSequenceNumber"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeCheckInSequenceNumber"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeCheckInSequenceNumber"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBoardingPassDocumentFieldType\/title","value":"SBSDKBoardingPassDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBoardingPassDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBoardingPassDocumentFieldType~1checkInSequenceNumber\/title","value":"SBSDKBoardingPassDocumentFieldTypeCheckInSequenceNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBoardingPassDocumentFieldType~1checkInSequenceNumber\/fragments","value":[{"kind":"identifier","text":"SBSDKBoardingPassDocumentFieldTypeCheckInSequenceNumber"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}