{"metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"fields","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"fields","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardField","text":"SBSDKHealthInsuranceCardField"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"fields"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognitionResult(py)fields","platforms":[],"modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fields"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardField","text":"SBSDKHealthInsuranceCardField"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"An array of extracted card fields.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognitionresult\/fields"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognitionresult\/fields"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognitionResult"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please consider using SBSDKGenericDocumentRecognizer."}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognitionResult\/fields"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognitionResult":{"deprecated":true,"abstract":[{"text":"The result of the health insurance card recognition returned by  the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizer","type":"reference"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognitionresult","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognitionResult"}],"title":"SBSDKHealthInsuranceCardRecognitionResult","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognitionResult","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardRecognitionResult","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognitionResult/fields":{"abstract":[{"type":"text","text":"An array of extracted card fields."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fields","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardField","text":"SBSDKHealthInsuranceCardField"},{"text":"]","kind":"text"}],"title":"fields","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognitionresult\/fields","navigatorTitle":[{"kind":"identifier","text":"fields"}],"deprecated":true,"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognitionResult\/fields"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizer":{"deprecated":true,"abstract":[{"text":"A class to recognize health insurance cards, a.k.a. elektronische Gesundheitskarten (eGK).","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizer","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizer"}],"title":"SBSDKHealthInsuranceCardRecognizer","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizer","navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizer"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardField":{"title":"SBSDKHealthInsuranceCardField","role":"symbol","abstract":[{"text":"Health insurance card field data.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfield","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardField","kind":"symbol","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardField","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKHealthInsuranceCardField","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"fields","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"fields","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKHealthInsuranceCardField *>"},{"text":" * ","kind":"text"},{"text":"fields","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognitionResult\/title","op":"replace","value":"SBSDKHealthInsuranceCardRecognitionResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognitionResult\/fragments","value":[{"text":"SBSDKHealthInsuranceCardRecognitionResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognitionResult~1fields\/title","value":"fields","op":"replace"},{"value":[{"kind":"identifier","text":"fields"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognitionResult~1fields\/fragments","op":"replace"},{"op":"replace","value":"SBSDKHealthInsuranceCardRecognizer","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizer\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizer\/fragments","value":[{"text":"SBSDKHealthInsuranceCardRecognizer","kind":"identifier"}]},{"value":"SBSDKHealthInsuranceCardField","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardField\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardField\/fragments","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardField"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}