{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"platforms":[],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKHealthInsuranceCardDetectionStatus","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKHealthInsuranceCardDetectionStatus","kind":"typeIdentifier"}],"symbolKind":"property","title":"status","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"status"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognitionResult(py)status"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognitionresult\/status"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognitionresult\/status"],"traits":[{"interfaceLanguage":"occ"}]}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Please consider using SBSDKGenericDocumentRecognizer."}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognitionResult"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKHealthInsuranceCardDetectionStatus","kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardDetectionStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardDetectionStatus"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognitionResult\/status"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Detection status."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognitionResult":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognitionResult"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognitionResult","title":"SBSDKHealthInsuranceCardRecognitionResult","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognitionresult","abstract":[{"type":"text","text":"The result of the health insurance card recognition returned by  the "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizer","type":"reference"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKHealthInsuranceCardRecognitionResult","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognitionResult/status":{"kind":"symbol","abstract":[{"type":"text","text":"Detection status."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognitionResult\/status","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKHealthInsuranceCardDetectionStatus","text":"SBSDKHealthInsuranceCardDetectionStatus","kind":"typeIdentifier"}],"deprecated":true,"title":"status","role":"symbol","navigatorTitle":[{"text":"status","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognitionresult\/status"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardDetectionStatus":{"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecarddetectionstatus","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKHealthInsuranceCardDetectionStatus","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardDetectionStatus","kind":"identifier"}],"title":"SBSDKHealthInsuranceCardDetectionStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardDetectionStatus","role":"symbol","abstract":[{"type":"text","text":"The health insurance card detection status."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizer":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizer"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizer","title":"SBSDKHealthInsuranceCardRecognizer","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizer","abstract":[{"type":"text","text":"A class to recognize health insurance cards, a.k.a. elektronische Gesundheitskarten (eGK)."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizer"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"status","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"status","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardDetectionStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKHealthInsuranceCardDetectionStatus","text":"SBSDKHealthInsuranceCardDetectionStatus"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognitionResult\/title","op":"replace","value":"SBSDKHealthInsuranceCardRecognitionResult"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognitionResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognitionResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognitionResult\/navigatorTitle","value":[{"text":"SBSDKHealthInsuranceCardRecognitionResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognitionResult~1status\/title","value":"status"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognitionResult~1status\/fragments","value":[{"kind":"identifier","text":"status"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardDetectionStatus\/title","op":"replace","value":"SBSDKHealthInsuranceCardDetectionStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardDetectionStatus\/fragments","op":"replace","value":[{"text":"SBSDKHealthInsuranceCardDetectionStatus","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardDetectionStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardDetectionStatus\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizer\/title","op":"replace","value":"SBSDKHealthInsuranceCardRecognizer"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizer\/fragments","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizer"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizer\/navigatorTitle","value":[{"text":"SBSDKHealthInsuranceCardRecognizer","kind":"identifier"}]}]}]}