{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/errorNothingFound","interfaceLanguage":"swift"},"metadata":{"title":"SBSDKDocumentDataExtractionStatus.errorNothingFound","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDataExtractionStatus@SBSDKDocumentDataExtractionStatusErrorNothingFound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNothingFound"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusErrorNothingFound"}],"roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus"]]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/errornothingfound"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/errornothingfound"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorNothingFound","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"text":"No document was detected.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus","title":"SBSDKDocumentDataExtractionStatus","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatus"}],"abstract":[{"text":"The status of the extraction process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatus"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus/errorNothingFound":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusErrorNothingFound"}],"title":"SBSDKDocumentDataExtractionStatus.errorNothingFound","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/errorNothingFound","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/errornothingfound","type":"topic","abstract":[{"type":"text","text":"No document was detected."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNothingFound"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKDocumentDataExtractionStatusErrorNothingFound","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKDocumentDataExtractionStatusErrorNothingFound","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKDocumentDataExtractionStatusErrorNothingFound","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKDocumentDataExtractionStatus","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentDataExtractionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/navigatorTitle","op":"replace"},{"value":"SBSDKDocumentDataExtractionStatusErrorNothingFound","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1errorNothingFound\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentDataExtractionStatusErrorNothingFound","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1errorNothingFound\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}