{"abstract":[{"type":"text","text":"Document detection user interface is enabled in the license."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"edgeDetectionUI","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfeature\/edgedetectionui"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfeature\/edgedetectionui"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/edgeDetectionUI"},"metadata":{"symbolKind":"case","title":"SBSDKFeature.edgeDetectionUI","roleHeading":"Case","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKFeature@SBSDKFeatureEdgeDetectionUI","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureEdgeDetectionUI"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"edgeDetectionUI","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/edgeDetectionUI":{"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/edgedetectionui","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"edgeDetectionUI"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/edgeDetectionUI","navigatorTitle":[{"text":"SBSDKFeatureEdgeDetectionUI","kind":"identifier"}],"title":"SBSDKFeature.edgeDetectionUI","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Document detection user interface is enabled in the license."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature":{"title":"SBSDKFeature","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature","abstract":[{"text":"The features that are activated in the ScanbotSDK license.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKFeature","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKFeature"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKFeatureEdgeDetectionUI"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKFeatureEdgeDetectionUI","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKFeatureEdgeDetectionUI","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1edgeDetectionUI\/title","value":"SBSDKFeatureEdgeDetectionUI"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1edgeDetectionUI\/fragments","value":[{"text":"SBSDKFeatureEdgeDetectionUI","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/title","value":"SBSDKFeature"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKFeature"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKFeature"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/navigatorTitle"}]}]}