{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Document detection is enabled in the license.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"edgeDetection","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/edgeDetection"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkfeature\/edgedetection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkfeature\/edgedetection"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"SBSDKFeatureEdgeDetection","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKFeature@SBSDKFeatureEdgeDetection","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"edgeDetection","kind":"identifier"}],"title":"SBSDKFeature.edgeDetection","symbolKind":"case","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature":{"url":"\/documentation\/scanbotsdk\/sbsdkfeature","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature","abstract":[{"type":"text","text":"The features that are activated in the ScanbotSDK license."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKFeature"}],"navigatorTitle":[{"text":"SBSDKFeature","kind":"identifier"}],"role":"symbol","title":"SBSDKFeature","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/edgeDetection":{"abstract":[{"text":"Document detection is enabled in the license.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/edgeDetection","navigatorTitle":[{"text":"SBSDKFeatureEdgeDetection","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfeature\/edgedetection","type":"topic","title":"SBSDKFeature.edgeDetection","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"edgeDetection"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKFeatureEdgeDetection","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKFeatureEdgeDetection","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKFeatureEdgeDetection","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/title","op":"replace","value":"SBSDKFeature"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/fragments","value":[{"kind":"identifier","text":"SBSDKFeature"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFeature"}],"op":"replace"},{"op":"replace","value":"SBSDKFeatureEdgeDetection","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1edgeDetection\/title"},{"value":[{"kind":"identifier","text":"SBSDKFeatureEdgeDetection"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1edgeDetection\/fragments","op":"replace"}]}]}