{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageProcessing","kind":"identifier"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/imageProcessing","interfaceLanguage":"swift"},"metadata":{"title":"SBSDKFeature.imageProcessing","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKFeature@SBSDKFeatureImageProcessing","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"imageProcessing","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureImageProcessing"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfeature\/imageprocessing"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfeature\/imageprocessing"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Image processing is enabled in the license.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature":{"url":"\/documentation\/scanbotsdk\/sbsdkfeature","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature","abstract":[{"type":"text","text":"The features that are activated in the ScanbotSDK license."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKFeature"}],"navigatorTitle":[{"text":"SBSDKFeature","kind":"identifier"}],"role":"symbol","title":"SBSDKFeature","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/imageProcessing":{"abstract":[{"text":"Image processing is enabled in the license.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureImageProcessing"}],"title":"SBSDKFeature.imageProcessing","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfeature\/imageprocessing","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageProcessing"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/imageProcessing","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKFeatureImageProcessing","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKFeatureImageProcessing","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKFeatureImageProcessing"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKFeature","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKFeature"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKFeature"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1imageProcessing\/title","op":"replace","value":"SBSDKFeatureImageProcessing"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1imageProcessing\/fragments","value":[{"text":"SBSDKFeatureImageProcessing","kind":"identifier"}],"op":"replace"}]}]}