{"metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invoiceDetection","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKFeature@SBSDKFeatureInvoiceDetection","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureInvoiceDetection"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKFeature.invoiceDetection","roleHeading":"Case"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/invoiceDetection","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfeature\/invoicedetection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfeature\/invoicedetection"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Invoice recognition is enabled in the licence. Currently unused."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invoiceDetection","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/invoiceDetection":{"navigatorTitle":[{"text":"SBSDKFeatureInvoiceDetection","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/invoiceDetection","title":"SBSDKFeature.invoiceDetection","abstract":[{"type":"text","text":"Invoice recognition is enabled in the licence. Currently unused."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invoiceDetection","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/invoicedetection","kind":"symbol","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature":{"type":"topic","abstract":[{"text":"The features that are activated in the ScanbotSDK license.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKFeature","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature","url":"\/documentation\/scanbotsdk\/sbsdkfeature","navigatorTitle":[{"text":"SBSDKFeature","kind":"identifier"}],"title":"SBSDKFeature"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKFeatureInvoiceDetection","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKFeatureInvoiceDetection","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKFeatureInvoiceDetection","kind":"identifier"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1invoiceDetection\/title","value":"SBSDKFeatureInvoiceDetection","op":"replace"},{"value":[{"text":"SBSDKFeatureInvoiceDetection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1invoiceDetection\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/title","op":"replace","value":"SBSDKFeature"},{"value":[{"text":"SBSDKFeature","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKFeature"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}