{"metadata":{"roleHeading":"Case","symbolKind":"case","role":"symbol","title":"SBSDKFeature.MRZRecognition","externalID":"c:@M@ScanbotSDK@E@SBSDKFeature@SBSDKFeatureMRZRecognition","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MRZRecognition"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKFeatureMRZRecognition","kind":"identifier"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfeature\/mrzrecognition"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfeature\/mrzrecognition"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MRZRecognition"}],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/MRZRecognition"},"abstract":[{"text":"Machine-readable-zone detection is enabled in the licence.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/MRZRecognition":{"type":"topic","title":"SBSDKFeature.MRZRecognition","abstract":[{"type":"text","text":"Machine-readable-zone detection is enabled in the licence."}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKFeatureMRZRecognition","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkfeature\/mrzrecognition","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MRZRecognition"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/MRZRecognition"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature":{"type":"topic","abstract":[{"text":"The features that are activated in the ScanbotSDK license.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKFeature","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature","url":"\/documentation\/scanbotsdk\/sbsdkfeature","navigatorTitle":[{"text":"SBSDKFeature","kind":"identifier"}],"title":"SBSDKFeature"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKFeatureMRZRecognition","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKFeatureMRZRecognition","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKFeatureMRZRecognition","kind":"identifier"}]}]}},{"value":"SBSDKFeatureMRZRecognition","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1MRZRecognition\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1MRZRecognition\/fragments","value":[{"text":"SBSDKFeatureMRZRecognition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/title","value":"SBSDKFeature","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/fragments","value":[{"text":"SBSDKFeature","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFeature"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}