{"kind":"symbol","metadata":{"title":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:"}],"navigatorTitle":[{"text":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization(im)initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization\/initwithcameratopbarcancelbuttontitle:cameratopbartitle:cameratopguidance:camerauserguidancestart:camerauserguidancenodocumentfound:camerauserguidancebadaspectratio:camerauserguidanceorientationmismatch:camerauserguidancebadangles:camerause-8q6dl"]}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization\/initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithCameraTopBarCancelButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraTopBarCancelButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraTopBarTitle:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraTopBarTitle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraTopGuidance:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraTopGuidance"},{"kind":"text","text":" "},{"text":"cameraUserGuidanceStart:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"cameraUserGuidanceStart","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cameraUserGuidanceNoDocumentFound:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceNoDocumentFound","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraUserGuidanceBadAspectRatio:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"cameraUserGuidanceBadAspectRatio","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceOrientationMismatch:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceOrientationMismatch","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraUserGuidanceBadAngles:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraUserGuidanceBadAngles"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraUserGuidanceTooNoisy:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraUserGuidanceTooNoisy"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraUserGuidanceTextHintOffCenter:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"cameraUserGuidanceTextHintOffCenter","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceTooSmall:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceTooSmall","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceTooDark:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"cameraUserGuidanceTooDark","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraUserGuidanceEnergySaveMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraUserGuidanceEnergySaveMode"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceReadyToCapture:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraUserGuidanceReadyToCapture"},{"kind":"text","text":" "},{"text":"cameraUserGuidanceReadyToCaptureManual:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceReadyToCaptureManual","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraImportButtonTitle:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraImportButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraTorchOnButtonTitle:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraTorchOnButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraTorchOffButtonTitle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraTorchOffButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraAutoSnapButtonTitle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"cameraAutoSnapButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraManualSnapButtonTitle:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraManualSnapButtonTitle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewButtonTitle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"cameraPreviewButtonTitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraIntroDoneButton:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraIntroDoneButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraIntroTitle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"cameraIntroTitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraIntroSubtitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"cameraIntroSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraIntroItem1:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraIntroItem1"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraIntroItem2:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraIntroItem2"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraIntroItem3:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"cameraIntroItem3","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraIntroItem4:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraIntroItem4","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraProgressOverlayTitle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraProgressOverlayTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraCancelAlertTitle:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraCancelAlertTitle"},{"text":" ","kind":"text"},{"text":"cameraCancelAlertSubtitle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"cameraCancelAlertSubtitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraCancelNoButtonTitle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraCancelNoButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraCancelYesButtonTitle:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"cameraCancelYesButtonTitle","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cameraLimitReachedAlertTitle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraLimitReachedAlertTitle"},{"kind":"text","text":" "},{"text":"cameraLimitReachedAlertSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraLimitReachedAlertSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraLimitReachedOkButtonTitle:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraLimitReachedOkButtonTitle"},{"text":" ","kind":"text"},{"text":"acknowledgementScreenBadDocumentHint:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"acknowledgementScreenBadDocumentHint"},{"kind":"text","text":" "},{"text":"acknowledgementRetakeButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"acknowledgementRetakeButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"acknowledgementAcceptButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"acknowledgementAcceptButtonTitle"},{"text":" ","kind":"text"},{"text":"reviewScreenTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reviewScreenTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewTopBarBackButtonTitle:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reviewTopBarBackButtonTitle"},{"text":" ","kind":"text"},{"text":"reviewScreenPageCount:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewScreenPageCount"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewScreenAddButtonTitle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewScreenAddButtonTitle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewScreenRetakeButtonTitle:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"reviewScreenRetakeButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewScreenCropButtonTitle:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewScreenCropButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewScreenRotateButtonTitle:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reviewScreenRotateButtonTitle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewScreenDeleteButtonTitle:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reviewScreenDeleteButtonTitle"},{"text":" ","kind":"text"},{"text":"reviewScreenSubmitButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewScreenSubmitButtonTitle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewScreenDeleteAllButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reviewScreenDeleteAllButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewScreenReorderPagesButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"reviewScreenReorderPagesButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"zoomOverlayCancelButtonText:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zoomOverlayCancelButtonText"},{"kind":"text","text":" "},{"text":"reviewDeletePageAlertTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reviewDeletePageAlertTitle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewDeleteAllPagesAlertTitle:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewDeleteAllPagesAlertTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewDeletePageAlertSubTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewDeletePageAlertSubTitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"reviewDeleteAllPagesAlertSubtitle:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewDeleteAllPagesAlertSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewDeletePageAlertConfirmButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"reviewDeletePageAlertConfirmButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewDeleteAllPagesAlertDeleteButtonTitle:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"reviewDeleteAllPagesAlertDeleteButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewDeletePageAlertDeleteRetakeButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"reviewDeletePageAlertDeleteRetakeButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewDeletePageAlertCancelButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"reviewDeletePageAlertCancelButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reviewDeleteAllPagesAlertCancelButtonTitle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"reviewDeleteAllPagesAlertCancelButtonTitle","kind":"internalParam"},{"kind":"text","text":" "},{"text":"acknowledgementTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"acknowledgementTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"reorderPageTitle:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reorderPageTitle"},{"kind":"text","text":" "},{"text":"reorderPageGuidanceTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"reorderPageGuidanceTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reorderPageText:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reorderPageText","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reorderTopBarConfirmButtonTitle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reorderTopBarConfirmButtonTitle"},{"text":" ","kind":"text"},{"text":"reorderTopBarCancelButtonTitle:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reorderTopBarCancelButtonTitle"},{"text":" ","kind":"text"},{"text":"croppingTopBarConfirmButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"croppingTopBarConfirmButtonTitle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"croppingTopBarCancelButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"croppingTopBarCancelButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingDetectButtonTitle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"croppingDetectButtonTitle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingRotateButtonTitle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"croppingRotateButtonTitle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"croppingResetButtonTitle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"croppingResetButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"croppingScreenTitle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"croppingScreenTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionCameraTopBarIntroButton:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionCameraTopBarIntroButton"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraTopBarCancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionCameraTopBarCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraImportButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionCameraImportButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraTorchOnButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraTorchOnButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionCameraTorchOffButton:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionCameraTorchOffButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionCameraShutterButton:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionCameraShutterButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraAutoSnapButton:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionCameraAutoSnapButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionCameraManualSnapButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraManualSnapButton"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionCameraPreviewButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionCameraPreviewButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraIntroDoneButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionCameraIntroDoneButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionAcknowledgementRetakeButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionAcknowledgementRetakeButton"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionAcknowledgementAcceptButton:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionAcknowledgementAcceptButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingTopBarConfirmButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCroppingTopBarConfirmButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCroppingTopBarCancelButton:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCroppingTopBarCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCroppingDetectButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionCroppingDetectButton"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCroppingRotateButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCroppingRotateButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingResetButton:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionCroppingResetButton"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReorderTopBarConfirmButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReorderTopBarConfirmButton"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReorderTopBarCancelButton:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReorderTopBarCancelButton"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewNextPageButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionReviewNextPageButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionReviewPreviousPageButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewPreviousPageButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionReviewAddButton:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionReviewAddButton"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionReviewRetakeButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewRetakeButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionReviewCropButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewCropButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionReviewRotateButton:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewRotateButton"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionReviewDeleteButton:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionReviewDeleteButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewSubmitButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionReviewSubmitButton"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewMoreButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewMoreButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewDeleteAllButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewDeleteAllButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionReviewReorderPagesButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewReorderPagesButton"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionZoomOverlayCancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionZoomOverlayCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewZoomButton:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionReviewZoomButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewTopBarBackButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewTopBarBackButton"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewDeletePageAlertConfirmButton:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewDeletePageAlertConfirmButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewDeletePageAlertCancelButton:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionReviewDeletePageAlertCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraLimitReachedOkButton:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionCameraLimitReachedOkButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionCameraCancelYesButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraCancelYesButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraCancelNoButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionCameraCancelNoButton"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraTitle:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraPermissionEnableCameraTitle"},{"kind":"text","text":" "},{"text":"cameraPermissionEnableCameraExplanation:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraPermissionEnableCameraExplanation"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraButton:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"cameraPermissionEnableCameraButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermissionCloseButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionCloseButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionCameraPermissionEnableCameraButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraPermissionEnableCameraButton"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionCameraPermissionCloseButton"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerTextLocalization/initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:":{"navigatorTitle":[{"text":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization\/initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","title":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization\/initwithcameratopbarcancelbuttontitle:cameratopbartitle:cameratopguidance:camerauserguidancestart:camerauserguidancenodocumentfound:camerauserguidancebadaspectratio:camerauserguidanceorientationmismatch:camerauserguidancebadangles:camerause-8q6dl","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerTextLocalization":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization","title":"SBSDKUI2DocumentScannerTextLocalization","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization","role":"symbol","abstract":[{"type":"text","text":"Configuration of all the strings for the standalone cropping screen."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/title","value":"SBSDKUI2DocumentScannerTextLocalization","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"op":"replace"}]}]}