{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerintroscreenconfiguration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerIntroScreenConfiguration\/hash","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerIntroScreenConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerIntroScreenConfiguration(py)hash","role":"symbol","fragments":[{"kind":"identifier","text":"hash"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"hash","kind":"identifier"}],"title":"hash"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerIntroScreenConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2CheckScannerIntroScreenConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerintroscreenconfiguration","title":"SBSDKUI2CheckScannerIntroScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerIntroScreenConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CheckScannerIntroScreenConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Configuration of the introduction screen for the check scanner.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerIntroScreenConfiguration/hash":{"url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerintroscreenconfiguration\/hash","kind":"symbol","fragments":[{"text":"hash","kind":"identifier"}],"title":"hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerIntroScreenConfiguration\/hash","abstract":[],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2CheckScannerIntroScreenConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerIntroScreenConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2CheckScannerIntroScreenConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerIntroScreenConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2CheckScannerIntroScreenConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerIntroScreenConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}