{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBaseScannerViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration\/defaultconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration\/defaultconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"This is the default configuration with the properties initialized as mentioned in their description.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/defaultConfiguration","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration(cpy)defaultConfiguration","role":"symbol","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBaseScannerViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"defaultConfiguration","kind":"identifier"}],"title":"defaultConfiguration"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewFinderConfiguration/defaultConfiguration":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultConfiguration"}],"abstract":[{"text":"This is the default configuration with the properties initialized as mentioned in their description.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration\/defaultconfiguration","title":"defaultConfiguration","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration","text":"SBSDKBaseScannerViewFinderConfiguration"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/defaultConfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewFinderConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration","title":"SBSDKBaseScannerViewFinderConfiguration","role":"symbol","abstract":[{"type":"text","text":"The view finder configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"type":"text","text":" "},{"type":"text","text":"Sometimes it is necessary to limit a live video frame detection or recognition to a certain rectangular area with"},{"type":"text","text":" "},{"type":"text","text":"a specific aspect ratio: the region or rectangle of interest. This is where a view finder comes in."},{"type":"text","text":" "},{"type":"text","text":"It crops the video frame to that region of interest before passing it to any scanner. Usually"},{"type":"text","text":" "},{"type":"text","text":"the performance of scanners gain a benefit from it because less pixels must be processed."},{"type":"text","text":" "},{"type":"text","text":"Additionally, to guide the user, the view finder visualizes the region of interest by drawing a rectangle around"},{"type":"text","text":" "},{"type":"text","text":"on the user interface."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"defaultConfiguration","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"defaultConfiguration"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration","text":"SBSDKBaseScannerViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"defaultConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1defaultConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"defaultConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1defaultConfiguration\/fragments"},{"op":"replace","value":"SBSDKBaseScannerViewFinderConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}