{"abstract":[{"text":"Require seeing the same result multiple times to confirm it.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"E.g. if the seen values are “John B. Doe”, “John B.”, “B. Doe”, “John B. Doe” then the confirmation count for"},{"text":" ","type":"text"},{"type":"text","text":"the value “John B. Doe” is 2 and for the rest it’s 1."},{"type":"text","text":" "},{"text":"A field’s value is considered CONFIRMED if its confirmation count is greater or equal to minConfirmations.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod\/exact","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"exact"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod"]]},"metadata":{"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKConfirmationMethod@SBSDKConfirmationMethodExact","title":"SBSDKConfirmationMethod.exact","symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"SBSDKConfirmationMethodExact","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exact","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkconfirmationmethod\/exact"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkconfirmationmethod\/exact"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConfirmationMethod":{"url":"\/documentation\/scanbotsdk\/sbsdkconfirmationmethod","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKConfirmationMethod"}],"abstract":[{"type":"text","text":"Method used to confirm a result."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKConfirmationMethod"}],"type":"topic","title":"SBSDKConfirmationMethod"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConfirmationMethod/exact":{"url":"\/documentation\/scanbotsdk\/sbsdkconfirmationmethod\/exact","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod\/exact","title":"SBSDKConfirmationMethod.exact","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"exact","kind":"identifier"}],"abstract":[{"text":"Require seeing the same result multiple times to confirm it.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"E.g. if the seen values are “John B. Doe”, “John B.”, “B. Doe”, “John B. Doe” then the confirmation count for"},{"type":"text","text":" "},{"type":"text","text":"the value “John B. Doe” is 2 and for the rest it’s 1."},{"text":" ","type":"text"},{"type":"text","text":"A field’s value is considered CONFIRMED if its confirmation count is greater or equal to minConfirmations."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKConfirmationMethodExact"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKConfirmationMethodExact","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"SBSDKConfirmationMethodExact","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKConfirmationMethodExact","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod\/title","value":"SBSDKConfirmationMethod"},{"value":[{"kind":"identifier","text":"SBSDKConfirmationMethod"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKConfirmationMethod"}]},{"value":"SBSDKConfirmationMethodExact","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod~1exact\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKConfirmationMethodExact"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod~1exact\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}