{"abstract":[{"type":"text","text":"The camera to be used."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice","text":"SBSDKCameraDevice","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"inlineContent":[{"text":"Defaults to ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/defaultBackFacingCamera","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicameraconfiguration\/camera"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicameraconfiguration\/camera"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration(py)camera","title":"camera","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice","kind":"typeIdentifier","text":"SBSDKCameraDevice"},{"kind":"text","text":"!"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"camera"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration\/camera","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraConfiguration":{"type":"topic","abstract":[{"text":"Configuration for the camera of all RTU-UI components.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuicameraconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICameraConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICameraConfiguration"}],"role":"symbol","title":"SBSDKUICameraConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraConfiguration/camera":{"type":"topic","title":"camera","url":"\/documentation\/scanbotsdk\/sbsdkuicameraconfiguration\/camera","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"camera","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration\/camera","abstract":[{"text":"The camera to be used.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice","text":"SBSDKCameraDevice","kind":"typeIdentifier"},{"text":"!","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSession"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession","title":"SBSDKCameraSession","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSession"}],"abstract":[{"text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the","type":"text"},{"text":" ","type":"text"},{"text":"camera device and the preview layer. Provides functionality to capture still images.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice":{"title":"SBSDKCameraDevice","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcameradevice","abstract":[{"text":"The camera device to be used with a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraDevice"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDevice"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice/defaultBackFacingCamera":{"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcameradevice\/defaultbackfacingcamera","title":"defaultBackFacingCamera","abstract":[{"type":"text","text":"Returns the default back side camera, which in most cases is the triple or dual camera."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/defaultBackFacingCamera","navigatorTitle":[{"text":"defaultBackFacingCamera","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultBackFacingCamera","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCameraDevice","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"camera","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"camera","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKCameraDevice","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice"},{"text":" * ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUICameraConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUICameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUICameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraConfiguration\/navigatorTitle"},{"value":"camera","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraConfiguration~1camera\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraConfiguration~1camera\/fragments","op":"replace","value":[{"text":"camera","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/title","op":"replace","value":"SBSDKCameraSession"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/fragments","value":[{"text":"SBSDKCameraSession","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/navigatorTitle","value":[{"text":"SBSDKCameraSession","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice\/title","value":"SBSDKCameraDevice"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice\/fragments","value":[{"text":"SBSDKCameraDevice","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCameraDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1defaultBackFacingCamera\/title","value":"defaultBackFacingCamera"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1defaultBackFacingCamera\/fragments","value":[{"kind":"identifier","text":"defaultBackFacingCamera"}]}]}]}