{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayConfiguration"]]},"metadata":{"role":"symbol","navigatorTitle":[{"text":"customView","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customView","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ScanbotSDK27SBSDKTrackedBarcodeInfoViewa","text":"SBSDKTrackedBarcodeInfoView"},{"text":"?","kind":"text"}],"title":"customView","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayConfiguration(py)customView"},"abstract":[{"type":"text","text":"A custom view that can be displayed over the barcode. Must conform to "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTrackedBarcodeInfoView","isActive":true,"type":"reference"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"customView","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTrackedBarcodeInfoView","text":"SBSDKTrackedBarcodeInfoView","preciseIdentifier":"s:10ScanbotSDK27SBSDKTrackedBarcodeInfoViewa","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlayconfiguration\/customview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlayconfiguration\/customview"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayConfiguration\/customView"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayConfiguration/customView":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"customView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKTrackedBarcodeInfoView","preciseIdentifier":"s:10ScanbotSDK27SBSDKTrackedBarcodeInfoViewa"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","abstract":[{"text":"A custom view that can be displayed over the barcode. Must conform to ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTrackedBarcodeInfoView","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlayconfiguration\/customview","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayConfiguration\/customView","navigatorTitle":[{"text":"customView","kind":"identifier"}],"title":"customView","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayConfiguration":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"title":"SBSDKBarcodeTrackingOverlayConfiguration","abstract":[{"text":"A class that represents the configuration options for a ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","isActive":true},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"This overlay is used to visualize the detected barcodes on the screen."},{"type":"text","text":" "},{"text":"The class provides various customization options for the appearance and behavior of the overlay.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlayconfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTrackedBarcodeInfoViewable":{"abstract":[{"text":"A protocol that defines the methods and properties required for a custom tracking view to be displayed over detected barcodes using the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayConfiguration"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"The custom view must conform to this protocol in order to be used as an overlay on top of the detected barcodes.","type":"text"}],"title":"SBSDKTrackedBarcodeInfoViewable","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTrackedBarcodeInfoViewable","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKTrackedBarcodeInfoViewable"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTrackedBarcodeInfoViewable","url":"\/documentation\/scanbotsdk\/sbsdktrackedbarcodeinfoviewable","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayController":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","kind":"symbol","title":"SBSDKBarcodeTrackingOverlayController","type":"topic","abstract":[{"type":"text","text":"A class that represents an overlay used for visualizing detected barcodes."},{"text":" ","type":"text"},{"text":"It provides a customizable user interface for displaying barcodes and supports interaction with them.","type":"text"},{"type":"text","text":" "},{"text":"The overlay can be used to highlight and select barcodes based on user input.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}],"navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTrackedBarcodeInfoView":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SBSDKTrackedBarcodeInfoView","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A "},{"code":"UIView","type":"codeVoice"},{"type":"text","text":" that conforms to the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTrackedBarcodeInfoViewable","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdktrackedbarcodeinfoview","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTrackedBarcodeInfoView","navigatorTitle":[{"kind":"identifier","text":"SBSDKTrackedBarcodeInfoView"}],"title":"SBSDKTrackedBarcodeInfoView","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"customView","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"customView","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)UIView@M@ScanbotSDK@objc(pl)SBSDKTrackedBarcodeInfoViewable","text":"UIView<SBSDKTrackedBarcodeInfoViewable>"},{"text":" * ","kind":"text"},{"text":"customView","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayConfiguration~1customView\/title","value":"customView","op":"replace"},{"value":[{"kind":"identifier","text":"customView"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayConfiguration~1customView\/fragments","op":"replace"},{"op":"replace","value":"SBSDKBarcodeTrackingOverlayConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTrackedBarcodeInfoViewable\/title","value":"SBSDKTrackedBarcodeInfoViewable","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTrackedBarcodeInfoViewable\/fragments","value":[{"text":"SBSDKTrackedBarcodeInfoViewable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/title","value":"SBSDKBarcodeTrackingOverlayController"},{"value":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/fragments"}]}]}