{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode\/badquality"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode\/badquality"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/badQuality","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The acknowledgement screen will only be shown when the quality of a scanned page is unacceptable. The quality"},{"type":"text","text":" "},{"type":"text","text":"threshold is determined by the "},{"code":"minimumQuality","type":"codeVoice"},{"type":"text","text":" parameter."}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementModeBadQuality"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2AcknowledgementMode@SBSDKUI2AcknowledgementModeBadQuality","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badQuality","kind":"identifier"}],"title":"SBSDKUI2AcknowledgementMode.badQuality"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badQuality","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementMode/badQuality":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementModeBadQuality"}],"abstract":[{"text":"The acknowledgement screen will only be shown when the quality of a scanned page is unacceptable. The quality","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"threshold is determined by the "},{"type":"codeVoice","code":"minimumQuality"},{"text":" parameter.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/badQuality","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode\/badquality","type":"topic","title":"SBSDKUI2AcknowledgementMode.badQuality","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"badQuality"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementMode":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AcknowledgementMode"}],"navigatorTitle":[{"text":"SBSDKUI2AcknowledgementMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode","abstract":[{"text":"Determines, after each page is snapped, whether the acknowledgment screen should be displayed or not.","type":"text"}],"kind":"symbol","role":"symbol","title":"SBSDKUI2AcknowledgementMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKUI2AcknowledgementModeBadQuality","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"SBSDKUI2AcknowledgementModeBadQuality","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementModeBadQuality"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUI2AcknowledgementModeBadQuality","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode~1badQuality\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode~1badQuality\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementModeBadQuality"}],"op":"replace"},{"value":"SBSDKUI2AcknowledgementMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode\/fragments","op":"replace","value":[{"text":"SBSDKUI2AcknowledgementMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}