{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscanner\/scan(from:orientation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscanner\/scan(from:orientation:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(scanFromSampleBuffer:orientation:) ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"text":"sampleBuffer","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"orientation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKVideoOrientation","text":"SBSDKVideoOrientation","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectionResult","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionResult"},{"text":"?","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"sampleBuffer","content":[{"inlineContent":[{"type":"text","text":"The sample buffer to scan from."}],"type":"paragraph"}]},{"name":"orientation","content":[{"type":"paragraph","inlineContent":[{"text":"The video orientation of the sample buffer.","type":"text"}]}]}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"The scanning result containing the status and a polygon."}],"type":"paragraph"}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":", "},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKVideoOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKVideoOrientation"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionResult","text":"SBSDKDocumentDetectionResult"},{"text":"?","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"scanFromSampleBuffer:orientation:","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScanner(im)scanFromSampleBuffer:orientation:","role":"symbol","symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"scan(from:orientation:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScanner"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScanner\/scan(from:orientation:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Scans a documents outline from a "},{"type":"codeVoice","code":"CMSampleBuffer"},{"text":".","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoOrientation":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoorientation","title":"SBSDKVideoOrientation","kind":"symbol","navigatorTitle":[{"text":"SBSDKVideoOrientation","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation","abstract":[{"text":"An enum describing the orientation of a video frame.","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoOrientation","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionResult":{"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"abstract":[{"text":"Result of the document contour detection.","type":"text"}],"title":"SBSDKDocumentDetectionResult","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScanner":{"type":"topic","abstract":[{"type":"text","text":"A class to scan a document’s outline on various image sources."}],"title":"SBSDKDocumentScanner","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentScanner"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScanner","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscanner","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentScanner","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScanner/scan(from:orientation:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKVideoOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKVideoOrientation"},{"text":") -> ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionResult"},{"text":"?","kind":"text"}],"kind":"symbol","title":"scan(from:orientation:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscanner\/scan(from:orientation:)","navigatorTitle":[{"text":"scanFromSampleBuffer:orientation:","kind":"identifier"}],"abstract":[{"type":"text","text":"Scans a documents outline from a "},{"type":"codeVoice","code":"CMSampleBuffer"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScanner\/scan(from:orientation:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"scanFromSampleBuffer:orientation:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scanFromSampleBuffer:orientation:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionResult"},{"text":" *) ","kind":"text"},{"text":"scanFromSampleBuffer:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"opaqueCMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@opaqueCMSampleBuffer"},{"kind":"text","text":" *) "},{"text":"sampleBuffer","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"orientation:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKVideoOrientation","kind":"typeIdentifier","text":"SBSDKVideoOrientation","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"orientation"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"sampleBuffer","content":[{"type":"paragraph","inlineContent":[{"text":"The sample buffer to scan from.","type":"text"}]}]},{"name":"orientation","content":[{"inlineContent":[{"type":"text","text":"The video orientation of the sample buffer."}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The scanning result containing the status and a polygon."}],"type":"paragraph"}]},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"SBSDKVideoOrientation","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation\/fragments","value":[{"text":"SBSDKVideoOrientation","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoOrientation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/title","value":"SBSDKDocumentDetectionResult"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/navigatorTitle"},{"value":"SBSDKDocumentScanner","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScanner\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScanner\/fragments","value":[{"text":"SBSDKDocumentScanner","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScanner\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentScanner","kind":"identifier"}]},{"value":"scanFromSampleBuffer:orientation:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScanner~1scan(from:orientation:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScanner~1scan(from:orientation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scanFromSampleBuffer:orientation:"}]}]}]}