{"sections":[],"kind":"symbol","metadata":{"title":"whiteBlackPointFilter()","symbolKind":"method","externalID":"s:10ScanbotSDK21SBSDKParametricFilterC015whiteBlackPointD0AA010SBSDKWhitefgD0CyFZ","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"whiteBlackPointFilter"},{"text":"() -> ","kind":"text"},{"text":"SBSDKWhiteBlackPointFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKWhiteBlackPointFilter"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"whiteBlackPointFilter","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKWhiteBlackPointFilter","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWhiteBlackPointFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKWhiteBlackPointFilter"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkparametricfilter\/whiteblackpointfilter()"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter\/whiteBlackPointFilter()"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter","navigatorTitle":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"type":"topic","role":"symbol","abstract":[{"text":"Base class for all parametric filters.","type":"text"}],"title":"SBSDKParametricFilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKParametricFilter"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter/whiteBlackPointFilter()":{"type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter\/whiteBlackPointFilter()","url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter\/whiteblackpointfilter()","title":"whiteBlackPointFilter()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"whiteBlackPointFilter"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKWhiteBlackPointFilter","kind":"typeIdentifier","text":"SBSDKWhiteBlackPointFilter"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWhiteBlackPointFilter":{"abstract":[{"type":"text","text":"Maps image value channel so that all the pixels darker than the black point are set to 0,"},{"type":"text","text":" "},{"type":"text","text":"all the pixels brighter than the white point are set to 255, and the pixels in between"},{"type":"text","text":" "},{"type":"text","text":"are linearly scaled."}],"title":"SBSDKWhiteBlackPointFilter","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKWhiteBlackPointFilter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWhiteBlackPointFilter","navigatorTitle":[{"text":"SBSDKWhiteBlackPointFilter","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkwhiteblackpointfilter"}},"variantOverrides":[{"patch":[{"value":"SBSDKParametricFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/title"},{"value":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/fragments"},{"value":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/navigatorTitle"},{"value":"SBSDKWhiteBlackPointFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWhiteBlackPointFilter\/title"},{"value":[{"kind":"identifier","text":"SBSDKWhiteBlackPointFilter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWhiteBlackPointFilter\/fragments"},{"value":[{"text":"SBSDKWhiteBlackPointFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWhiteBlackPointFilter\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}