{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"enabled","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":" = SBSDKUI2Color(colorString: \"?sbColorNegative\", isArgb: false), ","kind":"text"},{"kind":"externalParam","text":"iconColor"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"typeIdentifier"},{"text":" = SBSDKUI2Color(colorString: \"?sbColorOnPrimary\", isArgb: false))","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwipeToDelete\/init(enabled:backgroundColor:iconColor:)"},"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithEnabled:backgroundColor:iconColor:"}],"title":"init(enabled:backgroundColor:iconColor:)","roleHeading":"Initializer","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SwipeToDelete(im)initWithEnabled:backgroundColor:iconColor:","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"enabled","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"iconColor"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":")"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2swipetodelete\/init(enabled:backgroundcolor:iconcolor:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2swipetodelete\/init(enabled:backgroundcolor:iconcolor:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwipeToDelete"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwipeToDelete":{"navigatorTitle":[{"text":"SBSDKUI2SwipeToDelete","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2swipetodelete","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwipeToDelete","type":"topic","abstract":[{"type":"text","text":"Configuration of the swipe-to-delete button."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2SwipeToDelete"}],"kind":"symbol","title":"SBSDKUI2SwipeToDelete"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","title":"SBSDKUI2Color","url":"\/documentation\/scanbotsdk\/sbsdkui2color","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Color"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SwipeToDelete/init(enabled:backgroundColor:iconColor:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"enabled","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"iconColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SwipeToDelete\/init(enabled:backgroundColor:iconColor:)","navigatorTitle":[{"text":"initWithEnabled:backgroundColor:iconColor:","kind":"identifier"}],"role":"symbol","abstract":[],"type":"topic","title":"init(enabled:backgroundColor:iconColor:)","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2swipetodelete\/init(enabled:backgroundcolor:iconcolor:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithEnabled:backgroundColor:iconColor:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithEnabled:backgroundColor:iconColor:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithEnabled:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"enabled","kind":"internalParam"},{"kind":"text","text":" "},{"text":"backgroundColor:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","text":"SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"backgroundColor"},{"text":" ","kind":"text"},{"kind":"identifier","text":"iconColor:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"iconColor","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2SwipeToDelete","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwipeToDelete\/title"},{"op":"replace","value":[{"text":"SBSDKUI2SwipeToDelete","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwipeToDelete\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","value":"SBSDKUI2Color","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"initWithEnabled:backgroundColor:iconColor:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwipeToDelete~1init(enabled:backgroundColor:iconColor:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SwipeToDelete~1init(enabled:backgroundColor:iconColor:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithEnabled:backgroundColor:iconColor:"}],"op":"replace"}]}]}