{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController\/SBSDKFinderViewDelegate-Implementations"},"sections":[],"metadata":{"title":"SBSDKFinderViewDelegate Implementations","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"API Collection","role":"collectionGroup"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller\/sbsdkfinderviewdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller\/sbsdkfinderviewdelegate-implementations"]}],"kind":"article","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController\/finderView(_:didChangeRect:)"],"title":"Instance Methods"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewController/finderView(_:didChangeRect:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController\/finderView(_:didChangeRect:)","abstract":[{"text":"Informs the delegate, that the finder view has changed its finder rectangle.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Optional."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKFinderView","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKFinderView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didChangeRect","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller\/finderview(_:didchangerect:)","type":"topic","title":"finderView(_:didChangeRect:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"finderView:didChangeRect:"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewController":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController","role":"symbol","abstract":[{"text":"A highly customizable camera view controller that delivers a basic camera functionality along with video","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"frame extraction and preprocessing, orientation correction and still image capturing."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"type":"topic","kind":"symbol","title":"SBSDKBaseScannerViewController"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController\/finderView(_:didChangeRect:)"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":"finderView:didChangeRect:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController~1finderView(_:didChangeRect:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController~1finderView(_:didChangeRect:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"finderView:didChangeRect:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKBaseScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/title"},{"value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}]}]}]}