{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentPreviewImage(usingParametricFilters:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/documentpreviewimage(usingparametricfilters:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/documentpreviewimage(usingparametricfilters:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"documentPreviewImage(usingParametricFilters:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentPreviewImage"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"usingParametricFilters"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier","text":"SBSDKParametricFilter"},{"kind":"text","text":"]?) -> "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"documentPreviewImageUsingParametricFilters:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPage(im)documentPreviewImageUsingParametricFilters:"},"abstract":[{"type":"text","text":"A preview "},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" of the document image including applied rotations, polygon and the given filter in a resolution matching the devices screen."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"documentPreviewImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"usingParametricFilters","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"filters","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"SBSDKParametricFilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier"},{"kind":"text","text":"]?) -> "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The array of parametric filters the preview image should be generated with or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}]}],"name":"filters"}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The generated preview image or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the image could not be generated."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","type":"topic","title":"SBSDKParametricFilter","navigatorTitle":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter","abstract":[{"type":"text","text":"Base class for all parametric filters."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKParametricFilter","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/documentPreviewImage(usingParametricFilters:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentPreviewImage(usingParametricFilters:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentPreviewImage"},{"kind":"text","text":"("},{"text":"usingParametricFilters","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"text":"]?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"documentPreviewImageUsingParametricFilters:"}],"title":"documentPreviewImage(usingParametricFilters:)","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/documentpreviewimage(usingparametricfilters:)","abstract":[{"text":"A preview ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" of the document image including applied rotations, polygon and the given filter in a resolution matching the devices screen."}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"title":"SBSDKDocumentPage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPage"}],"navigatorTitle":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"documentPreviewImageUsingParametricFilters:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"documentPreviewImageUsingParametricFilters:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"documentPreviewImageUsingParametricFilters:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKParametricFilter *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"filters"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/title","op":"replace","value":"SBSDKParametricFilter"},{"value":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentPreviewImage(usingParametricFilters:)\/title","value":"documentPreviewImageUsingParametricFilters:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentPreviewImage(usingParametricFilters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentPreviewImageUsingParametricFilters:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title","op":"replace","value":"SBSDKDocumentPage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"op":"replace"}]}]}