{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPage(im)documentPreviewImageURLUsingFilter:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentPreviewImageURL","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"usingFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageFilterType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFilterType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"documentPreviewImageURLUsingFilter:"}],"title":"documentPreviewImageURL(usingFilter:)","modules":[{"name":"ScanbotSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/documentpreviewimageurl(usingfilter:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/documentpreviewimageurl(usingfilter:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentPreviewImageURL","kind":"identifier"},{"kind":"text","text":"("},{"text":"usingFilter","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"filter"},{"text":": ","kind":"text"},{"text":"SBSDKImageFilterType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFilterType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType"},{"text":") -> ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"filter","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The filter the preview image should be generated with."}]}]}]},{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The file URL of the generated preview image or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the image could not be generated."}]}],"kind":"content"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentPreviewImageURL(usingFilter:)"},"abstract":[{"type":"text","text":"The URL of a preview UIImage of the document image including applied rotations, polygon and the given filter in a resolution matching the devices screen."}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType":{"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype","abstract":[{"text":"The ScanbotSDK image filter types.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","navigatorTitle":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFilterType"}],"role":"symbol","type":"topic","deprecated":true,"title":"SBSDKImageFilterType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/documentPreviewImageURL(usingFilter:)":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/documentpreviewimageurl(usingfilter:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentPreviewImageURL(usingFilter:)","title":"documentPreviewImageURL(usingFilter:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentPreviewImageURLUsingFilter:"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentPreviewImageURL"},{"kind":"text","text":"("},{"kind":"externalParam","text":"usingFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFilterType","text":"SBSDKImageFilterType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The URL of a preview UIImage of the document image including applied rotations, polygon and the given filter in a resolution matching the devices screen."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentPage"}],"title":"SBSDKDocumentPage","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"documentPreviewImageURLUsingFilter:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"documentPreviewImageURLUsingFilter:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"documentPreviewImageURLUsingFilter:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFilterType","text":"SBSDKImageFilterType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"filter","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"filter","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The filter the preview image should be generated with."}]}]}],"kind":"parameters"}},{"op":"replace","value":{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"The file URL of the generated preview image or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the image could not be generated.","type":"text"}],"type":"paragraph"}]},"path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/title","value":"SBSDKImageFilterType"},{"value":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/navigatorTitle","value":[{"text":"SBSDKImageFilterType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentPreviewImageURL(usingFilter:)\/title","value":"documentPreviewImageURLUsingFilter:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentPreviewImageURL(usingFilter:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"documentPreviewImageURLUsingFilter:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title","value":"SBSDKDocumentPage","op":"replace"},{"value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/navigatorTitle","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}]}]}]}