{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithPageFileID:polygon:filter:documentImageSizeLimit:"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"init","title":"init(pageFileID:polygon:filter:documentImageSizeLimit:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPage(im)initWithPageFileID:polygon:filter:documentImageSizeLimit:","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"pageFileID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"kind":"text","text":", "},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon"},{"text":"?, ","kind":"text"},{"text":"filter","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageFilterType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFilterType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentImageSizeLimit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":")"}],"roleHeading":"Initializer"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/init(pagefileid:polygon:filter:documentimagesizelimit:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/init(pagefileid:polygon:filter:documentimagesizelimit:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(pageFileID:polygon:filter:documentImageSizeLimit:)"},"kind":"symbol","abstract":[{"type":"text","text":"Designated initializer. Creates a new page object."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"pageFileID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"filter"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFilterType","text":"SBSDKImageFilterType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"documentImageSizeLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"pageFileID","content":[{"inlineContent":[{"text":"The ID of the images in the default page file storage.","type":"text"}],"type":"paragraph"}]},{"name":"polygon","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The polygon of the area where the document is located within the pages image."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The filter to be applied to the page.","type":"text"}]}],"name":"filter"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Limits the maximum size of the document image. If width or height are zero this parameter is being ignored.","type":"text"}]}],"name":"documentImageSizeLimit"}],"kind":"parameters"}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"abstract":[{"text":"This class represents a scanned documents page.","type":"text"}],"navigatorTitle":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","title":"SBSDKDocumentPage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","role":"symbol","title":"SBSDKImageFilterType","url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype","type":"topic","abstract":[{"text":"The ScanbotSDK image filter types.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageFilterType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"url":"\/documentation\/scanbotsdk\/sbsdkpolygon","type":"topic","navigatorTitle":[{"text":"SBSDKPolygon","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPolygon"}],"title":"SBSDKPolygon","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/init(pageFileID:polygon:filter:documentImageSizeLimit:)":{"abstract":[{"text":"Designated initializer. Creates a new page object.","type":"text"}],"type":"topic","title":"init(pageFileID:polygon:filter:documentImageSizeLimit:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(pageFileID:polygon:filter:documentImageSizeLimit:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pageFileID"},{"text":": ","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"polygon"},{"kind":"text","text":": "},{"text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"filter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageFilterType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFilterType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentImageSizeLimit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithPageFileID:polygon:filter:documentImageSizeLimit:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/init(pagefileid:polygon:filter:documentimagesizelimit:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithPageFileID:polygon:filter:documentImageSizeLimit:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithPageFileID:polygon:filter:documentImageSizeLimit:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"initWithPageFileID:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSUUID","text":"NSUUID"},{"kind":"text","text":" *) "},{"text":"pageFileID","kind":"internalParam"},{"kind":"text","text":" "},{"text":"polygon:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"polygon"},{"text":" ","kind":"text"},{"text":"filter:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKImageFilterType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFilterType","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType"},{"text":") ","kind":"text"},{"text":"filter","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentImageSizeLimit:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":") ","kind":"text"},{"text":"documentImageSizeLimit","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The ID of the images in the default page file storage."}],"type":"paragraph"}],"name":"pageFileID"},{"content":[{"inlineContent":[{"type":"text","text":"The polygon of the area where the document is located within the pages image."}],"type":"paragraph"}],"name":"polygon"},{"name":"filter","content":[{"type":"paragraph","inlineContent":[{"text":"The filter to be applied to the page.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Limits the maximum size of the document image. If width or height are zero this parameter is being ignored.","type":"text"}],"type":"paragraph"}],"name":"documentImageSizeLimit"}]},"op":"replace"},{"op":"replace","value":"SBSDKDocumentPage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments","op":"replace","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentPage"}]},{"op":"replace","value":"SBSDKImageFilterType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/title"},{"value":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageFilterType"}]},{"value":"SBSDKPolygon","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKPolygon","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/navigatorTitle","value":[{"text":"SBSDKPolygon","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1init(pageFileID:polygon:filter:documentImageSizeLimit:)\/title","value":"initWithPageFileID:polygon:filter:documentImageSizeLimit:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1init(pageFileID:polygon:filter:documentImageSizeLimit:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithPageFileID:polygon:filter:documentImageSizeLimit:","kind":"identifier"}]}]}]}