{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"pageFileID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"filter"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFilterType","text":"SBSDKImageFilterType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"pageFileID","content":[{"inlineContent":[{"type":"text","text":"The ID of the images in the default page file storage."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The polygon of the area where the document is located within the pages image."}],"type":"paragraph"}],"name":"polygon"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The filter to be applied to the page.","type":"text"}]}],"name":"filter"}]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithPageFileID:polygon:filter:","kind":"identifier"}],"title":"init(pageFileID:polygon:filter:)","symbolKind":"init","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pageFileID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"polygon"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"filter"},{"text":": ","kind":"text"},{"text":"SBSDKImageFilterType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFilterType"},{"text":")","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPage(im)initWithPageFileID:polygon:filter:"},"sections":[],"abstract":[{"type":"text","text":"Designated initializer. Creates a new page object."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/init(pagefileid:polygon:filter:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/init(pagefileid:polygon:filter:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(pageFileID:polygon:filter:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType":{"abstract":[{"type":"text","text":"The ScanbotSDK image filter types."}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype","title":"SBSDKImageFilterType","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","deprecated":true,"navigatorTitle":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKImageFilterType","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/init(pageFileID:polygon:filter:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pageFileID","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"polygon"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon"},{"text":"?, ","kind":"text"},{"text":"filter","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKImageFilterType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFilterType"},{"text":")","kind":"text"}],"abstract":[{"text":"Designated initializer. Creates a new page object.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(pageFileID:polygon:filter:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPageFileID:polygon:filter:"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/init(pagefileid:polygon:filter:)","kind":"symbol","type":"topic","title":"init(pageFileID:polygon:filter:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"title":"SBSDKDocumentPage","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPage"}],"abstract":[{"text":"This class represents a scanned documents page.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","role":"symbol","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"abstract":[{"text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPolygon","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKPolygon","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon","title":"SBSDKPolygon","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithPageFileID:polygon:filter:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithPageFileID:polygon:filter:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithPageFileID:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSUUID","text":"NSUUID"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pageFileID"},{"text":" ","kind":"text"},{"text":"polygon:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"polygon"},{"kind":"text","text":" "},{"text":"filter:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKImageFilterType","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFilterType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"filter"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"SBSDKImageFilterType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1init(pageFileID:polygon:filter:)\/title","value":"initWithPageFileID:polygon:filter:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1init(pageFileID:polygon:filter:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPageFileID:polygon:filter:"}],"op":"replace"},{"value":"SBSDKDocumentPage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentPage"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title","value":"SBSDKPolygon","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPolygon"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments","op":"replace"}]}]}