{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Designated initializer. Creates a new page object.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(pageFileID:polygon:parametricFilters:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/init(pagefileid:polygon:parametricfilters:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/init(pagefileid:polygon:parametricfilters:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"pageFileID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"polygon"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","text":"SBSDKPolygon"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"parametricFilters"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier","text":"SBSDKParametricFilter"},{"kind":"text","text":"]?)"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ID of the images in the default page file storage."}]}],"name":"pageFileID"},{"name":"polygon","content":[{"type":"paragraph","inlineContent":[{"text":"The polygon of the area where the document is located within the pages image.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"The array of parametric filters to be applied to the page or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"parametricFilters"}]}],"kind":"symbol","metadata":{"symbolKind":"init","roleHeading":"Initializer","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPage(im)initWithPageFileID:polygon:parametricFilters:","title":"init(pageFileID:polygon:parametricFilters:)","navigatorTitle":[{"text":"initWithPageFileID:polygon:parametricFilters:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"pageFileID","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier","text":"SBSDKPolygon"},{"kind":"text","text":"?, "},{"text":"parametricFilters","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter","kind":"typeIdentifier"},{"kind":"text","text":"]?)"}],"modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKParametricFilter","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"abstract":[{"type":"text","text":"Base class for all parametric filters."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter","title":"SBSDKParametricFilter","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/init(pageFileID:polygon:parametricFilters:)":{"abstract":[{"type":"text","text":"Designated initializer. Creates a new page object."}],"kind":"symbol","type":"topic","title":"init(pageFileID:polygon:parametricFilters:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(pageFileID:polygon:parametricFilters:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/init(pagefileid:polygon:parametricfilters:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"pageFileID","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"kind":"text","text":"?, "},{"text":"parametricFilters","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter"},{"text":"]?)","kind":"text"}],"navigatorTitle":[{"text":"initWithPageFileID:polygon:parametricFilters:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"title":"SBSDKDocumentPage","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPage"}],"abstract":[{"text":"This class represents a scanned documents page.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygon","kind":"identifier"}],"abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"type":"topic","title":"SBSDKPolygon","url":"\/documentation\/scanbotsdk\/sbsdkpolygon","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithPageFileID:polygon:parametricFilters:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPageFileID:polygon:parametricFilters:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithPageFileID:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSUUID","text":"NSUUID","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"pageFileID"},{"text":" ","kind":"text"},{"kind":"identifier","text":"polygon:"},{"kind":"text","text":"("},{"text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"polygon","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"parametricFilters:"},{"kind":"text","text":"("},{"text":"NSArray<SBSDKParametricFilter *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"parametricFilters","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ID of the images in the default page file storage."}]}],"name":"pageFileID"},{"name":"polygon","content":[{"type":"paragraph","inlineContent":[{"text":"The polygon of the area where the document is located within the pages image.","type":"text"}]}]},{"name":"parametricFilters","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The array of parametric filters to be applied to the page or "},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}]}]}]},"op":"replace"},{"op":"replace","value":"SBSDKParametricFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/title"},{"value":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/fragments","op":"replace"},{"value":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/navigatorTitle"},{"op":"replace","value":"initWithPageFileID:polygon:parametricFilters:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1init(pageFileID:polygon:parametricFilters:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1init(pageFileID:polygon:parametricFilters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPageFileID:polygon:parametricFilters:"}]},{"value":"SBSDKDocumentPage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentPage"}]},{"value":"SBSDKPolygon","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments","value":[{"text":"SBSDKPolygon","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPolygon"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}