{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage"]]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/status","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/status"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/status"]}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectionStatus","text":"SBSDKDocumentDetectionStatus","kind":"typeIdentifier"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPage(py)status","title":"status","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"status","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectionStatus","kind":"typeIdentifier","text":"SBSDKDocumentDetectionStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The status of the documents polygon that was detected on the original image."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","type":"topic","title":"SBSDKDocumentPage","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPage","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentPage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus","title":"SBSDKDocumentDetectionStatus","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The status of the latest document detection."}],"navigatorTitle":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/status":{"abstract":[{"type":"text","text":"The status of the documents polygon that was detected on the original image."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/status","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectionStatus","text":"SBSDKDocumentDetectionStatus"}],"type":"topic","title":"status","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/status","navigatorTitle":[{"text":"status","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"status"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"status","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectionStatus","kind":"typeIdentifier","text":"SBSDKDocumentDetectionStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"SBSDKDocumentPage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/title","value":"SBSDKDocumentDetectionStatus","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1status\/title","value":"status"},{"value":[{"text":"status","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1status\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}