{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/unfilteredDocumentImage","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage"]]},"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPage(py)unfilteredDocumentImage","roleHeading":"Instance Property","role":"symbol","title":"unfilteredDocumentImage","navigatorTitle":[{"kind":"identifier","text":"unfilteredDocumentImage"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unfilteredDocumentImage","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unfilteredDocumentImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"UIImage"},{"text":" of the unfiltered document image including applied rotations and polygon.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/unfiltereddocumentimage"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/unfiltereddocumentimage"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/unfilteredDocumentImage":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/unfiltereddocumentimage","role":"symbol","title":"unfilteredDocumentImage","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" of the unfiltered document image including applied rotations and polygon."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/unfilteredDocumentImage","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unfilteredDocumentImage","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"unfilteredDocumentImage"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"title":"SBSDKDocumentPage","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentPage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"unfilteredDocumentImage","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"unfilteredDocumentImage","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":" * "},{"text":"unfilteredDocumentImage","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1unfilteredDocumentImage\/title","value":"unfilteredDocumentImage"},{"op":"replace","value":[{"kind":"identifier","text":"unfilteredDocumentImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1unfilteredDocumentImage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title","value":"SBSDKDocumentPage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentPage"}]}]}]}