{"relationshipsSections":[{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype"]}],"sections":[],"abstract":[{"type":"text","text":"The ScanbotSDK image filter types."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"symbolKind":"enum","platforms":[],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"SBSDKImageFilterType","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFilterType","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageFilterType","kind":"identifier"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType"},"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/backgroundClean","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/binarized","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/blackAndWhite","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/color","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/colorDocument","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/deepBinarization","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/edgeHighlight","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/gray","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/lowLightBinarization","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/lowLightBinarization2","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/none","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/otsuBinarization","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/pureBinarized","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/pureGray","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/sensitiveBinarization"],"generated":true,"title":"Enumeration Cases"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFilterType"}],"platforms":["iOS"],"languages":["swift"]}]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please consider using the new class-based SBSDKParametricFilters."}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/otsuBinarization":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/otsubinarization","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"otsuBinarization","kind":"identifier"}],"deprecated":true,"abstract":[{"type":"text","text":"A filter for black and white conversion using OTSU binarization."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/otsuBinarization","type":"topic","title":"SBSDKImageFilterType.otsuBinarization","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeOtsuBinarization"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/colorDocument":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/colordocument","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeColorDocument"}],"title":"SBSDKImageFilterType.colorDocument","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/colorDocument","kind":"symbol","deprecated":true,"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorDocument"}],"type":"topic","abstract":[{"type":"text","text":"Fixes white-balance and cleans up the background."},{"type":"text","text":" "},{"text":"Usecase: images of paper documents.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/gray":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/gray","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeGray"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"gray"}],"title":"SBSDKImageFilterType.gray","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/gray","abstract":[{"text":"Standard grayscale filter. Creates a grayscaled 8-bit image and optimizes contrast and dynamic range.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/blackAndWhite":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"blackAndWhite","kind":"identifier"}],"abstract":[{"text":"Black and white filter with background cleaning. Creates a grayscaled 8-bit image with mostly black or white pixels.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Usecase: Textual documents or documents with black and white illustrations."}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/blackandwhite","title":"SBSDKImageFilterType.blackAndWhite","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/blackAndWhite","deprecated":true,"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeBlackAndWhite"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/backgroundClean":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/backgroundClean","abstract":[{"type":"text","text":"Cleans up the background and tries to preserve photos within the image."},{"type":"text","text":" "},{"type":"text","text":"Usecase: magazine pages, flyers."}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/backgroundclean","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"backgroundClean","kind":"identifier"}],"title":"SBSDKImageFilterType.backgroundClean","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeBackgroundClean"}],"deprecated":true,"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/init(rawValue:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/init(rawvalue:)","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"title":"init(rawValue:)","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/init(rawValue:)","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/pureBinarized":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pureBinarized"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/purebinarized","kind":"symbol","abstract":[{"type":"text","text":"A filter for binarizing an image. Creates an 8-bit image with pixel values set to eiter 0 or 255."},{"text":" ","type":"text"},{"text":"Usecase: Preparation for optical character recognition.","type":"text"}],"title":"SBSDKImageFilterType.pureBinarized","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/pureBinarized","deprecated":true,"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypePureBinarized"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/sensitiveBinarization":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/sensitiveBinarization","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/sensitivebinarization","abstract":[{"type":"text","text":"Binarization filter for poor quality printed papers."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"sensitiveBinarization","kind":"identifier"}],"kind":"symbol","title":"SBSDKImageFilterType.sensitiveBinarization","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKImageFilterTypeSensitiveBinarization","kind":"identifier"}],"deprecated":true},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/deepBinarization":{"abstract":[{"type":"text","text":"A filter for black and white conversion primary used for low-contrast documents."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeDeepBinarization"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"deepBinarization","kind":"identifier"}],"title":"SBSDKImageFilterType.deepBinarization","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/deepBinarization","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/deepbinarization"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/lowLightBinarization2":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowLightBinarization2"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/lowlightbinarization2","kind":"symbol","abstract":[{"type":"text","text":"Binarization filter primary intended to use on low-contrast documents with heavy shadows."}],"title":"SBSDKImageFilterType.lowLightBinarization2","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/lowLightBinarization2","deprecated":true,"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeLowLightBinarization2"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/color":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/color","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/color","abstract":[{"type":"text","text":"Optimizes colors, contrast and brightness."},{"type":"text","text":" "},{"type":"text","text":"Usecase: photos."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"color","kind":"identifier"}],"kind":"symbol","title":"SBSDKImageFilterType.color","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKImageFilterTypeColor","kind":"identifier"}],"deprecated":true},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/pureGray":{"abstract":[{"type":"text","text":"Standard grayscale filter. Creates a grayscaled 8-bit image."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypePureGray"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pureGray"}],"title":"SBSDKImageFilterType.pureGray","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/pureGray","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/puregray"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/edgeHighlight":{"kind":"symbol","type":"topic","title":"SBSDKImageFilterType.edgeHighlight","abstract":[{"type":"text","text":"A filter that enhances edges in low-contrast documents."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"edgeHighlight"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/edgehighlight","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/edgeHighlight","role":"symbol","navigatorTitle":[{"text":"SBSDKImageFilterTypeEdgeHighlight","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/lowLightBinarization":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/lowLightBinarization","navigatorTitle":[{"text":"SBSDKImageFilterTypeLowLightBinarization","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Binarization filter primary inteded to use on low-contrast documents with heavy shadows."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/lowlightbinarization","title":"SBSDKImageFilterType.lowLightBinarization","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lowLightBinarization"}],"deprecated":true},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/RawRepresentable-Implementations":{"role":"collectionGroup","type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/RawRepresentable-Implementations","kind":"article","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/rawrepresentable-implementations","title":"RawRepresentable Implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType":{"abstract":[{"text":"The ScanbotSDK image filter types.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFilterType"}],"kind":"symbol","title":"SBSDKImageFilterType","navigatorTitle":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype","deprecated":true,"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/binarized":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/binarized","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Standard binarization filter with contrast optimization. Creates a grayscaled 8-bit image with mostly black or white pixels.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Usecase: Preparation for optical character recognition."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"binarized","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/binarized","navigatorTitle":[{"text":"SBSDKImageFilterTypeBinarized","kind":"identifier"}],"deprecated":true,"title":"SBSDKImageFilterType.binarized"},"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"kind":"article","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/equatable-implementations","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/Equatable-Implementations","role":"collectionGroup"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/none":{"abstract":[{"text":"Passthrough filter. Does not alter the image.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeNone"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"title":"SBSDKImageFilterType.none","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/none","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/none"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKImageFilterType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/backgroundClean","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/binarized","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/blackAndWhite","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/color","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/colorDocument","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/deepBinarization","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/edgeHighlight","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/gray","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/lowLightBinarization","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/lowLightBinarization2","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/none","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/otsuBinarization","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/pureBinarized","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/pureGray","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/sensitiveBinarization"],"title":"Enumeration Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFilterType"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SBSDKImageFilterTypeOtsuBinarization","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1otsuBinarization\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1otsuBinarization\/fragments","value":[{"text":"SBSDKImageFilterTypeOtsuBinarization","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1colorDocument\/title","value":"SBSDKImageFilterTypeColorDocument"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1colorDocument\/fragments","value":[{"text":"SBSDKImageFilterTypeColorDocument","kind":"identifier"}]},{"value":"SBSDKImageFilterTypeGray","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1gray\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1gray\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeGray"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1blackAndWhite\/title","op":"replace","value":"SBSDKImageFilterTypeBlackAndWhite"},{"value":[{"text":"SBSDKImageFilterTypeBlackAndWhite","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1blackAndWhite\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1backgroundClean\/title","value":"SBSDKImageFilterTypeBackgroundClean"},{"value":[{"text":"SBSDKImageFilterTypeBackgroundClean","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1backgroundClean\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1pureBinarized\/title","value":"SBSDKImageFilterTypePureBinarized","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1pureBinarized\/fragments","op":"replace","value":[{"text":"SBSDKImageFilterTypePureBinarized","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1sensitiveBinarization\/title","value":"SBSDKImageFilterTypeSensitiveBinarization","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1sensitiveBinarization\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeSensitiveBinarization"}],"op":"replace"},{"value":"SBSDKImageFilterTypeDeepBinarization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1deepBinarization\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeDeepBinarization"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1deepBinarization\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1lowLightBinarization2\/title","op":"replace","value":"SBSDKImageFilterTypeLowLightBinarization2"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1lowLightBinarization2\/fragments","value":[{"text":"SBSDKImageFilterTypeLowLightBinarization2","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1color\/title","op":"replace","value":"SBSDKImageFilterTypeColor"},{"op":"replace","value":[{"text":"SBSDKImageFilterTypeColor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1color\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1pureGray\/title","op":"replace","value":"SBSDKImageFilterTypePureGray"},{"value":[{"text":"SBSDKImageFilterTypePureGray","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1pureGray\/fragments"},{"value":"SBSDKImageFilterTypeEdgeHighlight","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1edgeHighlight\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1edgeHighlight\/fragments","value":[{"text":"SBSDKImageFilterTypeEdgeHighlight","kind":"identifier"}]},{"value":"SBSDKImageFilterTypeLowLightBinarization","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1lowLightBinarization\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1lowLightBinarization\/fragments","value":[{"text":"SBSDKImageFilterTypeLowLightBinarization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/title","value":"SBSDKImageFilterType"},{"value":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/fragments"},{"op":"replace","value":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1binarized\/title","op":"replace","value":"SBSDKImageFilterTypeBinarized"},{"value":[{"text":"SBSDKImageFilterTypeBinarized","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1binarized\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1none\/title","value":"SBSDKImageFilterTypeNone"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1none\/fragments","value":[{"text":"SBSDKImageFilterTypeNone","kind":"identifier"}],"op":"replace"}]}]}