{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpatterncontentvalidator\/initwithallowedcharacters:pattern:matchsubstring:patterngrammar:"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternContentValidator"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithAllowedCharacters:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"allowedCharacters","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pattern:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"pattern","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"matchSubstring:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"matchSubstring","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"patternGrammar:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternGrammar","text":"SBSDKPatternGrammar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPatternGrammar"},{"text":") ","kind":"text"},{"text":"patternGrammar","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithAllowedCharacters:pattern:matchSubstring:patternGrammar:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"initWithAllowedCharacters:pattern:matchSubstring:patternGrammar:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPatternContentValidator(im)initWithAllowedCharacters:pattern:matchSubstring:patternGrammar:","title":"initWithAllowedCharacters:pattern:matchSubstring:patternGrammar:","role":"symbol","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternContentValidator\/initWithAllowedCharacters:pattern:matchSubstring:patternGrammar:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPatternContentValidator/initWithAllowedCharacters:pattern:matchSubstring:patternGrammar:":{"abstract":[],"type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"initWithAllowedCharacters:pattern:matchSubstring:patternGrammar:","kind":"identifier"}],"title":"initWithAllowedCharacters:pattern:matchSubstring:patternGrammar:","url":"\/documentation\/scanbotsdk\/sbsdkpatterncontentvalidator\/initwithallowedcharacters:pattern:matchsubstring:patterngrammar:","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithAllowedCharacters:pattern:matchSubstring:patternGrammar:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternContentValidator\/initWithAllowedCharacters:pattern:matchSubstring:patternGrammar:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPatternContentValidator":{"type":"topic","title":"SBSDKPatternContentValidator","url":"\/documentation\/scanbotsdk\/sbsdkpatterncontentvalidator","abstract":[{"text":"Pattern content validator.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternContentValidator","role":"symbol","navigatorTitle":[{"text":"SBSDKPatternContentValidator","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPatternContentValidator","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPatternGrammar":{"type":"topic","title":"SBSDKPatternGrammar","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpatterngrammar","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPatternGrammar"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternGrammar","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPatternGrammar"}],"abstract":[{"text":"Grammar of pattern matching.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternContentValidator\/title","value":"SBSDKPatternContentValidator"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternContentValidator\/fragments","value":[{"kind":"identifier","text":"SBSDKPatternContentValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternContentValidator\/navigatorTitle","value":[{"text":"SBSDKPatternContentValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternGrammar\/title","value":"SBSDKPatternGrammar"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternGrammar\/fragments","value":[{"kind":"identifier","text":"SBSDKPatternGrammar"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternGrammar\/navigatorTitle","value":[{"text":"SBSDKPatternGrammar","kind":"identifier"}]}]}]}