{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodesextensionfilter\/nofilter"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodesextensionfilter\/nofilter"]}],"abstract":[{"text":"EAN and UPC barcoded with or without extensions will be returned.","type":"text"}],"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodesExtensionFilter@SBSDKBarcodesExtensionFilterNoFilter","title":"SBSDKBarcodesExtensionFilter.noFilter","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilterNoFilter"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"noFilter"}],"roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodesExtensionFilter"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"noFilter","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodesExtensionFilter\/noFilter","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodesExtensionFilter/noFilter":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodesExtensionFilter\/noFilter","role":"symbol","type":"topic","title":"SBSDKBarcodesExtensionFilter.noFilter","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodesextensionfilter\/nofilter","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"noFilter","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilterNoFilter"}],"abstract":[{"text":"EAN and UPC barcoded with or without extensions will be returned.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodesExtensionFilter":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodesExtensionFilter","navigatorTitle":[{"text":"SBSDKBarcodesExtensionFilter","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodesextensionfilter","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodesExtensionFilter","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"SBSDKBarcodesExtensionFilter","abstract":[{"text":"Filter for extended EAN and UPC barcodes.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKBarcodesExtensionFilterNoFilter","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilterNoFilter"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilterNoFilter"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodesExtensionFilter~1noFilter\/title","value":"SBSDKBarcodesExtensionFilterNoFilter","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodesExtensionFilter~1noFilter\/fragments","value":[{"text":"SBSDKBarcodesExtensionFilterNoFilter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodesExtensionFilter\/title","value":"SBSDKBarcodesExtensionFilter"},{"value":[{"text":"SBSDKBarcodesExtensionFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodesExtensionFilter\/fragments"},{"value":[{"text":"SBSDKBarcodesExtensionFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodesExtensionFilter\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}