{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/insuredpaycase"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/insuredpaycase"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType\/insuredPayCase","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insuredPayCase","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerCheckboxType@SBSDKMedicalCertificateRecognizerCheckboxTypeInsuredPayCase","modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxTypeInsuredPayCase","kind":"identifier"}],"title":"SBSDKMedicalCertificateRecognizerCheckboxType.insuredPayCase"},"kind":"symbol","abstract":[{"text":"The insured pay-case checkbox.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"insuredPayCase"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerCheckboxType":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxType"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Type classifiers for checkboxes recognized on medical certificates."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxType"}],"title":"SBSDKMedicalCertificateRecognizerCheckboxType","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerCheckboxType/insuredPayCase":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType\/insuredPayCase","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/insuredpaycase","abstract":[{"text":"The insured pay-case checkbox.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insuredPayCase","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxTypeInsuredPayCase","kind":"identifier"}],"title":"SBSDKMedicalCertificateRecognizerCheckboxType.insuredPayCase"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKMedicalCertificateRecognizerCheckboxTypeInsuredPayCase","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxTypeInsuredPayCase"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxTypeInsuredPayCase","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKMedicalCertificateRecognizerCheckboxType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType\/fragments","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType\/navigatorTitle","op":"replace"},{"value":"SBSDKMedicalCertificateRecognizerCheckboxTypeInsuredPayCase","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType~1insuredPayCase\/title","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxTypeInsuredPayCase","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType~1insuredPayCase\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}