{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:) "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bezierPath","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"cornerRadius"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":" "},{"text":"previewLayer","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer","text":"AVCaptureVideoPreviewLayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"text":"UIDeviceOrientation","preciseIdentifier":"c:@E@UIDeviceOrientation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isFrontCamera"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier","text":"UIBezierPath"}],"languages":["swift"]}]},{"parameters":[{"name":"cornerRadius","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The radius to use when drawing rounded corners."}]}]},{"name":"previewLayer","content":[{"type":"paragraph","inlineContent":[{"text":"The preview layer the path is going to be presented on.","type":"text"}]}]},{"name":"orientation","content":[{"inlineContent":[{"type":"text","text":"The device orientation. Used to calculate starting point."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Currently used camera - front camera. Used to calculate starting point.","type":"text"}]}],"name":"isFrontCamera"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"text":"An UIBezierPath instance representing the polygon.","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygon\/bezierPath(with:for:orientation:isFrontCamera:)","interfaceLanguage":"swift"},"abstract":[{"text":"Creates a UIBezierPath instance of the receiver for drawing purposes.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygon\/bezierpath(with:for:orientation:isfrontcamera:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygon\/bezierpath(with:for:orientation:isfrontcamera:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bezierPath"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer","text":"AVCaptureVideoPreviewLayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIDeviceOrientation","preciseIdentifier":"c:@E@UIDeviceOrientation"},{"text":", ","kind":"text"},{"text":"isFrontCamera","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKPolygon(im)bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:","roleHeading":"Instance Method","title":"bezierPath(with:for:orientation:isFrontCamera:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygon"]]},"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygon/bezierPath(with:for:orientation:isFrontCamera:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:"}],"role":"symbol","abstract":[{"type":"text","text":"Creates a UIBezierPath instance of the receiver for drawing purposes."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bezierPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer","text":"AVCaptureVideoPreviewLayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"orientation"},{"kind":"text","text":": "},{"text":"UIDeviceOrientation","preciseIdentifier":"c:@E@UIDeviceOrientation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isFrontCamera","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygon\/bezierPath(with:for:orientation:isFrontCamera:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygon\/bezierpath(with:for:orientation:isfrontcamera:)","title":"bezierPath(with:for:orientation:isFrontCamera:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygon":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygon","title":"SBSDKPolygon","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygon","navigatorTitle":[{"text":"SBSDKPolygon","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPolygon"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"UIBezierPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"bezierPathWithCornerRadius:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cornerRadius"},{"text":" ","kind":"text"},{"kind":"identifier","text":"forPreviewLayer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCaptureVideoPreviewLayer","preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer"},{"kind":"text","text":" *) "},{"text":"previewLayer","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"orientation:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIDeviceOrientation","preciseIdentifier":"c:@E@UIDeviceOrientation","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"orientation","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFrontCamera:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isFrontCamera"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"cornerRadius","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The radius to use when drawing rounded corners."}]}]},{"name":"previewLayer","content":[{"inlineContent":[{"type":"text","text":"The preview layer the path is going to be presented on."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The device orientation. Used to calculate starting point.","type":"text"}],"type":"paragraph"}],"name":"orientation"},{"name":"isFrontCamera","content":[{"type":"paragraph","inlineContent":[{"text":"Currently used camera - front camera. Used to calculate starting point.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"An UIBezierPath instance representing the polygon."}],"type":"paragraph"}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygon~1bezierPath(with:for:orientation:isFrontCamera:)\/title","op":"replace","value":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:"},{"value":[{"text":"- ","kind":"text"},{"text":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygon~1bezierPath(with:for:orientation:isFrontCamera:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygon\/title","value":"SBSDKPolygon","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygon\/fragments","value":[{"kind":"identifier","text":"SBSDKPolygon"}]},{"value":[{"text":"SBSDKPolygon","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygon\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}