{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelvcardentry\/initwithgenericdocument:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"initWithGenericDocument:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGenericDocument:"}],"navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentModelVCardEntry(im)initWithGenericDocument:","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocument","text":"SBSDKGenericDocument","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocument","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelVCardEntry\/initWithGenericDocument:","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelVCardEntry"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelVCardEntry":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelVCardEntry","kind":"identifier"}],"abstract":[{"text":"VCard Entry","type":"text"}],"title":"SBSDKBarcodeDocumentModelVCardEntry","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelVCardEntry","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelVCardEntry","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelvcardentry"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocument":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocument","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocument","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocument","abstract":[{"type":"text","text":"Generic document."}],"kind":"symbol","title":"SBSDKGenericDocument","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelVCardEntry/initWithGenericDocument:":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelVCardEntry\/initWithGenericDocument:","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelvcardentry\/initwithgenericdocument:","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"title":"initWithGenericDocument:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelVCardEntry\/title","value":"SBSDKBarcodeDocumentModelVCardEntry","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelVCardEntry\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardEntry"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelVCardEntry\/navigatorTitle","value":[{"text":"SBSDKBarcodeDocumentModelVCardEntry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/title","value":"SBSDKGenericDocument","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}