{"metadata":{"required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeScannerController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeScannerViewController","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didScanBarcodes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"title":"barcodeScannerController(_:didScanBarcodes:)","navigatorTitle":[{"text":"barcodeScannerController:didScanBarcodes:","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKBarcodeScannerViewControllerDelegate(im)barcodeScannerController:didScanBarcodes:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(barcodeScannerController:didScanBarcodes:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeScannerController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeScannerViewController","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didScanBarcodes","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"codes","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"SBSDKBarcodeItem","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem","kind":"typeIdentifier"},{"text":"])","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"controller","content":[{"inlineContent":[{"type":"text","text":"The calling "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"codes","content":[{"inlineContent":[{"type":"text","text":"Array of "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerResult","type":"reference"},{"text":" containing the scanned barcodes.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewControllerDelegate\/barcodeScannerController(_:didScanBarcodes:)"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewControllerDelegate"]]},"abstract":[{"text":"Informs the delegate that the receiver has scanned some barcodes.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontrollerdelegate\/barcodescannercontroller(_:didscanbarcodes:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontrollerdelegate\/barcodescannercontroller(_:didscanbarcodes:)"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewControllerDelegate":{"title":"SBSDKBarcodeScannerViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewControllerDelegate"}],"abstract":[{"type":"text","text":"The delegate protocol of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController","isActive":true},{"type":"text","text":" that provides methods for"},{"type":"text","text":" "},{"type":"text","text":"enabling\/disabling scanning and managing scanned barcodes."}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewControllerDelegate","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerViewControllerDelegate"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerResult":{"abstract":[{"text":"The result of barcode scanning.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerresult","title":"SBSDKBarcodeScannerResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewController":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"title":"SBSDKBarcodeScannerViewController","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode scanner."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeItem":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeItem"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeItem"}],"title":"SBSDKBarcodeItem","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeitem","abstract":[{"type":"text","text":"A single barcode found in the input image. Barcodes with the same content but different locations in the image are considered separate barcodes."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeItem","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewControllerDelegate/barcodeScannerController(_:didScanBarcodes:)":{"navigatorTitle":[{"kind":"identifier","text":"barcodeScannerController:didScanBarcodes:"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewControllerDelegate\/barcodeScannerController(_:didScanBarcodes:)","kind":"symbol","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeScannerController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKBarcodeScannerViewController","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didScanBarcodes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem"},{"kind":"text","text":"])"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontrollerdelegate\/barcodescannercontroller(_:didscanbarcodes:)","title":"barcodeScannerController(_:didScanBarcodes:)","type":"topic","abstract":[{"type":"text","text":"Informs the delegate that the receiver has scanned some barcodes."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"barcodeScannerController:didScanBarcodes:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"barcodeScannerController:didScanBarcodes:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"barcodeScannerController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didScanBarcodes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKBarcodeItem *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"codes","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"text":"The calling ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]},{"name":"codes","content":[{"type":"paragraph","inlineContent":[{"text":"Array of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerResult"},{"text":" containing the scanned barcodes.","type":"text"}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewControllerDelegate\/title","value":"SBSDKBarcodeScannerViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewControllerDelegate\/fragments","value":[{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerResult\/title","value":"SBSDKBarcodeScannerResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerResult\/fragments","value":[{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/title","value":"SBSDKBarcodeScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeItem\/title","value":"SBSDKBarcodeItem","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeItem\/fragments","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeItem\/navigatorTitle","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewControllerDelegate~1barcodeScannerController(_:didScanBarcodes:)\/title","value":"barcodeScannerController:didScanBarcodes:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewControllerDelegate~1barcodeScannerController(_:didScanBarcodes:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"barcodeScannerController:didScanBarcodes:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}