{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldStringValue"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithValue:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"value","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldStringValue\/initWithValue:"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:"}],"navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"title":"initWithValue:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUserFieldStringValue(im)initWithValue:","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuserfieldstringvalue\/initwithvalue:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUserFieldStringValue/initWithValue:":{"title":"initWithValue:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldStringValue\/initWithValue:","url":"\/documentation\/scanbotsdk\/sbsdkuserfieldstringvalue\/initwithvalue:","type":"topic","navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithValue:"}],"role":"symbol","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUserFieldStringValue":{"url":"\/documentation\/scanbotsdk\/sbsdkuserfieldstringvalue","title":"SBSDKUserFieldStringValue","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"ASCII string value (TIFF_ASCII)."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUserFieldStringValue","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUserFieldStringValue","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldStringValue"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldStringValue\/title","value":"SBSDKUserFieldStringValue","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUserFieldStringValue"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldStringValue\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldStringValue\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUserFieldStringValue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}