{"metadata":{"roleHeading":"Type Method","title":"fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorMRZFallbackConfiguration(cm)fromJsonWithJson:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"symbolKind":"method","modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorMRZFallbackConfiguration","text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/fromJsonWithJson:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration\/fromjsonwithjson:"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorMRZFallbackConfiguration/fromJsonWithJson:":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/fromJsonWithJson:","role":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"kind":"symbol","title":"fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration\/fromjsonwithjson:","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorMRZFallbackConfiguration":{"abstract":[{"text":"MRZ fallback configuration element.","type":"text"},{"text":" ","type":"text"},{"text":"This configuration element does not enable the scanning of any document types by itself.","type":"text"},{"text":" ","type":"text"},{"text":"Add to extractor configuration to enable recognizing the MRZ only, specifically for documents that are otherwise not","type":"text"},{"text":" ","type":"text"},{"text":"supported.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Note that this may enable scanning of documents that were not enabled through the accepted document types."}],"title":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration\/title"},{"value":[{"text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration\/navigatorTitle"}]}]}