{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"blackPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"whitePoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkwhiteblackpointfilter\/init(blackpoint:whitepoint:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkwhiteblackpointfilter\/init(blackpoint:whitepoint:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWhiteBlackPointFilter\/init(blackPoint:whitePoint:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"blackPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"whitePoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"title":"init(blackPoint:whitePoint:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKWhiteBlackPointFilter(im)initWithBlackPoint:whitePoint:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBlackPoint:whitePoint:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWhiteBlackPointFilter"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWhiteBlackPointFilter":{"role":"symbol","title":"SBSDKWhiteBlackPointFilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKWhiteBlackPointFilter"}],"abstract":[{"type":"text","text":"Maps image value channel so that all the pixels darker than the black point are set to 0,"},{"type":"text","text":" "},{"type":"text","text":"all the pixels brighter than the white point are set to 255, and the pixels in between"},{"type":"text","text":" "},{"type":"text","text":"are linearly scaled."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWhiteBlackPointFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKWhiteBlackPointFilter"}],"url":"\/documentation\/scanbotsdk\/sbsdkwhiteblackpointfilter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWhiteBlackPointFilter/init(blackPoint:whitePoint:)":{"role":"symbol","title":"init(blackPoint:whitePoint:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"blackPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"whitePoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWhiteBlackPointFilter\/init(blackPoint:whitePoint:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBlackPoint:whitePoint:"}],"url":"\/documentation\/scanbotsdk\/sbsdkwhiteblackpointfilter\/init(blackpoint:whitepoint:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithBlackPoint:whitePoint:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBlackPoint:whitePoint:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBlackPoint:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":") "},{"kind":"internalParam","text":"blackPoint"},{"kind":"text","text":" "},{"kind":"identifier","text":"whitePoint:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":") "},{"kind":"internalParam","text":"whitePoint"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWhiteBlackPointFilter\/title","value":"SBSDKWhiteBlackPointFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWhiteBlackPointFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKWhiteBlackPointFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWhiteBlackPointFilter~1init(blackPoint:whitePoint:)\/title","value":"initWithBlackPoint:whitePoint:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWhiteBlackPointFilter~1init(blackPoint:whitePoint:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBlackPoint:whitePoint:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}