{"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKCameraSessionDelegate(im)cameraSessionWillStart:","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"cameraSessionWillStart","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKCameraSession","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraSession"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"cameraSessionWillStart:"}],"required":true,"roleHeading":"Instance Method","role":"symbol","title":"cameraSessionWillStart(_:)","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionDelegate"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"cameraSessionWillStart","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraSession","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","text":"SBSDKCameraSession"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"session","content":[{"type":"paragraph","inlineContent":[{"text":"The camera session.","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcamerasessiondelegate\/camerasessionwillstart(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcamerasessiondelegate\/camerasessionwillstart(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionDelegate\/cameraSessionWillStart(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Informs the delegate that the camera session is about to be started."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSessionDelegate/cameraSessionWillStart(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionDelegate\/cameraSessionWillStart(_:)","url":"\/documentation\/scanbotsdk\/sbsdkcamerasessiondelegate\/camerasessionwillstart(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraSessionWillStart"},{"text":"(","kind":"text"},{"text":"SBSDKCameraSession","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraSession","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"cameraSessionWillStart:"}],"role":"symbol","required":true,"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Informs the delegate that the camera session is about to be started."}],"title":"cameraSessionWillStart(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSessionDelegate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSessionDelegate","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraSessionDelegate","kind":"identifier"}],"abstract":[{"text":"The  delegate protocol for ","type":"text"},{"type":"codeVoice","code":"SBSDKCameraSession"},{"text":".","type":"text"}],"title":"SBSDKCameraSessionDelegate","navigatorTitle":[{"text":"SBSDKCameraSessionDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcamerasessiondelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSession"}],"role":"symbol","abstract":[{"text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"camera device and the preview layer. Provides functionality to capture still images."}],"title":"SBSDKCameraSession","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraSession","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"cameraSessionWillStart:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"cameraSessionWillStart:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"cameraSessionWillStart:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraSession","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","text":"SBSDKCameraSession"},{"text":" *) ","kind":"text"},{"text":"session","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The camera session.","type":"text"}],"type":"paragraph"}],"name":"session"}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionDelegate~1cameraSessionWillStart(_:)\/title","op":"replace","value":"cameraSessionWillStart:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cameraSessionWillStart:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionDelegate~1cameraSessionWillStart(_:)\/fragments"},{"value":"SBSDKCameraSessionDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionDelegate\/title"},{"value":[{"kind":"identifier","text":"SBSDKCameraSessionDelegate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionDelegate\/fragments"},{"value":[{"text":"SBSDKCameraSessionDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSessionDelegate\/navigatorTitle"},{"op":"replace","value":"SBSDKCameraSession","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/title"},{"value":[{"kind":"identifier","text":"SBSDKCameraSession"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/fragments"},{"value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/navigatorTitle"}]}]}