{"sections":[],"metadata":{"roleHeading":"Initializer","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatioRange(im)initWithAspectRatio1:aspectRatio2:","symbolKind":"init","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"aspectRatio1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatio"},{"kind":"text","text":", "},{"kind":"externalParam","text":"aspectRatio2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatio"},{"kind":"text","text":")"}],"title":"init(aspectRatio1:aspectRatio2:)","navigatorTitle":[{"kind":"identifier","text":"initWithAspectRatio1:aspectRatio2:"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkaspectratiorange\/init(aspectratio1:aspectratio2:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkaspectratiorange\/init(aspectratio1:aspectratio2:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithAspectRatio1:aspectRatio2:) ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"aspectRatio1","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatio","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatio","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"aspectRatio2","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatio","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatio","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"aspectRatio1","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"First aspect ratio."}]}]},{"name":"aspectRatio2","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Second aspect ratio."}]}]}]}],"abstract":[{"type":"text","text":"Designated initializer. It takes two aspect ratio and compares them to get minimum and maximum ones."}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatioRange\/init(aspectRatio1:aspectRatio2:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatioRange"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAspectRatioRange":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaspectratiorange","navigatorTitle":[{"text":"SBSDKAspectRatioRange","kind":"identifier"}],"abstract":[{"type":"text","text":"A class that represents a range of aspect ratios."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAspectRatioRange","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatioRange","role":"symbol","title":"SBSDKAspectRatioRange"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAspectRatioRange/init(aspectRatio1:aspectRatio2:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaspectratiorange\/init(aspectratio1:aspectratio2:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatioRange\/init(aspectRatio1:aspectRatio2:)","abstract":[{"text":"Designated initializer. It takes two aspect ratio and compares them to get minimum and maximum ones.","type":"text"}],"title":"init(aspectRatio1:aspectRatio2:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAspectRatio1:aspectRatio2:"}],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"aspectRatio1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatio","text":"SBSDKAspectRatio"},{"kind":"text","text":", "},{"kind":"externalParam","text":"aspectRatio2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatio","text":"SBSDKAspectRatio"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAspectRatio":{"kind":"symbol","type":"topic","title":"SBSDKAspectRatio","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaspectratio","navigatorTitle":[{"text":"SBSDKAspectRatio","kind":"identifier"}],"abstract":[{"type":"text","text":"Aspect ratio is the ratio of the width to the height of an image or screen."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatio","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAspectRatio","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithAspectRatio1:aspectRatio2:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAspectRatio1:aspectRatio2:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithAspectRatio1:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKAspectRatio","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatio","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"aspectRatio1","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"aspectRatio2:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKAspectRatio","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAspectRatio","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"aspectRatio2","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"First aspect ratio."}],"type":"paragraph"}],"name":"aspectRatio1"},{"content":[{"inlineContent":[{"text":"Second aspect ratio.","type":"text"}],"type":"paragraph"}],"name":"aspectRatio2"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatioRange\/title","value":"SBSDKAspectRatioRange"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatioRange\/fragments","value":[{"kind":"identifier","text":"SBSDKAspectRatioRange"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatioRange\/navigatorTitle","value":[{"text":"SBSDKAspectRatioRange","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatioRange~1init(aspectRatio1:aspectRatio2:)\/title","op":"replace","value":"initWithAspectRatio1:aspectRatio2:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatioRange~1init(aspectRatio1:aspectRatio2:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithAspectRatio1:aspectRatio2:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio\/title","op":"replace","value":"SBSDKAspectRatio"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKAspectRatio"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAspectRatio\/navigatorTitle","op":"replace","value":[{"text":"SBSDKAspectRatio","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}