{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod1010","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm\/mod1010"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm\/mod1010"]}],"abstract":[{"type":"text","text":"Mod1010 checksum algorithm"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mod1010","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm@SBSDKUI2MSIPlesseyChecksumAlgorithmMod1010","role":"symbol","roleHeading":"Case","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm.mod1010","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mod1010"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod1010"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm/mod1010":{"title":"SBSDKUI2MSIPlesseyChecksumAlgorithm.mod1010","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod1010","kind":"identifier"}],"abstract":[{"type":"text","text":"Mod1010 checksum algorithm"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"mod1010","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod1010","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm\/mod1010"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm","abstract":[{"type":"text","text":"Type of MSI plessey checksum algorithm used."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm","type":"topic","navigatorTitle":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod1010","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod1010"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod1010"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod1010","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod1010\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod1010\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod1010"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/title","value":"SBSDKUI2MSIPlesseyChecksumAlgorithm"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/navigatorTitle","value":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}