{"abstract":[{"text":"Mod10 checksum algorithm","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod10"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm"]]},"metadata":{"role":"symbol","symbolKind":"case","roleHeading":"Case","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm.mod10","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm@SBSDKUI2MSIPlesseyChecksumAlgorithmMod10","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mod10"}],"navigatorTitle":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod10","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm\/mod10"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm\/mod10"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mod10","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm","abstract":[{"text":"Type of MSI plessey checksum algorithm used.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}],"title":"SBSDKUI2MSIPlesseyChecksumAlgorithm","type":"topic","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm/mod10":{"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm\/mod10","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm.mod10","type":"topic","abstract":[{"type":"text","text":"Mod10 checksum algorithm"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mod10"}],"navigatorTitle":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod10","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod10"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod10"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod10","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod10"}]}]}},{"value":"SBSDKUI2MSIPlesseyChecksumAlgorithm","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/navigatorTitle"},{"value":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod10","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod10\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod10\/fragments","value":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod10","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}