{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/autosnapprogresspolygonconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/autosnapprogresspolygonconfiguration"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoSnapProgressPolygonConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentScannerPolygonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerPolygonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerPolygonConfiguration"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"The default color of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerPolygonConfiguration\/strokeColor","type":"reference","isActive":true},{"type":"text","text":" is "},{"type":"codeVoice","code":"UIColor.blue"},{"type":"text","text":" and the default stroke"},{"type":"text","text":" "},{"type":"text","text":"width of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerPolygonConfiguration\/strokeWidth","type":"reference","isActive":true},{"type":"text","text":" is 5.0."}],"type":"paragraph"}],"name":"Note"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController\/autoSnapProgressPolygonConfiguration","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"autoSnapProgressPolygonConfiguration","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController(py)autoSnapProgressPolygonConfiguration","navigatorTitle":[{"text":"autoSnapProgressPolygonConfiguration","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoSnapProgressPolygonConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentScannerPolygonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerPolygonConfiguration"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property"},"kind":"symbol","abstract":[{"type":"text","text":"The configuration for the progress polygon displayed over the scanned document when the document is being scanned in auto snapping mode."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerPolygonConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerPolygonConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerpolygonconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerPolygonConfiguration","abstract":[{"text":"Configuration for the polygon displayed over the scanned document.","type":"text"}],"navigatorTitle":[{"text":"SBSDKDocumentScannerPolygonConfiguration","kind":"identifier"}],"title":"SBSDKDocumentScannerPolygonConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerPolygonConfiguration/strokeWidth":{"role":"symbol","type":"topic","title":"strokeWidth","abstract":[{"text":"The stroke width for the polygon displayed around the scanned document.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"strokeWidth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerpolygonconfiguration\/strokewidth","navigatorTitle":[{"text":"strokeWidth","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerPolygonConfiguration\/strokeWidth","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerPolygonConfiguration/strokeColor":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"strokeColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerpolygonconfiguration\/strokecolor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerPolygonConfiguration\/strokeColor","abstract":[{"type":"text","text":"The stroke color for the polygon displayed over the scanned document."}],"navigatorTitle":[{"text":"strokeColor","kind":"identifier"}],"title":"strokeColor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController/autoSnapProgressPolygonConfiguration":{"role":"symbol","type":"topic","title":"autoSnapProgressPolygonConfiguration","abstract":[{"type":"text","text":"The configuration for the progress polygon displayed over the scanned document when the document is being scanned in auto snapping mode."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSnapProgressPolygonConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerPolygonConfiguration","text":"SBSDKDocumentScannerPolygonConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/autosnapprogresspolygonconfiguration","navigatorTitle":[{"kind":"identifier","text":"autoSnapProgressPolygonConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController\/autoSnapProgressPolygonConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController":{"title":"SBSDKDocumentScannerViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"kind":"symbol","type":"topic","abstract":[{"text":"A UIViewController subclass to show a camera screen and run a user guiding document scanner.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"autoSnapProgressPolygonConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"autoSnapProgressPolygonConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerPolygonConfiguration","text":"SBSDKDocumentScannerPolygonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerPolygonConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"autoSnapProgressPolygonConfiguration"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentScannerPolygonConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerPolygonConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerPolygonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerPolygonConfiguration\/fragments"},{"value":[{"text":"SBSDKDocumentScannerPolygonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerPolygonConfiguration\/navigatorTitle"},{"value":"strokeWidth","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerPolygonConfiguration~1strokeWidth\/title"},{"value":[{"text":"strokeWidth","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerPolygonConfiguration~1strokeWidth\/fragments"},{"value":"strokeColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerPolygonConfiguration~1strokeColor\/title"},{"value":[{"kind":"identifier","text":"strokeColor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerPolygonConfiguration~1strokeColor\/fragments"},{"value":"autoSnapProgressPolygonConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController~1autoSnapProgressPolygonConfiguration\/title"},{"value":[{"text":"autoSnapProgressPolygonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController~1autoSnapProgressPolygonConfiguration\/fragments"},{"value":"SBSDKDocumentScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/navigatorTitle"}]}]}