{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkwordbox\/initwithtext:boundingrect:recognitionconfidence:"]}],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithText:boundingRect:recognitionConfidence:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKWordBox(im)initWithText:boundingRect:recognitionConfidence:","roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithText:boundingRect:recognitionConfidence:","kind":"identifier"}],"role":"symbol","symbolKind":"method","title":"initWithText:boundingRect:recognitionConfidence:"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWordBox\/initWithText:boundingRect:recognitionConfidence:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWordBox"]]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithText:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"text","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"boundingRect:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"text":"boundingRect","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"recognitionConfidence:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"recognitionConfidence","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWordBox/initWithText:boundingRect:recognitionConfidence:":{"title":"initWithText:boundingRect:recognitionConfidence:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWordBox\/initWithText:boundingRect:recognitionConfidence:","role":"symbol","kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithText:boundingRect:recognitionConfidence:"}],"url":"\/documentation\/scanbotsdk\/sbsdkwordbox\/initwithtext:boundingrect:recognitionconfidence:","navigatorTitle":[{"kind":"identifier","text":"initWithText:boundingRect:recognitionConfidence:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWordBox":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKWordBox","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkwordbox","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKWordBox","kind":"identifier"}],"abstract":[{"type":"text","text":"Structure containing recognized word text and bounds."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWordBox","title":"SBSDKWordBox"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWordBox\/title","op":"replace","value":"SBSDKWordBox"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWordBox\/fragments","op":"replace","value":[{"text":"SBSDKWordBox","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWordBox\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKWordBox"}]}]}]}