{"abstract":[{"text":"The accessibility hint for the ‘cancel’ button, located in the top bar of the cropping screen.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingTopBarCancelButton"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCroppingTopBarCancelButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is “Tap to close screen without applying changes”","type":"text"}]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"accessibilityDescriptionCroppingTopBarCancelButton","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCroppingTopBarCancelButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingTextLocalization(py)accessibilityDescriptionCroppingTopBarCancelButton","title":"accessibilityDescriptionCroppingTopBarCancelButton","role":"symbol","symbolKind":"property","roleHeading":"Instance Property"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingtextlocalization\/accessibilitydescriptioncroppingtopbarcancelbutton"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingtextlocalization\/accessibilitydescriptioncroppingtopbarcancelbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingTextLocalization"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingTextLocalization/accessibilityDescriptionCroppingTopBarCancelButton":{"title":"accessibilityDescriptionCroppingTopBarCancelButton","abstract":[{"text":"The accessibility hint for the ‘cancel’ button, located in the top bar of the cropping screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingTopBarCancelButton","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingtextlocalization\/accessibilitydescriptioncroppingtopbarcancelbutton","navigatorTitle":[{"kind":"identifier","text":"accessibilityDescriptionCroppingTopBarCancelButton"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingTopBarCancelButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingTextLocalization":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}],"abstract":[{"text":"Configuration of all the strings for the standalone cropping screen.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingtextlocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingTextLocalization","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}],"role":"symbol","title":"SBSDKUI2CroppingTextLocalization"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"accessibilityDescriptionCroppingTopBarCancelButton"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"accessibilityDescriptionCroppingTopBarCancelButton"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"accessibilityDescriptionCroppingTopBarCancelButton","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingTextLocalization~1accessibilityDescriptionCroppingTopBarCancelButton\/title","value":"accessibilityDescriptionCroppingTopBarCancelButton"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingTextLocalization~1accessibilityDescriptionCroppingTopBarCancelButton\/fragments","value":[{"kind":"identifier","text":"accessibilityDescriptionCroppingTopBarCancelButton"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingTextLocalization\/title","value":"SBSDKUI2CroppingTextLocalization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingTextLocalization\/fragments","value":[{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingTextLocalization\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CroppingTextLocalization"}]}]}]}