{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcommonfieldtype\/pseudonym"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcommonfieldtype\/pseudonym"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"pseudonym","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pseudonym","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCommonFieldType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCommonFieldType","kind":"typeIdentifier"}],"roleHeading":"Type Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCommonFieldType(cpy)pseudonym","title":"pseudonym"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType\/pseudonym","interfaceLanguage":"swift"},"abstract":[{"text":"Pseudonym field.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pseudonym","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCommonFieldType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType","text":"SBSDKCommonFieldType","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCommonFieldType":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCommonFieldType","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Common field types."}],"url":"\/documentation\/scanbotsdk\/sbsdkcommonfieldtype","title":"SBSDKCommonFieldType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType","role":"symbol","navigatorTitle":[{"text":"SBSDKCommonFieldType","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCommonFieldType/pseudonym":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType\/pseudonym","url":"\/documentation\/scanbotsdk\/sbsdkcommonfieldtype\/pseudonym","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pseudonym"}],"abstract":[{"type":"text","text":"Pseudonym field."}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pseudonym"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCommonFieldType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCommonFieldType"}],"title":"pseudonym","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"pseudonym","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"pseudonym","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCommonFieldType","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCommonFieldType","text":"SBSDKCommonFieldType"},{"text":" * ","kind":"text"},{"text":"pseudonym","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKCommonFieldType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCommonFieldType\/title"},{"value":[{"kind":"identifier","text":"SBSDKCommonFieldType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCommonFieldType\/fragments"},{"value":[{"text":"SBSDKCommonFieldType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCommonFieldType\/navigatorTitle"},{"value":"pseudonym","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCommonFieldType~1pseudonym\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCommonFieldType~1pseudonym\/fragments","value":[{"kind":"identifier","text":"pseudonym"}]}]}]}