{"abstract":[{"type":"text","text":"Initializer that takes a key generator."}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeyprovider\/init(keygenerator:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeyprovider\/init(keygenerator:)"]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider\/init(keyGenerator:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"keyGenerator","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKStorageCryptingKeyGenerator","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyGenerator","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingKeyGenerator"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"keyGenerator","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The key generator that generates an encryption key for a context if no key is available yet."}]}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithKeyGenerator:"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyGenerator"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyGenerator","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingKeyGenerator"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"required":true,"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingKeyProvider(im)initWithKeyGenerator:","title":"init(keyGenerator:)","symbolKind":"init"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyGenerator":{"role":"symbol","title":"SBSDKStorageCryptingKeyGenerator","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyGenerator","abstract":[{"type":"text","text":"Protocol for generating encryption keys."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeygenerator","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyProvider":{"navigatorTitle":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"title":"SBSDKStorageCryptingKeyProvider","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeyprovider","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider","abstract":[{"text":"Protocol for loading, storing and providing encryption keys.","type":"text"},{"text":" ","type":"text"},{"text":"The context parameter is used to distinguish between different encryption contexts.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyProvider/init(keyGenerator:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithKeyGenerator:"}],"required":true,"title":"init(keyGenerator:)","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"keyGenerator","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyGenerator","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingKeyGenerator","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeyprovider\/init(keygenerator:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider\/init(keyGenerator:)","abstract":[{"type":"text","text":"Initializer that takes a key generator."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithKeyGenerator:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithKeyGenerator:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithKeyGenerator:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<SBSDKStorageCryptingKeyGenerator>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingKeyGenerator"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"keyGenerator"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"keyGenerator","content":[{"inlineContent":[{"text":"The key generator that generates an encryption key for a context if no key is available yet.","type":"text"}],"type":"paragraph"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyGenerator\/title","op":"replace","value":"SBSDKStorageCryptingKeyGenerator"},{"value":[{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyGenerator\/fragments"},{"value":[{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyGenerator\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider\/title","value":"SBSDKStorageCryptingKeyProvider","op":"replace"},{"value":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider\/navigatorTitle","op":"replace"},{"value":"initWithKeyGenerator:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider~1init(keyGenerator:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithKeyGenerator:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider~1init(keyGenerator:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}