{"kind":"symbol","metadata":{"symbolKind":"case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","roleHeading":"Case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUpcEanExtensionBehavior@SBSDKUpcEanExtensionBehaviorRequire5","navigatorTitle":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehaviorRequire5"}],"title":"SBSDKUpcEanExtensionBehavior.require5","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"require5"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"require5"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Only barcodes with a 5-digit extension are accepted."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior\/require5"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior\/require5"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/require5","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUpcEanExtensionBehavior/require5":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/require5","role":"symbol","abstract":[{"type":"text","text":"Only barcodes with a 5-digit extension are accepted."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior\/require5","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehaviorRequire5"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"require5"}],"kind":"symbol","title":"SBSDKUpcEanExtensionBehavior.require5"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUpcEanExtensionBehavior":{"title":"SBSDKUpcEanExtensionBehavior","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior","kind":"symbol","navigatorTitle":[{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Behavior when scanning UPC\/EAN barcodes with EAN-2 or EAN-5 extensions."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKUpcEanExtensionBehaviorRequire5","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKUpcEanExtensionBehaviorRequire5","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehaviorRequire5"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUpcEanExtensionBehaviorRequire5","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior~1require5\/title"},{"op":"replace","value":[{"text":"SBSDKUpcEanExtensionBehaviorRequire5","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior~1require5\/fragments"},{"op":"replace","value":"SBSDKUpcEanExtensionBehavior","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior\/title"},{"op":"replace","value":[{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior\/fragments"},{"op":"replace","value":[{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}