{"sections":[],"metadata":{"roleHeading":"Instance Method","title":"toJson()","navigatorTitle":[{"text":"toJson","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration(im)toJson","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration\/toJson()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2barbuttonconfiguration\/tojson()"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2barbuttonconfiguration\/tojson()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2BarButtonConfiguration/toJson()":{"navigatorTitle":[{"text":"toJson","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration\/toJson()","title":"toJson()","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2barbuttonconfiguration\/tojson()","kind":"symbol","role":"symbol","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2BarButtonConfiguration":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2barbuttonconfiguration","title":"SBSDKUI2BarButtonConfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}],"abstract":[{"text":"Button configuration.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"toJson"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"toJson","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"toJson"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BarButtonConfiguration~1toJson()\/title","value":"toJson"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BarButtonConfiguration~1toJson()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toJson","kind":"identifier"}]},{"value":"SBSDKUI2BarButtonConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BarButtonConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BarButtonConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}