{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gray","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","metadata":{"title":"SBSDKColorConversion.gray","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gray","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKColorConversionGray","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKColorConversion@SBSDKColorConversionGray","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorConversion"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcolorconversion\/gray"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcolorconversion\/gray"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorConversion\/gray","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Load image as grayscale."}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorConversion/gray":{"navigatorTitle":[{"text":"SBSDKColorConversionGray","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcolorconversion\/gray","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorConversion\/gray","type":"topic","abstract":[{"type":"text","text":"Load image as grayscale."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gray","kind":"identifier"}],"role":"symbol","title":"SBSDKColorConversion.gray"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorConversion":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKColorConversion"}],"abstract":[{"text":"Color conversion to apply during image loading.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKColorConversion"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorConversion","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcolorconversion","type":"topic","title":"SBSDKColorConversion"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKColorConversionGray","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKColorConversionGray","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKColorConversionGray","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKColorConversionGray","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorConversion~1gray\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorConversion~1gray\/fragments","value":[{"text":"SBSDKColorConversionGray","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorConversion\/title","value":"SBSDKColorConversion","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorConversion\/fragments","value":[{"kind":"identifier","text":"SBSDKColorConversion"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorConversion\/navigatorTitle","value":[{"text":"SBSDKColorConversion","kind":"identifier"}],"op":"replace"}]}]}