{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Case","symbolKind":"case","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKAutoSnappingMode@SBSDKAutoSnappingModeDisabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"disabled","kind":"identifier"}],"role":"symbol","title":"SBSDKAutoSnappingMode.disabled","navigatorTitle":[{"kind":"identifier","text":"SBSDKAutoSnappingModeDisabled"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode"]]},"abstract":[{"text":"Auto-snapping and user guidance are disabled.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode\/disabled","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkautosnappingmode\/disabled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkautosnappingmode\/disabled"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disabled"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAutoSnappingMode":{"kind":"symbol","title":"SBSDKAutoSnappingMode","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkautosnappingmode","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAutoSnappingMode","kind":"identifier"}],"abstract":[{"type":"text","text":"The Auto-snapping mode handles different auto-snap scenarios."}],"navigatorTitle":[{"text":"SBSDKAutoSnappingMode","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 5.0.2","type":"text"}],"role":"collection","type":"topic","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAutoSnappingMode/disabled":{"abstract":[{"type":"text","text":"Auto-snapping and user guidance are disabled."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode\/disabled","title":"SBSDKAutoSnappingMode.disabled","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKAutoSnappingModeDisabled"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkautosnappingmode\/disabled","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"SBSDKAutoSnappingModeDisabled","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAutoSnappingModeDisabled"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKAutoSnappingModeDisabled","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAutoSnappingMode\/title","op":"replace","value":"SBSDKAutoSnappingMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAutoSnappingMode\/fragments","value":[{"kind":"identifier","text":"SBSDKAutoSnappingMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAutoSnappingMode~1disabled\/title","value":"SBSDKAutoSnappingModeDisabled","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAutoSnappingMode~1disabled\/fragments","value":[{"kind":"identifier","text":"SBSDKAutoSnappingModeDisabled"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}