{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecrypting\/keyprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecrypting\/keyprovider"]}],"sections":[],"abstract":[{"text":"The key provider that provides\/generates the encryption keys.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keyProvider"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingKeyProvider","kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyProvider","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCrypting\/keyProvider"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCrypting"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"keyProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingKeyProvider","text":"SBSDKStorageCryptingKeyProvider","kind":"typeIdentifier"}],"required":true,"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting(py)keyProvider","title":"keyProvider","navigatorTitle":[{"kind":"identifier","text":"keyProvider"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyProvider":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeyprovider","abstract":[{"type":"text","text":"Protocol for loading, storing and providing encryption keys."},{"type":"text","text":" "},{"type":"text","text":"The context parameter is used to distinguish between different encryption contexts."}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"navigatorTitle":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"title":"SBSDKStorageCryptingKeyProvider","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCrypting":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKStorageCrypting","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"title":"SBSDKStorageCrypting","kind":"symbol","abstract":[{"type":"text","text":"Protocol for implementing encryption and decryption of (streamed) data."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCrypting","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecrypting"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCrypting/keyProvider":{"kind":"symbol","navigatorTitle":[{"text":"keyProvider","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecrypting\/keyprovider","type":"topic","role":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyProvider","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKStorageCryptingKeyProvider","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingKeyProvider","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The key provider that provides\/generates the encryption keys."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCrypting\/keyProvider","title":"keyProvider"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"keyProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"keyProvider","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingKeyProvider","text":"id<SBSDKStorageCryptingKeyProvider>","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyProvider"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider\/title","op":"replace","value":"SBSDKStorageCryptingKeyProvider"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}]},{"value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/title","value":"SBSDKStorageCrypting"},{"value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/navigatorTitle"},{"value":"keyProvider","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting~1keyProvider\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting~1keyProvider\/fragments","value":[{"text":"keyProvider","kind":"identifier"}],"op":"replace"}]}]}