{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Method","title":"viewDidDisappear:","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUICameraViewController(im)viewDidDisappear:","symbolKind":"method","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"viewDidDisappear:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"viewDidDisappear:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuicameraviewcontroller\/viewdiddisappear:"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController\/viewDidDisappear:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController"]]},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUICameraViewController":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuicameraviewcontroller","title":"SBSDKUICameraViewController","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController","abstract":[{"text":"A ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewController","isActive":true,"type":"reference"},{"text":" subclass which adds support for enabled and disabled camera permission.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICameraViewController"}],"navigatorTitle":[{"text":"SBSDKUICameraViewController","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUICameraViewController/viewDidDisappear:":{"abstract":[],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuicameraviewcontroller\/viewdiddisappear:","title":"viewDidDisappear:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidDisappear:"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController\/viewDidDisappear:","type":"topic","navigatorTitle":[{"text":"viewDidDisappear:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIViewController":{"title":"SBSDKUIViewController","abstract":[{"type":"text","text":"An abstract base class for RTU-UI view controllers."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewController","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuiviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIViewController"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUICameraViewController\/title","value":"SBSDKUICameraViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUICameraViewController\/fragments","value":[{"text":"SBSDKUICameraViewController","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUICameraViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUICameraViewController\/navigatorTitle"},{"op":"replace","value":"SBSDKUIViewController","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/fragments","value":[{"text":"SBSDKUIViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/navigatorTitle","value":[{"text":"SBSDKUIViewController","kind":"identifier"}]}]}]}