{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardAnniversary"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardanniversary\/requireddocumenttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardanniversary\/requireddocumenttype"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"The name of the wrapped document type.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardAnniversary\/requiredDocumentType"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCardAnniversary(py)requiredDocumentType","navigatorTitle":[{"text":"requiredDocumentType","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"requiredDocumentType","roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCardAnniversary":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardAnniversary","title":"SBSDKBarcodeDocumentModelVCardAnniversary","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardAnniversary"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardAnniversary"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardanniversary","role":"symbol","abstract":[{"text":"Anniversary","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCardAnniversary/requiredDocumentType":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardanniversary\/requireddocumenttype","kind":"symbol","abstract":[{"type":"text","text":"The name of the wrapped document type."}],"type":"topic","title":"requiredDocumentType","navigatorTitle":[{"text":"requiredDocumentType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardAnniversary\/requiredDocumentType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"requiredDocumentType","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"requiredDocumentType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"requiredDocumentType","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKBarcodeDocumentModelVCardAnniversary","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardAnniversary\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardAnniversary"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardAnniversary\/fragments"},{"value":[{"text":"SBSDKBarcodeDocumentModelVCardAnniversary","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardAnniversary\/navigatorTitle"},{"value":"requiredDocumentType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardAnniversary~1requiredDocumentType\/title"},{"value":[{"kind":"identifier","text":"requiredDocumentType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardAnniversary~1requiredDocumentType\/fragments"}]}]}