{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration\/defaultConfiguration","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"title":"defaultConfiguration","navigatorTitle":[{"text":"defaultConfiguration","kind":"identifier"}],"roleHeading":"Type Property","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration(cpy)defaultConfiguration","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration","text":"SBSDKBaseScannerEnergyConfiguration","kind":"typeIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"This is the default configuration with the properties initialized as mentioned in their description."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration\/defaultconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration\/defaultconfiguration"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerEnergyConfiguration/defaultConfiguration":{"kind":"symbol","title":"defaultConfiguration","type":"topic","navigatorTitle":[{"text":"defaultConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration\/defaultconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration\/defaultConfiguration","role":"symbol","abstract":[{"text":"This is the default configuration with the properties initialized as mentioned in their description.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration","text":"SBSDKBaseScannerEnergyConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerEnergyConfiguration":{"title":"SBSDKBaseScannerEnergyConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}],"kind":"symbol","abstract":[{"text":"The energy management configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"},{"text":" ","type":"text"},{"text":"‘SBSDKBaseScannerViewController’ and subclasses sport a customizable energy management system.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Since detectors and recognizers running on a live video feed can put a lot of load onto the CPU and\/or GPU"},{"type":"text","text":" "},{"text":"of the device, causing the battery to drain quickly and running the device hot, you can customize the energy","type":"text"},{"text":" ","type":"text"},{"text":"consumption using this class by configuring the rate of detections\/recognitions per second in performance mode as","type":"text"},{"text":" ","type":"text"},{"text":"well as in energy saving mode.","type":"text"},{"text":" ","type":"text"},{"text":"In performance mode the detectors\/recognizers will be fed with a higher, configurable rate of","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"video frames per second."},{"type":"text","text":" "},{"type":"text","text":"After a certain, configurable period of inactivity the energy save mode will be engaged and the rate"},{"text":" ","type":"text"},{"text":"of detections\/recognitions will be reduced to a lower (configurable) rate.","type":"text"},{"type":"text","text":" "},{"text":"You can also configure the time of inactivity before the automatic mode switches from performance to energy save mode.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Inactivity here means that both of the following conditions are met:"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"value":"defaultConfiguration","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"defaultConfiguration","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration","text":"SBSDKBaseScannerEnergyConfiguration"},{"text":" * ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration~1defaultConfiguration\/title","op":"replace","value":"defaultConfiguration"},{"value":[{"text":"defaultConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration~1defaultConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration\/title","value":"SBSDKBaseScannerEnergyConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}