{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKKeyedImageStorage"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKKeyedImageStorage\/removeImages(matchingPrefix:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"removeImagesForKeysMatchingPrefix:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeImages","kind":"identifier"},{"kind":"text","text":"("},{"text":"matchingPrefix","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"title":"removeImages(matchingPrefix:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKKeyedImageStorage(im)removeImagesForKeysMatchingPrefix:","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"text":"Removes the images at keys from the receiver as well as from the file system, which keys prefix match the prefix string.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(removeImagesForKeysMatchingPrefix:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeImages"},{"text":"(","kind":"text"},{"text":"matchingPrefix","kind":"externalParam"},{"kind":"text","text":" "},{"text":"prefix","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The prefix of the keys for the images that should be removed.","type":"text"}],"type":"paragraph"}],"name":"prefix"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkkeyedimagestorage\/removeimages(matchingprefix:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkkeyedimagestorage\/removeimages(matchingprefix:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKKeyedImageStorage/removeImages(matchingPrefix:)":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Removes the images at keys from the receiver as well as from the file system, which keys prefix match the prefix string.","type":"text"}],"navigatorTitle":[{"text":"removeImagesForKeysMatchingPrefix:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeImages","kind":"identifier"},{"kind":"text","text":"("},{"text":"matchingPrefix","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"title":"removeImages(matchingPrefix:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKKeyedImageStorage\/removeImages(matchingPrefix:)","url":"\/documentation\/scanbotsdk\/sbsdkkeyedimagestorage\/removeimages(matchingprefix:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKKeyedImageStorage":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKKeyedImageStorage","abstract":[{"text":"A simple thread-safe multiple-reader-single-writer key-value fashioned disk image cache class.","type":"text"},{"type":"text","text":" "},{"text":"Manages images in a dictionary-like fashion.","type":"text"}],"title":"SBSDKKeyedImageStorage","navigatorTitle":[{"kind":"identifier","text":"SBSDKKeyedImageStorage"}],"url":"\/documentation\/scanbotsdk\/sbsdkkeyedimagestorage","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKKeyedImageStorage"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"removeImagesForKeysMatchingPrefix:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeImagesForKeysMatchingPrefix:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"removeImagesForKeysMatchingPrefix:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"prefix","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The prefix of the keys for the images that should be removed."}],"type":"paragraph"}],"name":"prefix"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"removeImagesForKeysMatchingPrefix:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage~1removeImages(matchingPrefix:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage~1removeImages(matchingPrefix:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"removeImagesForKeysMatchingPrefix:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage\/title","value":"SBSDKKeyedImageStorage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage\/fragments","value":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKKeyedImageStorage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}