{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgedButton\/badgeForegroundColor","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2badgedbutton\/badgeforegroundcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2badgedbutton\/badgeforegroundcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgedButton"]]},"metadata":{"title":"badgeForegroundColor","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgedButton(py)badgeForegroundColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badgeForegroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"badgeForegroundColor"}],"modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The color of the badge’s foreground (icon, text).","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badgeForegroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is “#C8193C”","type":"text"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BadgedButton":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BadgedButton"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BadgedButton"}],"kind":"symbol","abstract":[{"text":"Configuration of the button with a badge.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2badgedbutton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgedButton","title":"SBSDKUI2BadgedButton","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"abstract":[],"title":"SBSDKUI2Color","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","url":"\/documentation\/scanbotsdk\/sbsdkui2color","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Color"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BadgedButton/badgeForegroundColor":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badgeForegroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgedButton\/badgeForegroundColor","abstract":[{"text":"The color of the badge’s foreground (icon, text).","type":"text"}],"type":"topic","navigatorTitle":[{"text":"badgeForegroundColor","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2badgedbutton\/badgeforegroundcolor","title":"badgeForegroundColor","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"badgeForegroundColor"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"badgeForegroundColor","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":" * ","kind":"text"},{"text":"badgeForegroundColor","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgedButton\/title","op":"replace","value":"SBSDKUI2BadgedButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgedButton\/fragments","op":"replace","value":[{"text":"SBSDKUI2BadgedButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgedButton\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BadgedButton"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","op":"replace","value":"SBSDKUI2Color"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Color"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgedButton~1badgeForegroundColor\/title","op":"replace","value":"badgeForegroundColor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgedButton~1badgeForegroundColor\/fragments","op":"replace","value":[{"text":"badgeForegroundColor","kind":"identifier"}]}]}]}