{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickArOverlayPolygonConfiguration"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickaroverlaypolygonconfiguration\/hash"]}],"metadata":{"fragments":[{"text":"hash","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"hash","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FindAndPickArOverlayPolygonConfiguration(py)hash","role":"symbol","title":"hash","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickArOverlayPolygonConfiguration\/hash","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickArOverlayPolygonConfiguration":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickArOverlayPolygonConfiguration","abstract":[{"type":"text","text":"Configuration of the overlay polygon displayed on top of a barcode in the camera preview."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickaroverlaypolygonconfiguration","kind":"symbol","title":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickArOverlayPolygonConfiguration/hash":{"title":"hash","role":"symbol","abstract":[],"fragments":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickaroverlaypolygonconfiguration\/hash","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickArOverlayPolygonConfiguration\/hash"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickArOverlayPolygonConfiguration\/title","value":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickArOverlayPolygonConfiguration\/fragments","value":[{"text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickArOverlayPolygonConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2FindAndPickArOverlayPolygonConfiguration","kind":"identifier"}],"op":"replace"}]}]}