{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/accessibilityConfiguration","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"A configuration with accessibility texts settings."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/accessibilityconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/accessibilityconfiguration"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerAccessibilityConfiguration","text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration"}],"languages":["swift"]}]}],"sections":[],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"typeIdentifier","text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerTextConfiguration(py)accessibilityConfiguration","navigatorTitle":[{"text":"accessibilityConfiguration","kind":"identifier"}],"role":"symbol","title":"accessibilityConfiguration","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerTextConfiguration"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration","abstract":[{"type":"text","text":"Configuration for the textual contents of the document scanning screen."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIFinderDocumentScannerTextConfiguration","kind":"identifier"}],"title":"SBSDKUIFinderDocumentScannerTextConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 5.0.0"}],"title":"ScanbotDocumentScannerSDK","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerAccessibilityConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","title":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","abstract":[{"type":"text","text":"Configuration for the accessibility labels and hints."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration/accessibilityConfiguration":{"abstract":[{"text":"A configuration with accessibility texts settings.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/accessibilityconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityConfiguration"},{"text":": ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerAccessibilityConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityConfiguration"}],"type":"topic","role":"symbol","title":"accessibilityConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/accessibilityConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"accessibilityConfiguration","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"accessibilityConfiguration"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerAccessibilityConfiguration","text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"accessibilityConfiguration"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"SBSDKUIFinderDocumentScannerTextConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerTextConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/title","value":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/fragments","value":[{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1accessibilityConfiguration\/title","value":"accessibilityConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1accessibilityConfiguration\/fragments","value":[{"text":"accessibilityConfiguration","kind":"identifier"}],"op":"replace"}]}]}